solana-labs/solana

- core/src/cluster_info_vote_listener.rs
- core/src/rpc.rs
- core/src/rpc_pubsub.rs
- core/src/rpc_subscriptions.rs
- core/src/tpu.rs
- core/src/validator.rs
- docs/src/apps/jsonrpc-api.md
- sdk/src/commitment_config.rs
Backport single-gossip commitment implementation.
Also includes vote subscriptions.
cc @mvines
> V1.1 single gossip commitment

- sdk/src/genesis_config.rs
> Include GenesisConfig inflation in Display

- core/src/serve_repair.rs
When a validator submits an orphan repair request > UNLOCK_NONCE_SLOT and no nonce (they haven't upgraded to the `OrphanWithNonce` repair requests), then the `run_orphan` loop will run through all slot metas, effectively DOSing repair
Break if `repair_response_packet` returns None
Fixes #
> Fix run_orphan DOS

- core/src/rpc_service.rs
- core/src/validator.rs
During the mainnet-beta restart yesterday I had to manually fiddle with the api.mainnet-beta.solana.com load balancer configuration.  The backing RPC nodes were reporting bad `/health` as they sat in the `--wait-for-supermajority` loop waiting for everybody else.  This had adverse affects like the explorer and cli not working during this time, causing some confusion and annoyance.  
While in the `--wait-for-supermajority` mode it's better that RPC continue to generally work
> Feign RPC health while in a `--wait-for-supermajority` holding pattern

- core/src/serve_repair.rs
Same as https://github.com/solana-labs/solana/pull/10290, but less severe on master/1.2 due to much smaller attack surface: https://github.com/solana-labs/solana/pull/10290#issuecomment-635132594.
Patch potential edge case
Fixes #
> Fix repair dos

- net-utils/src/lib.rs
verify_reachable_ports has a UDP socket race that could cause `solana-validator` to crash on startup. 
As seen at https://buildkite.com/solana-labs/solana/builds/24968#4aca3cc2-d2ef-4367-8466-6bf7b9a6d0ff
> verify_reachable_ports: Handle errors without expect()

- ledger/src/blockstore.rs
Cherry-pick from https://github.com/solana-labs/solana/pull/10280
Fixes #
> Log leader in blockstore check

- programs/stake/src/stake_instruction.rs
- programs/vote/src/vote_instruction.rs
- sdk/src/loader_instruction.rs
- sdk/src/system_instruction.rs
Programs aren't in the docs.
* Working in the direction of generated docs by improving markdown, consistency and reducing duplication.
* Add signers to the list of account references
> Cleanup program docs

- core/src/replay_stage.rs
Missing gating switch vote behavior based on operating mode
Add gating based on operating mode.
TODO: will cherry pick this + https://github.com/solana-labs/solana/pull/10218 together into 1.2
Fixes #
> Add operating mode gating

- docs/src/SUMMARY.md
- docs/src/proposals/ledger-replication-to-implement.md
Archiver code was removed, and with it all documentation. But the design doc is still useful and relevant.
Restore both the implemented and unimplemented docs in one "accepted design proposal"
> Restore archiver/storage design document

- docs/src/integrations/exchange.md
My attempt to manhandle gitbook failed.
Reformat a bit better.
> Exchange doc reformat pt2

- client/src/rpc_client.rs
- client/src/thin_client.rs
- stake-accounts/src/main.rs
> Remove some unused RpcClient and ThinClient methods

- programs/stake/src/stake_instruction.rs
- runtime/src/system_instruction_processor.rs
- runtime/tests/stake.rs
v1.1 backport.
See https://github.com/solana-labs/solana/issues/10377
> No longer allow create-account to add funds to an existing account (#10192)

- core/src/ledger_cleanup_service.rs
- ledger/src/blockstore.rs
https://github.com/solana-labs/solana/pull/10414 for v1.1
> v1.1: ledger_cleanup_service: compact at a slower rate than purging

- docs/src/implemented-proposals/cross-program-invocation.md
CC: @jackcmay 
The title should tell. :)
Found while working on #10348
> docs: Fix missing closing code block ```

- core/src/cluster_info.rs
- core/src/crds_gossip.rs
- core/src/crds_gossip_pull.rs
- core/tests/crds_gossip.rs
By the time the pull request is processed the node may have already received the information through the push queue.
Filter messages that are likely to land via push.
Fixes #
> Gossip PullRequests tend to return a lot of duplicates.

- core/src/cluster_info.rs
No outgoing pull requests count.
Add counter.
Fixes #
> Add pull request count metrics

- core/src/poh_recorder.rs
- ledger/src/entry.rs
Warn messages for counters which are not that important generally.
Lower to info.
Fixes #
> Lower perf counter level from warn

- core/src/poh_service.rs
No Poh metrics enabled by default.
Enable poh metric.
Fixes #
> Enable and add tick rate to metrics

- core/src/cluster_info.rs
Metrics counters added twice and worker threads not named, so hard to tell when they are busy.
Name gossip worker threads and remove duplicate counter metrics.
Fixes #
> Remove duplicate gossip metrics and name worker threads

- stake-o-matic/src/whitelist.rs
> Add F3LudCbGqu4DMqjduLq5WE2g3USYcjmVK3WR8KeNBhWz

- ci/test-checks.sh
In honor of @svenski123 (#10445 ) :)
> Use cutting-edge (=nightly) clippy for all targets

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
No gossip or poh metrics on the dashboard.
Add panes for each to the default dashboard
Fixes #
> Add gossip/poh to dashboard

- stake-o-matic/src/main.rs
* Add --baseline-stake-amount and --bonus-stake-amount arguments, to allow overriding of the 5k/50k defaults
* Don't ever unstake more than 20% of the cluster at a time.   With the current gossip storm on testnet, without this sanity check stake-o-matic would literally unstake the entire cluster
> som improvements 

- docs/src/proposals/simple-payment-and-state-verification.md
> Fix broken image link

- tokens/src/commands.rs
- tokens/src/db.rs
- tokens/src/thin_client.rs
`solana-tokens` has an inaccurate mechanism for detecting expired blockhashes.
Switch to using `last_valid_slot` instead.
> Detect expired blockhashes in solana-tokens

- core/src/cluster_info.rs
- core/src/crds_gossip_push.rs
Inconsistent naming of me/self/obj in cluster_info
Unify to &self and self.xxx()
Fixes #
> ClusterInfo cleanup

- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- stake-monitor/src/lib.rs
The authorized staker can split accounts into smithereens but can't put the pieces back together again without bothering the authorized withdrawer.     
Part of https://github.com/solana-labs/solana/issues/9016
Cli support will be added in a follow-up
> Add StakeInstruction::Merge

- cli/src/cli.rs
- cli/src/stake.rs
Fixes https://github.com/solana-labs/solana/issues/9016
> cli: Add `merge-stake` subcommmand

- sdk/src/entrypoint_native.rs
Missing docs
Document the InvokeContext trait
Fixes #
> Document InvokeContext trait

- core/src/rpc.rs
`RpcClient` can't be used in parallel unit-tests. It requires a UDP socket to send messages to instead of a channel. The workaround is to tuck the RpcClient functionality under a trait and implement it with a BankClient, which may behave differently than RpcClient.
* Enable the generation of Rust clients, which can be instantiated with either a local client or an http client.
> Enable jsonrpc client

- docs/src/wallet-guide/apps.md
- docs/src/wallet-guide/cli.md
No security information about the risks of using Trust Wallet.
Add it.
> Add Trust Wallet security info

- core/src/banking_stage.rs
- core/src/cluster_info.rs
- core/src/crds.rs
- core/src/crds_gossip.rs
- core/src/crds_gossip_error.rs
- core/src/crds_gossip_pull.rs
- core/src/crds_gossip_push.rs
- core/src/replay_stage.rs
- core/tests/gossip.rs
- rayon-threadlimit/src/lib.rs
Gossip push is horribly broken.
1. fix gossip push
2. forward pulls through push
3. send the vote to the tpu and push
4. set the tpu forwarder to look for slot + 1 leader
Fixes #
> Fix fannout gossip bench

- core/src/crds_gossip_push.rs
> Fix trailing whitespace

- core/src/cluster_info.rs
gossip taking too much cpu
Lower number of threads.
Fixes #
> Dial down gossip threadpool

- core/tests/gossip.rs
> Further fix the ci

- ci/test-sanity.sh
Bring back something I've done while back-porting.....
> Clean up test-sanity.sh a bit

- web3.js/examples/bpf-rust-noop/do.sh
- web3.js/flow-typed/jayson.js
- web3.js/module.d.ts
- web3.js/module.flow.js
- web3.js/package-lock.json
- web3.js/package.json
- web3.js/rollup.config.js
- web3.js/src/bpf-loader.js
- web3.js/src/connection.js
- web3.js/src/index.js
- web3.js/src/loader.js
- web3.js/src/message.js
- web3.js/src/publickey.js
- web3.js/src/transaction.js
- web3.js/src/util/send-and-confirm-raw-transaction.js
- web3.js/src/util/send-and-confirm-transaction.js
- web3.js/test/bpf-loader.test.js
- web3.js/test/connection.test.js
- web3.js/test/nonce.test.js
- web3.js/test/publickey.test.js
- web3.js/test/stake-program.test.js
- web3.js/test/system-program.test.js
- web3.js/test/transaction-payer.test.js
- web3.js/test/transaction.test.js
https://github.com/solana-labs/solana-web3.js/tree/4fbad1052ce629e98e26a393cea71b74ceda1210
> Import solana-web3.js

- web3.js/.travis.yml
- web3.js/.travis/before_install.sh
- web3.js/.travis/script.sh
> ci: break up .travis.yml

- RELEASE.md
> Minor RELEASE doc updates

- clap-utils/src/input_validators.rs
Improvements to clap_utils input validators
- add generic is_parsable() input validator
- allow input validators to accept &str, &String and String parameters
> Add generic is_parsable() input validator

- cli/src/cli.rs
- cli/src/vote.rs
- cli/tests/vote.rs
Progress towards https://github.com/solana-labs/solana/issues/10461
> |solana withdraw-from-vote-account| now supports ALL, and refuses to deallocate the vote account

- multinode-demo/bootstrap-validator.sh
- multinode-demo/validator.sh
- net/net.sh
`--wait-for-supermajority` isn't plumbed through scripts
Plumb it
> Plumb --wait-for-supermajority through scripts

- ci/dependabot-updater.sh
Tested at https://github.com/solana-labs/solana/pull/10605/commits
> dependabot-updater: follow commit format change

- core/src/replay_stage.rs
https://github.com/solana-labs/solana/issues/10519
https://github.com/solana-labs/solana/issues/10311
Enable fork choice + switch votes immediately on devnet, at epoch 63 on testnet
Fixes #
> Enable fork choice and switch votes, devnet => now, testnet => epoch 63

- docs/book.toml
> Resotre linkcheck with some excludes

- stake-o-matic/src/main.rs
Stake-o-matic doesn't need to fully halt on poor block production.   It can still destake delinquents and award baseline stake.  It's only the bonus stake that can't be assessed when the cluster is performing poorly
> som: Still destake delinquents on poor block production

- runtime/src/bank_forks.rs
There's some semantic coupling that obfuscates what the working bank is.  It's currently implemented as either the initial bank with the highest slot or the most recent bank to be inserted. That latter bank *probably* has a higher slot, but it's not enforced.
Attempt no change in behavior, but possibly start returning a higher bank in the case where a bank with a lower slot was added after one with a higher slot. I'm not aware if that's ever the case or if any functionality depends on that.  My guess is this change will add a bit of determinism when blocks are arriving out of order.
> Derive the working bank

- tokens/src/arg_parser.rs
- tokens/src/args.rs
- tokens/src/commands.rs
- tokens/src/main.rs
- tokens/src/thin_client.rs
Bunch of type parameters that made solana-tokens code unnecessarily complicated
Dumb it down
> Clean up solana-tokens

- docs/src/clusters.md
> Update testnet shred version

- cli-config/src/config.rs
ref: https://github.com/solana-labs/solana/pull/10695
> v1.1: cli-config: Add stub address_labels field for 1.3 compatibility

- streamer/src/streamer.rs
Responder errors can be too chatty.
Reduce to 1 per second.
Fixes #
> Reduce responder error prints

- gossip/src/main.rs
gossip program is somewhat complex and only 1 function.
Split up logic into multiple smaller functions that are easier to read.
Fixes #
> Refactor gossip code from one huge function

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
Poh/transaction verify times incorrect on dashboard after split and rename.
Add them back.
Fixes #
> Add new split poh/transaction verify times to dashboard

- ci/buildkite-pipeline.sh
> Fix buildkite step typo

- core/src/repair_service.rs
- core/src/serve_repair.rs
- ledger/src/blockstore.rs
Hard to tell which slots repair is repairing
Add logs breaking down repairs by slot
Fixes #
> Add repair breakdown by slot and index

- core/tests/bank_forks.rs
> Tidy up following #10536 

- core/src/validator.rs
- ledger/src/blockstore/blockstore_purge.rs
Shreds with incorrect version can still exist in blockstore on a restart causing problems with the node where it could mark a slot dead based on a bad version of the slot.
If `--wait-for-supermajority` is given, then copy any shreds into a backup blockstore and remove them from the primary blockstore.
Fixes #
> Remove slots after --wait-for-supermajority slot

- core/src/cluster_info_vote_listener.rs
- core/src/repair_service.rs
- core/src/retransmit_stage.rs
- core/src/tvu.rs
- core/src/window_service.rs
Repair budget can be exhausted on a slot which nobody has if say a validator creates a slot with a large number of ticks and then goes offline.
Weight repairs by stake that has voted on it.
Fixes #
> Weight repair slots based on vote stake

- explorer/src/providers/accounts/historyManager.ts
Explorer account history search doesn't search back very far and has a bug that causes gaps in search history
* Bump the signature count threshold for ending the search process from 1 to 128
* Auto-reduce account history query range if too many results are returned (vote accounts) 
* Improve the "refresh recent history" search
* Fix search gaps bug
Fixes #
> Fix explorer account history search

- core/src/repair_service.rs
- local-cluster/tests/local_cluster.rs
Cherry-picked from https://github.com/solana-labs/solana/pull/10606
Fixes #
> Disable entire codepath

- docs/src/staking/README.md
> Fixup stake doc wording

- Cargo.lock
- programs/bpf/Cargo.lock
- programs/librapay/Cargo.lock
- programs/move_loader/Cargo.lock
v1.2 build is busted
Revert some stowaway changes from ccb7b1a
> Revert some stowaway changes from ccb7b1a

- Cargo.lock
- Cargo.toml
- ci/test-stable.sh
- poh-bench/Cargo.toml
- poh-bench/src/main.rs
No standalone PoH benchmark.
Add one with flags which runs all generic/simd/cuda flavors if present to compare.
Fixes #
> Add poh-bench

- core/src/non_circulating_supply.rs
Need an additional non-circulating withdraw authority for the Foundation to assist in locked stake issuance.
Add it.
> Add non-circulating withdraw authority

- core/src/consensus.rs
- core/src/tvu.rs
- core/src/validator.rs
- core/tests/fork-selection.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster.rs
#10718 is getting large.
Off-load some tiny clean-ups into this preparatory pr.
> Tiny cleanups in preparation for persistent tower

- core/src/heaviest_subtree_fork_choice.rs
Cherry-picked from https://github.com/solana-labs/solana/pull/10803
Fixes #
> Fix leaf propagation in case of no votes in HeaviestForkChoice

- ledger-tool/src/main.rs
No way to copy parts of a ledger from one into another which can be useful when doing restarts or analyzing some portion of slots.
Add `ledger-tool copy` command to copy shreds from one ledger into another.
Fixes #
> Add ledger-tool copy command

- core/src/rpc.rs
- core/src/rpc_service.rs
Hard to read code
Clean it up a bit
> Clean up rpc module

- core/src/heaviest_subtree_fork_choice.rs
HeaviestForkChoice lacks logging in case of root stalling
Add some debugging
Fixes #
> Add logging to HeaviestForkChoice

- core/src/replay_stage.rs
Hard to tell where replay gets stuck processing stuff.
Add more timing metrics.
Fixes #
> More replay stage timing metrics

- runtime/src/bank.rs
Some comment from #9527 is outdated.
Remove it because #10348 has already been landed.
> Remove outdated todo comment

- core/src/validator.rs
- ledger-tool/src/main.rs
- validator/src/main.rs
Missing checks for with-ledger restart.
Add checks for bank hash and wait for supermajority.
Fixes #
> More guard rails for restart with ledger procedure (1.2 bp)

- docs/src/clusters.md
Shred version not up-to-date.
Update shred version docs for testnet.
Fixes #
> Update expected shred version for testnet.

- core/src/consensus.rs
- core/src/validator.rs
Another really tiny cleaning-up pr in similar fashion to #10805.
Just do it.
context: #10718
> Rename new_banks_from_blockstore => new_banks_from_ledger

- core/src/heaviest_subtree_fork_choice.rs
- runtime/src/bank_utils.rs
- runtime/src/lib.rs
Missing utility functions needed for weighted repair
Add utility functions
Fixes #
> Add utility functions

- docs/src/SUMMARY.md
- docs/src/running-validator/restart-cluster.md
No docs for restarting the cluster.
Add instructions from issue #10678, modified to not remove ledger.
Fixes #10678
> Add docs for restarting a cluster

- docs/src/running-validator/validator-start.md
Some validators' logs are being suppressed
Add instructions for disabling 
Fixes #
> Instructions for validator logging

- core/src/accounts_background_service.rs
- ledger/src/bank_forks.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
Accounts clean taking a long time.
Move clean, backport #10898 
Fixes #
> Move clean accounts to background service (1.2 bp)

- ledger/src/blockstore.rs
Hard to tell whether recovered erasure blobs are redundant/invalid/ok
Add breakdown of recovered blobs
Fixes #
> Add breakdown of erasure blobs

- core/src/repair_service.rs
Hard to tell which parts in repair are taking a long time
Add repair timing 
Fixes #
> Repair timing metrics

- docs/src/clusters.md
testnet docs out of sync
Update to latest shred version.
Fixes #
> update testnet docs

- runtime/src/bloom.rs
Printing a Bloom object results in a huge page of `[true, false, true, ..]` which is not that helpful.
Add custom debug which prints the relevant fields and then the first portion of the bitvec.
Fixes #
> Add custom Debug for Bloom object

- transaction-status/src/lib.rs
v1.1 version of https://github.com/solana-labs/solana/pull/10991
> v1.1: Add EncodedTransaction::Raw

- Cargo.lock
- sdk/src/program_stubs.rs
Problem
window build is broken, happening on master and v1.2: https://travis-ci.com/github/solana-labs/solana/jobs/359548827#L639
Update spl-memo
I've confirmed windows now builds at the other pr(#10983 with this commit included.). :): https://travis-ci.com/github/solana-labs/solana/jobs/359595539#L600
Context #10983
> spl memo linking windows

- Cargo.lock
- account-decoder/Cargo.toml
- sdk/src/program_stubs.rs
- transaction-status/Cargo.toml
- Bump spl-version
- Feature-gate program_stubs
> Backport windows build fixes

- runtime/src/accounts_db.rs
Key could be revived between checking deletion and removing the key entry.
Check again that the entry is empty before removing the entry.
cc #11008
Fixes #
> Check for deleting accounts key, make sure list is empty again

- programs/vote/src/vote_state/mod.rs
No metrics visibility into dropped votes which can indicate serious problems.
Add a counter for dropped votes due to slot or hash mismatch.
Fixes #
> Add dropped vote metrics

- ci/env.sh
Manual backport for Travis CI environment fix #10974
> Fix Travis PR detection environment (#10974)

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
I broke the dashboard changes somewhere here: https://github.com/solana-labs/solana/commit/7a14e359d7c0199c675658d554b4cb652af804e5#diff-e3264d5e07139e1eb0ac1b40b0334b3c
Revert
Fixes #
> Revert dashboard changes

- docs/.gitignore
- docs/convert-ascii-to-svg.sh
- docs/src/cluster/stake-delegation-and-rewards.md
`mscgen` was producing a transparent background svg, which doesn't work when viewing in Dark Mode
Output .png instead.
> Change transparent .svg to opaque .png

- validator/src/main.rs
Downloading a snapshot can be really slow especially when tds snapshots are 150-500mb.
Turn off gossip while downloading the snapshot. Helped turn snapshot download from >30 minutes into 30 seconds.
Fixes #
> Turn off gossip before downloading snapshot.

- core/src/rpc.rs
- runtime/src/commitment.rs
Reverts solana-labs/solana#11103
Broke master :-/
> Revert "Use BlockCommitmentCache for RPC slots"

- ci/docker-rust-nightly/Dockerfile
- ci/docker-rust/Dockerfile
- ci/rust-version.sh
Depends-on: https://github.com/solana-labs/solana/pull/11122
> Upgrade to Rust 1.45.0

- core/src/cluster_info_vote_listener.rs
- core/src/consensus.rs
- core/src/repair_service.rs
- core/src/replay_stage.rs
- core/src/result.rs
- core/src/rpc_pubsub.rs
- core/src/rpc_subscriptions.rs
- core/src/tpu.rs
- core/src/tvu.rs
- core/src/validator.rs
Cherry-pick https://github.com/solana-labs/solana/pull/11119
Fixes #
> Add replay votes to gossip vote tracking

- core/src/rpc.rs
- runtime/src/commitment.rs
> Use BlockCommitmentCache for RPC slots, take 2

- core/src/consensus.rs
- local-cluster/src/cluster_tests.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster.rs
Rebased and fixed up: https://github.com/solana-labs/solana/pull/10343
@ryoqun fyi, added some tests for the switching threshold and fixed some switching threshold issues (described in https://github.com/solana-labs/solana/pull/10343). May have some implications for tests in https://github.com/solana-labs/solana/pull/10718.
Fixes #
> Fix `check_switch_threshold` and add switch threshold local cluster tests

- core/src/banking_stage.rs
- runtime/src/bank.rs
Manual backport of #11166 
cc: @t-nelson
> v1.1: Use OrderedIterator in collect_balances

- core/src/banking_stage.rs
- runtime/src/bank.rs
Manual backport of #11166
cc: @t-nelson
> v1.2: Use OrderedIterator in collect_balances

- net/net.sh
- sdk/docker-solana/build.sh
cc: https://github.com/solana-labs/solana/pull/11184
> Remove move more

- core/src/replay_stage.rs
> Test cleanup

- genesis-programs/src/lib.rs
- runtime/src/bank.rs
https://github.com/solana-labs/solana/pull/11199 for master
> Push back activation epochs

- docs/.gitignore
- docs/package-lock.json
No package-lock.json for docs build flow
Add it
> Add package-lock.json to docs

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/lib.rs
- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_token.rs
- transaction-status/Cargo.toml
We need an easy way for users to figure the current account balance/state of any SPL Fungible Token account, without having to resort to client-side language-specific decoding libraries.
- Implement account decoding for spl-token; affects `getAccountInfo` and `getProgramAccounts`
Fixes #10475 
Examples:
```
// Account
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getAccountInfo","params":["Aw5Qm9iUmQb77KKYsHQc1trERgSs5LgAYTRvDfjF2eCF",{"encoding":"jsonParsed"}]}' localhost:8899
{"jsonrpc":"2.0","result":{"context":{"slot":704},"value":{"data":{"token":{"account":{"amount":0,"delegate":null,"delegatedAmount":0,"isInitialized":true,"isNative":false,"mint":"6JQcJ78u4ktZGGnZ6n7pvyveHKa7x8RHmDX4rohRhE2P","owner":"HcZxVxNzPJrMREfadFytV7r7S339RqmD2Xpa97 …
```
> Add token account decoding

- local-cluster/src/cluster_tests.rs
Change from returning the voted slot for "Recent" confirmation instead of highest slot means a validator that's not voting will not return a new slot in `get_slot(CommitmentLevel::Recent)`
Check all validators for new slots in test because one of the validators may not be voting.
Fixes #
> Fix test stalling

- docs/src/cli/install-solana-cli-tools.md
> Fix markup for heading

- docs/docusaurus.config.js
- docs/src/theme/SearchBar/index.js
- docs/src/theme/SearchBar/styles.css
* Add Algolia configuration information
We can't search our docs!
Attempts to add search provided by Algolia to the docs deployment.
> Add Docusaurus search

- explorer/src/components/Banner.tsx
> Add mainnet beta upgrade announcement

- explorer/src/components/Banner.tsx
- explorer/src/scss/_solana.scss
> Adjust explorer banner margins

- core/src/cluster_info_vote_listener.rs
- core/src/consensus.rs
- core/src/lib.rs
- core/src/optimistic_confirmation_verifier.rs
- core/src/repair_service.rs
- core/src/replay_stage.rs
- core/src/rpc_pubsub.rs
- core/src/tpu.rs
- core/src/vote_stake_tracker.rs
- core/tests/ledger_cleanup.rs
- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
- programs/vote/src/vote_transaction.rs
Reboot and update https://github.com/solana-labs/solana/pull/10217
Fixes #
> Track votes from gossip for optimistic confirmation

- core/src/rpc.rs
Several RPC endpoints don't `debug!()` their request receipt
Add them
cc/ @CriesofCarrots
> Fill out missing RPC request received debug logging

- core/src/cluster_info_vote_listener.rs
- programs/vote/src/vote_transaction.rs
Parsing vote transactions is a common utility function that is currently in an inconvenient place.
Add utility to parse vote transactions to `vote_transaction.rs`
Fixes #
> Add parse vote transaction utility function

- .gitignore
- fetch-spl.sh
- genesis/src/main.rs
- multinode-demo/setup.sh
- net/net.sh
- run.sh
- sdk/docker-solana/build.sh
> Download and install SPL programs in run.sh/multinode-demo/docker

- docs/src/wallet-guide.md
When I moved wallet-guide.md, missed some link fixes to the new subdir for the other wallet guide pages
Fix it
> Fix wallet links

- logger/src/lib.rs
- metrics/src/metrics.rs
- programs/budget/src/budget_expr.rs
#11290 
Added let-wildcard bindings.
Fixes #11290
> Use the value of std::mem::replace

- fetch-perf-libs.sh
* fix for cuda sigverify check for small order pubkey
Fixes #
> Update perf libs to 0.19.1

- core/src/non_circulating_supply.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- programs/vote/src/vote_instruction.rs
- sdk/src/instruction.rs
- sdk/src/message.rs
- sdk/src/system_instruction.rs
- stake-monitor/src/lib.rs
> Backport custodian fix

- explorer/src/components/AccountDetails.tsx
- explorer/src/components/TransactionDetails.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/transactions/details.tsx
- explorer/src/providers/transactions/index.tsx
- Leftover logic from deleted table views for accounts and transactions
- Details pages refetch content even if it's already cached
- Improve data caching to decrease RPC requests
Fixes #
> Clean up explorer data providers

- explorer/src/components/AccountDetails.tsx
- explorer/src/components/common/LoadingCard.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/tokens.tsx
- Want to see list of an account’s owned tokens and their balances
- Add as a new card in the account details page
Fixes https://github.com/solana-labs/solana/issues/11243
> Display owned tokens on account details page

- explorer/src/components/AccountDetails.tsx
- explorer/src/components/TransactionDetails.tsx
- Race condition in explorer details fetching
- SOL delta rendering bug
> Fix explorer bugs

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- core/Cargo.toml
- core/src/rpc.rs
- transaction-status/Cargo.toml
This is the last step of https://github.com/solana-labs/solana-program-library/pull/190#issuecomment-667553589
> v1.2: Update spl-token and spl-memo

- explorer/src/components/MessageBanner.tsx
When epoch 61 hits, merge this PR and push the new explorer to prod
> explorer: Add mainnet-beta upgrade-in-process banner

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/AccountDetails.tsx
- explorer/src/components/TransactionDetails.tsx
- explorer/src/components/instruction/InstructionCard.tsx
- explorer/src/components/instruction/RawParsedDetails.tsx
- explorer/src/components/instruction/UnknownDetailsCard.tsx
- explorer/src/components/instruction/token/TokenDetailsCard.tsx
- explorer/src/components/instruction/token/types.ts
- explorer/src/providers/accounts/tokens.tsx
- explorer/src/providers/stats/solanaBeach.tsx
- explorer/src/providers/transactions/cached.ts
- explorer/src/providers/transactions/details.tsx
- explorer/src/scss/_solana-dark-overrides.scss
- explorer/src/scss/_solana.scss
- explorer/src/utils/tx.ts
Want to see details for SPL token instructions
- Update to custom superstruct
- Update web3
- Fetch parsed transactions by default
- Add raw parsed ix view that displays raw JSON for unsupported parsed instructions
- Validate parsed token instruction info and auto generate ix views
Fixes #
> Parse token instructions in the explorer

- explorer/src/components/StatsCard.tsx
Block height is not displayed and "Block" refers to slot which may be confusing
- Display both current slot and block height in explorer
Related to https://github.com/solana-labs/solana/issues/11385
> Display both slot and block height in explorer

- sdk/src/abi_digester.rs
The Solana SDK is not compatible with cbindgen due to a bug in cbindgen related to its inability to handle `()` in types defined in the form ` Result<(), Error>`
https://github.com/eqrion/cbindgen/issues/527
Defining the internal type that uses this convention was a nicety, remove it for now until cbindgen fixes this bug.
Fixes #
> Fix cbindgen compatibility

- explorer/src/components/SearchBar.tsx
- explorer/src/components/account/StakeAccountSection.tsx
- explorer/src/components/account/UnknownAccountCard.tsx
- explorer/src/components/common/Address.tsx
- explorer/src/scss/_solana-dark-overrides.scss
- explorer/src/scss/_solana.scss
- explorer/src/utils/tx.ts
No easy way to lookup history of stake, system, vote, etc instructions or sysvar data
- Search for program names to see recent program instructions
- Search for sysvars to see their current data
- Tweak search bar styling
Fixes #
> Add programs and sysvars to explorer search suggestions

- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/transactions/details.tsx
- explorer/src/providers/transactions/index.tsx
When switching clusters, a slow request for the previous cluster could populate data for the new cluster screen
- Check if cluster changed before accepting new data
Fixes #
> Fix data fetching races in explorer

- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/instruction/token/TokenDetailsCard.tsx
- explorer/src/components/instruction/token/types.ts
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/tokens.tsx
Want to see list of token transfers for tokens owned by a particular account
- Show list of transactions for the owned tokens of a particular account
Related to https://github.com/solana-labs/solana/issues/11244 but still needs more context (TO, FROM, AMOUNT)
> Show token transaction history in explorer

- explorer/package-lock.json
Old web3 falls back to base58 account data decoding
- Update web3
Fixes #
> Update explorer web3 to v0.66.2

- core/src/tvu.rs
- core/src/validator.rs
- ledger-tool/src/bigtable.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_db.rs
- validator/src/main.rs
wal recovery errors.
Backport --wal-recovery-mode
Fixes #
> Add db recovery methods (#10838) (v1.2 backport)

- web3.js/module.d.ts
- web3.js/module.flow.js
- web3.js/src/connection.js
- web3.js/test/connection.test.js
Want to fetch the top 20 largest accounts for a given mint address
- Add `getTokenLargestAccounts` method
Fixes #
> feat: add getTokenLargestAccounts method

- Cargo.lock
- core/src/cluster_info.rs
- core/src/crds_gossip.rs
- core/src/crds_gossip_pull.rs
- core/tests/crds_gossip.rs
Gossip is chatty and backs up.
1. ignore old gossip requests
2. respond with data that is older than the request
Fixes #
tag: @carllin @sakridge
> filter out old gossip pull requests

- core/src/crds_gossip_pull.rs
master CI got broken after https://github.com/solana-labs/solana/pull/11448
Just insignificant formatting fix.
> Fix rust fmt

- core/src/cluster_info.rs
- core/src/crds_gossip_pull.rs
No visibility into the number of items being stored in gossip.
Track table and purged values size
Fixes #
> Log table and purged values size

- docs/src/apps/jsonrpc-api.md
Missing documentation for `getTokenLargestAccounts` method
Add it
> Add getTokenLargestAccounts to docs

- explorer/src/components/account/OwnedTokensCard.tsx
- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/account/TransactionHistoryCard.tsx
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/tokens.tsx
- explorer/src/providers/cache.tsx
- explorer/src/providers/transactions/details.tsx
- explorer/src/providers/transactions/index.tsx
Context providers share a lot of common code and creating a new one is too much of a pain
- Consolidate all caching logic into a single generic provider
Fixes #
> Use common provider for explorer cached data

- core/src/repair_weight.rs
Setting roots on orphans subtrees in repair_service causes an assertion failure
`set_root` should find the orphan subtree if it exists and modify that instead of creating another new subtree
Fixes #
> Fix repair_service assertion failure

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
Retransmit stats not on default dashboard.
Add a retransmit panel.
Fixes #
> Add retransmit stats to dashboard

- core/src/cluster_info.rs
Want to debug gossip traffic, but no metrics for received pull responses.
Add counter for pull responses.
Fixes #
> Add incoming pull response counter

- banks-server/src/banks_server.rs
- core/src/rpc.rs
- core/src/rpc_subscriptions.rs
- runtime/src/commitment.rs
> Add CommitmentSlots::new_from_slot()

- explorer/package-lock.json
Superstruct is not coercing nullable types correctly
Update superstruct
Fixes #
> Explorer: Update superstruct

- docs/src/running-validator/validator-reqs.md
Hardware evolves, newer processors are released which are better value than previous gen.
Change to recommend newer processors.
Fixes #
> Update docs to latest processors

- docs/sidebars.js
CLI usage page got lost somewhere
Restore it
> Restore CLI usage page to docs

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/components/instruction/stake/AuthorizeDetailsCard.tsx
- explorer/src/components/instruction/token/TokenDetailsCard.tsx
- explorer/src/index.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/tokens.tsx
- explorer/src/providers/cluster.tsx
- explorer/src/providers/mints/largest.tsx
- explorer/src/providers/mints/supply.tsx
- explorer/src/providers/richList.tsx
- explorer/src/providers/supply.tsx
- explorer/src/providers/transactions/details.tsx
- explorer/src/providers/transactions/index.tsx
Want to know when accounts fail to validate and RPC API calls fail
- Setup sentry to track React crashes and manually report caught errors
Fixes #
> Explorer: add error reporting

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
Dashboard validator-streamer section is too big and not organized well.
Split out sections for gossip, repair, leader.
Fixes #
> Reorganize metrics dashboard

- docs/src/clusters.md
Devnet cluster info docs have diverged from reality
Synchronize them
> Update devnet docs

- .buildkite/env/secrets.ejson
Bogus credentials leak reports on hackerone
Comment that these credentials are encrypted
cc/ @jackcmay @mvines
> Add comment about encrypted API tokens for buildkite

- docs/docusaurus.config.js
Bogus secret disclosure reports regarding Aloglia API key on HackerOne
Add a comment
> Comment that docs Algolia key is safe to publish

- docs/src/apps/jsonrpc-api.md
Dangling old/incorrect info in signatureSubscribe docs
Remove
> Remove old signatureSubscribe info

- ledger-tool/src/main.rs
It's annoying to not be able to run `solana-ledger-tool -l ledger purge <start_slot>`, which will purge from `start_slot` to the end of the ledger.
> v1.2: ledger-tool: The end_slot argument to purge is now optional

- core/src/commitment_service.rs
- core/src/repair_weight.rs
- core/src/repair_weighted_traversal.rs
- core/src/rpc.rs
- core/src/validator.rs
- core/tests/gossip.rs
- ledger/src/blockstore.rs
- local-cluster/src/local_cluster.rs
- runtime/src/genesis_utils.rs
> Cleanup test utilities 

- programs/bpf/benches/bpf_loader.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
Aligned heap reduces the number of bytes that can be allocated from the heap depending on how the heap is used.  There could exist programs that would be affected by this. 
Feature gate the aligned to the new bpf loader
Fixes #
> Gate aligned program heap

- docs/sidebars.js
- docs/src/wallet-guide.md
- docs/src/wallet-guide/ledger-live.md
- docs/src/wallet-guide/solflare.md
- docs/src/wallet-guide/web-wallets.md
There is no reference or guide to SolFlare in the docs
Add it.
> Add SolFlare guide to docs

- stake-o-matic/README.md
README had old base/bonus (5,000/50,000) stake-o-matic amounts
updated to 50,000 / 500,000
Fixes #
> updated stake-o-matic base and bonus amounts

- core/src/consensus.rs
> Small cleaning around consensus/bank_forks

- genesis-programs/src/lib.rs
BPFLoader2 and compute budget not enabled
Enable them both at epoch 91
Fixes #
> Update epoch gating

- genesis-programs/src/lib.rs
BPFLoader2 and compute budget not enabled
Front port #11880
Fixes #
> Update epoch gating (#11880)

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- core/Cargo.toml
- core/src/rpc.rs
- transaction-status/Cargo.toml
Upstream changes to spl-token pack/unpack, especially len: https://github.com/solana-labs/solana-program-library/pull/359
> Update to token pack/unpack changes

- core/src/rpc.rs
get_parsed_token_accounts is erroneously filtering out Mint and Multisig accounts. This is consistent with the return sets of `getTokenAccounstByOwner` and `getTokenAccounstByDelegate` (which also filter by token account type), but not `getProgramAccounts`. This is low priority; afaict no one is using this method in this way downstream.
Filter out only token accounts that cannot be parsed
> Fix get_parsed_token_accounts

- explorer/src/components/SearchBar.tsx
- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/components/account/UnknownAccountCard.tsx
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/tokenRegistry.ts
- explorer/src/utils/tx.ts
- Cannot view address label on account details page
- No labels for serum tokens
- BPF loader label is missing
- Fix all of the above
Fixes #
> Update explorer address labels

- ledger-tool/src/main.rs
Resolves a TODO over here [1] that I just stubbed my toe on
[1] https://github.com/solana-labs/cluster/blob/7aeb170fe091f648cf283b150dd0adb9efd5fa31/launch-cluster.sh#L171
> ledger-tool: Add bank-hash subcommand

- web3.js/src/publickey.js
- web3.js/test/publickey.test.js
bn clips the generated program address
don't clip
Fixes #11950
> fix: bn clipping in create_program_address

- core/src/heaviest_subtree_fork_choice.rs
Fork choice log is spammy
Remove log
Fixes #
> Remove log

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/connection.js
- web3.js/test/connection.test.js
SPL Token interface changed and broke the setup for token tests
- Update spl-token
- Fix up tests
Fixes #
> chore: fix token tests

- web3.js/module.d.ts
Typescript bindings missing from `create_program_address` and `find_program_address`
Add them
Fixes #
> Update Pubkey typescript bindings

- programs/bpf/build.rs
- programs/bpf/tests/programs.rs
BPF program performance could degrade without detection
Monitor BPF test programs to detect if on-going changes increase the instruction count
Fixes #
> Add BPF test program instruction monitoring

- accounts-bench/Cargo.toml
> Revert Cargo.toml

- Cargo.lock
- accounts-bench/src/main.rs
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- sdk/src/hash.rs
Accounts hashing is slow
TODO: Add gating
Fixes #
> Switch account hashing to blake3

- storage-bigtable/src/bigtable.rs
Users report weird results for some RPC requests to get a recent signature status. Namely, RPC reports the signature was successful in an old block, when it does not actually appear in that block.
Reason:
If bigtable receives a query for a range of rows starting with a key that does not exist, it will still return results if there are following rows in the table, because there are no checks/restrictions on the following keys.
Our `BigTable::get_bincode_cell` method calls `BigTable::get_row_data` with a limit of `1`, and incorrectly assumes that the range request will error if the starting key isn't found. In fact, due to the above, it will return the row in the table with the next index. The result is that the `LedgerStorage::get_signature_status()` method sometimes returns positive …
> Bigtable method to return a single row of data

- core/src/banking_stage.rs
Forwarding calculation was using wrong units
Switch to ticks/slot
Fixes #
> Fix forwarding calculation

- explorer/src/tokenRegistry.ts
- explorer/src/utils/tx.ts
Wrapped SOL doesn't show up in the search bar
Add it to search results
Fixes https://github.com/solana-labs/solana/issues/11936
> explorer: make wrapped sol available through search

- remote-wallet/src/ledger.rs
We query the Ledger wallet app FW version with the wrong payload size, failing a device check recommended by LedgerHQ security review
- Add a `send_apdu()` variant that allows the caller to specify whether they expect an outdated app.
- Use it to query FW version
> Don't query modern Ledger wallet app version with deprecated payload size

- docs/src/proposals/secp256k1_instruction.md
No proposal for secp256k1 instruction operation.
Add proposal.
Fixes #
> secp256k1 instruction proposal

- docs/src/implemented-proposals/installer.md
```
solana-install info
solana-install deploy
solana-install update
solana-install run
```
Fixes #
> fix solana-install syntax

- core/src/crds_gossip_pull.rs
This is a follow up on https://github.com/solana-labs/solana/pull/11998. Per comments there, [`get_crds_filter`](https://github.com/solana-labs/solana/blob/bc7adb97edb8505f011d0718fc567d3b662a0718/core/src/crds_gossip_pull.rs#L66) relies on certain invariances on `filters: &'a mut Vec<CrdsFilter>` generated by [`new_complete_set`](https://github.com/solana-labs/solana/blob/bc7adb97edb8505f011d0718fc567d3b662a0718/core/src/crds_gossip_pull.rs#L82). i.e not every `Vec<CrdsFilter>` is valid to use there. However, as is, this is not checked or enforced by the type system and so can be a source of bugs.
This commit adds a new type `CrdsFilterSet` to enforce type-saftey and make required preconditions more explicit.
> adds new CrdsFilterSet type for Vec<CrdsFilter>

- core/src/rpc.rs
- core/src/rpc_service.rs
- core/src/send_transaction_service.rs
- core/src/validator.rs
>  Forward transactions to the expected leader instead of your own TPU port

- storage-bigtable/src/lib.rs
https://github.com/solana-labs/solana/pull/12058 for v1.2
> v1.2: Bigtable bug fixes

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/SearchBar.tsx
- explorer/src/utils/tx.ts
- Breaking change in web3 BpfLoader api
- Fix BpfLoader api usage
- Add bpf loaders to search results
Fixes #
> Bump web3 and add bpf loaders to search results

- docs/src/cluster/turbine-block-propagation.md
> Correct minor typo in turbine-block-propagation.md

- core/src/cluster_info_vote_listener.rs
When invalid gossip votes are processed, this loop filters out them.
So, `i` cannot correctly be compared against its pre-filter collection count: `gossip_vote_txs.len()`
I didn't confirmed anything. Just read the code. I might be wrong, though....
Wrap each vote transactions with is_gossip flag depending on the origin.
small bug fix while reading the code & cleaning the code.
> Fix bad predicate with malformed gossip votes

- web3.js/package-lock.json
- web3.js/package.json
`rpc-websockets` dependency processed messages out of order
- Update `rpc-websockets` with patch https://github.com/elpheria/rpc-websockets/pull/88
Fixes #
> fix: update rpc-websockets to fix notification race

- web3.js/src/connection.js
Websocket connections can get timed out if there is no client activity depending on server config. This is a problem because it's common to subscribe to account activity (variable time) or wait for a transaction to get finalized (>15s)
- Use a heartbeat interval to ping the server every 5s (assumes server idle timeout > 5s)
Fixes #
> fix: use heartbeat to keep ws connection alive

- core/src/rpc_subscriptions.rs
Cherry pick of https://github.com/solana-labs/solana/pull/12077
> Fix signature subscription panic (#12077)

- accounts-bench/src/main.rs
- clap-utils/src/input_parsers.rs
- core/src/non_circulating_supply.rs
- core/src/replay_stage.rs
- core/src/rpc_service.rs
- core/tests/bank_forks.rs
- genesis-programs/src/lib.rs
- genesis/src/main.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore_processor.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster.rs
- multinode-demo/setup.sh
- net/net.sh
- run.sh
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/rent_collector.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- sdk/src/genesis_config.rs
- stake-monitor/src/lib.rs
OperatingMode doesn't match with the reality.
Refactor and restore compatibility for devnet.
This is backport of #12068 
Fixes #12039
> Rename to ClusterType and restore devnet compat. (manual bp)

- Cargo.lock
- dos/Cargo.toml
- dos/src/main.rs
No way to simulate RPC dos attacks.
Add DOSing capability for `get_program_accounts` and `getAccountInfo`
Fixes #
> Add feature to DOS RPC

- ledger-tool/src/bigtable.rs
Another knob to control how to pull transaction history data out of bigtable
> ledger-tool: Add `bigtable transaction-history --query-chunk-size` argument

- genesis/src/main.rs
v1.2 `solana-genesis` doesn't know about this newfangled `--cluster-type` thing, which breaks its compatibility with modern multinode-demo scripts as used by rolling upgrade testing
Add a hidden `--cluster-type` arg and map its values onto `--operating-mode`
> genesis: Half-support new --cluster-type on v1.2

- ledger-tool/src/main.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
I'm too impatient to wait for two consecutive mergify backports
Pick them onto one branch
> Backport ledger-tool bank-hash subcommand to v1.2

- programs/bpf/benches/bpf_loader.rs
- programs/bpf_loader/src/serialization.rs
Serialiating the program parameters involves incremental writes to a vector which may induce many calls to alloc
Calculate the size ahead of time and alloc once
Fixes #
> Calc size ahead of time to alloc once

- docs/src/apps/jsonrpc-api.md
- sdk/src/commitment_config.rs
Docs are out of date for SingleGossip
Update docs 
Fixes #
> Update commitment options

- runtime/src/bank.rs
nit: use of qualified long names messy names
Shorten
Fixes #
> Nit, short name

- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/c/src/noop/noop.c
- programs/bpf/c/src/sanity/sanity.c
- programs/bpf/rust/noop/src/lib.rs
- programs/bpf/rust/sanity/Cargo.toml
- programs/bpf/rust/sanity/Xargo.toml
- programs/bpf/rust/sanity/src/lib.rs
Noop test programs are not actually noop and do a bunch of stuff that can affect noop bench metrics, etc...
Make them true noops
Fixes #
> Make noop a real noop

- core/src/crds_gossip_pull.rs
In CrdsFilter.mask all bits after mask_bits are set to 1:
https://github.com/solana-labs/solana/blob/555252f4/core/src/crds_gossip_pull.rs#L65
However the default implementation, sets both mask and mask_bits to zero
which is inconsistent with CrdsFilter::compute_mask for a mask_bits of
zero.
This commit changes the default implementation by setting mask to
`!0u64` (i.e all bits set to one). As a result, for the default crds
filter, `test_mask` will always return true, whereas previously it was
always returning false.
https://github.com/solana-labs/solana/blob/555252f4/core/src/crds_gossip_pull.rs#L85
This is only used in tests and benchmarks, but causes some benchmarks to
be misleading by short circuiting in this line:
https://github.com/solana-labs/solana/blob/555252f4/core/src/crds_gossi …
> patches default impl for crds filter

- faucet/src/faucet.rs
h/t @CriesofCarrots for spotting the `s/map/map_err/`
> Faucet: Improve error handling

- runtime/src/bank.rs
build is broken on master
Fix it.
@jackcmay FYI, #12135 was incompatible with #12195.
> Fix build breakage

- runtime/src/rent_collector.rs
> Enable stricter check on rent-exempt accounts on testnet

- runtime/src/bank.rs
> Enable retirement of rent collect in Bank::deposit() on testnet

- RELEASE.md
This is something a first-timer can bring in. :)
> Clarify some release docs

- programs/bpf/c/src/alloc/alloc.c
- programs/bpf/rust/alloc/src/lib.rs
- programs/bpf/tests/programs.rs
- sdk/bpf/c/inc/solana_sdk.h
No memory allocation support for C programs
Add it and fix the MAX values
Fixes #
> Add memory allocation support for C programs

- Cargo.lock
- tokens/Cargo.toml
- tokens/README.md
- tokens/src/arg_parser.rs
- tokens/src/args.rs
- tokens/src/commands.rs
- tokens/src/db.rs
- tokens/src/main.rs
- tokens/src/thin_client.rs
- tokens/tests/commands.rs
> v1.2: Backports of solana tokens improvements, including transfer to many arg

- validator/src/main.rs
> Rework snapshot download logic to be more forgiving when ` --expected-shred-version` is not provided

- client/src/rpc_client.rs
> v1.2: Remove client resends

- ci/nits.sh
- sdk/src/lib.rs
- sdk/src/program_option.rs
- sdk/src/program_pack.rs
SPL token contains some utilities that would be useful for other programs (are in a couple cases are already being used in the solana repo).
- Add COption, a C representation of rust's std Option, to sdk
- Add Pack trait to sdk
> Add Pack and COption to sdk

- docs/src/integrations/exchange.md
Mergify didn't like my PR
Manually backport it
> Docs: Add SPL Token exchange integration (bp #12303)

- validator/src/main.rs
Regression due to https://github.com/solana-labs/solana/pull/12340.   Lack of tests in validator/src/main.rs strikes yet again 📉
> validator: Bind to correct RPC addresses

- programs/bpf/rust/instruction_introspection/src/lib.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- sdk/benches/serialize_instructions.rs
- sdk/src/sysvar/instructions.rs
Some better naming and more gating noticed for the instruction introspection sysvar.
More consistent names and gating the instruction processing logic.
Fixes #
> Cleanup and feature gate instruction processing

- sdk/bpf/scripts/install.sh
Pulls in unaligned memory movement optimization, thanks @sconybeare!
Fixes #
> Bump rust-bpf to v0.2.4

- docs/src/implemented-proposals/instruction_introspection.md
- docs/src/implemented-proposals/secp256k1_instruction.md
secp256k1 feature implemented and instruction introspection not documented.
Move secp256k1 to implemented and add docs for instruction introspection.
Fixes #
> Add docs for secp256k1 and instruction introspection.

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
hashing behavior differs across branches.
synchronize the behavior across branches.
> Modernize pre-operating-mode-based hashing gating

- client/src/rpc_client.rs
Slight mixup going in/out of `json![]`
> RpcClient::get_multiple_accounts() now works

- Cargo.lock
- account-decoder/src/parse_token.rs
- cli-output/Cargo.toml
- cli-output/src/cli_output.rs
No support for SPL Token accounts in `cli-output` crate
Add it
> cli-output: Add CliTokenAccount type

- sdk/src/signers.rs
I need to sign transactions an arbitrary number of `Box<dyn Signer>`s 
Implement `Signers` for `Vec<Box<dyn Signer>>`
> Add `Signers` impl for `Vec<Box<dyn Signer>>`

- programs/bpf_loader/src/syscalls.rs
- sdk/bpf/c/inc/solana_sdk.h
Name mismatch and a test that depends on line number in the file
Align the names and fix the test so it is no longer dependent on line number
Fixes #
> Cleanup names, fix line dependent test

- programs/bpf/benches/bpf_loader.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
Budget calculation didn't drain the entire budget
Now does
Fixes #
> Drain the entire compute budget

- programs/bpf/tests/programs.rs
One test not being run, bad name
Add test, rename
Fixes #
> Nit: bpf test cleanup

- runtime/src/bank.rs
It's too hard to monitor inflation.  Emit a datapoint each epoch that details the results of inflation:
```rust
datapoint_warn!("epoch_rewards",
("slot", self.slot, i64),
("epoch", self.epoch, i64),
("validator_rate", validator_rate, f64),
("foundation_rate", foundation_rate, f64),
("epoch_duration_in_years", epoch_duration_in_years, f64),
("validator_rewards", validator_rewards_paid, i64),
("pre_capitalization", capitalization, i64)
("post_capitalization", self.capitalization(), i64)
```
> Add epoch rewards metric datapoint

- runtime/src/bank.rs
Post-merge feedback from #12376
> bank: Remove continues from compute_active_feature_set()

- runtime/src/bank.rs
- runtime/src/feature_set.rs
Add mechanism that'll allow us to fix the spl-token v2 multisig issue across the existing clusters
> Add feature to resolve the spl-token v2 multisig bug

- runtime/src/feature.rs
Address @ryoqun's post-merge feedback from #12376
> runtime/src/feature.rs: Add a couple feature tests

- core/src/crds_gossip_push.rs
Current implementation of `purge_old_pending_push_messages` does stack allocation, cloning, and 2 iterations which might be inefficient. `purge_old_received_cache` also does two iterations.
Updates `purge_old_pending_push_messages` to use `HashMap::retain` method.
Also, `purge_old_received_cache` is done in one iteration.
> purges old pending push messages more efficiently

- clap-utils/src/nonce.rs
- clap-utils/src/offline.rs
- cli/src/cli.rs
- cli/src/stake.rs
- client/src/blockhash_query.rs
> clap-utils: Allow nonce/offline args to be global (bp #12538)

- core/src/cluster_info.rs
https://github.com/solana-labs/solana/pull/12402 moved gossip-work threads:
https://github.com/solana-labs/solana/blob/afd9bfc45/core/src/cluster_info.rs#L2330-L2334
to ClusterInfo::new as a new field in the ClusterInfo struct:
https://github.com/solana-labs/solana/blob/35208c5ee/core/src/cluster_info.rs#L249
So that they can be shared between listen and gossip threads:
https://github.com/solana-labs/solana/blob/afd9bfc45/core/src/gossip_service.rs#L54-L67
However, in testing https://github.com/solana-labs/solana/pull/12360 it turned out this will cause breakage:
https://buildkite.com/solana-labs/solana/builds/31646
https://buildkite.com/solana-labs/solana/builds/31651
https://buildkite.com/solana-labs/solana/builds/31655
Whereas with separate thread pools all is good. It might be the …
> separates out ClusterInfo::{gossip,listen} thread-pools

- docs/src/apps/programming-faq.md
Developers don't have a place to look for commonly asked programming questions
Add first cut
Fixes #
> Add programming faq

- client/src/rpc_client.rs
v1.3 of https://github.com/solana-labs/solana/pull/12552
> v1.3: Switch get_program_accounts to use base64

- cli/src/feature.rs
As the managed feature set gets bigger for a cluster, it will be useful to be able to process status information from the Cli programmatically.
Add OutputFormat handling for `cli::features::process_status`
Examples:
```
$ solana feature status --url http://devnet.solana.com --output json
{
"features": [
{
"id": "3h1BQWPDS5veRsq6mDBWruEpgPxRJkfwGexg5iiQ9mYg",
"description": "consistent recentblockhashes sysvar",
"status": "active",
"sinceSlot": 5414912
},
{
"id": "DFBnrgThdzH4W6wZ12uGPoWcMnvfZj11EHnxHcVxLPhD",
"description": "bpf_loader2 program",
"status": "active",
"sinceSlot": 5414912
},
{
"id": "E3PHP7w8kB7np3CTQ1qQ2tW3KCtjRSXBQgW9vM2mWv2Y",
"description": "secp256k1 program",
"status": "active",
"sinceSlot": 5414912
},
{
"id": "E5JiFDQCwyC6QfT9REFyMpfK2mHcmv1GUDySU1Ue7TYv", …
```
> Enable json output from solana feature status

- cli/src/feature.rs
> v1.3: Enable json output from solana feature status (#12554)

- core/src/window_service.rs
- ledger/src/blockstore.rs
Not much visibility into the number of shreds inserted by repair vs. non-repair.
Add a counter to track which inserted shreds came from the repair port.
Fixes #
> Track inserted repair shreds

- docs/src/running-validator/validator-start.md
> Tune the sys-tuner documentation

- docs/src/apps/programming-faq.md
No problem
- Adding more information to the rand section of the app faq
- Reworded the rand topic title and moved it down to the "R" spot
Fixes #
> Add rand dep error to app faq

- runtime/src/accounts.rs
- runtime/src/feature_set.rs
- runtime/src/message_processor.rs
When running tests some features may not be enabled.
Run tests with features enabled and set a precedent for future tests
Fixes #
> Run tests with features on rather then off

- docs/sidebars.js
> Add programming-faq to sidebar

- ci/order-crates-for-publishing.py
- system-test/testnet-automation-json-parser.py
Python 2 is EOL, but we still have some
"Modernize"
> Modernize python scripts

- client/src/rpc_client.rs
If a transaction status isn't found on the first query, RpcClient send-and-confirm methods use the recent blockhash and continue polling until the transaction has expired. This doesn't work for nonced transactions, since the recent blockhash has deliberately already expired. The result is that the RpcClient method may return early that the transaction failed when in fact it has yet to land.
If the transaction is a nonced transaction, grab a recent blockhash from the chain and use that for initial timeout.
> Add nonced-tx check to RpcClient

- cli/src/cluster_query.rs
The "Rewards" section of `solana block ...` was a little weak, it now:
1. Sorts the addresses that received rewards
2. Displays the new balance for each rewarded account, and the % increase in each account
3. Renders the block time as local time instead of a unix timestamp
Example output from the latest testnet block that produced inflationary rewards:
```
$ solana block 38972256
Slot: 38972256
Parent Slot: 38972251
Blockhash: EKEKVLHNxRWwKT9DFh6ftQ3kapXw5m51mHFncsXHQB47
Previous Blockhash: B4oaihooct75MDoapk58PSENbe7ueSiGzCLTxDjMZqqR
Block Time: 2020-10-01T01:11:21-07:00
Rewards:
Address                                       Amount           New Balance    Percent Change
123JiW1rwJ4JM5BxYqFkBi6wQJ52pt6qUH88JDqrtU9i  ◎3224.5758       ◎30345.1966           0.1189% …
```
> cli: Improve `block` command output

- validator/src/main.rs
There is no handy way to disable port checking altogether for debugging and temporal work-around (like #12239 )
Just add it.
Maybe, I'm cursed by another unit-test less addition to the already over-populated jungle of `solana-validator` options ;)
> Add --no-port-check to validator

- ci/test-checks.sh
- programs/bpf/Cargo.lock
- programs/bpf/c/src/invoke/invoke.c
- programs/bpf/c/src/invoked/invoked.c
- programs/bpf/rust/invoke/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
cross-program invocation's don't enforce that the program be executable
- Enforce that programs are executable (mirrors this check: https://github.com/solana-labs/solana/blob/42aeead6b4e97663c8941ea5761b03b56eaa4be0/runtime/src/accounts.rs#L250)
- Remove long-standing `assert`
Fixes #
> Check CPI program is executable

- core/src/rpc_pubsub_service.rs
- core/src/validator.rs
- core/tests/client.rs
- validator/src/main.rs
v1.2 version of https://github.com/solana-labs/solana/pull/12616
> v1.2: Expose validator cli arguments for pubsub buffer tuning

- cli/src/cluster_query.rs
A common workflow is to start a validator with private RPC, and then monitor its catchup with `solana catchup`.  Until the validator loads the ledger and opens RPC `solana catchup` will fail on connection failures, requiring the user to repeatedly run  `solana catchup` until RPC opens.   Instead retry for the user.
> `solana catchup` now retries if the initial RPC connection fails

- core/tests/client.rs
- ledger-tool/src/main.rs
- run.sh
- version/src/lib.rs
we miss commit hash in versions
Show it. Also, some other niceties I've buffered. ;)
Fixes https://github.com/solana-labs/solana/pull/12376/files#r498626855
> Show commit in `--version` and ledger-tool's log

- web3.js/module.d.ts
- web3.js/module.flow.js
- web3.js/src/connection.js
web3.js will need to support program log messages found in the response of `getConfirmedBlock`.
Added necessary superstruct validators, typescript definitions, and flow definitions.
> web3.js: Introduce support for log messages inside ConfirmedTransactionMeta.

- cli-output/src/cli_output.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/src/vote.rs
Examples from testnet (see `Epoch Rewards:` section):
```
$ solana stake-account 5hBGx9rWB59snZyauR1p7KBM3aL2ZJcFbsyNqJ5zWjct
Balance: 400.742130995 SOL
Rent Exempt Reserve: 0.00228288 SOL
Delegated Stake: 400.739848115 SOL
Active Stake: 400.739848115 SOL
Delegated Vote Account Address: AT1kLQm1uYB5XZVocNUn9QkH3NPJRjRvf5orGS469xuy
Stake Authority: J78SNwDW6G86sMmh7djnBKGjewXNpjD74sJTjJ1iNgTH
Withdraw Authority: J78SNwDW6G86sMmh7djnBKGjewXNpjD74sJTjJ1iNgTH
Epoch Rewards:
Epoch     Reward Slot  Amount           New Balance      Percent Change             APR
105       40268260     ◎0.011577440     ◎400.742130995     0.000028891%    0.004858137%
104       39836256     ◎0.012396065     ◎400.730553555     0.000030935%    0.005213010%
```
and
```
$ solana vote-account …
```
> cli: Display vote/stake account epoch rewards

- programs/bpf/rust/ristretto/src/lib.rs
- programs/bpf/rust/ristretto/src/ristretto.rs
- programs/bpf/rust/sha256/src/lib.rs
- sdk/src/hash.rs
Unable to call `sha256` or `ristretto_mul` in a program test
- Fix the featurization
- Add tests to check featurization
Fixes #
> Fix syscall featurization

- docs/src/clusters.md
Reverts solana-labs/solana#12297
Fixes https://github.com/solana-labs/solana/issues/12298
> Revert "Restore --expected-shred-version argument for mainnet-beta"

- cli-output/src/cli_output.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/src/vote.rs
Manual backport of https://github.com/solana-labs/solana/pull/12711
> Display vote/stake account epoch rewards

- Cargo.lock
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/rust/call_depth/Cargo.toml
- programs/bpf/rust/call_depth/Xargo.toml
- programs/bpf/rust/call_depth/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- runtime/src/feature_set.rs
- runtime/src/process_instruction.rs
VM has a hardcoded max call depth and stack frame size
Pipe in as tuneable and bump the current max call depth from 20 to 64
Fixes #
> Add adjustable stack size and call depth

- sdk/src/pubkey.rs
Program addresses may collide for the same program id if the contamination of all the seeds results in the same string.
The issue is described in more detail here: #12343
Document the risk
Fixes #12343
> document program address collisions

- explorer/package-lock.json
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/scss/_solana-dark-overrides.scss
- explorer/src/scss/_solana.scss
Transaction instruction logs are not easy to view, and not at all from the explorer. This would be a great debug tool for program developers.
Adds program log section on Explorer transaction details page
Fixes https://github.com/solana-labs/solana/issues/12209
> Explorer: introduce program logs section on transaction details page

- Cargo.lock
- ci/test-checks.sh
- install/Cargo.toml
- install/src/command.rs
- programs/bpf/Cargo.lock
> v1.3: Pacify `cargo audit`

- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/native_loader.rs
Invalid native loader related tx's cause failures
Fix the issues
Fixes #
> fix native_loader behavior for invalid accounts

- ci/order-crates-for-publishing.py
#12579 broke crate publishing
Same, but different.  Really not sure why this behaves differently than the broken version.  Nor the broken one from the orig, tbh...
> CI: Fix crate publication

- scripts/cargo-install-all.sh
Users have to go hunting for the SPL Token CLI tool
Include it with release tarballs
> Release: Include SPL Token in release tarballs

- docs/src/pages/index.js
* remove `cli/usage`
* change `index.js`
* unclear CTA, docs unable to build
* fixes CTA
* removes breaking line in sidebars file
Fixes #
> Change developer CTA, remove sidebar issue

- Cargo.lock
- account-decoder/Cargo.toml
- core/Cargo.toml
- transaction-status/Cargo.toml
Crates can't be published due to sdk/feature mismatch in spl crates
Bump spl crates
cc @t-nelson
> Bump spl-memo and spl-token versions

- programs/bpf_loader/src/lib.rs
Developers don't have a nice way to determine how much of their compute budget a program used
On program completion the compute budget usage will be reported.  When making cross-program invocations each invocation's usage will also be reported.
Fixes #
> Report compute budget usage

- core/src/consensus.rs
Some tower assertions is unhelpful when debugging.
Fix that.
`automerge`-ing this because this is really small improvement.
absolutely, there is no functional change. :)
follow up #12875 
related to #12671 
cc: @carllin
> Another some tower logging improvements

- clap-utils/src/keypair.rs
- keygen/src/keygen.rs
Allow users to create mnemonics for other languages.
> keygen: add more mnemonic language support

- docs/src/integrations/exchange.md
- docs/src/running-validator/validator-reqs.md
> Mention monitoring and updating for exchanges

- docs/src/apps/jsonrpc-api.md
> Minor doc typo

- cli-output/src/cli_output.rs
Turn that raw unix timestamp in `solana vote-account ...` into a human-readable string
> cli: Improve vote-account "Recent Timestamp" output

- test-abi.sh
> fix broken ci

- cli/src/feature.rs
```
$ solana feature status EdM9xggY5y7AhNMskRG8NgGMnaP4JFNsWi8ZZtyT1af5
Stake By Feature Set:
2415322184 - 75% 
2674527397 - 24% 
EdM9xggY5y7AhNMskRG8NgGMnaP4JFNsWi8ZZtyT1af5 max invoke call depth 4                  active since slot 41904000
```
Yuck.
```
$ solana feature status EdM9xggY5y7AhNMskRG8NgGMnaP4JFNsWi8ZZtyT1af5
EdM9xggY5y7AhNMskRG8NgGMnaP4JFNsWi8ZZtyT1af5 max invoke call depth 4                  active since slot 41904000
```
Better.
> cli: Skip 'Stake by Feature Set' output when showing status of a single feature

- docs/src/implemented-proposals/program-derived-addresses.md
Outdated program address docs
bring up to date
Fixes #
> update program address docs

- Cargo.lock
- client/Cargo.toml
- client/src/mock_sender.rs
- client/src/rpc_client.rs
> RPC: Don't send base64 TXs to old clusters

- core/src/cluster_info.rs
Forgot to remove info log used during development
Remove log
Fixes #
> Remove spammy invalid rpc log

- core/src/rpc.rs
While attempting to simulate a secp256k1 instruction transaction, it was discovered that an invalid secp256k1 instruction won't be handled due to simulate_transaction's lack of precompile verification.
Introduces precompile verification to simulate_transaction call.
Fixes https://github.com/solana-labs/solana/issues/13079
> add precompile verification to simulate_transaction

- web3.js/package-lock.json
Nothing critical here, vast majority of "fixes" affected dev dependencies
> chore: npm audit fix

- sdk/Cargo.toml
- sdk/src/client.rs
- sdk/src/genesis_config.rs
- sdk/src/hard_forks.rs
- sdk/src/hash.rs
- sdk/src/pubkey.rs
- sdk/src/secp256k1.rs
- sdk/src/shred_version.rs
- sdk/src/signature.rs
- sdk/src/signers.rs
- sdk/src/system_transaction.rs
- sdk/src/transaction.rs
- sdk/src/transport.rs
> sdk: Rename "everything" feature to "full"

- scripts/coverage.sh
My hobby is killing time by watching ci console.
So, let's make the build output more beautiful. (I'm saying the above problem isn't actually a problem per se) xD
Fixes #humor
> Hide noisy specialization warnings for frozen abi

- docs/src/apps/programming-faq.md
Max cross-program invocation depth is now 4
Fixes #
> update call depth docs

- docs/src/running-validator/validator-start.md
Docs say testnet doesn't have a faucet, but it does
Clarify
> Docs: Testnet has a faucet now

- cli/src/cli.rs
`solana deploy ...` eats transaction error messages
Surface them
cc/ @CriesofCarrots
> CLI: Surface deploy transaction errors

- sdk/bpf/.gitignore
generated files in` sdk/bpf/dependencies` are not ignored
ignore them
Fixes #
> fix .gitignore

- web3.js/module.d.ts
- web3.js/module.flow.js
Web3.js `Message.from()` isn't exported
Export it
> fix: export message.from()

- net/scripts/solana-user-authorized_keys.sh
> Add SSH key for buildkite-agent on achille

- programs/bpf/rust/.gitignore
.so files created in the local rust program directory are not ignored
Fixes #
> ignore .so files

- runtime/src/bank.rs
- Bank transaction simulation doesn't account for forwarding delays which means that a transaction could pass simulation but fail processing after forwarding
- Account for forwarding delay in simulation
Fixes #
> Account for forward delay in transaction simulation

- sdk/bpf/scripts/install.sh
- the bpf install script relies on wget but clean macOS does not include it
- if a download gets interrupted in the middle the script thinks it was successful
- use curl if wget is not available
- restart the download if interrupted
Fixes #
> more portable install.sh

- ledger-tool/src/main.rs
- runtime/src/bank.rs
`ledger-tool cap`'s inflation simulation report isn't easy to view.
Make it beautiful.
Context: needed for debugging the initial inflation reward skew concern. (To be documented).
> Improve final report of ledger-tool capitalization

- docs/src/clusters.md
- docs/src/running-validator/validator-monitor.md
Validator metrics docs are stale
Update them
> docs: Metrics update

- docs/src/apps/sysvars.md
Prefer sysvar links go to the solana-program crate docs: https://github.com/solana-labs/solana/pull/13237#discussion_r513755038
> Update links from sdk to program

- sdk/program/src/pubkey.rs
Non-panicking version of `Pubkey::find_program_address()`, for when you never want to panic
> Add Pubkey::try_find_program_address()

- explorer/src/providers/block.tsx
- Retry doesn't work after first failure
- Retrying flashes default state before showing failure state
Fixes #
> Explorer: fix confirmed block refetch

- explorer/src/components/account/SlotHashesCard.tsx
- explorer/src/components/account/SysvarAccountSection.tsx
- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/account/TransactionHistoryCard.tsx
- explorer/src/components/account/VoteAccountSection.tsx
- explorer/src/components/account/VotesCard.tsx
- explorer/src/pages/ClusterStatsPage.tsx
Add links to slots in account details, transaction history, etc.
> Explorer: Linkify all displays of slot number

- runtime/src/accounts_db.rs
bad_bank_hash test is slow
Optimize, re-use account set and randomly sample from it for the store loop and reduce iterations. Reduces from about 2:30 into 30 seconds.
Fixes #
> Make bad_bank_hash test faster

- core/src/cluster_info.rs
- core/src/crds_gossip_push.rs
`ClusterInfo::handle_packets` can do some parallel processing:
https://github.com/solana-labs/solana/blob/c0675968b/core/src/cluster_info.rs#L1703-L1812
Incoming pull-requests and pull-responses are now processed using parallel iterators.
> adds more parallel processing to gossip packets handling

- Cargo.lock
- cli/Cargo.toml
- cli/src/cli.rs
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/benches/bpf_loader.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/feature_set.rs
The rbpf API has changed to unify the interfaces of the interpreter and the JIT.
Updates the interfaces and refactors the common code of test and bench targets into the bpf_test_utils crate.
Note: The JIT is not enabled by default yet.
Fixes #
> Rbpf v0.2.0

- sdk/program/src/program_pack.rs
The `Sealed` trait comment provides no new information
Fixes #
> clarify comment

- Cargo.lock
- banks-client/Cargo.toml
- banks-client/src/lib.rs
- banks-interface/Cargo.toml
- banks-server/Cargo.toml
- banks-server/src/banks_server.rs
- core/Cargo.toml
- tokens/Cargo.toml
- tokens/src/commands.rs
- tokens/src/main.rs
No known issues - just trying to keep tarpc close to HEAD so it's easier to upstream changes
Upgrade tarpc to 0.23 and tokio 0.3 (which aims to turn 1.0 by end of year)
> Upgrade tarpc and tokio

- explorer/public/tokens/front.svg
- explorer/src/tokenRegistry.ts
Wrapped FRONT needs to be added to token registry.
Add token information and icon.
> explorer: add Wrapped FRONT to token registry

- sdk/program/src/account_info.rs
> Update AccountInfo comments

- runtime/src/hardened_unpack.rs
There is a bug report that this error is causing trouble for unknown reason.
Print more detail.
Fixes #
> Print the entry type as well when checking archive

- Cargo.lock
- ci/test-checks.sh
- cli-config/Cargo.toml
- cli-config/src/config.rs
- cli/Cargo.toml
- install/Cargo.toml
- install/src/command.rs
- install/src/defaults.rs
- keygen/Cargo.toml
- keygen/src/keygen.rs
- programs/bpf/Cargo.lock
- tokens/Cargo.toml
> v1.4: Resolve cargo audit complaints

- Cargo.lock
- ci/test-checks.sh
- cli-config/Cargo.toml
- cli-config/src/config.rs
- cli/Cargo.toml
- install/Cargo.toml
- install/src/command.rs
- install/src/defaults.rs
- keygen/Cargo.toml
- keygen/src/keygen.rs
- programs/bpf/Cargo.lock
- tokens/Cargo.toml
> v1.3: Resolve cargo audit complaints

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/instruction/SerumDetailsCard.tsx
- explorer/src/components/instruction/TokenSwapDetailsCard.tsx
- explorer/src/components/instruction/serum/types.ts
- explorer/src/components/instruction/token-swap/types.ts
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/utils/tx.ts
Currently, Serum DEX instructions appear as Unknown (see: https://explorer.solana.com/address/ErF6ptYb3tKzSZjLKBoTqYJPUkMQtPUeAGo16kGLdGVt/tokens). It would be useful for Explorer to decode the instructions to provide more detail.
- maps serum instructions on TokenHistory and updates SerumDetails card
- maps token swap instructions on TokenHistory and adds TokenSwapDetails card
Fixes https://github.com/solana-labs/solana/issues/13171
> explorer: Parse Serum DEX and swap instructions for TokenHistory

- sdk/src/sysvar/mod.rs
backport of https://github.com/solana-labs/solana/pull/13175
> v1.3: check sysvar id for AccountInfo (#13175)

- docs/src/clusters.md
Cluster docs still say MB doesn't have smart contracts enabled
Correct them
> docs: Mainnet-beta totally has smart contract enabled

- runtime/src/stakes.rs
Stakes::clone_with_epoch is a bit hard to read.
Add some comments. There is no functional change.
Context: as a part of thinking correct stake account normalization strategy.
> Comment Stakes::clone_with_epoch

- docs/src/integrations/exchange.md
Much nicer!  Exchange users now only need to provide their primary SOL wallet address when withdrawing tokens
> Update SPL Token exchange documentation to include associated-token-account workflow

- docs/src/developing/deployed-programs/overview.md
Provide developers more information if they encounter a stack overflow error
Fixes #
> stack overflow docs

- sdk/cargo-build-bpf/src/main.rs
General feedback has been that playing the final ELF in the current working directory is not very nice.  Default  to `target/deploy` instead, which can still be overridden by the `--bpf-out-dir` argument.
At the end of the build, also print a message informing the user about where to find the final ELF:
```
$ cargo-build-bpf --bpf-sdk ../../../../sdk/bpf`
BPF SDK: /Users/mvines/ws/s3/sdk/bpf
Running: /Users/mvines/ws/s3/sdk/bpf/rust/xargo-build.sh
Finished release [optimized] target(s) in 0.33s
Running: /Users/mvines/ws/s3/sdk/bpf/scripts/strip.sh /Users/mvines/ws/s3/programs/bpf/target/bpfel-unknown-unknown/release/solana_bpf_rust_noop.so /Users/mvines/ws/s3/programs/bpf/target/deploy/solana_bpf_rust_noop.so
To deploy this program:
$ solana deploy …
```
> cargo-build-bpf: Final program ELF is now placed in ./target/deploy/ instead of .

- ci/publish-crate.sh
- ci/test-bench.sh
- ci/test-checks.sh
- ci/test-stable.sh
- docs/build-cli-usage.sh
- install/install-help.sh
- scripts/cargo-for-all-lock-files.sh
- scripts/cargo-install-all.sh
- scripts/coverage.sh
- storage-bigtable/build-proto/build.sh
Cargo toolchain resolution replicode
Use the branch-versioned cargo wrapper to resolve toolchain throughout CI/scripts
> CI: Use branch-versioned cargo throughout

- core/src/cluster_info.rs
Gossip packets processing breakdown
Added metrics for measuring processing time of each kind of gossip packets.
> measures processing time of each kind of gossip packets

- Cargo.lock
- Cargo.toml
- cargo-test-bpf
- program-test/src/lib.rs
- programs/bpf/rust/.gitignore
- scripts/cargo-install-all.sh
- sdk/cargo-build-bpf/src/main.rs
- sdk/cargo-test-bpf/Cargo.toml
- sdk/cargo-test-bpf/src/main.rs
> v1.4: Add cargo-test-bpf

- explorer/src/utils/tx.ts
- fetch-spl.sh
* Add explorer label
* Add program to `./fetch-spl.sh`
> SPL Associated Token Account plumbing

- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/rust/mem/Cargo.toml
- programs/bpf/rust/mem/Xargo.toml
- programs/bpf/rust/mem/src/lib.rs
- programs/bpf/tests/programs.rs
Incoming modifications to the bulitin mem routines don't have tests
Add them
Fixes #
> Add builtin mem tests

- program-test/src/lib.rs
- sdk/cargo-test-bpf/src/main.rs
The feature allows for tests to distinguish between `cargo test` and `cargo test-bpf` primarily for the purpose of excluding CPI tests that require the system program under `cargo test`, as the path to enabling CPI in `cargo test`-based testing is unclear.
It's really unfortunate that CPIs require `unsafe` modifications to the caller's `AccountInfo` structs.  This is ok in BPF VM construct but completely unviable from a pure Rust call chain.    Fixing this requires a major overhaul of `Account`, `KeyedAccount` and `AccountInfo`.  What a mess.  Blocking certain kinds of CPI from host-based program testing is the best  alternative I can think of until then.
> cargo-test-bpf now sets the "test-bpf" feature for crate tests

- sdk/cargo-build-bpf/src/main.rs
- sdk/cargo-test-bpf/src/main.rs
Running a `cargo build-bpf` or `cargo test-bpf` from the root of the SPL repo now works!   It builds/tests all workspace crates that contain a `Xargo.toml`
> cargo-build-bpf/cargo-test-bpf now support --workspace/--all

- docs/publish-docs.sh
URL redirects were not up to date and malformed
Update and fix formatting
Fixes #
> update doc redirects

- docs/src/developing/programming-model/cpi.md
Cross-program invocation docs refer to `keyed_accounts` and don't mention that the program itself needs to be passed.
Update the docs to reflect ^^
Fixes #
> update cpi docs

- core/src/rpc_subscriptions.rs
The RPC pubsub api allows subscribing to account changes in realtime. However, when account balance goes to 0, no notification is sent. This is a problem because clients with a live payer account need to know when an account's balance is depleted
Send a notification if an account is not found and last notified slot > 0
Fixes https://github.com/solana-labs/solana/issues/10442
> Send RPC notification when account is deleted

- core/src/completed_data_sets_service.rs
Access on transaction which may have no signatures.
Fix access
Fixes #
> Fix signature access

- sdk/bpf/c/inc/solana_sdk.h
New logging syscalls don't have stubs
Add stubs
Fixes #
> add missing c logging stubs

- runtime/src/accounts_db.rs
Store -> update index -> handle reclaims is a common pattern used by both regular account store and shrink.
Refactor this functionality into common functions shared with shrink and regular account store.
Fixes #
> Refactor store/update index function

- Cargo.lock
- banks-client/Cargo.toml
- banks-client/src/lib.rs
- tokens/src/commands.rs
Code complexity in BanksClient
Remove extension trait `BanksClientExt`
> Remove need for BanksClientExt trait

- sdk/bpf/c/inc/solana_sdk.h
- Missing test stubs
- No info on heap region
- Add missing test stubs
- Add info about heap region available to programs
Fixes #
> Add stubs and heap region definitions

- program-test/src/lib.rs
The zero-cost fee_calculator that comes by default at genesis is not ideal for normal program unit testing.  Like rent, it's better to have a realistic value by default.
This took more effort than one might expect to realize.  😅
> program-test: Use a non-zero fee_calculator for a more realistic test environment

- Cargo.lock
- program-test/Cargo.toml
- program-test/src/lib.rs
Backport of https://github.com/solana-labs/solana/pull/13541
> v1.4: program-test now generates new blockhashes for test usage

- runtime/src/bank.rs
> Small cleaning update_epoch_stakes

- net/net.sh
curl errors with 301 of redirect to https when downloading.
Use -L to follow redirect.
Fixes #
> Tell curl to follow redirects

- core/src/rpc.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- run.sh
- runtime/src/builtins.rs
- runtime/src/message_processor.rs
- sdk/src/process_instruction.rs
- web3.js/bin/localnet.sh
https://github.com/solana-labs/solana/pull/13556 for master
> Add stable program logging for BPF and native programs

- ledger-tool/src/main.rs
- programs/stake/src/stake_state.rs
- runtime/src/bank.rs
> ledger-tool cap: delegation owner and stake v2 flag

- ledger/src/blockstore.rs
- ledger/src/shred.rs
Assert fails to check additional case that could trigger shred completion updates
Fixes: https://github.com/solana-labs/solana-security/issues/14
Fixes #
> Fix assertion failure

- client/src/rpc_client.rs
Add the ability to override the default commitment in RpcClient (much like what solana-web3.js provides)
Example of the resulting client cleanup: https://github.com/solana-labs/solana-program-library/pull/853
> Add RpcClient::new_with_commitment()

- scripts/build-downstream-projects.sh
downstream-projects CI fails due to helloworld updates
helloworld no longer supports the program feature
Fixes #
> helloworld no longer supports program feature

- programs/stake/src/stake_state.rs
In the churn of fixing stake split, we missed one case: splitting a StakeState::Initialized account to a smaller StakeState::Initialized account. This operation needs to include the adjustment for the rent_exempt_reserve to be correct on the new account.
Add rent_exempt_reserve adjustment for stake-split Initialized
> Update Initialized split rent-exempt value

- account-decoder/src/parse_sysvar.rs
- runtime/src/bank.rs
Just a couple nits to improve monitoring of timestamp correction and bounding on testnet (PR to master to follow)
> v1.4: Improve monitoring of timestamp correction and bounding

- account-decoder/src/parse_sysvar.rs
- runtime/src/bank.rs
Fixes a couple nits to improve monitoring of timestamp correction and bounding
> Improve monitoring of timestamp correction and bounding

- Cargo.lock
- tokens/Cargo.toml
- tokens/src/commands.rs
- tokens/src/db.rs
- tokens/src/main.rs
- tokens/tests/commands.rs
solana-tokens broken on mainnet because BanksServer port isn't load balanced.
Revert to RpcClient
> Revert solana-tokens to RpcClient

- cli/Cargo.toml
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
Pick up overflow/underflow changes
Fixes #
> Bump rbpf to v0.1.33

- Cargo.lock
- tokens/Cargo.toml
- tokens/src/arg_parser.rs
`--version` is a stub, add the real version info
> solana-tokens: Add real --version

- explorer/src/tokenRegistry.ts
Add new NFT to the explorer https://solible.com/#/trade/rxqQa92aD8ZZGuyc2mjCARG4f832dBmQo9xiasX5mzq
> explorer: Add SRM tee-shirt NFT to the tokenRegistry

- core/src/rpc.rs
RPC's missing block error frightens the tourists
Demote it to a warning
> RPC: Demote missing block error to warning

- docs/set-solana-release-tag.sh
When building docs bsd sed fails but build still completes "successfully"
Bail if trying to use bsd sed
Fixes #
> Guard against bsd sed

- programs/stake/src/stake_state.rs
The new split stake exhibits a loophole to activate stake without going through the warm up period. If you create/activate an over-large stake account and split the entire account into an empty smaller account, the delta between the larger source rent-exempt-reserve and the new smaller one is instantly activated.
Only stake up to the source active stake amount when splitting the entire balance of a stake account
> Cap split stake at source stake when splitting entire balance

- core/src/rpc.rs
https://github.com/solana-labs/solana/pull/13776 for v1.4
> v1.4: Check SlotNotRooted if confirmed block not found in blockstore or BigTable

- scripts/build-downstream-projects.sh
Downstream project build is broken.
Peg to a specific, previous working commit
> Specify downstream commit

- core/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
> Nonce updates

- core/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
Cleanup nonce code for v1.3
Fixes #
> Nonce updates (v1.3 bp)

- clap-utils/src/input_parsers.rs
- cli/src/cli.rs
- cli/src/cluster_query.rs
- client/src/pubsub_client.rs
- client/src/rpc_config.rs
- client/src/rpc_response.rs
- core/src/rpc_pubsub.rs
- core/src/rpc_subscriptions.rs
- docs/src/developing/clients/jsonrpc-api.md
- runtime/src/bank.rs
```
$ solana logs --help
solana-logs 
Stream transaction logs
USAGE:
solana logs [FLAGS] [OPTIONS] <ADDRESS>
...
```
> Add `solana logs` command

- core/src/rpc.rs
Rpc `getConfirmedBlock` and `getBlockTime` methods return inconsistent results to the caller depending on whether the node supports BigTable long-term storage.
Follow up to https://github.com/solana-labs/solana/pull/13776
- Check for slot not *yet* rooted before potentially looking at BigTable
> Separate blockstore checks for not (yet) rooted and cleaned up

- system-test/performance-testcases/gce-cpu-only-perf-5-node-single-region.yml
No single region gce profile which is a bit faster for debug to get going with better network speed.
Add one.
Fixes #
> Add gce single region cpu-only

- multinode-demo/delegate-stake.sh
- net/net.sh
- net/remote/remote-node.sh
vote keys are referenced from the wrong location on the validator with remote-node.sh
Fix the location with a common helper function to get the path
Fixes #
> Fix validator keys path

- validator/src/main.rs
If the validator has a snapshot that's less than 500 slots away from the highest snapshot available for download, the validator now uses its local snapshot.  500 slots is ~ 3.3 minutes, and I'm seeing a mainnet-beta snapshot download take about that time when not sitting on the GCP backbone.    So it's better to use that 3.3 minutes trying to catchup with what you already have.   
`--maximum-local-snapshot-age 0` will disable this functionality and restore the previous behaviour of unconditional snapshot downloading.
> solana-validator: Add --maximum-local-snapshot-age argument

- validator/src/main.rs
https://github.com/solana-labs/solana/pull/13842 for v1.4
> v1.4: solana-validator: Add --maximum-local-snapshot-age argument

- Cargo.lock
- watchtower/Cargo.toml
- watchtower/src/main.rs
v1.4 version of https://github.com/solana-labs/solana/pull/13846
> v1.4: Groom solana-watchtower

- runtime/src/message_processor.rs
verify_and_update not checking all cases
Add more checks
Fixes #
> Add extra checks to verify_and_update

- explorer/src/components/SearchBar.tsx
- explorer/src/utils/tx.ts
Explorer search bar does not list the memo program.
Make memo program available in program list / map.
> Explorer: introduce Memo Program to search bar

- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/rust/spoof1/Cargo.lock
- programs/bpf/rust/spoof1/Cargo.toml
- programs/bpf/rust/spoof1/Xargo.toml
- programs/bpf/rust/spoof1/src/lib.rs
- programs/bpf/rust/spoof1_system/Cargo.lock
- programs/bpf/rust/spoof1_system/Cargo.toml
- programs/bpf/rust/spoof1_system/Xargo.toml
- programs/bpf/rust/spoof1_system/src/lib.rs
- programs/bpf/tests/programs.rs
> Add program id spoof tests

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
Overflow issues found in goblin crates
Pull in the fixes
Fixes #
> Bump to rbpf v0.1.34

- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/rust/caller_access/Cargo.lock
- programs/bpf/rust/caller_access/Cargo.toml
- programs/bpf/rust/caller_access/Xargo.toml
- programs/bpf/rust/caller_access/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
Program could invoke a program that was not passed to it
Check that the invoker has been grated access
Fixes #
> Check that the program was granted access to program_id

- ledger-tool/src/main.rs
There is missing global variables desired for the simpler inflation validation.
Add it.
Fixes #
> Ledger tool cap basic columns

- programs/bpf_loader/src/syscalls.rs
Syscall address translation apis are confusing because they are named for the reference type they return (mut or not) but also take an `AccessType` specifying wether the memory should be check for ro or rw privileges.  This can cause confusion and errors if the two are mismatched (passing `AccessType::Load` to a mutable API).
Cleanup the API by removing the `AccessType` parameter and strictly rely on the API name and what it returns
Fixes #
> Cleanup memory translation APIs

- programs/bpf_loader/src/syscalls.rs
- sdk/program/src/pubkey.rs
`create_program_address` has no cap on the number of seeds that can be passed which can lead to a large hash compute load
Cap the maximum number of seeds to a reasonable amount
Fixes #
> Cap number of program address seeds

- banks-server/src/banks_server.rs
> BankServer::send_transaction_with_context() now performs signature verification

- download-utils/src/lib.rs
- local-cluster/tests/local_cluster.rs
- validator/src/main.rs
No download status bar if only file logging is enabled.
Backport to v1.4
Fixes #
> Add non-progress bar download status (#13370)

- core/src/replay_stage.rs
Non consecutive leader blocks like `1-> 3` are still within the same `NUM_CONSECUTIVE_LEADER_SLOTS` set of slots, but `maybe_start_leader` will still incur a propagation check on slot `1` before starting to generate block `3`. This may cause slot `3` to be skipped. 
Don't trigger the propagation check on blocks within the same `NUM_CONSECUTIVE_LEADER_SLOTS` set
Fixes #
> Fix skip propagation check

- ledger/src/entry.rs
Serialized size of transactions can exceed PACKET_DATA_SIZE.
Check serialized size of transactions in `verify_transaction_signatures`.
> verifies that serialized size of transactions does not exceed packet data size

- explorer/src/providers/stats/solanaDashboardInfo.tsx
- explorer/src/providers/stats/solanaPerformanceInfo.tsx
Cluster stats are showing infinity when there are no samples.
Filter samples.
> explorer: infinity stats issue hotfix

- ledger/src/blockstore_processor.rs
Sometimes it's useful to recreate a snapshot of an existing snapshot `S`, but this fails if there's a root > than said starting snapshot in the ledger, because `S` will be purged before the `dev_halt_at_slot` check is triggered.
Move `dev_halt_at_slot` check to beginning of processing loop
Fixes #
> Ledger-tool recreate snapshot of starting snapshots

- ledger-tool/src/main.rs
The `--remove-account <PUBKEY>...` option allows for arbitrary deletion of accounts when creating a new snapshot.
> ledger-tool: Add --remove-account option to create-snapshot command

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
Dropped hash not on dashboard.
Add to dashboard.
Fixes #
> Add dropped hash to dashboard

- cli/src/cli.rs
- cli/src/cluster_query.rs
There is no easy way to sanity-check tx expiration behavior.
Slightly augment `solana ping` so that it can be used for such purpose:
```
$ ./target/debug/solana --url http://localhost:8899 ping --blockhash 4CCNp28j6AhGq7PkjPDP4wbQWBS8LLbQin2xV5n8frKX -D --timeout 1
Source Account: 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j
Fixed blockhash is used: 4CCNp28j6AhGq7PkjPDP4wbQWBS8LLbQin2xV5n8frKX (supplied from cli arguments)
[1607325923.358861] Submit failed:         seq=0   error=ClientError { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: Blockhash not found", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(BlockhashNotFound), logs: Some([]) }) }) }
[1607325925.371077] Submit failed: …
```
> solana ping: add --blockhash and --print-timestamp

- programs/bpf/build.rs
- programs/bpf/c/src/invoke/invoke.c
- programs/bpf/rust/invoke/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
No cap on the number of signers that can be passed to a CPI call, could use execcesive resources
Cap
Fixes #
> Cap CPI signers

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/syscalls.rs
Fuzzy testing discovered more bugs in BPF JIT which are fixed in this release.
Updates rbpf to v0.2.2
Fixes #
> Updates rbpf to v0.2.2

- runtime/src/accounts_db.rs
Snapshot hashing causing spikes in replay times
Use a lower priority thread pool to do the hashing
Fixes #
> Lower priority for hashing threads.

- programs/bpf/c/src/invoked/invoked.c
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/bank.rs
- sdk/program/src/instruction.rs
Was false positive
Fix it
Fixes #
> Fix priv escalation test

- client/src/thin_client.rs
- runtime/src/bank_client.rs
- sdk/src/client.rs
No way to get rent exemption info from Client
Expose it
Fixes #
> Add get_minimum_balance_for_rent_excemption to Client

- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
Mechanics common to both BPF and native invoke lives in the BPF loader, 
Clean it up, make it more general, and move it to the message processor.
Fixes #
> Clean invoke in prep for native invoke

- core/src/rpc_pubsub.rs
- core/src/rpc_subscriptions.rs
Subscription map can grow without bounds.
- Add a cap to subscription map to limit total size and memory use
> Add subscription cap

- ci/buildkite-pipeline.sh
- ci/dependabot-updater.sh
> Follow new dependabot's commit author name

- sdk/program/src/account_info.rs
Nice to be able to extract a slice of `AccountInfos` rather then iter each one
Add `next_account_infos` helper
Fixes #
> Add next_account_infos helper

- runtime/src/hardened_unpack.rs
regex is very slow for tar file checking
Use custom loop, speeds up untar by 3x. 15s => 5s.
Fixes #
> Remove regular expressions, speeds up untar

- docs/src/developing/deployed-programs/overview.md
Loader serialization documentation has an error and could be re-organized to be clearer
Fixes #
> Update serialization docs

- ledger/src/builtins.rs
- local-cluster/tests/local_cluster.rs
New BPF lead is enabled everywhere so don't block it from mainnet in genesis
Part of default genesis now, removed from features builtin
Fixes #
> Cleanup ledger builtins

- programs/bpf/c/src/invoke/invoke.c
- programs/bpf/rust/invoke/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
Account resize is not included in the access violation checks
Include them
Fixes #
> check for resize access violations

- docs/src/cluster/vote-signing.md
Bad formatting in public doc.
Fixed the formatting.
Fixes #
> fix formatting error in docs

- runtime/src/accounts_db.rs
No visibility into store stats.
Backport store stats to 1.4 backport of #12882
Fixes #
> Add timings for store accounts (#12882)

- Cargo.lock
- account-decoder/Cargo.toml
- ci/test-checks.sh
- core/Cargo.toml
- tokens/Cargo.toml
- transaction-status/Cargo.toml
> Unignore RUSTSEC-2020-0077 - v1.5

- Cargo.lock
- account-decoder/Cargo.toml
- ci/test-checks.sh
- core/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- tokens/Cargo.toml
- transaction-status/Cargo.toml
> Unignore RUSTSEC-2020-0077 - v1.4

- core/src/rpc_service.rs
#14213 dropped the `content-length` header from snapshot GETs, resulting in confusion from validators that had no idea how large the snapshot download is.   Restore the header
> Restore Content-Length header for streaming snapshot download

- download-utils/src/lib.rs
- runtime/src/snapshot_utils.rs
Immediately before the validator downloads a snapshot it **deletes** all the snapshot archives it currently has.  If the new snapshot download fails for any reason you're now in a hard place.   
Instead employ the normal snapshot archive purging logic to clean up older archives but retain the newer archives as an exit strategy for when that 1.5 GB download fails and you decide to try to instead catchup with what you have in hand.
> Do not delete ALL other snapshots before downloading a new snapshot

- runtime/src/bank.rs
- Backport timestamp metrics improvements (part of #14210 )
> v1.4 fix timestamp metrics

- README.md
> Legal disclaimers

- runtime/src/accounts_db.rs
Ditto #14260, for master
Closes #14258
> Ignore long/hanging test

- core/src/cluster_info.rs
- core/src/test_validator.rs
- core/src/validator.rs
- docs/src/clusters.md
- local-cluster/src/local_cluster.rs
- net-utils/src/lib.rs
- validator/src/main.rs
> validator: Multiple --entrypoint support

- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_vote.rs
- core/src/commitment_service.rs
- core/src/consensus.rs
- core/src/replay_stage.rs
- ledger/src/blockstore_processor.rs
- ledger/src/staking_utils.rs
- programs/stake/src/legacy_stake_state.rs
- programs/stake/src/stake_state.rs
- programs/vote/src/vote_state/mod.rs
- programs/vote/src/vote_state/vote_state_versions.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/vote_account.rs
- sdk/src/nonce_keyed_account.rs
Lazy robot won't backport #14242 to v1.5
Do it by hand
> Deinit zero lamport account data 1.5

- runtime/src/message_processor.rs
CPI no longer uses the program data passed through a user program when calling another program.  Instead it pulls the program from pre accounts or account deps but that incurs a clone of program's account data.
Save a clone by sharing the data
Fixes #
> Save cloning program account data

- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/message_processor.rs
A BPF program can be run where the runtime thinks the program being run is the BPF loader itself
Program id passed to `ProcessInstruction` should be the id of the program being executed.
Fixes #
> Prevent bpf loader impersonators

- web3.js/src/connection.js
- web3.js/src/loader.js
- web3.js/test/bpf-loader.test.js
- web3.js/test/connection.test.js
- web3.js/test/mockrpc/confirm-transaction.js
- web3.js/test/nonce.test.js
- web3.js/test/stake-program.test.js
- web3.js/test/system-program.test.js
- web3.js/test/transaction-payer.test.js
Give solana-web3.js tests some TLC
> fix: clean up racy tests

- core/src/cluster_info.rs
- core/src/cluster_slots.rs
- core/src/consensus.rs
- core/src/optimistically_confirmed_bank_tracker.rs
- core/src/replay_stage.rs
- core/src/rpc.rs
- core/src/sample_performance_service.rs
- core/src/validator.rs
- runtime/src/bank_forks.rs
Following up on [this comment](https://github.com/solana-labs/solana/pull/13929/files#r543545477)
Get the staked nodes from root-bank as opposed to the working bank
> obtains staked-nodes from the root-bank

- stake-o-matic/src/main.rs
Recent mainnet instability is often causing more than 20% of block producers to fail the threshold, halting all bonus stake from moving for good or bad block producers.
Allow setting the block production cutoff on the CLI to remove larger amount of stake if needed.  This is mostly a band-aid to keep the current stake bot running until @t-nelson finishes the work on the new delegation program, but will be useful right away for the currently deployed and often failing stake bot.
> Allow setting max poor block producer percentage

- sdk/cargo-test-bpf/src/main.rs
It's not possible to run a specific integration test with `cargo test-bpf` like you can with `cargo test --test <NAME>`
Forward the `--test` arg through to `cargo test`
Fixes #
> Add --test arg to cargo-test-bpf

- Cargo.lock
- core/src/validator.rs
- net-utils/Cargo.toml
- net-utils/src/ip_echo_server.rs
> Port ip-echo-server to tokio 0.3

- net-utils/src/lib.rs
The `solana-validator` port check takes ~15 seconds, reduce to 1-2 seconds.   The delay was due to unnecessarily waiting on UDP receive timeouts
> Speed up UDP reachable port checks

- system-test/automation_utils.sh
- system-test/testnet-automation-json-parser-missing.py
- system-test/testnet-automation.sh
We want to test hash mismatches with metrics
Read metrics from influx after test
Fixes #
> add logging using influx metrics

- programs/bpf_loader/src/lib.rs
Variable naming can be misleading when distinguishing between program id and loader id
Rename to clarify 
Fixes #
> nit: clarify loader id

- programs/bpf_loader/src/serialization.rs
Unnecessary non-debug assert in loader
Remove it
Fixes #
> Remove assert

- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
No gate on the CPI authorized programs list
Gate it
Fixes #
> Gate CPI authorized programs

- Cargo.lock
- banks-client/Cargo.toml
- banks-interface/Cargo.toml
- core/Cargo.toml
- core/src/bigtable_upload_service.rs
- core/src/rpc.rs
- core/src/rpc_service.rs
- faucet/Cargo.toml
- ledger-tool/Cargo.toml
- ledger-tool/src/bigtable.rs
- ledger/Cargo.toml
- ledger/src/bigtable_upload.rs
- net-utils/Cargo.toml
- program-test/Cargo.toml
Backport of https://github.com/solana-labs/solana/pull/14367
> v1.5: Back to tokio 0.2 for some of the tree

- core/src/rpc.rs
- core/src/validator.rs
- core/tests/snapshots.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- runtime/benches/accounts.rs
- runtime/benches/accounts_index.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/bank.rs
- runtime/src/inline_spl_token_v2_0.rs
- runtime/src/lib.rs
- runtime/src/secondary_index.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
- sdk/program/src/pubkey.rs
- sdk/src/pubkey.rs
- validator/src/main.rs
Scanning is slow on SPL tokens accounts with a filter for the mint is currently slow without an index
Introduce a mint index
Fixes #
> Mint index

- stake-o-matic/src/validator_list.rs
> Revert validator list changes

- explorer/src/components/TopAccountsCard.tsx
Loading the largest accounts has performance issues and until we can properly fix, we will introduce a load button.
Adds a load button to Largest Accounts card on Supply page.
> explorer: add load button for largest accounts card

- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
- sdk/src/feature_set.rs
CPI now ignores any changes a program may have made to an executable account and the caller no longer has to pass executable accounts but this change is not gated
Gate it
Fixes #
> Gate cpi program account passing

- core/src/poh_service.rs
PoH a bit too slow after update to hit target tick rate.
Adjust the target tick time down by 50ms.
Fixes #
> Add fixed tick rate adjustment

- explorer/src/App.tsx
- explorer/src/components/UnlockAlert.tsx
- explorer/src/pages/ClusterStatsPage.tsx
An alert box alerting the unlock of Jan 7. 
An alert box at the top of Explorer.
> explorer: add temporary unlock alert box

- explorer/src/components/UnlockAlert.tsx
Copy changes on banner unlock.
Implements those changes.
> Add UTC timing, tweak copy

- explorer/src/components/UnlockAlert.tsx
- explorer/src/utils/date.ts
Remove UTC from cluster time formatting globally. 
Don't display UTC
> explorer: remove UTC from cluster time 

- core/src/poh_service.rs
v1.5 backport of #14447 didn't happen automatically
Do it manually
> Add fixed tick rate adjustment (#14447)

- explorer/src/App.tsx
Unlock banner info no longer needed.
Removes unlock banner.
> Remove unlock banner

- programs/bpf_loader/src/lib.rs
Reporting the programdata account instead of the program account
Report the program account
Fixes #14484
> Report correct program id

- programs/bpf/c/src/invoke/invoke.c
- programs/bpf/rust/invoke/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
This is a cherry-pick of b1d702a
Fixes #
> Don't use caller passed executable account (#14276)

- runtime/src/snapshot_utils.rs
Hard linking of snapshots was disabled in https://github.com/solana-labs/solana/pull/6042 while we were still trying to get TdS Stage 0 off the ground.   Nowadays a mainnet-beta bank snapshot is ~27MB and there's no need to shuttle those bits around since a bank snapshot is immutable once created.  IOPS ⬇️
> snapshot_utils: Restore snapshot hard linking

- runtime/src/message_processor.rs
- runtime/src/native_loader.rs
The native loader does not check that the program it is asked to run actually belongs to it
Check it
Fixes #
> Check native account owner

- net/scripts/solana-user-authorized_keys.sh
> adds pubkey for behzad@solana.com

- core/src/send_transaction_service.rs
The send-transaction-service can be configured to send each transaction to more than one upcoming leader to increase the chances of the transaction landing. However, when a transaction is retried, it is only sent to one. This was my oversight.
- Use leader_forward_count for tx retries too, increasing the chances of a transaction landing sooner
> Use leader_forward_count for tx retries too

- stake-o-matic/src/main.rs
Validators with a commission greater than this amount get unstaked.
> stake-o-matic: Add --max-commission argument, default 100%

- core/src/retransmit_stage.rs
Removing local node's index early from the set here:
https://github.com/solana-labs/solana/blob/e1b59ded4/core/src/retransmit_stage.rs#L346
distorts the order of nodes depending on which node is computing the
turbine fan-out tree, and results in incorrect neighbors computation.
* Remove self _after_ computing turbine neighbors.
> patches bug in turbine's neighbors computation

- web3.js/module.d.ts
- web3.js/module.flow.js
- web3.js/src/system-program.js
- web3.js/test/system-program.test.js
The implementation of system-program in solana-web3 is incomplete.
Also... the implementations of AllocateWithSeed and AssignWithSeed are untested and broken (I guess no one has tried to use these!)
- Add TransferWithSeed handling
- Fix AllocationWithSeed and AssignWithSeed, and add tests to show they work now
> solana-web3: add TransferWithSeed implementation

- core/src/banking_stage.rs
- core/src/progress_map.rs
- ledger/src/blockstore_processor.rs
- program-test/src/lib.rs
- programs/bpf/tests/programs.rs
- runtime/src/bank.rs
Hard to debug node catchup issues without breakdown of execution times.
Add more metrics for execution.
Fixes #
> Add load/execute/store timings

- stake-o-matic/src/main.rs
If the RPC node doesn't locally contain epoch data, it still may be possible to fetch it from longer term storage.   Rework confirm blocks fetching to be friendly to this possibility. 
Freebie: `--url` is now accepted with `--cluster`, to make it possible to override the RPC URL that SoM uses while retaining the cluster-specific validator list.
> stake-o-matic: Fetch confirmed blocks from BigTable if all epoch data is not in the local ledger

- stake-o-matic/src/main.rs
Also quiet scary "Unexpected balance in stake account" messages that are now expected due to inflation
> Fix up stake-o-matic BigTable fetching

- web3.js/module.d.ts
- web3.js/module.flow.js
- web3.js/src/connection.js
solana-web3.js elements stripped from https://github.com/solana-labs/solana/pull/14430
> fix: handle confirmationStatus field in TransactionStatus

- watchtower/src/main.rs
The alert for a low validator identity balance is hard coded at 10 SOL.  Add `--minimum-validator-identity-balance` to grant the user more flexibility
> watchtower: Add --minimum-validator-identity-balance

- core/src/cluster_info.rs
- core/src/retransmit_stage.rs
- core/tests/cluster_info.rs
Current implementation is unnecessary complicated and involved.
The entire thing can be done in ~10 lines with no branches.
* Replaced retransmit peer computation with a simpler code.
* Added more test coverage.
> rewrites turbine retransmit peers computation

- programs/bpf_loader/src/lib.rs
- sdk/program/src/loader_upgradeable_instruction.rs
Small deploy buffers are invalid
Bail if found
Fixes #
> Bail on small deploy buffers

- Cargo.lock
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
Switch to accounts caching doesn't use parallel like the non-cached version does. Follow up to this: https://github.com/solana-labs/solana/pull/13140#discussion_r550840652
Add parallel scan to DashMap, add benchmark
Fixes #
> Parallel cache scan

- runtime/src/bank.rs
- sdk/src/feature_set.rs
> Add generalized voting process to enable full inflation

- core/src/rpc.rs
- transaction-status/src/lib.rs
Add transaction sanitization to a couple cli and RPC code paths
> Sanitize transactions more

- programs/bpf/tests/programs.rs
seems left out of https://github.com/solana-labs/solana/pull/14572
Fixes #
> adds missing block_time field

- programs/bpf_loader/src/lib.rs
- sdk/src/process_instruction.rs
The `log!()` macro in programs/bpf_loader/src/lib.rs is generically useful for other native programs.  Surface it in `sdk/src/process_instruction.rs` for use by the rest of the tree with some changes:
1. `log!()` is overloaded, so that name doesn't work generically
2. We use `msg!()` for BPF programs, so that's a starting point.  However `msg!()` relies on global state for its context, and we don't have that luxury in native programs (without introducing thread-local storage 😱)
3. Based on (1) and (2), I arrived at `ic_msg!(invoke_context,...)`.  It behaves like `msg!()` but with context
4. `ic_logger_msg()` is also provided for code that is already holding a `Logger`
> Add ic_msg()/ic_logger_msg() macros

- cli/src/feature.rs
Sometimes we want to force feature activation even though the cluster is not yet at 95% stake on the feature.  The current _solution_ is to modify the cli code but that's pretty terrible.  Add an undocumented workflow to accomplish this.
> solana feature activate: Add ability to force feature activation without code modification

- scripts/build-downstream-projects.sh
- sdk/src/feature_set.rs
Downstream tests disabled by accident
Re-enable
Fixes #
> Revert disabling script

- docs/src/developing/clients/jsonrpc-api.md
- docs/src/terminology.md
Clarify some behaviors of sendTransaction, mainly questioned by the parthers in the past.
Without double, this method is one of most used methos; it needs more details, before being too verbose. :)
Context #13443
> Improve documentation of sendTransaction

- explorer/src/components/instruction/token-swap/types.ts
- explorer/src/utils/tx.ts
The new token swap has new instructions and program id, so the explorer doesn't recognize it.
Add them!  I tested this locally and everything looked good
cc @bartosz-lipinski
> explorer: Add new token swap instructions and program id

- core/src/cluster_info.rs
- core/src/crds.rs
- core/src/crds_gossip.rs
- core/src/crds_value.rs
- core/src/duplicate_shred.rs
- core/src/result.rs
- core/src/window_service.rs
Following up on [this plan](https://discord.com/channels/428295358100013066/738253477331075162/784888854628139008).
when window service finds duplicate shreds, they are broadcasted through gossip.
> broadcasts duplicate shreds through gossip

- core/src/cluster_info_vote_listener.rs
- core/src/verified_vote_packets.rs
Another half-finished cleanup created while investigating #14806 is now polished up.
This was especially needed for human's eye liveliness analysis of VerifiedVotePackets and its fields... lol
There is no functional change.
Fixes #
> Clean up VerifiedVotePackets

- merkle-root-bench/src/main.rs
- runtime/src/accounts_db.rs
Remove legacy code. Add expected values for test.
See problem.
Fixes #
> remove legacy merkle root

- docs/README.md
- docs/src/developing/programming-model/accounts.md
- docs/src/developing/programming-model/transactions.md
There are two known security-related recommended practices when developing Solana's programs.
Document it properly as they're found.
Fixes #
> Add security best practice sections

- programs/bpf/tests/programs.rs
No explicit tests for:
- Invoking and upgrading a program in the same tx
- Upgrading one's self via cpi and invoking in the same tx
Add those tests
Fixes #
> Add more upgradeable tests

- docs/src/implemented-proposals/rent.md
> rent text cleanup

- cli/src/cli.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- core/src/rpc_pubsub.rs
- programs/stake/src/stake_instruction.rs
- stake-accounts/src/stake_accounts.rs
- tokens/src/commands.rs
- transaction-status/src/parse_stake.rs
> cli now supports a custodian for stake authorize operations

- runtime/src/accounts_background_service.rs
- runtime/src/accounts_db.rs
https://github.com/solana-labs/solana/issues/14834#issuecomment-767360854
Flush everything up to the `max_flush_root` so that snapshots aren't missing slots
Fixes #
> Snapshots missing slots from accounts cache clean optimization

- keygen/src/keygen.rs
Grinding vanity keypairs is fun to run in the background while doing other things, but grind defaults to `num_cpus::get()`, which can make it impossible to do anything else.
Add the "num-threads" argument to the grind command, defaulting to `num_cpus::get()`
Fixes #
> keygen: Add num-threads argument for grind

- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/scamRegistry.ts
- explorer/src/scss/_solana.scss
- explorer/src/spamRegistry.ts
We've identified a scam account and there will be more to come.
Introduce scam account registry and add specific account.
> explorer: Introduce scam registry and flag on account pages

- docs/src/developing/clients/jsonrpc-api.md
Adds documentation around token pre / post balances and blockTimes in getConfirmedSignatures2 and getConfirmedTransaction.
> RPC documentation updates for token deltas / blockTimes in getConfirmedSignatures2/getConfirmedTransaction

- programs/bpf/rust/invoked/src/processor.rs
Message is misleading
Fix it
Fixes #
> nit: message doesn't represent

- runtime/src/bank.rs
- sdk/src/feature_set.rs
Need to fix SPL Token without breaking the cluster
Add a feature
> Add feature for pending SPL Token self-transfer fix

- install/src/command.rs
Hitting ^C while solana-install update is extracting the new channel archive can brick your install. Fix it
cc: https://github.com/solana-labs/solana/pull/14919
> Prevent bricked install when ^C is pressed during archive extraction

- cli/src/cli.rs
- cli/src/program.rs
- cli/tests/program.rs
#14907  for master, for consistency
> Manually camelCase solana program json (#14907)

- sdk/src/feature_set.rs
Submit my nomination candidate request
Add pairs of nomination public keys
> Nam request for Inflation Candidate nomination

- sdk/src/feature_set.rs
Submit Stakeconomy.com nomination
Added our keys
> Stakeconomy Inflation Candidate Nomination

- runtime/src/accounts_db.rs
Cleaner way to get the count of AccountStorageEntry
Use it
Fixes #
> Use helper for count() in accountsDB

- validator/src/main.rs
There's no nice way to bootstrap a validator's ledger directory then exit.   This is a problem when running a validator in `--no-snapshot-fetch` mode (which is really best in general), but then you need to reinitialize the ledger directory due to some reason (fresh install, you fall 100k slots behind).  
The current workflow is restart the validator without `--no-snapshot-fetch` and watch the log as it downloads a new snapshot, then ^C at the right time, and restart the validator normally.   This is clunky.
Instead run `solana-validator <all normal args except for --no-snapshot-fetch> init` and the validator will exit itself at the right time.  No ^C required.
> solana-validator: Add "init" subcommand

- programs/bpf_loader/src/syscalls.rs
- runtime/src/message_processor.rs
More rich runtime logging and some cleanup
Fixes #
> More rich runtime logging

- cli-output/src/cli_output.rs
- cli-output/src/display.rs
Manual backport to v1.5 of #14963 'cause the :robot: is acting up
> CLI: Improve readability of `solana stake-history` (bp #14963)

- sdk/src/feature_set.rs
We lost the SPL Token self-transfer fix feature in 893cc76
Re-instate it
h/t @CriesofCarrots for the keen eye
> Reinstate SPL Token self-transfer fix feature

- Cargo.lock
- programs/bpf/Cargo.lock
- transaction-status/Cargo.toml
- transaction-status/src/parse_instruction.rs
SPL Memo v3 was just deployed; various RPCs don't parse memo instructions using the new program id
Update `parse_memo` to handle the new program id.
Example:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getConfirmedTransaction", "params":["32BZNu83y1exPNKKn3eETMJAFrbqkgW1nYAPr3WQSL6WBd4pV38woyCgYegC2KhRTMNLxRsQqQMdWpNidRNqGpcB","jsonParsed"]}' 127.0.0.1:8899 
{
"result": {
"blockTime": 1612218456,
"meta": {
"logMessages": [
"Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]",
"Program log: Signed by 7yVKsTKpWLieRYHa82DqwTfSSsgzB9wxkaJqj3u4axYh",
"Program log: Signed by Bbqg1M4YVVfbhEzwA9SpC9FhsaG83YMTYoR4a8oTDLX",
"Program log: Memo (len 4): \"🦖\"",
"Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed …
```
> Parse SPL Memo v3

- sdk/src/feature_set.rs
BL is not currently listed as an inflation nominee.
Adds BL to the sdk/src/feature_set.rs script.
> Inflation Nomination for BL

- runtime/src/append_vec.rs
> Disable AppendVec warn! for now

- docs/src/pages/index.js
Add hackathon promo banner.
Fixes #
> Add Hackathon banner

- runtime/src/accounts_db.rs
v1 shrink functions are confusing because no explanation of v1 is or what the difference is between non-v1.
* Move legacy v1 functions to another impl block
* Move cfg(test) functions to own impl block
* add some comments.
Fixes #
> Cleanup v1 shrink path

- cli/src/program.rs
Passing a buffer account by keypair file to `solana program deploy` doesn't work
Fix it
Fixes #14900
> Allow passing buffer by keypair to cli program deploy

- Cargo.lock
- client/Cargo.toml
- client/src/rpc_client.rs
- core/Cargo.toml
- core/src/rpc.rs
- core/src/rpc_pubsub.rs
- core/src/rpc_service.rs
- core/src/rpc_subscriptions.rs
- core/tests/rpc.rs
- programs/bpf/Cargo.lock
Our jsonrpc crates are out of date; the update requires some rewrite, as the tokio dependency moves from v0.1 to v0.2
Update crates and make necessary edits.
Toward #10187
> Upgrade jsonrpc crates to v17.0.0

- ci/setup-new-buildkite-agent/setup-buildkite.sh
- ci/setup-new-buildkite-agent/setup-limits.sh
- docs/src/running-validator/validator-start.md
- ledger/src/blockstore.rs
- sdk/docker-solana/README.md
- web3.js/bin/localnet.sh
What good are maps when you haven't any file descriptors?
Bump nofiles recommendation to match maps
> Docs: Bump nofiles recommendations to match maps

- sdk/src/feature_set.rs
> Nomination candidate for bunghi

- core/src/cluster_info.rs
- core/src/gossip_service.rs
- core/src/test_validator.rs
- core/src/validator.rs
- core/tests/gossip.rs
- local-cluster/src/local_cluster.rs
- validator/src/main.rs
Need capability to optionally disable duplicate instance check. 
Adds the validator flag to do so.
> adds flag to disable duplicate instance check

- sdk/src/feature_set.rs
> Nomination candidate for buburuza

- runtime/src/accounts_db.rs
Two problems with resetting the accounts backing store from `remove_account`:
* When async hashing comes the store may be in-use with snapshot hash calculation and if the store is reset, then doing `store.accounts(0)` will return an empty vec.
* When unrefing the store, if there is a reset, then accounts will not be unref'ed correctly in `finalize_dead_slot_removal` and thus not cleared from the index.
Add a new flag `reset_accounts` and only set `true` in the store_accounts path which is operating on non-frozen slots. Shrink and clean operate on only rooted slots and will set `reset_accounts=false` to keep the store contents from being reset.
Fixes #
> Don't reset accounts if the remove_account comes from a clean

- runtime/src/accounts_db.rs
same function was added overlapping resulting in duplicates
remove 2nd added function
Fixes #
> fix merge conflict

- sdk/src/feature_set.rs
> Nomination candidate for p2pvalidator

- runtime/src/accounts_db.rs
- runtime/src/snapshot_utils.rs
Clippy suggested this as part of larger changes and it is noisy, so I thought I'd pull it into its own pr.
type to &type
Fixes #
> borrow storages

- sdk/src/feature_set.rs
Fixes #
Rebase from the master and submitted a new PR
> Enable inflation candidate for RockX

- sdk/src/feature_set.rs
Would you marry me Solana? 50 TKPS 💍
> Add LowFeeValidation Nomination

- runtime/src/accounts_db.rs
unused arg in function
remove it
Fixes #
> remove unused arg from function

- sdk/src/feature_set.rs
@pkrasam was having trouble resolving merge conflicts here, https://github.com/solana-labs/solana/pull/14724#issuecomment-774055046, so I applied the patch he shared into this PR to help get him unstuck
> Add w3m's inflation pubkeys

- cli-output/src/cli_output.rs
- cli/src/program.rs
- cli/tests/program.rs
- Add show and dump tests
- update buffer len name
Fixes #
> Add cli deploy tests

- core/src/validator.rs
- ledger-tool/src/main.rs
- runtime/src/accounts_db.rs
- runtime/src/snapshot_utils.rs
ledger tool can use all available threads for hashing
allow the default thread pool to be used.
Fixes #
> Threadpool2

- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- sdk/src/feature_set.rs
> Require lockup authority to change withdraw authority on locked stake

- Cargo.lock
- banks-client/src/lib.rs
- banks-server/src/banks_server.rs
- program-test/Cargo.toml
- program-test/src/lib.rs
- program-test/tests/cpi.rs
- program-test/tests/fuzz.rs
- program-test/tests/warp.rs
- runtime/src/commitment.rs
The updates in program-test are needed in 1.5:
* #14997 
* #14998 
* #15136 
Backport them.
> v1.5: Backport program-test updates #14997 #14998 #15136 

- ledger-tool/src/main.rs
JIT and accounts cache arguments not plumbed in ledger-tool
Add them.
Fixes #
> Add jit and caching args to ledger-tool

- ledger/src/blockstore/blockstore_purge.rs
Purge can take a long time, but there is no indication of progress.
Add a 2s print with the status.
Fixes #
> Ledger purge printing

- ci/test-checks.sh
> v1.4: Quash cargo audit failure

- ledger-tool/src/main.rs
typo
puring => purging
Fixes #
> Fix ledger-tool typo

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/common/BalanceDelta.tsx
- explorer/src/components/transaction/TokenBalancesCard.tsx
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/utils/index.tsx
There is currently not a way to view token balance changes from the Transaction Details page.
Adds a "Token Balances" section on relevant transaction detail pages.
> explorer: introduce Token Balances on transaction details page

- core/src/rpc_pubsub_service.rs
Fixes #12619
Easy peasy thanks to @CriesofCarrots's efforts to get us up to jsonrpc 17.x
> Complete --rpc-pubsub-max-in-buffer-capacity/--rpc-pubsub-max-out-buffer-capacity plumbing

- runtime/src/accounts_background_service.rs
panic hit on simulation with capitalization mismatch after hash calculation.
revert to previous hash calculation algorithm.
Fixes #
> use index version of calculating hash

- core/src/rpc.rs
Users want to query for all token accounts of a particular mint, eg:
```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
{
"id": 1,
"method": "getProgramAccounts",
"params": [
"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
{
"encoding":"jsonParsed",
"filters": [
{
"dataSize": 165
},
{
"memcmp": {
"offset": 0,
"bytes": "<MINT_ADDRESS>"
}
}
]
}
]
}
'
```
However, this operation is currently very expensive, as it uses a full accounts scan.
When the `spl-token-mint` secondary index is available, use it for these requests (parallels existing fn for token-owner)
> Use spl-token-mint secondary index for relevant getProgramAccounts requests

- web3.js/package-lock.json
- web3.js/package.json
Snowpack doesn't resolve browser modules correctly with the current package.json config
Update to more widely accepted package.json config
Fixes https://github.com/solana-labs/solana-web3.js/issues/1010
> fix: use more widely accepted browser module config

- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
The cost of logging is not proportional to the amount logged
Charge per-byte for logging
Fixes #
> Add per-byte logging cost

- runtime/src/accounts_db.rs
Several parts of the merkle pipeline have been reworked previously. With the change in usage patterns, we can remove some code and improve both performance and simplicity as well as prepare for future changes that are coming to streamline this expensive operation further.
Remove some old code and rework.
Fixes #
> remove hash accumulation with lamports

- runtime/src/accounts_db.rs
We already use div_ceil and there will likely be a few more places soon.
implement div_ceil as a function
Fixes #
> create function div_ceil

- web3.js/module.flow.js
- web3.js/package-lock.json
- web3.js/package.json
Downstream flow errors: https://github.com/solana-labs/solana-program-library/pull/1212/checks?check_run_id=1879404711
> fix: move flow imports inside module declaration

- ledger-tool/src/main.rs
- programs/stake/src/stake_state.rs
related to this #15237 , another some very low-risk niceties, this is needed when I was doing last periodic inflation verification.
There should be no functional change.
> More failure codepath tracing wiring

- stake-o-matic/src/main.rs
Add log to for easier triage of unexpected SoM results
> stake-o-matic: Log validator root slot

- runtime/src/accounts_db.rs
Scanning accounts and accumulating hash and lamports is expensive. Flattening large vectors of data (from individual elements or from sub-vectors) is also expensive.
Allow hash calculation to operate on vectors of smaller size, resulting in lower time and memory use.
Later, we can do partial hashing of results to further reduce the data that has to be retained in memory during a scan.
Fixes #
> combine flatten and hash

- programs/stake/src/stake_state.rs
> Stake program update (v1.5)

- programs/stake/src/stake_state.rs
> Stake program update (v1.4)

- programs/stake/src/stake_state.rs
stake program checks
Stake program updates
Fixes #
> Update stake program

- sdk/program/src/hash.rs
base58 is slow
Don't try to decode more of it than we have to
> sdk: sanitize `Hash` base58 input

- cli/src/feature.rs
- cli/tests/stake.rs
- client/src/http_sender.rs
- client/src/pubsub_client.rs
- client/src/rpc_custom_error.rs
There are some typos exist in the codebase.
Fixes #
> style: Fix the typos

- ledger/src/blockstore.rs
Only sanitized transactions are included in rooted blocks. If an unsanitary transaction is read from a blockstore root, it likely indicates some sort of database corruption.
- Log any such incidents
> Log if unsanitary transactions are read from blockstore

- programs/stake/src/stake_state.rs
No test for an overflowing stake withdraw
Add one
> stake: add lamports overflow test for withdraw

- programs/bpf/Cargo.lock
- programs/config/Cargo.toml
> Bump rand_core to 0.6.2

- runtime/src/accounts_db.rs
CumulativeOffset was unfortunately named too specific to 1d. It will soon be used for 1d or 2d.
This is in its own pr to make the next change less messy.
Rename.
Fixes #
> rename CumulativeOffset in preparation of 2d support

- explorer/src/components/account/UpgradeableProgramSection.tsx
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/validators/accounts/upgradeable-program.ts
Not easy to know if a program is upgradeable or not
Add details for upgradeable program accounts
Immutable program:
Upgradeable program:
Fixes #
> explorer: Display upgradeable program details

- docs/src/developing/programming-model/accounts.md
> docs: Fix typo in account docs

- runtime/src/accounts_db.rs
https://github.com/solana-labs/solana/pull/15303#discussion_r576485645
Fixes #
> Change collect

- core/src/cluster_slots.rs
https://github.com/solana-labs/solana/issues/14366#issuecomment-769096305
If the cluster-slots map becomes too large, discard slots furthest away from the root.
> adds an upper bound on cluster-slots size

- programs/stake/src/stake_state.rs
More stake program checks
Stake program updates
> Clean & check stake

- core/tests/ledger_cleanup.rs
Creating and inserting a lot of shreds takes a long time. Hard to reproduce large ledger sizes.
Just clone to produce shreds and use a separate insert thread to overlap with shred creation.
Can insert shreds at 100k+ per second.
Fixes #
> Speedup ledger cleanup test

- sdk/src/nonce_keyed_account.rs
No test for an overflowing nonce withdraw
Add one
> Add lamports overflow test for nonce withdraw

- cli/src/program.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/bpf_verifier.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- sdk/src/feature_set.rs
- sdk/src/process_instruction.rs
> Cleanup old features

- web3.js/package.json
Parcel module resolution doesn't resolve correct browser module
Fixes https://github.com/solana-labs/solana-web3.js/issues/1011
> fix: fix browser module resolution for parcel

- program-test/src/lib.rs
- runtime/src/bank.rs
- sdk/program/src/instruction.rs
- sdk/program/src/program_error.rs
- storage-proto/build-proto/Cargo.lock
- storage-proto/proto/solana.storage.transaction_by_addr.rs
- storage-proto/src/convert.rs
- storage-proto/src/transaction_by_addr.proto
v1.5 version of https://github.com/solana-labs/solana/pull/15439
> v1.5: Rename IOError to BorshIoError

- core/src/cluster_info.rs
Need to monitor packets distribution. 
* Added metrics for inbound/outbound gossip packets counts
> adds metrics for inbound/outbound gossip packets counts

- clap-utils/src/input_validators.rs
- cli/src/cli.rs
- cli/tests/nonce.rs
- cli/tests/transfer.rs
- cli/tests/vote.rs
We aren't the only ones who've managed to send funds to derived addresses
Add hidden support for `SystemInstruction::TransferWithSeed` to CLI
Works on devnet, but needs tests fixed up + added
> CLI: Support transfer with seed

- core/src/validator.rs
Hard to debug.
Make it easier.
> Print original error from accounts dir remove

- account-decoder/src/lib.rs
- account-decoder/src/parse_token.rs
- cli-output/src/cli_output.rs
- core/src/rpc.rs
- scripts/build-downstream-projects.sh
- storage-proto/proto/solana.storage.confirmed_block.rs
- storage-proto/src/confirmed_block.proto
- storage-proto/src/convert.rs
- tokens/src/commands.rs
- tokens/src/spl_token.rs
- transaction-status/src/parse_token.rs
* Make UiTokenAmount::ui_amount a String
* Fixup solana-tokens
* Ignore spl downstream-project
> v1.5: Make UiTokenAmount::ui_amount a String (#15447)

- docs/src/developing/clients/jsonrpc-api.md
Update JSON-RPC docs to reflect uiAmount type change
cc @mvines
> Update uiAmount type in docs

- programs/bpf_loader/src/bpf_verifier.rs
Program size limit left in after feature cleanup
Remove it
Fixes #15469
> Remove limit on program size related to feature cleanup

- explorer/package-lock.json
- explorer/package.json
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/providers/accounts/flagged-accounts.tsx
We need to add a polyfill for fetch. Some older browsers and certain mobile browsers are not supported.
Add cross-fetch and some code cleanup
> explorer: add fetch polyfill and clean up / message change

- runtime/src/bank.rs
- runtime/src/epoch_stakes.rs
Epoch stakes doesn't like a vote account without an authorized voter
Handle it gracefully
Fixes #
> gracefully handle vote account without authorized voter

- explorer/src/components/instruction/MemoDetailsCard.tsx
- explorer/src/components/instruction/vote/VoteDetailsCard.tsx
Memo and vote instruction cards need to have the Program row at the top of the card.
Add Program for consistency.
> explorer: add program to vote and memo instruction card

- net/net.sh
- net/scripts/gce-provider.sh
Outdated version of 18.04 in places.
Image is 20.04, update everything to 20.04.
Fixes #
> Ubuntu 20.04 instead of 18.04

- account-decoder/src/lib.rs
- account-decoder/src/parse_token.rs
- cli-output/src/cli_output.rs
- core/src/rpc.rs
- scripts/build-downstream-projects.sh
- storage-proto/proto/solana.storage.confirmed_block.rs
- storage-proto/src/confirmed_block.proto
- storage-proto/src/convert.rs
- tokens/src/commands.rs
- tokens/src/spl_token.rs
- transaction-status/src/parse_token.rs
Reverts solana-labs/solana#15447
(Reverted on v1.5: #15535)
> Revert "Make UiTokenAmount::ui_amount a String"

- Cargo.lock
- Cargo.toml
- accounts-cluster-bench/Cargo.toml
- accounts-cluster-bench/src/main.rs
- client/src/rpc_client.rs
No standalone program for creating many accounts
Add one
Fixes #
> Add accounts cluster bench

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/connection.js
- web3.js/src/validator-info.js
- web3.js/test/connection.test.js
- web3.js/test/nonce.test.js
Old version of superstruct doesn't have coercions
- Update superstruct
- Program account notification attribute `accountId` is now coerced into PublicKey to match type definition
- Update all response validators to ignore extra attributes in responses
Fixes #
> feat: update superstruct and future proof type validations

- programs/config/src/config_processor.rs
- programs/stake/src/stake_instruction.rs
- programs/vest/src/vest_processor.rs
- programs/vote/src/vote_instruction.rs
- runtime/src/bank.rs
- sdk/program/src/instruction.rs
- sdk/src/feature_set.rs
- storage-proto/proto/solana.storage.transaction_by_addr.rs
- storage-proto/src/convert.rs
- storage-proto/src/transaction_by_addr.proto
It's easier to reason about program state if only the program that owns it can operate on it.
Check the program owners in a few of the builtin programs which don't check it.
Fixes #
> check program owners

- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
Manual backport of https://github.com/solana-labs/solana/pull/15567
💔 Mergify
> v1.5: ledger-tool: Trivialize creating a snapshot at the current root

- Cargo.lock
- notifier/src/lib.rs
- stake-o-matic/Cargo.toml
- stake-o-matic/src/main.rs
- stake-o-matic/src/validators_app.rs
SoM offers no way to to distribute stake based on infrastructure concentration.  Blaspheming one of the sects of decentralization
Add data center based distribution leveraging the validators.app API
> SoM: Support distribute stake based on infrastructure concentration

- cli/src/program.rs
cli `solana program dump` does not support non-upgradeable programs (mainly because `solana program` only supports upgradeable program operations).
Add support to `solana program dump` to dump non-upgradeable programs
Fixes #
> cli: dump non-upgradeable programs

- core/src/cluster_info_vote_listener.rs
Need to investigate where batches are broken up.
Added metrics
> adds metrics for the size and number of batches in bank_send_loop

- stake-o-matic/src/main.rs
Always have to adjust a fixed average when skip rate is variable.
Compare block producers against each other, classify based on a skip percentage below the mean.
Fixes #
> Use cluster average skip rate in stake-o-matic

- runtime/src/accounts_db.rs
formatting is messed up on a function
manually format it
Fixes #
> fix indentation format problem

- runtime/src/accounts.rs
> Fix clippy warnings

- core/src/banking_stage.rs
- core/src/poh_recorder.rs
Need more metrics to investigate where transactions are split
Added more metrics
> adds more metrics for tx counts and batch sizes

- docs/src/pages/index.js
The hackathon's over, people.
Remove the banner on the docs homepage.
Fixes #
> Remove Hackathon banner

- runtime/src/system_instruction_processor.rs
- sdk/src/nonce_keyed_account.rs
System program error reporting is cryptic
Add nice error messages
Fixes #
> Add error reporting to system program

- explorer/src/serumMarketRegistry.ts
Add a couple markets to the Serum registry.
Add a couple markets to the Serum registry.
> Explorer: introduce a couple new Serum market addresses

- programs/bpf/c/src/alloc/alloc.c
Finish TODO which replaces hardcoded number to defined macro 
Fixes #
> refactor: Use UINT64_MAX to replace hardcoded number

- core/src/cluster_info_vote_listener.rs
- core/src/verified_vote_packets.rs
Votes do not seem to coalesce in entries
Sends only the latest vote of each validator to the banking stage
> sends only the latest vote of each validator to the banking stage

- docs/src/running-validator/validator-reqs.md
Validator hardware recommendations are out of date
Update and generalize them
> Docs: Update validator hardware recommendations

- stake-o-matic/src/main.rs
We need time to inform the validator community of changes to stake-o-matic's skip rate calculation, but it's hard-coded on.
Stick the new behavior behind a flag
> Gate stake-o-matic cluster average behind a flag

- docs/src/running-validator/validator-reqs.md
:robot: beat me
Add @danpaul000's suggestions
> docs: address post-merge review of #15649

- cli-output/src/cli_output.rs
- cli/src/program.rs
- docs/src/cli/deploy-a-program.md
Now `solana program show` support for non-upgradeable programs and folks might try and be confused
Add it
Fixes #
> cli: add program show for non-upgradeable programs

- ledger/src/blockstore_processor.rs
Would be helpful to have timing stats printed when ledger-tool validate runs.
Log them when a ledger is validated.
Fixes #
> log timing after ledger process

- runtime/src/accounts.rs
Refactor this function because it is awkwardly written for changes that are coming. When we put the account's data in an arc, this becomes a little messy to rework. Makes more sense to just reorder the function cleanly first and remove uncertainty in the future, extensive change.
Fixes #
> refactor function to store into account after data is finished

- core/src/validator.rs
> validator: Remove unused id field

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/account/OwnedTokensCard.tsx
- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/components/transaction/TokenBalancesCard.tsx
- explorer/src/validators/accounts/token.ts
We have deprecated uiAmount in turn for uiAmountString to resolve some precision issues.
Use uiAmountString in place of uiAmount.
* Waiting on web3 build and release
> Explorer: support uiAmountString api updates

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/account/TokenLargestAccountsCard.tsx
TokenLargestAccounts now uses uiAmountString. 
Update uiAmount instances accordingly with BigNumber.
> Explorer: update TokenLargestAccounts to use uiAmountString. 

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
Not clear how slots are getting flushed and shrinking.
Add prints on shrink and flush.
Fixes #
> More debug on shrink and flush

- programs/bpf/c/src/dup_accounts/dup_accounts.c
- programs/bpf/rust/dup_accounts/src/lib.rs
- programs/bpf/tests/programs.rs
Missing test coverage of duplicate accounts via cpi
Fill the hole
Fixes #
> Add more duplicate account tests

- stake-o-matic/src/main.rs
Average cluster skip rate and each validator skip rate not in the log
Print it
Fixes #
> stake-o-matic Show cluster average skip rate

- stake-o-matic/src/main.rs
The `--max-poor-block-producer-percentage` safely belt doesn't work when ALL nodes are classified as poor.   
Thankfully due to an RPC error, the https://buildkite.com/solana-labs/stake-o-matic/builds/456#86b06df8-014d-4330-9623-9817cfe8da56 job from yesterday failed instead of accidentally removing stake from all nodes
> SoM: Avoid destaking all nodes when there are no quality block producers

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/SearchBar.tsx
- explorer/src/components/account/OwnedTokensCard.tsx
- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/account/TokenLargestAccountsCard.tsx
- explorer/src/components/instruction/token/TokenDetailsCard.tsx
- explorer/src/components/transaction/TokenBalancesCard.tsx
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/providers/mints/token-registry.tsx
- explorer/src/utils/tx.ts
The schema has changed for the latest spl-token-registry (to uniswap standard).
Update schema accordingly.
> Explorer: update to new spl-token-registry standard

- runtime/src/bank.rs
- sdk/program/src/instruction.rs
- sdk/src/genesis_config.rs
- sdk/src/hard_forks.rs
- sdk/src/lib.rs
- sdk/src/nonce_keyed_account.rs
- sdk/src/poh_config.rs
- sdk/src/process_instruction.rs
- sdk/src/secp256k1_instruction.rs
- sdk/src/shred_version.rs
- sdk/src/stake_weighted_timestamp.rs
- sdk/src/timing.rs
- storage-proto/proto/solana.storage.transaction_by_addr.rs
- storage-proto/src/convert.rs
- storage-proto/src/transaction_by_addr.proto
First steps to migrate sdk to `--deny clippy::integer_arithmetic`
Toward #15368
> Sdk: start to appease clippy's integer arithmetic check

- account-decoder/src/lib.rs
- account-decoder/src/parse_config.rs
- core/src/rpc.rs
- core/src/rpc_pubsub.rs
- core/src/rpc_subscriptions.rs
- ledger-tool/src/main.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/budget/src/budget_processor.rs
- programs/config/src/config_processor.rs
- programs/exchange/src/exchange_processor.rs
- programs/ownable/src/ownable_processor.rs
- programs/stake/src/config.rs
- programs/stake/src/stake_state.rs
- programs/vest/src/vest_processor.rs
- programs/vest/src/vest_state.rs
- runtime/benches/append_vec.rs
- runtime/src/accounts_cache.rs
- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/native_loader.rs
- runtime/src/rent_collector.rs
- runtime/src/stakes.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/keyed_account.rs
- transaction-status/src/token_balances.rs
We want to access accounts through traits.
This pr is part of a broader set of changes to use traits.
replace all non-mut account.data with account.data()
Fixes #
> account.data -> data()

- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
> AppendVec cleanup: remove dead code, rename non-idiomatic "new" function

- genesis/src/main.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
- runtime/src/message_processor.rs
- runtime/src/stakes.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/account.rs
Part of a larger effort to use methods to access account data.
add AccountSharedData.set_data method.
Fixes #
> AccountSharedData.set_data

- frozen-abi/macro/src/lib.rs
- frozen-abi/src/abi_digester.rs
- frozen-abi/src/abi_example.rs
- frozen-abi/src/lib.rs
Integer arithmetic in frozen-abi crate
Switch to checked/saturating arithmetic as needed
Toward: #15368
> Disallow integer aritmetic in frozen-abi

- cli-config/src/config.rs
- cli-config/src/lib.rs
Integer arithmetic in cli-config crate
Switch to checked math
Toward: #15368
> Disallow integer aritmetic in cli-config

- validator/src/main.rs
> solana-validator monitor: Fix delinquent stake display

- core/src/consensus.rs
- sdk/src/native_loader.rs
AccountSharedData.data is moving to private. All construction needs to follow the new pattern.
Constructions fixed.
Fixes #
> More AccountSharedData construction

- sdk/src/feature_set.rs
> nit: fix spelling

- explorer/src/components/account/TokenAccountSection.tsx
Token list now features wormhole bridge contract metadata. 
Support wormhole metadata. Extract address if only etherscan link is provided.
> explorer: display wormhole bridge details

- sdk/src/secp256k1_instruction.rs
- sdk/src/timing.rs
Integer arithmetic in sdk modules
Switch to saturating math
Toward #15368
> Sdk: remove integer arithmetic

- sdk/program/src/borsh.rs
- sdk/program/src/entrypoint.rs
- sdk/program/src/entrypoint_deprecated.rs
- sdk/program/src/epoch_schedule.rs
- sdk/program/src/fee_calculator.rs
- sdk/program/src/instruction.rs
- sdk/program/src/lib.rs
- sdk/program/src/message.rs
- sdk/program/src/native_token.rs
- sdk/program/src/program_error.rs
- sdk/program/src/pubkey.rs
- sdk/program/src/rent.rs
- sdk/program/src/serialize_utils.rs
- sdk/program/src/short_vec.rs
- sdk/program/src/slot_history.rs
- sdk/program/src/sysvar/instructions.rs
- sdk/program/src/sysvar/recent_blockhashes.rs
Integer arithmetic in solana-program crate
start migrating to checked/saturating integer math
> sdk/program: start removing integer arithmetic

- remote-wallet/src/ledger.rs
There is a test in the Ledger app repo that requires blind signing to be enabled. It's like number 40 of 50 tests.  I _never_ remember to re-enable blind signing between loading a new build and slogging through the test suite.  Ideally we'd query the devices settings and complain if they're incorrect at the start of tests, but the remote-wallet crate doesn't provide access to them :confused: 
Expose Ledger app settings from remote-wallet crate
> remote-wallet: Expose Ledger app settings

- cli/src/cluster_query.rs
Instead, use DEFAULT_MS_PER_SLOT to estimate epoch duration/elapsed
Fixes #15973
> solana epoch-info: avoid a panic when validator doesn't have performance samples

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
ConfirmedBlock types do not have blockTime, which would be helpful now that these are available. 
Add blockTime to ConfirmedBlock.
> feat: add support for blockTime on confirmed blocks

- sdk/src/account.rs
Found some code that isn't used anymore and is difficult to support.
Removing it.
Fixes #
> remove old Account<->AccountInfo code

- cli-output/src/cli_output.rs
- cli/src/program.rs
CLI cleanup feedback
Cleanup
Fixes #
> cli cleanup

- Cargo.lock
- cli/Cargo.toml
- client/Cargo.toml
- core/Cargo.toml
- crate-features/Cargo.toml
- download-utils/Cargo.toml
- install/Cargo.toml
- metrics/Cargo.toml
- notifier/Cargo.toml
- programs/bpf/Cargo.lock
- ramp-tps/Cargo.toml
- stake-o-matic/Cargo.toml
`reqwest 0.11.2` gets us more on `tokio 1`
> Update to reqwest 0.11.2

- programs/bpf_loader/src/lib.rs
> account data.fill replacement

- core/src/rpc.rs
https://github.com/solana-labs/solana/pull/16038 cherry-picked for CI expediency
> v1.5: Make getStakeActivation response consistent for undelegated accounts

- explorer/.prettierignore
- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/block/BlockRewardsCard.tsx
- explorer/src/components/instruction/vote/VoteDetailsCard.tsx
- explorer/src/providers/transactions/index.tsx
- Vote details row is not keyed
- Confirmation status can be undefined
- Rewards may be undefined
Fixes #
> explorer: minor cleanup and fixes

- perf/src/cuda_runtime.rs
- perf/src/lib.rs
- perf/src/recycler.rs
- perf/src/sigverify.rs
- sdk/program/src/message.rs
Integer arithmetic in perf crate
Use saturating/checked math instead
> perf: use saturating/checked integer arithmetic

- metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
New poh metrics added but not on the dashboard.
Update dashboard with new metrics.
Fixes #
> Update dashboard with new poh metrics

- net/scripts/install-certbot.sh
Snap is the worst
Use apt
Fixes #
> use certbot from apt not snap

- explorer/package-lock.json
- explorer/src/providers/mints/token-registry.tsx
Cluster slug of "custom" is failing when used with the token-list library.
Prevent using custom cluster slug with token registry.
> explorer: token registry avoids custom slug

- core/src/poh_service.rs
now that we do record from poh, we need to track the time spent in record.
track the time.
Fixes #
> poh record metrics

- docs/src/wallet-guide/apps.md
Exodus is not included as a mobile Solana wallet
Adding Exodus as an option
> Add Exodus as Solana Mobile app option

- runtime/src/accounts_db.rs
There can be more than 5 stores in test_account_grow
Up limit to 7
Fixes #
> Up store limit for test_account_grow

- clap-utils/src/keypair.rs
`clap-utils` can only resolve a `NullSigner` in sign-only mode.  `NullSigner`s can also be useful in situations where an arg can have mixed use, such as specifying either an SPL Token ATA or auxiliary account
Adds `signer_from_path_allow_null` variants that always return a `NullSigner` when a pubkey is specified in a signer role  and no matching signatures are passed.
> clap-utils: Allow `NullSigner`s outside sign-only mode

- account-decoder/src/parse_sysvar.rs
- programs/bpf_loader/src/lib.rs
- programs/stake/src/stake_instruction.rs
- programs/vote/src/vote_instruction.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/system_instruction_processor.rs
- sdk/benches/slot_hashes.rs
- sdk/benches/slot_history.rs
- sdk/program/src/clock.rs
- sdk/src/account.rs
- sdk/src/keyed_account.rs
- sdk/src/native_loader.rs
- sdk/src/recent_blockhashes_account.rs
Another cleaning is needed for the sysvar rent change....
There should be no functional change.
Simplify code before rent collection for sysvars.
Fixes #
> Simplify account.rent_epoch handling for sysvar rent

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/test/connection.test.ts
- Intermittent timeouts on the https test
- run-s is being loaded from transitive dependencies
> chore: modify https test and add run-all dep

- explorer/.slugignore
Try to fix slug build of explorer
> fix: test heroku slugignore for explorer

- perf/src/sigverify.rs
- sdk/program/src/short_vec.rs
> Shortu16 refactor 1.6

- core/src/replay_stage.rs
Printing about skipping leader slot due to no vote happens even when the node is not supposed to be leader and the vote picks up the unsigned vote signature.
Move the print and pick the signature after the vote is signed.
Fixes #
> Move skipping leader slot print and vote check

- client/src/blockhash_query.rs
- client/src/client_error.rs
- client/src/http_sender.rs
- client/src/mock_sender.rs
- client/src/nonce_utils.rs
- client/src/perf_utils.rs
- client/src/pubsub_client.rs
- client/src/rpc_cache.rs
- client/src/rpc_client.rs
- client/src/rpc_config.rs
- client/src/rpc_custom_error.rs
- client/src/rpc_request.rs
- client/src/rpc_response.rs
- client/src/thin_client.rs
Continue to the work of gradually switching the codebase over to the one `use` to rule them all style
> client/: Switch to a single `use`

- web3.js/package.json
- web3.js/scripts/flowgen.sh
Generated `module.flow.js` file from `flowgen` is lacking a module declaration and the exports are invalid
- Rewrite `module.flow.js` with fixed exports and an added module declaration
Fixes #
> fix: post process generated flow definition

- sdk/bpf/scripts/install.sh
This reverts commit cc7342a8ef719cbc1d44b37b8bcd8d6296e46598.
CC @jstarry 
Fixes #
> Revert bad backport: "Print the rust version when building bpf programs (#16181) (#16182)"

- program-test/src/lib.rs
ProgramTest does not handle `ProgramError` conversion the same way the runtime does
Change it to convert the `ProgramError` through a u64 like the runtime does when returning from BPF programs
Fixes #
> Align ProcessInstruction error handling

- web3.js/src/connection.ts
maybe, my code read is right as written in the new comment?
> Add documentation for reasons of non-obvious disableCache

- SECURITY.md
No scoping guidance for bug bounty program in security policy
Steal the one from our old H1 campaign
> security policy: Add out-of-scope section

- web3.js/src/connection.ts
- web3.js/src/instruction.ts
- web3.js/src/message.ts
- web3.js/src/secp256k1-program.ts
- web3.js/src/stake-program.ts
- web3.js/src/system-program.ts
- web3.js/src/transaction.ts
- web3.js/src/validator-info.ts
web3 docs haven't been fully migrated to typedoc yet
> chore: update doc comments

- runtime/src/message_processor.rs
data copies can be expensive
get rid of one
Fixes #
> get rid of unnecessary data copy

- core/src/rpc.rs
- ledger/src/blockstore.rs
`getConfirmedTransaction` may return the wrong slot if the transaction landed in multiple slots:
https://explorer.solana.com/tx/4ZmX7i82o25rq8p4Yhqqhak1GXe11gPeyQfJKrwcsETKrUxbMChTy1hTp8KXTxywd8RfQc1V6vgiLx9YZhCfK3as
was finalized in 71643755, but `getConfirmedTransaction` incorrectly reports 71643744
- Fix lazy test so that it examines real slot/root/signature scenarios
- Use AncestorIterator in blockstore to ensure transaction data is only from rooted or confirmed blocks
- Update rpc
> Rpc: fix getConfirmedTransaction slot

- core/src/cluster_slot_state_verifier.rs
- core/src/heaviest_subtree_fork_choice.rs
- core/src/replay_stage.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
Logging useful for tracking state verifier for dup, dead,confirmed, etc. slots is missing
Add such logging
Fixes #
> Add cluster state verifier logging

- validator/src/main.rs
`solana-validator exit` and `solana-validator wait-for-restart-window` now:
1. Indicate how far away (in slots) the next restart window is.  For mainnet-beta nodes with 1% of stake or more, sometimes a 10 minute restart window can be hours or more away
2. If there is no restart window available, error immediately so the operator can select a smaller restart window or just restart anyway
> validator: wait-for-restart-window now indicates how far away the next restart window is
