- banks-client/Cargo.toml
- banks-interface/Cargo.toml
- banks-server/Cargo.toml
- core/Cargo.toml
- faucet/Cargo.toml
- ledger-tool/Cargo.toml
- ledger/Cargo.toml
- net-utils/Cargo.toml
- program-test/Cargo.toml
version="1" seems to be more idiomatic in the tokio subcommunity
> Adjust tokio version to just "1"

- docs/src/running-validator/validator-reqs.md
Prospective validators think we have a minimum SOL requirement
Document the SOL needed to setup and operate a validator
> docs: Add validator SOL reqs

- ci/test-checks.sh
- ci/test-stable.sh
- programs/bpf/Cargo.lock
- programs/bpf/build.rs
- programs/bpf/rust/sysvar/Cargo.toml
- programs/bpf/rust/sysvar/src/lib.rs
- programs/bpf/rust/sysvar/tests/lib.rs
- programs/bpf/tests/programs.rs
- runtime/src/loader_utils.rs
program-test is not tested well for BPF programs and some runtime mechanism aren't tested at all via program-test
Start adding some tests, starting with sysvars and some sanity
Fixes #
> Add program-test tests to bpf programs

- docs/src/running-validator/validator-reqs.md
:robot:'s too fast
Clarify that validator SOL requirements only apply when participating in consensus
> docs: Validator SOL reqs followup

- explorer/src/pages/ClusterStatsPage.tsx
Active stake was previously being pulled from stake history, which is an epoch behind.
Use the existing getVoteAccounts call to sum active stake correctly.
> Explorer: active stake is an epoch off, use getVoteAccounts to sum

- validator/src/main.rs
Fix up some formatting that's too much for `cargo fmt` to handle
> validator: Fix up App formatting

- faucet/src/bin/faucet.rs
- faucet/src/faucet.rs
https://github.com/solana-labs/solana/pull/16487 backport
> v1.6: Add address_cache and exclude loopback from ip limit

- SECURITY.md
Our payment policy for bug bounty rewards is not clearly documented
Add it
> Clarify bug bounty payment policy

- validator/src/main.rs
Don't assume that `solana-validator authorized-voter add ...` is run from the same working directory as the validator process it's talking to
> validator: canonicalize authorized voter filepath

- programs/bpf/tests/programs.rs
- sdk/bpf/c/bpf.mk
- sdk/bpf/scripts/install.sh
- sdk/cargo-build-bpf/src/main.rs
> Add llvm feature option to compile for Solana BPF target

- programs/bpf/c/src/noop++/noop++.cc
- programs/bpf/c/src/noop/noop.c
- programs/bpf/tests/programs.rs
Track the instruction counts of more BPF programs
Fixes #
> Expand and update instruction count tests

- programs/bpf_loader/src/syscalls.rs
> fix cross-merge

- validator/src/bin/solana-test-validator.rs
> solana-test-validator: Add --faucet-port option

- docs/src/running-validator/validator-start.md
Old hostname no longer works for gossip
Corrects hostname to devnet entrypoint
> Correct gossip hostname

- README.md
`README.me` used the old logo.
Updates to new logo.
> Add new logo

- Cargo.lock
- cli/src/cli.rs
- cli/tests/nonce.rs
- cli/tests/stake.rs
- cli/tests/transfer.rs
- cli/tests/vote.rs
- client/Cargo.toml
- client/src/client_error.rs
- faucet/Cargo.toml
- faucet/src/bin/faucet.rs
- faucet/src/faucet.rs
- faucet/src/faucet_mock.rs
- programs/bpf/Cargo.lock
A couple backports to sync up devnet and testnet faucets, pre https://github.com/solana-labs/solana/pull/16563
> v1.5: faucet backports

- account-decoder/src/parse_nonce.rs
When requesting parsed account info for an allocated system account, the RPC response always indicates that the account is an uninitialized nonce regardless of size as long as allocated data is greater than zero
Only parse initialized nonce accounts
Fixes #16569
> Don't parse uninitialized system/nonce accounts

- runtime/src/bank.rs
- sdk/src/feature_set.rs
Omitted feature gate
Reinstate it
> Feature-gate hash-based duplicate transaction check

- core/benches/shredder.rs
- ledger/src/shred.rs
No functionality changes from this commit
The shreds module has some intricacies that weren't immediately obvious; hopefully the additions from this commit make things more clear for anyone trying to figure these out from a clean slate.
- Add some additional explanation / documentation of shreds at the top
- Rename several variables with more meaningful (in my opinion :) ) names
- Some misc. comment cleanup
> Document shreds

- runtime/src/accounts_index.rs
assert text wasn't helpful. And, I didn't know you could match tests on substrings of assert text.
parameterize assert text
Fixes #
> improve failing assert

- cli-output/src/cli_output.rs
https://github.com/solana-labs/solana/pull/16635 redefined the "credits" field of what `solana validators --output=json` outputs.  Restore the original meaning, and add a new "epochCredits" field to the output for credits earned in the current epoch
> `solana validators`: Restore the meaning of "credits" in the JSON output

- perf/src/cuda_runtime.rs
- perf/src/lib.rs
- perf/src/recycler.rs
- perf/src/sigverify.rs
- sdk/program/src/message.rs
Manual backport to v1.5 of #16042
> perf: use saturating/checked integer arithmetic (bp #16042)

- scripts/build-downstream-projects.sh
SPL has moved beyond 1.5
Pin its downstream build to something 1.5 can handle
> Pin SPL downstream build to 589da55

- docs/src/developing/runtime-facilities/programs.md
- docs/src/integrations/exchange.md
* Address verification section of the integration guide is light on details and doesn't mention footguns
* Native program descriptions lack details
* Expand
* Expand
> Expand a couple docs sections

- core/src/banking_stage.rs
- perf/src/sigverify.rs
- sdk/program/src/short_vec.rs
> Deny shortu16 alias - 1.5

- core/src/rpc.rs
`getVoteAccounts` currently returns up to 64 epochs worth of `epoch_credits` for each validator.  This is completely unnecessary and wasteful.   Instead return up to 5 epochs worth, which is still plenty of history. 
The limit is not documented in the JSON RPC API
> getVoteAccounts: Limit the length of the `epoch_credits` array

- program-test/src/lib.rs
A test does not have the ability to choose to execute a bpf program with jit or interpreted.  This can be useful for debugging, testing that the two are equivalent, or recreating an issue seen on a live cluster where jit/no jis is a question.
Expose an API to allow the test to select jit or not
Fixes #
> Selectable jit in program-test

- docs/src/developing/on-chain-programs/overview.md
Float docs are outdated and sparse
Add more info and a comparison of instruction counts between integer and float operations
Fixes #
> Update float docs

- runtime/src/accounts_index.rs
> increase rolling slot width to 4M

- runtime/src/accounts_db.rs
during do_shrink_slot_stores, we make unnecessary copies of many fields including an account and its data. This work is a precursor to creating a ReadableAccount trait impl for StoredAccountMeta such that we never have to allocate a new account structure and a new data: Arc<Vec<u8>> when we have a StoredAccountMeta instance.
eliminate completely unnecessary copies of accounts and data. Delay account creation during slot shrink operation.
Fixes #
> simplify do_shrink_slot_stores, delay/reduce account clone

- core/src/cluster_info.rs
Three strikes at https://buildkite.com/solana-labs/solana/builds/44621#d3342af0-97ec-4f27-82d0-15694c8b013a
cc: @behzadnouri
> Ignore flaky test_pull_request_time_pruning

- core/src/rpc.rs
> verify_pubkey() now takes a ref

- runtime/src/accounts_db.rs
- runtime/src/message_processor.rs
- sdk/src/nonce_keyed_account.rs
Problem
.lamports = X -> .set_lamports(X)
Fixes #
> Set lamports

- runtime/src/read_only_accounts_cache.rs
Several problems with read only cache lru cleaning.
Move lru cleaning to a background thread.
Fixes #
> clean read_only_cache in the bg

- ledger-tool/src/main.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/rent_collector.rs
- runtime/src/stakes.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/keyed_account.rs
- sdk/src/nonce_keyed_account.rs
lamports -> lamports()
Fixes #
> Readonlyaccounts

- programs/bpf_loader/src/serialization.rs
- sdk/src/account.rs
Problem
.owner.as_mut().copy_from_slice(slice)  -> .copy_into_owner_from_slice(slice)
Fixes #
> AccountSharedData.copy_into_owner_from_slice

- runtime/src/accounts.rs
Problem
.owner = X -> .set_owner(X)
Fixes #
> account.owner = X -> account.set_owner(X)

- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/serde_snapshot/tests.rs
Problem
.owner -> .owner()
Fixes #
> .owner -> .owner()

- runtime/src/read_only_accounts_cache.rs
If we track removes during read only cache remove, then we will save unnecessary lru purges.
Track remove size during remove.
Fixes #
> read_only_cache remove updates cache size

- docs/src/developing/on-chain-programs/developing-rust.md
Nit-picky text-wrapping change for recent punctuation fix.
> Restore text wrapping

- core/src/poh_service.rs
fyi @carllin and @jeffwashington
> Disable flaky test_poh_service

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
Problem
.owner = X -> .set_owner(X)
Fixes #
> .owner = X -> .set_owner(X)

- runtime/src/accounts_db.rs
This code is about to be refactored. This duplicate lookup of len is complicated.
Calculate it once and use local.
Fixes #
> refactor complicated len calculation

- runtime/src/bank.rs
Unchecked math in Bank::withdraw
check it
> runtime: checked math for Bank::withdraw

- programs/budget/src/budget_processor.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- sdk/program/src/instruction.rs
- sdk/program/src/lamports.rs
- sdk/program/src/lib.rs
- sdk/src/account.rs
Problem
lamports += X -> lamports.checked_add_lamports(X)
lamports -= X -> lamports.checked_sub_lamports(X)
Fixes #
> WritableAccount.add/subtract_lamports

- programs/bpf_loader/src/lib.rs
- runtime/src/bank.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/nonce_keyed_account.rs
Problem
.owner -> .owner()
Fixes #
> owner -> owner()

- runtime/src/accounts_db.rs
Latest occurrence: https://buildkite.com/solana-labs/solana/builds/44931#32b57115-5100-4c93-b018-c82421a9c853
> Ignore racy test_load_account_and_purge_race_without_retry

- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/tokens.tsx
- explorer/src/providers/block.tsx
- explorer/src/providers/mints/largest.tsx
- explorer/src/providers/richList.tsx
- explorer/src/providers/supply.tsx
Explorer is using deprecated commitment variants.
Update them
> Explorer: update deprecated commitments

- cli-output/src/cli_output.rs
New output from devnet.  Look at the "Last Vote" and "Root Slot" column for the changes:
```
$ solana validators -ud --sort root --reverse
Identity                                      Vote Account                            Commission  Last Vote        Root Slot      Epoch Credits Version  Active Stake
  dv1LfzJvDF7S1fBKpFgKoKXK5yoSosmkAdfbxBo1GqJ   5MMCR4NbTZqjthjLGywmeT66iwE9J9f7kjtxzJjwfUx2    0%   51647630        51647599              239632   1.6.6  77917479.472601518 SOL (100.00%)
  wWf94sVnaXHzBYrePsRUyesq6ofndocfBH6EmzdgKMS   AKoVXpZmi8wSz3sGvCYEygbpdHvSRysWsh36b97iPvKh  100%   51647628 ( -2)  51647597 ( -2)        239633  1.5.18  -
⚠️ BmSmUWB9gJkoePfnmnKGtcG9MXnW1VKDvvTRman8F1Te  BGMDEqc5TZ3xkSKWeGtiAHPNkbc4GeBqnQdNJry2xGth    0%   51517188 (xxx)  51517157 (xxx)        109190 …
```
> Show last vote/root behind distance in `solana validators` output

- explorer/README.md
> Add new logo to Explorer repo

- core/src/cluster_info.rs
- core/src/retransmit_stage.rs
- sdk/src/feature_set.rs
Redundant code and runtime overhead since the features have been long activated. 
Removed the runtime features.
> removes old runtime feature gates

- docs/src/developing/runtime-facilities/programs.md
Native-program docs refer to BPF deprecated loader
Update to upgradeable loader
> Update bpf loader info on native-programs docs

- cli/src/cluster_query.rs
`solana block-production` reports broken numbers when run against a node that booted from a snapshot.  But the SlotHistory sysvar maintains the block production history for the last two epoch with perfect accuracy, so there's no need to use the spotty `getBlocks` RPC method when the requested range is within the data that SlotHistory holds
> cli: block-production subcommand now uses SlotHistory sysvar when possible

- ledger-tool/src/main.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/message_processor.rs
- runtime/src/rent_collector.rs
- sdk/src/keyed_account.rs
Problem
use .executable()
Fixes #
> AccountSharedData.executable()

- runtime/src/accounts_index.rs
RootsTracker was designed to replace HashSet. HashSet.remove() returns true if the item was removed.
This is needed for future changes that are coming.
RootsTracker.remove() returns true if the item was removed.
Fixes #
> rootstracker.remove returns previous state

- ledger-tool/src/main.rs
Intermittent lifetime issue with compiler likely introduced with owner() refactoring.
*
Fixes #
> owner() lifetime issue

- ledger-tool/src/main.rs
- runtime/src/accounts.rs
- runtime/src/message_processor.rs
- runtime/src/rent_collector.rs
- sdk/src/keyed_account.rs
Problem
rent_epoch uses accessors now
Fixes #
> private AccountSharedData.rent_epoch

- docs/src/pages/index.js
> Add banner to hackathon page

- genesis/src/main.rs
- ledger-tool/src/main.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
Problem
lamports -> lamports()
Fixes #
> lamports -> lamports()

- programs/stake/src/config.rs
- runtime/src/message_processor.rs
Problem
lamports = -> set_lamports()
Fixes #
> set_lamports()

- sdk/program/src/pubkey.rs
https://github.com/solana-labs/solana/pull/16862, but for the Rust SDK
Factor out pubkey on-curve test to a helper
> SDK: Factor out pubkey on-curve test to a helper

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/instruction/BonfidaBotDetails.tsx
- explorer/src/components/instruction/bonfida-bot/CancelOrderDetails.tsx
- explorer/src/components/instruction/bonfida-bot/CollectFeesDetails.tsx
- explorer/src/components/instruction/bonfida-bot/CreateBotDetails.tsx
- explorer/src/components/instruction/bonfida-bot/CreateOrderDetails.tsx
- explorer/src/components/instruction/bonfida-bot/DepositDetails.tsx
- explorer/src/components/instruction/bonfida-bot/InitializeBotDetails.tsx
- explorer/src/components/instruction/bonfida-bot/RedeemDetails.tsx
- explorer/src/components/instruction/bonfida-bot/SettleFundsDetails.tsx
- explorer/src/components/instruction/bonfida-bot/types.ts
- explorer/src/components/transaction/InstructionsSection.tsx
- explorer/src/utils/instruction.ts
> explorer: add Bonfida Bots instructions

- runtime/src/accounts.rs
Working towards abstracting AccountSharedData to other implementations. Moving callers to use Readable/WritableAccount methods. We recently added checked_add_lamports and checked_sub_lamports to WritableAccount.
Modify code to return Results and use checked_sub_lamports.
Fixes #
> checked_sub_lamports

- runtime/src/accounts_db.rs
Remove copies of account and its data during a few code paths.
Fixes #
> Readable account trait for stored account meta

- web3.js/src/connection.ts
Slot updates are useful for tracking the current leader but the pubsub api hasn't been added to web3 yet
- Add the slot updates api
Fixes #
> feat: add support for slot update pubsub subscriptions

- docs/src/cluster/rpc-endpoints.md
Docs nit, remove errant backslash
> Remove errant backslash

- runtime/src/bank.rs
- runtime/src/message_processor.rs
lamports -> ReadableAccount
Fixes #
> tests: lamports -> ReadableAccount

- runtime/src/bank.rs
Bank not documented that well.
Add some more docs
Fixes #
> More docs for bank.rs

- runtime/src/accounts_db.rs
Reverts solana-labs/solana#17005
> Revert "reclaim unrefs accounts from index (backport #16838)"

- web3.js/.flowconfig
- web3.js/package-lock.json
- web3.js/package.json
- web3.js/rollup.config.js
- web3.js/src/connection.ts
`flowgen` tool produced invalid flow type definition and we had no way to detect that.
- Fix flow type issue by removing `Exclude` usage
- Add flow type checker to build step
- Fix audit issues
- Update package-lock.json version
- Fix rollup replace plugin warnings
Fixes #
> fix: fix flow type declaration

- core/src/validator.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
> validator: Add --tower argument to specify where tower files are persisted

- client/src/http_sender.rs
RpcClient now plays nice with api.mainnet-beta.solana.com and doesn't retry sooner than when asked
> RpcClient now respects the retry-after server response header when getting rate limited

- cli-output/src/cli_output.rs
- cli/src/cluster_query.rs
`solana gossip` can't `--output json`
print gossip nodes via `cli-output` crate
> CLI: Print gossip nodes with `cli-output` crate

- ledger-tool/src/main.rs
- runtime/src/bank.rs
This is mainly debugging.
CC: @t-nelson 
Fixes #
> Dump rent_collector/inflation with ledger-tool cap

- runtime/src/accounts_index.rs
> add metric for assumption

- runtime/src/accounts_db.rs
I was thinking I could get rid of a slower btree and replace it with something faster.
Comment why we need a btree.
Fixes #
> add comment

- core/src/rpc.rs
- docs/src/developing/clients/jsonrpc-api.md
> getBlockProduction RPC method now correctly reports block production

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/instruction/bonfida-bot/types.ts
Bonfida pulled their old dependency :/
Fixes #
> explorer: Fix bonfida dependency

- runtime/src/bank.rs
> Add comment for another unspoken eager collection subtlety

- runtime/src/accounts_index.rs
As part of [secondary index refactoring](https://github.com/solana-labs/solana/pull/17108), it looks like this test isn't generic enough.
Make it more generic.
Fixes #
> fix secondary index test

- docs/src/wallet-guide/web-wallets.md
Update web-wallet.md to add phantom with fixed link
Fixes #
> Update web-wallet.md to add phantom with fixed link

- docs/src/cluster/rpc-endpoints.md
https://devnet.solana.com change to https://api.devnet.solana.com
https://testnet.solana.com change to https://api.testnet.solana.com
"current" change to "concurrent"
> Update devnet and testnet endpoints

- docs/package-lock.json
- docs/src/pages/index.js
> docs: fix fixed layout

- docs/src/pages/index.js
~~Docs hackathon banner wasn't backported, so we'll lose it next release~~
Ok so it was, just totally differently than on master, so my backport broke in a strange way :shrug: 
Backport it
> docs: add hackathon banner consistently with master

- docs/sidebars.js
- docs/src/developing/test-validator.md
No docs for `solana-test-validator`
Add some
> docs: Add docs for `solana-test-validator`

- docs/src/clusters.md
> fix-endpoints

- validator/src/bin/solana-test-validator.rs
`solana-test-validator` uses the cli-config wallet as the mint address by default, but if it doesn't exist creates an ephemeral keypair for the mint. In the latter case, the other CLI tools aren't funded unless the user knows about `solana airdrop`
Add a hint
> test-validator: Hint at airdrop when wallet is unavailable

- programs/bpf/tests/programs.rs
> Fix deprecated trait object without an explicit dyn warning

- runtime/src/accounts_index.rs
Validator startup time is commonly experienced. Generating the index is a large part of that time.
Work is ongoing (#17194) to improve our initial index creation time and ultimately our ability to handle 1B accounts.
Fixes #
> minor refactoring of AccountsIndex in preparation of bigger things

- ledger/src/blockstore_processor.rs
startup time is a topic and issue lately.
add metrics on initial ledger processing
Fixes #
> add data point for ledger processing

- ledger/src/blockstore.rs
- ledger/src/shred.rs
#16602 introduced a change where shreds would have zero-padding stripped off for insertion into the blockstore, and then re-appended upon fetch from the blockstore. This introduced a compatibility break with v1.6 since v1.6 doesn't have the logic to "extend" shreds. This is problematic for a scenario where a node is running the tip of master (or really, any state of master at/after the mentioned PR) and inserts shreds into the blockstore, and then reverts to v1.6 and attempts to retrieve/operate on those shreds.
Add logic to ensure shred payloads are a consistent length
- For shreds that were inserted with the zero-padding (v1.6), this should be a no-op
- For shreds that were inserted without zero-padding (latest on master), this will create compatibility for v1.6
Fixes #17136
> Zero pad data shreds on fetch from blockstore

- docs/src/developing/clients/jsonrpc-api.md
Response fields list is missing a bullet for the data field
Added the missing bullet for the data field
> fixed getProgramAccounts fields list

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
Validator startup time is commonly experienced. Generating the index is a large part of that time.
Hold the accounts index lock while many inserts are done.
Fixes #
> hold lock to speed up insert

- runtime/src/bank.rs
- runtime/src/serde_snapshot/tests.rs
> fix comment

- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/pages/ClusterStatsPage.tsx
- explorer/src/scss/_solana.scss
- explorer/src/utils/coingecko.tsx
Tokens don't currently list a market price.
Now that token-list has CoingeckoIds, we can query for price data.
> Explorer: add token market prices from Coingecko

- runtime/src/bank.rs
- runtime/src/rent_collector.rs
just add some more assert!()s and comment for upcoming rent handling simplification.
> Minor test cleanup and comments

- runtime/src/bank.rs
validator startup time is painful - especially as # accounts grows. There will soon be an issue filed for this.
add metrics for verify_snapshot_bank to track improvements.
Fixes #
> datapoint for verify_snapshot_bank

- runtime/src/accounts_db.rs
Generate_index has some outdated comments and data structures. We don't need old write version entries during generate_index.
Simplify, remove old comments.
Fixes #
> simplify generate_index

- runtime/src/accounts_index.rs
Validator startup time is commonly experienced. Generating the index is a large part of that time.
In general, there is contention on account index updates.
Simplify accounts_index.update for clarity, reduced iterations, collapse redundant operations.
Fixes #
> rework slot list update

- core/src/cluster_info.rs
- core/src/cluster_info_metrics.rs
need to track how many other (staked) nodes each node observes in its gossip table.
added metrics fro number of (staked) nodes in gossip
> adds gossip metrics for number of staked nodes

- docs/src/offline-signing.md
Transactions expire after 150 recent blockhashes which is ~1min15s assuming 500ms slots and no skipped slots
Fixes #
> docs: Update transaction expiration time

- scripts/build-downstream-projects.sh
Serum was temporary disabled to get around build problems.
restore Serum in CI downstream job script
Fixes #17321
> restore Serum in CI downstream job

- sdk/src/feature_set.rs
An empty feature that we can start plumbing new stake program features with
> Add stake_program_v4 feature

- clap-utils/src/keypair.rs
`SignerSource` in `clap-utils` can't resolve Windows paths
* Burn a day on getting a reliable Windows build env up
* Fix it
fixes #17252
> clap-utils: Fix signer resolution on Windows

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
unnecessary flatten in hash calculation store scan
remove flatten
Fixes #
> remove flatten in storage scan

- runtime/src/accounts_index.rs
Add type to simplify code and in preparation of 2 other changes that use this type.
Fixes #
> add AccountsIndex AccountMapsReadLock type

- core/src/cluster_info.rs
push_epoch_slots is unlocking and locking again gossip when iterating
over epoch slot indices which is wasteful:
https://github.com/solana-labs/solana/blob/0486df02b/core/src/cluster_info.rs#L915-L929
* lock gossip only once for the entire iteration.
* also, removed redundant slots sort.
> locks gossip only once in push_epoch_slots

- core/src/crds.rs
Crds::get_votes is scanning over all votes in the crds table only to
return those inserted since the given cursor:
https://github.com/solana-labs/solana/blob/2ae57c172/core/src/crds.rs#L250-L266
Having votes indexed by insert order avoids the table scan and will be
more efficient.
* Index crds votes by insert order.
> indexes crds votes by insert order

- runtime/src/accounts_db.rs
calculating hash is taking a while with 360M accounts.
log how long it takes to capture all the pubkeys
Fixes #
> add metric for collect

- docs/src/offline-signing.md
> docs: budget program is gone, link to SPL Token multisig

- runtime/src/ancestors.rs
migrating ancestors to be a hashset instead of hashmap. API is already changed.
move Ancestors.large_range_slots to be HashSet
Fixes #
> ancestors.large_range_slots becomes HashSet

- runtime/src/ancestors.rs
https://github.com/solana-labs/solana/pull/17447 missed a line and doesn't build
Compile
Fixes #
> fixup! Ancestors to HashSet: From(Vec) (#17447)

- web3.js/test/connection.test.ts
A recent change wasn't rebased on latest master with updated formatter
> chore: fix formatting

- docs/src/running-validator/validator-reqs.md
No RPC Node specific HW guidance
Add some
> docs: Add RPC node HW recommendations

- scripts/sed-i-all-rs-files-for-rust-analyzer.sh
> Add a hacky shell for fun code reading

- docs/src/developing/programming-model/calling-between-programs.md
There were some questions about using `create_program_address`, and typically `find_program_address` is a part of that development flow, but the docs don't have any mention or examples using `find_program_address`.
Add the `find_program_address` implementation and a similar escrow example using `find_program_address` instead of `create_program_address`.
Fixes #
> docs: Add `find_program_address` and example

- runtime/src/accounts_db.rs
Lots of duplicated shrink code
Collapse down into 1 copy
Fixes #
> Remove copied shrink code

- docs/src/developing/on-chain-programs/overview.md
> Fix typo in docs

- runtime/src/accounts_db.rs
Move local out of loop for performance.
Fixes #
> hoist slot() call in accounts hash scan

- web3.js/src/connection.ts
- web3.js/src/util/url.ts
- web3.js/test/url.ts
- web3.js/test/websocket.test.ts
> feat(web3): add ability to pass different websocket endpoint #17387

- web3.js/README.md
Misleading instructions.
Removed broken link, updated instructions to get latest version for browser bundle.
2 pedantic changes.
Fixes #
> chore: update instructions for web3.js

- validator/src/bin/solana-test-validator.rs
Sometimes 1M localnet SOL worth of airdrops isn't enough
Add a flag
> test-validator: add an arg to control faucet genesis balance

- runtime/src/accounts_index.rs
RollingBitField will soon be the basis of Ancestors. Using this for Ancestors, which has different access patterns, has exposed some bugs and missing traits.
Improve RollingBitField.
Fixes #
> RollingBitField: bug fixes and add tests

- runtime/src/accounts_db.rs
Storages are likely to be changed soon.
Make some helper test methods for common test values to remove noise from more interesting PRs.
Fixes #
> refactor SnapshotStorage helpers to prepare for later changes

- programs/bpf/tests/programs.rs
- sdk/bpf/env.sh
- sdk/cargo-build-bpf/src/main.rs
> Add BPF rustc option to reduce the optimizations to safer level

- runtime/src/accounts_hash.rs
Superfluous type restriction leads to inflexibility when the types change (which they will).
get rid of unnecessary type.
Fixes #
> minor test code cleanup

- runtime/src/accounts_db.rs
hash data structures will likely soon change
rework construction for easier migration
Fixes #
> simplify test construction

- runtime/src/accounts_db.rs
no reason to ask storage for slot when we know it. getting slot is expensive.
remove the call.
Fixes #
> remove slot lookup

- programs/bpf_loader/src/lib.rs
- sdk/program/src/instruction.rs
- sdk/program/src/program_error.rs
- sdk/src/feature_set.rs
Missing `ProgramError` to `InstructionError` mappings
Add them back
Fixes #
> Add missing ProgramError to InstructionError mappings

- web3.js/src/connection.ts
Forced retrying on HTTP 429 (Too Many Requests) makes it hard to deal with a rate limiting RPC
Adds option to disable auto-retry on HTTP 429 (Too Many Requests)
> feat(web3.js): Add disableRetryOnRateLimit connection option

- core/src/progress_map.rs
- runtime/src/message_processor.rs
Hard to tell which program is taking the longest in the network.
Add per-program timings configurable with a validator flag.
Fixes #
> Per-program id timings

- runtime/src/bank.rs
> add data point for cap mismatch

- ledger/src/blockstore.rs
The logic to check if a slot had been cleaned up was repeated several times. Additionally, a first glance at the code may not have registered that `lowest_cleanup_slot` is a read lock
Combine repeated code into a function (no functional changes)
> Combine repeated logic for checking if slot has been cleaned up

- web3.js/src/connection.ts
No example for requesting a SOL airdrop
- Add example
Fixes https://github.com/solana-labs/solana-web3.js/issues/1044
> docs: add airdrop example

- runtime/src/accounts_hash.rs
With high bin counts, we appear to be spending lots of time finding a vector in a cumulative list
use slice.binary_search
Fixes #
> binary search in slices for hashing

- sdk/bpf/c/bpf.mk
When bpf-tools updates clang version, the generated dependencies files are becoming invalid and need to be rebuilt.
The current bps.mk file doesn't handle such situations.
The generated dependencies files made dependent on changes to bpf.mk and regenerated separately when necessary.
> Add separate rules to generate dependencies files for C BPF build

- web3.js/test/url.ts
Update devnet urls, in case users ever uncomment them. (Consider removing the comments, though)
> chore: update commented devnet urls

- core/src/progress_map.rs
- core/src/replay_stage.rs
> replay_stage.rs: Wrap long lines

- runtime/src/accounts_db.rs
This type will be used in more places later.
Make a type of specific generic.
Fixes #
> refactor: create type

- local-cluster/tests/local_cluster.rs
`test_optimistic_confirmation_violation_detection` is flaky
Disable test for now
@AshwinSekar, ignoring this test for now until your investigation is done, thanks!
Fixes #
> Ignore flaky test

- runtime/src/message_processor.rs
When Instruction account verification fails the runtime doesn't log what account failed, leaving the developer to guess
Report which account failed verification
Fixes #
> Log more info on runtime account verification errors

- system-test/automation_utils.sh
- system-test/restart-testcases/restart_gce.yml
- system-test/restart-testcases/restart_test_automation.sh
Simple test that restarts a 5 node network with equal stake and tries to confirm 5 transactions
Checking this in for ease of running in buildkite
Fixes #
> Restart test without supermajority

- gossip/src/crds.rs
Crds::find_old_labels can skip checking values timestamps if the
origin's contact info hasn't expired yet:
https://github.com/solana-labs/solana/blob/985280ec0/gossip/src/crds.rs#L394-L408
* short cut expiration check if origin's contact-info is still valid.
> short cuts expiration check if origin's contact-info is still valid

- runtime/src/accounts_index.rs
Panic #17756
no `unwrap()`
Fixes #17756
> Fix accounts index panic in purge_exact

- runtime/src/accounts_db.rs
Multiple usage patterns result in true, false, etc. in function calls.
Make a caller that will likely go through 2 changes shortly more explicit.
Fixes #
> name arguments to help with confusion

- Cargo.lock
- account-decoder/Cargo.toml
- accounts-cluster-bench/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- tokens/Cargo.toml
- transaction-status/Cargo.toml
Old version of spl-token caused build conflicts for devs.
Bump it
Fixes #17936
> Bump spl-token to v3.1.1

- runtime/src/accounts_background_service.rs
feedback from pr
fix it
Fixes #
> nit: rename measure

- runtime/src/serde_snapshot.rs
When loading from a snapshot, mem-mapping and creating appendvecs is done in serial right now.
Do it in parallel while nothing else is going on.
Fixes #
> parallel storage -> accounts folder

- runtime/src/accounts_db.rs
We are about to refactor generate_index to pipeline it with other startup tasks.
Refactor first half.
Fixes #
> refactor generate_index process_storage_slot

- metrics/src/metrics.rs
Metrics http client instantiation errors are unwrapped.
Log a warning instead
> metrics: Don't unwrap client instantiation errors

- validator/src/admin_rpc_service.rs
Scrub some commented-out debug code that doesn't belong
> Clean up remove_all_authorized_voters()

- runtime/src/accounts_index.rs
Create type for common complicated generic type that is also likely to change over time.
Fixes #
> introduce LockMapType for accounts_index

- sdk/cargo-build-bpf/src/main.rs
Users need to be able to pass additional command line options such as
-p that are not supported by 'cargo build-bpf' but are meaningful for
the 'cargo build' command.
This change allows cargo-build-bpf to pass all command line options specified after '--' option to 'cargo build'.
The relevant issue is #17849
> Make cargo-build-bpf pass additional options to cargo build command

- sdk/program/src/bpf_loader_upgradeable.rs
Loader instruction checker doesn't like empty slices
Make them friends
Fixes #
> fix loader instruction checker

- programs/bpf/rust/caller_access/src/lib.rs
- programs/bpf/rust/dup_accounts/src/lib.rs
- programs/bpf/rust/invoke_and_error/src/lib.rs
- programs/bpf/rust/invoke_and_ok/src/lib.rs
- programs/bpf/rust/invoke_and_return/src/lib.rs
> More nightly clippy fixes

- sdk/bpf/scripts/install.sh
- sdk/cargo-build-bpf/src/main.rs
Avoid including local paths in compiler generated ELF files
Fixes #17758
> Bump bpf-tools version to 1.11

- runtime/src/serde_snapshot.rs
Master CI is broken due to nightly clippy complaint on https://github.com/solana-labs/solana/pull/17987/files
cc @jeffwashington 
Fix suggestion
> Fix build: clippy lint

- core/src/rpc_health.rs
Backport of https://github.com/solana-labs/solana/pull/18098
> v1.6: Add logging when RpcHealthStatus::Unknown

- runtime/src/accounts_db.rs
generate_index slows us down at validator start.
Break up a complicated process in preparation for pipelining and optimizing.
Fixes #
> refactor generate_index_for_slot

- explorer/src/App.tsx
- explorer/src/scss/_solana-dark-overrides.scss
- explorer/src/scss/_solana-variables-dark.scss
> explorer: increase color contrast

- local-cluster/tests/local_cluster.rs
Reenabling the previously flaky test
Fixes #
> Enable previously flaky optimistic detection local cluster test

- docs/src/running-validator/validator-reqs.md
Validator networking requirements aren't clearly documented
Do so
> Docs val net reqs

- runtime/src/accounts_hash.rs
hash_total was double-counting some, resulting in incorrect stats.
don't double-count
Fixes #
> correctly calculate hash_total for hash/lamport calculation

- docs/src/developing/runtime-facilities/sysvars.md
Developers have to go looking to find out which sysvars support `get`
List them in the docs
Fixes #
> Update sysvar docs

- runtime/src/accounts_db.rs
Sort was reworked in latest hash calculation work.
plumb through metrics for sort of hash calculation
Fixes #
> capture sort time in hash calculation

- sdk/Cargo.toml
- sdk/README.md
- sdk/program/Cargo.toml
- sdk/program/README.md
Missing readmes in crates.io
Add readmes that point developers in the right direction
Fixes #
> Add sdk and program READMEs

- explorer/src/components/instruction/serum/types.ts
The Serum instruction lookup table needs instruction 14 and 15.
Add these instructions.
> Explorer: additional serum instructions

- runtime/src/accounts_index.rs
We copy account info unnecessarily through a few code paths of account info insert.
Rework code to preserve the already allocated data for re-use. This also allows us to switch to an iterator vs a vec and have less data that we have to collect into vectors during processing of many slots.
Fixes #
> remove unnecessary copies from accounts index code paths

- ci/env.sh
- ci/localnet-sanity.sh
- ci/order-crates-for-publishing.py
- ci/run-local.sh
- ci/test-downstream-builds.sh
- ci/test-stable.sh
- sdk/bpf/c/bpf.mk
No convenient way to run CI locally
Add an entry point script for running all tests and a few tweaks to push it along
> Add entrypoint to run CI locally

- Cargo.lock
- banks-client/Cargo.toml
- programs/bpf/Cargo.lock
- sdk/program/Cargo.toml
Prep for borsh bump in SPL programs
> Bump borsh from 0.8.1 to 0.9.0

- docs/src/wallet-guide/apps.md
I have added a quick infodump about Zelcore wallet supporting various features of the Solana ecosystem. I looked at previous commits and it seemed adding to the top of the file was the norm, but please feel free to move around if needed.
N/A
Initial addition of Zelcore supporting SOL assets
Fixes #
N/A
> Zelcore wallet support for SOL/SPLs info added

- runtime/src/accounts_index.rs
Pubkeys are unnecessarily copied in account index code path inside RwLock.
Avoid unnecessary copy.
Fixes #
> reduce pubkey copies on insert path

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
Startup time is slow. Account index generation is slow and single threaded. Account index is an area of much focus now and going forward towards 1B accounts.
Performance of btree degrades with # of entries. Reducing the # of entries/btree improves performance. Btree insertion is also single-threaded and exclusive, so inserting into the btree can be very expensive. Creating many individual btrees can allow insertions to be sorted and batch inserted into an individual btree in a thread while other items can be inserted in other bins simultaneously.
Lock contention can be reduced, startup time can drastically improve, lookup time can improve by 2x.
Internally, rework the account index to be:
```
Vec<RwLock<btree>>
```
instead of:
```
RwLock<btree>
```
A pubkey's value is used to determine …
> bin accounts index

- transaction-status/src/parse_instruction.rs
`solana-transaction-status` assumes memo instructions succeeded when they may not have
Add error handling
> tx-status: Don't assume a memo instruction succeeded

- runtime/src/accounts_db.rs
Missing test coverage for unrooted slot preventing clean  of zero lamport account
Add such a test
Fixes #
> Test coverage for unrooted slots and cleaning zero lamport accounts

- core/src/consensus.rs
- core/src/replay_stage.rs
`replay_blockstore_components()` has some duplicate code, and can leverage functionality from `VoteSimulator`
Fixes #
> Cleanup ReplayStage test replay_blockstore_components()

- gossip/src/cluster_info.rs
- gossip/src/cluster_info_metrics.rs
- gossip/src/crds.rs
reports of this error being possibly spammy:
https://discord.com/channels/428295358100013066/689412830075551748/859441080054710293
The commit changes the log level to debug.
Additionally adding a new metric to understand the frequency of this error.
> debug logs when crds table trim failed

- ledger/src/blockstore.rs
Iterating of chunks is being used but the code is doing the set_roots for the whole vector repeatedly.
set_roots per chunks.
Fixes #
> Fixed an issue doing the set_roots repeatedly for the same set.

- docs/src/developing/clients/jsonrpc-api.md
The slotsUpdates subscription appears in code, but is not documented.
Add docs
> Document slotsUpdates

- runtime/src/accounts_db.rs
We now bin accounts index based on the first few bits of the pubkey value. It is important that we have visibility into the binning behavior.
add metrics
Fixes #
> report on min/max bin stats for accounts index

- docs/src/developing/clients/jsonrpc-api.md
Missing documentation in WebSocket RPC client.
Added the formats to the notification objects in the WebSocket RPC client.
> Added formats to notifications in WebSocket RPC client.

- docs/src/developing/clients/jsonrpc-api.md
Follow-up to #18231 to update newly documented subscription and make consistent
> Docs: Update notification format info to be consistent

- net/init-metrics.sh
Fix influx port due to rollback
> fix-influx-port

- sdk/program/src/borsh.rs
> borsh: add bool type

- cli-output/src/display.rs
- core/src/cost_model.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- sdk/benches/serialize_instructions.rs
- sdk/program/src/message.rs
- sdk/src/feature_set.rs
- transaction-status/src/parse_accounts.rs
Removed feature switch for demoting sysvar write locks now that it is enabled on all clusters
> Remove feature switch for demoting sysvar write locks

- Cargo.lock
- programs/bpf/tests/programs.rs
- sdk/bpf/scripts/install.sh
- sdk/cargo-build-bpf/Cargo.toml
- sdk/cargo-build-bpf/src/main.rs
- sdk/cargo-build-bpf/tests/crates.rs
> Bump bpf-tools version

- runtime/src/bank.rs
> Record parent slot to reconstruct fork tree from influxdb

- gossip/src/cluster_info.rs
- runtime/benches/message_processor.rs
- runtime/src/message_processor.rs
- sdk/src/feature_set.rs
No featurizztion
Featureize it
Fixes #
> featurize_policy_update

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
accounts index performance
btree wants pubkey by value for insertion. Use pubkey by value instead of making extra copies.
Fixes #
> accounts index insert uses pubkey by value

- runtime/src/accounts_index.rs
performance of generating index
move allocation out of critical section and estimate capacity better
Fixes #
> move allocation out of critical section and estimate capacity better

- web3.js/src/publickey.ts
- web3.js/src/system-program.ts
doc tweaks" PublicKey.createWithSeed() and system-program's CreateAccountWithSeedParams obj
> chore: tweak docs for account creation methods

- programs/bpf/tests/programs.rs
> Make another insn count adjustment for failing test

- ci/test-checks.sh
> Show grcov version as well

- gossip/src/cluster_info.rs
- gossip/src/crds_gossip.rs
- gossip/tests/crds_gossip.rs
`ClusterInfo` is the gateway to `CrdsGossip` function calls, and it already
has node's pubkey and shred version (full `ContactInfo` and `Keypair` in
fact).
Duplicating these data in `CrdsGossip` adds redundancy and possibility for
bugs should they not be consistent with `ClusterInfo`.
* Removed id and shred_version from `CrdsGossip`.
* This is in preparation of making `CrdsGossip` thread-safe and 
instead moving `RwLock`s down to the individual struct fields.
> removes id and shred_version from CrdsGossip

- core/src/banking_stage.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore_processor.rs
- ledger/src/entry.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/non_circulating_supply.rs
- sdk/program/src/fee_calculator.rs
- sdk/src/feature_set.rs
Removed feature switch for secp256k1 program
> Remove feature switch for secp256k1 program

- core/src/cost_model.rs
- core/src/cost_tracker.rs
- core/src/cost_update_service.rs
- core/src/execute_cost_table.rs
- core/src/progress_map.rs
- runtime/src/message_processor.rs
No problem but some nits
- don't pass a reference to u64
- tuples are hard to follow if not used locally, use struct
- auto-drop
Fixes #
> cost model nits

- banks-client/src/lib.rs
No simple way to get `Clock` from `BanksClient`.
Add `BanksClient::get_clock`
> Add get_clock to BanksClient

- runtime/src/neon_evm_program.rs
> Update neon program id

- banks-client/src/lib.rs
https://github.com/solana-labs/solana/pull/18590 added `BanksClient::get_clock` but there still few sysvars which can be implemented. https://github.com/solana-labs/solana/pull/18604 added `SysvarId::id` which allow implement sysvar extraction as generic. While #18590 is not in release it's possible to replace `get_clock` by generic `get_sysvar`.
- Remove `BanksClient::get_clock`
- Add `BanksClient::get_sysvar`
> Replace get_clock by get_sysvar in BanksClient

- runtime/src/shared_buffer_reader.rs
error is being set before all the read data is being recorded. The result is that a reader can detect the error before it returns all the data that had been read prior to the error being hit.
Set the error after the data has been transferred.
Fixes #
> Fix race condition in bg file reader file error

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
code in generate index is taking a long time and is not measured
measure it and speed it up
Fixes #
> measure and speed up 2nd half of generate_index

- runtime/src/accounts_index.rs
Scans with binned pubkeys can be smarter about which bins they look in for matching pubkeys.
start looking at the bin where the start bound fits.
Fixes #
> accounts index scan starts looking in bin where bound would exist

- runtime/src/shared_buffer_reader.rs
Startup is slow.
Allocate new buffers within our budget for bg reader during untar, as needed, in the bg reader thread. Buffers are currently filled with 0s on allocation. This new mechanism causes us to fill the next new buffer with 0s and start using it immediately in the bg reader, ideally keeping the buffer in the cache. Previously, we allocated and filled all the buffers up front, in the client thread, before we kicked off the bg reader. We can also now allocate fewer buffers than we otherwise would if the readers are keeping up with decompression progress.
Fixes #
> lazy allocate buffers for bg reader in untar

- runtime/src/accounts_index.rs
AccountsIndex is changing a lot. It will be convenient if we have the debug trait on the type in AccountsIndex.
add the trait
Fixes #
> add Debug trait to T in AccountsIndex

- gossip/src/cluster_info.rs
ClusterInfo::repair_peers locks crds table twice, and shows performance
regression if the RwLock is not reader-preferred:
https://github.com/solana-labs/solana/blob/269028360/gossip/src/cluster_info.rs#L1188-L1210
This commit inlines `tvu_peers` filters into `repair_peers`,
and locks crds table only once.
> locks crds only once in ClusterInfo::repair_peers

- sdk/program/src/feature.rs
- sdk/src/feature.rs
- sdk/src/feature_set.rs
Steps to add a new feature switch may be unclear for someone unfamiliar with the steps (like me)
Document steps to add a new feature switch
> Add comments on how to add a new feature switch

- core/src/cluster_slot_state_verifier.rs
- core/src/fork_choice.rs
- core/src/heaviest_subtree_fork_choice.rs
- core/src/replay_stage.rs
- core/src/vote_simulator.rs
Added frozen hash column to blockstore, but it's not being populated
Add state transition for adding frozen hashes and duplicate confirmed to blockstore
Fixes #
> Add frozen hashes and marking DuplicateConfirmed in blockstore to state machine

- web3.js/README.md
Update web3 repo readme with links to example scripts
> docs: update web3 repo readme

- programs/bpf/rust/noop/src/lib.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
https://github.com/solana-labs/solana/issues/18732
Use saturating math for transaction timings
Fixes #
> Use saturating math for timings

- docs/src/developing/clients/jsonrpc-api.md
Add documentation about `unitsConsumed`
Fixes #
> Update simulateTransaction rpc docs

- core/src/cluster_nodes.rs
- core/src/cluster_slots.rs
- core/src/duplicate_repair_status.rs
- core/src/lib.rs
- core/src/repair_service.rs
- core/src/serve_repair.rs
- core/src/window_service.rs
- gossip/benches/weighted_shuffle.rs
- gossip/src/deprecated.rs
- gossip/src/weighted_shuffle.rs
- ledger/src/blockstore.rs
Missing logic to sample validators for correct ancestor hashes
Add a module for initiating and tracking ancestor hashes repair requests
Fixes #
> Add sampling logic and DuplicateSlotRepairStatus module

- docs/src/history.md
- docs/src/staking.md
Ambiguous entity naming.
Removes ambiguity!
> Clarify entities in docs

- explorer/README.md
- web3.js/README.md
The Explorer repo lacked a Solana Foundation disclaimer.
Adds disclaimer.
> Add Disclaimer to Explorer and web3js

- core/src/lib.rs
- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/voting_service.rs
Slow voting
Voting service backport
Fixes #
> Add voting service (#18552)

- perf/src/sigverify.rs
sigverify recyclers in tests could be cleaner
Consolidate sigverify recyclers
Fixes #
> Sigverify refactor

- perf/src/sigverify.rs
sigverify recyclers in tests could be cleaner
Consolidate sigverify recyclers
Fixes #
> Sigverify refactor (1.7)

- perf/src/sigverify.rs
sigverify recyclers in tests could be cleaner
Consolidate sigverify recyclers
Fixes #
> Sigverify refactor (1.6)

- Cargo.lock
- core/Cargo.toml
- core/src/ancestor_hashes_service.rs
- core/src/lib.rs
- core/src/outstanding_requests.rs
- core/src/repair_service.rs
- core/src/retransmit_stage.rs
- core/src/serve_repair.rs
- core/src/window_service.rs
Need a service to initiate ancestor hash repairs and process ancestor hash responses
Introduce such a service
Fixes #
> Introduce AncestorHashesService

- Cargo.toml
- ledger/Cargo.toml
- poh-bench/src/main.rs
https://github.com/solana-labs/solana/pull/17844
> Support running `cargo build` from an Apple M1 (backport #17632)

- programs/bpf_loader/src/lib.rs
> Reduce bpf_loader test dependencies

- ci/test-stable.sh
- programs/bpf/rust/invoke/src/lib.rs
BPF progrma unit tests are not being run
Run'em
Fixes #
> Run BPF program unit tests

- docs/src/wallet-guide/web-wallets.md
Updated the Phantom wallet description in the wallet list.
Removed the reference to invite codes.
> Updating Phantom description, removing invite code

- program-test/tests/sysvar.rs
- programs/bpf/rust/sysvar/src/lib.rs
- programs/bpf/rust/sysvar/tests/lib.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/bank.rs
- sdk/program/src/program_stubs.rs
- sdk/src/feature_set.rs
Fees sysvar is deprecated but still be updated and available to BPF programs via the sysvar `get` apis .
Add a feature to disable it when the time is right.
Fixes #
> Feature disable fees sysvar

- validator/src/bin/solana-test-validator.rs
`solana-test-validator` tries locking ledger twice
Removes some duplicated logic trying to lock ledger twice
Fixes  #19006
> v1.7: Fix broken test validator

- programs/bpf/tests/programs.rs
- sdk/bpf/scripts/install.sh
- sdk/cargo-build-bpf/src/main.rs
- improved memory operations performance
- minor fixes
> Bump bpf-tools to v1.14

- streamer/src/recvmmsg.rs
Enable IPv6 awareness in recvmmsg path.
> recvmmsg IPv6 awareness

- accounts-cluster-bench/src/main.rs
- ci/docker-rust-nightly/Dockerfile
- ci/docker-rust/Dockerfile
- ci/rust-version.sh
- core/src/heaviest_subtree_fork_choice.rs
- runtime/src/accounts_hash.rs
- runtime/src/bank.rs
- scripts/coverage.sh
We're using old Rust
Use the shiny new thing instead
> Bump Rust stable 1.54, nightly 2021-08-02

- runtime/src/accounts_index.rs
It will become expensive to create many disk buckets for an AccountsIndex. For testing, we don't need to create as many. So, we want to make it clear which functions are for testing only. Benches and /test tests require public, non #[test] entry points, so it seems more clear and helpful to modify the name of test-only functions to make it clear how an api will be used. This pr is for one such function. There will be others.
work on construction of AccountsIndex, the root of all startup problems related to # bins.
Fixes #
> Dynamic Account index creation

- runtime/src/accounts_index.rs
0-lamport keys could be cleaned from the snapshot, but are not added to the clean set.
Add 0-lamport entries to the clean set if they are not added by being a duplicate key.
Fixes #
> Handle 0-lamport account in index generation

- runtime/src/accounts_index.rs
It will become expensive to create many disk buckets for an AccountsIndex. For testing, we don't need to create as many. So, we want to make it clear which functions are for testing only. Benches and /test tests require public, non #[test] entry points, so it seems more clear and helpful to modify the name of test-only functions to make it clear how an api will be used. This pr is for one such function. There will be others. Seems useful to make sure we agree on this example before I do more.
Fixes #
> introduce AccountsIndex::default_for_tests()

- runtime/src/accounts_index.rs
traits on the generic value of AccountsIndex items are complicated and changing.
Collapse and simplify the traits.
Fixes #
> rework AccountsIndex traits

- explorer/src/components/SearchBar.tsx
- explorer/src/utils/tx.ts
Incinerator account is not labelled or searchable
Fixes https://github.com/solana-labs/solana/issues/19070
> Add incinerator to explorer search results

- runtime/src/accounts_db.rs
Move account index creation code from 3-tuple to struct for clarity.
Fixes #
> clean up types on account index generation

- ledger/src/blockstore_processor.rs
- runtime/src/bank.rs
restore function name that temporarily existed during separation of callers
Fixes #
> restore name: Bank::new_with_paths

- programs/bpf/Cargo.lock
I forgot to update programs/bpf/Cargo.lock in https://github.com/solana-labs/solana/pull/19126/commits/5a7d8f6f0d0e706c85f6e933b3e92425506ace2c
Update it
> Remove pin-project-lite warning more

- runtime/src/accounts_db.rs
Introduce type to replace enum. Calculation of this is about to get refactored. A struct aids in the code being correct by inspection.
Fixes #
> introduce StorageSizeAndCount

- sdk/bpf/scripts/install.sh
- sdk/cargo-build-bpf/src/main.rs
> Bump bpf-tools to v1.15

- ledger/src/builtins.rs
- local-cluster/tests/local_cluster.rs
- sdk/src/feature_set.rs
The feature gate is outdated.
Enables `solana_bpf_loader_upgradeable_program` unconditionally.
Fixes #
> Removes bpf_loader_upgradeable_program feature gate

- docs/src/inflation/terminology.md
Description of transaction fee burn was out of date and several users on Discord expressed confusion about this.
Updated the docs to show that the current value is 50% burned, 50% to validator.
Fixes #
> Updated transaction fee burn description.

- programs/bpf/Cargo.lock
- programs/bpf/rust/sanity/Cargo.toml
- programs/bpf/rust/sanity/src/lib.rs
- programs/bpf/rust/sanity/tests/lib.rs
- programs/bpf/rust/sysvar/tests/lib.rs
- programs/bpf/tests/programs.rs
> Add BPF Sanity program-test based test

- runtime/src/snapshot_utils.rs
Not sure how this got through.
Fixes #
> fix compile error in master

- ledger/src/staking_utils.rs
unused code.
* deleted.
* keeping the test for maintaining test-coverage.
> removes unused code from staking_utils

- runtime/src/snapshot_utils.rs
#19120 crossed with #18870 and broke master
Remove deprecated Bank api usage
> Fix crossed PRs; remove deprecated Bank api usage

- gossip/src/cluster_info.rs
Clusters are kept separate using the shred-versions obtained from
contact-infos. However, this mechanism breaks if there are 2 instances
of the same identity key running on different clusters, because then one
of the two contact-infos have the right shred-version.
If a node has the contact-info with the matching shred-version, then it
will pass all associated crds values even if they belong to the other
instance. So the shred-version check breaks.
To mitigate above, this commit is exempting node-instances from shred-version
check so that they are always propagated across clusters and halt one of the
running duplicate instances.
> exempts node-instances from shred-version check

- scripts/net-stats.sh
tracking socket buffer errors
added `{send,receive} buffer errors`
> adds send/receive buffer errors to net-stats

- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
Memory overlap does not check end of source buffer
Check it
Fixes #
> Fix memoverlap check

- core/src/accounts_hash_verifier.rs
- core/src/snapshot_packager_service.rs
- core/src/tvu.rs
- core/src/validator.rs
- core/tests/snapshots.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_utils.rs
SnapshotPackagerService does not know about Incremental Snapshots
Add a field to SnapshotPackage that is an enum for SnapshotType, so `archive_snapshot_package()` will do the right thing.
Fixes #19166
_Note: This is a continuation of #19169_
> Make SnapshotPackagerService aware of Incremental Snapshots

- core/src/validator.rs
- core/tests/snapshots.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- local-cluster/src/validator_configs.rs
- replica-node/src/replica_node.rs
- runtime/benches/accounts_index.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/bank.rs
- runtime/src/hybrid_btree_map.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
- validator/src/main.rs
Rework validator options to prepare to pass through more accounts index configuration options.
Fixes #
> accounts_index_bins to AccountsIndexConfig

- ledger/src/blockstore.rs
- sdk/src/signer/keypair.rs
Clippy was yelling at me (maybe new checks from nightly), so I fixed them.
> Fix some clippy warnings

- Cargo.lock
- programs/bpf/Cargo.lock
This is a fixup of mergify's PR #19363
> Update crossbeam-deque to 0.8.1 (#19361)

- client/src/rpc_client.rs
As of #19120, master `solana-cli` is not compatible with the public clusters.
Add backward compatibility for new RpcClient methods by checking node version and using deprecated methods when < v1.8.0
cc @behzadnouri
> Add backward compatibility for new RpcClient methods

- sdk/cargo-build-bpf/src/main.rs
In many Linux distros such as NixOS, the directory in which packages are installed is assumed to be read-only. To work around this, it is expected that the filepaths which packaged CLI tools take in are able to be freely configured through either 1) command-line flags, 2) environment variables, or 3) a configuration file.
In this commit, environment variables 'BPF_SDK_PATH' and 'BPF_OUT_PATH', which map respectively to command-line flags '--bpf-sdk-path' and '--bpf-out-dir', are now handled in cargo-build-bpf.
Additionally, given that arbitrary filepaths may now be set in which the BPF SDK is located, the requirement in which '$BPF_SDK_PATH/dependencies/bpf-tools' must strictly be a symbolic link to the directory '$HOME/.cache/solana/${bpf-tools.version}/bpf-tools has been relaxed. …
> cargo-build-bpf: allow sdk path to be set by environment variables

- runtime/src/accounts_index.rs
basic refactoring of AccountsIndex to prepare for disk buckets.
Fixes #
> some basic accounts index refactoring

- runtime/src/accounts_db.rs
add some stats to get insight for perf of shrink
Fixes #
> Debug shrink stats

- runtime/src/accounts_db.rs
make shrink faster by using available cores
Fixes #
> parallel shrink

- programs/bpf_loader/src/syscalls.rs
- programs/config/src/config_processor.rs
- programs/stake/src/stake_instruction.rs
- programs/vote/src/vote_instruction.rs
- runtime/src/accounts.rs
- runtime/src/message_processor.rs
- sdk/src/feature_set.rs
Features activated everywhere so just clouding the codebase
Remove them
Fixes #
> Feature cleanup

- programs/bpf/tests/programs.rs
> nit cleanups

- runtime/src/accounts_index.rs
minor annoyance I keep running into. No need to specify type here.
Fixes #
> remove type specifics to make funciton more flexible

- runtime/src/bank.rs
#19537 for v1.7 (uses fee_calculator)
> v1.7: Fix tests that make assumptions about tx fee rate

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
It is frequently useful to log the range while debugging.
Add Debug trait.
Fixes #
> add Debug trait to range for accounts index

- runtime/src/accounts_db.rs
shrink time gets large with high # of accounts
break up account index lookups into smaller chunks and process in parallel
Fixes #
> parallelize index_read in shrink

- runtime/src/accounts_db.rs
code is changed, touching this area elsewhere, nice time to get rid of a now-unused parameter
Fixes #
> remove unused is_startup

- Cargo.lock
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
when this test fails, it would be useful to know more information
Fixes #
> add debugging to test

- runtime/src/bank.rs
> add logging for a handful of tests

- runtime/src/accounts_index.rs
> accounts index test uses # test bins

- runtime/src/accounts_index.rs
Refactor allocate to prepare for multiple changes to this function.
Fixes #
> cleanup of allocate_accounts_index

- runtime/src/accounts_index.rs
extract all add/unref calls to an item in the accounts index to prepare for a disk backed index.
Fixes #
> refactor AccountEntry addref/unref

- core/src/retransmit_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- core/tests/snapshots.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- runtime/src/snapshot_utils.rs
Reverts solana-labs/solana#19550
> Revert "Make startup aware of Incremental Snapshots"

- runtime/src/accounts_index.rs
> get rid of unneeded mut and refactor addref

- validator/src/main.rs
When the validator is waiting to restart, the snapshot slot is checked.
With Incremental Snapshots, the full snapshot interval is going to be
_much_ higher, which would make this function wait for a looooong time.
So, if there's an incremental snapshot slot when checking, use that
slot, otherwise fall back to the full snapshot slot.
Related to #17088
> Make wait_for_restart_window() aware of Incremental Snapshots

- runtime/src/accounts_index.rs
Follow on changes will allow callers to not have to clone bounds to call range functions.
This is a little messy, so easier to do now.
Fixes #
> accounts index iterator takes &Range

- runtime/src/accounts_db.rs
Changing these constants break tests.
These constants and the surrounding code are about to enter a period of being more flexible.
Fixes #
> move constants in functions to global space

- docs/src/wallet-guide/support.md
There is an outdated telegram link of Solana at docs.
Update to new Telegram URL.
> Update to new Telegram link at docs

- web3.js/src/index.ts
for ability to do match of type on client-side
> fix(web3): export of errors

- Cargo.lock
- Cargo.toml
- banks-server/src/banks_server.rs
- core/src/banking_stage.rs
- docs/src/developing/runtime-facilities/programs.md
- programs/bpf/Cargo.lock
- programs/ed25519/Cargo.toml
- programs/ed25519/src/lib.rs
- programs/secp256k1/src/lib.rs
- rpc/src/rpc.rs
- runtime/Cargo.toml
- runtime/src/bank.rs
- runtime/src/builtins.rs
- sdk/Cargo.toml
- sdk/program/src/ed25519_program.rs
- sdk/program/src/fee_calculator.rs
- sdk/program/src/lib.rs
- sdk/src/ed25519_instruction.rs
- sdk/src/feature_set.rs
- sdk/src/lib.rs
- sdk/src/transaction/mod.rs
- sdk/src/transaction/sanitized.rs
> Add ed25519 sig verify program

- runtime/src/bank.rs
Work on parallelizing rent collection. It grows large with large # accounts in kin sim.
Fixes #
> collect rent in parallel for partitions

- runtime/src/accounts_db.rs
refactor do_shrink_slot_stores per request:
https://github.com/solana-labs/solana/pull/19506#discussion_r700557069
Fixes #
> refactor do_shrink_slot_stores

- core/tests/snapshots.rs
- ledger/src/blockstore_processor.rs
- runtime/src/accounts_background_service.rs
- runtime/src/snapshot_utils.rs
Add a dedicated function to check when we should take a full/incremental snapshot archive.
> Add fn to check when to take snapshots

- core/src/banking_stage.rs
- runtime/src/bank.rs
Extra copies/vec creation
Remove them.
Fixes #
> Remove some copying of lock results and transaction indexes

- client/src/tpu_client.rs
Using `getMaxShredInsertSlot` (or `getMaxRetransmitSlot`) to seed the leader schedule cache is no good because forked nodes can transmit their slots from well above the real cluster height, and that breaks the cache.  Instead start the cache from the current processed slot, which may be slightly behind the cluster but it's better than starting from thousands of slots ahead of it
> TpuClient now uses the processed slot to seed its leader schedule cache

- runtime/src/accounts_db.rs
a little constant and comment cleanup
Fixes #
> minor constant cleanup

- runtime/src/rent_collector.rs
reproduces this failure when this pr is rebased to master now. will be bisecting
#19704 
reverting original change: #19723
Fixes #
> add comment to save the next weary traveller

- runtime/src/accounts_db.rs
make a type for a compound type that gets used a lot and will be used more shortly.
Fixes #
> introduce BinnedHashData type to improve some code readability

- runtime/src/bank.rs
Reverts solana-labs/solana#19478
> Revert "collect rent in parallel for partitions"

- validator/src/bin/solana-test-validator.rs
Reverts solana-labs/solana#19655
> Revert "fixup! test-validator: start logging asap"

- runtime/src/bank.rs
rent collection costs something. measure # of partitions to guide optimization.
Fixes #
> metrics on rent partitions

- runtime/src/accounts_db.rs
useful to know how many accounts (and when) we load accounts for shrink. This is a large user of the accounts index.
Fixes #
> log accounts loaded for shrink stats

- runtime/src/accounts_index.rs
basic trait changes to facilitate disk index
Fixes #
> accounts index traits

- runtime/src/accounts_index.rs
This code will change more as we move to disk based accounts index. For the moment, this refactoring improves performance and will clear a way for other changes that are coming.
Fixes #
> refactor generate_index zero lamports

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
Give the map itself more knowledge of what it is holding as a value. Required for later work.
Fixes #
> push use of AccountMapEntry one level deeper

- docs/src/running-validator/validator-reqs.md
validator req docs reference unreleased zen3 skus
be less specific
> docs: be less specific about zen3 skus

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
this will be required by disk index
Fixes #
> accounts index get returns value

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
this will be required by disk index
Fixes #
> InMemAccountsIndex iter returns vec<owned>

- explorer/src/components/instruction/RawDetails.tsx
- explorer/src/pages/TransactionDetailsPage.tsx
> explorer: Display writable badge instead of readonly badge

- explorer/src/utils/tx.ts
Mercurial is not showing up on Solana Explorer.
This change will make sure that "Mercurial Stable Swap Program" is showing up on Solana Explorer.
> add Mercurial to Solana Explorer.

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
> move remove_if_slot_list_empty to InMemAccountsIndex

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
> move insert_new_entry_if_missing_with_lock into InMemAccountsIndex

- runtime/src/accounts_index.rs
re-use common code.
This enables easier refactoring and optimization and results in a simpler api to the accounts index.
Fixes #
> consolidate another use of remove_if_slot_list_empty

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
pushing account index functionality into InMemAccountsIndex to prepare for disk buckets
Fixes #
> move upsert and a handful of helpers to InMemAccountsIndex

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
Move items range filtering deeper into collection to prepare for disk based index.
Fixes #
> in_mem_accounts_index iter filters by range

- runtime/src/in_mem_accounts_index.rs
> remove 'remove' from InMemAccountsIndex

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
> move update_key_if_exists to InMemAccountsIndex

- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
> add stats inserts, deletes, updates_in_mem

- .github/workflows/web3.yml
- .travis.yml
- web3.js/.prettierrc.yaml
- web3.js/.travis.yml
- web3.js/commitlint.sh
- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/publickey.ts
- web3.js/src/transaction.ts
> chore(web3): use github actions

- explorer/src/components/common/HexData.tsx
lines mis-indented
Fixes https://github.com/solana-labs/solana/issues/19825
> explorer: Fix wrapping for pretty hex data

- .mergify.yml
> Update automerge settings for web3 github action checks

- runtime/src/accounts_index.rs
- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
> size and per-bin stats

- gossip/src/gossip_service.rs
Unnecessary clippy exception in gossip code
Remove
Fixes #
> Remove clippy exception

- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
> add <T> through accounts index

- core/src/banking_stage.rs
Unlimited packet forwarding
Limit packets forwarded
Fixes #
> Transaction forwarding limit

- runtime/src/accounts_db.rs
- runtime/src/in_mem_accounts_index.rs
> accounts index keys returns by value

- runtime/src/in_mem_accounts_index.rs
We will end up with lifetime and borrowing issues here which get quite complicated as the guts of the accts index get refactored. I was attempting to preserve the 'entry' function with its metrics directly, but that gets hairy. Since the code will all get reworked anyway shortly, I chose to inline the function, preserve the metrics, and take this step.
Fixes #
> rework acct idx entry to prepare for hashmap move

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
> introduce trait IndexValue for accounts index

- runtime/src/in_mem_accounts_index.rs
The map will soon move locations and code will begin moving. At the moment, there is value in abstracting access to the map itself.
Fixes #
> accounts index: extract map to map()

- runtime/src/in_mem_accounts_index.rs
Borrow checker issues are now gone, so I can use the accessor for stats. This allows easily code movement and architectural arrow redirecting.
Fixes #
> AcctIdx: use stats() accessor

- core/src/validator.rs
> Use f64 for stake math in get_stake_percent_in_gossip

- web3.js/src/ed25519-program.ts
- web3.js/src/index.ts
- web3.js/test/ed25519-program.test.ts
Add support for ed25519 program in web3.js library.
Fixes #
> feat: support for builtin ed25519 program in web3.js library

- runtime/src/bank.rs
> nit: misspelling

- ledger-tool/src/main.rs
ledger-tool doesn't know about incremental snapshots.
This commit only adds args to specify the maximum full/incremental
snapshot archives to retain when purging old snapshot archives.  It
purposely does *not* add a way to generate new incremental snapshots.
Fixes #19857
> Add incremental snapshot CLI args to ledger-tool

- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
> AccountsIndexStorage holds InMemAccountsIndex[]

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
> AcctIdx: move background() to AccountsIndexStorage

- client/src/tpu_client.rs
If `slots_per_epoch` is smaller than `MAX_FANOUT_SLOTS * 2`, then the tpu service can return an error.
Limit fanout to slots_per_epoch
Fixes #
> Fix tpu service fanout

- sdk/program/src/stake/state.rs
In its stake program copy-pasta, the stake pool program also has `BorshDeserialize` implemented for the stake program structs in order to cut down on compute cost when deserializing through stake accounts.  Since that implementation is not present in the sdk, stake pools currently can't move over to using it to resolve https://github.com/solana-labs/solana-program-library/issues/1865
Derive `BorshDeserialize` and `BorshSchema` where applicable for stake program structs.  The only important difference is `StakeState`, which can't use the default implementation because bincode serializes enums to 4 bytes, while borsh uses 1.
> stake: Add BorshDeserialize trait to structs

- runtime/src/bucket_map_holder.rs
We will soon have multiple threads working in parallel to sync and flush buckets.
Fixes #
> AcctIdx: add some bucket flush helpers

- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
> AcctIdx: initialize acct idx by config

- runtime/src/accounts_index_storage.rs
> AcctIdx: prepare to spin up multiple bg threads

- ledger-tool/src/main.rs
- runtime/src/accounts_index.rs
- validator/src/main.rs
Config struct changes break all these places each time. This code needs to be more tolerant of changing options.
Fixes #
> AcctIdx: handle future config defaults

- runtime/src/bucket_map_holder.rs
in-mem acct index will have an lru/age mechanism. We need a central place to store the current age, increment it, synchronize when it moves, etc.
Fixes #
> AcctIdx: central age functions/state

- Cargo.lock
- Cargo.toml
- bucket_map/Cargo.toml
- bucket_map/benches/bucket_map.rs
- bucket_map/src/bucket.rs
- bucket_map/src/bucket_item.rs
- bucket_map/src/bucket_map.rs
- bucket_map/src/bucket_stats.rs
- bucket_map/src/bucket_storage.rs
- bucket_map/src/data_bucket.rs
- bucket_map/src/index_entry.rs
- bucket_map/src/lib.rs
- bucket_map/tests/bucket_map.rs
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
This is the working decision of disk-backing we want for the on-disk accounts index.
There are several other potential project overlaps to pursue. This code may need to be generalized or otherwise optimized.
There are currently no callers of this outside of its crate.
Having this in master will allow us to easily begin calling it and improving and testing it in the system behind tests and optional configurations.
Fixes #
> introduce bucket map

- runtime/src/accounts.rs
- runtime/src/accounts_index.rs
- runtime/src/bank.rs
- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
Accounts index needs help from higher level code to know ranges of items which will be accessed and need to be held in memory. This change is staging for when we don't hold everything in memory in the accts index.
Fixes #
> AcctIdx: hold_range_in_memory

- runtime/src/bucket_map_holder.rs
> AcctIdx: introduce startup to bucket map

- runtime/src/in_mem_accounts_index.rs
Each bucket will have to keep track of the last age where it was flushed. Age is used for lru caching.
Fixes #
> AcctIdx: introduce age per in-mem bucket

- runtime/src/accounts_index.rs
- runtime/src/bucket_map_holder.rs
newly created items have an age that will cause them to age out in the future.
Fixes #
> AcctIdx: initial index items have future age to flush

- runtime/src/bucket_map_holder.rs
> AcctIdx: disk index now holds a bucket map

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder_stats.rs
> AcctIdx: metric for active bg threads

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
- runtime/src/waitable_condvar.rs
As the implementation has evolved, the correct waitable condvar has now appeared. Rename and consolidate it.
Fixes #
> AcctIdx: consolidate to correct CondVar

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_map.rs
> add bucketmap 'insert' to eliminate copies

- runtime/src/accounts_index_storage.rs
> AcctIdx: when bg processing in multiple threads, avoid bin collisions

- bucket_map/src/bucket_map.rs
> bucketmap items_in_range does not return Option

- runtime/src/bucket_map_holder.rs
> AcctIdx: age adds time component

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: delete from disk index

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
Documentation mentions getBlocks API but it is missing at web3.js
Implemented getBlocks API
> feat: getBlocks API is added

- runtime/src/bucket_map_holder.rs
minor cleanup after review.
Fixes #
> AcctIdx: Orderings and cleanup

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
acct idx will soon put most items on disk. Get will need to be able to read from disk or in-mem.
allow get to read from disk index
Fixes #
> AcctIdx: get can load from disk

- Cargo.lock
- docs/src/proposals/log_data.md
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/c/src/log_data/log_data.c
- programs/bpf/rust/log_data/Cargo.toml
- programs/bpf/rust/log_data/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- sdk/bpf/c/inc/sol/log.h
- sdk/program/Cargo.toml
- sdk/program/src/log.rs
- sdk/program/src/program_stubs.rs
- sdk/src/feature_set.rs
- sdk/src/process_instruction.rs
Solana has no support for solidity events.
Fixes #
> Proposal: event data for Solidity

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
without correct dirty tracking, we lose consistency
Fixes #
> AcctIdx: fix some missing dirty calls

- runtime/src/in_mem_accounts_index.rs
This function has to handle a new set of options where the item could exist on disk but not in the cache.
Fixes #
> AcctIdx: remove_if_slot_list_empty uses disk backing

- runtime/src/bucket_map_holder.rs
> AcctIdx: initialize stats with # bins

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
Bg loop needs to wake up every 'age' period at least to check to see if we need to age.
Fixes #
> AcctIdx: rework timing of bg loop

- runtime/src/in_mem_accounts_index.rs
the 2 flavors of upsert now get from disk if necessary to merge.
Fixes #
> AcctIdx: 2 upserts use disk

- runtime/src/accounts_index.rs
I think these were from a discussion we had.
Fixes #
> orderings on AcctIdx dirty

- runtime/src/accounts.rs
> get rid of logs left in test

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
Eliminating duplicate code.
Fixes #
> AcctIdx: consolidate lock_and_update_slot_list

- bucket_map/src/bucket_storage.rs
- runtime/src/bucket_map_holder_stats.rs
> AcctIdx: report disk bucket stats

- core/src/retransmit_stage.rs
Duplicate retransmits are not being logged in the retransmit metrics
Fixes #
> Add metric for duplicate retransmit

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
simplify and eliminate some coupling
Fixes #
> AcctIdx: PreAllocatedAccountMapEntry

- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: metrics for loading from disk

- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
We need different tracking for in mem vs total counts.
Fixes #
> AcctIdx: stats for in-mem

- runtime/src/bucket_map_holder.rs
- runtime/src/bucket_map_holder_stats.rs
log how much time bg threads spend waiting
Fixes #
> AcctIdx: log how much time bg threads spend waiting

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_map.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: range takes a ref

- docs/src/developing/clients/jsonrpc-api.md
Broken links
Point at docs.rs instead of github repo
Fixes #20064
> Update TransactionError links to docs.rs

- bucket_map/src/bucket_map.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: items needs to load from disk

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: store # threads in BucketHolder. Used later.

- .mergify.yml
> Fix automerge checks

- sdk/src/timing.rs
> add a few useful methods to AtomicInterval

- Cargo.lock
- ci/do-audit.sh
- programs/bpf/Cargo.lock
> Resolve zeroize_derive audit warning by bumping version

- docs/src/terminology.md
This terminology docs is not that friendly to noobs
> Terminology: link BPF

- explorer/src/components/account/UnknownAccountCard.tsx
- explorer/src/components/common/Account.tsx
- explorer/src/components/instruction/system/AllocateDetailsCard.tsx
- explorer/src/components/instruction/system/AllocateWithSeedDetailsCard.tsx
- explorer/src/components/instruction/system/AssignDetailsCard.tsx
- explorer/src/components/instruction/system/AssignWithSeedDetailsCard.tsx
- explorer/src/components/instruction/system/CreateDetailsCard.tsx
- explorer/src/components/instruction/system/CreateWithSeedDetailsCard.tsx
Few understand that the account "Owner" refers to the "Assigned Program Id"
Fixes #
> explorer: Make account owner program label clearer

- runtime/src/in_mem_accounts_index.rs
getting write locks is expensive. Upsert can usually satisfy a request by just getting a read lock and finding items in memory.
upsert looks in memory first using only a read lock.
Fixes #
> AcctIdx: upsert uses get from mem first

- runtime/src/bucket_map_holder_stats.rs
this is causing intermittent failures on stable ci (overflow) and was off by 1 anyway.
Fixes #
> AcctIdx: fix math error with stats calc

- runtime/src/in_mem_accounts_index.rs
Going to disk to get an item in the acct idx can be expensive.
This may be tuned in the future based on memory budget.
Keep items that are likely to be used again soon in in-mem cache.
These include items with slot list.len != 1 and items with cached storages in their slot list.
Fixes #
> AcctIdx: keep cached or multiple slot lists in cache

- runtime/src/accounts_index.rs
Part of refactoring AccountsIndex to be backed by disk. Keeping account data open longer should be discouraged. All users of WriteAccountMapEntry were only modifying the slot list.
Later, this can be refactored to move into in_mem_accounts_index to not require the arc clone either. Clean and shrink are both slower with disk based indexes. This is an attempt to improve those code paths.
Fixes #
> get rid of WriteAccountMapEntry instance

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: clone -> Arc::clone to make cost clear

- runtime/src/bucket_map_holder.rs
This may become dynamic later. Consolidate uses of the value.
Fixes #
> AcctIdx: add age_interval_ms() to remove constant use

- runtime/src/bucket_map_holder.rs
For disk based acct idx, wait_for_idle has been a place holder.
Implement it.
Fixes #
> AcctIdx: implement wait_for_idle

- runtime/src/bank.rs
Prior to panicing with cap mismatch, try calculating cap the other way (index vs non-index). This can help identify or eliminate possible failure causes.
#19985
Fixes #
> prior to panicing with cap mismatch, try other calculation

- program-runtime/src/instruction_processor.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- sdk/src/process_instruction.rs
This reverts commit df6905c3a67e46c17d66a282d200741508c9e5f0.
Fixes #
> Revert "Refactor: Merge MessageProcessor into InvokeContext (#20165)"

- runtime/src/in_mem_accounts_index.rs
logic was wrong resulting in us holding items in memory during startup
Fixes #
> AcctIdx: fix logic on should_remove_from_mem

- explorer/src/components/block/BlockOverviewCard.tsx
- explorer/src/utils/date.ts
> explorer: Display block timestamp

- explorer/package-lock.json
- explorer/package.json
> explorer: Bump @solana/web3.js from 1.29.1 to 1.29.2

- runtime/src/in_mem_accounts_index.rs
We only want to look at the slot list if we think we may throw the item out.
Fixes #
> AcctIdx: optimize should_remove_from_mem

- Cargo.lock
- dos/Cargo.toml
- dos/src/main.rs
No mode to dos a real transaction over the wire.
Add one.
Fixes #
> Add transaction mode to dos

- runtime/src/bucket_map_holder_stats.rs
> AcctIdx: us stats were showing ms

- sdk/program/src/program.rs
`invoke` and `invoke_signed` check that the caller is not mishandling any `RefCell`s in `Accountinfo`.  Doing so can be quite expensive in terms of compute units.
Provide an unchecked version of those functions for folks who want to avoid those checks and use at their own risk.
Fixes #20311
> add unchecked invokes

- runtime/src/in_mem_accounts_index.rs
non deterministic eviction jitter 
Fixes #
> AcctIdx: randomly evict items from in mem

- core/benches/sigverify_stage.rs
- core/src/sigverify_stage.rs
- streamer/src/streamer.rs
Sigverify queue can get backed up
Round-robin packets by IP, discard too many.
Fixes #
> Prune sigverify queue

- core/src/banking_stage.rs
forward_buffered_packets in banking_stage sends packets individually inline on a banking thread.
reduce syscalls to send packets by using sendmmsg
Fixes #
> Use batch_send in forward_buffered_packets

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: when disk index insert needs to grow, drop locks, grow, then restart flush

- README.md
Add one comma on line 121, fix a misspelling on line 125,
Fixes #
> Update README.md - fix typo and one grammar fix

- docs/README.md
> Update README.md - fix two typos

- bucket_map/src/bucket_api.rs
- bucket_map/src/bucket_map.rs
- bucket_map/src/lib.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: introduce BucketApi for access to a specific bucket

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_storage.rs
> AcctIdx: misc cleanup

- bucket_map/src/bucket_api.rs
> AcctIdx: Remove unnecessary Arc

- local-cluster/tests/local_cluster.rs
> Add tower rollback test

- runtime/src/accounts_db.rs
With 620M accounts, I calculate ~600k accounts per clean. Individual account index operations, such as deref, now have a higher latency. It makes a lot of sense to parallelize these operations.
Fixes #
> parallelize unref_from_storage from clean_dead_slots_from_accounts_index

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
> Add clean metrics

- local-cluster/tests/local_cluster.rs
A local-cluster test failed, but it was due to copying files... [CI log here](https://buildkite.com/solana-labs/solana/builds/56918#0585625f-6791-4ae1-a512-7c1e813e9747)
The copy fn tries to copy more than just file over, which can fail erroneously. I previously had this as a simple closure to just copy the files, not recurse, and skip directories/etc. Going back to that version.
For more info, refer to this commit which changed from the simple closure to the fs_extra copy:
https://github.com/solana-labs/solana/pull/19876/commits/7af0b553c5c23bd77d1217a8a0370935773acbf9
> Fix copy fn in local-cluster test

- core/benches/banking_stage.rs
- core/src/banking_stage.rs
- core/src/cost_tracker.rs
- ledger-tool/src/main.rs
Not enough data points in DB to visualize cost at transaction and bank level
add histogram for transaction and bank cost
Fixes #
> add transaction cost histogram metrics

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_api.rs
- bucket_map/src/bucket_storage.rs
write lock insert/update can require a grow.
Grow can now take place with a read lock. The grow uses a mutex to mark the bucket as grown.
The next write lock can check to see if there is a grown bucket available and switch to the grown bucket before returning the write lock
Fixes #
> AcctIdx: bucket map grows with read lock

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_map.rs
> AcctIdx: cleanup

- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: metric for bucket grow time

- runtime/src/bucket_map_holder.rs
current model could cause all threads to busily keep running while the last bucket(s) are being flushed.
Fixes #
> AcctIdx: sleep thread when enough threads are running to complete the remaining work

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_storage.rs
> AcctIdx: grow data buckets to default size on creation

- sdk/program/src/account_info.rs
This is another function Rust programmers encounter right away in tutorials.
Add docs and examples for next_account_info / next_account_infos.
> Document next_account_info(s)

- client-test/tests/client.rs
New `test_program_subscription` is brittle, because it depends on the system transfers that are part of TestValidator set up.
Create a new test-specific program-id
> Make test result not depend on TestValidator setup

- accountsdb-plugin-postgres/scripts/drop_schema.sql
- accountsdb-plugin-postgres/scripts/postgresql.conf
- accountsdb-plugin-postgres/src/accountsdb_plugin_postgres.rs
- accountsdb-plugin-postgres/src/postgres_client.rs
Improve AccountsDB plugin.
1. Added the reference postgresql.conf
2. Prepare slot update statement to reduce overhead in updating slot
3. Support custom connection string
4. Allow the plugin to panic on replication issues to ensure consistency
Fixes #
> Accountsdb plugin postgres improvement

- scripts/build-downstream-projects.sh
> v1.8: Fix serum-dex downstream build

- docs/src/developing/on-chain-programs/deploying.md
- docs/src/developing/programming-model/accounts.md
- docs/src/developing/programming-model/calling-between-programs.md
The docs mention that programs are immutable in a few places, which makes it sound like there's no upgradeable loader.
Mention that it's possible to upgrade programs.
Fixes #
> docs: Update language around immutable programs

- client/src/rpc_client.rs
RpcClient doctest throws deprecation warning
Bump variant to recommended
> Update deprecated variant in RpcClient doctests

- accountsdb-plugin-postgres/scripts/drop_schema.sql
- accountsdb-plugin-postgres/scripts/postgresql.conf
- accountsdb-plugin-postgres/src/accountsdb_plugin_postgres.rs
- accountsdb-plugin-postgres/src/postgres_client.rs
Added the reference postgresql.conf
Prepare slot update statement to reduce overhead in updating slot
Support custom connection string
Allow the plugin to panic on replication issues to ensure consistency
Fixes #
> Accountsdb plugin postgres improvement (#21034)

- runtime/src/bank.rs
- runtime/src/bank_forks.rs
set_root can take a long time sometimes and timing is not clear
Add some more metrics
Fixes #
> Add set_root timing metrics

- runtime/src/accounts_db.rs
filler accounts were being excluded from dirty keys and were not getting cleaned.
Include filler accounts in dirty_keys
Fixes #
> correctly clean filler accounts

- runtime/src/accounts_db.rs
- runtime/src/rent_collector.rs
- runtime/src/serde_snapshot.rs
We want information on rent exempt accounts.
Refactor RentCollection to break out important reusable parts.
Keep track of rent exempt accounts during index generation.
Fixes #
> log rent exempt accounts

- validator/src/bootstrap.rs
When incremental snapshots are enabled, bootstrap will fail to download a snapshot if there is not one that is a multiple of its full snapshot archive interval. This is not a good experience.
If bootstrap fails to find a snapshot that is a multiple, it should fallback to just finding the highest snapshot.
Since there aren't tests that exercise this code path, I ran this on a GCE machine against mainnet and saw it correctly (1) try to get a snapshot with the right multiple, then (2) see there were none, then (3) fallback and download the highest snapshot, then (4) load from that snapshot and continue starting up.
Fixes #21129
> Bootstrap falls back to getting highest full snapshot

- runtime/src/bank.rs
Add fn to bank.rs for getting stats on all accounts.
> Add bank::get_total_accounts_stats()

- runtime/src/accounts_db.rs
- runtime/src/rent_collector.rs
- runtime/src/serde_snapshot.rs
cleanup and refactoring of rent exemption logging
Fixes #
> refactor rent collector and logs

- validator/src/bootstrap.rs
>  Cleanup typos/comments in Bootstrap

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/rent_collector.rs
> add rent exempt count to get_total_accounts_stats

- runtime/src/bank.rs
Upgrade epochs are no longer used but still in the codebase
Remove the noise
Fixes #
> Remove unused upgrade epoch handling

- runtime/src/bank.rs
Test failure
Fix the test
Fixes #
> Fix rent debits test

- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
> Refactor `RentDebits` to use hashmap instead of vec (v1.8 backport)

- ledger-tool/src/main.rs
It takes a long time to print the contents of all the accounts.  I'll be
adding more to the "accounts" subcommand and would like to skip printing
the accounts contents.
See PR #21163 for the Total Accounts Stats that will come next
> Add flags to not print accounts contents

- runtime/src/accounts_hash.rs
> hashcalc eliminate zeros optimizations

- runtime/src/accounts_hash.rs
ongoing refactoring of hash calc eliminate zero to simplify and improve perf.
Fixes #
> hash calc eliminate zero refactor get_item

- ledger-tool/src/main.rs
- runtime/src/bank.rs
Calculating TotalAccountsStats is done in two places, and that code was duplicated, which we know is not ideal.
Refactor the calculation of TotalAccountsStats into a shared function. (I also added a few new stats too.)
> Refactor total stats calculation into shared fn

- programs/vote/src/vote_state/mod.rs
- runtime/src/stakes.rs
Double negatives are confusing
Fixes #
> Refactor vote state to remove double negative

- runtime/src/accounts_hash.rs
> hash calc: filler_accounts_enabled

- runtime/src/bank.rs
Nonce loading uses the slower method of loading accounts
Use the faster way since we are always loading from within the bank
Fixes #
> Load nonce with fixed root

- Cargo.lock
- core/Cargo.toml
- core/src/system_monitor_service.rs
- runtime/src/bucket_map_holder_stats.rs
- sdk/src/timing.rs
> report mem stats

- replica-node/src/replica_util.rs
- validator/src/bootstrap.rs
- validator/src/main.rs
The word "trust" still appears in the codebase; "known" is more accurate.
Update terms
> Update various terms to "known"

- runtime/src/accounts_cache.rs
- runtime/src/accounts_db.rs
> throttle store_cached when cache size is too large

- explorer/src/components/account/TokenAccountSection.tsx
> explorer: hide rank when it is null

- ledger-tool/src/main.rs
ledger-tool is useful for testing several algorithms with account data of various sizes. We recently added mem stats to system monitor. Would be nice to have mem data reported from ledger-tool verify.
Report system monitor stats during ledger-tool verify.
Fixes #
> ledger tool verify launches system monitor to report mem

- core/src/replay_stage.rs
- runtime/src/bank_forks.rs
set_root timings still a mystery
Add more metrics
Fixes #
> More set_root metrics

- runtime/src/accounts_hash.rs
Avoid copying hash values. Store refs instead. Perf is > 10%.
Fixes #
> HashCalc: Perf: use refs for hashes

- rpc/src/rpc.rs
- runtime/src/bank.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/feature_set.rs
- sdk/src/transaction/mod.rs
- sdk/src/transaction/sanitized.rs
Nonce accounts in nonce instructions must be writeable
Reject nonce transactions up front if not
Fixes #
> Nonce accounts must be writeable

- Cargo.lock
- programs/bpf/Cargo.lock
- runtime/src/accounts_db.rs
> remove store_cached stall

- runtime/src/bucket_map_holder_stats.rs
Without this, the initial time is 0. now - 0 is huge, so we get massive #s. This change simplifies the code. It also skips the first write, which causes us to only use intervals which are in the expected range.
Fixes #
> AcctIdx: fix initial massive metrics spike

- programs/stake/src/stake_state.rs
> Refactor: Fix typo in stake_state.rs

- runtime/src/bucket_map_holder_stats.rs
during startup and possibly under high load, age can exceed the metrics time. In those cases, we want to produce an estimate based on # bins flushed during the time period.
Fixes #
> AcctIdx: report on partial progress during flushing

- programs/bpf/benches/bpf_loader.rs
- programs/bpf/tests/programs.rs
- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/bank_utils.rs
- sdk/program/src/nonce/state/current.rs
Inconsistent and confusing nonce naming
Standardize and simplify it
Fixes #
> Nonce naming cleanup

- runtime/src/accounts_db.rs
I started going down this rabbit hole while looking at Issue #14960, which deals with duplicate `write_version`s. This should never happen, but it did. I didn't fully inspect the code at the time the issue was first raised, so maybe there was (is?) also another underlying bug to deal with. Minimally, I looking at `write_version`. I noticed that currently we use `write_version` to check and control logic, which is a big red flag with `Ordering::Relaxed`.
Basically, `Relaxed` does _not_ do anything for guaranteeing visibility, guaranteeing _other_ loads/stores nearby aren't re-ordered, nor does it constrain speculation. Anytime `Relaxed` is used, it should be considered akin to writing `unsafe { }`, where guarantees about its usage should be declared. `Relaxed` basically only guarantees …
> Constrain memory ordering on AccountStorageEntry::alive_bytes

- program-runtime/src/instruction_processor.rs
- program-runtime/src/invoke_context.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
See discussion in the referenced issue below.
- fixes the bug in `ThisInvokeContext::push()`
- throws `InstructionError::UnsupportedProgramId` in `InstructionProcessor::process_instruction()` again
- removes `debug_assert_eq!(first_instruction_account, 1);` in `process_instruction_with_program_logging()`
- adds a test to the bank
Fixes #21346
> Fix #21346

- ledger/src/shred.rs
Working towards encapsulating erasure coding scheme inside shreds in order to simplify upcoming changes and not to leak implementation details.
* Added methods to obtain shreds' erasure coded block and index.
* More sanity checks when computing erasure block index.
* Avoiding panic in `.drain`.
> adds methods to obtain shreds' erasure coded block and index

- runtime/src/bank.rs
No timing metrics for bank creation and rewards calculation
Add them
Fixes #
> Add timing metrics to bank creation and rewards calculation

- core/src/cluster_slots.rs
Cluster slots size can grow large
Report cluster slots memory usage
Fixes #
> Report cluster slots size

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/bank_forks.rs
High delays in `AccountsDB::set_root` not sure where it's coming from.
Add metrics for each operation in set_root.
Fixes #
> Add timing for accounts add_root

- core/src/qos_service.rs
The test that spawns two threads are flaky on ci, it fails from time to time as if one or both spawned threads didn't run.
Fixes #21392
> An async test is flaky on ci

- web3.js/src/account.ts
- web3.js/src/keypair.ts
- web3.js/src/secp256k1-program.ts
This package is failing in the [browser ESM + Import Map environment](https://jspm.org/sandbox#H4sIAAAAAAAAA61Y23LbNhB9z1cg6kvSmqRudhxH8ii1M5l4osaJ48n0qQOCKxE2CDAAaFnu9N+7BElZZGlGo/TBpkAszlnsgnvB5HmkmF2nQGKbiNNnk+oBNDp9RsgkAUsJi6k2YKe9zC68456bsNwKOL2W7hlNgmK8WSJpAtPeHYdVqrTtEaakBYkQKx7ZeBrBHWfgucEB4ZJbToVnGBUwHSDBJCg0mIQqWjvU556HD0Iuri7n5D1I0NQqTT4kOT6Z09TNvou4JddfPp7gfmxqToJgWYn6NyZNfK6CX66Hf8R/vv/99nze1+urh4ur60HMzm4+PfTl/Or157uv/f56YMz36Ob8ev4Qfp6vPrwdXVwmbH39Flk8zylkmOapJbnxpj3u1Eho6ozzt9OlfGl6J+ULfDUzSlBJgxWEI1QIp3obRelGQ5kmJw3J2cAf9f1hIHgYcBnBvR9qtTKgfTBJjuQY/jkomA1TKdSIW1i2pnPNQhqCCHSGHk0AzS9S0CagZi3ZV7UxeJfGNYTZK39w5PefBMp1PvghPRPUmDMqxFkM7HZv8jrMjtQaqIWzfOX+vI8Yu5EuwV5qZVV+qj4t9uatw+xGzWUMmtv9N1sB7EpnQav0C3zPuIZzWNBM2J/gbkHbTZFUGcNDAWdKGqszhmfzC9hMy72VeRJxN4Vyp6n9fY/xoIToptOw3Puj3 …
> feat: improve compatibility with native ESM in Node and the browser

- docs/src/developing/on-chain-programs/overview.md
Grammatical error in docs
s/a/an
Fixes #
> Fix grammatical error in docs

- sdk/program/src/program_option.rs
> Fix typo in program_option.rs

- explorer/src/components/instruction/SerumDetailsCard.tsx
- explorer/src/components/instruction/serum/CancelOrderByClientIdDetails.tsx
- explorer/src/components/instruction/serum/CancelOrderByClientIdV2Details.tsx
- explorer/src/components/instruction/serum/CancelOrderDetails.tsx
- explorer/src/components/instruction/serum/CancelOrderV2Details.tsx
- explorer/src/components/instruction/serum/CloseOpenOrdersDetails.tsx
- explorer/src/components/instruction/serum/ConsumeEventsDetails.tsx
- explorer/src/components/instruction/serum/ConsumeEventsPermissionedDetails.tsx
- explorer/src/components/instruction/serum/DisableMarketDetails.tsx
- explorer/src/components/instruction/serum/InitOpenOrdersDetails.tsx
- explorer/src/components/instruction/serum/InitializeMarketDetailsCard.tsx
- explorer/src/components/instruction/serum/NewOrderV3DetailsCard.tsx
- explorer/src/components/instruction/serum/PruneDetails.tsx
- explorer/src/components/instruction/serum/SettleFundsDetailsCard.tsx
- explorer/src/components/instruction/serum/SweepFeesDetails.tsx
- explorer/src/components/instruction/serum/types.ts
Explorer doesn't support the serum "new order v3" instruction
Clean up serum integration and add support for some more instruction types
Fixes #
> explorer: add support for more serum instructions

- explorer/package-lock.json
For proper compatibility checks, the "caniuse" browser list db should be updated occasionally
Fixes #
> explorer: update browserlist db

- cli/src/vote.rs
Some of the checks on the client did not match the checks in the vote program.
Fixes #
> fix checks in process_vote_authorize

- runtime/src/bank.rs
add test for newly introduced ability to abort scan
Fixes #
> add test for aborting index scan

- runtime/src/accounts_index.rs
Vast majority of 'update' calls are to items that already exist in the index. As a result, we don't need to allocate the arc and rwlock. We just need the raw parts. 
Don't allocate the arc and rwlock (and meta) for 'upsert' calls unless necessary.
Fixes #
> AcctIdx: upsert avoids unnecessary allocation

- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- sdk/program/src/entrypoint.rs
> v1.8: Fix more BPF alignment issues on arm64

- sdk/program/src/system_instruction.rs
> Fix typo in system_instruction.rs

- runtime/src/stakes.rs
While going through the staking code to learn, I refactored a few functions to make them simpler to read (at least for me!).
> Refactor fns that calculate stake and voter balances

- Cargo.lock
- accountsdb-plugin-postgres/Cargo.toml
- accountsdb-plugin-postgres/scripts/create_schema.sql
- accountsdb-plugin-postgres/scripts/drop_schema.sql
- accountsdb-plugin-postgres/src/accountsdb_plugin_postgres.rs
- accountsdb-plugin-postgres/src/postgres_client.rs
- accountsdb-plugin-postgres/src/postgres_client/postgres_client_transaction.rs
AccountsDb plugin for transactions -- part 4 -- persisting to the Db.
1. DB models for transactions
2. Rust models for transactions
3. Transform from SDK models to rust db models
4. Unit tests
Fixes #
> Accountsdb plugin transaction part 4 -- postgres plugin implementations -- DB models

- bucket_map/src/bucket.rs
some code cleanup to enforce correctness
Fixes #
> AcctIdx: disk bucket cleanup

- runtime/src/accounts_index.rs
> AcctIdx: cleanup trait

- runtime/src/accounts_cache.rs
- runtime/src/accounts_db.rs
- validator/src/main.rs
> aggressively flush cache based on cache size

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: remove unused function

- programs/bpf_loader/src/lib.rs
#20290 introduced a `let program_id` statement which shadows the existing `program_id` variable in `BpfExecutor::execute()` [here](https://github.com/solana-labs/solana/pull/20290/files#diff-b225f839559f40bfb9322cde13dbf4cb0516567faa672daf63dc637bdd9e0cd0R948). So subsequent calls to `stable_log` use the wrong `program_id`.
Turn `let (program_id, return_data) = ...` into `let (_returned_from_program_id, return_data) = ...`
Fixes #
> Fixes `invoke_context.get_return_data()` shadowing `program_id`

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
> AcctIdx: minor code cleanup

- runtime/src/accounts.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
While addressing a few nonce issues I found the bank's handling of durable nonces has devolved over time using different terms and overly complicated implementations
- align syntax
- simplify
- general cleanup
- updated comments
- No behavior changes
Fixes #
> Cleanup the bank's use of nonces

- runtime/src/accounts_index.rs
> AcctIdx: test cleanup

- runtime/src/message_processor.rs
Need to report bpf program compute units to cost model without having to enable `tx_wide_compute_cap` feature. 
Fixes #
> report compute units without tx_wide_compute_cap feature enabled

- runtime/src/stakes.rs
`calculate_stake()` and `store()` unnecessarily take `StakeHistory` wrapped in an Option. My next PR will change `StakeHistory` to be CoW, and this wrapped Option makes it much less ergonomic.
Remove Option wrapping.
> Remove unnecessary Option

- runtime/src/stake_delegations.rs
- runtime/src/stake_history.rs
Add tests to StakeDelegations and StakeHistory to ensure that the outer
types serialize and deserialize correctly to/from the inner types.
> Ensure that StakeDelegations and StakeHistory serde

- docs/src/implemented-proposals/ed_overview/ed_validation_client_economics/ed_vce_state_validation_protocol_based_rewards.md
Fix the formula on the proposal page: https://docs.solana.com/implemented-proposals/ed_overview/ed_validation_client_economics/ed_vce_state_validation_protocol_based_rewards
> docs: Fix SOL staked formula

- sdk/src/feature_set.rs
Existing pubkeys are not usable
> Ensure we have keys to activate solidity features

- runtime/src/accounts.rs
- runtime/src/accounts_index.rs
Followup to: #21327
Preparation for reusing this code in the non-indexed case.
Fixes #
> refactor and test scan abort code

- runtime/src/accounts_db.rs
these operations occur at startup, with no other operations running concurrently. So, give them all the threads they want. Accounts index has changed a lot, affecting our lock and threading performance.
Fixes #
> AcctIdx: disk generate index and filler accounts use more threads

- program-runtime/src/log_collector.rs
`LogCollector` uses a hardcoded bytes limit. When running tests with `cargo test --target=bpfel-unknown-unknown`, that leads to the output being truncated, eg:
```
...
test char::methods::bench_ascii_char_to_lowercase ... ok
test char::methods::bench_ascii_char_to_uppercase ... ok
test char::methods::bench_ascii_mix_to_lowercase ... ok
test char::methods::bench_ascii_mix_to_uppercase ... ok
test char::methods::bench_non_ascii_char_to_lowercase ... ok
test char::methods::bench_non_ascii_char_to_uppercase ... ok
Log truncatedok finished in 39.295 seconds
```
Introduce `LogCollector::new_ref_with_limit(limit: Option<usize>)` which can be used to initialize a collector with the given bytes limit. The limit can be `None`, in which case logs are never truncated.
> program-runtime: add LogCollector::new_ref_with_limit()

- core/tests/ledger_cleanup.rs
* Add NUM_WRITERS to ledger_cleanup to enable multiple writers.
(Note that our insert_shreds() is still single threaded because
it has a lock that limits only one writer at a time.)
* Make pre-generated slots more performent by directly inserting
into the shared queue.  Otherwise, the main-thread which
prepares the slots will be slower than the writers.
* Correct the shred insertion time -- before this diff it did not
wait for joining all writer threads.
> Add NUM_WRITERS to ledger_cleanup to enable multiple writers.

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
> Bump solana_rbpf to version v0.2.18 (backport #21774)

- runtime/src/accounts_db.rs
- runtime/src/serde_snapshot.rs
> introduce AtomicAppendVecId

- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
> use AppendVecId instead of usize

- runtime/src/account_info.rs
- runtime/src/accounts_db.rs
support further refactoring
Fixes #
> AccountInfo: construct with new()

- cli/src/feature.rs
Feature list displayed from the CLI is long and unorganized
Sort features so that most recent and actionable features are at the bottom and long ago activated features are at the top.
```
Feature                                      | Status                      | Description
...
BKCPBQQBZqggVnFso5nQ8rQ4RwwogYwjuUt9biBjxwNF | active since slot 100748256 | collect rent from accounts owned by sysvars
4d5AKtxoh93Dwm1vHXUU3iRATuMndx1c431KgT2td52r | active since slot 105068256 | Add compute_budget_program
HTTgmruMYRZEntyL3EdCDdnS6e4D5wRq1FA7kQsb66qq | active since slot 106796256 | remove support for the native loader
FjSRMpFe7mofQ3WrEMT7Smjk2sME1XdAoRxcv55V6M44 | active since slot 107228256 | deterministic shred seed
meRgp4ArRPhD3KtCY9c5yAf2med7mBLsjKTPeVUHqBL  | activation pending (mocked) | …
```
> cli: Order displayed feature list by status

- programs/vote/src/vote_instruction.rs
- programs/vote/src/vote_state/mod.rs
- sdk/src/feature_set.rs
Addresses leftover comments from #21531
Fixes #
> Addressing leftover comments from #21531

- runtime/src/account_info.rs
> AcctIdx: AccountInfo.lamports private

- runtime/src/message_processor.rs
If tx_wide_compute_cap feature is not enabled, invoke_context will create a new instance of compute_meter to process instruction. Therefore original compute-meter wouldn't report ix units.
Move ix unit reporting close to process_instruction.
Fixes #
> Backport bpf units reporting 1.8.10

- runtime/src/account_info.rs
- runtime/src/accounts_db.rs
allows refactoring and changing AppendVecID to different type that wraps around
Fixes #
> AcctInfo: create AcctInfo with cache explicitly

- runtime/src/account_info.rs
- runtime/src/accounts_db.rs
> AcctInfo: store_id private and add accessor

- ledger/src/shred.rs
> chore: fix typo in shred.rs

- Cargo.lock
- Cargo.toml
- cargo-build-bpf
- programs/bpf/Cargo.lock
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/gen-syscall-list/Cargo.toml
- programs/bpf_loader/gen-syscall-list/build.rs
- programs/bpf_loader/gen-syscall-list/src/main.rs
- scripts/cargo-install-all.sh
Backport of https://github.com/solana-labs/solana/pull/21896
> v1.9: Add helper crate to generate syscalls.txt

- runtime/src/account_info.rs
- runtime/src/accounts_db.rs
> AcctIdx: move cached store id to bit

- ledger/src/blockstore.rs
Add code comment for get_slot_meta_entry in blockstore.rs
> Add code comment for get_slot_meta_entry in blockstore.rs

- ledger/src/blockstore.rs
Add comment block for commit_slot_meta_working_set in blockstore.rs
> Add comment block for commit_slot_meta_working_set in blockstore.rs

- runtime/src/accounts_db.rs
> AcctIdx: consolidate next_id calls

- runtime/src/bucket_map_holder_stats.rs
> AcctIdx: fix metrics bug

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: streamline metric update

- runtime/src/account_info.rs
> AcctIdx: remove troublesome assert

- runtime/src/serde_snapshot/future.rs
this cannot change, but other refactoring is coming soon. So, separate this type.
Fixes #
> AcctIdx: define type for serialized AppendVecId

- core/tests/ledger_cleanup.rs
- Use info!()/warn!() over println!()/eprintln!()
- Make status prints consistent
- Add default RUST_LOG filter to see test printouts
- Adjust reported data to show shreds and rates we care about
> Clean up test_ledger_cleanup_compaction prints

- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
unused api in SherdIndex
* remove unused and test-only api.
* renamed some to be more consistent with rust api.
> simplifies ShredIndex api

- runtime/src/accounts_db.rs
Introduced in #19506, #19507
Fixes #
> use bg thread pool for shrink

- runtime/src/account_info.rs
- runtime/src/accounts_db.rs
> load_accounts_index_for_shrink ignores cached entries

- runtime/src/accounts.rs
- runtime/src/in_mem_accounts_index.rs
holding a range of None was partially supported but never implemented. Removing it to clean up code.
Fixes #
> AcctIdx: remove Option from held ranges

- runtime/src/accounts_db.rs
considering changes to AppendVecId data type. Evaluating panic condition at AppendVecId::Max.
Track actual append vec id growth
Fixes #
> log "next_id" to track append vec ids

- runtime/src/in_mem_accounts_index.rs
> AcctIdx: held ranges search in lifo order

- runtime/src/serde_snapshot.rs
remove unused Option<> to make refactoring more clear elsewhere.
Fixes #
> simplify api on reconstruct_single_storage

- bucket_map/src/bucket.rs
- bucket_map/src/index_entry.rs
prepare to reduce the cost of the per-index entry data structure for the accounts index
Fixes #
> disk buckets: refactor

- keygen/src/keygen.rs
> fix typo in keygen.rs

- runtime/src/snapshot_utils.rs
Manually backport #21925
See failed mergify backport PR here: https://github.com/solana-labs/solana/pull/21982#
> Check file size of snapshot_version when unarchiving snapshot (backport #21925)

- docs/src/developing/plugins/accountsdb_plugin.md
The sidebar for the plugin doc is showing the item as "Overview" -- it should show "Plugins"
Used correct HEAD styles.
Fixes #
> Fix the sidebar entry for plugins documentation

- bucket_map/src/bucket_storage.rs
factor out some unsafe code to clean up and prepare for potential other refactoring
Fixes #
> disk_buckets: factor out unsafe code

- bucket_map/src/bucket.rs
make if and else match. copy is better than clone
Fixes #
> disk buckets: clone_from_slice -> copy_from_slice

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_storage.rs
- bucket_map/src/index_entry.rs
Abstract UID_UNLOCKED so we can change the data type of Uid for perf.
Fixes #
> Disk buckets: abstract UID_UNLOCKED

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_storage.rs
Simplify implementation of disk buckets. Use borrow checker to enforce safety. Prepare for refactoring and perf improvements.
Fixes #
> DiskBuckets: remove unnecessary atomic on uid

- ledger/src/blockstore.rs
Add code comment for nsert_shreds_handle_duplicate in blockstore.rs
> Add comment block for insert_shreds_handle_duplicate in blockstore.rs

- Cargo.lock
- accounts-cluster-bench/Cargo.toml
- accountsdb-plugin-manager/Cargo.toml
- bench-streamer/Cargo.toml
- bucket_map/Cargo.toml
- core/Cargo.toml
- frozen-abi/Cargo.toml
- ledger-tool/Cargo.toml
- ledger/Cargo.toml
- local-cluster/Cargo.toml
- metrics/Cargo.toml
- net-shaper/Cargo.toml
- perf/Cargo.toml
- program-runtime/Cargo.toml
- program-test/Cargo.toml
- programs/bpf/Cargo.lock
- programs/vote/Cargo.toml
- remote-wallet/Cargo.toml
- rpc/Cargo.toml
- runtime/Cargo.toml
- sdk/program/Cargo.toml
- send-transaction-service/Cargo.toml
- streamer/Cargo.toml
Unused deps in Cargo.toml
* Removed unused deps.
* Also moving some to `[dev-dependencies]` so that they are not propagated
to other packages which depend on the package.
> removes unused Cargo dependencies

- Cargo.lock
- core/src/test_validator.rs
- core/src/validator.rs
- validator/Cargo.toml
- validator/src/admin_rpc_service.rs
- validator/src/bin/solana-test-validator.rs
- validator/src/main.rs
> validator: add contact-info query to admin port

- docs/src/developing/runtime-facilities/programs.md
> docs: fix typo

- web3.js/src/sysvar.ts
Closes https://github.com/solana-labs/solana/issues/21090
> web3.js: Add Sysvar PubKeys

- accountsdb-plugin-interface/src/accountsdb_plugin_interface.rs
- docs/src/developing/plugins/accountsdb_plugin.md
Add docs for notifying transactions via plugin
Fixes #
> Add docs for notifying transactions via plugin

- install/src/command.rs
> fix: Installer overall timeout to None

- core/tests/ledger_cleanup.rs
This PR simplifies test_ledger_cleanup_compaction and makes it lockless.  Specifically:
* Replace the shared queue with an atomic counter.
* Shred-generation is moved from main thread to writer thread to enable multi-thread (a follow-up PR will improve this further).
* Insertion status is reported via atomic counters (instead of having the main thread keep grabbing the lock of the shared queue).
* The behavior of PRE_GENERATE_DATA == true remains the same: writer threads will still obtain shreds from the shred queue.
> (Ledger store benchmark) Enable running multiple writers without lock

- core/tests/ledger_cleanup.rs
Remove duplicate code in ledger_cleanup_compaction_test.
> Remove duplicate code in ledger_cleanup_compaction_test

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- rbpf-cli/Cargo.toml
Manual backport of #22216.
Fixes #
> Bumps solana_rbpf to version v0.2.21 (backport #22216)

- runtime/src/bucket_map_holder.rs
`next_bucket_to_flush` is a Mutex right now to handle wrapping. It would be nice to use an atomic instead of a mutex for perf here.
Use `AtomicUsize::fetch_update()`, which will both be atomic and handle wrapping.
> Use AtomicUsize for next_bucket_to_flush

- docs/src/developing/on-chain-programs/developing-rust.md
Updated version of https://github.com/solana-labs/solana/pull/22122
> docs: Remove Xargo.toml reference

- core/src/validator.rs
see https://github.com/rust-lang/rust/issues/39364#issuecomment-634545136
work around as elsewhere in codebase
Fixes #
> work around rust 39364 for stats_reporter_sender

- ci/publish-tarball.sh
- install/solana-install-init.sh
- scripts/solana-install-deploy.sh
- scripts/solana-install-update-manifest-keypair.sh
I'll keep this on master for now, and backport to v1.9 once there's an arm64 buildkite agent setup
> Add support for arm64-apple-darwin release/channel artifacts

- core/tests/ledger_cleanup.rs
In the current code, the shred generation in the ledger_cleanup
test runs much slower than persisting shreds to the ledger store.
Such slowness prevents us from using `test_ledger_cleanup_compaction`
to benchmark the ledger store.
Instead of keeping creating new shreds, this PR only generates
one shred per thread and keeps reusing it by cloning and updating
its slot id.
Here're some benchmark numbers with 8 writer threads with RocksDB's
background compaction w/o the period clean-up service:
w/o this PR: ~52k shreds per second.
w/ this PR: ~93k shreds per second.
w/ this PR + no locks in `insert_shreds`: ~170k shreds per second.
This PR is based on top of #22090.
> (Ledger store benchmark - 2/N) Allow running benchmark in large scale 

- core/tests/ledger_cleanup.rs
Add comments about the ledger store benchmark and its arguments.
This PR is based on top of #22091
> (Ledger store benchmark - 3/N) Add comments about the benchmark and its arguments

- programs/bpf/tests/programs.rs
These tests were broken due to PR #22289
Fix `use` statements, and fix struct types.
> Fix broken build from bpf/tests/programs.rs

- zk-token-sdk/src/range_proof/mod.rs
- zk-token-sdk/src/sigma_proofs/fee_proof.rs
Relics from one of @samkim-crypto's recent late-night debug sessions I'm sure :)
> zk-token-sdk: Remove stray printlns

- core/tests/ledger_cleanup.rs
Add flag CLEANUP_SERVICE to ledger cleanup benchmark.
This flag indicates whether to have a background clean-up service.
If set to false, the ledger store will purely rely on RocksDB's
compaction to perform the clean-up.
This PR is based on top of #22160.
> (Ledger store benchmark - 4/N) Add CLEANUP_SERVICE flag

- zk-token-sdk/src/instruction/transfer.rs
- Fix ciphertext validity error
- Some restructuring to set the stage for fee proof
> zk-token-sdk: fix transfer verification / set up for fee proof

- runtime/src/accounts_db.rs
> refactor get_store_for_shrink

- runtime/src/accounts_db.rs
> factor out code in do_shrink_slot_stores

- bucket_map/src/index_entry.rs
> disk buckets: helpers and test

- ledger/src/blockstore_db.rs
Reducing the clutter / repeated use of constants for column families. Also added some instructions for what to update when a new column is added.
> Minimize boilerplate code around Rocks column families

- runtime/src/bank.rs
No metrics on the executor cache
Add some
nvm the first four commits. I'm just staying ahead of the conflicts
> Executor cache metrics

- runtime/src/bank.rs
New executor cache entries start with a zero use-count, making them susceptible to immediate eviction
Prime new entry use-counts with a biased random value
Review note: Only the last commit is relevant.  The others will be rebased away
> Executor cache count primer

- runtime/src/bank.rs
The executor cache api accepts a single executor, this prevents optimized addition of multiple
Add support for multi-add to reduce evictions
Fixes #
> improve multi executor cache addition

- Cargo.lock
- programs/bpf/Cargo.lock
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
No per program executor creation timings
Add a trace metric
> add excutor creation trace timings

- runtime/src/bank.rs
Executor cache hit/miss metrics are actually measuring replacement/insertion
Add correct hit/miss metrics, retain replacement/insertion with proper naming
> bank: fix executor cache metrics

- gossip/src/cluster_info_metrics.rs
Too much load on influxdb from gossip vote metrics 
Limit gossip vote stats to the top most voted slots.
> limits gossip vote stats to the top most voted slots

- core/benches/banking_stage.rs
Unnecessary variable initialization and update which just get overwritten in the next line.
Removed unnecessary code.
Fixes #21061
> Remove unnecessary var in banking_stage bench

- docs/src/developing/programming-model/accounts.md
- docs/src/integrations/exchange.md
#22292 prevents the creation of anything but RentExempt accounts. But docs still talk about how to handle paying rent
Update docs, esp for integrations
> Update docs vis-a-vis prohibition of RentPaying accounts

- accountsdb-plugin-postgres/scripts/create_schema.sql
A typo error due to merge conflict resolution.
Removed AddressLookupError
Fixes #
> Fixed a merge issue

- cli/src/test_utils.rs
- cli/tests/nonce.rs
- cli/tests/program.rs
- cli/tests/request_airdrop.rs
- cli/tests/stake.rs
- cli/tests/transfer.rs
- cli/tests/vote.rs
When a balance check fails it's not immediately obvious where in the test the failure occurred.
use a macro to expose the actual assert line in the test.
Fixes #
> nit: Traceable test balance checks

- ledger/src/blockstore_processor.rs
Errors are not propagated in BlockstoreProcessorError
Fixes #
> Log internals of BlockstoreProcessorError

- program-runtime/src/invoke_context.rs
- programs/vote/benches/process_vote.rs
- runtime/benches/bank.rs
Previous vote processing benchmark was end-to-end so had higher variance, it also didn't succeed properly due to buggy setup, and lastly didn't fill up the slot hashes sysvar completely.
- New better bench that just tests vote processing
Fixes #
> New benchmark for vote processing

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/genesis_utils.rs
- runtime/src/non_circulating_supply.rs
- runtime/src/rent_collector.rs
- runtime/src/system_instruction_processor.rs
Gated code needs to be cleaned up
- Remove special handling of sysvar rent exemption
Fixes #
> Cleanup activated rent_for_sysvars feature

- runtime/src/accounts_db.rs
> cleanup assert

- core/src/banking_stage.rs
- core/src/qos_service.rs
Want to identify the delta between leader estimated block units and actual units after execution. 
- report estimated execution units packed into block, and actual units and time after execution.
- report roll-up transaction costs per block, give us info such as "how many write lock units in this block"
Fixes #
> Add estimated and actual block cost units metrics

- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- sdk/src/feature_set.rs
> vote account withdraw authority may change the authorized voter

- docs/src/running-validator/vote-accounts.md
* Promote `solana vote-authorize-voter-checked`
* Discuss how nonce accounts can be helpful when rotating authorities
> docs: Add more details about vote account key rotation

- core/src/replay_stage.rs
something takes a long time in this function during a low TPS event
metrics
Fixes #
tag @carllin @sakridge
> metrics for generate new bank forks

- core/src/consensus.rs
> chore: Remove unused mut

- core/src/sigverify_stage.rs
missing metrics
add metrics
Fixes #
> Track discard time of excess packets in sigverify

- core/benches/sigverify_stage.rs
- core/src/sigverify_stage.rs
As shown by the added benchmark, current code does worse if there is a
spam address plus a lot of unique addresses.
on current master:
```
test bench_packet_discard_many_senders  ... bench:   1,997,960 ns/iter (+/- 103,715)
test bench_packet_discard_mixed_senders ... bench:  14,256,116 ns/iter (+/- 534,865)
test bench_packet_discard_single_sender ... bench:   1,306,809 ns/iter (+/- 61,992)
```
with this commit:
```
test bench_packet_discard_many_senders  ... bench:   1,644,025 ns/iter (+/- 83,715)
test bench_packet_discard_mixed_senders ... bench:   1,089,789 ns/iter (+/- 86,324)
test bench_packet_discard_single_sender ... bench:     955,234 ns/iter (+/- 55,953)
```
* No change to the order of packets or which packets are discarded.
* Drop hash-map entries if there are no more packets …
> improves sigverify discard_excess_packets performance

- Cargo.lock
- Cargo.toml
- bloom/Cargo.toml
- bloom/benches/bloom.rs
- bloom/build.rs
- bloom/src/bloom.rs
- bloom/src/lib.rs
- core/Cargo.toml
- core/src/banking_stage.rs
- core/src/sigverify_stage.rs
- gossip/Cargo.toml
- gossip/src/cluster_info.rs
- gossip/src/crds_gossip_pull.rs
- gossip/src/crds_gossip_push.rs
- perf/Cargo.toml
- perf/benches/dedup.rs
- perf/src/sigverify.rs
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> Dedup v1.8

- runtime/src/cache_hash_data.rs
> minor cleanup

- Cargo.lock
- core/src/sigverify_stage.rs
- perf/Cargo.toml
- perf/benches/dedup.rs
- perf/src/sigverify.rs
- programs/bpf/Cargo.lock
> Faster dedup v1.8

- Cargo.lock
- core/src/sigverify_stage.rs
- perf/Cargo.toml
- perf/benches/dedup.rs
- perf/src/sigverify.rs
- programs/bpf/Cargo.lock
> Faster dedup v1.9

- program-test/src/lib.rs
- program-test/tests/return_data.rs
- sdk/program/src/program_stubs.rs
> v1.9: Impl get_/set_return_data syscalls for ProgramTest

- explorer/src/components/block/BlockHistoryCard.tsx
> Explorer: Sort block program ids in filter dropdown

- net/init-metrics.sh
> undoing the changes for the traceability

- core/src/replay_stage.rs
- poh/src/poh_recorder.rs
- `leader_first_tick_height` includes grace ticks, but it's easy to forget that
- The slot for a given tick height is computed in multiple places
- Rename `leader_first_tick_height` to `leader_first_tick_height_including_grace_ticks`
- Add `slot_for_tick_height` helper method
- Add enum for `PohLeaderStatus`
Fixes #
> Refactor: Rename variables and helper method to `PohRecorder`

- Cargo.lock
- programs/bpf/Cargo.lock
CI audit-check is failing
Bump thread_local to patched version
> Bump thread_local

- runtime/src/bank.rs
- runtime/src/inline_spl_associated_token_account.rs
- runtime/src/lib.rs
- sdk/src/feature_set.rs
The new token program v3.3.0 plays best with the new associated token program.
Add a feature to release the new associated token account program, and refactor the bank bits to replace the program.
Fixes #
> spl-associated-token-account: Add feature for new program

- runtime/src/accounts_db.rs
> fix comment typos

- sdk/src/ed25519_instruction.rs
Just in case, do #22721 for master as well
Change up how `Signature` is referenced.
Fixes #
> sdk: Maybe fix build for the future with import

- sdk/src/ed25519_instruction.rs
The test test_ed25519 fails occasionally. It's easy to reproduce this by running this in the sdk directory:
```
while cargo test test_ed25519; do : ; done
```
This PR fixes the test
Fixes #
> Fix intermittent failure of test_e25519

- runtime/src/accounts_db.rs
- runtime/src/sorted_storages.rs
> SortedStoragesIter to remove random access requirement

- program-runtime/src/compute_budget.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
> Update syscall base costs

- runtime/src/accounts_db.rs
avoid copy to get data len.
Later, avoid copies while allowing access to append vec account info for hash calc.
Fixes #
> impl ReadableAccount for LoadedAccount

- runtime/src/rent_collector.rs
refactor rent collection into:
1. what to do
2. do it
This allows future calls to be made to just the 'what to do' part.
Fixes #
> refactor rent collection

- poh/src/poh_recorder.rs
- poh/src/poh_service.rs
- runtime/src/bank.rs
`_new_from_parent()` calls taking > 100ms on average
Add timings to debug what's slow
Fixes #
> Add new_from_parent() timings

- ledger/src/blockstore.rs
Add comments for find slot functions.
> (Ledger Store) Add comments for find slot functions.

- ledger/src/blockstore.rs
Add comment blocks for the following public functions in blockstore.rs:
* set_no_compaction
* destroy
* meta
* is_full
* orphan
* max_root
> (Ledger Store) Add comment blocks for six pub functions in blockstore.rs

- web3.js/examples/get_account_info.js
Typo exists in a comment
* Fixes typo in comment
Fixes #N/A
> Fixes typo in example script

- ledger/src/blockstore_processor.rs
- runtime/src/accounts_background_service.rs
- runtime/src/bank.rs
> cleanup api

- send-transaction-service/src/send_transaction_service.rs
RPC STS can resend transactions that are already in its retry queue
Dedupe earlier
cc/ #22828 
closes #22828
> rpc-sts: dedupe before initial send

- program-runtime/src/invoke_context.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/zk-token-proof/src/lib.rs
- runtime/src/builtins.rs
> nit: consistent name

- Cargo.lock
- dos/Cargo.toml
- dos/src/main.rs
No test to dos local cluster.
Add one.
Fixes #
> Dos local-cluster test

- core/src/cluster_nodes.rs
- gossip/src/weighted_shuffle.rs
The same struct is reconstructed for each shred broadcast/retransmit,
which is wasteful.
Instead of reconstructing WeightedShuffle struct for each shred
broadcast or retransmit, we can use the same struct with minimal
mutations.
> caches WeightedShuffle struct in ClusterNodes

- core/src/cluster_nodes.rs
retransmit has to exclude slot leader from set of nodes for each shred;
which currently requires doing a linear search.
https://github.com/solana-labs/solana/blob/e3b137066/core/src/cluster_nodes.rs#L238-L242
Added a reverse lookup index to cluster-nodes mapping pubkeys to their index.
> adds reverse lookup index to cluster-nodes

- core/src/broadcast_stage/broadcast_duplicates_run.rs
> fix typo in broadcast_duplicates_run.rs

- core/src/validator.rs
- rpc/src/rpc.rs
- validator/src/bin/solana-test-validator.rs
#22734 broke `solana-test-validator` 
Fix it
> test-validator-bin: reinstate full rpc method set

- core/src/banking_stage.rs
buffered packets will not be processed if next leader is unknown, even current bank is active. 
- update the consume_or_forward logic
Fixes #
> Allow buffered packets be consumed if bank is active, regardless leader schedule

- core/src/banking_stage.rs
> push live packets straight to buffer (backport #21957)

- programs/zk-token-proof/src/lib.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
Adding `VerifyTransferWithFee` instruction for zk-tokens.
> zk-token-sdk: add verify transfer with fee instruction

- Cargo.lock
- core/src/tpu.rs
- core/src/validator.rs
- gossip/src/cluster_info.rs
- programs/bpf/Cargo.lock
- sdk/src/lib.rs
- sdk/src/quic.rs
- streamer/Cargo.toml
- streamer/src/lib.rs
- streamer/src/quic.rs
See #22726
using quinn library
Fixes #
> Add quic port for accepting transactions

- bench-streamer/src/main.rs
greater than 1 num-recv-sockets doesn't work
producer threads is fixed to 3?
* get the num-recv-sockets working again
* make num producers configurable
Fixes #
> bench-streamer improvements

- ledger/src/blockstore_db.rs
Add some comments to explain why we chose some of DB option values.
In regards to `db_options.set_max_open_files(-1)` being explicitly set for both Primary and Secondary access now, the default is `-1` so we were using `-1` in both cases anyways. Shifting the call makes this more apparent now.
Documentation of these defaults:
https://github.com/facebook/rocksdb/blob/e7ac7363b44163b9b59cd86b639cc05841196d4e/include/rocksdb/options.h#L559
https://github.com/rust-rocksdb/rust-rocksdb/blob/8bf9faddb3b51bd1f1267efbc2037b323b4ba0a4/src/db_options.rs#L1334
> Add some comments for RocksDB option configuration

- ledger/src/blockstore.rs
- ledger/src/blockstore/blockstore_purge.rs
Improve comments for blockstore_purge.
> (Ledger Store) Improve comments for blockstore_purge

- gossip/src/cluster_info.rs
- net-utils/src/lib.rs
Consecutive ports may not be available on the first try.
Try multiple times.
Fixes #
> Search for consecutive ports

- runtime/src/accounts_index.rs
- runtime/src/ancestors.rs
max can mean inclusive or exclusive. Lack of clarity can lead to subtle bugs.
Make it clear that for this data, max is exclusive.
Fixes #
> clarify that RollingBitField max is exclusive

- programs/bpf_loader/src/syscalls.rs
Slice length mismatch could cause panic
Enforce slice length to be equal
Fixes #
> Fix slice length

- runtime/src/accounts_index.rs
eliminate duplicate state
Fixes #
> eliminate separate max root member

- zk-token-sdk/src/instruction/transfer.rs
- zk-token-sdk/src/instruction/transfer_with_fee.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod.rs
Fixing pod for zk-token transfer and transfer with fees.
> zk-token-sdk: fix pod for zk-token transfer

- core/src/banking_stage.rs
Cost model throttled transactions are not filtered at the end of the slot
Remove cost model from consideration in end of slot filtering
Fixes #
> Remove cost model from consideration in end of slot filtering
