solana-labs/solana

runtime/src/bank.rs
=> consolidate Rent construction in test code

runtime/src/rent_collector.rs
consolidate test code to aid refactoring later
Fixes #
=> rent: refactor test function

core/src/ledger_cleanup_service.rs
Improve code comments for ledger_cleanup.
=> (Ledger Cleanup) Improve code comments for ledger_cleanup.

web3.js/src/vote-program.ts, web3.js/test/vote-program.test.ts
Solana-web3.js does not support [`VoteInstruction::Authorize`](https://docs.rs/solana-vote-program/1.9.5/solana_vote_program/vote_instruction/enum.VoteInstruction.html#variant.Authorize).
Support it by adding a constructor and decoder for `VoteInstruction::Authorize`.
Fixes feature request in [#22932 (comment)](https://github.com/solana-labs/solana/pull/22932#pullrequestreview-873547038).
=> feat(VoteProgram): support VoteInstruction::Authorize

runtime/src/bank.rs, runtime/src/rent_collector.rs
prepare for ability for a bank to have a different rent rate than its parent
Fixes #
=> bank::get_rent_collector_from

runtime/src/rent_collector.rs
=> add Debug to RentResult

Cargo.lock, ledger/Cargo.toml
https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.18.0
=> Update rocksdb to 0.18.0 release

docs/src/developing/test-validator.md, validator/src/bin/solana-test-validator.rs
https://github.com/solana-labs/solana/pull/23046
=> v1.9: Add deactivate-feature feature to test validator cli (backport #23041) 

scripts/run.sh
`run.sh` got broken probably after #22734
CC: @t-nelson
=> Add --full-rpc-api to run.sh

streamer/src/streamer.rs
`packet::send_to` sends packets one by one:
https://github.com/solana-labs/solana/blob/9213fcb11/streamer/src/packet.rs#L63-L75
`sendmmsg` uses a single system call for multiple messages:
https://github.com/solana-labs/solana/blob/9213fcb11/streamer/src/sendmmsg.rs#L94
* use sendmmsg in streamer.
=> uses sendmmsg in streamer

bench-tps/src/main.rs, faucet/src/bin/faucet.rs, metrics/src/metrics.rs, validator/src/main.rs, watchtower/src/main.rs
Not immediately clear what version of the code node was running when panicked.
Added validator version to `set_panic_hook`.
=> adds validator version to set_panic_hook

ledger/src/blockstore.rs
Add code comments for SlotMetaWorkingSetEntry.
=> (Ledger Store) Add code comments for SlotMetaWorkingSetEntry.

docs/src/proposals/blockstore-rocksdb-compaction.md
This document explores RocksDB based solutions for Solana BlockStore
mentioned in issue [#16234](https://github.com/solana-labs/solana/issues/16234).
=> Proposal for RocksDB Compaction optimized for Solana BlockStore

core/src/replay_stage.rs, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf/build.rs, programs/bpf/rust/simulation/Cargo.toml, programs/bpf/rust/simulation/src/lib.rs, programs/bpf/rust/simulation/tests/lib.rs, programs/bpf/rust/simulation/tests/validator.rs, rpc/src/rpc.rs, runtime/src/accounts.rs, runtime/src/bank.rs
https://opcodes.fr/en/publications/2022-01/detecting-transaction-simulation/ describes a method to reliably detect when a program is being run under simulation. Render this method ineffective.
=> Add simulation detection countermeasure

rbpf-cli/src/main.rs
rbpf-cli only supports text output, which is hard to parse.
- Adds the `--output <json/json-compact>` flag from Solana CLI.
- Sends all non-structural output to stderr instead of stdout.
Fixes #
=> rbpf-cli: support json output

core/src/banking_stage.rs
When poh's bank is gone, leader's `consume_buffered_packets` would aggressively lock `poh` for remaining packet batches in the buffer, potentially starving replay_stage from setting new bank.
- set end-of-slot flag when poh's bank is gone. 
- replaced tuple with struct.
Fixes #
=> flag end-of-slot when poh bank is gone

validator/src/main.rs
Sometimes you just want to restart without for a new full snapshot
=> solana-validator: Add --skip-new-snapshot-check to exit and wait-for-restart-window subcommands

rbpf-cli/src/main.rs
rbpf-cli always runs StaticAnalysis even when not required.
Some programs are known to hang the analyzer or take long to check.
Wraps `Analysis` in a `LazyAnalysis` that runs the analyzer only on first use. 
Or not at all with default flags.
Fixes #
=> rbpf-cli: only run static analysis when needed

client/src/http_sender.rs, client/src/mock_sender.rs, client/src/rpc_client.rs, rpc/src/rpc.rs, test-validator/src/lib.rs, validator/src/bootstrap.rs, validator/src/main.rs
=> Fix snap server 1.9

runtime/src/in_mem_accounts_index.rs
=> DiskIdx: fix race condition with holding ranges in mem

docs/src/developing/clients/jsonrpc-api.md
Broken/incorrect links.
This PR fixes two links.
=> Fix links in jsonrpc-api.md

Cargo.lock, programs/bpf/Cargo.lock, runtime/Cargo.toml, runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/inline_spl_token.rs, runtime/src/inline_spl_token_2022.rs, runtime/src/lib.rs
token-2022 is now indexed by RPC nodes using the same mechanism as token.
=> accounts_index: Add SPL Token account indexing for token-2022 accounts

programs/zk-token-proof/src/lib.rs, zk-token-sdk/src/instruction/close_account.rs, zk-token-sdk/src/instruction/mod.rs, zk-token-sdk/src/instruction/transfer.rs, zk-token-sdk/src/instruction/transfer_with_fee.rs, zk-token-sdk/src/instruction/withdraw.rs, zk-token-sdk/src/instruction/withdraw_withheld.rs, zk-token-sdk/src/sigma_proofs/equality_proof.rs, zk-token-sdk/src/sigma_proofs/mod.rs, zk-token-sdk/src/zk_token_elgamal/convert.rs, zk-token-sdk/src/zk_token_elgamal/pod.rs, zk-token-sdk/src/zk_token_proof_instruction.rs
Adding zero-knowledge proofs for `WithdrawWithheld` instructions for the spl confidential token extension.
=> Add additional zkp for fee

web3.js/src/stake-program.ts, web3.js/test/stake-program.test.ts
Solana-web3.js `StakeProgram` does not support `split_with_seed`.
- Support `StakeProgram.splitWithSeed`.
- Minor refactor: add `StakeProgram.splitInstruction` to avoid duplicating logic in `StakeProgram.split` and `StakeProgram.splitWithSeed`.
Fixes #23134 
From [#23134 comment](https://github.com/solana-labs/solana/issues/23134#issue-1138251947):
> This means that users cannot perform a split that is signed by a single authority [...]
A signature of _only_ the authority is sufficient if `splitStakePubkey` is derived from `authorizedPubkey`. 
In the test `live staking actions` I've used a `splitStakePubkey` derived from a public key other than `authorizedPubkey`. Then, the transaction returned by `splitWithSeed` must be signed by two keys. The intentation was to avoid the implication …
=> feat(stake-program): support `splitWithSeed`

explorer/src/utils/tx.ts
=> Explorer: Add ed25519 sigverify precompile to search results

Cargo.lock, cli/Cargo.toml, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml, rbpf-cli/Cargo.toml
[solana_rbpf v0.2.24](https://github.com/solana-labs/rbpf/releases/tag/v0.2.24) was released.
Fixes #
=> Bump rbpf to v0.2.24

runtime/src/in_mem_accounts_index.rs
=> DiskIdx: rename 'remove' to 'evict'

.buildkite/hooks/pre-command
hack merged in #23244
revert it
=> ci: revert cache version hack

docs/src/developing/clients/jsonrpc-api.md, docs/src/developing/programming-model/accounts.md, docs/src/developing/programming-model/calling-between-programs.md, docs/src/developing/programming-model/runtime.md, docs/src/developing/programming-model/transactions.md
Some small syntax and grammar issues found in the "Developing -> Programming Model" section of the [docs](https://docs.solana.com/developing/programming-model/overview)  
Made grammar edits to allow the reader an easier time understanding the writer's intentions
Will be continuing to read through the docs as I learn Solana development, will correct other areas if found.
Fixes #
Grammar edits on 5 pages:
[Accounts](https://docs.solana.com/developing/programming-model/accounts) page
[Runtime](https://docs.solana.com/developing/programming-model/runtime) page
[Calling-between-programs](https://docs.solana.com/developing/programming-model/calling-between-programs) page
[Transactions](https://docs.solana.com/developing/programming-model/transactions) page
[JSON RPC …
=> Grammar corrections

docs/src/integrations/exchange.md
Exchange integration docs are unclear as to how to detect deposits into newly created SPL Token accounts
Add a note
=> docs: clarify spl token account creation handling for exchange integrations

core/src/progress_map.rs, ledger/src/blockstore_processor.rs, program-runtime/src/timings.rs, runtime/src/bank.rs
=> Fix rustfmt check

validator/src/bin/solana-test-validator.rs, validator/src/main.rs
Unhide AccountsDb plugin parameters from the validator and test validator.
Fixes #
=> Unhide AccountsDb plugin parameters

docs/src/developing/clients/jsonrpc-api.md, docs/src/developing/programming-model/accounts.md, docs/src/developing/programming-model/runtime.md, docs/src/developing/programming-model/transactions.md
A couple of notes missed when making last PR
Made edits/fixes where recommended
Fixes # 
Check PR #23206 and comments under it for more specifics
=> Grammar corrections PR#23206 Review Fixes

test-validator/src/lib.rs, validator/src/bin/solana-test-validator.rs
https://github.com/solana-labs/solana/pull/23194#discussion_r811564578
Fixes #
=> started_from_validator, ignore env var for cli

runtime/src/accounts_db.rs
a straggler from the last refactor
Fixes #
=> fix params for store_accounts_frozen

ledger-tool/src/main.rs, validator/src/main.rs
=> add arg --disable-accounts-disk-index

docs/src/integrations/exchange.md
Mergify beat me to addressing review on #23286
address review
=> docs: post merge review for #23286

programs/config/src/config_processor.rs
https://github.com/solana-labs/solana/pull/23056 is too big, so this is another spin off.
Replaces `KeyedAccount` by `BorrowedAccount` in the config processor.
Fixes #
=> Replaces `KeyedAccount` by `BorrowedAccount` in the config processor.

runtime/src/storable_accounts.rs
=> slot per account in StorableAccounts

ledger/src/blockstore.rs, test-validator/src/lib.rs, validator/src/bin/solana-test-validator.rs
=> all TestValdiators act like validators

bench-tps/src/bench.rs, ci/docker-rust-nightly/Dockerfile, ci/docker-rust/Dockerfile, ci/rust-version.sh, core/src/heaviest_subtree_fork_choice.rs, core/src/repair_weight.rs, perf/src/sigverify.rs, rpc/src/rpc.rs, scripts/coverage.sh, streamer/src/sendmmsg.rs
=> bump rust to 1.59.0

runtime/src/in_mem_accounts_index.rs
=> list -> slot_list

runtime/src/accounts_index.rs
=> acct idx comments

runtime/src/in_mem_accounts_index.rs
=> acct idx comment

runtime/src/bank.rs
this test is cumbersome to work on with its hard coded vars.
Fixes #
=> refactor test

runtime/src/bank.rs
=> refactor rent test

explorer/src/components/SolanaPingCard.tsx, explorer/src/pages/ClusterStatsPage.tsx, explorer/src/providers/stats/SolanaPingProvider.tsx, explorer/src/providers/stats/index.tsx
It would be nice to show Solana Ping API metrics in Explorer.
Adds Solana Ping bar chart to cluster stats page.
Fixes #
=> feat(explorer): add Solana Ping to cluster stats page

explorer/src/pages/ClusterStatsPage.tsx, explorer/src/providers/stats/index.tsx
We're going to rollback the ping feature in Explorer until the API is more stable.
Rollback changes.
Fixes #
=> fix(explorer): rollback ping until api is more stable

runtime/src/rent_collector.rs
trying to eliminate arbitrary multi-epoch gaps in rent collection from tests
Fixes #
=> tweak 2 rent tests to narrow epoch ranges

explorer/src/components/SolanaPingCard.tsx
Purple is too obnoxious. 
Red over 50% loss.
Fixes #
=> fix(explorer): remove purple from ping

runtime/src/accounts_db.rs
quite useful from ledger tool and validator when tracking down consistency issues
Fixes #
=> log hash and lamport result of calculate_accounts_hash_without_index

runtime/src/bank.rs
=> rework test to avoid multi-epoch gap

core/src/packet_threshold.rs, runtime/src/bank.rs
=> minor test cleanup

docs/src/cluster/rpc-endpoints.md
Too many developers think that public RPC services are suitable for production applications.
Add some comments & disclaimers to the docs.
=> Adds comments related to the public RPC endpoints

runtime/src/rent_collector.rs
=> 2 more rent collection tests don't skip epochs

programs/bpf_loader/src/allocator_bump.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/serialization.rs, programs/bpf_loader/src/syscalls.rs
The loader uses raw arithmetic but coding policy states that safe arithmetic should be used
Switch over to safe arithmetic operations
Fixes #
=> use saturating arithmetic

explorer/src/components/SolanaPingCard.tsx
Average Confirmation Time is not the correct term
Fixes #
=> fix(explorer): change title to average ping time

.github/workflows/explorer_preview.yml, .github/workflows/explorer_production.yml
=> fixing the vercel " promote to production" issue

.github/workflows/explorer_preview.yml, .github/workflows/explorer_production.yml, explorer/.gitignore
=> add comment to trigger the file to check the previous merge

explorer/.gitignore
=>  resolving promote to prod issue

explorer/.gitignore
=> testing latest changes on explorer

Cargo.lock, programs/bpf/Cargo.lock
=> sha-2:0.9.8 yanked, bump to 0.9.9

zk-token-sdk/src/encryption/discrete_log.rs, zk-token-sdk/src/encryption/elgamal.rs, zk-token-sdk/src/errors.rs, zk-token-sdk/src/instruction/transfer.rs, zk-token-sdk/src/instruction/transfer_with_fee.rs, zk-token-sdk/src/range_proof/inner_product.rs, zk-token-sdk/src/sigma_proofs/equality_proof.rs, zk-token-sdk/src/zk_token_elgamal/decryption.rs, zk-token-sdk/src/zk_token_elgamal/mod.rs
Adding ElGamal decryption for pod ElGamal ciphertexts.
=> Zk token sdk clean decryption

core/src/snapshot_packager_service.rs, core/tests/snapshots.rs, runtime/src/snapshot_utils.rs
Rename FILENAME to be consistent. 
Fixes #
=> rename status filename to be consistent

Cargo.lock, programs/bpf/Cargo.lock, storage-bigtable/build-proto/Cargo.lock
=> Update regex to v1.5.5

programs/bpf_loader/src/syscalls.rs, sdk/src/feature_set.rs
Some new saturated math requires featurization
Add it
Fixes #
=> featurize loader sat math

validator/src/bootstrap.rs
When incremental snapshots are enabled, bootstrapping may fail when getting the golden snapshot hashes from the known validators. This triggers an erroneous assert.
When getting the golden snapshot hashes, now ensure:
* A node's base snapshot hash exists in its full snapshot hashes
* If the golden snapshot hashes already has an entry for the full snapshot hash, do not reinitialize it's incremental snapshot hashes set back to zero...
Additionally:
* Refactor code to be testable
* Added test
Fixes #23509
Note: I'm not sure how helpful the diff will be here... It may be easiest/best to view the file and review the contents of `get_golden_snapshot_hashes_from_known_validators()` and `get_golden_snapshot_hashes()`.
=> Fix getting the golden snapshot hashes during bootstrap with Incremental Snapshots

core/src/replay_stage.rs, validator/src/admin_rpc_service.rs
Rework the set identity checks slightly to avoid writing a tower file for a validator that is not actively voting.  
This prevents a validator from exiting unnecessarily when 
https://github.com/mvines/validator-Identity-transition-demo#step-2-move-your-primary-validator-to-the-unstaked-identity is performed a second time after a couple days
=> `solana-validator set-identity` no longer writes a tower file unnecessarily

core/src/banking_stage.rs, core/src/cost_update_service.rs, core/src/tvu.rs, runtime/src/cost_model.rs, runtime/src/execute_cost_table.rs
Exponential moving average for cost computation: https://github.com/solana-labs/solana/pull/22286 has a bug that causes cost of programs to become too large.
Revert changes for now 
Fixes #
=> Revert exponential moving average cost model changes

Cargo.lock, rbpf-cli/Cargo.toml, rbpf-cli/src/main.rs, sdk/cargo-build-bpf/Cargo.toml, sdk/cargo-build-bpf/src/main.rs, sdk/cargo-test-bpf/Cargo.toml, sdk/cargo-test-bpf/src/main.rs
=> Update clap for all bpf utils

core/src/cost_update_service.rs, core/src/validator.rs
CI is slow and I'm impatient
Manually backport https://github.com/solana-labs/solana/pull/23530
=> Validator skip persisted cost table 1.9

ledger/src/blockstore_db.rs
Some cleanup changes to reduce the diff in https://github.com/solana-labs/solana/pull/23391. These changes should not affect functionality.
=> Cleanup several blockstore functions

programs/bpf_loader/src/syscalls.rs, sdk/src/feature_set.rs
Calls to `memcpy` check for region overlap, but just in the virtual space
Also check the physical addresses
Fixes #
=> Check for physical region overlap

programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/serialization.rs, programs/bpf_loader/src/syscalls.rs
Slice indexing could lead to a panic.
As a policy don't use anywhere in the loader, and enforce that policy
Fixes #
=> deny slice indexing

ledger/src/blockstore.rs
This PR generalizes RocksDB metric reporting macro so that future RocksDB metrics can reuse the same macro.
=> (LedgerStore) Generalize RocksDB metric reporting macro

zk-token-sdk/src/instruction/transfer.rs
Fixing an edge case issue with current range proof.
=> zk-token-sdk: fixing a range proof edge case

system-test/testnet-automation.sh
=> add script for the traceability

runtime/src/in_mem_accounts_index.rs
It's not hard to misuse `flushing_active`. Either by forgetting to set/unset, or by calling flush functions that require `flushing_active` to be set correctly.
- Add a Flush Guard RAII type for `flushing_active`.
- Update `flush_internal()` to take a `&FlushGuard` parameter to ensure that `flushing_active` has been set correctly prior to executing.
=> Add FlushGuard to ensure `flushing_active` is used safely

runtime/src/accounts_db.rs
=> remove unnecessary namespaces

program-runtime/src/invoke_context.rs, programs/bpf_loader/src/lib.rs, runtime/src/bank.rs
Nit: jit flag is passed twice which could lead to runtime mismatch as code evolves
Consolidate it to a single setting
Fixes #
=> consolidate use-jit flag

ledger/src/shred.rs
signing_coding_time on shredder is not being used.
Fixes #
=> small cleanup

validator/src/bootstrap.rs
Comments in bootstrap were out-of-sync with the code.
Removed the outdated comments.
Fixes #23625
=> Fix comments in bootstrap for downloading snapshots

runtime/src/bank.rs
=> move to get_slots_in_epoch

explorer/src/utils/tx.ts
N/A
Add Swim Protocol's ([swim.io](https://swim.io/)) Swap Program to known addresses. Our address: https://explorer.solana.com/address/SWiMDJYFUGj6cPrQ6QYYYWZtvXQdRChSVAygDZDsCHC
Fixes #
N/A
=> Add Swim Swap Program to known addresses

core/src/replay_stage.rs, core/src/tvu.rs
Minor improvements I stumbled across while reading
=> core/src/{replay_stage,tvu}.rs: little nits

core/src/system_monitor_service.rs, core/src/validator.rs, ledger-tool/src/main.rs, local-cluster/src/validator_configs.rs, validator/src/main.rs
The os memory stats are pretty spammy, add a flag to disable them
=> Add --no-os-memory-stats-reporting

runtime/src/vote_account.rs
use trait so we can generalize underlying type
Fixes #
=> minor VoteAccount refactoring

Cargo.lock
=> Bump openssl-src

ledger/src/blockstore_db.rs
As we start adding more options into BlockstoreOptions, it's better to allow
`new_cf_descriptor` to take the reference to BlockstoreOptions so that
we can avoid future function API changes on `new_cf_descriptor`.
=> (LedgerStore) Improve the function API of new_cf_descriptor

programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs
If the minimum stake delegation is increased, many of the stake tests break.
Update the tests to use `MINIMUM_STAKE_DELEGATION`. (Mostly just use/add `MINIMUM_STAKE_DELEGATION` for/to the existing stake amount.)
Also tested locally by changing the minimum stake delegation constant to multiple values: 1, 100_123_456_789.
=> Stake tests respect MINIMUM_STAKE_DELEGATION

runtime/src/in_mem_accounts_index.rs
if we need to get a read lock to the slot list to determine we should flush it, then keep that read lock open until we're done writing to disk.
Fixes #
=> acct idx flush keeps slot_list read lock open

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
=> AcctIdx: add stats for flushing and estimated memory

Cargo.lock, frozen-abi/Cargo.toml, frozen-abi/src/abi_example.rs, programs/bpf/Cargo.lock, sdk/src/account.rs
=> AccountSharedData::serialize

frozen-abi/src/abi_example.rs, sdk/src/account.rs
=> clean up/add comments

runtime/src/accounts_db.rs
=> factor out function

core/src/unprocessed_packet_batches.rs
Iterating UnprocessedPacketBatches buffer batch by batch limits us from implementing Leader QoS algorithm based on individual transactions. 
Having a method to examine _all_ unprocessed packets in buffer at once, instead of per batch, also helps produce better loaded entries. 
- Introduce struct `PacketLocator` as a cheap way to reference to individual packet in UnprocessedPacketBatches buffer, where packets are stored in batches.
- Add function to scan entire buffer for unprocessed packets, return their locators and sender's stakes. 
Fixes #
=> Indexes individual packets from unprocessed_packet_batches buffer

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
=> AcctIdx: remove -> evict

programs/bpf/rust/invoke/src/processor.rs
=> Fix typo in processor.rs

runtime/src/bank/sysvar_cache.rs
In `test_sysvar_cache_initialization()`, the `bank1_sysvar_cache` variable was set from _`bank0`'s_ `.sysvar_cache`. So the assertions in the test were incorrect.
* Updated the `bank1_sysvar_cache`, and other incorrect variables.
* Bank0 and Bank1 have different Fees, so (1) fixed that assertion, and then added a Bank2 to ensure Bank1 fees and Bank2 fees are equal
* Also, with a bank2, added an assertion for the slot hashes.
=> Fix bug in bank/sysvar_cache tests

runtime/src/in_mem_accounts_index.rs
=> AcctIdx: factor 'scan' out of flush_internal

ci/buildkite-pipeline-in-disk.sh, ci/buildkite-pipeline.sh
=> Increased timeout limit of coverage and stable-perf by 10 mins each

runtime/src/in_mem_accounts_index.rs
=> AcctIdx: fix infinite loop

zk-token-sdk/src/errors.rs, zk-token-sdk/src/instruction/mod.rs, zk-token-sdk/src/instruction/transfer.rs, zk-token-sdk/src/instruction/transfer_with_fee.rs, zk-token-sdk/src/sigma_proofs/fee_proof.rs
There were some missing cases for transfer with fee proof verification. 
Fixed the issue and added more tests for edge cases.
=> zk-token-sdk: handle edge cases for transfer with fee

runtime/src/in_mem_accounts_index.rs
=> AcctIdx: only remove a fixed number of items per write lock

core/src/banking_stage.rs
1. fix typos
2.  remove packet_has_more_unprocessed_transactions
Fixes #
=> Fix typos and a small refactor

Cargo.lock, programs/bpf/Cargo.lock, send-transaction-service/Cargo.toml, send-transaction-service/src/send_transaction_service.rs
Use the connection cache when sending transactions
=> Use connection cache in send transaction

runtime/src/in_mem_accounts_index.rs
=> AcctIdx: rework scan and write to disk

runtime/src/accounts_db.rs
if/when we start smashing multiple slots into 1 when we flush the write cache of roots, then it becomes very complicated to remain correct if we are flushing random roots.
see: #23197 for more context
This pr is part of that.
Fixes #
=> remove random flushing of write cache

explorer/src/components/instruction/token/types.ts
Sync Native is currently unsupported.
Add this to the token program validation / decoding. 
Fixes #
=> fix(explorer): add sync native to token program decode

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
1st change using the &self we pass to CalcHash
Fixes #
=> calc hash uses self.thread_pool_clean

runtime/src/accounts_db.rs
=> small refactor to shorten the lock on slot_under_contention hashset

core/src/accounts_hash_verifier.rs, core/src/tvu.rs, core/tests/snapshots.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> HashCalc uses self.accounts_hash_cache_path

runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
new features coming could drastically change the distribution of sizes of storages during runtime and in snapshots.
Fixes #
=> Log storage size stats at hash calc

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> calc hash uses self.num_hash_scan_passes

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> hash calc uses self.filler_account_suffix

runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> HashCalc uses self.accounts_index

runtime/src/accounts_db.rs
This refactoring prepares for the ability to squash multiple slots into 1 append vec when we're doing a cache flush.
Fixes #
=> flush_slot_cache takes [Slot]

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> HashCalc uses self.accounts_cache

runtime/src/accounts_db.rs
When we flush multiple slots from the cache into a single append vec, we need per-slot 'clean' behavior. It is helpful to have the max_clean_root check deeper in the call chain.
Fixes #
=> move max_clean_root deeper in flush cache

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> pass stats separately from CalcAccountsHashConfig

explorer/src/components/SolanaPingCard.tsx
When the ping collection halts, it looks like the cluster is experiencing problems
Show ping statistics unavailable for missing metrics
Fixes #
=> feat(explorer): show ping server metrics unavailable

Cargo.lock, programs/bpf/Cargo.lock, send-transaction-service/Cargo.toml, send-transaction-service/src/send_transaction_service.rs
Merge Use connection cache in send transaction (#23712) to v1.10
=> Use connection cache in send transaction (#23712)

core/src/accounts_hash_verifier.rs, runtime/src/snapshot_package.rs
=> rename 'accounts' hash

core/src/accounts_hash_verifier.rs
update stats from ahv just like we do for the normal code paths.
Fixes #
=> make verify_accounts_package_hash like other hash calc

cli/src/stake.rs, cli/src/vote.rs
cli plumbing needed to reach https://github.com/solana-labs/solana/commit/65f1e0fcc24379dd04909274d1f3b6af479530e4
=> cli: `vote-authorize-voter` now accepts either the vote or withdraw authority

runtime/src/rolling_bit_field.rs
This functionality will be used when we eliminate rewrites and have to maintain `roots_original`. We need to keep track of slots that used to be roots. At some point, we need to clean those slots up. This function is what is required to remove all the oldest items from a `RootsTracker`.
#23849
Fixes #
=> RollingBitField::get_all_less_than

cli/src/cli.rs, cli/src/program.rs, cli/tests/program.rs, transaction-dos/src/main.rs
https://github.com/solana-labs/solana/pull/23942 for v1.10
=> cli: allow skipping fee-checks when writing program buffers (hidden)

web3.js/src/connection.ts, web3.js/test/connection.test.ts
[getBlockProduction](https://docs.solana.com/developing/clients/jsonrpc-api#getblockproduction) RPC call was missing in web3.js
- adds getBlockProduction function in `connection.ts`
- adds unit test for getBlockProduction
=> feat: adds getBlockProduction RPC call

runtime/src/accounts_db.rs, runtime/src/sorted_storages.rs
=> use CalcAccountsHashConfig in calculate_accounts_hash

runtime/src/sorted_storages.rs
=> refactoring of SortedStorages tests to make other changes easier

runtime/src/accounts_db.rs, runtime/src/sorted_storages.rs
=> SortedStorages refactoring

runtime/src/sorted_storages.rs
=> fix typo in comments

Cargo.lock, programs/bpf/Cargo.lock, programs/bpf/rust/sanity/src/lib.rs, programs/bpf/tests/programs.rs, programs/bpf_loader/src/syscalls.rs, sdk/program/Cargo.toml, sdk/program/src/program.rs
CPI makes some assumptions about type layout
Assert that they are what is expected
Fixes #23749
=> assert type assumptions

runtime/src/snapshot_package.rs
File name is changing and will affect this code. This change makes it less brittle to change the file name.
Fixes #
=> AccountsPackage::new less brittle

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
This cleanup adds clarity and removes some nasty lifetime issues that other refactoring exposed.
Fixes #
=> add hash calc config.use_write_cache

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> calculate_accounts_hash_helper uses config

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/0-general.md, .github/ISSUE_TEMPLATE/1-feature-gate.yml, .github/PULL_REQUEST_TEMPLATE.md
Lack of feature gate tracking process
- Add new issue template for "feature gate tracking issues"
- Request feature gate tracking issue number in pull request template 
Fixes #
=> Add issue template for feature gate tracking issues

rpc/src/rpc_completed_slots_service.rs
This is a follow up pull request from https://github.com/solana-labs/solana/pull/24036 to address the comments by @[jbiseda](https://github.com/jbiseda).
When channel is disconnected, we should exit RpcSlotCompleteService.
Fixes #
=> Handle channel disconnect in RpcSlotCompleteService

client/src/thin_client.rs, runtime/src/bank_client.rs, sdk/src/client.rs
The `AsyncClient` trait implemented by `BankClient` and `ThinClient` doesn't support sending versioned transactions. Those clients are primarily used by benchmarks so adding support allows versioned transactions to be sent during benchmarks.
- Added `async_send_versioned_transaction` and `async_send_versioned_transaction_batch` methods to the `AsyncClient` trait
- Moved duplicated trait method implementations for `async_send_message`, `async_send_instruction`, and `async_transfer` to the default implementation of the `AsyncTrait`
Fixes #
=> Support sending versioned txs in AsyncClient

docs/src/running-validator/validator-failover.md
Just a typo in the documentation
Fixed one word.
=> Fixed a typo in the docs

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/serde_snapshot/newer.rs
=> root -> alive_root

runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/newer.rs
=> prior_roots -> historical_roots

runtime/src/stakes.rs
`Stakes::activate_epoch` can be done faster.
Tested with mainnet stakes obtained from the ledger at 5 recent epoch
boundaries, this code is ~30% faster than current master.
Current code:
```
epoch: 289, elapsed: 82901us
epoch: 290, elapsed: 80525us
epoch: 291, elapsed: 79122us
epoch: 292, elapsed: 79961us
epoch: 293, elapsed: 78965us
```
This commit:
```
epoch: 289, elapsed: 61710us
epoch: 290, elapsed: 55721us
epoch: 291, elapsed: 55886us
epoch: 292, elapsed: 55399us
epoch: 293, elapsed: 56803us
```
=> improves Stakes::activate_epoch performance

runtime/src/accounts_db.rs
ReadableAccount trait was recently impl'd for &StoredAccountMeta.
So, we can localize the decoding of StoredAccountMeta into where it is already happening and remove duplicate decodings.
Fixes #
=> remove basically duplicate function

runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/newer.rs, runtime/src/serde_snapshot/tests.rs
=> persist historical_roots

ledger/src/blockstore_db.rs
Previously, the metric reporting functions are implemented under LedgerColumnMetric.
However, there're operations like write batch which is issued by the function inside Rocks.
This PR moves reporting functions to its own dedicate mod so that both LedgerColumn and
Rocks can report column perf metrics.
=> (LedgerStore)(Refactor) Move metric reporting functions to a dedicate mod

programs/vote/src/vote_processor.rs
`verify_rent_exemption()` has only one call site.
Inlines `verify_rent_exemption()` in vote_processor.rs
=> Inlines verify_rent_exemption() in vote processor

ledger/src/blockstore_db.rs
This PR enables the reporting of both RocksDB read and write perf metrics for ProtobufColumns,
including TransactionStatus and Rewards. 
This PR is based on top of #24061, #24060, #23951, and #23834.
=> (LedgerStore) Report RocksDB perf metrics for ProtobufColumns

runtime/src/append_vec.rs
=> Add test cfg attribute

runtime/src/in_mem_accounts_index.rs
=> move around some index metrics to reduce locks

runtime/src/bank.rs
track end of epoch rewards distribution. Used to evaluate various strategies and identify hotspots.
Fixes #
=> add metrics around rewards

sdk/program/src/lib.rs
There was a typo in solana-program's lib.rs.
Fixed the typo.
Fixes #
=> Fix typo in solana-program lib.rs

ledger/src/blockstore_db.rs
This PR enables perf metrics reporting for RocksDB write-batches.
Samples are reported under "blockstore_rocksdb_write_perf" with op=write_batch
Its cf_name tag is set to "write_batch" as well as each writebatch could include multiple column families.
The sampling rate is still controlled by env arg SOLANA_METRICS_ROCKSDB_PERF_SAMPLES_IN_1K
and its default to 10 (meaning we report 10 in 1000 perf samples).
This PR is based on top of #24060 and #23951.
=> (LedgerStore) Report perf metrics for RocksDB write batches

Cargo.lock, core/Cargo.toml, ledger/Cargo.toml, replica-lib/Cargo.toml, replica-node/Cargo.toml, storage-bigtable/Cargo.toml, storage-bigtable/build-proto/Cargo.lock, storage-bigtable/build-proto/Cargo.toml, storage-bigtable/build-proto/src/main.rs, storage-bigtable/proto/google.api.rs, storage-bigtable/proto/google.bigtable.v2.rs, storage-bigtable/proto/google.rpc.rs, storage-proto/Cargo.toml, storage-proto/build.rs
https://github.com/solana-labs/solana/pull/24147 for v1.9
=> v1.9: Bump tonic, tonic-build, prost, and etcd-client

programs/stake/src/stake_state.rs
`get_if_mergeable()` in the stake builtin program still has a `KeyedAccount` parameter.
Use two explicit parameters instead:
- `stake_state: &StakeState,`
- `stake_lamports: u64,`
=> Removes `KeyedAccount` parameter from `get_if_mergeable()`

validator/src/bootstrap.rs
Problem
We ignore --only-known-rpc when --no-snapshot-fetch is passed.
Filter the list based on only-known-rpc  before checking no-snapshot-fetch
Fixes#
#23179
=> filter the list before checking --no-snapshot-fetch

core/src/leader_slot_banking_stage_timing_metrics.rs
commit metric is incremented twice
remove duplicate increment
Fixes #
=> Remove duplicate increment of commit metric

sdk/program/src/lib.rs
Fixed typo.
```
recieved -> received
```
Fixes #
=> sdk: fix typo in lib.rs

runtime/benches/bank.rs, runtime/src/bank.rs
Move test only function into *test_util* scope to avoid the clutter of actual bank APIs.
Fixes #
=> Refactor: move test function into test_util mod

Cargo.lock, cli/Cargo.toml, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/lib.rs, rbpf-cli/Cargo.toml
=> Bump solana-rbpf to v0.2.25

runtime/src/accounts_background_service.rs, runtime/src/bank.rs, runtime/src/snapshot_package.rs
=> remove clone

runtime/src/waitable_condvar.rs
=> document WaitableCondvar

programs/stake/src/stake_instruction.rs
The GetMinimumDelegation stake instruction does not require a stake account, but the stake program's `process_instruction()` checks for a stake account before any instruction-specific code.
Only check for a stake account if the instruction is _not_ GetMinimumDelegation.
=> GetMinimumDelegation does not require a stake account

ci/docker-rust-nightly/Dockerfile, ci/docker-rust-nightly/build.sh, ci/docker-rust/Dockerfile, ci/docker-rust/build.sh, ci/rust-version.sh, core/src/tower_storage.rs, metrics/src/metrics.rs, net-utils/src/ip_echo_server.rs, sdk/program/src/sysvar/mod.rs
=> Upgrade to Rust 1.60.0

measure/src/macros.rs
Update and expand the documentation for `measure!()`.
=> Update docs for measure!()

accounts-bench/src/main.rs, runtime/benches/accounts.rs, runtime/src/accounts.rs, runtime/src/serde_snapshot/tests.rs
=> move test fn into its own mod

program-runtime/src/invoke_context.rs, sdk/src/transaction_context.rs
Stackframe is deprecated and will hopefully soon go away
Move some members out and into invoke context
Fixes #
=> migrate memberes from deprecated structs

.mergify.yml
This PR https://github.com/solana-labs/solana/pull/24270 broke automated review requests for community PR's
Fix it
=> Fix community PR review requests

programs/bpf_loader/src/lib.rs, sdk/src/feature_set.rs
Callx r10 (stack pointer) instructions don't make sense and should be rejected.
Featurize the rejection
Fixes #
Feature Gate Issue: #24310
=> featurize rejection of callx r10 instructions

web3.js/src/connection.ts
Transaction simulation overrides transactions fields which can be surprising to developers.
- Create a shallow copy of a transaction during simulation so that the original transaction is not modified
- Revert change from https://github.com/solana-labs/solana/pull/24280 because it breaks existing behavior and causes tests to hang: https://app.travis-ci.com/github/solana-labs/solana-web3.js/builds/249335080
Fixes #
=> fix: do not modify transaction during simulation

runtime/src/expected_rent_collection.rs
=> check for rewrites skipped in closure

.mergify.yml
Automerge bot is failing in CI. Seems indentation problem with the YAML file.
Fixed the YAML file.
=> Fix merge Yaml file

rpc/src/rpc_subscriptions.rs
`rpc_subscriptions_recent_items` datapoint is submitted once per subscription event, which in practice is very frequent.
gate to one submission ever 2s
=> rpc-pubsub: reduce metrics/log spam

runtime/src/expected_rent_collection.rs
=> SlotInfoInEpoch

web3.js/src/connection.ts
See #24366 proposed solution 1
Add optional fetch function to `Connection` constructor arguments
=> feat: support overriding fetch function in Connection

scripts/build-downstream-projects.sh
Downstream build was broken and fixed with #24403 and #24328
Backport the fix.
Fixes #
=> v1.10-ci: Fix downstream build

cli/src/program.rs, docs/src/cli/deploy-a-program.md
Fixes https://github.com/solana-labs/solana/issues/24418
=> cli: Fix resume deploy directions

perf/src/sigverify.rs
=> Use Packet::from_data() to remove repeated logic

core/src/serve_repair.rs
=> Move repeated logic into common function

runtime/src/expected_rent_collection.rs
=> remove redundant EpochSchedule

core/src/retransmit_stage.rs, gossip/src/cluster_info.rs, gossip/src/cluster_info_metrics.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_pull.rs, gossip/src/lib.rs, gossip/tests/crds_gossip.rs, gossip/tests/gossip.rs
Counters are noisy and have extra overhead: https://github.com/solana-labs/solana/issues/24319
Replaced counters with datapoints.
=> replaces counters with datapoints in gossip metrics

streamer/src/quic.rs
=> patches v1.10 build breakage

runtime/src/expected_rent_collection.rs
rename for clarity, preparing for refactor
Fixes #
=> rename local: max_slot_in_storages -> inclusive

runtime/src/accounts_db.rs
https://github.com/solana-labs/solana/issues/24457
Fixes #
=> demote shink counter to debug

runtime/src/accounts.rs, runtime/src/accounts_db.rs, runtime/src/bank.rs, runtime/src/serde_snapshot/tests.rs
=> bank_hash_at uses rewrites

core/src/broadcast_stage/standard_broadcast_run.rs, core/src/shred_fetch_stage.rs, ledger/src/lib.rs, ledger/src/shred.rs, ledger/src/shred_stats.rs
simplifying the code for upcoming changes to shreds struct
moved shred stats to a separate file
=> moves shred stats to a separate file

runtime/src/accounts_db.rs, runtime/src/expected_rent_collection.rs
=> max_slot_in_storages_exclusive -> INclusive

streamer/src/quic.rs
There are a few conditions in quic streamer where the connection setup can fail. Need metrics to track such occurences.
Added `datapoint` for two such conditions.
Fixes #
=> Add some datapoints in quic for error conditions

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
=> add historical_roots_len stat

core/src/tvu.rs, core/src/validator.rs, core/tests/snapshots.rs, ledger-tool/src/main.rs, ledger/src/bank_forks_utils.rs, ledger/src/blockstore_processor.rs, local-cluster/src/validator_configs.rs, local-cluster/tests/local_cluster.rs, runtime/src/accounts_background_service.rs, runtime/src/runtime_config.rs, test-validator/src/lib.rs, validator/src/main.rs
https://github.com/solana-labs/solana/pull/23852 has accumulated too many preamble commits.  Shed them here as they're mostly just uninteresting code cleanup and other refactoring
=> Various core valdiator.rs refactoring 

runtime/src/expected_rent_collection.rs
=> remove temp dead_code markers

runtime/src/accounts.rs, runtime/src/bank.rs
=> type PubkeyAccountSlot

core/src/validator.rs
The `LoadingLedger...` phase of `solana-validator monitor` takes forever and one tends to start looking at the raw validator log in an attempt to glean more information regarding the startup status.  After the bank state is restored and blockstore is being processed, this PR adds user feedback about the latest slot that's been processed and how many slots remain.
=> solana-validator monitor now reports slot-level progress while loading blockstore

core/src/window_service.rs
=> demote receive_window_num_slot_shreds to debug logging

ledger-tool/src/main.rs, runtime/src/accounts_db.rs, validator/src/main.rs
will be connected up shortly
Fixes #
=> validator option: --accounts-db-skip-rewrites

explorer/src/components/SolanaPingCard.tsx
Per discord discussion, we're going to show 25-50% as orange
=> feat(explorer): show orange for 25-50 percent ping loss

runtime/src/accounts_db.rs
=> implement remove_old_historical_roots

runtime/src/bank.rs
log # of skipped rewrites when we collected rent on a bank
Fixes #
=> stats for rewrites

runtime/src/append_vec.rs
=> append_vec::remaining_bytes

runtime/src/bank.rs
Months of work to get here... When `--accounts-db-skip-rewrites` is specified to ledger-tool or validator, rewrites during rent collection are skipped.
Note that this produces snapshots which will be invalid contents for older validators. One failure will be in verifying the accounts hash of the snapshot. A second failure will be in bank hash when a bank loads and store an account which had a rewrite skipped and `rent_epoch` wasn't updated.
Now that this option is available, this will be run on test validators and work out a few more details (like squashing of really old (ie. ancient) slots).
Fixes #
=> eliminate rewrites with cli option

ledger/src/shred.rs
fix for test_shred_fec_set_index test case
Fixes #
=> test_shred_fec_set_index fix

runtime/src/storable_accounts.rs
=> provide default impl of 'is_empty'

docs/src/terminology.md
It is not clear that SPL has separate documentation
Add a link to the SPL documentation
Fixes #
=> Link to SPL documentation in terminology page

web3.js/scripts/typegen.sh
@t-nelson with the intel: https://github.com/solana-labs/solana/pull/24519#issuecomment-1104413370
=> `yarn type:gen` now works on BSD/GNU without hacks

.github/workflows/export-github-repo.yml
=> fix export-github-repo action

.github/workflows/export-github-repo.yml
1. fetch full git history of solana
2. use python3
=> fix(ci): export github repo action

cli/src/feature.rs
there is an effort underway to retain feature set entries indefinitely, but the very old ones are irrelevant to most
hide `solana feature status` entries that have been activated 15M+ slots (~90days) ago
=> Cli limit features

runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
add some stats on ancient slots & append vecs
Fixes #
=> metrics on ancient slots

runtime/src/stake_account.rs, runtime/src/vote_account.rs, sdk/src/account.rs
=> cleanup in vote/stake accounts

web3.js/.github/cicd.yml
I don't have a permission to access secrets. Could someone help me to check:
1. `NPM_TOKEN` exist
2. `PAT` has permission can push a workflow upgrade to web3 mirror project
=> feat(ci): mirgrate web3.js travis job to github action

runtime/src/active_stats.rs
this can take a while and be expensive.
It is useful to report when it is active.
the squash to ancient code is forthcoming.
Fixes #
=> add state for squash ancient

runtime/src/accounts_db.rs
lookup + insert becomes just insert
Fixes #
=> some cleanup

perf/src/packet.rs
Use more descriptive variable names
=> Variable renames for readability

Cargo.lock, cli/Cargo.toml, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls.rs, rbpf-cli/Cargo.toml
constructed by @Lichtso 
recommended by @mvines 
needed by @jeffwashington 
Fixes #
=> revert #24546

runtime/src/bank.rs
=> fix test_rent_eager_collect_rent_in_partition

explorer/src/pages/AccountDetailsPage.tsx
There have been quite a few reports of people creating tokens and then being confused by the disclaimer on their own token. 
Added some additional information + a CTA to verify based on feedback
=> fix: Update custom metadata token disclaimer

bench-tps/src/bench.rs
sending each transaction one-by-one is slow
Use batch mode to send faster
Fixes #
=> Use batch send instead of individual send when funding bench-tps

ledger/src/lib.rs, ledger/src/shred.rs, ledger/src/shredder.rs
Working towards embedding versioning into shreds binary; so Shredder can
no longer depend on internals of Shred.
Moved shredder out of the shred module
=> moves shredder out of the shred module

core/benches/sigverify_stage.rs, core/src/sigverify_stage.rs, core/src/tpu.rs, core/src/tvu.rs
All sigverify stage metrics come in one label
Separate them out so that TPU/TVU/TPU-vote is visible
Fixes #
=> Separate sigverify metrics for each verifier

explorer/src/components/block/BlockHistoryCard.tsx, explorer/src/components/transaction/ProgramLogSection.tsx, explorer/src/pages/inspector/SimulatorCard.tsx, explorer/src/utils/program-logs.ts
- Include CPI programs in the "invoked programs" column in the block transactions table 
- Hide vote txs by default because they make it hard to tell what else happened in a block
- Add compute column
Fixes #
=> explorer: Improvements to block transactions list

runtime/src/bank.rs, runtime/src/inline_spl_associated_token_account.rs, runtime/src/inline_spl_token.rs, sdk/src/feature_set.rs
We need to release new token-v3 and associated-token-account programs.  More information is in the feature gate issues.
Add new features and program ids for the updated programs.
Feature Gate Issue: #24741
Feature Gate Issue: #24740
=> token: Add features for new program releases

ledger/src/blockstore_db.rs
The RocksDB wrapper,`Rocks`, under blockstore_db is currently implemented
as a tuple with unnamed fields.  Accessing its fields requires syntax like `self.0`
which limits readability. 
This PR converts Rocks from tuple to struct so that it has more human-readable
fields.
=> (LedgerStore) Convert Rocks from tuple to struct with named fields

ledger/src/shred.rs, ledger/src/shredder.rs
de minimis
Removed Default implementation for ShredType. ShredType should always be
explicitly specified, and not rely on default values.
Simplified single-arg Shred Error variants to use shorter syntax.
Renamed erasure blocks to shards, to be consistent with reed_solomon
crate and not to confuse with FEC blocks.
=> minor edits in shred and shredder

validator/src/main.rs
=> fix typo on validator help

explorer/src/components/block/BlockHistoryCard.tsx
Log parsing fails for BPF logs in older blocks and causes app to crash
- Catch log parsing errors and don't show compute units if any logs fail parsing in a block
Fixes #
=> explorer: Hide compute units if log parsing fails

explorer/src/components/block/BlockHistoryCard.tsx
When there are no filtered transactions, an error state is shown.
Show an empty state when there are no filtered transactions
Fixes #
=> explorer: Fix empty state for filtered transactions

runtime/src/snapshot_utils.rs
When a new full snapshot archive is generated, all incremental snapshots for any previous full snapshots will be purged.  This can be undesirable in the case where Node B is running as a backup for Node A and:
1. Node A dies 
2. Node B creates a new full snapshot and purges its older incrementals
3. Node A restarts and wants the latest incremental from B based on the previous full snapshot.
But Node B has already purged it and Node A now has no choice but to fetch a full snapshot from B  
This PR thus:
a. preserves the existing behaviour for the highest full snapshot
b. retains the highest incremental snapshot for all other full snapshots
meaning that with the default snapshot config there'll be one additional incremental snapshot lying around on disk.
=> Always retain the highest incremental snapshot for all full snapshots

runtime/src/bank.rs
I believe this code is no longer necessary. Can we also delete the feature description? Enquiring minds want to know.
Fixes #
=> retire deprecate_rewards_sysvar

accounts-bench/src/main.rs, core/src/accounts_hash_verifier.rs, runtime/benches/accounts.rs, runtime/src/accounts.rs, runtime/src/accounts_background_service.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs, runtime/src/bank.rs, runtime/src/snapshot_package.rs, runtime/src/snapshot_utils.rs
Reverts solana-labs/solana#24340
=> Revert "Refactor to use EpochSchedule from within RentCollector struct"

web3.js/test/mocks/rpc-websockets.ts
Now that @marcnjaramillo is writing tests for timeouts in #24211, we need to be able to mock ‘the RPC never giving us an answer.’
You can now mock RPC messages with promises for values. Never resolving those promises is a good way to simulate timeouts.
=> test: you can now supply promises for values when mocking RPC subscriptions

client/src/connection_cache.rs
Some comments from #24857 have not been addressed.
1. Optimize cache eviction logic
2. Some cleanup as suggested in #24857
Fixes #
=> Optimize connection cache eviction logic

core/src/cluster_info_vote_listener.rs, core/src/sigverify.rs, core/src/sigverify_shreds.rs, core/src/sigverify_stage.rs, entry/src/entry.rs, perf/benches/sigverify.rs, perf/src/packet.rs, perf/src/sigverify.rs
=> Handle already discarded packets in gpu sigverify path (backport #22680)

runtime/src/bank.rs
Consistently use bank's accessor funciton for epoch_schedule
Fixes #
=> use bank's epoch_schedule accessor internally

rpc/src/optimistically_confirmed_bank_tracker.rs
=> Fixed a minor typo

runtime/src/accounts_db.rs
accounts-db ops running in global thread-pool taking excessive resources.
use designated thread-pools from accounts-db.
=> uses designated thread-pools for account db parallel ops

send-transaction-service/src/send_transaction_service.rs
Use data_point report metrics  periodically.
=> send-transaction-service metrics improvement

runtime/src/accounts_background_service.rs
=> when testing hash calc, also verify cap

runtime/src/accounts_db.rs, runtime/src/bank.rs
Work on tracking down why rewards calc and distribution takes so long.
Fixes #
=> add stats for stakes_cache_check_and_store_us

runtime/src/stakes.rs
Zero lamport accounts are not stored in accounts-db:
https://github.com/solana-labs/solana/blob/7b5835ddf/runtime/src/accounts_db.rs#L5007-L5014
https://github.com/solana-labs/solana/blob/7b5835ddf/runtime/src/accounts_db.rs#L4481-L4483
However, in order to purge the account from cache, stakes cache update
partially relies on accounts data to be also zeroed out :
https://github.com/solana-labs/solana/blob/7b5835ddf/runtime/src/bank.rs#L3471-L3478
This can be error-prone and introduce inconsistency between accounts-db
and vote/stake cache. This commit instead explicitly removes accounts
from cache if `lamports == 0`.
explicitly remove accounts with zero lamports from stakes cache
=> explicitly removes accounts with zero lamports from stakes cache

runtime/src/accounts_db.rs
required by devnet since epochschedule is different.
Fixes #
=> remove_old_historical_roots uses correct epoch schedule

sdk/program/src/message/legacy.rs
This code is indented 3 spaces.
=> Fix indentation of Message API examples

send-transaction-service/src/send_transaction_service.rs
Merge Use data_point report metrics periodically -- every 5 seconds for better metrics correlation and reduce noisy metrics.
=> Merge send-transaction-service metrics improvement (#24816) to v1.10

core/src/replay_stage.rs
=> fix typo in measure name

docs/src/wallet-guide/file-system-wallet.md
=> remove double word

.github/workflows/docs.yml, docs/src/validator/gossip.md
1. add missing VERCEL_TOKEN
2. add a newline to trigger docs build
=> chore: add missing VERCEL_TOKEN

sdk/program/src/lib.rs, sdk/program/src/sysvar/mod.rs
I previous missed updating this module's short docs. This makes it more consistent with the rest of the solana-program landing page.
There's still a lot to document within this module in the future.
=> Update sysvar module short docs

dos/src/main.rs
Even with non-unique transactions, work done to clone and serialize the same transaction on each loop iteration. Too many logs if the transaction is printed every time.
Don't set the generator if not generating unique transactions. Lower message to print transaction to debug level.
Before:
```
[2022-05-06T08:33:50.421251189Z INFO  solana_dos] count: 2455856 errors: 0
[2022-05-06T08:34:00.422299641Z INFO  solana_dos] count: 2432423 errors: 0
[2022-05-06T08:34:10.423339651Z INFO  solana_dos] count: 2052832 errors: 0
```
After:
```
[2022-05-06T08:27:14.617173766Z INFO  solana_dos] count: 2703760 errors: 0
[2022-05-06T08:27:14.932991537Z INFO  solana_dos] count: 2657111 errors: 0
[2022-05-06T08:27:15.215689888Z INFO  solana_dos] count: 2694998 errors: 0
[2022-05-06T08:27:15.511348928Z INFO …
```
=> dos: Skip generator if non-unique transactions

runtime/src/cache_hash_data.rs
Caching should be resilient to failure to load.
A truncated file should just fail to load.
#25072
Fixes #
=> check file size of accounts cache mmap before indexing

runtime/src/bank.rs
verify we didn't try to collect anything when we are skipping rewrites.
Fixes #
=> assert when rewrites skipped

runtime/src/accounts_db.rs
Move the complicated boxing into a single function.
This function will soon get a new caller as well.
Fixes #
=> simplify storage_finder -> storage

runtime/src/accounts_db.rs
extract function for re-use later
Fixes #
=> mark_dirty_dead_stores

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs, runtime/src/lib.rs
This is a logical piece of the ancient append vec feature coming soon.
Fixes #
=> add ancient_append_vecs

runtime/src/ancient_append_vecs.rs
a few ancient append vec helper functions
Fixes #
=> more ancient append vec fns

runtime/src/bank.rs
As reported in #24130, the compute budget override doesn't work.
With tx-wide compute budget enabled, the compute budget always dynamically calculates the compute budget during `ComputeBudget::process_message`.  If the compute budget has been overridden, the bank should always use it.  Note that this only happens in program-test with `set_max_compute_units` and in test-validator with `--max-compute-units`.
=> test-validator: Always use overridden compute budget in bank

ledger-tool/src/main.rs, runtime/src/accounts_db.rs, validator/src/main.rs
add hidden flag to enable ancient append vec as the feature hardens
Fixes #
=> add --accounts-db-ancient-append-vecs

docs/src/validator/tpu.md
=> Fix TPU docs typo

cli/src/program.rs
When deploying a program with a buffer, the calculated length of the program data stored in the buffer doesn't take into account the size of the buffer's metadata. This can lead to the program data not being created large enough for the deploy.
- Improve error handling on buffer inputs
- Fix program length calculation by subtracting buffer metadata size from buffer account length
Fixes #
=> cli: Fix deploy program length calculation when using buffers

docs/src/developing/on-chain-programs/developing-rust.md
Duplicate entry in the list in the documentation
Removed the invalid one
=> docs(developing): remove duplicate entry

runtime/src/accounts_db.rs, runtime/src/sorted_storages.rs
make a helper to cleanup some rough edges. There will soon be a few more callers who need this value.
Fixes #
=> SortedStorages::max_slot_inclusive()

core/src/validator.rs
[problem](https://github.com/solana-labs/solana/commit/05f32f287c778aae27b62a7340b5fcde88bc5760#r73503816)
Fixes #
=> println -> info

Cargo.lock, programs/bpf/Cargo.lock, runtime/Cargo.toml, runtime/src/shared_buffer_reader.rs, runtime/src/snapshot_utils.rs
Reverts solana-labs/solana#24889
=> Revert "Use memory map to speed up snapshot untar"

runtime/src/accounts_db.rs
we will get hash mismatches if this assertion is violated
Fixes #
=> assert we haven't squashed to ancient before hash calc

runtime/src/accounts_db.rs
ancient append vecs have to be shrunk differently
Fixes #
=> is_candidate_for_shrink respects ancient append vecs

runtime/src/ancient_append_vecs.rs
These functions weren't quite right yet.
Fixes #
=> ancient_append_vec refactoring

runtime/src/accounts_db.rs
=> populate ancient append vec metrics

CONTRIBUTING.md
Add ledger-store label and its description to CONTRIBUTING.md.
The label should help us track issues / PR easier.
=> Add ledger-store label and its description to CONTRIBUTING.md.

client/src/connection_cache.rs
Useless connections are being created which overloads the server and cause unreliable
connections on the client side.
This is due to the race in the connection cache for creating connections given a remote address. It was possible for multiple threads to create duplicate connections which only one of being used. This can overloads the server. 
After write lock is taken, check if the connection is available. If so, return without creating a new connection.
Fixes #
=> Fixed a race condition creating useless connections in MT env

runtime/src/serde_snapshot/newer.rs, runtime/src/serde_snapshot/tests.rs, sdk/program/src/fee_calculator.rs
Reverts solana-labs/solana#25181
=> Revert "Serialize lamports per signature in snapshots"

runtime/src/ancient_append_vecs.rs
recent clippy fixes left some test code in an unnecessarily verbose state
Fixes #
=> cleanup types in tests

account-decoder/src/parse_sysvar.rs, ci/buildkite-pipeline-in-disk.sh, ci/buildkite-pipeline.sh, ci/buildkite-solana-private.sh, client/src/blockhash_query.rs, programs/bpf_loader/src/syscalls.rs, runtime/src/bank.rs, sdk/program/src/clock.rs, sdk/program/src/epoch_schedule.rs, sdk/program/src/fee_calculator.rs, sdk/program/src/lib.rs, sdk/program/src/rent.rs, sdk/program/src/sysvar/fees.rs
Sysvar struct padding not zero'd when cloned
Zero it
Fixes #
=> Backport GHSA-wxrh-ff9f-fc6w

core/src/serve_repair.rs
We use `MAX_ORPHAN_REPAIR_RESPONSES + 1` in conjunction with a `<=`; I bumped the constant by 1 and replaced `<=` with `<` so that `run_orphan()` actually returns `MAX_ORPHAN_REPAIR_RESPONSES` responses (and we don't have to tack the +1 on)
Also, the PacketBatch that is being allocated has space for 64 packets in `run_orphan()`; `run_orphan()` will return `<= 11` packets so we were wasting the memory footprint of 53 packets (~60 kB) in allocation.
=> Simplify logic around MAX_ORPHAN_REPAIR_RESPONSES constant

rpc/src/rpc_subscriptions.rs, validator/src/main.rs
The PubSub service (`RpcSubscriptions` in particular) perform an eye twitching amount of work even when the websocket endpoint is not even enabled.  Clean this up by:
* Permitting `--rpc-pubsub-notification-threads 0` to turns off the internal PubSub notification machinery (useful if somebody wants the full RPC API but does not plan to ever use the websocket endpoint)
* The lack of `--full-rpc-api` now implies `--rpc-pubsub-notification-threads 0`
=> Reduce work performed by PubSub when not in use

runtime/src/expected_rent_collection.rs
Fix bug in expected rent collection related to rent paying accounts where the account's rent slot hasn't occurred in the current epoch yet. We need to use a rent collector that is one epoch older to correctly calculate rent if the slot in this epoch has not been hit yet.
Fixes #
=> use previous epoch rent collector in expected rent collection

rpc/src/rpc_subscriptions.rs
Fix regression from https://github.com/solana-labs/solana/pull/25307
Manual backport of #25341
=> v1.10: Avoid "Dropped RPC Notification" log spam

rpc/src/rpc_subscriptions.rs
=> Avoid "Dropped RPC Notification" log spam

client/src/connection_cache.rs, client/src/quic_client.rs, client/src/tpu_connection.rs
* Add metrics for open_uni
* Added metrics for make_connection
* measure make_connection success or fail
Fixes #
=> Add make_connection metrics (#25280) merge to v1.10

docs/src/developing/on-chain-programs/developing-rust.md, frozen-abi/Cargo.toml, programs/address-lookup-table/Cargo.toml, sdk/program/Cargo.toml, zk-token-sdk/Cargo.toml
Continuing the work started in https://github.com/solana-labs/solana/pull/25358
=> More target_arch = "bpf" => target_os = "solana"

runtime/src/expected_rent_collection.rs
during cluster warmup, and possibly later if a cluster changes its # slots per epoch, we need to take special care to calculate the correct slot# where rent should have been collected on a slot.
This should have no impact on mnb. But, private clusters or test clusters (like kin) will have hash inconsistencies (bank or accounts) when # of slots per epoch changes at an epoch boundary.
correctly handle this transition
Fixes #
=> use previous epoch's # slots per epoch

runtime/src/accounts_db.rs
=> simulate filler account hash calc time at delta hash

runtime/src/append_vec.rs, runtime/src/append_vec/test_utils.rs
=> Move append_vec::test_utils into its own file

runtime/src/accounts_db.rs
eliminate unnecessary 'vec' creation
Fixes #
=> apply AccountsInAppendVec to more places

programs/bpf_loader/src/syscalls.rs
_sol_alloc_free alignment test is broken
Fix it
Fixes #
=> fix test aligned

runtime/src/accounts_db.rs
=> special case for common case of 1 storage on append vec scan

client/src/quic_client.rs
Remove noisy metrics on open_uni
Fixes #
=> Remove noisy metrics on open_uni

explorer/src/components/instruction/ComputeBudgetDetailsCard.tsx, explorer/src/utils/index.tsx
Lack of support for new compute budget ixs
Fixes #
=> explorer: Add support for new compute budget ixs

streamer/src/quic.rs
When removing from the connection table, we could removed multiple entries at once but that wasn't accounted in the table-size calculations.
Account for the length of the array we remove.
Fixes #
=> quic: Fix prune_oldest table size calculation

metrics/src/datapoint.rs
Add comment block and examples for datapoint.rs
=> Add comment block and examples for datapoint.rs

.github/workflows/docs.yml, .mergify.yml, ci/affects.sh, ci/channel_restriction.sh, docs/src/proposals/comprehensive-compute-fees.md
Doc action doesn't exist on v1.10 yet
Fixes #
=> CI: Add docs workflow (v1.10)

Cargo.lock, core/Cargo.toml, programs/bpf/Cargo.lock
`retain_mut` appears unused, but we're wasting cycles on it
Remove it
Fixes #25487
=> Remove retain_mut dependency

client/src/rpc_response.rs, core/src/cluster_info_vote_listener.rs, docs/src/developing/clients/jsonrpc-api.md, gossip/src/cluster_info.rs, gossip/src/crds_value.rs, ledger/src/blockstore_processor.rs, local-cluster/tests/local_cluster_slow_1.rs, rpc/src/rpc_pubsub.rs, rpc/src/rpc_subscriptions.rs, runtime/src/vote_parser.rs
=> v1.10: voteSubscribe pubsub notification now includes the vote transaction signature 

runtime/src/bank.rs
`bank::tests::test_max_accounts_data_size_exceeded()` is _sloooowww_, taking over 30s to run.
Set the Bank's initial accounts data size near the max so that the test completes in around 0.1 seconds.
=> Speed up bank::tests::test_max_accounts_data_size_exceeded()

explorer/src/components/block/BlockHistoryCard.tsx
Can't easily see how many fees are paid by each tx in a block
Add sortable fee column to block history view
Fixes #
=> explorer: Add fee column to block history card

ci/run-sanity.sh
Prior to this change, genesis.tar.bz2 and the snapshot would be copied
over to a new directory but not rocksdb. As such, the verify step would
only unpack the snapshot and verify that hash.
Furthermore, `Blockstore::open()` only succeeds on the verify because
`genesis.tar.bz2` contained slot 0 blockstore data. We're moving away
from unpacking rocksdb from genesis archive, so this change makes
sure that proper blockstore data will be present.
Fixes #
=> Make run-sanity.sh ledger-tool verify operate on more slots

core/src/sigverify_stage.rs
The `num_valid_packets` metric of the SigVerify stage used to report the number of packets with successful signature validations but was accidentally changed to count packets passed into the verifier by e4409a87feae400d8430d3756853e8ff7cdded2f.
This restores the previous meaning.
@jstarry
=> SigVerify: Fix num_valid_packets metric

runtime/src/bank.rs
=> runtime: disable durable nonces

perf/src/sigverify.rs
=> perf: correct tracer packet detection bounds check

client/src/http_sender.rs
Fixes [this](https://github.com/solana-labs/solana/issues/25679)
=> use tokio sleep inside async

runtime/src/accounts_db.rs
=> u64 -> duration

runtime/src/bank.rs
=> add metrics on rent collection pieces

runtime/src/in_mem_accounts_index.rs
=> fix ordering in disk idx

runtime/src/bank.rs
Typo in the "epoch_stakes_creation" metric
Fixes #
=> epoch_stakes_reation -> epoch_stakes_creation in Bank::_new_from_parent

runtime/src/accounts_db.rs
accounts threads need more stack sometimes
increase the stack size
Fixes https://github.com/solana-labs/solana/issues/25481
=> Increase accounts stack size to 8mb

runtime/src/bank.rs
Extract useful function.
Fixes #
=> extract prefix_from_pubkey

runtime/src/bank.rs
When a bank's `Arc` wrapped `CachedExecutors` is cloned, the executors stats aren't reset back to zero. Stats are only ever reset when we call `Arc::make_mut` due to a cache update or when we cross an epoch boundary. Due to the recent increase in cache size, it's much more common for a bank not to update the executors cache and so its executor stats will accumulate from the previous bank's stats.
- Remove copy-on-write semantics for cached executors because the clone overhead is actually pretty small since all executors are individually `Arc` wrapped anyways.
Fixes #
=> Fix bank executor stats and remove copy-on-write semantics

SECURITY.md
bounties don’t need a patch. Just a demo or a valid bug. 
Clarify that bounties don’t need a patch
Fixes #
=> Clarify that bounties don’t need a patch

perf/src/sigverify.rs
debug into printed in long loop slows down and clutter CI output
turn it down
Fixes #
=> less noisy tests in CI

programs/bpf_loader/src/syscalls.rs, sdk/src/feature_set.rs
Panicking program could do extra work first
Instead bail quicker
Fixes #
=> quick bail on panic

docs/src/implemented-proposals/installer.md
=> docs: fix typo in installer.md

runtime/src/in_mem_accounts_index.rs
=> fix double count of account index del stats

runtime/src/bucket_map_holder.rs, runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
=> Refactor:  separate delete and insert account index stats

runtime/src/bank.rs
When reading through `Bank::apply_feature_activations()`, I often have to check the call sites to remember which caller sets `init_finish_or_warp` to `true` and which to `false`. Since the parameter is basically just saying who the caller is, why not make that explicit and then put the mapping inside `apply_feature_activations()` for (1) ease of understanding, and (2) added type safety?
Add `ApplyFeatureActivationsCaller` enum.
=> Add ApplyFeatureActivationsCaller enum

runtime/src/account_info.rs
Misleading comment. The storage offset is reduced offset * ALIGN_BOUNDARY_OFFSET
Fixes #
=> account_info.rs: docs offset is reduced_offset * ALIGN_BOUNDARY_OFFSET

programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf/build.rs, programs/bpf/rust/curve25519/Cargo.toml, programs/bpf/rust/curve25519/src/lib.rs, programs/bpf/tests/programs.rs, programs/bpf_loader/src/syscalls.rs, sdk/bpf/dependencies/sbf-tools, sdk/program/src/syscalls.rs, sdk/src/feature_set.rs, zk-token-sdk/src/curve25519/curve_syscall_traits.rs, zk-token-sdk/src/curve25519/edwards.rs, zk-token-sdk/src/curve25519/ristretto.rs
Adding additional tests for curve25519 syscalls.
=> Add syscall tests for curve25519

sdk/bpf/dependencies/sbf-tools
#25634 re-added a file that had previously been removed in #25844; 634 probably didn't rebase on top of 844
Delete the file again
=> fixup! Add syscall tests for curve25519 (#25634)

runtime/src/bank.rs
rent collection occurs in bank::freeze
when we skip slots, we collect rent over multiple slots.
Right now, we collect over those slots serially.
Rent collection can get very slow for large # accounts.
Parallelize by # partitions.
Fixes #
=> collect rent from multiple partitions in parallel

sdk/program/src/lib.rs
https://github.com/solana-labs/solana/pull/25334#discussion_r892675355
Add a static vector to get sdk ids
Fixes #
=> Add static vector to get sdk ids

docs/src/clusters.md
Docs language needs work
Work it
=> Clean up some RPC and cluster docs

runtime/src/in_mem_accounts_index.rs
=> get rid of dead code marker

runtime/src/in_mem_accounts_index.rs
=> remove dead code marker

program-runtime/src/invoke_context.rs, runtime/src/bank.rs
`reject_empty_instruction_without_program` will be activated on MNB soon.
Removes the feature gate of `reject_empty_instruction_without_program`
=> Removes the feature gate of `reject_empty_instruction_without_program`

core/src/ledger_cleanup_service.rs, ledger/src/blockstore.rs, ledger/src/blockstore_options.rs, perf/src/packet.rs, zk-token-sdk/src/curve25519/curve_syscall_traits.rs
`cargo doc` issues some warnings about broken links.
=> Fix doc warnings

cli/src/feature.rs
`solana feature status` with no account parameters is broken because `sdk/src/feature_set::FEATURE_NAMES` has more than 100 feature ids, and the cli command uses a single `RpcClient::get_multiple_accounts` request on all the features. The default cap for that rpc endpoint is 100 accounts.
Chunk the call to `RpcClient::get_multiple_accounts` based on `MAX_MULTIPLE_ACCOUNTS`. This could still be broken against RPC nodes that configure a lower `max_multiple_accounts` setting, but seems reasonable, and at least unbreaks solana-cli users targeting the Foundation RPC clusters.
=> Cli: Paginate rpc query to get feature accounts

web3.js/src/index.ts
=> fix: export custom transaction confirmation error classes

core/benches/cluster_nodes.rs, core/src/cluster_nodes.rs, core/src/retransmit_stage.rs
Track turbine efficacy in propagating shreds.
Added metric tracking number of shreds sent and received at different distances from the broadcast root.
=> tracks number of shreds sent and received at different distances from the root

explorer/src/utils/tx.ts
Their docs say it's their program https://whitepaper.stepn.com/decentralized-exchange
=> [explorer] Add STEPN dex program id for name resolution

ledger-tool/src/main.rs
=> add options to create snapshot

runtime/src/bank.rs
(cherry picked from commit 740ee0c50299e837ab50a31978cd20faf338d8dd)
Re-backport of https://github.com/solana-labs/solana/pull/25617 which I haphazardly screwed up.
Fixes #
=> Fix datapoint name (#25614)

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
count stat wasn't being updated correctly on batch insert after a recent change.
Fixes #
=> batch insert updates stat count correctly

sdk/src/packet.rs
If the packet is marked as discard, it is either invalid or otherwise
should be ignored, and so the payload should not be read from.
mask packet data if the packet is already marked as discard
=> masks packet data if the packet is already marked as discard

core/src/validator.rs, rpc/src/rpc_service.rs
See #25941
revert e263be2000a237e694a07c498151122c2169ce95
Fixes #
=> Revert handle start_http failure in rpc_service (#25400)

runtime/src/bank.rs, runtime/src/stakes.rs, runtime/src/vote_account.rs
log number of stake_accounts, vote_accounts, and stake_nodes of the stake_cache.
Fixes #
=> Stake cache size

docs/src/developing/programming-model/runtime.md, docs/src/implemented-proposals/transaction-fees.md, docs/src/proposals/comprehensive-compute-fees.md, docs/yarn.lock
Compute budget and fee docs are need updating
Update them
Fixes #
=> update compute budget docs

runtime/src/bank.rs
eliminate vec creation for storing rewards accounts
Fixes #
=> impl StorableAccounts for [StakeReward]

programs/bpf_loader/src/syscalls.rs
Feature fixed_memcpy_nonoverlapping_check as been enabled on mainnet
Clean it out of the runtime source
Fixes #
=> cleanup fixed_memcpy_nonoverlapping_check

runtime/src/bank.rs
=> eliminate vec creation in stake rewards

docs/package-lock.json, docs/yarn.lock
accidental `git commit -am`  in #26209
=> docs: revert unintentional packaging changes

core/src/retransmit_stage.rs
Shreds arriving at a node for retransmit tend to belong to the same slot
(or a just a couple of different slots). Slot leader and cluster nodes
are common for the shreds of the same slot, and so the common work to
look up these values can be factored out.
This commit first group-bys shreds by slot to factor out that common
lookup work.
=> factors out common retransmit work for shreds of the same slot

core/src/retransmit_stage.rs
For small batches rayon thread-pool only adds overhead.
The commit bypasses rayon thread-pool for small batches.
In order to preserve current behavior, the threshold is set to the
current value of the argument to `IndexedParallelIterator::with_min_len`.
Follow up commits will recalibrate this threshold to optimize
performance on mainnet-beta.
=> bypasses rayon thread-pool for small retransmit shred batches

runtime/src/bank.rs
=> test_rent_collect_rent_from_accounts

ledger/src/blockstore.rs
=> increase mmap file limit to 1M to match published instructions

core/src/cluster_info_vote_listener.rs
Add timing measure for gossip vote processing to compare the performance of https://github.com/solana-labs/solana/pull/25016
Fixes #
=> Add timing measurement for gossip vote txn processing

runtime/src/bank.rs
=> comment and expand on test

docs/src/developing/programming-model/runtime.md
post latest (~june 2022) ristretto reduction compute budget defaults
=> Updated link to compute budget struct

runtime/src/accounts_db.rs
This allows callee to lookup by index in future refactorings that are coming.
Fixes #
=> AccountsDb::load_accounts_index_for_shrink takes slice

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
prepare to reuse this function by shrink code paths, where loading the index is very expensive.
Fixes #
=> refactor acct idx scan func for reuse

runtime/src/bucket_map_holder.rs
https://discord.com/channels/428295358100013066/560503042458517505/991119443054837760
Fixes #
=> make test_age_time less intermittent

programs/bpf_loader/src/syscalls.rs
Feature activated on mainnet at epoch 321 but still conditional in the code
Remove the features conditionals
Fixes #
=> Cleanup feature: sycall base costs

core/src/retransmit_stage.rs
Testing on mainnet-beta, `with_min_len` does not seem helpful.
Removed `with_min_len`.
=> removes IndexedParallelIterator::with_min_len from retransmit

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
loading entries from the accounts index for shrink and ancient shrink is slow.
`scan` was already created as a lower overhead, faster function for reviewing account info for a set of pubkeys. Re-use it. It was previously only used by clean.
Fixes #
=> load_accounts_index_for_shrink uses scan

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
roots len is growing
track # roots added and removed
Fixes #
=> track # roots added/removed since last clean

validator/src/bootstrap.rs
There are some bootstrap snapshot download issues being reported on testnet and with tv1. While investigating, I wanted to have more logging in bootstrap. I also found some logic that could be simplified, and also added more test coverage on `build_known_snapshot_hashes()`.
* Simplify some bits (small impact)
* Add debug logging
* Add more test coverage
=> Tweak bootstrap::build_known_snapshot_hashes() (logs and tests)

ledger/src/blockstore.rs, ledger/src/shred.rs
Removing a repeated check as mentioned in https://github.com/solana-labs/solana/pull/26225#discussion_r909033829
=> Reduce repeated discard_shreds checks

cli/src/cli.rs, runtime/benches/bank.rs
prerequisite of https://github.com/solana-labs/solana/pull/25489
=> pacify nightly clippy

runtime/src/accounts.rs
provide more info so a single log line is more useful.
Fixes #
=> improve log

runtime/src/append_vec.rs
=> inc counter when append vec drop fails

ledger-tool/src/main.rs, validator/src/main.rs
=> cleanup cli arg help

core/src/shred_fetch_stage.rs, ledger/src/shred.rs
Some sanity checks are duplicate and so redundant.
deduped sanity checks.
=> simplifies packet/shred sanity checks

runtime/src/rent_collector.rs
we will use a feature to stop changing rent_epoch for rent exempt accounts
Fixes #
=> refactor calculate_rent_result

runtime/src/accounts_db.rs
=> is_shrinking_productive calls avoid arc clone

account-decoder/src/parse_account_data.rs, account-decoder/src/parse_nonce.rs, cli/src/nonce.rs, client/src/blockhash_query.rs, rpc/src/rpc.rs, rpc/src/transaction_status_service.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/nonce_keyed_account.rs, runtime/src/system_instruction_processor.rs, sdk/program/src/nonce/state/current.rs, sdk/program/src/nonce/state/mod.rs, sdk/src/nonce_account.rs, send-transaction-service/src/send_transaction_service.rs
Feature is activated on all clusters.
removed the feature gate code
closes #25950,  #25772
=> removes feature gate code separating durable nonce from blockhash domain

runtime/src/accounts_db.rs
Avoid iterating file twice and avoid creating vec.
Fixes #
=> use append vec iter in construct_candidate_clean_keys

runtime/src/accounts_db.rs
=> combine lookup in calc_delete_dependencies

runtime/src/accounts.rs, runtime/src/bank.rs, sdk/src/transaction/sanitized.rs
`max_tx_account_locks` feature is activated on all clusters and should be cleaned up
=> Clean up `max_tx_account_locks` feature

runtime/src/accounts_db.rs
avoid unnecessary second lock acquisition
Fixes #
=> simplify code

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
F: FnMut(bool, &SlotList<T>, &'a Pubkey, RefCount) -> AccountsIndexScanResult,
Refactor to take  (&'a Pubkey, Option<(&SlotList<T>, RefCount))
Fixes #
=> Refactor account index scan function parameters

runtime/src/bank.rs
`nonce_must_be_authorized ` feature is activated on all clusters and should be cleaned up
=> Clean up `nonce_must_be_authorized` feature

ledger/src/blockstore.rs
=> helpful error message when mmap limit can't change

runtime/src/accounts_db.rs
provide accurate stats for rent paying accounts at startup
```
total_rent_paying_accounts=
3,756,663
lamports_to_top_off_rent=
5,413,132,859,665
```
Fixes #
=> improve startup stats for rent payers

rpc/src/rpc.rs, runtime/src/bank.rs, runtime/src/nonce_keyed_account.rs, sdk/program/src/message/sanitized.rs, sdk/src/transaction/sanitized.rs
`nonce_must_be_writable ` feature is activated on all clusters and should be cleaned up
=> Clean up `nonce_must_be_writable` feature

runtime/src/accounts_db.rs
=> use iter for append vecs

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
Provide insight into how often active scans are interfering with clean.
Fixes #
=> add metrics for # scans active and scan distance

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs, runtime/src/snapshot_minimizer.rs
=> remove FoundStoredAccount.account_size

bench-tps/src/bench.rs, bench-tps/src/lib.rs, bench-tps/src/main.rs, bench-tps/src/send_batch.rs
*Please review by commit*
This is PR contains prerequisite changes for the follow up PRs to add support of  durable nonce transactions.
* Extracted sending batch funding transactions logic to separate file
* Refactored code of `SendBatchTransactions` to be reusable later for durable nonce accounts creation
=> refactor and extract send batch logic

programs/bpf_loader/src/syscalls.rs
Enabled on mainnet but still featurized in the code
Clean it up
Fixes #
=> cleanup feature: executables_incur_cpi_data_cost

bucket_map/src/bucket.rs, runtime/src/accounts_db.rs
https://github.com/solana-labs/solana/issues/26455
This is the first part of the change - prepare for changing refcount type.
use RefCount type alias
Fixes #
=> Use RefCount type alias instead of u64

programs/bpf_loader/src/syscalls.rs
Enabled on mainnet but still featurized in the code
Cleanit up
Fixes #
=> cleanup feature: quick_bail_on_panic

runtime/src/bank.rs
=> collapse some bank test creation fns

runtime/src/bucket_map_holder.rs
still intermittent failures
Fixes #
=> add more slop to test_age_time

runtime/src/bank.rs
simple functions to create simple bankj for tests
Fixes #
=> make bank test creation standard

.github/ISSUE_TEMPLATE/0-general.md
A common question for looking into reported issues is what version the issue was observed with.
Add a note to the template asking submitter to include software version
Fixes #
=> Add note to include software version (if relevant) in issue template

programs/vote/src/vote_processor.rs, programs/vote/src/vote_state/mod.rs
The `reject_non_rent_exempt_vote_withdraws ` feature is activated on all clusters and should be cleaned up
=> Clean up activated `reject_non_rent_exempt_vote_withdraws` feature

core/src/accounts_hash_verifier.rs, core/src/snapshot_packager_service.rs, runtime/src/snapshot_package.rs
Small code clean up and optimize.
Optimize O(N^2) hash vector removing to O(N).
1. remove unused code
2. extract fault hash inject fn
3. optimize hash vector remove
Fixes #
=> clean up and optimize account hash verify

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/in_mem_accounts_index.rs, runtime/src/snapshot_minimizer.rs
=> add StoreReclaims::Ignore

runtime/src/accounts_db.rs
=> fix active_scans metric to not swap

runtime/src/accounts_index.rs, runtime/src/bank.rs, runtime/src/serde_snapshot.rs
=> use OnceCell instead of RwLock for rent_paying_accounts_by_partition

bench-tps/src/bench.rs
This PR extracts function which splits flat containers of `Keypair`s into two set of chunks.
The motivation is to reuse this code for nonce accounts in the follow up PR.
=> extract method to split keypairs into two set of chunks

runtime/src/accounts_db.rs
=> change type to be more clear

programs/bpf/tests/programs.rs
When running program tests on macOS, the assert ix count test tries to JIT compile programs but this will always panic on archs that aren't x86
Exclude JIT tests on non x86 archs
Fixes #
=> Disable JIT bpf program tests on non x86 archs

core/src/consensus.rs, core/src/repair_service.rs, core/src/unfrozen_gossip_verified_vote_hashes.rs
erroneous `allow(dead_code)` annotations
removed them
=> removes erroneous allow(dead_code) annotations from core

runtime/src/accounts_db.rs
=> eliminate flatten().collect() of reclaims in clean

docs/src/proposals/blockstore-rocksdb-compaction.md
=> docs: fix typo in blockstore-rocksdb-compaction.md

bench-tps/src/bench.rs
Extract code which prepares chunks of transactions into a new structure.
This change simplifies follow up PR adding nonce durable accounts.
=> Refactor bench-tps chunking transactions logic

runtime/src/snapshot_utils.rs
Inconsistent naming of parallel_divisions
Consistently use parallel_divisions
Fixes #
=> rename parallel_archivers -> parallel_divisions for consistency

runtime/src/accounts_index.rs
No more write lock required. These functions used to take &mut, which required a write lock. Over time, they've migrated to taking '&self'
Fixes #
=> eliminate write lock usage in acct idx

banking-bench/src/main.rs, validator/src/main.rs
I merged PR #25914 too quickly and missed Tyera's comments. Addressing them here.
* Remove cruft from banking bench
* Simplify argument match
Fixes #
=> Cleanup from PR #25914

program-test/src/lib.rs
https://github.com/solana-labs/solana/pull/26630 modified a function which was added in https://github.com/solana-labs/solana/pull/26507 and resulted in a broken master build.
Fix merge conflict
Fixes #
=> Fix merge conflict in program-test

runtime/src/accounts_db.rs
=> log error for cache_hash_data save failure

bench-tps/src/bench.rs
This PR is part of chain of PRs introducing durable nonce transactions to bench-tps.
This particular one introduces chunks of nonce keypairs, the mechanism is exactly the same as for existing accounts keypairs.
* Extracted struct with source/destination keypair chunks (was pair of these vectors)
* Introduce nonce keypair chunks
=> Create nonce keypair chunks

runtime/src/serde_snapshot.rs
In #26590, we need the append_vec sizes from the snapshot file while we unpack in parallel.
Separate function so we can get bank & account fields from an individual snapshot, rather than requiring both the full and incremental.
Fixes #
=> Separate field_from_stream to get bank/account fields from individual snapshot stream

core/src/banking_stage.rs
Dead code still acquires `poh_recorder` read lock
remove it
Fixes #
=> Remove unnecessary poh_recorder read lock acquire

core/src/tpu.rs, core/src/validator.rs, local-cluster/src/validator_configs.rs, validator/src/main.rs
=> Enable QUIC servers by default

bucket_map/src/bucket.rs, bucket_map/src/bucket_stats.rs, runtime/src/bucket_map_holder_stats.rs
=> add stats for disk_index_find_entry_mut_us

sdk/src/feature_set.rs
=> Fix typo: contirbutor to contributor

runtime/src/accounts_db.rs
=> CalcAccountsHashConfig default for tests

runtime/src/append_vec.rs
store-tool is inconvenient to use because we may not know the current_len of an appendvec file.
Add a public `new_from_file_unchecked` function to AppendVec that does not perform sanitization checks. It will create and return an appendvec as long as we can open the file, map the memory, and the current_len we pass is reasonable, not greater than file_size for instance.
I don't anticipate this will be used outside of store-tool, and the interface is inconvenient for createing an AccountStorageEntry since it does not return the number of accounts in the AppendVec.
Fixes #
=> Add AppendVec::new_from_file_unchecked

runtime/src/serde_snapshot/newer.rs, sdk/src/deserialize_utils.rs
Get rid of duplicate code. I was about to duplicate it again.
Fixes #
=> cleanup ignore_eof_error

core/src/cluster_info_vote_listener.rs
Looks like a copy-paste error
reset gossip_txn_processing_time_us
Fixes #
=> Bugfix: VoteProcessingTiming reset both counters

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs
Switch from 2 pass find/insert to 1 pass.
Fixes #
=> insert perf improvement on bucket map

sdk/src/feature_set.rs
See  #26848 
Add feature module and pubkey for incremental snapshots hashing only accounts in the snapshot: #26848 
Fixes #
=> Feature-gate for incremental snapshots only hashing accounts in the incremental snapshot

sdk/bpf/c/inc/sol/inc/cpi.inc
generated header file was modified directly
move changes to the file's source
Fixes #26653
=> Copy changes made to a generated header file to its source

explorer/src/utils/program-verification.tsx
Old links, build link is broken
change links to use apr.dev
Fixes #
=> anchor verified build uses apr.dev

core/src/ancestor_hashes_service.rs, core/src/serve_repair.rs, core/src/serve_repair_service.rs, core/src/validator.rs
The wrappers are superfluous.
Removed the wrappers.
=> removes redundant Arc<RwLock<...>> and Option<&Arc<...>> wrappers from serve-repair

runtime/src/accounts_db.rs
=> allow caching on ancient append vecs for accounts hash calc

Cargo.lock, account-decoder/Cargo.toml, accounts-cluster-bench/Cargo.toml, programs/bpf/Cargo.lock, rpc/Cargo.toml, tokens/Cargo.toml, transaction-status/Cargo.toml, transaction-status/src/parse_token.rs
=> Bump spl-token

runtime/src/accounts_db.rs
=> log oldest dirty slot on clean

runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
=> add 'oldest_root' stat in hash calc

ledger/src/shred/stats.rs, ledger/src/shredder.rs
track distribution of num-data-shreds obtained from serialzing entries.
added histogram counts in 4 buckets.
=> records num data shreds obtained from serializing entries

bench-tps/src/bench.rs, bench-tps/src/keypairs.rs, bench-tps/src/main.rs, bench-tps/src/perf_utils.rs, bench-tps/src/send_batch.rs
*Please review by commit*
Extracted the code creating client in order to:
* simplify the logic in main: isolate client creation from Keypairs generation and cli args parsing
* reuse later in other client applications
Extracted code creating client into a separate function.
There will be a follow up PR to simplify logic of the extracted function.
=> Bench tps: refactor client creation

runtime/src/rent_paying_accounts_by_partition.rs
=> protect access to rent paying account vec

RELEASE.md
=> Add minor version clean up tasks to release doc

programs/bpf/tests/programs.rs, sdk/bpf/c/bpf.mk, sdk/bpf/scripts/install.sh, sdk/cargo-build-sbf/src/main.rs, sdk/cargo-build-sbf/tests/crates.rs
Upgrade SBF tools to Rust 1.62.0 and LLVM 14.0.
=> Bump sbf-tools version to v1.29

programs/bpf/tests/programs.rs
`cargo test --features="bpf_c"` fails to compile without this fix.
- annotate rust only test with proper `#[cfg()]` annotations
- split use directives to common for c and rust, and to rust-only
=> Fix programs/bpf bpf_c and bpf_rust features to work independently

Cargo.toml, ci/publish-tarball.sh
My bad cargo skillz:
https://github.com/solana-labs/solana/pull/26706#issuecomment-1208772275
=> Revert "Remove resolver=2 from Cargo.toml and add it to the Windows build"

core/src/broadcast_stage/standard_broadcast_run.rs, ledger/src/shred/stats.rs
track number of coding shreds
added metric
=> adds number of coding shreds to broadcast metrics

core/src/unprocessed_packet_batches.rs
=> Fix typo in test function

docs/src/proposals/return-data.md
=> docs: fix typo in return-data.md

gossip/src/cluster_info.rs
See #27110
Sleep between vote refreshes in unit test
=> Sleep between vote refreshes

core/src/result.rs, gossip/src/cluster_info.rs
verbose manual derivation of From and Display
derive Error trait
=> derives Error trait for ClusterInfoError and core::result::Error

runtime/store-tool/src/main.rs
Was using this and I wanted to see lamports. Might be useful for anyone else using it.
Print out lamports in store-tool.
Fixes #
=> store-tool: log lamports for each account

gossip/tests/gossip.rs, ledger/src/blockstore.rs, runtime/src/bank.rs
`from_secs` is more descriptive than `new` for duration creation.
Fixes #
=> Use from_secs api to create duration

runtime/src/in_mem_accounts_index.rs
=> create helper fn for clarity

runtime/src/accounts_index.rs, runtime/src/bucket_map_holder.rs
=> simple refactorings to disk idx

runtime/src/accounts_db.rs
=> rename unused parameter for clarity

runtime/src/accounts_index.rs
=> release roots tracker read lock earlier

runtime/src/accounts_db.rs
=> account_iter instead of accounts()

runtime/src/accounts_db.rs
=> refactor/document calc_delete_dependencies

runtime/src/accounts_index.rs
=> add _inclusive

runtime/src/accounts_db.rs
Help track down the accumulation of old append vecs.
Fixes #
=> log reason why oldest store_id isn't being cleaned

runtime/src/accounts_db.rs
Ancient append vecs are pre-release and enabled by cli arg only.
However, they are wrong right now wrt ref counts. When we move a slot's accounts into a different ancient append vec, if an older version of the account already exists in the ancient append vec, then we need to unref the account since there will now be 1 less append vec referring to the pubkey. Otherwise, we will have too many refcounts and the account will never go to a zero refcount.
Fixes #
=> in ancient shrink, unref accounts that were already ancient shrunk

client/src/rpc_response.rs, transaction-status/src/lib.rs
Many of the structs in rpc_response.rs are missing PartialEq and Eq. `RpcBlockCommitment` is also missing Clone.
Adds the above missing `derive`s to rpc_response.rs.
=> add missing derives

runtime/src/in_mem_accounts_index.rs
=> remove unnecessary references

rpc-test/tests/rpc.rs
Seeing another occurrence of the rpc test failure.
https://buildkite.com/solana-labs/solana/builds/80276#0182c6e5-ca68-4dbd-a641-5129a84f4048
Increase the timeout.
Fixes #
=> Another timeout tweak to reduce rpc test flakiness

runtime/src/accounts_index.rs
=> clean_rooted_entries adds _EXclusive

runtime/src/accounts_db.rs
=> failed_store_id should be searched per pubkey

runtime/src/accounts_db.rs
=> clean_accounts add _inclusive

runtime/src/serde_snapshot.rs
=> get rid of extra comment

core/src/accounts_hash_verifier.rs
make it easy to find this assert in github, etc.
Fixes #
=> add text to assert

sdk/program/src/example_mocks.rs, sdk/program/src/log.rs, sdk/program/src/message/legacy.rs, sdk/program/src/message/versions/v0/mod.rs, sdk/program/src/pubkey.rs, sdk/program/src/secp256k1_recover.rs, sdk/program/src/system_instruction.rs, sdk/program/src/sysvar/clock.rs, sdk/program/src/sysvar/epoch_schedule.rs, sdk/program/src/sysvar/rent.rs, sdk/program/src/sysvar/slot_hashes.rs, sdk/program/src/sysvar/slot_history.rs, sdk/program/src/sysvar/stake_history.rs, sdk/src/example_mocks.rs, sdk/src/secp256k1_instruction.rs, sdk/src/transaction/mod.rs
There are lots of references to `solana-client` in the sdk docs. Let's fix those up to point users at the new, slimmer client crates
Fixup docs
Toward https://github.com/solana-labs/solana/issues/27352
=> Fixup docs in sdk to use new clients

core/src/accounts_hash_verifier.rs
Fatal error message sounds innocuous
make it sound fatal
=> make fatal log message sound fatal

sdk/src/transaction/versioned/mod.rs
The `VersionedTransaction::try_new` constructor is overly strict because it requires signer keypairs to match the order of the message signer keys. Callers can't always anticipate the order of signer keys in a compiled message so this method should be flexible enough to handle keypairs in any order.
- Update `VersionedTransaction::try_new` implementation to rearrange signatures in the same order while still ensuring that the correct set of signers was passed
Fixes #
=> Relax keypair ordering restriction for `VersionedTransaction::try_new`

runtime/src/accounts_db.rs
=> ancient append vecs and cleaning dead slots

Cargo.lock, programs/bpf/Cargo.lock, runtime/Cargo.toml
https://github.com/solana-labs/solana/pull/27429 for v1.10
=> Address RUSTSEC-2022-0051 - v1.10

Cargo.lock, programs/bpf/Cargo.lock, runtime/Cargo.toml
https://github.com/solana-labs/solana/pull/27429 for v1.11
=> Address RUSTSEC-2022-0051 - v1.11

runtime/src/accounts_db.rs
=> clean_dead_slots_from_accounts_index unrefs correctly

runtime/src/accounts_db.rs
Refactoring began earlier to test and further parallelize this function.
Fixes #
=> refactor clean_dead_slots_from_accounts_index

runtime/src/accounts_db.rs
=> comment loop in function

runtime/src/in_mem_accounts_index.rs
There was unused code intending to insert directly to disk index. In various experiments over time, this never proved better.
Get rid of it.
Fixes #
=> remove unused acct idx::upsert_on_disk

runtime/src/accounts_db.rs
When we combine slots into ancient append vecs, we must make sure to unref any accounts that exist in both the source slot AND the ancient append vec. To do this, we need to find the intersection of 2 sets of pubkeys. Since the same ancient appendvec is appended to by many slots, it makes sense to build a hashset of its pubkeys once and then add to it and re-use it for subsequent combine operations.
The current implementation is very slow since it iterates the ancient append vec once per slot that is combined.
Keep a local hashset of the pubkeys already in the current ancient appendvec.
Fixes #
=> improve performance of unrefing ancient pubkeys

core/src/banking_stage.rs, core/src/lib.rs, core/src/packet_deserializer.rs, core/src/unprocessed_packet_batches.rs
#27009 and #27111
Initial step towards a separate deserialization stage
separate deserialization code from banking code
Ran bench-tps. No significant difference in results from master.
Fixes #
=> separate packet_deserializer inside banking_stage

web3.js/src/connection.ts
Reverts solana-labs/solana#27466
=> Revert "fix: add compute units to jsonrpc parser"

runtime/src/accounts_db.rs
fix some comments for clarity and correctness.
Fixes #
=> fix some comments

runtime/src/in_mem_accounts_index.rs
For account index, when a slot is in the write cache or the pubkey is in more than 1 slot, the entry is kept in memory, under the assumption that the entry will be modified soon. Previously, a change was made to pick the farthest 'age' in the future to consider evicting the account index entry from memory when a slot was cached. This needs to apply to pubkeys with more than 1 slot as well.
Defer trying to evict until farther in the future for in memory account index entries that are in more than 1 slot.
Fixes #
=> acctidx: use slot list len to determine if upsert remains in cache

runtime/src/accounts_index.rs
rename since we aren't using a lock anymore
Fixes #
=> acctidx renames for clarity

runtime/src/snapshot_utils.rs
While taking a snapshot, an `AccountsPackage` is made and submitted to the `PendingAccountsPackage` to be handled by Accounts Hash Verifier. The code that checks if a package can be submitted, and then actually submitting do not happen within a single lock. This is (1) not the safest, since it's semantically possible to change the state of the `PendingAccountsPackage` in between the `check` and `submit` steps, and (2) not the fastest, since if the lock is grabbed in both steps, duplicate work is done unnecessarily.
In practice, this change should not affect runtime performance, as (1) there is not a lot of contention on this lock. When we add Epoch Accounts Hash though, I want to ensure it is not possible to incorrectly submit/replace/take accounts packages.
Grab the …
=> Hold `PendingAccountsPackage` lock for both checking and submitting

core/src/packet_deserializer.rs
Follow up to #27120. Working on completely separating deserialization from banking stage, it was convenient to have this function separated from the actual channel receiving for tests.
Create a separate function that deserializes and builds ReceivePacketResults from packet_batches and tracer stats.
Incremental step for #27009 
Fixes #
=> refactor: add function for deserializing and collecting packets - separate from channel receive

ledger/src/blockstore.rs
Add code comments for lowest_cleanup_slot related functions to improve
the code readability for the consistency between blockstore purge logic
and the read side.
=> Add code comments for lowest_cleanup_slot related functions

test-validator/src/lib.rs
When cloning accounts, `test-validator` makes a single RPC request for each address, which is not very efficient:
https://github.com/solana-labs/solana/blob/6bc04b5e3a900e7d6aad37141dc7bd3496c6699d/test-validator/src/lib.rs#L290
Batch the request in chunks of `MAX_MULTIPLE_ACCOUNTS` and use the `get_multiple_accounts` method
=> test-validator clone with get_multiple_accounts

core/src/packet_deserializer.rs
Did not add tests as part of #27548
Added tests for `deserialize_and_collect_packets`
Fixes #
=> Add tests for deserialize_and_collect_packets

sdk/program/src/vote/mod.rs
These broke during refactoring.
Fixes #
=> Fix solana_program::vote docs

runtime/src/bank.rs
re-use guts of existing function to eliminate code copies
Fixes #
=> reuse shared function

core/src/validator.rs, ledger-tool/src/main.rs
=> In ledger-tool delete the account files in the async way

ci/test-stable.sh
forgot to make docs test uploading test result by conditions
=> chore: make docs test upload test result when needed

runtime/src/accounts_db.rs
remove outdated comment
Fixes #
=> remove outdated comment

core/tests/snapshots.rs, runtime/src/accounts_index.rs, runtime/src/bank.rs, runtime/tests/accounts.rs
Move tests from Keypair() to pubkey::new_rand. They are all just using a pubkey.
Fixes #
=> tests: Keypair::new().pubkey() -> pubkey::new_rand

runtime/src/accounts_index.rs
remove fn nobody calls anymore
Fixes #
=> remove unused 'unref' fn

ci/buildkite-pipeline-in-disk.sh, ci/buildkite-pipeline.sh, ci/buildkite-solana-private.sh
We will see the trigger step as an "unnamed job" on datadog.
Add a name for it.
=> chore: add a name for secondary trigger step

runtime/src/accounts_index.rs
A constant was missed in #27704 
Change it to the new name
Fixes #
=> Fix a constant that was missed

core/src/unprocessed_packet_batches.rs
Wasn't entirely sure what the return value of this was and there wasn't a comment to hover in banking code to tell me.
Add a comment so it's clear what is returned
Fixes #
=> Clean_up/upb_push_comment

cd/README.md
The canaries aren't documented
Created a cd directory (continuous delivery) and added a readme with canary overview.
What other info about canaries or delivery would you like to see here? Any preference for this going in an existing directory or naming it something other than "cd" (whether we'll ever get to continuous delivery is an open question)?
I just learned there's a way to view rendered markdown in PRs. Sharing in case I'm not the last person to find this:
=> Create continuous delivery directory and add readme with canary details.

runtime/src/accounts_db.rs
`AccountsDb.shrink` will remove the shrunk slot from `shrink_candidate_slots`. 
`shrink_candidate_slots` is used to identify slots that should be shrunk.
When a slot is shrunk, any not alive accounts are unref'd and the alive accounts are copied to a new appendvec for the slot.
With ancient append vecs, when a slot's append vec was combined into a new or existing ancient append vec, the old append vec is removed from the slot storage. However, the old append vec COULD have been in `shrink_candidate_slots`. If it was, then eventually this old appendvec, which has been combined into an ancient append vec, will be shrunk incorrectly. When it is shrunk, we could call unref on the account index for accounts in the old appendvec. This old append vec should disappear.
This can also lead to an …
=> remove ancient append vec stores from shrink_candidate_slots

runtime/src/accounts_db.rs
clean can be given a list of stores that could need to be cleaned. Every pubkey in the store is loaded from the index to look for opportunities to clean the pubkeys and even mark the slot dead.
Ancient append vecs represent a different type of store. Loading all the pubkeys from ancient appendvecs can be unnecessarily expensive.
Track how often we are loading the contents of an entire appendvec in clean during normal validator execution.
Fixes #
=> add `dirty_ancient_stores` to clean metrics

banking-bench/src/main.rs, bench-tps/src/bench_tps_client/tpu_client.rs, bench-tps/src/cli.rs, bench-tps/tests/bench_tps.rs, client/src/connection_cache.rs, client/src/nonblocking/quic_client.rs, client/src/nonblocking/tpu_client.rs, client/src/quic_client.rs, client/src/spinner.rs, client/src/tpu_client.rs, core/src/banking_stage.rs, core/src/tpu.rs, core/src/validator.rs, gossip/src/cluster_info.rs, local-cluster/src/cluster_tests.rs, local-cluster/src/local_cluster.rs, local-cluster/src/validator_configs.rs, local-cluster/tests/local_cluster.rs, local-cluster/tests/local_cluster_slow_1.rs, local-cluster/tests/local_cluster_slow_2.rs, multinode-demo/bootstrap-validator.sh, net-utils/src/lib.rs, sdk/src/quic.rs, streamer/src/nonblocking/quic.rs, validator/src/main.rs
commit 09ea899a2df5ab3298a29fe9876dc23b52d6f1dc —> done , some conflicts
Date: Sat May 21 20:22:30 2022 +0200
commit 826f3312ccfdb4ab72f28a27538914410529adc0 —> done
Date: Wed Jun 29 15:37:27 2022 +0800
commit f14922c2045a13c2aeb41968f0ec2f1fbad3f37b —> done
Date: Thu Jun 30 12:09:07 2022 -0700
commit 9714cb37641a8679982ee70a976b09757555b23f. —> done
Date: Sat Jul 16 17:03:31 2022 +0200
f0994c4ba10e4e535ec13f58533451a53a6657ee —> done
Date: Tue Jul 19 20:54:42 2022 +0800
commit 27866aeab427585ffad69da73d87c3700a17386c —> done
Date: Fri Jul 22 08:56:15 2022 -0700
commit fb922f613c1361faa5fe1bb56c985507c800434c —> done
Date: Fri Jul 29 08:44:24 2022 -0700
commit f2e5c6d3b141eb30026d95d8b3028ac39d01c602
Date: Wed Aug 10 17:53:44 2022 +0000
commit 4bda9098277a2f574074e0ad70e765001d93985d —> …
=> Backport quic to v1.13

.github/workflows/docs.yml, docs/src/getstarted/local.md
- print more info
- bump tj-actions/changed-files to v29.0.7
- fix changed files detection
=> chore: fix docs pipeline

docs/src/developing/clients/jsonrpc-api.md, transaction-status/src/lib.rs
=> Add new TransactionDetails level (backport #27601)

runtime/src/accounts_db.rs
fix a stat and add a new stat 'ancient_append_vecs_shrunk'
Fixes #
=> ancient append vec stats: ancient_append_vecs_shrunk

runtime/benches/accounts.rs, runtime/src/accounts.rs, runtime/src/bank.rs
more plumbing required for feature of enable_rehashing
#26491
Fixes #
=> pass enable_rehashing to verify_bank_hash_and_lamports

runtime/src/bank.rs
=> runtime: compleleted -> completed

runtime/src/bank.rs
=> runtime: ParitalEq -> PartialEq

runtime/src/expected_rent_collection.rs
=> runtime: ifno -> info

runtime/src/expected_rent_collection.rs
=> runtime: fix typo idnex -> index

runtime/src/accounts_db.rs
=> runtime: fix typo situtation -> situation

runtime/src/expected_rent_collection.rs
=> runtime: fix typo recalcluate -> recalculate

runtime/src/expected_rent_collection.rs
=> runtime: fix typo occured -> occurred

runtime/src/expected_rent_collection.rs
=> runtime: fix typo in expected_rent_collection.rs

core/src/broadcast_stage.rs, core/src/cluster_nodes.rs, core/src/retransmit_stage.rs
track number of staked/stale/dead nodes in turbine cluster-nodes
added metrics
=> tracks number of staked/stale/dead nodes in turbine cluster-nodes

runtime/src/bank.rs
=> runtime: fix 'governed' typo

runtime/src/bank.rs
=> runtime: fix typo for 'exempt'

docs/src/developing/clients/jsonrpc-api.md, rpc-client-api/src/response.rs
docs were missing this field
Added the field and fixed a typo in source code comment
=> Add missing rootSlot documentation

core/benches/retransmit_stage.rs, core/benches/shredder.rs, core/src/banking_stage.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/broadcast_duplicates_run.rs, core/src/broadcast_stage/broadcast_fake_shreds_run.rs, core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/consensus.rs, core/src/repair_generic_traversal.rs, core/src/repair_service.rs, core/src/repair_weighted_traversal.rs, core/src/replay_stage.rs, core/src/validator.rs, core/src/window_service.rs, core/tests/ledger_cleanup.rs, gossip/src/duplicate_shred.rs, ledger-tool/tests/basic.rs, ledger/benches/blockstore.rs, ledger/src/ancestor_iterator.rs, ledger/src/blockstore.rs, ledger/src/blockstore/blockstore_purge.rs, ledger/src/leader_schedule_cache.rs, ledger/src/shred.rs, ledger/src/shred/merkle.rs, ledger/src/shredder.rs, ledger/tests/blockstore.rs, ledger/tests/shred.rs, rpc/src/rpc.rs
Convert `&[Entry]` to Merkle shreds.
Added methods to convert `&[Entry]` to Merkle shreds.
=> generates merkle shreds from ledger entries

core/src/serve_repair.rs, sdk/src/feature_set.rs
- disable ping/pong verification for repair requests pending additional metrics to track stability
- ignore ping/pong cache checks for repair packets
Fixes #
=> allow unsigned repair requests

runtime/src/accounts_db.rs
1.14 is ooming.
this is one likely reason. In preparing for ancient append vecs, we needed to break out the large, old append vecs into their own cache file. However, this is bad combined with the bug that causes us to fail to unref, causing an accumulation of old appendvecs containing only zero lamport accounts.
group old slots together for hash calc, just like we do for the normal range of alive slots. This reduces allocations by 2500X.
Fixes #
=> get_one_epoch_old_slot_for_hash_calc_scan to handle many old append vecs

bench-tps/src/bench.rs, bench-tps/src/main.rs
=> fix typo: lamporots to lamports

core/benches/cluster_nodes.rs, core/src/banking_stage.rs, core/src/repair_service.rs, core/src/repair_weighted_traversal.rs, core/src/replay_stage.rs, core/src/sigverify_stage.rs, genesis/src/genesis_accounts.rs, genesis/src/main.rs, genesis/src/stakes.rs, ledger/src/slot_stats.rs, log-analyzer/src/main.rs, runtime/src/accounts_index.rs, runtime/src/bank.rs, runtime/src/cost_tracker.rs, runtime/src/execute_cost_table.rs, runtime/src/expected_rent_collection.rs, runtime/src/in_mem_accounts_index.rs, runtime/src/status_cache.rs, sdk/src/signer/signers.rs, storage-bigtable/src/lib.rs, tpu-client/src/nonblocking/tpu_client.rs
clippy errors from new rust nightly release
patched the errors
=> patches clippy errors from new rust nightly release

runtime/src/block_cost_limits.rs, runtime/src/cost_model.rs
issue #27991 
- increase instruction data cost by 4 times
Fixes #27991
=> increase instruction data cost

core/src/serve_repair.rs
Need count of unsigned repair requests to determine when signed requests can be required.
Add counter for unsigned repair requests.
Fixes #
=> count unsigned repair requests

RELEASE.md
There are some spelling and grammar issues in the README file 
Fix the spelling and grammar issues
=> RELEASE.md cleanup

explorer/src/components/SupplyCard.tsx, explorer/src/components/TopAccountsCard.tsx, explorer/src/components/account/StakeAccountSection.tsx, explorer/src/components/account/StakeHistoryCard.tsx, explorer/src/components/account/UnknownAccountCard.tsx, explorer/src/components/account/UpgradeableLoaderAccountSection.tsx, explorer/src/components/account/address-lookup-table/AddressLookupTableAccountSection.tsx, explorer/src/components/block/BlockHistoryCard.tsx, explorer/src/components/block/BlockRewardsCard.tsx, explorer/src/components/common/Account.tsx, explorer/src/components/common/BalanceDelta.tsx, explorer/src/components/common/SolBalance.tsx, explorer/src/components/instruction/ComputeBudgetDetailsCard.tsx, explorer/src/components/instruction/stake/SplitDetailsCard.tsx, explorer/src/components/instruction/stake/WithdrawDetailsCard.tsx, explorer/src/components/instruction/system/CreateDetailsCard.tsx, explorer/src/components/instruction/system/CreateWithSeedDetailsCard.tsx, explorer/src/components/instruction/system/NonceWithdrawDetailsCard.tsx, explorer/src/components/instruction/system/TransferDetailsCard.tsx, explorer/src/components/instruction/system/TransferWithSeedDetailsCard.tsx, explorer/src/pages/TransactionDetailsPage.tsx, explorer/src/pages/inspector/InspectorPage.tsx, explorer/src/utils/index.ts
Components should be in `components` not `utils`
=> Explorer: Split out `SolBalance` component from utils

runtime/src/cache_hash_data.rs
1.14 ooms
we can get rid of ram spikes by removing allocations during accounts hash calc
This is working towards using on-disk cached accounts hash data to calculate the accounts hash.
Provide access to the entire cache file with a &[].
Fixes #
=> hash cache get_slice

runtime/src/snapshot_utils.rs
Name didn't conform with @mvines's new format
change thread name
Fixes #
=> update upacking thread names

ledger/src/shred/merkle.rs
Merkle proof for shreds recovered from erasure codes are generated locally, and it is superfluous to verify them when sanitizing recovered shreds:
https://github.com/solana-labs/solana/blob/a0f49c2e4/ledger/src/shred/merkle.rs#L727-L760
bypass merkle proof verification for recovered merkle shreds
=> bypasses merkle proof verification for recovered merkle shreds

ledger/src/blockstore.rs, ledger/src/shred/merkle.rs, ledger/src/shredder.rs
If there is no parallelization, thread-pool only adds overhead.
bypass rayon thread-pool for single entry vectors
=> bypasses rayon thread-pool for single entry vectors

runtime/src/cache_hash_data.rs
1.14 is using too much memory
hash calc can be reworked to keep less in memory, thus reducing peak memory usage.
This can easily be done by leveraging the caching that already exists.
Refactor creating the map from `load_internal`.
Behavior remains the same, but further changes are now more straightforward.
Fixes #
=> refactor hash calc caching

core/benches/banking_stage.rs, sdk/src/packet.rs
Benches for banking stage only simulate txs
Simulate votes coming in from gossip and tpu as well
Fixes #
=> Add bench test for voting threads

Cargo.lock, cli/Cargo.toml, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls/mod.rs, rbpf-cli/Cargo.toml
Bumps things to the latest rbpf release.
=> Bump solana_rbpf to 0.2.33

explorer/package-lock.json, explorer/package.json, explorer/src/App.tsx
`@types/react-router` dependency patch update introduced a breaking change in type checking
Update and fix react-router types
Fixes https://github.com/solana-labs/solana/issues/28107
=> explorer: bump react-router type deps and fix type errors

explorer/src/components/transaction/TokenBalancesCard.tsx
Token balance changes aren't shown if a token is closed in the transaction
Show token balance changes even when a token account is closed
Fixes https://github.com/solana-labs/solana/issues/28130
=> explorer: Show token delta when token account is closed

runtime/src/accounts_hash.rs, runtime/src/cache_hash_data.rs
Verify map and alignment.
Refactor work that is coming soon needs &[EntryType]
#28078
Make functions less generic to guarantee we are in defined behavior.
Fixes #
=> alignment work

explorer/package-lock.json, explorer/package.json
Vercel deploy needs a direct dependency on `@solana/spl-token` for some reason
=> Explorer: use explicit @solana/spl-token dependency

core/src/banking_stage.rs, core/src/forward_packet_batches_by_accounts.rs, core/src/latest_unprocessed_votes.rs, core/src/unprocessed_packet_batches.rs, core/src/unprocessed_transaction_storage.rs
We will share these ImmutableDeserializedPacket  across threads. They should use Arc instead of Rc
Rc -> Arc for the immutable deserialized packets
Fixes #
=> ImmutableDeserializedPacket rc to arc

runtime/src/accounts_hash.rs
This code will soon move to use refs instead of allocations of data to calculate the accounts hash.
Add helper methods to deal with test data changes.
Fixes #
=> refactor some accts hash tests

runtime/src/cache_hash_data.rs
moving to using disk-based accounts index calculation
Fixes #
=> refactor CacheHashDataFile to use mmapped data

runtime/src/accounts_db.rs
comment some functions and refactor some code to prepare to use mmapped files instead of ram for accounts hash calc
Fixes #
=> accounts hash calc refactoring

runtime/src/cache_hash_data.rs
https://discord.com/channels/428295358100013066/560503042458517505/1026523391550832640
This assert existed prior to recent refactoring for bigger changes. The assert doesn't make sense in this context.
Remove it.
Fixes #
=> remove troublesome assert

runtime/src/accounts.rs, runtime/src/bank/address_lookup_table.rs, sdk/src/feature_set.rs
feature has been activated everywhere
remove it
Fixes #
=> remove feature return_none_for_zero_lamport_accounts

runtime/src/accounts_db.rs
prepare to rework and add tests around accounts hash calculation and ancient append vecs
just refactor code out into a separate function without making any changes.
Fixes #
=> refactor into split_storages_ancient

notifier/src/lib.rs, watchtower/src/main.rs
Watchtower alerts are useful but the alerting mechanisms don't always cut through the noise
Add Pagerduty integration to Watchtower
=> Watchtower pagerduty

runtime/src/accounts_db.rs
rename and document fields for refactoring, clarity, correctness, tests
Fixes #
=> rename fields in SplitAncientStorages

docs/src/developing/versioned-transactions.md
Fixed minor typos in the documentation.
=> Fix typo in Versioned Transactions

ci/test-checks.sh
CI error message can be made more informative
Add remediation instructions to CI error message.
=> Add remediation to CI error message for uncommited Cargo.lock changes

runtime/src/accounts_db.rs
add comments and refactor accounts hash scanning
Fixes #
=> accounts hash scan refactoring

core/src/broadcast_stage/standard_broadcast_run.rs, ledger/src/shred/stats.rs
Testing Merkle shreds on testnet.
Rolls out Merkle shreds to ~5% of testnet
=> rolls out merkle shreds to ~5% of testnet

ledger/src/blockstore_processor.rs
load_frozen_forks is running at a slow pace in 14.1 and later.
Add some sub-timings to track down inefficiencies.
Fixes #
=> add sub timings in load_frozen_forks

runtime/src/accounts_db.rs
allow for better testing and extending for calculating accounts hash using files instead of memory.
Fixes #
=> refactor into SplitAncientStorages::new

sys-tuner/src/main.rs
`solana-sys-tuner` may decrease `sysctl` values which is not desired.
This patch adds a check that the current value is smaller than new one before applying new value.
=> sys-tuner: Do not change sysctl parameters to smaller values

runtime/src/accounts_db.rs
split `SplitAncientStorages::new` so it is easier to test.
Fixes #
=> refactor SplitAncientStorages::new for testing

metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
https://github.com/solana-labs/solana/issues/28258
fix dashboard query
Fixes #
=> fix node count query

ledger/src/blockstore_processor.rs
We've seen slowdowns at startup, some of which can be attributed to blockstore_processor::load_frozen_forks(). But, unless we had the logs, we didn't have an easy way to know the rate at which slots were being processed.
Add a metric field to track number of slots processed. This, in combination with the existing `total_time_us` field will allow us to see the average processing rate of slots/s in metrics
=> Add metric to track number of slots processed in load_frozen_forks()

runtime/src/accounts_db.rs
This code is about to be reworked to calculate accounts hash using disk files instead of memory.
Refactor it some.
Fixes #
=> minor refactoring of accounts hash cache

Cargo.lock, cli/Cargo.toml, cli/src/program.rs, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf/benches/bpf_loader.rs, programs/bpf/tests/programs.rs, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls/cpi.rs, programs/bpf_loader/src/syscalls/logging.rs, programs/bpf_loader/src/syscalls/mem_ops.rs, programs/bpf_loader/src/syscalls/mod.rs, programs/bpf_loader/src/syscalls/sysvar.rs, rbpf-cli/Cargo.toml, rbpf-cli/src/main.rs
https://github.com/solana-labs/rbpf/releases/tag/v0.2.34 was released.
=> Bump solana_rbpf to 0.2.34

ledger/src/shred/merkle.rs
`fn sanitize` parses MerkleBranch twice once for proof size sanity check and once for Merkle-proof verification.
Moved Merkle proof size sanity check to `Shred{Code,Data}::merkle_branch`.
=> moves merkle proof size sanity check to Shred{Code,Data}::merkle_branch

streamer/src/quic.rs, tpu-client/src/quic_client.rs
Give the thread created for quic client and server for better performance debugging
quic_client
quic_server
Fixes #
=> Give the quic client and server thread the names

runtime/src/accounts_db.rs
minor tweaks for readability. Rename test.
see comments on #28202
Fixes #
=> hash calc chunking cleanup

docs/src/integrations/exchange.md
Users may like to get the result immediately. 
Use devnet blocks and transactions as examples
=> docs: use devnet blocks and transactions as v0 transaction examples

runtime/src/accounts_db.rs
I hit this error on 1.14. It could be useful to have more information on the specific pubkey to help track its journey.
Fixes #
=> add info for load race condition asserts

validator/src/bootstrap.rs
Some logs were not formatted nicely.
Fix 'em up.
=> formats logs in bootstrap

ledger/src/blockstore_db.rs
We have some columns where we don't want/need to do a deserialize() on get() calls; namely, the data/coding shred columns.
Add multi_get_bytes() which is similar to multi_get() but doesn't do the deserialize. We have a similar `get_bytes()` method, so following same convention.
=> Add rocksdb multi_get_bytes() method

core/tests/epoch_accounts_hash.rs
I left some code in https://github.com/solana-labs/solana/pull/28304 that was only meant for debugging the tests.
Remove it.
=> Cleans up debugging code in EAH tests

Cargo.lock, programs/bpf/Cargo.lock, programs/stake/Cargo.toml
solana-stake-program has some unused dependencies.
Remove them.
Related: https://github.com/solana-labs/solana/pull/27339
=> remove unused deps from solana-stake-program

runtime/src/bank.rs
=> runtime: fix typo 'transaction'

core/src/cluster_slot_state_verifier.rs, core/src/replay_stage.rs
Manual backport of
> Consensus Logging #28176
(Replaces PR #28207)
=> Consensus Logging (#28176)

docs/src/getstarted/hello-world.md
Grammatical mistake on Get Started page
Text changes on Get Started documentation file.
Fixes #
=> Fix Grammatical mistake on Get Started documentation page

streamer/src/nonblocking/quic.rs
Need clearer error code and error reason for connection close from server side to debug from client side for connection issues.
Define the error code and reasons for different connection close scenarios.
Application close code and reason are not interpreted by Quinn library and are passed to the client exactly. 
Fixes #
=> Give better error code and reason for connection close

runtime/src/accounts_db.rs
Work on clarity and improve testing of accounts hash files.
Soon we will rely on this for all accounts hash calculations.
Fixes #
=> factor out hashing of storages for caching

ledger/src/blockstore_db.rs
Add comment block for BankHash ledger column.
=> Add comment block for BankHash ledger column

ledger/src/blockstore_db.rs
Add comment block for SlotMeta column family
=> Add comment block for SlotMeta column family

ledger/src/blockstore_db.rs
Add comment block for ErasureMeta ledger column
=> Add comment block for ErasureMeta ledger column

explorer/package-lock.json, explorer/package.json, explorer/src/components/account/ConfigAccountSection.tsx, explorer/src/components/account/MetaplexNFTHeader.tsx, explorer/src/components/account/NonceAccountSection.tsx, explorer/src/components/account/StakeAccountSection.tsx, explorer/src/components/account/SysvarAccountSection.tsx, explorer/src/components/account/TokenAccountSection.tsx, explorer/src/components/account/UnknownAccountCard.tsx, explorer/src/components/account/UpgradeableLoaderAccountSection.tsx, explorer/src/components/account/VoteAccountSection.tsx, explorer/src/components/account/address-lookup-table/AddressLookupTableAccountSection.tsx, explorer/src/components/account/nftoken/NFTokenAccountSection.tsx, explorer/src/components/instruction/token/TokenDetailsCard.tsx, explorer/src/pages/AccountDetailsPage.tsx, explorer/src/pages/inspector/AddressTableLookupsCard.tsx, explorer/src/pages/inspector/AddressWithContext.tsx, explorer/src/pages/inspector/InspectorPage.tsx, explorer/src/providers/accounts/index.tsx
The inspector page fetches dozens of accounts at once which leads to rate limiting because each account maps to one RPC request.
- Batch account fetches together in one `getMultipleAccounts` request
Fixes #
=> Explorer: Batch account fetching

explorer/src/pages/inspector/SimulatorCard.tsx
When no logs are returned, the transaction simulator doesn't display a transaction error
=> Explorer: Show simulation error if no logs are returned

.buildkite/hooks/post-command
=> chore: stop uploading test data to buildkite

runtime/src/serde_snapshot/newer.rs
clones in reserialize code are not necessary
remove them
Fixes #
=> remove unnecessary clones

ledger/src/blockstore_db.rs
Add comment block for Orphans column family.
=> Add comment block for Orphans column family.

storage-bigtable/src/bigtable.rs, storage-bigtable/src/lib.rs
#28166 
- add does_row_key_exist
- add does_confirmed_block_exist
=> add a lighter way to check whether a block exists in the Bigtable

runtime/src/accounts_db.rs
refactor function for easier testing
add tests
Fixes #
=> refactor and test get_sorted_potential_ancient_slots

docs/src/transaction_fees.md
- fix some typos & sentence fragments
- clean up explanation of fee burn
=> docs: improve transaction fee documentation

runtime/src/accounts_db.rs
Plan to remove duplicate code.
Refactor for easier sharing.
Fixes #
=> refactor load_accounts_index_for_shrink for easier sharing

runtime/src/accounts_db.rs
=> simple minor refactoring

runtime/src/accounts_db.rs
Prepare to share code
Make it identical.
Fixes #
=> make ancient shrink consistent with shrink

ledger/src/blockstore_db.rs
Improve SlotColumn's code comment to include how
LedgerCleanupService manages the clean-up of a SlotColumn.
=> Improve SlotColumn's code comment.

runtime/src/accounts_db.rs
share complicated code between shrink and ancient append vecs
Fixes #
=> share shrink_collect code

runtime/src/accounts_db.rs
Prepare to share code.
Factor out metrics reporting for shrink operations.
Fixes #
=> factor out update_shrink_stats

rpc/src/rpc.rs
Unit test breaks
Add `space` to expected result
=> fix get_multiple_accounts test

runtime/src/accounts_db.rs
We will be sharing this code that is common with `do_shrink_slot_stores`.
refactor/rename to make it consistent.
Fixes #
=> simplify combine_ancient_slots

core/src/broadcast_stage/broadcast_duplicates_run.rs
=> Check for valid address in broadcast

runtime/src/accounts_db.rs
factor out common code
Fixes #
=> reuse update_shrink_stats for combine_ancient_slots

ledger/src/blockstore_db.rs
Add comment block for Root ledger column
=> Add comment block for Root ledger column

Cargo.lock, install/Cargo.toml, install/src/config.rs
added one more test case for #28388.
=> add test_save for install config

ledger/src/blockstore_db.rs
Add comment block for DeadSlots LedgerColumn
=> Add comment block for DeadSlots LedgerColumn

web3.js/src/connection.ts
The error message for `getFeeForMessage` is wrong
=> fix: incorrect error message for getFeeForMessage

runtime/src/accounts_db.rs
simplifying ancient append vec code
Fixes #
=> remove single use function for clarity

docs/src/running-validator/restart-cluster.md
=> Fix typo in restart-cluster.md

core/src/latest_unprocessed_votes.rs, programs/vote/src/vote_state/mod.rs, runtime/src/vote_parser.rs, sdk/program/src/vote/instruction.rs, sdk/program/src/vote/state/mod.rs
Consolidate all the places we match on vote types into one method for readability
Fixes #
=> Add convenience methods to VoteInstruction to distinguish vote types

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
cleanup and streamline ancient append vec code
Fixes #
=> simplify get_store_for_shrink

runtime/src/bank.rs
Now that the feature has been activated for preserving `rent_epoch` (#26479), we can simplify the skipping rewrites code.
We can now skip rewrites under the condition where the account was already written in current slot where the rewrite would occur.
Since we're not updating `rent_epoch` anymore, the account will already be exactly the same, so there is no reason to write it again, so we can now skip the rewrite (if we're skipping rewrites).
Note one of these tests fail when we try to remove the conditional feature-based `rent_epoch` update code. So, this pr cleans up the code to recognize the new status quo. Now when we remove the feature-based code, the test will continue to pass.
Remove the case where we were not skipping rewrite if `rent_epoch` needed to be updated.
Fixes #
=> skip_rewrite skips almost all accounts with no rent

runtime/src/accounts_db.rs
cleanup ancient appendvec code.
Fixes #
=> cleanup ancient append vec merge stats

runtime/src/accounts_db.rs
=> share index_read_elapsed code

runtime/src/accounts_db.rs
make ancient append vec code cleaner and easier to test
Fixes #
=> CurrentAncientAppendVec for clarity

gossip/src/cluster_info.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_push.rs, gossip/tests/crds_gossip.rs
=> pings peers before sending push messages

gossip/src/cluster_info.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_push.rs, gossip/tests/crds_gossip.rs
v1.14 backport of #28537 
cc/ @behzadnouri
=>  pings peers before sending push messages (bp #28537 )

banking-bench/src/main.rs
by specifying certain percentage of conflicting transactions with higher priority fee
Need tool to simulate banking buffer during nft mint event, where prioritized transactions with overlapping accounts take large chunk of buffer. 
1. updated banking-bench tool so its testing transaction include compute-budget::set_compute_unit_price ix.
2. add `--simulate-mint` to turn on simulation mode, in which `mint-txs-percentage` transactions in batch will have conflicting account, and higher priority fee. 
3. add `--mint-txs-percentage [0..99]` to fine tune the ratio of conflicting tx vs non-conflict transactions in each batch.
Fixes #
=> update banking-bench to simulate mint event 

Cargo.lock, cli/Cargo.toml, programs/bpf_loader/Cargo.toml, programs/sbf/Cargo.lock, programs/sbf/Cargo.toml, rbpf-cli/Cargo.toml
- recognize new SBF machine code in ELF header
=> Bump solana_rbpf to 0.2.35

runtime/src/accounts_db.rs, runtime/src/cache_hash_data.rs, runtime/src/cache_hash_data_stats.rs
rename for consistency
Fixes #
=> rename merge() -> accumulate()

runtime/src/accounts_db.rs
reduce code and make common
Fixes #
=> update stats in shrink_collect

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
cleanup pattern of calling `mark_dirty_dead_stores`
Fixes #
=> simplify mark_dirty_dead_stores

docs/src/proposals/partitioned-inflationary-rewards-distribution.md
Update voting accounts requirement for partitioned reward proposal.
Fixes #
=> Add vote section in reward proposal

runtime/src/accounts_db.rs
combine shrink and ancient append vec code
Fixes #
=> combine all_are_zero_lamports

runtime/src/accounts_db.rs
extract common code for clarity, correctness, perf, and testing
Fixes #
=> extract common code remove_old_stores_shrink from shrink and ancient append vecs

runtime/src/accounts_db.rs
break up `combine_ancient_slots` for clarity and better testability
Fixes #
=> extract ancient maybe_unref_accounts_already_in_ancient

bench-tps/src/bench.rs
prioritizatino
prioritization
Fixes #
=> fix typo: prioritizatino -> prioritization

sdk/bpf/scripts/install.sh, sdk/cargo-build-sbf/src/main.rs, sdk/sbf/scripts/install.sh
This version of sbf-tools is based on LLVM with the new SBF backend.
=> Bump sbf-tools to v1.31

runtime/src/accounts_db.rs
extract code from `combine_ancient_slots` for easier testing and clarity.
Fixes #
=> extract handle_dropped_roots_for_ancient from ancient append vec code
