- web3.js/src/transaction.ts
- web3.js/test/transaction.test.ts
Deserialized transactions can no longer be partially signed after Transaction mutation checks were added in https://github.com/solana-labs/solana/pull/23720
Only check for mutations in message fields, not for signatures
Fixes https://github.com/solana-labs/solana/issues/24462
> fix: allow signing a populated transaction

- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- runtime/src/non_circulating_supply.rs
- runtime/src/stakes.rs
- sdk/program/src/stake/instruction.rs
- sdk/program/src/stake/state.rs
- stake-accounts/src/stake_accounts.rs
- web3.js/src/stake-program.ts
It's not obvious what the enforced size of a stake account is
- Added a new const fn `StakeState::serialized_size()` to use in place of `size_of::<StakeState>()`
- Added a test assertion to make it obvious that 200 is the current size
Fixes #
> Define const fn `StakeState::size_of` for stake account size

- core/src/banking_stage.rs
- core/src/qos_service.rs
- programs/bpf/tests/programs.rs
- runtime/src/cost_model.rs
- runtime/src/cost_tracker.rs
- runtime/src/transaction_cost_metrics_sender.rs
Builtin programs are added to cost_table, being updated with `0` compute units from program-timing, lowers the builtin program costs. 
- removed builtin program from cost_table
- builtin program cost are queried directly from static `BUILT_IN_INSTRUCTION_COSTS`
Fixes #
> Cost model tracks builtins and bpf programs separately 

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- programs/bpf/Cargo.lock
- transaction-status/Cargo.toml
- transaction-status/src/parse_associated_token.rs
- transaction-status/src/parse_token.rs
There's a lot more to do wrt. integrating Token 2022 into the JSON RPC methods, this is just the tip of the spear.
> Add SPL Token 2022 to the list of known token ids

- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
Accounts sent via CPI are charged a per-data compute cost, but executables are not
Charge executables
Fixes #
Feature Gate Issue: #24512
> cpi charge for executables

- docs/src/developing/clients/jsonrpc-api.md
- ledger/src/blockstore.rs
- rpc/src/transaction_status_service.rs
- storage-proto/proto/confirmed_block.proto
- storage-proto/src/convert.rs
- storage-proto/src/lib.rs
- transaction-status/src/lib.rs
- transaction-status/src/token_balances.rs
Following #23067. Once we have both the current spl-token and the spl-token-2022 programs in play, transaction token pre- and post-balances will be difficult to reason about without program-id information.
Add `program_id` to the token-balances structs everywhere
> Add program_id to TokenBalances structs

- client/src/connection_cache.rs
packets and batches stats left off
Add reporting for packets and batches stats
Fixes #
> Add packets and batches sent to quic client stats

- runtime/src/accounts.rs
- runtime/src/bank.rs
we need the slot we loaded an account from when we skip rewrites.
Fixes #
> load_to_collect_rent_eagerly returns loaded_slot

- cli-output/src/cli_output.rs
- cli-output/src/display.rs
- ledger-tool/src/main.rs
- rpc/src/rpc.rs
clippy started complaining about this:
```
warning: casting the result of `i64::abs()` to u64
--> ledger-tool/src/main.rs:119:41
|
119 |                         lamports_to_sol(reward.lamports.abs() as u64),
|                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `reward.lamports.unsigned_abs()`
|
= note: `#[warn(clippy::cast_abs_to_unsigned)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_abs_to_unsigned
```
Fixes #
> Use unsigned_abs() instead of casting abs()

- core/src/replay_stage.rs
- poh/src/poh_recorder.rs
- runtime/benches/bank.rs
- runtime/src/bank.rs
- runtime/src/blockhash_queue.rs
- runtime/src/serde_snapshot/tests.rs
The blockhash queue implementation is hard to understand due to the names of its fields and methods.
- Renamed `hash_height` to `last_hash_index` since the value is 0-indexed
- Removed the distinction between blockhashes that aren't found and blockhashes that are too old assuming that https://github.com/solana-labs/solana/pull/24425 is accepted and it won't be possible to find a blockhash that is too old.
- Made method names clearer and more consistent
Fixes #
> Refactor: Rename BlockhashQueue fields and methods for clarity

- .mergify.yml
Backports for automerged PR's are assigned to the mergify bot account
Assign to author if community label isn't present, otherwise assign to community-pr-subscribers team
Jinja Filters ref: https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters
YAML anchor ref: https://docs.mergify.com/configuration/#yaml-anchors-and-aliases
Fixes #
> Assign backports for automerged PR to pr-subscribers group

- core/src/replay_stage.rs
- ledger/src/blockstore_processor.rs
- poh/src/poh_recorder.rs
- program-test/src/lib.rs
- runtime/src/bank.rs
- sdk/program/src/clock.rs
- sdk/src/feature_set.rs
As demonstrated in https://github.com/solana-labs/solana/pull/24242, the recent blockhashes queue tracks hashes for skipped blocks. The recent blockhash queue should only be storing hashes for produced blocks.
When registering ticks at slot boundaries, don't register the poh hash in the recent blockhash queue until all ticks have been completed for a bank.
some context for the justification of this change: https://github.com/solana-labs/solana/issues/23949#issuecomment-1098063237
Fixes https://github.com/solana-labs/solana/issues/24387
Feature Gate Issue: https://github.com/solana-labs/solana/issues/24388
> Only add hashes for completed blocks to recent blockhashes

- core/src/banking_stage.rs
Transaction processing is hard to follow in the banking stage
- Simplify the `record_transactions` method so that it's clearer that it's all or nothing
- Refactor how the `commit_transactions_result` list of booleans is created
Fixes #
> Refactor transaction processing in banking stage

- core/tests/snapshots.rs
- runtime/src/bank.rs
- runtime/src/epoch_stakes.rs
- runtime/src/genesis_utils.rs
- runtime/src/lib.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/stake_account.rs
- runtime/src/stakes.rs
- runtime/src/vote_account.rs
- sdk/src/feature_set.rs
Updating rewards at epoch boundary is slow; and Loading vote and stake accounts from accounts-db takes a significant portion of that computation time.
* This change bypasses accounts-db on the read path and instead uses vote and stake accounts cached in bank stakes:
https://github.com/solana-labs/solana/blob/d2702201c/runtime/src/stakes.rs#L148-L152
* These cached accounts are synchronized with accounts-db after each transaction, and so there should not be any change in the resulting computation:
https://github.com/solana-labs/solana/blob/d2702201c/runtime/src/bank.rs#L4526
Nevertheless, to avoid any chances of introducing a consensus issue, the switch to cached account is feature gated.
* In order to maintain backward compatibility, values in `stake_delegations` map in `Stakes` struct …
> updates rewards at epoch boundary using cached accounts

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/Cargo.toml
Syscall registration and binding are currently disjoint operations requiring the callers to explicitly do both for each syscall.
This can lead to mismatch or missing registration/binds and complicates the code. Another side effect is that it is difficult/impossible given the current API for callers to filter syscalls at the registration stage but allow them at the binding stage. One example is the effort to deprecate/disallow syscalls by preventing new deployments of programs that rely on a disallowed syscall while continuing to support existing programs that already rely on them.
These changes depend and build off the changes here: https://github.com/solana-labs/rbpf/pull/293
Syscalls are registered once, and later the bind operation uses a common context to bind all the previously …
> Simplify syscall register and bind

- runtime/src/accounts_db.rs
`slot` is unused. Supporting it when squashing flush cache slots is complicated, confusing, and unnecessary.
Also, code is not dead, so remove markers.
Fixes #
> cleanup FlushStats

- banks-server/src/banks_server.rs
- core/src/repair_service.rs
- multinode-demo/bootstrap-validator.sh
- multinode-demo/validator.sh
- rpc/src/cluster_tpu_info.rs
- rpc/src/rpc.rs
- send-transaction-service/src/send_transaction_service.rs
- send-transaction-service/src/tpu_info.rs
- validator/src/main.rs
Send transaction in batches to improve throughput
1. Introduced flag --tpu-do-batch2. 
2. Introduced flag to control the batch size-- by default 100 
3. The default batch timeout is 200ms -- configurable. If either it time out or the batch size is filled, a new batch is sent 
4. The batch honor the retry rate on the transaction already sent before.  
5. Introduced two threads in STS: one for receiving new transactions and doing batch send and one for retrying old transactions and doing batch.6.  
Fixes #
> Batch tpu calls in send-transaction-service

- runtime/src/storable_accounts.rs
when we squash multiple slots into a single slot, we need the ability to specify the old slot a group of accounts is coming from. In this case, we don't need per-account slot info, which would be wasteful. So, specify the original slot separately, once for the group of accounts.
Fixes #
> add StorableAccountsMovingSlots

- validator/src/main.rs
The current default max local snapshot age of 500 slots is now much too small for mainnet's 23GB snapshots.  Adjust the default to be more tolerant of slightly-older local snapshots.
Fixes #24486
> Increase default --maximum-local-snapshot-age to 2500

- sdk/program/src/lib.rs
The API docs for solana_sdk are missing several modules.
As described in https://github.com/solana-labs/solana/issues/23326#issuecomment-1104469118, this is happening because of an interaction that I don't fully understand between reexports in `solana_program::example_mocks::solana_sdk` and similar reexports in `solana_sdk`. Essentially, in this case rustdoc appears to choose the first reexport it finds to document, and leaves subsequent reexports undocumented.
Reordering the declaration of `solana_program::example_mocks` causes rustdoc to choose to document the reexports in `solana_sdk`.
This is a hack, and this patch documents it as such. It may be possible to fix within rustdoc itself, but that is not clear.
Fixes #23326
> Fix missing solana_sdk module docs

- explorer/src/pages/AccountDetailsPage.tsx
Explorer needs to also grab mint metadata from metaplex for fungible tokens
Use the existing `Metadata.load` function from `@metaplex-foundation/mpl-token-metadata` that we use to fill the [metadata card](https://github.com/solana-labs/solana/blob/d6927365ed427cb21b9191fb0a48c51d031a8ab9/explorer/src/components/account/MetaplexMetadataCard.tsx) and use the new [fungible token metadata standard](https://docs.metaplex.com/token-metadata/specification#token-standards) to show wallet metadata on a mint page
Fixes #
#23748
> fix: adds grab mint metadata for ft's

- core/src/banking_stage.rs
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/build.rs
- programs/bpf/rust/simulation/Cargo.toml
- programs/bpf/rust/simulation/src/lib.rs
- programs/bpf/rust/simulation/tests/lib.rs
- programs/bpf/rust/simulation/tests/validator.rs
- runtime/src/account_overrides.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/lib.rs
As pointed out in https://github.com/solana-labs/solana/pull/22880, it's possible for a program to detect if it's in a simulation.
Creating new banks has unintended knock-on effects all over the system, and a single source of truth for sysvars that falls back to the accounts db is error-prone, so #24033 and #24034 may cause more problems than they solve.
This is a much simpler approach, and simply overrides the slot history sysvar for simulation banks.
Fixes https://github.com/solana-labs/solana/issues/23260
> sim: Override slot hashes account on simulation bank

- explorer/.prettierrc.json
Currently when your run `npm run format:fix` it will do nothing or it will use your own local configuration.
My prettier configuration is different from the one used on the `solana/explorer` files, so it's updating all the files of the repository with my configuration and when I save a file it's formatting with my own configuration as well.
- Add a `.prettierrc.json` file matching the actual format rules of the repository
> chore(explorer): add .prettierrc.json

- explorer/src/utils/tx.ts
We would like to get our contract identified clearly on official Solana Explorer to facilitate user understanding and limit scams when they're inspecting transactions.
Contract: `CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz`
- Update the `utils/tx.ts` file to implement name and address of the Solanart contract
> Add Solanart program name

- banks-server/src/banks_server.rs
- multinode-demo/bootstrap-validator.sh
- multinode-demo/validator.sh
- rpc/src/cluster_tpu_info.rs
- rpc/src/rpc.rs
- send-transaction-service/src/send_transaction_service.rs
- send-transaction-service/src/tpu_info.rs
- validator/src/main.rs
Introduced flag --tpu-do-batch2.
Introduced flag to control the batch size-- by default 100
The default batch timeout is 200ms -- configurable. If either it time out or the batch size is filled, a new batch is sent
The batch honor the retry rate on the transaction already sent before.
Introduced two threads in STS: one for receiving new transactions and doing batch send and one for retrying old transactions and doing batch.6.
Fixes #
Fixes #
> Backport Batch tpu calls in send-transaction-service (#24083)

- programs/bpf_loader/src/syscalls.rs
Lots of copy-pasta around syscall declarations
Replace the copy-pasta with a macro to declare syscalls
Fixes #
> declare syscalls with macro

- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- local-cluster/tests/local_cluster.rs
- runtime/src/accounts_background_service.rs
- runtime/src/bank.rs
The blockstore processor module that reads the ledger at validator boot has its own full snapshot handling, and no support for incremental snapshots.
Rather than plumbing incremental snapshots, rip out blockstore processor's snapshot handling entirely and start the real snapshot packager earlier in the boot chain.
Additionally, start gossip/turbine before blockstore processing so that new blocks can be ingested into rocksdb as early as possible during validator startup
> Support incremental snapshots and run turbine while blockstore processing at validator boot

- Cargo.lock
- core/src/banking_stage.rs
- core/src/leader_slot_banking_stage_metrics.rs
- programs/bpf/Cargo.lock
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/lib.rs
- runtime/src/transaction_error_metrics.rs
https://github.com/solana-labs/solana/issues/24456
Move error counters inside `LeaderSlotMetrics` so that they're reported solely by the leader at the end of the block it's generating
Fixes #
> Move error counters to be reported by leader only at end of slot

- runtime/src/bank.rs
- runtime/src/vote_account.rs
Unless struct fields are explicitly ignored in `PartialEq` implementation,
there are no compile-time checks that if more fields are added to the
struct, `PartialEq` implementation is accordingly updated.
explicitly ignores struct fields which do not impact PartialEq impl
> explicitly ignores struct fields which do not impact PartialEq impl

- explorer/public/index.html
Apple touch icon had a broken link - it redirected to homepage and does not function as it should
Updated reference to current valid Apple touch icon (rainbow192.png, prior reference was logo192.png)
Fixes #
> Fix Apple touch icon broken link 

- web3.js/src/publickey.ts
- web3.js/test/publickey.test.ts
`PublicKey.isOnCurve` accepts a byte array, so passing a `PublicKey` object would silently return true every time, which is unexpected.
Allow `isOnCurve` to accept `PublicKeyInitData` for convenience.
Re-opens #22653
> feat: allow PublicKey.isOnCurve to accept PublicKeyInitData

- core/benches/cluster_nodes.rs
- core/benches/shredder.rs
- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- core/src/packet_hasher.rs
- core/src/repair_response.rs
- core/src/replay_stage.rs
- core/src/retransmit_stage.rs
- core/src/serve_repair.rs
- core/src/sigverify_shreds.rs
- core/src/window_service.rs
- gossip/src/cluster_info.rs
- gossip/src/duplicate_shred.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
- ledger/src/shred.rs
- ledger/src/sigverify_shreds.rs
- ledger/tests/shred.rs
Working towards embedding versioning into shreds binary, so that a new
variant of shred struct can include merkle tree hashes of the erasure
set.
removed implementation details from public interface
> hides implementation details of shred from its public interface

- streamer/src/quic.rs
There are a few conditions in which the data received on QUIC streams may get dropped. Some of these conditions do not have metrics or logging. Need a way to track such errors.
Added stats and datapoint to the relevant code paths.
Fixes #
> Add more datapoints in QUIC streamer

- web3.js/src/connection.ts
@lwus points out that the fact of a program trying to unsubscribe an RPC subscription listener multiple times is indicative of a program error. It's like a double-free, which is fatal in architectures that track ownership.
Here's the thing. This is JavaScript. I don't think I've ever seen a subscription API that punishes a double-unsubscribe with a fatal.
1. You can call `clearTimeout(id)`, `cancelAnimationFrame(id)`, and `clearInterval(id)` as many times as you like, with an id that may or may never have existed, and it will never fatal.
2. If you try to remove a DOM event listener for something that was never attached, the API will silently ignore it (`document.removeEventListener('click', function neverRegisteredThis() {});`)
In light of some changes coming down the pipe that change …
> fix: downgrade multiple unsubscribes from fatal to warning

- Cargo.lock
- account-decoder/src/parse_token.rs
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- rpc/src/parsed_token_accounts.rs
RPC now recognizes the spl-token-2022 program id, but cannot parse its accounts
All spl-token accounts are now parsed via spl-token-2022 (there are copious tests in SPL that demonstrate that base spl-token-2022 accounts parse the same as spl-token accounts).
Extensions are not yet parsed and represented, although extended accounts are otherwise parsed.
> Support token-2022 in RPC account parsing

- programs/stake/src/lib.rs
- rpc/src/rpc_pubsub.rs
The rpc test `test_account_subscribe()` fails once the stake minimum delegation is raised. See #24603 for more context.
- Update rpc test_account_subscribe() to be aware of stake minimum delegation
- Make `get_minimum_delegation` public
> Make rpc test_account_subscribe aware of stake minimum delegation

- core/src/window_service.rs
- gossip/src/duplicate_shred.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
Including the error in the output allows to debug when Shred::sanitize
fails.
return Error when Shred::sanitize fails
> returns Error when Shred::sanitize fails

- runtime/src/bank_forks.rs
When inserting parent into bank_forks, we perform a check for existence then do the actual insert. This can be optimized by do the insert first, then check that if return is None. Thus, it saves one lookup of the parents.  
Do the insert first, then check the return value.
Fixes #
> Check insert optimization for bank_forks

- metrics/src/metrics.rs
When logger is spammed, system will use more memory. However, there is no clear indicator of how many pending metrics are in the queue.
Add a report of metric command queue size.
Fixes #
> Report metric command queue size

- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
currently, `solana-test-validator -u m -c [ADDRESS]` will die if the account doesnt exist
i added a flag `--skip-missing-accounts` which ignores accounts that dont exist instead and continues fetching down the list. existing behavior without the flag is unchanged
my usecase is i want to take a transaction and generate a `solana-test-validator` command that fetches every account in its account list so i can easily replay the transaction in a test environment. without this flag i would need to fetch every account in my own code to see which ones dont exist, doubling my use of rpc resources
> Add skip account flag to solana-test-validator

- web3.js/scripts/typegen.sh
This reverts https://github.com/solana-labs/solana/pull/24567. That trick left a file name `lib/index.d.ts=` in the `lib/` directory on OS X.
> chore: re-re-repair web3.js typegen

- genesis/src/main.rs
- genesis/src/stakes.rs
- ledger-tool/src/main.rs
- runtime/src/genesis_utils.rs
- sdk/program/src/stake/state.rs
1. `StakeState::get_rent_exempt_reserve()` implicitly makes an assumption about the size of StakeStake, which may not be true in the future. 
2. Additionally, RPC clients tend to not use this method and go directly to `StakeStake::size_of()` anyway since an RPC client doesn't have a `Rent` struct to work with
3. With @brooksprumo's work at #24603, `StakeState::get_rent_exempt_reserve()` becomes even more useless since Stake accounts will require more than rent exempt reserve.
4. Scrubbing this function also points out a couple additional locations in the code base (ledger-tool/ and genesis/)  that will require updating as a part of #24603
> Remove StakeState::get_rent_exempt_reserve()

- Cargo.lock
- ledger/Cargo.toml
- ledger/src/leader_schedule_cache.rs
- programs/bpf/Cargo.lock
- programs/stake/src/lib.rs
The ledger test `test_next_leader_slot_next_epoch()` fails once the stake minimum delegation is raised. See #24603 for more context.
- Update ledger test_next_leader_slot_next_epoch() to be aware of stake minimum delegation
- ~~Make `get_minimum_delegation` public~~
> Make test_next_leader_slot_next_epoch() aware of stake minimum delegation

- web3.js/src/compute-budget.ts
- web3.js/src/index.ts
- web3.js/test/compute-budget.test.ts
Missing ComputeBudgetInstruction in web3 sdk
Adds ComputeBudgetInstruction to web3 sdk
> feat: add support for compute budget instructions

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/tests/programs.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/Cargo.toml
- rbpf-cli/src/main.rs
[solana_rbpf v0.2.27](https://github.com/solana-labs/rbpf/releases/tag/v0.2.27) was released.
v0.2.25 => v0.2.27
v0.2.26 was skipped as it had changes that were reverted, see: https://github.com/solana-labs/solana/pull/24647
> Bumps solana_rbpf to v0.2.27

- explorer/src/components/ProgramLogsCardBody.tsx
- explorer/src/utils/program-logs.ts
Some native programs don't emit logs and so the log pretty printer doesn't properly match up tx instructions and logs
Only match tx instructions to logs if the program id matches
Fixes #
> explorer: fix pretty printed logs for native programs without logging

- Cargo.lock
- rbpf-cli/Cargo.toml
- rbpf-cli/src/coverage.rs
- rbpf-cli/src/gcov.rs
- rbpf-cli/src/logger.rs
- rbpf-cli/src/main.rs
- adds DWARF parser using gimli
- adds coverage module to derive an execution trace to line numbers
- adds a gcov module to export a coverage profile to gcov intermediate JSON format
- add basic CLI logger
> rbpf-cli: add coverage flag

- runtime/src/bank.rs
rent collection has a mode when loading from snapshot where we need to build the list of skipped rewrites and not actually collect rent from any accounts or store any updates into the bank's append vec. When the validator was running, the population of the skipped rewrites list would have occurred when rent was collected for this bank. That occurred, but the only artifacts remaining are the accounts written to the bank's append vec. The accounts written to the append vec are not sufficient to calculate the bank's hash. We also need skipped rewrites. Skipped rewrites can be recalculated on snapshot load.
hook that mode up and correctly skip rewrites
Fixes #
> hookup 'just_rewrites'

- rpc/src/rpc_subscription_tracker.rs
- rpc/src/rpc_subscriptions.rs
- runtime/src/bank.rs
1. Make a subscription for `LogsSubscriptionKind::All` or `LogsSubscriptionKind::AllWithVotes`.
2. Also make a subscription for a specific pubkey using `LogsSubscriptionKind::Single(pubkey)`.
The presence of the `All` subscription starves the pubkey-specific ones. The `Single` subscribers will not be notified of any logs until the last `All` subscriber disappears.
cc/ @Riateche.
1. Uncomment [this test](https://github.com/solana-labs/solana/blob/c08cfafd6c599abbf440fbac1974ac8d754e265f/web3.js/test/connection.test.ts#L3723-L3762).
2. `solana-test-validator`
3. `solana logs`
4. `(cd web3.js && yarn && yarn test)`
The presence of the connected `solana logs` process will make that test fail. Quitting the `solana logs` process makes the test pass.
Always fill in the map of mentioned accounts. …
> Log subscription for `All` no longer clobbers `Some` subscription for pubkey

- keygen/src/keygen.rs
```
$ target/debug/solana-keygen grind --starts-with a:1
thread 'main' panicked at 'Command grind: Argument or group 'outfile' specified in 'conflicts_with*' for 'no_outfile' does not exist', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.8/src/build/debug_asserts.rs:171:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> keygen: fix debug build after migration to clap-v3-utils

- ledger/src/shred.rs
https://github.com/solana-labs/solana/pull/24653
introduced an off-by-one error in data-shred index sanitize.
Patched the off-by-one error and added test coverage.
> patches bug in data-shred index sanitize

- ledger-tool/src/main.rs
- programs/stake/src/stake_state.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
~~still draft; exploring best-desired least-intrusive code changes with some preparatory code cleanings (should be separated into its own pr)...~~
todo:
(See #22512)
(See #22512)
Fixes #22512
> Credits auto rewind on vote recreation

- core/benches/cluster_info.rs
- core/benches/cluster_nodes.rs
- core/src/outstanding_requests.rs
- core/src/serve_repair.rs
- ledger/src/shred.rs
`Shred::new_empty_data_shred` returns an invalid shred (i.e.
`shred.sanitize()` returns error). The method is only used in tests and
can be easily replaced with `Shred::new_from_data`. To keep the shred api
surface small, this commit removes this method.
Remove `Shred::new_empty_data_shred`.
> removes Shred::new_empty_data_shred

- gossip/src/cluster_info.rs
- perf/src/packet.rs
`ClusterInfo::handle_ping_messages()` currently builds a PacketBatch by constructing packets from serialized `PongMessages`. The packets are then copied into a PacketBatch within `PacketBatch::new_unpinned_with_recycler_data()`.
Serialize the `PongMessages` directly into the `PacketBatch` to save the final copy.
Fixes #
> Construct PacketBatches from PongMessages directly

- explorer/src/pages/TransactionDetailsPage.tsx
I got a question from community.
https://github.com/solana-labs/solana/blob/b48fd4eec273db5cd733532cdc73b7278954ab09/explorer/src/pages/TransactionDetailsPage.tsx#L276-L281
here we use Block instead of Slot
but actually it is a slot number not a block number.
replace Block with Slot
> explorer: replace Block with Slot

- web3.js/test/transaction.test.ts
See #24730.
Crank the timeout as a short-term mitigation.
> test: increase timeout for getEstimatedFee test

- programs/stake/src/stake_state.rs
It's difficult to remember what the return values from the Stake program's internal rewards-calculation functions signify. This one is especially awful:
```
fn calculate_stake_points_and_credits( ...) -> Option<(u64, u64, u64)> 
```
Replace opaque tuples with helper structs
No behavior changes
Open to bikeshedding on struct field names.
> Convert tuples to structs in Stake rewards-calculation functions

- metrics/Cargo.toml
- metrics/benches/metrics.rs
- metrics/src/counter.rs
- metrics/src/lib.rs
- metrics/src/metrics.rs
Metric agent use a HashMap of tuple of Vec and HashMap to store datapoint and counters. However, these data is flattened into a vector of datapoints before submission. 
This extra levels of nesting is not necessary, and can be removed.
The following shows the benchmarks comparison between the old and new implementation.
new 
```
test bench_counter_submission   ... bench:     890,414 ns/iter (+/- 634,869)
test bench_datapoint_submission ... bench:     487,493 ns/iter (+/- 106,276)
```
old
```
test bench_counter_submission   ... bench:     956,648 ns/iter (+/- 352,442)
test bench_datapoint_submission ... bench:     571,490 ns/iter (+/- 598,148)
```
For datapoints, the new implementation  is **17%** faster. For counters new implementation is …
> metric optimization: simply data structure used for metric datapoints and counter storage

- web3.js/.mocharc.js
- web3.js/package-lock.json
- web3.js/package.json
- web3.js/yarn.lock
You can use modern TypeScript language features in the code (like `??` and `?.`) but if you try to run the tests they'll explode.
UNTIL NOW.
Use the same compiler for the tests as we do for the production build.
> chore: compile web3.js tests with the same compiler as the build itself

- web3.js/rollup.config.js
- web3.js/src/loader.ts
- web3.js/src/message.ts
- web3.js/src/transaction-constants.ts
- web3.js/src/transaction.ts
Circular dependencies are actually really really bad. Let's eliminate them and keep them out.
_Musing: I haven't checked yet, but I wonder if this might have something to do with why some folks are having so much trouble doing tree-shaking._
* Turn circular dependencies into a build error.
* Actually fix the existing circular deps.
> Eliminate circular dependencies in web3 js

- Cargo.lock
- account-decoder/Cargo.toml
- client/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- scripts/patch-crates.sh
- transaction-status/Cargo.toml
- transaction-status/src/parse_token.rs
RPC now recognizes the spl_token_2022 program id, but cannot parse all its instructions.
Following the changes in #23067, this change set uses the spl_token_2022 to parse Instructions for RPC.
Currently supports only the subset of instructions also supported by the upcoming spl_token library.
It is expected that spl_token_2022 be an exact superset of spl_token, so using `spl_token_2022::instruction::Instruction::unpack` should be correct for instructions for both token programs. However, we will add tests upstream in SPL to be certain (edit) done here: https://github.com/solana-labs/solana-program-library/pull/3106
Note: I considered parsing extensions in this PR, but discovered that I need the various instruction decoders made `pub` in a new spl-token-2022 release. So in the interest of …
> Support token-2022 in RPC instruction parsing

- streamer/src/quic.rs
The newly added counters are not being swapped with 0. This causes counters to keep growing. It makes more sense to reset to 0 on every report.
Swap counters with 0 on reporting.
Fixes #
> Swap quic counters with 0 after reporting

- streamer/src/quic.rs
The original PR (#24535) was merged but caused flakiness in the CI. `test_quic_server_block_multiple_connections` was failing sporadically. #24535 was reverted due to the CI failures.
This is a resubmit of the original PR along with a fix to the flaky test.
Fixes #
> Increase worker thread limits in quic streamer runtime

- docs/src/cluster/overview.md
Typo in docs I found while reading.
follow -> following
> fix typo in cluster docs

- docs/src/developing/clients/javascript-api.md
There's a small typo in the javascript-api docs.
This PR fixes the typo by removing a duplicated word and adds code styling to specific text for better clarity.
> Typo fix in javascript-api docs

- ledger/src/blockstore.rs
- rpc/src/rpc.rs
After #23403, the first two blocks of a fresh validator become inaccessible to RPC after the first root is set. This is because of some assumptions that are true for a ledger that has had at least one prune or was booted from a snapshot, but not true for a ledger fresh from genesis.
For one, `Blockstore::lowest_slot()` (which `Blockstore::get_first_available_block()` uses to seed its root iterator) explicitly skips slot 0, even though it is populated and has SlotMeta. Secondly, the genesis block doesn't need a populated parent block to calculate parent blockhash, because it is *genesis*.
- Add `Blockstore::lowest_slot_with_genesis()` with the same logic as `Blockstore::lowest_slot()`, except the return slot may be zero
- Rework logic in `Blockstore::get_first_available_block()` to return …
> Fix get_first_available_block for genesis; also make get_blocks(_with_limit) consistent

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/rust/sysvar/src/lib.rs
- programs/bpf/rust/sysvar/tests/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/Cargo.toml
- rbpf-cli/src/main.rs
- sdk/program/src/program_stubs.rs
Syscall registration and binding are currently disjoint operations requiring the callers to explicitly do both for each syscall.
This can lead to mismatch or missing registration/binds and complicates the code. Another side effect is that it is difficult/impossible given the current API for callers to filter syscalls at the registration stage but allow them at the binding stage. One example is the effort to deprecate/disallow syscalls by preventing new deployments of programs that rely on a disallowed syscall while continuing to support existing programs that already rely on them.
These changes depend and build off the changes here: https://github.com/solana-labs/rbpf/pull/293
Syscalls are registered once, and later the bind operation uses a common context to bind all the previously …
> Simplify register and bind

- explorer/src/components/block/BlockAccountsCard.tsx
- explorer/src/components/block/BlockHistoryCard.tsx
- explorer/src/components/block/BlockOverviewCard.tsx
- Add support for "accountFilter" url param
- When accounts are clicked from a block's "Accounts" tab, it will open a filtered view of txs that load that account
Fixes #
> explorer: Support filtering block transactions by account

- runtime/src/bank.rs
The bank test `test_bank_cloned_stake_delegations()` fails once the stake minimum delegation is raised. See #24603 for more context.
- Update bank test_bank_cloned_stake_delegations() to be aware of stake minimum delegation
> Make test_bank_cloned_stake_delegations() aware of stake minimum delegation

- send-transaction-service/src/send_transaction_service.rs
Problem
In PR review https://github.com/solana-labs/solana/pull/24083/files#r852661162. We are concerned the leader info might be out dated if the retry queue is long causing large number transactions sent to outdated leaders and increasing the load in the network.
Proposed Solution
A leader info refresher can be used to ensure the leader info is up-to-date before being used in sending transactions. The refresher can update the new leader with updated endpoints.
#24525
> Leader info refresher

- account-decoder/src/lib.rs
- account-decoder/src/parse_token.rs
- account-decoder/src/parse_token_extension.rs
After #24619, Rpc can parse token-2022 accounts, but not the extensions
Parse all token-2022 Account and Mint extensions, except `ConfidentialTransferMint` and `ConfidentialTransferAccount`. I left these out largely due to PR size, but maybe it makes sense to hold off until closer to confidential-transfer launch anyway. Each of those extensions will appear in the extension list, but without any `state` (much like the `immutableOwner` in the example below).
- If any extension fails to parse, this api will currently return `unparseableExtension` in the list. I thought this was better than failing either the extension-parsing, or the account-parsing altogether. Thoughts?
- Thoughts on the response structure? Examples:
```
// An extended Mint
...
"parsed": {
"info": {
"decimals": 2, …
```
> Parse token-2022 account extensions (mostly)

- runtime/src/bank.rs
`test_rent_eager_collect_rent_in_partition` currently needs to be updated every time a dev adds a feature. This is not obvious to devs, and shouldn't be necessary.
Update test assert based on number of features. This can be made more precise and helpful for rewrite-skip development later.
cc @joncinque
> Make test less brittle

- client-test/tests/client.rs
- core/benches/consensus.rs
- core/src/ancestor_hashes_service.rs
- core/src/cluster_info_vote_listener.rs
- core/src/cluster_slot_state_verifier.rs
- core/src/commitment_service.rs
- core/src/consensus.rs
- core/src/heaviest_subtree_fork_choice.rs
- core/src/optimistic_confirmation_verifier.rs
- core/src/replay_stage.rs
- core/src/vote_simulator.rs
- core/tests/snapshots.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore_processor.rs
- rpc/src/optimistically_confirmed_bank_tracker.rs
- rpc/src/rpc.rs
- rpc/src/rpc_pubsub.rs
- rpc/src/rpc_subscriptions.rs
- runtime/src/bank_forks.rs
It's too easy to hold onto a borrowed value returned from `BankForks` and forget that it keeps a read lock.
Case in point: https://github.com/solana-labs/solana/pull/24799
- Removed unused `BankForks::snapshot_config` method
- `BankForks::banks` now returns an owned `HashMap` because it's cheap to clone
- `BankForks::descendants` now returns a cloned value because we clone immediately everywhere we call this method
- `BankForks:get_with_checked_hash` and `BankForks::get` both return an owned `Arc<Bank>`
Fixes #
> Update all BankForks methods to return owned values

- web3.js/test/connection.test.ts
These tests were never correct, because `getBlocks` is supposed to return the blocks between `startSlot` and `endSlot` _inclusive_.
I think they were _accidentally_ working before, because of a bug in the validator that has since been fixed in #23853.
* Wait for there to be at least 2 blocks, so that the tests have something to exercise.
* Fix the mock data to actually return the blocks between `startSlot` and `endSlot` _inclusive_.
* Make the test resilient to pruning by setting `startSlot` to whatever `firstAvailableBlock` returns (this will make the web3.js tests less flaky 🎉)
> test: repair web3.js getBlocks tests

- runtime/tests/stake.rs
The stake integration tests fails once the stake minimum delegation is raised. See #24603 for more context.
- Update stake integration tests to be aware of stake minimum delegation
> Make stake integration tests aware of stake minimum delegation

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/connection.ts
- web3.js/test/connection-subscriptions.test.ts
- web3.js/test/mocks/rpc-http.ts
- web3.js/test/mocks/rpc-websockets.ts
- web3.js/test/websocket.test.ts
- web3.js/yarn.lock
Props to @lwus for bringing to my attention that:
1. If you make two RPC subscriptions for fundamentally the same subscription (ie. same method, same params) only the first subscription's callback will ever fire.
2. If you start with more than one client subscription for fundamentally the same RPC subscription, and then dispose of _one_ of them, the client will unsubscribe _all_ of them.
3. If you make two RPC subscriptions for fundamentally the same subscription, we needlessly make two RPC subscription requests to the server, when only one is needed. 
This PR represents a pretty massive rewrite of the client subscriptions tracker. Let me lay out the goal of every commit:
* As preparation, we create a type called `ClientSubscriptionId` to disambiguate it from _server_ subscription ids. …
> fix: the one where we fix client subscriptions

- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shredder.rs
No need to expose shreds internals to public interface.
removed `SHRED_PAYLOAD_SIZE` from shred public interface
> removes SHRED_PAYLOAD_SIZE from shred public interface

- core/src/banking_stage.rs
- core/src/cluster_info_vote_listener.rs
- core/src/fetch_stage.rs
- core/src/warm_quic_cache_service.rs
- rpc/src/optimistically_confirmed_bank_tracker.rs
- rpc/src/rpc.rs
- rpc/src/rpc_service.rs
- rpc/src/rpc_subscriptions.rs
- Getting the bank for an RPC request grabs the bank forks read lock for confirmed commitments even when it doesn't need it
- REST endpoints hold bank forks read lock for no reason
- Lock guards are used in temporary variables for match-like expressions
- Deadlock for macos reintroduced in https://github.com/solana-labs/solana/pull/24801
Fixes #
> Avoid holding lock guards in match expressions

- runtime/src/bank.rs
In `Bank::hash_internal_state()`, the call to rehash unnecessarily holds the `HardForks` lock longer than necessary.
Note that the `hash::extend_and_hash()` function is likely very fast, but we were also holding the lock while performing I/O via the `info!()` call, which is relatively an eternity.
This investigation was prompted by @buffalu in Discord and their comment here: https://github.com/solana-labs/solana/pull/24799#issuecomment-1112382120
Get the hash data outside of the `if let` so as to not hold the lock unnecessarily.
> Do not hold lock unnecessarily when hashing

- docs/src/developing/programming-model/runtime.md
The compute budget docs are out of date
> docs: Update outdated compute budget docs

- cli/src/feature.rs
- Features are always activated at epoch boundaries so it's not very useful to display the activation slot.
- The status of old features is not displayed even when querying specifically for them
- Use the epoch schedule to display the activation epoch of features instead of the activation slot
- Always display the status for old features if they are being specifically queried for
- Display the epoch for a pending feature
Fixes #
> cli: Feature status improvements

- cli/tests/stake.rs
The CLI stake tests fail once the stake minimum delegation is raised. See #24603 for more context.
- Increase the stake amounts
- Remove solana_logger::setup() from tests to be less noisy by default
> cli stake tests: Increase stake amounts to handle raising minimum delegation

- ledger/src/blockstore_db.rs
- validator/src/main.rs
Currently, the number of RocksDB perf samples is controlled by an env arg
which is later handled using a lazy_static variable.  However, there is a known
performance overhead of using lazy_static as mentioned in
https://github.com/solana-labs/solana/pull/6472.
Instead, this PR uses a hidden validator argument for controlling the number
of RocksDB perf samples that replaces the use of lazy_static.
This PR depends on #24761.
> (LedgerStore) Hidden validator argument for RocksDB perf samples

- ledger/src/blockstore_db.rs
- validator/src/main.rs
This PR replaces the use of thread_rng in RocksDB perf metric samples by
AtomicU32 with Ordering::Relaxed to improve the performance of determining
whether to sample the current RocksDB's read/write perf metric.
This PR depends on #24761, and #24682.
> (LedgerStore) Improve RocksDB perf metric samples

- ledger-tool/src/bigtable.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_db.rs
- ledger/src/blockstore_processor.rs
- local-cluster/tests/common.rs
- local-cluster/tests/local_cluster_flakey.rs
The `AccessType` enum specifies different modes of opening RocksDB. As of right now, there are three values that function as follows
- `PrimaryOnly` ==> Gives read+write access, this is what a running validator process has/needs
- `PrimaryOnlyForMaintenance` ==> Gives read+write access, used by `ledger-tool purge` only
- `TryPrimaryThenSecondary` ==> Tries to open with primary access, but opens secondary if primary fails. Primary will fail if the ledger is already open (ie by the validator process), so this mode allows `ledger-tool` operations while the validator is still running.
- If Primary succeeds, read+write access is obtained
- If Primary fails and Secondary succeeds, only read access is obtained (Secondary is inherently read-only)
If a use case is fine with secondary, we shouldn't …
> Change Blockstore TryPrimaryThenSecondary to Secondary only

- metrics/src/metrics.rs
When we take the counter points from hashmap and convert them to datapoints for submission, the counter points are by reference. But the *From* trait for conversion expects counter point by value. Unnecessary copy incurred.  
Avoid copy when converting counters to datapoints
before:
```
test bench_counter_submission   ... bench:     958,245 ns/iter (+/- 587,452)
test bench_datapoint_submission ... bench:     457,622 ns/iter (+/- 58,431)
test bench_random_submission    ... bench:     660,389 ns/iter (+/- 94,540)
```
after:
```
test bench_counter_submission   ... bench:     496,585 ns/iter (+/- 97,219)
test bench_datapoint_submission ... bench:     484,038 ns/iter (+/- 61,726)
test bench_random_submission    ... bench:     488,835 ns/iter …
```
> Speed up metrics counter point submission

- explorer/src/components/block/BlockOverviewCard.tsx
- explorer/src/components/block/BlockProgramsCard.tsx
Old blocks don't have transaction metadata so the explorer shows that the transactions failed.
Don't show success details if metadata is missing for any tx in a block
Fixes #
> explorer: Don't show successful count if meta missing

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/tests/programs.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/Cargo.toml
- rbpf-cli/src/main.rs
[solana_rbpf v0.2.28](https://github.com/solana-labs/rbpf/releases/tag/v0.2.28) was released.
v0.2.26 => v0.2.28
The bump to v0.2.27 was reverted, see: https://github.com/solana-labs/solana/pull/24724
> Bump solana_rbpf to v0.2.28

- explorer/src/utils/program-logs.ts
@austbot ran into a problem where this transaction fataled the Explorer:
http://explorer.solana.com/tx/4zvAQJKkeY3RvgxLN4fDYBYRNKKEy77ptFAjDmPoEqpjnjQyxUhQVZ1t7RThsjNoNXeQbTbEqmeMK4sFGhHmi3r1?cluster=devnet
The reason was because this tx had _both_:
1. A log that starts with the word ‘failed’, and
2. A first-class `TransactionError`.
The ‘failed’ transaction tried to decrement the indent level, but it was _already_ at the top level.
* Make sure never to try to produce an indent marker when the depth is less than 2.
This doesn't fix the problem of this particular transaction having weird depth-tracking behavior, but at least it favors ‘bad rendering’ over ‘fataling the entire page.’
1. Visit http://localhost:3000/tx/4zvAQJKkeY3RvgxLN4fDYBYRNKKEy77ptFAjDmPoEqpjnjQyxUhQVZ1t7RThsjNoNXeQbTbEqme …
> fix: don't fatal Explorer when there's a 'failed' type message at the top level

- bench-tps/src/cli.rs
- bench-tps/src/main.rs
ThinClient with gossip mode for bench-tps is annoying to use because it doesn't know how long to wait for the target node to appear also it takes a while to find it.
Let me set my own custom ThinClient addresses.
Fixes #
> Add custom rpc/tpu address options for bench-tps ThinClient

- Cargo.lock
- ledger/Cargo.toml
- ledger/src/shred.rs
Working towards embedding versioning into shred binary.
Need to maintain backward compatibility while changing shred struct.
Added hard-coded tests to assert that shreds are backward
compatible when serialized and de-serialized.
> adds hard-coded tests for backward compatibility of shreds serialization

- core/src/broadcast_stage/standard_broadcast_run.rs
- ledger/src/shred.rs
- ledger/src/shredder.rs
shred flags uses raw bitmasking ops which lacks type-safety:
https://github.com/solana-labs/solana/blob/a829ddc92/ledger/src/shred.rs#L112-L114
use `bitflags` crate instead.
> defines shred flags using bitflags crate

- ledger/src/shred.rs
Current serialize/de-serialize code for shreds manually tracks offsets
into the payload; This can instead be done with std::io::Cursor.
https://github.com/solana-labs/solana/blob/e812430e2/ledger/src/shred.rs#L232-L258
* serialize/deserialize shred headers through a Cursor.
> (de-)serializes shred headers through a Cursor

- ledger-tool/src/main.rs
Ledger-tool doesn't save new snapshots to --snapshot-archive-path #24875 
Fixed behavior when choosing an `output-dir` for `create-snapshot` command.
If `output-dir` is not specified in args then it will be `--snapshot-archive-path` if present, otherwise `--ledger`. Before this fix, `--snapshot-archive-path` was not checked.
Fixes #24875
> ledger-tool: save new snapshots to --snapshot-archive-path

- explorer/src/index.tsx
Until we mount the app using the `createRoot()` API, the Explorer will run in React 17 compatibility mode.
* Enable React 18 through use of `createRoot` API.
Clicked through https://solana-explorer-clvt2er0x-steveluscher.vercel.app/
> fix: enable React 18 in Explorer

- explorer/src/components/ProgramLogsCardBody.tsx
- explorer/src/components/instruction/InstructionCard.tsx
- explorer/src/index.tsx
- explorer/src/pages/inspector/InstructionsSection.tsx
- explorer/src/providers/scroll-anchor.tsx
- explorer/src/scss/_solana.scss
- explorer/src/utils/get-instruction-card-scroll-anchor-id.ts
- explorer/src/utils/url.ts
So there I am, reading through the program logs, wishing that I could click on one of the numbered instructions to jump up to where it's described.
* Prevent the `clusterPath` helper from carrying the `hash` between routes. That's never the right thing to do when linking to a brand new view.
* Extract the format of the transaction card URL fragment into a helper so that we can never apply it incorrectly.
* Create a brand new React context and hook that lets you attach to a scroll target, announce when it has been rendered, and scroll to it if the hash in the URL targets it.
* Turn the instruction header in the program logs into a link.
*Clicking an instruction header*
https://user-images.githubusercontent.com/13243/166087326-70406de9-79a9-46a3-ab6c-ea7209fec8dd.mov
*Visiting a permalink …
> feat: you can now deep link to a particular instruction in Explorer

- docs/src/cli/install-solana-cli-tools.md
The simplest way of installing Solana CLI tool requires you to modify your $PATH variable manually. Given that developers are likely to have Homebrew installed on their machines, it would be easier to run the Homebrew install script. This will ensure solana tools are installed to the correct directory, are up to date and automatically added to $PATH.
Added Homebrew installation guide for solana tools.
> Update install-solana-cli docs with Homebrew instructions

- client/src/connection_cache.rs
`get_connection` takes excessive amount of time in `lock()` and on a cache hit. The time is in terms of 2-3 seconds.
Replace `Mutex` with `RwLock` and perform `read` lock for looking up the cache. The `write` lock is acquired only on cache miss for adding the new value.
Also, replace `LruCache` with a `BTreeMap`.
Fixes #
> Use RwLock instead of Mutex in QUIC connection cache

- ledger/src/blockstore_processor.rs
Our test code wrappers take an owned `ProcessOptions` struct whereas the underlying blockstore_processor functions they call only require a reference.
Change our test code wrappers to only require a reference so they don't have to clone the options struct if they call more than one of the underlying functions.
Originally called out here:
https://github.com/solana-labs/solana/pull/23391#discussion_r862187501
> Pass ProcessOptions struct around by reference

- banking-bench/src/main.rs
Banking bench has certain portions that are hard to read
Refactor and cleanup
Fixes #
> Cleanup banking bench

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
- ledger/src/lib.rs
blockstore_db.rs becomes bigger.
This PR creates blockstore_metric.rs and moves metric-related functions out from blockstore_db.rs.
> (LedgerStore) Move metric-related functions to blockstore_metrics.rs

- programs/zk-token-proof/src/lib.rs
The ZK proof for `VerifyWithdrawWithheldTokens` instructions are verified as in a `VerifyWithdraw` instruction causing it to always fail.
Fixed the issue by interpretting the `VerifyWithdrawWithheldTokens` under the same context.
> zk-token-sdk: verify WithdrawWithheldTokens proof under the correct context

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
- ledger/src/lib.rs
blockstore_db.rs becomes bigger.
Move trait ColumnMetrics and metric-macros to blockstore_metric.rs out from blockstore_db.rs.
> (LedgerStore) Move trait ColumnMetrics and metric-macros to blockstore_metrics.rs

- bench-tps/src/main.rs
In bench-tps with the --rpc-addr/--tpu-addr flags --use-tpu-quic isn't respected
Move test for quic flag out of the gossip mode if block.
Fixes #
> Fix quic mode with thinclient bench-tps

- ledger/src/shred.rs
- perf/src/packet.rs
Though current Shred struct is **not** vulnerable to this, adding `with_limit`
causes pre-allocation size to be limited to prevent against memory
exhaustion attacks:
https://github.com/bincode-org/bincode/blob/2d3f42034/readme.md
The commit limits pre-allocation size when deserializing shreds.
> limits pre-allocation size when deserializing shreds

- core/src/sigverify_stage.rs
Previously it was impossible to determine the total time the stage spent on dedup/discard/verify within a measurement window.
It's not possible to reconstruct these values from the histogram based data, because for large amounts of num_packets, all these values will be 0.
See #24747, where I'd have liked to have this data available.
Add metrics.
@sakridge
> SigVerify: Add total time metrics for dedup/discard/verify

- runtime/src/accounts_db.rs
- runtime/src/expected_rent_collection.rs
Rent collector code uses rent collector's epoch schedule.
The code used to identify partition index for a pubkey needs to use the bank's epoch schedule. These differ on devnet.
Fixes #
> use correct epoch schedule

- ledger-tool/src/main.rs
In validator, we could use `no_os_memory_stats_reporting_arg` to disable reporting memory_stats. It would be nice if we can disable memory stats reporting for ledger-tool too.
Add `no_os_memory_stats_reporting_arg` to ledger tool.
Fixes #
> Add no_os_memory_stats_reporting_arg to leger tool

- docs/src/developing/programming-model/runtime.md
- program-runtime/src/compute_budget.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
Defaulting the tx-wide cap to the max overestimates what a transaction will need and later will skew transaction scheduling for transactions that don't explicitly request
Default the units to 200k per non-compute budget instruction in the transaction
Fixes #
Feature Gate Issue: #24898
> default compute units per instruction

- perf/src/sigverify.rs
println! in tests puts a whole bunch of junk in the CI log making it hard to see what is going on.
Convert println! to debug! so these messages can be enabled with RUST_LOG if desired for debugging.
Fixes #
> Convert println! to debug! in shrink tests

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
blockstore_db.rs becomes bigger.
Move BlockstoreRocksDbColumnFamilyMetrics to blockstore_metric.rs out from blockstore_db.rs.
> (LedgerStore) Move BlockstoreRocksDbColumnFamilyMetrics to blockstore_metrics.rs

- client/src/nonblocking/rpc_client.rs
The examples in solana_client::nonblocking::rpc_client are using the blocking RpcClient.
Use the nonblocking client.
> Make nonblocking RpcClient examples use nonblocking RpcClient

- cli/src/stake.rs
The CLI returns the incorrect error during `withdraw-stake`.  Unearthed while looking at stake-related issues and projects :smile: 
Format the error as a `StakeError` instead of a `SystemError`. So with a lockup, instead of returning `Error: account does not have enough SOL to perform the operation`, you'll see `Error: lockup has not yet expired`.
Fixes #9744
> cli: Fix `withdraw-stake` error display

- runtime/src/message_processor.rs
See https://github.com/solana-labs/solana/issues/24705
Don't just skip instructions when `is_precompile` by `continue`,
instead have them be recorded in the `transaction_context`.
Additionally feature gated behind `record_instruction_in_transaction_context_push`.
Fixes #24705
Updates Feature Gate: https://github.com/solana-labs/solana/issues/24965
> Record instructions which are precompiles

- runtime/src/accounts_db.rs
#24710
Log all pubkeys & hashes for accounts that are in slots we purge. Goal is to pinpoint the discrepancy in the slot that caused the accounts hash on the slot to differ.
Fixes #
> log write cache contents from purge_slots_from_cache_and_store

- ledger/src/blockstore_processor.rs
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
When running ledger tool, we run a final hash calc check when we halt. based on which slots get flushed from the cache, we sometimes end up with cap mismatches between bank and accounts hash calc. This is misleading and incorrect. This startup/ledger-tool only code path needs to allow us to use the write cache for this case.
Fixes #
> allow ledger-tool halt at slot to calc hash using write cache

- docs/src/developing/programming-model/runtime.md
unclear description of how tx-wide compute budget will calculate the default maximum units
attempt to clarify it
> docs: clarify tx-wide default max units explainer

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/system-program.ts
- web3.js/test/system-program.test.ts
- web3.js/yarn.lock
_Note: this PR was made by @konytech, but @steveluscher is an idiot and accidentally corrupted #24797; reopened it as this PR_.
System transfers only support the 'number' type for lamports. For transferring large amounts, supporting 'bigint' like it's done in the spl-token library is required.
This follows the same encoding/decoding approach used by the spl-token library:
https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/instructions/transfer.ts#L56
- Add bigint support to system transfers
- Add @solana/buffer-layout-utils package required to decode u64 to bigint
- Fix tests with this new type support
> fix: add bigint support to system transfers

- .mergify.yml
Automerge doesn't work if docs files were updated because the travis job doesn't exist anymore but is still required for automerge
- Leave placeholder for docs GitHub action check
> Remove travis success condition for automerging doc changes

- explorer/src/providers/accounts/utils/isMetaplexNFT.ts
Explorer currently defines an NFT as any token with decimals = 0 and a supply of exactly one. However, the new [Fungible Asset](https://docs.metaplex.com/token-metadata/specification#token-standards) specification allows for NFT-style tokens with a supply of greater than one.
Change the `isMetaplexNFT` method to consider the token's `tokenStandard`, if defined.
Fixes #
> feat: Support Fungible Asset token standard

- runtime/src/bank.rs
- runtime/src/expected_rent_collection.rs
another straggler failing because devnet has 2 different epoch schedules.
without this, devnet ends up with vote failures because of bank hash mismatches
Fixes #
> maybe_update_rent_epoch_on_load uses correct EpochSchedule

- bench-streamer/src/main.rs
- core/src/ancestor_hashes_service.rs
- core/src/fetch_stage.rs
- core/src/serve_repair_service.rs
- core/src/shred_fetch_stage.rs
- gossip/src/gossip_service.rs
- streamer/src/streamer.rs
Fetch stage doesn't report metrics by default
- Collect stats by default in `streamer::receiver`
- Report stats for all fetch stage receivers on a regular interval
Fixes #
> Collect stats in streamer receiver and report fetch stage metrics

- sdk/program/src/message/legacy.rs
- sdk/program/src/message/versions/v0/loaded.rs
A bool variable is computed before it's actually used, resulting in a needless computation a reasonable percentage of the time.
Moved the two function calls involved to be made only when needed. Since these two calls are deceptively slow (and any slowness is exacerbated by code that's called once per referenced account per transaction), this results in a measurable speedup. This code is used in several places, including by the leader for every transaction in the block.
Fixes #
> Reorder a boolean computation to speed up processing

- docs/src/proposals/fee_transaction_priority.md
> Proposal for transaction scheduler based on fee priority 

- Cargo.lock
- banks-client/Cargo.toml
- banks-server/Cargo.toml
- client-test/Cargo.toml
- client/Cargo.toml
- core/Cargo.toml
- faucet/Cargo.toml
- ledger-tool/Cargo.toml
- ledger/Cargo.toml
- net-utils/Cargo.toml
- program-test/Cargo.toml
- programs/bpf/Cargo.lock
- replica-lib/Cargo.toml
- rpc-test/Cargo.toml
- rpc/Cargo.toml
- streamer/Cargo.toml
- test-validator/Cargo.toml
The RPC stall problem we are debugging appears when upgrading tokio from v1.15 to v1.16. Our v1.10 is already on tokio v1.17, which means it suffers the stalls.
Rollback tokio, and pin to the long-term support release v1.14
Inspired by https://github.com/solana-labs/solana/issues/24644
> Rollback tokio to LTS release v1.14

- Cargo.lock
- Cargo.toml
- scripts/cargo-install-all.sh
- sdk/bpf/c/bpf.mk
- sdk/bpf/c/inc/sol/blake3.h
- sdk/bpf/c/inc/sol/inc/assert.inc
- sdk/bpf/c/inc/sol/inc/blake3.inc
- sdk/bpf/c/inc/sol/inc/cpi.inc
- sdk/bpf/c/inc/sol/inc/keccak.inc
- sdk/bpf/c/inc/sol/inc/log.inc
- sdk/bpf/c/inc/sol/inc/pubkey.inc
- sdk/bpf/c/inc/sol/inc/return_data.inc
- sdk/bpf/c/inc/sol/inc/secp256k1.inc
- sdk/bpf/c/inc/sol/inc/sha.inc
- sdk/bpf/c/inc/sol/inc/string.inc
- sdk/bpf/c/inc/sol/keccak.h
- sdk/bpf/c/inc/sol/return_data.h
- sdk/gen-headers/Cargo.toml
- sdk/gen-headers/src/main.rs
Syscalls are functions implemented by the runtime system. In generated on-chain programs these functions appear as undefined symbols. Instead of using symbolic names of the syscall functions, we generate hash values from the function names and use these values as function addresses to assign to corresponding function pointers in code.  The run-time translates these hash values into actual runtime functions implementing the syscalls. This eliminates the undefined symbols and simplifies the loading of the on-chain programs.
Use template header files to generate the actual C header files in which syscall function declarations are replaced by functions that use sycall symbol hashes to invoke the syscall via an initialized function pointer.  A build time script regenerates the correct C header …
> Generate syscall headers

- local-cluster/src/local_cluster.rs
- local-cluster/tests/common.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_flakey.rs
- local-cluster/tests/local_cluster_slow_1.rs
- local-cluster/tests/local_cluster_slow_2.rs
The local-cluster tests fail/hang once the stake minimum delegation is raised. See #24603 for more context.
Update the local-cluster tests to have-and-use a higher default stake amount.
> Update local-cluster tests to work with higher minimum stake delegation

- .github/workflows/docs.yml
https://github.com/solana-labs/solana/pull/25029 added a new action that exits with return code 1 in a scenario that is perfectly valid, thus making the whole job fail.
> Make workflow not fail if no doc files changed

- core/src/consensus.rs
- core/src/progress_map.rs
- ledger/src/blockstore_processor.rs
- ledger/src/lib.rs
- ledger/src/staking_utils.rs
- runtime/src/bank.rs
- runtime/src/epoch_stakes.rs
- runtime/src/stake_account.rs
- runtime/src/stakes.rs
- runtime/src/vote_account.rs
A VoteAccount may only wrap an account if the account owner is
`solana_vote_program:id` or this check returns true:
`solana_vote_program::check_id(account.owner())`
Check the account owner when initializing a vote-account.
> checks the account owner when initializing a vote-account

- Cargo.lock
- banks-client/Cargo.toml
- banks-server/Cargo.toml
- client/Cargo.toml
- core/Cargo.toml
- faucet/Cargo.toml
- ledger-tool/Cargo.toml
- ledger/Cargo.toml
- net-utils/Cargo.toml
- program-test/Cargo.toml
- programs/bpf/Cargo.lock
- replica-lib/Cargo.toml
- rpc-test/Cargo.toml
- rpc/Cargo.toml
- streamer/Cargo.toml
The RPC stall problem we are debugging appears when upgrading tokio from v1.15 to v1.16. Currently, our branches do not restrict the tokio minor or patch versions
Pin tokio to the the long-term support release v1.14
Inspired by #24644
> Pin tokio to LTS release v1.14

- runtime/src/cost_model.rs
Code that computes costs of transactions is quite slow.
Combine two cost-computation functions (that each loop through instructions) into a single function.
Fixes #
> Speed up get-data-cost function

- runtime/src/accounts_index.rs
- runtime/src/bank.rs
bank benches (and all benches) need to use an appropriate # of bins to achieve comparable parallelism wrt locks.
Fixes #
> Bank::new_for_benches uses bench config

- core/src/find_packet_sender_stake_stage.rs
- core/src/tpu.rs
Both FindPacketSenderStake threads interleaved metrics datapoints. The values had no units.
- separate names for vote and non-vote thread
- time unit postfixes (one is in ns!)
@jstarry
> FindPacketSenderStake: Improve metrics

- core/src/banking_stage.rs
- entry/benches/entry_sigverify.rs
- entry/src/entry.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- rpc/src/rpc.rs
- rpc/src/transaction_status_service.rs
- runtime/src/bank.rs
- runtime/src/cost_tracker.rs
- sdk/program/src/message/versions/mod.rs
- sdk/program/src/message/versions/v0/mod.rs
- sdk/src/feature_set.rs
- sdk/src/transaction/sanitized.rs
- sdk/src/transaction/versioned.rs
- transaction-status/src/lib.rs
Transaction ingestion cannot do static analysis over transaction program instructions to determine user fees, precompile usage, and estimated compute without first loading addresses from on-chain lookup tables.
- Update transaction sanitization to require that tx instructions use static program ids
Fixes #
Feature Gate Issue: https://github.com/solana-labs/solana/issues/25034
> Fail tx sanitization when ix program id uses lookup table

- core/src/cluster_slot_state_verifier.rs
- core/src/window_service.rs
- Change multiline logs to single line
- Make `duplicate_slot_sender` and `duplicate_slots_sender` consistent
> Clean up logging and make variables consistent

- runtime/src/accounts_db.rs
Reverts solana-labs/solana#24954
Unfortunately, this blows the stack on ledger-tool and possibly on a validator.
```
4423:     0x55839d80006d - solana_runtime::bank::Bank::pay_validator_rewards_with_thread_pool::{{closure}}::{{closure}}::hfe73de5a5bbf6439
4424:     0x55839d7f34b4 - rayon::iter::plumbing::Folder::consume_iter::h212ec3edb3337b65
4425:     0x55839d6980bf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc1a34defd4bbaf8e
4426:     0x55839d658bc4 - std::panicking::try::h65214c4008e480ad
4427:     0x55839d6d8c18 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h399ae10d516d6c82
4428:     0x55839cdf5d4e - rayon_core::registry::WorkerThread::wait_until_cold::h8b957a1be346def2
4429:     0x55839cdbfa07 - …
```
> Revert "uses designated thread-pools for account db parallel ops"

- streamer/src/quic.rs
No sender stake on quic packet meta.
Add the stake from the connection table.
Fixes #
> Add sender stake to quic packets

- programs/stake/src/lib.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- sdk/src/feature_set.rs
The minimum stake delegation is too low. For more information, see the main issue: https://github.com/solana-labs/solana/issues/22559
- Add feature gate to raise minimum stake delegation to 1.0 SOL
- Actually set minimum delegation to 1 SOL
- Use stake_raise_minimum_delegation feature in the stake program impl
- Refactor tests to run for both old and new behavior
Feature Gate Issue: #24357
> Raise minimum stake delegation to 1 SOL

- program-runtime/src/compute_budget.rs
- programs/bpf_loader/src/syscalls.rs
- sdk/src/feature_set.rs
- zk-token-sdk/src/curve25519/curve_syscall_traits.rs
- zk-token-sdk/src/curve25519/edwards.rs
- zk-token-sdk/src/curve25519/ristretto.rs
Adding syscalls for curve25519 group operations for Edwards and Ristretto representations. These syscalls are feature gated by `curve25519_syscall_enabled`.
> Curve25519 syscall group ops

- core/src/banking_stage.rs
`BankingStage` is not able to keep up with `SigVerify` stage in case of QUIC.
The QUIC transactions are received as a packet batch of size 1. This is causing the channel between sigverify stage and banking stage to back up, as the banking stage is not doing greedy receive (all other stages in the pipeline are doing it via use of `recv_packet_batches`). This PR adds the greedy receive to the banking stage.
Fixes #
> Greedy receive in banking stage

- ledger-tool/src/main.rs
ledger-tool's non-primary access accounts directory can grow in size since it is never cleared.
Clear the directory (if it exists) when ledger-tool will use the directory to load accounts into.
Fixes #
> ledger-tool: Clear accounts directory

- core/src/banking_stage.rs
- core/src/unprocessed_packet_batches.rs
- sdk/program/src/message/versions/mod.rs
- sdk/program/src/message/versions/sanitized.rs
- sdk/src/transaction/sanitized.rs
- sdk/src/transaction/versioned/mod.rs
- sdk/src/transaction/versioned/sanitized.rs
The banking stage needs to efficiently sanitize transactions and messages to extract fee information. There is a `SanitizedTransaction` type but it requires using a bank to load addresses from an on-chain lookup table which is expensive and shouldn't be done before collecting fee information for tx prioritization.
- Add `SanitizedVersionedTransaction` and `SanitizedVersionedMessage` types which are lightweight and allow banking stage to efficiently collect fee information without address loading.
- Integrate the new sanitized types with the existing `SanitizedTransaction` type to avoid redoing any sanitization work.
Fixes #
> Add sanitized types for use in banking stage

- web3.js/test/connection.test.ts
- web3.js/test/stake-program.test.ts
The stake program live tests rely on getting a new finalized blockhash whenever a duplicate transaction is sent, but it takes awhile for a new validator to start finalizing blocks.
Update stake program test to not use a dup transaction
Fixes #
> chore: fix lagging stake program live test

- client/src/connection_cache.rs
- client/src/quic_client.rs
- client/src/tpu_connection.rs
TLS handshake for resumed session can require 1 round trip, which costs latency. See #25011 
- Enable 0rtt quic connections when possible
- Add metrics for tracking connection & 0rtt success
> Enable 0rtt

- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/default_account_state.rs
- transaction-status/src/parse_token/extension/memo_transfer.rs
- transaction-status/src/parse_token/extension/mint_close_authority.rs
- transaction-status/src/parse_token/extension/mod.rs
- transaction-status/src/parse_token/extension/reallocate.rs
- transaction-status/src/parse_token/extension/transfer_fee.rs
RPC now recognizes the spl_token_2022 program id, but cannot parse all its instructions.
Add parsing for various extension instructions: DefaultAccountState, MemoTransfer, MintCloseAuthority, Reallocate, TransferFee
Also parse CreateNativeMint instructions
I'm still kicking the ConfidentialTransfers-can down the road, but this should be everything else.
> Parse most token-2022 instructions

- ledger/src/blockstore_processor.rs
- runtime/src/bank.rs
- runtime/src/transaction_batch.rs
The rebatched transactions could potentially unlock accounts multiple times, if the code is updated to use multiple threads.
Reference: https://github.com/solana-labs/solana/pull/22917#discussion_r867903417
Set needs_unlock to false for the newly created batches.
Fixes #
> Unset needs_unlock for rebatched transactions batches

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
- validator/src/main.rs
LedgerColumnOptions contain two fields, perf_read_counter and perf_write_counter,
that are not really options but internal counters.
This PR introduces BlockstoreRocksDbPerfSamplingStatus, a struct that holds internal
status for RocksDB perf sampling and moves perf_read_counter and perf_write_counter
out from LedgerColumnOptions.
> (LedgerStore) Move metric sample counters out from LedgerColumnOptions

- core/src/poh_timing_report_service.rs
- core/src/validator.rs
PohTimingReportService takes exit as Arc. The caller have to clone the Arc and move it to the service. Instead, the service can take a reference and clone inside itself. Passing a reference is cheaper and it will save a move of Arc.
Make PohTimingReportService take ref of Arc.
Fixes #
> pass exit by ref

- account-decoder/src/parse_bpf_loader.rs
- cli/src/program.rs
- cli/tests/program.rs
- program-test/tests/builtins.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/loader_utils.rs
- sdk/program/src/bpf_loader_upgradeable.rs
The functions for returning the length of various upgradeable loader states are expensive and fallible.
Add new `const fn` methods to make size checks inexpensive and infallible
Fixes #
> Add size_of const fns for upgradeable loader states

- stake-accounts/src/main.rs
Running `solana-stake-accounts` will error if a config file is not already present.
If there's no config file, just use the defaults.
Fixes #20414
> Use default if there is no config file

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/yarn.lock
The `sinon-chai` package is listed in the `dependencies` resulting in a warning when using installing with yarn. 
```
$ yarn
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@solana/web3.js > sinon-chai@3.7.0" has unmet peer dependency "chai@^4.0.0".
warning "@solana/web3.js > sinon-chai@3.7.0" has unmet peer dependency "sinon@>=4.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 12.79s.
```
- move sinon-chai to devDependencies
> chore(web3.js): move sinon-chai to devDependencies

- web3.js/src/transaction.ts
- web3.js/test/transaction.test.ts
After deserializing a transaction, it's not possible to sign and send because sending the transaction could mutate the transaction's blockhash and cause a mutation error.
Allow mutating the recent blockhash of a deserialized transaction
Fixes https://github.com/solana-labs/solana/issues/25137
> fix: allow mutating transactions

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
when the try/catch exception identifier is excluded, during the build phase, `rollup` is throwing the error
`SyntaxError: Unexpected token in node_modules/@solana/web3.js/lib/index.browser.esm.js`
change
`try {} catch {}`
to
`try {} catch(_err) {}`
> include exception identifier in `catch` blocks

- Cargo.lock
- cli/src/checks.rs
- cli/src/cli.rs
- client/src/blockhash_query.rs
- client/src/mock_sender.rs
- client/src/nonblocking/rpc_client.rs
- client/src/pubsub_client.rs
- client/src/rpc_client.rs
- client/src/rpc_response.rs
- programs/bpf/Cargo.lock
- rpc/src/rpc.rs
- rpc/src/rpc_subscriptions.rs
- version/Cargo.toml
- version/src/lib.rs
When new API params are supported, it's not possible for clients to know if the new params are being ignored or not unless they first check the version of the RPC node they are connected to. Since RPC nodes are often used in pools, it's therefore quite difficult from the client to know what api version handled its request.
- Add the API version (solana software version) to the RPC response context
- Since subscriptions are long lived, it's not necessary to return the api version in each response so I've created new types for notification context responses.
```sh
curl 'http://localhost:8899' -X POST  -H 'content-type: application/json' --data-raw '{"method":"getAccountInfo","jsonrpc":"2.0","params":["DpVdRMmuvYZj3n4nCTJ7hufYi4odz2uNEsnfbH9vQ2sX"], "id":""}' | jq . …
```
> RPC: Add API version to context response

- core/src/banking_stage.rs
`test_banking_stage_entryfication` is flaky and goes into infinite loops sometimes.
The test sends two transactions and expects them to be part of two different entries. It was using `sleep` to induce delay in the posting of the transaction, so that the banking stage receive loop will process the two transaction in two separate iterations. But that's not very deterministic and causes the test to fail (and go in a loop).
This PR updates the test to ensure that the first transaction is recorded before the second is sent.
Fixes #
> Update test_banking_stage_entryfication to be more deterministic

- core/src/accounts_hash_verifier.rs
- runtime/src/accounts_db.rs
Squashing slots into ancient append vecs messes up rewrite skipping rehash code for ongoing hash calculations. The idea here is that when a hash calculation is done, it can note the slot it ran at so that squashing can occur on any slot older than an epoch from that slot.
Fixes #
> keep track of oldest slot used by last hash calculation

- cli/src/cli.rs
- cli/src/cluster_query.rs
- docs/src/developing/programming-model/runtime.md
- program-runtime/src/compute_budget.rs
- programs/bpf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- sdk/src/compute_budget.rs
- sdk/src/feature_set.rs
- sdk/src/transaction/error.rs
- storage-proto/proto/transaction_by_addr.proto
- storage-proto/src/convert.rs
Compute instruction's additional fee type is too small for the current use cases
Add support for u64 additional lamports fee and continue to support the older u32 fee
Fixes #
Feature Gate Issue: #25050
> support 64-bit prioritization fee

- Cargo.lock
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
- runtime/src/shared_buffer_reader.rs
- runtime/src/snapshot_utils.rs
https://github.com/solana-labs/solana/issues/24798
Use memory map to speed up snapshot untar.
1. use mmap to read snapshot archive files.
2. retune the parallel factor and chunksize
with mmap
```
reading entire decompressed file took: 44799890 us, bytes: 76654958592, read_us: 23072928, waiting_for_buffer_us: 21715846, largest fetch: 100000000, error: Ok(0)
```
master
```
reading entire decompressed file took: 44960804 us, bytes: 76654958592, read_us: 29821976, waiting_for_buffer_us: 15128175, largest fetch: 100000000, error: Ok(0)
```
The comparison does show that read_time is reduced from 29s to 23 seconds. But the the total untar time don't differ much. The reason is because, although we are reading the data faster, we spend more time on waiting for available buffer, 21s vs 15s. 
Next, …
> Use memory map to speed up snapshot untar

- sdk/program/src/message/compiled_keys.rs
- sdk/program/src/message/versions/v0/mod.rs
Once the feature for https://github.com/solana-labs/solana/issues/25034 is activated, program ids will no longer be allowed to be loaded from a lookup table. However, the client message building api still extracts program ids using lookup tables.
- Refactor `CompiledKeys` to allow for filtering out invoked keys
- Prevent invoked keys from being extracted by lookup tables
Fixes #
> Don't extract invoked keys from a message when using a lookup table

- core/src/banking_stage.rs
Banking stage is not able to keep up with receiving packets sent by the sigverify stage. The problem gets worse for QUIC, since each packet batch contains only one packet. This results into a lot of `blockhash_not_found` and `blockhash_too_old` errors.
Banking stage uses different receive timeout value based on whether packets are buffered. This PR updates the receive loop's greedy receive logic to use this timeout to continue to receive more packet batches.
Also, the PR computes the upper bound for receiving packet batches based on how many more can be buffered. This makes it more dynamic, and buffer capacity driven.
Tested the PR by running a dev cluster.
The TPS numbers are better:
Baseline
With this PR 
The `blockhash_not_found` errors have drastically reduced
Baseline
With this PR …
> Tune banking_stage receive loop timing

- ledger-tool/src/bigtable.rs
- ledger/src/bigtable_upload.rs
- ledger/src/bigtable_upload_service.rs
- rpc/src/rpc_service.rs
Currently, the Foundation runs several warehouse nodes on mainnet-beta, which upload blocks to BigTable long-term storage. When the warehouse nodes have long queues of blocks to upload to BigTable, they all end up wasting time attempting to serialize and upload the same set of blocks. This is because the check for whether BigTable already has a block is done only once at the beginning of processing that long queue, here: https://github.com/solana-labs/solana/blob/7de339cb5c14d8d8f498b14fc3a3afd390bfb5fc/ledger/src/bigtable_upload.rs#L69
For instance:
```
[2022-04-26T19:00:13.295284511Z INFO  solana_ledger::bigtable_upload] Loading ledger slots starting at 130129788...
[2022-04-26T19:00:13.477310935Z INFO  solana_ledger::bigtable_upload] Found 5714 slots in the range (130129788, 130135957) …
```
> Add configurable limit to number of blocks to check before Bigtable upload

- explorer/src/pages/TransactionDetailsPage.tsx
Transaction details page doesn't display the error details for failed transactions
Fixes https://github.com/solana-labs/solana/issues/25169
> explorer: Display error details on tx page

- web3.js/src/connection.ts
- web3.js/test/connection-subscriptions.test.ts
In #25133 @awojciak noticed that the subscriptions manager would keep trying to slam a closed socket with requests. I believe this is because we were not properly marking the socket as closed when receiving a `'close'` event.
Toggle the connectedness flag when we get a close/error event.
Fixes #25133.
> fix: mark the socket as closed when receiving a close/error message

- runtime/src/accounts_db.rs
PurgeStats and ReclaimResult were always the same option variant. 
Wrapped them together in a single option.
Fixes #
> Clean-Up: coalesce purge stats and reclaim result

- bench-streamer/src/main.rs
- core/src/ancestor_hashes_service.rs
- core/src/fetch_stage.rs
- core/src/replay_stage.rs
- core/src/serve_repair_service.rs
- core/src/shred_fetch_stage.rs
- core/src/tpu.rs
- gossip/src/gossip_service.rs
- runtime/src/bank_forks.rs
- streamer/src/streamer.rs
If we are in vote-only-mode, incoming TPU packets can still produce load on the validator causing it to take a long time processing other threads.
Start ignoring the TPU port when tip - root > 400 banks.
Fixes #
> Block packets in vote-only mode

- runtime/src/bank.rs
when doing the stressful outage gap block replay recovery on a warehouse node, I encountered a scary bank hash mismatch, which took some time to debug. and, it turned out that I was passing `--hard-fork NN` multiple times... ;)
Print additional info and make the hard fork message stand out:
- ... by showing actually hashed `buf` and pre-/post- bank hash
- ... by promoting it from `info!` to `warn!`
after:
```
[2022-05-14T09:31:13.615540883Z WARN  solana_runtime::bank] hard fork at slot 67 by hashing [1, 0, 0, 0, 0, 0, 0, 0]: 3V5jhy57A1nKj68wd8kbhQgjDg5D61GRemBFM77kM8iL => Dhg58CfgiTHyfEA7nGsETvXvmzazGWkZz7DHxyr7RegV
```
i thnk backport to mb can be justified:
- the change is very tiny and little risk
- it's handy, should another outage happens in near future....
> Improve hard fork message with more detail

- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
- sdk/program/src/fee_calculator.rs
The `FeeRateGovernor` in a bank does not serialize its current `lamports_per_signature` on snapshot. This causes issues if the block that we start a snapshot from is lined up with a fee increase, it is possible for this `lamports_per_signature` to be invalid. 
Serialize and deserialize this field by accessing it from the `FeeRateGovernor`
Fixes #23545
> Serialize lamports per signature in snapshots

- web3.js/src/connection.ts
- web3.js/src/util/send-and-confirm-raw-transaction.ts
- web3.js/test/bpf-loader.test.ts
- web3.js/test/connection.test.ts
- web3.js/test/mocks/rpc-http.ts
- web3.js/test/stake-program.test.ts
- web3.js/test/transaction.test.ts
`sendTransaction` right now only fetches a recent blockhash using the deprecated `getRecentBlockhash()` method. Notably this is missing the `lastValidBlockHeight` property that's needed to use the blockheight-based transaction confirmation strategy.
Teach the ‘recent blockhash’ cache to fetch using `getLatestBlockhash` and thread the `lastValidBlockHeight` down to `confirmTransaction` through its membership on `Transaction`.
Fixes #23949.
> feat: thread new blockheight expiry strategy through `sendAndConfirmTransaction`

- core/src/banking_stage.rs
- perf/src/packet.rs
* Banking stage is not getting to some transactions but not filling the block
* With a larger batch size there can be many conflicting or invalid transactions then they can fill up the banking-stage buffers easily because the limits are per-batch.
* Add 2 more banking threads
* Lower the default batch size to 64
* Increase total buffered packets to 700k
Fixes #
> Lower default batch size to 64 and add 2 banking threads

- cli/src/cli.rs
- cli/src/cluster_query.rs
- core/benches/unprocessed_packet_batches.rs
- core/src/banking_stage.rs
- core/src/unprocessed_packet_batches.rs
- docs/src/developing/programming-model/runtime.md
- program-runtime/src/compute_budget.rs
- program-runtime/src/lib.rs
- program-runtime/src/prioritization_fee.rs
- programs/bpf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- sdk/src/compute_budget.rs
- sdk/src/feature_set.rs
- The `ComputeBudget::SetPrioritizationFee` instruction doesn't let users directly set the relative priority of their transactions and it forces banking stage to do extra arithmetic to determine transaction priority
- Banking stage doesn't calculate transaction priority yet.
- Migrated `ComputeBudget::SetPrioritizationFee` to `ComputeBudget::SetComputeUnitPrice` where compute unit price is measured in "micro-lamports"
- Renamed the `prioritization_fee_type_change` feature to `add_set_compute_unit_price_ix`
- Banking stage now prioritizes transactions based on compute budget instructions (not feature gated)
- Updated prioritization fee calculations for instructions that use the `ComputeBudget::SetComputeUnitPrice` instruction (feature gated)
- Updated docs
Fixes #24615 
(Updated) Feature …
> Prioritize transactions in banking stage by their compute unit price

- docs/src/developing/programming-model/runtime.md
We're prioritizing on the rate now not the fee itself so this doc section is outdated
Remove it
Fixes #
> docs: Remove redundant and incorrect tx priority details

- Cargo.lock
- download-utils/src/lib.rs
- ledger-tool/src/main.rs
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
- runtime/src/snapshot_utils.rs
- runtime/src/snapshot_utils/archive_format.rs
- validator/src/main.rs
https://github.com/solana-labs/solana/issues/24998
lz4 provides a good compromise between compress and decompress speed and compression ratio. Compare with zstd, which is the current default option, lz4 can provide **3-4x** speed up for compression and decompression. The downside is that the archive files will be **1/3** larger.
For machine that have large disk space, lz4 will be a good option to choose from.
Add lz4 support for snapshot archives
Fixes #24998
> Support lz4 for snapshot archives

- client/src/connection_cache.rs
- client/src/quic_client.rs
- client/src/tpu_connection.rs
- client/src/udp_client.rs
- client/tests/quic_client.rs
1. Endpoint creation and connection initiation logic is spread in different places. This change move them together to improve cohesiveness and it achieves real lazy initialization for connections. Other considerations is we want to reduce the sys calls under larger locks such as the connection cache lock.
2. The get_or_add_connection is taking a lock on the cache which is shared across different connections. Under this it is also loading stats for a given connection, which  might not be fully connected yet. This results in that a lengthy connection could impact other working connection being created. 
1. Move logics related to creating endpoint, creating new connection and retry 0rtt connections into a wrapper construct QuicNewConnection to put the logic together.
2. …
> Refactor make_connection

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
After #25042, each LedgerColumn has its own BlockstoreRocksDbWritePerfMetrics
and BlockstoreRocksDbReadPerfMetrics instances.  As it has total ownership,
its member field does not need to use Arc.
Change perf_samples_counter from Arc<AtomicUsize> to AtomicUsize
under BlockstoreRocksDbWritePerfMetrics and BlockstoreRocksDbReadPerfMetrics.
This PR depends on #25042.
> (LedgerStore) Change perf_samples_counter from Arc<AtomicUsize> to AtomicUsize

- metrics/benches/metrics.rs
- metrics/src/metrics.rs
Extra heap allocations from push_str which clippy warns about
Switch to write!
old:
`test bench_write_points         ... bench:      53,335 ns/iter (+/- 958)`
new:
`test bench_write_points         ... bench:      12,321 ns/iter (+/- 343)`
Fixes #
> Use write! to fix clippy and save heap allocation

- core/src/banking_stage.rs
- BankingStage gets starved from new packets if it gets stuck with transactions that exceeds the cost model or repeatedly hit AccountInUse/other errors that mark packets as retry-able that take awhile to get drained from the buffer.
- Issue: https://github.com/solana-labs/solana/issues/24163
- BankingStage should attempt to read in new packets more frequently.
- Remove the looping for process_buffered_packets.
- BankingStage will attempt to go through each threads backlog once before reading new packets.
- If there's packets, set the recv_timeout to 0s so we perform the equivalent of a try_recv
NOTE:
- We are still wasting time trying to pack batches for txs where the cost model is already saturated (serialization, QoS, account locking, etc.) but this seems like a major improvement over …
> Fix BankingStage packet starvation (1.9)

- program-runtime/src/accounts_data_meter.rs
From nightly clippy:
```
warning: casting the result of `i64::abs()` to u64
--> program-runtime/src/accounts_data_meter.rs:178:56
|
178 |         assert_eq!(remaining_after, remaining_before + amount.abs() as u64);
|                                                        ^^^^^^^^^^^^^^^^^^^ help: replace with: `amount.unsigned_abs()`
|
= note: `#[warn(clippy::cast_abs_to_unsigned)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_abs_to_unsigned
```
Use `unsigned_abs()`.
> clippy: Use `unsigned_abs()`

- docs/src/terminology.md
https://docs.solana.com/terminology#signature misspelled "transaction" as "transacton". 
Changed to correct spelling.
Fixes #
> Fixed typo in Docs (in #signature section, "transacton" -> "transaction")

- ci/buildkite-pipeline-in-disk.sh
- ci/buildkite-pipeline.sh
- ci/buildkite-solana-private.sh
Downstream anchor is failing in CI because the bumped dependency on spl-token 3.3.0 is not compatible with the strict version in anchor.
This isn't going to be fixable because of dependencies in the anchor repo.  This build should get moved downstream to SPL to properly override those dependencies.  To start, let's disable it in the monorepo.
> ci: Remove downstream anchor projects

- rpc/src/rpc_subscriptions.rs
Even when `--rpc-pubsub-enable-vote-subscription` is not provided, an expensive `RpcVote` struct is created for every observed vote.  Knock it off.
> Avoid multiple base58 encodes for all votes when no `voteSubscribe` is disabled

- Cargo.lock
- ledger/src/bigtable_upload.rs
- programs/bpf/Cargo.lock
- storage-bigtable/Cargo.toml
- storage-bigtable/src/lib.rs
We were seeing our bigtable block upload running behind tip by several thousand blocks. We noticed it was uploading a block every ~500ms.
Added multiple blockstore read threads.
Run the bigtable upload in tokio::spawn context.
Run bigtable tx and tx-by-addr uploads in tokio::spawn context.
We're seeing around 50-60ms per block upload now, so we should be able to easily catch up and maintain bigtable state on the tip.
I think there's more to squeeze out, but curious what you guys think about this before I go down the next optimization rabbit hole.
> Speedup bigtable block upload by factor of 8-10x

- cli-output/src/cli_output.rs
- cli-output/src/cli_version.rs
- cli-output/src/lib.rs
- cli/src/cluster_query.rs
- cli/src/feature.rs
The `solana validators` command doesn't sort the breakdown of validators by version correctly because it sorts using strings instead of semver structs.
```
Stake By Version:
1.10.11  -    1 current validators ( 0.01%)
1.10.12  -    5 current validators ( 1.52%)
1.10.13  -    1 current validators ( 0.01%)
1.10.14  -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
1.10.3   -    1 current validators ( 0.02%)
1.10.8   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
1.9.16   -    1 current validators ( 0.06%)
1.9.17   -    1 current validators ( 0.02%)
1.9.18   -  151 current validators (29.63%),   3 delinquent validators ( 0.00%)
1.9.19   -    3 current validators ( 2.60%),   1 delinquent validators ( 0.00%)
1.9.20   -  116 current validators …
```
> cli: Fix sort order of staked validators by version breakdown

- client-test/tests/client.rs
- client/src/nonblocking/rpc_client.rs
- client/src/rpc_client.rs
- client/src/rpc_config.rs
- client/src/rpc_custom_error.rs
- docs/src/developing/clients/jsonrpc-api.md
- rpc-test/tests/rpc.rs
- rpc/src/rpc.rs
- rpc/src/rpc_pubsub.rs
- rpc/src/rpc_service.rs
- rpc/src/rpc_subscriptions.rs
When making requests to an RPC tool, it can be challenging to get consistent responses because requests could be handled by nodes which are lagging behind the node for a previously handled request.
Added a `minContextSlot` parameter to many RPC API's in order to fail fast and notify the client that the connected RPC client isn't caught up to the slot that was expected. Clients can tell if this parameter was respected by the RPC node by checking the `apiVersion` response in the context of the response is >= `1.11.0`
This PR only adds this feature to the RPC server, it doesn't implement the client changes to make use of this new parameter. That can come later in a separate PR
Fixes https://github.com/solana-labs/solana/issues/15705
> RPC: Add minContextSlot param to ensure consistent responses

- runtime/src/shared_buffer_reader.rs
- runtime/src/snapshot_utils.rs
It turns out that memory map helps most for "uncompressed" snapshot. For compressed snapshot, memory map doesn't make any noticeable improvement. Further investigation is needed.  
Revert the mmap change for reading snapshot. 
Fixes #
> Revert using memory map for reading snapshot

- client/src/nonblocking/rpc_client.rs
- client/src/rpc_client.rs
There is not a way for rpc client to get the stake minimum delegation.
Add `get_stake_minimum_delegation()` to rpc_client.
Fixes #24690
> Add get_stake_minimum_delegation() to rpc_client

- client/src/rpc_client.rs
I broke the build:
```
error[E0063]: missing field `api_version` in initializer of `rpc_response::RpcResponseContext`
--> client/src/rpc_client.rs:4338:34
|
4338 |                         context: RpcResponseContext { slot: 1 },
|                                  ^^^^^^^^^^^^^^^^^^ missing `api_version`
```
https://buildkite.com/solana-labs/solana/builds/73654#85d3587f-4854-49f1-b3a7-b332bc50680e
PR the introduced the break: #25200 
Add `api_version`.
> Fix RpcResponseContext in rpc_client test

- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_token.rs
- rpc/src/rpc.rs
- runtime/src/inline_spl_token_2022.rs
While running tests for https://github.com/solana-labs/solana-program-library/pull/3071 against master, there were still issues recognizing token-2022 accounts for some of the token-specific RPC endpoints.
Support token-2022 in a few more places in RPC.  Most of the changes are tests.
A few changes that you might disagree with, so I want to flag them:
* the filter resolution logic for token-2022 is a bit tricky, since a token account can *either* have length 165 or `data[165] == 2`. if someone specifies one of those, should we assume that they actually want all token accounts or truly respect what they say?
* added `program_id` to the UiTokenAccount types, which is helpful in the CLI when figuring out dynamically which program id the account belongs to
* added …
> rpc: Support token-2022 in token-specific calls

- ledger-tool/src/main.rs
value_t_or_exit()! will error if the user doesn't specify a value at
runtime, use value_of() instead which will give either the default value
or whatever the user specified.
Fixes #
> Fix ledger-tool from erroring with unspecified archive_format

- Cargo.lock
- ledger/Cargo.toml
- ledger/src/shred.rs
- programs/bpf/Cargo.lock
* Not immediately clear what the constant are equal to.
* Might silently change the constants as the code is updated.
* added `const_assert_eq`
> adds const_assert_eq for shred constants

- web3.js/src/connection.ts
- web3.js/src/util/send-and-confirm-raw-transaction.ts
I think there is a typo in `BlockheightBasedTransactionConfimationStrategy`
Rename `BlockheightBasedTransactionConfimationStrategy` to `BlockheightBasedTransactionConfirmationStrategy`
> fix typo: BlockheightBasedTransactionConfimationStrategy, Confimation => Confirmation

- validator/src/admin_rpc_service.rs
Reduce the number of threads used by the admin rpc service to a reasonable amount. If it turns out this new default is too small for some fringe use cases, a new `solana-validator` argument can be added to make the thread count configurable.
> Reduce admin rpc service thread count from the number of available cores to 3

- docs/src/developing/programming-model/runtime.md
- program-runtime/src/compute_budget.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/prioritization_fee.rs
- program-test/src/lib.rs
- programs/bpf/tests/programs.rs
- runtime/src/bank.rs
- runtime/src/cost_model.rs
- runtime/src/execute_cost_table.rs
- sdk/src/compute_budget.rs
- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
- Compute units are often just referred to as "units" which is too vague (the `RequestUnits` ix for example)
- `ComputeBudget::max_units` is confusingly named because it's only the max units for a particular tx, not the whole runtime
- Use consistent naming when talking about compute units and the compute unit limit for a tx
Fixes #
> Use consistent naming for compute unit limit

- core/src/unprocessed_packet_batches.rs
The transaction prioritization added in https://github.com/solana-labs/solana/pull/25178 unintentionally caused banking stage to drop all incoming transactions which use request heap instructions.
- Accept transactions which use request heap instructions in banking stage
Fixes #
> Don't drop transactions which use a request heap size ix

- validator/src/bootstrap.rs
Validator with --incremental-snapshots can't start to download snapshot if no one --known-validator set (not depended from --only-known-rpc)
Do not match snapshot hashes with snapshot hashes of known validators if no one is set.
Fixes #23927
> Fix bootstrap without known validators

- web3.js/src/transaction.ts
This `_verifySignatures()` step runs verification, returns the result of that verification to nobody, and does nothing. We're essentially paying the cost of `Message#serialize` and `Transaction#_verifySignatures` and then throwing out the result.
* We've gone 2 years without this code throwing if the result is `false` or otherwise making use of the result. Let's just get rid of it?
Fixes #24822.
> fix: speed up transaction signing by removing code that does nothing

- core/src/banking_stage.rs
- BankingStage gets starved from new packets if it gets stuck with transactions that exceeds the cost model or repeatedly hit AccountInUse/other errors that mark packets as retry-able that take awhile to get drained from the buffer.
- Issue: https://github.com/solana-labs/solana/issues/24163
- BankingStage should attempt to read in new packets more frequently.
- Remove the looping for process_buffered_packets.
- BankingStage will attempt to go through each threads backlog once before reading new packets.
- If there's packets, set the recv_timeout to 0s so we perform the equivalent of a try_recv
NOTE:
- We are still wasting time trying to pack batches for txs where the cost model is already saturated (serialization, QoS, account locking, etc.) but this seems like a major improvement over …
> Fix banking stage starvation

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/Cargo.toml
[solana_rbpf v0.2.29](https://github.com/solana-labs/rbpf/releases/tag/v0.2.29) was released.
- Syscall parameter `memory_mapping` becomes mutable: &**mut** MemoryMapping
- `MemoryMapping::resize_region()` becomes `MemoryMapping::replace_region()`
> Bumps solana_rbpf to v0.2.29

- streamer/tests/recvmmsg.rs
recv_mmsg test has an assumption of 0 packet drops.
Change to allow for 1% batches were drops could occur.
Fixes #
> Give some tolerance to recv_mmsg test

- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
Updating the bank's `accounts_data_len` after `execute`, but before `commit`, may result in incorrect values.
Move where `Bank::update_accounts_data_len()` is called; from `execute` to `commit`.
> Move updating accounts data len from execute to commit

- ledger-tool/src/main.rs
new CLI argument --snapshot-archive-format conflicted with --no-snapshot. Since --snapshot-archive-format had a default value, this effectively disables --no-snapshot.
They shouldn't conflict as --snapshot-archive-format only changes the format we save a snapshot in, while no-snapshot controls if we load from a snapshot.
Remove the conflict.
Fixes #
> Bugfix: snapshot-archive-format should not conflict with no-snapshot

- multinode-demo/delegate-stake.sh
Multinode-demo fails with default stake amount because it is too low. See linked issue for more context.
Increase default stake amount.
Fixes #25336
> multinode-demo: Increase default stake amount to 10 SOL

- client/src/connection_cache.rs
- client/src/quic_client.rs
- client/src/tpu_connection.rs
- client/src/udp_client.rs
- client/tests/quic_client.rs
We take the connection lock in the QuicClient while holding the connection cache lock in get_connection. This adds to lock contention for both locks.
Move updating the connection cache stats into the QuicClient itself, where we can do it without holding either lock.
Fixes #
> Implement updating the connection cache stats in the client

- ledger-tool/src/main.rs
- ledger-tool/tests/basic.rs
When there are a lot of program ids it's nice to see which is the most common and also to print a summary at the end of the whole range from what is the most common.
Add those to ledger-tool print command.
Fixes #
> ledger-tool: Sort per-program and print a summary of all slots in the range

- program-runtime/src/invoke_context.rs
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf/benches/bpf_loader.rs
- programs/bpf/build.rs
- programs/bpf/rust/inner_instruction_alignment_check/Cargo.toml
- programs/bpf/rust/inner_instruction_alignment_check/src/lib.rs
- programs/bpf/rust/invoke_and_return/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/src/main.rs
Recent syscall context considation wasn't handling the changes between instructions correctly.  In particular, alignment checking that depends on the loader being used was being set and stayed at the last program loaded rather than returning to the caller's setting.
This caused a bank hash mismatch on master due to some txs failing.
Track the syscall context per-instruction
Fixes #
> Fix alignment check

- web3.js/src/compute-budget.ts
- web3.js/test/compute-budget.test.ts
The compute budget interface will be updated before being activated on mainnet and the web3 api needs to be updated to match. For more details see: https://github.com/solana-labs/solana/pull/25178
- Added support for the new `SetComputeUnitLimit` and `SetComputeUnitPrice` prioritization fee ixs
Fixes #
> feat: support additional compute budget ixs

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/rollup.config.js
- web3.js/src/compute-budget.ts
- web3.js/src/system-program.ts
- web3.js/src/util/bigint.ts
There's a circular dependency from `@solana/web3.js` -> `@solana/buffer-layout-utils` -> `@solana/web3.js`. Also, apps are seeing compile errors due to `@solana/buffer-layout-utils` using an esm style import to import from `@solana/web3.js` when they their `@solana/web3.js` dependency is not an esm module (https://github.com/solana-labs/buffer-layout-utils/issues/6)
- Copy bigint implementation from `@solana/buffer-layout-utils`
- Remove `@solana/buffer-layout-utils` dependency
Fixes #
> fix: remove @solana/buffer-layout-utils to fix circular dependency build issues

- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
avoid creating a vector just to iterate
create an iterator over contents of an append vec
a follow on pr will replace 2 more sites with this.
This particular caller is already in code that is very expensive at high account counts.
Fixes #
> use iterator instead of vec to iterate accounts

- runtime/src/accounts_db.rs
- runtime/src/serde_snapshot.rs
filler accounts create dummy accounts to simulate high account # systems.
a feature that is hardening is skipping rent rewrites.
because filler accounts were created with rent_epoch=0, we ALWAYS did a rewrite on filler accounts. This means filler accounts are not acting like normal infreqently-updated accounts.
Create filler accounts with a useful rent epoch so that the skip_rewrite code actually skips rewrites on them.
Fixes #
> filler accounts get a non-zero rent_epoch

- ledger-tool/src/main.rs
create-snapshot will load bank_forks from a snapshot and try to replay up to snapshot_slot. If snapshot_slot does not exist, it will replay everything available and then fail. This can be slow.
Add a check to see if `snapshot_slot` is available in the blockstore BEFORE trying to load the bank_forks. If it's not we exit since we won't be able to create a snapshot.
Preliminary PR for minimized snapshot mode.
Fixes #
> Create-snapshot check if slot is available on startup

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
`--accounts-db-ancient-append-vecs`, validator and ledger-tool will squash ancient append vecs.
`--accounts-db-skip-rewrites`, rewrites will be skipped. (this is already in master)
These 2 can be combined.
All this code is behind `--accounts-db-ancient-append-vecs`
Fixes #
> impl squash to ancient append vecs

- ledger-tool/src/main.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
When using ledger-tool to track down a bug, it costs something to verify the accounts hash of the snapshot each load. Eliminating this unnecessary calculation improves the debugging cycle time.
passing `--accounts-db-skip-initial-hash-calc` allows ledger-tool verify to complete faster.
Fixes #
> add ledger-tool accounts-db-skip-initial-hash-calc

- runtime/src/accounts.rs
- runtime/src/bank.rs
This code path is not called at runtime, so we can run hash calc without a thread pool. This runs faster.
Fixes #
> allow hash calc to use all threads at startup

- docs/src/developing/programming-model/calling-between-programs.md
Because of the way the seeds are hashed there is a potential for
program address collisions for the same program id.  The seeds are hashed
sequentially which means that seeds {"abcdef"}, {"abc", "def"}, and {"ab",
"cd", "ef"} will all result in the same program address given the same program
id. Since the chance of collision is local to a given program id, the developer
of that program must take care to choose seeds that do not collide with each
other. For seed schemes that are susceptible to this type of hash collision, a
common remedy is to insert separators between seeds, e.g. transforming {"abc",
"def"} into {"abc", "-", "def"}.
Add the above to the PDA docs
Fixes #
> Add warning to program derived address docs

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
When the number of RocksDB read/write operations spikes, its payload size
might exceed the limit (413 Payload Too Large).
This PR rate-limit the perf-sampling of RocksDB read/write operations by one second
in addition to the existing sampling that is configurable via the hidden validator
argument --rocksdb-perf-sample-interval.
This PR depends on #25042 and #25043.
> (LedgerStore) Rate-limit RocksDB perf sample by a minimum time interval

- core/src/find_packet_sender_stake_stage.rs
- core/src/staked_nodes_updater_service.rs
- core/src/tpu.rs
Find packet sender stake stages are currently generating their own IP address --> stake map every 5 seconds even though we have a dedicated service generating this map already. Impact is 10s of ms latency impact in these stages every 5 seconds.
Have find packet sender stake stage use the shared IP address --> stake map that is generated by the staked nodes updater service
> Use Shared IP to Stake Map

- cli/src/program.rs
- programs/bpf/benches/bpf_loader.rs
- programs/bpf/c/src/alloc/alloc.c
- programs/bpf/rust/128bit/src/lib.rs
- programs/bpf/rust/alloc/src/lib.rs
- programs/bpf/rust/call_depth/src/lib.rs
- programs/bpf/rust/inner_instruction_alignment_check/src/lib.rs
- programs/bpf/rust/iter/src/lib.rs
- programs/bpf/rust/many_args/src/lib.rs
- programs/bpf/rust/membuiltins/src/lib.rs
- programs/bpf/rust/param_passing/src/lib.rs
- programs/bpf/rust/secp256k1_recover/src/lib.rs
- programs/bpf/rust/sha/src/lib.rs
- programs/bpf/rust/zk_token_elgamal/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- sdk/bpf/c/inc/sol/string.h
Programs are now built with an in-program and customizable heap implementation.  There is no more need for the built-in bump allocator syscall.  To end-of-life that syscall, future deployments depending on it should fail.
- Add C in-program allocator
- Prevent deployments of programs that depend on `_sol_alloc_free`
Fixes #
Feature Gate Issue: #24985
> Disallow deployment of deprecated _sol_alloc_free syscall

- streamer/src/lib.rs
- streamer/src/nonblocking/mod.rs
- streamer/src/nonblocking/recvmmsg.rs
- streamer/src/nonblocking/sendmmsg.rs
In order to support a nonblocking TPU client, we need the ability to asynchronously `sendmmsg` through a UDP client. 
Add a simple generic (ie. non-linux) implementation of `sendmmsg`.  `recvmmsg` was an easy addition for better testing.  This is one required step towards getting an async TPU client in #25383.
All of the tests were lifted from their blocking variants in `streamer/src/sendmmsg.rs` and `streamer/src/recvmmsg.rs`. They could potentially be refactored so helper functions call out elsewhere, but that seemed less readable in the end, since at least the tests are self-contained.
> streamer: Add nonblocking versions of sendmmsg / recvmmsg

- ledger/src/blockstore.rs
- ledger/src/blockstore/blockstore_purge.rs
- ledger/src/blockstore_db.rs
- ledger/src/blockstore_meta.rs
- ledger/src/blockstore_metrics.rs
Latest `optimistic_slot` value is needed when coordinating a restart.  This value can be lost if logging is disabled or logs are deleted.
blockstore column family changes to support storing optimistic slot information.
See #25311 for follow-on changes.
For release notes:
This change introduces a new rocksdb column family: `optimistic_slots`. If the validator software is subsequently downgraded the validator will fail to start with the following error:
'Failed to open ledger database: RocksDb(Error { message: \"Invalid argument: Column families not opened: optimistic_slots\" })'
This can be remedied by dropping the `optimistic_slots` column family. Use the `ldb` tool provided with the rocksdb distribution.
Confirm that the database contains the `optimistic_slots` column family:
`ldb …
> framework to preserve optimistic_slot in blockstore

- core/src/sigverify_stage.rs
- perf/benches/dedup.rs
- perf/src/sigverify.rs
Number of unique packets accounting in sig verify stage can be off if incoming packets were already marked for discard before dedup. This can result in packets being dropped unnecessarily to get under the 10k batch limit.
`dedup_packet` function returns 1 when encountering packets marked for discard. `verifier` function treats this return value as the summation of discarded+dedup'ed packets.
> Fix packet accounting after dedup

- core/src/validator.rs
- rpc/src/rpc_service.rs
In `JsonRpcService::new`: if `start_http` fails `close_handle_sender` will be dropped without sending a value to the channel. Subsequent `close_handle_receiver.recv().unwrap()` will fail on the closed channel.
Send error value over the channel to gracefully handle the failure.
Fixes #
> handle start_http failure in rpc_service

- ledger-tool/src/main.rs
Transaction status is only recorded if --enable-rpc-transaction-history
is enabled. We can still print transaction details even if we don't have
this status.
> Fix ledger-tool slot to output tx even when tx status is missing

- core/src/banking_stage.rs
The transaction forwarding is sometimes taking more than 300 msec. This causes banking stage thread to be blocked for that long, and prevents it from processing incoming transactions.
Use `send_wire_transaction_batch_async` to send the forwarded transactions.
Fixes #
> Use async send for forwarding transactions

- runtime/src/hardened_unpack.rs
Clippy warns on `is_digit(10)`:
```
warning: use of `char::is_digit` with literal radix of 10
--> runtime/src/hardened_unpack.rs:359:13
|
359 |         if !x.is_digit(10) {
|             ^^^^^^^^^^^^^^ help: try: `x.is_ascii_digit()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#is_digit_ascii_radix
```
Use `is_ascii_digit()` instead.
> clippy: is_digit(10) -> is_ascii_digit()

- sdk/program/src/message/versions/v0/mod.rs
The `test_try_compile` test asserts the order of compiled keys but there are two readonly non-signer non-table-lookup keys used in the test which can sometimes be included in reverse order because compiled keys are sorted by pubkey value 
Update the test to only use one readonly non-signer non-table-lookup key (the program id)
Fixes #
> Fix flakey v0::Message::test_try_compile test

- program-runtime/src/invoke_context.rs
- program-test/src/lib.rs
- programs/address-lookup-table/src/processor.rs
- programs/bpf_loader/src/lib.rs
- programs/config/src/config_processor.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
Instead of `PreAccount` catching misbehavior after the instruction finishes,
we want to call it out immediately, when it happens.
This is a preparation to throw errors on faulty access.
Introduces `Result` return types to the following methods of `BorrowedAccount`:
- `get_data_mut()`
- `set_data()`
- `set_data_length()`
- `set_owner()`
- `set_lamports()`
- `set_executable()`
And always return `Ok()` for now, the actual feature gated check comes later.
> Introduces `Result` return types to mutable accessors of `BorrowedAccount`

- streamer/src/streamer.rs
Packets received over the test's udp socket are sometimes split across multiple batches and cause the test to fail
Loosen the test assertion to check that at least one packet batch was received
Fixes #
> Fix flakey `streamer_send_test`

- client/src/spinner.rs
- client/src/tpu_client.rs
An async TPU client could involve a lot of copied code from the current TPU client, which would be tougher to maintain in the long term.
No behavior changes, mainly moving some bits around refactoring the internal tpu client types to be reusable.
The biggest change here is to split up the loop of the `LeaderTpuService` to fetch everything needed to update in one place, and then update in another.  This way, the async version only needs to reimplement a subset of the functionality.
> tpu-client: Refactor to prep for async client

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
The current RocksDB read/write perf metrics do not include the total operation nanos
and thus we have to include all fields that might contribute to the total operation nanos.
This PR includes the total operation nanos in RocksDB's read/write perf and reduces the
number of reported fields in its perf metric.
This PR depends on #25093.
> (LedgerStore) Report total nanos and downsize the perf metric for RocksDB read/write

- core/benches/banking_stage.rs
- ledger/src/bigtable_upload.rs
- perf/benches/sigverify.rs
- programs/bpf_loader/src/serialization.rs
- runtime/src/stake_account.rs
- send-transaction-service/src/send_transaction_service.rs
Clippy warns for let-bindings with unit values:
```
warning: this let-binding has unit value
--> core/benches/banking_stage.rs:88:13
|
88  | /             let _ignored = BankingStage::consume_buffered_packets(
89  | |                 &my_pubkey,
90  | |                 std::u128::MAX,
91  | |                 &poh_recorder,
...   |
100 | |                 10,
101 | |             );
| |______________^
|
= note: `#[warn(clippy::let_unit_value)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
help: omit the `let` binding
|
88  ~             BankingStage::consume_buffered_packets(
89  +                 &my_pubkey,
90  +                 std::u128::MAX,
91  +                 &poh_recorder,
92  +                 &mut …
```
> clippy: fix "this let-binding has unit value" warnings

- docs/src/running-validator/vote-accounts.md
Updating docs to include usage of --no-wait-for-vote-to-start-leader flag for validator identity rotation to ensure the secondary validator with the original identity produces blocks.
> Update docs for validator identity change to include --no-wait-for-vote-to-start-leader

- programs/bpf_loader/src/serialization.rs
Partially reverts solana-labs/solana#25429
Apparently CI runs for https://github.com/solana-labs/solana/pull/25429 and https://github.com/solana-labs/solana/pull/25380 have interleaved each other resulting in a broken master.
> Partially reverts "clippy: fix "this let-binding has unit value" warnings"

- core/src/sigverify_stage.rs
- perf/Cargo.toml
- perf/benches/discard.rs
- perf/src/discard.rs
- perf/src/lib.rs
Too many packets going into sigverify
Simple discard before discard/dedup
Fixes #
> sigverify: add discard before dedup

- ledger/src/blockstore_processor.rs
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
misleading logs like this:
2022-05-20T22:19:28.986101850Z WARN  solana_runtime::accounts_db] mismatched bank hash for slot 134161861: DH4fAzS97cTfJRZC6QUf93pVQzuEyLiL55AQNwDZgnxu (calculated) != 11111111111111111111111111111111 (expected)
[2022-05-20T22:19:28.986138916Z INFO  solana_metrics::metrics] datapoint: accounts_db_active hash=0i
[2022-05-20T22:19:28.986196582Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedBankHash
These came about because of the addition of code that ledger-tool runs when we halt-at-slot to calculate an accounts hash at that slot. That is incredibly useful when using ledger tool verify to track down hash mismatches. However, it had some unfortunate misleading side effects.
suppress the mismatch warnings
Fixes #24838
> stop logging misleading bank hash mismatch

- bench-streamer/src/main.rs
- core/src/ancestor_hashes_service.rs
- core/src/find_packet_sender_stake_stage.rs
- core/src/repair_response.rs
- core/src/serve_repair.rs
- core/src/window_service.rs
- gossip/src/cluster_info.rs
- perf/src/packet.rs
- sdk/src/packet.rs
- streamer/src/nonblocking/recvmmsg.rs
- streamer/src/packet.rs
- streamer/src/quic.rs
- streamer/src/recvmmsg.rs
- streamer/src/streamer.rs
* Packet `Meta.addr` field is an `IpAddr`.
* Packet `Meta::addr()` refers to a `SocketAddr`.
* Renamed `Packet Meta::{,set_}addr` methods to `{,set_}socket_addr`
> renames Packet Meta::{,set_}addr methods to {,set_}socket_addr

- ledger-tool/src/main.rs
It looks like there is a typo `matches` (arguments do not exist for Command but indeed for SubCommand).
Renamed to `arg_matches`
> fix problem with matches in ledger-tool

- bench-tps/src/bench.rs
We're seeing many invalid blockhash errors with bench-tps with quic
Adds some datapoints to help debug this
Fixes #
> Add datapoints to help debug the invalid blockhash issue with quic

- core/src/find_packet_sender_stake_stage.rs
The FindPacketSenderStake stage does no load-shedding.
Randomly discard batches if too many have arrived since the last iteration. This mimics #25388 which did the same for sigverify.
@sakridge @jstarry
> findpacketsenderstake: add discard after receive

- banking-bench/src/main.rs
- core/benches/banking_stage.rs
- core/benches/sigverify_stage.rs
- core/src/banking_stage.rs
- core/src/cluster_info_vote_listener.rs
- core/src/sigverify.rs
- core/src/sigverify_shreds.rs
- core/src/sigverify_stage.rs
- core/src/tpu.rs
- core/src/tvu.rs
- perf/benches/dedup.rs
- perf/benches/shrink.rs
- perf/src/sigverify.rs
- sdk/src/packet.rs
Tracer transactions and the associated logic is only necessary in the transaction sigverify pipeline, but not in the shred sigverify pipeline.
1. Introduce a `TransactionTracerPacketStats` tracking the tracer transactions detected in Sigverify. This struct is created in Sigverify and passed to BankingStage to be logged by the leader
2. Refactor `SigVerifier` trait to encapsulate the `Sender` and stub out a trait method `process_received_packet `https://github.com/carllin/solana/blob/a5d8399e03399e181e29b185f399fe043b6aae0e/core/src/sigverify.rs#L58-L62 for detecting tracer transactions before dedup in the transaction Sigverify pipeline
Fixes #
> Refactor Sigverify trait to prepare for tracer metrics

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/serialization.rs
- programs/vote/benches/process_vote.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- sdk/src/transaction_context.rs
`visit_each_account_once()` is used to calculate the duplicate accounts multiple times per instruction,
but once would be enough if we simply stored the result.
Adds `InstructionAccount::index_in_callee` and `InstructionContext::is_duplicate()`.
Both `visit_each_account_once()` and `is_duplicate()` in serialize.rs just check if their calculation matches for now (they will be replaced in the next PR).
Also documents `InstructionAccount` and adjusts affected tests and benches.
> Refactor: Adds `index_in_callee` to `InstructionAccount`

- tokens/src/db.rs
When running solana-tokens, the last line of stderr gets lost, probably due to incomplete flush.
Force flush by printing a new line after errors
> solana-tokens: add extra error line

- cli/src/cluster_query.rs
Many epochs, `solana epoch-info` only includes an estimate of time elapsed based on current slot durations, eg:
```
Epoch Completed Time: 1day 7h 7m 23s*/3days 13h 55m 11s (2days 6h 47m 48s remaining)
* estimated based on current slot durations
```
This is because the epoch start slot was skipped and we don't try any other slots.
Iterate `get_block_time` until we find the first not-skipped block (or until we try 16 slots), and use its block time plus the current average slot duration since the first slot in the epoch to make a better estimate of epoch time-elapsed.
> Find epoch start slot for estimated time elapsed

- runtime/src/bank.rs
- runtime/src/bank_forks.rs
`Bank::accounts_data_len` does not provide a way to tell how the initial vs the delta of the accounts data size. Nor can it tell what changes were due to on-chain events like transactions, vs off-chain events like rent collection.
Split up accounts_data_len into an "initial" and "delta" components.
> Split up accounts data size field

- ledger-tool/src/main.rs
ProcessOptions has a debug_keys field but ledger-tool has no way to use it. It's useful for debugging.
Add a --debug-key option to ledger-tool
Fixes #
> Add a --debug-key option to ledger-tool verify

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/vote/benches/process_vote.rs
- runtime/src/message_processor.rs
- sdk/src/transaction_context.rs
`index_in_caller` is shifted by the length of the executable chain, even though `InstructionAccount` can't access them.
For the sake of simplicity and consistency with `index_in_callee` the index should be shifted down to start at `0`.
Subtracts the offset `InstructionContext::get_number_of_program_accounts()` from `InstructionAccount::index_in_caller`.
> Refactor: Rebase offset of `index_in_caller`

- bench-streamer/src/main.rs
- core/src/banking_stage.rs
- core/src/packet_hasher.rs
- core/src/repair_response.rs
- core/src/serve_repair.rs
- core/src/sigverify_shreds.rs
- core/src/unprocessed_packet_batches.rs
- core/src/window_service.rs
- gossip/tests/gossip.rs
- ledger/src/shred.rs
- ledger/src/sigverify_shreds.rs
- perf/src/sigverify.rs
- sdk/src/packet.rs
- streamer/src/nonblocking/recvmmsg.rs
- streamer/src/nonblocking/sendmmsg.rs
- streamer/src/packet.rs
- streamer/src/quic.rs
- streamer/src/recvmmsg.rs
- streamer/src/sendmmsg.rs
- streamer/src/streamer.rs
Bytes past `Packet.meta.size` are not valid to read from
The commit makes the field private and instead provides two methods:
* `Packet::data()` which returns an immutable reference to the underlying
buffer up to `Packet.meta.size`. The rest of the buffer is not valid to
read from.
* `Packet::buffer_mut()` which returns a mutable reference to the entirety
of the underlying buffer to write into. The caller is responsible to
update `Packet.meta.size` after writing to the buffer.
> limits read access into Packet data to Packet.meta.size

- core/src/cluster_nodes.rs
- ledger/src/shred.rs
- sdk/src/feature_set.rs
Indices for code and data shreds of the same slot overlap; and so they
will have the same random number generator seed when shuffling cluster
nodes for turbine broadcast.
This results in the same propagation path for code and data shreds of
the same index and effectively smaller sample size for re-transmitter
nodes. For example a 32:32 batch (32 code + 32 data shreds), is
retransmitted through _at most_ 32 unique nodes, whereas ideally we want
64 unique re-transmitters.
This commit adds shred-type to seed function so that code and data
sherds of the same (slot, index) will (most likely) have different
propagation paths.
Feature Gate Issue: https://github.com/solana-labs/solana/issues/25558
> includes shred-type when computing turbine broadcast seed

- zk-token-sdk/src/zk_token_elgamal/convert.rs
Implementing standard `From` traits for converting between `ElGamalCiphertext` and `PodRistrettoPoint` types. This will simplifiy the syscall ciphertext arithmetic in applications such as spl.
> zk-token-sdk: Convert traits for elgamal ciphertexts and ristretto points

- program-runtime/src/invoke_context.rs
- runtime/src/builtins.rs
- Refactored `process_executor_chain`
- Enabled builtin program invoke logs by default
Fixes https://github.com/solana-labs/solana/issues/24748
> Add invoke logging to builtin programs that don't have it yet

- entry/src/entry.rs
We're currently looping through the entire vector of txs just to see if it has a non-zero number of non-tick txs. This is suboptimal, since we loop through the vector again right afterwards, and collect references to all the non-tick txs. Even if collecting the refs was more expensive, the only time where we wouldn't do that anyway (early return due to zero non-tick txs) is when there are no non-tick txs, and we simply loop through the possibly empty vector doing nothing. So the earlier loop to count the non-tick txs is unnecessary and slow.
Remove the loop to count the non-tick txs.
Fixes #
> Slightly refactor start_verify_transactions to avoid an unnecessary loop through the vector.

- core/src/find_packet_sender_stake_stage.rs
The work unit sizes were so small that using the thread pool slowed down this stage significantly.
The existing 1.10 mainnet nodes showed around 30us/packet:
But local tests indicate this should take 10-100ns.
Even when limiting to datapoints with at least 500k packets the processing time per packet stayed above 2us:
Drop the thread pool and `par_iter()`s.
I've tested this on testnet: Before, with 1.10.13:
```
find_packet_sender_stake-services_stats
apply_sender_stakes_time=83549i
total_batches=267i 
total_packets=4902i
```
and with a patched 1.10.19:
```
tpu-vote-find-packet-sender-stake
apply_sender_stakes_time_us=971i
total_batches=299i
total_packets=7752i
```
That means it improved from 17us/packet to 125ns/packet.
@sakridge
> FindPacketSenderStake: Remove parallelism to improve performance

- gossip/src/cluster_info.rs
- gossip/src/contact_info.rs
- gossip/src/crds_gossip.rs
- gossip/src/crds_gossip_pull.rs
- gossip/tests/crds_gossip.rs
Context:
https://discord.com/channels/428295358100013066/977244255212937306/977321454716735568
Each time a node generates gossip pull-requests, it sends out all the
requests to a single randomly selected peer:
https://github.com/solana-labs/solana/blob/fd7ad31ee/gossip/src/crds_gossip_pull.rs#L253-L266
This causes a burst of pull-requests at a single node at once. In order
to make gossip in-bound traffic less bursty, this commit fans out gossip
pull-requests to several randomly selected peers.
This should reduce spikes in inbound gossip traffic without changing the
average load which may help reduce number of times outbound data budget is
exhausted when responding to gossip pull-requests at the receiving node, and
reduce number of pull-requests dropped.
The commit fans out gossip …
> fans out gossip pull-requests to many randomly selected peers

- programs/bpf/rust/ro_modify/src/lib.rs
- sdk/program/Cargo.toml
- sdk/program/src/blake3.rs
- sdk/program/src/hash.rs
- sdk/program/src/instruction.rs
- sdk/program/src/keccak.rs
- sdk/program/src/lib.rs
- sdk/program/src/log.rs
- sdk/program/src/program.rs
- sdk/program/src/program_memory.rs
- sdk/program/src/pubkey.rs
- sdk/program/src/secp256k1_recover.rs
- sdk/program/src/syscalls.rs
- sdk/program/src/sysvar/mod.rs
- zk-token-sdk/src/curve25519/curve_syscall_traits.rs
- zk-token-sdk/src/zk_token_elgamal/ops.rs
SBFv2 changes the way syscalls are resolved from using dynamic symbol resolution at runtime, to implementing them statically via a special `CALL_IMM` form. 
I moved all declarations under the `solana_program::syscalls` module. Then using the `define_syscall!` macro, if the underlying target supports static syscalls, the calls are actually defined so they don't result in undefined dynamic symbols anymore. 
With this change the procedure to add a new syscall is to edit the syscalls module and add a `define_syscalls!(<syscall declaration>);` statement.
> Consolidate syscalls under solana_program::syscalls, implement static syscalls (sbfv2)

- core/src/repair_response.rs
- core/src/sigverify_shreds.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shredder.rs
- ledger/src/sigverify_shreds.rs
`sigverify_shreds` relies on wire layout of shreds:
https://github.com/solana-labs/solana/blob/0376ab41a/ledger/src/sigverify_shreds.rs#L39-L46
https://github.com/solana-labs/solana/blob/0376ab41a/ledger/src/sigverify_shreds.rs#L298-L305
In preparation of https://github.com/solana-labs/solana/pull/25237
which adds a new shred variant with different layout and signed message,
this commit removes shred layout specification from sigverify and
instead encapsulate that in shred module.
removed shred wire layout specs from sigverify
> removes shred wire layout specs from sigverify

- perf/benches/reset.rs
- perf/src/sigverify.rs
Looping over 1m AtomicU64 during reset is inefficient. 
Instead, "clear and resize" are more efficient. 
Use "clear and resize" to reset dedup filters.
```
// test bench_reset1 ... bench:     436,240 ns/iter (+/- 176,714)
// test bench_reset2 ... bench:     274,007 ns/iter (+/- 129,552)
```
Fixes #
> Opt: optimize dedup hash filter reset

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
Continuation of #25490.
- Removes `is_duplicate()`. (Fixes #25416)
- Removes `visit_each_account_once()`.
- Adds comments to clarify the order of `pre_accounts` and `instruction_accounts`. (Fixes #25421)
> Refactor: Remove `visit_each_account_once()`

- core/src/tvu.rs
- core/src/validator.rs
- core/tests/ledger_cleanup.rs
- genesis/src/main.rs
- ledger-tool/src/bigtable.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
- ledger/src/blockstore_options.rs
- ledger/src/blockstore_processor.rs
- ledger/src/lib.rs
- local-cluster/tests/common.rs
- test-validator/src/lib.rs
- validator/src/main.rs
blockstore_db.rs has a mutual dependency between blockstore_metrics.rs.
This PR removes the mutual dependency by moving the option-related stuff
out from blockstore_db.rs to its new home --- blockstore_options.rs.
By doing this, we address the mutual dependency and also make the code cleaner.
> (Refactor) Move option structs & enums out from blockstore_db.rs

- metrics/src/datapoint.rs
- metrics/src/metrics.rs
Our existing datapoint macro syntax does directly not support group-by tags.
The existing workaround is to embed the group-by tags into the metric name which does not scale well.
This PR extends the existing syntax to support group-by tags as follows.  The new syntax is also compatible with the existing syntax:
```
datapoint_debug!(
"metric_name",
"tag" => "tag-value",
"tag2" => "tag-value2",
....
("field1", 100, i64),  // field syntax is the same as the current syntax.
("field2", "hello", String),  
...
);
```
> Extend the datapoint macro to support group-by operations.

- runtime/src/accounts.rs
All accounts are loaded before checking the fee payer's lamport balance. 
- As soon as the fee payer is loaded, check the balance and bail out
@jstarry @t-nelson
> Check fee payer before loading all accounts

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
Use the new datapoint macro that supports group-by for RocksDB read/write perf metrics.
This PR depends on #25385 and #25393.
> Use the new datapoint macro that supports group-by for RocksDB read/write metrics.

- runtime/src/message_processor.rs
`ExecuteDetailsTimings` are re-accumulated after each tx instruction meaning that metrics like `create_executor_jit_compile_us` are much higher than they actually are.
- Clear invoke context timings after they are accumulated into higher level timings
cc @t-nelson @carllin
> fix: stop double counting execution timings

- core/src/sigverify_stage.rs
- perf/src/sigverify.rs
If packet batches are very sparse, validators which use GPU's for signature verification will send more memory to the GPU than necessary.
- Run the shrink pass before and after the sigverifier 
- Reduce the discarded packet rate threshold for the packetbatch shrinker from 80% to 10%
- Shrinker now truncates the packet batch list itself instead of requiring the caller to do it
Fixes #
> Add pre shrink pass before sigverify batch

- runtime/src/bank.rs
we have more popular programs than the executor cache has entries, leading to increased evictions and thus excessive JIT recompiles during times of high utility
as a stopgap to something more robust (and complex!), bump the cache size from 100 to 256
> bump executor cache max entries

- runtime/src/bank.rs
slot_height is not actually a height
Rename to slot
Fixes #
> Rename "slot_height" -> "slot" name

- runtime/src/shared_buffer_reader.rs
The test may hang if the total number of threads it wants to start
is greater than the number of threads configured in the rayon
threadpool. 
Check to avoid this situation from happening.
Fixes #
> Fix a possible test hang in runtime::test_shared_buffer_sweep

- web3.js/src/transaction.ts
When compiling messages, we sort accounts. The sort involves producing and comparing pubkey _strings_, which takes time and memory.
* Short circuit pub key comparisons at all when you can determine the sort order based on `isSigner` and `isWriteable` alone.
* Compare pubkeys without producing strings, copying them, or mutating them. The `cmp` method scans the 8-bit words in big-endian order and bails as soon as it finds that one is larger than the other.
Run the tests in `transaction.test.ts`. Sort orders still the same.
> fix: serializing transactions; sort that takes less time and memory

- core/src/sigverify.rs
- perf/src/sigverify.rs
Sigverify doesn't currently mark packets signed by the tracer feepayer before dedup
Add check for tracer key. Offset `TRACER_KEY_OFFSET_IN_TRANSACTION` was found by dissecting the ping transactions from solana ping
Fixes #
> Detect tracer key in sigverify

- runtime/src/hardened_unpack.rs
Unpacking the rocksdb directory from genesis archive can have unintended
consequences, such as clobbering files in pre-existing rocksdb
directory.
Ignore all rocksdb directories when unpacking genesis archive.
Fixes #23666
> Ignore rocksdb directories when unpacking genesis archive

- runtime/src/snapshot_utils.rs
We can create lz4 snapshots but the regex match we're using doesn't see them on load
Add "|tar\.lz4" to full and incremental snapshot regex
Fixes #
> Add lz4 to snapshot filename regex for matching files on load

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
- ledger/src/lib.rs
Use the new datapoint macro that supports group-by for RocksDB column family metrics.
By using the new macro, we can further remove large chunks of boilerplate code that try to work around the previous datapoint macro that does not support group-by.
This PR depends on #25385 and #25392.
> Use the new datapoint macro for RocksDB column family metrics

- runtime/src/accounts_db.rs
Aiming towards efficiency and simplicity wrt scanning billions of accounts in multiple passes.
Having a struct can reduce the code that runs per append vec and more importantly per account.
We can also add filtering later, reducing the work to skip accounts that don't match the current pass.
Fixes #
> add state while scanning

- sdk/program/src/program.rs
I believe that `invoke_unchecked` and `invoke_signed_unchecked` can result in undefined behavior as described in their docs. As with functions in `solana_program::program_memory`, to avoid a breaking API change, at least for now, I have documented them with "__This function is incorrectly missing an `unsafe` declaration.__".
> Add docs to solana_program::program

- runtime/src/bank.rs
- runtime/src/stake_weighted_timestamp.rs
- sdk/src/feature_set.rs
The clock on mainnet-beta has drifted because blocks are slower than the acceptable margin; current 80% of poh-estimate, or 720ms/slot.
Bump timestamp to the current cluster stake-weighted median on activation
Extend bounding on the slow side to permit up to 150% of poh-estimate, or 1s/slot
Closes #25627
Feature Gate Issue: #25668
> Add feature to increase timestamp bounding on the slow side to 1s/slot

- core/Cargo.toml
- core/src/validator.rs
- programs/bpf/Cargo.lock
it's hard to reconcile which `solana-validator` version were running for any given past period of time.
Make influxdb to retain _historical_ version update along with node restarts.
Especially, this is needed for my rainbow tool.
sample:
```
[2022-05-30T03:44:41.833277386Z INFO  solana_metrics::metrics] datapoint: validator-new id="7eVT4kj1gJ7dij8bDEeqmAYcWPP7jyDV7hgBhAN68zVm" version="1.11.0 (src:d2816cb5; feat:2888452000)"
```
Fixes #
> Record solana-validator ver to metrics at startup

- runtime/src/accounts_db.rs
we can return quickly from this function causing noise in the metrics.
So, delay setting the active state until we're actually finding interesting work to do.
Fixes #
> set active state to shrink_ancient when doing interesting work

- runtime/src/accounts_db.rs
Scanning append vecs for accounts hash calc works with multiple passes based on pubkey value ranges. Add ability to filter by pubkey range so that scanning does less work overall since we see pubkeys one time for each pass.
Fixes #
> add filter to AppendVecScan

- runtime/src/accounts_db.rs
- runtime/src/rolling_bit_field.rs
- runtime/src/serde_snapshot.rs
Adding large numbers of filler accounts prior to validator starting takes a long time. This leaves the validator way behind the network and causes it to spend a long time catching up.
Fixes #
> add filler accounts with cache flush

- client/src/nonblocking/mod.rs
- client/src/nonblocking/tpu_client.rs
- rpc-test/tests/nonblocking.rs
An async TPU client will help towards "async"ing other clients and runtime bits.
As part of ongoing work for #25383, start by adding in a "fake" async TPU client.  This looks very similar to the blocking TPU client, except that all of the RPC and network calls are async.
Also, since the PubsubClient works with async notification streams in nonblocking mode, rather than callbacks, the implementation differs slightly.
There's still a lot of copy-pasta between this and the blocking version, but I couldn't come up with a slicker way to do it.  I tried doing the same thing as with the RPC client, ie. exposing the underlying tokio runtime and blocking on async operations, but `send_transactions_with_spinner` would hog the runtime for too long to make sense.  Creating a second runtime seemed …
> tpu-client: Add "fake" async version with sync sending 

- runtime/src/bank.rs
I believe counters are less efficient.
We are already reporting metrics per bank for rent collection. Add total time to the existing metric and remove the counter.
Fixes #
> move rent collection time into datapoint

- runtime/src/accounts_db.rs
Improve perf for common call with low # accounts to update.
See #24692
The largest call I saw on a mnb snapshot and brief ledger replay was 302 accounts being updated at a time.
Fixes #
> remove par_iter on update index below threshold

- core/src/banking_stage.rs
- core/src/unprocessed_packet_batches.rs
To make it possible to use requested compute-units instead of estimated transaction cost.
- Add `compute_unit_limit` to ImmtuableDeserializedPacket alone with `priority`
- Read and set its value from `compute_budget` during initialization
Fixes #
> Cache user requested compute-units with ImmutableDeserialziedPacket

- client/src/nonblocking/mod.rs
- client/src/nonblocking/quic_client.rs
- client/src/quic_client.rs
As part of the work to create an async TPU client in #25383, we want to include QUIC through the connection cache, just like in the blocking version.  There's already a lot of great async code in `client/src/quic_client` that are perfect for reuse.
To prepare for an async implementation, refactor the async bits into a new file under `client/src/nonblocking`.  There are absolutely no functional changes in this PR, literally just moving a few structs from one file to another.
> client: Refactor quic client to nonblocking

- ledger/src/shred/stats.rs
- ledger/src/shredder.rs
Data shreds are batched into `MAX_DATA_SHREDS_PER_FEC_BLOCK` shreds for
each erasure batch. If there are residual shreds not making a full
batch, then we cannot generate coding shreds and need to buffer shreds
until there is a full batch; This may add latency to coding shreds
generation and broadcast.
In order to evaluate upcoming changes removing this buffering logic,
this commit adds metrics tracking residual number of data shreds which
don't make a full batch.
> records number of residual data shreds which don't make a full batch

- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
Check I added in #25329 was too restrictive. It's possible we having missing blocks in the range, but can still generate a snapshot.
Update the blockstore slots check to iterate from the starting slot -> halt_slot using `slot_meta.next_slots`. 
Fixes #
> Fix pre-check of blockstore slots during load_bank_forks

- runtime/src/bank.rs
Create some helper functions to more easily get rent partitions for a slot range. To be used in #25334 
Fixes #
> Helper functions for getting rent partitions between slots

- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- sdk/program/src/stake/instruction.rs
When the linked features are enabled, delegating a stake amount below the minimum will return with an error saying "Error: split amount is more than is staked", which is misleading since the error was caused during delegate and not split.
See linked Issue for more information.
Use new error if stake delegation is below the minimum.
Note, _neither_ of the two linked feature are enabled, so no new feature-gate is required.
Fixes #25337 
Feature Gate Issue: #24357 
Feature Gate Issue: #24669
> Add new error if stake delegation is below the minimum

- cli/src/checks.rs
- cli/src/program.rs
Deploying programs often doesn't work during times of congestion because the blockhash expires by the time the fees are checked, which has forced many people to use the `--skip-fee-check` flag, which is dangerous in the long run.
Assuming that all write messages cost the same, only get the fee for the initial message, final message, and one write message, and figure out the total cost as:
```
cost = rent_exempt_balances + initial_message_fee + final_message_fee + write_message_fee * num_write_messages
```
Fixes #23427
> cli: Speed up fee check on program deployment

- client/src/udp_client.rs
- client/tests/quic_client.rs
- core/src/banking_stage.rs
- core/src/fetch_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
- gossip/src/cluster_info.rs
- net-utils/src/lib.rs
- streamer/src/quic.rs
- validator/src/bootstrap.rs
QUIC server to receive forwarded transactions is not running. This causes the transactions to be dropped when forwarded using QUIC.
Added code to spawn QUIC server to receive forwarded transaction.
Updated `banking_stage` code to forward votes using UDP specific connection.
Ensure only staked nodes are able to connect to QUIC forwarding port.
Fixes #
> Fix forwarding of transactions over QUIC

- core/benches/shredder.rs
- core/src/replay_stage.rs
- core/src/sigverify_shreds.rs
- ledger/benches/sigverify_shreds.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shred/common.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shred/traits.rs
- ledger/src/shredder.rs
- ledger/src/sigverify_shreds.rs
- ledger/tests/shred.rs
- validator/src/main.rs
```diff
- This is the versioning part extracted out of:
- https://github.com/solana-labs/solana/pull/25237
```
Need backward compatible way to change binary layout of shreds;
which requires some form of versioning embedded into shred binary
**First commit:**
In preparation of https://github.com/solana-labs/solana/pull/25237
which adds a new shred variant with merkle tree branches, the commit
embeds versioning into shred binary by encoding a new `ShredVariant`
type at byte 65 of payload replacing previously `ShredType` at this
offset.
```rust
enum ShredVariant {
LegacyCode, // 0b0101_1010
LegacyData, // 0b1010_0101
}
```
* `0b0101_1010` indicates a legacy coding shred, which is also equal to
`ShredType::Code` for backward compatibility.
* `0b1010_0101` indicates a legacy data shred, which …
> embeds versioning into shred binary

- validator/src/bootstrap.rs
I see following on the testnet.
Some nodes save full snapshots more often then every default 25K blocks (and/or don't produce incremental snapshots at all).
This leads to an error in choosing the highest snapshot.
Choose highest incremental snapshot first.
If all incremental are none, then choose highest full.
Else it does not matter which one will be full.
> choose highest incremental snapshot first

- runtime/src/bucket_map_holder.rs
Use the value returned from fetch_add instead of loading it again.
This happens once per bucket.
Fixes #
> disk idx: reduce lock calls

- bench-streamer/src/main.rs
- core/src/banking_stage.rs
- core/src/packet_hasher.rs
- core/src/serve_repair.rs
- core/src/unprocessed_packet_batches.rs
- core/src/window_service.rs
- gossip/tests/gossip.rs
- ledger/src/shred.rs
- ledger/src/sigverify_shreds.rs
- perf/src/sigverify.rs
- sdk/src/packet.rs
- streamer/src/nonblocking/sendmmsg.rs
- streamer/src/packet.rs
- streamer/src/sendmmsg.rs
- streamer/src/streamer.rs
Packets are at the boundary of the system where, vast majority of the
time, they are received from an untrusted source. Raw indexing into the
data buffer can open attack vectors if the offsets are invalid.
Validating offsets beforehand is verbose and error prone.
The commit updates `Packet::data()` api to take a `SliceIndex` and always to
return an `Option`. The call-sites are so forced to explicitly handle the
case where the offsets are invalid.
> removes raw indexing into packet data

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- rbpf-cli/Cargo.toml
[solana_rbpf v0.2.30](https://github.com/solana-labs/rbpf/releases/tag/v0.2.30) was released.
`Config::noop_instruction_ratio` => `Config::noop_instruction_rate` (from `f32` to `u32`).
> Bumps solana_rbpf to v0.2.30

- programs/vote/src/vote_state/mod.rs
We need to enable `fail vote account withdraw to 0 unless account earned 0 credits in last completed epoch` on testnet, devnet and eventually mainnet-beta and need better monitoring on testnet & devnet to ensure code paths have been exercised.
Add datapoints.
> Add metrics to vote account close feature

- core/src/progress_map.rs
- core/src/replay_stage.rs
Inter-block replay time could be significant and replay_active_banks metric captures a lot of work.
Break down the work to see what is actual transaction replay time vs. freeze or other time.
Fixes #
> Add new replay metrics for replay blockstore_into_bank and complete

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/read_only_accounts_cache.rs
Adds the ability to load an account into the read cache.
This is useful for prefetch situations. Examples: prior to tx processing and rent collection. In these cases, we know which accounts will be loaded.
I have built this functionality and repeatedly needed to use it. Now that rent scanning is taking ever longer (and unacceptably so), this will be used.
Fixes #
> load_account_into_read_cache

- runtime/src/accounts.rs
- runtime/src/bank.rs
Previously store() calls were done one-by-one, which leads to suboptimal performance.
Collect all needed stores, and then run them together.
@jeffwashington
> Bank: Batch account stores in collect_rent_eagerly

- runtime/src/accounts_index.rs
From<PreAllocatedAccountMapEntry<T>> for (Slot, T) grabs a write lock unnecessarily. (Also, the element doesn't need to be removed, so could save on any Vec memory management calls.) 
Since indexing the first element performs a copy, I wanted to check the size of the object to ensure it was small. For the case where `T = AccountInfo`, this is `(Slot, AccountInfo)`. Sizes are `Slot = 8B` and `AccountInfo = 12B`. So in total 20 bytes. I think the read-lock + memcpy of 20B is faster than the write-lock + move + any Vec memory management due to `remove()`.
Change write-lock to read-lock.
> Grab read-lock instead of write-lock in From<PreAllocatedAccountMapEntry<T>> for (Slot, T)

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
Rent collection is serialized currently. 1 account after another.
This process takes longer with growing # accounts.
Rent collection occurs in Bank::freeze() after all tx processing is done. The bank cannot finish until rent collection completes.
parallelize loading, collection and storing.
Fixes #
> parallelize rent collection

- account-decoder/src/parse_nonce.rs
- cli/src/nonce.rs
- cli/tests/nonce.rs
- cli/tests/stake.rs
- cli/tests/transfer.rs
- client/src/blockhash_query.rs
- client/src/nonce_utils.rs
- rpc/src/rpc.rs
- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/nonce_keyed_account.rs
- sdk/program/src/example_mocks.rs
- sdk/program/src/nonce/state/current.rs
- sdk/program/src/nonce/state/mod.rs
- sdk/program/src/system_instruction.rs
- sdk/src/feature_set.rs
- sdk/src/nonce_account.rs
- send-transaction-service/src/send_transaction_service.rs
`AdvanceNonceAccount` instruction updates nonce to blockhash. This makes it
possible that a durable transaction is executed twice both as a normal
transaction and a nonce transaction if it uses a recent blockhash (as opposed to 
the durable nonce) for its `recent_blockhash` field.
The commit prevents this double execution by separating nonce and blockhash
domains; when advancing nonce account, blockhash is hashed with a fixed string.
As a result a blockhash cannot be a valid nonce value; and if transaction was
once executed as a normal transaction it cannot be re-executed as a durable
transaction again and vice-versa.
To add type-safety and prevent old blockhash `Hash` values creeping into nonce
accounts the commit adds a new `DurableNonce` type replacing previous
blockhash value in nonce …
> separates durable nonce and blockhash domains

- web3.js/src/transaction.ts
- web3.js/test/transaction.test.ts
So, turns out that #25642 changed the sort order of accounts in a way that broke signature verification on compiled messages.
Here's a demonstration that sorting keys by the order of their _value_ produces a different order than when you sort by their Base58 representation, stringwise:
```
it('sorts the way it used to', () => {
const keysStringSorted = [];
const keysCmpSorted = [];
for (let ii = 0; ii < 100; ii++) {
const key = Keypair.generate().publicKey;
keysStringSorted.push(key);
keysCmpSorted.push(key);
}
keysStringSorted.sort((a, b) => {
return a.toBase58().localeCompare(b.toBase58());
});
keysCmpSorted.sort((a, b) => {
return a._bn.cmp(b._bn);
});
// Sometimes fails
expect(keysStringSorted.map(a => a.toBase58())).to.eql(
keysCmpSorted.map(a => a.toBase58()),
);
});
```
Run that …
> fix: revert sort order of pubkeys when compiling messages to stringwise strategy

- metrics/src/datapoint.rs
Initially when I reviewed https://github.com/solana-labs/solana/pull/25385, I thought having static tag values would suffice for the use cases I had in mind. Now that I actually took a look, my thoughts on that have changed and I want the flexibility of a String so values can be chosen at runtime.
In terms of runtime cost, the tags that I'll be adding are currently fields. Fields are owned `String`s so these cases will have the same total number of `String`s when I shift it from a field to a tag. And in general, we use `String`s for all field values, so I think my previous concerns about runtime cost over using static strings might have been overblown.
> Allow metric tag values to be runtime configurable

- client/src/connection_cache.rs
- client/src/nonblocking/mod.rs
- client/src/nonblocking/tpu_connection.rs
- client/src/nonblocking/udp_client.rs
- client/src/tpu_connection.rs
- client/src/udp_client.rs
- net-utils/src/lib.rs
As part of #25383, to order to properly support all async clients, we need underlying async connections (quic and udp).
Add the UDP client and connection trait.
There's some weirdness with repeated names and `enum_dispatch`, so I had to refactor some stuff and call the nonblocking connection `NonblockingConnection`, which is a bit ugly, but is useful later when choosing to fetch a blocking or nonblocking connection from the connection map.
> client: Add nonblocking udp client and connection trait

- runtime/src/bank.rs
This is a follow-up PR to https://github.com/solana-labs/solana/pull/25767#pullrequestreview-995595929. That PR parallelized rent collection, but there were a number of shared atomics inside the inner parallel loop; this will cause cache contention and lots of cache invalidations across all the cores. If possible, no shared data should be written to inside a parallel loop.
Instead of modifying the atomics/shared data inside the parallel loop, return them. Then have the outer loop perform a 'reduce' and finally update all the values once the parallel loop is done.
> Avoid RMWs on shared data inside parallel loops: collect_rent_from_accounts()

- scripts/cargo-install-all.sh
cargo-{build,test}-bpf now invoke cargo-{build,test}-sbf. The latter should be built by the install script.
> Add cargo sbf tools to install all script

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_options.rs
- validator/src/main.rs
When FIFO compaction is used, the size ratio between data shred and coding
shred is set to 1:1 based on the `--rocksdb_fifo_shred_storage_size` arg.
However, BlockstoreRocksFifoOptions::default() uses 5:4 ratio instead
(which is only used in the benchmark.)
This PR makes both validator argument and BlockstoreRocksFifoOptions::default()
to use 1:1 ratio between data and coding shred size.
> Make the default values of FIFO compaction consistent with validator args

- Cargo.lock
- scripts/cargo-install-all.sh
- sdk/cargo-build-sbf/Cargo.toml
- sdk/cargo-build-sbf/src/main.rs
cargo-build-sbf uses logger for all diagnostic messages.  The logger must be initialized.
Add a statement that sets up a solana logger at the beginning of main in cargo-build-sbf.
> Set up solana logger in cargo-build-sbf

- web3.js/src/transaction.ts
In https://github.com/solana-labs/solana/commit/375968da3bee9bfc184f7e70be6c9b5caa2d3811 we changed the name of `TransactionCtorFields` without realizing that there were downstream consumers importing this type.
Here's why this happened:
1. Our documentation generator TypeDoc forces us to over-export fundamentally private types from @solana/web3.js just so it can generate documentation for them. This has to stop.
2. I didn't stop to think that someone might have imported `TransactionCtorFields` types for use in their app. It turns out that one such consumer was Metaplex.
* Alias the type back to its old name.
For anyone reading this, if you ever need the type of a constructor's arguments, you don't have to rely on a library like ours to export it. You can use the `ConstructorParams` …
> fix: alias `TransactionCtorFields_DEPRECATED` back to the way it was for back-compat

- runtime/src/bank.rs
There wasn't a simple test for checking the accounts data size is correct (on all three fields) after processing a bad transaction.
This was implicitly done by other larger tests, but I kept rewriting this test while debugging anyway, so it makes sense to me to add it.
Add tests that process a good/bad transaction to affect the accounts data size (CreateAccount), and then ensure all the accounts data size fields in Bank are modified correctly.
> Add tests to Bank for accounts data size

- core/src/system_monitor_service.rs
- core/src/validator.rs
- ledger-tool/src/main.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
Metrics around host CPU utilization are very sparse, making it difficult to debug CPU bottleneck related performance issues.
Add in some CPU utilization metrics such as:
- number of vCPUs
- clock frequency
- average load across different time intervals
- number of total threads
Fixes #
> Cpu metrics

- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/broadcast_stage/broadcast_utils.rs
- core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- core/src/broadcast_stage/standard_broadcast_run.rs
- ledger/src/shred/stats.rs
- ledger/src/shredder.rs
If the blockstore has shreds for a slot, it should not recreate the
slot:
https://github.com/solana-labs/solana/blob/ff68bf6c2/ledger/src/leader_schedule_cache.rs#L142-L146
https://github.com/solana-labs/solana/pull/15849/files#r596657314
Therefore in broadcast stage if `UnfinishedSlotInfo` is `None`, then
`fec_set_offset` will be zero:
https://github.com/solana-labs/solana/blob/ff68bf6c2/core/src/broadcast_stage/standard_broadcast_run.rs#L111-L120
As a result `fec_set_offset` will always be zero, and is so redundant and
can be removed.
Removed `fec_set_offset` from `UnfinishedSlotInfo`.
> removes fec_set_offset from UnfinishedSlotInfo

- ledger/src/shred.rs
- ledger/src/shred/common.rs
- ledger/src/shred/merkle.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shredder.rs
Coding shreds can only be signed once erasure codings are already
generated. Therefore coding shreds recovered from erasure codings lack
slot leader's signature and so cannot be retransmitted to the rest of
the cluster.
`shred/merkle.rs` implements a new shred variant where we generate merkle
tree for each erasure encoded batch and each shred includes:
* full 32-byte Hash root of the merkle tree.
* slot leader's signature of the root of the merkle tree.
* merkle tree nodes along the branch the shred belongs to, where hashes
are trimmed to 20 bytes during tree construction.
This schema results in the same signature for all shreds within an
erasure batch.
When recovering shreds from erasure codes, we can reconstruct merkle
tree for the batch and for each recovered shred also recover …
> adds a new shred variant embedding merkle tree hashes of the erasure batch

- ledger/src/blockstore_options.rs
- validator/src/main.rs
Currently, the creation of ShredStorageType::RocksFifo is hard coded in validator/src/main.rs.
But this common code will also need to be used in other places like ledger-tool.
This PR creates a helper functionShredStorageType::rocks_fifo that takes a total shred_storage_size
and equally allocates to data-shred and coding-shred storage.
This PR depends on #25778.
> Helper function for creating ShredStorageType::RocksFifo

- banks-client/src/lib.rs
- banks-interface/src/lib.rs
- banks-server/src/banks_server.rs
It isn't possible to just simulate a transaction to get the return data on banks-client.
Add an implementation for it!  It's pretty much a copy of how transactions are currently simulated.  To save some lines of code, we have some `mut`, let me know if that's too weird.
Fixes  #25731
> banks-client: Add `simulate_transaction` implementation

- scripts/cargo-install-all.sh
Users installing CLI from source on macOS may not have greadlink. This clarifies the issue if that happens, and prints an error message with instructions on how to resolve the issue.
Check if greadlink is available. If it's not, print a descriptive message and exit early.
Fixes #
> Error on missing greadlink

- program-test/tests/builtins.rs
test_bpf_loader_upgradable_present => test_bpf_loader_upgradEable_present to be consistent with spelling of upgradeable elsewhere.
Fixes #
> Fix typo: upgradable to upgradEable

- runtime/src/bucket_map_holder.rs
- runtime/src/bucket_map_holder_stats.rs
- runtime/src/in_mem_accounts_index.rs
`bucket_map_holder::tests::test_age_time` fails intermittently, i.e.
https://buildkite.com/solana-labs/solana/builds/75341#01813b58-9c10-4e40-84a4-fccda52386bb
Increase the test timing tolerance for `bucket_map_holder::tests::test_age_time` to fix the intermittent test failure.
This is a follow up pull request for https://github.com/solana-labs/solana/pull/25800
Fixes #
> fix intermittent bucket age test failure

- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/nonce_keyed_account.rs
- sdk/program/src/message/sanitized.rs
- sdk/src/feature_set.rs
- sdk/src/nonce_account.rs
- send-transaction-service/src/send_transaction_service.rs
A transaction should only be processed as a durable nonce transaction if the used nonce account's authority signed the transaction.
- Add a feature gate for only processing durable nonce transactions that have been signed by the nonce authority
Feature Gate Issue: https://github.com/solana-labs/solana/issues/25835
> Reject durable nonce transactions not signed by authority

- sdk/bpf/.gitignore
- sdk/bpf/dependencies/sbf-tools
bpf-tools is gradually replaced by sbf-tools. An ignore for the changed name in sdk/dependencies was missing, and
a generated file was accidentally added to the repository.
Remove the wrongly added file and add it to ignore list
> Ignore sbf-tools in sdk/bpf/dependencies and remove the ignored file

- sdk/cargo-build-sbf/src/main.rs
Usernames and other environment specific information can be revealed
in on-chain program binary files that compiler generates, because it
includes paths to source files as strings in the binary files.  The
added option instructs the compiler to strip the path parts up to
and including crate root subdirectory from the path strings added to
the generated binary files.
> Add a rustc option to strip environment information from path strings

- core/src/banking_stage.rs
- core/src/lib.rs
- core/src/sigverify.rs
- core/src/tracer_packet_stats.rs
- core/src/unprocessed_packet_batches.rs
- core/src/voting_service.rs
- perf/src/sigverify.rs
- sdk/src/packet.rs
Tracer infrastructure isn't currently being used to report metrics
Builds on top of: https://github.com/solana-labs/solana/pull/25579
BankingStage aggregates all tracer packets:
1. Received/deduped/dropped by sigverify
2. That enter the pending buffered queue in BankingStage
3. Dropped from the pending buffered queue in BankingStage
4. Forwarded from BankingStage and who it was forwarded too
Together, these should be enough to form a directed graph tracing where packets are being shuffled across the network, assuming nodes in the graph are validators that are reporting metrics 😝 
Follow-up:
Add some metrics about tracer packets that are committed/dropped by nonretryable errors
Fixes #
> Tracer metrics for sigverify, banking_stage buffering and forwarding

- net/remote/remote-client.sh
- net/scripts/gce-provider.sh
* remove deprecated `--faucet` option for `bench-tps` call
* remove unnecessary duplication of `--imageName` option
> Net scripts clean up

- core/src/validator.rs
blockstore clean and compact is quite slow with wait-for-supermajority purge and can take 20-30 minutes
as described in #25710.
This PR removes the compaction logic in backup_and_clear_blockstore as the
actual the restoration from a bad fork is handled by `blockstore.purge_slots`
(which is done by issuing rocksdb range-delete that makes the bad fork
unavailable.)
Compaction is irreverent to the shred version, as its main job in this context
is to reclaim disk storage from the deleted slots, which we can let the rocksdb
automatic background compaction to handle it.
Fixes #25710
> Remove the compaction logic in backup_and_clear_blockstore

- runtime/src/waitable_condvar.rs
`WaitableCondvar` has a mutex so it can use `Condvar`, but doesn't need a value. It stores a `u8`, but doesn't need to.
Change what the mutex holds to nothing, i.e. the unit type: `()`.
> Change `WaitableCondvar`'s mutex to hold `()`

- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_nonce.rs
- cli/src/nonce.rs
- client/src/blockhash_query.rs
- client/src/nonce_utils.rs
- rpc/src/rpc.rs
- rpc/src/transaction_status_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/program/src/nonce/state/current.rs
- sdk/program/src/nonce/state/mod.rs
- sdk/src/nonce_account.rs
- send-transaction-service/src/send_transaction_service.rs
https://github.com/solana-labs/solana/pull/25744
separated durable nonce and blockhash domains, which will stop double
execution going forward. However it is possible that a durable
transaction has *already* been executed once as a normal transaction and
it is now a valid durable transaction. #25744 cannot stop such
transactions to be re-executed until the nonce accounts are advanced.
This commit adds a new nonce version indicating that the nonce is moved
out of blockhash domain, and permanently disables durable transactions
for legacy nonces which are in blockhash domain.
> permanently disables durable nonces with chain blockhash domain

- programs/bpf_loader/src/syscalls.rs
`CFK1hRCNy8JJuAAY8Pb2GjLFNdCThS2qwZNe3izzBMgn | active since slot 134352008 | add add_get_processed_sibling_instruction_syscall`
Fixes #
> cleanup feature: add_get_processed_sibling_instruction_syscall

- cli/src/cli.rs
- cli/src/nonce.rs
- docs/src/developing/clients/javascript-api.md
- runtime/src/system_instruction_processor.rs
- sdk/program/src/nonce/state/mod.rs
- sdk/program/src/system_instruction.rs
- transaction-status/src/parse_system.rs
- web3.js/src/system-program.ts
https://github.com/solana-labs/solana/pull/25788
permanently disables durable transactions with legacy nonce versions
which are within chain blockhash domain.
This commit adds a new system instruction for a one-time idempotent
upgrade of legacy nonce accounts in order to bump them out of chain
blockhash domain.
> adds system instruction to upgrade legacy nonce versions

- programs/bpf_loader/src/syscalls.rs
`6uaHcKPGUy4J7emLBgUTeufhJdiwhngW6a1R9B7c2ob9 | active since slot 117936008 | enable sol_log_data syscall`
Fixes #
> cleanup feature: sol_log_data_syscall_enabled

- .github/workflows/client-targets.yml
due to github action has upgraded their default ndk version
(https://github.com/actions/virtual-environments/issues/5595)
We will need to relink ndk 21 back so that our test won't break.
> chore: set ndk21 as default

- programs/bpf_loader/src/syscalls.rs
`DwScAzPUjuv65TMbDnFY7AgwmotzWy3xpEJMXM3hZFaB | active since slot 117936008 | enable sol_{set,get}_return_data syscall`
Fixes #
> cleanup feature: return_data_syscall_enabled

- programs/bpf_loader/src/syscalls.rs
`6RvdSWHh8oh72Dp7wMTS2DBkf3fRPtChfNrAo3cZZoXJ | active since slot 104976000 | secp256k1_recover syscall`
Fixes #
> cleanup feature: secp256k1_recover_syscall_enabled

- runtime/src/bank.rs
When assigning a new cost tracker in `Bank::new_from_fields()` and `Bank::new_with_paths()`, based on the cap-total-accounts-data-size feature, the `Bank::feature_set` that is used for the comparison is still the unpopulated default set. This means the existing code never actually set a new cost tracker to correctly track the total accounts data size in these code paths. The check must occur _after_ `Bank::apply_feature_activations()` as run.
Move assigning a new cost tracker into `Bank::finish_init()`.
Feature Gate Issue: #24135
> Fix new cost tracker with accounts data size limit

- banking-bench/src/main.rs
- bench-tps/src/cli.rs
- bench-tps/src/main.rs
- client/src/connection_cache.rs
- client/src/nonblocking/quic_client.rs
- client/src/quic_client.rs
- client/tests/quic_client.rs
- core/src/validator.rs
- dos/src/main.rs
- local-cluster/src/local_cluster.rs
- rpc-test/tests/rpc.rs
- test-validator/src/lib.rs
- validator/src/main.rs
To improve QUIC transaction send throughput and connection reliability. 
1. Connection pool is devised which is per address in the connection cache. The count is configurable. The default is 4 which is found to offer best balance of performance improvement and the additional memory overhead.  Each address now in the connection cache map points to a pool of connections. The pool consists of a number connection pool entries. The pool entry is checked out randomly to ensure even usage for the connections for the same address.
2.  Optimization has been done to share the Endpoint for QUIC -- connections from the same address now share the same LazyInitialized endpoint.
3. The quic_client is improved to handle connection errors. Care has been take to avoid the situation where large number of …
> Connection pool support in connection cache and QUIC connection reliability improvement

- core/src/consensus.rs
#21683 caused a regression in the implementation of `Tower::is_stray_last_vote()` whereby a default tower is considered to have a stray last vote. This can incorrectly trigger a panic here:
https://github.com/solana-labs/solana/blob/4e58b3870c29e0b141e8c9e150bfff3af4f075ee/core/src/heaviest_subtree_fork_choice.rs#L864-L876
> A default tower is no longer considered to contain a stray last vote

- program-runtime/benches/pre_account.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/pre_account.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- runtime/src/account_rent_state.rs
- runtime/src/accounts.rs
- runtime/src/bank/transaction_account_state_info.rs
`75m6ysz33AfLA5DDEzWM1obBrnPQRSsdVQ2nRmc8Vuu1 | active since slot 133920008 | support account data reallocation`
Fixes #
> cleanup feature; do_support_realloc

- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
I find the `SlotT` type alias more confusing than it's worth. It changes `(Slot, T)` to `SlotT<T>`, which adds a level of indirection to the underlying type but doesn't _really_ abstract away anything.
Remove the `SlotT` type alias and use `(Slot, T)` directly.
> Remove `SlotT` type alias

- programs/bpf/Cargo.lock
- programs/bpf/rust/curve25519/Cargo.toml
curve25519 tests backport landed while the v1.10 automated version bump
was progressing through CI. As such, the Cargo.toml file didn't exist in
the repo yet to be picked up by the script for bump.
> Manual Bump Version to 1.10.26

- programs/bpf/rust/curve25519/Cargo.toml
- programs/bpf/rust/zk_token_elgamal/Cargo.toml
The rest of the monorepo uses 2021 as the rust version, bumping these up to match.
Fixes #
> Bump rust edition to 2021 to match rest of repo

- runtime/src/in_mem_accounts_index.rs
Disabling and re-enabling evictions from the in-mem accounts index is decoupled, which makes it possible to forget to re-enable. This is especially true as refactors happen, or if early-returns are introduced.
Add an RAII type (`EvictionsGuard`) to handle disabling and re-enabling evictions.
> Add EvictionsGuard to InMemAccountsIndex

- explorer/src/pages/TransactionDetailsPage.tsx
The explorer shows "Details are not available" while transaction details are being fetched
-
Fixes #
> fix explorer to show loading rather than "Details are not available" while transaction details are being fetched

- ledger/src/blockstore_processor.rs
- runtime/src/bank_utils.rs
Simple vote transactions that land in incompatible forks are currently being suppressed and never reach `ClusterInfoVoteListener`.
This is not ideal because all signed and valid simple vote transactions should contribute to consensus as quickly as possible, regardless if whether they successfully executed or not.
Conversely, this is not fatal because (a) votes are gossiped, and gossip-based votes are not executed at all before being processed, (b) eventually a simple vote transaction should find it's way into a compatible fork and be counted, assuming the fork has meaningful stake behind it.
Therefore including these failed simple vote transactions shouldn't harm, and in some case may allow nodes to more quickly compute the stake weight between competing forks.
> Do not exclude failed simple vote transactions from consensus

- runtime/src/snapshot_utils.rs
We check if the length is greater than 1, and error if it is. The sort is unnecessary.
Removed the sort
Fixes #
> snapshot_utils.rs: remove unnecessary sort

- RELEASE.md
Several instructions are slightly out of date from recent CI changes / improvements.
- Most notably, https://github.com/solana-labs/solana/pull/25821 automated the process creating a PR to update Cargo.toml versions.
- We also moved away from TravisCI, so include updates on where Windows and macOS artifacts come from
> Update RELEASE.md to reflect recent CI changes

- rayon-threadlimit/src/lib.rs
A third party fuzzer uncovered a divide-by-zero error in `blockstore_processor::execute_batches()`.
https://github.com/solana-labs/solana/blob/3e1fd4dad0919011925b1f4315957a97091c885e/ledger/src/blockstore_processor.rs#L356-L361
`target_batch_count` could be `0` due to the impl of `get_thread_count()`.
Add in a `.max(1)` to ensure the smallest number returned is 1, not 0.
> Take `.max(1)` when computing MAX_RAYON_THREADS

- core/src/banking_stage.rs
- core/src/leader_slot_banking_stage_metrics.rs
- core/src/leader_slot_banking_stage_timing_metrics.rs
Counters for forwarding that accumulated between banks are not reported.
- Separate leader slot boundary checking and metrics reporting/resetting into two steps;
- report metrics _before_ consuming, or _after_ forwarding.
Fixes #
> Include forwarding counters in leader slot metrics

- perf/benches/sigverify.rs
- perf/src/sigverify.rs
Continuation from #25833 
When a node is about to become leader, there is a flood of traffic on the TPU port. This causes a spike in verify CPU time consumption, which takes away compute resources from replay and can slow it down. We've observed this slowdown in replay leading to forks and thus skipped slots, especially in lower core count systems.
Add minimum length iterator (for packet count) when dealing with lower packet counts to reduce the amount of CPU consumed. This minimum limit is dynamic based on incoming packet count and strives to have no more than X packets (taking ~X*100us to verify) per thread when possible.
> Add minimum iterator packet count for rayon verification threads

- transaction-status/src/parse_associated_token.rs
- transaction-status/src/parse_bpf_loader.rs
- transaction-status/src/parse_stake.rs
- transaction-status/src/parse_system.rs
- transaction-status/src/parse_vote.rs
Instruction parser tests don't verify that the instruction parsers return a happy error instead of a panic when the instruction's `accounts` vector is too short to cover the indexes used.
Add such test cases
> RPC instruction parser tests are missing some cases

- docs/src/cluster/stake-delegation-and-rewards.md
- programs/vote/src/vote_instruction.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- runtime/src/vote_parser.rs
- sdk/src/feature_set.rs
- transaction-status/src/parse_vote.rs
Given a base key, a seed (arbitrary data, like the string `"VOTER_SEED"`) and the address of a program, you can create a derived key for that program. This key can never sign for anything, because it has no associated secret key.
The vote program lets you authorize an account to be the ‘withdrawer.’
There's nothing stopping you from authorizing a derived key to be the ‘withdrawer’ authority on a vote account, but if you do, you'll never be able to withdraw funds, since nobody can sign for the derived key.
Fixes #25860.
Feature Gate Issue: #25930.
> Implement `VoteInstruction::AuthorizeWithSeed` & `VoteInstruction::AuthorizeWithSeedChecked`

- .mergify.yml
No need to ping community-pr-subscribers list / add community tag for commits from github-actions bot.
> Add github-actions bot to approved commit author list

- measure/src/measure.rs
`Measure` does not have a method to return its duration as a `Duration`. I've found myself wanting this method to use when interfacing with other code that takes in a `Duration`.
Add `as_duration()` to `Measure`.
> Add `Measure::as_duration()`

- ledger/src/blockstore_processor.rs
Replay's blockstore_processor iterates through transaction batches twice to pull out lock results and then transactions. Could be done in one iteration instead.
Combine iterators into one (prep for adding another array in https://github.com/solana-labs/solana/pull/25688)
> Reduce 2 iterators to one

- runtime/src/accounts_index_storage.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
Remove potential race condition by limiting age advancement to 1 special thread in the flushing pool.
Fixes #
> AcctIdx: only advance age on thread 0

- .github/ISSUE_TEMPLATE/1-feature-gate.yml
It's always tedious to figure out the lowest release(s) a feature is present in
Add fields to the feature-gate issue template to store minimum version info for both stable and beta releases (these might be the same, but often they aren't)
> Add inputs to indicate minimum beta and stable releases that support the feature

- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- core/src/broadcast_stage/standard_broadcast_run.rs
- core/src/tpu.rs
`&Arc<...>` is almost always redundant and can be replaced with either of `Arc<...>` or plain reference `&`.
Removed `&Arc<...>`.
> removes erroneous uses of &Arc<...> from broadcast-stage

- runtime/src/accounts.rs
get rid of this noisy log that got N threads worse when we parallelized rent collection
```
32216Z INFO  solana_metrics::metrics] datapoint: load_to_collect_rent_eagerly_scan_elapsed total_elapsed=272i latest_slot_elapsed=0i read_lock_elapsed=0i load_account_elapsed=12i iterator_elapsed=220i num_keys_iterated=38i
[2022-06-15T04:27:45.280459038Z INFO  solana_metrics::metrics] datapoint: load_to_collect_rent_eagerly_scan_elapsed total_elapsed=282i latest_slot_elapsed=0i read_lock_elapsed=0i load_account_elapsed=26i iterator_elapsed=207i num_keys_iterated=46i
[2022-06-15T04:27:45.280562384Z INFO  solana_metrics::metrics] datapoint: load_to_collect_rent_eagerly_scan_elapsed total_elapsed=363i latest_slot_elapsed=1i read_lock_elapsed=1i load_account_elapsed=72i iterator_elapsed=244i …
```
> disable logging per thread on rent collection load

- runtime/src/bank.rs
- runtime/src/stake_weighted_timestamp.rs
`warp_timestamp_with_a_vengeance` has been activated on all clusters, making the logic around both that feature and `warp_timestamp_again` obsolete.
Clean up warp-timestamp features. I left a note about how to warp the timestamp again in the future, if needed.
I also left the previous limit constants as sort of a historical record
Fixes #25668
> Clean up warp-timestamp features

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
For startup perf.
At startup, queue up insertions into account index to process when a bin is being flushed.
Fixes #
> generate_index straight to disk and batched

- runtime/src/bank.rs
There are not explicit accounts data size tests to ensure that:
1. Resize/realloc transactions correctly update the bank's accounts data size fields
2. Reclaimed accounts from rent collection correctly update the bank's accounts data size fields
Add two tests. One for accounts data size and resize transactions, and one for accounts data size and rent collection.
> Add bank tests for accounts_data_size and resize transactions / rent collection

- ledger-tool/src/bigtable.rs
- rpc/src/rpc.rs
- rpc/src/rpc_service.rs
- storage-bigtable/src/bigtable.rs
- storage-bigtable/src/lib.rs
- validator/src/bin/solana-test-validator.rs
- validator/src/main.rs
Google Cloud Bigtable uses [App Profiles](https://cloud.google.com/bigtable/docs/app-profiles) to manage routing traffic to clusters allowing users to maintain replicas, perform automatic-failover, and isolate workloads. The current `solana-bigtable` code always uses the default app profile (named `default`) that is created with each instance. Users are unable to override.
This PR adds the ability to override the default app profile in `solana-bigtable`. A flag is introduced in both the validator and the ledger-tool to override.
Fixes #
> Add ability to use a non-default app profile id in bigtable requests

- ledger/src/blockstore_processor.rs
- sdk/src/feature_set.rs
The per-block accounts data size limit is only part of BankingStage, and is not checked in ReplayStage.
Add checks to ReplayStage that will fail blocks that exceed the accounts data size _per-block_ limit.
Feature Gate Issue: #25517
> Enforce accounts data size limit per block in ReplayStage

- programs/bpf_loader/src/syscalls.rs
Spin-off from #25899.
Replace `AccountSharedData` by `BorrowedAccount` in CPI syscall.
As all methods in `BorrowedAccount` always succeed this should not make a difference (for now).
> Use `BorrowedAccount` in CPI syscall.

- ledger/src/shred/stats.rs
- ledger/src/shredder.rs
Data shreds may have trailing buffer wasted.
Added metric tracking how much buffer is wasted on average per shred.
> adds metric tracking wasted data buffer in shreds

- program-runtime/src/invoke_context.rs
- program-runtime/src/sysvar_cache.rs
- program-test/src/lib.rs
- programs/address-lookup-table/src/processor.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/config/src/config_processor.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- programs/vote/benches/process_vote.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
`index_in_instruction` is a mixed index, meaning that it maps both program accounts and instruction accounts in one sequence.
`index_in_instruction = program_account_index`
or
`index_in_instruction = number_of_program_accounts + instruction_account_index`
In most cases however, we only want to use one: Either program accounts or instruction accounts.
Thus, it is better to split their interfaces to avoid conflation and also to reduce the index shifting in the code base.
Also, some interfaces were already split, because they only make sense for one of the two account types,
so this PR makes the interfaces more uniform and hopefully less confusing as well.
Split methods of `InstructionContext`:
- `get_index_in_transaction()` into `get_index_of_program_account_in_transaction()` and …
> Refactor: instruction account index

- programs/bpf/Cargo.lock
CI `checks` job failing due to cargo audit
Bump openssl in programs/bpf
> Bump openssl in programs/bpf

- ledger-tool/src/bigtable.rs
- ledger/src/bigtable_upload.rs
- ledger/src/bigtable_upload_service.rs
https://github.com/solana-labs/solana/pull/24716 added a configurable limit to the number of blocks that `solana_ledger::bigtable_upload::upload_confirmed_blocks` checks at a time. However, it neglected to update `solana-ledger-tool`.
Add a loop to `solana-ledger-tool bigtable upload` so that the upload service iterates through the entire requested range, instead of stopping at the first limit.
Fixes #26023
> Add ledger-tool bigtable upload loop

- cli/src/cli.rs
- cli/src/cluster_query.rs
Currently we cannot search stakes and filtering by withdraw authority. I have added into cli stakes command a way to filter it with withdraw authority.
Updating cli to pass withdrawer_pubkey and filter the results out by doing memcmp on the stakes.
Fixes #25462
> Filter stakes by withdrawer

- client/src/nonblocking/udp_client.rs
- client/src/udp_client.rs
- net-utils/src/lib.rs
v1.10 will panic when all ports in the 8000-10000 range are bound:
1. https://github.com/solana-labs/solana/blob/d2f61c7bb62111805120ae874c3404e2e1c99bba/core/src/banking_stage.rs#L608
2. https://github.com/solana-labs/solana/blob/d2f61c7bb62111805120ae874c3404e2e1c99bba/client/src/nonblocking/udp_client.rs#L22
v1.9 still panics but only when all u16 ports are bound:
1. https://github.com/solana-labs/solana/blob/f60d8522ebfcea3dc22c20d067e22a2927c0b75d/core/src/banking_stage.rs#L958
Restore the full u16 range for master/v1.10 as this panic has been observed in real life. It'd be nice to handle the unwrap more gracefully as a long-term cleanup item
> UdpTpuConnection no longer restricts its local port to the 8000-10000 range

- cli/src/cluster_query.rs
Why write a whole match when a mutable reference will do?
Fixup recently merged `solana stakes` code to simplify adding withdrawer-authority filter
Fixes #
> Nitty code simplification

- core/src/tpu.rs
- core/src/validator.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
Add hidden flag to enable QUIC servers for `ClusterType::MainnetBeta` to allow for further testing before a wider roll out.
> core: disable quic servers on mainnet-beta

- runtime/src/in_mem_accounts_index.rs
There is a possible deadlock caused by double readlock in `assert!` in fn `write_startup_info_to_disk`.
The read lock on L1024 is not released before acquiring another read lock on L1025.
For more details on this kind of deadlock, see
https://www.reddit.com/r/rust/comments/urnqz8/different_behaviors_of_recursive_read_locks_in/
Interestingly, the readlock on L1022 is immediately released and does not cause deadlock.
The fix is to acquire the read lock once and reuse it.
Fixes #
> runtime: fix double-readlock in in_mem_accounts_index.rs

- core/src/validator.rs
There is a possible deadlock caused by double readlock in fn `Validator::new`.
`bank_forks: Arc<RwLock<BankForks>>`
The first readlock is on L705 and the second on L706
https://github.com/solana-labs/solana/blob/fbf7143a97a18a872f5b111b9dd1ce0b7ba412a0/core/src/validator.rs#L704-L707
For more details on this kind of deadlock, see
https://www.reddit.com/r/rust/comments/urnqz8/different_behaviors_of_recursive_read_locks_in/
Call readlock once and reuse it. After the call, drop the guard.
Fixes #
> core: fix double-readlock in validator

- ci/README.md
- ci/run-local.sh
- ci/test-stable.sh
- scripts/coverage-in-disk.sh
- scripts/coverage.sh
Running CI locally using `ci/run-local.sh` on macOS fails with "local CI runs are only supported on Linux".
- Fallback to `sysctl hw.memsize` instead of `/proc/meminfo` to obtain installed memory if `/proc/meminfo` is not found
- Remove `uname -o` check which allows only Linux OS to run local CI
- Add instructions for installing prerequisites
> Support local CI on macOS

- streamer/src/nonblocking/quic.rs
We are currently always assuming we remove 1 connection from the quic server connection table when we remove the connections associated with an IP:Port pair. However, there may actually be multiple connections associated with an IP:Port pair. In that case, the total connection table size becomes incorrect due to this incorrect assumption.
Calculate the number of connections actually removed from the connection table and subtract this value from the total connection table size.
Fixes #
> Fix incorrect total connection table size in the quic server when removing multiple connections with the same IP:Port

- net/scripts/gce-provider.sh
The current version of image uses kerne version `5.4.0-1030-gcp`.
Problem is that there is no dpkg for linux-tools for this kernel version in ubuntu artifactory (to check `apt-cache search linux-tools-5.4.0-1030-gcp`).
It means that it is not possible to install perf for the following PR https://github.com/solana-labs/solana/pull/25624
Updates ubuntu image
> update ubuntu image 

- dos/src/main.rs
Sending packages in batches gives significant effect when there are many packets to send (follow up PRs add higher transactions generation rate).
This is part of larger PR: https://github.com/solana-labs/solana/pull/25335
> replace send with sendmmsg

- core/src/banking_stage.rs
`UdpTpuConnection` allocates a new socket on creation. Forwarding of votes is creating a new instance of this class for every batch of vote forwarding. This is creating excessive amount of sockets, and can lead to port exhaustion.
This PR resurrects vote forwarding logic from v1.9 branch. The banking stage creates one UDP socket at start, and uses this socket to forward all the votes.
Fixes #26077
> Do not use UdpTpuConnection to forward votes

- core/src/lib.rs
- core/src/packet_hasher.rs
- core/src/retransmit_stage.rs
Packet-hasher is not mutated across threads and does not need to be
wrapped in a mutex.
Moved packet-hasher out of the mutex.
> moves packet-hasher out of the mutex

- bench-tps/src/bench_tps_client.rs
- bench-tps/src/bench_tps_client/bank_client.rs
- bench-tps/src/bench_tps_client/rpc_client.rs
- bench-tps/src/bench_tps_client/thin_client.rs
- bench-tps/src/bench_tps_client/tpu_client.rs
There is no method `get_account` for `BenchTpsClient` which is needed for follow up PRs adding durable nonce transactions.
* Adds `get_account` method
> add get_account to BenchTpsClient

- runtime/src/in_mem_accounts_index.rs
This reverts commit 05cb25d8da06e590a13f6bc9a17cde826f5c40b2.
#25797
note that today I saw a negative account count:
Trying to figure out how that happened.
I don't think this was caused by the original change, but I'm not sure yet.
```
2022-06-20T16:04:19.314331706Z INFO solana_metrics::metrics] datapoint: accounts_index estimate_mem_bytes=535184i flush_should_evict_us=0i count_in_mem=10291i count=-4838i bg_w
```
Fixes #
> Revert "fix double count of account index del stats (#25797)"

- client/src/nonblocking/quic_client.rs
- client/tests/quic_client.rs
- core/src/find_packet_sender_stake_stage.rs
- core/src/staked_nodes_updater_service.rs
- core/src/tpu.rs
- sdk/src/quic.rs
- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
- streamer/src/streamer.rs
Weight concurrent streams by stake for staked nodes
Ported changes from https://github.com/solana-labs/solana/pull/25056 after address merge conflicts and some refactoring
Fixes #26033
> Weight concurrent streams by stake

- web3.js/src/connection.ts
The return value of these was incorrect, leading to an `any` propagating through the code, which led to real breakages in the framework (eg. #26099).
When we properly represent this return type as a _promise for an array_ then array methods like `map()` return correct types.
> chore: correct the types of `Rpc{Batch}Request` to prevent type errors in `Connection.ts`

- banking-bench/src/main.rs
- bench-tps/src/main.rs
- client/src/connection_cache.rs
- client/src/nonblocking/udp_client.rs
- client/src/udp_client.rs
- core/src/validator.rs
- dos/src/main.rs
- local-cluster/src/local_cluster.rs
- rpc-test/tests/rpc.rs
Every instance of`UdpTpuConnection` creates a new socket to send packets. The current design leads to opening of excessive amount of UDP ports. A single UDP socket should be sufficient. 
The user of `UdpTpuConnection` will initialize the send socket, and provide it to `UdpTpuConnection` at init time.
Fixes #26077
> Use single send socket in UdpTpuConnection

- runtime/src/bank.rs
I found a lone `StatusCache<Result<()>>` in `bank.rs` while reading through the status cache code. Since we're in `bank.rs`, use the `BankStatusCache` type alias instead.
Replace `StatusCache<Result<()>>` with `BankStatusCache`.
> Use BankStatusCache in bank.rs

- storage-bigtable/src/lib.rs
There are no time series for tracking the latest block uploaded to Bigtable.
This commit adds a datapoint metric called
"storage-bigtable-query-last-block-uploaded" which reports the most
recently uploaded block by the threads spawned inside the
"solana_ledger::bigtable_upload::upload_confirmed_blocks" function.
It gets the information into a time series database-compatible format,
which makes it a easier to build monitoring and alerting.
We built the binary locally using the solanalabs/rust container image,
and tested the binary on a machine and saw log messages that looked like
this:
```
[2022-06-17T14:01:43.843999910Z INFO  solana_metrics::metrics] datapoint: storage-bigtable-query-last-block-uploaded height=135987534i
[2022-06-17T14:01:43.871708319Z INFO  solana_metrics::metrics] …
```
> Add metric for tracking Bigtable blocks uploaded

- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
QUIC stream receiver waits indefinitely for data from peer. This can cause a client to open unbounded number of streams on a receiver.
Add a timeout to receive data on stream.
Add a unit test.
Fixes #
> QUIC stream timeouts if no data is received

- ledger/src/blockstore.rs
This issue was discovered from investigations into https://github.com/solana-labs/solana/issues/26028. A more detailed writeup is included in [this comment](https://github.com/solana-labs/solana/issues/26028#issuecomment-1161361398), but the quick summary is:
Given a slot `s` with parent slot `p`, it is possible for `s` to be inserted into `p`'s SlotMeta::next_slots Vec multiple times when `Blockstore::clear_unconfirmed_slot()` is called on slot `s`. If `p` was processed again, `s` would be added to the queue of slots to be processed multiple times. 
Make `clear_unconfirmed_slot()` on slot `s` remove `s` as a next slot from `s`'s parent.
Some alternative ways that we could fix this specific bug:
- Update the below function to check if value exists before inserting. `next_slots` is a `Vec` …
> Make clear_unconfirmed_slot() update parent's next_slots list

- core/src/lib.rs
- core/src/retransmit_stage.rs
- core/src/shred_fetch_stage.rs
- core/src/sigverify_shreds.rs
- core/src/tvu.rs
- core/src/window_service.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shred/stats.rs
Shred versions are not verified until window-service where resources are
already wasted to sig-verify and deserialize shreds.
The commit verifies shred-version earlier in the pipeline in fetch stage.
> verifies shred-version in fetch stage

- runtime/src/bank.rs
- runtime/src/snapshot_utils.rs
`StatusCacheRc::append()` is only called in one place, and doesn't abstract anything away usefully (IMO).
Call `StatusCache::append()` directly.
> Call StatusCache::append() directly

- runtime/src/bank.rs
- runtime/src/stakes.rs
Storing stake accounts suffers from RWLock contention on stake_cache.  That's why storing stake account (running highly parallel) takes much longer time than storing vote account (running single threaded).
Separate stake account store from reward redeem. Keep reward redeem running in parallel, batch the staking accounts to store and store the stake accounts in a single thread. 
**Result**
Store time reduced from 4.4s to 1.7s.
```
update_rewards_with_thread_pool_us=7230692i load_vote_and_stake_accounts_us=4454714i store_stake_accounts_us=1767486i
```
```
update_rewards_with_thread_pool_us=12077002i load_vote_and_stake_accounts_us=7272740i store_stake_accounts_us=4467960i
```
Fixes #
> Optimize stake accounts store

- runtime/src/accounts.rs
- runtime/src/bank.rs
pushing `StorableAccounts` one function farther upstream.
Fixes #
> Accounts::store_accounts_cached uses StorableAccounts

- scripts/confirm-cargo-version-numbers-before-bump.sh
The Github Action version bump checks if the tag and branch name match. If a release is tagged off master this check fails.
Add exception for master branch.
> Update version bump check so it works on master branch

- streamer/src/nonblocking/quic.rs
The stream timeout should not result in abandoning stream.
This was discussed as PR comments here: https://github.com/solana-labs/solana/pull/26116#discussion_r903464323
1. Do not abandon the stream on read timeout
2. Reduce the timeout value
3. Update the test to ensure the writes are successful after read timeout
Fixes #
> Tune stream timeout and reading after timeouts

- ci/buildkite-secondary.yml
- ci/publish-installer.sh
- ci/publish-tarball.sh
Due to #26064, I found two things:
1. We upload installer script many times although they are the same
2. When we try to upload something, We run s3cmd in docker and volume the target files into it. The bug is that our x86 mac seems cache volume file for a while. I can reproduce the bug but haven't found the real reason.
I think we should solve both but ideally when this PR been merged and then 2.'s bug will be hidden. I'll merge this first and still investigating 2.
1. reorder steps attributes
4. extract publish installer logic as an independent step
> chore: separate publish installer process

- runtime/src/status_cache.rs
The PR's title and the diff should be sufficient for this tiny PR 😄
> StatusCache::roots() returns `Slot`s not `u64`s

- runtime/src/builtins.rs
- sdk/src/lib.rs
https://github.com/solana-labs/solana/pull/23295 added auto traits to `BuiltinFeatureTransition` to work around Rust issue https://github.com/rust-lang/rust/issues/92987. This bug was fixed in Rust v1.60.0, which is the version we use, so this work-around can be removed.
https://github.com/solana-labs/solana/blob/e344c8476f5aa63860602923c5db68f5fc33b7f8/runtime/src/builtins.rs#L94-L110
Remove work-around from #23295 and #23321.
> Remove auto traits from ICE work-around

- core/benches/retransmit_stage.rs
- core/benches/shredder.rs
- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- core/src/window_service.rs
- gossip/src/duplicate_shred.rs
- ledger/src/blockstore.rs
- ledger/src/shredder.rs
- ledger/tests/shred.rs
Simplifying https://github.com/solana-labs/solana/pull/25807; extracting trivial parts in a separate PR.
In prepration of https://github.com/solana-labs/solana/pull/25807
which reworks erasure batch sizes, this commit:
* adds a helper function mapping the number of data shreds to the
erasure batch size.
* adds `ProcessShredsStats` to `Shredder::entries_to_shreds` in order to
replace and remove `entries_to_data_shreds` from the public interface.
> maps number of data shreds to erasure batch size

- rpc/src/rpc.rs
There is a possible deadlock caused by double readlock in fn `get_transaction_status`.
`block_commitment_cache` is an `Arc<RwLock<...>>`.
The first readlock is on L1434
https://github.com/solana-labs/solana/blob/fbf7143a97a18a872f5b111b9dd1ce0b7ba412a0/rpc/src/rpc.rs#L1434-L1436
The second readlock is on L253 in fn `bank`
https://github.com/solana-labs/solana/blob/fbf7143a97a18a872f5b111b9dd1ce0b7ba412a0/rpc/src/rpc.rs#L250-L254
For more details on this kind of deadlock, see
https://www.reddit.com/r/rust/comments/urnqz8/different_behaviors_of_recursive_read_locks_in/
The fix is to move the first readlock after the calling of fn `bank`.
But I wonder if this is correct or optimal.
1. I do not know if `optimistically_confirmed` should be protected by `block_commitment_cache`? OR
2. can we …
> rpc: fix possible deadlock in rpc

- core/tests/snapshots.rs
- runtime/benches/status_cache.rs
- runtime/src/bank.rs
- runtime/src/bank_forks.rs
- runtime/src/snapshot_utils.rs
- runtime/src/status_cache.rs
All uses of `StatusCacheRc::slot_deltas()` (1) only get the roots from the status cache, and (2) unnecessarily sort. These are performance loses.
1. Add `StatusCache::root_slot_deltas()` which gets the slot deltas from its roots
2. Remove `StatusCacheRc::slot_deltas()` and call `StatusCache::root_slot_deltas()` instead
3. Add benchmarks to ensure this is actually a speedup
```sh
1. test bench_status_cache_root_slot_deltas               ... bench:       8,366 ns/iter (+/- 592)
2. test bench_status_cache_slot_deltas                    ... bench:       9,200 ns/iter (+/- 612)
3. test bench_status_cache_slot_deltas_get_roots_sorted   ... bench:      16,086 ns/iter (+/- 2,978)
4. test bench_status_cache_slot_deltas_get_roots_unsorted ... bench:      10,692 ns/iter (+/- 809)
```
In (2), that is …
> Add StatusCache::root_slot_deltas() and use it

- runtime/src/in_mem_accounts_index.rs
While reviewing https://github.com/solana-labs/solana/pull/26046, I noticed that `InMemAccountsIndex::map()` wasn't used outside this struct, and adds an unnecessary indirection (IMO).
Remove `InMemAccountsIndex::map()` and use `InMemAccountsIndex::map_internal` directly
> Remove `InMemAccountsIndex::map()` and use `map_internal` directly

- streamer/src/nonblocking/quic.rs
The number of total active streams is not calculated properly
Fixes #26034
> [quic]Decrement total_streams correctly

- explorer/src/pages/inspector/AddressWithContext.tsx
The tx inspector (`/inspect`) doesn't annotate the size of the account inputs
- Add size in account details
- Remove special handling for executable accounts
Fixes #
> explorer: Add account bytes to tx inspector

- runtime/src/bank.rs
This was exposed by a stake account whose partition was 0. Function was doing what it was supposed to do, but the caller was passing the wrong epoch, so the if was never true.
Fixes #
> don't skip rewrite when account was written IN the current slot already

- core/tests/snapshots.rs
- runtime/src/bank.rs
- runtime/src/bank_forks.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
The `StatusCacheRc` doesn't provide any useful abstraction, IMO.
Remove `StatusCacheRc` and use `StatusCache` directly.
> Remove `StatusCacheRc` and use `StatusCache` directly

- runtime/src/bank.rs
Instead of accessing nested struct members to get stake reward, add a more meaningful fn to get stake reward.
extract get_stake_reward fn from StakeReward
Fixes #
> refactor: extract get_stake_reward fn from StakeReward

- validator/src/admin_rpc_service.rs
- validator/src/main.rs
This does not work:
```shell
ssh solana@example.org "solana-validator --ledger /ledger set-identity" <local/identity/file.json
```
This does not work too:
```shell
ssh solana@example.org "solana-validator --ledger /ledger set-identity /dev/stdin" <local/identity/file.json
```
New admin RPC functions added to support this feature. Old functions are still there, so any existing third-party tools around this functionality will continue to work.
> Support reading keypair from stdin in `solana-validator set-identity`/`solana-validator authorized-voter add`

- runtime/src/bank.rs
> retain prior metric behavior for invalid_cached_stake_accounts

- bench-streamer/Cargo.toml
- ci/README.md
- ci/test-checks.sh
- dos/Cargo.toml
- frozen-abi/Cargo.toml
- gossip/Cargo.toml
- ledger-tool/Cargo.toml
- net-shaper/Cargo.toml
- programs/bpf/Cargo.toml
- programs/bpf/rust/128bit/Cargo.toml
- programs/bpf/rust/dep_crate/Cargo.toml
- programs/bpf/rust/many_args/Cargo.toml
- programs/bpf/rust/param_passing/Cargo.toml
- programs/bpf/rust/realloc_invoke/Cargo.toml
- runtime/Cargo.toml
- send-transaction-service/Cargo.toml
Dependencies in Cargo.toml are occasionally unsorted.
- Run `cargo sort --workspace` to sort dependencies
- Introduce `cargo sort --workspace --check` in nits.sh 
Fixes #23608
> Enforce Cargo.toml tables are sorted in CI

- core/src/progress_map.rs
- runtime/src/vote_account.rs
- sdk/src/account.rs
converting `AccountSharedData` to `Account` causes a copy of data. We previously did this so we could serialize. We can now serialize `AccountSharedData` directly.
Fixes #
> vote_account uses AccountSharedData to avoid copies

- docs/package-lock.json
- docs/src/implemented-proposals/transaction-fees.md
- docs/src/running-validator/validator-start.md
- docs/yarn.lock
tuning guide omits adjusting `fs.nr_open` sysctl knob along with the max maps count, which puts an limits us to 1<<20 regardless of how we set the present tuneables
update it in sync with maps
> docs: update tuning guide

- runtime/src/nonce_keyed_account.rs
- sdk/program/src/nonce/state/mod.rs
Moving out portion of https://github.com/solana-labs/solana/pull/26055 which is new code into a separate pull request.
Follow up commit removes feature gate code separating durable nonce from
blockhash domain. This commit allows to encapsulate any logic
distinguishing legacy vs current nonce versions in the nonce module
after removing the feature gate.
> encapsulates AuthorizeNonceAccount implementation in the nonce module

- core/src/commitment_service.rs
- core/src/consensus.rs
- core/src/replay_stage.rs
- core/src/vote_simulator.rs
- runtime/src/bank.rs
The stake value is never used when calling `Bank::get_vote_account`
- Simplify the return type of `Bank::get_vote_account` to return only the vote account rather than a tuple with the stake amount
Fixes #
> Refactor: No need to return stake in Bank::get_vote_account

- core/src/cluster_info_vote_listener.rs
- runtime/src/epoch_stakes.rs
- runtime/src/vote_account.rs
There a few places that get the delegated stake for a vote account in the same way
- Add new `get_delegated_stake` method to `VoteAccounts` and use it instead of `VoteAccounts::get` where appropriate
Fixes #
> Refactor: Add get_delegated_stake method to VoteAccounts

- runtime/src/bank.rs
- runtime/src/stakes.rs
- runtime/src/vote_account.rs
It's not clear when callers need to access a vote account or its delegated stake
- Add separate methods for retrieving stake info from VoteAccounts
Fixes #
> Refactor: Add separate methods for retrieving stake info from VoteAccounts

- core/src/consensus.rs
- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
- ledger/src/blockstore_processor.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/common.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_flakey.rs
- local-cluster/tests/local_cluster_slow_2.rs
some rooted slots could be omitted to be marked.
some rooted slots could be omitted after restart (hard fork), if the hard fork slot is ahead of the validator's latest ledger root before the restart.
This is usually the case because current practice of cluster restart is based on the opt-conf-ed slot. (i.e. no node should have rooted that slot yet)
ultimately, this leads to hole in bigtable.
cc: @mvines @sakridge @carllin 
~~fix it. (this is wip; I'm working on to fix the actual hole now).~~ impl finished
related: #13536
> Avoid to miss to root for local slots before the hard fork

- web3.js/src/transaction.ts
- web3.js/test/transaction.test.ts
Right now, `compileMessage()` is side-effectful. If you start with a nonce-based `Transaction` instance whose `recentBlockhash` member is `undefined`, running `compileMessage` will ‘fill in’ the `recentBlockhash` member with the value of `nonceInfo.nonce`. It will also have the side effect of _prepending_ the `AdvanceNonceAccount` instruction to `instructions`.
`compileMessage` has no right to do this. It should perform reads only. The only thing that can result from this is confusion. Why does a nonce-based transaction have no recent blockhash at one point in time, but does in another? What if `recentBlockhash` differs from `nonceInfo.nonce` because someone overwrote it? Which will the developer expect to be used? Why did the size of the instructions list change when I called …
> fix: nonce-based Transactions no longer mutate the transaction in place when you `compileMessage`

- Cargo.lock
- sdk/Cargo.toml
- sdk/src/packet.rs
The well known magic number `1232` is always hard to `grep`...:
precedent: #16812
> Add const_assert_eq to PACKET_DATA_SIZE

- runtime/src/append_vec.rs
Test fails on m1 mac's w/ current rust compiler.
Assert that sanitize_executable fails (what we really care about).
Remove the check that `*executable_bool == FALSE`, which changes based on compilers.
Fixes #
> fix test_new_from_file_crafted_executable for m1

- core/benches/cluster_nodes.rs
- core/src/cluster_nodes.rs
- core/src/retransmit_stage.rs
- ledger/src/shred.rs
Following commits will skip shreds deserializaton before retransmit, and
so we will only have a `ShredId` and not a fully deserialized shred to
obtain the shuffling seed from.
moved `Shred::seed` to `ShredId` and adds test coverage
> moves Shred::seed to ShredId and adds test coverage

- streamer/src/nonblocking/quic.rs
awaiting streams in order can produce head of line blocking when streams come in out of order
spawn for each stream
Fixes #26031
> QUIC server: Spawn for each stream

- core/src/retransmit_stage.rs
- core/src/sigverify_shreds.rs
- core/src/tvu.rs
- core/src/window_service.rs
Shreds are dropped in window-service if the slot leader is the node
itself:
https://github.com/solana-labs/solana/blob/cd2878acf/core/src/window_service.rs#L181-L185
However this is done after wasting resources verifying signature on
these shreds, and requires a redundant 2nd lookup of the slot leader.
This commit instead discards such shreds in sigverify stage where we
already know the leader for the slot.
> discards shreds in sigverify if the slot leader is the node itself

- client/src/http_sender.rs
RPC providers collect metrics today, but have no way of filtering those metrics by a particular version of the client. This would be useful in identifying regressions (eg. a version of the client that's particularly badly behaved) or improvements (eg. a version of the client that aims to reduce load on RPCs, like #26236).
* Added a `user-agent` HTTP header to each request.
```
cd cli && cargo run block 125791054 
```
Attached a proxy and observed the header making it out.
> Add user-agent header to Solana rust client requests

- Cargo.lock
- cli/Cargo.toml
- client/Cargo.toml
- core/Cargo.toml
- download-utils/Cargo.toml
- install/Cargo.toml
- metrics/Cargo.toml
- notifier/Cargo.toml
- programs/bpf/Cargo.lock
- rpc-test/Cargo.toml
Are you feeling **SQUEEZED**? Has life got you in a **VICE**? Is the **PRESSURE** getting to you? Well _SQUEEZE BACK_!
JSON is a _terrible_ wire format, full of redundant markup and waste. The easiest mitigation for this is to employ a wire _compression_ algorithm, like gzip. Savings can be as much as 80%.
Wire compression, however, works better when you turn it on.
* Enable gzip, deflate, and brotli compression in the Solana CLI and Rust client, wherever supported by an RPC provider.
* Actually, just go and enable it everywhere.
* Remove `reqwest` dependency from `core`, where it is – in fact – not used.
This PR doesn't need to be tested, per se, because the implementation of the HTTP header-crafting and response decompression is [already …
> Enable wire compression in Solana CLI and Rust client

- streamer/src/nonblocking/quic.rs
Calling `unwrap` on `oldest_ip` while it's `None` is causing crash.
If the table is empty, or has no valid entry, the value of `oldest_ip` will be `None`.
This is a defensive check to use `oldest_ip` only when it is not `None`. 
Fixes #26263
> Do not unwrap the oldest IP in QUIC connectiont table

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
convert accumulating 2 refs into accumulating 1 ref in slow code during shrink (normal and ancient append vec).
Fixes #
> load_accounts_index_for_shrink uses &item instead of (&item.0, &item.1)

- runtime/src/nonce_keyed_account.rs
- sdk/src/transaction_context.rs
Spin-off from #25899. Both kinds of `LamportsError` are turned into `InstructionError::ArithmeticOverflow` anyway. See https://github.com/solana-labs/solana/blob/39ca788b9562d67daaef657371c9d5330063f068/sdk/program/src/lamports.rs#L16
- Simplifies `BorrowedAccount::checked_add_lamports()` and `BorrowedAccount::checked_sub_lamports()`.
- Removes `.map_err(|_| InstructionError::ArithmeticOverflow)?` from `withdraw_nonce_account()`.
> Removes `LamportsError` from `BorrowedAccount`

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
This allows us to begin with [(Pubkey, ...)] and prevent making copies in re-use scenarios of this function.
Fixes #
> AccountsIndex::Scan takes iter

- runtime/src/vote_account.rs
`VoteAccounts::num_staked_nodes` doesn't ensure that the lazily computed `staked_nodes` map has been constructed before returning the length
Ensure that staked nodes is populated before returning length
Fixes https://github.com/solana-labs/solana/issues/26249
> Ensure that staked nodes is populated before returning length

- programs/vote/src/vote_error.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
The `ActiveVoteAccountClose` error was added to `InstructionError` and `ProgramError` instead of `VoteError`
Fix the error
Fixes #
> Fix active vote account close error

- streamer/src/nonblocking/quic.rs
Handling of QUIC stream exit can be improved.
Reference: https://github.com/solana-labs/solana/pull/26116#discussion_r903468164
Close the connection on dropping (pruning) the connection. This will force all corresponding streams to also close. That'll help cleanup the stream faster than waiting for the timeouts.
Fixes #
> Close QUIC connection before dropping the entry

- client/src/http_sender.rs
- web3.js/rollup.config.js
- web3.js/src/connection.ts
RPC providers collect metrics today, but have no way of filtering those metrics by a particular version of the Solana client. This would be useful in identifying regressions (eg. a version of web3.js that's particularly badly behaved) or improvements (eg. a version of the Rust client that reduces load on RPCs).
Added a `solana-client` HTTP header to each request.
Read and followed this guidance: https://www.rfc-editor.org/rfc/rfc6648#page-4
The Rust client changes are a follow-on to #26262 that turned out to be a regrettable decision. In #26262 we added a `user-agent` header. This is fine for Rust/Node, but you _can't_ mess with the `user-agent` header in the browser. You _can_ add your own custom header though, which is what should have been done from the start.
```
cd cli && cargo run …
```
> Add `solana-client` header to client requests

- client/src/nonblocking/quic_client.rs
See #26101. Quic-client currently unwraps certain results. However, all of these results that we unwrap are "infallible" - if they fail we actually have a bug in our code, and it's not the result of external conditions. So these unwraps would be better as expects to help with debugging.
Replace the unwraps with expects.
Fixes #
> Replace unwraps with expects in quic-client to aid debugging

- program-runtime/src/invoke_context.rs
There are three sources of errors in `InvokeContext::process_instruction()`:
- `self.push()`
- The part in between: `self.process_executable_chain()` and `self.verify()` or `self.verify_and_update()`
- `self.pop()`
The `pop` always happens, even if the `push` did not. Thus `InvokeContext::process_instruction()` loses its stack height invariance if the `push` fails.
The only important thing is that the error priority / order is maintained, so that this PR does not need a feature gate. The change to the stack height invariance now being maintained is irrelevant for now, as the stack is not used anymore after an error occurs. Also, the result of `pop` is no longer ignored, but `pop` is guaranteed to return `Ok(())` as it only happens if the preceding `push` succeeded.
> Refactor `push` and `pop` in `InvokeContext::process_instruction()`.

- runtime/src/accounts_db.rs
fn returns an enum, which is better at self documenting, so removing comment
Fixes #
> remove outdated, confusing comment

- web3.js/src/connection.ts
- web3.js/src/util/send-and-confirm-raw-transaction.ts
- web3.js/src/util/send-and-confirm-transaction.ts
A new config param was added that lets you perform API calls while enforcing that the receiving RPC must have proceeded past a given slot. This API needs to be added to web3.js
Fixes #26276.
> feat: add `minContextSlot` configuration to (almost) all web3.js methods

- runtime/src/bank.rs
This error should most likely not have been submitted. It is a corner case of rent collection ranges. I spent some time experimenting and thinking about the new inverse function. I think all is well. I am concerned that these 'no-op' ranges do include a single pubkey value. Is it possible to have a pubkey at that value? Yes. Likely? No. Dangerous? Probably not?
I did get a report from @steviez that we're seeing this error go off after epoch boundaries. I'm not sure why yet. But, doesn't seem 'wrong'.
Fixes #
> remove noisy and useless 'error!' and add test

- core/src/retransmit_stage.rs
`slot_stats` are submitted at a different cadence from the rest of
`RetransmitStats`. Current code erroneously clears `slot_stats` before
submitting any metrics.
stop dropping slot_stats when submit retransmit stats.
> patches bug in retransmit stats where slot stats are erroneously dropped

- runtime/src/bank.rs
- runtime/src/stakes.rs
- runtime/src/vote_account.rs
`VoteAccounts` uses `std::sync::{RwLock, Once}` to lazily compute and cache
`staked_nodes`:
https://github.com/solana-labs/solana/blob/032bee13a/runtime/src/vote_account.rs#L89-L104
`RwLock` overhead is unnecessary for this purpose.
This commit instead switches to using `once_cell::sync::OnceCell` which
provides this exact intended functionality by design.
> removes RwLock+Once in favor of OnceCell in caching staked-nodes

- cli-output/src/cli_output.rs
when numbering the output of `solana validators`, line numbers to not respect `--reverse`
respect reverse
> cli: make `solana validators` line numbering respect sort reversal

- runtime/src/accounts_background_service.rs
- runtime/src/accounts_background_service/stats.rs
There are not top-level stats for the Accounts Background Service. Specifically, how long it takes to run each iteration.
Add stats.
> Add stats for Accounts Background Service

- core/src/unprocessed_packet_batches.rs
- program-runtime/src/compute_budget.rs
- program-runtime/src/invoke_context.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
The tx wide compute cap has been enabled for a while on mainnet:
`5ekBxc8itEnPv4NzGJtr8BVVQLNMQuLMNQQj7pHoLNZ9 | active since epoch 313  | 135216004       | transaction wide compute cap` and should be cleaned up from the master branch
Cleanup
Fixes #
> cleanup feature: tx-wide-compute-cap

- core/benches/cluster_nodes.rs
- core/benches/retransmit_stage.rs
- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/cluster_nodes.rs
- core/src/packet_hasher.rs
- core/src/retransmit_stage.rs
- core/src/window_service.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
Fully deserializing shreds in window-service before sending them to
retransmit stage adds latency to shreds propagation.
This commit instead channels through the payload and relies on only
partial deserialization of the few required fields: slot, shred-index,
shred-type.
> skips shreds deserialization before retransmit

- ledger/src/blockstore.rs
Remove `pub` keyword from unit tests as they are not needed
> Removing pub keyword from blockstore unit tests

- client/src/rpc_custom_error.rs
- web3.js/src/connection.ts
- web3.js/src/errors.ts
An RPC can fail for a variety of reasons, like you having asked for a minContextSlot that the RPC hasn't processed yet. The errors that we throw don't contain that information.
* Create an error class to encapsulate an RPC error `code`, `data`, and a message.
* Search for every instance of `if ('error' in` and replace the thrown `Error` with the new custom one.
> feat: web3.js RPC errors now hold the error `code` and `data` on the error object

- web3.js/src/connection.ts
maxRetries was stripping when it was set to 0. 
I followed steveluscher's proposition and set the AND statement to check for null and not falsey. The commit makes the `maxRetries` in parallel structure with the `minContextSlot` IF statement below it!
Fixes #26295
> Update connection.ts, maxRetries no longer strips

- ledger/src/bigtable_upload_service.rs
When a node with a BigtableUploadService starts from a snapshot with a fresh ledger, it can get stuck on the error `bigtable: upload_confirmed_blocks: Ledger has no slots from 0 to XXX` and never upload blocks until it is rebooted. This is because the BigtableUploadService only checks `Blockstore::get_first_available_block()` once when the service is booted, and the first available block is always zero until the node makes it's first post-snapshot root.
Recheck `Blockstore::get_first_available_block()` if no blocks were uploaded and the BigtableUploadService's start_slot remains zero
Fixes #26080
> BigtableUploadService: recheck first_available_block

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
`_buildArgs` is dumb and always adds the connection's default commitment. Problem is, some API calls _don't take a commitment param_. When you send them one, they break.
* Create a sigil for use with `_buildArgs` that tells it not to override the commitment.
Fixes #26372.
> fix: `getPerformanceSamples` no longer breaks when the connection has a default commitment

- ledger/src/blockstore_processor.rs
- runtime/src/bank.rs
ledger-tool does an accounts hash after halt-at-slot
This is very useful for debugging.
However, if the halt-at-slot is not a root, then it will produce a cap mismatch (and the wrong hash) to report hash calc results that are associated with a non-root, when accounts hash is actually calculated based on the previous rooted slot. This wastes time debugging.
Find the parent bank that is a root and report results on that slot.
Fixes #
> prevent ledger tool from calculating hash on non-rooted slots

- ledger-tool/src/main.rs
Ledger tool is a useful tool for perf improvements.
It is helpful to have an overall execution time ball park # reported.
```ledger tool total execution time took 327.6s```
Fixes #
> add info to ledger tool for total execution time

- banking-bench/src/main.rs
- core/benches/banking_stage.rs
- core/src/banking_stage.rs
- core/src/cluster_info_vote_listener.rs
- core/src/fetch_stage.rs
- core/src/replay_stage.rs
- core/src/tpu.rs
- core/src/tvu.rs
- core/src/validator.rs
- core/src/voting_service.rs
- core/src/warm_quic_cache_service.rs
- poh/src/poh_recorder.rs
- poh/src/poh_service.rs
- rpc/src/cluster_tpu_info.rs
- rpc/src/rpc_service.rs
A lot of read-only access to `PohRecorder`.
`Mutex` will cause redundant lock contention.
Replaced `Mutex<PohRecorder>` with `RwLock<PohRecorder>`.
> uses RwLock<PohRecorder> instead of Mutex<PohRecorder>

- sdk/src/feature_set.rs
- sdk/src/secp256k1_instruction.rs
Missing privkey for 8aXvSuopd1PUj7UhehfXJRg6619RHp8ZvwTyyJHdUYsj
Add a 2nd key to enable on mainnet.  devnet and testnet will remain activated
Fixes #
> Missing privkey, add 2nd feature key

- storage-bigtable/src/lib.rs
It's possible to get few blocks with `get_confirmed_blocks_with_data` but there is no method for get few transactions.
Add `LedgerStorage::get_confirmed_transactions` to `solana-storage-bigtable`.
> Add `get_confirmed_transactions` to `storage-bigtable`

- core/src/accounts_hash_verifier.rs
help track down cap mismatch in accounts hash calc by running hash calc again prior to asserting failure
Fixes #
> add 2nd pass at hash calc when failure seen

- validator/src/main.rs
this could also be deleted. The more surgical change is to just hide the parameter. The original intent was to make disk index default, but that got cancelled.
Fixes #
> 1.10 only: hide confusing cli option

- runtime/src/accounts_db.rs
when we moved accounts hash calc into accounts hash verifier, we stopped calling `mark_old_slots_as_dirty` during hash calc. This was a stop gap measure to help us clean up old slots correctly. We could identify 'old' slots each time we were gathering slots for accounts hash calc, so it is easy to mark them for cleanup then.
Fixes #
> move mark_old_slots_as_dirty to be called from ahv

- runtime/src/snapshot_utils.rs
when tracing all callers of a function, it is helpful to know that these functions are not called at runtime.
Fixes #
> update comment for the next weary traveller

- banking-bench/src/main.rs
- core/benches/banking_stage.rs
- core/benches/unprocessed_packet_batches.rs
- core/src/banking_stage.rs
- core/src/forward_packet_batches_by_accounts.rs
- core/src/leader_slot_banking_stage_metrics.rs
- core/src/leader_slot_banking_stage_timing_metrics.rs
- core/src/lib.rs
- core/src/tpu.rs
- core/src/unprocessed_packet_batches.rs
- runtime/src/cost_tracker.rs
from #23211: `keep filling account buckets and forward each bucket to the next leader to avoid starving accounts on forwards. As the account buckets are filled with CUs, forwards should start sending txs from multiple accounts, not just the one with the highest fees. Naive implementation would forward highest paid TXs first, which are likely to be only for a single hot account. Otherwise a single congested market with a ton of demand will saturate the forward queues.`
- using requested_cu from `compute_budget` for transaction cost (instead of using estimated cost);
- add `forward_packet_batches_by_account` to group transactions to "account buckets" in fee priority
- forward block of transactions (grouped by account buckets)
Fixes
> forward packets by prioritization in desc order

- core/src/retransmit_stage.rs
- core/src/sigverify_shreds.rs
- core/src/tvu.rs
- core/src/window_service.rs
With recent patches, window-service recv-window does not do much other
than redirecting packets/shreds to downstream channels.
The commit removes window-service recv-window and instead sends
packets/shreds directly from sigverify to retransmit-stage and
window-service insert thread.
> bypasses window-service stage before retransmitting shreds

- cli/src/program.rs
- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/stake/src/stake_state.rs
- programs/vote/benches/process_vote.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
Spin-off from #25899.
Adds these two properties to `TransactionContext`:
- `total_resize_limit`: Maximum number of bytes which can be allocated in this transaction (measured at the beginning of the transaction).
- `total_resize_delta`: Negative bytes numbers mean the total allocation decreased, positive bytes numbers mean it increased.
Also adds the method `TransactionContext::get_total_resize_remaining()` which calculates the difference between these two properties.
> Replicates `AccountsDataMeter` in `TransactionContext`

- runtime/src/bank.rs
`nonce_must_be_advanceable ` feature is activated on all clusters and should be cleaned up
> Clean up `nonce_must_be_advanceable` feature

- runtime/src/accounts.rs
- runtime/src/bank.rs
`leave_nonce_on_success ` feature is activated on all clusters and should be cleaned up
> Clean up `leave_nonce_on_success` feature

- runtime/src/accounts_db.rs
The prior startup behavior was to put EVERY slot in the uncleaned_roots HashSet.
Startup improvements led us to skip clean when we were using a locally generated snapshot.
Experiments with high #s of accounts then caused the first time clean ran to oom because EVERY slot would try to load every account into the in-mem accounts index to find duplicates and zero-lamport accounts. So, we skipped adding any slots to uncleaned_roots at startup if the initial clean was going to be skipped. This turned out to be a big problem because some older slots would never make it on the uncleaned_roots list. Therefore, some slots would never be cleaned and allowed to be shrunk or dropped. Most likely there was a cascading effect where because those older slots weren't thrown out, newer slots weren't …
> generating index sets uncleaned_roots correctly

- runtime/src/bank.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/storage.rs
- runtime/src/snapshot_utils.rs
For debugging tools,  we often only need information about epochs like the leader schedule and the epoch stakes. In these cases there's no need to recreate all of AccountsDb to parse this information.
Parse out `BankFieldsToDeserialize` from a given snapshot path via a new `bank_fields_from_snapshot_archives()`.
Fixes #
> Parse snapshot for bank fields

- runtime/src/accounts.rs
test_load_largest_accounts because of the order assumption of the keys
created by new_unique() is broken.
new_unique() does not guarantee the increment order due to the bytes
array storage and its eq-partial trait interpreting the bytes in the
big-endian way.
Sort first to ensure the order before the test.
Fixes #
> Fix the order assumption of the pubkeys created by Pubkey::new_unique()

- cli/src/cluster_query.rs
- cli/src/program.rs
- client/src/nonblocking/rpc_client.rs
- client/src/rpc_filter.rs
- docs/src/developing/clients/jsonrpc-api.md
- rpc/src/rpc.rs
`MemcmpEncodedBytes` has several variants, but since these are serialized as untagged, the only ones actually available to a JSON RPC request are Binary (when sending a string) or Bytes (when sending an array of u8). What we actually want is for users to specify base-58 or base-64 encoding explicitly.
Use serde `into` and `from` tags on `rpc_filters::Memcmp` to emulate adjacent tagging of `MemcmpEncodedBytes`, and turn on explicit `"encoding":"base58"` and `"encoding":"base64"` parameters.
This preserves all current JSONRPC functionality (including the undocumented Bytes handling, eg `"filters":[{"memcmp":{"bytes":[2,0,0,0],"offset":0}}]`), and maps new encoding values to old (or returns an error, in the case of base64) in `solana-client` when querying a node on old software.
This likely …
> Enable base58 and base64 encoding parameters for Memcmp filters

- program-test/src/lib.rs
Another spin-off from #25899.
Uses `BorrowedAccount` instead of `AccountSharedData` in program-test.
> Uses `BorrowedAccount` instead of `AccountSharedData` in program-test.

- runtime/src/bank.rs
`enable_durable_nonce` feature is activated on all clusters and should be cleaned up
> Clean up `enable_durable_nonce` feature

- runtime/src/bank.rs
during refactoring, this metric stopped getting populated
Fixes #
> restore population of 'accounts' metric in rent collection

- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
https://github.com/solana-labs/solana/pull/23844 and https://github.com/solana-labs/solana/pull/25364 added new fields to be serialized in snapshots. Partial backports to v1.10 were added to allow a v1.10 client to consume snapshots produced by newer clients that contain these fields.
However, we also need the `lamports_per_signature` value to be stored in snapshots. If this value isn't stored, we could run into issues when restarting from a snapshot that was taken at a slot where the `lamports_per_signature` value was non-default. If the value isn't stored, we're forced to use the default on restart, and as such, we deviate from consensus immediately. See https://github.com/solana-labs/solana/issues/26069 for more info.
Make v1.10 serialize new fields (default for accountsdb / proper …
> Backport writing new fields to snapshot

- runtime/benches/accounts_index.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
bool -> enum for clarity.
And allowing addition of a third option to ignore reclaims while not being cached (such as during shrink)
Fixes #
> introduce UpsertReclaim

- docs/src/terminology.md
Phrase `(0.000001 lamports per compute unit)` can be confused as const value of Compute Unit Price. 
Clarify it as smallest increment value of Compute Unit Price
Fixes #
> Clarify micro-lamports is unit of Compute Unit Price

- client/src/nonblocking/pubsub_client.rs
- client/src/nonblocking/rpc_client.rs
- client/src/pubsub_client.rs
- client/src/rpc_filter.rs
- rpc/src/rpc_pubsub.rs
https://github.com/solana-labs/solana/pull/26437 introduces filter mapping for `getProgramAccounts` RPC requests against older software, but doesn't handle `programSubscribe` pubsub requests.
Add `getVersion` endpoint to rpc_pubsub service
Use `getVersion` to optionally map filters in blocking and nonblocking PubsubClients. Note in the case of the nonblocking PubsubClient, this involves rudimentary general handling of non-subscription pubsub requests. (The blocking client just uses a one-off method.)
> Add Pubsub getVersion, and support programSubscribe filter mapping

- core/src/consensus.rs
- programs/vote/src/vote_state/mod.rs
The transition to the new voting schema has blown up block sizes. `VoteStateUpdate` contains the whole tower which is much larger than the incremental votes.
Create a more compact vote state update. 
1. Change confirmation size to a `u8` as it will never be larger than 32.
2. Given 2 adjacent members of the tower `l0` and `l1`, notice that `l1.slot <= l0.slot + l0.lockout`. Instead of storing this slot, if we store just the offset it can fit in a `u32`
3. If confirmation count is < 15 the offset can fit in a `u16`, as `lockout <= 2^15` and similarly a `u8` for confirmation counts < 7. Split up the tower into 3 and store the offset to the next member.
Fixes #
> Create a more compact vote state update transaction

- cli/src/program.rs
- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/stake/src/stake_state.rs
- programs/vote/benches/process_vote.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
It's not possible to deterministically enforce a cluster-wide global/per-block accounts data size limit within `TransactionContext`. So the code that currently attempts to do that should be removed.
For more context, please see https://github.com/solana-labs/solana/pull/26438#discussion_r916865675 and https://github.com/solana-labs/solana/issues/26439.
Remove `get_total_resize_remaining()` and `total_resize_limit` from `TransactionContext`.
> Remove `get_total_resize_remaining()` and `total_resize_limit` from `TransactionContext`

- Cargo.lock
- frozen-abi/Cargo.toml
- frozen-abi/macro/Cargo.toml
- programs/bpf/Cargo.lock
- sdk/program/Cargo.toml
- zk-token-sdk/Cargo.toml
Indirect dependency packages introduce variations in features of other
dependencies, which affect the fingerprints of previously built
packages such as solana-program and cause redundant rebuilds of
affected packages.  These changes specify several features in
dependencies specifications explicitly to a common set of
features. The result of such consolidation is improved re-usability of
previously built binary packages across programs/bpf/rust/ packages
when these packages are built in CI jobs.
Fixes #25765
> Consolidate dep features in Cargo.toml files to minimize rebuilds

- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/expected_rent_collection.rs
- runtime/src/rent_collector.rs
- sdk/src/feature_set.rs
https://github.com/solana-labs/solana/pull/22292 prevents rent paying account creation going forward. As a result
`rent_epoch` field for rent exempt accounts is redundant, and advancing
this field will incur expensive account rewrites and cause discrepancy
between accounts-db and cached vote/stake accounts.
This commit adds a feature which upon activation preserves `rent_epoch`
field for rent exempt accounts so that the field is frozen and is no
longer advanced.
Feature Gate Issue: https://github.com/solana-labs/solana/issues/26509
> preserves rent_epoch for rent exempt accounts

- web3.js/README.md
There's a lot more documentation to this library than many users would see looking at the current README
- Make a dedicated 'Documentation and examples' heading
- Bring the Solana Cookbook (which has more examples than all the other documentation listed in the README) to the top 
- Mention the examples higher up in the README
> Make documentation and examples more prominent in README

- scripts/cargo-fmt.sh
9425478 broke paths referenced in `scripts/cargo-fmt.sh`, which is presently decoupled from CI
update them
NOTE: backport not necessary, 9425478 is only in master
> update `scripts/cargo-fmt.sh` to  reflect changes in 9425478

- gossip/src/cluster_info.rs
`PruneData::signable_data` redundantly clones inner fields, while only
references suffice:
https://github.com/solana-labs/solana/blob/d1370f2c7/gossip/src/cluster_info.rs#L219-L233
Use references instead of cloning.
> removes redundant clone in gossip PruneData::signable_data

- runtime/src/bank.rs
redundantly the feature activation is checked repeatedly for each account.
moved check for feature activation out of accounts loop
> moves check for feature activation out of accounts loop

- core/tests/snapshots.rs
- ledger/src/blockstore_processor.rs
- runtime/src/bank.rs
- runtime/src/snapshot_utils.rs
This allows passing info to accounts db and accounts index at startup time for testing new features.
Fixes #
> add accounts db config to bank tests

- core/src/accounts_hash_verifier.rs
I incorrectly put the 2nd run only on the test branch as opposed to lamports mismatch branch.
Fixes #
> do this right: add 2nd pass at hash calc when failure seen (#26392)

- bucket_map/src/bucket.rs
- core/src/banking_stage.rs
- core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- core/src/commitment_service.rs
- core/src/optimistic_confirmation_verifier.rs
- core/src/repair_weight.rs
- core/src/replay_stage.rs
- core/src/sigverify.rs
- core/src/unfrozen_gossip_verified_vote_hashes.rs
- entry/src/poh.rs
- gossip/src/epoch_slots.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
- local-cluster/tests/local_cluster.rs
- metrics/src/metrics.rs
- poh/src/poh_recorder.rs
- rpc/src/rpc.rs
- runtime/src/accounts_db.rs
- runtime/src/append_vec/test_utils.rs
- runtime/src/bank.rs
- runtime/src/in_mem_accounts_index.rs
- runtime/src/rolling_bit_field.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/shared_buffer_reader.rs
Almost all instances should be replaced by `std::mem::{take,replace}`,
or plain assignment.
removed erroneous uses of `std::mem::swap`.
> removes erroneous uses of std::mem::swap

- explorer/src/components/account/UpgradeableLoaderAccountSection.tsx
- explorer/src/components/common/VerifiedBadge.tsx
Add "(experimental)" and use a neutral badge instead of a green one.
The current iteration of verifiable builds does not come with
particularly strong guarantees - best to avoid giving users
any false sense of security.
It relies on an unaudited third party service independent of the explorer,
and the nature of Cargo's build process means it is hard to make strong
claims about the resulting artifacts.
(CC @CherryWorm, who brought this up)
> explorer: mark verifiable builds as experimental

- core/src/unprocessed_packet_batches.rs
It seems unnecessary to prioritize packets by sender stake on top of transaction's compute-unit price, due to: 
1. Quic stake weight part already giving priority to highly staked senders;
2. When compute-unit price is widely adapted, due to micro-lamport as its unit, it is very unlikely enough transactions have same priority; makes adding sender stake into MinMaxHeap ordering unnecessary;
therefore it makes sense to remove sender stake from MinMaxHeap ordering to save some computing and simplify code a bit.
Remove sender-stake from MinMaxHeap ordering.
Fixes #
> Remove sender stakes from banking_stage buffer prioritization

- Cargo.lock
- Cargo.toml
- programs/bpf-loader-tests/Cargo.toml
- programs/bpf-loader-tests/tests/common.rs
- programs/bpf-loader-tests/tests/extend_program_data_ix.rs
- programs/bpf_loader/src/lib.rs
- sdk/program/src/bpf_loader_upgradeable.rs
- sdk/program/src/loader_upgradeable_instruction.rs
- sdk/src/feature_set.rs
- transaction-status/src/parse_bpf_loader.rs
Developers need to pre-allocate large program data accounts because those accounts cannot be resized. Once program byte code gets too large, programs cannot be upgraded anymore.
Add a feature gate to enable a new `ExtendProgramData` instruction which is permission less and allows extending the program data by a specified number of bytes.
Note that this instruction will extend the program data without updating the executors cache. My understanding is that elf deserialization won't be affected by trailing zeroes so this should be safe to do.
Resizing is permission-less so that it can more easily be performed without CPI for multisig or dao controlled programs which would otherwise need to resize via CPI.
Fixes #
Feature Gate Issue: https://github.com/solana-labs/solana/issues/26385
> Allow extending upgradeable program data account length

- ledger/src/blockstore_processor.rs
blockstore_processor can't do anything when the starting_slot is missing. This log might help user realize that their snapshot slot does not fall within the range of slots in blockstore (ie when manually assembling ledger `solana-ledger-tool verify`)
> Add log for missing start_slot in blockstore_processor

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
report_rocksdb_read_perf() always uses the hard-coded operation name "get"
As we will add a new read operation -- multi_get(), report_rocksdb_read_perf()
needs to have an input parameter for operation name.
> Make report_rocksdb_read_perf() to take a operation name.

- runtime/src/accounts_db.rs
When we overflowed an ancient append vec, we would fail to combine some accounts into the old or new ancient append vec. So, those accounts disappeared. That causes cap mismatches in hash calculation.
Fixes #
> ancient append vec: reuse AccountsToStore

- runtime/src/accounts_db.rs
zero lamport accounts show up as owing rent, but they are not going to have rent collected from them. So, ignore them.
Fixes #
> do not count 0 lamport accounts as rent-paying

- program-runtime/src/invoke_context.rs
In #25882 this now dead code was supposedly forgotten. Seems like it went undetected because it uses itself.
Removes `prev_account_sizes` from `InvokeContext::native_invoke()`.
> Cleanup: Removes `prev_account_sizes` from `InvokeContext::native_invoke()`

- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
Define PERF_METRIC_OP_NAME_PUT and PERF_METRIC_OP_NAME_WRITE_BATCH
to replace repetitive / hard-coded operation names for report_rocksdb_write_perf.
> Create const &strs for rocksdb perf write operation names

- ledger/src/blockstore.rs
- ledger/src/blockstore_options.rs
Blockstore::blockstore_directory() function takes a ShredStorageType and returns a path.
As it's a ShredStorageType related function, moving it under ShredStorageType as a
member function is a better fit.
In addition, as we start doing automatic shred compaction type selection under ledger-tool,
it becomes more convenient to reuse the function and const under blockstore_options
namespace instead of blockstore.
> Move Blockstore::blockstore_directory() to ShredStorageType

- runtime/src/accounts_db.rs
this can avoid a trip through `handle_reclaims`
When we're doing shrink, we know that the entire original append vecs should be recycled or dropped.
We don't need to reduce their count to 0. When all Arc::strong_counts are removed, the append vec can be recycled or deleted.
So, a background hash calculation using the old append vec remains valid for hash calculation.
Keep track of stores that are shrunk and mark for drop all stores that were shrunk, independent of their count. Subsequent prs will stop calling `HandleReclaims` in shrink paths.
Fixes #
> shrink stores by id

- sdk/cargo-build-bpf/src/main.rs
cargo-build-bpf if started from cargo may run a wrong (non-BPF capable) rust compiler.
Remove RUSTC var from cargo-build-bpf environment
Fixes #26583
> Prevent cargo from running a non-BPF compiler for BPF target

- ci/test-stable.sh
Follow up #26369
Check that build log doesn't contain redundant rebuilds of solana-program package. If it does report a regression in build efficiency due to dependency package features triggering redundant rebuilds.
> Add a check for rebuild regression due to dep features in cargo tomls

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/bank.rs
- runtime/src/lib.rs
- runtime/src/rent_paying_accounts_by_partition.rs
- runtime/src/serde_snapshot.rs
The specific accounts that can possibly be rent-collecting will be known at load from snapshot time.
We can efficiently build a read-only Vec<Pubkey> per rent collection partition at startup generate_index(). We can use that to iterate the rent-paying pubkeys per partition. This avoids us having to scan account index by pubkey range in bank freeze. There will be an average of 3 accounts per root (assuming no skipped slots) from which we need to collect rent. I have a pr I'm building now to get this ready. Once we stop rewrites, we can improve performance and decouple some things and get rid of account index pubkey sorting by using this rent-paying read-only data structure.
https://discord.com/channels/428295358100013066/943609352068145162/995055464654049311
Fixes #
> handle rent paying accounts differently

- rpc/src/rpc.rs
For a newly created stake account, `getStakeActivation` returns `StakeActivationState::Inactive` with an `inactive` amount equal to the number of lamports held by the stake account, minus the rent exempt reserve.
However for a fully deactivated stake account, `getStakeActivation` returns `StakeActivationState::Inactive` with an `inactive` amount equal to the number of lamports in the previously active delegation. This is wrong because the user may have deposited or withdrawn lamports from the account since it was deactivated, and is inconsistent with the result returned for newly created stake accounts.
Likewise `StakeActivationState::Deactivating` could return an incorrect amount of `inactive` stake due to user deposits or withdrawals
> rpc: getStakeActivation now correctly returns the inactivate lamports for deactivat{ed,ing} stake account in all cases

- web3.js/package.json
- web3.js/rollup.config.js
- web3.js/src/__forks__/react-native/fetch-impl.ts
- web3.js/src/connection.ts
- web3.js/src/util/__forks__/react-native/url-impl.ts
- web3.js/src/util/makeWebsocketUrl.ts
- web3.js/src/util/url-impl.ts
- web3.js/yarn.lock
React Native has a kneecapped `URL` implementation, and uses a browser-like `fetch` API. For web3.js to work in React Native we need to supply forks/polyfills.
* Create a fork of the URL impl for use in React Native
* Use the same `fetch` fork as we do for browsers
* Convince the build system to build a React Native bundle.
> fix: fork `URL` and `fetch` for React Native in web3.js

- client/src/nonblocking/quic_client.rs
- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
QUIC server/client don't use ALPN
Sets solana-tpu ALPN protocol identifier for QUIC server and client.
Fixes #
Rebased version of #26176
> Set solana-tpu ALPN protocol ID

- program-test/src/lib.rs
- web3.js/src/address-lookup-table-program.ts
- web3.js/src/index.ts
- web3.js/test/address-lookup-table-program.test.ts
Web3 TypeScript bindings were missing for Address Lookup Table Program. This PR adds the appropriate client bindings to generate instructions needed to interact with the said program.
* Adds bindings to all of the instructions provided by the Address Lookup Table program
* Adds the correct layouts for instruction data serialization and deserialization
Fixes [#3294 on Solana Program Library](https://github.com/solana-labs/solana-program-library/issues/3294)
Proudly contributed by the worthless pixels, an NFT project full of die hard solana maxis. Wen arb bot? @worthlesspixels on Twitter.
> Address Lookup Table Program Web3 Bindings

- sdk/cargo-build-sbf/src/main.rs
- sdk/cargo-test-sbf/src/main.rs
As we evolve SBF, there needs to be a way to select which version to build for.
Add `--arch` option that can be used to select SBF version. Currently `sbf` and `sbfv2` are supported.
See https://github.com/solana-labs/llvm-project/pull/26
> cargo-build-sbf, cargo-test-sbf: add --arch option

- rpc-test/tests/rpc.rs
`test_rpc_slot_updates` fails if `SlotUpdate::Completed` is received after
`SlotUpdate::Frozen`:
https://github.com/solana-labs/solana/blob/dcfd823ca/rpc-test/tests/rpc.rs#L198-L228
However, `SlotUpdate::Completed` is sent asynchronous to banking-stage and
replay when shreds are inserted into blockstore. When the leader
generates blocks, replay may freeze the bank before shreds are all
inserted into blockstore; and so `SlotUpdate::Completed` may be received
_after_ `SlotUpdate::Frozen`.
The commit removes the ordering check for SlotUpdate::Completed.
> patches flaky test_rpc_slot_updates

- sdk/bpf/c/inc/sol/string.h
The compiler issues a warning every time I compile using the Solana C SDK.  Also I am pretty sure that if anyone tried to use the return value of sol_memset, they would experience an error.  The man page for memset says the return value should be:
"The memset() function returns a pointer to the memory area s."
Given the prototype:
void *memset(void *s, int c, size_t n);
Return the correct value.
Fixes #
> Fix sol_memset to return the correct value.

- sdk/program/src/pubkey.rs
The message kitchen sink test assumes that unique pubkeys are always greater than previously created unique pubkeys but this assumption breaks as soon as the static counter goes from 255 to 256:
Key 255: `JAQxrJ2WuDF4APfSifurJJ4HzV5Z3FyBuBeSMj7mo9aw` (encoded as [255, 0, ..])
Key 256: `1tJ93RwaVfE1PEMxd5rpZZuPtLCwbEaDCrNBhAy8Cw` (encoded as [0, 1, ..])
Failing CI test: https://buildkite.com/solana-labs/solana/builds/77855#0181f45d-f09d-4b0d-ba22-ff33b632cb5b
Use big endian encoding for unique pubkeys generated from the static counter
Fixes #
> Fix flaky message kitchen sink test

- ci/test-stable.sh
- sdk/cargo-build-bpf/src/main.rs
- sdk/cargo-build-sbf/src/main.rs
- sdk/cargo-test-bpf/src/main.rs
- sdk/cargo-test-sbf/src/main.rs
Switching to SBF breaks 3rd party projects that rely on target_arch being "bpf".
Depending on the arch command line option compile for either sbf or bpf target.
Fixes #26485
> Compile for bpf target for compatibility when cargo-build-bpf is used

- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
`solana-test-validator` has a flag for loading accounts from local files (`--account <ADDRESS FILENAME.JSON>`), but the `ADDRESS` value is silently ignored since as it's actually read from the specified file
https://github.com/solana-labs/solana/blob/e3d1fe52a26bc00ad376d6884f9d743c00814ccd/test-validator/src/lib.rs#L320
Use the `ADDRESS` value, or read it from the file if `-` is passed (`--account - FILENAME.JSON`)
> test-validator: use or skip ADDRESS value from account flag

- cli/src/program.rs
- ledger/src/blockstore_processor.rs
- program-runtime/src/invoke_context.rs
- program-test/src/lib.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls.rs
- programs/stake/src/stake_state.rs
- programs/vote/benches/process_vote.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/feature_set.rs
- sdk/src/transaction_context.rs
This is a continuation of #25380.
Currently, for BPF programs the verification cost is:
- One data copy from `AccountSharedData` to create or update the `PreAccount`
- One data copy from the BPF program into the `AccountSharedData` so we can compare it against `PreAccount`
- The actual comparison in `PreAccount` (this is skipped if the data is allowed to be modified)
Assuming that copies and comparison incur a similar cost (as they both need to access two different pointers, polluting the data cache), we could reduce this cost by 50% up to 66% for every account in every ABIv0 and ABIv1 BPF program executed. Built-in programs would also profit, reducing their verification cost by almost 100%. In ABIv2 BPF programs will be like built-in programs in this regard.
This PR introduces the …
> Feature: Early verification of account modifications in `BorrowedAccount`

- programs/bpf_loader/src/lib.rs
The `reduce_required_deploy_balance` feature is activated on all clusters and should be cleaned up
> Clean up activated `reduce_required_deploy_balance` feature

- core/src/replay_stage.rs
- core/tests/snapshots.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- rpc/src/rpc_health.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/lib.rs
- runtime/src/verify_accounts_hash_in_background.rs
- test-validator/src/lib.rs
- tokens/src/commands.rs
Hash calc looks like it takes around 43s on startup of validator.
start accounts hash calc in bg on snapshot load. Wait until initial hash is verified before voting can occur.
Fixes #
> async hash verify on load

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
When shrinking, we don't need `update_index` to call `handle_reclaims`. This is unnecessary work. We know that the existing index entries at the slots we're updating are to the append_vec(s) we're shrinking away, so we don't need to go through the work of updating the count and status per pubkey we write into the new append vec. This also means that the accounts index can handle this update asynchronously since there are no longer return values from `upsert`
Fixes #
> shrink stops using HandleReclaims

- core/src/forward_packet_batches_by_accounts.rs
- core/src/lib.rs
- core/src/transaction_priority_details.rs
- core/src/unprocessed_packet_batches.rs
To share function of getting priority details (eg, compute-unit price, requested compute-units) from `SanitizedVersionedTransaction` and/or `SanitizedTransaction`. 
Add trait `GetTransactionPriorityDetails`, implemented for above transaction types.
Fixes #
> Share function to get priority details from various transaction types

- streamer/src/nonblocking/quic.rs
unchecked math can overflow
Remove unchecked math from the quic chunk handler. These values are checked earlier so this should not be an issue but better to have checked math for future refactoring and safety.
Fixes #
> Remove some unchecked math from the quic chunk handling

- client/src/mock_sender.rs
- client/src/nonblocking/rpc_client.rs
- client/src/rpc_client.rs
- client/src/rpc_request.rs
- docs/src/developing/clients/jsonrpc-api.md
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- rpc/src/rpc.rs
There is not an RPC method to get the stake minimum delegation.
Add one 😊
Fixes #24690
> Add RPC getStakeMinimumDelegation

- .buildkite/hooks/post-command
- .buildkite/hooks/pre-command
- ci/docker-run.sh
related to #26171 
sccache config has setup on buildkite-agent server. This PR is only for
- remove old cache mechanism
- trigger sccache in docker container
> chore: use sccache

- sdk/bpf/c/inc/sol/return_data.h
C SDK syscall `sol_get_return_data` incorrectly declares a const pointer for the first function argument, although the syscall actually writes data to it.
```diff
-typedef uint64_t(*sol_get_return_data_pointer_type)(const uint8_t *, uint64_t, SolPubkey *);
+typedef uint64_t(*sol_get_return_data_pointer_type)(uint8_t *, uint64_t, SolPubkey *);
```
Fixes #
> sdk/bpf/c: fix sol_get_return_data signature

- runtime/src/ancient_append_vecs.rs
smaller ancient append vec sizes cause us to have more ancient append vecs. It also means fewer account writes are required to result in shrinking ancient append vecs. The goal is to cause the ancient append vec code to run more often to look for bugs.
Fixes #
> temporarily make ancient append vecs 10x smaller to find intermittent bugs

- client/src/client_error.rs
- client/src/connection_cache.rs
- client/src/nonblocking/quic_client.rs
- validator/src/lib.rs
The GHSA-x236-qc46-7v8j advisory needs to be patched for v1.10 for Quic support. With Quic enabled a peer that has a UDP tpu_port above U16::MAX - QUIC_PORT_OFFSET can cause an overflow when adding QUIC_PORT_OFFSET to it in order to obtain the corresponding Quic tpu_port. 
Backport fix for GHSA-x236-qc46-7v8j, in order to force nodes to set their UDP tpu_ports such that adding QUIC_PORT_OFFSET will not cause an overflow, and, when encountering a remote peer which does have a UDP tpu_port that is too large (e.g. due to not having yet upgraded), avoid the overflowing addition, and simply fall back on UDP.
Fixes #
> Backport ghsa x236 qc46 7v8j

- runtime/src/snapshot_utils.rs
Previously, we created a generic `reader` closure which we then immediately created a SharedBuffer from. This seemed much more complicated than it needs to be.
Create the SharedBuffer in archive_format match directly and pass that into `unpack_snapshot_local`. Removes the need for `untar_snapshot_file`.
Fixes #
> Add helper fn to create shared buffer - simplify archive format matching

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
This used to be the main accounts index lock. Now everyone is happy with a read lock to get an immutable reference. Thus, we don't need a lock at all.
Fixes #
> get rid of rwlock per bin in accounts index

- runtime/src/snapshot_utils.rs
#26674 added this helper function, but we don't need it to be wrapped in a `Result`.
Remove the `Result`, and `?` where used
Fixes #
> untar_snapshot_create_shared_buffer doesn't need to return a result

- programs/bpf/benches/bpf_loader.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- sdk/program/src/entrypoint.rs
- sdk/program/src/instruction.rs
- sdk/src/feature_set.rs
- storage-proto/proto/transaction_by_addr.proto
- storage-proto/src/convert.rs
BPF programs can only correctly deserialize up to 255 instruction accounts but the bpf loader doesn't enforce that yet.
- Add a feature gate to start enforcing that no more than 255 accounts can be passed to a bpf program instruction
Feature Gate Issue: https://github.com/solana-labs/solana/issues/26628
> Cap the number of accounts passed to a bpf program ix

- runtime/src/accounts_index.rs
no need to clone arc just to read refcount
use ref to entry to get refcount
Fixes #
> AcctIdx: ref_count_from_storage remove Arc::clone

- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
although it is possible to load multiple accounts via 
> `$ solana-test-validator --account - file.json --account - another_file.json ...`
it quickly becomes very cumbersome when the number of accounts is high
add the flag `--account-dir <DIRECTORY>` that finds all json files in the specified directory, and loads them as accounts
> test-validator: add account-dir flag

- core/src/tpu.rs
- core/src/validator.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
QUIC disabled because of security issues
This reverts commit a5f290a66f10a25e0c3ee004a1fcd2889eca2785.
Fixes #
> Revert "core: disable quic servers on mainnet-beta"

- core/src/transaction_priority_details.rs
- program-runtime/src/compute_budget.rs
- runtime/src/bank.rs
Feature `J2QdYx8crLbTVK8nur1jeLsmc3krDbfjoxoea2V1Uy5Q` was enabled in epoch 327 but featurization still exists
Cleanup feature
Fixes #
> cleanup feature: default units per instruction

- core/src/system_monitor_service.rs
UDP stats derived from `/proc/net/snmp` currently use usize, but the actual type from `net-procfs.c` library is u64 and values could become large enough to exceed 32-bit unsigned int
Switch from using usize to using u64
> Switch UDP stats from usize to u64

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- runtime/src/message_processor.rs
- sdk/src/transaction_context.rs
Feature `3aJdcZqxoLpSBxgeYGjPwaYS1zzcByxUDqJkbzWAH1Zb` is activated on all networks.
Removes `TransactionContext::record_instruction()` and the feature gating.
Marks `TransactionContext::instruction_accounts_lamport_sum()` as non public.
fixes: #24965
> Cleanup: `record_instruction_in_transaction_context_push`

- program-runtime/src/invoke_context.rs
- program-runtime/src/sysvar_cache.rs
- programs/stake/src/stake_instruction.rs
- runtime/src/bank/sysvar_cache.rs
`SysvarCache` explicitly expects `AccountSharedData` even though it only needs `&[u8]` data.
Replaces the callback which returns `AccountSharedData` by a second nested callback which deserializes the data in place. This is a double control-flow back pass, similar to a coroutine.
> Removes `AccountSharedData` from `SysvarCache`.

- core/src/banking_stage.rs
It is not obvious why forwarder stops iterating packet buffer as soon as first packet failed to add to "account buckets".
Add comment 
Fixes #
> Add comment for forwarder buffer iteration behavior

- cli/src/stake.rs
`solana stake-minimum-delegation` does not respect the cli config for output.
Use `CliBalance` to output the stake minimum delegation
Fixes #26698
> cli: Use CliBalance for `solana stake-minimum-delegation` output

- .github/label-actions.yml
- .github/workflows/label-actions.yml
We want to make it as easy as possible for core team members to nudge people over to Stack Exchange when questions that are not issues with Solana itself get posted to GitHub.
* Added a GitHub workflow to comment on and close issues when the `question` tag is added.
> Adding the `question` tag will now auto-close Issues and direct people to post on the Solana Stack Exchange

- cli/src/wallet.rs
`solana balance` does not respect the cli config for output.
Use `CliBalance` to output the balance
To see the output differences, refer to the description in PR #26703.
> cli: Use CliBalance for `solana balance` output

- web3.js/src/connection.ts
> feat: add `maxSupportedTransactionVersion` option to `getBlock` and `getTransaction`

- docs/src/developing/clients/jsonrpc-api.md
The `maxSupportedTransactionVersion` parameter is confusing. Intuition suggests that if the parameter isn't present, all transaction versions will be supported, but this is not the case.
Add a line each usage in RPC docs describing behavior when parameter is not present.
> Update maxSupportedTransactionVersion docs to explain what happens if parameter isn't present

- web3.js/src/connection.ts
Follow on from #26726.
Addresses #26391.
> fix: add `maxSupportedTransactionVersion` config to remaining `getTransaction` calls

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
- web3.js/test/stake-program.test.ts
The PR adds --
1). support for ```getStakeMinimumDelegation``` to web3.js with a test.
fixes #26564
> feat(web3.js): add support for get stake minimum delegation

- explorer/package-lock.json
- explorer/package.json
- explorer/src/providers/transactions/raw.tsx
> fix: use `maxSupportedTransactionVersion` param when getting raw transactions in Explorer

- programs/bpf_loader/src/syscalls/cpi.rs
`serialized_len_ptr` follows the same calculation in the C and the Rust version of CPI.
Merges the two identical calculations of `serialized_len_ptr` to one at the end of the CPI call.
> Removes `serialized_len_ptr` from `CallerAccount`.

- client/src/nonblocking/quic_client.rs
- sdk/src/quic.rs
- streamer/src/nonblocking/quic.rs
The chunking logic was reversed. It was always creating chunks, where each chunk contains 128 transactions. So if a batch had 20,000 transactions, it'll create 157 chunks. For a batch of 100 transactions, it'll create only 1 chunk. 
The batching code will work better if we can create more chunks, so that multiple streams can be used to transmit the transactions in parallel.
This PR reverses the chunking logic. It'll try to create up to `QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS` chunks now. For a 100 transaction batch, it'll create 100 chunks. Any batch with more than `QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS` transactions will have `QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS` chunks.
This change uncovered some issues on the streamer side of code as well.  If the client is a staked node, but doesn't …
> Fix transaction chunking on QUIC batch send

- .github/workflows/release-artifacts.yml
- Cargo.toml
- ci/publish-tarball.sh
See discussion on PR #26555
PR #24196 added `resolver = "2"` to Cargo.toml. That fixed the broken Windows build but is causing other problems (see https://github.com/solana-labs/solana/issues/22603)
* Remove `resolver = "2"` from Cargo.toml
* Add steps to the Windows build that add `resolver = "2"` to the local copy of Cargo.toml immediately before the build.
Fixes #22603
> Remove resolver=2 from Cargo.toml and add it to the Windows build

- ledger-tool/src/main.rs
1. annoying off-by-one in skipped slot count arrow labels
2. rendering 2k+ vote accounts is painfully slow and they're rarely valuable for debugging
1. finally fix it
2. optionally render vote account `--vote-account-mode {disabled, last-only, vote-history}`. off by default
> `solana-ledger-tool graph` improvements

- docs/src/proposals/tick-verification.md
> fix typo: ticck -> tick

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
Implementing the `Display` trait for `AeCiphertext` and `ElGamalCiphertext` structs.
> zk-token-sdk: implement Display for ciphertexts

- explorer/src/components/block/BlockHistoryCard.tsx
Non vote transactions with a single invocation are hidden by the "All Except Votes" filter
|| => &&
Fixes #
> Hide vote txs that don't invoke any other programs like the comment says

- core/src/transaction_priority_details.rs
- program-runtime/src/compute_budget.rs
- runtime/src/bank.rs
This reverts commit 39a34db52a4f545d1f6572e421e0dc43c4edc5ab.
mnb validators are failing with vote errors
Fixes #
> Revert "cleanup feature: default units per instruction (#26684)"

- core/src/banking_stage.rs
- core/src/serve_repair.rs
Repair currently throttles the number of requests made per call to `run_listen()`, but the outbound budget per fixed interval is currently unrestricted
Replace existing throttle on requests in `DynamicPacketToProcessThreshold` with a 12MB outbound limit on all repairs enforced via `DataBudget`
Fixes #
> Enforce a 12MB limit on outbound repair

- web3.js/src/connection.ts
If the websocket _closes_ while there's an active idle timer, the connection can enter a corrupt state as described in #26198.
* Clear the idle timer whenever the websocket connection drops.
Fixes #26665.
> fix: (web3.js) clear the idle timer whenever the websocket closes

- transaction-status/src/token_balances.rs
While the apis in `token_balances.rs` support the new token program_id, they are still using `program_pack::Pack` to unpack the accounts, preventing population of pre-/postTokenBalances for token-2022 transactions.
Jon, I grepped the monorepo for all callers of `unpack()` and it looks like everything else has been updated properly, except `solana-tokens` (not urgent, I think I will handle, but separately).
Also, sorry for missing this!
Add failing test, and fix by importing spl_token_2022 instead, and using `StateWithExtensions` and account `base` information.
> Support spl-token-2022 properly in pre-/postTokenBalances

- runtime/src/bank.rs
ReplayStage tests need to set the bank's accounts data size(s) but cannot.
See https://github.com/solana-labs/solana/pull/26744 for usage.
Add Bank::update_accounts_data_size_delta_off_chain_for_tests()
> Add Bank::update_accounts_data_size_delta_off_chain_for_tests()

- runtime/src/serde_snapshot.rs
#26590 will move this functionality; separating the current functionality into functions so we can just call those directly.
Create helper functions remap_and_reconstruct_storages to remap and reconstruct append vec storages
Fixes #
> Separate remapping append_vecs into functions

- storage-bigtable/src/bigtable.rs
PR #25918 added `HttpConnector` creation.
- By default in `hyper` `nodelay` set to `false`: https://docs.rs/hyper/0.14.19/src/hyper/client/connect/http.rs.html#120
- By default in `tonic` `nodelay` set to `true`: https://docs.rs/tonic/0.7.2/src/tonic/transport/channel/endpoint.rs.html#408
So 25918 introduces `nodelay` changes.
Set `nodelay` to `true` for custom http connector as it previously was.
> bigtable: set_nodelay for http connector

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- account-decoder/src/parse_token_extension.rs
- ci/test-stable.sh
- client/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- rpc/src/rpc.rs
- transaction-status/Cargo.toml
- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/interest_bearing_mint.rs
- transaction-status/src/parse_token/extension/mod.rs
- transaction-status/src/token_balances.rs
SPL token program-2022 has added support for a couple new extensions, but the RPC account and instruction parsers can't yet handle them.
Bump spl-token-2022 to v0.4.1 (@joncinque , any reason not to do this?)
Parse NonTransferable and InterestBearingMint extensions and instructions
> Parse more token-2022 extensions and instructions

- explorer/src/pages/AccountDetailsPage.tsx
Since we take present legacy token-list data over metaplex metadata for ft metadata, legacy token-list tokens can't update their metadata by creating a metaplex metadata account
Wallets also take metadata in this order:
1. Metaplex metadata if exists
2. Otherwise legacy token-list
Make the explorer retrieve metadata the same way wallets do to allow updating metadata on legacy token-list tokens via creating a new metadata account.
> fix: match wallet + dapp ordering with ft metadata on Explorer

- zk-token-sdk/src/zk_token_elgamal/pod.rs
We want to be able to parse ConfidentialTransfer extensions and instructions, but it's not straightforward to print the various fields.
Implement Display for structs used in extension states and instructions
> Add Display implementations for various ConfidentialTransfer pod structs

- runtime/src/hardened_unpack.rs
Used in #26590 - separate enough functionality moving to a new PR.
Adds a new `streaming_unpack_snapshot`, which sends all unpacked entries over a crossbeam channel. Instead of `unpack_snapshot` which collects all accounts files in a hashmap.
Fixes #
> Add streaming_unpack_snapshot to send entry files during unpack

- programs/bpf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
When bank calculates transaction fee, it's hardcoded to not to use default units per instruction, which is a feature already enabled in mainnet-beta. It should use default units. 
Add feature to pass `false` (current behavior) when feature is not enabled, and `true` (desired behavior) when feature is enabled.
Fixes #26785
> Add feature gate to use default units per instruction for fee calculation

- runtime/store-tool/src/main.rs
accounts(0) will allocate memory for all the accounts, we really just want to iterate through them and print
Fixes #
> store-tool use accounts_iter

- core/src/cluster_info_vote_listener.rs
- core/src/verified_vote_packets.rs
Since the new vote updates are no longer incremental, there
is no value in storing intermediate votes.
Only store the latest vote for each validator before sending to banking stage. 
Fixes #
Feature Gate Issue: #24717
> Only take the latest vote for each validator in gossip

- explorer/src/pages/AccountDetailsPage.tsx
Most tokens broken on the explorer
Circle cannot update the metadata because the update authority is a token Multisig account
https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
Same for USDT...
Example of token without an update authority but no uri set so looks broken: https://explorer.solana.com/address/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/metadata
Fall back to tokenDetails if uri is missing and tokenDetails exist
Fixes #
> explorer falls back to token list when uri is blank and tokenDetails exists

- runtime/src/accounts_db.rs
accounts index caching can do much better with the introduction of ancient append vecs. Ancient append vecs are large, multi-slot data structures. They are worth caching all by themselves as opposed to re-scanning every time.
Break the caching range into ancient append vecs, and then 'normal' slots.
Fixes #
> allow caching on ancient append vecs for accounts hash calc

- runtime/src/accounts_db.rs
Under expected situations, we should end up with 1 append vec (the newly shurnk one) after shrinking a slot. In the wild, we are seeing snapshots that contains multiple append vecs (the post-shrunk and pre-shrunk append vecs) included in a snapshot. This is not correct.
inc a counter and log when shrink leaves behind 2 append vecs
Fixes #
> log when shrink still contains extra stores

- core/src/consensus.rs
- core/src/replay_stage.rs
- programs/vote/src/vote_instruction.rs
- programs/vote/src/vote_processor.rs
- runtime/src/vote_parser.rs
- sdk/src/feature_set.rs
- transaction-status/src/parse_vote.rs
Vote state updates are too large and inflate block size.
Create a feature flag and on any serialize / deserialize of vote state updates transform between `CompactVoteStateUpdate`
Builds off of #26092 
Fixes #
Feature Gate Issue: #26617
> Compact vote state updates to reduce block size

- sdk/bpf/scripts/objcopy.sh
- sdk/cargo-build-sbf/src/main.rs
cargo-build-sbf does not generate debug info for release builds.
- When setting `--debug` flag
- Adds the `-g` flag to RUSTFLAGS by default to generate debug symbols ([Rust Reference](https://doc.rust-lang.org/rustc/command-line-arguments.html#-g-include-debug-information))
- Uses `llvm-objcopy --only-keep-debug` to create a `.debug` symbols file adjacent to the `.so` output file. Reference: [GDB: Separate Debug Files](https://sourceware.org/gdb/current/onlinedocs/gdb/Separate-Debug-Files.html#Separate-Debug-Files)
Fixes #
> cargo-build-sbf: support debug info

- cli-output/src/cli_output.rs
```
$ solana validators -n -ul | head -n2
Identity                                      Vote Account                            Commission  Last Vote        Root Slot     Skip Rate  Credits  Version            Active Stake
1   12GxYJMVymf9KsigAqcakWhk774xi4yi19hfPBBmKqhw  CXsSF1ytAddR9rd1CpkArifiZ78xhxXAbAWwoMrWXsZd    0%      12644 (  0)      12613 (  0)   0.02%    12567   1.11.3    999999.997717120 SOL (100.00%)
```
```
$ solana validators -n -ul | head -n2
Identity                                      Vote Account                            Commission  Last Vote        Root Slot     Skip Rate  Credits  Version            Active Stake
1   12GxYJMVymf9KsigAqcakWhk774xi4yi19hfPBBmKqhw  CXsSF1ytAddR9rd1CpkArifiZ78xhxXAbAWwoMrWXsZd    0%      12689 (  0)      12658 (  0)   0.02%    12612 …
```
> Adjust `solana validators -n` header to be correctly aligned with the columns

- cli/src/cli.rs
- cli/src/stake.rs
- cli/src/test_utils.rs
- cli/tests/stake.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- sdk/program/src/stake/instruction.rs
- sdk/src/feature_set.rs
- transaction-status/src/parse_stake.rs
The stake deactivation penalty makes active stake too sticky and causes stake pools to perform poorly. 
#24762 proposes a new stake account format to deal with this problem, but that's a big change. What if we could get most of the way there with something more incremental in the v1.11 timeframe.
Enter the `StakeInstruction::Redelegate` instruction. It works by initializing a new stake account to allow for the re-delegated stake to warm up in parallel to the stake cooling down "virtually" in the original stake account. At the end of the warm-up/cool-down, the original stake account holds rent exempt lamports that can be withdrawn.
This approach does cause the redelegated stake to be double counted towards the per-epoch max warm-up/cool-down rate of 25%. One implication here is that …
> Add StakeInstruction::Redelegate

- programs/stake/src/stake_instruction.rs
As per https://github.com/solana-labs/solana/pull/26294#discussion_r922747616, it's easy to miss the check needed to preserve consensus when adding a new feature-gated stake instruction while `add_get_minimum_delegation_instruction_to_stake_program` is not yet active.
Add explicit comment describing pattern to follow
> Add explicit comment about get_stake_account to StakeInstruction enum

- docs/.prettierrc.json
When making changes to the docs website, prettier auto-formatting may not be enabled in the user's code editor.
This can lead to minor changes discrepancies (like trailing white spaces) that could fail sanity checks from the CI. 
Added a prettier config file to standardize the prettier config settings used when saving the docs website files.
> [docs] added prettier config file

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token_extension.rs
- client/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- transaction-status/Cargo.toml
Parsing apis for spl-token-2022 ConfidentialTransaction extensions are only stubs.
- Flesh out parsing
- Also, bump spl-token-2022 version, and do tedious rollback of Cargo.lock changes from #26746 (in retrospect, I'm not sure why cargo forced that solana v1.11.3 bump on me...)
> Parse ConfidentialTransaction extensions

- client/src/connection_cache.rs
- client/src/nonblocking/quic_client.rs
- core/src/tpu.rs
- core/src/validator.rs
- streamer/src/nonblocking/quic.rs
QUIC client is always chunking transactions with `QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS` as maximum number of chunks. This limits staked clients (e.g. nodes forwarding transactions) on how fast the transactions can be sent.
The following graph is from master branch.
This PR updates client to use the same logic as QUIC streamer to calculate how many transactions can be sent in parallel. The calculation uses client's stake and total stake across cluster. The information is already available on a full validator node. 
The following graph is with this PR
Fixes #
> Compute maximum parallel QUIC streams using client stake

- docs/src/developing/clients/jsonrpc-api.md
Someone was confused why `sendTransaction` accepts a `minContextSlot`, since that's irrelevant from the perspective of making a new transaction.
* Make it clear that the `minContextSlot` option on `sendTransaction` specifies the minimum slot at which _preflight_ checks should be made.
> Make it clear that `minContextSlot` in `sendTransaction` affects _preflight_ checks

- runtime/src/accounts_index.rs
*Relax* Memory Ordering is used for reading and updating ref-counts on AccountEntry. This can lead to inconsistent view of the struct between different threads.
Change memory ordering for read to *Acquire*, for write to *Release*.
Fixes #
> Fix ordering for AccountEntry ref_count

- ledger-tool/src/main.rs
- ledger/src/blockstore_processor.rs
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
when a validator fails with a hash mismatch in accounts hash verifier, we store off the individual account data that was used to calculate the overall hash.
This new option on ledger-tool allows us to save off the individual account data that was used to calculate the final ledger-tool hash. Then, specific different accounts can be identified and debugged to determine why the validator got off course.
Fixes #
> ledger tool verify can store debug info on hash calc

- bench-tps/src/bench.rs
- bench-tps/src/send_batch.rs
Adds function which withdraws durable nonce accounts.
This is part of the series of PRs adding durable nonce accounts to bench-tps: https://github.com/solana-labs/solana/issues/25759
> add withdraw durable nonce

- core/src/ancestor_hashes_service.rs
- core/src/repair_service.rs
- core/src/serve_repair.rs
- core/src/shred_fetch_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- dos/src/main.rs
- gossip/src/ping_pong.rs
- ledger/src/shred/stats.rs
- sdk/src/feature_set.rs
Repair requests should be signed.
- Expand `RepairProtocol` to include new variants with signature support.
- Verify signatures for incoming repair requests.
- Add ping/pong support for the repair port.
- Verify that an incoming request pubkey has completed a succussful ping/pong.
Fixes #26834
> sign repair requests

- rbpf-cli/src/main.rs
`rbpf-cli` doesn't include log in output.
Includes program log (from `sol_log_`) in output.
Fixes #
> rbpf-cli: capture log

- runtime/src/in_mem_accounts_index.rs
I'm about to refactor how we scan for flushing. This option was only there so we could drop each item at a time. This can be done by draining instead.
Fixes #
> use Vec::drain instead of option/take

- ledger/src/blockstore_processor.rs
When using ledger-tool to dump debug info for the accounts hash calculation, the option doesn't work if the snapshot is AT the slot that we want to halt at.
Run the post-hash code if the cli option is specified to dump the debug data.
Fixes #
> --halt-at-slot-store-hash-raw-data works for root bank

- runtime/src/accounts_db.rs
if caching was disabled, `--halt-at-slot-store-hash-raw-data` debug feature wasn't working
Fixes #
> enable accounts hash caching if store_detailed_debug_info_on_failure

- core/src/serve_repair.rs
Repair socket handling processes both ping responses and shred packets. A shred packet with size equal to a ping response can be discarded by ping processing.
When attempting to process ping responses only discard packets which have successfully passed signature verification.
Fixes #
> mark repair ping packets for discard only after successful signature verification

- sdk/program/src/sysvar/recent_blockhashes.rs
This is an unused test function for a deprecated sysvar.
Delete `create_test_recent_blockhashes`.
While this is part of the public API it doesn't seem like something downstream projects would be using and is probably safe to just delete. I am also happy to deprecate it.
Fixes #
> Delete unused create_test_recent_blockhashes

- runtime/src/accounts.rs
This is a doozy for a one-line change.
With  #26479 activated, the rent epoch of accounts is no longer updated. If you start a new cluster (or test validator) with this enabled, there may be some accounts with `rent_epoch = 0`.
When one of those accounts is closed, the runtime thinks it's a new account since its rent epoch is 0, tries to collect rent on it, and cleans up the account in the process.
This is normally OK, but if the account in question is a stake account, the stakes cache will go out of sync and eventually crash the bank during epoch rollover on this assertion: https://github.com/solana-labs/solana/blob/422cff69fdc6e9268020dd52db842c6a0b64a4cd/runtime/src/bank.rs#L2704
Very simply, don't collect rent on newly created accounts if the feature flag from #26479 is enabled. …
> accounts: Don't collect rent on newly created accounts

- runtime/src/accounts_db.rs
Reverts solana-labs/solana#26770
This is causing us to parallel iterate 5M 'ancient' slots. Something is broken.
```
chunks: 5318273 ancient_slot_count: 5318099
```
> Revert "allow caching on ancient append vecs for accounts hash calc"

- ledger/src/shredder.rs
`data_shreds_to_coding_shreds` relies on the hardcoded
`MAX_DATA_SHREDS_PER_FEC_BLOCK` batches of data shreds:
https://github.com/solana-labs/solana/blob/e74ad90cd/ledger/src/shredder.rs#L175-L183
This hardcoded logic is unnecessary since the shreds belonging to the
same erasure batch can be identified from run of the same FEC-set index.
* removed the hardcoded logic.
* infers erasure batches from FEC-set indices of data shreds
> infers erasure batches from FEC-set indices of data shreds

- runtime/src/accounts_db.rs
This causes all slots (including start..first_boundary and last_full_slot_end..max_slot to be included when we dump the debug hash info on mismatch.
Without this, we fail to save some pubkeys that were used to calculate the full hash, if they were in slots at the oldest or newest uneven chunks of the last 432k slots.
Fixes #
> calculate cache hash path for store_detailed_debug_info_on_failure

- core/src/system_monitor_service.rs
- core/src/validator.rs
- ledger-tool/src/main.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
Currently have very limited insight into storage device performance.
Start tracking aggregated metrics from `/proc/diskstats` to understand storage device performance and bottlenecks
> Add IO metrics

- runtime/src/bank.rs
`process_message` function can return a transaction error for either invalid account or invalid instruction. This error gets interpreted in `execute_loaded_transaction` function. However, this match statement only explicitly looks for `TransactionError::InvalidRentPayingAccount` and `TransactionError::InsufficientFundsForRent`. All other errors are assumed to be instruction errors, which could result in inflated instruction error count metrics.
Add a match statement for `TransactionError::InvalidAccountIndex` in `execute_loaded_transaction` function and increment the already existing `invalid_account_index` error counter
> Make tx error accounting more granular

- banking-bench/src/main.rs
- bench-tps/src/cli.rs
- client/src/connection_cache.rs
- dos/src/cli.rs
- multinode-demo/bootstrap-validator.sh
- validator/src/main.rs
* As of v1.10.32 the validator listens for QUIC connections by default
* The validator can forward transactions via quic if run with `--tpu-use-quic`, but doesn't by default
* Switch the default client behavior to use QUIC
* Add argument to disable the quic client
> Enable QUIC client by default. Add arg to disable QUIC client.

- runtime/src/in_mem_accounts_index.rs
Scan in-mem acct idx once every 5 slots, putting items to evict by age into 5 future vecs. As opposed to scanning each bucket each slot.
This shows a 3x improvement on scan time during flush.
Fixes #
> in mem acct idx scan multiple ages simultaneously

- core/src/replay_stage.rs
Spamming warn log with messages like:
`405344:[2022-08-02T18:06:32.918756200Z WARN  solana_core::replay_stage] 1 active bank(s) to replay: [144228509]`
Reduce log severity to trace
> Reduce severity level of log in replay

- core/src/validator.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- runtime/src/accounts_background_service.rs
Prior to this change, long running commands like `solana-ledger-tool
verify` would OOM due to AccountsDb cleanup not happening.
Make `solana-ledger-tool` enable `AccountsBackgroundService`.
Credit to @mvines for doing most of the actual work in https://github.com/solana-labs/solana/pull/26349.
I had previously been encountering an OOM after ~5k slots of processing on mnb with `solana-ledger-tool` on a ledger I had assembled for testing something else. With this change, I successfully processed the ~10k slots I had been hoping to without issue.
As an interesting perf datapoint, here is processing comparison between `master` and `v1.10.32`; the memory stats are taken from last print out immediately before last frozen bank:
```
datapoint: memory-stats total=269843996672i
swap_total=1996796i …
```
> Make `solana-ledger-tool` run AccountsBackgroundService

- ledger/Cargo.toml
master cannot be build due to version conflict
```
cargo build
Updating crates.io index
error: failed to select a version for `spl-token`.
... required by package `solana-ledger v1.11.6 (edger)`
... which satisfies path dependency `solana-ledger` (locked to 1.11.6) of package `solana-gossip v1.11.6 (gossip)`
... which satisfies path dependency `solana-gossip` (locked to 1.11.6) of package `solana-accounts-cluster-bench v1.11.6 (accounts-cluster-bench)`
versions that meet the requirements `=3.3.1` are: 3.3.1
all possible versions conflict with previously selected packages.
previously selected package `spl-token v3.5.0`
... which satisfies dependency `spl-token = "=3.5.0"` of package `solana-account-decoder v1.11.6 (/account-decoder)`
... which satisfies path dependency …
```
> fix version of spl-token to prevent conflict

- transaction-status/src/parse_bpf_loader.rs
The close instruction of the `bpf_loader` program can either be called to close a buffer account or a program data account.
Currently, the bpf loader parser parse the closure of a buffer account properly but is missing an account regarding closure of a program account.
This PR add parsing for the program account.
> add program account to bpf loader close instruction parser

- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
`setup_connection` function has gotten convoluted over time, and could use a refactor.
Refactored the function into smaller blocks and also improve the code reuse.
Fixes #
> Refactor QUIC new connection handler function

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/lib.rs
- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_address_lookup_table.rs
- programs/bpf/Cargo.lock
No easy way to introspect AddressLookupTable accounts
Add jsonParsed support for `solana-address-lookup-table-program`
> Support jsonParsed address lookup table accounts

- programs/bpf_loader/src/syscalls/mod.rs
- sdk/program/src/instruction.rs
Syscall `sol_get_processed_sibling_instruction` writes struct `ProcessedSiblingInstruction` to VM memory. This struct contains `usize` parameters, which have different lengths across different architectures. The de-facto host `usize` is 64-bit on Solana, of course.
32-bit hosts such as `wasm32` would write 32-bit values, causing memory corruption in the VM.
Changes `usize` parameters in `ProcessedSiblingInstruction` to `u64`. This is a no-op on 64-bit host architectures.
Fixes #
> Fix sol_get_processed_sibling_instruction on 32-bit hosts

- banks-server/Cargo.toml
- client/Cargo.toml
- faucet/Cargo.toml
- ledger-tool/Cargo.toml
- ledger/Cargo.toml
- net-utils/Cargo.toml
- program-test/Cargo.toml
- storage-bigtable/Cargo.toml
- streamer/Cargo.toml
- test-validator/Cargo.toml
https://github.com/solana-labs/solana/pull/25028 pinned tokio across all solana crates. However, in actuality only solana-rpc needs to be pinned to avoid the RPC stalls, and the pin is causing problems for downstream users of solana client crates.
Unpin tokio everywhere except solana-rpc
> Unpin tokio for non-rpc crates

- docs/publish-docs.sh
The `publish-docs.sh` script being used to generate the redirects for Vercel are sending multiple pages to incorrect or unknown pages.
Updates the `publish-docs.sh` script to correctly redirect to known live URLs on the docs site.
> [docs] fixing incorrect/unknown redirects 

- programs/bpf_loader/src/syscalls/mod.rs
PR #26637 refactored syscalls into modules. This downgraded the visibility of these syscalls from public to private (default-visibility). 
Out-of-tree apps using syscalls are stuck with Solana ~v1.11.2 for now and can't upgrade to v1.11.5.
This seems like an inadvertent change since it's a breaking change but it went into a patch release.
Make syscalls pub again!
Fixes #
> bpf-loader: make syscalls pub

- cli-output/src/display.rs
- client/src/mock_sender.rs
- core/src/banking_stage.rs
- ledger/src/blockstore.rs
- programs/bpf/tests/programs.rs
- rpc/src/transaction_status_service.rs
- storage-bigtable/src/bigtable.rs
- storage-bigtable/src/lib.rs
- storage-proto/proto/confirmed_block.proto
- storage-proto/src/convert.rs
- storage-proto/src/lib.rs
- transaction-status/src/lib.rs
The transaction status structs don't track compute units consumed.
Adds `compute_units_consumed` to TransactionStatusMeta, StoredTransactionStatusMeta (bincode) and proto::TransactionStatusMeta (Protobuf/bigtable)
Fixes #
> transaction-status, storage-proto: add compute_units_consumed

- core/src/replay_stage.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster_slow_1.rs
- runtime/src/genesis_utils.rs
- sdk/src/signer/keypair.rs
`Keypair::clone()` was not implemented upstream in ed25519-dalek to force everyone to think twice before creating another copy of a potentially sensitive private key in memory.
See https://github.com/dalek-cryptography/ed25519-dalek/issues/76
However, there are now 9 instances of
```
Keypair::from_bytes(&keypair.to_bytes())
```
in the solana codebase and it would be preferable to have a function.
In particular since this also comes up when writing programs and can cause users to either start messing with lifetimes or discover the from_bytes() workaround themselves.
Add `clone()` to `Keypair`.
This patch opts to not implement the Clone trait. This avoids automatic use in order to preserve some of the original "let developers think twice about this" intention.
> Keypair: implement clone()

- rpc/src/rpc.rs
- rpc/src/rpc_service.rs
- validator/src/main.rs
Currently the  default is set in `MAX_REQUEST_PAYLOAD_SIZE` in rpc module. We need the ability to configure this for our RPC services as some payloads exceed 50KB.
Added a flag `--rpc-max-request-payload-size` to allow rpc operator to specify their own maximum request payload size.
Fixes #
N/A
> added arg --rpc-max-request-payload-size to validator
