solana-labs/solana

- Cargo.lock
- runtime/store-tool/Cargo.toml
- runtime/store-tool/src/main.rs
store-tool is inconvenient since we may not know the current_len of arbitrary appendvec files we want to inspect. 
With the change from #26795, we can skip sanitization checks and still print the contents of an appendvec file.
We can stop the loop when we hit a default account since that *should* indicate we've past the point of written data, this is guaranteed on POSIX systems (https://pubs.opengroup.org/onlinepubs/9699919799/functions/lseek.html) since our initial seek when creating the appendvec files should fill the gaps with zeros.
On windows, this probably won't work though, but we can still provide the length as previously.
Fixes #
> A more convenient store-tool

- .github/workflows/release-artifacts.yml
- storage-bigtable/build-proto/Cargo.toml
- storage-bigtable/build-proto/src/main.rs
- storage-proto/Cargo.toml
- storage-proto/build.rs
#26854 broke windows release builds do to the requirement of a C compiler
On windows machines, use installed protoc, instead of trying to build vendored package
Here is an example successful build: https://github.com/solana-labs/solana/runs/7721331802?check_suite_focus=true
[from this branch](https://github.com/solana-labs/solana/pull/26981), hacked up to run the CI job on a PR and only build the `solana-storage-proto` crate
Adding protoc to $PATH instead of setting the envar should also work, if you prefer that approach @yihau .
> Fix windows release builds

- core/src/ledger_cleanup_service.rs
- ledger/src/blockstore/blockstore_purge.rs
- ledger/src/blockstore_db.rs
LedgerCleanupService requires compactions to propagate & digest range-delete tombstones
to eventually reclaim disk space.
This PR makes LedgerCleanupService::cleanup_ledger delete any file whose slot-range is
older than the lowest_cleanup_slot.  This allows us to reclaim disk space more often with
fewer IOps because 1) we don't need to wait for rocksdb compactions, and 2) the purge
is done by deleting old files without iterating the checking every single key inside the file
using the compaction filter.
To make the above cleanup consistent with our range-deletion and reclaim disk space
more effectively, the cleanup range in LedgerCleanupService::cleanup_ledger has been
changed from (the-oldest-slot-in-db, lowest_cleanup_slot) to (0, lowest_cleanup_slot).
The detailed reason for this is …
> Delete files older than the lowest_cleanup_slot in LedgerCleanupService::cleanup_ledger

- ledger/src/blockstore_processor.rs
The caller of execute_batches() that assembles batches may call this
function with empty batches; we know we can bail early in this scenario.
Performance improvements look to be negligible with this change running `solana-ledger-tool` on a single bare metal machine. However, I think it is more intuitive to bail out early
> Bail out of execute_batches() early for empty batches slice

- docs/src/developing/clients/javascript-api.md
- docs/src/developing/clients/javascript-reference.md
- docs/src/developing/on-chain-programs/developing-c.md
- docs/src/developing/on-chain-programs/developing-rust.md
- docs/src/developing/programming-model/transactions.md
- docs/src/integrations/retrying-transactions.md
The docs have a few places where absolute URLs are used to link to internal docs pages. This can lead to people browsing updated docs on the `edge` or `beta` docs sites to be redirected away from the docs version they are browsing.
These internal links should be using the relative file structure to link to internal docs pages (all the relative links are auto-resolved when Docusaurus builds the various docs site versions)
- changed various absolute urls to use relative urls based on the file structure
- minor formatting changes due to auto-formatting
- updated images on the `integrations/retrying-transactions` to use the relative file structure (which is auto resolved for builds with Docusaurus)
> [docs] updated absolute routes to local routes

- sdk/src/signer/signers.rs
@joncinque
Sometimes a `Signer` need to be cloned as a trait object to avoid (attempted) rereads of the source data, like in https://github.com/solana-labs/solana-program-library/issues/2668 where data is provided via STDIN. A `Box` holding a trait object can't be cloned in this way, but using another pointer type which allows cloning trait objects like `Arc` requires `Signers` impls for `Vec<Arc<dyn Signer>>` and `[Arc<dyn Signer>>]`.
Add `Signers` impls for `Vec<Arc<dyn Signer>>` and `[Arc<dyn Signer>>]`
See https://github.com/solana-labs/solana-program-library/pull/3290#discussion_r929262764
> Add `Signers` impls for `Arc<dyn Signer>`

- core/src/tracer_packet_stats.rs
report is reseting the id to 0, so we lose that info after the first report
Get the current id, and call new instead of setting to default
Fixes #
> tracer-packet-stats reporting should not reset id

- Cargo.lock
- ledger-tool/Cargo.toml
- ledger-tool/src/main.rs
See #26886 
Support Geyser plugins in `solana-ledger-tool verify`
Adds `--geyser-plugin-config` flag to ledger-tool.
Only supports account updates for now.
Fixes #
> ledger-tool: support Geyser accounts updates

- Cargo.lock
- core/src/staked_nodes_updater_service.rs
- programs/bpf/Cargo.lock
- sdk/src/quic.rs
- streamer/Cargo.toml
- streamer/src/nonblocking/quic.rs
- streamer/src/streamer.rs
Differentiate the staked and non-staked connections and set different receive_window. Testing has show that with everything equal, by tweaking the receive window alone, the receive_window is impacting the chunks_received only below about 10 * PACKET_DATA_SIZE. Beyond that -- it is not making much difference. 
This change sets the receive_window for non-staked node to 1 * PACKET_DATA_SIZE, and maps the staked nodes's connection's receive_window between 1.2 * PACKET_DATA_SIZE to  10 * PACKET_DATA_SIZE based on the stakes.
The changes is based on Quinn library change to support per connection receive_window tweak at the server side. https://github.com/quinn-rs/quinn/pull/1393
Fixes #
> Set receive_window per quic connection

- programs/vote/src/vote_instruction.rs
The VoteInstruction enum is backward-incompatible with v1.10 due to 2 new variants added in the middle.
Move those variants to the end
> Fix VoteInstruction order

- rpc-test/tests/rpc.rs
The test sends the signatures and then a ready message all in tokio async tasks.  The problem is that tokio async tasks are not run in order, so receiving the ready message does not guarantee that the signature sending is done.
This test is too flaky at 15-second timeout.  Debugging show occasional multi-second delay which could come from multiple sources -- other tokio tasks, tokio scheduler, OS scheduler.  The async nature makes it hard to track down the origin of the delay.
Without fundamentally changing the test design, this change only increases the timeout to reduce the flakiness of the test.
thread 'test_rpc_subscriptions' panicked at 'recv_timeout, 569/1000 signatures remaining', core/tests/rpc.rs:354:17
> Increase timeout to reduce the flakyness of rpc signature receving test

- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
To understand better of throughput for transactions from staked and non-staked, metrics are added for staked_received_chunks and unstaked_received_chunks
> Different staked vs unstaked chunks_received

- Cargo.lock
- core/src/commitment_service.rs
- core/src/consensus.rs
- core/src/replay_stage.rs
- core/src/tower1_7_14.rs
- core/src/validator.rs
- local-cluster/src/local_cluster.rs
- program-test/src/lib.rs
- programs/bpf/Cargo.lock
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- programs/vote/Cargo.toml
- programs/vote/src/lib.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- programs/vote/src/vote_transaction.rs
- rpc/src/rpc.rs
- runtime/src/bank.rs
- runtime/src/stakes.rs
- sdk/program/src/lib.rs
- sdk/program/src/vote/authorized_voters.rs
- sdk/program/src/vote/error.rs
- sdk/program/src/vote/instruction.rs
- sdk/program/src/vote/mod.rs
- sdk/program/src/vote/state/mod.rs
- sdk/program/src/vote/state/vote_state_0_23_5.rs
- sdk/program/src/vote/state/vote_state_versions.rs
- validator/src/bootstrap.rs
It's difficult to make use of the vote program's state and instructions from the context of another program because these definitions are not program compatible,  due to the dependence on the `solana-sdk` module.
To resolve this, vote program now follows the same model as stake program whereby the `solana-program` crate now contains the state/instruction definitions. There is further potential refactoring that could take place in the vote program itself in the future, as the remains of `programs/vote/src/vote_state/` could be folded into `programs/vote/src/vote_processor.rs`.
> Move vote program state and instructions to solana-program

- core/src/banking_stage.rs
- core/src/forward_packet_batches_by_accounts.rs
- core/src/immutable_deserialized_packet.rs
- core/src/lib.rs
- core/src/unprocessed_packet_batches.rs
Transaction schedulers will create and use `ImmutableDeserializedPacket`s outside the context of the `UnprocessedPacketBatches`. A preliminary step towards #27009 
Move the `ImmutableDeserializedPacket` type into its own file, and add a `new()` constructor.
Fixes #
> Separate file for ImmutableDeserializedPacket type

- explorer/src/components/account/TokenHistoryCard.tsx
- explorer/src/components/account/history/TokenInstructionsCard.tsx
- explorer/src/components/account/history/TokenTransfersCard.tsx
- explorer/src/components/account/history/common.tsx
- explorer/src/components/transaction/InstructionsSection.tsx
- explorer/src/components/transaction/ProgramLogSection.tsx
- explorer/src/components/transaction/TokenBalancesCard.tsx
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/transactions/parsed.tsx
- explorer/src/utils/instruction.ts
- Replaced usages of deprecated `ParsedConfirmedTransaction` with `ParsedTransactionWithMeta`
- Renamed local variables used for `ParsedTransactionWithMeta` to `transactionWithMeta` for clarity
> Explorer: Refactor parsed transaction handling

- ci/publish-tarball.sh
I broke windows build after #26555 
```
Compiling crossbeam-epoch v0.9.5 (https://github.com/solana-labs/crossbeam?rev=fd279d707025f0e60951e429bf778b4813d1b6bf#fd279d70)
error: expected item, found `..`
--> C:\Users\runneradmin\.cargo\git\checkouts\crossbeam-2841e3eed153c98b\fd279d7\crossbeam-epoch\no_atomic.rs:1:1
|
1 | ../no_atomic.rs
| ^^
error[E0425]: cannot find value `NO_ATOMIC_CAS` in this scope
--> C:\Users\runneradmin\.cargo\git\checkouts\crossbeam-2841e3eed153c98b\fd279d7\crossbeam-epoch\build.rs:27:8
|
27 |     if NO_ATOMIC_CAS.contains(&&*target) {
|        ^^^^^^^^^^^^^ not found in this scope
For more information about this error, try `rustc --explain E0425`.
error: could not compile `crossbeam-epoch` due to 2 previous errors
warning: build failed, waiting for other jobs to …
```
> Fix windows build after crossbeam-epoch patch

- gossip/src/cluster_info.rs
- net-utils/src/lib.rs
TestValidator doesn't work with the quic client on by default (as in #26927, for example); namely, transaction send attempts time out. This is because the ContactInfo assignment for a TestValidator (in `Node::new_single_bind`) uses different port logic than what the client expects (quic offsets are hard-coded in the client).
This alternative to #27044 replaces `bind_two_consecutive_in_range()` with a method that takes a custom offset. This should accomplish the same thing as #27044 for `Node::new_single_bind()`, but also be useful for `Node::new_localhost()`, which might be run by multiple local nodes at the same time.
Closes #27044
> Fix quic client on TestValidator, alternative

- core/src/validator.rs
On a restart, validators need to pour over logs and run rpc to:
1. Ensure their node is waiting for supermajority at the right slot
2. Monitor the gossip stake percentage 
Extend `solana-validator monitor` to remove this annoyance.
Old, static status:
```
$ solana-validator monitor
Ledger location: ledger
⠤ Validator startup: WaitingForSupermajority...
```
New, dynamic status:
```
$ solana-validator monitor
Ledger location: ledger
⠒ Validator startup: WaitingForSupermajority { slot: 144871251, gossip_stake_percent: 54 }...
```
> `solana-validator monitor` how displays slot and gossip stake % while waiting for supermajority

- Cargo.lock
- programs/bpf/Cargo.lock
- streamer/Cargo.toml
Warning during build:
warning: /Users/lijunwang/sol2/solana2/streamer/Cargo.toml: unused manifest key: dependencies.quinn-proto.commit
warning: /Users/lijunwang/sol2/solana2/streamer/Cargo.toml: unused manifest key: dependencies.quinn.commit
Use "rev" only in git dependency.
Fixes #
> Fixed a cargo warning on specifing quinn dependencies

- web3.js/src/connection.ts
The `loadedAddresses` field is returned with transaction metadata but is currently ignored 
Add support for detecting and validating the `loadedAddresses` field in tx metadata responses
Fixes #
> feat: handle `loadedAddresses` field in tx meta responses

- web3.js/src/connection.ts
- web3.js/src/fee-calculator.ts
Some types are only used by deprecated methods but aren't annotated as deprecated yet
annotate more types as deprecated
Fixes #
> chore: annotate more types as deprecated

- sdk/src/lib.rs
The docs for solana_sdk show many duplicated modules and macros. Per https://github.com/solana-labs/solana/issues/26211 this is due to a bug in rustdoc (https://github.com/rust-lang/rust/issues/60522) that causes *-imports that are shadowed by local definitions to not be removed from the docs.
This bug not only causes duplicate listings of items, but also non-deterministically causes the docs for those items to show shadowed *-imported version, causing some items defined within those duplicated modules to not be documented at all.
This patch removes the `solana_program::*` import and instead lists every non-shadowed import explicitly.
This is obviously a lot harder to maintain so long as every item in solana_program is intended to be reexported, and made more difficult by some items being …
> Fix duplicate / incorrect docs in solana_sdk by removing the solana_program::* import

- Cargo.lock
- sdk/cargo-build-sbf/Cargo.toml
- sdk/cargo-build-sbf/src/main.rs
- sdk/cargo-build-sbf/tests/crates.rs
cargo-build-sbf uses `CARGO_TARGET_SBF_SOLANA_SOLANA_RUSTFLAGS` env variable to pass solana specific command line options to rust compiler. However, it also sets `RUSTFLAGS` environment variable which overrides the former variable.
- Make cargo-build-sbf use `CARGO_TARGET_SBF_SOLANA_SOLANA_RUSTFLAGS` exclusively to pass rust compiler options.
- Add an integration test that validates that `--arch sbfv2` option indeed forces cargo-build-sbf to build SBFv2 binaries.
Fixes #26971
> Fix rust flags handling in cargo-build-sbf

- local-cluster/src/cluster_tests.rs
The local cluster tests are failing when QUIC is enabled.
The IP address used for connection (0.0.0.0) didn't match what was used for creating the authentication certificate (127.0.0.1). Changing the server address to 127.0.0.1 fixes the issue.
Fixes #
> Fix local cluster tests for QUIC usage

- core/benches/shredder.rs
- core/src/broadcast_stage/broadcast_utils.rs
- core/src/broadcast_stage/standard_broadcast_run.rs
- core/src/shred_fetch_stage.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shredder.rs
- ledger/tests/shred.rs
Context:
https://discord.com/channels/428295358100013066/478692221441409024/981207623527452705
Given the 32:32 erasure recovery schema, current implementation requires
exactly 32 data shreds to generate coding shreds for the batch (except
for the final erasure batch in each slot).
As a result, when serializing ledger entries to data shreds, if the
number of data shreds is not a multiple of 32, the coding shreds for the
last batch cannot be generated until there are more data shreds to
complete the batch to 32 data shreds. This adds latency in generating
and broadcasting coding shreds.
In addition, with Merkle variants for shreds, data shreds cannot be
signed and broadcasted until coding shreds are also generated. As a
result *both* code and data shreds will be delayed before broadcast if …
> removes buffering when generating coding shreds in broadcast

- web3.js/src/connection.ts
`Connection.getParsedAccountInfo` doesn't support the `minContextSlot` field yet
- Allow `getParsedAccountInfo` to be called with a config object to match `getAccountInfo` 
Fixes #
> feat: support minContextSlot in getParsedAccountInfo method

- Cargo.lock
- ledger/Cargo.toml
- ledger/src/blockstore_db.rs
- programs/bpf/Cargo.lock
https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.19.0
> Bump rust-rocksdb to 0.19.0 tag

- Cargo.lock
- bench-tps/Cargo.toml
- bench-tps/src/bench.rs
- bench-tps/src/cli.rs
- bench-tps/src/main.rs
bench-tps should have option to send transactions with different compute-unit-price in order to test fee market functions. 
- Add option to enable sending transactions with randomized compute-unit-price (in range of 0..100).
Fixes #
> add subcommand to set randomized compute-unit-price to transactions.

- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- local-cluster/src/local_cluster.rs
- rpc/src/rpc_service.rs
- test-validator/src/lib.rs
- validator/src/main.rs
In `JsonRpcService::new` if `start_http` fails `close_handle_sender` will be dropped without sending a value to the channel. Subsequent `close_handle_receiver.recv().unwrap()` will fail on the closed channel.
Send error value over the channel to gracefully handle the failure. Handle errors gracefully in `Validator::new` rather than using `validator::abort()`.
See #25400 for original change which was reverted by #26130 due to #25941.
Description of issue with original change from #25941:
> Problem seems to be that `Validator::new` fails using `abort()` which in tests calls `panic()`. This is handled by the test framework and can leave rocksdb background threads accessing partially torn down state. This is exacerbated by tests in `program.rs` and `commands.rs` running parallel tests which …
> Handle JsonRpcService startup failure

- local-cluster/src/cluster_tests.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster.rs
Some local cluster tests are still failing when QUIC is enabled.
Following #27071, changes server addresses to 127.0.0.1
I don't think this fixes all the problems, but it allows some tests that were failing in current iteration of  #26927 to succeed (eg. `test_spend_and_verify_all_nodes_2`, `test_spend_and_verify_all_nodes_3`) cc @willhickey
> Fix local-cluster for QUIC more

- program-test/src/lib.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/runtime_config.rs
- sdk/src/transaction/sanitized.rs
- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
The number of accounts that can be locked by each transaction is currently limited 64 accounts but is not configurable by devs who want to test transactions with more accounts.
- Added the `--transaction-account-lock-limit` cli arg to `solana-test-validator` to override the hardcoded limit of 64
- Allow overriding the tx account lock limit in ProgramTest
Fixes #
> Allow overriding the runtime transaction account lock limit

- runtime/src/bank.rs
The bank test, `test_accounts_data_size_and_resize_transactions`, sometimes fails if the random numbers used to create the account and grow the account are too large. If the starting account size is very large, and the resize amount is also large, then the resize transaction will fail due to the new account size being greater than the max allowed size.
It likely happened here:
https://buildkite.com/solana-labs/solana/builds/79623#01829209-7fdb-4941-a2ab-7abb8a52a23e
Limit the random number generator's range such that the resize will always be a valid amount.
> Fix test_accounts_data_size_and_resize_transactions

- ledger/src/shred.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shredder.rs
As a consequence of removing buffering when generating coding shreds:
https://github.com/solana-labs/solana/pull/25807
more coding shreds are generated than data shreds, and so
`MAX_CODE_SHREDS_PER_SLOT` needs to be adjusted accordingly.
Updated values based on `ERASURE_BATCH_SIZE`.
> adjusts max coding shreds per slot

- client/tests/quic_client.rs
The tests test_quic_client_multiple_writes fails sporadically because all 4000 packets might not be sent all in the allotted time.
The issue is likely more easily showing up since the receive_window change when we reduce the receive_window for non-staked nodes.
Reduce the count to 3000
> Reduce quic multi write test packets count

- cli/src/program.rs
- cli/tests/program.rs
There's no confirmation step when closing a program with the CLI. Closing a program is irreversible so this UX should be improved to help prevent mistakes.
When a program is closed with the CLI, display a warning unless the `--bypass-warning` flag is present
Fixes #
> cli: Require `--bypass-warning` flag to close program accounts

- runtime/src/bank.rs
`default_units_per_instruction` is now activated on all clusters and the feature gate code can be removed
Removed usages of `default_units_per_instruction`
Closes https://github.com/solana-labs/solana/issues/24898
> clean-feature: `default_units_per_instruction`

- bench-tps/src/bench.rs
- bench-tps/src/cli.rs
- bench-tps/src/main.rs
- bench-tps/tests/bench_tps.rs
Part of [chain of PRs](https://github.com/solana-labs/solana/issues/25759) to add durable nonce to the bench-tps tool.
This one introduces flag `use_durable_nonce` which allows to turn on this mode manually (cli option in the next PR).
It also introduce optional creation of blockhash thread (since for durable nonce we don't need blockhashes).
> Bench tps add nonce flag

- core/src/transaction_priority_details.rs
- program-runtime/src/compute_budget.rs
- programs/bpf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
`request_units_deprecated ` is now activated on all clusters and the feature gate code can be removed
Removed usages of `request_units_deprecated `
Closes https://github.com/solana-labs/solana/issues/25050
> clean feature: `request_units_deprecated`

- runtime/src/accounts_db.rs
> don't log when there is no work to do for combining ancient slots

- web3.js/src/account-data.ts
- web3.js/src/connection.ts
- web3.js/src/programs/address-lookup-table/index.ts
- web3.js/src/programs/address-lookup-table/state.ts
- web3.js/test/connection.test.ts
No way to fetch and decode address lookup tables with web3
- Add `getAddressLookupTable` method to `Connection`
- Add deserialization logic for decoding raw lookup table account data buffers
Fixes #
> feat: add getAddressLookupTable method to Connection

- ledger-tool/src/bigtable.rs
- ledger-tool/src/main.rs
RocksDB settings include an option to create_if_missing, which will
create missing columns or the entire rocksdb directory if starting from
scratch. However, create_if_missing functionality only works if the
session has Primary (read+write) access. Many ledger-tool commands only
need Secondary (read-only) access to the database, so these commands are
unable to open the Blockstore when a column must be added.
This change detects when Secondary access open fails due to missing
column(s) or files, opens the database temporarily with Primary access,
and then reattempts to open the database Secondary access.
> Add fallback for ledger-tool commands to create new column families

- explorer/src/components/account/address-lookup-table/AddressLookupTableAccountSection.tsx
- explorer/src/components/account/address-lookup-table/LookupTableEntriesCard.tsx
- explorer/src/components/account/address-lookup-table/types.ts
- explorer/src/components/instruction/address-lookup-table/types.ts
- explorer/src/pages/AccountDetailsPage.tsx
Can't view address lookup table details on the explorer
Added a details page for address lookup able accounts which displays metadata and includes a tab to view which addresses are stored.
Fixes #
> Explorer: Add details page for address lookup table accounts

- validator/src/bin/solana-test-validator.rs
`solana-test-validator` has a couple args that take multiple values, but their help output confusingly stuffs them both into one pair of chevrons.
```
--account <ADDRESS FILENAME.JSON>...
Load an account from the provided JSON file (see `solana account --help` on how to dump an account to file).
Files are searched for relatively to CWD and tests/fixtures. If the ledger already exists then this
parameter is silently ignored
--bpf-program <ADDRESS_OR_PATH BPF_PROGRAM.SO>...
Add a BPF program to the genesis configuration. If the ledger already exists then this parameter is silently
ignored. First argument can be a public key or path to file that can be parsed as a keypair
```
Split them by using `value_names()` instead of `value_name`
```
--account <ADDRESS> <DUMP.JSON>
Load an account from …
```
> test-validator: improve multi-value arg help output

- Cargo.lock
- cli/Cargo.toml
- programs/bpf/Cargo.lock
- programs/bpf/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/allocator_bump.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/mod.rs
- rbpf-cli/Cargo.toml
[solana_rbpf v0.2.32](https://github.com/solana-labs/rbpf/releases/tag/v0.2.32) was released.
- `AlignedMemory` now takes the alignment as a const generic instead of a constructor parameter.
- `AlignedMemory::new` => `AlignedMemory::with_capacity`
- `AlignedMemory::new_with_size` => `AlignedMemory::zero_filled`
- `AlignedMemory::resize` => `AlignedMemory::fill_write`
- Removed `disable_unresolved_symbols_at_runtime` and `disable_deprecated_load_instructions` from `vm::Config`
- Added `new_elf_parser` and `reject_rodata_stack_overlap` to `vm::Config`
> Bumps solana_rbpf to v0.2.32

- runtime/src/accounts.rs
under certain startup conditions, 2 hash calcs could run in parallel.
Fixes #
> wait for bg hash calc to complete before 'calculate_capitalization'

- sdk/macro/src/lib.rs
- sdk/program/src/clock.rs
- sdk/program/src/epoch_schedule.rs
- sdk/program/src/example_mocks.rs
- sdk/program/src/lib.rs
- sdk/program/src/rent.rs
- sdk/program/src/slot_hashes.rs
- sdk/program/src/slot_history.rs
- sdk/program/src/sysvar/clock.rs
- sdk/program/src/sysvar/epoch_schedule.rs
- sdk/program/src/sysvar/fees.rs
- sdk/program/src/sysvar/instructions.rs
- sdk/program/src/sysvar/mod.rs
- sdk/program/src/sysvar/recent_blockhashes.rs
- sdk/program/src/sysvar/rent.rs
- sdk/program/src/sysvar/rewards.rs
- sdk/program/src/sysvar/slot_hashes.rs
- sdk/program/src/sysvar/slot_history.rs
- sdk/program/src/sysvar/stake_history.rs
More docs needed.
This adds documentation to the sysvar module and its submodules, to the data types and supporting functions associated with each sysvar. It moves the crate-level sysvar docs into the sysvar module.
> Add more sysvar API docs

- runtime/src/accounts_db.rs
- runtime/src/read_only_accounts_cache.rs
We are seeing rewards regression on 8/2/ epoch. 
https://github.com/solana-labs/solana/issues/26922
It seems that the cache is full during the epoch boundary. 
Adding a stat for evict to verify the cache pressure during epoch boundary.
Fixes #
> Add stats for readonly cache evicts

- ci/do-audit.sh
Bumping rocksdb is blocked on updating rust to v1.60+, and that's too much churn for stable branch.
Ignore audit warning
> Ignore rocksdb audit warning

- .buildkite/hooks/post-command
- ci/test-stable.sh
We don't have an efficient way to detect flaky tests. I uploaded test results to buildkite and datadog. Let them generate an analysis for us.
exported test result in this PR
- stable
- doctest
- stable-bpf
- stable-perf
- local-cluster
- local-cluster-flakey
- local-cluster-slow-1
- local-cluster-slow-2
will export in next PR
- coverage
will ignore
- sanity
- shellcheck
- checks
- downstream-projects
- wasm
- bench
> chore: upload test results to buildkite and datadog

- ledger/src/shred.rs
- ledger/src/shred/merkle.rs
Maintain symmetry between code and data shreds:
* `ShredData::capacity` -> data buffer capacity
* `ShredCode::capacity` -> erasure code capacity
renames `size_of_erasure_encoded_slice` to `ShredCode::capacity`.
> renames size_of_erasure_encoded_slice to ShredCode::capacity

- runtime/src/accounts_db.rs
When a validator fails due to a cap mismatch, it restarts. it often then gets another snapshot. It can then fail again on a different slot.
Keep track of failures per slot. Note this has the downside that it can use up all disk capacity, but that is only in the case that it repeatedly encounters hash calc cap mismatches, which should be exceedingly rare in practice.
This allows the original failure to be debugged.
Fixes #
> store hash calc failures in a separate folder by slot

- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
cleanup remnants of `abort()` remaining after #27075
return `Result` rather than panicking inline.
Fixes #
> remove abort() from test-validator

- runtime/src/ancestors.rs
- runtime/src/status_cache.rs
On Ancestors, the `get` and `contains_key` APIs are exactly the same, which cause confusion. 
Remove `get` API and replace with `contains_key`.
Fixes #
> Share Ancestors API get with contains_key

- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/cluster_nodes.rs
A change included in https://github.com/solana-labs/solana/pull/20480
was that when the root node in turbine broadcast tree is down, the
leader will broadcast the shred to all nodes in the first layer.
The intention was to mitigate the impact of dead nodes on shreds
propagation, because if the root node is down, then the entire cluster
will miss out the shred.
On the other hand, if `x%` of stake is down, this will cause `200*x% + 1`
packets/shreds ratio at the broadcast stage which might contribute to
line-rate saturation and packet drop.
To avoid this bandwidth saturation issue, this commit reverts that logic
and always broadcasts shreds from the leader only to the root node.
As before we rely on erasure codes to recover shreds lost due to staked
nodes being offline.
> reverts wide fanout in broadcast when the root node is down

- Cargo.lock
- account-decoder/Cargo.toml
- client/Cargo.toml
- ledger/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- transaction-status/Cargo.toml
https://github.com/solana-labs/solana/pull/26825 needs new info definitions from spl-token-2022 v0.4.3
Bump spl-token-2022
Cargo really wants to bump the SPL dependencies to v1.11 as part of this. I had to manually keep these on v1.10 in the past, due to zk-token-sdk pod display definitions, but will give it a try now.
> Bump spl-token-2022

- web3.js/src/programs/vote.ts
- web3.js/test/program-tests/vote.test.ts
Currently when withdrawing rewards from a vote account, the JS SDK can withdraw an amount that will leave the account with less than the minimum required for rent, and will transparently close the account without any confirmation or warning to the developer.
To get feature parity with the CLI, we've added a `safeWithdraw` method to the vote-program. The CLI offers an "ALL" option when withdrawing from a vote account which will leave enough SOL balance to cover the minimum rent for the account. If you accidentally withdraw the entire balance the vote account gets closed.
> VoteProgram.safeWithdraw function to safeguard against accidental vote account closures

- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/confidential_transfer.rs
- transaction-status/src/parse_token/extension/mod.rs
Parsing apis for spl-token-2022 ConfidentialTransaction instructions are only stubs.
Add parsing for all ConfidentialTransaction instructions.
Need rebase on https://github.com/solana-labs/solana/pull/26820
> Parse ConfidentialTransaction instructions

- banking-bench/src/main.rs
- bench-tps/src/cli.rs
- bench-tps/tests/bench_tps.rs
- client/src/connection_cache.rs
- core/src/banking_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
- dos/src/cli.rs
- dos/src/main.rs
- local-cluster/src/validator_configs.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_slow_1.rs
- local-cluster/tests/local_cluster_slow_2.rs
- multinode-demo/bootstrap-validator.sh
- validator/src/main.rs
This is a re-creation of PR #26879 which was reverted by PR #26913
* As of v1.10.32 the validator listens for QUIC connections by default
* The validator can forward transactions via quic if run with --tpu-use-quic, but doesn't by default
* Switch the default client behavior to use QUIC
* Add argument to disable the quic client
> Enable QUIC client by default. Add arg to disable QUIC client. Take 2

- runtime/src/snapshot_utils.rs
Similar to #25889, we should also serialize the version file so we can unpack and reconstruct in parallel.
Necessary to make #26590 more robust and switch on version.
Serialize the version file first so we can check the version and switch to the correct deserialization method while we unpack.
Fixes #
> snapshots: serialize version file first

- core/src/accounts_hash_verifier.rs
- core/tests/snapshots.rs
- runtime/src/bank.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
To switch the contents of an incremental snapshot accounts hash, we need to save additional information with a snapshot. This pr provides the saving/loading of the incremental info. It will be saved as None at the moment. The change to switch the incremental snapshot accounts hash will be a feature we can activate once the network is all running a version that can save this new information.
Fixes #
> serialize incremental_snapshot_hash

- sdk/cargo-build-bpf/src/main.rs
- sdk/cargo-test-bpf/src/main.rs
If you run `cargo build-bpf <args> -- <extra_args>`, the `--arch bpf` bit is added at the end, rather than before the `--`, which breaks builds.
Put `--arch bpf` before `--`
Fixes #
cc @2501babe
> sdk: Fix args after "--" in build-bpf and test-bpf

- rpc-test/tests/rpc.rs
`test_rpc_subscriptions` is timing out somewhat frequently. Here are two examples where unrelated changes failed in CI:
```
thread 'test_rpc_subscriptions' panicked at 'recv_timeout, 4/1000 accounts remaining', rpc-test/tests/rpc.rs:415:17
thread 'test_rpc_subscriptions' panicked at 'recv_timeout, 30/1000 accounts remaining', rpc-test/tests/rpc.rs:415:17
```
In both cases we were very close to completing all of the accounts.
Increase timeout from 5 seconds to 10 seconds
> Flaky Unit Test test_rpc_subscriptions

- ci/docker-run.sh
I broke docs pipeline due to sccache
https://github.com/solana-labs/solana/runs/7883281080?check_suite_focus=true
only buildkite ci use sccache when exec docker-run
> chore: only buildkite pipelines use sccache in docker-run.sh

- programs/bpf_loader/src/syscalls/cpi.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/ed25519-tests/tests/process_transaction.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/genesis_utils.rs
- runtime/src/message_processor.rs
- sdk/src/feature_set.rs
- sdk/src/precompiles.rs
`prevent_calling_precompiles_as_programs` is now activated on all clusters and the feature gate code can be removed
Removed usages of `prevent_calling_precompiles_as_programs`
Closes https://github.com/solana-labs/solana/issues/24746
> clean feature: `prevent_calling_precompiles_as_programs`

- bench-tps/src/bench_tps_client.rs
- bench-tps/src/bench_tps_client/bank_client.rs
- bench-tps/src/bench_tps_client/rpc_client.rs
- bench-tps/src/bench_tps_client/thin_client.rs
- bench-tps/src/bench_tps_client/tpu_client.rs
Add method `get_account_with_commitment` (`get_account` already exists).
Version of the method with explicit commitment is used for consistency with the codebase of bench-tps.
RpcClient and TpuClient are using default commitment level `CommitmentConfig::confirmed()`, for ThinClient it is not explicitly specified.
It is used in the next https://github.com/solana-labs/solana/pull/27151 to get durable nonce from account data (https://github.com/solana-labs/solana/pull/27151/commits/4feeb4afdbc826a0ce9238e0afe763e1312f99b5).
For simplicity, this wrapper`BenchTpsClient::get_account_with_commitment`  returns `Result<Account>` instead of `Result<Option<Account>>` like in the underlying implementation.
> Add get_account_with_commitment to BenchTpsClient

- ledger/src/blockstore.rs
get_entries_in_data_block() panics when there's inconsistency between
slot_meta and data_shred.
However, as we don't lock on reads, reading across multiple column families is
not atomic (especially for older slots) and thus does not guarantee consistency
as the background cleanup service could purge the slot in the middle.  Such
panic was reported in #26980 when the validator serves a high load of RPC calls.
This PR makes get_entries_in_data_block() panic only when the inconsistency
between slot-meta and data-shred happens on a slot older than lowest_cleanup_slot.
> Fix the inconsistency check in get_entries_in_data_block()

- runtime/src/accounts_db.rs
The debug feature to capture contents of a hash calc for later debugging is not compatible with using the write cache for hash calculation. So, assert if that combination is requested. Note that this should not happen unless a custom build is used with hardcoding for whether to capture the failing hash contents. But, when this does happen, a long time can be wasted figuring out that this was an invalid request. Now, this will immediately fail.
Fixes #
> add an assert for a debug feature to avoid wasted time

- runtime/src/in_mem_accounts_index.rs
Caller already sets the age to the future.
https://github.com/solana-labs/solana/blob/7720b48aa67450485d6dc1e7a3db216b34a3bfe9/runtime/src/in_mem_accounts_index.rs#L281-L284
Fixes #
> remove redundant call that bumps age to future

- runtime/src/accounts_db.rs
This is only used during debug logging.
<slot>/failed_calculate_accounts_hash_cache/...
becomes
failed_calculate_accounts_hash_cache/<slot>/...
Fixes #
> reorder slot # in debug hash data path

- runtime/src/bank.rs
- runtime/src/snapshot_utils.rs
By definition, if we're verifying the bank from a snapshot, then there will be a slot for that snapshot/bank. When calling `verify_snapshot_bank()`, we currently do not enforce that, which could result in unintended misuse/bugs.
Change `last_full_snapshot_slot` param's type in `Bank::verify_snapshot_bank()` to `Slot`.
> Verifying snapshot bank must always specify the snapshot slot

- Cargo.lock
- cli-output/src/cli_output.rs
- cli/Cargo.toml
- cli/src/address_lookup_table.rs
- cli/src/clap_app.rs
- cli/src/cli.rs
- cli/src/lib.rs
- cli/tests/address_lookup_table.rs
Can't use the cli to interact with the address lookup table program
Added an `addresss-lookup-table` subcommand which itself has a list of subcommands for creating, extending, freezing, deactivating, closing, and displaying lookup tables.
```
$ solana address-lookup-table get F3MfgEJe1TApJiA14nN2m4uAH4EBVrqdBnHeGeSXvQ7B -ud
Lookup Table Address: F3MfgEJe1TApJiA14nN2m4uAH4EBVrqdBnHeGeSXvQ7B
Authority: AhzQ41qzaBoqfVC72sMtWgkcGDJpkfsnWTAJfFqAQV62
Deactivation Slot: None (still active)
Last Extended Slot: 154734400
Address Table Entries:
Index  Address
0      1111111QLbz7JHiBTspS962RLKV8GndWFwiEaqKM
1      1111111ogCyDbaRMvkdsHB3qfdyFYaG1WtRUAfdh
2      11111112D1oxKts8YPdTJRG5FzxTNpMtWmq8hkVx3
3      11111112cMQwSC9qirWGjZM6gLGwW69X22mqwLLGP
4      111111131h1vYVSYuKP6AhS86fbRdMw9XHiZAvAaj …
```
> cli: Add subcommands for address lookup tables

- core/src/ancestor_hashes_service.rs
- core/src/serve_repair.rs
- gossip/src/cluster_info.rs
- gossip/src/ping_pong.rs
ping-pong protocol need hash domain.
In order to maintain backward compatibility, for now the responding node
will hash the token both with and without domain so that the other node
will accept the response regardless of its upgrade status.
Once the cluster has upgraded to the new code, we will remove the legacy
domain = None case.
> adds hash domain to ping-pong protocol

- sdk/src/transaction/error.rs
Problem
I ran into this problem today where I developed on Solana and did not provide sufficient funds:
Now I'm pretty sure that is a case of double negation and *should* say 
"results in an account *with* insufficient funds for rent"
So i corrected that in this repo where it appeared
> correct double negation

- banking-bench/src/main.rs
- bench-tps/src/cli.rs
- bench-tps/tests/bench_tps.rs
- client/src/connection_cache.rs
- core/src/banking_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
- dos/src/main.rs
- local-cluster/src/validator_configs.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_slow_1.rs
- local-cluster/tests/local_cluster_slow_2.rs
- multinode-demo/bootstrap-validator.sh
- validator/src/main.rs
* Enable QUIC client by default. Add arg to disable QUIC client.
* Deprecate --disable-quic-servers arg
* Add #[ignore] annotation to failing tests
> Enable QUIC client by default. Add arg to disable QUIC client. (Forward port #26927)

- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
`slots_connected` was returning false if we did not have *exactly* the `ending_slot`. This is more restrictive than necessary for ledger-tool modes that are not `create-snapshot`.
* `slots_connected` => `slot_range_connected`
* returns true if we can get past the `ending_slot` (ie there is a path from `starting_slot` to some slot >= `ending_slot`)
Fixes #
> slots_connected: check if the range is connected (>= ending_slot)

- ledger-tool/src/main.rs
Follow up to #27152
check if snapshot_slot exists when creating a snapshot
blocked by #27152
Fixes #
> create-snapshot check if snapshot slot exists

- runtime/src/block_cost_limits.rs
`ed25519_program` is missing from built-in instructions cost table
add it
follow-up to: #21995
> add ed25519_program to built-in instruction cost list

- runtime/src/accounts_db.rs
> add _inclusive for clarity

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
An old feature modified some sysvar lamport values from 1 to 0 for the purposes of hash calc. This causes us to need to distinguish between ACTUALLY 0 lamport accounts and those that had become 0 during hash calculation. This feature code has since been removed and we no longer modify lamport values for hash calculation. So, the very convenient '0' value can be used for zero lamport accounts. This removes an unnecessary concept.
Fixes #
> eliminate unnecessary ZERO_RAW_LAMPORTS_SENTINEL

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
> make test code more clear

- core/src/banking_stage.rs
aggregated_tracer_packet_stats_option always started off as None in this code.
The if let statement was not doing anything, so just set aggregated_tracer_packet_stats_option as the result of the recv.
Fixes #
> banking stage: actually aggregate tracer packet stats

- runtime/src/bank.rs
This is the No.1 of a seriers of pull requests to refactor epoch reward
calculation.
> Refactor epoch reward 1

- Cargo.lock
- ledger/Cargo.toml
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shred/merkle.rs
- ledger/src/shredder.rs
erasure code -> merkle shreds
The commit
* Identifies Merkle shreds when recovering from erasure codes and
dispatches specialized code to reconstruct shreds.
* Coding shred headers are added to recovered erasure shards.
* Merkle tree is reconstructed for the erasure batch and added to
recovered shreds.
* The common signature (for the root of Merkle tree) is attached to all
recovered shreds.
> recovers merkle shreds from erasure codes

- core/src/validator.rs
The validator logs show that clean_accounts_paths takes too long time.  This moves files deleting work to an async background task, unblocking validator new() to move forward without waiting for the deletion to be done.
INFO  solana_core::validator] done. clean_accounts_paths took 14.5s
Rename the files first, which should take much less time than deleting them.
Call an async task to remove the files in async context, let the validator init to go forward without blocking on it.
Before the validator process starts, there is 105GB files in the directory, which would take 14s before the change. 
sol@dev-server-da11:~$ du /mnt/nvme1n1/ledger/accounts
98832856        /mnt/nvme1n1/ledger/accounts/accounts
105338348       /mnt/nvme1n1/ledger/accounts
With the change, there is no more 14s …
> Account files remove

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/mod.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- sdk/src/transaction_context.rs
ABIv2 will need a consecutive memory layout to map the `instruction_trace` into the VM address space. Also, putting everything in a single allocation would reduce the multi threading overhead of memory management dramatically.
The `instruction_trace` is flattened from a `Vec<Vec<InstructionContext>>` into a `Vec<InstructionContext>`. The outer `Vec` represented the transaction level instructions and the inner `Vec` the CPI instructions, the `instruction_stack` had the index into the outer `Vec` as the first entry and indices into the inner `Vec` for every following entry.
Now, both levels are collapsed into one homogeneous `instruction_trace` and `instruction_stack`. No information is lost by removing the partitioning of the outer `Vec`, because `InstructionContext` has a `nesting_level` …
> Refactor: Flattens `TransactionContext::instruction_trace`

- runtime/src/accounts_db.rs
While analyzing startup time, identified `clean_accounts` as a function that gets called several times, especially while shrinking slots. Execution time varies and depends heavily on key count, but takes on the order of seconds. Dirty store processing itself (part of `construct_candidate_clean_keys`) was taking multiple seconds. It also takes a couple of seconds to return from `construct_candidate_clean_keys`
1. Parallelize dirty store key insertion <-- saves a few seconds per call
2. "inline" `construct_candidate_clean_keys` into `clean_accounts` <-- saves a couple seconds per call
> Parallel insertion of dirty store keys during clean

- runtime/src/accounts_db.rs
> cleanup comment on filter_zero_lamport_clean_for_incremental_snapshots

- runtime/src/accounts_db.rs
> remove inaccurate log

- runtime/src/bank.rs
- runtime/src/vote_account.rs
Invalid cached vote accounts is over-counting actual mismatches, and
invalid cached stake accounts is under-counting.
patched invalid cached vote/stake accounts metrics
> patches metrics for invalid cached vote/stake accounts

- cli/src/program.rs
`solana deploy --help` made no mention of deploy being non-upgradeable and the preferred operation is `solana program deploy`
Updated the subcommand 'about' text to give more information
Fixes #27228
> Update `solana deploy` subcommand to warn non-upgradable

- runtime/src/stakes.rs
Need to verify that cached vote accounts are consistent with accounts-db
The commit adds sanity checks that when loading a bank from snapshots:
* cached vote accounts are consistent with accounts-db.
* all valid vote-accounts referenced in stake delegations are already
cached.
> checks that cached vote accounts are consistent with accounts-db

- runtime/src/accounts_db.rs
`mark_old_slots_as_dirty` never had a None `slots_per_epoch` passed to it
Make `slots_per_epoch` a required parameter
Fixes #
> slots_per_epoch shouldn't be optional

- core/src/validator.rs
Threads in the global Rayon pool are now named, `solRayonGlob{:02}` instead of the less useful default name of `solana-validato`.
> Assign custom names to the Rayon global thread pool

- cli/src/address_lookup_table.rs
- cli/tests/address_lookup_table.rs
- programs/address-lookup-table-tests/tests/create_lookup_table_ix.rs
- programs/address-lookup-table/src/instruction.rs
- programs/address-lookup-table/src/processor.rs
- sdk/src/feature_set.rs
Since lookup tables are derived from a recent slot, it's difficult to time a transaction that creates an address lookup table account controlled by a multisig or governance program. This is due to the create lookup table instruction requiring the authority to be a signer.
- Allow address lookup tables to be created for an authority without requiring the signer to sign
- Make lookup table creation idempotent so that lookup table creation can't be failed from front-running
Feature Gate Issue: https://github.com/solana-labs/solana/issues/27205
> Relax authority signer check for lookup table creation

- runtime/src/execute_cost_table.rs
> Remove redundant and stale comment

- docs/src/developing/clients/jsonrpc-api.md
As per https://github.com/solana-labs/solana/pull/27191#issuecomment-1217627061, there is nothing outside of code that documents for which accounts and instructions RPC nodes will return JSON parsing.
Add a section to the JSON-RPC docs with additional info and support table.
> Add documentation for JSON parsing

- core/src/validator.rs
Remove some log lines, as suggested in PR #26910
path renaming may fail in the /mnt/account case. 
Fall back to synchronous rmdir call if the path renaming fails.
Fixes #
> Fallback to synchronous rm_dir call if path moving fails

- program-runtime/src/pre_account.rs
- program-runtime/src/timings.rs
- runtime/src/bank.rs
- sdk/src/transaction_context.rs
See #26990
Removes `total_data_size` and `data_size_changed` from `ExecuteDetailsTimings`.
Fixes #26990
> Remove `total_data_size` and `data_size_changed` from `ExecuteDetailsTimings`

- runtime/src/accounts_db.rs
Without this, ALL ancient append vecs are enqueued for clean each time hash calc runs. This is not sustainable.
Fixes #
> don't mark ancient append vecs as dirty wrt clean

- tokens/src/commands.rs
- tokens/src/main.rs
`solana-tokens` installs a handler for Ctrl-C so that the db is cleaned up nicely. However, querying balances does not check the `exit` flag, so it will not terminate early gracefully.
This is an issue with a lot of accounts (like when doing a feature proposal for 3100+ validators).
Pass the `exit` flag when querying balances.
> Allow Ctrl-C when querying balances

- storage-bigtable/src/bigtable.rs
- storage-proto/src/convert.rs
Clippy warnings are annoying after #27303 
Ignore the warning, as per reccomended from a prost maintainer: https://github.com/tokio-rs/prost/issues/661
Fixes #
> ignore clippy derive_partial_eq_without_eq in prost generated code

- runtime/src/accounts_db.rs
instead of a count per store_id, we only need 0 or non-zero once the calculations are complete. So, if we discover a store that cannot be removed, we can remove the entry for the store_id completely, and that corresponds to non-zero and 'cannot delete this store'
Fixes #
> clean optimization for store count

- programs/bpf_loader/src/syscalls/mod.rs
- sdk/src/feature_set.rs
Currently the `get_processed_sibling_instruction()` syscall only stops its search at top level instructions. This is a bit inconsistent and it should be interrupted whenever the current level hits a gap.
`break` the reverse search at the rising edge (in trace recording direction) from `nesting_level - 1` to `nesting_level`.
Feature Gate Issue: #27289
> Feature: `stop_sibling_instruction_search_at_parent`

- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
See #27212
If we save these new fields in 1.11, then 1.10 will be unable to load snapshots created in 1.11
In 1.11, just READ the new fields, but do not write them.
Fixes #
> only READ BankIncrementalSnapshotPersistence in 1.11

- zk-token-sdk/src/sigma_proofs/fee_proof.rs
The transcript that is used in sigma proofs is not constant-time conditionally selectable. This results in the fee sigma proof generation to execute in non-constant time.
Remove transcript from being assigned conditionally by hashing proof values into the transcript twice. This allows proof generation to run in constant time at a small cost of a few additional hashes.
> zk-token-sdk: remove non-constant time assign for fee_proof transcript

- core/src/replay_stage.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- runtime/src/vote_parser.rs
- sdk/program/src/vote/state/mod.rs
- transaction-status/src/parse_vote.rs
When converting between `VoteStateUpdate` and `CompactVoteStateUpdate` we perform unchecked arithmetic which could cause overflow and liveness issues in debug builds. 
Check overflow 
Fixes #
> Check overflow on vote tx compaction boundary

- zk-token-sdk/src/range_proof/inner_product.rs
Currently, non-constant time multiscalar multiplication `VartimeMultiscalarMul` is used for inner product proof generation/verification for range proof. This is fine for range proof verification since verification is public, but this could theoretically result in a security vulnerability for proof generation.
Use `MultiscalarMul` as opposed to `VartimeMultiscalarMul` for inner product proof generation.
> zk-token-sdk: use constant-time msm for inner product proof generation

- zk-token-sdk/src/instruction/transfer_with_fee.rs
The fee calculation when producing zk-proofs for the fees involve conditional branches, which results in non-constant-time execution. This could theoretically reveal information about the transfer amount.
Instead of dividing and checking whether remainder is zero, add by (dividend-1) and then divide. This results in a simpler round-up division without conditional branches.
The `checked_div` operation may still be implemented as non-constant-time ops by the rust compiler. Making the fee calculation completely constant-time will require a new division implementation. Since timing attacks are generally theoretical vulnerabilities, we opt to still use `checked_div` and then provide sufficient warning on non-constant-time execution for fee calculation.
> zk-token-sdk: calculate transfer fee without conditional branch

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
Authenticated encryption and ElGamal secret key can be derived from the signing key for easier key management. Currently, the key derivation function runs in non-constant-time since it uses the vanilla bit-wise equality check.
Use the constant time equality provided by the `subtle` crate for key derivation.
> zk-token-sdk: constant time equality check for elgamal and aes key derivation

- multinode-demo/validator.sh
- net/net.sh
- net/remote/remote-node.sh
Support passing --tpu-disable-quic in validator launched by net scripts
> Support tpu disable quic in net scripts

- Cargo.lock
- docs/src/developing/clients/jsonrpc-api.md
- programs/bpf/Cargo.lock
- transaction-status/Cargo.toml
- transaction-status/src/lib.rs
- transaction-status/src/parse_address_lookup_table.rs
- transaction-status/src/parse_instruction.rs
RPC nodes parse address-lookup-table accounts, but not instructions
Add parser for address-lookup-table instructions
https://github.com/solana-labs/solana/pull/27268 needs updating
> Parse address-lookup-table instructions

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/connection.ts
- web3.js/src/utils/__forks__/react-native/url-impl.ts
- web3.js/src/utils/makeWebsocketUrl.ts
- web3.js/src/utils/url-impl.ts
- web3.js/test/makeWebsocketUrl.test.ts
- web3.js/yarn.lock
The `URL` class is not available in all runtimes, namely React Native. For this, web3.js currently depends on a polyfill.
Thing is, our use of `URL` is very constrained:
* Determine if a URL is valid
* Determine if a URL starts with `https:`
* Parse the port number out of a URL and modify it
I'm all for relying on built-ins, but when the built-in doesn't exist on a target platform, it's worth taking a look at whether you can get away with a minimal implementation of it rather than a full polyfill.
* Eliminate the dependency on the `URL` class in favor of purpose-built userspace implementations of URL parsing.
* Remove React Native `URL` polyfill and regenerate lockfiles
* Search for `new URL` in `src/`; no more uses.
Addresses #26904
Closes: #27001
> [web3.js] Eliminate dependency on `URL` class

- storage-bigtable/src/bigtable.rs
- storage-bigtable/src/lib.rs
`BigTable::get_row_*` apis unexpected return data when a limit of zero is passed.
Update two apis to respect the zero limit
> Update BigTable apis to respect a limit of zero

- docs/sidebars.js
- docs/src/cluster/commitments.md
- docs/src/implemented-proposals/commitment.md
- docs/src/terminology.md
Very little information on the commitment statuses
- added a commitment doc (with the summary table from trent [here](https://solana.stackexchange.com/questions/1760/commitment-processed-vs-confirmed-vs-finalized/2199#2199))
- added this new page the the "architecture/consensus" sidebar area
- added commitment to the terminology page
- minor typo fixes
> [docs] added commitment page

- programs/vote/src/vote_state/mod.rs
- sdk/src/feature_set.rs
https://github.com/solana-labs/solana/issues/27361
Set root to largest slot in VoteState less than the proposed root
Fixes #
> Handle VoteStateUpdates for outdated roots bigger than slots in existing VoteState

- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/pedersen.rs
- zk-token-sdk/src/sigma_proofs/equality_proof.rs
- zk-token-sdk/src/sigma_proofs/fee_proof.rs
- zk-token-sdk/src/sigma_proofs/validity_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
Currently, the decoding of some of the cryptographic objects in the zk-token-sdk could panic when the supplied byte slice is of different size.
Add length checks on slices during decoding of cryptographic objects.
> zk-token-sdk:add length checks

- web3.js/src/layout.ts
- web3.js/src/message/index.ts
- web3.js/src/message/legacy.ts
- web3.js/src/message/v0.ts
- web3.js/src/message/versioned.ts
- web3.js/src/transaction/constants.ts
- web3.js/src/transaction/index.ts
- web3.js/src/transaction/versioned.ts
- web3.js/test/connection.test.ts
- web3.js/test/message-tests/v0.test.ts
- web3.js/test/transaction.test.ts
Can't create version 0 transactions with web3
- Added `VersionedMessage` type which can be used to represent legacy or v0 messages
- Added `VersionedTransaction` class which is message version agnostic by using `VersionedMessage`
- Added `MessageV0` class to serialize/deserialize v0 messages
- Implemented serialization/deserialization for v0 transactions and messages
- Introduced `MessageCompiledInstruction` type as a successor to the `CompiledInstruction` type because it's inefficient and unnecessary to encode instruction data as a base58 string
Fixes #
> feat: add support for creating version 0 transactions

- bench-tps/src/bench_tps_client.rs
- bench-tps/src/bench_tps_client/bank_client.rs
- bench-tps/src/bench_tps_client/rpc_client.rs
- bench-tps/src/bench_tps_client/thin_client.rs
- bench-tps/src/bench_tps_client/tpu_client.rs
It turned out that requesting durable nonce blockhashes one by one is too expensive. 
By requesting 100 of them (maximum possible), tps is x3 higher.
These changes will be used for https://github.com/solana-labs/solana/pull/27151
In particular, at this line: https://github.com/solana-labs/solana/blob/19de07a98633fd21e9a6ca100a2a0f1bd3f15c7b/bench-tps/src/bench.rs#L549
* add `get_multiple_accounts` to BenchTpsClient`
* note, that this method is not implemented for `BankClient` because neither `SyncClient` nor `AsyncClient` doesn't have it
> add get_multiple_accounts to BenchTpsClient

- cli/src/clap_app.rs
- cli/src/cli.rs
- cli/src/main.rs
- cli/src/program.rs
Program deploy uses UDP transaction send and has no QUIC path.
Add --use-quic flag so that `solana program deploy` can use QUIC to send transactions.
Fixes #
> Add use-quic flag to allow for using quic in program deploy

- ledger/src/blockstore_processor.rs
We potentially run accounts hash/capitalization verification from two places at almost the same time, which seems wasteful and appears to slow down startup by ~30 seconds (Takes ~2 minutes on current master and ~1.5 minutes after this change). Here is the call stack for each:
Wait for any existing verifications to complete. Only check capitalization from `process_blockstore_from_root` in the event we loaded frozen bank forks
> Attempt to skip redundant startup account verification

- rpc-test/tests/rpc.rs
I found that we send all transactions before all subscriptions setup sometimes. it will cause a situation like:
1. send create account tx
2. tx confirmed and account has created
3. setup account subscription
Obviously it is an endless waiting and I think it is the culprit to incur test_rpc_subscriptions is so flaky.
I send account creating transactions after all subscriptions have setup.
btw, I have a variable do clone and clone. I think it should have a better way to do it.
> fix test_rpc_subscriptions

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/src/programs/secp256k1.ts
- web3.js/src/publickey.ts
- web3.js/src/utils/secp256k1.ts
- web3.js/test/program-tests/secp256k1.test.ts
- web3.js/yarn.lock
Notwithstanding the fact that the `web3.js` library arguably should not _include_ the `Secp256k1Program` utilities (they should be their own package) the dependency tree that utility pulls in is massive. This PR aims to replace the signing and hashing algorithms therein with smaller ones having fewer dependencies.
* Replaced `@ethersproject/sha2` with `@noble/hashes/sha256`
* Replaced `secp256k1` with `@noble/secp256k1`
Published the development build to npm and compared it to the latest version [using bundlephobia](https://bundlephobia.com/package/@solana/web3.js@1.53.0).
|Before|After|
|---|---|
|<img width="2087" alt="image" src="https://user-images.githubusercontent.com/13243/186546033-49797678-1ed9-4226-8dab-65b713d4a0c6.png">|<img width="2118" alt="image" …
> [web3.js] Replace sha256 and secp256k1 impls

- tpu-client/src/connection_cache.rs
- tpu-client/src/nonblocking/quic_client.rs
Currently chunking is broken for quic batch send. The chunk size represents the number of concurrent streams, not the number of chunks, since we iterate through all the chunks one at a time, and call join_all on the elements of each chunk (which schedules them all concurrently on the runtime). We currently target number of chunks, rather than chunk size, meaning that with a larger number of chunks (such as with staked nodes), each chunk is actually smaller, meaning staked nodes actually open fewer streams at the same time.
Fix the quic batch send chunking
Fixes #
> Fix quic staked chunking

- rpc/src/transaction_status_service.rs
- runtime/src/message_processor.rs
- sdk/program/src/message/sanitized.rs
- sdk/program/src/message/versions/v0/loaded.rs
- sdk/src/transaction/sanitized.rs
Would be good if `SanitizedMessage` can cache writable accounts for reusing, cause repeatedly calling `is_writable()` can be costly.
- Add `is_writable_account_cache: Vec<usize>` to `SanitizedMessage` variants. 
- Call `is_writable()` once during construction to populate `is_writable_account_cache: Vec<usize>`
- Add test
Comments from #27263 ,
> Add a SanitizedMessage type that caches writable accounts indexes

- core/src/validator.rs
If the validator does not have permission to delete the directory passed with the `--accounts` arg the validator will panic on startup.
Catch error and log warning.
I'm starting this on mce2 at the moment. It's past the warning and looks good but I'll wait for it to catch up to be sure.
Fixes #27350
> Fix startup panic if removing accounts directory fails

- send-transaction-service/src/send_transaction_service.rs
RPC STS ignores app exit, zombieing the process in some fatal error cases
check exit signal in tx receiver thread loop
> rpc-sts: respect app exit in tx receiver thread

- web3.js/package-lock.json
- web3.js/package.json
- web3.js/rollup.config.js
- web3.js/yarn.lock
I always forget to do this, and there's no static analysis to stop this mistake from being made.
```
yarn build
```
Inspect ESM bundles in `/lib/`. Observe that `@noble/hashes` and `@noble/secp256k1` are no longer inlined.
> Update rollup script to exclude new secp256k1 and hmac/sha256 dependencies

- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- local-cluster/src/validator_configs.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
- validator/src/main.rs
Concurrent slot replay has been merged but is currently not active and controlled by a feature switch. Feature switch is unnecessary in this case, and parameter would allow some set of validators to opt in to testing this capability.
Add `replay_slots_concurrently` parameter to enable replaying of slots from different forks concurrently during replay stage.
> Switch concurrent replay from feature to param

- bench-tps/src/bench.rs
- bench-tps/src/cli.rs
- bench-tps/src/send_batch.rs
Final PR in the [chain of PRs](https://github.com/solana-labs/solana/issues/25759) adding durable nonce transactions to bench-tps.
~Requires https://github.com/solana-labs/solana/pull/27176~
Requires https://github.com/solana-labs/solana/pull/27379
* Introduce `--use-durable-nonce` option to cli
* Request durable nonce in a loop
TPS is now ~5k
Some plots with running with this option:
The bottom plot is for data shreds: at the beggining there are many data shreds because we create nonce durable accounts. During transactions execution this metric is lower.
If we zoom into the transaction phase, we observe that the tps is spiky:
It happens because it takes time to request blockhashes before executing transactions
> add use_durable_nonce option

- Cargo.lock
- programs/bpf/Cargo.lock
- runtime/Cargo.toml
https://rustsec.org/advisories/RUSTSEC-2022-0051.html
bump `lz4-sys` to v1.9.4
> bump `lz4-sys` to 1.9.4 as per RUSTSEC-2022-0051

- web3.js/src/message/versioned.ts
- web3.js/test/message-tests/versioned.test.ts
Lack of utility function to check the version of a serialized message without fully deserializing the message
- Added `VersionedMessage.deserializeMessageVersion`
Fixes #
> feat: add VersionedMessage.deserializeMessageVersion utility function

- docs/src/terminology.md
Terminology about PDA confuses owner and authority.
Replaced "An account whose owner is a program" by "An account whose **signing authority** is a program"
> [docs] Terminology PDA - replace owner by authority

- core/src/validator.rs
- runtime/src/accounts_background_service.rs
In kin-sim, we found that bounded channel causes halt for account
background services. As the number of accounts grows, the time for
pruning and cleaning increases, which would leads to longer intervals
between the pruning of deaded bank slots. With 1.7B accounts, we will
exceed the 10K bounded channel threshold that causes halt of account
back ground services. Without pruning, the node will eventually run out
of memory.
> make pruned_bank channel unbounded.

- runtime/src/accounts_db.rs
ancient shrink combines parts of shrink and clean.
When a slot gets old, we remove its alive contents and put it into an ancient append vec in a prior slot. When we remove all storages from a slot, the slot is now not useful. Clean removes dead slots in a similar way. When it does so, the mechanism to get rid of a bank hash entry for that slot runs. This same mechanism needs to run when we combine an old slot's data into an ancient append vec.
Fixes #
> remove old bank hashes with ancient shrink

- banking-bench/Cargo.toml
- banks-server/Cargo.toml
- bench-tps/Cargo.toml
- client-test/Cargo.toml
- core/Cargo.toml
- dos/Cargo.toml
- gossip/Cargo.toml
- install/Cargo.toml
- local-cluster/Cargo.toml
- rpc-client-nonce-utils/Cargo.toml
- rpc-client/Cargo.toml
- rpc-client/src/nonblocking/rpc_client.rs
- rpc-client/src/rpc_client.rs
- rpc-client/src/spinner.rs
- rpc-test/Cargo.toml
- rpc/Cargo.toml
- send-transaction-service/Cargo.toml
- test-validator/Cargo.toml
- thin-client/Cargo.toml
- tpu-client/Cargo.toml
- tpu-client/src/nonblocking/tpu_client.rs
- tpu-client/src/tpu_client.rs
- transaction-dos/Cargo.toml
- validator/Cargo.toml
- watchtower/Cargo.toml
As per https://github.com/solana-labs/solana/pull/27246#discussion_r953005270, the client progress bars pull in dependencies that are only useful when building a command-line tool.
Wrap `spinner` module and client methods that use it in a `spinner` feature in rpc-client and tpu-client
This is currently an "opt-out" feature (on by default); I went back and forth on this, but landed on this direction because I was worried that docs.rs wouldn't display the docs for the feature-wrapped apis if spinner was off by default
Toward #27352
> Featurize spinner in rpc-client and tpu-client

- bench-tps/tests/bench_tps.rs
- dos/src/main.rs
- gossip/src/cluster_info.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_slow_1.rs
- local-cluster/tests/local_cluster_slow_2.rs
Enabling quic by default broke multiple tests. See issues #27160 and #27165
Bind to 127.0.0.1 instead of 0.0.0.0
> Fix test_bench_tps_local_cluster_solana

- validator/src/main.rs
Restarts using just a full snapshot will put the node significantly further behind than if an incremental snapshot is also used, as full snapshots are larger and take much longer to create.
Therefore if the node just created a new full snapshot, wait a little longer until it creates the first incremental snapshot for the full snapshot.
> `solana-validator exit`: Wait for first incremental snapshot after a full snapshot before restarting

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
Avoid grabbing a read lock on the slot list when all we want to do is unref.
An enum with a fn may be more clear here, but it didn't seem worth the effort to wrestle with the compiler.
Fixes #
> get rid of acquisition of read lock while unrefing accounts in scan

- runtime/src/accounts_db.rs
ancient shrink combines parts of shrink and clean.
When a slot gets old, we remove its alive contents and put it into an ancient append vec in a prior slot. When we remove all storages from a slot, the slot is now not useful. Clean removes dead slots in a similar way. When it does so, the removal of the hashmap entry from that slot to a now empty set of storages runs. This same mechanism needs to run when we combine an old slot's data into an ancient append vec.
Fixes #
> remove storages that only contain empty

- runtime/src/accounts_db.rs
`unref_accounts` was recently refactored. It had a long standing bug in it where if caller asked to unref > 10k accounts, the accounts past 10k would not be unref'd. That bug has been fixed.
add tests
Fixes #
> add tests to AccountsDb::unref_accounts

- ledger/src/shred/shred_code.rs
- ledger/src/shredder.rs
Currently magic number exists for defining max code shreds.
Replace magic number 17 with source of this number (worst case code to data shred ratio).
> Minor shred constant cleanup

- ci/buildkite-pipeline.sh
downstream-projects stage of CI has been failing intermittently due to timeout issues.
Example:
https://buildkite.com/solana-labs/solana/builds/80851#_
Increase timeout from 30 mins to 35 mins
> Increase downstream-projects timeout

- ledger/src/blockstore.rs
- ledger/src/blockstore/blockstore_purge.rs
- ledger/src/blockstore_db.rs
RocksDB's delete_range applies to [from, to) while delete_file_in_range
applies to [from, to] by default, and the rust-rocksdb api does not include
the option to make delete_file_in_range apply to [from, to).  Such inconsistency
might cause `blockstore::run_purge` to produce an inconsistent result as it
invokes both delete_range and delete_file_in_range.
rocksdb::DeleteRange
https://github.com/facebook/rocksdb/blob/91166012c848f720f0208e91d766810d4f7e8cf9/include/rocksdb/db.h#L463-L479
rocksdb::DeleteFilesInRange
https://github.com/facebook/rocksdb/blob/91166012c848f720f0208e91d766810d4f7e8cf9/include/rocksdb/convenience.h#L496-L503
and rocksdb's c api hides the `include_end` default param, defaulting to `= true`....
https://github.com/facebook/rocksdb/blob/91166012c848f720f0208e91d766810d …
> Fix the boundary inconsistency between delete_file_in_range and delete_range

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
Methods like `Connection.getTransaction` and `Connection.getBlock` support the `maxSupportedTransactionVersion` config but the return type contains a `Message` class which doesn't support versioned messages.
- Deprecate the usage of `getTransaction`, `getTransactions`, and `getBlock` RPC APIs without passing a `maxSupportedTransactionVersion` in the config
- Add support for versioned transaction fields in `getTransaction`, `getParsedTransaction`, `getBlock`, and `getTransactions` responses
This change is *not* a breaking change because the responses for the modified `Connection` methods only include a versioned message when a user opts into receiving versioned transactions with the `maxSupportedTransactionVersion` config.
Fixes #
> feat: update `Connection` to support versioned transactions

- runtime/src/accounts_index.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/in_mem_accounts_index.rs
In mem acct idx holds items in memory for at most 255 'ages'. An age is 400ms, so correlates to slot time.
We hold in-mem anything with a slot list len > 1 or with a cached item.
Bg threads have to go through all in-mem entries to figure out what to throw out. Items that are put into memory with cached items especially are unlikely to be flushed for approximately 100 slots into the future. This means the bg threads will continually check to see if they can be thrown out yet, only to find out 'no' and punting them 5 more slots into the future. When the write cache is flushed, the index is updated with non-cache append vec ids and eviction is scheduled for the normal 5 slots in the future.
It is better to have a mechanism where if we know a cached item is being added, we set the age to try …
> delay trying to flush cached upserts until far future

- ci/run-local.sh
The `run-local` CI script does not have the correct steps for local-cluster-slow.
Update steps.
> ci: Fix steps in run-local

- runtime/src/message_processor.rs
- sdk/src/transaction_context.rs
There are lots of methods and structs in transaction_context.rs which are not meant to be compiled into SBF programs. Some are runtime only, others need a special (syscall based) implementation.
`TransactionContext::get_keys_of_accounts()` returns a slice, but we won't be able to guarantee consecutive memory allocations once memory is shared with the SBF programs. Returning an iterator instead would be possible and such a helper method might be introduced later, once we start porting the SPL to ABIv2 and finalize the internal structures.
- Marks methods and structs which are only to be used by the program runtime.
- Removes `TransactionContext::get_keys_of_accounts()`.
> Refactor: `TransactionContext` ABIv2 adjustments

- sdk/src/commitment_config.rs
The `CommitmentConfig` constructors cannot be used in const contexts. This isn't a big problem because `CommitmentConfigs`'s only field is public, so sdk users can just use e.g. `CommitmentConfig{commitment: CommitmentLevel::Finalized}` instead of `CommitmentConfig::finalized()`, but using the latter would be a bit more convenient and there aren't any obvious-to-me reasons not to make the functions `const`.
Make the constructors `const`.
Fixes #
> Make CommitmentLevel constructors const

- runtime/src/snapshot_utils.rs
```
thread 'snapshot_utils::tests::test_incremental_snapshots_handle_zero_lamport_accounts' panicked at 'SharedBufferReaders must all be created before the first one reads', runtime/src/shared_buffer_reader.rs:324:17
```
Create all shared buffer readers before spawning threads for unpacking snapshots.
Fixes #
> Create all shared buffer readers before spawning threads

- ci/shellcheck.sh
- net/gce.sh
- net/net.sh
- net/scripts/colo-node-onfree.sh
- system-test/testnet-automation.sh
Seems we used v0.7.0 shellcheck and the current stable version is v0.8.0.
1. use shellcheck v0.8.0
2. fix some info/warn after upgrade.
- add quote to variable 
- rename a variable, `FORCE_DELETE`, to prevent self assignment
- ignore check for `eval ... $@`
- use `$*` to replace `$(eval echo "$@")`
> chore: bump shellcheck v0.8.0

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
In kin sim, we notice that account db clean time can reach 52 minutes. Add a report to track the number of dirty slots to clean during hash calculation.
> Report number of dirty slots for cleaning during hash calculation

- runtime/src/accounts_db.rs
Ancient append vec code only runs occasionally and only after long intervals.
This makes it difficult to gain confidence that it is correct.
Randomly shrink ancient appendvecs during normal processing, prior to them becoming full. This allows for exercising the code paths more often.
Fixes #
> randomly shrink ancient append vecs

- runtime/src/bank.rs
- runtime/src/serde_snapshot/newer.rs
We need to add Option<Hash> representing the epoch accounts hash into the snapshot persistence so it can be used later.
#26847
Doing the deserialize first in its own pr.
This can be easily backported without separating out the serialization part in the backport.
Fixes #
> deserialize(or eof) snapshot epoch_accounts_hash

- web3.js/src/connection.ts
The auto-complete of my editor did not show the computeUnitsConsumed field.
Tested with this example script:
```
import { Connection } from "@solana/web3.js";
async function main() {
const conn = new Connection("https://testnet.rpcpool.com");
const commitment = "confirmed";
const version = await conn.getVersion();
console.log({ version });
const slot = await conn.getSlot(commitment);
console.log({ slot });
const block = await conn.getBlock(slot, { commitment });
console.log({ block });
const tx = block?.transactions[0];
console.log("tx", tx);
}
main();
```
> fix: add compute units to jsonrpc parser

- bench-tps/src/bench_tps_client/tpu_client.rs
- tpu-client/src/nonblocking/tpu_client.rs
- tpu-client/src/tpu_client.rs
The `bench-tps` performance is not great when QUIC is used for sending transactions.
The client was sending individual transaction from batch one at a time, and waiting for the QUIC to finish sending it. This throttles the transaction send rate.
This PR implements a `batch_send` wrapper using the existing client APIs, and uses that that in the bench-tps client.
Fixes #
> Use batch send in bench-tps to send transactions

- docs/src/developing/clients/jsonrpc-api.md
`JSON RPC API` had object member name typo, basically `account_keys` and `accountKeys` were pointing towards same property of the object `accountKeys`. In the `getBlock` method request parameter, the `commitment` parameter was defined without providing the argument name. Upon misinterpretation it will cause JSON parse error.
Fixes #
- Changed `account_keys` to `accountKeys`
- added argument name `commitment` after testing the request parameters.
> Fixed typo and json standards in the document

- sdk/program/src/entrypoint.rs
- sdk/program/src/log.rs
- sdk/program/src/program.rs
Rust 1.63 appears to fixed some bugs in macro doc link resolution. This makes these links work again.
Fixes #
> Fix broken macro doc links

- core/src/validator.rs
- rpc/src/rpc_subscriptions.rs
See #27480. CI test flakiness
have `new_with_config` optionally signal back to callers when RPC Notifier thread pool routine has been installed. Have tests wait for setup to complete before proceeding with next steps.
Have `new_for_tests` call `new_for_tests_with_blockstore` to reduce redundant code
> RPC Notifier Signal when Setup Complete

- scripts/coverage.sh
We can't read logs from a failed coverage test cuz we redirect stderr to a file. when it failed, it didn't upload the file.
This change will make this test become very noisy. It prints a lot of things due to `RUST_LOG=solana=trace`.
Tee target/cov/coverage-stderr.log
> chore: tee coverage test stderr

- docs/src/developing/clients/jsonrpc-api.md
https://github.com/solana-labs/solana/pull/27557 fixed some inconsistencies around `commitment` format in the JSON-RPC docs, but there are a bunch more
Make commitment config handling consistent
Add a missing `minContextSlot` config param
Make `(optional)` tag placement consistent across all parameters and fields
Fixes #
> Fixup docs formatting re: commitment configuration

- runtime/src/prioritization_fee_cache.rs
async `update()` in test could panic 
- call `sync_update()` instead in test
Fixes #
> fix a flacky test

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/vote/benches/process_vote.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/nonce_keyed_account.rs
- sdk/src/transaction_context.rs
Preparation for ABIv2 so that SBF programs can write into the last `InstructionContext` of the `TransactionContext::transaction_trace` directly. This way the CPI syscall of ABIv2 does not need to copy any `Instruction` data (see https://github.com/solana-labs/solana/issues/27384).
- Replaces `InstructionContext::new()` by `InstructionContext::configure()`.
- Adds `TransactionContext::get_next_instruction_context()`.
- Hoists `InstructionContext::configure()` from `TransactionContext::push()` and `InvokeContext::push()` into `InvokeContext::process_instruction()`.
- Switches back to using references as parameters for `InstructionContext::configure()`.
> Refactor: `InstructionContext::configure()`

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/stake/src/stake_instruction.rs
- programs/vote/src/vote_processor.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
Preparation for upcoming refactoring.
- Lets `instruction_accounts_lamport_sum()` have the `&InstructionContext` as parameter directly.
- Updates docu comments.
- Uses accessors methods instead of accessing private properties of other structs.
- Adds `#![deny(clippy::indexing_slicing)]`.
- Has `InstructionContext::get_signers()` return a `Result` instead of using `unwrap()`.
- Removes `InvokeContext::get_key_of_account_at_index()`.
> Cleanup: `TransactionContext`

- explorer/src/components/account/OwnedTokensCard.tsx
- explorer/src/providers/accounts/tokens.tsx
Explorer hangs when viewing the token holdings of accounts with many tokens like the incinerator account.
Truncate token holdings and hide token holdings if an account has over 100 tokens
Fixes #
> explorer: Don't show token holdings for accounts with too many tokens

- transaction-status/src/lib.rs
- transaction-status/src/parse_accounts.rs
The `jsonParsed` encoded response for versioned transactions and blocks doesn't include account keys resolved from lookup tables in the parsed message account keys list. I consider this a bug because the parsed message response is meant to be a user-friendly response which indicates all the account keys and whether they were writable or signers.
- Include resolved keys from table lookups in parsed message response
- Add `source` field to `ParsedAccount` to indicate whether the account key came from a transaction or lookup table
Fixes #
> RPC: include resolved keys from table lookups in parsed message response

- streamer/src/nonblocking/quic.rs
To address https://github.com/solana-labs/solana/issues/27597
It looks like with this fix number of connections is stable:
> fix total_connections metric

- ledger-tool/src/main.rs
- runtime/src/accounts_db.rs
- validator/src/main.rs
accounts index stores a refcount and a list of alive account info (store id, offset, size) for each pubkey. There is 1 refcount for each appendvec that references this pubkey.
There have been bugs with refcounts. Refcounts are used in clean to throw away old accounts.
In order to verify correctness, a full scan of all appendvecs must be performed. That is expensive and an ever moving target.
Add a debug option to exhuastively compare append vecs and the index's refcount as of a slot. This is enabled with a hiddent cli argument. This code could be useful in the future or to run periodically to ensure we are correctly handling all issues with refcounts.
Fixes #
> add --accounts-db-verify-refcounts for debugging

- local-cluster/tests/local_cluster.rs
Fixed the local-cluster test case test_optimistic_confirmation_violation_detection, which is an existing test issue exposed when we disable the udp based tpu port. In the test, when we restart the node, we restarted the entry point validator. And when the gossip port of the restarted node changes, the two nodes are not able to talk to each other via gossip. I have changed the restart the logic to make the second validator the heavier node and restart it instead of the entypoint one (the first node).
Fixes #
> Fixed the local-cluster test case test_optimistic_confirmation_violation_detection

- runtime/src/in_mem_accounts_index.rs
`InMemAccountsIndex::update_slot_list` is used by ancient append vecs, and later by flushing the cache, to move or merge account index entries from one slot to another. Account index entries keep 1 refcount for each slot that has an appendvec that contains account data. When we are doing `update_slot_list`, we need to addref if the new slot does not already contain a refcount. The situation that was missed was when the old slot already had a refcount, we did not want to add another refcount. The old slot will be going away, so any refcount from that old slot can be transferred to the new slot.
If an uncached entry already exists in the old slot, then don't addref.
Fixes #
> acctidx: avoid extra addref in combine ancient slots

- .buildkite/hooks/post-command
- ci/test-stable.sh
1. upload test results on edge, beta, and stable channel branches.
2. only matched branches generate test results. the other branches will run the original test command.
> chore: only generate test result on specific branches

- web3.js/src/message/account-keys.ts
- web3.js/src/message/compiled-keys.ts
- web3.js/src/message/index.ts
- web3.js/src/message/v0.ts
- web3.js/src/publickey.ts
- web3.js/test/message-tests/account-keys.test.ts
- web3.js/test/message-tests/compiled-keys.test.ts
- web3.js/test/message-tests/v0.test.ts
No easy way to create transactions with lookup tables
- Add `MessageAccountKeys` class to provide an abstraction over a message's static and dynamic (using lookup tables) account keys. This class is used during message compilation.
- Add `CompiledKeys` class to track account key metadata during message compilation. This is only intended for internal use.
- Add `MessageV0.compile` method for creating a v0 transaction message with address lookup tables. The `compile` method will attempt to load as many account keys as possible from the provided address lookup tables.
Fixes #
> feat: implement message v0 compilation

- web3.js/src/message/legacy.ts
- web3.js/src/message/v0.ts
- web3.js/src/transaction/index.ts
- web3.js/src/transaction/message.ts
- web3.js/test/message-tests/legacy.test.ts
- web3.js/test/message-tests/v0.test.ts
- web3.js/test/transaction-tests/message.test.ts
Lack of a common interface for creating and displaying transactions which supports both legacy and versioned transactions
- Add `TransactionMessage` class which can be used to construct or decompile legacy and v0 transactions.
- Add `Message.compile` method to the legacy message class to mirror the equivalent `MessageV0.compile` method added in https://github.com/solana-labs/solana/pull/27524
- Add `getAccountKeys` method to both `Message` and `MessageV0` classes for use in transaction decompilation and to allow devs to conveniently resolve account indexes with a common interface for legacy and versioned transactions
- Add `resolveAddressTableLookups` method to `MessageV0` which is used to decompile v0 transactions
Fixes #
> feat: add `TransactionMessage` class

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
Not possible to use the `Connection.sendTransaction` and `Connection.simulateTransaction` methods with versioned transactions.
- Deprecate the usage of `Connection.sendTransaction` and `Connection.simulateTransaction` without using a `VersionedTransaction` class.
- Deprecate the side effects of the above methods including "recentBlockhash" replacement and signing
Fixes #
> feat: support versioned txs in `sendTransaction` and `simulateTransaction`

- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_db.rs
This PR adds a ledger tool subcommand print-file-metadata.
```
USAGE:
solana-ledger-tool print-file-metadata [FLAGS] [OPTIONS] [SST_FILE_NAME]
Prints the metadata of the specified ledger-store file.
If no file name is unspecified, then it will print the metadata of all ledger files
```
Example output:
```
$ ./solana-ledger-tool print-file-info --ledger /mnt/disks/ledger/mainnet/
[/001434.sst] cf_name: meta, level: 0, start_slot: Some(143642862), end_slot: Some(143663961), size: 921933, num_entries: 983
[/001366.sst] cf_name: meta, level: 0, start_slot: Some(143642588), end_slot: Some(143663209), size: 935010, num_entries: 952
[/001284.sst] cf_name: meta, level: 0, start_slot: Some(143642308), end_slot: Some(143662497), size: 856478, num_entries: 910
[/001217.sst] cf_name: meta, level: 1, …
```
> Add ledger tool command print-file-metadata

- codecov.yml
Codecov doesn't actually pick up any code changes. It still thinks all the files live at `src/`.
* Give it the bad news.
> chore: tell Codecov about the web3.js move, a few years later

- web3.js/src/layout.ts
Imagine you have a data structure like this:
```
Layout.structure([
u8('instruction'),
Layout.structure([
rustString('variableSizeString'),
]);
]);
```
The present implementation of `getAlloc` will not dive into that inner structure and size it, so the total size of this entire layout will – incorrectly – be 1.
* When `getAlloc` encounters a structure it recurses into it to obtain its size.
> fix: recursively size variable size structs in your buffer layouts

- web3.js/src/layout.ts
- web3.js/src/programs/vote.ts
- web3.js/test/program-tests/vote.test.ts
Read all about what the `authorizeWithSeed` instruction is for, here. #25928.
* Added `VoteProgram.authorizeWithSeed`
* Added test for `VoteProgram.authorizeWithSeed`
Closes #25974.
> feat: added `authorizeWithSeed` to the vote program in web3.js

- transaction-status/src/lib.rs
Now that the `jsonParsed` accounts list[ includes the account source](https://github.com/solana-labs/solana/pull/27552) (transaction or address lookup-table), the `loadedAddresses` array is redundant.
Only return `loadedAddresses` when other types of encoding are requested.
> Skip loadedAddresses for jsonParsed tx meta

- validator/src/main.rs
clippy nightly is reccomending using `is_some()` and `is_none()` instead of checking `!= None` or `== None`.
I imagine this clippy change will make its way into stable, so just hitting it preemptively. 
Use `is_some()` and `is_none()` in validator's main.rs
Fixes #
> validator: clippy nightly fixes

- core/src/accounts_hash_verifier.rs
- core/tests/snapshots.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/epoch_accounts_hash.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
follow on to:
#27513
related to issue:
#26847
Write epoch_accounts_hash to serialization in snapshot.
For now, this always writes None.
Fixes #
> serialize epoch_accounts_hash

- core/src/accounts_hash_verifier.rs
- runtime/src/accounts_background_service.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
When we activate the feature #26491, we will no longer store accounts on rewrites during rent collection.
As a result, as of that moment, the hash value per account will be frozen forever until the account is written again. Thus, we need to disable the rehashing during the accounts hash as of this feature activation. To disable the rehashing, we need to be able to pass that to config for the accounts hash calculation. The requestor of the hash knows which bank to use and thus, whether a feature has been activated. As a result, if `enable_rehashing` is false, then whatever hash is found in the most recent append vec per account is used directly.
add `enable_rehashing` to `CalcAccountsHashConfig` for use on feature activation.
Fixes #
> allow accounts hash calc to specify enable_rehashing

- core/benches/shredder.rs
clippy nightly is reccomending using `is_some()` and `is_none()` instead of checking `!= None` or `== None`.
I imagine this clippy change will make its way into stable, so just hitting it preemptively. 
Use `is_some()` and `is_none()` in shredder.rs
Fixes #
> shredder: clippy nightly fixes

- core/src/replay_stage.rs
clippy nightly is reccomending using `is_some()` and `is_none()` instead of checking `!= None` or `== None`.
I imagine this clippy change will make its way into stable, so just hitting it preemptively. 
Use `is_some()` and `is_none()` in replay_stage.rs
Fixes #
> replay_stage: clippy nightly fixes

- core/src/cluster_slot_state_verifier.rs
clippy nightly is reccomending using `is_some()` and `is_none()` instead of checking `!= None` or `== None`.
I imagine this clippy change will make its way into stable, so just hitting it preemptively. 
Use `is_some()` and `is_none()` in cluster_slot_state_verifier.rs
Fixes #
> cluster_slot_state_verifier: clippy nightly fixes

- core/src/accounts_hash_verifier.rs
- core/tests/snapshots.rs
- runtime/src/accounts_background_service.rs
- runtime/src/accounts_db.rs
- runtime/src/bank_forks.rs
- runtime/src/lib.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_utils.rs
Accounts Background Services does not know about Epoch Accounts Hash.
Add an `EpochAccountsHash` request type to pass into ABS, and then plumb that through the the snapshot request handler, snapshot utils, and AccountsHashVerifier.
There's a lot changes due to plumbing, which makes this PR look big and noisy. I am happy to clarify any/all sections of code; whatever is helpful!
> Make Accounts Background Services aware of Epoch Accounts Hash

- web3.js/src/transaction/message.ts
- web3.js/test/transaction-tests/message.test.ts
The `accountKeys` field on `TransactionMessage` is redundant because the instructions already list all the account keys. Also, there is no easy way to get or set the `payerKey` on a `TransactionMessage` instance.
- Replace `accountKeys` with `payerKey`
Fixes #
> fix: replace `TransactionMessage` `accountKeys` field with `payerKey`

- runtime/src/rolling_bit_field.rs
from ci logs, it appears debug traces make it to the log. This one in particular is large.
comment out the debug log
Fixes #
> suppress large debug message on test

- core/src/unprocessed_packet_batches.rs
`UnprocessedPacketBatches::{pop_max, pop_max_n}` are only used by tests, and *should* only be used by tests. These provide a somewhat confusing interface, since when we are popping from the priority queue during banking stage we don't want to remove from the map until they are fully processed.
Remove pub, and mark as `#[cfg(test)]`.
Fixes #
> UnprocessedPacketBatches pop_max fn are only used in tests

- docs/src/developing/clients/jsonrpc-api.md
- ledger-tool/src/bigtable.rs
- transaction-status/src/lib.rs
The `getBlock` parameter `rewards` currently only affects whether block-level rewards are returned. Transaction-level rewards are returned regardless. While this isn't super critical with very few Rent payment, current behavior is a bit counterintuitive and may force clients to consume more data than they want to.
Pass `show_rewards` into UiTransactionStatusMeta constructors and only populate rewards when true.
Also fixup docs to be correct
> Respect rewards parameter in getBlock transaction-level rewards

- core/src/accounts_hash_verifier.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_utils.rs
The bank knows whether the skip rewrites feature is enabled or not. We need that information when we calculate the hash. It needs to go into `AccountsPackage`
add `enable_rehashing` to `AccountsPackage`
Fixes #
> add enable_rehashing to AccountsPackage

- ledger/src/shred/common.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/merkle.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shred/traits.rs
These methods are only used in tests but invoked on a merkle shred they will always invalidate the shred because the merkle proof will no longer verify. As a result the shred will not sanitize and blockstore will avoid inserting them. Their use in tests will result in spurious test coverage because the shreds will not be ingested.
The commit removes implementation of these methods for merkle shreds. Follow up commits will entirely remove these methods from shreds api.
> removes set_{slot,index,last_in_slot} implementations for merkle shreds

- web3.js/src/keypair.ts
- web3.js/test/keypair.test.ts
An unintended side effect of https://github.com/solana-labs/solana/pull/27435 is that the `Keypair.secretKey` property is no longer coerced into a `Uint8Array` and therefore the `toString` behavior has been changed.
Ensure that `Keypair.secretKey` is always a proper `Uint8Array` and not a `Buffer` in disguise
Fixes https://github.com/solana-labs/solana/issues/27684
> fix: ensure that Keypair.secretKey is a Uint8Array

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
The `source` field for parsed account keys is not made available by the sdk yet
- Parse the `source` of parsed account keys
Fixes #
> feat: add source field to parsed account key responses

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
add_un_ref makes it harder to tell at a glance where unref vs addrefs are coming from in the call hierarchy
Separate the functions as we never pass a variable to it.
Fixes #
> Separate add_un_ref for easier tracing

- web3.js/README.md
This was mostly so that there's a note about React Native compatibility in there.
Addresses: #27685.
> chore: update the README for web3.js with compatibility notes

- program-runtime/src/compute_budget.rs
- program-runtime/src/prioritization_fee.rs
- programs/bpf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/transaction_priority_details.rs
- sdk/src/compute_budget.rs
- sdk/src/feature_set.rs
Should remove `ComputeBudgetInstruction::RequestUnitsDeprecated`, need feature gate to stop supporting it.
- Pass `true` (existing behavior) to ComputeBudget::process_instructions() when new feature is not activated, pass `false`  (eg not supporting deprecated ix) when feature is activated. 
- Add `TODO` comments to replace deprecated enum variants, and remove deprecated code once feature's activated.
Fixes #27500
> Add feature gate to remove support for RequestUnitsDeprecated instruction

- merkle-tree/src/merkle_tree.rs
```
warning: binary comparison to literal `Option::None`
--> merkle-tree/src/merkle_tree.rs:157:32
|
157 |             if lsib != None || rsib != None {
|                                ^^^^^^^^^^^^ help: use `Option::is_some()` instead: `rsib.is_some()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#partialeq_to_none
```
Appease clippy
> Fix partialeq_to_none clippy lint

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
- runtime/src/snapshot_minimizer.rs
Validators can correctly delete an account from the accounts index, for example, because latest one has zero lamports.
While doing that (during clean):
1. Clean can first figure out that the slot list has become empty and remove the pubkey entirely from the accounts index.
2 Clean later calls unref on the pubkey in the accounts index. Normally, the pubkey is not in the accounts index anymore, so this unref is a no-op.
However, if a concurrent tx processing re-inserts the same pubkey (re-funds the account) between steps 1 and 2, then the unref in step 2 will be incorrect and will result in an under ref count for the pubkey in the accounts index.
This will later lead to throwing away accounts in clean that cannot be legally thrown away. This will result in capitalization mismatches when …
> clean race condition with extra unref

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
`AccountsIndex::roots_and_ref_count` was only called by test code.
move it to be a test only function.
Fixes #
> move fn only used by tests to tests

- core/src/validator.rs
- local-cluster/src/validator_configs.rs
- validator/src/main.rs
v1.11 and newer process the ledger on validator startup after networking services are started. Add the `--process-ledger-before-service` flag to revert back to the v1.10 ledger processing behaviour, which can be useful when comparing v1.10 startup performance to v1.11
> Add --process-ledger-before-service flag to solana-validator

- core/src/replay_stage.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/local_cluster_slow_1.rs
- runtime/src/bank.rs
- runtime/src/genesis_utils.rs
- sdk/src/signer/keypair.rs
See discussion in #26248
@behzadnouri 
I didn't use `mock_clone()` because it doesn't have something to do with mocks, and the insecure wording stands out more.
> Remove KeypairInsecureClone trait and add insecure_clone() instead

- explorer/src/scss/_solana.scss
The responsive is broken in metaplex metadata json viewer.
Fixed responsive for metadata metadata json view.
> Fix responsive in metaplex metadata json viewer

- core/src/consensus.rs
- core/src/replay_stage.rs
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- runtime/src/vote_parser.rs
- sdk/program/src/lib.rs
- sdk/program/src/serde_varint.rs
- sdk/program/src/vote/instruction.rs
- sdk/program/src/vote/state/mod.rs
- transaction-status/src/parse_vote.rs
`VoteStateUpdate` has large serialized size.
The commit removes `CompactVoteStateUpdate` and instead reduces serialized
size of `VoteStateUpdate` using varint encoding for vote-state lockout
offsets.
> uses varint encoding for vote-state lockout offsets

- programs/vote/src/vote_state/mod.rs
if let destructuring within for loop is not necessary and not efficient compared to move it out of for loop
move if let destructuring out of for loop
Fixes #
> move if let destructuring out of for loop

- ledger/src/blockstore_processor.rs
when running final hash calculation after ledger tool halts at a slot, we used to allow the hash calculation to use the write cache. This is incompatible with dumping accounts hash final data to disk, which is an optional ledger tool argument for debugging.
After flushing the write cache, tell accounts hash calc it may not use the write cache (since there is nothing in the write cache anyway).
Fixes #
>  fix ledger tool final hash calc

- core/src/validator.rs
- core/tests/snapshots.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- local-cluster/tests/local_cluster.rs
- runtime/benches/accounts_index.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
- runtime/src/bank.rs
- runtime/src/bucket_map_holder.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
Acct idx spins up background threads for synchronizing with disk.
These threads need to quit when the validator says to quit.
https://discord.com/channels/428295358100013066/560503042458517505/1016840318840221726
Pass through an atomic bool that the threads will listen to.
Fixes #
> use exit signal for acct idx bg threads

- accounts-bench/src/main.rs
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
we will need to enable/disable rehashing during accounts hash calculation when we activate #26599
add parameter to various functions.
Fixes #
> pass 'enable_rehashing' through all accounts hash functions

- runtime/src/accounts_db.rs
This `info!()` log can pump out a log message thats ~500kb in length.
> Rework 'remove_dead_slots_metadata: slots' info log message

- ledger/src/blockstore.rs
- ledger/src/blockstore_db.rs
- ledger/src/blockstore_metrics.rs
Blockstore operations such as get_slots_since() issues multiple rocksdb::get()
at once which is not optimal for performance.
This PR adds LedgerColumn::multi_get() based on rocksdb::batched_multi_get(),
the optimized version of multi_get() where get requests are processed in batch
to minimize read I/O.
> (LedgerStore) LedgerColumn::multi_get()

- web3.js/src/programs/compute-budget.ts
- web3.js/test/program-tests/compute-budget.test.ts
Now that the request units instruction is deprecated by the runtime, the test validator fails any transactions which use it.
- Remove failing test 
- Mark `ComputeBudget.requestUnits` function as deprecated
Fixes #
> chore: remove failing request units test

- web3.js/src/connection.ts
- web3.js/src/transaction/versioned.ts
When differentiating between `VersionedTransaction` and `Transaction`, it's a little awkward to use `if ('message' in transaction')`. It'd be more natural to check for the existence of a `version` property.
Expose `VersionedTransaction.message.version` with a new `version` getter function
Fixes #
> feat: add version getter to VersionedTransaction class

- .mergify.yml
In order to backport quic changes to v1.10 in the safest possible manner the version numbers are all being incremented 3 minor releases. See discussion on Discord in #releng and #proj-quic-tpu:
https://discord.com/channels/428295358100013066/910937142182682656/1019051275318476881
Bump mergify versions to v1.13 and v1.14 to match new stable and beta branch numbers.
> Update mergify backport actions to new version numbers v1.13 and v1.14

- ledger-tool/src/main.rs
- ledger-tool/tests/basic.rs
The ledger-tool copy command currently assumes target_db uses the same
shred storage type as the source ledger.
This PR enables ledger-tool copy command to infer the target_db shred storage
type based on whether rocksdb or rocksdb_fifo exists under the target_db directory
(same way as how ledger-tool infers the shred storage type for the main db.)
> Enable ledger-tool copy command to infer target_db shred storage type.

- programs/bpf_loader/src/lib.rs
The refactoring in #24381 overlooked statements in which the `keyed_account.try_account_ref_mut()` expression stayed borrowed while another account is being accessed. This caused some aliasing restrictions to be effectively lifted and broke consensus.
Restores the following aliasing restrictions of  as they were in 1.10.
- `UpgradableLoaderInstruction::DeployWithMaxDataLen`: buffer != payer
- `UpgradableLoaderInstruction::Upgrade`: buffer != spill, programdata != spill
- `UpgradableLoaderInstruction::Close`: close != recipient
Fixes #27740
> Restore aliasing rules in BPF loader.

- web3.js/src/programs/address-lookup-table/state.ts
- web3.js/test/message-tests/compiled-keys.test.ts
- web3.js/test/message-tests/v0.test.ts
- web3.js/test/transaction-tests/message.test.ts
Some bundlers convert `**` to `Math.pow` which breaks bigint exponentiation used in the web3 sdk
- Replace calculated max u64 with a literal value for improved compatibility
Fixes #
> fix: replace computed max u64 constant with literal

- web3.js/test/transaction.test.ts
There is a `partialSign` test which tries to cause an exception by changing the first value in a signature to `0` but sometimes that byte is already a `0` and no exception is thrown.
- Ensure that the test always throws an exception by using an invalid signature
Fixes #
> chore: fix flakey partialSign test

- core/src/forward_packet_batches_by_accounts.rs
- core/src/immutable_deserialized_packet.rs
- core/src/latest_unprocessed_votes.rs
- core/src/lib.rs
- programs/vote/src/vote_state/mod.rs
- programs/vote/src/vote_transaction.rs
- sdk/program/src/vote/state/mod.rs
Will be used in banking stage to throw out extraneous vote packets
before processing
Picks up from #26722 . 
Creates a thread safe structure to store vote packets - only latest by slot # for each validator. 
Fixes #
> Add structure to collect and coalesce vote packets

- runtime/src/accounts_index.rs
- runtime/src/in_mem_accounts_index.rs
While tracking down over/under refcounting issues, it is useful to identify a specific pubkey that is incorrect. That can illuminate the sequence that could lead to the incorrect unref.
return whether an error occurred or not from `unref`. If so, info! log the offending pubkey.
On a healthy validator, this code should never run.
Fixes #
> acctidx: unref returns whether refcount went negative

- runtime/src/accounts.rs
- runtime/src/bank.rs
during feature activation of skipping rewrites (#26491), we'll need to be able to let the bank govern whether rehashes are allowed or not on accounts hash calculation.
Add `enable_rehashing` to `accounts`.`calculate_capitalization` allowing a caller to specify whether to allow rehashes or not.
Fixes #
> calculate_capitalization gets 'enable_rehashing'

- ci/buildkite-pipeline.sh
Downstream projects CI is failing on v1.13 but downstream projects are using v1.14 now so no need to maintain compatibility.
Remove the downstream projects check from CI for v1.13
> Remove downstream project check from stable branch CI

- core/src/banking_stage.rs
- core/src/latest_unprocessed_votes.rs
- core/src/lib.rs
- core/src/unprocessed_packet_batches.rs
- core/src/unprocessed_transaction_storage.rs
Separate storage for voting and transaction threads:
- Voting threads utilize a shared reference in order to dedup extraneous votes
- Transactions have thread local storage like before
Create structure to store packets for both - will be incorporated into banking stage in the next pr
Fixes #
> Add structure to house unprocessed transactions in banking_stage

- runtime/src/accounts_background_service.rs
- runtime/src/bank.rs
- runtime/src/snapshot_package.rs
during feature activation of skipping rewrites (#26491), we'll need to be able to let the bank govern whether rehashes are allowed or not on accounts hash calculation.
Add `bank`.`bank_enable_rehashing_on_accounts_hash` as a clear way to answer the question of whether to allow rehashes or not.
Fixes #
> add bank.bank_enable_rehashing_on_accounts_hash

- runtime/src/accounts_db.rs
It looks like `accounts_db_store_timings2.create_store_count` is incremented not in all the places where `create_store` is indirectly called.
In particular, `create_store` is indirectly called also in at least one other place https://github.com/solana-labs/solana/blob/master/runtime/src/accounts_db.rs#L6092
It might explain why this metric is always 0 for the private cluster simulations:
After running with this change situation changes:
Increment this metric inside the target function instead of doing that before calling it.
> move create_store counting to create_store

- cli-output/src/display.rs
- client/src/mock_sender.rs
- transaction-status/src/lib.rs
- transaction-status/src/option_serializer.rs
https://github.com/solana-labs/solana/pull/27790 for v1.10
> Add serialization-control enum for RPC Options (backport #27676)

- zk-token-sdk/src/instruction/transfer.rs
- zk-token-sdk/src/instruction/withdraw_withheld.rs
- zk-token-sdk/src/range_proof/inner_product.rs
Update errors in the comments in the zk-token-sdk
> zk-token-sdk: update errors in comments

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank/address_lookup_table.rs
- sdk/src/feature_set.rs
Seems like a better api to not return zero lamport accounts as `Some(zero_lamport_account)`.
`AccountsDb::load()` returns `None` if account has zero lamports.
#27800
Fixes #
> don't return zero lamport accounts from 'load' with feature

- docs/src/developing/clients/jsonrpc-api.md
JSON-RPC docs about jsonParsed support got caught in the crossfire of #27742
Correct versions
> Fix parsing versions in published docs

- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- runtime/src/bank.rs
- sdk/bpf/c/inc/sol/cpi.h
- sdk/bpf/c/inc/sol/inc/cpi.inc
- sdk/program/src/syscalls/mod.rs
- sdk/src/feature_set.rs
- sdk/src/transaction/sanitized.rs
The transaction account lock limit is currently set to 64 which is too limiting for use-cases like the Neon EVM
Added a feature gate that bumps the account lock limit and CPI account info limit both to 128.
Fixes: https://github.com/solana-labs/solana/issues/27756
Feature Gate Issue: https://github.com/solana-labs/solana/issues/27241
> Increase transaction account lock limit from 64 to 128

- web3.js/src/message/legacy.ts
- web3.js/src/message/v0.ts
- web3.js/test/message-tests/legacy.test.ts
- web3.js/test/message-tests/v0.test.ts
Lack of account inspection methods on `MessageV0`
Add `isAccountWritable` and `isAccountSigner` methods to `MessageV0` to mirror `Message`
Fixes #
> feat: add isAccountWritable and isAccountSigner to MessageV0

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank/address_lookup_table.rs
- sdk/src/feature_set.rs
* don't return zero lamport accounts from 'load'
* add feature
* rename
(cherry picked from commit 138d5ed5b0d21e8e0a287748e05678040e830943)
manually merged
Fixes #
> backport: don't return zero lamport accounts from 'load' with feature (#27793)

- ledger-tool/src/main.rs
`solana-ledger-tool create-snapshot` uses the same default number of snapshots to retain as the validator. However, `ledger-tool` should be non-destructive and not delete any snapshots by default.
Change default values for `maximum-*-snapshots-to-retain` to `usize::MAX`; a user can still specify values for these arguments should they choose.
> Make solana-ledger-tool retain all snapshots by default

- Cargo.lock
- docs/src/developing/clients/jsonrpc-api.md
- pubsub-client/Cargo.toml
- pubsub-client/src/nonblocking/pubsub_client.rs
- pubsub-client/src/pubsub_client.rs
- rpc-client/src/rpc_client.rs
No docs.
Add docs for `solana_client::pubsub_client` and `solana_client::nonblocking::pubsub_client`.
The blocking pubsub client is missing some guidance on how to use the `send_unsubscribe` and `shutdown` methods - as far as I can tell it isn't currently possible to reliably shutdown the blocking client, and its not clear how to use these methods correctly. These docs indicate that if clean shutdown is needed the async client should be used, and the async client has a comprehensive example to crib from.
Fixes #
> Document the pubsub client APIs.

- scripts/build-downstream-projects.sh
After adding the token upgrade CLI, the downstream build fails because it's trying to test the token-upgrade CLI without the token-ugprade program built.
Add the token-upgrade program to the list of programs to build and test.
Fixes #
> ci: Add spl-token-upgrade to downstream program build

- ledger/src/shred.rs
Inequality is reversed.
For current shreds `range.end == shred.len()`, so this is a no-op.
But for upcoming Merkle shreds this will cause shreds to incorrectly fail sig-verify.
Corrected the inequality direction.
> patches range check in get_signed_message_range

- programs/bpf_loader/src/lib.rs
See #27752
Adds tests for the two account aliasing restrictions of `UpgradeableLoaderInstruction::Upgrade` which can be triggered.
The other two in `UpgradableLoaderInstruction::DeployWithMaxDataLen` and `UpgradableLoaderInstruction::Close` can not fail and return `InstructionError::AccountBorrowFailed` because other prior checks already prevent that.
Fixes #
> Tests for the patch in #27752

- ledger/src/blockstore_db.rs
Previously before #26651, our LedgerCleanupService needs RocksDB background
compactions to reclaim ledger disk space via our custom CompactionFilter.
However, since RocksDB's compaction isn't smart enough to know which file to pick,
we rely on the 1-day compaction period so that each file will be forced to be compacted
once a day so that we can reclaim ledger disk space in time.  The downside of this is
each ledger file will be rewritten once per day.
As #26651 makes LedgerCleanupService actively delete those files whose entire slot-range
is older than both --limit-ledger-size and the current root, we can remove the 1-day compaction
period and get rid of the daily ledger file rewrite.
The results on mainnet-beta shows that this PR reduces ~20% write-bytes-per-second
and reduces ~50% …
> Remove daily rewrite/compaction of each ledger file

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_vote.rs
- programs/bpf/Cargo.lock
See also: #27845 
`solana-account-decoder` depends on `solana-vote-program` which has a lot of dependencies. But it only needs the parts of `solana-vote-program` that are re-exported from `solana-sdk`.
Use `solana_sdk::vote` instead of `solana_vote_program` in `solana_account_decoder` and remove `solana-vote-program` from the dependencies.
> remove vote-program dep from account-decoder

- Cargo.lock
- programs/bpf/Cargo.lock
- transaction-status/Cargo.toml
- transaction-status/src/parse_instruction.rs
- transaction-status/src/parse_vote.rs
`solana-transaction-status` depends on `solana-vote-program` which has a lot of dependencies. But it only needs the parts of `solana-vote-program` that are re-exported from `solana-sdk`.
Use `solana_sdk::vote` instead of `solana_vote_program` in `solana_transaction_status` and remove `solana-vote-program` from the dependencies.
> remove solana-vote-program dep from solana-transaction-status

- rpc-client/src/http_sender.rs
- watchtower/src/main.rs
There are two problems with current `solana-watchtower`:
1. It is not always possible to tell to which cluster certain error message belongs if two `solana-watchtower` processes (one for the Testnet and one for the Mainnet) send notifications into the same one channel.
2. `Error: rpc-error: error sending request for url (https://api.testnet.solana.com/): connection closed before message completed` every two minutes. This problem seems to be rare and depends on ISP. Quick search on Discord shows that I am not the only one affected: 
* `Add watchtower option to add custom string into notifications` addresses first problem.
* `Add a builder for an HttpSender to support more client options` makes HTTP RPC client more configurable, with a possibility to add more configuration options in …
> Watchtower improvements

- ledger/src/blockstore_db.rs
Several of the get() methods return a deserialized object (as opposed to
a `Vec<u8>`) by first getting a byte array out of Rocks, and then using
`bincode::deserialize()` to get the underlying type. However,
`deserialize()` only requires a u8 slice, not an owned `Vec<u8>`. So, we can
use get_pinned_cf() to reference memory owned by Rocks and avoid an
unnecessary copy.
Use `DBPinnableSlice` via `get_pinned_cf()` in cases that where intermediate buffer from `get_cf()` would have been immediately discarded.
https://docs.rs/rocksdb/latest/rocksdb/struct.DBCommon.html#method.get_pinned_cf
> Remove extra data copy from several Rocks get() methods

- net/net.sh
typo.
```
propogated -> propagated
```
> chore: fix typo in net.sh

- web3.js/src/publickey.ts
Removes a redundant Buffer declaration
Addresses #27590.
> web3.js: remove Buffer from PublicKeyInitData

- .mergify.yml
v1.13 is intended to be v1.10 + some quic changes. So backports to v1.13 should also be backported to v1.10.
Add v1.10 mergify backport action to the v1.13 label
> Add v1.10 backport for v1.13 label

- validator/src/bootstrap.rs
When searching for RPC peers during bootstrap, gossip is polled in a tight loop. This is bad for gossip, since it grabs the CRDS lock each time. It's also bad for the user/log since the RPC Peers table is logged each time.
I started up a new node against mnb, and let it run until it began downloading a snapshot. I did this three times, with a clean ledger each time. The log's were:
| run | log size | number of lines |
| ---: | ---: | ---: |
| 1 | 324 MB | 2,828,522 |
| 2 | 131 MB | 1,247,188 |
| 3 | 178 MB | 1,684,973 |
Original context in Discord:
https://discord.com/channels/428295358100013066/439194979856809985/1020102644095795270
Add a 1 second sleep in the loop to get rpc peers.
With this change, I started up another node. Here's the log results:
| run | log size | number of lines | …
> bootstrap: Sleep in loop to get rpc peers

- core/tests/snapshots.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/bank_forks.rs
- test-validator/src/lib.rs
- tokens/src/commands.rs
During startup of a validator, 0, 1, or 2 accounts hash calculations are run.
In a previous pr, we moved the initial accounts hash calculation to be async. Prior to that hash calculation completing successfully, a validator would skip its leader slot and it would not vote. The goal was to improve startup time with the theory that the hash calculation would complete before the validator had finished replaying the slots it had missed after the snapshot it started from.
However, there are conditions where a second hash calculation is run after some number of slots are replayed. [`process_blockstore_from_root`](https://github.com/solana-labs/solana/blob/e6687b89e692243461f2900a193156b09c887172/ledger/src/blockstore_processor.rs#L868) is the location of this second call, which calls …
> bank.initial_blockstore_processing_complete to avoid concurrent hash calculations

- docs/src/developing/clients/jsonrpc-api.md
- scripts/increment-cargo-version.sh
increment-cargo-version.sh increments version numbers in markdown files. This behavior is no longer necessary and sometimes increments version numbers that should be static.
Some discussion here:
https://discord.com/channels/428295358100013066/560503042458517505/1020445231004532810
* Remove markdown file update code
* Restore version numbers in jsonrpc-api.md
> Remove markdown file update from version increment-cargo-version.sh

- web3.js/src/programs/address-lookup-table/state.ts
- web3.js/test/message-tests/compiled-keys.test.ts
- web3.js/test/message-tests/v0.test.ts
- web3.js/test/transaction-tests/message.test.ts
Some JavaScript runtimes support `BigInt` but not bigint literals.
* Replace `18446744073709551615n` with `BigInt('0xffffffffffffffff')`
This makes web3.js compatible with runtimes that don't understand bigint literals but _do_ understand `BigInt` constructors. For whatever that's worth.
> fix: replace bigint literals with `BigInt` constructors

- ledger/src/blockstore.rs
The current implementation of get_slots_since() invokes multiple rocksdb::get().
As a result, each get() operation may end up requiring one disk read.  This leads
to poor performance of get_slots_since described in #24878.
This PR makes get_slots_since() use the batched version of multi_get() instead,
which allows multiple get operations to be processed in batch so that they can
be answered with fewer disk reads.
> Optimize get_slots_since() using the batched version of multi_get()

- runtime/src/accounts_db.rs
- runtime/src/snapshot_minimizer.rs
Shrinking an append vec finds all alive accounts and writes them to a new, shrunken append vec.
The dead accounts are unref'd and not included in the new, shrunken append vec.
After shrink, we currently send the ENTIRE OLD append vec for clean to process next time. Clean then reads all pubkeys out of the old append vec and processes those pubkeys.
This sends clean more pubkeys to process than are useful.
The only useful pubkeys after a shrink are:
1. those that were unref'd and no longer in storage at a slot. Now, other pubkeys or slots may be able to be destroyed.
plus:
2. if the ONLY alive accounts remaining in the slot have zero lamports, then maybe the entire slot could be marked dead.
Otherwise, alive accounts retain the same state and do not need to be visited by clean. Nothing has …
> when shrinking, don't send entire old append vec to clean

- runtime/src/accounts_hash.rs
This was introduced in #24437.
As part of development of 
#26491
We don't have to be able to process snapshots that contain either rewritten accounts anymore except during testing, so we don't need to penalize the entire cluster for that.
Normal validators will not be skipping rewrites, so their appendvecs will be correct. Probably, only the validators that I am running as tests will be generating snapshots that do not include rewrites during rent collection. For those validators, I'll need to disable caching to get the correct answer.
If a validator needed to rehash skipped rewrites, the result will now be a hash mismatch error - either against known validators on gossip during runtime or at startup relative to the expected startup accounts hash from the snapshot.
Calculating the …
> re-enable caching of hash calculation

- programs/bpf_loader/src/syscalls/mod.rs
There are tests for the curve25519 operations themselves, but no tests for the actual curve25519 syscalls.
Added tests for curve25519 point validation syscall.
> Add curve validation syscall tests

- programs/bpf_loader/src/syscalls/mod.rs
There are tests for the curve25519 ooperations themselves, but no tests for the actual curve25519 syscalls.
Added syscall tests for curve25519 group operation syscalls.
> Add syscall curve group ops tests

- ledger/src/blockstore_processor.rs
At startup from a snapshot, we
1. check accounts hash capitalization after loading from a snapshot, verifying both cap and hash. This is done asynchronously as of recently to improve startup time.
2. starts accounts background service, where the write cache is flushed periodically
3. process whatever tx rocks has stored locally past the snapshot slot. Resulting slots are stored in the write cache.
4. check accounts hash capitalization again (this is done synchronously right now)
5. start the normal validator processing where the accounts background service calculates the accounts capitalization and verifies it against the bank and gossip periodically
(4) is redundant.
It only checks capitalization against the bank. The only side effect is to halt the validator if capitalization doesn't …
> remove extra accounts cap call at startup

- programs/bpf_loader/benches/serialization.rs
This:
- adds serialization benches for invocations with a large number of instruction accounts (255)
- sets the correct `InstructionAccount::index_in_callee`
- benchmarks the whole `serialize_parameters` instead of only the inner functions
> Improve serialization benches

- .github/workflows/docs.yml
- ci/buildkite-pipeline.sh
v1.13 and v1.10 are intended to match except for specific quic related commits but I didn't manage the branches well enough and a couple of commits made it into v1.13 without being on v1.10:
```
9a161c56ad chore: fix docs pipeline (backport #27794) (#27795)
aa0b46cb23 Remove downstream project check from stable branch CI (#27775)
```
Cherry pick 9a161c56ad and aa0b46cb23 onto v1.10
I've combined into one PR to get through CI but will not squash these so they remain distinct.
> Apply 1.13 non-quic commits to v1.10

- web3.js/src/transaction/versioned.ts
- web3.js/test/transaction.test.ts
Unlike the legacy Transaction class, the new VersionedTransaction class has no `addSignature()` function to add signatures that were generated externally (by a third party library, browser extension etc.).
Implemented `addSignature(publicKey: PublicKey, signature: Uint8Array)`
> web3.js: Implement addSignature in VersionedTransaction

- docs/src/integrations/exchange.md
Lack of info on how exchanges need to handle versioned transactions while doing deposit detection.
- Add migration section to the docs explaining additional parameters needed to properly support versioned transactions
- Update RPC example requests with additional required parameters
Fixes #
> docs: Add versioned tx info to exchange integration guide

- runtime/src/snapshot_utils.rs
- runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
#27346. #26590 introduced snapshot rebuilding logic that did not check version *before* unpacking account fields since the version file was serialized later on. We've moved the version file forward in the snapshot in #27192, so we can check the version before loading account fields.
Wait for, deserialize, and check snapshot version before processing accounts fields
Fixes #27346
> Interleaved snapshot unpack versioning

- runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
Follow up for #27484. Refactor `get_snapshot_file_kind` to use regex.
Refactor `get_snapshot_file_kind` to use regex.
Fixes #
> Use regex in get_snapshot_file_kind

- ledger/src/blockstore.rs
Cleanup on a test - test on an empty blockstore and remove a needless variable rename.
> Cleanup blockstore test

- runtime/src/bank.rs
0% commission validators find that their vote accounts are excluded from the `getBlock` RPC method `rewards` response field. At face value this seems reasonable, as those vote accounts truly received no rewards. 
However the `rewards.commission` field is still very useful in this case, as it allows an rpc client to easily disambiguate between an active vote account that had 0% at a given epoch versus one that did not vote at all.
With this change, 0% commission validators that earned rewards for their stakers in a given block will now be represented in the `getBlock` RPC method `rewards` response field (as earning 0 lamports)
> Nodes with 0% commission are now included in the `getBlock` RPC method `rewards` response field.

- core/src/validator.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_processor.rs
There are several places that want the highest slot in the blockstore;
remove duplicate code and combine into a single function.
More importantly, those couple instances got the last element very
inefficiently. The previous code got a forward iterator for SlotMeta
column and proceeded through the entire iterator until it hit the end.
This means that every single SlotMeta was being read from disk and
deserialized.
To avoid all this extra work, instead use a reverse iterator that starts
at the end so we only need to yield a single element from the iterator.
> Add Blockstore::highest_slot() method

- sdk/benches/accounts.rs
- sdk/src/account.rs
`set_data_from_slice()` can be optimized by not doing a memcmp and by not unconditionally throwing away the current buffer if it's not shared. 
Remove the memcmp and reuse the existing buffer if it's not shared. Quoting the change:
```
// Reserve additional capacity if needed. Here we make the assumption
// that growing the current buffer is cheaper than doing a whole new
// allocation to make `new_data` owned.
//
// This assumption holds true during CPI, especially when the account
// size doesn't change but the account is only changed in place. And
// it's also true when the account is grown by a small margin (the
// realloc limit is quite low), in which case the allocator can just
// update the allocation metadata without moving.
//
// Shrinking and copying in place is always faster …
```
> AccountSharedData: optimize set_data_from_slice

- runtime/src/stake_account.rs
`clippy::result_large_err` error on newer rust versions.
Boxed `StakeState`.
> boxes StakeState in stake_account::Error::InvalidDelegation

- runtime/src/bank_forks.rs
- runtime/src/lib.rs
- runtime/src/root_bank_cache.rs
Locking is bad for performance. If the root bank hasn't changed we do not need to lock again. 
* root_slot on BankForks is now an atomic
* BankForks can return a read-only wrapper of root_slot
* added a caching root bank that only locks the bank forks if the root bank has changed
Fixes #
> root_bank_cache

- core/src/immutable_deserialized_packet.rs
Vote transactions do not require prioritization.
- reset all vote transactions' priority to default. 
Fixes #
> Remove priority from vote transactions 

- program-runtime/src/invoke_context.rs
- program-test/src/lib.rs
- programs/address-lookup-table/src/processor.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- runtime/src/bank.rs
- runtime/src/message_processor.rs
- runtime/src/system_instruction_processor.rs
- sdk/src/transaction_context.rs
`set_data()` used to take a slice and would force alloc+copy if the caller has owned values (eg account creation, account lookup table).
Expose set_data_from_slice() for callers that have slices, and switch set_data() to taking an owned Vec.
> BorrowedAccount: add set_data_from_slice(), make set_data() take owned values

- explorer/src/__tests__/lamportsToSol.ts
- explorer/src/components/account/StakeAccountSection.tsx
- explorer/src/components/common/Epoch.tsx
- explorer/src/components/instruction/serum/types.ts
- explorer/src/utils/index.tsx
- explorer/src/validators/accounts/stake.ts
- explorer/src/validators/bignum.ts
- explorer/src/validators/number.ts
`bn.js` dependency isn't required for bigint operations and requires extra overhead to convert to bigint types used by the web3 library for things like address lookup tables
- Replace uses of bn.js with bigint
- Fix lamports to SOL conversion and expand test coverage
Fixes #
> Explorer: replace usages of bn.js with BigInt

- explorer/src/components/common/BalanceDelta.tsx
Lamport conversion utils previously had a side effect of taking the absolute value of the lamport value which the balance delta component relied on. Once the side effect was fixed in https://github.com/solana-labs/solana/pull/28040, the balance delta display broke.
Fix balance delta display
Fixes #
> Explorer: Fix balance delta display

- web3.js/src/message/v0.ts
The ergonomics of `MessageV0.getAcccountKeys` isn't great when writing code that can handle legacy or v0 messages:
```js
const accountKeysFromLookups = txWithMeta.meta?.loadedAddresses;
const accountKeys = message.getAccountKeys(accountKeysFromLookups && {
accountKeysFromLookups,
});
```
Allow args in `GetAccountKeysArgs` to be undefined or null for improved ergonomics:
```js
const accountKeys = message.getAccountKeys({
accountKeysFromLookups: txWithMeta.meta?.loadedAddresses,
});
```
Fixes #
> fix: improve `MessageV0.getAccountKeys` API ergonomics

- explorer/package-lock.json
- explorer/package.json
- explorer/src/components/ProgramLogsCardBody.tsx
- explorer/src/components/block/BlockAccountsCard.tsx
- explorer/src/components/block/BlockHistoryCard.tsx
- explorer/src/components/block/BlockOverviewCard.tsx
- explorer/src/components/block/BlockProgramsCard.tsx
- explorer/src/components/block/BlockRewardsCard.tsx
- explorer/src/pages/TransactionDetailsPage.tsx
- explorer/src/pages/inspector/AccountsCard.tsx
- explorer/src/pages/inspector/AddressTableLookupsCard.tsx
- explorer/src/pages/inspector/AddressWithContext.tsx
- explorer/src/pages/inspector/InspectorPage.tsx
- explorer/src/pages/inspector/InstructionsSection.tsx
- explorer/src/pages/inspector/RawInputCard.tsx
- explorer/src/pages/inspector/SignaturesCard.tsx
- explorer/src/pages/inspector/SimulatorCard.tsx
- explorer/src/providers/accounts/history.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/block.tsx
- explorer/src/providers/transactions/parsed.tsx
- explorer/src/providers/transactions/raw.tsx
- explorer/src/validators/accounts/address-lookup-table.ts
Explorer doesn't support displaying and inspecting versioned transactions
- Fetch v0 transactions / blocks by default
- Display transaction version in transaction overview section
- Add badge for accounts loaded from lookup tables
- Add "Address Lookup Tables" card to transaction inspector
Test links:
- [Details page with v0 transaction 1](http://localhost:3000/tx/4zZBQVkkJUKbASJoKStzsnLh8ifA8ywMXS6GqWBZeGghBiedM3ve7ujaTKniRGVekZ5DUvkVzbhxTLfCRWr3Z29N?cluster=devnet)
- [Details page with v0 transaction 2](http://localhost:3000/tx/5j9WCjiybkEDMXYyuUTy8d2kEcJeaRyzcsPpkF4kmJdVbxR483dzKsJLRTrY91bKxi9tA94vfzqjCmdP3G596kBt?cluster=devnet)
- [Inspector with processed v0 transaction](http://localhost:3000/tx/5j9WCjiybkEDMXYyuUTy8d2kEcJeaRyzcsPpkF4kmJdVbxR483dzKsJLRTrY91bKxi9tA94vfzqjCmdP3G596kBt/i …
> Explorer: Support displaying and inspecting versioned transactions

- Cargo.lock
- ledger/Cargo.toml
- programs/bpf/Cargo.lock
Need to pick up https://github.com/rust-rse/reed-solomon-erasure/pull/104 in order to unblock https://github.com/solana-labs/solana/pull/27510
updated reed-solomon-erasure
> updates reed-solomon-erasure crate version to 6.0.0

- ledger/Cargo.toml
- ledger/src/blockstore.rs
- ledger/src/shred/merkle.rs
- programs/bpf/Cargo.lock
Shreds received from other nodes over the socket are sanitized when the payload is deserialized:
https://github.com/solana-labs/solana/blob/315707504/ledger/src/shred/legacy.rs#L137 
https://github.com/solana-labs/solana/blob/315707504/ledger/src/shred/legacy.rs#L77 
https://github.com/solana-labs/solana/blob/315707504/ledger/src/shred/merkle.rs#L355 
https://github.com/solana-labs/solana/blob/315707504/ledger/src/shred/merkle.rs#L439
Similarly, shreds recovered from erasure codes are also sanitized at deserialization:
https://github.com/solana-labs/solana/blob/f02fe9c7e/ledger/src/shredder.rs#L330
or explicitly so for Merkle shreds:
https://github.com/solana-labs/solana/blob/f02fe9c7e/ledger/src/shred/merkle.rs#L753
Shreds generated locally by the node itself during its leader slots do …
> removes redundant shred.sanitize() from blockstore

- Cargo.lock
- bench-tps/Cargo.toml
- cli-config/Cargo.toml
- genesis/Cargo.toml
- install/Cargo.toml
- programs/bpf/Cargo.lock
- validator/Cargo.toml
https://github.com/solana-labs/solana/pull/27970#issuecomment-1257039425
This reverts commit da9206fb87c2e07738699cfc0567d52a7b8d9ad8.
> Revert "chore: bump serde_yaml from 0.8.26 to 0.9.13 (#27970)"

- core/benches/retransmit_stage.rs
- core/benches/shredder.rs
- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- core/src/broadcast_stage/standard_broadcast_run.rs
- core/src/shred_fetch_stage.rs
- core/src/window_service.rs
- gossip/src/duplicate_shred.rs
- ledger/src/blockstore.rs
- ledger/src/shred.rs
- ledger/src/shred/merkle.rs
- ledger/src/shredder.rs
- ledger/tests/shred.rs
`ReedSolomon::new(...)` initializes a matrix and a data-decode-matrix cache:
https://github.com/rust-rse/reed-solomon-erasure/blob/273ebbced/src/core.rs#L460-L466
Current master code is redoing this computation for each batch.
In order to cache this computation, this commit caches the reed-solomon
encoder/decoder instance for each `(data_shards, parity_shards)` pair.
> caches reed-solomon encoder/decoder instance

- runtime/src/cache_hash_data.rs
1.14 is having oom issues
hash calc can perform its operations on files instead of using ram spikes
Some refactoring needs to occur for this.
Make non-mut version of access to loaded hash cache data.
This will be used later to remove the current requirement of having a &mut self
Fixes #
> get rid of unnecessary mut

- explorer/src/utils/tx.ts
Source: https://docs.wormhole.com/wormhole/contracts
Wormhole is a popular asset bridge. The Solana Explorer displays Wormhole's program IDs as "unknown program".
Adds Wormhole program IDs for devnet and mainnet.
Fixes #
> explorer: add Wormhole program IDs

- docs/layouts/CardLayout.js
- docs/sidebars.js
- docs/src/developing/clients/jsonrpc-api.md
- docs/src/developing/lookup-tables.md
- docs/src/developing/versioned-transactions.md
No documentation for Versioned Transactions and Address Lookup Tables
- added doc page for each Versioned Transactions and ALTs
- added the links to the Developer's sidebar
- updated the sidebar parser to allow nested categories
Addresses: #26391
> [docs] versioned transactions and lookup tables

- gossip/src/cluster_info.rs
- gossip/src/cluster_info_metrics.rs
Gossip packets are counted after excess packets are dropped.
This makes it difficult to debug gossip traffic spikes if the majority of the packets are dropped.
Count gossip packets received before excess packets are dropped
> counts gossip packets received before excess packets are dropped

- runtime/src/in_mem_accounts_index.rs
accidentally had a singular and plural version of 'duplicate'. Both were used so no compiler warnings.
The result was we were never cleaning initial old duplicate accounts we loaded from a snapshot.
Initial old duplicates could possibly not get cleaned for a very long time, leaving us a possible trail of old append vecs.
Remove duplicate 'duplicate' and use the same one.
Fixes #
> fix duplicate local variable

- client/src/connection_cache.rs
- core/src/fetch_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
- local-cluster/src/local_cluster.rs
- multinode-demo/bootstrap-validator.sh
- multinode-demo/validator.sh
- net/net.sh
- net/remote/remote-node.sh
- rpc-test/tests/rpc.rs
- test-validator/src/lib.rs
- validator/src/main.rs
* Added option to turn on UDP for TPU transaction and make UDP based TPU off by default (#27462)
--tpu-enable-udp is introduced. And when this is on, the transaction receive and transaction forward is enabled using udp.
Except for a few tests which was hard-coded sending transactions using udp, most tests are being done with udp based tpu disabled.
(cherry picked from commit 7f223dc582dee5ec65739105907a9108b1a46bc7)
* Fixed merge conflicts
* Fixed another conflict
* Fixed a fmt
Co-authored-by: Lijun Wang <83639177+lijunwangs@users.noreply.github.com>
Fixes #
> Added option to turn on UDP for TPU transaction and make UDP based TPU off by default (backport #27462) (#27658)

- ledger/src/blockstore_db.rs
Improve code comment for Blockstore::delete_range_cf esp. for the corner case
where the from Slot and to Slot are the same.
> Improve code comment for delete_range_cf

- ledger-tool/src/main.rs
- ledger/src/blockstore_options.rs
- validator/src/main.rs
When FIFO compaction is used while --rocksdb_fifo_shred_storage_size
is unspecified, the FIFO shred storage size is set to a const default based
on the default `--limit-ledger-size`.
When --rocksdb_fifo_shred_storage_size is unspecified, it is now
derived from `--limit-ledger-size` by reserving 1500 bytes for each
shred.
> Derive rocksdb_fifo_shred_storage_size based on limit-ledger-size

- explorer/src/components/account/address-lookup-table/AddressLookupTableAccountSection.tsx
- explorer/src/components/account/address-lookup-table/LookupTableEntriesCard.tsx
- explorer/src/pages/AccountDetailsPage.tsx
When the RPC API supports parsing address lookup table accounts, the explorer UI breaks
Properly handle parsed address lookup table responses
Fixes https://github.com/solana-labs/solana/issues/27287
> Explorer: Support parsed address lookup table responses

- runtime/src/accounts_db.rs
correct off by 1 error in width calculation
This does not appear to have a practical effect, but it is an incorrect calculation of 'width'
add 1
Fixes #
> width of hash calc bins was off by 1

- core/benches/unprocessed_packet_batches.rs
- core/src/banking_stage.rs
- core/src/forward_packet_batches_by_accounts.rs
- core/src/latest_unprocessed_votes.rs
- core/src/unprocessed_packet_batches.rs
- core/src/unprocessed_transaction_storage.rs
Filtering invalid packets (eg too old, or already processed) at end-of-slot was accidentally removed. It is worth to add it back to avoid forwarding unnecessary (eg, invalid) packets. 
When checking if packet is invalid, should keep in mind not to lock bank's blockhash_queue and status_cache for every transactions, as that's be bad for overall performance. This requires to change the forwarder's workflow from transaction-by-transaction to batch-by-batch.
- Move packets filtering to the beginning of forwarding process, so the logic only responsible for forwarding. (leader still filters invalid packets at `consume_buffered_packets` as usual).
- Sanitizing batch of packets into transactions, validating transactions with `bank` in batch to avoid excessive locking on bank's blockhash and …
> Batch filtering invalid transactions before forwarding

- .github/workflows/client-targets.yml
seems the latest cargo-ndk killed us due to this commit
https://github.com/bbqsrc/cargo-ndk/commit/e5896937b4feb762b64be77d8efcb700ee836642
use cargo-ndk@2.11.0 for a while
> chore: use cargo-ndk@2.11.0

- explorer/package-lock.json
- explorer/package.json
`tweetnacl` used to be a transitive dependency and is required for signature verification in the inspector. It should be an explicit direct dependency.
Add `tweetnacl` dependency to `package.json`
Fixes #
> Explorer: add explicit dependency on tweetnacl

- core/tests/ledger_cleanup.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_options.rs
Removes the constant default for ShredStorageType::RocksFifo
as the shred storage size is either user-specified or derived
from --limit-ledger-size in #27459.
> Remove the const default for RocksFifo

- runtime/src/accounts_db.rs
Soon, we'll be using vec<&[]> instead of vec<vec<>>. This will require some adjustments to expected data in tests.
Fixes #
> refactor accts hash tests

- core/src/heaviest_subtree_fork_choice.rs
- core/src/replay_stage.rs
Validators are unable to reset back to the heaviest bank on the fork that includes their last vote if the heaviest bank's slot matches their last voted slot. If there is a heavier bank on the last voted fork than the last voted bank itself, validators can erroneously reset to an invalid slot.
- Allow resetting to a slot which matches the last vote slot
- Disallow resetting to a slot which is part of an invalid fork
- Fix tests
Fixes #
> Allow validators to reset to the slot which matches their last voted slot

- runtime/src/accounts_hash.rs
When we switch from ram usage for accounts hash calculation to disk, we need to separate cache file data into vecs by bin.
Source data will now be references to sorted pubkeys.
add `get_binned_data()` to bin the data for parallel processing
This code will be used soon by accounts hash calculation.
Fixes #
> add accounts hash get_binned_data()

- core/src/cluster_slot_state_verifier.rs
- core/src/replay_stage.rs
Need more insight into DuplicateConfirmed/bank frozen versions
Fixes #
> Consensus Logging

- ledger/src/blockstore.rs
`traverse_children_mut()` searches through blocks by pushing block's children onto a queue. Popping from the front of a `Vec` of `n` items requires the remaining `n-1` items to be shifted to fill the first `n-1` positions. `VecDeque` is a ring buffer, and as such, saves the memcpy when popping from the front.
For what it is worth, this change will probably have negligible impact. The `next_slots` queue should never really get that large; in the absence of forking, this queue would just be a single element, with a parent getting popped off and then replaced by its' child. With normal forking (ie current epoch boundary issue), we are typically looking at on the order of 10 forks. Regardless, `VecDeque` is the right structure here. 
Use `VecDeque` instead of `Vec`.
> Use VecDeque as a queue instead of Vec

- ledger-tool/src/main.rs
In order to see the full SlotMeta, you have to pass `-vv`; this dumps out all the entries / transactions which is a massive wall of text.
- Display the full SlotMeta for `verbosity >= 1` instead of `verbosity >= 2`
- Print `next_slots` for `verbosity == 0`
- Remove "Slot Meta" text as `fmt` trait will display the struct name anyways
- Make leading spaces consistent
This is a pretty subtle change, but saves either a ton of scrolling or having to tack on `head -n X` to the command when using `-vv`
```
// verbosity == 0
Slot 152886692
num_shreds: 1358, parent_slot: Some(152886691), num_entries: 371, is_full: true
// verbosity == 1
Slot 152886692
num_shreds: 1358, parent_slot: Some(152886691), num_entries: 371, is_full: true
Transactions: 3458, hashes: 800000, block_hash: …
```
> Cleanup solana-ledger-tool slot output

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank/address_lookup_table.rs
remove parameter to api and now default value and its fallout for simplification.
Fixes #
> remove LoadZeroLamports enum

- cli/src/checks.rs
- programs/address-lookup-table/src/error.rs
- rpc-client/src/nonblocking/rpc_client.rs
- rpc-client/src/rpc_client.rs
- rpc/src/rpc.rs
- runtime/src/bank/address_lookup_table.rs
- sdk/program/src/message/address_loader.rs
- sdk/program/src/message/mod.rs
- sdk/program/src/message/sanitized.rs
- sdk/src/transaction/error.rs
- sdk/src/transaction/sanitized.rs
The `getFeeForMessage` RPC API and the equivalent RPC client method `get_fee_for_message` both do not support versioned messages yet.
- Add support for versioned messages in the `getFeeForMessage` RPC API
- Add support for versioned messages through the new `SerializableMessage` trait in the `get_fee_for_message` RPC client api
- Refactor `AddressLoader` to make it usable inside `solana-program`
- Remove pre v1.9 handling in RPC client since no clusters are running v1.8 or earlier
Fixes https://github.com/solana-labs/solana/issues/28182
Fixes https://github.com/solana-labs/solana/issues/28214
> RPC: Support versioned txs in getFeeForMessage API

- runtime/src/accounts_db.rs
- runtime/src/sorted_storages.rs
cleanup/simplify accounts hash chunking code
take &Range instead of Range
This avoids making copies of ranges.
Fixes #
> use ref for snapshot_storages.iter_range

- ledger-tool/src/main.rs
- ledger-tool/tests/basic.rs
- ledger/src/blockstore_options.rs
- validator/src/main.rs
A fifo rocksdb instance must be opened with max size parameter on the fifo columns. To support this, we previously plumbed a constant up to callers that provided a default if unbounded growth desired.
This change attempts to be more rusty by exposing an option for this value, and converting the option to a constant at the lowest level possible.
> Make RocksFifo storage size API expose an Option<u64>

- ledger-tool/src/main.rs
- ledger/src/blockstore_processor.rs
When ledger-tool runs, it runs a final hash calc at the end to verify capitalization if halt-at-slot is passed.
This inadvertently ran during validator startup if there was a ledger when the validator was started.
This extra hash calc is only for debugging and should not be running on validator startup.
only run this hash calc from ledger-tool verify
Fixes #
> after replay at validator startup don't verify hash calc

- Cargo.lock
- Cargo.toml
- memory-management/Cargo.toml
- memory-management/src/aligned_memory.rs
- memory-management/src/dynamic_layout.rs
- memory-management/src/lib.rs
It has become clear that if we want to optimize the validator performance further, we will have to do things like custom allocators, memory layouts and memory management. For now we will only extract some code from solana_rbpf which did not belong there, but this crate will grow in the near future (e.g. with the dynamic stride arrays of #27587).
Moves [`AlignedMemory` from `solana_rbpf`](https://github.com/solana-labs/rbpf/blob/main/src/aligned_memory.rs) into a new crate: `memory-management`.
> Moves AlignedMemory from solana_rbpf into a new crate: memory-managment.

- Cargo.lock
- notifier/Cargo.toml
- notifier/src/lib.rs
- watchtower/src/main.rs
On the initial PagerDuty implementation when watchtower sends an All Clear message it triggers a new PagerDuty incident, instead of resolving the existing one
Create a dedup key for PagerDuty alerts to group initial trigger and resolution together
Without this it was triggering a new incident on the All Clear message
Renames the NotificationType enum to NotificationChannel and creates a new NotificationType enum to hold the actions Trigger and Resolve
Generates a random hash to use as a dedup key and resets it after the failure is resolved so next failure triggers a new incident.
- Tested with balance check alert multiple times, including multiple separate incidents/alerts to ensure the dedup_key is being correctly rotated
- Tested Slack and Telegram alerts as well to ensure they're not …
> Resolve PagerDuty incident on All Clear instead of triggering new incident

- runtime/src/accounts_db.rs
We're wasting time down deep in `Bank::freeze` inside `AccountsDb::extend_hashes_with_skipped_rewrites()`
remove unnecessary iteration of all entries to hash at bank freeze if we have no skipped rewrites.
skipped rewrites only occur as a result of a cli option at the moment. As soon as the way forward is cleared, this will occur behind a feature flag.
Fixes #
> exit early deep in bank freeze, avoiding some unnecessary work

- runtime/src/accounts_db.rs
in chunking slot ranges for accounts hash calculation, handle ancient slots correctly and separately.
refactor function, add tests.
Fixes #
> accounts hash calc, add get_ancient_slots

- runtime/src/epoch_accounts_hash.rs
- runtime/src/epoch_accounts_hash/utils.rs
Move the EAH utility functions into their own submodule to make code organization a bit simpler.
No code was changed, just relocated.
> Move epoch accounts hash utility functions

- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
perf issues on startup in 1.14
If we run the initial hash calc in the background, which was new to 1.14, we were using the foreground threads still. This starves the foreground processes.
Previously, at startup, we waited for the hash calculation to complete before beginning tx processing. Now, we run it in the background, and wait to create snapshots or vote until we have verified our full accounts state at startup in the background.
If we run the initial hash calc in the background, then have it use the background threads.
Fixes #
> run initial hash calc in background, using background threads

- explorer/src/components/account/history/TransactionHistoryCard.tsx
Have to click through tx signatures to get the UTC timestamp of transactions. They should be visible in the history table
Before
After
Fixes #
> Explorer: Display block utc timestamp in account history

- rpc-client-api/src/custom_error.rs
- rpc/src/rpc.rs
The `Transaction version ({0}) is not supported` error message is not very clear or actionable. It appears to be an error that the RPC API server needs to fix rather than the client.
Make it clear that the requestor needs to pass a param if they request an unsupported transaction version and receive an error
Fixes #
> RPC: Improve unsupported transaction error message

- docs/src/cli/install-solana-cli-tools.md
The install instructions for Windows instruct users to open a cmd window and run the install command.
However this is an easy detail to miss, especially since:
- VSCode defaults to PowerShell when opening a new Terminal
- Windows has replaced cmd with PowerShell in the WinX menu (<kbd>Win</kbd> + <kbd>X</kbd>, <kbd>Win</kbd> + <kbd>A</kbd>)
- New users, especially those without a programming background might not know the difference between shells
PowerShell has a (horrible) feature where it aliases `curl` to `Invoke-Web-Request` inspite of modern Windows versions shipping with curl by default.
This results in a cryptic error message that is hard for new users to debug
```powershell
> curl https://release.solana.com/v1.14.3/solana-install-init-x86_64-pc-windows-msvc.exe `
>> --output …
```
> Better install command for Windows

- .github/workflows/docs.yml
- docs/yarn.lock
The docs build is failing because the vercel app is configured with node 12: https://github.com/solana-labs/solana/actions/runs/3198536595/jobs/5223180480
This does not directly fix the problem, since that needs to be configured on the vercel side.  Since that will eventually be upgraded, however, we should also use the right node version during the docs build step.
While trying this locally, my machine updated the yarn.lock file, so I committed up that change too.
Fixes #
> docs: Update node build version to v16

- docs/src/running-validator/restart-cluster.md
As of 1.14.x, validators don't need to grep logs to find the latest optimistically confirmed slot.
> Update restart guide to include the use of `solana-ledger-tool latest-optimistic-slots`

- runtime/src/accounts_db.rs
chunk tracking is complicated wrt uneven start/end and ancient append vecs.
Soon we will rely on this to perform well for ancient append vecs.
We will also rely on this to use files to calculate the accounts hash with files instead of using memory.
extract the math into a separate, testable piece and add tests.
Fixes #
> add chunk tracking in SplitAncientStorages

- core/tests/epoch_accounts_hash.rs
CI spuriously fails intermittently in EAH tests. The failure is caused in test cleanup, when background threads are being joined and throw an error [^1]. Since the test has already completed its useful bits, this error is not germane.
[^1] It appears that if the snapshot packager service has an outstanding snapshot request to service, the input files or output directory (or both) is getting cleaned up before the snapshot archive is made.
Update: [^1] may be fixed by https://github.com/solana-labs/solana/pull/28270
Here's what the error looks like:
https://buildkite.com/solana-labs/solana/builds/83273#0183abb6-af57-44eb-ae6b-c3d089995265
Ignore errors when joining background threads in the EAH tests.
> Ignore errors when joining background threads for EAH tests

- Cargo.lock
- programs/bpf/Cargo.lock
- validator/Cargo.toml
- validator/src/main.rs
We keep deprecated arguments around to avoid breaking compatibility; however, they add clutter to the code.
Move all of the deprecated arguments and warnings for using the deprecated warnings into their own functions to keep main function more readable.
Here is a run with all of these arguments specified and the subsequent warnings to prove I didn't screw up the copy/paste:
```
target/debug/solana-validator \
--identity keypair.json \
--dynamic-port-range 8002-8032 \
--gossip-port 8001 \
--ledger ./ \
--limit-ledger-size \
--log ./ \
--rpc-port 8899 \
--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
--wal-recovery-mode skip_any_corrupted_record \
--accounts-index-memory-limit-mb 5000 \
--trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \ …
```
> Separate deprecated arguments out to reduce clutter

- runtime/src/accounts_db.rs
move code only used by tests into test module.
This makes returning zero lamport accounts easier to wrangle.
Fixes #
> move accounts_db::load_without_fixed_root to test mod

- program-test/src/lib.rs
- programs/bpf/benches/bpf_loader.rs
- programs/bpf/tests/programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- rbpf-cli/src/main.rs
- sdk/src/transaction_context.rs
This PR refactors the serialization code a bit. It does 3 things:
- it removes two loops over the accounts by gathering all the accounts and their original length at once in `serialize_parameters`
- it moves creating the MemoryRegion for the serialized data from `create_vm` to `serialize_parameters`. This is in preparation of merging the direct mapping work, where the serialized data spans multiple regions.
- it introduces an internal `Serializer` builder-like thing to build the serialization data. This too is in preparation of landing the direct mapping work where we build multiple regions
> Serialization refactor

- core/src/leader_slot_banking_stage_metrics.rs
- runtime/src/bank.rs
- runtime/src/transaction_error_metrics.rs
Some of transaction errors are not reported to metrics. 
- reports TooManyAccountLocks and 4 WouldExceed*Limit errors
Fixes #
> report additional transaction errors to metrics

- runtime/src/accounts_db.rs
This allows us to track root progress with a single metric whether it is being done from replay at startup or normal validator operation.
Startup time is sometimes struggling. We have no visibility of the rates we are processing slots.
Fixes #
> log adding root every 10s

- core/src/banking_stage.rs
- core/src/unprocessed_packet_batches.rs
Not all packets left in banking buffer have been selected for forwarding, it is inaccurate to mark all of them as forwarded.
- add `mark_accepted_packets_as_forwarded()` to only mark packet accepted for forwarding as `forwarded`
Fixes #https://github.com/solana-labs/solana/issues/27738 part 1.
> Correctly mark packets as forwarded

- sdk/src/transaction/sanitized.rs
We want to move this check into sanitization, creating a simple preliminary PR to just separate this valdiation from current function.
Separate checks if we can lock accounts for tx (duplicate and count checks) from getting the locks
Fixes #
> separate account locks validation from creating the locks

- ledger/src/blockstore.rs
`Blockstore::get_entries_in_data_block()` pulls individual shreds out of the blockstore in a loop. This type of behavior is well suited to use `multi_get()`
Refactor to use `multi_get_bytes()` to get the gains of a batched read vs multiple individual reads.
Note that this now performs all of the I/O before doing the correctness checks (check for missing shred and `Shred` creation). I think this is a fine tradeoff to make in the name of optimizing the non-error code-path.
I'll try to get some runtime on comparable nodes with this change. For normal replay, I don't expect massive savings since those reads should be hitting memtables (ie recently inserted). However, this should drop fetch time when we're catching up at startup, and for RPC nodes who are serving queries on past slots.
Depends …
> Make Blockstore::get_entries_in_data_block() use multi_get()

- validator/src/main.rs
This PR makes two FIFO-related validator arguments public:
--rocksdb_shred_compaction and --rocksdb_fifo_shred_storage_size.
* There're already ~26 validators running FIFO in mainnet-beta for more than 30 days, no issues were reported so far.
* Ran a validator with FIFO for days and observed it's able to consistently catch up
and create new roots.
> Make FIFO related validator arguments public

- docs/src/integrations/exchange.md
1. fix content to fit rpc example
2. getBlocks use devnet data (it is more easy for users to get the result immediately)
> docs: fix exchanges integration

- runtime/src/accounts_background_service.rs
ABS's snapshot request handler re-calculates the request's `AccountsPackageType` unnecessarily.
Remove the redundant calculation.
> Removes redundant accounts_package_type

- transaction-status/src/parse_associated_token.rs
When a deprecated ATA create instruction doesn't include the (optional) rent sysvar in the account input list, parsing fails.
Ignore the rent sysvar account when parsing ATA create instructions
Fixes #
> RPC: Fix ATA create instruction parsing

- ledger/src/blockstore_processor.rs
load_frozen_forks() finds new slots to process by creating new Banks for the children of the current slot in process_next_slots(). Prior to this change, we would then immediately check if we had reached the halt_at_slot and correctly halt processing when appropriate. As such, it would be possible for Banks to be created for slots beyond the halt_at_slot.
While a potential child slot that is past halt_at_slot wouldn't be replayed, the Bank being created still alters some universal state in AccountsDb. Ie
```
[... ERROR solana_runtime::accounts_db] set_hash: already exists; multiple forks with shared slot <CHILD> as child (parent: <PARENT>)!?
```
`halt_at_slot` is specified in normal operation; we capture the largest slot available during startup and say we'll go no further than that in …
> Fix blockstore_processor::load_frozen_forks() halt_at_slot behavior

- CONTRIBUTING.md
- README.md
Hello :wave:  , this is my first contribution to the project.
* Some links to the existing proposals docs were broken.
* I missed the needed Linux packages (Fedora setup) in the readme for building the project. 
Here are the respective solutions for the commented problems:
* Fix the `CONTRIBUTING.md` proposals links 4622419734ca09540afd7733a909b3fab0f08f9e
* Add the Fedora needed dependencies in `README.md` 19c98cba3681dd192ce7c8f9db0e7586d59d2722
1. I used the official Fedora 36 docker image as base for the tests.
```bash
$ docker run -it --rm fedora:36 bash
```
Rest of the steps are going to be executed on this container.
2. Install Git and Rust
```bash
```
3. At this point, i looked to the packages for the current Ubuntu setup, and found the ones for Fedora. Just installed them. …
> Documentation fixes and improvements

- explorer/src/components/account/UpgradeableLoaderAccountSection.tsx
- explorer/src/providers/accounts/index.tsx
The explorer doesn't support closed program accounts, if it can't find a program data account it falls back to default account details page.
Fixes #
> Explorer: Support displaying closed program accounts

- explorer/src/components/instruction/bpf-upgradeable-loader/BpfUpgradeableLoaderDetailsCard.tsx
- explorer/src/components/instruction/bpf-upgradeable-loader/types.ts
The `ExtendProgram` and `Close` instructions aren't supported by the explorer yet
> Explorer: Support additional bpf upgradeable loader instructions

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
No way to fetch a `jsonParsed` encoded block with web3.js
- Added `Connection.getParsedBlock` method
Fixes #
> feat: add getParsedBlock method to Connection

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
remove non-determinism from `pub accounts_db::load(...)`
See linked pr below. It also links to others. We've tried a few different approaches. I think this one ends up being the most straightforward.
Fixes #
> accounts_db::load returns None for zero lamport accounts

- runtime/src/accounts_db.rs
We get similar coverage from the slot field of bank-forks_set_root; additionally, we can see banks with bank-new_from_parent-heights.
This reverts commit 16853acf354ea855fbf1aa632304ff58689fba58.
`bank-forks_set_root` slot field and `add_root` root are in lock step as you can see; I included the bank-new_from_parent-heights so that you can see that the validator is spinning at this point (the node in this graph had consensus failure for orange flatline)
> Revert "log adding root every 10s (#28280)"

- scripts/cargo-install-all.sh
we are preparing a new release of the token-cli based on solana 1.14, which is incompatible with 1.10 and 1.13 because of the upgrade from rust 1.59 to rust 1.60
lock the 1.10 and 1.13 branches to token-cli version 2.0.17, which builds on rust 1.59
> lock 1.13 cargo-install-all.sh to token-cli 2.0.17

- scripts/cargo-install-all.sh
we are preparing a new release of the token-cli based on solana 1.14, which is incompatible with 1.10 and 1.13 because of the upgrade from rust 1.59 to rust 1.60
lock the 1.10 and 1.13 branches to token-cli version 2.0.17, which builds on rust 1.59
> lock 1.10 cargo-install-all.sh to token-cli 2.0.17

- runtime/src/accounts_db.rs
This is left over code from a while ago. We are updating stats that never get used.
The real stats are updated in a higher function `fn store<'a, T: ReadableAccount + Sync + ZeroLamport>(`
In looking into these stats, it was confusing they were written in 2 places. Turns out this write is ignored.
Fixes #
> eliminate worthless work in store_accounts_to

- ledger/src/blockstore_processor.rs
PR #28317 previously attempted to fix a case where blockstore processing would create children banks for slots past the halt_at_slot.
However, the previous fix didn't handle the case where a slot could be strictly less than the halt_at_slot, but have children that were greater than the halt_at_slot. For example, this could happen if the child of slot S is S+n where n > 1.
The result is that we were corrupting the same state like the other issue
```
[2022-10-12T01:57:50.035632651Z ERROR solana_runtime::accounts_db] set_hash: already exists; multiple forks with shared slot 154881268 as child (parent: 154881259)!?
```
The above log came from a case where halt_at_slot would have been *263, but we still created a bank for *268 as part of `load_frozen_forks()`
```
// Replay existing ledger …
```
> Fix blockstore_processor::load_frozen_forks() halt_at_slot behavior II

- explorer/src/pages/inspector/SimulatorCard.tsx
The `simulateTransaction` method in web3.js used to have a side effect of replacing a simulated message's recent blockhash but that was removed when versioned transaction support was added. The explorer relied on that side effect to work properly during tx simulation.
- Explicitly call `simulateTransaction` with the `replaceRecentBlockhash` option
Fixes #
> Explorer: Fix transaction inspector simulation

- explorer/src/providers/cluster.tsx
The explorer RPC API is restricted to solana.com domains and needs to be manually overridden when running the explorer locally.
- Don't use the explorer RPC API for localhost env
Fixes #
> Explorer: Disable cluster url replacement on localhost

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
The `GetAccountInfoConfig` and `GetMultipleAccountsConfig` types don't support the `dataSlice` config yet
> feat: add dataSlice param to account fetching config

- explorer/src/__tests__/parseNFTokenAccounts.ts
- explorer/src/components/account/AnchorAccountCard.tsx
- explorer/src/components/account/RewardsCard.tsx
- explorer/src/components/account/StakeAccountSection.tsx
- explorer/src/components/account/TokenAccountSection.tsx
- explorer/src/components/account/UnknownAccountCard.tsx
- explorer/src/components/account/UpgradeableLoaderAccountSection.tsx
- explorer/src/components/account/address-lookup-table/AddressLookupTableAccountSection.tsx
- explorer/src/components/account/nftoken/isNFTokenAccount.ts
- explorer/src/pages/AccountDetailsPage.tsx
- explorer/src/pages/inspector/AddressWithContext.tsx
- explorer/src/providers/accounts/index.tsx
- explorer/src/providers/accounts/utils/isMetaplexNFT.ts
- explorer/src/utils/index.ts
The account provider data type is clunky because too many fields can be undefined
- Initialize all account metadata fields for accounts that don't exist
- Clean up parsed vs raw data type representation
- Clean up type handling
Fixes #
> Explorer: Refactor account provider data types

- programs/zk-token-proof/src/lib.rs
- zk-token-sdk/src/errors.rs
- zk-token-sdk/src/instruction/close_account.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/instruction/pubkey_validity.rs
- zk-token-sdk/src/instruction/withdraw.rs
- zk-token-sdk/src/instruction/withdraw_withheld.rs
- zk-token-sdk/src/sigma_proofs/errors.rs
- zk-token-sdk/src/sigma_proofs/mod.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
- zk-token-sdk/src/transcript.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
Currently there is no mechanism for a user of confidential tokens to prove the validity of an ElGamal public key.
Add a proof-of-knowledge public key validity proof instruction for the twisted ElGamal public key.
> [zk-token-sdk] add pubkey proof

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
We're about to rework accounts hash caching to reduce memory spikes. This refactoring aids that.
Fixes #
> refactoring of accounts hash to prepare for using files always

- Cargo.lock
- bench-tps/Cargo.toml
- bench-tps/src/main.rs
- cli-config/Cargo.toml
- cli-config/src/lib.rs
- genesis/Cargo.toml
- genesis/src/main.rs
- install/Cargo.toml
- install/src/config.rs
- programs/sbf/Cargo.lock
- validator/Cargo.toml
Earlier attempt to bump serde_yaml broke gce testnets with bench-tps clients because of the breaking change in[ v0.9.0](https://github.com/dtolnay/serde-yaml/releases/tag/0.9.0) to remove leading `---\n` strings and [this assumption](https://github.com/solana-labs/solana/blob/f627b7d8267e74a7a905178731ffb185fc0e92f5/net/remote/remote-node.sh#L196)
cc @behzadnouri 
In addition to performing the serde_yaml bump to v0.9.13, manually prepend `---\n` to all yaml files we write.
Confirmed that v0.9.13 reads existing v0.8 format yaml files correctly.
Dependabot notes duplicated:
* chore: bump serde_yaml from 0.8.26 to 0.9.13
Bumps [serde_yaml](https://github.com/dtolnay/serde-yaml) from 0.8.26 to 0.9.13.
- [Release notes](https://github.com/dtolnay/serde-yaml/releases)
- …
> chore: bump serde_yaml from 0.8.26 to 0.9.13

- core/src/progress_map.rs
- core/src/replay_stage.rs
We have transactions counted in replay-slot-end-to-end-stats, but that metric is broken down to report things per thread. Given that this will be machine dependent based on what all is available when replaying segments of the slot and the rebatching that occurs, this number won't be consistent between nodes.
So, report total_transactions for the entire slot (all threads) in replay-slot-stats.
> Report total_transactions in replay-slot-stats

- zk-token-sdk/src/encryption/discrete_log.rs
- zk-token-sdk/src/encryption/errors.rs
- zk-token-sdk/src/encryption/mod.rs
- zk-token-sdk/src/errors.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
The errors types that are purely associated with the ElGamal encryption scheme is contained under `ProofError` that should be related to proof generation and verification.
Create a dedicated `EncryptionError` type and use it for errors associated with ElGamal enryption. This removes some types in the `ProofError`. This should be okay since zk tokens are not yet enabled.
> [zk-token-sdk] Restructure proof error types

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
Lack of method for fetching multiple parsed accounts in one request
- Added `getMultipleParsedAccounts` method to `Connection`
Fixes #
> feat: add getMultipleParsedAccounts method

- web3.js/src/connection.ts
It's _conceivable_ that someone could open up so many WebSocket connections (ie. in a long running Node process) so as to exhaust this index. JavaScript integers, after all, have a maximum value of `Number.MAX_SAFE_INTEGER`.
Upon hearing a report of someone with a script that works from Saturday to Thursday but then crashes with the dreaded infinite recursion bug (see #26198) I immediately thought that this index might be overflowing, essentially _pinning_ it to a constant value from `Number.MAX_SAFE_INTEGER + 1` onward.
Wrap the index back around to 0 after hitting `Number.MAX_SAFE_INTEGER`.
Addresses #26198. Closes #28426.
> fix: wrap _rpcWebSocketGeneration around when about to overflow

- Cargo.lock
- cli/src/cli.rs
- cli/src/wallet.rs
- docs/sidebars.js
- docs/src/cli/sign-offchain-message.md
- docs/src/wallet-guide/hardware-wallets/ledger.md
- programs/sbf/Cargo.lock
- remote-wallet/src/ledger.rs
- remote-wallet/src/ledger_error.rs
- remote-wallet/src/remote_wallet.rs
- sdk/Cargo.toml
- sdk/src/lib.rs
- sdk/src/offchain_message.rs
https://github.com/solana-labs/solana/issues/21366
Adds signing of non-transaction messages with a Solana wallet. This feature can be used to authenticate users or provide proof of wallet ownership.
See [Docs](https://github.com/solana-labs/solana/pull/27456/files#diff-6259934a49f0f3a75b91507a9aec073ca7726d632c7d84fc13c9f3790c0d979b) for more details.
In accordance with the [Proposal](https://github.com/solana-labs/solana/blob/e80f67dd58b7fa3901168055211f346164efa43a/docs/src/proposals/off-chain-message-signing.md).
Off-chain messages can be signed and verfied using Solana CLI and any of the supported wallets including Ledger. Latest firmware and Solana Ledger App v1.3.0 or higher is required for this feature to work.
Fixes #
> Add off-chain messages support

- ci/buildkite-pipeline.sh
- ci/test-stable.sh
`stable-sbf` ci job is still targeting the `gcp` buildkite queue, which was recently decommissioned
move it to the `solana` buildkite queue
> ci: move `stable-sbf` job to `solana` queue

- ci/buildkite-pipeline.sh
all ci jobs are not run when the pipeline generator script changes
add pipeline generator script to mandatory affects list
> ci: run all jobs when the pipeline generator script changes

- cli/src/program.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/sbf/benches/bpf_loader.rs
- programs/sbf/tests/programs.rs
- rbpf-cli/src/main.rs
`create_executor()`s interfaces make it hard to use from other crates such as the runtime.
This PR introduces `create_executor_from_account()` which allows the bank to crate executors form accounts it loaded.
- Moves `disable_deploy_of_alloc_free_syscall` parameter inside `create_executor()`.
- Lets `register_syscalls()` take `&FeatureSet` only instead of the entire `InvokeContext`.
- Uses `ic_logger_msg!()` instead of `ic_msg!()` inside `create_executor()`.
- Inlines `map_ebpf_error()`.
- Adds `register_syscalls_us` to `executor_metrics::CreateMetrics`.
- Moves timings accumulation into `executor_metrics::CreateMetrics::submit_datapoint()`.
- Moves `&invoke_context.feature_set` into a variable.
- Lets `create_executor()` return `executor_metrics::CreateMetrics` via a mutable parameter.
- …
> Refactor - create_executor() to be usable outside of bpf_loader

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
- runtime/src/cache_hash_data.rs
accounts hash calc currently consumes large spikes of memory while it is scanning, sorting, de-duping, and hashing.
We can leverage the cache files we were already making to just mmap and scan files instead of pulling into memory. The result is more negligible memory spikes.
Fixes #
> accounts hash calculation uses files instead of memory

- runtime/src/accounts.rs
- runtime/src/accounts_cache.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/snapshot_minimizer.rs
- runtime/src/storable_accounts.rs
- runtime/tests/accounts.rs
- sdk/src/feature_set.rs
#28404
To facilitate eliminating rewrites during rent collection, we need a feature to stop using the slot an account was written in its hash calculation.
Implement a feature (#28420) to change the account hash calculation.
Fixes #
Feature Gate Issue: #28420
> remove slot# from account hash

- core/src/ancestor_hashes_service.rs
- core/src/serve_repair.rs
- gossip/src/cluster_info.rs
- gossip/src/ping_pong.rs
https://github.com/solana-labs/solana/pull/27193 added hash domain to ping-pong protocol.
For backward compatibility responses both with and without domain were generated and accepted.
Now that all clusters are upgraded, this commit enforces the hash domain by removing the response without the domain.
enforce hash domain for ping-pong protocol
> enforces hash domain for ping-pong protocol

- program-test/src/lib.rs
- program-test/tests/cpi.rs
When working in "native mode" in program-test, the syscall to `sol_get_stack_height` defaults to 0, as noticed during https://github.com/solana-labs/solana-program-library/pull/3712
We have the information, so implement the real thing from the invoke context.
Fixes #
cc @2501babe
> program-test: Add working `get_stack_height` stub call

- .mergify.yml
v1.10 is EOL, but mergify is still creating backports for it
stop
> ci: v1.10 is EOL. stop creating backports for it

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
simplify code for ancient append vecs.
The idea was to differentiate between 'full' ancient append vecs and 'non-full' ones.
This idea is not necessary. We can always try to add more accounts to any ancient append vec. If it fills up, the code already has to handle the case where we create a new ancient append vec and continue appending accounts there.
Remove 'full' ancient append vecs as a concept.
Fixes #
> remove concept of 'full' ancient append vec

- zk-token-sdk/src/zk_token_elgamal/ops.rs
Some parts of the pod ElGamal arithmetic operations are either outdated or unnecessary.
- remove unnecessary pod arithmetic components
- add docs for arithmetic functions
- update tests
> [zk-token-sdk] clean up pod ciphertext arithmetic operations

- account-decoder/src/lib.rs
- docs/src/developing/clients/jsonrpc-api.md
- rpc/src/rpc.rs
RPC account encoding ignores the data slice config when falling back to base64 encoded account data when `jsonParsed` encoding fails
If `jsonParsed` encoding fails, ensure that the data slice config is still used when doing base64 encoding
Fixes #
> RPC: respect data slice config if account parsing fails

- transaction-dos/src/main.rs
We are on the process of removing `solana deploy` along with all related functionality.
This PR is prerequisite for https://github.com/solana-labs/solana/pull/28399
Replace call for `program_deploy` to call to `process_command` with underlying command `CliCommand::Program(ProgramCliCommand::Deploy { ... })`
> get rid of process_deploy call in transaction-dos

- client/src/connection_cache.rs
- core/src/fetch_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
- local-cluster/src/local_cluster.rs
- multinode-demo/bootstrap-validator.sh
- multinode-demo/validator.sh
- net/net.sh
- net/remote/remote-node.sh
- rpc-test/tests/rpc.rs
- test-validator/src/lib.rs
- validator/src/main.rs
make UDP based TPU off by default (backport #27462) (#27658)""
This reverts commit 411f0a32e33b5864a857c46105fb20deab7c1d17.
Fixes #
> Added option to turn on UDP for TPU transaction and

- core/src/serve_repair.rs
reenable ping/pong support for repair requests.
Enable ping creation/verification for repair requests.
See #27910 for reference.
Fixes #
> enable repair ping/pong cache

- ledger-tool/src/main.rs
base58 encoding accounts data is painfully slow, not useful at all _and default behavior for ledger-tool_
* switch default to base64
* remove ability to specify base58 for any data encodings
> ledger-tool: remove inefficient base58 encoding options

- runtime/src/bank.rs
account stats accumulation into `TotalAccountsStats` is performed in a method on `Bank` with an inconvenient interface
move accumulation logic out to a helper on `TotalAccountStats` to ease reuse
> bank: factor accumulation out to helper on `TotalAccountsStats`

- cli-output/src/cli_output.rs
- cli/src/wallet.rs
ctor for `CliAccount` is hiding in the `cli` crate and i wanna use it somewhere else
move it to `cli-output` where it can be reused
> cli-ouput: add ctor for `CliAccount`

- web3.js/test/connection-subscriptions.test.ts
- web3.js/test/connection.test.ts
#28421 added a `space` param to this response.
* Updated the web3.js tests to expect it.
> test: repair tests, `space` having been added to the account response

- docs/src/proposals/timely-vote-credits.md
Validators can intentionally delay voting in order to survey forks and make voting choices that are less likely to be on losing forks.
Added a proposal for awarding more vote credits for votes that have less lag.
> proposal: Added timely vote credits proposal.

- rpc-client-api/src/filter.rs
- rpc-client-api/src/lib.rs
- rpc-client-api/src/version_req.rs
As per #28413, using the latest master version, the command `program show --programs` presents the following error when using `--url devnet`
```
Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`. 
```
This is because there was a rpc-client version check for nodes below v1.11.2 which didn't get updated when v1.10 got tied to v1.13 and v1.11 got warped to v1.14.
Add VersionReq struct to provide tooling to handle cases when we need to match on multiple, non-contiguous versions.
Update mapping in MemCmp filters to check for versions before `v1.11.2` and any `v1.13` patch.
Replaces #28413 as fix, but I also want to consider that change for efficiency reasons
Fixes #28265
> Fix RpcClient MemCmp filter version mapping

- client/src/lib.rs
- client/src/rpc_filter.rs
- client/src/version_req.rs
#28499 for v1.14 (lots of client re-org on master, so did manually to be careful with the rebase)
> v1.14: Fix RpcClient MemCmp filter version mapping

- cli/src/cli.rs
- cli/src/program.rs
- sdk/program/src/bpf_loader.rs
- sdk/program/src/bpf_loader_upgradeable.rs
This PR is to remove `solana deploy` command, see https://github.com/solana-labs/solana/issues/27834
This PR depends on:
https://github.com/solana-labs/solana/pull/28398 (merged)
https://github.com/solana-labs/solana/pull/28448 (merged)
* Removes `deploy` subcommand
* Removes mentions of `solana deploy` command from code documentation
> Remove immutable deploy

- system-test/deprecated-testcases/gce-gpu-perf-100-node.yml
- system-test/partition-testcases/gce-5-node-3-partition.yml
- system-test/partition-testcases/gce-5-node-single-region-2-partitions.yml
- system-test/partition-testcases/gce-partition-once-then-stabilize.yml
- system-test/partition-testcases/gce-partition-recovery.yml
- system-test/partition-testcases/gce-partition-with-offline.yml
- system-test/performance-testcases/gce-cpu-only-perf-10-node.yml
- system-test/performance-testcases/gce-cpu-only-perf-5-node-single-region.yml
- system-test/performance-testcases/gce-cpu-only-perf-5-node.yml
- system-test/performance-testcases/gce-gpu-perf-10-node-single-region.yml
- system-test/performance-testcases/gce-gpu-perf-10-node.yml
- system-test/performance-testcases/gce-gpu-perf-25-node-single-region.yml
- system-test/performance-testcases/gce-gpu-perf-25-node.yml
- system-test/performance-testcases/gce-gpu-perf-5-node-single-region.yml
- system-test/performance-testcases/gce-gpu-perf-5-node.yml
- system-test/performance-testcases/gce-gpu-perf-50-node-single-region.yml
- system-test/performance-testcases/gce-gpu-perf-50-node.yml
- system-test/restart-testcases/restart_gce.yml
- system-test/stability-testcases/gce-perf-stability-5-node-single-region.yml
- system-test/stability-testcases/gce-stability-5-node.yml
- system-test/stake-operations-testcases/offline_stake_gce.yml
A earlier thread with Trent https://discord.com/channels/428295358100013066/1031929516383281154/1032472304472563752
The main idea is that we would like to more close user's experience
Use n2-standard-32 in all performance tests.
There is a test sample: https://discord.com/channels/428295358100013066/1031929516383281154/1032709168278282240
> chore: all gce performance tests use n2-standard-16

- net/remote/remote-node.sh
remote-node script waits until we catch up to bootstrap validator before delegating stake. Because we drop votes from unstaked validators no votes will land. The sanity check does not allow staking to validators that haven't voted.
Use the already existing --force flag to bypass the check.
Fixes #
> remote-node script use --force when delegating stake

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/expected_rent_collection.rs
- runtime/src/lib.rs
- sdk/src/feature_set.rs
> testnet fixup: only update rent_epoch on load until feature

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
the accounts scanning interfaces have a _seemingly_ unnecessary `Default` requirement, which restricts what types can be used to collect in to.
switch to `FnMut` closures and move the accumulator construction out to the call sites
> runtime: remove `Default` req on account scan interfaces

- rpc/src/rpc.rs
Error messages for decoding failures in RPC responses aren't very clear. For example, an invalid base64 encoded message passed to `getFeeForMessage` could return "InvalidLength" as an error message and it's not clear that this is related to invalid base64 encoding or some other invalid length in deserialization or message sanitization.
- Use more verbose error messages for errors from dependency crates like bs58 and base64
- Expand test coverage for error cases
Fixes #
> RPC: Improve error messages for decoding errors

- sdk/src/feature_set.rs
we need this feature in master, for activation on mnb.
However, it is not compatible with mnb.
So, when it is activated on mnb, it will do nothing.
The changes affected by this feature's activation will only exist in 1.14 and only temporarily long enough to fix testnet.
Fixes #
> feature 28541 no-op

- docs/src/developing/clients/javascript-api.md
- docs/src/developing/clients/javascript-reference.md
- docs/src/integrations/retrying-transactions.md
The core docs use the deprecated calls for `connection.confirmTransaction`
Update the example code snippets to use the non-deprecated method call for `connection.confirmTransaction` using the `BlockheightBasedTransactionConfirmationStrategy`
Here is the `@solana/web3.js` docs for [`confirmTransaction`](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#confirmTransaction) for reference.
> [docs] corrected use of confirmTransaction in examples

- scripts/build-downstream-projects.sh
https://buildkite.com/solana-labs/solana/builds/84345#01840d4d-81e9-42b2-92cc-c191d06f3679
we should build spl-instruction-padding in the ci script.
add it.
> chore: add spl-instruction-padding/program to downstream ci script

- ledger/src/blockstore.rs
- programs/sbf/tests/programs.rs
- rpc-client/src/mock_sender.rs
- rpc/src/transaction_status_service.rs
- runtime/src/bank.rs
- storage-proto/proto/confirmed_block.proto
- storage-proto/src/convert.rs
- transaction-status/src/lib.rs
- transaction-status/src/parse_instruction.rs
The inner instruction stack height isn't recorded after transaction processing so clients can't determine if an inner instruction was invoked by another inner instruction.
Builds on https://github.com/solana-labs/solana/pull/28427
- Record `stack_height` in a new `InnerInstruction` protobuf message type for each inner instruction
- Add a new `stack_height` field to instruction data types returned by the RPC API
Related to https://github.com/solana-labs/solana/issues/27736
> Record inner instruction stack height

- ci/do-audit.sh
A few RUSTSEC advisories have been ignored over the years, but the crates have since upgraded for the most part!
Remove ignores that aren't needed anymore.
Fixes #
> ci: Remove unneeded ignores in audit

- ci/buildkite-solana-private.sh
the `local-cluster-slow` is outdated
use new steps local-cluster-slow-1 and local-cluster-slow-2
> chore: fix solana-private pipeline

- docs/src/proposals/versioned-transactions.md
There is a minor typo.
Fixed the minor typo.
Ironically, I had a typo when I named this branch!
> Minor typo fix.

- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- sdk/program/src/program_stubs.rs
- sdk/src/feature_set.rs
Some syscalls have multiple outputs which are written back to buffers provided in the parameters. C users could accidentally provide overlapping buffers, which is kind of a foot gun.
- Extends `is_nonoverlapping()` to be able to deal with two different lengths.
- Uses `is_nonoverlapping()` for syscall output parameters.
- Feature gates the new throws of `SyscallError::CopyOverlapping`.
- Adds tests which trigger `SyscallError::CopyOverlapping`.
Feature Gate Issue: #28600
> Feature - Check syscall outputs do not overlap

- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- sdk/program/src/program_stubs.rs
- sdk/src/feature_set.rs
Backport of #28599 to v1.14, without the tests.
> Backport of #28599 to v1.14

- programs/bpf_loader/src/syscalls.rs
- sdk/program/src/program_stubs.rs
- sdk/src/feature_set.rs
Backport of #28599 to v1.13, without the tests.
> Backport of #28599 to v1.13

- client/src/quic_client.rs
Limit the number async tasks spawned to the runtime to avoid congestions.
Co-authored-by: Lijun Wang <83639177+lijunwangs@users.noreply.github.com>
Fixes #
> Limit async tasks spawn to runtime for quic transaction send (backport #28452) (#28603)

- sdk/src/ed25519_instruction.rs
- sdk/src/precompiles.rs
- sdk/src/secp256k1_instruction.rs
- sdk/src/transaction/mod.rs
- sdk/src/transaction/sanitized.rs
Looking through code and noticed this is (maybe?) more restrictive than necessary
Don't require precompile verify to pass a reference to `Arc<FeatureSet>`
Fixes #
> precompile verify: &Arc<FeatureSet> to &FeatureSet

- core/src/ancestor_hashes_service.rs
- core/src/cluster_slot_state_verifier.rs
- core/src/replay_stage.rs
When there is a bug in the runtime we get stuck in a repair/purge loop due to bank hash mismatches. In this state there is no way for the validator to recover so it's best to exit and not spam the network. 
Track a purge counter and exit validator when we exceed it for a single slot. 
Fixes #28511
> Exit when stuck in an unrecoverable repair/purge loop

- account-decoder/src/parse_account_data.rs
- cli-output/src/cli_output.rs
need a finer grained constructor for `CliAccount`
add a config-based constructor
> cli-output: add config ctor for CliAccount

- core/src/ledger_cleanup_service.rs
- core/src/tvu.rs
- core/src/validator.rs
- core/tests/ledger_cleanup.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore/blockstore_purge.rs
- local-cluster/src/validator_configs.rs
- test-validator/src/lib.rs
- validator/src/main.rs
The manual Blockstore compaction that was being initiated from LedgerCleanupService has been disabled for quite some time in favor of several optimizations.
Rip out the dead code (and eliminate one thread)
I was poking around LedgerCleanupService following an idea I discussed with Yueh-Hsuan, and then was reminded of the dead code in there. So, I decided to pick up some of the cleanup from https://github.com/solana-labs/solana/pull/27529. However, that PR modified compaction and purge routines. I thought it'd be more manageable to handle one item per PR, so here is just the compaction stuff. The compaction removal is more straightforward than the purge change as well, so this should be a less complex review.
> Remove Blockstore manual compaction code

- frozen-abi/macro/src/lib.rs
make diff command in the error message of abi assert on a new line so that is is easier to copy and paste. 
add line separator before diff command
Fixes #
> make diff command on new line in abi error message

- core/src/unprocessed_transaction_storage.rs
#28654 - v1.15 PR.
Reserve a new queue and verify capacity after processing/forwarding.
Fixes #
> Maintain original queue capacity for unprocessed packet buffer

- .github/workflows/docs.yml
- .github/workflows/release-artifacts.yml
[GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
replace all ::set-output with >> $GITHUB_OUTPUT
> chore: use >> $GITHUB_OUTPUT instead of ::set-output

- explorer/src/components/account/TokenAccountSection.tsx
No freeze authority was being displayed for NFTs
Display Freeze Authority for NFTs
Fixes #
> show freeze authority for NFTs

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
- runtime/src/append_vec.rs
- runtime/src/storable_accounts.rs
pubkey is already available in `StoredAccountMeta`.
Including in the tuple when we store just causes us to add duplicate information.
Remove pubkey from the tuple and get the pubkey from StoredAccountMeta.
Fixes #
> remove duplicate pubkey when shrinking or combining ancient

- tpu-client/src/connection_cache_stats.rs
- tpu-client/src/nonblocking/quic_client.rs
- tpu-client/src/quic_client.rs
- tpu-client/src/tpu_connection.rs
Time out async sends to avoid slackers stuck in the queue for too long impacting future sends.
Use Tokio::timeout to timeout the async sends.
Fixes #
> Time out async sends to avoid slackers stuck in the queue for too long

- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/rent_collector.rs
feature is activated on all clusters
removed feature gate code
Fixes #26509
> removes feature gate code preserving rent_epoch for rent exempt accounts

- runtime/src/accounts_db.rs
allow better testing of ancient append vecs by controlling whether they can randomly shrink
Fixes #
> ancient append vecs: pass through can_randomly_shrink

- sdk/program/src/example_mocks.rs
- sdk/program/src/system_instruction.rs
- sdk/program/src/system_program.rs
Adds documentation for the module, and functions `create_account`, `alloc`, `assign`, `transfer`, and `transfer_many`.
Fixes #
> Add docs for system_instruction and some of its functions

- core/src/tpu.rs
- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
- tpu-client/tests/quic_client.rs
In the quic server handle_connection, when we timed out in receiving the chunks, we loop forever to wait for the chunk. If the client never provide another chunk, the server can hopelessly wait for that chunk and wasting server resources. Instead WAIT_FOR_CHUNK_TIMEOUT_MS is introduced to bound this to 10 seconds at maximum. The stream will be dropped if it times out.
Fixes #
> Enforce stream receive timeout

- clap-utils/src/keypair.rs
- clap-v3-utils/src/keypair.rs
When running cilppy linter on Windows, clippy warns about using string for single character for such lines:
```
source.replace("\\", "/")
```
Fixes #
Both lines were changed to this:
```
source.replace('\\', "/")
```
> Fix clippy warnings on Windows

- Cargo.lock
- sdk/cargo-build-sbf/src/main.rs
- sdk/cargo-test-sbf/Cargo.toml
- sdk/cargo-test-sbf/src/main.rs
cargo-test-sbf doesn't pass additional parameters to cargo, limiting the versatility of the tool.  The extra args specified after `--` command line option are forwarded to the test harness executable which is the expected behavior. Thus it is not possible to fully control the underlying cargo process that cargo-test-sbf uses to build and run the tests.
Add an option to specify packages in a workspace to be tested instead of testing all packages in a workspace.
> Add to cargo-test-sbf an option to test specific packages

- runtime/src/accounts_db.rs
A stat used by shrink is not used by ancient append vecs.
Don't report this stat.
Fixes #
> remove unused stat ancient.skipped_shrink

- .github/workflows/client-targets.yml
They fixed the ring crates building issue. `https://github.com/bbqsrc/cargo-ndk/issues/76`
We don't need to stuck in the old version anymore. Bump it to the latest.
bump cargo-ndk to 2.12.2
Close #28153
> chore: bump cargo-ndk to v2.12.2

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/discrete_log.rs
- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/pedersen.rs
Updating and adding additional docs for the encryption part of the `zk-token-sdk`.
> [zk-token-sdk] Update docs for encryption in zk-token-sdk

- net/net.sh
- net/remote/remote-client.sh
- net/remote/remote-node.sh
Currently, there's not convenient way to choose the client type in the net scripts.
Add such an option
Fixes #
> Add ability to choose client type in GCE cluster scripts

- .github/workflows/client-targets.yml
`actions-rs/cargo` doesn't maintain for a long time. I would like to get rid of it.
- separate ios and android into different jobs
- build them with our stable and nightly version
- use Github Actions built-in NDK version. (r25)
- trigger pipeline when `ci/rust-version.sh` changed
> ci: build ios and android in our stable and nightly

- sdk/macro/src/lib.rs
- sdk/program/src/clock.rs
- sdk/program/src/epoch_schedule.rs
- sdk/program/src/lib.rs
- sdk/program/src/rent.rs
- sdk/program/src/sysvar/fees.rs
- sdk/src/lib.rs
`clone_zeroed()` is currently manually implemented for every struct.
That is risky because someone might be changing the definition but forget to update the `impl Clone`.
Automates `impl Clone` by introducing a derive proc macro.
> Refactor - derive `CloneZeroed`

- runtime/src/snapshot_utils.rs
Code is somewhat hard to read, and somewhat redundant.
Refactor to get the snapshot archive info first.
> Refactors snapshot_archive_info in bank_from_snapshot_archives()

- sdk/program/src/serde_varint.rs
- sdk/program/src/syscalls/mod.rs
There are a few undocumented top level items in solana-program
Add descriptions. Document clone_zeroed and copy_field but make them `doc(hidden)` since they are not useful to program authors.
> Add missing solana-program docs

- runtime/src/accounts_db.rs
- runtime/src/snapshot_minimizer.rs
all stats from `drop_or_recycle_stores` were going to `shrink_stats`
correctly use `ancient_shrink_stats`
Fixes #
> report ancient stats correctly in drop_or_recycle_stores

- client/src/connection_cache.rs
- client/src/nonblocking/quic_client.rs
- client/src/quic_client.rs
- client/src/tpu_connection.rs
* Time out async sends to avoid slackers stuck in the queue for too long (#28545)
> Backport timeout async send tasks to v1.13

- program-runtime/src/executor.rs
- program-runtime/src/executor_cache.rs
- program-runtime/src/lib.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/bank.rs
For the new loader built-in program it would be useful to share these.
- Moves `CreateMetrics` into the program-runtime crate.
- Moves the `Executor` trait into executor.rs
- Removes the first_instruction_account parameter from `Executor::execute()`.
> Refactor - Move `Executor` in program-runtime crate

- runtime/src/accounts_db.rs
ancient append vecs are shrinking everytime there is at least one dead account
use a ratio to pick ancient append vecs to shrink
Fixes #
> shrink ancient append vecs at 90%

- program-runtime/src/compute_budget.rs
- programs/bpf_loader/src/syscalls/mod.rs
- sdk/program/src/instruction.rs
- sdk/program/src/program_stubs.rs
- sdk/program/src/syscalls/definitions.rs
- sdk/src/transaction_context.rs
Using type inference in the VM might allow us to avoid memory address translation in ABIv2 all together. Thus, the syscall would become useless.
Removes `SyscallSetAccountProperties`, `AccountPropertyUpdate` and `TransactionContextAttribute`.
> Revert #27444

- ledger-tool/src/main.rs
- runtime/src/accounts_db.rs
- validator/src/main.rs
For testing ancient append vecs, allow caller to specify an offset for how many additional slots within the last epoch to include into ancient append vecs. This causes the ancient append vec code to run more normally while we're still collecting rent.
Ancient append vecs are behind this cli arg, so this will not affect any real validators or tests.
Fixes #
> allow ancient append vec threshold to be set on cli

- core/src/unprocessed_transaction_storage.rs
refactor (per #28146 ) to check and filter is_forwarded packets earlier.
- combines checking for is_forwarded and is_tracer into single iteration, 
- move the logic into a separate function, add test
Fixes #28146
> check is_forwarded packet earlier

- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
The inversion method in the ElGamal pubkey derivation was removed when I was adding additional comments and cleaning up the code.
- Add the inversion method again
- Augment the tests so that these type of misses can be caught in the future
> [zk-token-sdk] Fix ElGamal key derivation

- runtime/src/bank.rs
@jeffwashington informed me that https://github.com/solana-labs/solana/pull/28690/ was failing in CI due to an error in `test_accounts_data_size_and_resize_transactions()`:
https://buildkite.com/solana-labs/solana/builds/85042#01847837-100f-41b7-af5a-fe94c67358f6
Running locally, I observed this test failing intermittently will this error:
```
[2022-11-15T14:29:15.554837000Z DEBUG solana_runtime::bank] tx error: MaxLoadedAccountsDataSizeExceeded SanitizedTransaction { message: Legacy(LegacyMessage { message: Message { header: MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }, account_keys: [J6MEcxb4f4oeePxv1RvzCyzhfXpi8SkJUAMfEWCLNSRh, 11111112cMQwSC9qirWGjZM6gLGwW69X22mqwLLGP, 7QmP1NzaR3SfDfKZBZ28LM6Wt4ii19AAFM2jMWcZJDg1, …
```
> Lowers test's account data size to avoid hitting MaxLoadedAccountsDataSizeExceed

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
the larger ancient append vecs get, the longer scanning them for accounts hash is taking.
Metrics for this will be important.
Fixes #
> add scan statistics in hash calc for ancient append vecs

- bucket_map/src/bucket_storage.rs
The test didn't clean up it's "temp" directory. If you change users this causes the test to fail since the directory won't have correct permissions.
Ran into this when I switched from using `sol` user to my personal username on a machine. Unlikely to cause many other people issues, but easy enough to fix. 
Use an actual tempdir so it cleans itself up.
Fixes #
> use a tempdir in test_bucket_storage

- sdk/src/quic.rs
- streamer/src/nonblocking/quic.rs
Address one of the security review findings.
Initially QUIC concurrent streams were capped at 2048, an empirical number
that maximized TPS as measured on GCP, and based on tests results higher
values had no impact on TPS nor on overall performance. Since then,
this limitation was replaced with QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS
and QUIC_MIN_STAKED_CONCURRENT_STREAMS which are both set to 128. Cur-
rently compute_max_allowed_uni_streams returns the amount of unidirec-
tional streams for a specific peer based on stake weight and there is no
upper limit to the number of streams.
Consequently, a highly staked node can open an excessive number of unidi-
rectional streams, which do not provide any significant benefits in terms
of TPS, while those streams could otherwise be reused by other …
> Limit the maximum staked streams to avoid excessive streams from staked nodes

- core/src/ancestor_hashes_service.rs
- core/src/serve_repair.rs
pubkey mismatch in tests
fix/cleanup signed repair request tests
Fixes #
> signed repair request test fixes/cleanup

- rpc-client-api/src/response.rs
- rpc-client/src/nonblocking/rpc_client.rs
- rpc-client/src/rpc_client.rs
- rpc/src/rpc.rs
As per #25869, `RpcClient::get_program_accounts_with_config()` cannot deserialize the responses from all current clusters when `with_context` is set to true. https://github.com/solana-labs/solana/pull/17399 added the `OptionalContext` wrapper to the response from the `getProgramAccounts` RPC endpoint, but didn't add any handling to client methods. This has been broken in practice since whenever that change was released to public clusters, which unfortunately means all current branches.
Add support for OptionalContext to `nonblocking::RpcClient::get_program_accounts_with_config()`
Fixes #25869
> Fix client get_program_accounts_with_config calls with context

- streamer/src/quic.rs
MAX_CONCURRENT_UNI_STREAMS and receive_window could overflow.
This is found when experimenting with QUIC_MAX_UNSTAKED_CONCURRENT_STREAMS for
unthrottled quic streams.
https://github.com/solana-labs/solana/pull/28837
Make the calculation saturating.
Fixes #
> saturating max_concurrent_uni_streams and receive_window instead of overflow

- program-runtime/src/compute_budget.rs
- runtime/src/bank.rs
`test_accounts_data_size_and_resize_transactions():` generate random account data size without compute_budget instruction to set tx's max data size. When the randomly generated account size exceeds default 10M limit, transaction will fail due to `MaxLoadedAccountsDataSizeExceeded`
- add compute_budget instruction to set correct tx max data size limit
Fixes #
> fix account resize test by requesting max tx data size

- core/src/serve_repair.rs
repair requests from staked nodes should be prioritized.
For each iteration we will select `MAX_REQUESTS_PER_ITERATION` requests to process. Accept up to `2 * MAX_REQUESTS_PER_ITERATION` packets before load shedding packets in the incoming channel. Select top `MAX_REQUESTS_PER_ITERATION` requests by stake of requesting node.
Limiting this change to testnet.
Fixes #
> limit repairs to top staked requests in batch

- rpc-client-api/src/config.rs
- rpc/src/rpc.rs
- runtime/src/accounts_index.rs
- runtime/src/bank.rs
- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
Add support to RCP API for querying the size of a specific secondary index key.
toward https://github.com/solana-labs/solana/issues/28666
> Get Index Key Size RPC Support

- ledger-tool/src/main.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
`ledger-tool accounts` buffers all accounts before printing them to console. with the number of accounts on some of the public cluster, this consumes an unreasonable amount of memory, requiring absurd hardware to do what should be a fairly trivial task
stream the output while we scan instead of buffering
> ledger-tool: stream output of `accounts` subcommand

- core/src/banking_stage.rs
- core/src/qos_service.rs
Lots of code in banking stage for calculating/accumulating costs. Cleaner to have this elsewhere imo.
Move cost model calculation, selection, accumulation into qos_service.
Fixes #
> refactor: move more BankingStage cost_model stuff into qos_service

- runtime/benches/append_vec.rs
- runtime/src/append_vec.rs
Remove a public api that is only used for testing.
This allows us to optimize the remaining public api for performance and simplicity.
Fixes #
> remove test only append_account

- Cargo.lock
- quic-client/Cargo.toml
- quic-client/src/lib.rs
- tpu-client/src/tpu_connection_cache.rs
- udp-client/Cargo.toml
- udp-client/src/lib.rs
Currently, Tpu connection actions like creating a self-sign tls cert chain (Quic) or binding to a socket (Udp) are done in default implementations, which cannot be fallible, and success asserted. This means we cannot handle any errors sensibly.
- Replace TpuConfig Default impl with FallibleCtor trait
- Add Quic/UdpClientError enums
- Make TpuConnectionCache::new() fallible, and add new_with_config() helper fn as infallible alternative
Toward #28401
> Remove Default impls for TpuConnectionCache and ConnectionPool clients

- zk-token-sdk/src/curve25519/edwards.rs
- zk-token-sdk/src/curve25519/ristretto.rs
- zk-token-sdk/src/curve25519/scalar.rs
- zk-token-sdk/src/errors.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
Currently, convertion from `PodScalar` to `Scalar` uses `Scalar::from_bits()`. This conversion accepts scalar values that are non-canonically encoded, which is generally not a problem, but could potentially cause disagreement on the validity of a non-canonical input by different actors in a protocol.
Use `Scalar::from_canonical_bytes()` for pod conversions.
> [zk-token-sdk] use canonical decoding for scalars

- runtime/src/accounts.rs
- Rename `load_transaction` to `load_transaction_accounts`
- Removed nesting layer to improve readability
> Refactor: Rename `load_transaction` to `load_transaction_accounts`

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
- runtime/src/storable_accounts.rs
The plan was to be able to specify a target slot for a store of accounts as well as a source slot per account. This allows us to update the index correctly when moving between slots during ancient append vec work. However, we don't need per-account slot, we just need a single source slot shared by all accounts that are moving.
Remove the variations that allowed a per-account slot and use a single source slot for all accounts.
Fixes #
> remove per-account slot in ancient append vecs

- explorer/src/components/instruction/SerumDetailsCard.tsx
- explorer/src/components/instruction/serum/CancelOrderByClientIdDetails.tsx
- explorer/src/components/instruction/serum/CancelOrderByClientIdV2Details.tsx
- explorer/src/components/instruction/serum/CancelOrderDetails.tsx
- explorer/src/components/instruction/serum/CancelOrderV2Details.tsx
- explorer/src/components/instruction/serum/CloseOpenOrdersDetails.tsx
- explorer/src/components/instruction/serum/ConsumeEventsDetails.tsx
- explorer/src/components/instruction/serum/ConsumeEventsPermissionedDetails.tsx
- explorer/src/components/instruction/serum/DisableMarketDetails.tsx
- explorer/src/components/instruction/serum/InitOpenOrdersDetails.tsx
- explorer/src/components/instruction/serum/InitializeMarketDetailsCard.tsx
- explorer/src/components/instruction/serum/MatchOrdersDetailsCard.tsx
- explorer/src/components/instruction/serum/NewOrderDetailsCard.tsx
- explorer/src/components/instruction/serum/NewOrderV3DetailsCard.tsx
- explorer/src/components/instruction/serum/PruneDetails.tsx
- explorer/src/components/instruction/serum/SettleFundsDetailsCard.tsx
- explorer/src/components/instruction/serum/SweepFeesDetails.tsx
- explorer/src/components/instruction/serum/types.ts
- explorer/src/utils/tx.ts
OpenBook Serum community fork not deserialized in the explorer
Add logic to also work for OpenBook, backward compatible to display Serum
Fixes #
Example tx with cancel order v2 + consume events + settle funds
http://localhost:3000/tx/3YDJQXihRiTpQpWv9WYuvZSiKLW7dTVuJNjnJA3GVJPCtL6ubcgETk9hFGAf48YKHg3sFPs1Te19VSvMyXuwJf8B
> explorer: OpenBook ix details using Serum code

- core/src/banking_stage.rs
Explicit Measure::start/stop around very simple blocks.
Use measure! so the code is simpler.
Fixes #
> Clean up: banking_stage_prepare_sanitized_batch

- bench-tps/tests/bench_tps.rs
- core/tests/epoch_accounts_hash.rs
- core/tests/snapshots.rs
- rpc/src/rpc.rs
- runtime/src/bank.rs
- test-validator/src/lib.rs
goal is to enable write cache always, since it is always enabled in the validator.
This lets us get rid of `write_version` and the concept of multiple append vecs per slot.
Fixes #
> use write cache by default in some tests

- web3.js-experimental/.eslintrc
- web3.js-experimental/.eslintrc.json
- web3.js-experimental/.gitignore
- web3.js-experimental/.npmrc
- web3.js-experimental/.prettierignore
- web3.js-experimental/package.json
- web3.js-experimental/pnpm-lock.yaml
- web3.js-experimental/src/doThing.browser.js
- web3.js-experimental/src/doThing.js
- web3.js-experimental/src/doThing.native.js
- web3.js-experimental/src/env-shim.ts
- web3.js-experimental/src/index.ts
- web3.js-experimental/src/rpc.ts
- web3.js-experimental/src/types/global.d.ts
- web3.js-experimental/tsconfig.declarations.json
- web3.js-experimental/tsconfig.json
- web3.js-experimental/tsup.config.ts
- web3.js-experimental/turbo.json
`pnpm build` & `pnpm build:typedefs` build separate bundles for Node, the browser, React Native, and an IIFE for CDNs. The IIFE comes in a development and a production flavor. Every other build lets you toggle dev-mode by setting the value of `process.env.NODE_ENV` (which most build systems do).
In code, you now have access to several macros to use to gate code:
* `__DEV__` is true when in development mode
* `__REACTNATIVE__` is true in the `.native.js` build
* `__BROWSER__` is true in the `.browser.js` build
* `__NODEJS__` is true in the `.node.js` build
<details><summary>Output of the build looks like this</summary>
```bash
> @solana/web3.js-experimental@0.0.0-development build /home/sol/src/solana/web3.js-experimental
> tsup
[NODE] CLI Building entry: ./src/index.ts
[NODE] CLI Using …
```
> Boilerplate for web4.js

- .github/workflows/client-targets.yml
- .github/workflows/docs.yml
- .github/workflows/export-github-repo.yml
- .github/workflows/release-artifacts-auto.yml
`voxmedia/github-action-slack-notify-build@v1` doesn't maintain anymore. I use pure curl to replace it. I think it will be more easy for us to do some custom changes in the future.
- remove voxmedia/github-action-slack-notify-build@v1 action
> ci: rewrite Github Actions slack error reporting

- measure/src/macros.rs
In probably 90% (ooma) cases where we use measure!, we immediately call .as_us().
Just create a macro to measure in microseconds directly
Fixes #
> add a measure_us macro

- explorer/src/utils/tx.ts
This program is owned by Serum, not by Bonfida
This program was mislabeled as `Bonfida Pool`, but is actually owned by Serum: https://github.com/project-serum/serum-dex/tree/master/pool
- Remove the `Bonfida Pool`
- Add `Serum Pool`, update labels
> Renaming the Bonfida Pool -> Serum Pool

- ledger-tool/src/main.rs
- validator/src/bin/solana-test-validator.rs
- validator/src/cli.rs
- validator/src/main.rs
Disabled caching is already not well tested and it is about to get less tested.
We already default to caching for validators and ledger-tool.
Remove the ability to disable the accounts write cache.
Fixes #
> remove cli arg "--no-accounts-db-caching"

- ledger-tool/src/main.rs
Error message when trying to create a snapshot for a slot that doesn't exist (or is not full) was not good, and done through panic.
Use eprintln + exit, improve error message.
Old:
```
thread 'main' panicked at 'snapshot slot doesn't exist', ledger-tool/src/main.rs:2983:17
```
New:
```
Error: snapshot slot 43 does not exist in blockstore.
```
Fixes #28896
> Improve error message

- core/benches/banking_stage.rs
- core/src/banking_stage.rs
Unused parameter, been here for a long while.
Remove it.
Fixes #
> clean up: remove my_pubkey arg from consume_buffered_packets

- core/tests/epoch_accounts_hash.rs
When running EAH tests locally, I tend to do `cargo test epoch_accounts_hash`, which will run all the tests with "epoch_accounts_hash" in the test function's name. For unit tests, their file is included in the matchable string. For integration tests, the file name is not. This means when I run `cargo test epoch_accounts_hash`, I would not run one test that I _did_ want to run.
Rename the test to include the string "epoch_accounts_hash".
(Alternatively, I could've put the whole EAH integration test into its own module, but that felt like overkill.)
> Renames EAH test fn

- programs/bpf_loader/src/syscalls/cpi.rs
I've refactored CPI a bit:
- added `CallerAccount::from_account_info` and `CallerAccount::from_sol_account_info` to create caller accounts from `AccountInfo` (rust) and `SolAccountInfo` (C) respectively
- added `update_callee_account` and `update_caller_account` to sync caller <-> callee accounts at entry and exit of CPI respectively
- I've done some smaller refactorings
- added tests and some comments
I've done this so that I can more confidently land the account direct mapping branch by having tests that check that changes to accounts, data and realloc space are identical. 
The diff is large but I've split the changes in logical commits, which should be pretty easy to review one by one. I've taken care to refactor the code without changing any error paths.
> Refactor CPI, add tests and sprinkle some comments

- runtime/src/accounts_db.rs
Shrinking and ancient append vecs can be more efficient if we assume only a single store per slot.
Assert that when we shrink, we only ever have 1 append vec per slot. This will be true for validators that are using the write cache. The write cache can no longer be disabled due to a recent commit. All laggard tests that don't use the write cache are being addressed. All the tests that triggered this assert have already been adapted to use the write cache.
Fixes #
> expect only 1 store per slot

- web3.js-experimental/package.json
- web3.js-experimental/tsconfig.declarations.json
- web3.js-experimental/tsup.config.ts
* You can now import the thing in CommonJS and ESM environments without fanfare
* Added exports for common CDNs like JSDelivr and unpkg
* Excluded source files from npm package
> [web3.js][experimental] Improve package exports

- web3.js-experimental/package.json
- web3.js-experimental/pnpm-lock.yaml
This will run as part of the GitHub Actions workflow, and simply install _itself_ via `pnpx`
> [web3.js][experimental] Remove bundlewatch dependency

- core/src/system_monitor_service.rs
In dashboard, the memory usage are aggreated for 1 minute interval. Reporting
it at one point per second is too much. 
Reduce the memory usage reporting frequency to 1 point per 5 seconds.
Fixes #
> reduce memory usage report freq to 1 per 5s

- core/benches/cluster_nodes.rs
- core/src/cluster_nodes.rs
No need to send duplicate shreds if several nodes have the same tvu socket address because they are behind a relayer or whatever.
Dedup turbine retransmit peers by tvu socket addresses.
> dedups turbine retransmit peers by tvu socket addresses

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- account-decoder/src/parse_token_extension.rs
- ledger/Cargo.toml
- programs/sbf/Cargo.lock
- rpc-client-api/Cargo.toml
- rpc/Cargo.toml
- transaction-status/Cargo.toml
- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/confidential_transfer.rs
- transaction-status/src/parse_token/extension/cpi_guard.rs
- transaction-status/src/parse_token/extension/mod.rs
- transaction-status/src/parse_token/extension/permanent_delegate.rs
we just released a new version of token-2022 and would like to bring the monorepo up to this version so that we can use the account decoder in the token cli for the new extensions
i updated the token-2022 dependency to `=0.5.0` everywhere in the monorepo, and added support for our new extensions and instructions in account-decoder and transaction-status. most code for `CpiGuard` is copy-paste-adapted from `RequiredMemoTransfers`, and `PermanentDelegate` from `MintCloseAuthority`, because they share largely identical interfaces
im also going to pr a backport of this to 1.14 branch, since thats the version we are on. ill do it manually since `Cargo.lock` will likely differ
> update to spl-token-2022 0.5.0

- Cargo.lock
- account-decoder/Cargo.toml
- account-decoder/src/parse_token.rs
- account-decoder/src/parse_token_extension.rs
- client/Cargo.toml
- ledger/Cargo.toml
- programs/bpf/Cargo.lock
- rpc/Cargo.toml
- transaction-status/Cargo.toml
- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/cpi_guard.rs
- transaction-status/src/parse_token/extension/mod.rs
- transaction-status/src/parse_token/extension/permanent_delegate.rs
this is #28932 backported to 1.14. the only difference is `Cargo.lock` changes appreciably more, because `1.14` is on `0.4.2` (whereas `1.15` is on `0.4.3`) which itself depends on `1.10`
edit: note to rebase after #28926
> update to spl-token-2022 0.5.0 (backport to 1.14)

- core/src/banking_stage.rs
A TODO comment about re-iterate high priority txs more often is outdated since MI. 
remove it
Fixes #
> remove obsoleted comment

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
- web3.js/test/mocks/rpc-websockets.ts
If you call confirmTransaction for a signature that has already been processed, the signatureSubscribe subscription will never fire a notification. This will certainly mean that confirmTransaction() will throw an expiry error for a transaction that is, in actual fact, confirmed.
https://github.com/solana-labs/solana/issues/25955
add getSignatureStatuses
> web3.js: add getSignatureStatuses to confirm transaction

- explorer/src/components/account/SlotHashesCard.tsx
Incorrect labelling, the slot hash is the hash of the parent bank. Easy to verify in the explorer that they aren't the same thing:
click on a slot, read blockhash, blockhash != slot hash
https://explorer.solana.com/address/SysvarS1otHashes111111111111111111111111111/slot-hashes
Fixes #
> explorer: fix blockhash into hash for Slot Hashes

- tpu-client/src/nonblocking/tpu_client.rs
The client is sometimes unable to send transactions using TPU client.
The leader schedule cache in TPU client advances in the middle of transaction dispatch. Due to this it is unable to lookup the leader address from the cache, since the target slot is out of bound.
With this PR, the value of `first_slot` is being read inside the `read()` lock of the cache. This will ensure that the first_slot and the cache will be in sync.
Fixes #
> TPU client fix for leader schedule cache lookup

- sdk/src/feature_set.rs
See #28935
This is a no-op for mnb and devnet and eventually for testnet
The same feature is in 1.14.
Fixes #
Feature Gate Issue: https://github.com/solana-labs/solana/issues/28934
> add feature #28934 (no-op in master)

- web3.js/src/transaction/legacy.ts
Removes use of Buffer from signature verification.
> web3.js: remove Buffer from signature verification

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
A small bug snuck in at #28290 where the one-shot fetch for the current commitment status could result in a transaction being confirmed when it shouldn't be. The reason was because we did not check that the result _met_ the target commitment.
When fetching the one-shot `getSignatureStatus` for a given transaction, make sure that the instantaneous signature status at least meets the target commitment.
> fix: verify commitment level when confirming transactions with one-shot fetch

- web3.js/src/connection.ts
- web3.js/src/nonce-account.ts
- web3.js/src/transaction/expiry-custom-errors.ts
- web3.js/src/transaction/legacy.ts
- web3.js/src/utils/send-and-confirm-raw-transaction.ts
- web3.js/src/utils/send-and-confirm-transaction.ts
- web3.js/test/connection.test.ts
- web3.js/test/mocks/rpc-http.ts
- web3.js/test/transaction.test.ts
```typescript
const tx = new Transaction({nonceInfo});
const signature = connection.sendTransaction(tx, [/* ... */]);
await connection.confirmTransaction({
minContextSlot, // A slot where the nonce was known to be the candidate value.
nonceAccountPubkey,  // The account where we can expect to find the latest nonce value.
nonceValue: nonceInfo.nonce,  // Whatever nonce value the `tx` contained when it was signed.
signature,
});
```
Closes #25303.
> feat: a nonce-based transaction confirmation strategy for web3.js

- web3.js/src/publickey.ts
> web3.js: fix typo in PublicKey.unique

- web3.js/src/message/legacy.ts
Replace casts with not null assertions
> web3.js: replace casts with not-null assertions

- web3.js/src/publickey.ts
Deprecate `findProgramAddress` to encourage developers to use the synchronous version instead.
Addresses #25648
> web3.js: deprecate PublicKey.findProgramAddress

- web3.js/src/publickey.ts
Deprecating createProgramAddress will encourage developers to use the synchronous version instead.
Fixes: #25648
> web3.js: add deprecation notice for createProgramAddress

- web3.js/src/account.ts
Removes a redundant 'Buffer' type from the `Account` class.
> web3.js: remove redundant 'Buffer' from 'Account' class

- program-test/src/lib.rs
While fixing the various stake pool test failures, I noticed that the easy solution was to force refresh the blockhash (see https://github.com/solana-labs/solana-program-library/pull/3853 for example).  This is kind of annoying, since it forces you to constantly refresh from a previous blockhash and then keep it around in a separate variable.
The last blockhash is already stored on the ProgramTestContext, so just refresh it directly there, so that way you can do:
```
context.get_new_latest_blockhash().await?;
```
then use `context.last_blockhash` as normal. This will make it much easier to fix these issues anytime they come up.
I wanted to keep this consistent with the banks client extension, but happy to bikeshed a better name for it.
Fixes #
> program-test: Add `ProgramTestContext::get_new_latest_blockhash`

- runtime/src/accounts_hash.rs
At least 2 validators have reported this failure. A bit flip is a likely cause. Having the actual 128 bit value could be helpful.
Fixes #
> add balance to cap overflow message

- runtime/src/accounts_db.rs
- validator/src/cli.rs
- validator/src/main.rs
We will be removing multi-pass accounts hash scanning. So, we don't need to be able to specify the # of scans passes.
The accounts scan will now use the file system to avoid memory spikes during accounts hash calculation.
Remove cli arg and all plumbing.
Fixes #
> remove cli arg to specify # accounts hash scan passes

- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
keep track of how many append vecs are currently alive and mapped. This helps with predicting failures.
Fixes #
> log # append vecs open

- Cargo.lock
- fetch-spl.sh
- programs/sbf/Cargo.lock
- tokens/Cargo.toml
- transaction-status/Cargo.toml
The monorepo retains a dependency on 2 versions of spl-token-2022 because of the old version of spl-associated-token-account.
Bump spl-ata to new version
> Bump spl-ata to v1.1.2

- zk-token-sdk/src/errors.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/instruction/transfer.rs
- zk-token-sdk/src/instruction/transfer_with_fee.rs
- zk-token-sdk/src/zk_token_elgamal/ops.rs
The transfer fees for confidential transfers are encrypted as one single ciphertext, which prevents it from being added on to the destination token account's pending balance.
Divide the transfer fee and encrypt it as two separate ciphertexts. Update the zk proofs accordingly.
> [zk-token-sdk] divide fee encryption into two ciphertexts

- ledger/src/blockstore.rs
- ledger/src/blockstore_metrics.rs
There are currently two metrics for tracking number of blockstore shred insertions that failed because the shred already exists. Maintaining separate metrics based on the source of the shred allows for better understanding of the interplay between turbine, repair, and recovery. However, turbine and repair sources are both counted under the `num_data_shreds_exists` counter (recovery has its own split out metric, `num_recovered_exists`).
Having this increased granularity will be useful for understanding things like if we are being too aggressive in initiating repair requests (e.g. if we need to wait longer for turbine)
Bifurcate the `num_data_shreds_exists` counter into a counter for turbine sourced shreds `num_turbine_data_shreds_exists` and repair sourced shreds …
> Distinguish turbine vs repair insertion metrics

- core/src/heaviest_subtree_fork_choice.rs
- core/src/repair_generic_traversal.rs
- core/src/repair_weight.rs
- core/src/repair_weighted_traversal.rs
- core/src/replay_stage.rs
- core/src/tree_diff.rs
Additionally refactor subtrees to store children as a set since we shouldn't have duplicates as we key by bankhash. 
The only use of this subtree where we don't properly key by bankhash (using `Hash::default()` instead) is during repair weighting. In that case it is beneficial to aggregate stake anyways as more votes = more indication that we should repair, so it is fine to combine. 
When we dump nodes for repair, stake is not properly updated in bank_forks or repair subtrees. Step 1 of the overall fix is to add this functionality.
Contributes to #28648
> Add dump_node to update stake for heaviest subtrees

- core/src/window_service.rs
- ledger/src/blockstore.rs
The num_repair field is only blockstore insertion metric being updated outside of Blockstore::insert() call chain
Move the update to insert() with the rest of the fields in BlockstoreInsertionMetrics struct.
> Move BlockstoreInsertionMetrics field update to blockstore.rs

- web3.js/src/transaction/message.ts
- web3.js/test/transaction-tests/message.test.ts
Message headers give you the following:
* number of required signatures (`numRequiredSignatures`)
* number of read-only signed accounts (`numReadonlySignedAccounts`)
* number of read-only unsigned accounts (`numReadonlyUnsignedAccounts`)
If we want to know how many writable unsigned accounts there are, we have to:
* start with the total number of accounts
* subtract the number of those that are signers (`numRequiredSignatures`)
* subtract the number of read-only unsigned accounts (`numReadonlyUnsignedAccounts`)
That spells:
```ts
const numWritableUnsignedAccounts =
message.staticAccountKeys.length -
numRequiredSignatures -
numReadonlyUnsignedAccounts;
```
Unfortunately, we forgot to subtract out the number of signers, making it possible to overcount `numWritableUnsignedAccounts`. This …
> fix: TransactionMessage.decompile() now counts the correct number of unsigned, writable accounts

- streamer/src/nonblocking/quic.rs
quic::test::test_quic_server_multiple_writes is failing intermittently in CI. For example,
https://buildkite.com/solana-labs/solana/builds/85659#0184c4f7-b4a2-4d62-bdd1-2181a87b8233
https://buildkite.com/solana-labs/solana/builds/85636#0184c435-32f3-4068-a016-fa7fe6192c55
Increased timeout from 0.1 second to 1 second
Fixes #
> Increase stream timeout to 1 sec to fix flaky tests

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
As noticed in https://solana.stackexchange.com/questions/4597/how-getfeeformessage-for-versioned-transaction, we can't use `getFeeForMessage` with a versioned message.
Similar to how versioned and legacy transactions are supported in `sendTransaction`, accept `VersionedMessage` in `getFeeForMessage`, and serialize it properly.
There's some mismatch in how the types are defined between `VersionedTransaction` and `VersionedMessage`, so here's the type definition for reference:
```
export type VersionedMessage = Message | MessageV0;
```
Fixes #
> fix: support `VersionedMessage` in `getFeeForMessage`

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
- runtime/src/storable_accounts.rs
avoid making copies while combining alive accounts from an old append vec into an ancient append vec
impl a trait to allow the data to be used as-is
Fixes #
> avoid copies when writing to an ancient append vec

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
Memory usage spikes when accounts hash calculation is going on.
Use files instead of ram for hash values prior to being reduced by merkle tree hashing. We can also eliminate multi-pass scanning. This simplifies the code and testing. It also means we will only visit each append vec entry once per calculation instead of multiple times.
Fixes #
> use files for merkle tree inputs on accounts hash

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
While combining into an ancient append vec, avoid iterating all accounts to check for size if we already know the total size and all accounts fit (which is the common case).
Fixes #
> pass alive bytes to AccountsToStore::new

- programs/bpf_loader/src/syscalls/mod.rs
- sdk/src/feature_set.rs
Community contribution #27961 was missing a feature key.
Renames `alt_bn128_syscall_enabled` => `enable_alt_bn128_syscall` for consistency.
> Adds a feature ID for `enable_alt_bn128_syscall`

- docs/src/developing/programming-model/accounts.md
- docs/src/developing/programming-model/runtime.md
There is a bit of stale info about who can change the account data and size (also by how much).
Also, there is no mention of how to balance accounts before CPI.
See the diff.
> Adjusts docs about changing the data, size and balance of accounts.

- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
We currently use the `is_connected` field to be able to signal to
ReplayStage that a slot has replayable updates. It was discovered that
this functionality is effectively broken, and that `is_connected` is never
true.
In order to convey this information to ReplayStage more
effectively, we need extra state information so this PR changes the
existing bool to bitflags with two bits.
From a compatibility standpoint, the `is_connected bool` was already
occupying one byte in the serialized SlotMeta in blockstore. Thus, the
change from a bool to bitflags still "fits" in that one byte allotment.
In consideration of a case where a client may wish to downgrade software
and use the same ledger, deserializing the bitflags into a bool could
fail if the new bit is set. As such, this PR introduces the …
> Change SlotMeta is_connected bool to bitflags

- docs/src/developing/clients/jsonrpc-api.md
Docs say base64 encoding in filters is supported in v1.11.2+. This is confusing, since it isn't supported in v1.13, which was built on v1.10.
Update docs to reference v1.14. Technically, the parameter is supported in v1.11.2-v1.11.10, but since no public clusters are running the v1.11 line, doesn't seem worth the potential confusion of including those details.
> Update filter docs, v1.11 -> v1.14

- runtime/src/bank.rs
trying to get rid of non-write cache code paths
use write cache, flush as necessary
Fixes #
> test_bank_update_sysvar_account uses write cache

- runtime/src/bank.rs
make straggler tests use write cache.
Fixes #
> test_purge_empty_accounts uses write cache

- core/src/forward_packet_batches_by_accounts.rs
- core/src/latest_unprocessed_votes.rs
- core/src/unprocessed_transaction_storage.rs
- runtime/src/cost_tracker.rs
Forwarder uses requested_cu to track how many CUs are forwarded. Now cost_model has been updated to use requested_cu (#28281), forwarder should use cost_model for consistency.
- refactor forwarder to use cost_model to calculate transaction cost (instead of use requested_cu as a rough measure)
- remove requested_cu from cost_tracker.
Fixes #
> Refactor to remove requested_cu from cost_trarcker

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
These were added to the RPC interface but never to this client library.
* Add Typescript types for the missing params.
* Add structs to deserialize the different kinds of responses that result when you change the `transactionDetails` param.
Fixes #28999.
> feat: the web3.js getBlock APIs now accept `rewards` and `transactionDetails` config

- sdk/program/src/alt_bn128.rs
Unwraps in syscalls can cause the local test validator to panic. The alt_bn128 syscall https://github.com/solana-labs/solana/pull/27961 also uses unwraps. 
You can reproduce the issue by passing in e.g. little endian bytes instead of big endian bytes. 
This is difficult to catch in unit tests since tests for invalid inputs pass and don’t easily account for the the validator crashing.
Removed all unwraps in alt_bn128 syscalls.
Fixes #
> remove unwraps in alt_bn128 syscall

- programs/bpf_loader/src/syscalls/mod.rs
#23781 had a typo.
Turns binary `&` into logical `&&` in `translate_slice_inner()`.
> Fix - Turns binary `&` into logical `&&` in `translate_slice_inner()`.

- runtime/src/bank.rs
trying to fix tests that don't use the write cache.
Fixes #
> do_test_clean_dropped_unrooted_banks uses write cache

- runtime/src/bank.rs
migrating all tests to be able to use write cache so we can remove the old code path.
Fixes #
> test_bank_hash_internal_state works with write cache

- runtime/src/bank.rs
migrate tests to still pass when we use the write cache
Fixes #
> test_add_builtin_account* works with write cache

- runtime/src/bank.rs
migrate all tests to be able to use write cache so we can delete that code path.
Fixes #
> test_bank_update_rewards_determinism works with write cache

- runtime/src/snapshot_utils.rs
move snapshot tests to use write cache.
Fixes #
> rebuild_bank_from_snapshots uses write cache

- web3.js/src/connection.ts
Oof. Classic nullish coercion bug. This PR ensures that even subscriptions with exactly the id `0` get cleaned up when they should.
> fix: prevent the first-ever signature subscription from leaking

- web3.js/package.json
- web3.js/src/connection.ts
- web3.js/src/epoch-schedule.ts
- web3.js/src/utils/send-and-confirm-transaction.ts
- web3.js/test/connection.test.ts
- web3.js/yarn.lock
Now that we have long-running transaction confirmation strategies, like #25839, one might like to cancel outstanding transaction confirmations that they no longer care about. For instance, if a user takes an action, but then visits a different page on your site before the transaction has confirmed, you might like to dispose of it.
* Add `abortSignal` as an input to `confirmTransaction()`
Now, callers can do this:
```ts
const abortController = new AbortController();
try {
await connection.confirmTransaction({
abortSignal: abortController.signal,
/* ... usual transaction confirmation strategy properties */
});
} catch (e) {
if (e.name === 'AbortError') {
// Handle aborted confirmation.
}
}
// ...then some time later:
abortController.abort();
```
Fixes #25304.
> feat: you can now abort transaction confirmations in web3.js

- web3.js/.gitignore
- web3.js/README.md
> chore: remove last references to Flow types in web3.js

- .mergify.yml
Don't automatically include the `automerge` label on backport PRs created by mergify. The label can still be added by a human. 
This change is part of a broader shift to backport less frequently and review backports more closely.
Context: https://discord.com/channels/428295358100013066/910937142182682656/1048642921517301810
> Mergify: don't add automerge label to backport PRs

- runtime/src/bank.rs
See comments in the test. This pr allows the default to be set to write cache only for all tests without affecting this test.
Fixes #
> test_process_stale_slot_with_budget never uses write cache

- validator/src/bin/solana-test-validator.rs
while trying to run `anchor test` the `program_data` account of the program that is automatically deployed does not initialize, so some tests won't run.
If you just run  `anchor test` against a local network, it will start a new test validator using the --bpf-program argument with solana-test-validator, which defaults to the non-upgradeable loader
just change from using `bpf_loader` to `bpf_loader_upgradeable`
reference from StackOverflow question: https://solana.stackexchange.com/questions/4632/anchorerror-caused-by-account-program-data-error-code-accountnotinitialized/4691#4691
> change test validator from non upgradable bpf loader to upgradable bpf loader

- runtime/src/accounts_db.rs
moving all tests to use the write cache
Fixes #
> test_accounts_clean_after_snapshot_restore_then_old_revives can use write cache

- runtime/src/bank.rs
migrating all tests to use write cache.
All bank tests now support this.
make `new_for_tests_with_config` always enable the write cache. Other plumbing will be removed later once all tests everywhere use the write cache.
Fixes #
> bank tests use write cache

- runtime/src/accounts_db.rs
Migrating all tests to use write cache.
`store_uncached` will not be supported anymore for most tests.
Replace all accounts_db.rs calls to `store_uncached` with `store_for_tests`. Functionality is equivalent since `store_for_tests` looks at whether write cache is enabled.
Fixes #
> store_uncached -> store_for_tests

- .github/workflows/docs.yml
https://github.com/solana-labs/solana/pull/29026
mergify only detects job names. make docs's job name more explicit.
> ci: make docs job name more explicit

- runtime/src/accounts_db.rs
migrate all tests to use write cache
Fixes #
> test_clean_accounts_with_last_full_snapshot_slot uses write cache

- .mergify.yml
Mergify seems broken on docs PRs (eg https://github.com/solana-labs/solana/pull/29017/checks?check_run_id=9830706173), presumably since https://github.com/solana-labs/solana/pull/28852
Fix
It might be enough to use just the `check-skipped=error_reporting` condition. Wdyt @yihau ?
> Fix mergify for docs PRs

- runtime/src/accounts_db.rs
> test_clean_multiple_zero_lamport_decrements_index_ref_count uses write cache

- ledger/src/sigverify_shreds.rs
- perf/src/perf_libs.rs
- perf/src/sigverify.rs
As part of the work in #29055 to refactor the `Packet` type, the GPU sigverify path needs to work for two different types, and not just `Packet`.
The underlying perf libs take `uint8_t*`, so make `Elems` consistent with that, which will also make it work for another `Packet` type.
Fixes #
> perf: Change underlying Elems to *const u8

- runtime/src/accounts_db.rs
migrating tests to use write cache.
This test tests adding storages at a slot to accomodate writing too many accounts. With the write cache, we don't do that - we just keep the latest per pubkey in memory and then write to a single append vec.
Fixes #
> test_account_grow uses write cache

- runtime/src/accounts_db.rs
> test_accounts_db_serialize_zero_and_free uses write cache

- runtime/src/accounts_db.rs
migrating tests to use write cache.
This fixes:
test_accounts_purge_chained_purge_after_snapshot_restore
test_accounts_purge_chained_purge_before_snapshot_restore
Fixes #
> with_chained_zero_lamport_accounts works with write cache

- core/src/replay_stage.rs
A big chunk of `core/src/replay_stage.rs` is not correctly formatted because the coding style causes `cargo fmt` to error.
See for example:
https://github.com/solana-labs/solana/blob/91d556dc6/core/src/replay_stage.rs#L667
https://github.com/solana-labs/solana/blob/91d556dc6/core/src/replay_stage.rs#L647
* The 1st commit just slightly changes the code style to unblock `cargo fmt`.
* The 2nd commit is just `cargo fmt`.
* No changes to code logic.
> patches rust code formatting in core/src/replay_stage.rs

- runtime/src/accounts_db.rs
> do_full_clean_refcount uses write cache

- core/src/accounts_hash_verifier.rs
- core/src/validator.rs
- core/tests/epoch_accounts_hash.rs
- core/tests/snapshots.rs
- local-cluster/src/local_cluster.rs
- local-cluster/tests/common.rs
- local-cluster/tests/local_cluster.rs
- test-validator/src/lib.rs
- validator/src/bootstrap.rs
- validator/src/main.rs
As one of the deleted comments in this PR states, `SnapshotConfig` is required for the validator:
```
// A snapshot config is required.  Remove the Option<> wrapper in the future.
```
Remove the option, and make `SnapshotConfig` required for validator and sub-services. SnapshotConfig remains in a wrapper in two place:
- `BankForks` since `BankForks` can be loaded from genesis via `load_bank_forks()` (see https://github.com/solana-labs/solana/issues/25577)
- `rpc/src/*` - we can address this down to keep line count down / ensure there isn't any one downstream that is explicitly passing a `None` here to disable serving snapshots on their node
> Remove unused Option<> around ValidatorConfig's SnapshotConfig

- web3.js/package.json
- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
There are folks who have good reasons to want to disable or override our default HTTP agent (ie. the thing that implements connection persistence in Node for the RPC). This PR _keeps_ the behaviour of creating the usual default `http.Agent`, but offers config to disable or override it.
```ts
new Connection(url, {httpAgent: false});
```
```ts
new Connection(url, {httpAgent: new https.Agent()});
```
Note, that if you supply your own, it's up to you to dispose of the agent when the connection is no longer needed.
* Added an `httpAgent` config parameter to `Connection`
* Auto-disable creating the default agent when `process.env.NODE_ENV` is `test`.
Fixes #25069.
> feat: you can now supply your own HTTP agent to a web3.js Connection

- core/src/validator.rs
When failed to process_blockstore_from_root, solRptLdgrStat thread will hang.
exit solRptLdgrStat thread when process_blockstore_from_root failed.
Fixes #
> fix solRptLdgrStat thread hang

- core/src/replay_stage.rs
This is manual backport of https://github.com/solana-labs/solana/pull/29123 to avoid future merge conflicts in backports to this file.
The actual code change (the 1st commit) is pretty small and just style change.
The rest is just `cargo fmt`.
* The 1st commit just slightly changes the code style to unblock `cargo fmt`.
* The 2nd commit is just `cargo fmt`.
* No changes to code logic.
> patches rust code formatting in core/src/replay_stage.rs (backport #29123)

- runtime/src/accounts_db.rs
> test_clean_zero_lamport_and_old_roots uses write cache

- core/src/banking_stage.rs
- core/src/replay_stage.rs
- core/src/validator.rs
- poh/src/poh_recorder.rs
- poh/src/poh_service.rs
- rpc/src/cluster_tpu_info.rs
PohConfig being passed and saved as an Arc makes it more difficult to change the values and understand the side effects. There's no real benefit to having it be an Arc in the first place, particularly when passing the struct into a function that just reads out and uses a few values from it.
This change will make it more straightforward to add a feature gate around the hash rate as a next step.
Fixes #
> Remove Arcs from PohConfig parameters and pass the struct by reference only

- runtime/src/accounts_db.rs
migrating tests to use write write cache
Fixes #
> test_get_snapshot_storages_only_non_empty uses write cache

- runtime/src/accounts_db.rs
migrating all tests to use write cache.
These tests all failed when I eliminated the member variable completely that allows us to turn off the write cache.
Fixes #
> migrate some tests to work with write cache

- cli/src/clap_app.rs
- cli/src/main.rs
On v1.15 / master, UDP is disabled for transactions, so just running `solana program deploy ...` will fail, since it's expecting to use quic. 
Add a flag to force using UDP, but default to `!DEFAULT_TPU_ENABLE_UDP`.
Fixes #29131
> cli: Use QUIC if the default TPU does *not* use UDP

- runtime/src/bank.rs
> test_shrink_candidate_slots_cached works with write cache

- ledger-tool/src/main.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
Migrating everything to use write cache so we can eliminate the old code path.
ledger-tool create-snapshot does not use the write cache.
The biggest hang up with using the write cache is a call to `calculate_capitalization`. That tries to scan storages. But, if we have not written to storages yet because we're using the write cache, then we can't calculate cap correctly. But, if we flush to the write cache, then we later update sys vars in the same slot. As a result, we violate some design constraints by writing to a slot that has already been flushed from the write cache.
A solution to this is to have `calculate_capitalization` use the index to calculate that capitalization. This could be revisited later but is sufficient for now since it does not affect any real validators.
Fixes #
> ledger-tool create-snapshot uses write cache

- runtime/src/accounts.rs
This allows us to test with and without the activation of the feature in #28690, which has to do with fixing `rent_epoch` at a consistent value for rent exempt accounts.
Introduce parameter for excluding features from activation in tests in accounts.rs.
Fixes #
> support for accounts tests loading accounts with excluded feature

- .github/workflows/manage-stale-issues-and-prs.yml
I got this wrong in #29134. The original config set this at 365 days, not 7.
Fixes #29093.
> chore: correct days before an issue in GitHub is considered stale by stalebot

- runtime/src/accounts_db.rs
> test_shrink_candidate_slots uses write cache

- runtime/src/rent_collector.rs
This is pre-work for #[28690](https://github.com/solana-labs/solana/pull/28690)
We need to distinguish between rent exempt, rent paying with rent now, and rent paying with rent later.
Introduce a third `RentResult` enum value: `NoRentCollectionNow` and rename one.
Fixes #
> change RentResult enum values

- runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
#29053
Remove unwraps from the rebuilder threads, and send back a result of success or failure for each thread so the main-thread knows if it was successful or not.
Fixes #
> Storage Rebuilder: better error propagation

- web3.js/src/publickey.ts
- web3.js/test/connection.test.ts
`console.log(publicKey)` is unreadable in Node.
Add an object stringifier that includes the base58 string.
```shell
$ node
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> const {PublicKey} = require('./lib/index.cjs.js')
undefined
> console.log(PublicKey.default.toString())
11111111111111111111111111111111
undefined
> console.log(PublicKey.default)
PublicKey [PublicKey(11111111111111111111111111111111)] {
_bn: <BN: 0>
}
undefined
```
Fixes #20022.
> fix: pretty print PublicKey objects in node and in the browser

- runtime/src/bank.rs
This code only runs when the write cache is disabled. You can no longer disable the write cache.
panic! when the code is called and remove the test. The test will fail when the write cache is used by default.
Fixes #
> panic on process_stale_slot_with_budget and remove test

- core/src/validator.rs
- core/tests/epoch_accounts_hash.rs
- ledger-tool/src/main.rs
- program-test/src/lib.rs
- runtime/src/bank.rs
Migrating everything to write cache only. Tests that warp end up causing trouble related to setting roots, flushing the write cache, and using the write cache by default. For now, all of these code paths can use the index version of the hash calculation to get past the issue with ripping out the !accounts_caching dead code.
Fixes #
> warp_from_parents works with write_cache enabled

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
- runtime/src/serde_snapshot/tests.rs
removing skip rewrites from rent collection. Once we stop collecting rewrites due to a feature, we don't need to continue to hash them. epoch accounts hash will take care of this behavior.
More changes to come up to pull out a few more pieces.
Fixes #
> remove skip rewrites from bank

- scripts/build-downstream-projects.sh
seems their latest commit will broke their tests. I've made a PR there (https://www.github.com/openbook-dex/program/pull/22). will revert this PR when their test is fine.
> ci: don't run openbook_dex downstream-project test temporarily

- web3.js/src/publickey.ts
Need to try it out/check code to find out in what endianess the bytes/buffer of the PublicKey are returned
Specify it's in big endian in the comment/docs
> docs: add endianess for pubkey byte/buffer functions

- core/src/consensus.rs
The code style causes `cargo fmt` error out and parts of the file is not correctly formatted.
* The 1st commit just slightly changes the code style to unblock `cargo fmt`.
* The 2nd commit is just `cargo fmt`.
* No changes to code logic.
> fixes rust code formatting in core/src/consensus.rs

- core/src/consensus.rs
This is manual backport of https://github.com/solana-labs/solana/pull/29204 to avoid future merge conflicts in backports to this file.
The actual code change (the 1st commit) is pretty small and just style change.
The rest is just `cargo fmt`.
* The 1st commit just slightly changes the code style to unblock `cargo fmt`.
* The 2nd commit is just `cargo fmt`.
* No changes to code logic.
>  fixes rust code formatting in core/src/consensus.rs (backport #29204)

- Cargo.lock
- cli/Cargo.toml
- cli/src/program.rs
- program-runtime/Cargo.toml
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- programs/sbf/benches/bpf_loader.rs
- programs/sbf/tests/programs.rs
- rbpf-cli/Cargo.toml
- rbpf-cli/src/main.rs
https://github.com/solana-labs/rbpf/releases/tag/v0.2.38 will be released.
Preparation for unifying the mechanics of syscalls and CPI.
Thus, `SyscallRegistry` becomes a loader `BuiltInProgram`, which is now also sharable across programs.
> Bump solana_rbpf to v0.2.38

- gossip/src/cluster_info.rs
- gossip/src/cluster_info_metrics.rs
- gossip/src/crds_gossip.rs
- gossip/tests/crds_gossip.rs
This is already tracked in `CrdsDataStats`:
https://github.com/solana-labs/solana/blob/5e799ad56/gossip/src/crds.rs#L96-L106 https://github.com/solana-labs/solana/blob/5e799ad56/gossip/src/cluster_info_metrics.rs#L652-L656 and is so duplicated.
Removing the metric would simplify this code path for upcoming commits.
removed `process_push_success`
> removes metric for process_push_success

- core/tests/snapshots.rs
#29053
We unpacked into the existing (running/active) accounts directory. Appendvecs get dropped which leads to the files being dropped. If this occurs between when the unpacker unpacks and the rebuilder rebuilds, we get a missing file error on the rebuilder.
Use a separate accounts directory for unpacking the snapshot for verification.
Fixes #29053
> Use a different tempdir for unpacking snapshots

- runtime/src/accounts_db.rs
trying to remove reliance on `write_version` since we are only using the write cache now.
This change requires that we are always using the write cache.
Fixes #
> don't rely on write_version increasing - just assert that it is for now

- rbpf-cli/src/main.rs
Same as in #29208 just in the rbpf CLI tool.
> Cfg disable JIT code on systems where it is not supported (2)

- geyser-plugin-manager/src/accounts_update_notifier.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_db/geyser_plugin_utils.rs
- runtime/src/accounts_update_notifier_interface.rs
I introduced a bug in geyser a few weeks ago with geyser's usage of write_version.
Use a monotonically incrementing write_version.
Fixes #
> handle write_version correctly in geyser api

- runtime/src/accounts_db.rs
getting rid of `caching_enabled` everywhere.
Right now, `add_root` takes a `caching_enabled` parameter that determines whether we add a root to `uncleaned_roots` or not. `caching_enabled` is going away, so we need to handle adding to `uncleaned_roots` during index generation separately.
Previously, we relied on `add_root` to add roots to `uncleaned_roots`. That functionality will soon be removed from `add_root`. Index generation is the only caller that passes `caching_enabled=false` to `add_root`. So, we get rid of the case where any caller passes `caching_enabled=false` to `add_root` so we can remove `caching_enabled` as a parameter to `add_root`.
Fixes #
> handle unclean roots explicitly during index generation

- programs/bpf_loader/src/lib.rs
- programs/sbf/tests/programs.rs
- runtime/src/bank_client.rs
- sdk/program/src/bpf_loader_upgradeable.rs
- sdk/src/feature_set.rs
At the moment a program can be redeployed within the same slot. In order to switch to one validator global executor cache (instead of having one per bank) it would be useful if the program address + slot number would identify a programs version.
Prevent the upgradeable loader from redeploying the same program within the same slot.
Feature Gate Issue: #29135
> Feature - Program redeployment cooldown

- runtime/src/accounts_db/geyser_plugin_utils.rs
trying to get rid of storing write_version
assert the `write_version` behavior expected.
Fixes #
> improve write_version usage in geyser scan from snapshot

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
somehow these 2 tests are broken.
test_handle_dropped_roots_for_ancient
test_clean_and_unclean_slot
add to `uncleaned_roots` correctly after `add_root` calls.
Fixes #
> fix tests broken by add_root change

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/snapshot_utils.rs
removing code with `caching_enabled`
Fixes #
> remove rebuild_bank_from_snapshots(caching_enabled)

- local-cluster/tests/local_cluster_flakey.rs
https://github.com/solana-labs/solana/issues/29221
local_cluster_flakey tests failed from time to time. And usually a manual retry (or a few) will likely to pass the test. It, therefore, is good to let the test retry by itself.
Add retry for flakey local cluster test
Fixes #
> add retry for flakey local cluster test

- geyser-plugin-manager/src/accounts_update_notifier.rs
- runtime/benches/append_vec.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_db/geyser_plugin_utils.rs
- runtime/src/ancient_append_vecs.rs
- runtime/src/append_vec.rs
- runtime/src/append_vec/test_utils.rs
- runtime/src/snapshot_minimizer.rs
- runtime/src/storable_accounts.rs
- runtime/store-tool/src/main.rs
Staging to get rid of the use of `write_version`. Now that the write cache is always enabled, we never use 2 append vecs per slot. This means we don't need `write_version` anymore.
Note that we can't stop writing `write_version` in incrementing values because there are asserts that the value increments when we find the same account in the same slot multiple times. Of course, that may only be possible with ancient append vecs now that the write cache is on all the time.
rename to add `_obsolete`. This will make it easier to safely remove dependency on `write_version` and remove uses from other structs and functions.
Previously added a few asserts to make sure behavior is as expected.
Fixes #
> write_version -> write_version_obsolete

- explorer/src/components/account/TokenAccountSection.tsx
Since the maximum is 20 as per the default spec (https://tc39.es/ecma402/#sec-defaultnumberoption), we should explicitly declare it.
TokenAccountSection failsafe to a maximum of 20!
Fixes #
https://github.com/solana-labs/solana/issues/25756
> Explorer: Token Decimal Fix

- programs/bpf_loader/src/lib.rs
- rbpf-cli/src/main.rs
Windows builds and non x86__64 target architectures are throwing a warning for unused mutable variable. This is because these builds do not run executable through JIT compile
cfg switch for these builds to use immutable variable.
> Fix compile warning for some targets

- runtime/src/account_storage.rs
- runtime/src/accounts_db.rs
- runtime/src/lib.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
- runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
Prepare to refactor slot -> append_vec(s) map.
Move AccountStorage to its own file. This lets us encapsulate the behavior without leaking the implementation.
Fixes #
> move AccountStorage out of accounts_db.rs

- runtime/src/accounts_db.rs
refactor `unwrap_or_default` to get default of processed type instead. This gives us the flexibility to change the return value of `get_slot_storage_entries` to not have a default later. The plan is to remove the `Vec` that is currently returned and instead return a single entry.
Fixes #
> refactor unwrap_or_default for type that will soon not have a default

- explorer/src/pages/SupplyPage.tsx
`getLargestAccounts` has been deprecated from the public explorer RPCs
Only show the `TopAccounts` card when there's a custom URL in use -- allowing it to be used for debugging, or in coordination with a separate RPC provider.
Fixes #
> explorer: Only show supply page for custom urls

- Cargo.lock
- client-test/Cargo.toml
- client-test/tests/client.rs
for running them simultaneously correctly
- used `check_server_is_ready` instead of waiting a magic number time period
- separated all test ports
- removed serial_test
> chore: improve solana-client-test

- gossip/src/cluster_info.rs
- gossip/src/crds.rs
- gossip/src/crds_gossip.rs
- gossip/src/crds_gossip_push.rs
- gossip/src/lib.rs
- gossip/src/received_cache.rs
- gossip/tests/crds_gossip.rs
As described here: https://github.com/solana-labs/solana/issues/28642#issuecomment-1337449607
current gossip pruning code fails to maintain spanning trees across
cluster.
This commit instead implements a pruning code based on timeliness of
delivered messages. If a messages is delivered timely enough (in terms
of number of duplicates already observed for that value), it counts
towards the respective node's score. Once there are enough many CRDS
upserts from a specific origin, redundant nodes are pruned based on the
tracked score.
Since the pruning leaves some configurable redundancy and the scores are
reset frequently, it should better tolerate active-set rotations.
> prunes gossip nodes based on timeliness of delivered messages

- gossip/src/cluster_info.rs
- gossip/src/crds_gossip.rs
- gossip/src/crds_gossip_push.rs
- gossip/tests/crds_gossip.rs
Processing push messages is locking and unlocking crds table for each
push message:
https://github.com/solana-labs/solana/blob/536b879aa/gossip/src/cluster_info.rs#L2266-L2276
https://github.com/solana-labs/solana/blob/536b879aa/gossip/src/crds_gossip_push.rs#L215C9-L260
This commit instead locks the crds table once for all the received push
messages.
> locks crds table only once to process push messages

- gossip/src/cluster_info.rs
- gossip/src/crds_gossip.rs
- gossip/src/crds_gossip_push.rs
`Protocol::PruneMessage(Pubkey, _)` is the same as `PruneData.pubkey` and so is redundant and can be ignored:
https://github.com/solana-labs/solana/blob/95d339300/gossip/src/cluster_info.rs#LL277-L279 
https://github.com/solana-labs/solana/blob/95d339300/gossip/src/cluster_info.rs#L361-L367
Ignore pubkey in `Protocol::PruneMessage`
> ignores pubkey in Protocol::PruneMessage

- rpc/src/rpc.rs
Possible panic in RPC thread in `optimize_filters`.
`optimize_filters` was introduced in https://github.com/solana-labs/solana/pull/20185 (by me :rofl:) but uses `.unwrap()` (my bad!). instead it would be better to ignore invalid data. It's very strange that nobody reported possible panics.
> rpc: fix possible panics in optimize_filters

- entry/src/poh.rs
- poh/src/poh_recorder.rs
`Poh` struct contains unused `ticks_per_slot` variable. We set this variable when creating `Poh`, but it is never read except for when resetting `Poh`.
Remove `ticks_per_slot` from `Poh`
> Remove unused ticks_per_slot variable

- ledger/src/blockstore.rs
The logic for detecting first insert is repetitive.
- `maybe_first_insert = slot_meta.received == 0` is calculated
- We then update `slot_meta.received` to be `max(index + 1, slot_meta_received)`
- `index` is an unsigned int, so `index + 1` is strictly `>= 1`; thus updated `slot_meta.received` is also strictly `>= 1`
- Given the above, the `&& slot_meta.received > 0` is redundant and will always be true when this function is called
Remove the redundant half of `if` statement
> Remove repetitive logic in SlotMeta first insert detection logic

- core/src/accounts_hash_verifier.rs
- core/src/ancestor_hashes_service.rs
- runtime/src/bucket_map_holder.rs
- sdk/program/src/clock.rs
We have redundant constants `SLOT_MS` and `DEFAULT_MS_PER_SLOT`, which can be confusing
eliminate `SLOT_MS` and replace all usages with `DEFAULT_MS_PER_SLOT` because it is more widely adopted
> Prune redundant const SLOT_MS

- explorer/src/components/account/UnknownAccountCard.tsx
When an account have 0 lamports and is purged, user wants to remove amount
balance and add message along the line that it doesn't exists [#28273](https://github.com/solana-labs/solana/issues/28273#issue-1400105550)
If account have 0 balance, showed message instead of lamports
> Removed lamports balance and added message for reaped accounts 

- ledger/src/shred.rs
- ledger/src/shred/merkle.rs
- ledger/src/sigverify_shreds.rs
Even though it does not happen in production, `make_shreds_from_data` can still work with empty data.
If data is empty, `make_shreds_from_data` will now return one data shred with empty data. This preserves invariants verified in tests regardless of data size.
> patches shred::merkle::make_shreds_from_data when data is empty

- explorer/src/components/account/UnknownAccountCard.tsx
Previous description for UnknownAccountCard was misleading
Change description to "Account does not exist" which makes it more clear that an account may never have actually "existed" on chain. Previous description implied that non-existent accounts existed previously
Fixes #28273
> Explorer: account does not exist

- streamer/src/nonblocking/quic.rs
Still seeing timeout https://buildkite.com/solana-labs/solana/builds/86606#01850f20-ff56-4c79-bd59-3ca8f3f8a25b in quic streamer test. Locally it is hard to reproduce, it seems to show up in recent CI builds.
Allow longer chunk receive timeout without impacting testing the stream exit condition for unit tests. The exit is periodically checked, we will break only when the total allowed chunk receive timed out. The start time is reset when a new chunk is received.
Fixes #
> quic test timeout fix

- net-utils/src/ip_echo_server.rs
Fixup clippy warnings to upgrade to Rust 1.66.0
```
warning: non-binding `let` on a future
--> net-utils/src/ip_echo_server.rs:133:13
|
133 |             let _ = tcp_stream.shutdown();
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: consider awaiting the future or dropping explicitly with `std::mem::drop`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_future
= note: `-D clippy::let-underscore-future` implied by `-D warnings`
```
Await the shutdown.
> Fixes non-binding `let` on a future (ip-echo-server)

- .github/workflows/manage-stale-issues-and-prs.yml
Oops. Changed this in the repository, but failed to update it in code.
_Note to self: land this _after_ 8:00UTC Dec 10_
> chore: correct the name of the STALEBOT_START_DATE_RFC_2822 variable

- ci/publish-tarball.sh
- ci/rust-version.sh
- rust-toolchain.toml
* Introduce `rust-toolchain.toml` file
* Use version specified in this file instead of specifying one in `ci/rust-version.sh`
> take rust version from toolchain file

- runtime/src/rent_collector.rs
These metrics pre-dated the feature activation that caused us to stop updating `rent_epoch` for rent exempt accounts.
Remove the metrics.
Fixes #
> remove metrics from prior to rent_epoch feature activation

- runtime/src/accounts_db.rs
We're copying data right now into hashes, write_version, and StoredMeta when we shrink. This is not necessary.
Use `StorableAccounts` trait to use data in `FoundStoredAccount`
Fixes #
> shrink avoids reshaping data by using StorableAccounts trait

- web3.js/src/publickey.ts
toBytes claims to return a Uint8Array when in reality it returns a Buffer. This isn't a huge problem as in 99.9% of cases these two work just as well for the caller, but causes issues in some edge cases (e.g. toString() on a Uint8Array and on a Buffer over the same bytes returns different strings). It's also a code smell, due to making this method fully redundant to the toBuffer() method in addition to its typehint not returning *exactly* what it says it should.
Actually convert the buffer to a Uint8Array
> fix: make toBytes actually return the type it's typehint claims

- gossip/src/cluster_info.rs
- gossip/src/crds.rs
Retrieve all recently upserted duplicate-shreds from gossip crds table.
* Indexed duplicate-shreds in gossip crds table
* Also adding `Crds::get_duplicate_shreds` which retrieves all upserted duplicate-shreds since a given cursor using the index.
> indexes duplicate-shreds in gossip crds table

- runtime/src/accounts_db.rs
- runtime/src/snapshot_minimizer.rs
test was writing uncached and ending up with multiple append vecs in the same slot
write to the cache
Fixes #
> test_minimize_accounts_db uses write cache correctly

- core/src/broadcast_stage/standard_broadcast_run.rs
https://github.com/solana-labs/solana/pull/29339 adds hash domain to merkle shreds. In order to merge that change, need to temporarily disable merkle shreds on testnet.
Temporarily disable merkle shreds on testnet.
> rolls back merkle shreds on testnet

- runtime/src/prioritization_fee.rs
Would like to add min/max fee to [fee_market](https://metrics.solana.com:3000/d/0n54roOVz/fee-market?orgId=1) dashboard, as well as counts of transactions with and without fee.
- add counters
Fixes #
> Add metrics for min/max priority fee per slot, and counters for fee/non-fee transactions

- accounts-bench/src/main.rs
- runtime/benches/accounts.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/serde_snapshot/tests.rs
Working on allowing 0 or 1 append vecs per slot, not > 1.
There is test code that allocates multiple append vecs for the same slot unnecessarily.
1. move test_utils into accounts_db.rs
2. pre-allocate an append vec that can store all test accounts
Fixes #
> test_utils::create_test_accounts pre-allocates an append vec first

- runtime/src/account_storage.rs
- runtime/src/accounts_db.rs
- runtime/src/snapshot_minimizer.rs
Moving towards a future where there is 1 append vec per slot (as opposed to 0, 1, or > 1).
Shrink is a time when there must be 2 findable append vecs for 1 slot. Alive accounts have been copied from 1 append vec to a new, shrunk one. While the index is being updated to refer to the new append vec's id, both append vecs need to be findable.
Produce a reliable way to represent the state where there is an append vec actively being shrunk.
Fixes #
> introduce ShrinkInProgress

- runtime/src/bank.rs
- sdk/src/feature_set.rs
- send-transaction-service/src/send_transaction_service.rs
Found a couple typos
Fix them.
The edit to `feature_set.rs` should not cause any issues, since it is just the module name used under the hood and doesn't touch cli output.
Just as a fun walk down memory lane: the STS typo has been there since https://github.com/solana-labs/solana/pull/10446
> Fix "tranaction" typo in code base

- cli/src/feature.rs
It is annoying to have to set and use the solana-cli default signer to activate features.
Add `--fee-payer` arg to allow an alternate payer
There's an argument to be made that this should be called `--from` instead, since it's paying for the feature account as well as the tx fee. Or perhaps there should be both `--fee-payer` and `--from` params. But what I've done was easiest and, I thought, clear enough. Wdyt?
> Add fee-payer arg to solana feature activate

- Cargo.lock
- programs/vote/Cargo.toml
- programs/vote/src/vote_processor.rs
- programs/vote/src/vote_state/mod.rs
- sdk/program/src/epoch_schedule.rs
- sdk/program/src/vote/error.rs
- sdk/src/feature_set.rs
Commission ruggers are a big annoyance.
Following the proposal in #29346, simply prohibit updating commissions in the second half of epochs.
Fixes #29346
Feature Gate Issue: #29361
> vote: Prevent commission update in the second half of epochs

- explorer/src/components/account/SecurityCard.tsx
- explorer/src/utils/security-txt.ts
We have added two new fields to the [Security Txt](https://github.com/neodyme-labs/solana-security-txt). 
Add `source_release` and `source_revision` fields to the security tab.
> Security TXT: Add source_release and source_revision fields

- ledger-tool/src/bigtable.rs
- ledger/src/bigtable_upload.rs
`solana_ledger::bigtable_upload::upload_confirmed_blocks()` returns an Err if the targeted Blockstore has no blocks in the range requested. This is inconsistent with the other "nothing to upload" case where blocks exist in Blockstore but have already been uploaded to Bigtable, which returns Ok.
Change Err to Ok; make it more clear through docs and var names that the the slot returned by the method is the last block checked, and doesn't depend on anything actually being uploaded during that pass.
> Fix BigTable upload early return

- ledger/src/bigtable_upload.rs
Adjust some logs, and remove an unnecessary cloned().
> Minor cleanup on bigtable_upload

- ledger-tool/src/bigtable.rs
Currently, if starting-slot is unspecified, a value of 0 will be chosen. In the common case where someone is operating on a range much more recent, this will result in a ton of wasted operations.
Instead, choose a smarter default value for starting-slot based on what we detect is currently in the blockstore.
> Adjust ledger-tool bigtable upload starting-slot default value

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
The web3.js wrapper does not currently support the JSON RPC call "getInflationRate". 
This change adds a function to the Connection object to expose the JSON RPC call "getinflationRate", as well as adds a test for the function call.
> Add getInflationRate RPC call to web3.js

- core/src/ancestor_hashes_service.rs
- core/src/heaviest_subtree_fork_choice.rs
- core/src/repair_service.rs
- core/src/repair_weight.rs
- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/window_service.rs
When dumping a slot from replay_stage as a result of duplicate or ancestor hashes, properly update repair subtrees to keep weighting and forks view accurate.
Repair has no idea when replay dumps blocks
Notify repair and update subtrees
Fixes #28648
> Plumb dumps from replay_stage to repair

- core/src/cluster_nodes.rs
- core/src/retransmit_stage.rs
- sdk/src/feature_set.rs
https://discord.com/channels/428295358100013066/1016733708562202674/1055874753736482846
* Need to understand how different turbine fanouts perform on the actual cluster.
* Optimize turbine fanout accordingly.
* The commit allocates 2% of slots to running experiments with different turbine fanouts based on the slot number.
* The experiment is feature gated with an additional feature to disable the experiment.
Feature Gate Issue: https://github.com/solana-labs/solana/issues/29394, https://github.com/solana-labs/solana/issues/29395
> experiments different turbine fanouts for propagating shreds

- core/src/serve_repair.rs
- local-cluster/tests/local_cluster_flakey.rs
Unable to reproduce failure in #29221, we remove the retry mechanism and add more logging to diagnose such failure if it appears in CI
Revert #29228 and add more debug logging surrounding repair
Fixes #
> Add more logging and documentation to flaky optimistic confirmation tests

- docs/build-cli-usage.sh
> replaced ./cargo with cargo in build docs

- web3.js/src/connection.ts
- web3.js/test/connection.test.ts
The `@solana/web3.js` SDK `InflationReward` type and `rewards` in the `meta` for `transaction status metadata object` properties do not match the JSON RPC spec in that they are missing the `commission` field. This is causing an issue with the types when attempting to access field value.
See:
- https://docs.solana.com/developing/clients/jsonrpc-api#getinflationreward
- https://docs.solana.com/developing/clients/jsonrpc-api#getblock
Adds the commission field in the `src/connection.ts`
- `InflationReward`
- `RewardsResult`
- `GetInflationRewardResult`
- `BlockResponse`
- `ParsedBlockResponse`
- `VersionedBlockResponse`
- `ConfirmedBlock`
Adds commission field in the `mockRpcResponse` in the `tests/connection.test.ts` file.
> feat: add commission fields matching RPC spec

- ledger/src/shred.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/merkle.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shred/traits.rs
- ledger/src/sigverify_shreds.rs
Working towards removing merkle root from shreds payload. 
Added api to obtain signed data from shreds binary.
> adds shred::layout::get_signed_data

- ledger/src/shred/merkle.rs
- ledger/src/shred/shred_code.rs
Merkle shreds within the same erasure batch have the same merkle root.
The root of the merkle tree is signed. So either the signatures match
or one is invalid, and the comparison of merkle roots is redundant.
removed merkle root comparison in erasure_mismatch
> removes merkle root comparison in erasure_mismatch

- core/src/broadcast_stage/broadcast_duplicates_run.rs
- ledger/src/shred.rs
- ledger/src/shred/legacy.rs
- ledger/src/shred/merkle.rs
- ledger/src/shred/shred_code.rs
- ledger/src/shred/shred_data.rs
- ledger/src/shred/traits.rs
* Working towards removing merkle root from shreds binary.
* This would require legacy and merkle shreds returning different types for `signed_data` method.
The commit adds an associated `SignedData` type to Shred trait so that merkle and legacy shreds can return different types for `signed_data` method.
This would allow legacy shreds to point to a section of the shred payload, whereas merkle shreds would compute and return the merkle root. Ultimately this would allow to remove the merkle root from the shreds binary.
> generalizes the return type of Shred::get_signed_data

- runtime/src/accounts_db.rs
- runtime/src/append_vec.rs
add test specifically for over flow case of ancient append vecs
Fixes #
> add test_shrink_ancient_overflow

- runtime/src/bank.rs
- runtime/src/rent_collector.rs
test permutations of feature activation
Fixes #
> test permutations of set_exempt_rent_epoch_max
