runtime/src/accounts_db.rs

code cleanup for clarity and testability
Fixes #

ancient append vec comments and cleanup

---

runtime/src/accounts_db.rs

simplify and clarify the logic for dropping/retaining a store and root in ancient append vecs
Fixes #

cleanup drop in ancient append vecs

---

runtime/src/accounts_db.rs

add tests for `shrink_collect`
Fixes #

ancient append vec tests

---

runtime/src/accounts_db.rs

add current_ancient tests

---

runtime/src/accounts_db.rs

add tests, factor out function
Fixes #

tests for maybe_unref_accounts_already_in_ancient

---

runtime/src/accounts_db.rs
runtime/src/accounts_index.rs
runtime/src/in_mem_accounts_index.rs

share code across shrink, clean, and ancient append vecs
Fixes #

extract 'unref_pubkeys' for shared code

---

core/src/banking_stage.rs

Metric is never set.
Stop reporting it.
Fixes #

remove unused handle_retryable_packets_elapsed

---

core/src/banking_stage.rs

#28654 - manual backport to v1.14. This is close enough to v1.13 that we can use label backporting once reviewed.
Reserve a new queue and verify capacity after processing.
Fixes #

Maintain original queue capacity for unprocessed packet buffer - Manual v1.14 Backport

---

core/src/ledger_cleanup_service.rs

Add a test to better exercise `find_slots_to_clean()`, as well as a minor
bug fix to this method that was found as a result of writing test.

Add LedgerCleanupService::find_slots_to_clean() test

---

core/src/banking_stage.rs

Really long functions in banking-stage are hard to understand.
Break them up a bit and combine like-data in structs. No functional change.
Fixes #

Banking stage refactor commit transactions

---

runtime/src/accounts_db.rs

add test_get_keys_to_unref_ancient

---

runtime/src/accounts_db.rs

add more test variations
Fixes #

add test variations for shrink_collect

---

runtime/src/rent_collector.rs

This allows me to know that changes won't affect anything outside this file.
Fixes #

remove public from rent code

---

geyser-plugin-manager/src/accounts_update_notifier.rs
runtime/src/accounts_db.rs
runtime/src/append_vec.rs
runtime/store-tool/src/main.rs

simplify code with accessor for pubkey()
Also minor type cleanup u64 -> Slot
Fixes #

.pubkey() instead of meta.pubkey for stored account

---

runtime/src/accounts_db.rs
runtime/src/ancient_append_vecs.rs
runtime/src/snapshot_minimizer.rs
runtime/src/storable_accounts.rs

remove duplicate pubkey storage per entry while shrinking
Fixes #

remove duplicate pubkey during shrink

---

runtime/src/accounts_db.rs

add tests for handle_dropped_roots_for_ancient

---

runtime/src/accounts_db.rs

ancient append vecs assert with this incorrect behavior. Shrink works fine.
fix the logic.
Fixes #

fix ancient append vec throwing away stores bug

---

runtime/src/accounts_db.rs

add tests for ancient append vecs
Fixes #

add ancient append vec tests

---

runtime/src/accounts_db.rs
runtime/src/read_only_accounts_cache.rs

assist in benchmarking performance
Fixes #

add ability to flush read only accounts cache

---

programs/bpf-loader-tests/tests/common.rs
programs/bpf-loader-tests/tests/extend_program_ix.rs

No easy way make account modifications when setting up accounts for tests

Refactor upgradeable loader test utility function

---

runtime/src/accounts_db.rs

ancient append vec stat fixes

---

runtime/src/accounts_db.rs

add stats for ancient append vecs
Fixes #

add ancient append vec stats

---

README.md

Docs don't mention using the ./cargo script for builds.

Update docs to use ./cargo

---

runtime/src/cost_tracker.rs

Fix typo in cost_tracker.rs

---

runtime/src/accounts_db.rs

test multiple slots appended
Fixes #

improve ancient append vec test

---

runtime/src/accounts_db.rs
runtime/src/bank.rs

remove unnecessary pub api fn
Fixes #

remove LoadedAccount::stored_size

---

runtime/src/accounts_db.rs

test ancient append vecs with dead slots
Fixes #

test ancient append vecs with dead slots

---

runtime/src/account_rent_state.rs
runtime/src/accounts.rs
runtime/src/bank.rs
runtime/src/bank/transaction_account_state_info.rs

Feature is activated on all clusters.
Removed feature gate code.
Fixes #26607

removes feature gate code preventing crediting accounts that end rent paying

---

runtime/src/accounts_db.rs

This lets me construct different sets of slots with accounts in them and then combine them in different ways into ancient append vecs.
Fixes #

refactor test ancient population code

---

runtime/src/accounts_db.rs

In warping tests, this takes a really long time because we have a sparse set of slots. I have observed this slow behavior elsewhere at various times as well..
Wait to init accumulator until we find that we actually have storages to scan.
Fixes #

acct hash: don't init accum or create hash file if no storages

---

runtime/src/accounts_db.rs
runtime/src/append_vec.rs

I had to read code for a while to understand fully the return value from `append_accounts`.
Use `Option` to clarify the out of space condition.
Fixes #

cleanup return value from append_accounts

---

runtime/src/accounts_db.rs

This stat wasn't getting reported.
Report it.
Fixes #

collect storage_read_elapsed for shrink and ancient

---

runtime/src/accounts_db.rs

stats are unnecessarily reported when almost no work is done
Fixes #

only log ancient append vec stats when they are useful

---

runtime/src/accounts_db.rs

refactor for use in tests
Fixes #

refactor into combine_one_store_into_ancient

---

docs/src/cluster/rpc-endpoints.md

Serum RPC is no longer available
Remove from docs

Docs: Removed Serum RPC mention

---

.github/workflows/docs.yml

- use git diff + grep to detect files status
- separate workflow into three main blocks
- check
- build & deploy (deploy when needed)
- notification (when failed)

ci: refactor docs pipeline

---

runtime/src/accounts_db.rs

Better api, and allows for improving the runtime api and not touching more tests than necessary.
Fixes #

extract test append_account function

---

runtime/src/accounts_db.rs

add tests for shrinking ancient append vec itself
Fixes #

add shrink ancient test

---

runtime/src/accounts_background_service.rs
runtime/src/accounts_db.rs

cleanup CalcAccountsHashDataSource

---

Cargo.lock
cli/Cargo.toml
program-runtime/Cargo.toml
programs/bpf_loader/Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
rbpf-cli/Cargo.toml

bump solana_rbpf to v0.2.37

---

scripts/build-downstream-anchor-projects.sh

Replace link to the anchor repo with the new one

replace serum/anchor with coral-xyz/anchor

---

core/src/broadcast_stage/standard_broadcast_run.rs

Testing Merkle shreds on testnet.
Rolls out Merkle shreds to ~20% of testnet

rolls out merkle shreds to ~20% of testnet

---

runtime/src/accounts_hash.rs

comment function

---

sdk/cargo-build-sbf/tests/crates.rs

failre in one of the test names
change to failure
Fixes #

typo: failre to failure

---

core/src/banking_stage.rs

remove unnecessary clippy attributes

---

runtime/src/accounts_db.rs

We want to enable write cache on all tests. At least all tests dealing with shrink.
This test calls shrink and does not use the write cache.
Enable the write cache for this test.
Fixes #

test_store_reuse uses write cache

---

runtime/src/append_vec.rs

see comments in test
stop testing that we can write an illegal file
Fixes #

test_new_from_file_crafted_zero_lamport_account uses static append vec file

---

runtime/src/accounts_hash.rs

function is about to be changed
make one of the outputs more clear in its meaning
Fixes #

rename test var for clarity

---

core/src/validator.rs
local-cluster/tests/local_cluster.rs

goal is to transition all tests to use write cache only
convert some tests to use write cache
Fixes #

default some tests to write cache = true

---

scripts/build-downstream-projects.sh

As part of CI checks, we build serum-dex which was migrated to openbook-dex.
Replace serum-dex with openbook-dex

replace serum-dex with openbook-dex

---

runtime/benches/append_vec.rs
runtime/src/accounts.rs
runtime/src/accounts_db.rs
runtime/src/ancient_append_vecs.rs
runtime/src/append_vec.rs
runtime/src/bank.rs
runtime/src/snapshot_minimizer.rs
runtime/src/storable_accounts.rs

This improves performance of shrink and ancient shrink.
Eliminate creating vec of hashes in shrink/ancient.
Fixes #

improve perf of storing accounts for shrink/ancient

---

core/src/banking_stage.rs

cleanliness. working to separate decision making, locking, etc, from banking stage processing.
make_decision as a separate function
Fixes #

separate make_decision in BankingStage

---

programs/bpf_loader/src/syscalls/cpi.rs
programs/bpf_loader/src/syscalls/mem_ops.rs
programs/bpf_loader/src/syscalls/mod.rs

The syscall_saturated_math feature has been enabled, this removes the feature checks

The syscall_saturated_math feature was activated, remove checks

---

banking-bench/src/main.rs

move comments to correct place
Fixes #

Update code comments for banking bench

---

core/src/repair_generic_traversal.rs
core/src/repair_service.rs
core/src/repair_weight.rs
core/src/repair_weighted_traversal.rs
core/src/serve_repair.rs

More documentation + small refactor for RepairService

---

web3.js/src/publickey.ts

web3.js: use constant for PUBLIC_KEY_LENGTH for checking length of input

---

web3.js/package.json
web3.js/yarn.lock

Upgraded this in #27333 and then thought… hey… is this even used?

chore: remove unused http-server dependency from web3.js

---

web3.js/package.json
web3.js/yarn.lock

chore: remove @babel/register dependency from web3.js

---

runtime/src/accounts_db.rs

distinguish between '# bytes' and '# accounts' with better struct member names
Fixes #

add 'bytes' to aligned/alive_total for clarity

---

tpu-client/src/nonblocking/tpu_client.rs

https://github.com/solana-labs/solana/pull/28954 removed usage of estimated current slot while looking up leader TPU sockets. This can cause the TPU client to send transactions to the first set of leaders until the cache is updated.
This change reintroduces the usage of estimated current slot. This will enable the TPU client to cycle through the cache and send transactions to the estimated current leaders.
Fixes #

Use estimated current slot in tpu client

---

runtime/src/serde_snapshot/tests.rs

trying to get all tests to use the write cache so we can get rid of the non-write cache code copies.
Fixes #

tests use write cache

---

runtime/src/bank.rs

We want to remove the code paths for not using the write cache. This test is a laggard.
Fixes #

test_add_precompiled_account_inherited_cap_while_replacing uses write cache

---

runtime/src/bank.rs

migrate all tests to use write cache
Fixes #

test_add_instruction_processor_for_existing_unrelated_accounts works with write cache

---

runtime/src/cost_tracker.rs

All `*_internal()` functions in cost_tracker are no longer necessary
- remove them
Fixes #

remove redundant internal functions

---

runtime/src/bank.rs

migrating all tests to use write cache so we can eliminate the non-write-cache option completely.
This test will now work either way.
Fixes #

test_bank_hash_internal_state_verify works with write cache

---

runtime/src/bank.rs

migrate all tests to use write cache so we can eliminate the old code path
Fixes #

test_bank_update_vote_stake_rewards works with write cache

---

ledger/src/blockstore_meta.rs

Add a unit test to guarantee the behavior of slot 0 being connected.

Add SlotMeta unit test for connected at slot zero

---

gossip/src/cluster_info.rs
gossip/src/cluster_info_metrics.rs
gossip/src/crds_gossip.rs
gossip/src/crds_gossip_push.rs
gossip/tests/crds_gossip.rs

How many nodes each gossip message is fanned out to?
Added metrics for gossip push fanout

adds metrics for gossip push fanout

---

runtime/src/bank.rs

migrating all tests to use write cache only
Fixes #

test_verify_snapshot_bank works without write cache

---

runtime/src/accounts_db.rs

test_lazy_gc_slot can use write cache

---

runtime/src/accounts_db.rs

test_uncleaned_roots_with_account uses write cache

---

runtime/src/accounts_db.rs

migrating all tests to use the write cache
Fixes #

test_shrink_stale_slots_processed uses write cache

---

runtime/src/accounts_db.rs

migrating tests to use write cache

---

runtime/src/account_info.rs
runtime/src/accounts_db.rs

test_clean_zero_lamport_and_dead_slot uses write cache

---

runtime/src/accounts_db.rs

migrate tests to work with write cache

---

runtime/src/accounts_db.rs

test_remove_unrooted_slot_snapshot uses write cache

---

runtime/src/accounts_db.rs

test_shrink_collect_simple uses write cache

---

runtime/src/bank.rs

migrating all tests to use write cache so we can eliminate dead code
Fixes #

migrate tests to use write cache

---

runtime/src/accounts_db.rs
runtime/src/append_vec.rs

`STORE_META_OVERHEAD` is too large. The result is we way over-allocate append vecs when we flush the write cache. This causes us to need to shrink later unnecessarily soon.
Calculate the required file size accurately.
Fixes #

introduce aligned_stored_size to flush write cache

---

.github/workflows/docs.yml

chore: fix wrong name for GITHUB_SHA

---

core/src/system_monitor_service.rs
core/src/validator.rs
ledger-tool/src/main.rs

refactor system monitor report config
Fixes #

refactor sysmonitor config

---

core/tests/epoch_accounts_hash.rs
runtime/src/bank.rs
runtime/src/serde_snapshot/tests.rs

removing vestiges of caching enabled.
Fixes #

remove bank_test_config_caching_enabled

---

runtime/src/accounts.rs
runtime/src/serde_snapshot/tests.rs

removing vestiges of caching enabled.
Fixes #

remove Accounts::new_with_config_for_tests.caching_enabled

---

core/tests/snapshots.rs
runtime/src/accounts_background_service.rs

removing all vestiges of caching_enabled
Fixes #

remove handle_snapshot_requests.caching_enabled

---

bench-tps/tests/bench_tps.rs
core/src/validator.rs
local-cluster/src/validator_configs.rs
local-cluster/tests/local_cluster.rs
test-validator/src/lib.rs
validator/src/main.rs

removing all vestiges caching_enabled.
Fixes #

remove ValidatorConfig.caching_enabled

---

rpc/src/rpc.rs
runtime/src/bank.rs

removing all vestiges of caching_enabled
Fixes #

remove BankTestConfig.caching_enabled

---

runtime/src/accounts_db.rs

Removing all vestiges of caching_enabled.
Fixes #

remove AccountsDb::new_with_config_for_tests.caching_enabled

---

core/src/serve_repair.rs

#28673 applies only to `ClusterType::Testnet`.
Apply #28673 changes to clusters other than MainnetBeta.
Fixes #

apply [limit repairs to top staked... #28673] to non-MainnetBeta clusters

---

.github/workflows/crate-check.yml
ci/check-crates.sh

#29002
add a crate check Github Actions.

ci: check crates

---

ledger/src/blockstore_processor.rs
runtime/src/bank.rs

removing all code related to disabling write cache
Fixes #

remove accounts_caching from Bank::new_with_paths

---

core/tests/snapshots.rs
ledger/src/blockstore_processor.rs
runtime/src/bank.rs
runtime/src/snapshot_utils.rs

Removing old code paths that disabled write cache.
Fixes #

remove caching_enabled from Bank::new_with_paths_for_tests

---

runtime/src/bank.rs

removing code paths that allowed disabled write cache
Fixes #

remove enable_caching from Bank::new_with_config_for_tests

---

core/src/validator.rs
ledger-tool/src/main.rs
ledger/src/bank_forks_utils.rs
ledger/src/blockstore_processor.rs

removing all code related to disable write cache
Fixes #

remove ProcessOptions::accounts_db_caching_enabled

---

scripts/build-downstream-projects.sh

some context here #29201
and the fixed PR has been merged https://www.github.com/openbook-dex/program/pull/24
add openbook_dex back

ci: add openbook_dex back to downstream project test

---

runtime/src/accounts_background_service.rs

getting rid of all caching_enabled tentacles.
Fixes #

remove some if accounts_db_caching_enabled {

---

runtime/src/bank.rs

removing all non write cache code paths
Fixes #

remove test_store_scan_consistency(caching_enabled)

---

runtime/src/accounts_background_service.rs

getting rid of all caching_enabled calls
Fixes #

remove handle_snapshot_requests(caching_enabled)

---

runtime/src/accounts_background_service.rs
runtime/src/bank.rs

getting rid of all caching_enabled tentacles.
Fixes #

remove process_stale_slot_with_budget

---

runtime/src/accounts_background_service.rs

removing all code with `caching_enabled`
Fixes #

remove handle_snapshot_request(caching_enabled)

---

runtime/src/accounts_db.rs
runtime/src/accounts_index.rs
runtime/tests/accounts.rs

remove all `caching_enabled` parameters and associated dead code paths.
Fixes #

remove process_stale_slot_v1 and other fns

---

runtime/src/accounts_db.rs

Maybe the last thing remaining from the non-write cache code path.
Removing everything from the v1/non-write-cache code path.
Fixes #

remove shrink_candidate_slots_v1

---

runtime/src/accounts_db.rs
runtime/src/snapshot_minimizer.rs

preparing to only allow 1 append vec per slot
0..n append vecs per slot complicates many code paths and requires the `write_version` field. We don't use multiple append vecs per slot anymore.
Fixes #

Vec<Arc<AccountStorageEntry>> becomes SnapshotStorage

---

runtime/src/account_storage.rs
runtime/src/accounts_db.rs
runtime/src/serde_snapshot.rs

making AccountStorage hide its implementation so we can change it.
Fixes #

make AccountStorage::map private

---

ledger/tests/shred.rs

fix typo in shred.rs

---

explorer/src/utils/anchor.tsx

Anchor argument parsing was incomplete for enum
Adds recursive parsing for anchor enum arguments that have fields associated with them (this has a specific rust macro `syn` name that I'm blanking on - it's an EnumWithData or something)
Fixes #28306

explorer: add enum parsing for anchor arguments

---

ledger/src/shred/merkle.rs

Instead of sanitizing shreds late in recover code:
https://github.com/solana-labs/solana/blob/50ad0390f/ledger/src/shred/merkle.rs#L786
`Shred{Code,Data}::from_recovered_shard` should sanitize shreds before returning:
https://github.com/solana-labs/solana/blob/50ad0390f/ledger/src/shred/merkle.rs#L192-L216
https://github.com/solana-labs/solana/blob/50ad0390f/ledger/src/shred/merkle.rs#L324-L350
Sanitize shreds recovered from erasure shards

sanitizes shreds recovered from erasure shards

---

rpc/src/rpc_subscriptions.rs

`Box<dyn ...>` requires dynamic dispatch, is heap allocated, slow and verbose.
removed `Box<dyn Iterator<...>>`

removes Box<dyn Iterator<...>> from rpc/src/rpc_subscriptions.rs

---

ledger-tool/src/main.rs

The `list-roots` ledger-tool subcommand has an off-by-one error in regards to which roots it will output.
- The old find-roots logic called `.enumerate()` and took entries until `i > num_roots`
- This is equivalent to `i <= num_roots` and would yield `num_roots + 1` elements if available
- The output logic also called `.enumerate()` and output entries while `i < num_roots`
There is obviously an incongruence here in that we're collecting `num_roots + 1` entries and outputting `num_roots` of them; since we print the roots in descending order, this means we are dropping the oldest root (ie the `start-slot` if `start-slot` is indeed a root) from output.
Use "rustier" iterator conventions which eliminate the aforementioned bug.

Make ledger-tool list-roots subcommand inclusive of start-root arg

---

client-test/tests/client.rs

Fixup clippy warnings to upgrade to Rust 1.66.0
Fixes format string

Fixes format string

---

core/src/unprocessed_transaction_storage.rs

function `filter_forwardable_packets_and_add_batches()` makes a straight through call to `filter_and_forward_with_account_limits()`. They can be merged into one.
- remove `filter_and_forward_with_account_limits()`
Fixes #

remove a wrapper function

---

runtime/src/accounts_db.rs

Remove old code that creates multiple append vecs per slot.
This is only having an effect with tests.
Fixes #

remove acctdb.min_num_stores

---

validator/src/admin_rpc_service.rs

I made a mistake in rebasing and preserved a dangling println in an rpc test
Remove it
Fixes #29338

Remove println

---

runtime/src/prioritization_fee_cache.rs

Vote transactions are not prioritized (eg. always have zero prioritization fee), updating block's min-fee-cache with them will incorrectly skew the min-fee towards zero.
- skip `sanitized_transaction.is_simple_vote_transaction()` when updating min-fee-cache.
Fixes #

exclude Vote transactions from updating min-fee-cache

---

docs/src/developing/programming-model/transactions.md

- added broad overview of Transactions
- update the internal links to work better with relative routing
- added SEO description

[docs] Updated transactions overview page

---

docs/sidebars.js
docs/src/cluster/fork-generation.md
docs/src/developing/intro/transaction_fees.md
docs/src/developing/on-chain-programs/deploying.md
docs/src/developing/transaction_confirmation.md
docs/src/transaction_fees.md

Resources and information for Solana is scattered around the internet. This PR pulls in the amazing articles written by and located on @jstarry 's [Solana Dev Blog](https://jstarry.notion.site/jstarry/Solana-Dev-Blog-302b7e08652c4a2dbc0be4f6a3b0d317) 
> NOTE: Most of the content from the articles on the blog was added into these docs, except for the "status updates" portions.
- created a new "transaction fees" page from the article
- created a new "transaction confirmation" page from the article
- added some extra info (and the example) of fork generation
- added the new transaction fee and confirmation pages to the Developer's sidebar
- updates 
> NOTE: The old transaction fees page was kept (almost as is) to remain a quicker, less technical page and a high level overview of the …

docs: transactions fees/confirmation and deploying programs

---

client-test/tests/client.rs

fix: client-test timeout

---

cargo-build-bpf
cargo-build-sbf
cargo-test-bpf
cargo-test-sbf

Replace ./cargo with cargo in `cargo-[test|build]-[bpf|sbf]`

replace ./cargo with cargo in sbf/bpf build scripts

---

scripts/build-downstream-anchor-projects.sh
scripts/build-downstream-projects.sh

get rid of ./cargo when building downstream projects

---

web3.js/package-lock.json

seems the incorrect lock file make this test failed
(like https://github.com/solana-labs/solana/actions/runs/3752463623/jobs/6374650446)
update web3.js/package-lock.json
the lock file generated by
```shell
> node -v
v16.19.0
> npm -v
8.19.3
```

ci: fix web3-commit-lint

---

entry/src/entry.rs
ledger/src/sigverify_shreds.rs
perf/src/sigverify.rs

Need to maintain correctness for upcoming merkle shred changes.
Expanded test coverage for merkle/legacy shreds sigverify.

expands test coverage for merkle/legacy shreds sigverify

---

ledger/src/sigverify_shreds.rs

Need to maintain correctness for upcoming merkle shred changes.
Expanded test coverage for sign_shreds_gpu.

expands test coverage for sign_shreds_gpu

---

ledger/src/sigverify_shreds.rs

Preparing changes to remove Merkle roots from shreds binary.
Minor refactors. No logic changes.
Test coverage was first expanded in https://github.com/solana-labs/solana/pull/29424 and https://github.com/solana-labs/solana/pull/29429

simplifies shreds sigverify

---

ledger/src/shred.rs
ledger/src/shred/merkle.rs

Working towards removing merkle roots from shreds payload.
In preparation of removing merkle roots form shreds binary, the commit adds api to recover the root from the merkle proof embedded in shreds payload.

implements shred::layout::get_merkle_root

---

runtime/src/account_storage.rs

Code cleanup during refactoring.
We would already panic on the unwrap() below this code if there were no existing append vecs at this slot. It is an illegal use to call this when there are no append vecs at the slot. That is not a valid shrinking use case.
Fixes #

cleanup 'shrinking_in_progress'

---

runtime/src/accounts_db.rs

update comments and add test.
Fixes #

add test and comments

---

runtime/src/accounts_db.rs

`get_storages_for_slot` had an equivalent implementation already.
Re-use existing impl.
Fixes #

simplify get_storages_for_slot

---

runtime/src/bank.rs

Refactoring to make skipping rewrites fully feature driven. We no longer need to keep track of skipped rewrites for bank hash inclusion.
Remove old code no longer used.
Fixes #

remove skip rewrite code from collect_rent_from_accounts

---

runtime/src/accounts_db.rs

moving towards only 1 append vec per slot
cleanup function
Fixes #

refactor RecycleStores::add_entries

---

runtime/src/account_storage.rs
runtime/src/accounts_db.rs

Inline single use function to simplify api.
Inline `AccountStorage`::`slot_store_count`.
Fixes #

remove single use AccountStorage.slot_store_count

---

ledger/src/blockstore_metrics.rs

Fix typo in blockstore_metrics.rs

---

account-decoder/src/parse_address_lookup_table.rs
clap-utils/src/input_parsers.rs
clap-v3-utils/src/input_parsers.rs
core/src/validator.rs
programs/stake/src/stake_instruction.rs
rpc-client-nonce-utils/src/blockhash_query.rs
rpc-client-nonce-utils/src/nonblocking/blockhash_query.rs
runtime/src/accounts.rs
zk-token-sdk/src/range_proof/mod.rs

`clippy::redundant_clone`
https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
fixed errors.

fixes errors from clippy::redundant_clone

---

runtime/src/accounts_db.rs

shrink fns take a single append vec
Fixes #

shrink fns take a single append vec

---

runtime/src/accounts_db.rs

Callers to `do_shrink_slot_stores` all had a single store at this point and built an iter to call `do_shrink_slot_stores`
rename `do_shrink_slot_stores` -> `do_shrink_slot_store`
Change from iter of stores to a single store.
Fixes #

do_shrink_slot_stores -> do_shrink_slot_store

---

core/benches/banking_stage.rs
core/benches/retransmit_stage.rs
core/src/broadcast_stage.rs
entry/src/entry.rs
gossip/src/cluster_info.rs
gossip/src/epoch_slots.rs
ledger/src/blockstore.rs
transaction-status/src/parse_stake.rs
transaction-status/src/parse_token.rs

unnecessary lint bypass.
removed it.

removes #[allow(clippy::same_item_push)]

---

runtime/tests/accounts.rs

moving towards using 1 append vec per slot
This test adds to an append vec over and over. The result is we end up adding extra append vecs.
This is not realistic of normal system behavior.
The test writes to the cache, then flushes the cache so we read from both the cache and the append vecs.
Fixes #

test_bad_bank_hash uses write cache

---

ci/do-audit.sh

RUSTSEC-2023-0001
This only affects Windows builds. Unblocking CI.
Add an exception for RUSTSEC-2023-0001
https://discord.com/channels/428295358100013066/560503042458517505/1062063157184581633

Add exception for RUSTSEC-2023-0001 to unblock CI.

---

ci/do-audit.sh

RUSTSEC-2023-0001
Tokio problem with named pipes on windows.
Add exception.
https://discord.com/channels/428295358100013066/560503042458517505/1062063157184581633

Add exception for RUSTSEC-2023-0001

---

runtime/src/accounts_db.rs

`shrink_collect` takes 1 append vec instead of slice.
Fixes #

shrink_collect takes a single append vec

---

sdk/program/Cargo.toml

chore: bump anyhow to 1.0.58

---

runtime/src/accounts_db.rs
runtime/src/snapshot_minimizer.rs

rename to remove plural for clarity
Fixes #

get_unique_accounts_from_storages drops plural

---

programs/bpf_loader/src/syscalls/cpi.rs
sdk/src/feature_set.rs

979792b went directly into the v1.14 branch, leaving master's `feature_set` inconsistent
forward port the gate

fix: synchronize cpi error prioritization with v1.14 (fp #29593)

---

Cargo.lock
net-utils/Cargo.toml
programs/sbf/Cargo.lock

chore: bump socket2 to 0.4.7

---

Cargo.lock
program-test/Cargo.toml
program-test/tests/warp.rs
runtime/src/bank.rs
sdk/src/feature_set.rs

filter stake by min delegation for rewards https://github.com/solana-labs/solana/issues/29622
Fixes #

Feature: filter stake by min delegation for rewards

---

Cargo.lock
client/Cargo.toml
programs/sbf/Cargo.lock
quic-client/Cargo.toml
quic-client/src/nonblocking/quic_client.rs
streamer/Cargo.toml
streamer/src/nonblocking/quic.rs

Update Quinn library to later versions
quinn-> 0.9.3
Quinn-proto --> 0.9.2
Quinn-udp --> 0.3.2
Fixes #
#29385

Update quinn versions

---

runtime/src/bank.rs
runtime/src/bank/metrics.rs

More cleanup in moving non-essential items out of bank.rs

chore: Move new bank metric into metric submodule

---

runtime/src/accounts_db.rs

Moving to 1 append vec per slot. This multiple append vec per slot function can be removed.
Remove `scan_multiple_account_storages_one_slot`
Fixes #

remove scan_multiple_account_storages_one_slot

---

runtime/src/snapshot_utils.rs
runtime/src/sorted_storages.rs

Moving towards 1 append vec per slot.
Data type has changed.
Replace the few stragglers left using `SnapshotStorages`
Fixes #

remove remaining uses of SnapshotStorages

---

gossip/src/crds.rs

It was not immediately clear why the second `CrdsValue` insertion in the test must always succeed.  Turns out the test was relying on hash values having a specific relationship.  It is confusing to someone not deeply familiar with the test.
As overwrite based on the hash value is not part of the behavior that we
consider valuable, we just remove that check.
Unified assertion between two checks into one.

gossip: crds::test::test_update_timestamp: Remove hash comparison

---

runtime/src/accounts_db.rs

`get_slot_stores(slot)` returns internals of the map and callers expect `Vec<...>` return value.
`get_slot_storage_entry(slot)` addresses both problems.
`get_slot_stores` -> `get_slot_storage_entry`
Fixes #

get_slot_stores -> get_slot_storage_entry

---

runtime/src/account_storage.rs

`get_account_storage_entry()` could return an incorrect store that doesn't match if a shrink is in progress.
Check `append_vec_id()` before returning.
Fixes #

get_account_storage_entry handles missing shrink in progress entry correctly

---

ledger/src/blockstore.rs

Simplify some logic and add some more documentation explaining why things are expected

chore: Cleanup and document a Blockstore chaining test

---

sdk/program/src/serde_varint.rs

more test coverage
added test verifying `serde_varint` vs `ShortU16`

verifies serde_varint vs ShortU16

---

core/src/shred_fetch_stage.rs
ledger/src/shred.rs
ledger/src/shred/stats.rs

track merkle shreds on the receiving end.
added metrics for num merkle shreds on the receiving end

adds metrics for num merkle shreds on the receiving end

---

runtime/src/account_storage.rs
runtime/src/accounts_db.rs

moving to 1 append vec per slot.
`SlotStores` includes a lock and a Vec. We don't want to leak either.
make `remove()` return the contents but not in `SlotStores`
Fixes #

storage.remove does not leak SlotStores

---

explorer/src/utils/program-logs.ts

Messed up formatting from earlier PR breaks build pipeline
Ran `npm run format:fix`
Fixes #

Explorer: Fix explorer formatting

---

runtime/src/account_storage.rs

Cleaning up vestiges of old api to AccountStorage.
slot_stores is an old concept that has been removed. Get rid of the unused pub api and internal uses.
Fixes #

remove get_slot_stores from AccountStorage

---

runtime/src/accounts_db.rs

We have moved to 1 append vec per slot.
Make some plurals singular.
Fixes #

make storages not plural

---

runtime/src/account_storage.rs
runtime/src/accounts_db.rs
runtime/src/serde_snapshot.rs
runtime/src/serde_snapshot/tests.rs
runtime/src/snapshot_minimizer.rs
runtime/src/snapshot_utils.rs
runtime/src/sorted_storages.rs

remove typedef that isn't helpful anymore. Recently code was modified to have 1 append vec per slot.
Fixes #

remove SnapshotStorageOne

---

gossip/src/crds_gossip.rs
gossip/src/crds_gossip_pull.rs
gossip/src/crds_gossip_push.rs

Duplicate code in gossip `{push,pull}_options`.
Factored out the code into one common function.

factors out common gossip {push,pull}_options code

---

banking-bench/src/main.rs
core/benches/banking_stage.rs
core/src/banking_stage.rs
core/src/tpu.rs

Currently, the trio of channel receivers for incoming transactions into banking stage is named/used inconsistently.
- use of `verified_` or not. (I don't think putting `verified` into _variable_ names clarifies and/or improves our code's security. it should be encoded as type if wanted to do so: ref `SanitizedTransaction`. and vague meaning of _verified_ (yeah, not `sigverified`). banking stage still does various _verification_/_sanitization_/_validation_ or whatever we call)
- as a illustration: there are `verified_gossip_vote_sender` and `gossip_verified_vote_sender` for  real
- everytime i see `verified_receiver`, I always wonders what's receiving.
- also, the next line `tpu_vote_receiver` and i always has to remember that this is actually `verified_` much like `verified_sender`.
- the …

Rename banking stage packet receivers consistently

---

docs/src/proposals/embedding-move.md

Mention that the document is stale.

---

core/src/banking_stage.rs
core/src/banking_stage/decision_maker.rs

**Simple Move PR**
Moves functions for decision making into a new module.
Fixes #

BankingStage Refactor: Move decision making functions to new module

---

core/src/system_monitor_service.rs

These values are fixed based on hardware, so no need to report as frequently as the realtime CPU utilization stats.
Break cpuid value reporting onto its' own interval (from realtime CPU stats), and set that interval to be 1 hour.

Reduce cpuid reporting frequency to once an hour

---

runtime/src/accounts_db.rs

It is more correct to only create an ancient append vec once we have discovered there is at least 1 alive account. Otherwise, the whole slot should have been destroyed.
In reality, this should not occur. But, eliminating the fact that there are 0 accounts to write makes the model easier to understand.
Don't create an ancient append vec for a slot if the slot contains 0 alive accounts.
Fixes #

if 0 alive accounts, don't create ancient append vec

---

runtime/src/accounts_db.rs

some tests are still using vec<append vec>
get rid of vec/slice
Fixes #

update tests for 1 append vec per slot

---

runtime/src/accounts_db.rs

only 1 append vec per slot
update some test code
Fixes #

update tests storages -> storage

---

banking-bench/src/main.rs
core/benches/banking_stage.rs
core/benches/cluster_info.rs
core/benches/retransmit_stage.rs
core/src/accounts_hash_verifier.rs
core/src/banking_stage.rs
core/src/broadcast_stage.rs
core/src/broadcast_stage/broadcast_fake_shreds_run.rs
core/src/broadcast_stage/standard_broadcast_run.rs
core/src/cluster_nodes.rs
core/src/cluster_slots_service.rs
core/src/repair_service.rs
core/src/serve_repair.rs
core/src/sigverify_shreds.rs
core/tests/snapshots.rs
gossip/src/cluster_info.rs
gossip/src/duplicate_shred_listener.rs
rpc/src/rpc.rs
rpc/src/rpc_health.rs
rpc/src/rpc_service.rs
validator/src/admin_rpc_service.rs

Pubkey in keypair should be the same as contact-info id.
```
assert_eq!(contact_info.id, keypair.pubkey());
```

asserts that cluster-info keypair is consistent with contact-info id

---

sdk/src/feature_set.rs

Community contribution https://github.com/solana-labs/solana/pull/28503 was missing a feature key.
Add a feature key.

Add a feature ID for enable_big_mod_exp_syscall

---

core/src/banking_stage.rs
core/src/banking_stage/forwarder.rs

**Simple Move PR**
Moved banking packet forwarding functions/logic into a separate module.
Blocked by #29401
Fixes #

BankingStage Refactor: Separate Forwarder Module

---

CONTRIBUTING.md

Create a section under CONTRIBUTING.md for crate creation.

Update CONTRIBUTING.md for crate creation.

---

gossip/src/crds_gossip_pull.rs
ledger-tool/src/output.rs
sdk/cargo-build-sbf/src/main.rs
validator/src/dashboard.rs

To upgrade our Rust (nightly) we need to fix up any new clippy lints. One of those is inlining variables into format strings when possible.
Inline variables into format strings.

Inlines variables into format strings

---

ledger/src/blockstore_processor.rs

Few local `*cost_without_bpf*` variables don't have actual use, possible leftovers from previous changes. Should clean it up before making changes in that area.
- remove unused variables.
Fixes #

Refactor: remove unused variable

---

core/src/serve_repair.rs

Repair request processing time is not tracked.
Add metric for repair request processing time.
Fixes #

track repair handle_requests time

---

ledger-tool/src/main.rs

Several subcommands may wish to specify AccountsDb configuration options. The matching is currently duplicated in both "verify" and "create-snapshot" command
Move the config to a common helper
Note that each subcommand that wishes to use any argument will still need to add the argument to its' argument list under App::new().
Fixes #29934

ledger-tool: Move AccountsDbConfig building to common helper function

---

runtime/src/accounts_db.rs

refactoring to change how we create ancient append vecs
Remove unnecessary lifetimes, which complicate things.
Fixes #

remove unnecessary lifetimes

---

runtime/src/accounts_db.rs

newer version of macro gives closer to ideal results
replace `measure!` with `measure_us!`
Fixes #

measure! -> measure_us!

---

validator/src/admin_rpc_service.rs

Need to expose the front end RPC API for https://github.com/solana-labs/solana/issues/28666
Add Admin RPC API.

Add Admin RPC Front End for Top N Secondary Index Key Sizes Query.

---

core/src/banking_stage.rs
core/src/banking_stage/decision_maker.rs

`DecisionMaker` requires external "book-keeping" in what variables are passed in.
Simplify by storing data on a `DecisionMaker` object.
Leaving metrics as is due to mutable reference - want to overhaul these in the future.
Fixes #

BankingStage Refactor: Add state to DecisionMaker

---

runtime/src/accounts_db.rs

Reworking ancient storage combining to write new storages in 1 pass.
New code will not be in accounts_db.rs.
Mark structs and functions as pub(crate).
Fixes #

add pub(crate) to shrink functions

---

core/src/banking_stage.rs
core/src/banking_stage/packet_receiver.rs
core/src/packet_deserializer.rs

Follow-up to #29761 
Simplifying PacketReceiver before pulling in state.
Fixes #

BankingStage Refactor: Simplify PacketReceiver

---

runtime/src/accounts_db.rs
runtime/src/ancient_append_vecs.rs

This will be put in 1 dead code piece at a time with tests until all pieces are present.
Introduce a few functions and structs used to pack ancient storages.
Fixes #

AncientSlotInfos, piece of packed ancient storage

---

core/src/banking_stage.rs
core/src/banking_stage/packet_receiver.rs

deserializer and id never change
Pull in state to PacketReceiver
Fixes #

BankingStage Refactor: Add state to PacketReceiver

---

runtime/src/accounts_db.rs
runtime/src/ancient_append_vecs.rs

see #30119
remove some arcs, remove a stale comment
Fixes #

minor cleanup on tests

---

docs/src/developing/intro/rent.md
docs/src/developing/lookup-tables.md
docs/src/developing/test-validator.md
docs/src/proposals/ledger-replication-to-implement.md
docs/src/running-validator/vote-accounts.md

Fix: typos

---

gossip/src/duplicate_shred_handler.rs

There are at most 3 entries with keys 0, 1, 2. A hashmap has unnecessary overhead to store these entries.
Switched to array.

uses array instead of HashMap in duplicate shreds ProofChunkMap

---

runtime/src/ancient_append_vecs.rs

Add `choose_storages_to_shrink` and helper method and tests.
Fixes #

ancient choose_storages_to_shrink

---

programs/bpf_loader/src/lib.rs

`use_jit` flag in `BpfExecutor` is redundant and if handled incorrectly might diverge from the existence of a compiled program inside the executable. Also, removing the flag makes `BpfExecutor` a simple wrapper around `VerifiedExecutable` which could potentially be removed.
Uses `verified_executable.get_executable().get_compiled_program().is_some()` instead.

Refactor - Remove redundant `use_jit` flag from `BpfExecutor`

---

runtime/src/ancient_append_vecs.rs

introduce `PackedAncientStorageTuning` and `filter_ancient_slots`
Fixes #

add ancient filter_ancient_slots

---

runtime/src/ancient_append_vecs.rs

Using `NonZeroU64` instead of u64 to avoid `.max(1)`
Fixes #

NonZeroU64 for ideal_storage_size

---

core/src/completed_data_sets_service.rs

With so many elements, it is good to have documentation for top level modules.
Just a short description.

doc: ledger: Document `completed_data_sets_service` module

---

net/net.sh

Add some documentation to client-type option added to net.sh

add client-type cli option documentation

---

runtime/src/ancient_append_vecs.rs

add `ancient collect_sort_filter_info`
Fixes #

add `ancient collect_sort_filter_info`

---

runtime/src/accounts_db.rs

Dropped roots are currently held in `Vec<Slot>`. Soon, dropped roots are held in a `HashSet<Slot>`. We can iterate both and that's all `handle_dropped_roots_for_ancient` does anyway.
Convert `handle_dropped_roots_for_ancient` to take …

handle_dropped_roots_for_ancient takes iter

---

runtime/src/accounts_db.rs

Useful to have debug on structs.
Add `Debug` impl.
Fixes #

add Debug to some structs

---

sdk/bpf/scripts/install.sh
sdk/cargo-build-sbf/src/main.rs
sdk/sbf/scripts/install.sh

This version of sbf-tools includes a debugger for on-chain programs.

Bump sbf-tools version

---

runtime/src/cost_model.rs

The version number stated in a comment is wrong
correct it
Fixes #

correct a comment with right info

---

runtime/src/accounts_db.rs

`AliveAccounts` hold everything alive FROM a slot.
It is useful to have the struct hold is slot so we have everything we need to combine storages and move accounts across slots. This can prevent bus that could occur trying to match up data …

AliveAccounts includes source slot

---

gossip/src/duplicate_shred.rs
gossip/src/duplicate_shred_handler.rs

Duplicate-shreds handler is using a nested hash-map for the incomplete chunks buffered. This is resulting in a convoluted logic to limit the number of entries:
https://github.com/solana-labs/solana/blob/427bd6264/gossip/src/duplicate_shred_handler.rs#L62
This commit instead uses a flat buffer mapping `(Slot, Pubkey)` pairs to the respective duplicate shreds chunks. The buffer is allowed to grow to twice the intended capacity, at which point the extraneous entries are removed, resulting an amortized O(1) performance.

flattens the internal buffer in the duplicate-shreds handler

---

core/src/banking_stage.rs
core/src/leader_slot_banking_stage_timing_metrics.rs
poh/src/poh_recorder.rs

Function seems to belong to the existing `TransactionRecorder` rather than `BankingStage`.
Move it to `TransactionRecorder` as part of BankingStage refactor efforts in TransactionScheduler project.
Blocked by #30093 
Fixes #

BankingStage Refactor: transaction recorder record transactions

---

runtime/src/accounts_db.rs

When adding test accounts to storages, it is useful to be able to make the accounts alive in the index, too.
test fn append_single_account_with_default_hash can add to index
Fixes #

test fn append_single_account_with_default_hash can add to index

---

runtime/src/accounts_db.rs
runtime/src/ancient_append_vecs.rs

fix tests to be more realistic
allocate correctly sized append vecs
Fixes #

change ancient tests to correct size

---

runtime/src/ancient_append_vecs.rs

build broken due to pr conflicts
Fixes #

add test parameters to fix build

---

sdk/src/feature_set.rs

Feature issue number of `prevent_rent_paying_rent_recipients` is mysterious
Fill in correct number

Fill in feature issue number in feature_set

---

runtime/src/ancient_append_vecs.rs

After collecting accounts from all potential ancient slots to combine, we need to be able to write the accounts with many ref counts to new shrunk storages at their same slot.
add `write_ancient_accounts_multiple_refs` to write the accounts …

add ancient write_ancient_accounts_multiple_refs

---

bench-tps/src/main.rs
cli/src/program.rs
client/src/connection_cache.rs
client/src/nonblocking/tpu_client.rs
client/src/thin_client.rs
client/src/tpu_client.rs
rpc-test/tests/rpc.rs

There is essentially duplicate code in client/thin_client and thin-client/thin_client.
Make client/thin_client  a thin wrapper and forward calls to the thin-client/thin_client
Fixes #

Refactor thin client

---

gossip/src/duplicate_shred_handler.rs

Duplicate shreds handler calls to blockstore for almost every duplicate-shred received.
In order to reduce number of calls to blockstore, the commit upserts local self.consumed cache with blockstore.

caches blockstore duplicate shreds slots

---

validator/src/bootstrap.rs

Some magic numbers floating around `bootstrap.rs`
Add constants for blacklist purging threshold and wait for newer snapshot threshold + updated comments

Replace magic numbers and update comments

---

client/src/connection_cache.rs
client/src/thin_client.rs

duplicate macro definitions
consolidated all `dispatch` macros into one.

consolidates quic/udp dispatch macros

---

sdk/program/src/message/versions/mod.rs

To prevent social attacks by which the signer is tricked into signing a transaction, the runtime **MUST NOT** accept signed off-chain messages as transactions under any circumstances. The first byte of the [signing domain specifier](#signing-domain-specifier) is chosen such that it corresponds to a value (`0xff`) which is implicitly illegal as the first byte in a transaction `MessageHeader` today. The property is implicit because the top bit in the first byte of a `MessageHeader` being set signals a versioned transaction, but only a value of zero is supported at this time. The runtime needs to be modified to reserve 127 as an illegal version number, making this property explicit.
Deserialization of VersionedMessage
Fixes #

Prevent runtime from using messages with version 127

---

runtime/src/ancient_append_vecs.rs

break out pieces of higher level algorithm for easier testing and readability.
add `write_packed_storages`
Fixes #

add ancient write_packed_storages

---

core/src/qos_service.rs
runtime/src/cost_tracker.rs

There will be multiple spot where CostTrackerError need to be converted into TransactionError.
Implement From trait to reduce code duplication.
Fixes #

implement From trait for CostTrackerError to TransactionError

---

docs/src/proposals/off-chain-message-signing.md

We don't have a specification for signing off-chain messages, so teams keep rolling their own custom protocol that are various types of dangerous
Propose a specification for off-chain message signing
cc/ #21366

Proposal for off-chain message signing

---

poh/src/poh_recorder.rs

Incorrect name on one of the measure! calls.
Swap in measure_us! (& remove names)
Fixes #

use measure_us, remove incorrect name

---

entry/src/entry.rs

`start_verify_transactions` is relatively long and contains both a small part of the CPU verification and the full GPU verification code.  As CPU and GPU verification are equal peers, it seems easier to follow the code when they each live in separate functions.
No functional changes.  Only moving code around.

entry: Split `start_verify_transactions` into `*_{cpu,gpu}`

---

runtime/src/accounts_hash.rs

some stuff is slightly incorrect or useless
Fixes #

misc. cleanup

---

gossip/src/crds_gossip.rs
gossip/src/duplicate_shred.rs
gossip/src/duplicate_shred_listener.rs

Unused code in gossip/duplicate_shred.rs
Removed it.

removes unused code from duplicate-shreds

---

gossip/src/crds.rs

Local-timestamp used in current gossip eviction code:
https://github.com/solana-labs/solana/blob/a36e1b211/gossip/src/crds.rs#L469-L511
does not indicate how old the entry is but how recently it was received.
The commit instead uses origin's wallclock to identify old values. In order to avoid cases where the wallclock on the entry is bogus, it is capped by local-timestamp.

evicts old gossip entries by origin's wallclock

---

ledger/src/shred/merkle.rs
ledger/src/shredder.rs

Need to separate domains for Merkle shreds hashes.
Added hash domains.

adds hash domain to merkle shreds

---

docs/src/terminology.md
docs/src/validator/tvu.md

* add entries for `tpu` and `tvu` in the terminology page
* add a brief description to the `tvu` page

TPU and TVU docs changes

---

core/src/banking_stage/consumer.rs

Nothing really, just cleaning some stuff up to be a bit nicer before #30288
Just some minor clean ups in `Consumer` before I pull state into the struct.
Changes separated by commit:
- some measure! to measure_us
- consistent naming of the `TransactionRecorder` that's passed around
- Remove an outdated comment
- re-use a local variable that was declared
Blocked by #30238
Fixes #

BankingStage Refactor: Simplify Consumer

---

core/src/serve_repair.rs
ledger-tool/src/main.rs

Uninlined format args are now a clippy lint, blocking #29947
Inline format args

Inline format args

---

core/src/banking_stage/consumer.rs

Bunch of naked `.saturating_add` when we can use this macro
Use `saturating_add_assign!` where appropriate.
Use saturating add in an accumulate where it should have been previously.
Fixes #

Clean up: consumer saturating add assign

---

gossip/src/cluster_info.rs
program-runtime/src/loaded_programs.rs

CI checks fail due to clippy errors: https://buildkite.com/solana-labs/solana/builds/90572#018660c8-0fab-467a-9711-eff432ae1830
Cosmetic changes to peacify clippy

Make clippy to be happy

---

test-validator/src/lib.rs

While implementing upgradeable-loader support for TestValidator, I came upon a couple nits.
Pick nits:
- remove comment that seems to be leftover from a previous method definition
- #29880 but for TestValidator

TestValidator nits

---

genesis/src/main.rs

The program help text in `solana-genesis` cli is inconsistent with `solana-test-validator` (partly my fault in #29994)
Fixup
Sorry to add to the pile, @joncinque . I wasn't sure who to ask for review on this tiny change, and you were to mind because of the TestValidator stuff 😅

solana-genesis help nit: bpf->sbf

---

install/solana-install-init.sh

Update documentation to reflect changes in solana-installer

---

ci/localnet-sanity.sh
docs/src/cluster/bench-tps.md
multinode-demo/bootstrap-validator.sh
multinode-demo/validator.sh

#30157
Add `--allow-private-addr` to `bootstrap-validator.sh` default args.
Fixes #30157

Add --allow-private-addr to bootstrap-validator.sh

---

runtime/src/in_mem_accounts_index.rs

Working on reducing disk footprint of disk index.
Soon, in-mem and disk index account info will be different generic type.
pass `is_empty` directly instead of passing a slice to call `is_empty()`
Fixes #

simplify remove_if_slot_list_empty_value

---

runtime/src/accounts_file.rs

Replace the use of `append_vec::*` in accounts_file.rs

Fix the dependency of accounts_file.rs

---

SECURITY.md

Another legacy address to update

Update security email address

---

core/src/repair_generic_traversal.rs

`get_closest_completion` does not check `processed_slots` when following parent slots.
- Only insert slots into `processed_slots` when calling `generate_repairs_for_slot`.
- use separate HashSet for slot tracking during closeness calculation
- skip already processed slots before generating repairs
Fixes #

prevent revisiting slots in get_closest_completion

---

runtime/src/account_storage.rs

Reducing what gets stored in disk index.
Remove magic numbers in test to make test more clear as it changes later.
Fixes #

remove magic numbers in test

---

runtime/src/account_storage.rs

Working on improving performance of disk accounts index.
Once we remove the append vec id from every disk index entry, we have to do things differently.
Rearrange the order of storing the old and new shrinking storage.
Fixes #

rearrange how shrink_in_progress_map is populated

---

runtime/src/accounts_db.rs

There is now only 1 append vec per slot.
We are working towards getting rid of append vec id in the accounts index.
Change some clean function tracking to use slot instead of append vec id. They are equivalent.
Fixes #

use slot with store id in some clean paths

---

bucket_map/src/bucket.rs
core/src/cluster_nodes.rs
ledger/src/blockstore_db.rs
runtime/src/bucket_map_holder.rs
runtime/src/stake_account.rs

drop default from PhantomData::default()

---

runtime/src/accounts_db.rs

There is only 1 append vec per slot (except while shrinking).
`AccountsDb`.`dirty_stores` used `(Slot, AppendVecId)` as a key. It only needs `Slot`
Remove `AppendVecId` from key of `AccountsDb`.`dirty_stores`
Fixes #

dirty_stores key is slot and not AppendVecId

---

runtime/src/bank.rs
runtime/src/bank_creation_freezing_progress.rs

Encapsulate `BankCreationFreezingProgress`, add waitable condvar, and add tests.
Fixes #

improve BankCreationFreezingProgress and add tests

---

docs/src/wallet-guide/hardware-wallets/ledger.md

Fix typo in ledger.md

---

SECURITY.md

SECURITY.txt suggests pinging admins on discord, which is a good way to get banned
suggest pinging the `Solana Labs` role instead

security.txt - pinging admins is a good way to get banned

---

install/src/config.rs

We have merged #30535. I think maybe we could have a test for it in case we break it in the future.
add a test for loading the config which made by serde_yaml v0.8

test: add test_load_serde_yaml_v_0_8_config

---

ledger-tool/src/main.rs

The print command looks up program_ids from transactions by creating SanitizedTransactions. But, print doesn't have access to a Bank so transactions that include an address table lookup can't be sanitized. 
Sanitizing the transaction isn't necessary, so this change just looks up the program id from unsanitized transactions.
This addresses one of the issues called out in https://github.com/solana-labs/solana/issues/30531
Running this on a slot that previously presented `Failed to analyze unsupported transaction` warnings, I no longer see those warnings.

ledger-tool: Avoid creating SanitizedTransaction in print command

---

core/src/accounts_hash_verifier.rs

The AHV loop could be simpler to read by using `let-else`, like what is done in SnapshotPackageManager.
https://github.com/solana-labs/solana/blob/db94e4564fefdf37d35362d42bfd9e3ade36261b/core/src/snapshot_packager_service.rs#L81-L88
Use `let-else`.

AHV loop uses let-else

---

core/src/accounts_hash_verifier.rs

For Incremental Accounts Hash, incremental snapshots will need to include info from the full snapshot they were based on in order to populate `BankIncrementalSnapshotPersistence`. Unfortunately that information is not saved anywhere to use when needed.
Add a `last_full_snapshot` variable in the AccountsHashVerifier loop that is updated every time a full snapshot package is processed.
Since full snapshots are always handled *before* incremental snapshots, we are guaranteed that `last_full_snapshot` will be update-to-date whenever a incremental snapshot package is handled.
Note 1: This guarantee will be asserted in a future PR once incremental snapshots write `BankIncrementalSnapshotPersistence`
Note 2: A subsequent PR will need to pipe in the information from any *initial* full snapshot …

AccountsHashVerifier remembers last full snapshot info

---

program-runtime/src/loaded_programs.rs

Need to add eviction strategy to new loaded programs cache.
Evicts least used programs by usage counter.
Fixes #

Add Executor Cache Eviction Strategy

---

ci/do-audit.sh

remove_dir_all security audit failure
Add audit exception
Fixes #

 Add audit exception for 1.13

---

docs/src/api/methods/_getAccountInfo.mdx
docs/src/api/methods/_getMultipleAccounts.mdx
docs/src/api/methods/_getProgramAccounts.mdx
docs/src/api/methods/_getTokenAccountsByDelegate.mdx
docs/src/api/methods/_getTokenAccountsByOwner.mdx

One of these is wrong (the one attached to `getAccountInfo`) and the rest could use clarification.
Before:
After:

[docs] Fix `dataSlice` definition

---

validator/src/cli.rs

See #30557 . `solana-test-validator` can deadlock when using minimum `--ticks-per-slot` and `--slots-per-epoch` values because if we skip slots, we won't generate the leader schedule for the next epoch in time because we haven't rooted a slot in the current epoch.
Require minimum of 2 ticks per slot

Require minimum of 2 ticks per slot for test val

---

core/benches/banking_stage.rs
core/src/banking_stage.rs
core/src/banking_stage/consumer.rs

`test_fn` is not a good design and was carried around for a single test, which no longer uses it.
Remove `test_fn` entirely
Blocked by #30615 
Fixes #

remove test fn

---

Cargo.lock
Cargo.toml
programs/bpf_loader/src/allocator_bump.rs
programs/bpf_loader/src/lib.rs
programs/bpf_loader/src/syscalls/cpi.rs
programs/bpf_loader/src/syscalls/mod.rs
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
programs/sbf/benches/bpf_loader.rs
programs/sbf/tests/programs.rs
rbpf-cli/src/main.rs

[solana_rbpf v0.2.40](https://github.com/solana-labs/rbpf/releases/tag/v0.2.40) has been released.

 Bump solana_rbpf to v0.2.40

---

runtime/src/block_cost_limits.rs

Link to monitor the solana cluster doesnt work
Dashboard to see cluster data not working
I link to some other solana mev+ monitoring dashboard as a temporary fix 
Fixes #

Link needs updating

---

runtime/src/accounts_index.rs

when populating the memory index, we are failing to identify duplicate pubkeys. The result is incorrect stats and a different initial set of pubkeys and slots to clean.
Now that 1.14 enables memory index by default, it is important to be consistent and correct.
Identify duplicate pubkeys correctly.
Fixes #

mem idx tracks duplicates better

---

core/src/verified_vote_packets.rs

`test_verified_vote_packets_validator_gossip_votes_iterator_correct_fork` is currently hard coded to 2 validators in some spots but uses a local variable to define the number of validators in other spots.
Use `num_validators` to control number of validators to expect (and asserts) through the test.

`test_verified_vote_packets_validator_gossip_votes_iterator_correct_fork` dynamic num validators

---

ledger/src/blockstore.rs

#30684 accidentally introduced a temporary debug change
revert it

revert unintional debug change introduced by d373e87

---

ledger/src/builtins.rs
program-runtime/src/invoke_context.rs
program-test/src/lib.rs
programs/bpf_loader/src/deprecated.rs
programs/bpf_loader/src/lib.rs
programs/bpf_loader/src/upgradeable.rs
programs/bpf_loader/src/upgradeable_with_jit.rs
programs/bpf_loader/src/with_jit.rs
programs/sbf/benches/bpf_loader.rs
programs/sbf/tests/programs.rs
runtime/benches/bank.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/builtins.rs
runtime/src/message_processor.rs
sdk/src/builtins.rs

#30639 conflicts with changes @Lichtso is working on. We opted to a different approach #30702 to consume builtin units. 
- This reverts #30692 ( commit 7b95c8e698e12ec8d2c96d3c75186a089fbe2da5. )
Fixes #

Revert "add default_cost as mandatory field for Builtin (#30639)"

---

core/src/packet_hasher.rs
core/src/shred_fetch_stage.rs
core/src/validator.rs
perf/src/deduper.rs

shred-fetch-stage deduper has small capacity and memory/reset-cycle.
Increased capacity and memory/reset-cycle.

increases shred-fetch-stage deduper capacity and reset-cycle

---

ledger-tool/src/main.rs

#30352 broke master, crossing with #30755.  Changes in ledger-tool look spurious, so reverting them.

Revert ledger-tool changes, fix master

---

ledger/src/blockstore_processor.rs

No functional changes.  Use early return pattern, to reduce indentation in the most important part of the confirmation logic.

ledger: confirm_slot_entries(): Refactor: reduce indent

---

core/benches/banking_stage.rs
core/src/banking_stage.rs
core/src/banking_stage/consumer.rs
poh/src/poh_recorder.rs

https://github.com/solana-labs/solana/pull/30395#discussion_r1142050562
Rename fn from `recorder` to `new_recorder` for clarity.
Fixes #

PohRecorder::recorder -> new_recorder

---

core/src/broadcast_stage/standard_broadcast_run.rs

Nodes broadcast shreds over the shred limit.
Panic the node when this happens since the node has forked off. (backport of #30555)
Fixes #

Panic when shred index exceeds the max per slot (v1.13)

---

.buildkite/hooks/pre-command
ci/platform-tools-info.sh
ci/test-stable.sh
docs/src/developing/on-chain-programs/debugging.md
programs/sbf/build.rs
sdk/cargo-build-sbf/src/main.rs
sdk/cargo-build-sbf/tests/crates.rs
sdk/cargo-test-bpf/src/main.rs
sdk/sbf/.gitignore
sdk/sbf/c/sbf.mk
sdk/sbf/env.sh
sdk/sbf/scripts/dump.sh
sdk/sbf/scripts/install.sh
sdk/sbf/scripts/objcopy.sh
sdk/sbf/scripts/strip.sh

SBF is damned.
Renamed sbf-tools to platform-tools and updated all references to sbf-tools to the new name.
Fixes #30566 partially

Update references to platform-tools

---

core/src/serve_repair.rs

There are no metrics to determine whether shred data for repair requests have been found in blockstore.
Add metric to track unsuccessful blockstore queries from repair requests.
Fixes #

add metric for repair request blockstore misses

---

core/src/verified_vote_packets.rs

Stakes are already paired when vote-account keys are collected.
Removed hash-map lookups when sorting vote-account keys.

removes hash-map lookups when sorting vote-account keys

---

poh/src/poh_recorder.rs

Manual implementation equivalent to derive.
use `#[derive(Clone)]`
Fixes #

derive clone for TransactionRecorder

---

core/src/serve_repair.rs

Too many `if ... else ...` branches.
Simplified the code using iterator constructs.

simplifies ServeRepair::run_orphan

---

core/src/cluster_nodes.rs

Current metrics by "number" of nodes does not indicate how much of stake is dead/stale.
Added metrics by stake.

reports cluster-nodes metrics by stake

---

validator/src/bootstrap.rs

Duplicate code to shutdown the gossip service spun up during RPC bootstrap process.
Make a gossip shutdown function that is called in both places

Abstract RPC bootstrap gossip exit into function

---

ledger-tool/src/main.rs

Performing a manual ledger compaction can be very time consuming. Although the compaction will optimize storage use, swapping to skip compaction favors the command completing faster. Additionally, we no longer do regular compaction in the validator (via LedgerCleanupService) and instead make use of range deletion which is much more efficient.
Given the above, this changes alters the default behavior to skip ledger compaction by default, and introduces a flag should a user really want to run compaction.

ledger-tool: Skip compaction in purge command by default

---

metrics/README.md
metrics/metrics-main/grafana.sh
metrics/metrics-main/kapacitor.sh
metrics/metrics-main/start.sh

fix grafana configuration

---

runtime/src/snapshot_utils.rs

fix typo in info log

---

streamer/src/nonblocking/quic.rs

Hard to read nested code.
Simplified code

simplifies streamer::nonblocking::quic::get_connection_stake

---

docs/src/proposals/bankless-leader.md

Added the link to simd so it shows up on the solana website if anyone looking to contribute.

Linking the simd

---

.buildkite/hooks/post-command

they have flaky tests detection atm. would like to give it a shot again.
reactivate it!

chore: reactivate buildkite test analytics

---

validator/src/bootstrap.rs

We currently have a `RwLock` on `blacklisted_rpc_nodes` because there is one area w/ parallel iterators that can write `blacklisted_rpc_nodes`.
- Create a local `newly_blacklisted_rpc_nodes` with a lock for the parallel iterators to insert into and then extend `blacklisted_rpc_nodes` with these entries.
- Remove lock from `blacklisted_rpc_nodes`

Minimize lock on blacklist nodes

---

bucket_map/src/bucket.rs
bucket_map/src/index_entry.rs

Soon, index entries may not contain `MultipleSlots` data.
Move `num_slots()` methods to `MultipleSlots`.
Fixes #

disk index: move num_slots() to MultipleSlots

---

metrics/metrics-main/alertmanager.sh
metrics/metrics-main/status.sh

refactor metrics container status check code

refactor container status check

---

.buildkite/hooks/post-checkout

Update the post-checkout to exclude all the metrics servers

fix condition to exclude the metrics servers

---

bucket_map/src/bucket_map.rs
bucket_map/src/index_entry.rs

improve disk bucket test that uses refcounts for clarity and better testing coverage
Fixes #

fix up refcounts on disk bucket test

---

gossip/src/crds_value.rs

See https://github.com/solana-labs/solana/pull/30895#discussion_r1153938471 from: #30895
Amend comment
Fixes #

ammend clarifying comment for duplicate instance detection

---

rbpf-cli/src/main.rs

RBPF CLI generates execution traces one per a program invocation. If a program invokes another program via CPI call the called program execution is recorded in a separate trace. A whole stack of traces is recorded. When requested to dump execution trace, rbpf-cli outputs only the last trace.
Output every trace from a recorded collection of traces.

Output all trace frames instead of last one from rbpf-cli

---

programs/sbf/tests/programs.rs
sdk/bpf/scripts/install.sh
sdk/cargo-build-sbf/src/main.rs
sdk/sbf/scripts/install.sh

Upgrade platform tools to Rust 1.68.0

Bump platform-tools version to v1.37

---

core/src/ancestor_hashes_service.rs
core/src/duplicate_repair_status.rs

Rename DeadSlotAncestorRequestStatus -> AncestorRequestStatus

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/bank_forks.rs

- typo
- refactor squash timing report
Fixes #

Refactor squash timing report

---

metrics/metrics-internal/chronograf_8888_internal.sh
metrics/metrics-internal/chronograf_8889_internal.sh
metrics/metrics-internal/grafana_internal.sh
metrics/metrics-internal/start.sh
metrics/metrics-main/chronograf.sh
metrics/metrics-main/chronograf_8889.sh
metrics/metrics-main/start.sh

Fix chronograf session timeout

fix session timeout

---

docs/sidebars.js
docs/src/developing/guides/compressed-nfts.md
docs/src/learn/state-compression.md

Docs do not include info on State Compression and/or compressed NFTs.
- added doc for State compression
- added guide for compressed NFTs
- updated the sidebar to link to these new docs

[docs] state compression and compressed nfts

---

runtime/src/accounts_db.rs

ancient append vecs were not enabled by default due to the bug this pr fixes.
We got Some(None) and that should have turned into the default value of Some(-10_000).
Instead, we got None, which disables ancient append vecs.
Correctly handle the nested Options.
Fixes #

fix cli arg for ancient append vecs

---

core/src/banking_stage/thread_aware_account_locks.rs

I missed to spot one edge-case overflow bug at https://github.com/solana-labs/solana/pull/30422 while reviewing.
Fix it along with really tiny nits.
Fixes #

Avoid overflow in ThreadSet::any() and nits

---

validator/src/bootstrap.rs

We currently don't have any insight into how long snapshot download is taking
Add metrics to understand snapshot download time
Example of these metrics collected on MNB:

Add snapshot download metrics

---

runtime/src/bank.rs

- extract new epoch processing out of new_bank
(a refactor to prepare the epoch reward v2 work)
Fixes #

Extract new_epoch processing out of new_bank

---

bucket_map/src/bucket.rs
bucket_map/src/bucket_map.rs

Add more tests for #31133
Fixes #

disk index: add more tests

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json

- Install the official docusaurus plugin for google analytics.
- added GA tracking code to the docs config
Notes:
- GA will only be active in production, to not pollute analytics while in dev mode (per the [plugins official docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag))
- the GA tracking code is not secret, and is safe to be published

[docs] added google analytics to docs

---

quic-client/src/nonblocking/quic_client.rs

* `RwLock<Option<...>>` adds unnecessary overhead for lazy initialization.
* `OnceCell` instead provides the right api for lazy initialization.
Use `OnceCell` instead.

uses OnceCell for lazy endpoint initialization in quic-client

---

runtime/src/bank.rs

break up of https://github.com/solana-labs/solana/pull/31143
break up reward payout code into separate fns so that it can be used for
reward calculation and reward distribution separately .
(prepare for epoch v2 works)
Also, this change fixes a potential subtle bug. When stake cache is inconsistent with accounts_db, loading stake_history from the cache, before actual loading vote/stake accounts from accounts db (which will pruning invalid cache keys), can lead to invalid stake/vote accounts to participate into later rewarding code. This is incorrect. With this change, stake_history are loaded correctly after pruning invalid cache keys.
Part 1: type alias
Fixes #

Refactor reward payout code - part 1

---

SECURITY.md

Too many speculative or undeveloped vulnerability submissions.
Require PoC for consideration

SECURITY.md: Require exploit PoC for submission consideration

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

break up of #31143
break up reward payout code into separate fns so that it can be used for
reward calculation and reward distribution separately .
(prepare for epoch v2 works)
Part 2: extract load_vote_stake_accounts fn
Fixes #

Refactor reward payout code - part 2

---

ledger-tool/src/main.rs

#31150
Move final hash calc to cli arg.
Fixes #

ledger-tool verify cli for final hash calc

---

runtime/src/bank.rs

break up of #31143
break up reward payout code into separate fns so that it can be used for
reward calculation and reward distribution separately .
(prepare for epoch v2 works)
Part 3: extract calculate points fn 
Fixes #

Refactor reward payout code - part 3

---

runtime/src/bank.rs

break up of #31143
break up reward payout code into separate fns so that it can be used for
reward calculation and reward distribution separately .
(prepare for epoch v2 works)
Part 4: extract redeem_reward fn
Fixes #

Refactor reward payout code - part 4

---

core/src/snapshot_packager_service/snapshot_gossip_manager.rs

In a previous PR, I had added a github comment about some of the code. It was requested to put the comment into the code too. Original comment: https://github.com/solana-labs/solana/pull/31154#discussion_r1164248681.
Add the comment.

Add comment in SolanaGossipMananger::update_latest_full_snapshot_hash()

---

ledger/src/blockstore_processor.rs

`blockstore_processor::process_blockstore_from_root()` starts with a BankForks that contains exactly one Bank. The function grabs an Arc of this initial Bank, and does some logging and initial setup before processing more slots in `load_frozen_forks()`.
`process_blockstore_from_root()` holds that Arc until it returns. This increases the ref count and prevents the initial Bank from getting cleaned up in a timely manner if `load_frozen_forks()` prunes that initial Bank from BankForks.
This change extracts the needed information from the Arc<Bank>, and drops the Arc so that the Bank can be dropped in a timely manner.
I noticed this issue while digging into elevated memory usage by `solana-ledger-tool` across epoch boundaries (while trying to debug the same phenomenon with …

Prevent process_blockstore_from_root() from holding Bank for too long

---

metrics/metrics-main/alertmanager-discord.sh
metrics/metrics-main/alertmanager.sh
metrics/metrics-main/chronograf.sh
metrics/metrics-main/chronograf_8889.sh
metrics/metrics-main/grafana.sh
metrics/metrics-main/kapacitor.sh
metrics/metrics-main/prometheus.sh
metrics/metrics-main/prometheus.yml
metrics/metrics-main/start.sh

We need to increase docker containers memory allocation

increase docker mem allocation

---

docs/src/validator/blockstore.md

Some formatting is broken
Fixed formatting

fix docs blockstore formatting

---

ci/common/limit-threads.sh
ci/common/shared-functions.sh
ci/test-stable.sh
scripts/coverage-in-disk.sh
scripts/coverage.sh

some cleanup logic split from #31151 
- extract the thread limit feature into a single script, `ci/common/limit-threads.sh`
- extract common functions into `ci/common/shared-functions.sh`

ci: cleanup

---

runtime/src/ancient_append_vecs.rs

When packing ancient append vecs, writing the append vecs can take a long time and there can be many of them.
Packing these ancient append vecs runs in accounts background service, and can block cache flushing, clean, and shrink.
Parallelize the write to the ancient append vecs, using account_db's `clean` thread pool.
Fixes #

packed ancient: parallel write to append vecs

---

runtime/src/ancient_append_vecs.rs

packing ancient append vecs requires collecting accounts from many append vecs.
Collect the accounts in parallel.
Later, we will also take advantage of the side effect of unref'ing pubkeys in `shrink_collect` by unref'ing all pubkeys first. Then, we will discover that some pubkeys now have only 1 ref when they had > 1 when `shrink_collect` was run. This lets us find more slots to combine. So, the ordering of calling `shrink_collect` on all slots first, then checking for `many_refs` will be necessary.
Fixes #

packed ancient: shrink_collect accounts in parallel

---

runtime/src/ancient_append_vecs.rs

packed ancient append vecs are failing to addref when a packing operation fails.
add_ref each previously unref'd account when a packing operation fails.
Fixes #

packed ancient: addref when pack operation fails

---

metrics/influx-enterprise/status.sh

Add influx meta and data nodes

add influx servers

---

runtime/src/ancient_append_vecs.rs

Packed ancient append vecs need to scan accounts with > 1 refs in 2 passes.
Accounts with ref_count=1 can be packed into any slot. Accounts with ref_count > 1 cannot move slots.
After unref'ing all all dead accounts while packing ancient storages, revisit the accounts with > 1 ref to see if any of them have now been unref'd to only 1 ref count now. Note that there should be very few accounts with > 1 ref.
Fixes #

packed ancient: add revisit_accounts_with_many_refs

---

runtime/src/ancient_append_vecs.rs

pack ancient: add test for addref_accounts_failed_to_shrink_ancient

---

runtime/src/append_vec.rs

more precise lifetimes are helpful for these 2 fns.
Add appropriate lifetimes.
@yhchiang-sol needs this for his tiered storage work.
Fixes #

add lifetimes to refs in ReadableAccount

---

Cargo.lock
programs/sbf/Cargo.lock

h2 v0.3.17 was yanked
Bump to newer patch

Bump h2 to 0.3.18

---

sdk/src/feature_set.rs

Forgot to include issue # for zan's change [31264](https://github.com/solana-labs/solana/pull/30831)
Fixes #

Link issue for vote state latency feature gate

---

accounts-cluster-bench/src/main.rs
core/src/broadcast_stage.rs
core/src/broadcast_stage/broadcast_duplicates_run.rs
core/src/broadcast_stage/broadcast_fake_shreds_run.rs
core/src/cluster_nodes.rs
core/src/next_leader.rs
core/src/result.rs
core/src/serve_repair.rs
core/src/warm_quic_cache_service.rs
dos/src/main.rs
gossip/src/cluster_info.rs
gossip/src/contact_info.rs
gossip/src/crds.rs
gossip/src/crds_gossip.rs
gossip/src/crds_gossip_pull.rs
gossip/src/crds_gossip_push.rs
gossip/src/gossip_service.rs
gossip/src/legacy_contact_info.rs
gossip/src/main.rs
gossip/tests/crds_gossip.rs
gossip/tests/gossip.rs
local-cluster/tests/common.rs
rpc/src/cluster_tpu_info.rs
rpc/src/rpc.rs
streamer/src/socket.rs
transaction-dos/src/main.rs
validator/src/bootstrap.rs

Working towards `LegacyContactInfo` => `ContactInfo` migration.
The commit makes sockets in `LegacyContactInfo` private and expands API parity with the new `ContactInfo`.

makes sockets in LegacyContactInfo private

---

runtime/src/ancient_append_vecs.rs

When packing ancient append vecs, we have to leave account with ref_count > 1 in their same slot.
If the ONLY accounts in an append vec are alive and ref_count > 1, then the append vec cannot be rewritten any more compactly, so leave it alone.
This situation occurs when the offset is set (via cli) to a positive number. We end up with many 'ancient' slots which are small append vecs, where the algorithm attempts to combine them. But, since all accounts are ref_count>1 and alive, the end result of each of these append vecs is the same as the current state. So, nothing to be done.
Fixes #

ancient packing: leave same append vecs alone

---

runtime/src/ancient_append_vecs.rs

hook up `random` data point for packed ancient append vecs
Fixes #

packed ancient: report random stat

---

ci/nits.sh

ever procrastinate me made a promise
fulfill the promise per https://github.com/solana-labs/solana/pull/30843#issuecomment-1480399497
Fixes #

ci: suggest to use hidden_unless_forced()

---

ci/docker-run.sh
ci/test-checks.sh

(no rush; no need to work on weekend like me)
for much-anticipated sccache/rust toolchain updates!
follow-up: #30652

ci: show sccache version and prefix

---

.buildkite/hooks/post-checkout
.buildkite/hooks/post-checkout.sh
.buildkite/hooks/post-command
.buildkite/hooks/post-command.sh
.buildkite/hooks/pre-command
.buildkite/hooks/pre-command.sh
ci/shellcheck.sh

- remove unnecessary files
- unify the header

ci: update buildkite's hook

---

program-runtime/src/invoke_context.rs

In some use cases it's necessary to create InvokeContext with specific builtin programs.
Overload with_mock_invoke_context macro to accept an extra argument that passes a custom builtin programs when an instance of InvokeContext is created.

Overload with_mock_invoke_context with custom BuiltinPrograms option

---

ledger-tool/src/args.rs
ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/utils.rs

ledger-tool main.rs has overgrown. Some of its functions can be reused by other commands.
This PR factors out several functions from main.rs to a separate module for reuse in run command added in #31346

Refactor ledger-tool moving some of functions to a separate module

---

runtime/src/accounts_db.rs
runtime/src/accounts_hash.rs

these metric are unused
remove them
Fixes #

remove unused metrics

---

ci/buildkite-solana-private.sh

assign wrong agents to private pipeline

ci: fix private pipeline agents

---

program-runtime/src/invoke_context.rs

Traces of nested invocations are currently discarded when syscall context is popped off. Need to collect these traces in a separate field of InvokeContext for recovering at the end of a program execution.
Add a new field to collect execution traces data and a method to access this field.

Save nested traces on syscall context pop in InvokeContext

---

runtime/src/snapshot_utils.rs

Within the contents of snapshot_utils::add_bank_snapshot(), metrics were being reported in several datapoints and counters. This adds extra overhead, and makes it harder to correlate fields that correspond to the same snapshot.
So, combine the counters and multiple datapoints into a single datapoint.

Combine multiple snapshot_utils metrics

---

runtime/src/bank.rs

As we work on adding a new feature around rewards calc and distribution, this code needs to be fully understood. In the future, others will need to read this code.
replace tuple with named members for clarity.
Fixes #

replace tuple with `VoteReward` struct

---

metrics/influx-enterprise/status.sh

fix influx status check, the current loop check is broken

fix influx status check

---

metrics/influx-enterprise/status.sh

Add ssh connection check to the influx enterprise status script and some retry logic

add ssh connection check

---

core/src/leader_slot_banking_stage_metrics.rs
runtime/src/transaction_error_metrics.rs

remove unnecessary struct initialization
Fixes #

remove unnecessary-struct-initialization

---

runtime/src/bank.rs

Counters can only report a single field; this adds an extra step to debugging efforts to figure out the context for where/why the counted event occurred.
Use datapoints instead to submit some extra context.

Replace inc_new_counter_* with datapoint_* in Bank

---

metrics/influx-enterprise/status.sh
metrics/metrics-main/prometheus.yml

Remove inactive hosts from monitoring

remove inactive hosts

---

ci/check-crates.sh
scripts/reserve-cratesio-package-name.sh

publishing dummy packages on crates.io to reserve new names is kinda a pita
* add a script to do it
* suggest using the script in ci error text

add and recommend script for reserving new package names on crates.io

---

core/src/next_leader.rs
core/src/replay_stage.rs
core/src/tvu.rs
core/src/voting_service.rs
runtime/src/bank.rs

Feature already activated on all cluster.
Removed feature gate code.

removes feature gate code sending votes to tpu-vote-port

---

runtime/src/accounts_db.rs

the original impl for reporting clean status of the oldest slot was originally connected to the last hash calculation slot. This is an unnecessary coupling.
Use the min dirty slot, independent of ancient append vecs. This work is required to break the coupling that exists between the last hash calc and ancient append vec packing.
Fixes #

clean stats for ancient aren't based off last hash calc slot

---

metrics/metrics-main/prometheus.yml

Add the new canaries to the metrics config

Add canaries to metrics config

---

ledger-tool/src/main.rs
ledger-tool/src/program.rs

run sub-command of ledger-tool is deemed too generic.
Rename and reorganize the ledger-tool run sub-command to program and multiple sub-sub-commands.

Reorganize ledger-tool run sub-command

---

Cargo.lock
core/src/ancestor_hashes_service.rs
core/src/cluster_slot_state_verifier.rs
core/src/duplicate_repair_status.rs
core/src/heaviest_subtree_fork_choice.rs
core/src/repair_service.rs
core/src/repair_weight.rs
core/src/replay_stage.rs
core/src/serve_repair.rs
core/src/tvu.rs
core/src/window_service.rs
ledger/src/blockstore.rs
local-cluster/Cargo.toml
local-cluster/tests/common.rs
local-cluster/tests/local_cluster_slow_2.rs
runtime/src/epoch_stakes.rs

Add ancestor hashes to state machine

---

ci/docker-rust/Dockerfile

installed lld to docker images

ci: install lld to docker images

---

core/benches/retransmit_stage.rs
core/src/broadcast_stage.rs
core/src/broadcast_stage/broadcast_duplicates_run.rs
core/src/cluster_nodes.rs
dos/src/main.rs
gossip/src/cluster_info.rs
gossip/src/contact_info.rs
gossip/src/legacy_contact_info.rs
gossip/tests/gossip.rs
validator/src/admin_rpc_service.rs
validator/src/bootstrap.rs

Working towards migrating turbine to QUIC.
Added QUIC tvu port to contact-info.

adds quic tvu port to contact-info

---

core/benches/consumer.rs
core/src/banking_stage/consumer.rs

Record is actually failing since the signal receiver is out of scope.
Keep `signal_receiver` in scope.
Fixes #

Keep signal_receiver in scope

---

core/src/qos_service.rs

Follow up on https://github.com/solana-labs/solana/pull/31542#discussion_r1188125023
Remove unused debug
Fixes #

Remove unused debug

---

runtime/src/accounts_db.rs

`is_ancient` alters behavior for several accounts_db algorithms.
These functions are thinking about ancient append vecs that are meant to be appended to. With packed ancient append vecs, writes are one-shot and the resulting ancient append vecs are not identifiable, apart from their slot #. So, the functions that ask `is_ancient` will be modified over time.
`get_ancient_slots` is used to separate out how storages are scanned for hash calculation. Any separation is legal. This is about performance of which ones to group together. Under normal operations, there should be no ancient append vecs at the moment. Later, when rewrites are eliminated, there will be ancient append vecs. In that case, those should be treated differently based solely on their slot being old.
Fixes #

`get_ancient_slots` returns slots based on slot as opposed to contents

---

send-transaction-service/src/send_transaction_service.rs

Found this randomly. But, we don't need to clone these since we already have the owned Arcs.
Don't clone them
Fixes #

Remove unneccessary Arc clones

---

bucket_map/src/bucket.rs

disk index was reworked to basically never use a data bucket file, in order to improve performance.
But, we were still allocating a default data bucket file. This is unnecessary and can be allocated on first actual necessary use.
Avoid the initial data bucket file allocation.
Fixes #

avoid unnecessary disk bucket data file allocation

---

runtime/src/accounts_db.rs
runtime/src/storable_accounts.rs

partitioned rewards interval will require a new `StorableAccounts` impl.
Create the new impl and add tests.
Fixes #

add StorableAccount impl for account value

---

core/src/packet_deserializer.rs

We use `bank_forks` here to get the working bank, not root.
Update the comment to be accurate to implementation.
Fixes #

Comment Fix: provides working bank

---

runtime/src/serde_snapshot/newer.rs

write EpochRewardStatus to snapshot if it is not default `Inactive`.
For now, we will always write as though the status is `Inactive`. This lets us verify the abi hash hasn't changed in the normal persistence of a snapshot.
Later, we will populate this based on the bank's `epoch_reward_status`. However, that field will ALWAYS be `Inactive` until the feature is activated for partitioned rewards. This approach allows us to leave snapshot persistence UNCHANGED unless `epoch_reward_status` is `Active`. This means we can easily test this feature on clusters without having to backport the change that reads_eof the `epoch_reward_status` field.
If another field needs to be added to the end of the persistence, then this field will have to always be persisted along with the new hypothetical field. …

working towards persistence for EpochRewardStatus

---

core/src/banking_stage/consumer.rs

A test for cost tracking should be setup with a feature gate both T/F status.
- update test
Fixes #

update test for both feature gate status

---

streamer/src/nonblocking/quic.rs

Intermittent test failure with test_quic_server_block_multiple_connections -- the open_uni can fail before writing to the stream due to connection limiting. 
Failure stack:
--- STDERR:              solana-streamer quic::test::test_quic_server_block_multiple_connections ---
--
thread 'quic::test::test_quic_server_block_multiple_connections' panicked at 'called `Result::unwrap()` on an `Err` value: ApplicationClosed(ApplicationClose { error_code: 4, reason: b"too_many" })', streamer/src/nonblocking/quic.rs:1235:45
stack backtrace:
0: rust_begin_unwind
at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
1: core::panicking::panic_fmt
at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
2: core::result::unwrap_failed
at …

Expect errors when opening 2nd stream due to connection limit

---

rbpf-cli/src/main.rs

As requested in https://github.com/solana-labs/solana/pull/31584/files#r1190775199

rbpf-cli: fix deprecation notice

---

scripts/cargo-install-all.sh

See https://github.com/hyperledger/solang/releases/tag/v0.3.0

Update Solang Solidity compiler to v0.3.0

---

runtime/src/accounts.rs

Cleanup - instructions_sysvar_owned_by_sysvar

---

runtime/src/account_rent_state.rs
runtime/src/accounts.rs
runtime/src/bank/transaction_account_state_info.rs

Cleanup - include_account_index_in_rent_error

---

programs/vote/src/vote_processor.rs
programs/vote/src/vote_state/mod.rs

Cleanup - vote_withdraw_authority_may_change_authorized_voter

---

runtime/src/bank.rs
runtime/src/serde_snapshot/tests.rs

Cleanup - disable_fee_calculator

---

programs/vote/src/vote_processor.rs
programs/vote/src/vote_state/mod.rs

Cleanup - reject_vote_account_close_unless_zero_credit_epoch

---

docs/src/implemented-proposals/tower-bft.md

Consensus docs are outdated
Update to latest consensus spec
Fixes #

Update consensus docs

---

runtime/src/accounts_file.rs
runtime/src/tiered_storage.rs
runtime/src/tiered_storage/error.rs
runtime/src/tiered_storage/footer.rs

This PR adds a new error type for the tiered storage.

Add new error type -- TieredStorageError

---

runtime/src/accounts_db.rs

AccountsHasher create temporary accounts hash cache files that currently live in the same full and incremental accounts hash cache directory. This may not be the best. In theory these files should be cleaned up, but it's possible they stick around longer than necessary, esp. if there's a crash and restart doesn't remove those files. Instead, it would be cleaner to have a separate directory entirely for these temporary files.
Create a new directory for the temporary accounts hash cache files.

Moves transient accounts hash cache files into their own dir

---

runtime/src/bank.rs

reformat comments for consistency
Fixes #

reformat comments

---

runtime/src/bank.rs

impl debug is helpful, especially for composing larger structs.
Fixes #

add debug to VoteReward

---

programs/bpf_loader/src/syscalls/mod.rs

Cleanup - limit_secp256k1_recovery_id

---

programs/vote/src/vote_processor.rs

Cleanup - vote_authorize_with_seed

---

ledger-tool/src/args.rs
ledger-tool/src/main.rs
runtime/src/accounts_db.rs
runtime/src/partitioned_rewards.rs
validator/src/cli.rs
validator/src/main.rs

Use config for partitioned rewards, and add cli args.
Fixes #

add cli args and use of partitioned rewards config

---

metrics/src/metrics.rs

A slowdown within counters is that we take a mutex lock every time we submit a counter (or datapoint) to the agent. These calls only send across a channel, which does not require us to do any exclusive locking.
Remove the lock.
Fixes #

remove lock from metrics agent singleton

---

.buildkite/scripts/build-bench.sh
.buildkite/scripts/build-bench.test.sh
ci/bench/common.sh
ci/bench/part1.sh
ci/bench/part2.sh
ci/buildkite-pipeline.sh
ci/buildkite-solana-private.sh

separate bench tests into two ~10 mins tests

ci: separate bench tests

---

zk-token-sdk/src/encryption/auth_encryption.rs
zk-token-sdk/src/encryption/elgamal.rs

The functions `{ElGamalKeypair, ElGamalSecretKey, AeKey}::new_from_signer(signer: &Signer, tag: &[u8]) -> Result<...>` uses the variable name `tag`. However, the variable `tag` is used more like a seed to derive the encryption keys rather than a "short" tag message that usually acts as domain seperator. This variable can be better named.
Since "seed" usually implies private bytes to derive cryptographic seed, rename the variable to `public_seed`.
This is a follow up to the discussion https://github.com/solana-labs/solana/pull/31811#discussion_r1205687767.
Fixes #

[zk-token-sdk] Rename variable `tag` to `public_seed` in encryption key `new_from_signer` functions

---

streamer/src/nonblocking/quic.rs

Still see the flaky test even though much more rarely:
https://buildkite.com/organizations/solana-labs/analytics/suites/solana-1/tests/213938430/executions/23446762246
Put the test code in the else condition to ensure the condition is checked.
Fixes #

Flkay quic test in check_block_multiple_connections

---

runtime/src/tiered_storage/byte_block.rs

Add doc comments for byte_block.rs
This is a comment-only PR.  No code change.

[TieredStorage] Add doc comments for byte_block.rs

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

Bump version to v1.16.1

---

ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/program.rs

This function has morphed as it has been updated, and the existing function name is a bit of misnomer. 
Update the function name to use terminology that I think is more clear and more consistent with what we use core/src/validator.rs. Additionally, adjust the error messages to be more clear about what exactly is wrong for when we can't process.

ledger-tool: Rename load_frozen_forks() and adjust error messages

---

runtime/src/accounts_db.rs

accounts_db: demote spammy log message

---

metrics/metrics-main/prometheus.yml

Add stackpath development servers

Add stackpath development servers

---

runtime/src/tiered_storage/byte_block.rs

This PR adds raw_len() to ByteBlockWriter which returns
the length of the data after decoding.  This information is needed
for the cold storage to keep track of the current size of the account
block after decompression.
Improved existing tests to verify the returned raw_len().
Tested in mnb w/ the prototype implementation of the tiered storage (https://github.com/solana-labs/solana/pull/30626)

[TieredStorage] Add raw_len() to ByteBlockWriter

---

core/src/qos_service.rs

"tramsaction"
transaction
Fixes #

Fix typo: process_and_record_tramsaction -> process_and_record_transaction

---

banks-server/src/banks_server.rs
core/src/banking_stage/consumer.rs
core/src/read_write_account_set.rs
entry/benches/entry_sigverify.rs
entry/src/entry.rs
ledger-tool/src/main.rs
ledger/src/blockstore.rs
rpc/src/rpc.rs
rpc/src/transaction_status_service.rs
runtime/src/bank.rs
runtime/src/cost_tracker.rs
sdk/program/src/message/versions/mod.rs
sdk/program/src/message/versions/sanitized.rs
sdk/program/src/message/versions/v0/mod.rs
sdk/src/transaction/sanitized.rs
sdk/src/transaction/versioned/mod.rs
transaction-status/src/lib.rs

Cleanup - require_static_program_ids_in_transaction

---

runtime/src/accounts.rs
runtime/src/bank.rs

add `RewardInterval::InsideInterval` and impl. This will be used shortly.
Fixes #

add RewardInterval::InsideInterval

---

core/src/repair_generic_traversal.rs

typo.
Additionaly -> Additionally

Fix typo in repair_generic_traversal.rs

---

runtime/src/ancient_append_vecs.rs

tests were tuned incorrectly so we weren't packing what some tests were intending. Also, sweeping through several extra append vecs tests better.
sweep through several # normal storages.
Fixes #

improve packed ancient test by sweeping

---

runtime/src/bank/tests.rs
runtime/src/cost_model.rs

tests for CostModel belong in cost_model
move it
Fixes #

move cost model tests

---

programs/stake/src/stake_instruction.rs

[StakeInstruction::DeactivateDelinquent](https://github.com/solana-labs/solana/issues/24302) is now enabled on all clusters, remove featurization.

Remove StakeInstruction::DeactivateDelinquent featurization

---

runtime/tests/stake.rs

Since rewards will not be credited until some slots after next epoch, stake tests need to be able to wait for a bank a few slots after an epoch boundary. Currently, no waiting is required.
Fixes #

 stake tests modification: next_epoch_and_n_slots

---

metrics/metrics-main/kapacitor.conf
metrics/metrics-main/kapacitor.sh
metrics/metrics-main/start.sh

- add 3 pager duty channels + canaries channel to httppost
- use the same kapacitor script to start

ci: update kapacitor config

---

metrics/metrics-main/kapacitor.sh
metrics/metrics-main/start.sh
metrics/metrics-main/status.sh

don't cd to the script's folder.

ci: update metrics related deploying code

---

metrics/metrics-main/start.sh

sorry. I think I missed some of them 😢

fix: update metrics deploy script

---

runtime/src/serde_snapshot/tests.rs

add tests for snapshot epoch reward fields
Fixes #

snapshot epoch reward fields tests

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

factor out get_epoch_reward_calculate_param_info to share results.
The results will be needed shortly in a subsequent call.
Fixes #

factor out get_epoch_reward_calculate_param_info to share results

---

bucket_map/src/bucket.rs

apparently this compiler warning is inconsistent.
Fix code to remove unnecessary mut.
Fixes #

remove compiler warning

---

runtime/src/bank.rs

Add compare_with_partitioned_rewards_results for testing partitioned rewards.
This code will only run from tests or when a debug cli argument is passed to a validator prior to feature activation of partitioned rewards feature.
Fixes #

add compare_with_partitioned_rewards_results for testing partitioned rewards

---

runtime/src/bank.rs

fix build error by removing duplicate struct definition
Fixes #

remove build error from merge

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/epoch_rewards_hasher.rs

add partitioned rewards helpers
Fixes #

add partitioned rewards helpers

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

add `calculate_validator_rewards`
Fixes #

add calculate_validator_rewards

---

programs/vote/src/vote_state/mod.rs

Cleanup - filter_votes_outside_slot_hashes

---

docs/src/developing/runtime-facilities/sysvars.md
sdk/program/src/epoch_rewards.rs
sdk/program/src/lib.rs
sdk/program/src/program_stubs.rs
sdk/program/src/syscalls/definitions.rs
sdk/program/src/sysvar/epoch_rewards.rs
sdk/program/src/sysvar/mod.rs

Add epoch_reward sysvar
Fixes #

Add epoch_reward sysvar

---

runtime/src/bank.rs

add `calculate_rewards_and_distribute_vote_rewards`
Fixes #

add calculate_rewards_and_distribute_vote_rewards

---

runtime/src/bank.rs

Prepare a testing fn which help us test the activation and use of the activated partitioned rewards feature.
Add `force_reward_interval_end_for_tests()`
Fixes #

partitioned rewards fn for tests: force_reward_interval_end_for_tests

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

Implementing solana-foundation/solana-improvement-documents#15 (comment) in pieces.
depends on 
https://github.com/solana-labs/solana/pull/32051
Fixes #

add test for is_partitioned_rewards_feature_enabled

---

core/benches/cluster_nodes.rs
core/src/cluster_nodes.rs
core/src/retransmit_stage.rs
gossip/src/cluster_info.rs

Feature activated on all clusters.
Removed feature-gate code.

removes feature gate code dropping redundant turbine path

---

programs/vote/src/vote_processor.rs

Missing tests for this instruction type
Fixes #32224

vote_processor: Add tests for CompactVoteStateUpdate

---

ci/docker-rust/Dockerfile

#32169 is getting some positive feedback and we need to install `cargo hack` in preparation of it: https://github.com/solana-labs/solana/pull/32169/files#r1237437440
Install in advance.

Install cargo-hack for upcoming dev-utils

---

core/src/cluster_slot_state_verifier.rs

We sometimes use `Some(Hash::default())` and clunky `is_dead` flag to represent dead slots.
Unify and use the `BankStatus` enum everywhere.
Additionally while refactoring removed some spurious uses of `MarkSlotDuplicate` on slots that are dead (no-ops)
Fixes #31451

Use bank status instead of default hash in state machine

---

account-decoder/src/parse_sysvar.rs
programs/bpf_loader/src/syscalls/mod.rs
programs/bpf_loader/src/syscalls/sysvar.rs
programs/sbf/rust/sysvar/src/lib.rs
programs/sbf/rust/sysvar/tests/lib.rs

Implementing solana-foundation/solana-improvement-documents#15 (comment) in pieces.
depends on 
https://github.com/solana-labs/solana/pull/32155
Add epoch_rewards syscalls
Fixes #

Add epoch_rewards syscalls

---

ledger/src/blockstore.rs

Missing comments and unit test
Add doc comments and unit test

Add comments and unit test for Blockstore::scan_and_fix_roots()

---

runtime/src/tiered_storage/meta.rs

This PR adds several functions to AccountMetaOptionalFields
for obtaining the offset of each optional field.
New unit test cases are included in this PR.

[TieredAccountStorage] functions for obtaining optional fields offsets

---

runtime/src/bank/tests.rs

Add test for partition out of range
Fixes #

Add test for partition out of range

---

ledger-tool/src/ledger_utils.rs

The previous help message was pretty generic as it covered two potential error scenarios. 
This change gives a more detailed error message to each of those errors.
I tested this out with some manual ledger-tool runs to ensure that the error catching still works as before, but with new messages displayed for each case (missing blockstore and missing column)

ledger-tool: Adjust the help messages for force-update-to-open

---

runtime/src/bank/tests.rs

Add test for partitioned epoch rewards store
Fixes #

Add test for partitioned epoch rewards store

---

runtime/src/bank/tests.rs

Test partitioned reward history update from rewards slice
Fixes #

test partitioned reward history update from rewards slice

---

turbine/src/broadcast_stage/standard_broadcast_run.rs

Starting mainnet Merkle shreds rollout.
The commit rolls out Merkle shreds to ~5% of mainnet slots.

rolls out merkle shreds to ~5% of mainnet slots

---

runtime/src/bank/tests.rs

Test `EpochRewards` sysvar creation, distribution, and burning.
Fixes #

Test `EpochRewards` sysvar creation, distribution, and burning.

---

docs/src/proposals/simple-payment-and-state-verification.md

concatentation -> concatenation
Fixes #

Fix typo in simple-payment-and-state-verification.md

---

core/src/repair/serve_repair.rs
entry/src/entry.rs
gossip/src/cluster_info.rs
perf/src/packet.rs
streamer/src/streamer.rs

redundant clones
removed redundant recycler clones.

removes redundant recycler clones

---

runtime/src/bank/tests.rs

Test rewards compuation and partitioned rewards distribution at the epoch boundary
Fixes #

Test rewards compuation and partitioned rewards distribution at the epoch boundary

---

ledger-tool/src/ledger_utils.rs

Found typo while reviewing #32400.
Fix it. "stroage" to "storage"
Fixes #

Fix typo: "stroage" to "storage"

---

core/src/repair/ancestor_hashes_service.rs
core/src/repair/duplicate_repair_status.rs
core/src/repair/repair_service.rs
core/src/replay_stage.rs
local-cluster/tests/local_cluster.rs

Ancestor hashes service is a bit inefficient, after finding the mismatched ancestor also sends its descendants to replay for dump and repair. 
Building off of the fix in #31559 , we can just send the problematic ancestor, and replay will dump any descendants that are confirmed duplicate.
Fixes #31313

Only send earliest mismatched ancestor to replay

---

runtime/src/bank/tests.rs

test stake program execution restricted in reward period
Fixes #

Test stake program execution restricted in reward period

---

ledger/src/blockstore.rs

Test was flaky, full explanation at https://github.com/solana-labs/solana/issues/32391#issuecomment-1629265675
Given that timing of execution is relevant for this test, adjust one of the parameters to allow a little buffer to avoid flaky results.
Fixes #32391

Fix flaky find_missing_data_indexes_timeout() test

---

runtime/src/accounts.rs
runtime/src/accounts_db.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/epoch_rewards_hasher.rs

Remove unnecessary dead_code attr since all the feature code has been checked in.
build on top of https://github.com/solana-labs/solana/pull/32415
Fixes #

Remove unnecessary dead_code attributes

---

ci/downstream-projects/func-spl.sh

ci: fix spl test

---

core/src/validator.rs

As part of another review within `/core/src/validator.rs`, some minor items that could be better were pointed out.
- Use .map_err() instead of match and return
- Adjust log severity and add context to generic "done" logs

Minor cleanup in Validator::new()

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml

https://github.com/solana-labs/solana/pull/32488/files#r1263251288

Really remove ntapi patching except spl-token-cli's one

---

ci/docker-run.sh
ci/test-coverage.sh

Add --fail to curl for more robust retries

---

ledger/src/blockstore.rs

Add doc comments and simplify logic inside the function.
Was reading this function while trying to figure out https://github.com/solana-labs/solana/issues/32391, so figured I would add the comments and simplifying logic while I was already in there

Cleanup Blockstore::find_missing_indexes()

---

runtime/src/bank.rs

Convoluted nested code.
Simplified the code using iterator constructs.

simplifies update_stakes_cache implementation

---

program-runtime/src/compute_budget.rs

* Remove inappropriate use of usize.

Remove inappropriate use of usize. Refactor upcast.

---

runtime/src/transaction_priority_details.rs

Transaction without priority details will be dropped by priority queue (at `immutable_deserialized_packet::new()`), yet transaction_priority_details is hardcoded not to support deprecated ix. Combined, it results TX with deprecated compute budget ix will be dropped by leader. 
1. Add test case for transaction with deprecated ix;
2. change implementation to support above two scenarios.
Fixes #32549

Priority queue supports deprecated compute budget ix 

---

turbine/src/broadcast_stage/standard_broadcast_run.rs

Ramping up Merkle shreds on mainnet.
Roll out Merkle shreds to ~20% of mainnet slots.

rolls out merkle shreds to ~20% of mainnet slots

---

.buildkite/hooks/post-command

we don't use these data atm.
stop upload them.

v1.16: ci: don't upload test result

---

.buildkite/hooks/post-command

ci: fix post-command logic

---

.buildkite/hooks/post-command

we don't use these data atm.
stop upload them.

v1.14: ci: don't upload test result

---

runtime/src/bank.rs
runtime/src/bank/metrics.rs

Add distributed rewards for the block in partitioned reward metrics
Fixes #

Add distributed rewards for the block in partitioned reward metrics

---

runtime/src/accounts_db.rs
runtime/src/bank.rs
runtime/src/bank/metrics.rs
runtime/src/bank/tests.rs
runtime/src/stake_account.rs
runtime/src/stakes.rs

Feature activated on all clusters.
Removed the feature-gate code.

removes feature-gate code for updating rewards from cached accounts

---

core/src/banking_stage/decision_maker.rs

current tests in decision_maker were not sufficient, and let a bug be introduced: see #32468 
Add some additional tests which test correct decision given slot offset until leader.
Fixes #

DecisionMaker: Add more tests

---

core/src/validator.rs

As `git blame` would show, some of this code is pretty old and could use a little polish.
- Make subfunctions return a Result and allow error handling above
- Add some clarifying comments
- Give backup directory name a more meaningful name
- Add some additional logs (with timing info) for long running parts

Cleanup backup_and_clear_blockstore()

---

runtime/src/bank.rs
runtime/src/stake_account.rs
runtime/src/stakes.rs

After calculating epoch boundary rewards, stake accounts are stored in a single thread due to lock contention on the stakes-cache, causing slower parallel code. This has now become the bottleneck of epoch boundary rewards calculation and takes the majority of computation time. 
The commit removes the lock contention on stakes-cache by adding api to refresh all stake delegations and vote accounts for all updated stake accounts at once so that stake accounts can be stored in parallel.

stores stake-accounts in parallel after epoch rewards calculations

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

No changes in this commit except the version bump:
```
$ gs
On branch version_bump_v1.16.7
Your branch is up to date with 'origin/version_bump_v1.16.7'.
nothing to commit, working tree clean
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.6|^\+( \")?solana.*1.16.7|^-version|^\+version"
$
```

Bump version to v1.16.7

---

core/src/banking_stage/qos_service.rs

An extra reporting thread is spawned for each QosService instance - which is 1 per banking stage thread. This leads to 6 threads which only do reporting.
- We currently send a `QosMetrics::BlockBatchUpdate { slot: Slot }` every batch to reporting thread via channel
- The separate thread was originally shared and introduced to clean up banking stage and report metrics on an **interval**.
- At later points we:
- changed these to report per slot which required input from banking threads
- changed metrics to not be shared between threads
We will use less threads and reduce code complexity by just making banking stage threads report these more directly.
Just check slot and report QosMetrics inline for banking stage.
Banking bench shows no significant difference in banking performance:
```
with …
```

QosService inline metrics reporting

---

turbine/src/cluster_nodes.rs

For as long as cache entries have not expired yet, a shared lock is enough and would avoid lock contention.
Use `RwLock` instead of `Mutex` for cache entries in `ClusterNodesCache`.

uses RwLock instead of Mutex for cache entries in ClusterNodesCache

---

turbine/src/quic_endpoint.rs

Frequently accessed remote addresses are cached, making a shared-lock sufficient which would reduce lock contention for the more common cache-hit lookups.
* Read-lock connection cache for lookups
* Write-lock now only happens in the less frequent cache-miss cases.

read-locks Turbine QUIC connection cache for lookups

---

runtime/src/accounts_db.rs
runtime/src/bank.rs

Audit of bank code identified a number of bank fns missing doc comments.
Add comments.
Fixes #

add some doc comments identified in audit

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ gs
On branch version_bump_v1.16.8
nothing to commit, working tree clean
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.7|^\+( \")?solana.*1.16.8|^-version|^\+version"
$
```

Bump version to v1.16.8

---

runtime/src/tiered_storage.rs

This PR makes TieredStorage implement Drop which does the remove-on-drop
behavior that follows the AccountsFile convention.

TieredStorage struct (4/N) -- remove_on_drop

---

Cargo.lock
Cargo.toml

Old crate.
Upgrades `serial_test` to 2.0.0.

upgrades serial_test to 2.0.0

---

docs/src/proposals/off-chain-message-signing.md

Fix typo in off-chain-message-signing.md

---

runtime/src/accounts_hash.rs

Recent refactoring made some stats no longer updated.
Remove orphan stats.
Fixes #

remove some stats that are no longer kept

---

rpc-client/src/rpc_client.rs

`get_account` will `Err` on missing account, however before a feature is activated its account will be missing. This causes problems with stake related cli commands as they use `get_feature_activation_epoch`.
Use `get_account_with_commitment` which returns `Ok(None)` for missing accounts instead.
Fixes #

rpc: get_feature_activation_slot should not error for inactive features

---

accounts-db/src/read_only_accounts_cache.rs

Extract performance statistics from read-only cache
Fixes #

Extract read-only cache stats

---

accounts-db/src/accounts_db.rs

code became dead at some point and can be removed
remove dead code
Fixes #

removed unused accounts hash code

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
a04a42bc46 2023-08-11 16:36:49 -0500  (HEAD -> version_bump_v1.16.9)  will.hickey@solana.com Bump version to v1.16.9
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.8|^\+( \")?solana.*1.16.9|^-version|^\+version"
$
```

Bump version to v1.16.9

---

accounts-db/src/accounts_cache.rs

fix a write cache size grow/shrink bug
Fixes #

Fix write cache size grow/shrink bug

---

.github/scripts/downstream-project-spl-common.sh
.github/scripts/purge-ubuntu-runner.sh
.github/workflows/downstream-project-spl-nightly.yml
.github/workflows/downstream-project-spl.yml
ci/downstream-projects/func-spl.sh

re-enable SPL downstream project test on Github Action!

ci: re-enable SPL downstream project test on Github Action

---

programs/stake/src/stake_state.rs

feature `clean_up_delegation_errors` has been activated on mainnet-beta as of epoch 490
remove the feature gating logic
Fixes #31206

remove clean_up_delegation_errors feature

---

gossip/src/cluster_info.rs

`set_serve_repair` instead of `set_serve_repair_quic`.
fixed.

patches set_serve_repair instead of set_serve_repair_quic

---

accounts-db/src/accounts_db.rs

Code is inside loop.
Move it out.
Fixes #

move invariant code outside loop

---

accounts-db/src/cache_hash_data.rs

working on reducing memory usage during accounts hash scanning.
Refactor accounts hash file to soon use mmap files open when used.
Fixes #

refactor cache hash data files

---

accounts-db/src/read_only_accounts_cache.rs

refactoring going on here for performance
fix some easy stuff
Fixes #

minor cleanup to read only accounts cache

---

accounts-db/src/cache_hash_data.rs

working on reducing memory usage during accounts hash scanning.
Refactor accounts hash file to soon use mmap files open only when used.
Fixes #

move `map` to `CacheHashDataFileReference`

---

accounts-db/src/cache_hash_data.rs

remove unnecessary clone call
https://github.com/solana-labs/solana/pull/32877#discussion_r1298485290
Fixes #

remove clone()

---

cli-output/src/cli_output.rs
cli/src/vote.rs
programs/vote/benches/process_vote.rs
programs/vote/src/vote_state/mod.rs
rpc/src/rpc.rs
sdk/program/src/vote/state/mod.rs
sdk/src/feature_set.rs

Mentioned commit causes master to diverge from consensus; see https://github.com/solana-labs/solana/issues/32889
This reverts commit 35ec7bf804f363f9fdfb1b59794e1a108986e87f.

Revert "Implement timely vote credits feature (#31291)"

---

rpc/src/optimistically_confirmed_bank_tracker.rs

The previous implementation is a little tricky to follow, and repeats some functionality that is already implemented in
Bank::parents_inclusive(). 
So, swap in parents_inclusive() for parents() and add a comment to explain looking up the last slot.
This PR spun out of comment in https://github.com/solana-labs/solana/pull/32802, I'll aim to land this PR first and then rebase that PR on top of this one

Simplify get_parent_chains() test function

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
4662bc8780 2023-08-18 16:12:40 -0500  (HEAD -> version_bump_v1.16.10, origin/version_bump_v1.16.10)  will.hickey@solana.com Bump version to v1.16.10
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.9|^\+( \")?solana.*1.16.10|^-version|^\+version"
$
```

Bump version to v1.16.10

---

quic-client/src/nonblocking/quic_client.rs

As mentioned in issue #32792, the quic client swallows any error that's returned during `send_data`.
Surface the error properly!
Fixes #32792

quic-client: Return error when `send_data` fails

---

bucket_map/src/bucket_api.rs

Working on fast restart with index files on disk.
Refactor bucket creation function.
Fixes #

disk bucket: factor out allocate_bucket

---

ci/do-audit.sh

#32933
ignore RUSTSEC-2023-0052 atm 😢

v1.16: ci: ignore RUSTSEC-2023-0052

---

ci/do-audit.sh

https://github.com/solana-labs/solana/issues/32933
ignore RUSTSEC-2023-0052

v1.14: ci: ignore RUSTSEC-2023-0052

---

scripts/cargo-install-all.sh

See https://github.com/hyperledger/solang/releases/tag/v0.3.2

Update Solang Solidity compiler to v0.3.2

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
glol -1
6c183d4f61 2023-08-25 23:17:21 -0500  (HEAD -> version_bump_v1.16.11)  will.hickey@solana.com Bump version to v1.16.11
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.10|^\+( \")?solana.*1.16.11|^-version|^\+version"
$
```

Bump version to v1.16.11

---

Cargo.lock
programs/sbf/Cargo.lock

#32996 broke the master's sanity test.
`./scripts/cargo-for-all-lock-files.sh tree`  and commit the changes

fix cargo lock

---

accounts-db/src/accounts_index.rs

some code was only called by tests
Move it out of non-test code.
Fixes #

move uncleaned roots code to test mod

---

core/src/repair/ancestor_hashes_service.rs
core/src/repair/repair_service.rs
core/src/repair/serve_repair.rs
core/src/repair/serve_repair_service.rs

Working towards migrating repair over QUIC protocol. 
The commit adds repair-protocol argument for identifying right serve-repair socket.

adds repair-protocol identifying serve-repair socket

---

sdk/src/feature_set.rs

Impl has changed significantly and we're now targeting 1.17
Feature Issue: #29708

feature_set: rekey direct_mapping

---

core/src/shred_fetch_stage.rs

- BankForks is not an optional argument, so remove dated comment
- Given that BankForks is always present, no need for special values to
initialize variables before the loop
- Root slot can be retrieved from root bank, no need for second call to
BankForks (which would load the underlying atomic a second time)
- Use BankForks::highest_slot() instead of .slot() on .working_bank() to
avoid the extra clone that .working_bank() performs
- Move several operations outside of BankForks read lock scope to
minimize lock time

Cleanup BankForks access code in ShredFetchStage

---

accounts-db/src/accounts_index.rs
accounts-db/src/in_mem_accounts_index.rs

This costs nothing, but puts the data in the same format necessary for downstream processing. At some point this will allow for a memcpy of the data instead of element by element copy.
reorder tuple members when batching up index insertion
Fixes #

reorder generate_index info

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
43e70ddbca 2023-08-30 23:24:28 -0500  (HEAD -> version_bump_v1.16.12, origin/version_bump_v1.16.12)  will.hickey@solana.com Bump version to v1.16.12
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.11|^\+( \")?solana.*1.16.12|^-version|^\+version"
$
```

Bump version to v1.16.12

---

turbine/src/sigverify_shreds.rs

Nested for loops and extra branches.
Simplified the code using iterator constructs.

simplifies sigverify_shreds::get_slot_leaders

---

gossip/src/cluster_info.rs
gossip/src/crds.rs
runtime/src/bank_forks.rs
runtime/src/vote_account.rs

manual `let ... else`:
https://rust-lang.github.io/rust-clippy/master/index.html#/manual_let_else
removed them.

removes manual let...else

---

.github/scripts/downstream-project-spl-install-deps.sh
.github/workflows/downstream-project-spl.yml

ci: add a common script for installing dependencies

---

turbine/src/broadcast_stage/standard_broadcast_run.rs

Ramping up Merkle shreds on mainnet.
Roll out Merkle shreds to 100% of mainnet slots.

rolls out merkle shreds to 100% of mainnet slots

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
ca118246e7 2023-09-01 17:51:10 -0500  (HEAD -> version_bump_v1.16.13, origin/version_bump_v1.16.13)  will.hickey@solana.com Bump version to v1.16.13
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.12|^\+( \")?solana.*1.16.13|^-version|^\+version"
$
```

Bump version to v1.16.13

---

sdk/program/src/bpf_loader_upgradeable.rs

Original PR: [32813](https://github.com/solana-labs/solana/pull/32813)

Fix a typo & phrasing of `bpf_loader_upgadeable` docs

---

programs/bpf_loader/src/lib.rs
programs/loader-v4/src/lib.rs

See https://github.com/solana-labs/solana/pull/33104#discussion_r1316015345.
Removes the redundant check and adds more error log messages.

Refactor - Minor fixes in the error handling of executing tombstones

---

core/src/banking_stage/decision_maker.rs

https://discord.com/channels/428295358100013066/439194979856809985/1148556473035665468
Test was flaky. We test the boundaries of each decision category. The test failed at the lower bound for `ForwardAndHold` decision, this is possible if the service ticked which would make the decision change to `Hold` instead.
Set exit and immediately drop the poh service.
Fixes #

Drop poh_service to avoid unwanted ticking

---

ci/docker-rust-nightly/Dockerfile
ci/test-coverage.sh

use codecov command line tool to upload coverage results.
close #33107

ci: use codecov command line tool

---

runtime/src/bank/tests.rs

Function does not have a pre-existing unit test

Add unit test for Bank::register_hard_fork()

---

runtime/src/bank.rs

inconsistent errors between 1.14 and 1.16
normalize them

Check lamports balance before and after tx execution

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

Bump version to v1.16.14

---

core/src/banking_stage/transaction_scheduler/transaction_state.rs

CI didn't actually run for a push in #33002.
State must be `&mut self` to modify it...
Fixes #

set_forwarded needs mut ref

---

accounts-db/src/accounts_hash.rs

refactoring going on with improving perf of accounts hash dedup
Fixes #

add a few accounts hash dedup tests

---

accounts-db/src/accounts_hash.rs

There are a bunch of items in `accounts_hash.rs` that are currently public but do not need to be.
Remove `pub`.

Removes `pub` from accounts_hash.rs items

---

core/src/repair/ancestor_hashes_service.rs
core/src/repair/quic_endpoint.rs
core/src/repair/repair_service.rs
core/src/repair/result.rs
core/src/repair/serve_repair.rs
core/src/shred_fetch_stage.rs
core/src/tvu.rs
core/src/validator.rs
core/src/window_service.rs

repair over QUIC protocol.
The commit implements client-side of serve-repair and ancestor-hash-service over QUIC protocol.

sends repair requests over QUIC protocol

---

accounts-db/src/cache_hash_data.rs

Replace `pub` with `pub crate`.
Fixes #

clean up pub crate

---

accounts-db/src/accounts_db.rs

add comments to a struct in generate index. We're about to refactor some of this for performance.
Fixes #

add comments

---

ci/stable/run-partition.sh

move solana-core to nextest for
1. faster testing
2. the test result

ci: move solana-core to nextest

---

accounts-db/src/accounts_db.rs

test logic could be cleaner & more resilient to change.
Fixes #

cleanup test

---

accounts-db/src/accounts.rs
cost-model/src/cost_model.rs
program-runtime/src/compute_budget.rs
programs/sbf/tests/programs.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/transaction_priority_details.rs

feature `Hr1nUA9b7NJ6eChS26o7Vi8gYYDDwWD3YeBfzJkTbU86 ` #30076 has been activated everywhere. 
cleanup feature code
Fixes #

cleanup feature: enable request heap frame instruction #30076

---

accounts-db/src/accounts_index.rs

https://github.com/solana-labs/solana/pull/33252#event-10401440885
- O(N) dedup
Fixes #

O(n) dedup

---

docs/src/developing/on-chain-programs/faq.md

add Solana stack exchange site - https://solana.stackexchange.com/

docs: add solana stack exchange site

---

bucket_map/src/bucket_storage.rs

We want to re-use index files on restart.
Refactoring of disk index to prepare for re-using disk bucket files on startup.
Fixes #

bucket storage refactoring

---

bucket_map/src/bucket_storage.rs

working on speeding up startup.
Prepare to load disk index files from previous run instead of always creating them from scratch.
Refactor
Fixes #

refactor bucket storage file open

---

docs/src/developing/guides/compressed-nfts.md

Update compressed-nfts.md  typo  single single token

---

bucket_map/src/bucket_storage.rs

speeding up startup.
Trying to reuse disk index files on restart.
Refactor header offset check.
Fixes #

refactor header alignment check in bucket storage

---

bucket_map/src/index_entry.rs

speeding up startup.
Trying to reuse disk index files on restart.
fix comments
Fixes #

fix comments

---

ci/test-local-cluster-flakey.sh
ci/test-local-cluster-slow-1.sh
ci/test-local-cluster-slow-2.sh
ci/test-local-cluster.sh
ci/test-stable.sh

I merged all local cluster tests into a single file in #31730 and it works well for 4 months. it's a good time to remove those unused code!
🔪

chore: remove unused code

---

ci/docker-rust/Dockerfile

ci: use new installation instructions for nodejs

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs
accounts-db/src/partitioned_rewards.rs
ci/docker-rust-nightly/Dockerfile
ci/docker-rust/Dockerfile
ci/rust-version.sh
ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs
local-cluster/tests/local_cluster.rs
rust-toolchain.toml
sdk/program/src/vote/state/vote_state_versions.rs

rust stable 1.72.0 is [apparently not always stable](https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html)
* bump rust stable to 1.72.1
* bump rust nightly to 2023-09-20
* fix new lints

bump rust stable to 1.72.1

---

ledger/src/blockstore_db.rs

The function was previously defined in a block that required the column implement `TypedColumn + ColumnName`. However, the column does not have to be `TypedColumn` to allow deletions. For example, we can perform deletes on `ProtobufColumn` columns with ease since a delete only requires the key.
So, move the implementation to a block where the column trait bounds are Column + ColumnName.
I need this change as part of another larger change, but decided to break this out separately.

Move LedgerColumn delete() implementation to less restrictive traits

---

bucket_map/src/bucket_storage.rs

speeding up startup.
Trying to reuse disk index files on restart.
Add `load_on_restart` to enable us to load and map a previous disk index file.
Fixes #

add bucket::load_on_restart

---

ci/do-audit.sh

https://github.com/quinn-rs/quinn/compare/0.8.3...0.9.x
ignore. 1.14 isn't long for this world

ignore RUSTSEC-2023-0063

---

runtime/src/bank.rs
sdk/src/feature_set.rs
sdk/src/transaction/error.rs
storage-proto/proto/transaction_by_addr.proto
storage-proto/src/convert.rs

v1.14 backport - better error codes for tx lamport check

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
0af0fd69f1 2023-09-21 15:13:30 -0500  (HEAD -> version_bump_v1.16.15)  will.hickey@solana.com Bump version to v1.16.15
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.14|^\+( \")?solana.*1.16.15|^-version|^\+version"
$
```

Bump version to v1.16.15

---

bucket_map/src/bucket.rs
bucket_map/src/bucket_api.rs

Minor cleanup prior to bigger code changes.
Fixes #

simple cleanup in bucket map

---

bucket_map/src/bucket.rs

Working towards reusing index files on startup.
remember whether a bucket was created re-using an existing file vs. blank.
Fixes #

diskidx: keep track if bucket file was reused so we can gen idx faster

---

bucket_map/src/bucket_map.rs

Speeding up startup.
Re-using index files on startup.
On restart, re-use previous index files if possible. The content data is still not being re-used, but at least we know the correct size so we don't have to resize and we don't have to zero out a file first.
This already saves about 3s.
Fixes #

disk idx: restart re-uses disk index files

---

ci/downstream-projects/func-spl.sh

single-pool path changed
change it here

fix single-pool path for ci

---

Cargo.lock
accounts-db/Cargo.toml
programs/sbf/Cargo.lock

I missed some unused deps in #33420 🤦‍♂️

chore(solana-accounts-db): remove unused deps

---

connection-cache/src/connection_cache.rs

Simplify code and use match to harden logic

Simplify code and use match to harden logic

---

Cargo.lock
sdk/cargo-build-bpf/Cargo.toml
sdk/cargo-test-bpf/Cargo.toml

chore(bpf): remove unused deps

---

ci/do-audit.sh

https://discord.com/channels/428295358100013066/560503042458517505/1157318202011959296
suppress it atm

v1.16: ci: fix audit

---

ci/do-audit.sh

https://discord.com/channels/428295358100013066/560503042458517505/1157318202011959296
suppress it atm

v1.14: ci: fix audit

---

accounts-db/src/accounts_hash.rs

Convert unamed tuple into DedupResult for clearer code. 
Also, avoid overallocation for the hash_files vector in `fold` operator. In each
folding group, the size of the hash_files vec won't reach MAX_BINs. all hash_files together will be MAX_MINs.
Worst case, we could be allocating 65K*65K, more than 3 billion elements in the vec.
Fixes #

Convert tuple into dedup result struct

---

sdk/program/src/instruction.rs

Typo fix in instruction.rs

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
dc3513d621 2023-09-30 10:51:15 -0500  (HEAD -> version_bump_v1.16.16, origin/version_bump_v1.16.16)  will.hickey@solana.com Bump version to v1.16.16
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.15|^\+( \")?solana.*1.16.16|^-version|^\+version"
$
```

Bump version to v1.16.16

---

core/src/snapshot_packager_service.rs
download-utils/src/lib.rs
rpc/src/rpc_service.rs
runtime/src/bank/serde_snapshot.rs
runtime/src/snapshot_bank_utils.rs

- Add test coverage for incremental snapshot redirect
- Switch snapshot compression type to Tar in unit tests
- Remove an incorrect comment about compression type on test-validator

Minor cleanup on some snapshot related tests

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
f52c7e40f6 2023-10-02 12:00:15 -0500  (HEAD -> version_bump_v1.17.1)  will.hickey@solana.com Update version to v1.17.1
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.0|^\+( \")?solana.*1.17.1|^-version|^\+version"
$
```

Update version to v1.17.1

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
997c3ec91b 2023-10-02 11:43:37 -0500  (HEAD -> version_update_v1.18)  will.hickey@solana.com Update version to v1.18.0
$ git diff master..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.0|^\+( \")?solana.*1.18.0|^-version|^\+version"
$
```

Update version to v1.18.0

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
c2f5af46cb 2023-10-06 16:46:27 -0500  (HEAD -> version_bump_v1.16.17)  will.hickey@solana.com Bump version to v1.16.17
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.16|^\+( \")?solana.*1.16.17|^-version|^\+version"
$
```

Bump version to v1.16.17

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
94ee74d2aa 2023-10-06 16:52:03 -0500  (HEAD -> version_bump_v1.17.2)  will.hickey@solana.com Update version to v1.17.2
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.1|^\+( \")?solana.*1.17.2|^-version|^\+version"
$
```

Update version to v1.17.2

---

CHANGELOG.md
CONTRIBUTING.md
SECURITY.md

There were some typing errors in the repository.
- exaustion -> exhaustion
- automically -> automatically
- Compatability -> Compatibility

Fixed typing errors

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
349d8a93ee 2023-10-20 16:38:07 -0500  (HEAD -> version_bump_v1.16.19, origin/version_bump_v1.16.19)  will.hickey@solana.com Update version to v1.16.19
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.18|^\+( \")?solana.*1.16.19|^-version|^\+version"
$
```

Update version to v1.16.19

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
e7e7817849 2023-10-20 16:40:55 -0500  (HEAD -> version_bump_v1.17.4, origin/version_bump_v1.17.4)  will.hickey@solana.com Update version to v1.17.4
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.3|^\+( \")?solana.*1.17.4|^-version|^\+version"
$
```

Update version to v1.17.4

---

docs/src/developing/versioned-transactions.md

Typo in the Versioned Transaction docs.
Fixed typo.

Fix typo in versioned-transactions.md

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
d548695f71 2023-10-30 19:07:47 -0500  (HEAD -> version_bump_v1.17.5, origin/version_bump_v1.17.5)  will.hickey@solana.com Update version to v1.17.5
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.4|^\+( \")?solana.*1.17.5|^-version|^\+version"
$
```

Update version to v1.17.5

---

core/src/replay_stage.rs

unused metrics
remove them
Fixes #

remove unused replay-loop-voting-stats values

---

sdk/src/feature_set.rs

rekey stake redelegate feature
Fixes #
Feature Gate Issue: https://github.com/solana-labs/solana/issues/26765

rekey stake redelegate feature

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
cdc0542bab 2023-11-12 09:58:51 -0600  (HEAD -> version_bump_v1.16.20, origin/version_bump_v1.16.20)  will.hickey@solana.com Bump version to v1.16.20
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.19|^\+( \")?solana.*1.16.20|^-version|^\+version"
$
```

Bump version to v1.16.20

---

accounts-db/src/tiered_storage/hot.rs

HotStorageReader currently not yet has an API to obtain account_address
This PR adds HotStorageReader::get_account_address() which returns
the Pubkey of the account associated with the specified IndexOffset.
Augmented an existing unit-test to cover get_account_address() case.

[TieredStorage] HotStorageReader::get_account_address

---

accounts-db/src/accounts.rs
accounts-db/src/transaction_results.rs
ledger-tool/src/program.rs
program-runtime/src/invoke_context.rs
program-runtime/src/message_processor.rs
programs/bpf_loader/src/lib.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

Cleanup - Feature gate of `delay_visibility_of_program_deployment`

---

accounts-db/src/tiered_storage/hot.rs

#34032 mentioned nice-to-have a formatting improvement that
can improve the readability. 
Improve the code formatting in test_hot_storage_get_account_offset_and_address().

Improve formatting in test_hot_storage_get_account_offset_and_address()

---

runtime/src/bank.rs

`bank::load_program()` function can be simplified. It's currently special handling the creation of tombstones in various error conditions, that could be unified.
Simplify the code.
Fixes #

Simplify code for bank::load_program()

---

programs/bpf_loader/src/syscalls/cpi.rs
programs/bpf_loader/src/syscalls/mod.rs

Cleanup - Feature gate of `disable_cpi_setting_executable_and_rent_epoch`

---

runtime/src/bank/fee_distribution.rs

correct english grammar.
Fixes #

grammar correction

---

.buildkite/scripts/build-bench.sh
ci/buildkite-pipeline.sh

a following PR for https://github.com/solana-labs/solana/pull/33815
run bench test in docker

ci: run bench test in docker

---

ci/buildkite-pipeline.sh
ci/buildkite-solana-private.sh

a following PR for https://github.com/solana-labs/solana/pull/33815
run doctest in docker

ci: run doctest in docker

---

runtime/src/bank/tests.rs

The variable name and actual test logic are inconsistent. 
Fix tests variable name and actual test logic.
Fixes #

Fix tests  for disabling rent collection

---

ledger/src/blockstore.rs

minimized snapshot creation introduced a regression bug at #33273 for handling of alt accounts.
basically, this functionality is broken for mainnet-bata due to almost ubiquitous use of alts.

Correctly store ALTs themselves into minimized snapshot

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
808068bfdc 2023-11-17 16:37:44 -0600  (HEAD -> version_bump_v1.16.21, origin/version_bump_v1.16.21)  will.hickey@solana.com Bump version to v1.16.21
$  git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.20|^\+( \")?solana.*1.16.21|^-version|^\+version"
$
```

Bump version to v1.16.21

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
7ab3250f46 2023-11-17 16:45:14 -0600  (HEAD -> version_bump_v1.17.7, origin/version_bump_v1.17.7)  will.hickey@solana.com Update version to v1.17.7
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.6|^\+( \")?solana.*1.17.7|^-version|^\+version"
$
```

Update version to v1.17.7

---

sdk/src/account.rs

The build is broken because of the merging error.
Fix merging error.
Fixes #

fix merge error

---

core/src/banking_stage/multi_iterator_scanner.rs

Fix typo in multi_iterator_scanner.rs

---

.mergify.yml

ci: fix mergify regex

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
145fbd32aa 2023-12-08 21:26:34 -0600  (HEAD -> version_bump_v1.16.23, origin/version_bump_v1.16.23)  will.hickey@solana.com Update version to v1.16.23
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.22|^\+( \")?solana.*1.16.23|^-version|^\+version"
$
```

Update version to v1.16.23

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
d60c61b690 2023-12-08 21:33:11 -0600  (HEAD -> version_bump_v1.17.9, origin/version_bump_v1.17.9)  will.hickey@solana.com Update version to v1.17.9
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.8|^\+( \")?solana.*1.17.9|^-version|^\+version"
$
```

Update version to v1.17.9

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
d71e1ccf8e 2023-12-10 11:47:19 -0600  (HEAD -> version_bump_v1.16.24, origin/version_bump_v1.16.24)  will.hickey@solana.com Update version to v1.16.24
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.23|^\+( \")?solana.*1.16.24|^-version|^\+version"
$
```

Update version to v1.16.24

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
9f64469e06 2023-12-10 11:58:33 -0600  (HEAD -> version_bump_v1.17.10, origin/version_bump_v1.17.10)  will.hickey@solana.com Update version to v1.17.10
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.9|^\+( \")?solana.*1.17.10|^-version|^\+version"
$
```

Update version to v1.17.10

---

cli/src/cli.rs
sdk/program/src/loader_v4.rs
sdk/src/signer/mod.rs

Browsing through the code I found some typos, thought might as well fix those while at it.
Seems like batching a bunch of these together into 1 PR is fitting (instead of creating 3 separate ones) ?

comments: fix typos

---

program-runtime/src/loaded_programs.rs

v1.16: Fix - Uses fetch_add() to accumulate usage counters in LoadedPrograms (backport of #34319)

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

- Run `./scripts/increment-cargo-version.sh patch`
- Manually undo the hashbrown update

V1.17.11 version bump

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
73319d8681 2023-12-15 21:13:38 -0600  (HEAD -> version_bump_v1.16.25, origin/version_bump_v1.16.25)  will.hickey@solana.com Update version to v1.16.25
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.24|^\+( \")?solana.*1.16.25|^-version|^\+version"
$
```

Update version to v1.16.25

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
e429c4a433 2023-12-15 21:19:32 -0600  (HEAD -> version_bump_v1.17.12, origin/version_bump_v1.17.12)  will.hickey@solana.com Update version to v1.17.12
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.11|^\+( \")?solana.*1.17.12|^-version|^\+version"
$
```

Update version to v1.17.12

---

program-runtime/src/loaded_programs.rs
programs/sbf/tests/programs.rs
runtime/src/bank.rs

v1.17 - Cooperative Program Loading

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
5c6b37ae9f 2023-12-16 22:22:25 -0600  (HEAD -> version_bump_v1.17.13, origin/version_bump_v1.17.13)  will.hickey@solana.com Update version to v1.17.13
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.12|^\+( \")?solana.*1.17.13|^-version|^\+version"
$
```

Update version to v1.17.13

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
7ca2bff3b7 2023-12-21 09:21:16 -0600  (HEAD -> version_bump_v1.17.14, origin/version_bump_v1.17.14)  will.hickey@solana.com Update version to v1.17.14
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.13|^\+( \")?solana.*1.17.14|^-version|^\+version"
$
```

Update version to v1.17.14

---

ledger-tool/src/program.rs
program-runtime/src/invoke_context.rs
program-runtime/src/message_processor.rs
program-test/src/lib.rs
programs/address-lookup-table/src/processor.rs
programs/bpf_loader/benches/serialization.rs
programs/bpf_loader/src/lib.rs
programs/bpf_loader/src/serialization.rs
programs/bpf_loader/src/syscalls/cpi.rs
programs/config/src/config_processor.rs
programs/loader-v4/src/lib.rs
programs/sbf/benches/bpf_loader.rs
programs/stake/src/stake_instruction.rs
programs/stake/src/stake_state.rs
programs/system/src/system_instruction.rs
programs/system/src/system_processor.rs
programs/vote/src/vote_state/mod.rs
programs/zk-token-proof/src/lib.rs
runtime/src/bank/tests.rs
sdk/src/transaction_context.rs

Split from https://github.com/solana-labs/solana/pull/34194
Pass feature_set into BorrowedAccount
Fixes #

pass feature_set to BorrowedAccount

---

core/src/cluster_info_vote_listener.rs
core/src/consensus/heaviest_subtree_fork_choice.rs
core/src/replay_stage.rs
core/tests/snapshots.rs

Few typo fixing in core. Doesn't require testing.

Fix typo in comments in core

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
97eb9f2dc2 2024-01-02 16:42:01 -0600  (HEAD -> version_bump_v1.17.15, origin/version_bump_v1.17.15)  will.hickey@solana.com Update version to v1.17.15
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.14|^\+( \")?solana.*1.17.15|^-version|^\+version"
$
```

Update version to v1.17.15

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
b20b457906 2024-01-03 14:26:26 -0600  (HEAD -> version_bump_v1.16.26, origin/version_bump_v1.16.26)  will.hickey@solana.com Update version to v1.16.26
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.25|^\+( \")?solana.*1.16.26|^-version|^\+version"
$
```

Update version to v1.16.26

---

programs/vote/src/vote_state/mod.rs

This function declares extra variables and does unnecessary assertions which makes it difficult to read.
- Improve readability
- Remove unnecessary assertions
Fixes #

refactor: `check_update_vote_state_slots_are_valid`

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
2a9b501111 2024-01-06 23:28:54 -0600  (HEAD -> version_bump_v1.17.16, origin/version_bump_v1.17.16)  will.hickey@solana.com Update version to v1.17.16
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.15|^\+( \")?solana.*1.17.16|^-version|^\+version"
$
```

Update version to v1.17.16

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
edb208afab 2024-01-06 23:06:48 -0600  (HEAD -> version_bump_v1.16.27, origin/version_bump_v1.16.27)  will.hickey@solana.com Update version to v1.16.27
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.26|^\+( \")?solana.*1.16.27|^-version|^\+version"
$
```

Update version to v1.16.27

---

programs/sbf/rust/spoof1/src/lib.rs

Fixes https://github.com/solana-labs/solana/issues/34687

programs/sbf: "fix" invalid_reference_casting lint

---

cost-model/src/cost_tracker.rs

A comment was left behind after relevant code was removed. 
- remove old comment
Fixes #

remove old comment

---

programs/bpf_loader/src/lib.rs

Cleanup - feature gate of `remove_bpf_loader_incorrect_program_id`

---

send-transaction-service/src/send_transaction_service.rs

Tests expect zero transaction fee without be explicit about it.
- explicitly sets up tests with zero fee rate
Fixes #

explicitly sets tests that does not handle transaction fee

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
e87f8b5c22 2024-01-20 21:12:02 -0600  (HEAD -> version_bump_v1.17.18, origin/version_bump_v1.17.18)  will.hickey@solana.com Update version to v1.17.18
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.17|^\+( \")?solana.*1.17.18|^-version|^\+version"
$
```

Update version to v1.17.18

---

Cargo.lock
programs/sbf/Cargo.lock

audit failed: https://buildkite.com/solana-labs/solana/builds/107049#018d3232-7df3-45e2-b6b8-d08915431674
bump shlex to 1.3.0

bump shlex to 1.3.0

---

Cargo.lock
programs/sbf/Cargo.lock

v1.17: bump shlex to 1.3.0

---

gossip/src/cluster_info.rs

Add push and get methods for RestartHeaviestFork

Add push_heaviest_fork and get_heaviest_fork.

---

runtime/src/bank.rs

Minor inconsistencies between similar methods of Bank.
Update the signature of Bank::check_age to use the same convention as in Bank::check_status_cache

Refactoring internal bank method signature for consistency

---

runtime/src/accounts/account_rent_state.rs
runtime/src/accounts/mod.rs
runtime/src/bank/transaction_account_state_info.rs

RentState code could use some cleanup.
Minor cleanup by moving functions inside `impl` block and removing unnecessary `pub` qualififer.
Fixes #

Code cleanup in account_rent_state

---

runtime/src/bank.rs

The logic of calculating counters, and logging can be implemented using the return value of `load_and_execute_sanitized_transactions()`. The logic can be pulled out of `load_and_execute_sanitized_transactions()`, as this function will eventually be part of SVM. 
Move the code back to the caller, `load_and_execute_transactions()`.
Fixes #

Move counter and logging code back to load_and_execute_transactions()

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
79a850a44f 2024-01-27 00:54:40 -0600  (HEAD -> version_bump_v1.17.19, origin/version_bump_v1.17.19)  will.hickey@solana.com Update version to v1.17.19
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.18|^\+( \")?solana.*1.17.19|^-version|^\+version"
$
```

Update version to v1.17.19

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -2
65ac102e4d 2024-01-27 00:47:03 -0600  (HEAD -> version_bump_v1.18.1, origin/version_bump_v1.18.1)  will.hickey@solana.com Revert proc-macro-crate version changes
c1a98f6640 2024-01-27 00:43:16 -0600   will.hickey@solana.com Update version to v1.18.1
$ git diff v1.18..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.18.0|^\+( \")?solana.*1.18.1|^-version|^\+version"
$
```

Update version to v1.18.1

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -2
3832b79c2c 2024-01-30 22:13:34 -0600  (HEAD -> version_bump_v1.18.2)  will.hickey@solana.com Revert proc-macro-crate and hashbrown version changes
18b457de0f 2024-01-30 22:09:47 -0600   will.hickey@solana.com Update version to v1.18.2
$ git diff v1.18..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.18.1|^\+( \")?solana.*1.18.2|^-version|^\+version"
```

Version bump v1.18.2

---

accounts-db/src/rent_collector.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
svm/src/account_loader.rs

feature #28683 was activated on all clusters.
Remove code for handling prior to feature activation.
Fixes #

remove activated feature set_exempt_rent_epoch_max

---

docs/README.md
docs/src/proposals/comprehensive-compute-fees.md
docs/src/proposals/simple-payment-and-state-verification.md
metrics/README.md

Came across few errors while reading the docs, corrected them.
Doesn't require testing/changelog entry.

chore(docs): proofreading

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
f6609ddca8 2024-02-12 15:04:31 -0600  (HEAD -> version_bump_v1.17.22, origin/version_bump_v1.17.22)  will.hickey@solana.com Update version to v1.17.22
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.21|^\+( \")?solana.*1.17.22|^-version|^\+version"
$
```

Update version to v1.17.22

---

core/src/validator.rs

The directory is currently named with the expected_shred_version; however, the backup contains shreds that do NOT match the expected_shred_version. So, use the found (incorrect) shred version in the name instead.

Update the directory naming for incorrect shred version backup

---

core/src/vote_simulator.rs

Clean up redundant dev-context-util attributes
Fixes #

clean up dev-context-only attribute

---

sdk/src/feature_set.rs
turbine/src/cluster_nodes.rs

Feature is activated on all clusters.
Remove the feature-gated code.

removes feature-gated code revising turbine epoch stakes for shreds propagation

---

svm/src/account_loader.rs

Unit tests in `accounts_loader.rs` are causing it to depend on `accounts-db` structs.
Update the tests to remove the deps.
Fixes #35147

SVM: Remove accounts-db deps in accounts_loader tests

---

core/src/banking_stage/transaction_scheduler/mod.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/scheduler_metrics.rs

- Will be adding additional slot-based metrics in #35087
- Separating out simple move to new file into this PR to simplify the diff
- Move `SchedulerCountMetrics` and `SchedulerTimingMetrics` to a new file: `scheduler_metrics.rs`
- `pub` the necessary metrics (not interval reports) of these structs so that controller code can accumulate
Fixes #

Scheduler: Separate scheduler metrics module

---

.github/workflows/downstream-project-anchor.yml
scripts/build-downstream-anchor-projects.sh
scripts/patch-crates.sh

#35262 has been reverted due to red CI.
- pick it back
- fix the bug that is introduced by the PR
- trigger the downstream project pipeline correctly

ci: update anchor downstream project

---

core/src/banking_stage/forwarder.rs
core/src/banking_stage/qos_service.rs
core/src/banking_stage/unprocessed_transaction_storage.rs

Went over the repo and found a few typos, fixing them in this diff ~

fix: cleanup

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
65aef80ed8 2024-02-23 23:09:58 -0600  (HEAD -> version_bump_v1.17.24)  will.hickey@anza.xyz Update version to v1.17.24
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.23|^\+( \")?solana.*1.17.24|^-version|^\+version"
$
```

Update version to v1.17.24

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -2
7eddaee93c 2024-02-23 22:52:53 -0600  (HEAD -> version_bump_v1.18.4)  will.hickey@anza.xyz Revert proc-macro-crate version changes
d97ea6b59a 2024-02-23 22:38:51 -0600  (origin/version_bump_v1.18.4)  will.hickey@anza.xyz Update version to v1.18.4
$ git diff v1.18..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.18.3|^\+( \")?solana.*1.18.4|^-version|^\+version"
$
```

Update version to v1.18.4

---

ledger/src/shred.rs

Simplify https://github.com/solana-labs/solana/pull/35293.
The commit splits test_shred_variant_compat into separate test-cases.

splits test_shred_variant_compat into separate test-cases

---

programs/sbf/rust/sanity/src/lib.rs
programs/sbf/tests/programs.rs
sdk/bpf/scripts/install.sh
sdk/cargo-build-sbf/src/main.rs
sdk/program/Cargo.toml
sdk/sbf/c/sbf.mk
sdk/sbf/scripts/install.sh

The platform tools version is outdated.
I updated the version to v1.41.

Bump platform tools version

---

sdk/benches/ed25519_instructions.rs
sdk/benches/secp256k1_instructions.rs

need to benchmark precompiled program perf
- add bench tests
Fixes #

add bench for precompiled programs

---

svm/src/account_loader.rs
svm/src/account_overrides.rs
svm/src/account_rent_state.rs
svm/src/transaction_account_state_info.rs
svm/tests/account_loader.rs

Function in the SVM crate were not properly tested inside the crate.
I added more tests.
PS: In the next PRs, I will test the SVM entry point and the functions in `sum/transaction_processor.rs`

Add more unit tests to SVM

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
e4d313f015 2024-03-02 20:59:52 -0600  (HEAD -> version_bump_v1.18.5, origin/version_bump_v1.18.5)  will.hickey@anza.xyz Update version to v1.18.5
$ git diff v1.18..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.18.4|^\+( \")?solana.*1.18.5|^-version|^\+version"
$
```

Update version to v1.18.5

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -1
9b7ad94b6e 2024-03-02 21:05:09 -0600  (HEAD -> version_bump_v1.17.25, origin/version_bump_v1.17.25)  will.hickey@anza.xyz Update version to v1.17.25
$ git diff v1.17..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.17.24|^\+( \")?solana.*1.17.25|^-version|^\+version"
$
```

Update version to v1.17.25

---

core/src/consensus/heaviest_subtree_fork_choice.rs
core/src/replay_stage.rs
docs/static/katex/katex.js
docs/static/katex/katex.mjs
dos/src/main.rs
download-utils/src/lib.rs
local-cluster/tests/local_cluster.rs
sdk/program/src/secp256k1_recover.rs
sdk/src/secp256k1_instruction.rs
send-transaction-service/src/tpu_info.rs

remove repetitive words
