solana-labs/solana

runtime/src/accounts_db.rs
Ancient append vec overflow was not being handled correctly with `shrink_in_progress`.
When we continue refactoring shrink, `shrink_in_progress` will be relied upon solely to determine which append vecs to drop from a slot.
This is tested by `test_shrink_ancient_overflow`. The test fails once we get rid of `should_retain` parameter from `mark_dirty_dead_stores`. At the moment, we are still relying on the append vec ids and `should_retain` to correctly remove old stores after a shrink.
Update `shrink_in_progress` correctly for ancient append vec overflow case.
Fixes #
=> handle ancient overflow case correctly

runtime/src/accounts_db.rs
Trying to get rid of `AccountStorage::get`
Some tests use it to check for `is_none`
migrate tests to use `get_slot_stores`, which returns an equivalent Some/None
Fixes #
=> migrate tests to not use AccountStorage::get

runtime/src/accounts_db.rs
We randomly shrink ancient append vecs. Right now it is 1% of the time. With large ancient append vecs, these unnecessary shrinks can be quite expensive.
Reduce rate to .01%
Fixes #
=> decrease frequency of random shrink of ancient append vec

runtime/src/bank.rs
skipping rewrites will no longer hash the skipped accounts
remove the metric measuring this time
Fixes #
=> remove metric time_hashing_skipped_rewrites_us

local-cluster/tests/local_cluster.rs
`test_snapshot_download` and `test_incremental_snapshot_download` are not testing what they intend to. Intention is to generate snapshot(s), download the snapshot(s) to a validator, and boot from the snapshot(s). Problem is that the snapshots are downloaded to the leader's snapshot folder, so when the validator boots, it doesn't find any snapshots and instead loads from genesis.
Download snapshots to validator's snapshot folders (as opposed to leader's).
=> Fix snapshot download test

runtime/src/rent_collector.rs
[It should not be legal for an account to be rent exempt and then become rent paying.](https://discord.com/channels/428295358100013066/838890116386521088/1059515211763155054)
With the activation of feature set rent_epoch to Epoch::MAX (#28690)
collecting rent on an exempt account will set `rent_epoch` to u64::MAX. This will prevent us from collecting rent on this account in the future. Thus, this test will fail once that feature is activated.
prevent the test from testing an illegal combination.
Fixes #
=> test_rent_exempt_temporal_escape works in passes

runtime/src/account_storage.rs, runtime/src/serde_snapshot.rs
Refactoring is ongoing to only allow 1 append vec per slot.
add comments and renames to `account_storage.rs`.
Fixes #
=> cleanup in account_storage.rs

local-cluster/tests/local_cluster.rs
See #29457 - missed one spot to point at proper snapshot directories
Download incremental snapshot to right directory so validator loads from it for `test_incremental_snapshot_download`
=> Snapshot download test

ledger-tool/src/main.rs, runtime/src/accounts_db.rs, runtime/src/bank.rs, validator/src/main.rs
Skipping rewrites will now be feature enabled only. This means the hidden cli args and accounts_db state have already not been useful.
remove hidden option and accounts_db `skip_rewrites`
Fixes #
=> skip_rewrites will only be feature driven

runtime/src/accounts_db.rs
instead of iterate and 
1. collect
2. iterate all
3. filter
This function is being refactored to remove the call to `AccountStorage::get`. As part of that, it makes sense to reorder how we do filtering.
iterate and
1. filter
2. collect
3. iterate already filtered
Fixes #
=> filter get_snapshot_storages for requested_slots earlier

cli/src/program.rs
While troubleshooting https://github.com/solana-labs/solana/issues/29451, I found some of the code in `solana program` confusing due to dead and superfluous code.
- Remove the `messages` Vecs that are being constructed and never used
- Remove some unnecessary Option wrappers
No functional changes
Some of the Options passed into `send_deploy_messages()` are technically superfluous as well, but I think that method probably needs its own overhaul, with the various potential messages and their respective signers combined into discrete Options.
=> Cli: refactor program code slightly

cli/src/program.rs, cli/tests/program.rs
`solana program` uses some bespoke signer-parsing logic in a couple places to fall back to the DefaultSigner. This allows `solana program write-buffer --buffer-authority <PUBKEY>` to succeed, even though `--buffer-authority` must be a Signer. (As described in https://github.com/solana-labs/solana/issues/17890, the result is that the authority is unexpectedly set as the DefaultSigner.)
Fix parsing logic. In the case of `solana program deploy`, the changes are a noop.
Fixes #29451
=> Cli: the authority passed to `solana program write-buffer` must be a proper signer

core/src/validator.rs, ledger-tool/src/main.rs, runtime/src/snapshot_utils.rs
The async remove function is more used in snapshot_utils.rs.  It is an util function anyway, cleaner to be in the util file than in the main application file.
Move move_and_async_delete_path to snapshot_utils.rs.
This is one of the split PRs for https://github.com/solana-labs/solana/pull/28745.
Fixes #
=> Move async remove to snapshot_utils.rs

runtime/src/account_info.rs, runtime/src/accounts_db.rs
Unnecessary explicit types make refactoring more difficult.
remove explicit types
fix clippy warning
Fixes #
=> remove unnecessary type

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
add `is_empty()` to clearly answer that query.
Fixes #
=> add AccountStorage.is_empty

runtime/src/accounts_db.rs
Tests assert that there is no an entry in the storage map for a given slot. This is complicated to implement.
Localize the behavior into new test method `assert_no_storages_at_slot()` for later refactoring.
Fixes #
=> add test method assert_no_storages_at_slot()

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
working on removing calls to `AccountStorage.get`
`get_snapshot_storages` uses iteration to get storages instead of calling `get`
Fixes #
=> get_snapshot_storages removes call to AccountStorage.get

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
the `should_retain` closure is no longer necessary now that we have `shrink_in_progress`
remove `should_retain` closure and modify tests to use `shrink_in_progress`
Fixes #
=> remove should_retain from mark_dirty_dead_stores

ledger-tool/src/main.rs
In ledger-tool command line help, we use both "append vec" and "AppendVec". It
is better to use the same term for the help messages.
Change "append vec" to "AppendVec" in ledger-tool command line help message.
Fixes #
=> update leger tool help for db verify refcounts

gossip/src/contact_info.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_pull.rs, gossip/src/crds_gossip_push.rs, gossip/src/crds_value.rs
In order to avoid traffic congestion or sending duplicate packets, when sampling gossip nodes, if several nodes have the same gossip address because they are behind a relayer or whatever, they need to be deduplicated into one.
dedup gossip addresses, taking the one with highest weight
=> dedups gossip addresses, taking the one with highest weight

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Moving towards 1 append vec per slot.
`AccountStorageEntry`.`get_slot_storage_entries()` returns `Option<Vec<Arc<AccountStorageEntry>>>`
When shrink is not running, we only ever have 0 or 1 entries in the `Vec`, but all code has to handle any number of entries.
Introduce `get_slot_storage_entry()`, which returns `Option<Arc<AccountStorageEntry>>`. Callers only have to handle 0 or 1 entries. Soon, `get_slot_storage_entries()` will be removed and it will not be possible to have multiple append vecs per slot (except during shrinking, and then, the second append vec will be held separately).
Fixes #
=> add AccountStorage.get_slot_storage_entry

runtime/src/accounts_db.rs, validator/src/cli.rs
refactor `get_snapshot_storages` for clarity.
Fixes #
=> cleanup get_snapshot_storages

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
A few tests want to verify that there is an entry for a slot, but that it is empty.
Introduce `AccountStorage`::`is_empty_entry()` to answer the question correctly.
Fixes #
=> add AccountStorage.is_empty_entry for tests

core/src/banking_stage.rs, runtime/src/bank.rs
A subsequent change to `SamplePerformanceService` introduces non-vote transaction counts, which `bank`s need to store.
Added the necessary counts.
Part of work on https://github.com/solana-labs/solana/issues/29159
=> bank: Record non-vote transaction count

ledger/src/shred.rs, ledger/src/shred/merkle.rs, ledger/src/sigverify_shreds.rs
```diff
- This is a prerequisite of
- https://github.com/solana-labs/solana/pull/29427
```
`{verify,sign}_shreds_gpu` need to point to offsets within the packets for the signed data. For merkle shreds this signed data is the merkle root of the erasure batch and this would necessitate embedding merkle roots in the shreds payload.
However this is wasteful and reduces shreds capacity to store data because the merkle root can already be recovered from the embedded merkle proof.
Instead of pointing to offsets within shreds payload, this commit recovers merkle roots from the merkle proofs and stores them in an allocated buffer. `{verify,sign}_shreds_gpu` would then point to offsets within this new buffer for the respective signed data.
This would unblock us from removing merkle roots from …
=> recovers merkle roots from shreds binary in {verify,sign}_shreds_gpu

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
moving to a single append vec per slot.
Ancient append vec code was written to handle Vec
`should_move_to_ancient_append_vec()` now requires a single append vec per slot.
Fixes #
=> should_move_to_ancient_append_vec works with a single storage

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Moving to allowing only 1 append vec per slot.
Some code currently uses `get_slot_storage_entries()`.
We want to use the single version of `get_slot_storage_entry()`
Convert some code to use `get_slot_storage_entry()`
Fixes #
=> get_storages_for_slot uses get_slot_storage_entry

rpc-client-api/src/custom_error.rs
rpc_custom_error module is returning the wrong error code for TransactionPrecompileVerificationFailures, because consts with similar names are hard.
Fix it
Fixes #19019
=> Fix TransactionPrecompileVerification RPC error

rpc/src/rpc_subscriptions.rs
Test is intermittent because newly created accounts get `rent_epoch`=0. But, after their rent collection slot, they go to `u64::MAX`
pick a keypair that gets rent collected.
Modify expected results to be `u64::MAX`
Fixes #
=> make rpc test tolerant of rent_epoch being set to max

Cargo.lock, logger/Cargo.toml, logger/src/lib.rs, metrics/Cargo.toml, programs/sbf/Cargo.lock
With https://github.com/env-logger-rs/env_logger/issues/208 resolved, `env_logger::Target::Pipe` works properly, but the validator still outputs to console on Windows since it's on an older version.
Update to version 0.9.3 to pick up the fix, and have file logging work properly on Windows.
Fixes #
=> logger: Update to env_logger 0.9.3

runtime/src/accounts_db.rs
unnecessary call to `to_vec()`, adds uncertainty to refactoring
remove it
Fixes #
=> remove unnecessary to_vec()

runtime/src/snapshot_minimizer.rs
Shrinking operations need to ignore reclaims. As we move towards limiting to 1 append vec per slot, this test causes asserts.
ignore reclaim while doing snapshot minimization, which is shrink operation and is a ledger-tool only functionality anyway.
Fixes #
=> filter_storages ignores reclaims

runtime/src/accounts_db.rs
We need the lifetime of `shrink_in_progress` to be correct (like a real shrink would be). Some tests are violating that. Refactoring `AccountStorage` results in asserts due to this.
Handle lifetime of `shrink_in_progress` return values correctly.
Fixes #
=> cleanup ancient append vec tests

runtime/src/accounts_db.rs
Use `get_slot_storage_entry()` in tests to return a single append vec and assert there is only 1.
Fixes #
=> migrate tests to get_slot_storage_entry

runtime/src/accounts_db.rs
We don't need to keep track of `store_ids` during shrink anymore. `ShrinkInProgress` does that.
Remove `store_ids` from a few shrink data structures.
Fixes #
=> remove store_ids from a few shrink data structures

runtime/src/accounts_db.rs
moving towards 1 append vec per slot
`get_storages_to_move_to_ancient_append_vec()` returns a single append vec instead of a vector
Fixes #
=> get_storage_to_move_to_ancient_append_vec returns a single append vec

runtime/src/accounts_db.rs
migrating pattern of
`Vec<storage>.first().unwrap()`
to 
`storage` // a single storage
by using new test fn `get_storage_for_slot()`
Fixes #
=> use get_storage_for_slot() in tests

runtime/src/accounts_db.rs
migrate fn `process_storage_slot()` to take a single append vec
Fixes #
=> process_storage_slot takes a single append vec

core/src/replay_stage.rs, geyser-plugin-interface/src/geyser_plugin_interface.rs, geyser-plugin-manager/src/block_metadata_notifier.rs, geyser-plugin-manager/src/block_metadata_notifier_interface.rs, runtime/src/bank.rs
The plugins need to know when all transactions for a block have been all notified to serve getBlock request correctly. As block and transaction notifications are sent asynchronously to each other it will be difficult.
Include the executed transaction count in block notification which can be used to check if all transactions have been notified.
Fixes #
=> Stream the executed transaction count in the block notification

cli/src/program.rs, ledger/src/blockstore.rs, ledger/src/blockstore_db.rs, remote-wallet/src/ledger.rs, runtime/src/append_vec/test_utils.rs, tokens/src/commands.rs
`clippy::needless_borrow`
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
fixed errors.
=> fixes errors from clippy::needless_borrow

runtime/src/accounts_db.rs
`shrink_slot_forced()` gets a single append vec
Fixes #
=> shrink_slot_forced uses a single append vec

ci/buildkite-pipeline.sh
Version bump PRs currently run the entire CI suite which is unnecessary and takes a few hours.
Add a check to the pipeline builder that detects version bump PRs and only runs the `checks` step
I don't know a way to test this in Buildkite without merging it but I stubbed out the buildkite agent and ran tests locally for:
* master minor version bump
* master and v1.14 patch version bumps
* master and v1.14 changes unrelated to version bumps
* master and v1.14 dependency version bumps (this still runs the full CI pipeline as intended)
Since it hasn't been tested in Buildkite yet I've left in some echo statements for debugging in case there are problems.
=> Update CI pipeline to only run `checks` step on version bump PRs

ledger/src/sigverify_shreds.rs, perf/src/sigverify.rs
* don't need to allocate a vector for signature lengths in sigverify shreds.
* verbose  code.
* changed arg type to iterator.
* simplified the code.
=> simplifies sigverify copy_return_values

runtime/src/append_vec.rs
The existing error message does not provide path information needed for recycling error debugging.
Add the specific path information.
This is a split of the PR https://github.com/solana-labs/solana/pull/28745 and https://github.com/solana-labs/solana/pull/29496/
Fixes #
=> Refine appendvec sanitize error message to include path

runtime/src/accounts_db/geyser_plugin_utils.rs
Removed assert on write_version ordering  as snapshot created by earlier version is not honoring that.
Fixes #
=> Removed assert on write_version ordering 

runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
Minor cleanup in regex code in snapshot_storage_rebuilder.rs
One of the split PRs from https://github.com/solana-labs/solana/pull/28745
Move duplicated regex from inside function to top of the file;
Change get_slot_and_append_vec_id() implementation to use regex.
Fixes #
=> storage rebuilder regex cleanup

Cargo.lock, stake-accounts/Cargo.toml, stake-accounts/src/arg_parser.rs
```
$ solana-stake-accounts -V
solana-stake-accounts version
```
Fix clap inputs, including version (minor cleanup on a largely unsupported bin, but doing it since it's still in the monorepo)
```
$ cd stake-accounts && cargo run -- -V
solana-stake-accounts 1.15.0 (src:devbuild; feat:629316760)
```
Fixes #20413
=> Fix solana-stake-accounts version

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
Moving towards 1 append vec per slot.
It is inconvenient and now unnecessary to return # remaining append vecs after `mark_dirty_dead_stores()`. The answer will always be 1 or 0 now. We were previously using this to assert it was never > 1. That will always be true now.
Remove return value, simplify calling code.
Fixes #
=> stop returning remaining # stores from mark_dirty_dead_stores

ci/buildkite-pipeline-in-disk.sh, ci/buildkite-pipeline.sh
some context: https://discord.com/channels/428295358100013066/560503042458517505/1060679253290655785
The time which stable-perf taking is so closing to the origin timeout limit, 20 min.
I think we can either 1) increasing timeout limit or 2) upgrade our gcp agent's hardware.
I do 1) atm.
=> chore: increase stable-perf timeout_in_minutes to 35

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Moving towards 1 append vec per slot.
Other refactoring has made only 1 caller to `AccountStorage::is_empty()`
Remove the unused function to simplify understanding and testing.
Fixes #
=> remove AccountStorage::is_empty()

accounts-cluster-bench/src/main.rs
```
[2023-01-04T08:03:03.172226504Z INFO  solana_accounts_cluster_bench] ids: 1
[2023-01-04T08:03:03.172910773Z WARN  solana_accounts_cluster_bench] get_fee_for_message failure: Err(Error { request: None, kind: Custom("Invalid blockhash") }). remaining retries 4
[2023-01-04T08:03:03.274184232Z WARN  solana_accounts_cluster_bench] get_fee_for_message failure: Err(Error { request: None, kind: Custom("Invalid blockhash") }). remaining retries 3
[2023-01-04T08:03:03.375479668Z WARN  solana_accounts_cluster_bench] get_fee_for_message failure: Err(Error { request: None, kind: Custom("Invalid blockhash") }). remaining retries 2
[2023-01-04T08:03:03.476697420Z WARN  solana_accounts_cluster_bench] get_fee_for_message failure: Err(Error { request: None, kind: Custom("Invalid blockhash") }). …
```
=> Refresh blockhash for retrials of failed get_fee calls

runtime/src/accounts_db.rs
Make `ShrinkCandidates` only be able to hold a single append vec per slot.
Fixes #
=> ShrinkCandidates only hold 1 append vec per slot

ledger-tool/src/main.rs
There is a possible deadlock caused by double readlock in fn `ledger-tool/src/main.rs`.
`last_point_value: Arc<RwLock<Option<PointValue>>>`
The first readlock is on L3737 and the second on L3744
https://github.com/solana-labs/solana/blob/e4a7d01e10e7f0dea2254025d76897ff008f3118/ledger-tool/src/main.rs#L3734-L3747
For more details on this kind of deadlock, see
https://www.reddit.com/r/rust/comments/urnqz8/different_behaviors_of_recursive_read_locks_in/
Call read lock once. If the returned `Option<PointValue>` is Some, then map it to pair (Some(rewards), Some(points)); othewise, map it to (None, None).
Fixes #
=> ledger-tool: fix double-readlock in main

runtime/src/accounts_db.rs, runtime/src/serde_snapshot.rs
Adding initial filler accounts (which is a debug only feature) makes this difficult.
Remove the ability to add filler accounts in bulk initially. This avoids us having to use 2 append vecs per slot.
Fixes #
=> filler accounts only work gradually

runtime/src/accounts_db.rs, runtime/src/accounts_db/geyser_plugin_utils.rs
subset of #29549
That one has deeper issues that I have to untangle.
moving towards 1 append vec per slot
`get_slot_stores()` returns internals of the storage map.
Move to the more contained `get_slot_storage_entry()` api which can help us control the data types and expectations better.
Fixes #
=> convert some get_slot_stores -> get_slot_storage_entry

runtime/src/accounts.rs
Moving to 1 append vec per slot. These tests are storing uncached, directly to the append vec. This is not supported in the runtime. We can get the same result by writing to the cache instead. This makes getting to 1 append vec per slot easier.
Move some accounts.rs tests to call `store_for_tests()` instead of `store_slow_uncached()`
Fixes #
=> accounts tests use store_for_tests

client/src/rpc_response.rs, core/src/validator.rs, docs/src/developing/clients/jsonrpc-api.md, rpc/src/rpc.rs, rpc/src/rpc_service.rs, runtime/src/prioritization_fee_cache.rs
=> Add getRecentPrioritizationFees RPC endpoint (backport #27278)

rpc-client-api/src/request.rs, rpc-client/src/mock_sender.rs, rpc-client/src/nonblocking/rpc_client.rs, rpc-client/src/rpc_client.rs
It's current difficult for downstream users to access prioritization_fee_cache data because they must query the RPC endpoint directly.
Add RpcClient support for get_recent_prioritization_fees
=> Add rust client support for getRecentPrioritizationFees

core/src/multi_iterator_scanner.rs, ledger/src/blockstore_db.rs
`cargo doc` generates warnings
Turn a code block into a not-rust code block. Remove a link to `LedgerCleanupService`, which can't be reached from the `solana-ledger` crate because it is in `solana-core`.
=> Fix doc warnings

gossip/src/cluster_info.rs, gossip/src/legacy_contact_info.rs
Since https://github.com/solana-labs/solana/pull/20480, turbine includes all epoch staked nodes in tree construction and no longer relies on obtaining their contact-info from gossip; and so distinguishing between `is_valid_address` and `is_valid_tvu_address` is no longer necessary and the latter can be removed.
removed `LegacyContactInfo::is_valid_tvu_address`.
=> removes LegacyContactInfo::is_valid_tvu_address

cli-output/src/cli_output.rs, rpc-client-api/src/response.rs, rpc-client/src/mock_sender.rs, rpc/src/rpc.rs, validator/src/dashboard.rs
`getClusterNodes` response misses PubSub address, returns only the RPC address.
Added PubSub address in this response and respective mock sender. Additionally, added same data to CLI and dashboard.
Fixes #
=> Add pubsub address to RpcContactInfo

runtime/src/accounts_db.rs
`combine_one_store_into_ancient` takes 1 append vec instead of slice.
Fixes #
=> combine_one_store_into_ancient takes 1 append vec

runtime/src/accounts_db.rs, runtime/src/bank.rs, sdk/src/feature_set.rs
At some point, we want to stop doing rewrites in rent collection. This will eliminate needless work.
This pr introduces the feature flag which will govern when rewrites stop occurring.
Activating this feature requires that ancient append vecs be enabled by default. Otherwise, validators will exhaust their mmap file handle limit.
introduce feature flag that causes us to skip rewrites in rent collection.
Fixes #
Feature Gate Issue: #26599
=> feature: don't do rewrites in rent collection

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
converting apis that take vec to take a single append vec
`get_unique_accounts_from_storages()` takes single storage
Fixes #
=> get_unique_accounts_from_storages takes 1 append vec

runtime/src/bank.rs, sdk/src/transaction_context.rs
When debugging consensus failure it is often necessary to isolate the events of a single TX from the rest of all message processing.
Adds TX signature to `TransactionContext` in debug mode.
=> Adds TX signature to `TransactionContext` in debug mode

pubsub-client/src/nonblocking/pubsub_client.rs, rpc-client/src/nonblocking/rpc_client.rs
See  #26994
Add a setter in order to force the RPC version and avoid a call to the get_version method
Closes #26994
...as rebasing was a pain
=> Setter for node_version property

rpc/src/rpc_pubsub.rs, rpc/src/rpc_subscriptions.rs
Many of our RPC test fail sporadically in CI with a receiver timeout.
This is caused by a race condition between completing processing of a subscription and processing some notification. We need the subscription to be processed first so we will receive a message when the notification is processed later, but occasionally (~10% of the time for some tests) the notification is processed first because these activities are handled async.
Note: this is a known issue observed in #27480 and partially mitigated by #27481 and #28998. The latest failing test observed failing was `test_logs_subscribe`
Add an API for unit tests, `block_until_processed`, that will not return until server side handling of notifications has completed. It does this by subscribing to slot notifications, queueing a slot …
=> Fix RPC tests race condition

programs/bpf_loader/src/syscalls/cpi.rs, sdk/src/feature_set.rs
https://github.com/solana-labs/solana/pull/26737 implicitly reordered error priorities which are triggered if the user supplied pointer is unaligned for example.
Add a feature gate that switches from the reverted code to the new.
Fixes #29576
Feature Gate Issue: #29592
=> Fix - #26737

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
Moving to 1 append vec per slot
`FoundStoredAccount` has now unnecessary `store_id` member.
Remove `store_id`
Fixes #
=> FoundStoredAccount removes store_id

ledger-tool/src/main.rs, runtime/src/accounts_db.rs, validator/src/cli.rs, validator/src/main.rs
There will soon be a feature to enable skipping rewrites. When that occurs, we have to be able to combine into ancient append vecs, or we will run out of mmap file handles.
There is a cli arg `--accounts-db-ancient-append-vecs` This offset is usually positive for debugging, causing us to put accounts into ancient append vecs when they are less than 432k slots old. Making it negative pushes the inflection point older.
Enable ancient append vecs by default at -10k slots. This means we won't try to put anything into an ancient append vec until it is older than 432k + 10k slots from the max root. Until the feature gets activated, this means that nothing should get put into ancient append vecs.
Fixes #
=> ancient append vecs enabled at -10k by default

Cargo.lock, ci/sbf-tools-info.sh, sdk/cargo-build-sbf/Cargo.toml, sdk/cargo-build-sbf/src/main.rs
The version of sbf-tools is hard-coded in cargo-build-sbf utility code and fixed for users of an official release of solana.
Such users need an option to install and use more recent releases of sbf-tools.
Add a new command line option to cargo-build-sbf utility that specifies a version of sbf-tools the utility should install and use.
=> Add an option to install a specific version of sbf-tools

bucket_map/src/bucket_stats.rs, runtime/src/bucket_map_holder_stats.rs
A lock (mutex) for max_size stat on bucketstats is unnecessary. It can be replaced with Atomic variable.
Use atomicu64 for max_size in bucketstats
Fixes #
=> use atomicu64 for bucket maxsize instead of lock

runtime/src/accounts_db.rs
Return value isn't used and can be difficult to calculate.
Remove return value.
Fixes #
=> remove unused ret val from do_shrink_slot_store

runtime/src/account_info.rs, runtime/src/accounts_db.rs
There could be race conditions in tests without this change. Recent changes are moving towards 1 append vec per slot.
The comparison here was asking for `.store_id()` of account info. This asserts if the account info refers to data in the write cache. It is sufficient to just test the slot since there can only be one append vec per slot.
We were hitting this specific case because a test was running shrink and flush in parallel. This meant that flush could create an append vec to flush to, then shrink could concurrently try to shrink that append vec. This is undefined behavior. A way to avoid this at a higher level is #29615. It already was my intuition that checking for any entry at the shrinking slot was sufficient to mean the account is alive. So, this change is simpler and correct as …
=> just use slot to determine alive while shrinking

pubsub-client/src/pubsub_client.rs
Some RPC nodes are sending WebSocket messages with the `PING` opcode which makes client fail on JSON deserialization attempt and stop iteration over incoming messages. Example of such node – `wss://solana-api.projectserum.com`, it's mentioned in the official docs here: https://docs.solana.com/ru/cluster/rpc-endpoints#mainnet-beta
Ignore WebSocket message with the `PING` opcode. Don't worry about server – Tungstenite will handle such messages for us and respond with corresponding `PONG` reply.
Fixes #26343
=> Don't try to deserialize WebSocket ping messages

runtime/src/bank.rs, runtime/src/bank/metrics.rs
bank.rs is very cluttered.
Move the metrics reporting code into a separate file. This reduces line count and also makes the actual logic in bank.rs more readable by removing a big block of boilerplate code.
This can be done for more metrics as well, starting with just this one for sake of keeping PR's light
=> chore: Move bank new epoch metrics into separate file

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Moving towards 1 append vec per slot. While shrinking is in progress, there need to be 2 findable append vecs. But, we want the data structures to be optimized for holding only 1 entry per slot.
Introduce `shrink_in_progress_map` to hold the append vec being shrunk while the index is being updated to the new, shrunk append vec. This allows the entry in the main `map` to not need to be a `Vec`, allowing us to move to a state where only a single entry per slot is possible in `map`.
Fixes #
=> while shrinking, old append vec is held outside of storage.map

runtime/src/accounts_cache.rs, runtime/src/accounts_db.rs
a test exposes a race condition with shrinking while flushing the write cache.
Never shrink if a slot is in the write cache.
Fixes #
=> never try to shrink a slot that is in the write cache

runtime/src/accounts_db.rs
Would like to stop storing per-account size in the account index. If this can be easily recalculated, then there is no reason to store it.
assert that the calculated size when we need the size always matches the stored size.
Fixes #
=> verify acct size in index can easily be recalculated

runtime/src/accounts.rs, runtime/src/accounts_db.rs
Trying to stop saving `write_version` in append vecs.
Now that we only ever have 1 append vec per slot, account data we find later is always more recent.
Assert that write_version is increasing per pubkey.
Fixes #
=> assert write version is increasing per slot as we read from a slot

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs, runtime/src/snapshot_minimizer.rs, runtime/src/storable_accounts.rs
Moving to 1 append vec per slot
`FoundStoredAccount` is now an unnecessary wrapper of `StoredAccountMeta`
remove `FoundStoredAccount`, all code paths now interact directly with `StoredAccountMeta`
Fixes #
=> remove FoundStoredAccount

ci/docker-rust/Dockerfile
Since #26854, protoc is built from source in the places that we need it (solana-storage-bigtable and solana-storage-proto). Nothing is using this protoc install; both the comment and the protoc version itself are out of date.
Remove
cc: https://github.com/solana-labs/solana/pull/26827
=> Remove protoc from docker image

runtime/src/accounts_db.rs
Soon we will only have 1 append vec per slot. 
Inside `scan_multiple_account_storages_one_slot()` is the code for handling a single append vec. Soon, that code will be all that we need and we can delete the rest of `scan_multiple_account_storages_one_slot()`
Move the single append vec scanning code into `scan_single_account_storage()` and add tests for it.
Fixes #
=> factor out scan_single_account_storage

runtime/src/accounts_db/geyser_plugin_utils.rs
we want to stop persisting `write_version_obsolete` in append vecs. Geyser uses this field specifically
Always pass 0 for `write_version_obsolete` to geyser. This means geyser doesn't care what `write_version_obsolete` exists in the append vec.
Fixes #
=> decouple geyser's write_version from append vec on snapshot load

core/src/snapshot_packager_service.rs, core/tests/snapshots.rs, runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs, runtime/src/bank.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_minimizer.rs, runtime/src/snapshot_package.rs, runtime/src/snapshot_utils.rs, runtime/src/sorted_storages.rs
Moving to 1 append vec per slot. The entire snapshot storage path used a Vec<> per slot.
Convert this code path to use `Vec<AccountStorageEntry>` per slot.
Fixes #
=> snapshot storage path uses 1 append vec per slot

ledger/src/blockstore_processor.rs, sdk/src/feature_set.rs
An inactivated feature that meant to check block cost limits during replay is dated - it only checks accumulates transaction costs against block limit, which is only a subset of `cost_tracker.would_fit()`. Should symmetrically use `cost_tracker` in replay (in separate PR)
- remove inactivated feature, and its direct implementation. 
Fixes #
=> remove dated cost checking feature

runtime/src/sorted_storages.rs
A few months ago, we could iterate a slot range to get accounts in storages merged with accounts in the write cache. With the addition of accounts background service to startup, this became no longer viable. So, the ability to merge in write cache accounts with storages was removed. However, `SortedStorages` still maintained a data structure to support the old behavior.
Ancient append vecs have been enabled in master. However, they are not useful until the feature is activated to eliminate rewrites. At that point, the validator will be accumulating very old slots and the associated storages. The result will be a very large range of slots in `SortedStorages`. This would result in an ever growing `Vec<>` over that range. That is totally unnecessary and increasingly wasteful. …
=> SortedStorages holds HashMap instead of Vec

entry/src/poh.rs, poh/src/poh_recorder.rs, runtime/src/bank.rs, sdk/src/feature_set.rs
There currently exists no mechanism for being able to change the number of hashes per tick.
1. Add new feature to control updating hashes per tick on epoch boundary (to `DEFAULT_HASHES_PER_SECOND`)
2. When synchronizing PoH with a bank, update hashes per tick from the bank value
3. Reset PoH from `set_bank` when a new `hashes_per_tick` value is detected
4. Remove `poh_config` from `PohRecorder`
Note 4 above is the key change that gets things working. With naive implementation, we see PoH continue building up tick entries with old ticks_per_slot, and once the bank with updated ticks_per_slot gets assigned, it sends these old entries associated with the new bank and Blockstore barfs. We need to kill these old tick entries and restart with updated `hashes_per_tick`
PoH will derive …
=> Configurable hashes per tick

runtime/src/accounts_db.rs, runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_minimizer.rs, runtime/src/sorted_storages.rs
Old types make code more confusing. Vec<> is a straightforward type.
Replace `SnapshotStorage` with `Vec<SnapshotStorageOne>` for functions which make sense.
`SnapshotStoragesOne` is the placeholder type at the moment for what is held in a snapshot package.
Renames coming once we get down to the right types everywhere.
Fixes #
=> remove type SnapshotStorage and uses

docs/src/developing/clients/jsonrpc-api.md
getRecentPrioritizationFees endpoint is still unstable. Docs also missing some useful details.
Mark as unstable and update docs
=> Update getRecentPrioritizationFees json-rpc docs

sdk/program/src/message/versions/v0/mod.rs
`message::versions::v0::Message` implementation of `Sanitize` allows for up to 256 accounts to be specified, but account loads are capped lower in `Bank::get_transaction_account_lock_limit`
add a comment to highlight the discrepancy
=> add note about discrepancy between accounts load and sanitize caps

runtime/src/accounts_db.rs, runtime/src/bank.rs
`get_slot_stores(slot)` returns internals of the map and callers expect `Vec<...>` return value.
`get_slot_storage_entry(slot)` addresses both problems.
`get_slot_stores` -> `get_slot_storage_entry`
Fixes #
=> get_slot_stores -> get_slot_storage_entry

quic-client/Cargo.toml, streamer/Cargo.toml
Currently, Solana advertises support for legacy TLS 1.2 cipher suites (`0xc0??`).
TLS 1.3 is widely supported at this point -- for security and simplicity, support for TLS 1.2 should be disabled.
```
Cipher Suites (10 suites)
Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
Cipher Suite: …
```
=> disable rustls tls12 feature

streamer/src/tls_certificates.rs
QUIC allows clients to use certificate chain during connection setup. Solana's use case is restricted to using single self signed certificates. The code should be updated to this specific use of the API.
Updated code to restrict using single self signed certificates.
Fixes #
=> Restrict QUIC to use single self signed client cert

client/src/connection_cache.rs, quic-client/src/lib.rs, quic-client/src/nonblocking/quic_client.rs, quic-client/tests/quic_client.rs, streamer/src/nonblocking/quic.rs, streamer/src/quic.rs, streamer/src/tls_certificates.rs
QUIC client certificate code can use cleanup. It's using single self signed certificate, but the functions support certificate chains.
Updated the functions to use single certificate instead of a vector/slice of certificates.
Fixes #
=> Cleanup QUIC single signed client cert code

core/src/sample_performance_service.rs, ledger/src/blockstore.rs, ledger/src/blockstore_db.rs, ledger/src/blockstore_meta.rs, rpc/src/rpc.rs
As part of work on https://github.com/solana-labs/solana/issues/29159 we need to store "non-vote transaction counts" in the blockstore.
Store non-vote transaction counts that will be recorded by the banks into the `blockstore`.
Part of work on #29159
=> ledger/blockstore: PerfSampleV2: num_non_vote_transactions

tokens/src/arg_parser.rs, tokens/src/main.rs
Confusing error:
```
$ solana-tokens distribute-spl-tokens --db-path db.db --fee-payer payer.json --input-csv /dist.csv  --from <TOKEN_ACCOUNT> --owner payer.json --url mainnet-beta
Error: ProgramError(InvalidAccountData)
```
This is being thrown because `solana-tokens` doesn't know about monikers, and is trying to query account states from a non-existent cluster. Arguably, the error should be more descriptive, but also, it would be nice to support monikers, and the short `-u` for url.
Add short flag for url and config
Support parsing monikers in url parameter
cc @danpaul000
=> Support monikers in solana-tokens

runtime/src/accounts.rs, runtime/src/accounts_db.rs
Moving to 1 append vec per slot so we can get rid of `write_version`.
Get rid of code that was using `write_version` to handle multiple append vecs since that is no longer possible to encounter.
Fixes #
=> remove some uses of write_version

docs/src/developing/clients/jsonrpc-api.md
Fee data returned is per-compute-unit, but docs imply that it is the total fee for the transaction
Fix
=> getRecentPrioritizationFees docs: make clear that fee is per compute-unit

streamer/src/nonblocking/quic.rs
quic server logs `accept()` timeouts (no client has attempted to connect in the last 1s) at info level and with an ambiguous message
* demote it
* mention that it originates from `accept()`
=> quic-server: demote and annotate noisy, ambiguous log message

programs/bpf_loader/src/lib.rs, programs/sbf/benches/bpf_loader.rs, programs/sbf/tests/programs.rs, runtime/src/loader_utils.rs
[`GTUMCZ8LTNxVfxdrw7ZsDFTxXb7TutYkzJnFwinpE6dg`](https://github.com/solana-labs/solana/pull/23757) has been activated on all networks.
Removes the deployment functionality of the deprecated BPF loader and adjusts the tests.
=> Cleanup - `disable_deprecated_loader`

gossip/src/cluster_info.rs, gossip/src/cluster_info_metrics.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_pull.rs, gossip/src/crds_gossip_push.rs, gossip/tests/crds_gossip.rs
Amplifying gossip peer sampling weights by the time since last pull-request has undesired consequence that a node coming back online will see a huge number of pull requests all at once.
This "time since last request" is also unnecessary to include in weights because as long as sampling probabilities are non-zero, a node will be almost surely periodically selected in the sample.
The commit reworks peer sampling probabilities by just using (dampened) stakes as weights.
=> reworks weights for gossip pull-requests peer sampling

core/src/cluster_nodes.rs, core/src/shred_fetch_stage.rs, ledger/src/shred.rs, sdk/src/feature_set.rs
Need to temporarily drop merkle shreds from testnet so that https://github.com/solana-labs/solana/pull/29339 and https://github.com/solana-labs/solana/pull/29427 can be merged and released. 
added feature to (temporarily) drop merkle shreds from testnet
Feature Gate Issue: https://github.com/solana-labs/solana/issues/29712, https://github.com/solana-labs/solana/issues/29713
=> adds feature to (temporarily) drop merkle shreds from testnet

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Change iterator to not expose internals of `map`. This allows refactoring the internal type of `AccountStorage`.
Also, iterator only returns a single append vec from each slot. Nobody is producing multiple append vecs per slot anymore.
Fixes #
=> iterate contents of AccountStorage without exposing internals

runtime/src/account_storage.rs, runtime/src/accounts_db.rs, runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
Change data type in `AccountStorage` to a single `Arc<AccountStorageEntry>` instead of `Vec<Arc<AccountStorageEntry>>`
It will now no longer be possible to have anything but 1 append vec per slot.
Fixes #
=> AccountStorage only holds a single append vec

core/src/packet_deserializer.rs
(no rush; no need to work on weekend)
as discussed here (https://github.com/solana-labs/solana/pull/25172/files#r1044407292), overflow check isn't needed and is inconsistent even with nearby code.
just remove it along side with some cleanings
as pointed here (https://github.com/solana-labs/solana/pull/29196#discussion_r1046146323), this change must preceed prior to my banking tracer pr: #29196
cc: @apfitzge, @ryleung-solana 
Fixes #
=> Remove PacketDeserializer's extra overflow guard

programs/sbf/tests/programs.rs, runtime/src/loader_utils.rs
The state of the madness is currently neither documented nor covered by test cases (except for redeployment). Here is the effect of a top-level upgradeable loader instruction on subsequent instructions in the same transaction:
| Action | top-level-instruction | CPI-instruction |
| --- | --- | --- |
| deployment | invisible | visible |
| redeployment (upgrade) | visible | visible |
| undeployment (close) | invisible | invisible |
CPI-instructions themselves can not invoke the upgradeable loader to perform these actions.
- Unifies `test_program_sbf_upgrade_and_invoke_in_same_tx()` and `test_program_sbf_upgrade_self_via_cpi()` into `test_program_sbf_invoke_in_same_tx_as_redeployment()`.
- Adds `test_program_sbf_invoke_in_same_tx_as_deployment()` and …
=> Adds symmetric tests for all cases of un-/re-/deployment inside the same transaction

runtime/src/accounts_db.rs
We have moved to 1 append vec per slot. Write version will no longer be relevant. Soon we hope to always write `0` for write_version. A new append vec file format will not even have this field.
Stop checking `write_version_obsolete` while iterating.
Fixes #
=> remove some write_version checking

runtime/src/accounts_db.rs
We moved to 1 append vec per slot. `fn slot_stores` is an antiquated name.
Replace the uses of `fn slot_stores(...)` with `is_empty_entry(...)`
Fixes #
=> remove test method slot_stores

ci/do-audit.sh, ci/publish-crate.sh, ci/test-bench.sh, ci/test-checks.sh, ci/test-stable.sh, scripts/cargo-for-all-lock-files.sh
Replacing `./cargo` with `cargo` where it is possible
There are two commits:
* Replace ./cargo with cargo in [cargo-for-all-lock-files.sh](https://github.com/solana-labs/solana/commit/54010231bb1f85b2f6768e5fab315863c97ead41)
* The same with all shell scripts in the ci folder
=> Add toolchain file usage

runtime/src/accounts_db.rs
We moved to 1 append vec per slot.
remove test method `get_storages_for_slot()`
Fixes #
=> remove test method get_storages_for_slot

gossip/src/cluster_info.rs, gossip/src/crds_value.rs, sdk/src/lib.rs, version/src/legacy.rs, version/src/lib.rs
Need to distinguish clients from each other: solana-labs vs jito vs firedancer etc
https://discord.com/channels/428295358100013066/439194979856809985/1062127366756909197
* 1st commit renames old `{,Legacy}Version` to `LegacyVersion{1,2}`.
* 2nd commit adds new `solana_version::Version` with `ClientId`.
* also removed `Option` around `commit` and using `serde_varint`.
=> adds new solana_version::Version with ClientId

core/src/repair_generic_traversal.rs, ledger/src/blockstore.rs
`MAX_TURBINE_PROPAGATION_IN_MS` is used as a delay threshold for issuing shred repairs and analysis (see #28638) is showing we are overly aggressive in requesting repairs. Shreds show up via turbine before the repair completes the vast majority of the time
Increase constant from 100ms to 200ms. This value was shown to significantly reduce the number of repairs requested without impacting block 'is_full' times
=> Increase turbine propagation const

core/src/serve_repair.rs
#28673 should be enabled for mainnetbeta
See #28673 #29163
Enable oversampling of repair requests to prioritize by stake.
Fixes #
=> prioritize repair requests by stake

ledger-tool/src/main.rs
The existing logic will clean account paths only when we had secondary access to the blockstore. However, the access mode shouldn't dictate when we clean accounts data.
We can and should clean account data from previous runs in all instances given that we always start over from a snapshot. So, move the logic to clean old account data in all scenarios. We're about to start writing to that directory anyways.
This is expanding the logic added in https://github.com/solana-labs/solana/pull/27622 to all blockstore access mode scenarios.
=> ledger-tool: Clean account paths in all cases

docs/.gitignore, docs/docusaurus.config.js, docs/layouts/CardLayout.js, docs/package-lock.json, docs/package.json, docs/src/cluster/commitments.md, docs/src/developing/intro/programs.md, docs/src/developing/intro/rent.md, docs/src/developing/intro/transaction_fees.md, docs/src/developing/lookup-tables.md, docs/src/developing/versioned-transactions.md, docs/src/getstarted/hello-world.md, docs/src/getstarted/local.md, docs/src/getstarted/rust.md, docs/src/pages/developers.js, docs/src/pages/getstarted.jsx, docs/src/terminology.md, docs/src/transaction_fees.md
Docusaurus version is outdated, running on v2.0 "beta" version
- upgraded Docusaurus packages to v2.2
- updated Algolia keys for the new version
- changed .md front-matter `keywords` to arrays to satisfy Docusaurus
- corrected broken internal link on a page
- added `yarn.lock` to `.gitignore` to prevent future build warning
- added code block theme support for the Rust lang!
- corrected invalid `Link` child component
=> docs: update Docusaurus to v2.2

docs/README.md
Many people struggle to get the Docs site running locally, partially due to lack of documentation on the process. 
updated the `docs/readme.md` to add amplifying information on getting the docs site running local
=> docs: updated readme

Cargo.lock, cli-output/src/cli_output.rs, cli-output/src/display.rs, install/src/command.rs, programs/config/src/date_instruction.rs, tokens/Cargo.toml, tokens/src/db.rs
(no rush; no need to work on weekend)
#29196 is blocked on chrono version bump (via `rolling-file` crate, which is newly added there).
cc: @apfitzge 
Update chrono to v0.4.23: https://github.com/chronotope/chrono/releases/tag/v0.4.23
Acoompanied code change is due to `chrono`'s new deprecations. Basically, it's trying to get rid of `panic!()` even with out-of-range inputs in those deprecated API, forcing users to handle errors gracefully while relieving users from validating complex human's calendar (i think this is sensible, considering it's _time_ library) https://github.com/chronotope/chrono/issues/815. so, although I just lazily resorted to `.unwrap()` naively, it's completely non-functional-change. ;)
=> Bump chrono to v0.4.23

core/src/banking_stage.rs
(no rush; no need to work on weekend)
There's remaining instances of stale variable names for the type of `ReplayVote{Sender/Receiver}`.
hmm, actually, i found that it's not _stale_ after some `git log` unfolding.... it seems that the var name and type name were inconsistent since the beginning...: https://github.com/solana-labs/solana/pull/11434/files#r1070596384 (#11434).... 
(
I think it's a bit off that we call this type as `*Replay*Vote{Sender,Receiver}` considering its usage inside BankingStage. yet again `*gossip*_vote_{sender,receiver}` is misnomer too, considering it's not only gossip but all of committed votes in banking stage is sent over the channel (including vote tpu, non-vote tpu origins).... Fixing this is out of scope, I'll just align all to type names.... cc: @carllin …
=> Rename remaining ones to replay_vote_{sender,receiver}

explorer/src/components/account/AnchorAccountCard.tsx
In the explorer, the `/anchor-account` card throws an unhandled error and crashes in case the anchor account parsing fails.
Example: https://explorer.solana.com/address/5VsCBvW7CswQfYe5rQdP9W5tSWb2rEZBQZ2C8wU7qrnL/anchor-account
Add error handling to print the error out to the console and have the card display the `ErrorCard` instead of crashing the explorer.
Fixes #29294
=> Explorer: Fix crash on failed anchor account parsing

ledger/src/blockstore_processor.rs, runtime/src/bank_utils.rs
This reverts commit b4237f3f2cbdacc06ca9b81f54e6b096cc3b4110.
Usually votes ingested from gossip for optimistic confirmation are verified in `ClusterInfoVoteListener` via `verify_votes` in `recv_loop()`: https://github.com/solana-labs/solana/blob/b1340d77a2166448b18b7c6042261fac07599f8b/core/src/cluster_info_vote_listener.rs#L320-L323
However, votes sent from `BankingStage` and `ReplayStage` to `ClusterInfoVoteListener` are ingested via a separate loop https://github.com/solana-labs/solana/blob/b1340d77a2166448b18b7c6042261fac07599f8b/core/src/cluster_info_vote_listener.rs#L291
`process_votes_loop()`, where it's assumed that those votes have been verified by `BankingStage` and `ReplayStage`.
Thus signatures of authorized voters sent from `ReplayStage` and `BankingStage` are not verified …
=> Revert "Do not exclude failed simple vote transactions from consensus"

explorer/src/components/transaction/ProgramLogSection.tsx
There is no way to view raw program instruction logs of historical data for debugging purposes on the explorer
The following screenshots are from the following transaction on devnet: https://explorer.solana.com/tx/3x661bDMK811eRhrZ1uNXRKBm963qREKdhve1bKzoSE572N6v5P4oRCXiHb5PL3oeU9QxcjgDN3XtN3qW8JmXSn8?cluster=devnet
Before the changes:
After the changes:
After the changes, on clicking the `<> Raw` button:
Add the `<> Raw` button to the program instruction logs like it is done for the instruction and have it display the raw logs
Fixes #23784
=> Explorer: Add toggle for raw tx logs

account-decoder/src/parse_vote.rs, cli-output/src/cli_output.rs, core/src/commitment_service.rs, core/src/consensus.rs, core/src/replay_stage.rs, core/src/verified_vote_packets.rs, core/src/vote_simulator.rs, ledger-tool/src/main.rs, programs/vote/src/vote_state/mod.rs, rpc/src/rpc.rs, runtime/src/vote_transaction.rs, sdk/program/src/vote/state/mod.rs
lack of encapsulation in `vote_state::Lockout` clutters https://github.com/solana-labs/solana/pull/29524 with unnecessary plumbing
encapsulate it
this should be purely cosmetic aside from the note below
=> vote: encapsulate `Lockout`

.github/workflows/crate-check.yml, .github/workflows/docs.yml
I only set current commit for push event as COMMIT_RANGE so we got empty value when we `git diff $COMMIT_RANGE`
use HEAD~1..HEAD as commit range
=> ci: fix commit range in push event

core/src/banking_stage.rs, core/src/banking_stage/packet_receiver.rs
Split packet receiving and buffering into a separate module from BankingStage.
Fixes #
=> BankingStage Refactor: Move packet receiving and buffering functions to separate module

runtime/src/snapshot_utils.rs, sdk/program/src/nonce/state/current.rs, sdk/program/src/stake/state.rs
Manual `impl Default for` enums is unnecessary and verbose.
removed manual implementations of `Default` for enums
=> removes manual implementations of Default for enums

bench-tps/src/bench.rs, bench-tps/src/cli.rs
bench-tps currently has entirely non-conflicting transactions which is not useful if we want to measure performance under contentious load.
Add a new cli arg to `bench-tps`: `--num-conflict-groups <num_conflict_groups>` which gives us a lever to control how many txs conflict.
The number of "conflict groups" determines how many unique destination accounts we have per chunk. This means that the lower number of conflict groups means more contention, `num_conflict_groups = 1` is the maximum contention we can have (every transaction in a chunk conflicts).
Related #29126 
Fixes #
=> Add conflict groups to bench-tps

validator/src/cli.rs, validator/src/main.rs
operators pass `--no-duplicate-instance-check` without understanding its repercussions
remove it, retaining plumbing in case we need it for testing
=> validator: remove `--no-duplicate-instance-check`

core/src/cluster_nodes.rs, core/src/retransmit_stage.rs
Turbine excludes the slot leader from the random shuffle when broadcasting shreds. Doing so, shreds should never loopback to the leader. If shreds reaching retransmit stage are from the node's own leader slot they cannot be retransmited to any nodes.
error out when retransmit loopbacks to the slot leader
=> errors out when retransmit loopbacks to the slot leader

core/src/banking_stage.rs, core/src/lib.rs, core/src/next_leader.rs, core/src/voting_service.rs
**Simple Move PR**
These functions are only used by the packet forwarding logic of banking stage, but are used outside of banking stage. For this reason I've split these functions out entirely separate, and they will be used by forwarding module in follow-up PR.
Fixes #
=> BankingStage Refactor: Separate Next Leader Functions

faucet/src/faucet.rs, validator/src/bin/solana-test-validator.rs, validator/src/cli.rs
Some of the faucet flags are not present in the test-validator.
Expose more of the faucet flags in the test-validator. I kept these in SOL to keep this consistent with the `faucet-sol` flag.
=> faucet: Expose time-slice, per-time-cap, and per-request-cap in test validator

core/src/sigverify_shreds.rs, core/src/tvu.rs, sdk/src/signer/keypair.rs
Sigverify-shreds discards shreds from node's own leader slot:
https://github.com/solana-labs/solana/blob/6baab92ab/core/src/sigverify_shreds.rs#L153-L154
But if the identity is hot-swapped the pubkey would be wrong since it is instantiated only once at startup:
https://github.com/solana-labs/solana/blob/6baab92ab/core/src/tvu.rs#L168
Don't store the pubkey but instead read it directly from cluster-info.
=> patches bug in sigverify-shreds when identity is hot-swapped

runtime/src/bank.rs
The `bank_transaction_count_fix` [gated feature](https://github.com/solana-labs/solana/issues/29349) is now active on all clusters. But the gating logic is still in place, and it tedious to work around.
Remove feature-gated logic
Closes #29349
=> Remove bank_transaction_count_fix logic

core/src/ledger_cleanup_service.rs, ledger/src/blockstore_db.rs
Currently, the cleanup service counts the number of shreds in the database by iterating the entire SlotMeta column and reading the number of received shreds for each slot. This gives us a fairly accurate count at the expense of performing a good amount of IO.
Instead of counting the individual slots, use the live_files() rust-rocksdb entrypoint that we expose in Blockstore. This API allows us to get the number of entries (shreds) in the data shred column family by reading file metadata. This is much more efficient from IO perspective.
Fixes #28403
=> Reduce the amount of IO that LedgerCleanupService performs

core/src/serve_repair.rs
Need to keep these types backward compatible.
Added `frozen_abi` annotations.
=> adds frozen_abi annotations to repair service enums/structs

core/src/heaviest_subtree_fork_choice.rs, core/src/repair_weight.rs
When dumping slot from replay the parent info wasn't being properly cleared (although the tree was orphaned) in the repair weighting tree. This causes a panic if you have a chain of dumped slots all orphaned together that then link back in the same manner. 
```thread 'solRepairSvc' panicked at 'called `Option::unwrap()` on a `None` value', core/src/heaviest_subtree_fork_choice.rs:589:42```
Clear the parent + add test
Additionally this fixes the flakiness in the `test_duplicate_shreds_broadcast_leader` local-cluster test. 
Fixes #29792
=> Clear parent in repair weighting when dumping from replay

core/src/sigverify_stage.rs
find_packet_sender_stake_stage::FindPacketSenderStakeReceiver is quite verbose to include in function arguments, and type name is descriptive enough that it doesn't need to be qualified with the crate name in every instance.
Fixes #
=> Cleanup FindPacketSenderStakeReceiver function args

local-cluster/tests/common.rs
QUIC server may close connection when max peer connections is exceeded. See #29602 for an example of a failing test that encounters this case intermittently.
Restrict the TPU connection pool size to 2 (down from current default value of 4) to limit number of parallel connections coming from clients and eliminate possibility of exceeding max peer connections
=> Reduce TPU connection pool size for test

ci/docker-rust-nightly/Dockerfile, ci/docker-rust/Dockerfile, rust-toolchain.toml
https://blog.rust-lang.org/2023/01/10/Rust-1.66.1.html
Note, this PR only updates the stable Rust version. In Rust 1.68 (what would be the normal nightly), the layout of structs can/does change. This is manifesting in the program runtime how a few types are passed to and from the vm. These types need to be audited to see if any require a stable-layout version.
Related: #29304
=> Upgrades to Rust 1.66.1

ci/buildkite-pipeline-in-disk.sh, ci/buildkite-pipeline.sh, ci/buildkite-solana-private.sh
TLDR: We don't handle pagination for github api in our ci-gate bot. Use gh cli tool to get affected files instead.
https://discord.com/channels/428295358100013066/560503042458517505/1066925491401019462
use gh cli to get affected files
=> use gh cli to get affected files

runtime/src/accounts_db.rs
We need to combine multiple slots into ancient append vecs with a single create (as opposed to an append).
Introduce a trait `ShrinkCollectRefs` to abstract this new way to collect alive accounts.
Fixes #
=> trait ShrinkCollectRefs

core/src/staked_nodes_updater_service.rs
We do not currently include the Pubkey/stake for our own node in the shared stake node table. This table can be queried with our pubkey for determining things like connection/packet priority for TPU transactions. There are a couple places where we could send transactions to ourself:
1. In rpc when using send-transaction-service. If the leader is itself, it can send to itself.
2. When handling transaction as a leader and forwarding the excessive transactions to the next leader and that next leader happens to be itself. I think this happens relatively easily in smaller cluster like in the bench-tps. But in large cluster like MNB, chance of that happening is small.
This also has impact on local cluster testing where connection to our own node gets put in same connection table entry as client …
=> Include own node in stake table

runtime/src/accounts_db.rs
It is convenient to pass `AccountStorageEntry` (which contains `AppendVec`) instead of `AppendVec`.
We can now set alive bytes for example.
pass `AccountStorageEntry` (which contains `AppendVec`) instead of `AppendVec`. to `append_single_account_with_default_hash`
Fixes #
=> test fn append_single_account_with_default_hash uses AccountStorageEntry

runtime/src/stakes.rs
https://github.com/solana-labs/solana/pull/26479 preserves rent epoch for rent-exempt accounts; since the feature got activated, vote accounts in stakes cache have identical `rent_epoch` field as the accounts in accounts-db. The commit verifies this in stakes-cache sanity checks.
includes `rent_epoch` in vote-accounts sanity checks
=> includes rent_epoch in vote-accounts sanity checks

runtime/src/bank.rs
As Behzad pointed out, I change the name of a metric field in an unobvious way in https://github.com/solana-labs/solana/pull/29599. Changing a metric name creates a split between datapoints in metrics db between versions; old versions reports old field and new version reports new field.
Backport the field name change to v1.14 so we'll be able to view datapoints for all nodes (v1.14 and v1.15+) under one field.
Additionally, I double checked the rest of the fields as well as another PR that moved some metrics around; this was the only rename
=> Manual backport of #29599 for consistent metric name

ledger-tool/src/main.rs
`bank-hash` subcommand sets `halt_at_slot` to 0 which goes against the meaning of `halt_at_slot`, as well as not doing what the description of `bank-hash` does: "Prints the hash of the working bank after reading the ledger".
Don't set `halt_at_slot` for `bank-hash` subcommand.
Fixes #29799
=> Bugfix: bank-hash optionally takes halt_at_slot

ledger-tool/src/main.rs
Error message isn't clear from the connected slots check if halt_slot is specified incorrectly.
Add a check that `halt_slot >= starting_slot` before checking connected slots.
Fixes #
=> Check that halt_slot >= starting_slot

core/src/snapshot_packager_service.rs, core/tests/epoch_accounts_hash.rs, core/tests/snapshots.rs, ledger-tool/src/main.rs, local-cluster/src/local_cluster.rs, local-cluster/tests/common.rs, local-cluster/tests/local_cluster.rs, runtime/src/accounts_db.rs, runtime/src/hardened_unpack.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_utils.rs, test-validator/src/lib.rs, validator/src/main.rs
To allow hardlinking accounts files into snapshot directories (PR 29496), the first step is to generate run/ and snapshot directories for all the user provided account_paths. 
This is a split of the PRs https://github.com/solana-labs/solana/pull/29496 and https://github.com/solana-labs/solana/pull/28745
Add the setup_accounts_run_and_snapshot_paths function;
Add the generate_test_tmp_account_path function to be used for the tests;
Many other small changes to call the setup function to initialize the account paths. 
Fixes #
=> Add run parent directory for accounts files

core/src/replay_stage.rs
We emit a similar log with more information shortly after from Bank, so this logline is extra that occurs for every slot.
```
[2023-01-22T00:00:30.373085940Z INFO  solana_core::replay_stage] bank frozen: 173717829
[2023-01-22T00:00:30.382211976Z INFO  solana_runtime::bank] bank frozen: 173717829 hash: DVZoobrBKXLr5c5fuLSDKexwN5sJkPQc4RwZR4vttziT accounts_delta: AMUUEc9pCK6tTYujYsQgQ7imkkBUZP9DxxWxX7YvK6ot signature_count: 2823 last_blockhash: AYoJHoD9cU83f4ysG8ttyZ4CRSnop3z4KfFuzJGRfVBy capitalization: 539127927997816978
[2023-01-22T00:00:30.714653459Z INFO  solana_core::replay_stage] bank frozen: 173717830
[2023-01-22T00:00:30.719940414Z INFO  solana_runtime::bank] bank frozen: 173717830 hash: 9U3azf5wb41xoa8DNctK8bRN5SPiFnWnmNx7YojtJPup accounts_delta: …
```
=> Remove duplicate bank frozen log from ReplayStage

net/remote/remote-node.sh
The bootstrap node creates the bootstrap snapshot at slot 0 so we do indeed want the bank hash at slot 0. However, stricter error checking in solana-ledger-tool made it such that the bank-hash command would error.
Specify slot 0 as the slot we want bank hash for. See https://github.com/solana-labs/solana/issues/29799 for more context; this must go in after https://github.com/solana-labs/solana/pull/29865
=> Use halt-at-slot to specify getting bank-hash for slot 0

program-test/src/lib.rs, program-test/src/programs.rs
While working on #29878, I noticed that the lamports for accounts are using `rent.minimum_balance(...).min(1)`, which will just put 1 lamport in the account, which won't reflect what's on mainnet.
Use `max` instead of `min`, which I think is the intended behavior.
Fixes #
=> program-test: Use "max" for program account lamports

Cargo.lock, banking-bench/src/main.rs, core/Cargo.toml, core/benches/banking_stage.rs, core/benches/banking_trace.rs, core/benches/sigverify_stage.rs, core/src/banking_stage.rs, core/src/banking_trace.rs, core/src/cluster_info_vote_listener.rs, core/src/leader_slot_banking_stage_metrics.rs, core/src/lib.rs, core/src/packet_deserializer.rs, core/src/replay_stage.rs, core/src/sigverify.rs, core/src/sigverify_stage.rs, core/src/tpu.rs, core/src/tvu.rs, core/src/validator.rs, ledger/src/blockstore.rs, local-cluster/src/validator_configs.rs, perf/src/cuda_runtime.rs, perf/src/packet.rs, programs/sbf/Cargo.lock, sdk/Cargo.toml, sdk/src/packet.rs, validator/src/cli.rs, validator/src/main.rs
It's hard to reproduce/examine past banking-related performance problems which are observed only at mainnet-beta.
The underlying problem is that it's not easy to create a similar load on test/dev environments. Worse, we also don't have good visibility of actual load due to limited set of metrics, which are indirect by nature and aggregated in ad-hoc definitions.
This is especially so for banking, say unlike replay performance. That's because any discarded packets are unavailable afterwards like later investigating/benchmarking.
Lastly, the performance profile of banking isn't linear by any means as well. There's various factors affecting its throughput (account access pattern, qos, resource contentions across banking threads...)
So, let's get to bottom of this.
Namely, start to collect …
=> Add fully-reproducible online tracer for banking

ledger-tool/src/main.rs
Fix https://github.com/solana-labs/solana/issues/29799
Special case slot 0 for block connectness check.
Fixes #
=> Special case slot 0 for block connectness check in ledger tool

core/src/snapshot_packager_service.rs, core/tests/epoch_accounts_hash.rs, core/tests/snapshots.rs, ledger-tool/src/main.rs, local-cluster/src/local_cluster.rs, local-cluster/tests/common.rs, local-cluster/tests/local_cluster.rs, runtime/src/accounts_db.rs, runtime/src/hardened_unpack.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_utils.rs, test-validator/src/lib.rs, validator/src/main.rs
This PR is causing OOM on master.  Reverting it for now.
This reverts commit 74f89d149490055019898f13c8654be94affe820.
https://github.com/solana-labs/solana/pull/29496 is is causing OOM.
Reverting the commit.
Fixes #
=> Revert "Add run parent directory for accounts files (#29794)"

sdk/program/src/message/legacy.rs, sdk/program/src/message/mod.rs, sdk/program/src/message/versions/v0/mod.rs
The `CompileError` is not properly exposed to outside users when trying to compile v0 messages.
Keep the `compiled_keys` module private, but only expose the `CompileError` type. We can also expose the `compiled_keys` module and force everyone to go through that, but this seemed a bit cleaner since nothing else is exposed from `compiled_keys`.
Fixes  #29858
=> sdk: Expose `CompileError` to the outside

genesis/src/main.rs
While investigating adding upgradeable programs to solana-genesis, I got confused by the existing `--bpf-program` parameter, as the `value_name` is inconsistent with actual usage.
Fix it
=> solana-genesis: fix bpf-program value_name

core/src/sigverify_stage.rs, perf/benches/dedup.rs, perf/src/deduper.rs, perf/src/lib.rs, perf/src/sigverify.rs
`Deduper` is used by `SigverifyStage` to remove obvious duplicates before performing an expensive sig-verification; but, the content of `Deduper` is decoupled enough from sigverify that it can be broken out into its' own file for the sake of reducing clutter.
No functional changes, just a straight move up move of `Deduper` impl + tests.
=> Move Deduper into a separate file

core/src/replay_stage.rs, geyser-plugin-interface/src/geyser_plugin_interface.rs, geyser-plugin-manager/src/block_metadata_notifier.rs, geyser-plugin-manager/src/block_metadata_notifier_interface.rs
Ability to construct full block with geyser interface.
https://docs.rs/solana-storage-proto/1.14.13/solana_storage_proto/convert/generated/struct.ConfirmedBlock.html
Currently we can construct all transactions from `notify_transaction` but we still need `previous_blockhash` + `parent_slot`.
There also a question, do I understand correctly that number of transactions in the block should be equal to `executed_transaction_count`?
Add `previous_blockhash` + `parent_slot` to `ReplicaBlockInfoV2`
=> geyser: add parent slot/blockhash to block

streamer/src/nonblocking/quic.rs
Multiple QUIC connections can originate from the same client endpoint. All of them will have the same peer address, port and pubkey. When a connection disconnects (due to close, timeout or any other error), the server calls `remove_connection()` to remove the entry from its connection table. The current code is removing all the connections that match the peer IP/Pubkey, and  port). This will result in removing the connections that might still be active.
Each QUIC connection has a `stable_id` that's specific to the connection (and doesn't change over the lifetime of the connection). This PR updates the `remove_connection()` code to match the `stable_id` of the connection that's being removed with the connections in the table. It also adds a test to make sure the specific connection is …
=> Remove the specific QUIC connection entry that disconnected

core/src/banking_stage.rs, core/src/banking_stage/committer.rs, core/src/qos_service.rs
**Simple Move PR**
Moved transaction committing functions into separate module.
Blocked by #29401
Fixes #
=> BankingStage Refactor: Separate transaction commiting module

.mergify.yml
The `automerge` label doesn't work, eg: https://github.com/solana-labs/solana/pull/29903/checks?check_run_id=10882505832
Fix by removing references to non-existent dont-squash-my-commits team
@yihau , sorry I can't remember... will this need to be backported, or is having the change in master enough to fix automerge for stable and beta branches?
=> Fix mergify, vis-a-vis missing dont-squash-my-commits team

scripts/cargo-fmt.sh
`scripts/cargo-fmt.sh` assumes it is being run from the repo root
resolve absolute paths to the subject directories
=> make `scripts/cargo-fmt.sh` $PWD agnostic

programs/vote/src/lib.rs, programs/vote/src/vote_processor.rs, programs/vote/src/vote_state/mod.rs, sdk/program/src/vote/state/mod.rs
Still some lingering uses of `#![allow(clippy::integer_arithmetic)]` in the vote program.
Eliminate them by using checked or saturating arithmetic.
Left `vote_state_0_23_5` alone since it's not in use anymore. 
Fixes #
=> Eliminate unchecked arithmetic in vote program

faucet/src/faucet.rs, ledger/src/blockstore_db.rs, remote-wallet/src/remote_wallet.rs, runtime/src/accounts_db.rs, runtime/src/sorted_storages.rs, runtime/src/stakes.rs, sdk/src/signer/keypair.rs, sdk/src/transaction_context.rs
`cargo +nightly doc` generates a number of warnings.
Quote type references and some text that should be treated as code.
=> doc: Fix documentation warnings and add some links

Cargo.lock, frozen-abi/src/abi_example.rs, gossip/Cargo.toml, gossip/src/cluster_info.rs, gossip/src/cluster_info_metrics.rs, gossip/src/contact_info.rs, gossip/src/crds.rs, gossip/src/crds_gossip_pull.rs, gossip/src/crds_gossip_push.rs, gossip/src/crds_value.rs, gossip/src/lib.rs, programs/sbf/Cargo.lock
* Need to add/remove sockets from `ContactInfo` in a backward and forward compatible way.
* Current sockets specification in `LegacyContactInfo` is inefficient and unnecessarily duplicates IP addresses.
Implemented a new `ContactInfo` where
* Ports and IP addresses are specified separately so that unique IP addresses can only be specified once.
* Different sockets (tvu, tpu, etc) are specified by opaque `u8` tags so that adding and removing sockets is backward and forward compatible.
* `solana_version::Version` is also embedded in so that it won't need to be gossiped separately.
* In order to identify duplicate running instances, the struct also includes when the instance was first created and so the separate `NodeInstance` crds-value will become redundant.
Update plan:
* Once the cluster …
=> adds new contact-info with forward compatible sockets

ledger/src/blockstore_db.rs, zk-token-sdk/src/encryption/elgamal.rs, zk-token-sdk/src/encryption/pedersen.rs
Clippy warning exception is no longer necessary.
Clippy does not seem to be complaining anymore.  It looks like this rule is now only applied to methods that take `self` as the first argument:
https://github.com/rust-lang/rust-clippy/blob/a9c251f11d2a07ec57ca4b8e17674f7f29daf249/clippy_lints/src/methods/wrong_self_convention.rs#L106
=> ledger: Remove `clippy::wrong_self_convention`

ledger/src/blockstore_db.rs
Some type references are not property marked in the doc-comments.  As a result, they are not shown as links in the generated documentation.
Add proper decorations to have more links in the generated docs.
=> doc: ledger::blockstore_db::columns: Add links

core/src/staked_nodes_updater_service.rs
`staked_nodes_updater_service` is unnecessarily locking gossip repeatedly to obtain same set of nodes:
https://github.com/solana-labs/solana/blob/bd9b311c6/core/src/staked_nodes_updater_service.rs#L128-L129
Obtain gossip nodes only once out of the loop.
=> removes staked-nodes updater service excessive locks on gossip

ledger/src/blockstore_meta.rs
When reading the `completed_data_indexes` I was confused, assuming it stores indices of all received shard.
It is also possible to add `SlotMeta` to the generated docs, as it is a public structure.
Clarify field behaviors.
Change `SlotMeta` comments into doc-comments.
=> doc: ledger: SlotMeta: Clarify `consumed` and `completed_data_indexes`

validator/src/main.rs
Call the macro once, and simplify some logic for creating owned copy (String) of the version text.
=> chore: Cleanup repeat instances of solana_version!()

ledger-tool/src/main.rs
Duplicate call to function; only call it once
=> ledger-tool: Remove duplicate open_genesis_config_by() call

cli/src/cluster_query.rs
In #29731, the lamports-per-* field were removed since all accounts must be rent exempt moving forward. However, this broke backwards compatibility of the command by removing two fields.
This change reintroduces those fields, and hard-codes them to 0. However, the change to omit fields from Display implentation is persisted.
With this PR,
```
$ cargo run -- rent 123          
Finished dev [unoptimized + debuginfo] target(s) in 0.61s
Running `/.../solana rent 123`
Rent-exempt minimum: 0.00174696 SOL
$ cargo run -- rent 123 --output json
Finished dev [unoptimized + debuginfo] target(s) in 0.60s
Running `/.../solana rent 123 --output json`
{
"lamportsPerByteYear": 0,
"lamportsPerEpoch": 0,
"rentExemptMinimumLamports": 1746960
}
```
=> Restore compatibility for solana rent --output json command

runtime/src/block_cost_limits.rs, runtime/src/cost_model.rs
These three built-in programs have no cost defined. 
Replayed a random set of mainnet-beta snapshots, collected the program's executing time, compare to `system` program, the results are: 
|built-in | times of system program |
|------|------|
|ComputeBudget111111111111111111111111111111| 1 |
|AddressLookupTab1e1111111111111111111111111| 5 |
|BPFLoaderUpgradeab1e11111111111111111111111| 155|
Add static costs for them
Fixes #
=> add cost to additional built-in programs

runtime/src/accounts_db.rs, runtime/src/bank.rs, runtime/src/stakes.rs
Add test around activation of rent_epoch max feature.
This test verifies that activating the feature keeps the stakes cache up to date.
Note that this test fails unless I remove the assert:
`test_stake_vote_account_validity`
Add ability to cause stakes cache mismatches to assert for testing.
Fixes #
=> add test_stake_account_consistency_with_rent_epoch_max_feature

core/src/shred_fetch_stage.rs
Initial patch https://github.com/solana-labs/solana/pull/29711 restrained the feature gate only to testnet cluster, because merkle shreds have only partially been rolled out to testnet.
However it does not hurt to be able to feature gate the merkle shreds on all clusters; 
(just to keep our hands open, might not need the feature though).
feature gate merkle shreds on all clusters
=> feature gates merkle shreds on all clusters

gossip/src/crds_gossip.rs, gossip/src/crds_gossip_push.rs, gossip/src/push_active_set.rs, gossip/src/received_cache.rs
Outdated gossip crds upserts from push messages should also be recorded in received-cache for later pruning.
Record outdated gossip crds upserts from push messages in received-cache
=> records outdated gossip crds upserts in received-cache

runtime/src/cost_model.rs
function `sum_without_bpf()` is not used externally.
remove it
Fixes #
=> refactor: remove obsoleted function

ledger-tool/src/main.rs
The logic was searching for argument in global argument matches when it should have been searching in the subcommand matches.
Match `accounts_db_ancient_append_vecs` from subcommand matches.
To illustrate, I applied this change to the tip of master immediately after the arg was matched in the `AccountsDbConfig` creation:
```rust
+                if !accounts_db_config.as_ref().unwrap().ancient_append_vec_offset.is_some() {
+                    panic!("Didn't match ancient_append_vec_offset");
+                }
```
and then ran:
```
$ cargo run --release --bin solana-ledger-tool -- verify --ledger ~/empty_ledger/ --accounts-db-ancient-append-vecs 5
```
which yielded:
```
thread 'main' panicked at 'Didn't match ancient_append_vec_offset', ledger-tool/src/main.rs:2761:21
note: run with …
```
=> ledger-tool: Fix argument matching for accounts_db_ancient_append_vecs

docs/src/developing/backwards-compatibility.md
Json output should remain consistent to avoid breaking automation; however, we want to be free to update human-reader-centric output to remove output as it becomes deprecated.
=> Add backwards compatibility clarification on CLI tooling output

core/src/snapshot_packager_service.rs, core/tests/epoch_accounts_hash.rs, core/tests/snapshots.rs, ledger-tool/src/main.rs, local-cluster/src/local_cluster.rs, local-cluster/tests/common.rs, local-cluster/tests/local_cluster.rs, runtime/src/accounts_db.rs, runtime/src/hardened_unpack.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_utils.rs, test-validator/src/lib.rs, validator/src/main.rs
PR https://github.com/solana-labs/solana/pull/29794 was reverted because of OOM.  This is the resubmission with the fix.
The new image uses the run/ sub directory for the appendvec files.  When transitioning from an old image to this new image, the appendvec files in the old account_path should be cleaned up to avoid taking the space.  In the ramfs case, it was taking the memory, causing OOM.
All commits have passed the review in PR 29794 except the last one [f8f58f2](https://github.com/solana-labs/solana/pull/29942/commits/f8f58f2907406f61205988ebad45f4c0892d99c8) 
The fix is to clean up the files in the old path.
Fixes #
=> Account path add run parent with old path cleanup

runtime/src/accounts_db.rs
Reworking ancient append vecs to create in a single shot instead of appending.
Refactor `update_shrink_stats` to allow multiple passes of `rewrite_elapsed` to accumulate stats.
Fixes #
=> refactor update_shrink_stats

runtime/src/accounts_db.rs
ancient append vecs need to be built in 1 shot as opposed to being appended to.
Refactor `shrink_collect` to allow the collection of unique accounts to occur prior to calling `shrink_collect`
Fixes #
=> refactor shrink_collect

explorer/src/components/instruction/pyth/PythDetailsCard.tsx, explorer/src/components/instruction/pyth/program.ts
Some transactions related to the Pyth oracle are not displayed properly.
- Fix a bug where the instruction setMinimumPublishers was not recognized
- Fix a bug where the public keys in the instruction payload to AddPublisher and DeletePublisher where not deserialized properly.
Fixes #
=> [explorer] Fix parsing of some Pyth transactions.

web3.js/test/connection.test.ts
due to https://www.github.com/solana-labs/solana/pull/29528. the default epoch has become u64 max
change expected rentEpoch to u64 max
=> test: fix rentEpoch value

web3.js/src/connection.ts, web3.js/src/transaction/legacy.ts
The return type of `getFeeForMessage` did not match the implementation, which is nullable.
Update the typehint to reflect reality. Apologies to those of you for whom this causes your project to start failing to typecheck – please update your code to handle the possible `null` here.
Fixes #29993.
=> fix: correct return type of getFeeForMessage

core/src/result.rs, core/src/serve_repair.rs
Repair request decode and verification should return result rather than updating stats with error counts inline.
Return error code types rather than updating stats inline. (One remaining instance of inline error reporting for special case of unsigned requests which will be removed).
Changes are a subset of #29729.
Fixes #
=> restructure repair decode error handling

core/src/repair_service.rs, core/src/repair_weight.rs
stats paramaters for `get_best_weighted_repairs` are unnecessarily wrapped in `Option`s only used for tests.
replace `None` instances of options in tests with `::default()` stats variants.
Fixes #
=> get_best_weighted_repairs parameter cleanup

web3.js/rollup.config.js, web3.js/src/__forks__/browser/rpc-websocket-factory.ts, web3.js/src/__forks__/react-native/rpc-websocket-factory.ts, web3.js/src/connection.ts, web3.js/src/rpc-websocket-factory.ts, web3.js/src/rpc-websocket.ts, web3.js/test/connection-subscriptions.test.ts, web3.js/test/connection.test.ts, web3.js/test/mocks/rpc-http.ts, web3.js/test/mocks/rpc-websocket.ts, web3.js/test/nonce.test.ts, web3.js/test/transaction-payer.test.ts, web3.js/test/websocket.test.ts
Our `rpc-websockets` dependency does not guard against the underlying socket not being `OPEN` before it tries to call `send()` on the socket itself.
* When the `readyState` of a socket is `CONNECTING` and you try to call `send()`, it will fatal.
* When the `readyState` of a socket is `CLOSING` or `CLOSED` and you try to call `send()`, it will discard the call silently. A console error results sometime later, but in no event does it fatal your program.
All of this can lead to corruption of the internal state of the RPC; it can think that it's connected, able to send messages, and is owed responses, when it is not.
* Subclass `rpc-websockets` and wrap the `call()` and `notify()` methods in code that checks the `readyState` before trying to call `send()`.
Fixes #25578, #27167, #26198.
=> fix: [web3] only ever send RPC socket messages when the socket is open

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/secondary_index.rs
Secondary account indexes can become quite large for certain keys which have many associated accounts in the system and thus require many GB of ram to store and can cause the validator to OOM. When the RPC call is made to the validator it also will just spin in a core and allocate memory and the resulting request will be too large to transmit over a single RPC request requiring many seconds and hitting connection timeouts. So often even indexing these keys is not useful at least with the current apis. 
Add an RPC API that can query the list of secondary index keys and their sizes such that we can figure out which keys are taking a lot of ram and add them to the exclusion list.
Fixes # 
https://github.com/solana-labs/solana/issues/28666
=> Add an RPC API that can query the list of Top N secondary index keys and their sizes

.mergify.yml
Branches have advanced, so mergify config needs to be updated
Change branch names for beta and stable branches:
Added mergify config for v1.15
TODO: After v1.14 has supermajority stake on mainnet-beta remove the v1.13 label and associated mergify config
=> Update mergify backport actions to new version numbers v1.14 and v1.15

explorer/src/utils/tx.ts
Account Compression is SPL program on Mainnet & Devnet, but it's hard to find on explorer
Make it show up in search bar when typing "Account Compression Program"
Fixes #
=> [explorer] Add Account Compression Program to searchable programs on explorer

runtime/src/accounts_db.rs
Reworking shrinking and ancient shrink.
It is convenient to add accounts to storages and mark them alive in the index.
Add `mark_alive` option to test fns.
Fixes #
=> tests adding accounts can mark alive in index

runtime/src/accounts_db.rs
Moving towards writing ancient storages in 1 shot and handling them differently.
We currently avoid shrinking ancient append vecs that are allocated as ancient size. Soon, 'ancient append vecs' will be of varying sizes and can only be identified by slot.
Normal shrinking should ignore any ancient append vecs it may otherwise consider shrinking.
shrink does not try to shrink any append vecs that are old enough to be ancient when ancient append vecs are enabled.
Fixes #
=> shrink ignores ancient slots

bench-tps/src/cli.rs, clap-utils/src/input_validators.rs, clap-v3-utils/src/input_validators.rs, cli/src/stake.rs, cli/src/vote.rs, validator/src/cli.rs
Wanted to re-use this validator code in #29513 to check the value is in the range `1..`.
Made `is_within_range` more generic. This does change formatting of the range on error (looks like rust ranges: `input '0' out of range 1..`) 
Fixes #
=> Use RangeBounds for is_within_range

runtime/src/prioritization_fee.rs
block min fee and top 10 most expensive accounts min fee are reported to `block_min_prioritization_fee` every slot, that's more data than we need to monitor.
reports top 10 accounts min fee at `datapoint_trace!` so only configured hosts reports these datapoints.
Fixes #
=> report less datapoints to block_min_prioritization_fee

ledger-tool/src/ledger_path.rs, ledger-tool/src/main.rs
The function reports an error if ledger_path is not found in argument matches; however, ledger_path has a default value so a value will always be present. The check that actually matters is provided by canonicalize_ledger_path() which checks that a path is actually valid.
Rip out the unnecessary function.
Here is the tool's output from running without ledger path specified when a `ledger` directory doesn't exist in the current working directory. Note this is the error from `canonicalize_ledger_path()`, not `parse_ledger_path()`.
```
$ solana-ledger-tool bounds
...
Unable to access ledger path 'ledger': No such file or directory (os error 2)
```
And for completeness, here is output when `ledger` is a valid sub-directory in current working directory:
```
$ …
```
=> ledger-tool: Remove unnecessary function to parse ledger path arg

runtime/src/storable_accounts.rs
trait account(...) returns `StoredAccountMeta` in some impls.
Use account(...) to get at `StoredAccountMeta`, which contains all other fields (hash, pubkey, write_version)
Fixes #
=> simplify 2 StorableAccounts impls

runtime/src/storable_accounts.rs
Moving to writing ancient storages in 1 pass instead of appending to them.
Introduce new struct to hold the data for accounts moving from different slots into 1 target slot.
Fixes #
=> add StorableAccountsBySlot to move accounts from multiple slots to 1

runtime/src/cost_model.rs
`compute_budget` is now included in `BUILT_IN_INSTRUCTION_COSTS`, the additional `else if !compute_budget(...)` is no longer necessary.
- remove obsoleted else..if clause for clarity 
Fixes #
=> remove obsoleted else-if clause

runtime/src/accounts_db.rs
writes to cache know a storage is never needed.
Writes NOT using cache have to look up a storage deep in the bowels of the code.
Writes NOT using cache are either shrink, flush, or tests.
shrink and flush create the storage ahead of time.
Tests often do not, but they use specific test apis.
Ideally, we never lookup a storage deep in the bowels of writing accounts.
This allows us to simplify and improve performance of account writing.
Further changes will include the required storage in the `Storage` enum value so that it doesn't have to be looked up deeper.
Overall, changing this to an enum makes it trivial to find all places which are not using the cache.
Add enum to replace bool.
Fixes #
=> is_cached_store, bool -> Storage enum

runtime/src/accounts_db.rs, runtime/src/bank.rs, runtime/src/storable_accounts.rs
There are multiple impls of `StorableAccounts`. Almost all of them do NOT contain multiple slots.
Provide default impl of `contains_multiple_slots()`
Fixes #
=> impl default version of contains_multiple_slots

runtime/src/accounts_db.rs
Currently refactoring shrink/combine ancient to change how we pack ancient append vecs/cold storage.
stats for `remove_old_stores_shrink` are cumbersome.
clean up `remove_old_stores_shrink` stats
Fixes #
=> clean up remove_old_stores_shrink stats

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
Refactoring ancient append vec packing code. Extra life times make wrestling with the borrow checker less fun.
Remove unnecessary lifetime.
Fixes #
=> remove unnecessary lifetime

programs/sbf/tests/programs.rs, runtime/src/accounts.rs, runtime/src/bank.rs, sdk/src/feature_set.rs
`congestion multiplier` in transaction fee calculation is rarely used; at several occasions, it had been suggested for removal. Thought to open a PR to get discussion going.
- remove `congestion_multiplier` from transaction fee calculation
- add feature to gate the change
Feature Gate Issue: Remove congestion multiplier from transaction fee calculation #29881
=> remove congestion multiplier from transaction fee calculation

core/src/banking_stage.rs, core/src/banking_stage/committer.rs
Some clean up in `committer.rs`.
Fixes #
=> BankingStage Refactor: Committer Simplify

core/src/snapshot_packager_service.rs, core/tests/snapshots.rs, runtime/src/accounts_background_service.rs, runtime/src/snapshot_package.rs, runtime/src/snapshot_utils.rs
The slot_deltas is a necessary part of the bank state, needed for reconstructing the bank.  It should be serialized together with the bank.
Serialize the slot_deltas into the bank snapshot directory in add_bank_snapshot, so it is generated with the bank file.  Move it out of the AccountsPackage data structure.  When building the archive, instead of using the data structure inside the AccountsPackage, hard-link the serialized slot-delta file in the bank snapshot directory.
This is one of the split PRs from https://github.com/solana-labs/solana/pull/28745/
Fixes #
=> Add slot deltas into the bank snapshot directory

runtime/src/accounts_db.rs
`original_bytes` is too vague.
Rename to `capacity`
Fixes #
=> rename original_bytes -> capacity

ci/test-sanity.sh
the conflict marker check in `ci/test-sanity.sh` is overly presumptuous about the working tree configuration
- query the target branch instead of hardcoding
- various robustness and dx improvements
=> ci: make merge conflict marker sanity check more robust

runtime/src/accounts_db.rs
fn `total_bytes()` calls `capacity()` to get a result. Seems useful to have common names.
Rename
Fixes #
=> total_bytes -> capacity

runtime/src/accounts_db.rs
Currently refactoring shrink/combine ancient to change how we pack ancient append vecs/cold storage.
stats for shrinking are cumbersome.
combine some stats into `ShrinkStatsSub`
Fixes #
=> combine some stats into ShrinkStatsSub

runtime/src/append_vec.rs
Replace 4 fn calls (and possibly expensive lookups) with 1 call. This allows us to percolate the changes one level deeper into `StorableAccounts` and reduce the overhead of looking up and returning the data to store.
Fixes #
=> combine lookups in StorableAccountsWithHashesAndWriteVersions

runtime/src/accounts_db.rs
when adding test accounts, test can request alive_bytes be updated on the storage. The # of bytes added was incorrectly calculated.
set the correct # of alive bytes
Fixes #
=> fix alive_bytes test fn

runtime/src/accounts_db.rs
when testing shrink functions, it is convenient to create a setup of various slots and accounts. Being able to specify the data size of an account is useful. For example, to set the data size large enough to cause the storage to need to shrink or not.
Allow tests to specify the size of account data to create in sample accounts.
Fixes #
=> add test accounts with custom data size

ledger-tool/src/bigtable.rs, ledger-tool/src/main.rs
The shred storage type (ie compaction) only needs to be known for opening the blockstore, so move the discovery next to open instead of having to pass around as an arg in a bunch of places.
Shift the call to determine shred storage type. Note that this change will also avoid the warn (now info) when we won't even open the blockstore at all, such as in some of the upcoming `accounts` commands.
=> ledger-tool: Move shred storage type inference next to Blockstore::open

faucet/src/bin/faucet.rs, faucet/src/faucet.rs, gossip/src/cluster_info.rs, gossip/src/crds.rs, gossip/src/legacy_contact_info.rs, rpc/src/rpc.rs, test-validator/src/lib.rs
Code cleanup.
Use Ipv4Addr constants in `socketaddr!` calls.
=> Use Ipv4Addr constants in socketaddr!

.github/workflows/release-artifacts-auto.yml
In the same branch, we should cancel previous Windows building when a new one starts.
This PR can cancel previous running. It looks like this:
=> ci: cancel previous Windows build when start a new one

.mergify.yml
Need a new tag for us to recognize L1 access author's changes.
- exclude monorepo-xxx team from community
- add need:merge-assist label for monorepo-triage team and community
=> chore: label for monorepo-triage team

core/src/validator.rs
The QUIC client certificate is being initialized with Gossip IP address in validator code. If the validator is using different IP for gossip and TPU, the certificate will carry gossip IP, but the QUIC connections will be opened from TPU IP address.
Update the code to use TPU IP instead of gossip IP.
Fixes #
=> Use TPU IP instead of gossip for QUIC client certificate info

Cargo.lock, install/Cargo.toml, programs/bpf/Cargo.lock, runtime/Cargo.toml, sdk/cargo-build-sbf/Cargo.toml, storage-bigtable/Cargo.toml
https://discord.com/channels/428295358100013066/560503042458517505/1070941749234634782
https://buildkite.com/solana-labs/solana/builds/89544#0186156a-3b08-4242-bd6e-c3fe77e544e1
```
Crate:     bzip2
Version:   0.4.3
Title:     bzip2 Denial of Service (DoS)
Date:      2023-09-01
ID:        RUSTSEC-2023-0004
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0004
Solution:  Upgrade to >=0.4.4
```
=> chore: bump bzip2 from 0.4.3 to 0.4.4

runtime/src/accounts_db.rs
It is useful to combine calls to test creation functions.
The fact that we have to use a TempFile complicates that.
Allow storage creation functions to take a None for TempFile.
Fixes #
=> test create storages can ignore TempFile

runtime/src/ancient_append_vecs.rs
This will be put in 1 dead code piece at a time with tests until all pieces are present.
add ancient `sort_shrink_indexes_by_bytes_saved`. This will be used to identify which ancient slots to combine.
Fixes #
=> add ancient sort_shrink_indexes_by_bytes_saved

core/src/banking_stage/packet_receiver.rs
Follow-up to comment here: https://github.com/solana-labs/solana/pull/29784#discussion_r1094529924
Returning unit makes clippy unhappy, so I opted for a comment instead:
```
36 |                 .map(|receive_packet_results| -> () {
|                                              ^^^^^^ help: remove the `-> ()`
```
Fixes #
=> Add comment on the closure

core/src/banking_stage.rs
#29403 and #29784 individually did not get us under the clippy limit, but together do.
Remove clippy warning ignore (a sign of progress 🎉 )
Fixes #
=> remove unnecessary clippy warning ignore

runtime/src/bank.rs, runtime/src/bank/tests.rs, sdk/src/feature_set.rs
There is still one way accounts can end up newly rent-paying: a validator identity account with a very small or zero balance may receive a sub-rent-exemption rent distribution here: https://github.com/solana-labs/solana/blob/151585e59688b4f71e2724ee353058198075f244/runtime/src/bank.rs#L5035
Add feature-gate that, when active, will burn attempted rent distributions that do not meet rent-state transition requirements
Piggy-backs on #16847 (which in retrospect, should have included a test. I wasted some time thinking the `test_distribute_rent_to_validators_overflow` was testing the credit-overflow checked in that PR)
=> Prevent Rent-reward recipients from ending up RentPaying

.mergify.yml
With multiple backport targets, it's now too difficult to watch for overeager backporting as one needs to go directly into the PR to see the target branch. 
Surface the target branch in the PR title.
=> Mergify: include destination branch in backport PR title

runtime/src/bank.rs
use rust `then` idiom for multi-key ordering compare.
Fixes #
=> refactor rent payment order cmp

core/src/banking_stage.rs
Want to move `record_transactions` onto the existing `TransactionRecorder` as part of BankingStage refactoring, but don't want these counters inside.
Move counters out of `record_transactions`
Note:
I'm actually partial to removing these counters entirely and folding them into some other reported metrics - but keeping this PR as a simple refactor (move) of the counters so I can move `record_transactions` into `TransactionRecorder` for a better interface.
Fixes #
=> BankingStage Refactor: Move counters out of record_transactions

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
Working towards knowing the storage at a higher level without having to get it somewhere deeper in store code path.
`StoreTo::Storage` holds a storage. `StoreTo::Cache` does NOT have one or need one.
Fixes #
=> StoreTo::Storage holds storage

rpc-client-api/src/response.rs
Current response for ```getRecentPrioritizationFee``` is ```snake_case```  but as of docs it should be ```camelCase ```
eg:
```
{
"slot": 348125,
"prioritizationFee": 0
}
```
use ```[serde(rename_all = "camelCase")]``` for ```RpcPrioritizationFee``` struct
https://github.com/solana-labs/solana/blob/d387f15587b3a1d9ec2ae1cb5d0d14e04e901644/rpc-client-api/src/response.rs#L549
=> Fix camelCase response for RpcPrioritizationFee

Cargo.lock, programs/sbf/Cargo.lock
[vuln](https://rustsec.org/advisories/RUSTSEC-2023-0007) in `openssl-src` dependency
update to 111.25
=> ci: update openssl-src to 111.25 as per RUSTSEC-2023-0007

Cargo.lock, programs/sbf/Cargo.lock, runtime/src/accounts_db.rs
Storage is always known in all calls to `write_accounts_to_storage`
remove `storage_finder` from `write_accounts_to_storage`
Fixes #
=> remove storage_finder from write_accounts_to_storage

runtime/src/accounts_db.rs, runtime/src/append_vec.rs
The runtime V2 needs an API to filter executable/program accounts in a transaction, without reading the whole account in the memory. We don't currently have such an API.
An API that can match account's owner with a set of pubkeys (loader pubkeys) will be ideal.
Add API to `account_matches_owners` in `append_vec.rs` and `accounts_db.rs`. Also, add unit tests.
Fixes #
=> API to match account owner against a set of owners

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
Add `get_unique_accounts_from_storage_for_combining_ancient_slots` as a piece we'll need shortly.
Fixes #
=> add ancient get_unique_accounts_from_storage_for_combining_ancient_slots

ledger/src/blockstore.rs
It is harder to "connect the dots" when core types are not documented.
Added a short description, connecting `CompletedDataSetInfo` to the producers and consumers.
=> doc: ledger: Document `CompletedDataSetInfo`

net/remote/remote-client.sh
Some time ago a new option was added to net script which allows to specify different types of clients.
For example: `./net/net.sh start --client-type [thin-client, tpu-client, rpc-client]` but the problem is that there is `http` missing in the url.
Add http to url
=> add http to the url in remote-client script

gossip/src/cluster_info.rs, gossip/src/duplicate_shred.rs, gossip/src/duplicate_shred_handler.rs
Duplicate-shred handler relies on all chunks within a duplicate-shred proof having the same wallclock. But this is only an implementation detail and does not need to be the case.
Removed wallclock from duplicate-shreds handler.
=> removes wallclock from duplicate-shreds handler

runtime/src/account_storage.rs, runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
add `write_ancient_accounts` which will be needed shortly.
Fixes #
=> add ancient write_ancient_accounts

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
Currently, ancient append vec 'shrink' occurs on a single slot at a time. Thus, when we are done with that slot and call `remove`, there is never another shrink active. However, with the new packing algorithm, many slots are actively …
=> add shrink_can_be_active to remove

program-runtime/src/lib.rs, program-runtime/src/loaded_programs.rs, runtime/src/bank.rs, runtime/src/bank_forks.rs
Need facility to cache programs across active forks based on their deployment/updates.
This PR adds a new cache `LoadedPrograms`. The cache maintains multiple versions of loaded programs based on the active forks, and program's deployment/update slot. When the root slot is updated, the unreachable forks can be pruned from the cache.
This PR adds the framework for cache, and associated unit tests. More changes are needed in bank, accounts and surrounding code to integrate it in the flow.
Fixes #
=> LoadedPrograms cache implementation and tests

ledger/src/bigtable_upload.rs
After recently looking at GDB output, I noticed that there are multiple threads spawned with the name solBigTGetBlk. 
Append an integer so each of them appear uniquely as we do for other thread pools in the codebase.
=> Append integer to solBigTGetBlk threads to uniquify them

sdk/macro/src/lib.rs
The functions and ID created with `declare_id` could be const, but they're not, limiting their usage in other const situations, for example, as associated items on traits, where `static` is not allowed.  For example, this is not allowed:
```
trait Id {
static ID: Pubkey;
}
```
Mark `id()` and `ID` as `const`, so we can do things like:
```
trait Id {
const ID: Pubkey;
}
impl Id on Struct {
const ID: Pubkey = system_program::ID;
}
```
Fun side note: I don't think this will break anyone! It currently isn't possible to do something like
```
static SYSTEM_ID: &str = "11111111111111111111111111111111";
crate::declare_id!(SYSTEM_ID);
```
So this only makes things better.
Fixes #
=> sdk: Make `declare_id` mostly const

Cargo.lock, bench-tps/Cargo.toml, bench-tps/src/bench_tps_client/tpu_client.rs, bench-tps/src/main.rs, bench-tps/tests/bench_tps.rs, cli/src/program.rs, client/src/connection_cache.rs, client/src/nonblocking/tpu_client.rs, client/src/thin_client.rs, client/src/tpu_client.rs, connection-cache/src/connection_cache.rs, core/src/banking_stage/forwarder.rs, core/src/warm_quic_cache_service.rs, dos/src/main.rs, quic-client/src/lib.rs, rpc-test/tests/rpc.rs, send-transaction-service/src/send_transaction_service.rs, thin-client/src/thin_client.rs, tpu-client/src/nonblocking/tpu_client.rs, tpu-client/src/tpu_client.rs, udp-client/src/lib.rs
Dynamic dispatch forces heap allocation and adds extra overhead.
Dynamic casting as in the ones below, lacks compile-time type safety:
https://github.com/solana-labs/solana/blob/eeb622c4e/quic-client/src/lib.rs#L172-L175
https://github.com/solana-labs/solana/blob/eeb622c4e/udp-client/src/lib.rs#L52-L55
The commit removes all instances of `Any`, `Box<dyn ...>`, and `Arc<dyn ...>`,
and instead uses generic and associated types.
There are only two protocols QUIC and UDP; and the code which has to
work with both protocols can use a trivial thin enum wrapper.
With respect to connection-cache specifically:
* `connection-cache/ConnectionCache` is a single protocol cache which
allows to use either QUIC or UDP without any build dependency on the
other protocol.
* `client/ConnectionCache` is an …
=> removes dynamic cast and dynamic dispatch from connection-cache

core/src/replay_stage.rs, core/src/validator.rs, entry/src/entry.rs, ledger/src/blockstore.rs, ledger/src/blockstore_processor.rs, ledger/src/shredder.rs, ledger/src/sigverify_shreds.rs, perf/src/sigverify.rs
No functional changes, just done for consistency. Additionally, the `ix` abbreviation is used to refer to instruction in other places so avoid that.
=> chore: Use `i` over `ix` variable name when naming worker threads

docs/.prettierrc.json
The doc's markdown files often have line lengths >80 characters, resulting in inconsistent formatting of the files and difficulty in reading on screen.
Updated prettier config file to force line lengths to 80 characters within the markdown files. This will enable auto format on save.
=> [docs] style: prettier force line length to 80 chars

Cargo.lock, programs/bpf/Cargo.lock
cherry-pick of https://github.com/solana-labs/solana/pull/30173 and https://github.com/solana-labs/solana/pull/30113 to v1.13
=> ci: resolve outstanding v1.13 cargo-audit errors

programs/bpf_loader/src/lib.rs
Basically the same as with #29208 and #29226.
Which makes this the third time that a PR broke something on windows or arm (e.g. apple silicon) and yet it went through CI because we don't build tests on these platforms.
Moves `if use_jit` outside of `#[cfg()]`.
Fixes #30116
=> Moves `if use_jit` outside of `#[cfg()]`.

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
Add `ancient calc_accounts_to_combine` to separate accounts to prepare for creating packed ancient append vecs. This will be used soon.
Fixes #
=> add ancient calc_accounts_to_combine

runtime/src/accounts_db.rs
test code compares sets of accounts after clean/shrink operations.
The indexing was off and new tests were giving false positives.
The test code was equivalent as long as everything was in the same order.
Fix test code comparison indexes.
Fixes #
=> fix bug in test fn compare_all_accounts

core/benches/banking_stage.rs, core/src/banking_stage.rs, core/src/banking_stage/committer.rs
Passing around `transaction_status_sender` and `replay_vote_sender` everywhere.
* intermediate step towards separating out a `TransactionConsumer` that holds the remaining pieces.
Move `transaction_status_sender` and `replay_vote_sender` into `Committer`.
Fixes #
=> BankingStage Refactor: Add state to Committer

core/src/ancestor_hashes_service.rs, core/src/replay_stage.rs
We should not dump our own leader slots ever, this indicates that manual intervention is required.
Panic when dumping our own leader slots.
Remove the circular transmission check so that we can repair our own leader slots in case of ledger corruption/deletion on restart.
Fixes #30126 #30197
=> Fix repair behavior concerning our own leader slots

runtime/src/ancient_append_vecs.rs
Introducing `PackedAncientStorage`
and the first method to use it:
`write_one_packed_storage`
ancient add `write_one_packed_storage`
Fixes #
=> ancient add write_one_packed_storage

core/src/repair_generic_traversal.rs, core/src/repair_service.rs, core/src/repair_weight.rs, core/src/repair_weighted_traversal.rs, ledger/src/blockstore.rs, ledger/src/shred.rs
Turbine propagation delay is not considered before creating a `HighestShred` request.
- use propagation delay and the reference tick of the last shred we have received for the slot to determine if a `HighestShred` repair request should be sent.
- moves network propagation delay value from blockstore to repair.
Fixes #
=> defer HighestShred repairs during shred propagation threshold

runtime/src/accounts_db.rs
many tests compare groups of accounts after running an algorithm. Debug logs of vecs of accounts can be difficult to scan for humans, looking for differences.
Also, it is nice to know how many failures there are instead of just that there was 1.
Return # of failures.
Allow easy modification of which fields are dumped in the assert message.
Fixes #
=> improve debugging test fn compare_all_accounts

ledger-tool/src/main.rs
Previously, ledger-tool had a guardrail to disallow a custom accounts path when access mode to the blockstore was Secondary. This was to avoid potentially pulling the accounts out from underneath solana-validator. When ledger-tool switched over to use Secondary blockstore access for all commands that do not need write access, this removed the ability to use custom accounts paths with ledger-tool at all for these commands. Custom accounts paths are desirable, especially if that custom path is in tmpfs to speed up processing.
With this change, when a custom accounts path is passed for a command using Secondary access, ledger-tool now checks if Primary access is being held by another process. If not, allow processing to proceed with the custom accounts path.
The above check isn't fullproof, …
=> ledger-tool: Reallow custom accounts path with Secondary access

ledger-tool/src/main.rs, ledger/src/blockstore.rs, runtime/src/bank.rs
Currently, we can't create a minimized snapshot for mainnet-beta due to wide-spread use of address-lookup-table txes which is currently-unsupported for the minimized snapshot.
Support it. Needed bunch of seemingly unrelated changes...
=> Add address lookup tables to minimized snapshot

runtime/src/ancient_append_vecs.rs
test was inadvertently set to 2..4 slots instead of 0..4
set range to 0..4 to test a few more cases.
Fixes #
=> restore test to all slot combos

runtime/src/ancient_append_vecs.rs
The tuning parameters need to be reused by other functions.
Pass by ref.
Fixes #
=> collect_sort_filter_ancient_slots takes tuning by ref

runtime/src/accounts_db.rs, runtime/src/snapshot_minimizer.rs
Now that we shrink multiple slots concurrently, when we remove a slot indicating that we shouldn't, we hit an assert that there is not a shrink in progress. There is correctly a shrink in progress.
pass `shrink_can_be_active` through a few …
=> pass shrink_can_be_active through shrink fns

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
add `pack()` to organize ancient accounts into packed storages.
Fixes #
=> add ancient pack_ancient_storages

runtime/src/ancient_append_vecs.rs
It turns out to be useful to have the slots in sorted order later. Since the input is sorted, it is easy to ensure that `target_slots` remain in sorted order.
Change name to make sure it is clear slots are sorted.
Fixes #
=> maintain sorted order on ancient target slots

ledger-tool/src/main.rs
The previous PR (#30228) used Primary access; however, it is better to use PrimaryForMaintenance in this case to disallow any potential compaction from happening.
Use PrimaryForMaintenance instead of Primary per [this comment](https://github.com/solana-labs/solana/pull/30228#discussion_r1102202339).
=> fixup! lt: Reallow custom accounts path with Secondary access (#30228)

runtime/src/accounts_db.rs
over time, the shrink and ancient code has been improved. We no longer spend time reshaping the data in shrink like we used to. As a result, the metric for `find_alive_elapsed` has become unnecessary. Where we spend time is already handled by other metrics.
Remove metric that is not useful.
Fixes #
=> remove unused metric

runtime/src/ancient_append_vecs.rs
we no longer need `SlotInfo` per account to keep.
Remove the value from the hashmap tuple.
Fixes #
=> simplify AccountsToCombine.accounts_keep_slots

core/src/validator.rs, validator/src/cli.rs, validator/src/main.rs
rampant use of various `--no-*-test` flags by validator operators creating unnecessary and difficult to debug support requests
remove suggestions to use them from failure logs
=> remove recommendations to skip validator startup tests on failure

client/src/nonblocking/tpu_client.rs, client/src/tpu_client.rs, thin-client/src/thin_client.rs, tpu-client/src/nonblocking/tpu_client.rs, tpu-client/src/tpu_client.rs
A number of temporary_pub modules in tpu_client and thin_client can now be safely removed or really made public as duplicate code is removed.
Remove temporary_pub code.
Fixes #
=> Cleanup tempoary pub modules

ci/do-audit.sh
`cargo-audit` displays (obnoxiously long in our case) dependency trees for each flagged advisory, frequently leading to missed/or misidentified vulnerable crates.  conveniently, it offers a `--quiet` that does _not_ suppress these trees :facepalm: 
`grep` out the dependency trees in the `ci/do-audit.sh` wrapper by default.
introduce a `--display-dependency-trees` arg to get them back if/when needed
=> ci: suppress dep trees by default in `ci/do-audit.sh`

program-runtime/src/executor_cache.rs, programs/bpf_loader/src/lib.rs, programs/sbf/tests/programs.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs, sdk/src/feature_set.rs
[Currently some changes to programs made by un-/re-/deployment are visible immediately, even within the same transaction](https://github.com/solana-labs/solana/pull/29725). These inconsistency between top-level instructions and CPI should be removed. This is a preparation for the replacement of the current executor cache by one that supports a [bitemporal model](https://en.wikipedia.org/wiki/Bitemporal_modeling). Once that is done, the new executor cache will further delay the visibility from the end of the transaction to a slot in the future, with a constant offset from the slot the action occurred in.
- Use three separate `HashMap`s instead of the `enum` `TxBankExecutorCacheDiff`
- Replaces all places which deploy programs by a macro
- Load previous version into the cache before …
=> Refactor - Delay visibility of program un-/re-/deployment

sdk/program/Cargo.toml
=> chore: bump assert_matches to 1.5.0

runtime/src/ancient_append_vecs.rs
In combining the functions together to complete ancient packing, it is far cleaner to pass this accumulation of results by &mut instead of returning it and accumulating later.
change to pass by `&mut`
Fixes #
=> ancient: pass WriteAncientAccounts by &mut

runtime/src/ancient_append_vecs.rs
In combining together these functions, some names could be clearer.
Rename and update comments.
Fixes #
=> rename parameter and update comments

runtime/src/ancient_append_vecs.rs
add ancient
Breaking out pieces of the higher level packing ancient algorithm for easier testing and readability.
add`finish_combine_ancient_slots_packed`
Fixes #
=> add ancient finish_combine_ancient_slots_packed

core/src/repair_generic_traversal.rs, core/src/repair_service.rs, core/src/repair_weight.rs
Sleeps in repair tests are unnecessary.
Use `post_shred_deferment_timestamp` in repair tests rather than `sleep`.
Fixes #
=> remove sleeps from repair tests

ledger/src/blockstore_processor.rs, sdk/src/feature_set.rs
Leaders use `cost_tracker` to ensure each block produced are with block limits. Same cost tracking and checking against limits should be symmetrically performed during replay, blocks exceed limits should fail replay.
- calling `bank.cost_tracker.try_add(tx)` during replaying, return error if block exceeds limits
- add feature gate since this change breaks consensus 
Feature Gate Issue: #29595 
**NOTE**: Until this point, cost_model and cost_tracker are exclusively used by leaders during block packing, so we enjoyed the freedom to change how it works without worrying much about breaking consensus. With this PR, future changes to `cost_model.rs`, `cost_tracker.rs`, `block_cost_limits.rs` and maybe other models that would change how transaction cost measures against block limits could break …
=> add cost tracking for each bank during replay

core/src/sample_performance_service.rs
A recent change to this service to store the number of non-vote transactions introduced a bug in the computation of the number of transactions during the time interval. This resulted in bogus values being stored in Blockstore and eventually getting served through RPC for the TPS chart on explorer.
`Bank::transaction_count()` returns the total number of transactions all time up to whatever slot that `Bank` is at. So, if we want to compute how many transactions occur in a time window (as SamplePerformanceService does), we need to call `Bank::transaction_count()` at the start and end of the time window. The number of transactions during that period is the difference in the two counts.
We had pre-existing behavior to save the total transaction count from one sample to use as comparison for …
=> Fix transactions counts stored by SamplePerformanceService

ledger/src/blockstore.rs
This deadlock could only occur on nodes that call
Blockstore::get_rooted_block(). Regular validators don't call this function, RPC nodes and nodes that have BigTableUploadService enabled do.
Blockstore::get_rooted_block() grabs a read lock on lowest_cleanup_slot right at the start to check if the block has been cleaned up, and to ensure it doesn't get cleaned up during execution. As part of the callstack of get_rooted_block(), Blockstore::get_completed_ranges() will get called, which also grabs a read lock on lowest_cleanup_slot.
If LedgerCleanupService attempts to grab a write lock between the read lock calls, we could hit a deadlock if priority is given to the write lock request in this scenario.
This change removes the call to get the read lock in get_completed_ranges(). The lock is …
=> Remove recursive read lock that could deadlock Blockstore

validator/src/cli.rs
validator long args are inconsistently defined with some having a double-dash prefix and others leaving it to `clap`. both work fine for their intended purpose, but the inconsistency makes grep/find+replace easy to screw up. (i missed a case in #30250)
leave all the double-dashing to `clap`
i checked the entire monorepo and only found the validator instances of this pattern
=> validator: let `clap` double-dash prefix long args

ledger/src/blockstore_processor.rs
We use the Vec that results from .collect(), so the exception to allow a needless collect is no longer appropriate.
Remove outdated clippy exception; noticed this while looking at another review.
=> chore: Remove clippy exception that is no longer needed

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
finally adding top level fn `combine_ancient_slots_packed` to pack ancient storages with new algorithm.
Fixes #
=> add combine_ancient_slots_packed

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
fix typos, remove unnecessary clippy allow, and saturating_add_assign
Fixes #
=> typos, clippy and saturating_add_assign

core/src/sample_performance_service.rs
The initial Bank reference in the SamplePerformanceService is held for the life of the service, even though it's only used to query some sample-snapshot data at boot.
Only hold the Bank reference while generating the initial sample snapshot.
https://github.com/solana-labs/solana/pull/30297 will also fix this issue, but this is a more lightweight change to consider for backporting. Wdyt @steviez ?
Fixes #30312
=> Scope SamplePerformanceService Bank only for initial sample snapshot

core/src/sample_performance_service.rs
Snapshot construction and interaction code was a bit more manual than necessary, even [causing a bug](https://github.com/solana-labs/solana/pull/30280) to slip past a review.
Separated snapshot construction from the diffing of two snapshots.
This should make the logic clearer.
Fixes #30312
=> SamplePerformanceService: Refactor stats snapshot logic

ci/buildkite-pipeline.sh
https://discord.com/channels/428295358100013066/560503042458517505/1074785045107196066
made these steps run on bk agent which queue is `check` (has already set up them on bk)
- sanity (about 15s)
- shellcheck (about 19 s)
- checks (about 5~7 mins)
=> ci: group check steps into an individual queue

cli-output/src/cli_output.rs, cli/src/feature.rs
None, just code cleanup.
Small code cleanup change using `.cmp`.
=> Simplify some comparisons using (a1, a2).cmp(&(b1, b2))

core/src/sample_performance_service.rs, docs/src/api/methods/_getRecentPerformanceSamples.mdx
It's not immediately obvious why we're querying `BankForks::highest_slot()` in SamplePerformanceService, instead of using the same bank slot that we query for transaction counts.
Add comments to SamplePerformanceService
Also update jsonrpc docs to be more correct.
=> Add clarifying comments to SamplePerformanceService

program-runtime/src/loaded_programs.rs, programs/bpf_loader/src/lib.rs
Need API to load a program from its program and programdata account.
Added a new API to bpf_loader to load the program. Also updated `LoadedProgram` structure to store more meta data about the program.
Fixes #
=> Code to load a program from its account

runtime/src/accounts_db.rs, runtime/src/append_vec.rs
The `account_matches_owner()` API doesn't return which owner matches the program account's owner. The information is needed while processing the transactions. The API could be updated to return this information.
The API is updated to return the owner information (the index of the matching owner in `owners` array). Also, updated unit tests.
Fixes #
=> Return index of matching owner for a program account

core/src/banking_stage/committer.rs, core/src/banking_stage/packet_receiver.rs, measure/src/macros.rs, runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
Unlikely to have significant impact, but this is slightly more efficient way of doing `measure_us`. 
measure_us! was using a `Measure` internally:
Flow in the current macro:
1. Create `std::time::Instant` (in `Measure::start`)
2. Do $val (what we're measuring)
3. Store `duration: u64` on `Measure` from `duration_as_ns(&self.start.elapsed())`
4. Return result and `duration / 1000`
Micro-optimizations:
Just directly calculate the `us` from duration using `duration_as_us`. Can skip the `ns` store and extra division. Also bypass the `Measure` struct which holds a `&str`.
More specific namespacing also lets me get rid of now unused imports of `measure!`
Fixes #
=> measure_us! use Instant and duration_to_us internally

local-cluster/tests/local_cluster.rs
`test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup` has a race where files are deleted out from under a running validator. If that validator is in the middle of archiving a snapshot, it will panic. 
The validator doesn't need to be running when the files are being deleted, but currently it is. 
Stop the validator before we delete the snapshot files.
Fixes #30291
=> Fixes race in local cluster incremental snapshot test

ledger/src/shred.rs, ledger/src/shred/merkle.rs, ledger/src/shred/shred_data.rs, ledger/src/sigverify_shreds.rs
* The merkle root is unnecessary encoded into shreds binary, reducing shreds capacity to store data.
* The root is 32 bytes hash, but since the merkle root is truncated, the signature is on the truncated 20 bytes.
https://github.com/solana-labs/solana/pull/29445 makes it unnecessary to embed merkle roots into shreds binary. This commit removes the merkle root from shreds binary.
This adds 20 bytes to shreds capacity to store more data.
Additionally since we no longer need to truncate the merkle root, the signature would be on the full 32 bytes of hash as opposed to the truncated one.
Also signature verification would now effectively verify merkle proof as well, so we no longer need to verify merkle proof in the sanitize implementation.
=> removes the merkle root from shreds binary

runtime/benches/accounts.rs, runtime/src/accounts.rs, runtime/src/accounts_db.rs, runtime/src/bank.rs
Too many parameters for verify bank hash and lamports fn 
Extract `BankHashLamportsVerifyConfig` into struct.
Fixes #
=> Extract BankHashLamportsVerifyConfig

Cargo.lock, programs/sbf/Cargo.lock, validator/Cargo.toml, validator/src/bootstrap.rs
We can hang indefinitely if we don't find any viable RPC peers in `get_rpc_peers`
1. Add a 5 minute timeout to give up searching for RPC peers
2. Return error when no peers are found instead of inferring error from empty vector
3. Rename `rpc_node_details_vec` to `rpc_node_details`
=> Add timeout for getting bootstrap RPC peers

core/src/repair_generic_traversal.rs, core/src/repair_service.rs, core/src/repair_weight.rs, core/src/repair_weighted_traversal.rs, ledger/src/blockstore.rs
- race between timestamp passed to `get_best_weighted_repairs` and newly inserted shred `first_shred_timestamp`
- `find_missing_indexes` timestamp calculation should use `saturating_sub`
restore `timestamp()` call to `find_missing_indexes` and use saturating math.
Fixes #
=> restore timestamp() in find_missing_indexes

gossip/src/cluster_info.rs, gossip/src/crds_gossip_pull.rs
`CrdsGossipPull.msg_timeout` is effectively redundant and never used.
Removed it.
=> removes redundant CrdsGossipPull.msg_timeout

core/src/banking_stage/consumer.rs
Noticed this was needlessly allocating when doing #30253 but thought it was separate enough to justify a separate PR.
Rewrite of `accumulate_execute_units_and_time` to accumulate without allocating temporary vectors.
Fixes #
=> Rewrite accumulate_execute_units_and_time without allocation

runtime/src/accounts_db.rs, runtime/src/accounts_file.rs, runtime/src/ancient_append_vecs.rs, runtime/src/lib.rs, runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/sorted_storages.rs
This PR abstracts out AppendVec into AccountsFile enum.
This will allow different implementations of AccountsFile that support the AccountsDB.
=> Abstract out AppendVec into AccountsFile enum

runtime/src/accounts_file.rs
The API conflict wasn't detected in the auto-merge.
Fix the AccountsFile::account_matches_owners() to include the matched index
=> Fix the return type of AccountsFile::account_matches_owners()

runtime/src/snapshot_utils.rs
To boot faster, we want to boot from a bank snapshot directory, instead of an archive.  This requires getting meta information from the snapshot directories indicating the snapshot versions and the completion statuses, to help identify a good directory to boot from.
Add snapshot version file and the state_complete file flag into the bank snapshot directory.  This completes the bank snapshot directory, marks it ready for constructing a bank from it.
Add version file
Add state_complete flag
Add function to check the directory and selects the highest completed directory.
This is a split PR from https://github.com/solana-labs/solana/pull/28745
It is orthogonal to the account hardlink PR https://github.com/solana-labs/solana/pull/29496.  But it is better to be committed after that so that the …
=> Add version and state_complete flag into bank snapshot

program-runtime/src/loaded_programs.rs
`LoadedPrograms::insert_entry()` checks if a program exists in the cache that matches deployment and effective slot number for the given program key. It currently returns false in such cases. However, it should return an existing program entry, as that is needed for deduplication in case two transaction batches load the same program simultaneously.
This PR changes the return type to an enum `LoadedProgramEntry`, that conveys if the entry already existed, or was newly added. Also, it carries an `Arc` to the valid loaded program instance.
Fixes #
=> Return loaded program entry from the cache after insert

core/src/serve_repair.rs, gossip/src/crds_gossip_pull.rs, rpc-client-api/src/response.rs, runtime/src/ancient_append_vecs.rs, sdk/program/src/alt_bn128.rs
In order to upgrade Rust in #29947, we must resolve new clippy lints.
Run `clippy --fix`
=> Apply clippy fixes for future rust upgrade

docs/src/running-validator/validator-start.md
The current documentation fails to call out that some items go under the ledger directory by default. If this is the case, then the stated 500 GB number will most certainly be exceeded.
Add some additional details so that operators aren't immediately given false expectations about disk footprint of the ledger.
https://github.com/solana-labs/solana/pull/26651 made it so space used by blockstore is kept in check better; but it is arguable that https://github.com/solana-labs/solana/issues/23248 is still an issue given that with default args, ledger will grow past 500 GB with blockstore / accounts / accounts index / snapshots.
Fixes #
=> docs: Update on --limit-ledger-size and ledger disk usage

gossip/src/cluster_info.rs
Lots of redundancy in setting up all the sockets as part of `new_localhost_with_pubkey`
Create local variables for localhost and unspecified IP address that can be reused for binding
=> Clean up socket binding reuse

ledger-tool/src/main.rs, validator/src/main.rs
unexpected storage contention with accounts disk index enabled on systems without ledger and accounts on different volumes
disable accounts disk index by default on v1.14
=> validator: disable accounts disk index by default - v1.14

docs/src/running-validator/validator-start.md, validator/src/cli.rs
followup to #30250. missed the worst one due to #30303 :facepalm: 
hide `--no-port-check`
=> hide commonly misused `--no-port-check` validator arg

runtime/src/accounts.rs
Missing code that can extract unique executable program accounts from a batch of transactions.
Add a new API to accounts that returns executable program accounts from a transaction batch.
Added unit tests for the API.
Fixes #
=> API to enumerate executable program accounts in tx batch

cli/src/cluster_query.rs
https://github.com/solana-labs/solana/pull/11644 added `until` support to `getSignaturesForAddress`. This included `solana transaction-history` plumbing, but the actual cli param was not added.
Add it
=> Cli: expose until param in solana transaction-history

ci/test-checks.sh
https://discord.com/channels/428295358100013066/560503042458517505/1075566094439436298
It is not easy to read the errors which produced by `cargo sort`.
hide all stdout when run on CI environment. it looks like
the build: https://buildkite.com/solana-labs/solana/builds/90451#01865a17-95f1-4eb1-82c0-0f87b482cb77
=> ci: don't print 'Checking PACKAGE_NAME...' when do cargo sorting check

local-cluster/tests/local_cluster.rs
Original problem: https://github.com/solana-labs/solana/pull/30291
Partial fix: https://github.com/solana-labs/solana/pull/30340
Remaining issue:
https://github.com/solana-labs/solana/pull/30340#issuecomment-1433535391
Possible fixes:
https://github.com/solana-labs/solana/pull/30340#issuecomment-1433740383
Tl;dr: We are deleting tmp snapshot archives from underneath a running validator. If that validator is in the middle of archiving a snapshot, it will fail since its working-files will just have been rugged.
There's no need to remove the tmp snapshot archives from the validator *before* we copy snapshot archives over to the final validator. So don't 😄 
Fixes #30291
I ran this modification in a tight loop for approximately 550 iterations without a failure. Hopefully this will fix the last …
=> local-cluster test: Do not delete files that are in use by node

geyser-plugin-interface/src/geyser_plugin_interface.rs, geyser-plugin-manager/src/accounts_update_notifier.rs, geyser-plugin-manager/src/block_metadata_notifier.rs, geyser-plugin-manager/src/slot_status_notifier.rs, geyser-plugin-manager/src/transaction_notifier.rs
The current geyser plugin interface requires a mutable reference. This creates a massive bottleneck on plugins running geyser plugins that can cause nodes to slow down and fall behind the network. 
- In `geyser-plugin-interface`, it removes the `mut` reference on `update_account`, `update_slot_status`, `notify_end_of_startup`, `notification_transaction`, and `notify_block_metadata`.
- In `geyser-plugin-manager`, it replaces write locks with read locks on the plugin manager and changes plugin references to be non-mutable. 
Fixes #
=> Update geyser interface to not require write locks

bench-tps/src/cli.rs, bench-tps/src/main.rs
Currently node_id is generated randomly, this complicates testing if we want to use staked connection with bench-tps.
~~I guess it might be possible to get `bind_address` in the code using some wrapper for `getifaddrs`, yet it looks like we usually specify this as cli argument.~~
* add two additional parameters `bind_address` and `client_node_id` to cli
* add code to get total active stake and stake information from the network
* use this data when constructing `ConnectionCache`
=> Node identity for bench

runtime/src/accounts_db.rs, runtime/src/accounts_hash.rs
Ancient append vecs are changing to a 1 pass packing algorithm. This has an effect on how hash calculation works.
Add a stat for how many 'chunks' get created to divide up the work for gathering hash info.
Fixes #
=> add hash calc scan_chunks metric

sdk/bpf/scripts/install.sh, sdk/cargo-build-sbf/src/main.rs, sdk/cargo-build-sbf/tests/crates.rs, sdk/sbf/scripts/install.sh
New toolchains generate EM_SBF files by default. These files are not accepted by the runtime until SBFv2 is enabled.
This release of sbf-tools generates EM_BPF files by default, emitting EM_SBF machine code only for files compiled to SBFv2 CPU subtarget.
Related to #30375
=> Bump sbf-tools version

Cargo.lock, programs/sbf/Cargo.lock, runtime/Cargo.toml, runtime/src/account_info.rs, runtime/src/accounts_db.rs
A goal is to reduce the per-account cost in the accounts index.
The size field is not used in foreground processing, yet it is stored for every entry in the accounts index. So, we want to get rid of the size field.
Move the 2 extra 'bits' (zero lamport and is cached) onto the offset field. The offset field must exist for every entry in the index.
Fixes #
=> move AccountInfo bits from size to offset

program-runtime/src/executor_cache.rs, program-runtime/src/loaded_programs.rs, programs/bpf_loader/src/lib.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs
LoadedProgram cache is currently unused.
Find and load missing programs in LoadedPrograms cache
- filter program accounts in a transaction batch
- filter the accounts that are missing in LoadedPrograms cache
- load the programs before processing the transactions
Fixes #
=> Find and load missing programs in LoadedPrograms cache

core/src/accounts_hash_verifier.rs, core/src/snapshot_packager_service.rs, core/src/validator.rs, core/tests/epoch_accounts_hash.rs, core/tests/snapshots.rs, runtime/src/snapshot_package.rs, runtime/src/snapshot_package/compare.rs
SnapshotPackager service doesn't have a lot of insight available for seeing how long items wait to be processed, or if any are dropped/replaced and *not* processed.
Additionally, `PendingSnapshotPackage` can only hold a single element. So if SPS already has a pending full snapshot, but hasn't taken it yet, AHV cannot queue up the next incremental snapshot. Instead, that incremental snapshot would be dropped. This can occur in tests/CI where SPS isn't schedule to run as often.
Similar to https://github.com/solana-labs/solana/pull/28352, convert `PendingSnapshotPackage` to a channel.
Also add metrics to SPS and each SnapshotPackage in the queue.
This PR is quite large due to the number of pieces this code touches. I've tried to call out the main/important parts; please let me know if …
=> Uses a channel for AHV -> SPS

ci/docker-rust/Dockerfile
#29893 is stuck for a month cuz I'm waiting for wasm-pack releases their new version which including workspace inheritance. (the thread: https://www.github.com/rustwasm/wasm-pack/pull/1185)
it seems that it won't happen soon. It makes me need to resolve conflict for #29893 again and again if the PR stuck there 😢 
Use wasm-pack latest version in our docker. 
(there is a success build: https://buildkite.com/solana-labs/solana/builds/89556#01866265-2a8e-4148-817e-fccff680a70b)
=> ci: use wasm-pack latest version

cli-output/src/cli_output.rs, cli/src/cluster_query.rs
`solana transaction-history` still doesn't support `--output json`
Implement support
I changed the `--show-transactions` output for humans slightly: `-v` now does nothing, since it just replicates data in the transaction. I will include before/after examples in comments.
Also, the `--show-transactions` variant will now wait until all transactions have been queried to print anything, since we don't support streaming output via `config.output_format.formatted_string`. Just realizing I should probably add a spinner for stderr while this is processing... will do in a small follow-up.
Fixes #14509
=> Cli: support json output for transaction-history

cli-output/src/cli_output.rs
During #30376, I discovered that `solana confirm -v` does not return a transaction's slot in its json output, only in the human-readable display. This looks like a simple oversight.
Convert blanket skip_serializing to only skip if populated with None. Affects `solana confirm -v --output json` and `solana transaction-history --show-transactions --output json`
=> Cli: expose tx slot in json output for confirm or transaction-history

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
Trying to simplify on disk index.
Hold items with ref count != 1 in memory. This allows us to not have to store refcount in the disk index.
Fixes #
=> hold items with ref count != 1 in memory

runtime/src/account_info.rs, runtime/src/accounts_db.rs
We need to reduce the bytes per entry in the account index.
Stored size is only used in background processes. Instead of storing a size per entry, the size can be looked up when needed.
Fixes #
=> remove 'stored_size' from account info

core/src/repair_service.rs, core/src/repair_weight.rs, core/src/repair_weighted_traversal.rs
`ignore_slots` appears to be unused throughout repair service (w/ the exception of one unit test) but it incurs extra overhead, complexity, and checks.
Remove `ignore_slots` and associated unit test
=> Remove ignored slots from repair

core/src/repair_weight.rs
`get_best_weighted_repairs` could be a little more clear and straightforward in some places to improve readability
- Change instantiation of `processed_slots` to use `HashSet::from`
- Reword 1 comment and add 1 additional comment
=> get_best_repairs minor cleanup

core/src/repair_generic_traversal.rs, core/src/repair_service.rs, core/src/repair_weight.rs
It is hard to tell what might be causing a spike in closest completion repair type between:
1. More shreds requiring repair on given slot(s)
2. Large ancestor path of slots being pulled in for repair
3. Large number of repair trees to iterate across
See #30374 
Add metrics to better understand how many repair trees are being looked at and the number of ancestor slots being repaired as part of closest completion slots
=> Metrics for repair trees & closest completion slots

bucket_map/src/bucket.rs, bucket_map/src/bucket_api.rs
Working on reducing disk footprint of disk index.
Soon, in-mem and disk index account info will be different generic types.
This change makes decoupling the two types more straightforward.
`try_write()` takes an iter(&T) and len instead of a `&[T]`. Source data is not shaped as `[T]`, it will be `[U]`.
We also expect the len to be always 1 in the near future. In fact, only random flushes at the moment cause us to ever write a slot list with len != 1.
Fixes #
=> bucket map try_write takes iter

core/src/repair_generic_traversal.rs, core/src/repair_weight.rs
`get_unrepaired_path` can follow parent slot to include the root slot.
add root slot to visited list 
Fixes #
=> stop get_unrepaired_path at root slot

geyser-plugin-manager/src/accounts_update_notifier.rs, runtime/benches/append_vec.rs, runtime/src/account_storage.rs, runtime/src/account_storage/meta.rs, runtime/src/accounts_db.rs, runtime/src/accounts_db/geyser_plugin_utils.rs, runtime/src/accounts_file.rs, runtime/src/accounts_update_notifier_interface.rs, runtime/src/ancient_append_vecs.rs, runtime/src/append_vec.rs, runtime/src/serde_snapshot.rs, runtime/src/storable_accounts.rs, runtime/store-tool/src/main.rs
As we start supporting new storage formats, those account-meta
structs will be shared by different storage formats and thus need
a new home.
This PR creates meta.rs under account_storage and moves all the account-meta
structs out from append_vec.rs.
Will follow-up with PRs that implements getters to access member
fields and will eventually turn account-meta structs into traits
as currently the meta structs are tied to the implementation details
of the AppendVec.
=> Move account-meta structs from append_vec.rs to account_meta.rs

.github/workflows/docs.yml, docs/publish-docs.sh
https://github.com/solana-labs/solana/actions/runs/4245534288/jobs/7381468172
I think we changed the Vercel team slug about weeks ago. sorry for the late response 😢 
extract Vercel scope as an env `VERCEL_SCOPE` which has already setup in this repo.
=> ci: extract vercel scope as an env

runtime/src/bank.rs
Need a path forward to remove `AccountSharedData` for executable/programs in message processing. Currently the programs are eagerly loaded but lazily verified and compiled, which necessitates passing their `AccountSharedData` to the loader built-in program.
Eagerly load, verify and compile programs in the cache so that all programs required for a transaction/batch are already present in the cache before the start of the transaction processing.
Fixes #
=> Replenish executor cache eagerly during transaction processing

runtime/src/accounts_db.rs
Working on reducing disk footprint of disk index.
Soon, in-mem and disk index account info will be different generic types.
use a typedef in a test fn
Fixes #
=> cleanup test type

runtime/src/accounts_db.rs, runtime/src/bank.rs
To reduce the contents of the accounts index, we need to be able to identify when all bank account loads that started are completed.
Introduce two atomics that are incremented when banks are created and frozen/destroyed. Currently these are reported as stats. Later, they will be relied upon to know that all account loads in the foreground as of a certain point have completed.
Fixes #
=> add bank progress stats

Cargo.lock, programs/sbf/Cargo.lock, test-validator/Cargo.toml, test-validator/src/lib.rs, validator/src/bin/solana-test-validator.rs, validator/src/cli.rs
#29051 attempted to default `solana-test-validator --bpf-program` to use the upgradeable loader, but had to be reverted. But the issue remains that most people want to use the upgradeable loader, and the only way to do that with solana-test-validator is [clone from another cluster](https://github.com/solana-labs/solana/pull/30279).
Add `--upgradeable-program` flag to automatically initialize solana-test-validator with an upgradeable program. Parallels #29994
I added this as a separate path from the existing param because I thought it would be cool to support an optional upgrade authority, which would break the existing `--bpf-program` interface. However, we could make `--bpf-program` an alias for `--upgradeable-program <PROGRAM_ID> <PROGRAM.SO> none`. What do you think?
If you like that …
=> Add solana-test-validator --upgradeable-program

runtime/src/accounts_db.rs
stored_size is already calculated and stored in `StoredAccountMeta`
use `StoredAccountMeta.stored_size`
Fixes #
=> get stored_size from StoredAccountMeta

runtime/benches/accounts_index.rs, runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/accounts_index_storage.rs, runtime/src/bucket_map_holder.rs, runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
Working on reducing disk footprint of disk index.
Soon, in-mem and disk index account info will be different generic types.
Introduce second type to accounts index. The new second type will be the type that is stored on disk. Practically, it will have no append vec field.
Fixes #
=> add second type to accounts index for disk

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
We are removing `store_id` from account info.
So, slot is sufficient for figuring out which store.
While shrink is not going on, there is always only 1 store per slot. Shrink should never run in conjunction with 'remove_dead_accounts()'
Rework `remove_dead_accounts()` to use slot as key of a map instead of `AppendVecId`
Fixes #
=> remove_dead_accounts uses slot instead of AppendVecId

core/src/consensus.rs, core/src/validator.rs
See #30258 
We are failing when running test validator and warping slots. E.g. like so:
```
$ solana-install init 1.14.16
✨ 1.14.16 initialized
$ solana-test-validator --reset --warp-slot 20
Ledger location: test-ledger
Log: test-ledger/validator.log
⠐ Initializing...
⠋ Initializing...
⠁ Initializing...
⠚ Initializing...
⠒ Initializing...
⠄ Initializing...
⠠ Initializing...
⠖ Initializing...
⠒ Initializing...
⠈ Initializing...
Identity: 69BsCtTFeJDzgEB12YHDWGFMe9BezypotP1CQvE4mJzR
Genesis Hash: GSB8fKhzFf89M2TZaUKqVE49WUX1QJhkv13vKqzZ3MCi
Version: 1.14.16
Shred Version: 16939
Gossip Address: 127.0.0.1:1024
TPU Address: 127.0.0.1:1027
JSON RPC URL: http://127.0.0.1:8899
⠋ 00:00:29 | Processed Slot: 20 | Confirmed Slot: 20 | Finalized Slot: 20 | Full Snapshot Slot:
^C
```
We are asserting …
=> Adjust tower root after warp slot

Cargo.lock, bench-tps/Cargo.toml, bench-tps/src/cli.rs, bench-tps/src/main.rs
Parsing cli args is different from other places (due to exit, panic, println), it also makes it more difficult to test.
Added a basic unit test for cli.
This is preliminary work to migrate it to clap-v3, most of the things will be rewritten during migration to clap-v3
* Rename parse function
* Get rid of panics, exit and println
* Add basic unit tests
=> Improve cli args parsing in bench-tps

docs/src/developing/programming-model/runtime.md, program-runtime/src/compute_budget.rs, programs/sbf/tests/programs.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs, runtime/src/cost_model.rs, runtime/src/transaction_priority_details.rs, sdk/src/compute_budget.rs, sdk/src/feature_set.rs
Need instruction for users to set per transaction accounts data size limit
- add compute budget instruction, with 64MB as Max (current hard coded limit)
- feature gated
- updated call sites 
Feature Gate Issue: #30366
=> add compute budget instruction to set loaded accounts data size limit

test-validator/src/lib.rs, validator/src/bin/solana-test-validator.rs, validator/src/cli.rs
As discussed in #30412 and #29051, `solana deploy` has been deprecated, so users probably don't intend to use the immutable bpf loader with solana-test-validator either.
Use the upgradeable loader under the hood for `--bpf-program` inputs
Deprecate public non-upgradeable program interfaces
=> Default solana-test-validator --bpf-programs to upgradeable loader

sdk/program/Cargo.toml, zk-token-sdk/Cargo.toml
make `sdk/program/Cargo.toml` and  `zk-token-sdk/Cargo.toml` use bincode 1.3.3.
=> chore: bump bincode to 1.3.3

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/accounts_index_storage.rs, runtime/src/bucket_map_holder.rs, runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
Moving to a more concise disk format for account info in disk index.
Introduce trait `DiskIndexValue` which must be impl'd for disk index type.
Fixes #
=> add DiskIndexValue trait for disk index

runtime/src/account_info.rs
Moving to a different account info stored on disk from what is in memory. `AccountOffsetAndFlags` will be saved to disk in the near future. Note it does not contain `store_id`
Split `AccountInfo` into a sub struct that can be persisted to disk separately.
Fixes #
=> break apart AccountInfo

runtime/src/snapshot_utils.rs
Before constructing a bank from a snapshot, we need to read the snapshot directories and find the highest correct one with the necessary meta info files.  Sometimes a directory may have partial information, not fully ready to be used for bank construction.  Only the ones passing the checks will be selected.
Add snapshot version into BankSnapshotInfo, fill that from the version file;
Add checks to ensure only a correct directory is used to generate a BankSnapshotInfo. 
A function to find the one with the highest slot, which is a wrapper of get_bank_snapshots and selecting the highest one.
Add the test function test_get_highest_bank_snapshot.  It removes the meta files in the directories, and check if it gets the highest correct snapshot.
This is one of the split PRs of …
=> Add checks when constructing a BankSnapshotInfo from a directory 

runtime/src/accounts_db.rs
Use local for store_id instead of reading it from atomic for each account.
Fixes #
=> use local for store_id in write_accounts_to_storage

runtime/src/accounts_db.rs
There is no only 1 append vec per slot.
Use slot instead of store_id in clean functions.
Fixes #
=> use slot instead of store_id in clean

runtime/src/accounts_db.rs, runtime/src/bank_creation_freezing_progress.rs, runtime/src/lib.rs
accounts_db.rs is crowded.
About to add waitable cond var and tests on `BankCreationFreezingProgress`
move `BankCreationFreezingProgress` to its own file. Prepare to impl more to hide details.
Fixes #
=> move BankCreationFreezingProgress to its own file

pubsub-client/src/nonblocking/pubsub_client.rs
`tx` is usually reserved to shorthand `transaction`, but `tx` and `rx` are often used to denote the sender and receiver ends of channels (e.g. mpsc channels).
change instances of `tx` to `sender` and `rx` to `receiver`
=> Disambiguate tx = transaction, tx = sender in `pubsub-client`

perf/src/sigverify.rs
Versioned vote transaction should not be tagged as _simple_ vote tx. 
- filter versioned transaction out of `check_for_simple_vote_transaction`
Fixes #
=> Not to tag versioned transaction as simple_vote_tx

runtime/src/bank.rs, runtime/src/vote_parser.rs, sdk/src/transaction/sanitized.rs
sigverify checks and flags `is_simple_vote_tx` in packet.meta, all downstream should just use the flag when possible. `SanitizedTransaction.try_create()` is an exception because it may not have access to `packet` but only `VersionedTransaction`, so it might have its own implementation.
- removed `VoteParser.is_simple_vote_transaction`, `bank` calls `sanitized_transaction.is_simple_vote_transaction()` directly. 
- updated `sanitized_transaction.try_create()` to set is_simple_vote flag when: is legacy message && has only one vote ix
Fixes #
=> refactor to remove additional is_simple_vote check

runtime/src/prioritization_fee_cache.rs
Transactions request zero CU should not be used to update prioritization fee cache.
- filter out such transaction
Fixes #
=> Not allow transactions request zero CU to update prioritization fee cache

sdk/program/src/vote/state/mod.rs
the existing `VoteState::deserialize` implementation overruns the sbf stack and is unusable in a program context. unfortunately, _all_ programs that import `solana_program` receive a stack size violation warning due to this, regardless of whether they attempt to use the function
compiling spl-token 3.5.0 against solana-program 1.15.3:
```
Compiling solana-program v1.15.3 (/home/hana/work/solana/solana/sdk/program)
Error: Function _ZN14solana_program4vote5state9VoteState11deserialize17hbbcc05667760d2caE Stack offset of 6344 exceeded max offset of 4096 by 2248 bytes, please minimize large stack variables
Error: Function _ZN229_$LT$solana_program..vote..state..vote_state_0_23_5.._..$LT$impl$u20$serde..de..Deserialize$u20$for$u20$solana_program..vote..state..vote_state_0_23_5..VoteState0_23_5$ …
```
=> remove VoteState::deserialize() from sbf builds

.buildkite/scripts/build-downstream-projects.sh
the build doesn't return error although jq cmd not found
https://buildkite.com/solana-labs/solana/builds/90948#01868484-f36c-4355-9551-1b770c65c511
set -e for `.buildkite/scripts/build-downstream-projects.sh`
=> ci: set -e for .buildkite/scripts/build-downstream-projects.sh

geyser-plugin-manager/src/accounts_update_notifier.rs, runtime/benches/append_vec.rs, runtime/src/account_storage/meta.rs, runtime/src/accounts_db.rs, runtime/src/accounts_db/geyser_plugin_utils.rs, runtime/src/ancient_append_vecs.rs, runtime/src/append_vec.rs, runtime/src/snapshot_minimizer.rs, runtime/src/storable_accounts.rs, runtime/store-tool/src/main.rs
This PR makes all the StoredAccountMeta fields `pub(crate)`
and provides getter functions to access its member fields.
This PR is a preparation step for making StoredAccountMeta
a trait.
This PR depends on https://github.com/solana-labs/solana/pull/30443
=> getter functions for StoredAccountMeta

Cargo.lock, install/Cargo.toml, install/src/config.rs
when the `serde_yaml` crate was bumped to v0.9 in #28388, `solana-install` lost the ability to load existing config files written by prior versions. this is operationally... annoying and will likely create a support burden when we start upgrading clusters to v1.15
* reintroduce `serde_yaml` v0.8
* attempt to migrate the config file when load fails with the appropriate error
=> install: support config upgrade from serde_yaml v0.8

ledger-tool/src/main.rs
The v1.14 branch was initially supposed to have the accounts-index on disk. In constrast, v1.13 and previous branches had the accounts-index in memory. However, high disk i/o during validator startup with v1.14 prompted a change to revert to in-memory accounts-index by default. This default behavior was enforced at the level of command line argument parsing, not defaults of the underlying config structs.
The create-snapshot command did not previously have any of the arguments to configure the accounts-index mem/disk usage, so it implicitly used the default AccountsIndexConfig and IndexLimitMb value. As a result, create-snapshot has been running with accounts, accounts-index and the created snapshot all on disk. This shows the similar disk contention whcih results in the create-snapshot …
=> Add accounts-index disk/mem arguments to create-snapshot command

core/src/repair_generic_traversal.rs
`explored_slots` is unnecessary. Slots added to `HeaviestSubtreeForkChoice` in repair are not differentiated by hash with `SlotHashKey`.
Remove `explored_slots`.
Fixes #
=> cleanup get_closeset_completion

net/common.sh, net/net.sh, system-test/testnet-automation.sh
It seems that we make `--allow-private-addr` as a default arg. (https://github.com/solana-labs/solana/pull/30163)
However, we still may pass `--allow-private-addr` to `boostrap-validator.sh`
https://github.com/solana-labs/solana/blob/master/net/common.sh#L72
https://github.com/solana-labs/solana/blob/master/net/net.sh#L947
https://github.com/solana-labs/solana/blob/master/system-test/testnet-automation.sh#L141
and then we will get an error `echo "Unknown argument: --allow-private-addr"`
remove those possibilities and keep `--allow-private-addr` as a default setting
=> fix: remove unnecessary --allow-private-addr setup

sdk/program/Cargo.toml
We have already use `bincode`, `borsh` and `borsh-derive` in [dependencies] section. It seems that we don't need to write them again in [dev-dependencies]
remove `bincode`, `borsh` and `borsh-derive` from [dev-dependencies]
=> chore: remove redundant packages

runtime/src/bucket_map_holder_stats.rs
throttling index generation at startup needs to take into account items held because of refcount != 1.
Throttling occurs at startup to keep us from running out of memory while initially populating the disk index.
include the count of items with refcount != 1 in the excluded list of items to use in throttling calculations.
Fixes #
=> wip: throttle correctly

runtime/src/accounts_db.rs, runtime/src/accounts_index.rs
To remove store_id from AccountInfo, we need to be able to hold index entries in memory while shrinking is taking place.
To do that, we need to hold onto the index entries themselves so they cannot be thrown out.
Hold onto the index entries being shrunk during shrink operations.
Fixes #
=> add index_entries_being_shrunk to ShrinkCollect

core/src/admin_rpc_post_init.rs, core/src/lib.rs, core/src/validator.rs, local-cluster/src/local_cluster.rs, test-validator/src/lib.rs, validator/src/admin_rpc_service.rs, validator/src/bin/solana-test-validator.rs, validator/src/main.rs
The validator admin interface will not accept validator identities while a node is waiting for supermajority during a restart, because the post-init setting doesn't happen until after Validator::new() returns.
Move AdminRpcRequestMetadataPostInit to solana core so it can be used inside Validators::new(). Write admin_rpc_service_post_init just before `wait_for_supermajority()`
Fixes #30530
=> Admin RPC Service: move post-init activation to before wait-for-supermajority

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
we will rely more on stats for why items are held in memory.
Prepare to keep these stats more accurately.
Break out held in memory stats into a struct.
Fixes #
=> consolidate held in mem stats

runtime/src/account_storage/meta.rs
All the references returned from a `StoredAccountMeta` instance actually come from the underlying account.  As written, the lifetimes of the returned references is constrained by the lifetime of the `StoredAccountMeta` instance.
While technically correct, it is overly strict.  It is totally fine to use the returned reference as long as the underlying account is alive. Which could be longer than the lifetime of the `StoredAccountMeta` wrapper.
=> StoredAccountMeta: Relax returned refs lifetimes.

core/src/accounts_hash_verifier.rs
AHV's datapoint names are not consistent with SPS's. This inconsistency makes it slightly harder to quickly understand that the datapoints in AHV and SPS are the same.
https://github.com/solana-labs/solana/blob/db94e4564fefdf37d35362d42bfd9e3ade36261b/core/src/snapshot_packager_service.rs#L113-L127
Rename AHV datapoints to match SPS
=> AHV uses metrics names like SPS's

core/src/accounts_hash_verifier.rs
It is not possible to tell if/when AHV has stopped solely by inspecting logs, which can be useful for debugging.
SPS *does* log when stopped, so AHV could do the same thing.
https://github.com/solana-labs/solana/blob/db94e4564fefdf37d35362d42bfd9e3ade36261b/core/src/snapshot_packager_service.rs#L129
Log when AHV stops
=> AHV logs when stopped

core/src/broadcast_stage/standard_broadcast_run.rs, ledger/src/shred.rs, ledger/src/shred/shred_code.rs
Nodes keep making new shreds and broadcasting them after hitting the shred limit
Panic the node when this case happens
Fixes #
=> Panic when shred index exceeds the max per slot

ledger/src/shred/legacy.rs, ledger/src/shred/shred_code.rs, ledger/src/shredder.rs
https://github.com/solana-labs/solana/pull/26070 introduced `MAX_CODE_SHREDS_PER_SLOT` which because of how coding shreds are generated was later set larger than `MAX_DATA_SHREDS_PER_SLOT`.
The old code was discarding: `index >= MAX_DATA_SHREDS_PER_SLOT` regardless of if the shred is code or data:
https://github.com/solana-labs/solana/blob/v1.13.6/core/src/window_service.rs#L193-L195
This might allow more load on the cluster for slots which don't get rooted anyways.
Since that many code (or data) shreds will probably never result in a rooted slot anyways, the commit reduces `MAX_CODE_SHREDS_PER_SLOT` to what previously was the effective limit.
=> reduces MAX_CODE_SHREDS_PER_SLOT

core/src/validator.rs
backup_and_clear_blockstore() opens a Blockstore session; however, it
is currently using Blockstore::open(). This Blockstore method uses
BlockstoreOption::default() under the hood. As a result, any validator
args that adjust Blockstore settings are not considered in
backup_and_clear_blockstore().
This is especially problematic if the non-default value of
--rocksdb-shred-compaction is being used. In this case,
backup_and_clear_blockstore() was opening the wrong directory and
incorrectly finding an empty ledger.
This change plumbs any blockstore configuration to
backup_and_clear_blockstore().
Fixes #30528
=> Make backup_and_clear_blockstore() honor ValidatorConfig options

runtime/src/accounts_db.rs, runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
There is value in 1.15 being able to load any snapshot from 1.13 or 1.14.
Loading from a snapshot with > 1 storage per slot, combine the multiple accounts into 1 storage.
Fixes #
=> support loading snapshots with > 1 append vec per slot

program-runtime/src/invoke_context.rs, program-test/src/lib.rs, programs/address-lookup-table/src/processor.rs, programs/bpf_loader/src/lib.rs, programs/compute-budget/src/lib.rs, programs/config/src/config_processor.rs, programs/stake/src/stake_instruction.rs, programs/vote/benches/process_vote.rs, programs/vote/src/vote_processor.rs, programs/zk-token-proof/src/lib.rs, runtime/benches/bank.rs, runtime/src/bank/tests.rs, runtime/src/builtins.rs, runtime/src/message_processor.rs, runtime/src/system_instruction_processor.rs
`first_instruction_account` is being passed around to all built-in programs even though it is only used in `bpf_loader`.
Moves the calculation of `first_instruction_account` from `InvokeContext::process_executable_chain()` into `bpf_loader::process_instruction_common()`.
=> Refactor - Remove `process_instruction` parameter `first_instruction_account`

core/benches/banking_stage.rs, core/src/banking_stage.rs, core/src/banking_stage/consumer.rs
Lots of common parameters passed all the way down the chain of functions for consuming packets.
Blocked by #30253 
Move common structs onto Consumer so we don't need to pass them everywhere
Fixes #
=> BankingStage Refactor: Consumer State

runtime/benches/append_vec.rs, runtime/src/account_storage/meta.rs, runtime/src/accounts_db.rs, runtime/src/accounts_file.rs, runtime/src/append_vec.rs
The existing append_accounts returns a vector of offsets, which accounts-db
later uses it to infer the storage size of each account.  However, such inference
does not apply to the new hot/cold storage format.
This PR changes the return value of append_accounts() to `Vec<StoredAccountInfo>`,
which includes both offset and storage size information of an account.
=> Generalize the return value of append_accounts()

runtime/src/accounts_db.rs
`get_all_accounts()` does not accept closed ranges.
As `Range` is a special case of an `Iterator`, this is a generalization that makes `get_all_accounts()` accept other kinds of ranges.  Such as `RangeInclusive`.
=> accounts_db::get_all_accounts: Select slots with an iterator

sdk/bpf/scripts/install.sh, sdk/cargo-build-sbf/src/main.rs, sdk/sbf/scripts/install.sh
- this release includes fixes in relocation handling necessary for source-level debugging of on-chain programs
=> Bump sbf-tools version to v1.35

.mergify.yml
v1.15 is dead. Once v1.14 hits mainnet, we'll create a v1.16 branch off master at that time and work towards stabilizing it.
=> mergify: Remove v1.15 backport rules

.mergify.yml
v1.13 is no longer needed. Remove its mergify backport config
=> CI: Remove mergify backport config for v1.13

core/src/retransmit_stage.rs
Retransmit shreds received cache can overflow with supported slot sizes.
- Increase packet cache size based on max number of shreds per slot.
- Add metric to count number of times an entry is evicted from the LRU shred cache to detect overflow.
Fixes #
=> increase retransmit shreds received cache size

docs/src/developing/on-chain-programs/debugging.md
Debugging on-chain programs using rbpf-cli and Solana sdk lldb is not documented.
Add instructions about debugging an on-chain program and setting up VSCode for debugging on-chain programs.
=> Document debugging on-chain programs

program-test/tests/lamports.rs
There was an error in upgrading the stake-o-matic registration program to 1.13, where it gave `UnbalancedInstruction` for an instruction that provided an account twice, and moved lamports to that account. The issue was most likely due to poor propagation of account state changes in program-test, which has been fixed post-1.13.  See the fixing PR in stake-o-matic at https://github.com/solana-foundation/stake-o-matic/pull/471
Add a test exercising the behavior to avoid re-introducing the bug in the future. I tested this against 1.13 as well, where it showed the `UnbalancedInstruction` error.
This was fixed in #26507
Fixes #
=> program-test: Add test for moving lamports

docs/src/index.mdx
I discovered a typo in the index of Solana documentation
Fix the typo: `Documentaion` -> `Documentation` 
Fixes #
=> [docs] Fix typos

ci/docker-run.sh
There's no way for team eng to get out of being stuck after ci cache issue.
implement ala circleci's build-without-cache feature:
seems to work:
Fixes #
=> Disable cache if retried 3 times

programs/bpf_loader/src/lib.rs
The logic in `process_instruction_common()` is quite complex and hard to understand. Additionally, we want to get rid of `program_indices` and `try_borrow_program_account`, so their usage in the BPF loader needs to be minimized.
There are five cases of what `program_account` inputs `process_instruction_common()` needs to handle:
- Program Management Instruction: [Loader]
- Transaction Level Instruction: [Loader, Program]
- Transaction Level Instruction: [Loader, Programdata, Program]
- Cross Program Invocation: [Program]
- Cross Program Invocation: [Programdata, Program]
From that we can tell, that we only need to look at the last program in the chain, and only in case of the upgradeable loader also need the second last (the programdata account).
- Removes `first_instruction_account` from …
=> Refactor - Remove `first_instruction_account` in `bpf_loader`

docs/src/api/methods/_getBlocks.mdx
I'm pretty sure these are backwards.
Note, in the docs, that `start_slot` comes first and `end_slot` (optionally) comes next.
=> docs: fix order of positional `start_slot` and `end_slot` in `getBlocks` API docs

core/src/heaviest_subtree_fork_choice.rs, core/src/repair_service.rs, core/src/repair_weight.rs
When updating root, we purge all unrooted slots and track them so they cannot be added back in even if voted on
To keep repair weights more accurate, track pruned subtrees.
We manage size by cleaning up slots that are less than new root
Fixes #
=> Track pruned subtrees in repair weight

core/src/repair_weight.rs
https://github.com/solana-labs/solana/pull/29922 merged in without rebasing #30438, so even though all CI checks were green this ended up breaking master. 
Add back the contains trait
Fixes #
=> Fix repair_weight test bad merge failure

.buildkite/hooks/pre-command, ci/docker-run.sh
https://discord.com/channels/428295358100013066/560503042458517505/1083170016163274812
add `SCCACHE_S3_KEY_PREFIX` to share cache in a more stable way. It will create a folder for us. for now I use 
`SCCACHE_S3_KEY_PREFIX="${rust_stable}_${rust_nightly}_${SBF_TOOLS_VERSION}"`
it looks like this on s3
Close #29366
=> ci: add SCCACHE_S3_KEY_PREFIX

runtime/src/account_storage/meta.rs, runtime/src/accounts_db.rs, runtime/src/accounts_db/geyser_plugin_utils.rs, runtime/src/ancient_append_vecs.rs, runtime/src/append_vec.rs, runtime/src/storable_accounts.rs
The existing StoredAccountMeta requires the file and in-memory layout of
account metadata to match StoredMeta and AccountMeta.  This limits the
flexibility to implement different accounts storage file formats.
This PR abstracts out StoredAccountMeta as an Enum.
This PR depends on https://github.com/solana-labs/solana/pull/30571.
=> Abstract out StoredAccountMeta as an Enum

.codecov.yml, runtime/src/bank.rs
restored codecov caused some issues: https://discord.com/channels/428295358100013066/560503042458517505/1083472186305675435
this is original yml (no text; took only screenshot when reviewing codecov's settings before enabling; never expected this would cause troubles and yml is nuked now... lol):
- Removed `fixes: ... web3` thing (no longer needed thanks to #30062)
- Added `github_checks: false`. (this is crucial not to block merge, i think)
```
$ curl --data-binary @.codecov.yml https://codecov.io/validate
Valid!
{
"comment": {
"behavior": "default",
"layout": "diff",
"require_changes": false
},
"coverage": {
"precision": 1,
"range": [
50.0,
100.0
],
"round": "down",
"status": {
"patch": false,
"project": false
}
},
"github_checks": false
}
```
=> Add .codecov.yml with checks disabled

runtime/src/bank.rs
The most common validator configuration is JIT on, so test that. On platforms that don't support JIT we'll still fallback on the interpreter.
=> Enable JIT in Bank::new_with_config_for_tests()

ledger/src/builtins.rs, program-runtime/src/invoke_context.rs, program-test/src/lib.rs, programs/bpf_loader/src/deprecated.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/upgradeable.rs, programs/bpf_loader/src/upgradeable_with_jit.rs, programs/bpf_loader/src/with_jit.rs, programs/sbf/benches/bpf_loader.rs, programs/sbf/tests/programs.rs, runtime/benches/bank.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs, runtime/src/builtins.rs, runtime/src/message_processor.rs, sdk/src/builtins.rs
Builtin should consume compute units when executed; if no exact units being deducted from compute budget, a default cost should be used. In order to do so, a mandatory `default_cost` field is added to `Builtin`, which is passed down to `invoke_context::BuiltinProgram` where it can be used for compute budget. 
- add mandatory `default_cost` to `Builtin`, assigned pre-defined value from `block_cost_limits.rs`
- updated macros
- pass default_cost to `invoke_context::BuiltinProgram` (A follow up PR would use that value to deduct builtin's cost from compute budget)
Fixes #
=> add default_cost as mandatory field for Builtin

runtime/src/bank.rs
The logs at startup when verifying a snapshot bank leave more to be desired—at least from me.
- It would be nice to know when each step completes
- It would be nice to know if a step was skipped
- The accounts hash calculation and verification is called "bank hash"
- The bank hash verification is just called "hash", so it's a bit confusing to see this right after seeing "verify_bank_hash.."
* Add explicit logs for when each step is done or skipped
* Correct the naming for accounts hash vs bank hash verification
Note, the diff makes it look like a lot changed. There was no change to any *functionality* (or at least there should not be). I recommend ignoring whitespace in the diff to make this more obvious.
=> Improves logs in bank verification at startup

core/src/progress_map.rs, core/src/replay_stage.rs
https://github.com/solana-labs/solana/blob/94ef881de/core/src/progress_map.rs#L178
always returns true the first time around because retry_time is None.
So every slot is broadcasted twice.
Removed `.unwrap_or(true)`.
=> stops nodes from broadcasting slots twice

core/src/progress_map.rs, core/src/replay_stage.rs, ledger/src/blockstore.rs
```diff
- This is manual v1.13 backport of:
- https://github.com/solana-labs/solana/pull/30681
```
https://github.com/solana-labs/solana/blob/94ef881de/core/src/progress_map.rs#L178 always returns true the first time around because retry_time is None. So every slot is broadcasted twice.
removed `unwrap_or(true)`.
=> v1.13: stops nodes from broadcasting slots twice (backport of #30681)

core/src/replay_stage.rs
Apparently https://github.com/solana-labs/solana/pull/30681 made `test_retransmit_latest_unpropagated_leader_slot` flaky.
"fixed" it.
=> patches flaky test_retransmit_latest_unpropagated_leader_slot

core/src/validator.rs
`validator_parallel_exit` test regenerates the `GenesisConfig` for each validator, despite them using the same leader node. since `GenesisConfig` contains a seconds-precision timestamp and `GenesisConfig::default()` queries said timestamp, this introduces a race condition on the genesis hash at second boundaries.
no idea if the is _the_ problem, but this test has been flaky af for ages
share one `GenesisConfig` between all validator instances in `validator_parallel_exit` test
=> tests: share `GenesisConfig` in `validator_parallel_exit`

core/src/accounts_hash_verifier.rs, runtime/src/accounts_db.rs
For Incremental Accounts Hash, when processing an incremental snapshot package in AccountsHashVerifier (AHV), we will need to get the full snapshot's accounts hash and capitalization. That information will come from `AccountsDb::accounts_hashes`. But right now *no one*[^1] updates `AccountsDb::accounts_hashes`. Thus, the full snapshot's accounts hash and capitalization are *not* available in AHV when needed.
In AHV, update `AccountsDb::accounts_hashes` with the calculated accounts hash and capitalization
[^1]: When creating a snapshot with ledger-tool, `AccountsDb::accounts_hashes` is updated. But that's not useful/usable for a normal validator.
=> AccountsHashVerifier updates AccountsDb after calculating accounts hash

rpc/src/rpc_service.rs
rpc_service.rs uses `current_transaction_status_slot` where the rest of the code base calls this variable `max_complete_transaction_status_slot`. Rename within rpc_service.rs for easier searching across files
=> rpc_service: Rename variable for consistency with the rest of the code base

ledger-tool/src/main.rs
#30357 and #30541
both used `matches` instead of `arg_matches`
The result was that disk index was always disabled in 1.14 ledger-tool verify and create-snapshot. This is incorrect.
lookup args in `arg_matches`
Fixes #
=> use arg_matches instead of matches for ledger tool args

docs/src/api/methods/_getRecentPrioritizationFees.mdx, docs/src/developing/intro/transaction_fees.md, docs/src/developing/programming-model/runtime.md, docs/src/terminology.md, docs/src/transaction_fees.md
The docs lack complete information on how to use prioritization fees and what they are
- moved prioritization fees info from `runtime` to `transaction_fees` (left a brief explainer and internal link)
- added more information and examples of how to use prioritization fees to the `transaction_fees` page
- added elaboration of `micro-lamports` to the terminology page
=> docs: prioritization fees

validator/src/cli.rs, validator/src/main.rs
See
[discord discussion](https://discord.com/channels/428295358100013066/1075087536361320548/1084962412744147057)
When starting a validator, we currently skip startup clean and shrink if the snapshot was generated locally. As of 1.13 or 1.14?, we now start accounts background service much earlier in the startup process. Accounts background service does a clean and shrink concurrently with tx processing.
Note that clean is probably slower with a disk index than without. This synchronous clean thus has a bigger penalty on startup when disk index is enabled.
Always skip the synchronous initial clean/shrink on validator startup. Make the cli arg obsolete.
Fixes #
=> validators always skip clean/shrink on startup

ledger/src/blockstore_processor.rs, sdk/src/feature_set.rs
This reverts commit e7a57ca21f09834cd915505df37005abb5e691c2.
backing out a noncritical, no-affect bp
=> Revert "remove dated cost checking feature (backport #29598) (#29656)"

programs/bpf_loader/src/lib.rs, sdk/src/feature_set.rs
Should round up heap size to next 32k block before `div`
- refactor the heap cost into a function
- add test with refraction heap size (the 3rd case would fail before fix)
- fix size truncation by round up to next 32K block first
- add feature gate
- check result of `consume_checked` if feature is activated 
OPTIONAL: Feature Gate Issue: #30679
=> fix heap cost calculation rounding error

core/src/replay_stage.rs, ledger/src/blockstore_processor.rs
it's bothersome to understand how `entry_callback` is used. ~Actually, it can be `#cfg(test)`-ed trivially.~
~do it for easier reasoning.~
~just by coincidence, this is very similar to this: https://github.com/solana-labs/solana/pull/30288#discussion_r1121013327 (so, I'm requesting @apfitzge for review, how you'd like these along line of changes, in general)~
~context here is that, I'm finally creating preparatory prs to merge the unified scheduler. for it to make compatible with current impl, I need to be very careful to the extent i need to examine the actual use of each and every args of blockstore_processor.~
EDIT: turned out it can be removed.
=> Remove unused ProcessOptions::entry_callback

core/src/banking_stage.rs, core/src/banking_stage/decision_maker.rs, core/src/leader_slot_banking_stage_metrics.rs
Central scheduler will not use LeaderSlotReceiveMetricsTracker. 
Separate the updating of leader slot metrics from decision making so that scheduler isn't forced to use it.
Fixes #
=> Separate stats updates from decision_maker

runtime/src/accounts_file.rs, runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/tests.rs
Accounts db currently use AppendVec::new_from_file() directly
to create a new AcountsFile instance from an existing file.
However, this method should be abstracted out to AccountsFile
so that an existing file can be opened correctly using the right format.
Add new_from_file() API to AccountsFile which will open an existing
file based on its accounts file format.
Currently, it only supports AppendVec.
=> Add new_from_file() API to AccountsFile

ci/do-audit.sh, ci/docker-run.sh
=> ci: fix do-audit don't report error

cli/src/cli.rs, cli/src/stake.rs, cli/tests/stake.rs
We introduced a bug in https://github.com/solana-labs/solana/pull/26294, namely that the `redelegation_stake_account` is always included in `bulk_signers`, which pulls in the default keypair when not redelegating. This causes problems for a normal `solana delegate-stake` command that attempts to specify all signers to other than the default keypair -- `try_partial_sign` attempts to sign with the default keypair, even though that pubkey is not present in the transaction.
Rework `redelegation_stake_account` to match the pattern for optional signers in other commands
Incidentally, I [mentioned nonces](https://discord.com/channels/428295358100013066/910937142182682656/1085590351915520203) in my initial look at this bug. This is because it was the `nonce_authority` index that was pointing to …
=> Make redelegate signer more optional

Cargo.lock, core/src/sigverify_stage.rs, perf/Cargo.toml, perf/benches/dedup.rs, perf/src/deduper.rs
Current Deduper implementation uses many bits per entry:
https://github.com/solana-labs/solana/blob/65cd55261/perf/src/deduper.rs#L70-L73
and may be saturated quickly. It also lacks api to specify desired false positive rate.
The commit instead uses an atomic bloom filter with K hash functions. The false positive rate is obtained by tracking popcount of bits.
Note that with K=2, this is 2x slower than the old deduper, because the old deduper had only one hasher. On the other hand because we only consume 2 bits per entry, this gets saturated less quickly and would need less frequent resets.
=> dedups packets using an atomic bloom filter

bucket_map/src/bucket.rs, bucket_map/src/bucket_api.rs, bucket_map/src/bucket_map.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
Working towards improving disk index performance:
#30711
avoid difficulties by returning `&[]` instead of something more complicated from disk index when an empty slice is required
Fixes #
=> disk index handles empty slot list more correctly

ledger-tool/src/main.rs
To test future branches for mainnet-beta, we anticipate testnet first rolling back to mainnet-beta software version and feature-gate state and then executing the update. This will almost always require deactivating some feature gates that are active on testnet, but not yet on mainnet-beta. There's currently no overt way to deactivate feature gates when running `solana-ledger-tool create-snapshot`.
Add `--deactivate-feature` parameter, which checks that an account is indeed a `solana_sdk::feature::Feature` before removing it. Logs a warning if account is a queued feature gate that is not yet active.
=> Ledger-tool: add param to deactivate features in snapshot creation

ledger-tool/src/main.rs
Declare constants at top of function with comment, and stringify the constants when needed to be in line with how other defaults are done in ledger-tool main function.
This stemmed from a comment in https://github.com/solana-labs/solana/pull/30704 - Upstreaming this in master and will BP to other branches for sake of consistency between them.
=> ledger-tool: chore: Cleanup snapshot retention constants

runtime/src/bank.rs
https://github.com/solana-labs/solana/pull/29628 swapped args in wrong way
this is breaking my consensus rainbow charting tool....
Fix it.
=> Fix wrongly swapped parent slot and block height

measure/src/measure.rs
In most cases, for a given `Measure` value, a `stop()` call must always be followed by a call to one of the `as_*()` methods.  Combining them into a single function call makes the API a bit simpler.
=> measure: Measure::end_as{ns,us,ms,s,duration}

bucket_map/src/bucket.rs
see #30711
The current implementation of disk buckets (as used by accounts index on disk) was optimized for use as a hashmap with good speed in all cases.
The implementation in the validator synchronizes the in-mem hash map with the disk based one in the background.
Currently, we resize data buckets when we don't find an empty spot when starting a search at a random offset and searching for `max_search`, which is defaulted to approximately 32.
This max search makes sense for the index buckets where we have to exhaustively search on read and write to prove something does not exist. For data buckets, we just need to find any vacant bucket to store data. The offset will then be stored in the index bucket.
Search 10x locations before resizing disk buckets. This will result in more compact …
=> when writing to disk bucket index, tune towards packing tighter

metrics/src/datapoint.rs
When I write a macro that calls one of the `datapoint` macros inside, I need to special case it, due to the `datapoint` macros not allowing trailing commas.
Rust grammar allows trailing commas in most places where a list of elements is accepted.  It simplifies cases when the list is generated by a macro, allowing the macro to avoid special cases for a one element list vs longer lists.
As such, it is a common practice to allow trailing commas in macros as well.
Accept and ignore a single trailing comma in all macro calls.
=> metrics: datapoint macro: Allow trailing comma

core/src/validator.rs, ledger-tool/src/main.rs, local-cluster/src/validator_configs.rs, runtime/src/snapshot_utils.rs, validator/src/main.rs
In the bank snapshot dir snpashot/\<slot\>/, there is account_hardlinks/ which contains a list of symlinks to <account_path>/snapshot/\<slot\>/.  When purging an old bank snapshot, the code follows the these symlinks to go to <account_path>/ to clear the old snapshot slots there.
We observed a case that there are extra <account_path>/snapshot/\<slot\>/ not referenced by the symlinks in snpashot/\<slot\>/account_hardlinks/, therefore they are left unpurged.
Add the function clean_orphaned_account_snapshot_dirs to clean up all <account_path>/snapshot/\<slot\>/ directories not referenced by the symlinks in  snpashot/\<slot\>/account_hardlinks/
clean_orphaned_account_snapshot_dirs requires account_snapshot_paths, which were returned by create_accounts_run_and_snapshot_dirs but dropped.  I …
=> Clean orphaned account snapshot dirs

runtime/benches/accounts.rs, runtime/src/accounts_db.rs
`AccountsDb::get_snapshot_storages()` has a parameter for ancestors. Also, all storages returned must be for rooted slots. Since ancestors are only useful for disambiguating unrooted slots on forks, the param is effectively useless. Additionally, I was confused why it existed and had to investigate that it was left over from previous cleanup.
Remove `ancestors` param from `AccountsDb::get_snapshot_storages()`.
For small, incremental PRs and diffs, future PRs will clean up the *callers* of this function.
=> Do not use ancestors in get_snapshot_storages

ledger-tool/src/main.rs
Manual backport of #27788 and #30745 to ensure that ledger-tool won't delete any snapshots when running commands.
=> v1.13: ledger-tool: Retain all snapshots by default

core/src/shred_fetch_stage.rs, core/src/sigverify_stage.rs, perf/benches/dedup.rs, perf/src/deduper.rs
`Deduper.false_positive_rate` field is misleading because it is not enforced until `maybe_reset` is called. But then `maybe_reset` can be invoked with an explicit argument.
* removed the `false_positive_rate` field from `Deduper`.
* `maybe_reset` now takes a `false_positive_rate` argument.
=> removes false_positive_rate field from Deduper

core/src/shred_fetch_stage.rs, core/src/sigverify_stage.rs, ledger/src/shred/stats.rs
track how often the deduper gets saturated before reset-cycle.
added metrics.
=> adds metrics tracking deduper saturations

core/src/shred_fetch_stage.rs
Current merkle shreds feature-gates are "on" by default which is not backward compatible.
In order to maintain backward compatibility, the commit reworks merkle shreds feature gate to off by default until the feature activation.
=> filters out merkle shreds until feature activation

Cargo.lock, accounts-cluster-bench/Cargo.toml, accounts-cluster-bench/src/main.rs, client/src/transaction_executor.rs
Similar [to bench-tps](https://github.com/solana-labs/solana/pull/24227), accounts-cluster-bench was written for custom clusters, so it assumes rpc access is available at the entrypoint and every node in the cluster. This means the tool can't be easy pointed at public clusters, like testnet.
Broader context: we are using this tool to increase the size of testnet snapshots, and an expanded version of this tool may be useful in the future to make testnet topography better reflect that on mainnet-beta
Add support for the `--url` parameter and monikers in accounts-cluster-bench, and use to create RpcClient.
Also update airdrops to use rpc instead of trying to target the faucet directly (avoiding the need for the machine where accounts-cluster-bench to be whitelisted on a public faucet).
This …
=> Update accounts-cluster-bench to work against public clusters

runtime/src/account_info.rs, runtime/src/accounts_file.rs, runtime/src/append_vec.rs, runtime/src/lib.rs
As we start supporting new storage formats, alignment-related constants and macros
defined in append_vec.rs aren't only specific to AppendVec.
Move alignment-related constants/macros from append_vec.rs to accounts_file.rs
=> Move alignment related consts from append_vec.rs to accounts_file.rs

core/src/sigverify_shreds.rs, ledger/benches/sigverify_shreds.rs, ledger/src/sigverify_shreds.rs
The lazy-static thread-pool is not accessible from outside the `ledger/src/sigverfiy_shreds.rs` file.
The commit passes the thread-pool explicitly from higher in the call stack so that https://github.com/solana-labs/solana/pull/30786 can use the same thread-pool for shred deduplication.
=> removes lazy-static thread-pool from sigverify-shreds

ledger/src/blockstore_processor.rs
There is some logic related to how timing values are collected that is not immediately obvious.  It is better to document it, rather than requiring everyone interested to reverse engineer it from the code.
=> doc: ledger: Document `ConfirmationTiming`

programs/bpf_loader/src/lib.rs, programs/sbf/tests/programs.rs, sdk/src/feature_set.rs
#30614 removed an incorrect error condition partially and without a feature gate.
Add a feature gate `remove_bpf_loader_incorrect_program_id` which temporarily reverts the behavior back to what it was before.
Feature Gate Issue: #30747
=> Fix - Revert and feature gate incorrect error message in BPF loader

ledger/src/blockstore.rs, ledger/src/blockstore_meta.rs, ledger/src/blockstore_processor.rs
First off, kudos to @offerm for initially spotting something was awry in https://github.com/solana-labs/solana/issues/27729 and https://github.com/solana-labs/solana/pull/27786.
The SlotMeta `is_connected` field was found to not be functioning as expected. Namely, `is_connected` was permanently false for nodes starting from snapshots because the supplied definition of is_connected requires a "path" back to genesis. See more details in https://github.com/solana-labs/solana/issues/27820
Change `is_connected` boolean to bitflags to allow tracking more state
```rust
pub struct ConnectedFlags:u8 {
const CONNECTED        = 0b0000_0001;
const PARENT_CONNECTED = 0b1000_0000;
}
```
Now, when `load_frozen_forks()` is called, the first slot will be marked as connected, as starting will either be at …
=> Fix SlotMeta connected tracking

runtime/src/bank.rs
At startup verification, we calculate the accounts hash and compare it with what was in the snapshot. This accounts hash calculation is over the whole slot range, so `clean` and `shrink` here don't affect the calculation.
However, with Incremental Accounts Hash, we're going to calculate the accounts hash over a *subset* of slots/storages—not all. This means if we `clean` *past* the slot we're about to use for the accounts hash calculation, then accounts can be removed from older storages, which will affect the calculation and produce a different value, and then cause startup snapshot verification to fail.
At startup in snapshot verification, do not clean past the last full snapshot slot.
(I remember we've also talked about removing this serial `clean` and `shrink` entirely; I didn't want …
=> Cleans *up to* the last full snapshot slot in verify_snapshot_bank()

core/tests/snapshots.rs, local-cluster/src/local_cluster.rs, runtime/src/snapshot_utils.rs
`snapshot_utils` does not know about Incremental Accounts Hash, so the helps functions that create snapshots, and the functions that reconstruct a bank from snapshot archives cannot handle IAH.
`snapshot_utils` can now to do bank-to-snapshot-archive and bank-from-snapshot-archive for incremental snapshots with IAH.
Feature Gate Issue: #30819
=> Makes snapshot_utils aware of Incremental Accounts Hash

programs/sbf/c/src/read_program/read_program.c, programs/sbf/tests/programs.rs
We are currently missing a test to check the following use case:
A program reads data from a program account.
E.g. to verify the version or some sort of signature.
Adds `test_program_reads_from_program_account()`.
=> Adds test for programs which read from a program account

Cargo.lock, core/src/sigverify_stage.rs, perf/Cargo.toml, perf/benches/dedup.rs, perf/src/sigverify.rs
```diff
- This is manual v1.13 backport of:
- https://github.com/solana-labs/solana/pull/30726
```
dedups packets using an atomic bloom filter (#30726)
Current Deduper implementation uses many bits per entry:
https://github.com/solana-labs/solana/blob/65cd55261/perf/src/deduper.rs#L70-L73
and may be saturated quickly. It also lacks api to specify desired false
positive rate.
The commit instead uses an atomic bloom filter with K hash functions.
The false positive rate is obtained by tracking popcount of bits.
(cherry picked from commit 7a7b020580ebe26533bea14d64a20753ef601cf8)
=> v1.13: dedups packets using an atomic bloom filter (backport of #30726)

runtime/src/accounts_db.rs, runtime/src/in_mem_accounts_index.rs
See #30711
At startup, scan storages to populate index. We can easily identify pubkeys that are in multiple slots (duplicates).
There are metrics on this, but they have misleading names.
More importantly, the duplicate list needs to include the first slot we encounter that contains a given duplicate pubkey so that clean will pick it up correctly.
Rename and add metrics.
When we find the first duplicate, also mark as duplicate the first item that was already added which has now become a duplicate.
Fixes #
=> better duplicate key stats during index generation

runtime/src/bank.rs, runtime/src/vote_account.rs
On mainnet, it shows that it takes 100ms - 400ms to update epoch stakes at the
epoch boundary. 
Most of the time is spent on logging the details of epoch stakes. 
Do not log the details of epoch stakes.
Fixes #
=> Do not log detailed epoch stakes

bucket_map/src/bucket.rs
Upcoming work causes `allocate()` to take `&mut self`. This breaks the borrow checker in the missing/to be allocated case of `find_entry_mut`.
Only return an element if it is found. If it must be allocated, return a None and the calling code can look up the slot instead.
Fixes #
=> rework find_entry_mut for missing case

core/src/packet_hasher.rs, core/src/shred_fetch_stage.rs, core/src/validator.rs, perf/src/sigverify.rs
```diff
- This is manual v1.13 backport of:
- https://github.com/solana-labs/solana/pull/30690
```
increases shred-fetch-stage deduper capacity and reset-cycle (#30690)
(cherry picked from commit 93f696dac720ec6beac70ea01508872e6851bd36)
=> v1.13: increases shred-fetch-stage deduper capacity and reset-cycle (backport of #30690)

programs/sbf/tests/programs.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs, sdk/src/feature_set.rs
Transaction should pay for memory space it requests to load accounts.
Transaction can request limit of loaded accounts data size via `compute_budget.loaded_accounts_data_size_limit` instruction (after v1.16 and feature `support_set_loaded_accounts_data_size_limit_ix` activation), otherwise the MAX limit of 64MB per tx is used as default.
`runtime` charges heap space at rate of 8cu per 32K. We can use same rate to charge compute units for requested memory for loading accounts, fold into transaction's request compute unit limit before submitting to `fee_structure` to calculate lamports as part of transaction base fee.
- feature gate
- use heap rate to calculate requested accounts space
- summarize compute units from both requested CU and calculated accounts CU, then submit to fee_structure. …
=> include loaded accounts data size limit in transaction fee calculation

core/src/shred_fetch_stage.rs, core/src/sigverify_stage.rs, perf/benches/dedup.rs, perf/src/sigverify.rs
```diff
- this is manual v1.13 backport of:
- https://github.com/solana-labs/solana/pull/30788
```
Deduper.false_positive_rate field is misleading because it is not
enforced until maybe_reset is called. But then maybe_reset can be
invoked with an explicit argument.
(cherry picked from commit 46614c0e9f66773d375ef8b49095158c86a6ac2f)
=> v1.13: removes the false_positive_rate field from the Deduper (backport of #30788)

core/src/shred_fetch_stage.rs, core/src/sigverify_stage.rs, ledger/src/shred_stats.rs
```diff
- This is manual v1.13 backport of
- https://github.com/solana-labs/solana/pull/30779
```
(cherry picked from commit 4b595ebaaf9cb0605a4bb30bea3a217f1c851b81)
=> v1.13: adds metrics tracking deduper saturations (backport of #30779)

core/src/validator.rs, ledger-tool/src/main.rs, ledger/src/blockstore_processor.rs, local-cluster/src/validator_configs.rs, local-cluster/tests/local_cluster.rs, test-validator/src/lib.rs, validator/src/cli.rs, validator/src/main.rs
`poh_verify` actually disables transaction signature, tick count and built in program argument verifications as well.  It is somewhat confusing to call it `poh_verify`.
Renamed it to `run_verification`, along with the CLI argument.
Old argument is still accepted, but produces a deprecation message, suggesting a new name.
=> poh_verify => run_verification: Rename to be more accurate

runtime/src/bucket_map_holder_stats.rs, runtime/src/in_mem_accounts_index.rs
Disk bucket flushing is a source of much i/o.
Add stat for how many disk buckets are flushed when we log accounts index info every 10s.
Fixes #
=> add stat for disk buckets flushed

bucket_map/src/bucket_storage.rs
If we store the single bit for 'allocated' status somewhere other than the header of each element, we save 8 bytes per element. Also remember the disk index is possibly 2x over-allocated.
Storage options include:
1. in-mem bitfield per bucket
2. in high bits stolen from `ref_count`'s high bits
3. in some other clever place (such as pubkey being a random pubkey which is unlikely to ever be used)
Placeholders for removing the allocated bit from the header.
Fixes #
=> disk bucket allocated bit can be not in header

core/src/serve_repair.rs, perf/src/data_budget.rs
Repair requests can still access blockstore after bandwidth budget has been exhausted.
- Check if there is sufficient bandwidth in the budget to process the request prior to querying blockstore.
- Allow processing of Pong messages in the packet batch if bandwidth has been exhausted.
Fixes #
=> check data budget before accessing blockstore

Cargo.lock, core/Cargo.toml, core/src/validator.rs, ledger-tool/src/main.rs, local-cluster/src/validator_configs.rs, programs/sbf/Cargo.lock, validator/src/cli.rs, validator/src/main.rs
There's no way to switch block verification/production implementations from cli in the replay/banking stages.
Add minimal cli-side plumbing so that we can add actual impls. 
Hope, my unified scheduler for replaying can come soon....
Anyway, let's focus to battle for naming of cli args and descriptions here. :)
bike shed battle ended:
```
$ SOLANA_NO_HIDDEN_CLI_ARGS_= ./target/release/solana-ledger-tool verify --help
...
--block-production-method <METHOD>
Switch transaction scheduling method for producing ledger entries [default: thread-local-multi-iterator]
[possible values: thread-local-multi-iterator]
--block-verification-method <METHOD>
Switch transaction scheduling method for verifying ledger entries [default: blockstore-processor] [possible
values: blockstore-processor, …
```
=> Add --block-{verification,production}-method flags (noop atm)

cli/src/stake.rs
The cli doesn't require that `stake-authorize-checked` include an authority to change, and ultimately submits an empty transaction if you don't provide one.
In contrast, the unchecked `stake-authorize` uses `.required_unless("new_withdraw_authority")` on `new_stake_authority` and `.required_unless("new_stake_authority")` on `new_withdraw_authority`.
```
$ solana stake-authorize
error: The following required arguments were not provided:
<STAKE_ACCOUNT_ADDRESS>
--new-stake-authority <PUBKEY>
--new-withdraw-authority <PUBKEY>
USAGE:
solana stake-authorize <STAKE_ACCOUNT_ADDRESS> --config <FILEPATH> --new-stake-authority <PUBKEY> --new-withdraw-authority <PUBKEY>
```
```
$ solana stake-authorize-checked
error: The following required arguments were not provided:
<STAKE_ACCOUNT_ADDRESS>
USAGE: …
```
=> cli: require one or more authority params in `stake-authorized-checked`

ledger/src/blockstore_processor.rs
#30600 removed the `entry_callback` parameter for `process_entries_with_callback`. Name is now misleading.
Rename it to simply `process_entries`. Also we no longer have too many parameters -> goodbye clippy allow
Fixes #
=> rename process_entries_with_callback to process_entries

ledger-tool/src/main.rs, ledger/src/blockstore.rs
In cluster restart scenarios, it is desirable to know the latest
optimistic slot(s), which the subcommand latest-optimistic-slots will
return. However, it is also useful to know whether slots contain only
votes or if they contain votes and user transactions.
This change adds an extra column of output that tells whether a slot is
vote only (contains zero non-votes), and adds a flag that enables viewing
only slots that are NOT vote-only.
On a ledger from a node that has yet to be restarted after the outage, I see the following:
```
// Without flag
$ ./cargo run --release --bin solana-ledger-tool -- latest-optimistic-slots --ledger ~/ledger/ --num-slots 2
Slot                                         Hash                        Timestamp    Vote Only?
179528951 …
```
=> ledger-tool: Add flag to find non-vote optimistic slots

ledger/src/blockstore_processor.rs
To improve accuracy, prioritization_fee_cache should be updated with _executed_ transactions. 
- pass `prioritization_fee_cache` into `execute_batch()`
- call `prioritization_fee_cache.update()` with executed_transactions
Fixes #
=> only executed transactions are used to update prioritization_fee_cache

banking-bench/src/main.rs, core/benches/banking_stage.rs, core/src/banking_stage.rs, core/src/banking_stage/committer.rs, core/src/banking_stage/consumer.rs, core/src/tpu.rs, core/src/validator.rs
Originally penned by @ryoqun to construct a test, this change injects prioritization_fee_cache into banking_stage so in minimally setup local cluster, the cache will be updated too.  
- banking_stage updates prioritization_fee_cache with executed transactions
Fixes #
=> Allow banking_stage to update prioritization_fee_cache

clap-v3-utils/src/nonce.rs
In `clap-utils` and `clap-v3-utils`, the nonce argument `nonce_arg()` (i.e. `--nonce`) requires the blockhash argument `blockhash_arg` (i.e. `--blockhash`). The blockhash argument is not strictly necessary when using the `--nonce` flag for the solana cli applications since the nonce account contains the blockhash. The `requires(BLOCKHASH_ARG.name)` makes unnecessary requirement on the cli applications.
For example, currently in the token-cli, if `--nonce` flag is set on some sub-commands, the application panics since the `--blockhash` flag is not defined (and not needed).
On the other hand, in cli applications, the nonce authority argument is needed whenever the nonce argument is specified. It would make sense if the `requires(BLOCKHASH_ARG.name)` for `nonce_arg()`.
Remove the blockhash …
=> [clap-utils] Remove `--blockhash` arg as a strict requirement when passing `--nonce`

bucket_map/src/bucket.rs
https://github.com/solana-labs/solana/issues/30711
This function has been a consistent source of trouble with the borrow checker.
Refactoring to take a mut ref to the index as opposed to self. This helps.
Fixes #
=> refactor disk index bucket::find_entry_mut

Cargo.lock, Cargo.toml, programs/sbf/Cargo.lock, zk-token-sdk/Cargo.toml
`zk-token-sdk` lists `cipher` as a dependency, but nothing is being directly imported from it.
Remove unused declaration.
`cipher v0.4` is still being pulled because of spl-token-2022 v0.6 -> solana-zk-token-sdk v1.15, but will be removed from Cargo.lock entirely when we update to a version of spl-token on solana v1.16
Closes #30866
=> Remove unused dependency

Cargo.lock, programs/sbf/Cargo.lock
`cargo audit` is flagging an issue with `openssl`.
Just ran
cargo update --package openssl
=> Cargo.lock: Update `openssl`, as suggested by `cargo audit`

geyser-plugin-interface/src/geyser_plugin_interface.rs
Various users, including RPC providers, would like to be able to cryptographically verify that a block stored in long-term storage (either via Bigtable upload or streamed via Geyser) contains complete and correct transaction data. There is currently no way to do this, because the transactions get flattened and the Entry data is not included in the stored copy.
This PR is the first toward [this project](https://github.com/orgs/solana-labs/projects/29) to address the Geyser side of the issue.
Add basic Entry interface elements to solana-geyser-plugin-interface
The entry notification is not actually sent anywhere yet.
=> Add Geyser entry interfaces

poh/src/poh_recorder.rs
This error variant, `PohRecorderError::InvalidCallingObject`, is unused.
Remove `PohRecorderError::InvalidCallingObject`
Fixes #
=> Remove unused error variant

banking-bench/src/main.rs
#27194 changed the cli argument name to `tpu_disable_quic` but didn't adjust the matches use in banking-bench.
Change the usage from `tpu_use_quic` to `tpu_disable_quic`
Fixes #
=> banking bench tpu_disable_quic

runtime/src/prioritization_fee_cache.rs
In #27237 @mvines has tried to standardize solana-controlled thread names. This thread was introduced around the same time, and so it has snuck through.
Shorten thread name to 15 characters.
Fixes #
=> Standardize Thread Naming - Prioritization Fee Cache

core/src/accounts_hash_verifier.rs
The kin sim cluster was upgraded and had Incremental Accounts Hash enabled. I was eager to evaluate the performance of IAH, so I went looking at the metrics. I first pulled up the datapoint, but wasn't sure what the units were. I had to double check by looking at the code. It would be helpful to not need to check the code for the units.
Append `_us` to the datapoint's name.
=> Add units to incremental accounts hash datapoint

program-runtime/src/invoke_context.rs, programs/loader-v3/src/lib.rs
#30702 introduced `InstructionError::BuiltinProgramsMustConsumeComputeUnits` but that can not be triggered in the tests because they never pass through `InvokeContext::process_executable_chain()`.
- Uses `InvokeContext::process_instruction()` in `mock_process_instruction()`.
- Uses `InvokeContext::process_instruction()` in tests of loader-v3.
- Only throw `InstructionError::BuiltinProgramsMustConsumeComputeUnits` if `result.is_ok()`.
=> Refactor - mock_process_instruction()

ci/docker-rust-nightly/Dockerfile, ci/docker-rust/Dockerfile, ci/rust-version.sh, rust-toolchain.toml
The nightly upgrade is breaking the `geyser_plugin_manager`.  We will probably need more investigation before we can move forward with it.
Examples of failed CI runs:
https://buildkite.com/solana-labs/solana/builds/92624#0187160f-ec5e-40ae-84b8-a1859f44986a
https://buildkite.com/solana-labs/solana/builds/92627#0187161c-4431-4f62-945a-5e07869b3163
https://buildkite.com/solana-labs/solana/builds/92619#018715aa-c516-4f5f-886c-dd2f9628ec73
The CI log says
```
ci/intercept.sh: command failed; please see ./intercepted-console-2023y03m24d22h15m46s071144271ns.log in artifacts
```
In this log file I see:
```
+ exec cargo +nightly-2023-02-08 test --jobs 48 --target-dir target/cov --lib --all --exclude solana-local-cluster -- --nocapture
Finished test [unoptimized + debuginfo] target(s) in 0.62s …
```
=> Revert Rust 1.68.0 upgrade

programs/bpf_loader/src/lib.rs, programs/loader-v3/src/lib.rs, runtime/src/bank.rs
The new `LoadedPrograms` cache eviction logic is not being exercised.
- Increment usage count of a `LoadedProgram` when it is executed.
- Call cache eviction code after a batch of transaction has been executed. 
Fixes #
=> Increment usage count for loaded programs and call eviction

programs/bpf_loader/src/lib.rs
The deployment slot for the upgraded program is incorrect. It's being set to the deployment slot of the old program.
Use the `clock.slot` to set the deployment slot of the upgraded program.
Fixes #
=> Fix deployment slot for upgraded programs

bucket_map/src/bucket.rs, bucket_map/src/bucket_map.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
https://github.com/solana-labs/solana/issues/30711
Improving perf of disk index.
Several project involve removing the header from the allocated data entries and having alternate implementations/storage for the occupied/free bit (and other state).
Introduce a trait that allows each type of bucket to have a different 'occupied/free' bit location strategy.
Fixes #
=> use trait for disk bucket header

gossip/benches/crds.rs, gossip/src/cluster_info.rs, gossip/src/crds.rs, gossip/src/crds_gossip.rs, gossip/src/crds_gossip_pull.rs, gossip/tests/crds_gossip.rs
`CrdsGossipPull::make_timeouts` iterates over the stakes hashmap and creates a new hashmap which is unnecessary:
https://github.com/solana-labs/solana/blob/c032dc275/gossip/src/crds_gossip_pull.rs#L517-L539
The commit instead keeps a reference to the stakes hashmap.
=> reworks gossip crds timeouts

validator/src/cli.rs, validator/src/main.rs
Follow-up for
```
commit 809041b1519ebaa54d6ffe4ce194f04feb8eda0f
Author: Illia Bobyr <illia.bobyr@solana.com>
Date:   Wed Mar 22 11:03:30 2023 -0700
poh_verify => run_verification: Rename to be more accurate (#30811)
`poh_verify` actually disables transaction signature, tick count and
built in program argument verifications as well.  It is somewhat
confusing to call it `poh_verify`.
```
=> validator: Move `skip_poh_verify` into the deprecated list

runtime/src/snapshot_utils.rs
Observed that when account_path was missing, there was IO failures without explicit error messages pin-pointing the exact error and location.
This is part of the work in https://github.com/solana-labs/solana/pull/28745.  Specifically the code in https://github.com/solana-labs/solana/pull/30171 should be refined with more explicit error messages.
Map the dir and file operation errors to the errors with more explicit error messages for easier debugging. 
Fixes #
=> Add more explict error messages for hardlink operations

validator/src/cli.rs, validator/src/main.rs
It is better to have a single list of deprecated arguments.  It is also very common that an argument is replaced by another single argument - provide a standard way to describe that.
=> validator: Refactor deprecated arguments logic

streamer/src/nonblocking/quic.rs, streamer/src/quic.rs
We recently had a surge in possible Quic traffic associated with some nodes going down, and were unable to directly estimate the amount of actual Quic traffic incoming to the Quic server due to lack of appropriate statistics.
Add appropriate statistics
Fixes #
=> Quic server log data rate

sdk/cargo-test-sbf/src/main.rs
https://github.com/solana-labs/solana/pull/30764 renamed sbf-tools to platform-tools and made some nice clean-ups, but it seems like cargo-test-sbf is not yet updated accordingly.
In particular, you cannot currently run cargo-test-sbf due to the default `--arch` being `sbf` --> `sbfv1`. This makes the CI to fail in the spl repo.
```
Running `token/twoxtx-solana/target/debug/cargo-build-sbf --manifest-path /home/runner/work/solana-program-library/solana-program-library/token/program-2022-test/Cargo.toml --sbf-sdk ./token/twoxtx-solana/sdk/sbf --sbf-out-dir /home/runner/work/solana-program-library/solana-program-library/target/deploy --arch sbf`
error: "sbf" isn't a valid value for '--arch <arch>'
[possible values: sbfv1, sbfv2]
Did you mean "sbfv2"?
USAGE:
cargo-build-sbf --manifest-path …
```
=> [cargo-test-sbf] Rename sbf-tools to platform-tools and use sbfv1

system-test/testnet-automation.sh
need a new type for local cluster test.
make `system-test/testnet-automation.sh` support `bare`
=> chore: add bare type to testnet-automation.sh

runtime/src/in_mem_accounts_index.rs
Disk bucket writing to disk can be expensive.
flush fewer buckets, but more elements per 'slot' time, accumulating dirty results in a bucket, resulting in less page writes per unit of time. Hopefully resulting in lower overall disk write throughput. Since items tend to be held in the 'read' aspect of the in-memory buckets longer, this should help the read throughput as well.
Fixes #
=> flush individual buckets every n ages

Cargo.lock, Cargo.toml, core/Cargo.toml, perf/src/deduper.rs, programs/sbf/Cargo.lock
`AHasher::new_with_keys` removed from `ahash` public api.
* upgraded to ahash `0.8.3`.
* use `RandomState` instead of seeds in `Deduper`.
=> upgrades to ahash 0.8.3

program-runtime/src/executor_cache.rs, program-runtime/src/invoke_context.rs, program-runtime/src/loaded_programs.rs, programs/bpf_loader/src/lib.rs, programs/loader-v3/src/lib.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/bank/tests.rs
Program/ProgramData accounts get loaded even though the compiled program exists in the cache.
Check if the compiled program is already cached. If it is, do not load its program and program data accounts.
Fixes #
=> Stop loading program accounts if program exists in cache

runtime/src/accounts.rs, sdk/src/feature_set.rs
The accounts.rs code currently checks if the message includes upgradeable loader key, if an upgradeable program is being loaded for writing. The check looks necessary and harmless at quick glance. But its unnecessary, as the transaction will fail due to other checks in the execution. The check is making it harder to refactor the code for the runtime V2/Cache replacement (https://github.com/solana-labs/solana/issues/29803).
- Remove the check under a feature gate.
- Update the unit tests.
- Add feature gate.
Feature Gate Issue #30559
=> Remove redundant check during loading upgradeable program for writing

ledger/src/blockstore_processor.rs, sdk/program/src/instruction.rs
The documentation for InstructionError is incorrect. The error cause is not included in the bank hash.
Added a unit test to confirm that actual instruction error does not influence the value of the bank hash. All instruction errors result into the same bank hash.
Updated the documentation.
Fixes #
=> Update documentation of instruction error and add a unit test

Cargo.lock, bucket_map/Cargo.toml, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs, programs/sbf/Cargo.lock
Remove header from both index and data files. Store occupy bit in bitvec.
So, a u64 per allocated entry on disk (and mmapped) is replaced with a single bit in an in-mem BitVec.
See comment below for effects.
Fixes #
=> store data and index occupy in bitvec

core/src/banking_stage/forwarder.rs
Just cleaning up some of this in preparation for #30925.
Move `update_data_budget` into a separate function so our forwarding function is less cluttered.
Fixes #
=> Forwarder: separate update_data_budget

Cargo.lock, geyser-plugin-manager/Cargo.toml, geyser-plugin-manager/src/entry_notifier.rs, geyser-plugin-manager/src/geyser_plugin_manager.rs, geyser-plugin-manager/src/geyser_plugin_service.rs, geyser-plugin-manager/src/lib.rs, programs/sbf/Cargo.lock, rpc/src/entry_notifier_interface.rs, rpc/src/lib.rs
https://github.com/solana-labs/solana/pull/30872 added geyser interfaces for receiving/handling Entry notifications, but the validator plugin manager isn't yet able to actually send these notifications.
Add plumbing toward Entry notifications. This adds the geyser-plugin-manager pieces needed to construct and send the notifications, but still does not actually send them.
=> Plumb Entry notification into plugin manager

core/src/banking_stage/forwarder.rs
Saw an odd use of filter_map
Use chained methods to do equivalent operations in less code
Fixes #
=> Forwarder: clean up packet_vec filter

core/src/progress_map.rs, core/src/replay_stage.rs, ledger/src/blockstore_processor.rs
`ConfirmationTiming` has 3 fields that measure `execute_batch()` performance over time and across threads.  They are interconnected and have dedicated logic.
Extracted time metrics related to transaction execution into a separate structure.  This allows me to call `process_entries_with_callback()` without locking the whole instance of `ConfirmationTiming`, passing just the `BatchExecutionTiming` part.
I want to add a new metric that starts at the beginning of the `confirm_slot_entries()` call and ends until the very end.  In order to use a `scopeguard::defer`, I need to be able to have an excursive reference to it for the whole body of `confirm_slot_entries()`.
Plus a few minor renamings to clarify which verifications and results variables actually store.  And corrected a few messages, …
=> ledger: Extract `BatchExecutionTiming`

core/src/banking_stage/forwarder.rs
Just cleaning up some of this in preparation for #30925.
Move `get_leader_and_addr` into a separate function so our forwarding function is less cluttered.
Use ["new" let-else rust syntax](https://github.com/rust-lang/rfcs/pull/3137) to return early 
Fixes #
=> Forwarder: separate get_leader_and_addr

Cargo.lock, banks-client/src/lib.rs, program-test/Cargo.toml, program-test/tests/timeout.rs
BanksClient times out in certain situations, such as when you try to send a transaction but it doesn't get committed (https://github.com/solana-labs/solana/issues/30527). This should be fixed but in the meantime it would be better not to wait a whole minute before timing out.
Removed lines that increment the deadline by 50 seconds, with the result that the deadline is now 10 seconds instead of 60. Those lines were written by @garious in #10728. Unfortunately I can't tell why they are there, maybe @garious remembers why.
Also added a test to demonstrate a panic on timeout.
=> Make BanksClient timeout after 10 seconds instead of 60

client/Cargo.toml, connection-cache/Cargo.toml, dos/Cargo.toml, entry/Cargo.toml, perf/Cargo.toml, program-runtime/Cargo.toml, program-test/Cargo.toml, programs/address-lookup-table/Cargo.toml, programs/loader-v3/Cargo.toml, programs/sbf/rust/big_mod_exp/Cargo.toml, programs/zk-token-proof-tests/Cargo.toml, quic-client/Cargo.toml, storage-proto/Cargo.toml, thin-client/Cargo.toml, tpu-client/Cargo.toml, udp-client/Cargo.toml
Some crates don't use workspace inheritance
make them use it ⛏️
=> chore: workspace inheritance

tpu-client/src/nonblocking/tpu_client.rs
The "Blockhash expired. {expired_blockhash_retries} retries remaining" message was off by one retry.
The original counter would expire after saying "1 retry left", which was misleading. We can safely change the comparison to >= 0 as our counter is an i32.
=> tpu-client: Fix counter for expired blockhash retries

ci/test-checks.sh
#10464 https://github.com/solana-labs/solana/pull/10464/files#r1151343840 isn't needed anymore!
Remove it as this is fixed long time ago by clippy: https://github.com/rust-lang/rust-clippy/issues/4612
=> Remove workaround for already-fixed clippy bug

program-runtime/src/loaded_programs.rs, programs/bpf_loader/src/lib.rs, programs/loader-v3/src/lib.rs
The new cache sets effective slot of a program at the next slot to the deployment slot. If the program gets upgraded or deployed, it won't be active for another slot. This behavior should be covered under the existing feature gate `delay_visibility_of_program_deployment`.
If `delay_visibility_of_program_deployment` is not active, set the effective slot to the deployment slot. If the feature is active, set it to the next slot.
Fixes #
=> Use feature gate to set effective slot of loaded programs

runtime/src/snapshot_utils.rs
One test case had an out-of-date comment, another had some extra arithmetic that could use an additional comment.
=> Update comments around snapshot retention policy unit tests

program-runtime/src/loaded_programs.rs, runtime/src/bank.rs
Currently the global cache is locked for every single program that is replenished. But one write lock would suffice.
Also, `assign_program()` should only be used for program management instructions.
- Only lock the global cache once all missing programs have been loaded.
- Factors out call of `self.rc.accounts.filter_executable_program_accounts()` into caller.
- Replaces `assign_program()` by `replenish()`.
- Replaces `LoadedProgramEntry` by a boolean.
=> Cleanup - `load_and_get_programs_from_cache()`

docs/docusaurus.config.js, geyser-plugin-interface/README.md, sdk/README.md, sdk/program/README.md
See #30791 Old discords link (https://discord.com/invite/pquxPsq) being used in some places appears to be broken
We also have a few READMEs pointing to Discord that should probably point to SSE instead.
Update Discord link to https://solana.com/discord
Point README files at SSE (https://sola.na/sse) instead of Discord
=> Update discord invite links

validator/src/bootstrap.rs
`rpc_bootstrap` function is pretty unwieldy. Sub-functioning the process to get vetted RPC nodes improves readability. This also sets the stage for decoupling parts of the full/incremental snapshot download
Add function for getting vetted RPC nodes
=> Sub function getting vetted RPC nodes

Cargo.lock, core/src/progress_map.rs, ledger/Cargo.toml, ledger/src/blockstore_processor.rs, programs/sbf/Cargo.lock
We do not have a metric that covers wall clock time that would include both PoH/transaction verification, and the subsequent replay stage.
Measure total time spent inside `confirm_slot_entries()`.  Useful metric
in addition to `replay_elapsed` and
`poh_verify_elapsed`/`transaction_verify_elapsed`, as it shows how PoH
and transaction verification interact with the replay process.
=> ledger: confirm_slot_entries(): confirmation_elapsed metric

banks-client/src/lib.rs
This takes care of everything but the `VersionedMessage` part of #30434. It replaces `Transaction` with `impl Into<VersionedTransaction>` in the relevant BanksClient methods, as had been started by #28739
=> Add missing versioned tx support to BanksClient

core/src/admin_rpc_post_init.rs, core/src/lib.rs, core/src/validator.rs, local-cluster/src/local_cluster.rs, test-validator/src/lib.rs, validator/src/admin_rpc_service.rs, validator/src/bin/solana-test-validator.rs, validator/src/main.rs
Backport of https://github.com/solana-labs/solana/pull/30544 to v1.14
=> v1.14: Admin RPC Service: move post-init activation to before wait-for-supermajority (backport of #30544)

validator/src/cli.rs, validator/src/main.rs
`--skip-verification` was introduced as a replacement for `--skip-poh-verify`, but the name does not reflect the important detail, that this argument only disables verification during the validator startup.
As the argument was introduced just a few days ago, it seems fine to rename it "in-place".
=> validator: Rename arg: skip-{=>startup-ledger-}verification

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs
see https://github.com/solana-labs/solana/issues/30711
`get_mut_cell_slice()` should have taken `&mut self` but took `&self` due to borrow checker difficulties.
correctly use `&mut self`
Fixes #
=> disk bucket: get mut right on get_mut_cell_slice

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
We will need a `T` parameter on these structs soon. This change is noisy and inconsequential.
Fixes #
=> disk index: include T on a few structs

clap-utils/src/input_validators.rs, core/src/snapshot_packager_service.rs, download-utils/src/lib.rs, ledger-tool/src/main.rs, local-cluster/tests/common.rs, local-cluster/tests/local_cluster.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_config.rs, runtime/src/snapshot_utils.rs, validator/src/cli.rs, validator/src/main.rs
Retaining 0 full or incremental snapshots doesn't make a lot of sense, since that would mean immediately purging any created snapshots. Moreso, we have some code in place that already assumed that these values would be > 0.
This changes the snapshots_to_retain config parameters from usize to NonZeroUsize to enforce that values must be nonzero.
Fixes #30794
=> Enforce a minimum of 1 on full and incremental snapshot retention

bucket_map/src/bucket.rs, bucket_map/src/index_entry.rs
`IndexEntry` will soon require <T> since the index entry will contain the value type in most cases.
Add the T now to simplify the follow on pr.
Fixes #
=> disk index IndexEntry gets <T>

streamer/src/nonblocking/quic.rs, streamer/src/quic.rs
We're currently investigating potential attacks on the Quic server, including opening many slow streams that send small chunks at a time just to keep from timing out. However, we currently don't gather any data on the number of chunks handled by the Quic server.
Adds stats on the number of chunks handled by the Quic server
Fixes #
=> Add logging of the number of chunks handled by the quic server

runtime/src/accounts.rs
The program cache could contain a tombstone for a program (e.g. if it failed verification, or was closed). It's already detected early in `accounts.rs`. But it currently returns error from BPF loader. The check could be made early and error could be returned earlier in the processing pipeline.
Return early if the program cache contains a tombstone for the program.
Fixes #
=> Return error early if program is a tombstone

bucket_map/src/bucket.rs, bucket_map/src/index_entry.rs
Move the methods specific to having data with multiple slots to `impl MultipleSlots`
Fixes #
=> disk index: move fns to MultipleSlots

bucket_map/src/bucket.rs, bucket_map/src/index_entry.rs
Soon, index entries may not contain `MultipleSlots` data.
Move `data_bucket_ix()` method to `MultipleSlots`.
Fixes #
=> Move `data_bucket_ix()` method to `MultipleSlots`

bucket_map/src/bucket.rs, bucket_map/src/index_entry.rs
Soon, disk index 'index' entry will contain a single element if there is only a single element in the slot list.
To facilitate this, we need `MultipleSlots` to contain what is required to reference a data file entry.
move `fn data_loc` to `MultipleSlots`
Fixes #
=> disk index: move fn data_loc to MultipleSlots

gossip/src/crds_value.rs
Duplicate instance detection should have a comment describing why the older instance is selected for termination.
add comment explaining duplicate instance detection ordering
Fixes #
=> add clarifying comment for duplicate instance detection

ledger/src/blockstore.rs
When `create_ticks()` is called with `0` for `hashes_per_tick` it does not update the hash value at all for empty ticks.  And as we start with a `default()` hash every time, which is actually all zero, we end up with identical PoH hashes in all the generated `entries`.
This could hide bugs in tests.
Start with a unique hash every time and call the hashing function once per tick.
=> make_slot_entries(): Use unique hashes

bucket_map/src/bucket_map.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
We can use extra bits inside of `RefCount` to store bits like `Occupied` inside a disk index or data bucket. We can also use them as an enum tag for more complicated implementations such as storing a single slot list entry inside `IndexEntry` and not using the data file at all.
Fixes #
=> disk index: break ref_count u64 into reserved bits

bucket_map/src/index_entry.rs
=> disk index remove dead code

programs/sbf/tests/programs.rs
No way to test if runtime is returning consistent results for various transaction use-cases after changes to the code base.
Add a new test that runs with stable bank and genesis to produce deterministic hash.
Fixes #
=> SBF test that runs with stable bank and genesis to produce deterministic hash

bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
We'll be moving 0 or 1 slot entries into the index entry instead of the data file. This is a step in that direction.
Store the occupied/free bit in the refcount spare bits as an enum.
Fixes #
=> disk index: use bits in ref count to store occupied

streamer/src/nonblocking/quic.rs
Nested loops and branches.
Simplified the code using `Iterator::min_by_key`.
=> simplifies quic::ConnectionTable::prune_oldest

runtime/src/in_mem_accounts_index.rs
As part of #30736, we stopped writing duplicate entries to the disk index and held them for later.
The issue is the duplicate code shared a mutex with the insertion code.
This meant that insertion into the index from the 432k append vecs was blocking while a disk bucket was flushing. This slowed down overall index generation time which slows down startup time.
separate the 2 parts of startup index generation into their own mutexes. This does not affect steady state operation at all.
Fixes #
=> reduce contention on startup index generation

runtime/src/in_mem_accounts_index.rs
clean up code in assert
Fixes #
=> fix assert

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
99.9% of entries in the disk index have a slot list of length 1.
Use a union and an enum to store either the single element value OR the information required to find the entry in a data file.
The result is half the page reads and writes to use the disk index, an overall reduction in mmapped file size, and the elimination/use of fields which are now redundant in the 1 element case.
Fixes #
=> disk index: store single slot list in index entry

bucket_map/src/bucket_storage.rs
`new_map` takes bytes instead of `capacity_pow2` and `cell_size`. This separates concerns and allows us to allocate a file of full pages.
Fixes #
=> disk bucket: new_map takes bytes

cli/src/program.rs, program-runtime/src/invoke_context.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/serialization.rs, programs/bpf_loader/src/syscalls/cpi.rs, programs/bpf_loader/src/syscalls/mod.rs, programs/config/src/config_processor.rs, programs/loader-v3/src/lib.rs, programs/sbf/benches/bpf_loader.rs, programs/sbf/tests/programs.rs, programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs, programs/vote/benches/process_vote.rs, programs/vote/src/vote_processor.rs, rbpf-cli/src/main.rs, runtime/src/bank/tests.rs, runtime/src/message_processor.rs, runtime/src/nonce_keyed_account.rs, runtime/src/system_instruction_processor.rs
`InvokeContext::new_mock()` should not be used externally as it has references to some internals which tend to create messy lifetimes.
- Turns `with_mock_invoke_context()` into a macro.
- Removes `prepare_mock_invoke_context()`.
- Replaces `InvokeContext::new_mock()` with `with_mock_invoke_context()`.
- Removes override parameters from `mock_process_instruction()`.
- Removes Cow from `InvokeContext::sysvar_cache`.
=> Cleanup - mock InvokeContext

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs
Working on moving refcount to data file and assuming 1 otherwise.
Add trait fn to get notified when an index entry is copied during resizing. This lets in-memory data be copied if necessary.
Note that there are no buckets that require this fn yet, but the index buckets will soon require this.
Fixes #
=> disk bucket: add trait fn copying_entry

bucket_map/src/bucket.rs, bucket_map/src/index_entry.rs
`read_value` always returns Some(...). Simplify everyone by making it return the value directly without wrapping in an `Option`
Fixes #
=> disk index: remove Option on read_value

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
get/get_mut fns have been tricky to get safe and right. For buckets that need access to header slice, it helps to be able to specify whether a caller wants the header included or not. Note that noone uses the `Header` enum value yet. But, a caller will soon.
Fixes #
=> disk index: refactoring get/get_mut fns

Cargo.lock, bucket_map/Cargo.toml, bucket_map/src/index_entry.rs, programs/sbf/Cargo.lock
enum tag is stored separately from enum values in the disk index.
Create an enum of the values themselves for safety, clarity, and easier refactoring.
Fixes #
=> disk index: refactor OccupiedEnumTag

core/src/cache_block_meta_service.rs, core/src/cost_update_service.rs, core/src/fetch_stage.rs, core/src/replay_stage.rs, core/src/rewards_recorder_service.rs, core/src/sample_performance_service.rs, core/src/sigverify_stage.rs, core/src/tvu.rs, rpc/src/transaction_status_service.rs, zk-token-sdk/src/encryption/auth_encryption.rs, zk-token-sdk/src/encryption/elgamal.rs
While looking at some adjacent code, I thought it was weird that `TransactionStatusService::new()` is tagged with `#[allow(clippy::new_ret_no_self)]`, even though it returns Self.
Turns out, there are a bunch of unnecessary `#[allow(clippy::new_ret_no_self)]` tags. I think a lot of these are just copy-pasta from a thing that used to need it. Others return Result<Self> or a tuple including Self, which is okay since https://github.com/rust-lang/rust-clippy/pull/3338
Remove unnecessary allow tags
=> Remove unneeded `clippy::new_ret_no_self` allows

bucket_map/src/bucket.rs, bucket_map/src/bucket_api.rs, runtime/src/in_mem_accounts_index.rs
At startup, we know how many inserts are soon coming.
This appears to cut ~15s off startup time and should greatly reduce disk i/o during startup.
This is a candidate for 1.14 if we want to enable disk index.
Tell the disk index code how many inserts are coming so that the resizing algorithm doesn't go through unnecessary incremental regrows.
This becomes very important when we stop doubling the index size each time we grow the index bucket.
Fixes #
=> disk index: set_anticipated_count to optimally grow disk buckets at startup

bucket_map/src/bucket.rs, bucket_map/src/bucket_map.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
Currently index buckets are only powers of 2 large. Will soon allow index buckets to be any size.
Introduce `Capacity` to allow data buckets and index buckets to both get pow2 sizes or random sizes.
Currently, index and data are both pow2 sized.
Fixes #
=> disk index: add `Capacity`

bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
we want to move refcount to the data file. Doing so requires that we store a 2-bit enum in a bitvec per index entry.
Fixes #
=> disk index: move key enum to bitvec

bucket_map/src/bucket.rs, bucket_map/src/bucket_stats.rs, runtime/src/bucket_map_holder_stats.rs
add stat counting # of failed resizes during disk index, index file grow
Fixes #
=> disk index: add stat: disk_index_failed_resizes

programs/bpf_loader/src/syscalls/logging.rs, programs/bpf_loader/src/syscalls/mod.rs, sdk/src/feature_set.rs
All call sites of `translate_string_and_do()` supply the length, a linear search for it is simply superfluous and wastes performance.
Adds a feature gate to remove the search for the end and truncation of the tail.
Feature Gate Issue: #31029
=> Feature - Stop truncating strings in syscalls

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
Move capacity to `contents` within each disk bucket. This allows data and index buckets to have different algorithms for growth.
Fixes #
=> disk index: move capacity to contents

runtime/src/snapshot_utils.rs
bank_from_snapshot_dir returns BankFromArchiveTimings.  This is not clean, because the the from_dir route has not archive involved.  It was copied over from the from_archive route.
Generate a new structure BankFromDirTimings and use that for the return.
Fixes #
=> bank_from_snapshot_dir returns BankFromDirTimings

bucket_map/src/bucket.rs, bucket_map/src/bucket_storage.rs, bucket_map/src/index_entry.rs
Top line is master now.
On the right graph, the drop in the blue line is the index file shrinking thanks to index entry no longer containing u64 refcount.
The left graph is total data file size. The very bottom line is the change that stores slotlist=1 elements in the index file (4MB). The line just above it is THIS change, which adds a u64 per element so we can store ref_count. Not sure why we have a handful of data files. 6MB total allocated now when it used to be 4MB.
Note that both scales are log.
The very bottom line on the right graph is a test validator that increases the search length, thus, reducing the # of over-allocations we attempt.
These compound, so with that change, we’d be in the mid 20GB for the entire index …
=> disk index: store ref_count in data file

core/src/replay_stage.rs
It is currently cumbersome to identify how long partitions last in the replay stage.
1. Sub-function checking for and updating replay partition metrics
2. Track partition start time and report time elapsed when partition is resolved
3. Remove metric counters for partition detected and partition resolved
=> enhance replay partition metrics

.buildkite/hooks/post-command
- ignore cargo2junit's error. (cargo2junit will return error when test result including failed test cases)
- group messages for datadog uploading. it looks like
=> ci: improve uploading test results

bucket_map/src/bucket.rs, bucket_map/src/bucket_map.rs, bucket_map/src/index_entry.rs
Instead of index files doubling in size, grow them more incrementally.
Fixes #
=> disk index: index files grow by bytes instead of doubling

Cargo.lock, Cargo.toml, ledger/src/blockstore_processor.rs, program-runtime/src/invoke_context.rs, program-runtime/src/loaded_programs.rs, program-runtime/src/stable_log.rs, program-test/src/lib.rs, programs/address-lookup-table/src/processor.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls/cpi.rs, programs/bpf_loader/src/syscalls/logging.rs, programs/bpf_loader/src/syscalls/mem_ops.rs, programs/bpf_loader/src/syscalls/mod.rs, programs/bpf_loader/src/syscalls/sysvar.rs, programs/compute-budget/src/lib.rs, programs/config/src/config_processor.rs, programs/loader-v3/src/lib.rs, programs/sbf/Cargo.lock, programs/sbf/Cargo.toml, programs/sbf/tests/programs.rs, programs/stake/src/stake_instruction.rs, programs/vote/src/vote_processor.rs, programs/zk-token-proof/src/lib.rs, runtime/benches/bank.rs, runtime/src/bank/tests.rs, runtime/src/message_processor.rs, runtime/src/system_instruction_processor.rs
We pack error types into deeply nested structures such as `EbpfError::UserError(BpfError::SyscallError(SyscallError::InstructionError(err)))` and
unpack and repack them multiple times when switching between the control flow of the program-runtime, the RBPF-VM and (CPI) syscalls. This is not only annoying to deal with, but also hinders the unification of built-in programs and syscalls, as that would require a common return type, which requires a common result type, which in turn requires a common error type.
- Removes these wrapped error types: `BpfError::VerifierError`, `BpfError::SyscallError`, `rbpf::EbpfError::UserError`, `SyscallError::InstructionError`
and turns them into `Box<dyn std::error::Error>` instead.
- Turns result of `ProcessInstructionWithContext` from `InstructionError` …
=> Refactor - Cleanup error handling in program runtime

perf/src/packet.rs
This shouldn't be `pub` because it is marked as `cfg(test)` and is generic.
If you try to use this outside of the crate, it leads to confusing messaging about the fn not existing.
Remove pub
Fixes #
=> remove pub from to_packet_batches_for_tests

program-runtime/src/loaded_programs.rs, programs/bpf_loader/src/lib.rs, programs/loader-v3/src/lib.rs
Need a way to mark cache entry valid for only a certain number of slots. This will be useful to replenish cache with programs using old feature map, while the new programs are being compiled and pre-loaded in the cache. This will also be useful to mark tombstones valid only for certain duration (e.g. for delay visibility feature).
- Add a new optional field to cache entry.
- Set it for tombstones corresponding to delay visibility feature.
- Update `extract` to treat a program as missing if the latest matching cache entry is expired.
- Update unit test.
Fixes #
=> Add expiration slot to loaded program cache entry

clap-v3-utils/src/keypair.rs, sdk/src/signer/keypair.rs, sdk/src/signer/mod.rs
The clap utils do not yet support ElGamal keypairs and authenticated encryption key that are needed in cli tools such as the token-cli. Adding support for these types would require creating analogous functions to `keypair_from_path` and `keypair_from_seed` in the clap-v3-utils.
Instead of writing these separate functions, it would be nice to write `keypair_from_path` and `keypair_from_seed` as generic functions that can support any type of cryptographic keys/keypairs that implement a certain interface.
- Create a trait `EncodableKey` that defines the interface for cryptographic keys/keypairs are read, written, and derived from sources.
- Implement `EncodableKey` for the standard `Keypair` in the sdk.
- Write `keypair_from_path` and `keypair_from_seed` as generic functions using …
=> [clap-v3-utils] Define `EncodableKey` and make `keypair_from_path` and `keypair_from_seed` generic functions

Cargo.lock, keygen/Cargo.toml, keygen/src/keygen.rs
There are no tests for solana-keygen (https://github.com/solana-labs/solana/issues/24691). For PRs like this https://github.com/solana-labs/solana/pull/30977, it would be great to have some sanity tests that we can run to verify that it is not breaking anything.
Since the cli behavior is via stdout, it is not possible to exhaustively test all behavior of its behavior without significant refactor of the code or additional testing tools. This PR adds just the simple sanity tests to check that the cli does not panic when it is not expected to do so (e.g. https://github.com/solana-labs/solana/pull/24686).
Some notable changes to the code:
- Reorganized argument parsing into a separate `app(...)` function to be able to run clap's internal `debug_asserts`
- For a couple places in `do_main` …
=> [keygen] refactor argument parsing logic into separate `app(...)` function and add tests

core/src/consensus.rs, core/src/progress_map.rs, core/src/replay_stage.rs
No visibility of stake breakdown when failing propagated, threshold, or switch threshold checks
Add observed stake and total stake (in case of epoch boundary this is more info than %)
Fixes #
=> Add stake breakdown to metrics for HeaviestForkFailures

keygen/src/keygen.rs
`solana-keygen grind` is slightly inefficient in that it checks a few too many keys when searching for prefixes. The largest pubkey is `JEKNVnkbo3jma5nREBBJCDoXFVeKkD56V3xKrvRmWxFG` and has 44 characters. If the starting ascii character for the grind is between K and z, this means that it is impossible for the resulting pubkey to match if the sampled key has 44 characters.
The smallest key with 44 characters is `21111111111111111111111111111111111111111111`, we can short circuit the main loop if the sampled key >= `21111111111111111111111111111111111111111111` depending on the supplied prefixes.
Efficiency improvement is admittedly marginal:
Original:
```
Searched 40000000 keypairs in 93s. 0 matches found.
```
Updated:
```
Searched 40000000 keypairs in 81s. 0 matches found.
```
I guess …
=> Improve keygen grind algo by 10%

core/src/banking_stage.rs, core/src/banking_stage/thread_aware_account_locks.rs
With transaction batch scheduling, we end up with inefficieny if we wait to schedule conflicting txs until we receive a completed signal. Want a way of queueing up conflicting transactions onto the same thread - to do so we need to track the what locks are on which thread.
Account locks that track per-thread usage.
Fixes #
=> ThreadAwareAccountLocks

docs/src/getstarted/local.md
Went from a `##`(2) header to `####`(4), markdown linter was complaining at me:
```
MD001/heading-increment/header-increment: Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
```
Reduce the header level to `###`(3).
Fixes #
=> reduce header level

.github/dependabot.yml
The current limit of 3 is too low, as the updates are happening faster than they are processed via our review process.
As this limit applies to the total number of outstanding PRs, any PR that requires additional investigation is further reducing the update speed.
Bumping 2x to see if this would get us back on track to catching up with the current state of the world.
=> dependabot: Increase PR limit to 6

program-runtime/src/invoke_context.rs, programs/address-lookup-table/src/processor.rs, programs/bpf_loader/src/lib.rs, programs/compute-budget/src/lib.rs, programs/config/src/config_processor.rs, programs/loader-v3/src/lib.rs, programs/sbf/tests/programs.rs, programs/stake/src/stake_instruction.rs, programs/vote/src/vote_processor.rs, programs/zk-token-proof/src/lib.rs, runtime/src/bank/tests.rs, runtime/src/message_processor.rs, runtime/src/system_instruction_processor.rs
We need the tests to be consistent about how they use `mock_process_instruction()` if we want to unify the built-in and syscall interfaces.
- Uses `declare_process_instruction!()` in all tests.
- Adds `post_adjustments` to `mock_process_instruction()`.
=> Cleanup - mock_process_instruction()

core/src/staked_nodes_updater_service.rs, streamer/src/streamer.rs
Since https://github.com/solana-labs/solana/pull/31077 `ip_stake_map` is no longer used.
Removed it.
=> removes ip_stake_map field from streamer::StakedNodes

bucket_map/src/bucket.rs
No need to change index's `random` when growing the index.
Use the same random.
Fixes #
=> disk index: keep same random during resize

bucket_map/src/bucket.rs
Hashing the pubkey and random is useful by itself.
Remove the `% capacity` from the fn. Callers can do it themselves.
Fixes #
=> disk index: bucket_index_ix doesn't % by capacity

runtime/src/bank.rs
In central scheduler w/ multi-iterator approach for forwarding, we want to check transaction ages individually before trying to batch them.
Separate the internals of the function.
Fixes #
=> separate check_transaction_age from check_age

core/src/multi_iterator_scanner.rs, core/src/unprocessed_transaction_storage.rs
The current use-cases of the `MultiIteratorScanner` will always handle all items in the given slice.
However, this is not guaranteed to be the case (and will not for the multi-iterator scheduler).
Currently, there is no way of determining which items were handled vs not after finalizing the `MultiIteratorScanner`.
`MultiIteratorScanner::finalize` returns `(self.payload, self.already_handled)`.
Fixes #
=> MultiIteratorScanner::finalize returns (payload, already_processed)

core/benches/unprocessed_packet_batches.rs
After #31077 removed `packet.sender_stake`, some of bench tests for `unprocessed_packet_batches` became redundant. 
- remove redundant tests
Fixes #
=> update benches after removing packet.sender_stake

core/src/accounts_hash_verifier.rs, core/src/validator.rs, core/tests/epoch_accounts_hash.rs, core/tests/snapshots.rs, local-cluster/src/validator_configs.rs, local-cluster/tests/local_cluster_slow_2.rs
The current test code of fault hash injection for AccountsHashVerifier is
implemented with account package processing code, which is tightly coupled with
the normal account package processing code. And because of this,
`fault_injection_rate_slots` param has to be passed down into implementation of
account package processing code. 
This make the code less readable and more difficult to change.
- refactor out fault hash inject code into lambda fn out of AccountsHashVerifier
Fixes #
=> Refactor fault hash injection into lambda 

program-runtime/src/loaded_programs.rs
Seeing this warning while building on MacOS.
```
--> program-runtime/src/loaded_programs.rs:8:9
|
8 |         error::EbpfError,
|         ^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
Move import under the requied config flag.
Fixes #
=> Fix unused import error in LoadedPrograms

docs/src/developing/on-chain-programs/deploying.md
Typo in `on-chain-programs` documentation.
Fixed typo.
=> Documentation typo in on-chain-programs/deploying.md

bench-tps/src/main.rs, core/src/staked_nodes_updater_service.rs, core/src/tpu.rs, quic-client/src/lib.rs, streamer/src/nonblocking/quic.rs, streamer/src/streamer.rs
`{min,max}_stake` are computed but never assigned:
https://github.com/solana-labs/solana/blob/4564bcdc1/core/src/staked_nodes_updater_service.rs#L54-L57
The updater code is inefficient and verbose.
Patched bugs and removed verbose updater code.
=> reworks streamer::StakedNodes

Cargo.lock, genesis-utils/Cargo.toml, genesis-utils/src/lib.rs, programs/sbf/Cargo.lock, validator/src/bootstrap.rs
Abstraction boundary for downloading and checking genesis hash during bootstrap process is a little messy.
Push more of the genesis hash checking inside of `download_then_check_genesis_hash` function. Add another support function for download and setting expected hash.
=> Reconfigure genesis hash download and check

bucket_map/src/bucket.rs, bucket_map/src/bucket_map.rs
#31094 failed to update the count in the disk index after batch insertion.
Symptom of failure was `panic!` from `Vec::with_capacity`, trying to allocate too large of a vec based on an incorrect negative count.
Update the count correctly.
Fixes #
=> disk index: correctly keep track of count during batch add

docs/src/developing/plugins/geyser-plugins.md
Typo `ReplicaTransactionInfoVersionsoVersions`
`ReplicaTransactionInfoVersionsoVersions` - > `ReplicaTransactionInfoVersions`
=> doc: typo in geyser plugin doc

ledger/src/blockstore.rs
Slots refer to time windows where a block could be produced whereas height refers to how many blocks are actually in a fork. This function is operating on a list of slots, so the use of "height" is incorrect and misleading.
Rename variable
=> chore: Variable rename `height` ==> `slot` in blockstore function

ledger/src/blockstore.rs
Add more descriptive doc comment for the function. Additionally, change the function signature to use Slot instead of u64. Slot is defined as an alias of u64 so these are functionally equivalent, but using Slot over u64 is more expressive of the intent.
=> chore: Update Blockstore::get_slots_since() doc comments

gossip/src/cluster_info_metrics.rs
The datapoints for snapshot hashes are now named incorrectly.
Rename them to match their actual name.
=> Renames SnapshotHashes in cluster info metrics

runtime/src/accounts.rs, runtime/src/bank/tests.rs
Web3.js has a test started to fail against tip of validator master. The test sends a transaction requesting 2sol as prioritization fee, with payer account has 2sol balance. Test correctly expects the transaction to failed due to `Err(TransactionError::InsufficientFundsForFee)` therefore not landed.
- Add tests to confirm the transaction base fee calculation and payer account validation behave correctly.
Fixes #
=> Add test for transaction has too high prioritization fee

core/src/snapshot_packager_service.rs, core/src/snapshot_packager_service/snapshot_gossip_manager.rs
The `_max_incremental_snapshot_hashes` parameter to `SnapshotGossipManager::new()` is unused and can be removed.
Remove it.
=> Removes unused arg from SnapshotGossipManager::new()

validator/src/bootstrap.rs
I get a "warning" from my editor about the import line:
```rust
snapshot_utils::{self},
```
Because the `{self}` is not needed. Maybe this is a future clippy lint? Regardless, it's not the best.
Remove the `{self}` part.
=> Cleans up imports in bootstrap.rs

streamer/src/nonblocking/quic.rs
`prune_unstaked_connections_and_add_new_connection` receives both `MutexGuard<ConnectionTable>` and `Arc<Mutex<ConnectionTable>>`.
Removed redundant `MutextGuard<ConnectionTable>`.
=> removes duplicate connection-table arguments

core/src/banking_stage/forwarder.rs
Separate forwarding from metrics updates - banking stage workers will not use the same metrics structs.
This is a combination of and is blocked by #30920, #30921, #30922, #30923
Fixes #
=> Forwarder: forward_packets w/o metrics

validator/src/bootstrap.rs
In `bootstrap.rs` there are a bunch of log lines that could have their variables placed inline within the format string. In many cases this can improve readability.
I'm currently reading/editing this file, and cleaning up the logging would be nice.
Inline variables into format strings.
=> Inlines variables into logging format strings

runtime/src/snapshot_utils.rs
bank_from_snapshot_dir requires cleaning the <account_path>.  It is cleaner to put this necessary cleaning into the function to avoid duplicate the cleaning code before each call.
This addresses the review comment.  https://github.com/solana-labs/solana/pull/31115#discussion_r1161915681
Added the cleaning code in the function bank_from_snapshot_dir
Removed the cleaning code in the test.
Fixes #
=> Clear the account paths before constructing a bank from a snapshot dir

.buildkite/hooks/pre-command
We need to do `eval "$(ci/channel-info.sh)"` everywhere to get the channel info. I think we can get rid of this in Buildkite by exporting them in the pre-command
export channel info in Buildkite's pre-command
=> ci: export channel info in buildkite pre-command

core/src/banking_stage/decision_maker.rs
If we have a working bank, we don't need to find the next leader or check if we are the leader in the next 20 slots.
Without considering testability, the solution we'd have likely gone with originally is checking each condition in the if statements of `consume_or_forward_packets`, because if we have a working bank we can return immediately.
We can achieve the same using closures so that we don't need to rangle the `poh_recorder` in our tests.
Take in functions (generic) for checking bank_start, would_be_leader_shortly, etc.
This is a nice balance between leaving the function in an easily testable format, while also making it exit (drop the lock) earlier.
Blocked by #30481
Fixes #
=> decision maker perf

.github/workflows/release-artifacts.yml
our windows build got broken cuz openssl path.
conv: https://discord.com/channels/428295358100013066/560503042458517505/1093768739306094682
I found the Windows container already have it. I exported the path for openssl package.
=> ci: use preinstalled openssl

core/src/snapshot_packager_service/snapshot_gossip_manager.rs, ledger/src/bank_forks_utils.rs, runtime/src/snapshot_hash.rs
The starting snapshot hashes have a full and incremental component. The incremental component currently has a 'base' field, which is always populated by the *full* snapshot's info. Since we always have the full snapshot, the base field does not actually give us any additional information (and now I think it might be more confusing to have the 'base' field at all).
Remove the `base` field from `IncrementalSnapshotHash`.
=> Removes `base` from `IncrementalSnapshotHash`

docs/build-cli-usage.sh
CI build times for any commits within the docs directory take a long time to complete due to compiling the solana cli from source on each push.
Specifically, the `build.sh` script runs `build-cli-usage.sh`, which uses docker to compile the solana cli from source. Which is then used to output each cli command into the `cli/usage.md` doc for viewing on the actual docs site frontend (currently: Docusaurus)
Having the complete output of the solana cli is only needed for deployments of the docs, not within the rest of the CI pipeline
For non deployment-grade commits within the docs directory, tweaked the `build-cli-usage.sh` script to skip generating the entire `usage.md` by compiling the solana cli from source.
NOTE: The `build-cli-usage.sh` script will still always output contents to the …
=> [docs][ci] skip usage doc build for non-deploys

runtime/src/snapshot_utils.rs
Part of the project https://github.com/orgs/solana-labs/projects/33/ to boot from a snapshot directory.
This is to get the latest snapshot dir and boot from it.
It is split from https://github.com/solana-labs/solana/pull/30859 as suggested in its review.
Add the function bank_from_latest_snapshot_dir
Add its test function
Fixes #
=> bank_from_latest_snapshot_dir

Cargo.lock, programs/sbf/Cargo.lock
[Dependabot alert](https://github.com/solana-labs/solana/security/dependabot?q=is%3Aopen+manifest%3ACargo.lock+package%3Ah2)
Bump h2 dependency (hyper)
=> Bump h2 to v0.3.17

Cargo.lock, clap-v3-utils/Cargo.toml, clap-v3-utils/src/keypair.rs
```
$ solana-keygen pubkey usb://ledger
thread 'main' panicked at '`confirm_key` is not a name of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', /Users/tyeraeulberg/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.8/src/parse/matches/arg_matches.rs:659:14
```
In clap v3+, `ArgMatches::is_present()` panics if the arg named is not actually present in the arg definition: https://docs.rs/clap/3.1.5/clap/struct.ArgMatches.html#method.is_present
We were using `is_present` under the hood in signer resolution to check whether a remote wallet should prompt the user to confirm a used key. But not all callers of those signer-resolution methods are Args that include the `confirm_key` definition; `solana-keygen`, for …
=> Fix keygen usb panic (debug only)

ci/buildkite-pipeline.sh, ci/buildkite-solana-private.sh
- we need to wait coverage test for 30mins and no one is running with it in the same time. it wastes lots of idle agents.
- I think we should test coverage after we passed the stable test. if stable test is failed, I don't think we care about the coverage.
move coverage test to the last block
=> ci: move coverage to the last block

sdk/cargo-build-sbf/Cargo.toml
cargo-build-sbf uses reqwest crate and it depends on OpenSSL 1.1.1 which is deprecated on more recent Linux systems.
Use a feature of reqwest that enables TLS functionality provided by rustls.
Fixes #31128
=> Eliminate dependency on Open SSL in cargo-build-sbf

runtime/src/root_bank_cache.rs
If `root_bank` is not called, the `Arc<Bank>` is kept around indefinitely, which will keep the bank alive.
This struct is not used until #31148, so it shouldn't be causing the issue observed on discord (@steviez https://discord.com/channels/428295358100013066/1069667675443314849/1096122129726066839), but it should be fixed prior to being used.
Only store the `Weak` reference inside the struct, and try upgrading on call to `root_bank`.
Fixes #
=> RootBankCache: only cache weak reference to avoid keeping a bank alive

core/src/banking_stage/consumer.rs, core/src/qos_service.rs
We don't need to pass the entire bank, just the slot.
Context: Looking around for places an `Arc<Bank>` could get stuck.
`BlockBatchUpdate` wraps a `Slot` instead of `Arc<Bank>`.
Fixes #
=> store slot on BlockBatchUpdate

core/src/accounts_hash_verifier.rs, runtime/src/accounts_background_service.rs
Constructing a bank should be done from a POST snapshot (to have the calculated hash).  So the reference counts should be held for the latest POST snapshot dir, not just the latest dir.  AHV is the right place, because it converts PRE to POST.
Move last_snapshot_storage from ABS to AHV
Remove storages cloning inside ABS, because there is no need to return a copy from handle_snapshot_request
There is a new cloning in AHV at the start of AHV handling a new accounts_package.  The total number of cloning is not changed.
Fixes #
=> Move reference-holding last_snapshot_storages from ABS to AHV

programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs, sdk/src/feature_set.rs
when `split` violates the minimum delegation, sometimes it returns `InstructionError::InsufficientFunds`, and other times it returns `StakeError::InsufficientStake`. the description for the second error is "split amount is more than is staked," which isnt really whats happening
this changes it to use `StakeError::InsufficientDelegation` in all cases, the correct error for this condition
Feature Gate Issue: #31206
=> clean up delegation errors

ledger-tool/src/main.rs
There was an oversight in https://github.com/solana-labs/solana/pull/30891 to provide a warning about the arg now being deprecated.
Warn about deprecated argument
Fixes #
=> ledger-tool: Add deprecation warning for --no-compaction

Cargo.lock, Cargo.toml, frozen-abi/Cargo.toml, programs/sbf/Cargo.lock
We never use this dependency in our code (directly), so we should remove it.
Noticed there was an upgrade PR (#31123), and was curious where we used it since from the repo's [readme](https://github.com/rust-lang/hashbrown):
> Since Rust 1.36, this is now the HashMap implementation for the Rust standard library.
Remove it.
Closes #31123
=> remove unused hashbrown dependency

multinode-demo/bench-tps.sh
Using additional arguments to bench-tps.sh is annoying - it requires specifying all the default arguments.
I run it locally, with additional arguments quite often; my approach so far has always been to just modify the bench-tps.sh to include my args so I don't have to specify all the defaults via cli.
Use `default_arg` from common to add defaults if they are not specified via args
Fixes #
=> Simplify using additional arguments in bench-tps.sh

Cargo.lock, clap-utils/src/input_validators.rs, clap-v3-utils/src/input_validators.rs, cli-output/src/cli_output.rs, cli/Cargo.toml, cli/src/cli.rs, cli/src/wallet.rs
There is no tool to calculate program derived address.
Each time you need to make this for each program.
Add `find-program-address` command.
**Usage**
```
solana find-program-address [FLAGS] [OPTIONS] <PROGRAM_ID> [SEED]...
...
ARGS:
<PROGRAM_ID>    The program_id that the address will ultimately be used for, 
or one of NONCE, STAKE, and VOTE keywords
<SEED>...       The seeds. 
Each one must match the pattern PREFIX:VALUE. 
PREFIX - the one of [string, pubkey, hex, u8] 
or matches the pattern [u,i][16,32,64,128][le,be] (for example u64le) 
where first two parts represent a number type and last one (le/be) - byte order
```
**Samples**
To find metaplex metadata address for `9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E ` Wrapped Bitcoin:
```
solana find-program-address …
```
=> Cli: add `find-program-derived-address` command

runtime/src/accounts_db.rs
Packed ancient append vecs are applying the offset twice.
Only apply the offset on use.
Fixes #
=> ancient append vecs: better application of offset

runtime/src/snapshot_utils.rs
As pointed in https://github.com/solana-labs/solana/pull/31191#discussion_r1167642764, the bank_snapshots_dir can be a TempDir directly.   So some old code doing that wrong need to be cleaned up.
Let bank_snapshots_dir be defined as TempDir.
Fixes #
=> Define bank_snapshots_dir as tmpdir

scripts/cargo-install-all.sh
https://buildkite.com/solana-labs/solana-secondary/builds/10071#01878ec1-ce85-4760-9cc3-bbaa02d2bddc
maybe we should make v1.14 branch always use spl-token-cli v2.3.0 which is its pervious version.
install spl-token-cli 2.3.0 in `scripts/cargo-install-all.sh`
=> fix: lock spl-token-cli version in v2.3.0

bench-tps/src/cli.rs, multinode-demo/bench-tps.sh
tx_count is snake_case while the rest of the args are kebab-case
* Change long argument name from "tx_count" to "tx-count"
* Add alias "tx_count" to avoid breaking scripts
Blocked by #31210 
Fixes #
=> bench-tps: rename tx_count arg to tx-count for consistency

docs/src/api/websocket/_logsSubscribe.mdx
The `logsSubscribe` websocket method's `mentions` parameter has confusing language about how many addresses should be supplied.
added clarifying text and `caution` box about the logsSubscribe's `mentions` parameter
Fixes #31217
=> [docs] clarify logsSubscribe `mentions` param

ci/publish-crate.sh
Our CI job for publishing crates is broken because v1.14 is on rust v1.60, newer `time` releases have an msrv to v1.63, and cargo package/publish doesn't respect Cargo.lock (which specify an older version of `time`).
Set the `RUST_STABLE_VERSION` envar to v1.63.0 in publish-crate.sh in v1.14
Should we do this in v1.13 as well, in case of additional patches?
=> v1.14: Hardcode newer rust version for crate publishing

runtime/src/snapshot_utils.rs
Multiple test cases have duplicated common code for creating test snapshot dirs in PRE or POST states.
Created a function create_snapshot_dirs_for_tests to refactor the common code for creating test snapshot dirs in any numbers of PRE or POST states.
Fixes #
=> Refactor the common test snapshot dirs creation code

core/tests/snapshots.rs, local-cluster/tests/local_cluster.rs, runtime/src/accounts_background_service.rs, runtime/src/snapshot_utils.rs
In https://github.com/solana-labs/solana/pull/30978, we need more refined control of the snapshot dir purging behavior.
Before booting, we want to purge all PRE snapshot dirs.
During run time, we should purge only the POST snapshot dirs, letting AHV to process PRE snapshot dirs into POST.
Add the filter_by_type param.  Call purging by type.
Fixes #
=> Add a filter_by_type param for purge_old_bank_snapshots

.github/workflows/release-artifacts.yml
fix Windows building
(backport of #31107)
=> v1.13: ci: use preinstalled openssl (backport of #31107)

ledger/src/blockstore_processor.rs, runtime/src/bank.rs
Bank has super wide public interface. Limiting this is helpful for looser coupling and future sub-moduling of `bank.rs`
- Make `VerifyAccountsHashConfig` and `verify_accounts_hash` private to bank
- Move `fn run_final_hash_calc` into bank
=> Make VerifyAccountsHashConfig private

core/src/accounts_hash_verifier.rs, runtime/src/bank.rs, runtime/src/serde_snapshot.rs, runtime/src/serde_snapshot/tests.rs, runtime/src/snapshot_utils.rs
`bank.rs` is overloaded and `BankIncrementalSnapshotPersistence` is more closely aligned with snapshot handling
Move `BankIncrementalSnapshotPersistence` from `bank` to `serde_snapshot`
=> Move BankIncrementalSnapshotPersistence

runtime/src/accounts_db.rs, runtime/src/ancient_append_vecs.rs
packed ancient append vecs is disabled by default.
When enabled, more stats and connected ancient stats would be helpful.
Add and update stats.
Fixes #
=> update stats for packed ancient

core/src/consensus.rs, core/src/replay_stage.rs, ledger-tool/src/main.rs, rpc/src/rpc.rs, runtime/src/bank.rs, runtime/src/vote_account.rs
`VoteAccount::vote_state()` returns an `&Result<...`, forcing every call site to `.as_ref()` et. all on use.
internally transpose the referencing. clean up call sites
this was very satisfying. i wish i'd caught it on review :sweat_smile:
=> runtime: transpose `VoteAccount::vote_state()` return to improve ergonomics

core/src/banking_stage/forwarder.rs
Want to add some additional `Forwarder` tests, but set up is repetitive.
* Refactor some common test setup into a function so we can call it for all tests
* Add a `TestSetup` struct to hold onto references we need to keep around
Fixes #
=> Forwarder: Add common setup for tests

core/src/replay_stage.rs
When ReplayStage::new() kicks off, it needs to do some setup with the working bank prior to entering the main processing loop. This setup is done before entering the main processing loop; however, a bug made it such that an Arc<Bank> remained in scope after the processing loop had been entered. The processing loop is only exited when the process exits, so this means that Bank was being held for the lifetime of the process. This is a waste of resources and prevents background cleanup.
Rework the `ReplayStage:: reset_poh_recorder()` to more properly take an `Arc<Bank>` over `&Arc<Bank>`; this makes is such that the `Arc<Bank>` is moved out of scope from `ReplayStage::new()`
This is a very simple change for something that took quite a bit of work to track down. ~~I believe this bug is the …
=> Fix bug where ReplayStage holds an Arc<Bank> for process lifetime

runtime/src/account_storage.rs, runtime/src/accounts_db.rs
assert doesn't include line # of failure and inlining can eliminate stack.
move assert into individual functions to easily identify which fn hits the assert.
@yhchiang-sol ran into this while working on cold storage format. Pulling it out separately for clarity.
Fixes #
=> rework assert_no_shrink_in_progress to get assert stack easily

runtime/src/accounts_db.rs, runtime/src/accounts_file.rs
Working on tiered storage.
Not every type of storage is recyclable.
add `is_recyclable` to `AccountsFile`
@yhchiang-sol found and will need this.
Fixes #
=> add `is_recyclable` to `AccountsFile`

core/src/banking_stage.rs, core/src/banking_stage/scheduler_messages.rs
Banking Scheduler and Worker threads need to communicate via message passing.
Scheduler PR and Worker PR will both use these messages, so it makes sense to separate them into a separate PR to be merged before either scheduler/worker.
Messages that are passed from [scheduler to worker] and [worker to scheduler].
The message flow between Scheduler and Worker(s) is as follows:
```mermaid
flowchart LR
subgraph Forwarding
direction LR
C[Scheduler];
D[Worker];
C -->|ForwardWork|D -->|FinishedForwardWork|C;
end
subgraph Consuming
direction LR
A[Scheduler];
B[Worker];
A -->|ConsumeWork|B -->|FinishedConsumeWork|A;
end
```
Fixes #
=> Scheduler Messages

rbpf-cli/src/main.rs
Seeing this warning when building on MacOS
```
warning: variable does not need to be mutable
--> rbpf-cli/src/main.rs:248:9
|
248 |     let mut verified_executable = if magic == [0x7f, 0x45, 0x4c, 0x46] {
|         ----^^^^^^^^^^^^^^^^^^^
|         |
|         help: remove this `mut`
```
`verified_executable` is JIT compiled under a config flag, for which a `mut` reference is needed.  Updated code to suppress the warning.
Fixes #
=> Suppress warning for unused_mut in rbpf-cli

ci/docker-rust-nightly/Dockerfile, ci/docker-rust/Dockerfile, rust-toolchain.toml
Dependabot now needs 1.68: https://github.com/dependabot/dependabot-core/pull/7066
=> Upgrade Rust to 1.68.2
