- cli-output/src/cli_output.rs
- cli/src/stake.rs
`solana vote-account` can print rewards, but it's nice to have the date column for determining price of sol on said date
* Added time as a column
tldr; this was helpful for collecting reward history for tax purposes
Fixes #
> Add time field to solana vote-account rewards output

- banks-server/src/banks_server.rs
- banks-server/src/rpc_banks_service.rs
- rpc/src/rpc.rs
- rpc/src/rpc_service.rs
- send-transaction-service/src/send_transaction_service.rs
The SendTransactionService doesn't receive exit signals from the validator, allowing the threads to continue in zombie mode when the validator has otherwise halted.
Extend the JsonRpcService exit block to signal SendTransactionService when the validator exits, by passing in an AtomicBool instead of creating on inside SendTransactionService
Fixes #31079
> Register SendTransactionService exit

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
Windows build is broken after https://github.com/solana-labs/solana/pull/31289
Error:
Compiling solana-genesis-utils v1.16.0 (D:\a\solana\solana\genesis-utils)
error[E0432]: unresolved import `winapi::um::winuser`
--> install\src\command.rs:385:17
|
385 |             um::winuser::{
|                 ^^^^^^^ could not find `winuser` in `um`
For more information about this error, try `rustc --explain E0432`.
https://github.com/solana-labs/solana/actions/runs/4759519915/jobs/8458877323
Revert https://github.com/solana-labs/solana/pull/31289
> Revert: Bump console from 0.15.0 to 0.15.5 (#31289)

- runtime/src/accounts.rs
- sdk/src/feature_set.rs
Should use checked arithmetic in most cases.
- Add tests
- Use checked arithmetic
- Add feature gate
Feature Gate Issue: #31273
> use checked arithmetic

- ledger/src/bank_forks_utils.rs
https://github.com/solana-labs/solana/issues/31241
When boot from an archive, out-of-memory(OOM) happens when --account is using a memory mapped path
Purge the snapshot dirs to release the memory before loading from an archive.
Fixes #31241
> Purge snapshot dirs before loading from an archive

- ledger/src/blockstore_processor.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/lib.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v3/src/lib.rs
- programs/vote/benches/process_vote.rs
- runtime/benches/bank.rs
- runtime/src/builtins.rs
Built-ins (`ProcessInstructionWithContext`) and syscalls (`BuiltInFunction`) use two different function interfaces.
In order to unify them this PR replaces the interface of built-in by the one used for RBPF syscalls.
This does not allow access of built-ins as syscalls yet, it is merely a preparation step.
> Refactor - Use builtin function interface from rbpf

- core/src/shred_fetch_stage.rs
In `ShredFetchStage::modify_packets` ping response packets will be marked `set_discard(true)` after processing. The subsequent call to `should_discard_packet()` will call `packet.data()` which will fail because the packet is set for `discard`. This will cause an `index_overrun` error to erroneously be recorded.
Check for `packet.meta().discard()` prior to calling `should_discard_packet()`.
Fixes #
> check for prior discard in shred_fetch_stage

- program-runtime/src/loaded_programs.rs
Evicting tombstones can cause incorrect view of the cache. If the tombstone and updated program entry both get evicted, the cache can potentially return old program to the caller.
Do not evict tombstones. Also updated the tests.
Fixes #
> Do not evict tombstones

- core/src/cluster_nodes.rs
- core/src/validator.rs
- gossip/src/cluster_info.rs
- gossip/src/crds.rs
- gossip/src/crds_gossip_push.rs
- gossip/src/crds_value.rs
- gossip/src/legacy_contact_info.rs
- gossip/tests/crds_gossip.rs
- gossip/tests/gossip.rs
Working towards `LegacyContactInfo` => `ContactInfo` migration. 
* removed `wallclock` from `LegacyContactInfo` public interface.
* expand api parity between `LegacyContactInfo` and `ContactInfo`.
> removes wallclock from LegacyContactInfo public interface

- gossip/src/contact_info.rs
- gossip/src/legacy_contact_info.rs
- rpc-client-api/src/response.rs
- rpc-client/src/mock_sender.rs
- rpc/src/rpc.rs
New `ContactInfo` implemented in https://github.com/solana-labs/solana/pull/29596
specifies sockets for QUIC protocols explicitly.
The commit adds `tpu_quic` field to `RpcContactInfo` in preparation of `LegacyContactInfo` => `ContactInfo` migration.
added `tpu_quic` field to `RpcContactInfo`.
> adds tpu_quic field to RpcContactInfo

- ci/buildkite-pipeline.sh
the step which we trigger secondary pipeline usually makes our whole pipeline red. however most of time it just cannot trigger due to it is a private pipeline.
I have two idea for this situation.
the pipeline will be green but the step is still red. it looks like
instead of
we're in business plan on buildkite so we can use the team feature. there is a env, `BUILDKITE_BUILD_CREATOR_TEAMS`, which we can decide whether we append the trigger step in the end of the pipeline.
I would like to ship 1) atm.
> ci: soft fail trigger_secondary_step

- ci/nits.sh
- ci/test-checks.sh
(Properly) Fixes #2630 with https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#default_trait_access
> ci: prefer clippy::default_trait_access over shell

- ledger/src/builtins.rs
- program-runtime/src/builtin_program.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/lib.rs
- program-test/src/lib.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/message_processor.rs
There are currently three structs for built-in programs:
- `solana_rbpf::vm::BuiltInProgram`
- `solana_program_runtime::invoke_context::BuiltinProgram`
- `solana_runtime::builtins::Builtin`
This PR aims to unify the second and the third.
- Moves BuiltinProgram of the program runtime into its own file.
- Unifies the runtimes Builtin and program runtimes BuiltinProgram definitions.
- Moves BuiltinPrograms from bank.rs into the program runtime.
> Refactor - `BuiltinPrograms`

- gossip/src/cluster_info.rs
- validator/src/admin_rpc_service.rs
- validator/src/cli.rs
- validator/src/main.rs
This PR is a continuation of the work on issue #30451
A node operator can manage a public `TPU` address (at node startup and while it's running), but doesn't have the ability to manage the `TPU Forwards` address as well.
This PR adds that functionality.
1) Added the start argument `--public-tpu-forwards-address`
2) Reworked the `set-public-tpu-address` subcommand into the `set-public-address` subcommand
> Add ability to manage public TPU Forwards address

- core/src/snapshot_packager_service.rs
- core/tests/snapshots.rs
- runtime/src/accounts_db.rs
- runtime/src/snapshot_utils.rs
Per suggestion in https://github.com/solana-labs/solana/pull/30978#discussion_r1160744478, split the changes in the test function create_and_verify_snapshot into a new PR.
See https://github.com/solana-labs/solana/pull/31245#issuecomment-1513786773.  The files for testing is not in sync in the current real snapshot dirs.
Update the implementation of fn create_and_verify_snapshot:
Replace the test snapshot creation code with the new create_snapshot_dirs_for_tests function from https://github.com/solana-labs/solana/pull/31223
Replace the archiving code with package_and_archive_full_snapshot.
Move create_snapshot_dirs_for_tests out of mod tests for sharing across the files
Update verify_snapshot_archive to add the slot parameter 
It is needed in both the Deterministic and NonDeterministic …
> Update fn create_and_verify_snapshot

- ci/docker-run.sh
- ci/docker-rust/Dockerfile
> ci: use the sccache which installed in the docker image

- ci/docker-rust/Dockerfile
- ci/test-checks.sh
the latest wasm-pack (v0.11.0) has already included workspace inheritance support. we don't need to specific the commit anymore!
> ci: use stable wasm-pack version in docker

- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- ledger/src/builtins.rs
- ledger/src/lib.rs
- program-runtime/src/loaded_programs.rs
- program-test/src/lib.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/upgradeable_with_jit.rs
- programs/bpf_loader/src/with_jit.rs
- programs/loader-v3/src/lib.rs
- rbpf-cli/src/main.rs
- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/runtime_config.rs
- test-validator/src/lib.rs
- validator/src/bin/solana-test-validator.rs
- validator/src/cli.rs
- validator/src/main.rs
This option is useless in production and for debugging the validator is mostly build from sources. It is routed through the validator code via multiple obscure techniques such as registering multiple versions of the same built-in program. It should be removed because it stands in the way of unifying all built-in programs in one place.
- Removes the CLI argument "no-bpf-jit".
- Removes its plumbering through out the validator code base.
- Removes the with_jit variants of the bpf_loader programs.
- Removes the `to_builtin!()` macro.
> Cleanup - Removes the CLI option "no-bpf-jit"

- ci/check-crates.sh
seems that we can't get CRATE_TOKEN correctly in a PR.
just use curl to get crates owner list
> ci: use crates api to get owner list

- .github/workflows/release-artifacts-auto.yml
https://discord.com/channels/428295358100013066/560503042458517505/1100438277711986730
we need to upgrade our tokio crates to make it green
stop windows building on master temporarily
> ci: stop windows building on master temporarily

- core/src/multi_iterator_scanner.rs
Doing a traced debug of an issue in scheduler - couldn't print out decisions for each packet.
Derive Debug for the ProcessingDecision so it can be printed out when debugging
Fixes #
> derive Debug for multi_iterator_scanner::ProcessingDecision

- core/src/accounts_hash_verifier.rs
- core/src/snapshot_packager_service.rs
- core/tests/snapshots.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_package/compare.rs
- runtime/src/snapshot_utils.rs
For booting a bank from a snapshot dir, we need a post snapshot with hash calculated.  Previously, the account package is generated with a tmp dir, and the hash was calculated for the tmp dir and packaged into the archive.  The snapshot dir under snapshot/ stays at the PRE stage without the account hash.
Let account package use the snapshot dir in-place, so AHV computes the accounts hash and turns the pre snapshot dir into a post snapshot dir.
Change SnapshotPackage::snapshot_links from TempDir to PathBuf, let it point to the snapshot dir.  Remove the tempdir setup.
Build archive staging directory using the snashot dir info from the updated SnapshotPackage.
Fixes #
> AHV processes the snapshot dirs in place

- runtime/src/accounts_partition.rs
- runtime/src/bank.rs
Abstraction between `accounts_partition` and `bank` could be improved by reducing visibility of internal types.
- Add `fn rent_multi_epoch_collection_cycle_params` to pair with existing `rent_single_epoch_collection_cycle_params`
- Rework `bank` so that knowledge of `RentCollectionCycleParams` is not needed
- Make `RentCollectionCycleParams` private to `accounts_partition`
> Rework bank to allow RentCollectionCycleParams private

- ci/test-checks.sh
- core/src/ancestor_hashes_service.rs
- core/src/tvu.rs
- core/src/window_service.rs
- core/tests/snapshots.rs
- faucet/src/faucet.rs
- ledger/src/blockstore_processor.rs
- perf/src/cuda_runtime.rs
- rpc-test/tests/rpc.rs
- runtime/src/accounts_index.rs
- sdk/program/src/pubkey.rs
- sdk/program/src/vote/state/mod.rs
- tokens/src/main.rs
Using `_`-prefixed variables are odd: https://github.com/solana-labs/solana/pull/31239#discussion_r1169860871
Remove and deny them in the future.
Fixes #
> ci: treewide: deny used_underscore_binding

- bench-tps/src/bench.rs
Builtins consume CUs - we need to account for it otherwise the transactions fail in bench-tps if using the `--use-randomized-compute-unit-price` option
Set the CUs to 450:
1 System program call (150) + 2 ComputeBudget calls (150) = 450.
Fixes #
> Set compute unit limit correctly

- Cargo.lock
- client/Cargo.toml
- programs/sbf/Cargo.lock
solana-net-utils isn't used anywhere in solana-client despite being a dependency.
remove it
> remove unused solana-net-utils dep from solana-client

- cli/src/vote.rs
- ledger/src/staking_utils.rs
- local-cluster/src/local_cluster.rs
- program-test/tests/warp.rs
- programs/vote/src/vote_processor.rs
- runtime/src/bank/tests.rs
- runtime/tests/stake.rs
- sdk/program/src/vote/instruction.rs
- transaction-status/src/parse_vote.rs
https://github.com/solana-labs/solana/pull/30831 added a new VoteState version that requires a different amount of account space. This version will be enabled on activation of feature `vote_state_add_vote_latency`.
The instruction builders in solana_program::vote::instruction use `VoteState::size_of()` to determine the amount of space to request the system program allocate for a new vote account; ie. always the new size. This means `solana create-vote-account` on an edge `solana-cli` fails against all current clusters, where the `vote_state_add_vote_latency` feature gate isn't active.
Add new instruction-set builders that take as input a config struct with a `space` field. Opted for a config struct so that additional parameters can be added in the future without breaking the builder …
> Add new CreateVoteAccount instruction-set builders

- bench-tps/src/cli.rs
`keypair_multiplier` is required to be >= 2, and the check here is doing the opposite.
Bug was introduced [here](https://github.com/solana-labs/solana/pull/30307/files#diff-d14e602d4b2d368407717910683a50eaaee95be475fdd8a1e895297655201430L465) in #30307
The default value of this arg is 8 by the way 😄 
Reverse the check.
Fixes #
> Fix keypair multiplier check

- runtime/src/snapshot_utils.rs
When removing a snapshot, if the corresponding account/snapshot/\<slot\> directory is missing, the remove_dir_all can fail with IO error, leading to the unwrap panic when returning from add_bank_snapshot().
Replace it with async move_and_async_delete_path, which handles the dir missing gracefully, and also save time.
Fixes #
> Use async delete to save time and gracefully handle missing dir

- bench-tps/src/main.rs
- core/benches/cluster_nodes.rs
- core/src/broadcast_stage/broadcast_duplicates_run.rs
- core/src/cluster_nodes.rs
- core/src/cluster_slots.rs
- core/src/serve_repair.rs
- core/src/validator.rs
- dos/src/main.rs
- gossip/src/cluster_info.rs
- gossip/src/crds_gossip.rs
- gossip/src/crds_gossip_pull.rs
- gossip/src/crds_gossip_push.rs
- gossip/src/crds_value.rs
- gossip/src/gossip_service.rs
- gossip/src/legacy_contact_info.rs
- gossip/src/main.rs
- gossip/tests/crds_gossip.rs
- gossip/tests/gossip.rs
- local-cluster/src/cluster_tests.rs
- local-cluster/tests/local_cluster.rs
- local-cluster/tests/local_cluster_slow_2.rs
- rpc/src/cluster_tpu_info.rs
- rpc/src/rpc.rs
- validator/src/bootstrap.rs
Working towards `LegacyContactInfo` => `ContactInfo` migration. 
* removed `pubkey` from `LegacyContactInfo` public interface.
* expand api parity between `LegacyContactInfo` and `ContactInfo`.
> removes pubkey from LegacyContactInfo public interface

- Cargo.lock
- Cargo.toml
- ledger/src/blockstore_processor.rs
- program-runtime/src/loaded_programs.rs
- programs/loader-v3/src/lib.rs
- programs/sbf/Cargo.lock
- runtime/Cargo.toml
- runtime/src/bank.rs
- runtime/src/bank_forks.rs
During cold start, the program cache could have an incomplete view of the deployed/modified programs. The cache relies on program management instructions to update and manage program cache entries during regular run time. But, at the startup ledger may have modifications to the program that are not yet rooted (i.e. only valid on certain forks). This can lead to execution of an outdated program.
- Compute the highest slot in the startup/snapshot ledger
- Until the root slot moves past the highest slot, do the following
- Read the program state to find the deployment slot. 
- If the deployment slot is in future compared to the program entry in the cache, treat the program as missing in the cache.
- This will trigger the reloading of the program by reading the program account visible on the …
> Check program modification slots during cold start

- runtime/src/snapshot_utils.rs
The way that a parameter can be of type `AsRef<Path>` can be spelled a few different ways. Let's standardize on one, `impl AsRef<Path>`, since then we do not need any generic parameters nor `where` clauses.
Replace generic parameters and `where` clauses with `impl AsRef<Path>`.
> Cleanup usage of AsRef<Path> in snapshot_utils

- docs/src/staking/stake-accounts.md
Since `require_custodian_for_locked_stake_authorize` was activates (https://github.com/solana-labs/solana/pull/14861), a stake account's lockup custodian must sign any change to the account's withdraw authority. The docs weren't updated to reflect that change.
Fix docs. Change looks bigger than it is because I also reflowed the hard wrap. Sorry.
Proposing backport to get out into published docs.
> Fix lockup docs

- program-test/src/lib.rs
- programs/bpf_loader/benches/serialization.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v3/src/lib.rs
- programs/sbf/benches/bpf_loader.rs
- programs/sbf/rust/realloc/src/instructions.rs
- programs/sbf/rust/realloc/src/processor.rs
- programs/sbf/tests/programs.rs
- rbpf-cli/src/main.rs
- runtime/src/bank/tests.rs
- sdk/src/account.rs
- sdk/src/feature_set.rs
- sdk/src/transaction_context.rs
This PR introduces the `bpf_account_data_direct_mapping` feature. When enabled, account data is directly mapped into vm memory at vm setup time. This removes the need to have large copies during transaction execution, going in and out of the vm at each instruction/CPI boundary.
The only data copy left now is when an account is first mapped as writable during a transaction. That copy is unavoidable at the moment since accounts are cached in memory and written back only every N slots. I'm planning to try and remove that copy in a separate PR.
Feature gate issue: #29708
> Account data direct mapping

- runtime/src/snapshot_utils.rs
Seeing the errors in the log before loading a bank
Unable to read bank snapshot for slot 191023016: I/O error: No such file or directory (os error 2)
It is due to the incomplete snapshot dir left by the previous process.  There is completion file flag check, but not done ahead of other file checks, which causes the IO errors.  The code handles them without crashing.  But such error messages are misleading.
Move the incompletion file flag check ahead of other checks to avoid the IO errors.
Add a line to log the detection and removing of the incomplete snapshot dir.
Fixes #
> Check incomplete file flag first

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
To use Bank in ledger-tool for off-chain program execution requires minor modifications to Bank API
- Make load_program method of Bank public for use in ledger-tool
- Add an accessor method to get a reference to builtin_programs of Bank
- Add a parameter to Bank::load_program to control debugging_features
> Add minor extensions to Bank API

- install/Cargo.toml
`winapi` hides every module behind a feature flag, see here:
https://github.com/retep998/winapi-rs#why-am-i-getting-errors-about-unresolved-imports
`install` was working by accident as for each package, requested feature set is a superset of all features requested by all packages in the workspace, and `console` used to list features that `install` needs. But after a change in `console` we had build breakages.
List the necessary features explicitly.
> Cargo.toml: winapi: List used features

- core/src/accounts_hash_verifier.rs
It is more efficient to submit the metrics together, and there is no reason for them to be separate.
Combine the fields into one datapoint which also removes a `inc_new_counter_info` instance
Fixes #
> Combine AccountsHashVerifier metrics

- program-runtime/src/loaded_programs.rs
- runtime/src/bank.rs
Program management instructions could potentially modify loaded programs by redeployment or closing. Having a separate data structure to contain transaction batch specific loaded program will simplify the code.
Add a second level cache to store transaction batch specific program entries. This cache can contain only one program for a given key, that's visible at a given slot. The program management instruction will replace the program entry if the program gets modified.
Fixes #
> Add a second level cache to contain tx batch specific programs

- core/src/accounts_hash_verifier.rs
- core/src/snapshot_packager_service.rs
- core/tests/snapshots.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_package/compare.rs
- runtime/src/snapshot_utils.rs
Per https://github.com/solana-labs/solana/pull/30978#discussion_r1177886353, replaced the outdated SnapshotPackage snapshot_links field with bank_snapshot_dir 
Now all the snapshot file paths info per slot is under the snapshot dir, there is no need to use "snapshot_links" which has the layout like the top snapshots dir, which contains extra info outside of the slot, and requires conversion back-and-forth.
Change to use the per-slot bank_snapshot_dir in SnapshotPackage.
When creating AccountsPackage, use bank_snapshot_dir, skip the parent() call.
in archive_snapshot_package, remove the "join(&slot_str)"
In reserialize_bank_with_new_accounts_hash, join the slot string for once, instead of twice.
Fixes #
> Clean up the outdated SnapshotPackage snapshot_links field

- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
The function `snapshot_utils::get_bank_snapshots_dir()` (note the plural) actually gets the path to the bank snapshot (non-plural) dir. I've always found this confusing, and should be updated.
* Rename fn to `get_bank_snapshot_dir`
* Add doc comments to it
* Fix the impl to reuse `get_snapshot_file_name`
* Add doc comments to `get_snapshot_file_name`
* Make these two functions `pub` so they can be called from non-runtime code
Note: This PR purposely does not update existing code that *could* use the now-public functions. That will happen in a subsequent PR.
> Fixes name of snapshot_utils::get_bank_snapshot_dir()

- core/tests/snapshots.rs
A test in `core/tests/snapshot.rs` duplicates the logic in `snapshot_utils::get_bank_snapshot_dir()`. We can use `snapshot_utils::get_bank_snapshot_dir()` directly instead.
Replace duplicate code with `snapshot_utils::get_bank_snapshot_dir()`
> Uses get_bank_snapshot_dir() in `core/tests/snapshot.rs`

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
Changes:
https://github.com/console-rs/console/compare/0.15.0...0.15.5
This is a re-application of this change:
commit 4e3300e7d66a12d4fd377704d1b5c202897d08eb
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Thu Apr 20 15:40:14 2023 -0700
Bump console from 0.15.0 to 0.15.5 (#31289)
Bumps [console](https://github.com/console-rs/console) from 0.15.0 to 0.15.5.
- [Release notes](https://github.com/console-rs/console/releases)
- [Changelog](https://github.com/console-rs/console/blob/master/CHANGELOG.md)
- [Commits](console-rs/console@0.15.0...0.15.5)
---
updated-dependencies:
- dependency-name: console
dependency-type: direct:production
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>
It is now safe to upgrade …
> Bump console from 0.15.0 to 0.15.5

- bucket_map/src/bucket_storage.rs
- bucket_map/src/index_entry.rs
* The fns `BucketStorage::get_from_parts()` aren't used within BucketStorage, only in `index_entry.rs`
* The fns take a slice of bytes, not a pointer and length, so the "from parts" name feels slightly off to me
* Move the fns to `index_entry.rs`
* Rename the fns to `get_from_bytes()`
Note: No functional changes to the code.
> bucket_map: Moves get_from_bytes() to index_entry.rs

- programs/bpf_loader/src/lib.rs
- programs/sbf/tests/programs.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
`bpf_loader` still has code to lazily load programs, but its obsolete now. The `bank` loads all the programs in a transaction batch before the loader is called. The obsolete code should be removed.
Removed the obsolete code, and updated the tests.
Fixes #
> Remove obsolete code for lazily loading programs

- core/src/replay_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- geyser-plugin-manager/src/geyser_plugin_service.rs
- geyser-plugin-manager/src/slot_status_observer.rs
- rpc/src/optimistically_confirmed_bank_tracker.rs
- rpc/src/rpc.rs
- rpc/src/rpc_subscriptions.rs
It is reported that Geyser is missing some Root notifications for slots. https://github.com/solana-labs/solana/issues/31124
The Root notification is sent from replay_stage's code in handle_votable_bank.  https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L1981. However, the validator does not necessarily vote on every slot on the rooted chain. From @carllin 
For instance if the rooted chain is 1->2->3->4
You might only vote on 1 and 4
But when 4 is rooted, 2 is also rooted
But handle_votavle_bank is not called on 2
As result of this, we may miss notifications for slot 2 and 3.
1. Enhanced BankNotification to add NewRootedChain enum to send the chains of parent roots.
2. Renamed BankNotification::Root -> BankNotification::NewRootBank
3. Introduced SlotNotification …
> Fixed missing Root notifications via geyser plugin framework

- core/src/serve_repair.rs
repair defines a `SlotHash` type for `(Slot, Hash)` while other validator usage uses `(Slot, Hash)` directly.
Remove `SlotHash` type in repair and replace instances with `(Slot, Hash)`.
Fixes #
> Rationalize (Slot, Hash) in repair by removing SlotHash type

- program-runtime/src/loaded_programs.rs
- runtime/src/bank.rs
Delay visible tombstones could be inferred by the presence of unloaded/loaded programs. Removing the explicit tombstone will simplify the handling of program management instructions.
This PR updates program eviction logic to not remove unloaded programs. This will enable the cache to always have either a loaded or unloaded cache entry for an upgraded program. This cache entry will imply that the older/outdated program is expired and should not be accessible after the given slot. 
Fixes #
> Do not evict unloaded programs

- core/src/banking_stage/committer.rs
- core/src/banking_stage/consumer.rs
- runtime/src/bank.rs
Counters are non-negligible in timing when we have small batches of transactions.
Profiling (see below svg) we see nearly 12% of the solTxWorker-2 time is spent just incrementing counters.
<details>
<summary>Flamegraph</summary>
This profile is from a scheduler branch w/ worker - but uses the same functions for execute, commit, record.
</details>
Remove several counters from banking stage hot loop.
Fixes #
> remove counters in hotpath

- core/src/banking_stage/thread_aware_account_locks.rs
Running an experiment w/ unlocking threads which requires using a `DashMap` inside the thread aware locks struct.
The interface for DashMap is slightly different, and we cannot do in-place tuple destructuring like is currently done; The code ended up having `.0`, or `.1` in several places which feels very brittle and less readable.
Create simple structs to hold Account-specific read and write locks w/ named fields.
This makes changes (described above) cleaner if we end up doing that.
Fixes #
> Internal structs for ThreadAware AccountRead/WriteLocks

- ledger/src/blockstore_processor.rs
These counters are not needed:
- The removed `bank-par_execute_entries-count` counter is captured in replay-slot metrics. Additionally, it was at debug level so effectively dead code.
- The removed `load_frozen_forks-cluster-confirmed-root` counter has been combined into `process_blockstore_from_root datapoint`.
> Remove metric counters from blockstore_processor

- core/src/serve_repair.rs
While working on https://github.com/solana-labs/solana/pull/31487 to upgrade our nightly Rust version, we ran into clippy lint errors like this one:
```
error: the borrowed expression implements the required traits
  | --> core/src/serve_repair.rs:1452:47
  | \|
  | 1452 \|         let mut pkt = Packet::from_data(None, &request).unwrap();
  | \|                                               ^^^^^^^^ help: change this to: `request`
  | \|
  | = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
  | = note: `-D clippy::needless-borrow` implied by `-D warnings`
```
Here's the build log: https://buildkite.com/solana-labs/solana/builds/95022#0187e79f-b4ed-4e24-b5d1-926696b8d1a3
Looks like there are a few needless borrows in …
> Removes needless borrows

- runtime/src/accounts.rs
The feature `disable_builtin_loader_ownership_chains` is designed to strictly limit the length down to two. However, it does not check that the owner of the program is owned itself by the `native_loader` and has the executable flag set like the chain loader did before.
- Adds the new restriction to the feature gate of `disable_builtin_loader_ownership_chains`.
- The case in which the loader is not owned by the `native_loader` changes its error message from `CallChainTooDeep` to `InvalidProgramForExecution`.
Feature Gate Issue: #29956
> Feature Gate Update - Requires the owner accounts of programs to be built-ins.

- programs/sbf/tests/programs.rs
- runtime/src/bank_client.rs
Using new LoadedPrograms cache causes test failures in SBF program tests.
The failing tests deploy programs and then send transactions to use the newly deployed/upgraded programs. The tests are using the same bank to deploy the program and execute the transactions. Due to delay visibility feature, the program is not effective for 1 slot after deployment. With the new cache (LoadedPrograms) this check uses bank's slot to compute the effective slot of the program.
This change advances the bank_client to the next slot after deployment of the programs.
Fixes #
> Update SBF programs tests to use bank from the correct slot

- program-runtime/src/loaded_programs.rs
The program loading fails at deployment due to existence of a tombstone.
This was observed in unit tests where the program was being deployed. During deployment, the bank tried to load the program, as the owner matches the loader. But the verification of the program failed, and it resulted in a tombstone in the cache.
After the successful deployment, the bank tries to add the new program to the cache, but the slot matches with the tombstone's slots (since delay visibility feature is not yet enabled, the effective slot for the program is same as the deployment slot).
This change allows the replacement of the tombstone with a non-tombstone entry even though the slots match between the two entry. Also adds a unit test to test this case.
Fixes #
> Allow replacing tombstone with a non-tombstone

- programs/sbf/benches/bpf_loader.rs
SBF bench fails to execute transactions using the loaded program with the new LoadedPrograms cache. 
This is similar to https://github.com/solana-labs/solana/pull/31491. The loaded program is not effective till the next slot. This PR updates bank_client to next slot's bank as the program is available in the next slot's bank.
Fixes #
> Update SBF bench to account for delay visibility

- ledger/src/blockstore_processor.rs
Re-reading this function for the first time in a while, I found some aspects of it to not follow best practice / make it harder to read.
Changes include:
- Remove redundant argument
- Shift related variable definitions to be adjacent
- Shift several variables into inner scope
- Rename several variables
- Insert newlines into log statement that was very long in addition to
moving some of the logged values to debug
~~This PR on top of https://github.com/solana-labs/solana/pull/31474.~~ Additionally, this was just a bunch of minor cleanup so seemed reasonable to lump it into one PR.
> Cleanup blockstore_processor::load_frozen_forks()

- programs/sbf/rust/invoke/src/processor.rs
In two places in `programs/sbf/rust/invoke/src/processor.rs`, `RefCell::borrow_mut` is used where `RefCell::borrow` could be used instead.
The two calls were changed to `RefCell::borrow`.
Found with [a Dylint lint](https://github.com/trailofbits/dylint/tree/master/examples/supplementary/unnecessary_borrow_mut#readme), if interested.
> `borrow_mut` -> `borrow` in two places

- program-runtime/src/loaded_programs.rs
The explicit placement of delay visibility tombstone has been removed from the code. Need to update `extract()` to implicitly return the tombstone under correct conditions.
Return the delay visibility tombstone if the current slot is between deployment and effective slot for the cached program.
Updated the unit tests.
Fixes #
> Return implicit delay visibility tombstone

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/ancient_append_vecs.rs
- runtime/src/in_mem_accounts_index.rs
It was possible to scan accounts index, addref, and then throw away the fact we addref'd. This results in a refcount issue.
Apply dirty accounts index changes to the durable index.
Fixes #
> clarify AccountsIndexScanResult::OnlyKeepInMemoryIfDirty

- gossip/src/cluster_info.rs
`test_gossip_node` is regularly failing in CI for unrelated PRs.
For example: https://buildkite.com/solana-labs/solana/builds/94996
Using a fixed port could cause a false negative, if the port is currently in use.  We actually see this test failing regularly with an error that port `1111` is already in use.
A quick search did not show any tests that hardcode port 1111, so it is unclear why is this happening.  But using hardcoded ports is not a good practice anyway.
Use random port.  There is already machinery that supports that.
This test logic does not seem to care for a specific port.
> test_gossip_node: Use random port

- core/src/immutable_deserialized_packet.rs
- core/src/latest_unprocessed_votes.rs
- core/src/packet_deserializer.rs
- core/src/unprocessed_packet_batches.rs
- core/src/unprocessed_transaction_storage.rs
`None` is always passed as 2nd parameter in calling `ImmutableDeserializedPacket::new(packet, None)`
- remove unnecessary second parameter
- remove `DeserializedPacket::new_internal()`
Fixes #
> Refactor remove unnecessary parameter

- program-runtime/src/loaded_programs.rs
The `WorkingSlot` only tracks ancestor till the latest root. If the program was deployed prior to the latest root, it fails the ancestor check in `LoadedPrograms` cache.
The `LoadedPrograms` gets notified of new roots via `prune()` API calls. This change tracks the latest root in the cache, and treats all programs deployed prior to the latest root as available on all current forks. Since, pruning removes all forks that are unreachable from the new root.
Also updated the relevant unit tests to account for pruning and roots.
Fixes #
> Programs deployed before the latest root available on all current forks

- system-test/automation_utils.sh
The test report is querying a metric that has been removed for being too noisy.
So, update the query to use a metric that we report once per slot. The metric `bank-process_transactions` was removed in https://github.com/solana-labs/solana/pull/31398.
As for the two metrics ...
- `bank-process_transactions` was a counter that was updated for any transactions from any slot
- `replay-slot-stats` is submitted when a slot is completed
So, `replay-slot-stats` is inherently excluding transactions from discarded blocks (ie one that are abandoned and result in `TooFewTicks`). Looking at a [previous test run](https://internal-metrics.solana.com:3000/d/monitor-edge/cluster-telemetry-edge?var-testnet=bare-perf-cpu-only&from=1683180719875&to=1683182010677&orgId=1) before the metric was pulled out, I …
> Update queried metric to determine tps in system tests

- program-runtime/src/loaded_programs.rs
The code for handling delay visibility tombstones needs to be replicated in tx batch cache, and can use a refactor.
Refactored the code into a function and updated the call sites.
Fixes #
> Refactor implicit handling of delay visibility tombstones

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
`historical_roots` was intended to be used when rehashing old accounts when we stopped doing rewrites. We backed up and went an entirely different direction.
So, this code is orphaned.
Remove `historical_roots` and its connections.
Fixes #
> remove unused historical_roots

- program-runtime/src/loaded_programs.rs
- runtime/src/bank.rs
The tombstones fail to match at start up while running `ledger-tool`
The criteria to match against closed program is too restrictive. The tombstones were of `LoadedProgramType::FailedVerification` type. This PR generalizes the check to match against any type of tombstone.
Fixes #
> Generalize matching criteria for tombstone at boot up

- validator/src/bin/solana-test-validator.rs
- validator/src/cli.rs
current test-validator is missing the unstable block-sub argument 
this pr adds the cli argument and adds it to the pubsub config
> add block-sub argument to solana-test-validator

- core/src/replay_stage.rs
Counters can cause heavy traffic to `MetricsAgent`, and also don't have any additional context on when the counted event occurred.
Remove the two remaining counters from ReplayStage:
- replay_stage-voted_empty_bank has been converted into a datapoint that now includes slot number
- replay_stage-replay_transactions has been removed altogether as we can get similar information on a per-slot basis from replay-slot-stats metric.
Fixes #
> Remove counters from ReplayStage

- program-runtime/src/loaded_programs.rs
- runtime/src/bank_forks.rs
`ForkGraph` returns `BlockRelation::Unknown` for programs deployed before current root slot. That causes pruning of such programs from the cache.
The `bank_forks` retains slot relationship history till the current root. The pruning has the following logic.
1. `BankForks::set_root()` gets called when a new root slot is identified.
2. `set_root()` calls cache's `prune()` method before actually storing the new root slot (i.e. cache's view of ForkGraph still has the old root slot).
3. `prune()` calls `ForkGraph::relationship()` trait method on the BankForks object with new root, and program's deployment slot. 
- If the deployment slot is descendant of the new root, it's retained in the cache.
- If the deployment slot is an ancestor of the new root, it's retained in the cache (and first …
> Use current root slot to disambiguate pruning of old programs

- Cargo.lock
- clap-v3-utils/Cargo.toml
- clap-v3-utils/src/keypair.rs
- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/errors.rs
The clap utils do not yet support ElGamal keypairs and authenticated encryption key that are needed in the token-cli for the token-2022 program. The `EncodableKey` trait was added in https://github.com/solana-labs/solana/pull/30947, but the encryption keys in zk-token-sdk do not yet implement this trait.
- Implement `EncodableKey` for `ElGamalKeypair`
- Implement `EncodableKey` for `AeKey`
This is a split PR from https://github.com/solana-labs/solana/pull/31468.
Fixes #
> [zk-token-sdk, clap-v3-utils] Implement `EncodableKey` for encryption keys

- runtime/src/bank.rs
- runtime/src/bank/address_lookup_table.rs
- runtime/src/bank/tests.rs
- runtime/src/builtins.rs
- runtime/src/genesis_utils.rs
`add_compute_budget_program` and `versioned_tx_message_enabled` are enabled on MNB and their feature gates can be removed.
- Moves `compute_budget_program` and `address_lookup_table_program` into `genesis_builtins()`.
- Removes feature gate of `versioned_tx_message_enabled`.
> Cleanup - `add_compute_budget_program` and `versioned_tx_message_enabled`

- runtime/src/bank.rs
- runtime/src/builtins.rs
- runtime/src/snapshot_minimizer.rs
This PR is a preparation for unifying the logic which transitions built-in programs on epoch boundaries (in which their features are activated) and the bitemporal model of the `LoadedPrograms` cache (which utilizes an effective slot field per entry).
- Removes `builtins::get_builtins()`, instead derives them from `Bank::builtin_programs`.
- Removes `BuiltinAction`.
- Turns `BuiltinFeatureTransition` from an enum into a struct.
- Makes `Bank::remove_builtin()` place tombstones.
> Refactor - Simplify built-in program feature transition

- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/bank.rs
The new `LoadedPrograms` cache does not have stats.
Reimplemented stats from `ExecutorCache` in `LoadedPrograms`.
Fixes #
> Add stats for LoadedPrograms

- core/src/banking_stage.rs
- core/src/banking_stage/consumer.rs
- core/src/banking_stage/forwarder.rs
- core/src/unprocessed_transaction_storage.rs
Counters incur additional overhead in sending points to the MetricsAgent over a crossbeam channel for every increment. Additionally, some of these counters would be submitted by non-voting nodes which is just extra overhead and noise.
This change condenses several updates of a counter into a field of the existing BankingStageStats metrics struct.
> Condense banking_stage counters into existing datapoint

- tokens/src/commands.rs
- tokens/src/spl_token.rs
As stated in #27318, there are excessive RPC calls in `solana-tokens distribute-spl-tokens` that cause RPC rate-limiting leading to expired blockhashes and failed transactions.
There are 3 changes to the code to reduce RPC rate-limits and blockhash expiry.
1. Batch accounts in calls to `get_multiple_accounts` instead of hitting the RPC once per account when looking to see if an ATA needs to be created.
2. Refactor `get_fees_for_messages` into `get_fee_estimate_for_messages`, where the RPC is queried for a single fee (and the fee is multiplied by the number of transactions) instead of querying the RPC for a fee for each message
3. ~~Transaction blockhashes are updated before transactions are sent~~
> Batch rpc calls in `solana-tokens distribute-spl-tokens`

- core/src/banking_stage.rs
- core/src/banking_stage/packet_receiver.rs
- core/src/immutable_deserialized_packet.rs
- core/src/packet_deserializer.rs
- runtime/src/prioritization_fee_cache.rs
- runtime/src/transaction_priority_details.rs
- sdk/src/packet.rs
Passing current root_bank's feature status from packet_receiver to ImmutableDeserializedPacket is cumbersome. The plumbing go through many level call stacks (poc #31543). 
Another possibility is to add an additional flag to `Packet`, which is set by root bank feature status at the moment of packet deserialization. So the feature status goes with packet instead of passing multiple layers of calls. It'd also make removing feature code easier when it's fully activated.
- add `round-compute-unit-price` flag to `Packet`
- `PacketDeserializer` uses `bank_fork` to get root_bank's feature set status
Fixes #
> Refactor pass feature status to deserialized packet via packet meta

- runtime/src/accounts_db.rs
`write_version` is a concept from when we allowed multiple append vecs per slot. This is no longer supported. When building the index, we were still passing around the write_version. This is not used at all.
Remove `write_version` from `IndexAccountMapEntry`
Fixes #
> remove unused IndexAccountMapEntry.write_version

- runtime/src/accounts_db.rs
`store_id` was required when we allowed multiple append vecs per slot. This is no longer supported. When building the index, there is only 1 store per slot.
Remove `store_id` from `IndexAccountMapEntry`
Fixes #
> remove IndexAccountMapEntry.store_id

- runtime/src/accounts_db.rs
- runtime/src/bank.rs
We must decouple ancient append vec boundary from hash calc to prevent append vecs from growing out of control when we stop doing rewrites.
Ancient append vec boundary is now a function of max root instead of the last hash calc slot.
Fixes #
> use highest alive root to determine ancient for packing

- runtime/src/accounts_db.rs
This struct dates back to when we had multiple stores per slot. We don't have that anymore.
Remove unnecessary struct.
Fixes #
> remove unnecessary struct IndexAccountMapEntry

- accounts-bench/src/main.rs
- core/src/accounts_hash_verifier.rs
- core/tests/epoch_accounts_hash.rs
- runtime/benches/accounts.rs
- runtime/src/accounts_background_service.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
- runtime/src/bank.rs
- runtime/src/snapshot_package.rs
- runtime/src/snapshot_utils.rs
We want to stop storing an account's hash in append vecs. But, we still need the hash for the full accounts hash calculation.
Pass through `include_slot_in_hash` to all accounts hash calculation functions so we can correctly calculate an account's hash.
Fixes #
> pass include_slot_in_hash through hash calcs to allow rehashing if hash is not stored

- core/src/accounts_hash_verifier.rs
- runtime/src/accounts_db.rs
We must decouple ancient append vec boundary from hash calc to prevent append vecs from growing out of control when we stop doing rewrites.
Remove code related to notifying when hash calc is complete and using that complete slot.
Fixes #
> remove unused functions connecting hash calc and ancient append vec boundary

- .mergify.yml
when we try to trigger mergify to an existing PR, it may remove its automerge label.
I do some test for 
https://www.github.com/solana-labs/solana/pull/31196
https://www.github.com/solana-labs/solana/pull/31407 
the status of the latest commit in 31196 is green. mergify just ignore it.
the status of the latest commit in 31407 is red. when we try to trigger mergify again, it scan all rule and remove its `automerge` label
the event log on Mergify
prevent mergify from removing `automerge` label when a PR has been merged.
Close #31562
> ci: make mergify only remove automerge when PR hasn't been merged

- Cargo.lock
Fixes builds when using llvm16 systems
Would get error:
```
thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident'
```
when attempting to build the bins.
Ref:
https://github.com/rust-rocksdb/rust-rocksdb/issues/713
Bumps librocksdb-sys to 0.8.3
and bindgen to 0.64.0
in the Cargo.lock
> Bump librocksdb-sys to 0.8.3 and bindgen to 0.64.0

- docs/src/developing/on-chain-programs/debugging.md
ledger-tool UI has changed and outdated documentation referring to the UI.
Update the docs in accordance with changes in the ledger-tool UI.
> Update on-chain debugging docs following up changes in ledger-tool UI

- core/src/banking_stage/consumer.rs
- core/src/qos_service.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
In worker PR #30970, between sanitization/scheduling time and when transactions arrive at the worker thread the slot may have changed.
This leads to some filtering of transactions *before* QoS - (crossed epoch boundary, or ALTs were closed).
QoS doesn't currently fit nicely with any filtering before itself.
* select_and_accumulate_transaction_costs takes in a new `pre_results` argument.
* select_and_accumulate_transaction_costs returns `Vec<Result<TransactionCost>>` where only selected transactions have the costs returned.
Fixes #
> QoS refactor: Allow pre-filtering

- program-runtime/src/loaded_programs.rs
The code in `extract()` API can use some cleanup and more unit tests.
Moved some of the conditions and checks in a separate function. Added unit tests specific to the new function.
Fixes #
> LoadedPrograms::extract() code cleanup and unit tests

- Cargo.lock
- Cargo.toml
- cli/src/program.rs
- ledger-tool/src/program.rs
- program-runtime/src/builtin_program.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v4/src/lib.rs
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- programs/sbf/benches/bpf_loader.rs
[solana_rbpf v0.4.0](https://github.com/solana-labs/rbpf/releases/tag/v0.4.0) was released.
- Moves `disable_deploy_of_alloc_free_syscall` parameter inside `create_loader()`.
- Removes the `is_abi_v2` flag in `create_loader()`, because there will be no syscalls at all in program-runtime-v2.
- Dissolves the wrapper `vm::VerifiedExecutable` into `elf::Executable`.
- Has `vm::BuiltInProgram::register_function()` accept raw byte strings instead of UTF-8 strings.
> Bump solana_rbpf to v0.4.0

- core/benches/consumer.rs
Wanted some idea for performance of processing function w/o considering interference from other threads or work.
Essentially creating ideal conditions for single-threaded bank tx consume performance: no possible conflicts, essentially no overhead.
This will help gauge performance in the scheduler/worker threads in terms of overhead.
Add benchmarks for `Consumer::process_and_record_transactions` for different batch sizes.
Fixes #
> consumer bench

- docs/src/api/methods/_getSignatureStatuses.mdx
- docs/src/api/websocket/_signatureSubscribe.mdx
The RPC docs are a little unclear with respect to methods that can be used to fetch information about signatures. These methods can only be called with first signatures, txids, not additional signatures.
Adds a note to `getSignatureStatuses` and `signatureSubscribe` to clarify that these use txids.
> [docs] Add note about txids to signature status RPC method docs

- core/src/duplicate_repair_status.rs
If duplicate block is received immediately upon startup from snapshot, the ancestor sample will be discarded as it falls under mismatch then match case (earlier ancestors are missing from blockstore but snapshot bank matches).
Disambiguate mismatch then match case to allow this interaction. 
Fixes #31583
> disambiguate the matches then mismatches case for ancestor samples

- banks-server/src/banks_server.rs
- client-test/tests/client.rs
- core/src/commitment_service.rs
- core/src/replay_stage.rs
- core/src/validator.rs
- ledger/src/blockstore.rs
- rpc/src/rpc.rs
- rpc/src/rpc_pubsub.rs
- rpc/src/rpc_subscriptions.rs
- runtime/src/bank_forks.rs
- runtime/src/commitment.rs
Name is a bit confusing, `highest_cluster_confirmed_root` implies a root which 2/3+ of cluster has voted for.
It's actually checking for a root that 2/3+ of the cluster has also rooted, so renaming to `highest_super_majority_root`
Fixes #
> refactor: highest_cluster_confirmed_root -> highest_super_majority_root

- runtime/src/accounts_db.rs
`is_ancient` alters behavior for several accounts_db algorithms.
These functions are thinking about ancient append vecs that are meant to be appended to. With packed ancient append vecs, writes are one-shot and the resulting ancient append vecs are not identifiable, apart from their slot #. So, the functions that ask `is_ancient` will be modified over time.
`mark_old_slots_as_dirty` should do nothing if ancient append vecs are enabled. `mark_old_slots_as_dirty` was a backstop to re-seed the clean system in case old accounts were not correctly getting cleaned. Several bugs related to refcounts in accounts_db have been fixed. The backstop isn't necessary anymore. And, ancient append vecs will do a better job of dealing with old accounts.
Fixes #
> mark_old_slots_as_dirty is a no-op when ancient append vecs are enabled

- ledger-tool/src/program.rs
The cfg and disassemble sub-sub-commands don't need to load a ledger database for running, and neither do they need an input file specifying instruction accounts etc.
This change creates a simplified invoke_context for processing the static actions of ledger-tool program sub-command.
> Fix ledger-tool program command for non-runnable subcommands

- banks-server/src/banks_server.rs
- runtime/src/bank.rs
The banks-server transaction execution used by solana-program-test hits a race condition when executing large test suites. Here's [an example](https://github.com/blockworks-foundation/mango-v4/actions/runs/4966814314/) of such a run, which only succeeded on the 3rd attempt.
```
2023-05-13T12:26:36.4991091Z thread 'solBankForksCli' panicked at 'assertion failed: !self.freeze_started()', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-runtime-1.14.17/src/bank.rs:6201:9
2023-05-13T12:26:36.4991704Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-05-13T12:26:36.4992796Z thread 'cases::test_perp_settle::test_perp_settle_pnl' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', …
```
> race condition when running solana-program-test

- runtime/src/cost_model.rs
Writing tests for these is pretty inconvenient w/o equal comparison.
Was in the process of adding some more tests to `QosService` after #31542  when I encountered this
derive PartialEq and Eq
Fixes #
> derive TransactionCost::{PartialEq, Eq}

- ledger-tool/src/program.rs
Leave a paper trail for where magic numbers come from. I initially had this change before `is_elf` variable was added, but in any case, I think pulling into a context and giving a little extra context doesn't hurt.
> ledger-tool: Move ELF magic numbers into constant with comment

- runtime/src/accounts_db.rs
`is_ancient` alters behavior for several accounts_db algorithms.
These functions are thinking about ancient append vecs that are meant to be appended to. With packed ancient append vecs, writes are one-shot and the resulting ancient append vecs are not identifiable, apart from their slot #. So, the functions that ask `is_ancient` will be modified over time.
Some stats should report ancient based on a cutoff instead of the contents of storages.
Fixes #
> cleanup a stat call to `is_ancient`

- runtime/src/accounts_db.rs
`is_ancient` alters behavior for several accounts_db algorithms.
These functions are thinking about ancient append vecs that are meant to be appended to. With packed ancient append vecs, writes are one-shot and the resulting ancient append vecs are not identifiable, apart from their slot #. So, the functions that ask `is_ancient` will be modified over time.
clean up `is_ancient` in `is_candidate_for_shrink`
Fixes #
> clean up is_ancient in is_candidate_for_shrink

- measure/src/measure.rs
`measure::tests::test_measure_end_as` is flaky.
Report: https://github.com/solana-labs/solana/issues/31585
Increase measurement margins to 20%.
> measure: `as_*`/`end_as_*` tests: Increase margins to 20%

- ci/buildkite-pipeline.sh
```
++git branch
--
| * (HEAD detached at 06b7ccc3b4)
| master
| >++git status
| HEAD detached at 06b7ccc3b4
| Untracked files:
| (use "git add <file>..." to include in what will be committed)
| pipeline.yml
|  
| nothing added to commit but untracked files present (use "git add" to track)
| +++git diff v1.14..HEAD validator/Cargo.toml
| +++grep -e '^-version'
| +++sed 's/-version = "\(.*\)"/\1/'
| fatal: ambiguous argument 'v1.14..HEAD': unknown revision or path not in the working tree.
```
The current implementation fails because `BUILDKITE_PULL_REQUEST_BASE_BRANCH` is `v1.14` branches like `v1.14` don't exist in the Buildkite clone. The fully qualified `origin/v1.14` branches exist, so adding the `origin/` prefix should resolve this.
Similar PR against master: #31636
Debugging PRs: …
> Add origin/ prefix for git diff when building CI pipeline.

- ci/buildkite-pipeline.sh
#31603 Reverted the ci version bump logic because it was failing. I think the Buildkite clone has `origin/<release branch>` branches. This restores the original code and add the origin/ prefix to the branch names.
> Restore ci version bump logic with origin/ prefix on branch names

- storage-bigtable/src/lib.rs
- Manually accumulate counters and submit as a datapoint
- Counters have been observed to have non-trivial overheads so do the accumulation locally and send accumulated result
- Adjust debug log lines to trace
- These lines felt more like trace to me as they are just stating entry into a function. More so, demoting this to trace gives an operator the granularity to enable metrics submission (datapoint_debug) without the local logging
The demotion to trace and the change from `inc_new_counter_` to an accumulated value with `datapoint_` are separate commits so I can break those apart if desired
> bigtable: Adjust logging and condense counters

- runtime/src/accounts_db.rs
Switch to using packed ancient storages instead of appended ancient storages.
This has been thoroughly tested against mnb, kin, including with 300k slots INTO the current epoch against mnb.
We can remove the append code at some point soon.
This should have no effect except during testing until we enable the eliminate rewrites feature.
Fixes #
> default to using packed ancient append vec

- docs/src/api/methods/_getEpochInfo.mdx
This PR removes an incorrect address parameter from the docs for `getEpochInfo`
Relevant source code: 
https://github.com/solana-labs/solana/blob/bac4d50761ccb96ff1eff3794dc303483ec2c010/rpc-client/src/rpc_client.rs#L2733-L2735
https://github.com/solana-labs/solana/blob/bac4d50761ccb96ff1eff3794dc303483ec2c010/rpc-client/src/rpc_client.rs#L2758-L2763
As far as I can tell there's no path where an address is used in the `getEpochInfo` call
In addition making the RPC call:
```json
{
"id": 1,
"method": "getEpochInfo",
"params": [
"H3BRzVGdedrBQD9wFitEbzEBhRoPXTemopuvS8AcNxLy"
]
}
```
Gives the error:
```json
"error": {
"code": -32602,
"message": "Invalid params: invalid type: string \"H3BRzVGdedrBQD9wFitEbzEBhRoPXTemopuvS8AcNxLy\", expected struct RpcContextConfig."
},
```
> [docs] remove incorrect pubkey param from getEpochInfo

- runtime/src/bank.rs
- runtime/src/serde_snapshot/newer.rs
For supporting partitioned reward distribution, we need to save the rewards to distribute to the snapshot.
Deserialize and ignore (for the moment) the contents of the newly written field. This allows the future version, which serializes this field, to create snapshots that can be read by the version this change goes into. The field is read and ignored by this change. The field is NOT written by this change.
Fixes #
> support snapshot deserialization with EpochRewardStatus

- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
We will soon be distributing epoch rewards over a range/interval of slots.
Introduce an enum and parameter to specify whether a slot is in the reward interval or not.
Fixes #
> prepare load_transaction_accounts to recognize reward interval

- core/src/accounts_hash_verifier.rs
- core/src/validator.rs
- core/tests/epoch_accounts_hash.rs
- core/tests/snapshots.rs
- ledger-tool/src/ledger_utils.rs
- local-cluster/src/validator_configs.rs
- local-cluster/tests/local_cluster_slow_2.rs
- validator/src/cli.rs
- validator/src/main.rs
old debug code lying around doing old debug code things
remove it
> validator: remove optional remote accounts hash consistency check

- clap-v3-utils/src/keypair.rs
- sdk/src/signer/keypair.rs
- sdk/src/signer/mod.rs
- zk-token-sdk/src/encryption/elgamal.rs
The `confirm_keypair_pubkey` and `confirm_elgamal_keypair_pubkey` share much of the same code, but they are defined separately since there is no generic trait that both `Keypair` and `ElGamalKeypair` implement to extract the pubkey.
- Add the `EncodableKeypair` trait that extends `EncodableKey` for asymmetric keypairs (i.e. have associated public keys)
- Implement `EncodableKeypair` trait for `Keypair` and `ElGamalKeypair`
- Replace `confirm_keypair_pubkey` and `confirm_elgamal_keypair_pubkey` in clap-v3-utils with generic `confirm_encodable_keypair_pubkey`
Fixes #
> [clap-v3-utils] Add `EncodableKeypair` trait and make `confirm_keypair_pubkey` generic

- runtime/src/bank.rs
`pub` is not necessary. Type is currently private. Soon, type will be `pub(crate)`.
remove unnecessary `pub` on `fn get_stake_reward`
Fixes #
> remove unnecessary pub

- docs/src/api/methods/_getBlockTime.mdx
This PR updates the response type in the docs for `getBlockTime` and adds an extra example response 
As far as I can tell there is no path where the function returns null, it either returns a block time for the requested slot or an error. Source code: https://github.com/solana-labs/solana/blob/694099bbe3891d2168e6abb226e5202cc9190fed/rpc-client/src/nonblocking/rpc_client.rs#L3292-L3302
I've added an example response showing the error, in a similar way to [getHealth](https://docs.solana.com/api/http#gethealth)
> [docs] add error response for getBlockTime RPC call

- clap-v3-utils/src/keypair.rs
The function `ae_key_from_seed_phrase` in clap-v3-utils `keypair` module returns `ElGamalKeypair` as opposed to `AeKey`. This is a mistake from a previous PR :pray:.
Change output type of `ae_key_from_seed_phrase` to `AeKey`.
Fixes #
> [clap-v3-utils] Fix output type of `ae_key_from_seed_phrase`

- ledger-tool/src/program.rs
Seeing the following warning in M1 MacOS builds
```
--> ledger-tool/src/program.rs:353:9
|
353 |     let mut verified_executable = if is_elf {
|         ----^^^^^^^^^^^^^^^^^^^
|         |
|         help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```
The `mut` variable is used under a flag. Added clippy ignore.
Fixes #
> Fix warning about unused mut in ledger-tool

- ci/publish-crate.sh
Our CI job for publishing crates is broken because it specifies rust v1.63, newer winnow releases have an msrv of v1.64, and cargo package/publish doesn't respect Cargo.lock (which specify an older version of winnow).
But wait, there's more: time just published a new version with an msrv of v1.65
Set the `RUST_STABLE_VERSION` envar to ~~v1.64.0~~ v1.65.0 in publish-crate.sh in v1.14
> v1.14: Hardcode even newer rust version for crate publishing

- core/src/validator.rs
- rpc/src/rpc_service.rs
Cluster simulations still exhibit zombie threads in the rpc_service/send_transaction_service area when the [recently removed](https://github.com/solana-labs/solana/pull/31279) `AccountsHashVerifier::should_halt()` is triggered. This is because [this change](https://github.com/solana-labs/solana/pull/5566) is only exercised when a formal ValidatorExit is triggered, and not when the exit AtomicBool is set to true.
- Call `JsonRpcService::exit()` inside `JsonRpcService::join()`, to ensure the Server actually closes when cleaning up threads
- Also clean up a slight regression introduced in #5566 and perpetuated in #31261 wherein the SendTransactionService uses an rpc-service-specific exit, instead of the same exit as all the other services. (This did not appear to be causing zombie threads, …
> Eradicate zombie RPC threads

- clap-v3-utils/src/keypair.rs
- sdk/src/signer/keypair.rs
- sdk/src/signer/mod.rs
- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
Currently, the `EncodableKey` trait contains functions related to both the encoding of keys and seed derivation. Structs like `Pubkey` and `ElGamalPubkey` are keys that can be written and read from files, but they are public keys and hence not directly derivable from seeds (one can first derive the private key first and then derive public key from it, but this is not very useful). It seems natural for `Pubkey` and `ElGamalPubkey` to implement `EncodablePubkey` minus the seed derivation part.
- Move the seed derivation component of `EncodableKey` into a separate `SeedDerivable` trait
- Implement `SeedDerivable` for `Keypair` and `ElGamalKeypair`
- Implement `EncodableKey` for `ElGamalPubkey`
- Implement `EncodableKey` and `SeedDerivable` for `ElGamalSecretKey`
It seems natural to also …
> [clap-v3-utils, sdk, zk-token-sdk] Split `EncodableKey` into `EncodableKey` + `SeedDerivable`

- rpc/src/rpc_service.rs
As of #31381, CI doesn't catch redundant clones, but running clippy locally does.
Remove redundant clone that I neglected to remove in #31688 (no backport needed; bundled with #31689)
> Remove redundant clone

- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
manual backport of #31049 to v1.14 (should pick clean onto v1.13 as well)
> Add connection error metrics - v1.14 (bp #31049)

- ledger-tool/src/program.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/message_processor.rs
`InvokeContext` should not require `Rc` and `RefCell` to carry program cache references.
Clean up the cache references in `InvokeContext` and update surrounding code.
Fixes #
> Remove Rc and RefCell to carry program cache in invoke_context

- core/src/banking_stage/consumer.rs
Enabling the mentioned feature without first removing the QoS Adjustment Logic (https://github.com/solana-labs/solana/issues/29595#issuecomment-1524087480) breaks cluster test runs off head of Master, where all features are enabled by default. 
- disables the QoS Adjustment Logic when feature is activated (Will still remove the logic eventually #31379)
Fixes #31340
> disable qos adjustment logic when feature apply_cost_tracker_during_replay is activated

- ci/test-checks.sh
I disabled rather useful clippy lint altogether at #31381 , causing some trouble around bp-ing. ref: #31690 
Restore the functionary with somewhat degraded state as a band-aid fix for now..
namely, `check` will take extra minutes, but i think it's acceptable.
upstream bug: https://github.com/rust-lang/rust-clippy/issues/10577
> Temporarily use stable clippy for redundant_clone

- rpc/src/rpc_pubsub_service.rs
Counters incur non-trivial system overhead. Additionally, individual
counters on related fields are hard to view in influx given that they all
show up under different measurements.
The counters have been combined into fields within a struct that are
accumulated locally and submitted on a set interval (10s). Doing so
decreases overhead on the system as well as makes it easier to compare
these similar fields in the metrics explorer by having them all under
the same measurement.
Looking at the metrics for these fields over the last day, I see a few nodes on mnb that have a cumulative count of all these fields in excess of 5M per hour, or 1388 per second. With the new interval of 10s, this is several orders of magnitude of reduction in reporting frequency. This is also a huge drop in the …
> Condense and rename pubsub counters into a single datapoint

- ci/buildkite-pipeline.sh
downstream project tests take almost 30mins in last few times build.
I guess the testing speed is related to the setup of NVMe but I haven't had a look at them. 
no matter what, I think we can have more tolerance with this one.
increase timeout to 40mins for downstream project tests
> ci: increase timeout for downstream project tests

- runtime/src/bank.rs
- runtime/src/serde_snapshot/newer.rs
- runtime/src/serde_snapshot/tests.rs
write EpochRewardStatus to snapshot if it is not default `Inactive`, based on the bank's `epoch_reward_status`. However, that field will ALWAYS be `Inactive` until the feature is activated for partitioned rewards. This approach allows us to leave snapshot persistence UNCHANGED unless `epoch_reward_status` is `Active`. This means we can easily test this feature on clusters without having to backport the change that reads_eof the `epoch_reward_status` field.
Fixes #
> persist EpochRewardStatus::Active

- runtime/src/serde_snapshot/newer.rs
partitioned reward feature is making its way into reality, behind a feature gate.
In the meantime, peristance into snapshot has to be reworked to deal with `EpochRewardStatus`.
Apply the loaded `epoch_reward_status` into `BankFieldsToDeserialize`
Fixes #
> deserialize epoch_reward_status into BankFieldsToDeserialize

- core/src/banking_stage/consumer.rs
Clarify a comment
- update comment
Fixes #
> update comment for clarification

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
- runtime/src/cache_hash_data.rs
building with nighly reports some warnings.
remove redundant uses of `mut`
Fixes #
> remove redundant `mut`s

- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/bank.rs
Farming work out to a thread-pool works well for a lot of accounts-wide operations but is a bottleneck in the banking-stage and replay stage hot loops (see svg in details below).
Additional bool argument passed down to allow callers to force inline execution of the `update_index` function.
Still need to do some additional benching, however, this change shows significant improvement in bench-tps numbers when we have a lot of conflict:
Numbers are displayed as "MAX TPS / AVG TPS"
| number of serializable tx-chains | 1 | 4 | 16 | 50000 |
| --- | ---: | ---: | ---: | ---: |
| master | 6715 / 4048 | 13397 / 7541 | 23603 / 12765 | 75637 / 52698 |
| PR | 11699 / 8208 | 24159 / 18601 | 40706 / 31451 | 80685 / 51630 |
<details>
<summary>Command details</summary>
Table columns correspond to:
1. …
> Performance: Allowed forced inline update_index (no thread pool)

- program-runtime/src/loaded_programs.rs
new loaded programs cache hijacked the old metrics datapoint name, which pollutes both metrics
rename the datapoint to reflect it's actual source
> runtime: rename executor cache datapoint

- core/src/serve_repair.rs
The value reported by this counter is also reported by the
self_repair field in the serve_repair-requests_received datapoint.
Remove redundant counter
> Remove redundant counter from ServeRepair

- cli/src/cluster_query.rs
When invoking `$ solana epoch-info` against local cluster, it results in the following panic:
```
thread 'main' panicked at 'overflow when adding durations', library/core/src/time.rs:920:31
stack backtrace:
<skipped>
15: solana_cli_output::cli_output::OutputFormat::formatted_string
at ./cli-output/src/cli_output.rs:77:38
16: solana_cli::cluster_query::process_get_epoch_info
at ./cli/src/cluster_query.rs:1145:8
17: solana_cli::cli::process_command
at ./cli/src/cli.rs:905:37
18: solana::do_main
at ./cli/src/main.rs:256:22
19: solana::main
at ./cli/src/main.rs:247:5
20: core::ops::function::FnOnce::call_once
at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
``` …
> process_get_epoch_info resulting in duration value underflow

- docs/src/implemented-proposals/abi-management.md
Docs need more details for `frozen_abi` dev workflow.
Add instruction to use `SOLANA_ABI_DUMP_DIR=. cargo +nightly test abi`.
Fixes #
> update frozen_abi dev workflow in docs

- net/net.sh
`net.sh start` fails with the following error.
```
rsync: mkdir "/home/solana/$HOME/solana" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(681) [Receiver=3.1.3]
+ exit 1
^^^ +++
```
The script is unable to resolve `$HOME`. Replaced it with `~`. 
Fixes #
> Resolve remote $HOME in net.sh

- keygen/Cargo.toml
The `tempfile` crate dependency uses a concrete version as opposed to workspace shared version.
Use workspace version for `tempfile` crate.
Fixes #
> [keygen] Use workspace version for `tempfile`

- local-cluster/src/local_cluster.rs
Local cluster assumes that the feature flag `vote_state_add_vote_latency` is always turned on when creating a new vote account on the cluster. This causes `VoteInstruction::InitializeAccount` to fail if the feature flag is not actually turned on.
Check the status of the feature flag before creating new vote accounts. 
Fixes #
> local-cluster: use feature flag for size for vote accounts

- program-runtime/src/loaded_programs.rs
The builtin's are not being pruned from the program cache.
Remove the special handling of builtin in `prune()` that prevents removal of the entries.
Fixes #
> Remove special handling of builtin while pruning

- net/scripts/network-config.sh
The `net` scripts fail to start private testnet cluster.
The `net` scripts were not configuring`vm.max_map_count` and number of open FDs. This PR adds the configuration commands as part of network configuration script.
Fixes #
> Adjust mmap and FD count for net scripts

- Cargo.lock
- programs/sbf/Cargo.lock
Dependabot is not able to update regex for some reason
Update manually
> Bump regex to v1.8.1

- zk-token-sdk/src/instruction/ctxt_ctxt_equality.rs
- zk-token-sdk/src/instruction/pubkey_validity.rs
- zk-token-sdk/src/instruction/transfer.rs
- zk-token-sdk/src/instruction/transfer_with_fee.rs
- zk-token-sdk/src/instruction/withdraw.rs
- zk-token-sdk/src/instruction/zero_balance.rs
Currently, the function used to generate transcripts for zero-knowledge proofs `transcript_new` lives as an associated function of the individual proof types, taking in all the proof context fields as input. This can be simplified by making `transcript_new` as an associated function of the proof context types instead.
- Refactor the `transcript_new` functions in each proof instructions module to be an associated function of the proof context types
- Rename `transcript_new` to `new_transcript` to make the funciton name slightly more natural
- For `TransferWithFee`, also include the fee parameters in the transcript. It is okay not to include the fee parameters, but it could be safer and more complete to append the entire proof context information in the transcript.
Fixes #
> [zk-token-sdk] Generate proof transcript directly from proof contexts

- cli/src/program.rs
- ledger-tool/src/program.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/sbf/benches/bpf_loader.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
Currently the RBPF config and syscall registry are created for each Instruction of a Transaction, which is wasteful and makes it hard to control the config in one place. Note, that this PR does not yet implement the feature activation recompilation phase nor does it adjust the RBPF config based on feature activations.
- Adds `LoadedPrograms::program_runtime_environment_v1` which is created in `Bank::finish_init()` and used in `Bank::load_program()`.
- Merges `get_programdata_offset_and_deployment_offset()` into `load_program_from_account()`.
- Renames `create_loader()` to `create_program_runtime_environment()`.
> Refactor - Share RBPF config and syscall registry globally

- Cargo.lock
- Cargo.toml
- zk-keygen/Cargo.toml
- zk-keygen/src/main.rs
There is currently no cli utility to create encryption keys (ElGamal and authenticated encryption) used for token-2022 and more generally zero-knowledge proofs.
Create a `zk-keygen` cli tool to generate encryption keys and add the `new` command that randomly generates encryption keys analogously to `keygen`.
Other commands like `recover` (recover key/keypair from passphrase) and `pubkey` (print out pubkey from an ElGamal keypair) will be added in a follow-up PR.
The `solana-zk-keygen` is marked not for publication for now.
Fixes #
> [zk-keygen] create cli utility and add `new` command

- Cargo.lock
- zk-keygen/src/main.rs
https://github.com/solana-labs/solana/pull/31641 was merged without rebasing https://github.com/solana-labs/solana/pull/31668, which splits `EncodableKey` trait into `EncodableKey` and `SeedDerivable`. This prevents `zk-keygen` from building and causes ci error. Sorry! :pray:
Import `SeedDerivable` trait in `zk-keygen`.
Fixes #
> [zk-keygen] import `SeedDerivable` trait

- transaction-status/src/lib.rs
While developing the spec for the new web3.js RPC I noticed that despite this message in the docs:
> List of address table lookups used by a transaction to dynamically load addresses from on-chain address lookup tables. Undefined if `maxSupportedTransactionVersion` is not set.
…that `"addressTableLookups": null` would appear in the response for `getTransaction`.
Just like for `"encoding": "json"`, make it so that we don't serialize `addressTableLookups` when the encoding is `jsonParsed`.
1. Airdropped myself
2. Looked up the transaction with `jsonParsed` encoding
```json
{
"result": {
"blockTime": 1684520057,
"meta": {
"computeUnitsConsumed": 150,
"err": null,
"fee": 5000,
"innerInstructions": [],
"logMessages": [
"Program 11111111111111111111111111111111 invoke [1]", …
```
> fix: `addressTableLookups` no longer serialized unless version set

- runtime/src/accounts_db.rs
- runtime/src/accounts_file.rs
- runtime/src/append_vec.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
AccountsFile- and AppendVec-related code uses io::Error for their main error type.  However, there're many errors under AccountsFile that don't belong to io::Error.
This PR introduces AccountsFileError and makes minimum changes to keep the PR small.
Subsequent changes related to this will be in separate PRs.
> Add new error type AccountsFileError

- runtime/src/serde_snapshot.rs
- runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs
Part of the snapshot-related code uses io::Error while other parts use SnapshotError.
As SnapshotError can be created from io::Error, this PR makes snapshot-related
code to use SnapshotError instead.
This PR also makes the refactoring of AccountsFile errors easier (#31631, which has landed).
> Refactor SnapshotError related code

- runtime/src/serde_snapshot.rs
The return error type -- io::Error used in reconstruct_single_storage()
isn't suitable to describe all possible errors inside the function such as
AccountsFileError.
This PR makes it return SnapshotError which can better handle
both AccountsFileError and io::Error.
This small PR depends on #31632.
> Make reconstruct_single_storage() returns SnapshotError

- runtime/src/bank/tests.rs
Split from #31750.
The feature gating logic was already cleaned up in #29695 for the most part.
> Cleanup - bank_transaction_count_fix

- banking-bench/src/main.rs
- core/src/banking_stage.rs
- core/src/banking_stage/consumer.rs
- core/src/replay_stage.rs
- poh/src/poh_recorder.rs
- poh/src/poh_service.rs
`set_bank` is taking ownership of the `Arc<Bank>`.
Update function signature.
Fixes #
> set_bank takes owned Arc<Bank>

- cli/src/cluster_query.rs
- cli/src/wallet.rs
- core/src/broadcast_stage.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- runtime/src/accounts.rs
cargo nightly started flagging on some redundant clones. Some are false positives, others are not.
Fix the actual redundant clones.
Fixes #
> Remove redundant clones

- Cargo.lock
- zk-keygen/Cargo.toml
- zk-keygen/src/main.rs
The `solana-zk-keygen` tool does not yet have commands for recovering encryption keys from seed phrases and ElGamal pubkey from an ElGamal keypair file.
Add the `pubkey` and `recover` commands.
For the `pubkey` command, the key-type argument `--type` is required even if `elgamal` is the only possible option. I can change this if anyone has an opinion against this.
Fixes #
> [zk-keygen] Add `pubkey` and `recover` commands

- core/src/validator.rs
- ledger-tool/src/ledger_utils.rs
- runtime/src/snapshot_utils.rs
In ledger-tool, we delete the `<account_path>/run` directory at start up.
Creating a bank from disk expects these directories exist in order to perform hard linking from the `<account_path>/snapshot/XX/*` files into `run`.
We prevously made changes to ensure the run and snapshot directories exist, and but then immediately remove them.
Only delete contents of run dirs on startup, not the directories themselves.
Fixes #
> async delete contents but leave directory

- Cargo.lock
- zk-token-sdk/Cargo.toml
- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
For applications like token-2022, users must maintain separate encryption keys (`ElGamalKeypair` and `AeKey`). For users that do not want to maintain separate encryption keys, they have the option to derive these encryption keys from a signer via `ElGamalKeypair::new` and `AeKey::new`. These functions take in a signer and a pubkey and derive the encryption keys as follows:
1. generate a signature of a fixed message
2. hash the signature to generate a seed
3. use the seed to generate the encryption keys
From the perspective of a token-2022 user, the signer should be the user's signing key and the pubkey should be its token account address.
Currently, the fixed message at step 1 is a Solana `Instruction` message with `program_id` as the pubkey parameter and data as a fixed bytes …
> [zk-token-sdk] Generalize encryption key derivation from signers

- zk-token-sdk/src/encryption/auth_encryption.rs
Currently, there is an inconsistency between the way ElGamal and Ae keys are randomly generated. `ElGamalKeypair::new_rand() -> ElGamalKeypair` uses `OsRng` internally to sample a new keypair. `AeKey::random<T: RngCore + CryptoRng>(rng: &mut T) -> AeKey` takes in an external random generator and samples a new key.
Update `AeKey::random` function to `AeKey::new_rand` so that it is consistent with how `ElGamalKeypair` is randomly generated.
Split from https://github.com/solana-labs/solana/pull/31586
Fixes #
> [zk-token-sdk] Update random `AeKey` generation to use `OsRng` internally

- entry/src/entry.rs
- ledger/src/blockstore_processor.rs
#31290 adds an entry notification service -- only for nodes running with a geyser plugin that wants entry notifications -- but there isn't anywhere sending Entry messages to the service.
Hook up the Tvu path, sending Entry messages from `blockstore_processor`
~~Needs rebase on #31290~~ ✅
> Send messages to EntryNotifierService from blockstore_processor

- runtime/src/bank.rs
- runtime/src/serde_snapshot/tests.rs
in simplifying partitioned epoch rewards, it is simpler to use the current block height instead of parent.
Fixes #
> change StartBlockHeightAndRewards from parent to current

- zk-keygen/Cargo.toml
Minor typo in `Cargo.toml` that yielded warnings when building:
```
$ cargo build --release --bin solana-validator
warning: /home/sol/src/solana/zk-keygen/Cargo.toml: dependency (thiserror) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
warning: /home/sol/src/solana/zk-keygen/Cargo.toml: unused manifest key: dependencies.thiserror.worskapce
```
Fix the typo
> Fixed typo: worskapce ==> workspace

- programs/bpf_loader/src/syscalls/mod.rs
> Cleanup - check_syscall_outputs_do_not_overlap

- docs/src/getstarted/local.md
The CLI setup in [/getstarted/local](https://docs.solana.com/getstarted/local) isn't in sync with [/cli/install-solana-cli-tools](https://docs.solana.com/cli/install-solana-cli-tools). Windows setup instructions aren't included. 
I've copied over the Windows setup from the CLI install page but replaced the release version with `stable`. I've also mentioned that WSL is recommended for Windows users.
> Add Windows installation instructions

- runtime/src/lib.rs
- runtime/src/partitioned_rewards.rs
Add config for partitioned rewards. Usable by tests and cli on ledger-tool and validator. Holds basic configuration info.
Fixes #
> add partitioned_rewards.rs

- runtime/src/accounts_db.rs
Allow delta hash to skip accounts. This is specifically useful when we are [forcing partitioned epoch rewards to occur in a single slot](https://github.com/solana-labs/solana/pull/31354#issuecomment-1561292446) for testing against the unactivated feature (ie. status quo). We need to ignore the sys var for epoch rewards.
Fixes #
> add optional ignore to `calculate_accounts_delta_hash`

- runtime/src/accounts_file.rs
- runtime/src/append_vec.rs
AppendVec currently uses std::io::ErrorKind::Other for its own errors.
This PR introduces AppendVecError and has AppendVec use it.
> Add enum AppendVecError

- ledger-tool/src/main.rs
- validator/src/cli.rs
when submitting earlier, #31800, I switched up the -/_ symbols in the long and name arguments of the cli args for ledger-tool and validator. Problem is, I got them backwards. TIL.
reverse -/_ in name vs long
Fixes #
> fix cli args

- banking-bench/src/main.rs
- bench-tps/src/main.rs
- cli/src/program.rs
- client/src/connection_cache.rs
- client/src/nonblocking/tpu_client.rs
- client/src/tpu_client.rs
- connection-cache/src/connection_cache.rs
- connection-cache/src/connection_cache_stats.rs
- core/benches/banking_stage.rs
- core/src/banking_stage.rs
- core/src/banking_stage/forwarder.rs
- core/src/tvu.rs
- core/src/validator.rs
- dos/src/main.rs
- local-cluster/src/local_cluster.rs
- rpc-test/tests/nonblocking.rs
- rpc-test/tests/rpc.rs
- rpc/src/rpc.rs
- rpc/src/rpc_service.rs
- send-transaction-service/src/send_transaction_service.rs
- tpu-client/src/nonblocking/tpu_client.rs
- tpu-client/src/tpu_client.rs
Need to distinguish connection-cache metrics for different protocols (e.g. TPU vs turbine).
Separated out connection-cache metrics for different protocols
> separates out connection-cache metrics for different protocols

- client/src/connection_cache.rs
- core/src/tpu.rs
- quic-client/tests/quic_client.rs
- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
Need to distinguish QUIC streamer metrics for different protocols (e.g. TPU vs turbine).
Separated out QUIC streamer connection stats from different servers.
> separates out quic streamer connection stats from different servers

- measure/src/measure.rs
- sdk/src/timing.rs
flaky `Measurement` tests
* test timer and unit conversions separately
* test `sdk::timing::duration_as_*()` helpers directly
Fixes #31810
> ci: deflake `Measurement` tests

- perf/src/sigverify.rs
- sdk/src/transaction/sanitized.rs
When replay stage flags simple vote transaction, it should check number of signatures as banking stage does [here](https://github.com/solana-labs/solana/blob/master/perf/src/sigverify.rs#L355-L359). 
- add tests
- add signature count check
Fixes #
> check simple vote could have 1 or 2 signatures when creating sanitized transaction

- ci/test-checks.sh
seems #23599 introduced unneeded whitespace, skewing indent a bit. 
irony here is that it's a pr for source code formatting... ;)
Fix indent
context: needed for https://github.com/solana-labs/solana/pull/31692#pullrequestreview-1431649685
Fixes #
> Fix indent of ./ci/test-checks.sh

- programs/zk-token-proof-tests/tests/process_transaction.rs
- programs/zk-token-proof/src/lib.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/instruction/range_proof.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
The zk-token-proof program does not yet have an instruction that can verify range proof on a Pedersen commitment.
Add `VerifyRangeProof64` instruction. This instruction can be used to prove that a committed value is in a certain range.
The verification for these instruction was benched in the devserver and CU units were computed assuming that 1 CU should take roughly 33ns (as per https://github.com/solana-labs/solana/pull/25464#issuecomment-1142598915).
Fixes #
> [zk-token-sdk] add range-proof proof instruction

- zk-token-sdk/src/encryption/auth_encryption.rs
There are no docs for the authenticated encryption module in zk-token-sdk.
Add docs to functions in `auth_encryption`.
This is split from https://github.com/solana-labs/solana/pull/31586.
Fixes #
> [zk-token-sdk] Add function docs for authenticated encryption

- poh/src/poh_recorder.rs
#4961 oddly started to re-expose `Slot` from the mod: https://github.com/solana-labs/solana/pull/4961#discussion_r1206264120, confusing rust/human a bit like this: https://github.com/solana-labs/solana/pull/30976#discussion_r1170825849:
Fix it
Fixes #
> Don't needlessly expose Slot from solana-poh

- ci/test-checks.sh
Add proper and updated explanation as to _nightly_ clippy (https://github.com/solana-labs/solana/pull/31692#pullrequestreview-1431649685):
> What's the argument for running nightly clippy everywhere, incidentally? The comment only refers to sdk. It would also be nice to document what nightly-only code we're actually using there.
... so that I can hide my real desire (hint: branch name) from public scrutiny. :)
ref: https://github.com/rust-lang/rust/issues/66287
> Explain use of nightly clippy over whole monorepo

- sdk/program/src/lib.rs
AFAICT invoking `system_instruction::transfer` does not require passing `system_program` in `account_infos` and that seems to be how Anchor does it (see https://github.com/coral-xyz/anchor/blob/c3625c8cf2ea1cb5f94859f6234c2d73c6f17928/lang/src/system_program.rs#L298-L313)
Removed comment stating the system_program is required for the instruction and updated the doc's code sample.
Fixes #
> remove inaccurate comment about system instructions

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/pedersen.rs
In some places in the zk-token-sdk, abbreviated variable names are used, which makes the code harder to read.
Use full variable names in the `auth_encryption` and `pedersen` submodules. There are some abbreviated variable names in `zk_token_elgamal`, but they will be updated in a separate PR as part of https://github.com/solana-labs/solana/issues/31813.
Fixes #
> [zk-token-sdk] Use full variable names

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/elgamal.rs
1. The `ElGamalKeypair::from_seed()` function returns a boxed error, although there is one possible choice of error: seed is too short.
2. The `AuthenticatedEncryptionError::SeedLengthTooShort` variant was added to return a suitable error type when `EncodableKey::pubkey_string()` is called on `AeKey`. However, the trait function `EncodableKey::pubkey_string()` ended up being removed (https://github.com/solana-labs/solana/pull/30947#discussion_r1157838687).
1. Add `{ElGamalError, AuthenticatedEncryptionError}::SeedLengthTooShort` error variant and use it for `from_seed` functions
2. Remove `AuthenticatedEncryptionError::SeedLengthTooShort` error variant
There are no downstream projects currently using `AuthenticatedEncryptionError`, so removing the variant`SeedLengthTooShort` should be …
> [zk-token-sdk] Add encryption error variant `SeedLengthTooShort` and remove variant `PubkeyDoesNotExist`

- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/elgamal.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
- zk-token-sdk/src/zk_token_elgamal/pod/pedersen.rs
As pointed out in https://github.com/solana-labs/solana/issues/31813, the code in `zk-token-elgamal` is quite messy. In particular, the types in `pod.rs` and the conversion logic in `convert.rs` can be re-organized into submodules following the module structure of the rest of `zk-token-sdk`.
The `pod` types were refactored in https://github.com/solana-labs/solana/pull/31814. The `convert.rs` can now be refactored.
- Moved pod `DecryptHandle` from `pod::pedersen` to `pod::elgamal`. This was a miss from the previous refactor (https://github.com/solana-labs/solana/pull/31814) since `Decrypt` handle lives in `encryption::elgamal` as opposed to `encryption::pedersen`.
- The conversion logic for `elgamal` and `pedersen` typs are refactored into their respective `pod` submodules from …
> [zk-token-sdk] Refactor `zk-token-elgamal` conversion code for `elgamal` and `pedersen` pod types

- cli/src/test_utils.rs
- cli/tests/stake.rs
Some stake tests will need to wait a given number of slots AFTER a new epoch for partitioned rewards payout to have completed.
modify `wait_for_next_epoch` to `wait_for_next_epoch_plus_n_slots` to allow waiting for additional slots. When partitioned rewards are enabled, we'll need to wait several slots after the next epoch.
Fixes #
> allow stake tests to wait for rewards payout

- runtime/src/bank/metrics.rs
add some metrics reporting for partitioned rewards. This will be hooked up shortly.
Fixes #
> add RewardsStoreMetrics for partitioned rewards

- runtime/src/bank.rs
add `parent_height` to `Bank::process_new_epoch`. This will be used shortly to determine which partition index to distribute rewards for.
Fixes #
> bank process_new_epoch takes parent_height

- .mergify.yml
Since v1.15 was abandoned we've only done Mergify backports with v1.14 (see #30621). Now that our branches are back to normal(ish) this adds the Mergify logic for v1.16 backports
> Add Mergify rules for v1.16 backport

- account-decoder/src/parse_account_data.rs
- account-decoder/src/parse_token.rs
- accounts-cluster-bench/src/main.rs
- ledger/src/token_balances.rs
- rpc/src/parsed_token_accounts.rs
- tokens/src/commands.rs
- tokens/src/spl_token.rs
- transaction-status/src/parse_associated_token.rs
- transaction-status/src/parse_token.rs
- transaction-status/src/parse_token/extension/cpi_guard.rs
- transaction-status/src/parse_token/extension/default_account_state.rs
- transaction-status/src/parse_token/extension/memo_transfer.rs
- transaction-status/src/parse_token/extension/mint_close_authority.rs
- transaction-status/src/parse_token/extension/permanent_delegate.rs
- transaction-status/src/parse_token/extension/reallocate.rs
- transaction-status/src/parse_token/extension/transfer_fee.rs
- validator/src/admin_rpc_service.rs
Since #31607, there is only a single `solana-program` in the build tree. As a result, spl-token and spl-token-2022 apis can operate with normal Pubkey and Instruction types, instead of needing to convert to different versions.
Deprecate type conversion methods and remove their usage. It would be nice to remove the conversion apis altogether, but I'm not sure if any dependents are using those methods (they shouldn't need to). They are part of the public api for `solana-account-decoder` and `solana-transaction-status`, unfortunately.
> Clean up Spl type conversions

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/byte_block.rs
- runtime/src/tiered_storage/footer.rs
This PR includes the util structs for writing byte blocks, which will be used
by the TieredStorage writer (currently used in the prototype #30626).
The PR only includes the Raw encoding format.  Will add more in subsequent PRs.
Tested in mnb with the prototype implementation of the tiered-storage (#30626)
Unit tests are also included in this PR.
> Byte-blocks utils for TieredStorage (1/N)

- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/auth_encryption.rs
- zk-token-sdk/src/zk_token_elgamal/pod/range_proof.rs
- zk-token-sdk/src/zk_token_elgamal/pod/sigma_proofs.rs
This is a follow-up to https://github.com/solana-labs/solana/pull/31846 on refactoring conversion logic in `convert.rs`.
- Refactor `Try` and `TryFrom` implementation for authenticated encryption type to `zk_token_elgamal::auth_encryption`
- Refactor `Try` and `TryFrom` implementation for range proof types to `zk_token_elgamal::range_proof`
- Refactor `Try` and `TryFrom` implementation for sigma proof types to `zk_token_elgamal::sigma_proofs`
Fixes #
> [zk-token-sdk] Refactor `zk-token-elgamal` conversion code for authenticated encryption, range proof, and sigma proof types

- zk-token-sdk/src/encryption/grouped_elgamal.rs
- zk-token-sdk/src/encryption/mod.rs
- zk-token-sdk/src/zk_token_elgamal/pod/grouped_elgamal.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
Please see https://github.com/solana-labs/solana/issues/31853 for further background.
- The ciphertext validity proofs that are to be added to the zk token proof program can be more cleanly defined in terms of `GroupedElGamalCiphertext`
- The `TransferAmountEncryption` and `FeeEncryption` in the `instruction::transfer` and `instruction::transfer_with_fee` modules can be simplified as thin wrappers around `GroupedElGamalCiphertext`
Add the `GroupedElGamalCiphertext` type.
Fixes #
> [zk-token-sdk] Add `GroupedElGamalCiphertext` type

- bench-tps/Cargo.toml
accidentally found a place doesn't use workspace inheritance. just corrected it.
> chore: use workspace's tempfile

- core/src/validator.rs
- core/tests/epoch_accounts_hash.rs
- core/tests/snapshots.rs
- ledger-tool/src/ledger_utils.rs
- ledger/src/bank_forks_utils.rs
- ledger/src/blockstore_processor.rs
- local-cluster/tests/local_cluster.rs
- runtime/benches/accounts_index.rs
- runtime/src/accounts.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
- runtime/src/accounts_index_storage.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/snapshot_utils.rs
The callstack updated in this PR passed an &Arc<...> down only to have
the bottom level clone the reference. Thus, we are giving shared
ownership so the reference is a bit redundant and arguably obscures the
intention to clone further down the callstack.
Perform the clone of Arc<...> at the top level, and pass the owned Arc through the callstack. Noticed this while reviewing 31870
> Replace improper &Arc<...> with Arc<...> in Bank and Accounts

- core/src/ancestor_hashes_service.rs
Some of the comments and strings in the tests are misleading...
Correct misleading comments for repair test. 
Fixes #
> Correct misleading comments for repair test

- core/src/verified_vote_packets.rs
The feature flag `allow_votes_to_directly_update_vote_state` allows an optimization of only storing one vote per validator before forwarding to banking stage. We store votes for the latest slot - which implicitly drops refreshed votes.
Create a tiebreaker, if the slot is the same as the latest vote only accept it if it has a later timestamp (refreshed vote)
Fixes #
> Relax gossip to banking stage filtering to allow refreshed votes

- .github/ISSUE_TEMPLATE/2-feature-gate.yml
There is no process around feature testing and stabilization to validate feature gates as they are activated on public clusters.
Add a lightweight mechanism that simply asks for deployment considerations when a feature-gate issue is created.
> Add field for feature-gate-issue deployment considerations

- ci/publish-crate.sh
our crates publish failed cuz our version is inherited from workspace.
- check workspace.version in `Cargo.toml` and `programs/sbf/Cargo.toml`
- do old version check when the version isn't `{ workspace = true }`,
> ci: fix publish crate version checking

- programs/zk-token-proof-tests/tests/process_transaction.rs
- programs/zk-token-proof/src/lib.rs
- zk-token-sdk/src/instruction/batched_grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/transcript.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
The zk-token-proof program does not yet have instructions that can verify whether a ciphertext is valid.
Add `VerifyGroupedCiphertext2HandlesValidity ` and `VerifyBatchedGroupedCiphertext2HandlesValidity` instructions.
The verification for these instructions were benched in a devserver and CU units were computed assuming that 1 CU should take roughly 33ns (as per https://github.com/solana-labs/solana/pull/25464#issuecomment-1142598915). I hope to create another PR with the benchmark code as a follow-up.
This will be the last set of instructions to be added to the proof program for token-2022.
Fixes #
> [zk-token-sdk] Add `VerifyGroupedCiphertext2HandlesValidity` and `VerifyBatchedGroupedCiphertext2HandlesValidity` proof instructions

- runtime/src/tiered_storage/byte_block.rs
Support Lz4 in ByteBlockWriter.
Added test cases for Lz4.
Tested in mnb w/ the prototype implementation of the tiered storage (#30626)
> [TieredStorage] Support Lz4 in ByteBlockWriter (2/N)

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/meta.rs
This PR implements AccountMetaFlags, which will later be used in
the tiered accounts storage to support optional fields.
> [TieredStorage] AccountMetaFlags

- zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u128.rs
- zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u256.rs
- zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u64.rs
- zk-token-sdk/src/instruction/range_proof.rs
- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/instruction/withdraw.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
- zk-token-sdk/src/zk_token_elgamal/pod/range_proof.rs
The zk-token-proof instruction name for 64-bit range proof has bee updated to `VerifyRangeProofU64`, but the zk-token-elgamal pod types for range proof is still `RangeProof64`.
Change type names `RangeProof{64, 128, 256}` to `RangeProofU{64, 128, 256}`.
This is a follow-up to https://github.com/solana-labs/solana/pull/31855#discussion_r1210449561.
Fixes #
> [zk-token-sdk] Rename `RangeProof{64,128,256}` to `RangeProofU{64,128,256}`

- programs/loader-v4/Cargo.toml
solana-runtime needs solana-loader-v4-program for crates publishing
https://github.com/solana-labs/solana/blob/4353ac67975d917d57392ffe9c1580e00567801b/runtime/Cargo.toml#L53
publish loader v4 program
> ci: make loader v4 program publish = true

- program-runtime/src/loaded_programs.rs
- runtime/src/bank.rs
The cache stats are monotonically increasing, since the same cache object is being shared for all banks. This makes it hard to compare the stats with previous implementation. Also, the stats will eventually rollover.
Reset the stats when a new bank in created, after submitting to the database.
Fixes #
> Reset program cache stats after submit

- runtime/src/snapshot_utils.rs
The measurement is later logged, so include a name to more clearly identify what the measurement was.
For example, the current pair of logs for creating this snapshot is as follows, noting that there is nothing before `took` in the second log.
```
[2023-06-01T03:04:10.287058361Z INFO  solana_runtime::snapshot_utils]
Creating bank snapshot for slot 197099927, path: /home/sol/ledger/snapshot/197099927/197099927.pre
[2023-06-01T03:04:26.324303651Z INFO  solana_runtime::snapshot_utils]  
took 7.5s for slot 197099927 at /home/sol/ledger/snapshot/197099927/197099927.pre
```
> chore: Add name string for bank_serialize measure!

- Cargo.lock
- Cargo.toml
- program-runtime/src/invoke_context.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v4/src/lib.rs
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
[solana_rbpf v0.5.0](https://github.com/solana-labs/rbpf/releases/tag/v0.5.0) was released.
- Some bug fixes for the new ELF parser.
- Renames `BuiltIn` to `Builtin` for consistency.
> Bump solana_rbpf to v0.5.0

- programs/address-lookup-table/src/processor.rs
- programs/bpf_loader/src/lib.rs
- programs/compute-budget/src/lib.rs
- programs/config/src/config_processor.rs
- programs/loader-v4/src/lib.rs
- programs/stake/src/stake_instruction.rs
- programs/system/src/system_processor.rs
- programs/vote/src/vote_processor.rs
- runtime/src/block_cost_limits.rs
builtin programs compute units are defined in two places: runtime/src/block_cost_limits.rs and at runtime for each program. This potentially introduces inconsistency. Should define builtin program's CU at one place.
- add `pub const DEFAULT_COMPUTE_UNITS` for each program,
- update block_cost_limit to use builtin cost defined in program itself. 
Fixes #
> use one definition of builtin program cost in runtime and banking stage

- Cargo.lock
- programs/sbf/Cargo.lock
zeroize_derive 1.2.0 has been yanked. (https://crates.io/crates/zeroize_derive/versions)
bump it to 1.4.2
---
perf test
```
mean_tps: 28137
max_tps: 97743
mean_confirmation_ms: 979
max_confirmation_ms: 7805
99th_percentile_confirmation_ms: 4732
max_tower_distance: 47
last_tower_distance: 31
slots_per_second: 2.699
```
> chore: bump zeroize_derive to 1.4.2

- rpc/src/cluster_tpu_info.rs
- send-transaction-service/src/send_transaction_service.rs
- send-transaction-service/src/tpu_info.rs
Fixing send-transaction-service using quic, tpu address is wrong (using the udp address not quic address) when transaction is retried
Get tpu address for quic when connection is quic based.
Fixes #
https://github.com/solana-labs/solana/issues/31898
> Fixing send-transaction-service using quic, tpu address is wrong

- program-runtime/src/invoke_context.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v4/src/lib.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
The program usage counter is based on usage in instructions. This causes programs to get evicted/unloaded which are referenced in a transaction, but not called by an instruction. This results into unnecessary unloading/reloading of such programs.
- Track usage of a program cache entry by how many transactions loaded it
- Update eviction logic to use the new counter
Fixes #
> Evict program cache using transaction usage counter

- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
This is a preparation for #31945.
When a program is unloaded, it's loader configuration is dropped. The configuration is useful to check if program needs re-verification when it is reloaded. If the configuration (e.g. feature set) has been modified, the program must be re-verified.
Retain the configuration as part of `Unloaded` variant.
Fixes #
> Retain runtime environment config for unloaded programs

- .github/workflows/release-artifacts-auto.yml
- Cargo.lock
- Cargo.toml
It's been awhile we _temporarily_ stopped Windows build due to incompatibility between one of transitive deps (`ntapi`) and the solana monorepo's rust toolchain version (v1.69)....:
https://github.com/solana-labs/solana/pull/31353
https://github.com/solana-labs/solana/pull/31893
Unfortunately, it's not easy to update to `ntapi v0.4.x` (which contains a fix for the incompatibility), due to its being middle of our gigantic dep. graph (beneath our somewhat outdated `tokio`...). On top of ti, the crate maintainer hasn't been responsive with regard to backporting the fix into `v0.3.x`.
Patch `ntapi`: https://github.com/solana-labs/ntapi/commit/5980bbab2e0501a8100eb88c12222d664ccb3a0a : 
```
~/work/ntapi$ git diff --no-index /home/ryoqun/.cargo/registry/src/github.com-1ecc6299db9ec823/ntapi-0.3. …
```
> Patch ntapi to restore windows build

- Cargo.toml
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- scripts/cargo-install-all.sh
We needed more tender and loving care for patching `ntapi`, still breaking windows build after #31961 
patch moar!
(i'll create a proper pr at the spl-token repo...)
Fixes #
> Patch ntapi more thoroughly

- docs/src/api/websocket/_signatureSubscribe.mdx
for the `signatureSubscribe` websocket method, the docs do not give details on:
- the `enable_received_notification` config param
- the `receivedSignature` notification type
added documentation and clarification on the websocket method
Fixes #24558
> [docs] `signatureSubscribe` websocket

- core/src/lib.rs
- core/src/tpu.rs
- core/src/tpu_entry_notifier.rs
An alternative to #31889
https://github.com/solana-labs/solana/pull/31290 adds an entry notification service, which is currently only fed from the Tvu pipeline. But leaders should also support geyser entry notifications -- this is especially useful for testing plugins on solana-test-validator, since the TestValidator is the leader for every slot.
Adds a little service to sit between PohRecorder and BroadcastStage in the Tpu pipeline. If geyser entry notifications are supported, the entry summary information is copied from the message and sent to the entry notification service. All entries are passed through unchanged to the BroadcastStage receiver.
Differs from #31889 in that entry indexes are tracked in the TpuEntryNotifier instead of PohRecorder.
Closes #31889
> Send messages to EntryNotifierService in Tpu, simpler

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- scripts/cargo-install-all.sh
the solana git _repo_ and published spl _crate_ are using different versions of `ntapi`, which is troubling consistent `[patch]`-ing. the repo had been pinning to v0.3.6 via Cargo.locked. but the published spl _crate_ is specifying `v0.3.x` and resolved to latest one: `v0.3.7`
Just use same version, restoring `--locked`.
so, this effectively bumps monorepo's ntapi from v0.3.6 to v0.3.7, which seems to contain only small changes:
https://github.com/MSxDOS/ntapi/compare/cbea31ea9d624169f01ae0997e6698baceb51867...3a0063ad916e5f0c6972ab53e025689b9f0f92ad according to:
```
$ git diff --no-index ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntapi-0.3.{6,7}/.cargo_vcs_info.json
diff --git a/home/ryoqun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntapi-0.3.6/.cargo_vcs_info.json …
```
> Bump patched ntapi from v0.3.6 to v0.3.7

- metrics/metrics-main/kapacitor.sh
seems that we assign `KAPACITOR_USERNAME` twice.
> ci: fix env name

- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/syscalls/mod.rs
- runtime/src/bank.rs
The cached `program_runtime_environment` and all programs compiled against it can become outdated when a feature which involves the RBPF config is activated.
- Call `create_program_runtime_environment()` in `Bank::apply_builtin_program_feature_transitions()`.
- Adds `LoadedPrograms::prune_feature_set_transition()`.
This PR does only ensures that the cache does not contain any outdated entries after the feature transition, it does not recompile them before the epoch boundary hits.
> Feature - Prune on feature set transition

- core/src/broadcast_stage/standard_broadcast_run.rs
Continue Merkle shreds rollout off last one: https://github.com/solana-labs/solana/pull/28905
Roll out merkle shreds to ~50% of testnet
> rolls out merkle shreds to ~50% of testnet

- runtime/src/cost_model.rs
`CostModel` processes compute_budget instructions when calculates transaction's cost. If `process_instructions()` fails, `CostModel` would know the transaction will [not be executed by bank](https://github.com/solana-labs/solana/blob/8fbada42f947570bbb606385668f03af070d1e3c/runtime/src/bank.rs#L4591-L4609), therefore it should set transaction's execution cost to zero. This helps to improve block packing accuracy. 
- check `ComputeBudget::process_instructions()` result, setting execution costs to zero if `Err`
Fixes #
> Will failed transaction should be considered has zero execution cost by cost model

- streamer/src/quic.rs
Client IP control is verified later in the handshake than it could be
Use QUIC Retry packets to challenge clients' control over their IP upfront
> Use QUIC Retry packets during handshake

- quic-client/src/lib.rs
`QuicConfig` isn't really optional and allowing it to be `None` results in misconfigured connections.
Removed `Option`.
> removes Option wrapper from QuicConfig in QuicConnectionManager

- bench-tps/src/bench_tps_client/tpu_client.rs
- client/src/connection_cache.rs
- client/src/nonblocking/tpu_client.rs
- client/src/tpu_client.rs
- connection-cache/src/connection_cache.rs
- quic-client/src/lib.rs
- thin-client/src/thin_client.rs
- tpu-client/src/nonblocking/tpu_client.rs
- tpu-client/src/tpu_client.rs
- udp-client/src/lib.rs
Working towards removing hard-coded TPU specific configurations from QUIC code; NewConnectionConfig is redundant and gets in the way.
Removed `NewConnectionConfig`.
> removes redundant NewConnectionConfig trait

- ledger-tool/src/program.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v4/src/lib.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
The programs that failed verification could succeed after a certain runtime feature has been activated. Currently, cache does not store the runtime environment that was used when the program failed to verify/compile. It's needed to check if the re-verification should be triggered for the failed program. 
Retain environment for FailedVerification tombstones.
Fixes #
> Add runtime environment to FailedVerification tombstones

- sdk/src/transaction/sanitized.rs
The function signature was changed in #31767, but these instances were not updated due to the PR being created before the instances were added to the repo.
Get build working
> Fixup missed instances of SanitizedTransaction::try_create()

- runtime/src/tiered_storage/meta.rs
AccountMetaFlags and its fields are required to be public as the visibility of their get
functions generated by `bit_fields` are tied to the visibility of their fields, and the
get functions will later be used to support the TieredAccountMeta for AccountMeta.
Make AccountMetaFlags and its fields public
> [TieredStorage] Make AccountMetaFlags and its fields public

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/genesis_utils.rs
The epochs for this transition code have long passed, so it can be cleaned up.
See https://github.com/solana-labs/solana/pull/13461#issuecomment-1560981002 .
Removes `Bank::reconfigure_token2_native_mint()`.
> Cleanup - `Bank::reconfigure_token2_native_mint()`

- runtime/src/bank.rs
- runtime/src/lib.rs
- runtime/src/serde_snapshot/tests.rs
- runtime/src/stake_rewards.rs
Move `StakeReward` to its own file for later use and to simplify `bank.rs`.
Fixes #
> move StakeReward to stake_rewards.rs

- poh/src/poh_recorder.rs
`record()` called from BankingStage panics on potential `SendError`'s bubbled up on send in `PohRecorder::record()` between `PohService` and `BankingStage`
Return `MaxHeightReached` instead of panicking because `BroadcastStage` has exited and all further record will fail. BankingStage will then exit on the next iteration of fetch from `Sigverify` because that channel will be disconnected as well because the `exit` flag is set
Fixes #
> Fix panic in record()

- quic-client/src/lib.rs
`QuicConnectionManager::new_connection_config` is returning an invalid new `QuicConfig` instead of the value it is initialized with.
Return `self.connection_config` instead of a new `QuicConfig`.
> patches QuicConnectionManager::new_connection_config

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/cost_model.rs
- runtime/src/transaction_cost.rs
There is cost associated with amount memory space transactions request to load accounts into. #30659 formulated cost into CUs for base fee calculation. Can use same formula in cost model, also behind `include_loaded_accounts_data_size_in_fee_calculation` feature gate
- Add `loaded_accounts_data_size_cost` to cost_model. When feature gate `include_loaded_accounts_data_size_in_fee_calculation` is activated, additional CUs for loaded_accounts_data_size will be contributed to overall transaction cost;
Note: Behind feature Gate Issue #30657
> include cost of transaction's requested loaded accounts size in cost model

- runtime/src/tiered_storage/meta.rs
This PR introduces AccountMetaOptionalFields, the in-memory struct for
handling optional fields.
More functions will be added in separate PRs.
This PR depends on #32004 (a small PR).
Tested in mnb w/ the prototype implementation of the tiered storage (#30626).
> [TieredStorage] AccountMetaOptionalFields (1/N)

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
When we eliminate rewrites, we will not identify dead slots in the same way anymore. The ancient append vec code will squash these dead slots. This will change the pattern of how we update root stats (such as # of alive_roots). Furthermore, we are often removing multiple dead slots in serial. We only need the stats at the end.
Today, we end up with stats like this, which is not ideal. We would like to see a better sampling of the stats:
Separate out removing root from updating stats.
Update the stats after each clean, whether we found dead slots or not.
As a nice side effect, we hold the write lock on `roots_tracker` for less time.
Fixes #
> simplify clean_dead_slot, factor out root stats

- runtime/src/ancient_append_vecs.rs
The[ append ancient append vec code](https://github.com/solana-labs/solana/blob/7cea6dd57cf9ec73b0a997ed4b355aa212226f1b/runtime/src/accounts_db.rs#L4608-L4609) removed append vecs that were combined from the shrink candidate list. We need to do the same thing when packing ancient append vecs.
Remove append vecs packed into ancient append vecs from `shrink_candidate_slots`. These slots have already been shrunk.
Fixes #
> remove packed ancient append vec from shrink candidate list

- runtime/src/ancient_append_vecs.rs
`ancient_append_vec.rs` has `#[allow(dead_code)]` on many places that are now used.
Remove `#[allow(dead_code)]`
> Removes #[allow(dead_code)] from ancient_append_vecs.rs

- runtime/src/snapshot_utils.rs
- validator/src/main.rs
We stopped canonicalizing validator `account_paths` in #30645.
This causes [issues](https://discord.com/channels/428295358100013066/670512312339398668/1116426454041907321) if users specify `account_paths` which are symlinks, when we start to clean our account directories. The directory that the cleanup process deletes & recreates should be at the followed path, not the location of the link.
canonicalize the `account_paths` like we've always done.
Fixes #
> create and  canonicalize account_paths

- runtime/src/accounts_db.rs
- runtime/src/ancient_append_vecs.rs
improving testing of packed ancient append vecs
verify that packing append vecs drops the old ones correctly. This requires dealing with recycling.
Fixes #
> test ancient packing with recycling

- core/src/shred_fetch_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- gossip/src/cluster_info.rs
- net-utils/src/lib.rs
Working towards migrating turbine to QUIC.
Added QUIC receiver to shred-fetch-stage.
> adds quic receiver to shred-fetch-stage

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
Add `update_reward_history_in_partition`.
This is basically a copy of the existing fn right above this one: `update_reward_history`.
`update_reward_history` will be deleted once this feature is activated.
We cannot efficiently remove `StakeReward`s from a single partition, so we need to pass a ref to the current partition's rewards. Vote rewards would have been saved off earlier, so we'll never save vote rewards in the same code path.
Fixes #
>  add update_reward_history_in_partition

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
Add `calc_vote_accounts_to_store`.
Fixes #
> add calc_vote_accounts_to_store

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
The feature affects RBPF as it changes the set of valid syscalls, so it must be included in `FEATURES_AFFECTING_RBPF` as well.
- Adds `enable_alt_bn128_syscall` to `FEATURES_AFFECTING_RBPF`.
- Fixes `test_runtime_feature_enable_with_program_cache`.
> Fix - `enable_alt_bn128_syscall`

- runtime/src/accounts.rs
- runtime/src/cost_model.rs
Noticed the misusage of feature gate `use_default_units_in_fee_calculation` when working on another issue. This feature gate (#26785) was introduced to fix a hard-coded bug in `bank::calculate_fee()`, should only be used when calling `calculate_fee()`. 
`default_units_per_instruction` was enabled in mnb in epoch 327, all calls to `ComputeBudget::process_instructions()` should pass `true` to this parameter. 
The misusage corrected in this PR most likely resulting from copy/paste. Correcting should not have functional impact.
- use `true` for default_units_per_instruction instead of using  wrong feature gate status.
Fixes #
> correct feature gate use_default_units_in_fee_calculation usage

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
Add `store_vote_accounts_partitioned`.
Fixes #
> add store_vote_accounts_partitioned

- validator/src/main.rs
Validator crashes if you specify account shrink paths. Discord context: https://discord.com/channels/428295358100013066/670512312339398668/1117869012576129074
#29496 introduced hardlinking for account storages, which created an expected account directory structure. Account directories are expected to have a structure:
```
account_path
|
-----run/
|
-----snapshot/
```
appendvecs in directories that do not follow this structure will cause `get_account_path_from_appendvec_path` to return an `InvalidAppendVecPath`.
The validator ensures account paths follow this structure, but does not do so for account shrink paths.
Ensure correct account directory structure for account shrink paths.
I was able to replicate the bug by running a local node w/ account shrink paths. On the snapshot after …
> Bugfix: Account Shrink Paths must conform to account directory structure 

- core/src/serve_repair.rs
Signed repair requests are not required on all cluster types. Versions prior to 1.13.6 do not send signed repair requests. Once the cluster validator floor version is at least 1.13.6, repair requests should be required to be signed.
Remove `ClusterType` gating for signed repair requests.
Fixes #
> require repair request signature

- zk-token-sdk/src/instruction/transfer/encryption.rs
- zk-token-sdk/src/instruction/transfer/mod.rs
- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/grouped_elgamal.rs
- zk-token-sdk/src/zk_token_elgamal/pod/instruction.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
The `TransferAmountEncryption` used in the transfer instructions is defined as a struct that contains a Pedersen commitment and three decryption handles associated with the source, destination, and auditor public keys. It can be defined as a thin wrapper around the type `GroupedElGamalCiphertext` (https://github.com/solana-labs/solana/pull/31849).
- `03b9f01`: Defined the `TransferAmountEncryption` as a thin wrapper around `GroupedElGamalCiphertext`
- `4f52343`: Previously, `GroupedElGamalCiphertext<3>` implemented the `From` trait for `GroupedElGamalCiphertext2Handles`, but it should be `GroupedElGamalCiphertext3Handles`. This was a miss from a previous PR (https://github.com/solana-labs/solana/pull/31849) :pray:. Fixed it here.
- `3447f6c`: Defined the `Pod` version of …
> [zk-token-sdk] rename `TransferAmountEncryption` to `TransferAmountCiphertext` and define it as a wrapper around `GroupedElGamalCiphertext`

- zk-token-sdk/src/instruction/batched_grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/sigma_proofs/batched_grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/mod.rs
- zk-token-sdk/src/sigma_proofs/validity_proof.rs
- zk-token-sdk/src/transcript.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
- zk-token-sdk/src/zk_token_elgamal/pod/sigma_proofs.rs
The instructions `VerifyGroupedCiphertext2HandlesValidity` and `VerifyBatchedGroupedCiphertext2HandlesValidity` have been added to the proof program (https://github.com/solana-labs/solana/pull/31816). The actual sigma proofs that are used as proof data for these instructions are named `ValidityProof` and `AggregatedValidityProof`, which doesn't quite match with the proof program instructions.
- renamed type `ValidityProof` to `GroupedCiphertext2HandlesValidityProof`
- renamed type `AggregatedValidityProof` to `BatchedGroupedCiphertext2HandlesValidityProof`
- refactored the two types above into their own separate submodules
- updated function, variable, and test names accordingly
Fixes #
> [zk-token-sdk] Refactor ciphertext validity sigma proof and rename `ValidityProof` to `GroupedCiphertextValidityProof`

- zk-token-sdk/src/range_proof/inner_product.rs
- zk-token-sdk/src/sigma_proofs/batched_grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
- zk-token-sdk/src/transcript.rs
The (private) function names in the `transcript` module use shortened names. For example, `pubkey_proof_domain_sep`.
Update function names to use `separator` instead of `sep`. For example `pubkey_proof_domain_sep` --> `pubkey_proof_domain_separator`.
This is a follow-up to https://github.com/solana-labs/solana/pull/32040#discussion_r1227357628.
Fixes #
> [zk-token-sdk] Update transcript functions to use full names

- docs/src/api/websocket/_signatureSubscribe.mdx
The docs wording for websocket's `signatureSubscribe` are slightly unclear.
Reworded some words and updated links
Related: https://github.com/solana-labs/solana/pull/31841
> [docs] signatureSubscribe wording tweaks

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
add `calculate_stake_vote_rewards` for partitioned rewards
Fixes #
> add calculate_stake_vote_rewards for partitioned rewards

- gossip/src/contact_info.rs
- gossip/src/legacy_contact_info.rs
- validator/src/admin_rpc_service.rs
`const` socket-addr is stable since rust 1.69.0:
https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html
added `const SOCKET_ADDR_UNSPECIFIED`.
> adds const SOCKET_ADDR_UNSPECIFIED

- core/src/repair_service.rs
Repair slot min/max are collected for each repair type, but min/max across repair types are not uniformly reported.
- Add metrics for `WindowIndex`, `HighestWindowIndex`, `Orphan` repair request min/max slot values. Only report non-default values.
- Retain `repair-highest-slot` and `repair-orphan` values for continuity with existing metrics. These data points can eventually be removed.
- Remove `repair-total` metric. This metric is the sum of existing `shred-count`, `highest-shred-count`, and `orphan-count` values.
Fixes #
> rationalize repair type min/max metrics

- runtime/src/bank.rs
pass `bank.get_reward_interval()` to load_accounts. Prior to feature activation, `bank.get_reward_interval()` will only be `RewardInterval::OutsideInterval`, which is the default no-op behavior that exists today.
Fixes #
> pass get_reward_interval to load_accounts

- core/src/cluster_info_vote_listener.rs
- core/src/verified_vote_packets.rs
Previously we were using the working bank to access the feature set. This only works while we are leader, but we start sending gossip votes to banking stage slightly before we are leader.
Instead use the root bank from bank forks to access feature set. 
Fixes #
> bank_send_loop: Get feature flag from root bank

- runtime/src/bank.rs
- runtime/src/epoch_rewards_hasher.rs
add `calculate_rewards_for_partitioning`
This ties together many previous prs to get the result of rewards calculation.
Fixes #
> add calculate_rewards_for_partitioning

- runtime/src/bank.rs
add `compare_with_partitioned_rewards`
This fn will be called when a test cli arg is passed to a validator. (`--partitioned_epoch_rewards_force_enable_single_slot`)
Normal rewards code will run, then this code will be run to make sure that both methods produce the same set of stake and vote account changes.
Fixes #
> add compare_with_partitioned_rewards

- runtime/src/bank.rs
partitioned epoch rewards will be a feature at some point. It is unwise to create a feature id until the feature is ready to be activated. In the meantime, it is convenient to have a constant fn which can be called to determine if the feature has been activated. Returning a constant `false` allows existing code to run as-is. When the feature is added, the impl of this fn can be filled out.
add `partitioned_rewards_feature_enabled`
Fixes #
> add partitioned_rewards_feature_enabled

- cli/src/program.rs
I think there is an issue with the deploy command. It does not compute correctly the minimum balance required for deploying the program.
1. Try and deploy a program with an empty account.
```
Error: Account D7GiatJ4KwZ6WmuBLkACyyY9FNs4txdPZWMnAnpbRzYU has insufficient funds for spend (1.41881688 SOL) + fee (0.00103 SOL)
```
2. Airdrop the necessary amount
```solana airdrop 1.42```
3. Redeploy the program
```
Error: Deploying program failed: Error processing Instruction 1: custom program error: 0x1
```
> Fix minimum balance when deploying program

- runtime/src/bank.rs
During normal beginning of epoch reward calculation and distribution, we can calculate rewards to stake and vote accounts using the partition code. We can then compare the partitioned reward expectations with what is about to be applied to stake and vote accounts.
This can be accomplished in tests by setting (which is on by default for all tests):
https://github.com/solana-labs/solana/blob/a44b080b7f5009150519b0228eb8b1ecbc69aed2/runtime/src/accounts_db.rs#L481
or by the validator cli argument:
`--partitioned-epoch-rewards-compare-calculation`
such that a running validator compares the results.
This costs time to the validator, but has no other …
> optionally compare with partitioned rewards

- runtime/src/bank.rs
When running a validator with the debug cli argument `--partitioned-epoch-rewards-force-enable-single-slot`,
we need to not include the zero-ed out epoch reward sysvar in the delta hash of the bank. If we include it, the bank hash will never match the non-activated feature bank hash.
optionally ignore the sysvar account in delta hash if we're testing the new rewards calculation against a cluster where the feature is not activated.
This code will have no effect unless the cli arg is passed.
Note the sysvar account will have zero lamports if the functionality works correctly, but even having the zero lamport sysvar account in the delta hash will …
> in testing, hash_internal_state ignores epoch_rewards_sysvar

- runtime/src/bank.rs
add `distribute_epoch_rewards_in_partition`
update reward history, update cap, store stake accounts
Fixes #
> add distribute_epoch_rewards_in_partition

- bench-tps/src/bench.rs
#31905 includes CU cost of transaction's loaded_accounts_data_size to cost model. Mentioned [here](https://discord.com/channels/428295358100013066/1031929516383281154/1116747787070079026), if transaction does not explicitly use `ComputeBudgetInstruction::set_loaded_accounts_data_size_limit()` to set accounts data limit, the default 64M (chosen to not to break any existing mainnet-beta programs) will be used. Applying same heap cost (eg 8cu per 32K), that'd add 16K CU to each Transfer transaction, quickly fill up block CU limit, reduce tps.
- Add `ComputeBudgetInstruction::set_loaded_accounts_data_size_limit(30 * 1024)` to Transfer transaction.
tested and confirmed on single node cluster.
Fixes #
> set Transfer transaction loaded_accounts_data_size in bench-tps

- runtime/src/bank.rs
When running a validator with the debug cli argument `--partitioned-epoch-rewards-force-enable-single-slot`,
we need to run some partitioned rewards code even though the feature is not enabled.
add `partitioned_rewards_code_enabled`
which returns: true if the feature is activated or `--partitioned-epoch-rewards-force-enable-single-slot`
This code will have no effect unless the cli arg is passed (or feature is activated).
Fixes #
> add is_partitioned_rewards_code_enabled

- bench-tps/src/bench.rs
Should #31469 lands, bench-tps needs to set `compute-unit-price` at 1_000 microlamports incremental. Can update bench-tps now.
- add multiplier 1_000 to compute-unit-price when used
Fixes #32079
> bench-tps add 1_000 as multiplier to compute-unit-price

- runtime/src/bank.rs
see #32114 or the other end of this pr.
The partitioned reward status goes from inactive to active and back to inactive.
Active is the state while we are distributing rewards to stake accounts, some per block.
We need a method to begin the period when are actively distributing rewards.
This will be called on the first block of a new epoch.
Later, this will also create the sysvar.
add `begin_partitioned_rewards`
Fixes #
> add begin_partitioned_rewards

- .buildkite/hooks/post-checkout
there's a hack in our buildkite post-checkout hook that blindly attempts to `cargo uninstall` some bin crates that may not actually be installed.  when they aren't, a misleading error is printed prominently, which frequently distracts from the true cause of a failed ci job.
swallow all `cargo uninstall` output in the buildkite post-checkout hook
> ci: discard misleading `cargo uninstall` errors in bk post-checkout hook

- cli-output/src/cli_output.rs
id like to use `OutputFormat` as a cli arg for a clap v3 cli like so:
```
/// Return information in specified output format
#[clap( 
global(true),
long = "output",
id = "FORMAT",
value_parser = PossibleValuesParser::new(["json", "json-compact"]).map(|o| parse_output_format(&o)),
)]
pub output_format: Option<OutputFormat>,
```
but this requires `Clone`
derive `Clone`
> derive Clone for OutputFormat in cli-output

- runtime/src/bank.rs
sysvar changes were happening in parallel to accounts work.
sysvar changes are now in.
Time to start hooking up the sysvar to be used in its proper place in the partitioned rewards distribution.
Add some partition fns which work with the sysvar.
Fixes #
> add partitioned rewards sysvar fns

- sdk/src/signer/signers.rs
we routinely use `Arc<dyn Signer>` in spl command line utilities, but without fixed-length impls for the `Signers` trait we have to do silly things like `&vec![payer]` or `&[&*payer]` to find a trait impl when passing signers to `Transaction` signing functions
impl for arrays, letting us do `&[payer]`
> impl Signers for Arc<dyn Signer> arrays

- runtime/src/bank.rs
sysvar changes were happening in parallel to accounts work.
sysvar changes are now in.
When deactivating the reward interval, burn the sysvar correctly.
Fixes #
> deactivate_epoch_rewards_status burns sysvar

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
When partitioned epoch rewards are enabled, each block may need to store some stake account rewards.
add `distribute_partitioned_epoch_rewards`
to distribute the epoch rewards to this block/partition
Fixes #
> add distribute_partitioned_epoch_rewards

- core/src/consensus.rs
- core/src/replay_stage.rs
Follow up to the change #31879, now that we use vote tx timestamp as a tiebreaker in the vote queue deduplication logic, send a different timestamp everytime we refresh a vote.
On refresh increment the timestamp by 1 (using the time of refresh has potential to break the Timestamp Oracle). If the previous vote didn't have a timestamp try to estimate as best as possible. 
Fixes #
> Increment timestamp on refreshed votes

- bench-tps/src/bench.rs
The most common usage for bench-tps is a development cluster, which has all features enabled.
Update bench-tps tests to use a bank w/ all features enabled.
Fixes #
> bench-tps tests use bank w/ all features enabled

- bench-tps/src/bench.rs
- bench-tps/src/send_batch.rs
We must specify the data limit on the funding transactions otherwise funding takes longer.
Add data limit on funding transactions
Fixes #
> Funding transactions must specify data limit

- runtime/src/bank.rs
sysvar changes were happening in parallel to accounts work.
sysvar changes are now in.
create sysvar in `begin_partitioned_rewardsbegin_partitioned_rewards`
Fixes #
> update begin_partitioned_rewards to include sysvar

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
We need to consistently have access to and use total # stake rewards as opposed to # of blocks stake rewards are partitioned into.
The math in `distribute_partitioned_epoch_rewards` was asserting based on # partitioned blocks as opposed to total # of stake rewards.
rework fn to use the right values.
Fixes #
> cleanup math in distribute_partitioned_epoch_rewards

- zk-token-sdk/src/instruction/transfer/encryption.rs
- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/instruction.rs
The `FeeEncryption` used in the transfer with fee instruction is defined as a struct that contains a Pedersen commitment and two decryption handles associated with the destination and withdraw withheld authority public keys. Instead, it can be simplified to be a thin wrapper around the type `GroupedElGamalCiphertext`.
Define the `FeeEncryption` to be a thin wrapper around the type `GroupedElGamalCiphertext`.
This is a follow-up to https://github.com/solana-labs/solana/pull/32026. It would be nice to rename `FeeEncryption` to `FeeCiphertext` as was done in https://github.com/solana-labs/solana/pull/32026 for `TransferAmountEncryption`, but unfortunately, this breaks downstream. We can perhaps update it in a future PR.
Fixes #
> [zk-token-sdk] Define `FeeEncryption` as a wrapper around `GroupedElGamalCiphertext`

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
As described in the following PR comments,
https://github.com/solana-labs/solana/pull/32164#issuecomment-1593806091, pass
the total number of rewards to the reward number of block computationn function
doesn't enforce the correct number of total rewards when the underlying data strucutre changes.
In this example, the calculated rewards data structure has been refactored from
`Vec<Rewards>` into `Vec<Vec<Rewards>`, and the compiler won't catch this type
change at the number of blocks computation function. 
Refactor to Pass Vec<Rewards> to number of blocks computation function.
Fixes #
> Refactor reward block calculation fn

- sdk/src/feature_set.rs
Add epoch reward feature id
Feature Gate Issue: #32166
> Add epoch reward feature id

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
https://github.com/solana-labs/solana/pull/32158 will enable epoch reward feature for stake tests. Therefore, the stake tests update for epoch reward features should go in together with 32158. 
This reverts commit d06b099ecb40e22cdfc65946dd2a4ad0054ff0ce.
We will do #32158 again with update of stake tests together.
Fixes #
> Revert "add test for is_partitioned_rewards_feature_enabled (#32158)"

- runtime/src/bank.rs
- runtime/src/serde_snapshot/tests.rs
Make fn signature and members be clear that field is grouped by partition.
rename
Fixes #
> rename to stake_rewards_by_partition for clarity

- zk-token-sdk/src/instruction/transfer/mod.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/instruction.rs
Currently, the `FeeParameters` type in the zk-token-sdk instruction module contains manual byte conversion `to_bytes` and `from_bytes`. There already exists `Pod` conversions between decoded and pod `FeeParameters` in `zk-token-elgamal` and hence these manual conversions can be removed for simplicity.
- Removed manual byte conversions `to_bytes` and `from_bytes` for the `FeeParameters` type
- Refactored `Pod` conversions betweenn the decoded and non-decoded `FeeParameters` types that existed in the `convert` submodule to the `instruction` submodule where the pod `FeeParameters` type is defined. This is now in-line with how the other the pod types and conversion logic are structured in `zk-token-elgamal`.
Fixes #
> [zk-token-sdk] Refactor pod `FeeParameters` conversion and remove manual byte conversion for the type

- program-runtime/Cargo.toml
I noticed in https://github.com/solana-labs/solana/pull/32028/files that the `solana-program-runtime` crate is using a specific version of serde for no reason I can intuit (it is the same version as specified in the workspace).
Use workspace serde
> Use workspace serde dependency in program-runtime

- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/zk_token_elgamal/convert.rs
- zk-token-sdk/src/zk_token_elgamal/pod/instruction.rs
- zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
The struct `TransferPubkeys` and `TransferWithFeePubkeys` in the `instruction::transfer` module exist to group the ElGamal public keys needed in a transfer instruction (`source_pubkey`, `destination_pubkey`, ...). However, this struct is not very useful:
The constructors for `TransferData` and `TransferWithFeeData` take in the individual ElGamal public keys as input, groups them into a `TransferPubkeys` and `TransferWithFeePubkeys`, and then immediately converts them to their `Pod` variants.
The verification functions does take in the types `TransferPubkeys` and `TransferWithFeePubkeys` as input, but they invoke the sigma or range proof verification functions with the individual public keys.
The code can be quite simplified by just removing the non-`Pod` types `TransferPubkeys` and …
> [zk-token-sdk] remove non-pod structs `TransferPubkeys` and `TransferWithFeePubkeys`

- cli/tests/stake.rs
- program-test/src/lib.rs
- program-test/tests/warp.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/tests/stake.rs
Implementing solana-foundation/solana-improvement-documents#15 (comment) in pieces.
redo: https://github.com/solana-labs/solana/pull/32158
Enable partitioned epoch reward by feature id
1. enable partitioned epoch reward by feature id
2. update relevant stake tests after enable partitioned epoch rewards feature.
Fixes #
> Enable partitioned epoch reward by feature id

- core/src/consensus.rs
No visibility when timestamps are missing
Add metrics:
* When clock error results in not sending a timestamp
* When refreshing a vote with no original timestamp
Normal refresh vote with timestamp can be derived from the existing metric "refresh_vote" and subtracting "refresh-timestamp-missing"
Fixes #
> Add metrics for invalid vote timestamps

- program-runtime/src/sysvar_cache.rs
- runtime/src/bank/sysvar_cache.rs
Implementing https://github.com/solana-foundation/solana-improvement-documents/pull/15#issuecomment-1545187348 in pieces.
depends on 
https://github.com/solana-labs/solana/pull/32158
Add epoch_rewards to sysvar_cache
Fixes #
> Add epoch_rewards to sysvar cache

- core/benches/retransmit_stage.rs
- core/src/broadcast_stage/broadcast_fake_shreds_run.rs
- core/src/serve_repair.rs
- core/src/shred_fetch_stage.rs
- core/src/tvu.rs
- core/src/validator.rs
- dos/src/cli.rs
- dos/src/main.rs
- gossip/src/cluster_info.rs
- gossip/src/contact_info.rs
- gossip/src/legacy_contact_info.rs
- gossip/tests/gossip.rs
- validator/src/admin_rpc_service.rs
- validator/src/bootstrap.rs
- validator/src/main.rs
Shreds are no longer sent to `tvu_forward`.
Removed outdated `tvu_forward` socket.
> removes outdated tvu_forward socket

- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/pedersen.rs
Currently, the `Scalar` and `RistrettoPoint` components of the `PedersenOpening` and `PedersenCommitment` types have visibility `pub(crate)` while each of these types have getters to access the inner types.
- Make the inenr `Scalar` and `RistrettoPoint` components in these structs be fully private
- For places that accesses these inner components directly, update them so that they use the specific getter function
Fixes #
> [zk-token-sdk] Make inner scalar and ristretto point of `PedersenOpening` and `PedersenCommitment` private

- zk-token-sdk/src/encryption/auth_encryption.rs
Currently, the fields `Nonce` and `Ciphertext` component of the `AeCiphertext` type are public. But these components should never really be used independently in any downstream projects.
Updated these fields to private fields.
Fixes #
> [zk-token-sdk] Make `AeCiphertext` inner fields be private

- Cargo.lock
- programs/sbf/Cargo.lock
- zk-token-sdk/Cargo.toml
- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/fee_proof.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/mod.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
`arrayref` is used throughout the `zk-token-sdk`. However, the need for `arrayref` should be largely obviated by `TryFrom<&[T]>` for `&[T; N]`.
Removing `arrayref` from `zk-token-sdk` has the following benefits:
- `arrayref` requires that we suppress `clippy::integer_arithmetic`. Unchecked Integer arithmetic should really be removed from `zk-token-sdk`, so removing `arrayref` is a necessary step.
- `arrayref` does not play nicely with constant variables and requires hard-coded constants. Hard-coded constants should be remioved from `zk-token-sdk`, so removing `arrayref` is a necessary step.
- We want to minimize dependencies in general
Removed `arrayref` from `zk-token-sdk` and replaced it with using `TryFrom<&[T]>` for `&[T; N]`.
Fixes #
> [zk-token-sdk] Use `TryFrom<&[T]>` for `&[T]` instead of `arrayref`

- core/src/validator.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- program-test/src/lib.rs
- program-test/tests/sysvar_last_restart_slot.rs
- runtime/src/bank.rs
- sdk/src/hard_forks.rs
Callers could previously obtain a a lock to read/write HardForks from any Bank. This would allow any caller to modify, and creates the opportunity for inconsistent handling of what is considered a valid hard fork (ie too old).
This PR adds a function to Bank so consistent sanity checks can be applied; the caller will already have a Bank as that is where they would have obtained the HardForks from in the first place. Additionally, change the getter to return a copy of HardForks (simple Vec).
> Restrict access to Bank's HardForks

- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
- zk-token-sdk/src/zk_token_proof_program.rs
There are not much docs for the ZK Token proof program in the repo.
- Added docs to reference https://edge.docs.solana.com/developing/runtime-facilities/zk-token-proof
- Added note about requiring contexts state account to be pre-allocated
- For those that were missing, brief descriptions of the proofs were added
I think it would be nice to refactor/organized the modules `zk_token_proof_program.rs`, `zk_token_proof_instruction.rs`, `zk_token_proof_state.rs`, and `instructions` into a separate `proof_program` submodule that contains code relating to the proof program. There are some outstanding PRs that touch the `instruction` module, so I will do the refactor on a follow-up once these PRs are merged.
Fixes #
> [zk-token-proof] Update docs for the ZK Token proof program in `zk-token-sdk`

- core/src/replay_stage.rs
Right now when we dump a duplicate slot we dump all of the descendants of that duplicate slot from blockstore as well.
Instead we
1) Remove all descendants from bank forks and associated ancestor/descendant maps
2) Only if the descendant has a bank hash do we purge from blockstore (if it has a bank hash it must also be a duplicate)
3) Otherwise if no bank hash, just clear the dead flag so that it can be replayed once the parent is repaired
This saves us some rounds of repair, as descendants that are dead or unreplayed are not necessarily duplicate and don't need to be dumped. 
See #31313
> Only dump duplicate descendants in dump & repair

- programs/zk-token-proof-tests/tests/process_transaction.rs
- programs/zk-token-proof/benches/verify_proofs.rs
- zk-keygen/src/main.rs
- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/grouped_elgamal.rs
- zk-token-sdk/src/instruction/batched_grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/ciphertext_ciphertext_equality.rs
- zk-token-sdk/src/instruction/ciphertext_commitment_equality.rs
- zk-token-sdk/src/instruction/grouped_ciphertext_validity.rs
- zk-token-sdk/src/instruction/pubkey_validity.rs
- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/instruction/withdraw.rs
- zk-token-sdk/src/instruction/zero_balance.rs
- zk-token-sdk/src/sigma_proofs/batched_grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
- zk-token-sdk/src/zk_token_elgamal/decryption.rs
- zk-token-sdk/src/zk_token_elgamal/ops.rs
Currently, the fields `public` and `secret` in the type `ElGamalKeypair` are all public. This is somewhat unnatural and could also cause security issues since the `secret` component implements `Copy` allowing downstream to copy/clone the secret key in memory under the hood.
- Changed the `public` and `secret` fields in `ElGamalKeypair` to be private
- Added constructor for `ElGamalKeypair` and getters for its private fields
- Updated the rest of the repo for the new visibility
I referenced the interface for `Keypair` in the sdk. There, we have the interface
```
pub fn secret(&self) -> &SecretKey { ... } // returns reference to `SecretKey`
```
and
```
pub fn pubkey(&self) -> Pubkey { ...} // returns a copy of `Pubkey`
```
In this PR, I made both getters to return references to …
> [zk-token-sdk] Make `ElGamalKeypair` fields private

- ci/docker-rust/Dockerfile
docker image update at #32234 updated various other commands and `wasm-pack` introduced some compatibility issue:
```
+ wasm-pack --version
error: unexpected argument '--version' found
tip: a similar argument exists: '--verbose'
Usage: wasm-pack <--verbose...|--quiet|--log-level <LOG_LEVEL>> <COMMAND>
```
already reported to upstream: https://github.com/rustwasm/wasm-pack/issues/1308
Pin it for now.
Fixes #
> Fix wasm-pack

- ci/_
- runtime/src/bank.rs
echo-ing to stdout by `_` isn't desirable sometimes
Print to stderr. it seems this works.
Fixes #
> Make `ci/_` to print to stderr instead of stdout

- runtime/src/tiered_storage/meta.rs
This PR introduces TieredAccountMeta, a trait that allows different implementations
of the account meta for different tiers of the accounts storage.
This PR includes the mutator and getter methods for the common TieredAccountMeta
fields.  Functions that also work with the account data block will be in separate PRs.
> [TieredStorage]  TieredAccountMeta (1/N)

- runtime/src/tiered_storage/meta.rs
This PR adds AccountMetaOptionalFields::size_from_flags that takes
`&AccountMegaFlags` and returns the size of the AccountMetaOptionalFields
based on the input AccountMegaFlags.
This function is needed because the reader of the TieredAccountMeta
directly extract all the Some fields of AccountMetaOptionalFields
from its account block without constructing the AccountMetaOptionalFields
instance.
Improve existing unit tests that further verify the correctness of the function.
> [TieredStorage] AccountMetaOptionalFields::size_from_flags()

- streamer/src/nonblocking/quic.rs
The quic streamer run_server unnecessarily sleep. This can slow down processing connection in initializing state and build up memory pressure. We do not need it as we have already used timeout when doing
let timeout_connection = timeout(WAIT_FOR_CONNECTION_TIMEOUT, incoming.accept()).await;
Remove the unnecessary sleep.
Fixes #
> Remove a unnecessary sleep in run server

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/hot.rs
This PR introduces HotAccountMeta, the storage and in-memory struct of
the metadata struct for a hot account.
Also tested in mnb w/ the prototype implementation of the tiered account storage (#30626)
This PR depends on #32220 which introduces TieredAccountMeta.
> [TieredStorage] HotAccountMeta (2/N)

- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
The flag for #24669 is finally active on all networks, but its code is still present.
Remove the code!
Fixes #24669
> stake: Remove `stake_allow_zero_undelegated_amount` usage

- sdk/cargo-build-sbf/src/main.rs
Platform tools version is not very informative. Additional information about the version of Rust the tools are based on could be helpful.
Add a function that extracts the version of the rust compiler installed in the platform-tools and output the version for the `--version` command line option of cargo-build-sbf.
> Add base rust version to the output of cargo-build-sbf --version

- ci/test-stable.sh
- sdk/program/Cargo.toml
People are accidentally using unsupported versions of rust when building solana programs.
A recent notable occurrence of this is #32133, where people are trying to build solana-program 1.16.1 without installing the 1.16-version of the platform-tools. The resulting error is not obvious and hard to debug. With this patch instead they'll get an immediate error from `cargo` indicating they're using an unsupported rustc version
Fixes #32133
> Add rust-version field to solana-program to prevent the accidental use of unsupported platform-tools versions

- runtime/src/message_processor.rs
The tests in `message_processor` have dependency on `solana_runtime` due to `RentCollector.` It can be removed, since the tests are using it to get default `Rent`, which can be obtained using `Rent::default()`.
Updated the code to remove the dependency.
Fixes #
> Remove message_processor dependency on solana_runtime

- programs/stake/src/stake_state.rs
- runtime/src/bank.rs
The [credits_auto_rewind feature](https://github.com/solana-labs/solana/issues/24674) is active on all public clusters, but the gating logic is still present.
Remove it. Also follow cleaning orders for if-else
Closes #24674
> Clean up credits_auto_rewind feature

- zk-token-sdk/src/zk_token_proof_instruction.rs
Oops, we missed a typo in the ZK Token proof program instruction docs.
Fix
> [zk-token-proof] Fix doc typo

- Cargo.lock
- program-runtime/Cargo.toml
- program-runtime/src/lib.rs
- program-runtime/src/message_processor.rs
- runtime/src/bank.rs
- runtime/src/lib.rs
`MessageProcessor` could be moved down to `program-runtime` as it has no dependencies on runtime. 
Moved the code and updated imports and Cargo.
Fixes #
> Move message_processor to program-runtime

- core/src/accounts_hash_verifier.rs
- core/src/validator.rs
- core/tests/snapshots.rs
- local-cluster/tests/common/mod.rs
- runtime/src/snapshot_utils.rs
- validator/src/main.rs
Slot::MAX was used to specify that a type of snapshots should not be created; define a constant to be that value and reference the constant to have a single point of edit.
The naming felt a little awkward for this; I think what I came up with is passable but open to suggestions as well
> Add constant for disabled snapshot interval

- core/src/ancestor_hashes_service.rs
- core/src/repair_service.rs
- core/src/serve_repair.rs
- core/src/tower1_7_14.rs
- Unnecessary error conversions in core take dependencies on `core::result::Result`.
- Instances of crossbeam channel error handling not distinguishing between `RecvTimeoutError::Timeout` and `RecvTimeoutError::Disconnected`.
- Remove unnecessary error conversions.
- update crossbeam channel error handling.
Fixes #
> unnecessary error conversions in core

- runtime/src/tiered_storage/meta.rs
This PR adds getter functions to the TieredAccountMeta for accessing
optional fields and account data.
This PR only adds methods to a trait.  More tests will be included in the
follow-up PRs.
> [TieredStorage] getter functions for TieredAccountMeta

- local-cluster/tests/common/mod.rs
Use the is_snapshot_config_valid() helper function instead of repeated logic.
> Remove duplicate SnapshotConfig validation code

- core/src/cluster_info_vote_listener.rs
Current bank vote send metrics have a quirk in that the last leader slot (of 4) metrics are not reported until the next leader slot begins. This is because there is no working bank once we transition out of the last slot.
Report the last slot's metrics once we stop being leader.
> report last slot vote send metrics

- Cargo.lock
- programs/zk-token-proof-tests/Cargo.toml
- programs/zk-token-proof-tests/tests/process_transaction.rs
- programs/zk-token-proof/Cargo.toml
- programs/zk-token-proof/benches/verify_proofs.rs
- programs/zk-token-proof/src/lib.rs
- zk-token-sdk/src/instruction/fee_sigma.rs
- zk-token-sdk/src/instruction/mod.rs
- zk-token-sdk/src/zk_token_proof_instruction.rs
The fee sigma proof in the `sigma_proofs` module was not previously wrapped as a separate ZK Token proof program instruction, which was previously missed. Adding this instruction can simplify the logic in Token2022 when breaking up the proofs for the `TransferWithFee` instruction.
Added fee sigma proof instruction to the ZK Token proof program.
Fixes #
> [zk-token-sdk] Add fee sigma proof verification instruction

- zk-token-sdk/src/sigma_proofs/batched_grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/fee_proof.rs
- zk-token-sdk/src/sigma_proofs/mod.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
The docs in the `sigma_proofs` module could be added/improved.
- Updated the `new` and `verify` function docs with respect to the actions they take (follow-up to https://github.com/solana-labs/solana/pull/32040#discussion_r1227353595).
- Added brief description of how the fee sigma proof is generated
- Added a link to the ZK Token proof program docs
This PR touches docs only.
Fixes #
> [zk-token-sdk](docs) Update docs to include a brief description of how fee sigma proof is computed

- runtime/src/tiered_storage/byte_block.rs
This PR adds ByteBlockReader::read_type(), an util function that
reads the raw part of the input byte block at the specified offset
as type T.  This function will be later used by the hot storage.
Modified existing unit tests to use ByteBlockReader::read_type()
when the input byte block is properly aligned.
> [TieredStorage] ByteBlockReader::read_type

- ci/docker-rust/Dockerfile
we added a version lock for wasm-pack cuz they removed `--version` accidentally. A good news is that they brought it back in 0.12.1. (https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.1)
remove the wasm-pack version lock
> ci: remove wasm-pack version lock

- runtime/src/tiered_storage/hot.rs
This PR implements HotAccountMeta's getter functions for accessing
optional fields (e.g. rent_epoch, account_hash, etc) and account data.
A new unit test is included in this PR.
This PR depends on #32311 that adds functions for obtaining optional
fields offsets.
> [TieredAccountStorage] getter functions for HotAccountMeta

- core/benches/consumer.rs
- core/src/banking_stage/consumer.rs
- core/src/banking_stage/qos_service.rs
When feature `apply_cost_tracker_during_replay` is applied, transactions that are added to QoS but aren't executed or committed will never get removed. This will result in an overestimation of actual compute units used, resulting in smaller blocks.
Uncommitted or unrecorded transaction costs **always** remove costs. Costs are only updated if `apply_cost_tracker_during_replay` is applied
> Ensure that uncommitted transactions are always removed from QoS

- zk-token-sdk/src/encryption/auth_encryption.rs
- zk-token-sdk/src/encryption/discrete_log.rs
- zk-token-sdk/src/encryption/elgamal.rs
- zk-token-sdk/src/encryption/grouped_elgamal.rs
- zk-token-sdk/src/encryption/pedersen.rs
- zk-token-sdk/src/lib.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
- zk-token-sdk/src/sigma_proofs/fee_proof.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
- zk-token-sdk/src/sigma_proofs/mod.rs
- zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
- zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
- zk-token-sdk/src/zk_token_elgamal/pod/auth_encryption.rs
- zk-token-sdk/src/zk_token_elgamal/pod/elgamal.rs
- zk-token-sdk/src/zk_token_elgamal/pod/grouped_elgamal.rs
- zk-token-sdk/src/zk_token_elgamal/pod/pedersen.rs
- zk-token-sdk/src/zk_token_elgamal/pod/range_proof.rs
- zk-token-sdk/src/zk_token_elgamal/pod/sigma_proofs.rs
Throughout zk-token-sdk, there are many hard-coded constants, which make the code harder to read and maintain.
Use constant variables to replace hard-coded constants.
In the process, I updated/simplified the way serialization is done in the sigma module. Previously, direct indexing was used to update slices. Now, chunks iterator is used to update the slices.
The hard-coded constants in the `range_proof` module will be updated in a separate PR.
Fixes #
> [zk-token-sdk] replace hard-coded constants with constant variables

- gossip/src/crds_gossip_push.rs
A Push Fanout of 6 is too small, resulting in the following:
* slow message propagation
* sparse network
The key here is that by increasing push fanout, gossip is able to reach more nodes in fewer hops. The pruning logic then removes the redundant paths, leaving us with a more dense MST without significant overhead (in steady state). 
All numbers and claims below are based off of a simulated gossip framework here: [gossip-sim](https://github.com/gregcusack/gossip-sim)
Data from simulated gossip framework can be found here: [Grafana Dashboard
](https://internal-metrics.solana.com:3000/d/EO2GyD_4k/gossip-simulation?orgId=1&from=1687973935288&to=1687975889674&var-TimeWindow=1h&var-start_time_2=1687962090627912000&var-start_time=0)
* Increase `CRDS_GOSSIP_PUSH_FANOUT` from 6 to 9, while …
> Increase push fanout from 6 to 9

- runtime/src/bank.rs
- runtime/src/transaction_batch.rs
- `prepare_simulation_batch` requires `.clone()`-ing.
- its name isn't generic to be used by others (ref: #31239 )
- make it take refs; seems there's no practical merit of transferring the ownership into `TransactionBatch` in the hope of avoiding some internal cloning... Originally, i thought generic approach made sense: https://github.com/solana-labs/solana/pull/31239#discussion_r1211183825
- less is more. :)
- and rename it.
Fixes #
> Make prepare_simulation_batch() more usable

- core/src/validator.rs
- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
Several problems broken up by commits:
1. `LedgerCleanupService` cleaning while `Blockstore::scan_and_fix_roots()` is running could cause inconsistency between Blockstore columns. Namely, the root column could be out of sync with everything else is a slot is identified to have the root repaired, but `LedgerCleanupService` purges that slot before `Blockstore::set_roots()` gets called.
2. `solana-ledger-tool repair-roots` implements near identical logic as `Blockstore::scan_and_fix_roots()`
To address the numbered items above:
1. Hold lowest cleanup slot lock (reader) while function runs; will prevent cleanup but still allow other stuff (such as RPC reads)
2. Adjust `scan_and_fix_roots()` to work for both callers (`solana-validator` and `solana-ledger-tool`)
The broader goal here is to …
> Make Blockstore::scan_and_fix_roots() take optional start/stop slots

- programs/vote/src/vote_state/mod.rs
#27361 has been activated on all clusters
Remove the associated flag
Fixes #
> feature flag cleanup: vote_state_update_root_fix

- runtime/src/accounts_hash.rs
When calling `datapoint!()`, casts are unnecessary.
Remove casts.
> Removes unnecessary casts calling datapoint!

- sdk/src/signer/mod.rs
signers are equal when pubkeys are equal, and pubkey equality is total, but signer is only partial. total equality is required for iterator sort, which would be useful for deduplicating vectors of signers
this uses the default impl of Eq for dyn Signer
> impl Eq for dyn Signer

- runtime/src/tiered_storage/hot.rs
- runtime/src/tiered_storage/meta.rs
Function data_size_for_shared_block() is designed to provide
the data_size when its account shares its account block with
other accounts.  However, TieredAccountMeta already has another
function for returning data size.
This PR removes data_size_for_shared_block() from TieredAccountMeta.
Will follow-up with another PR that includes a better API.
> [TieredStorage] Make data_size related APIs cleaner

- turbine/src/broadcast_stage/standard_broadcast_run.rs
Ramping up Merkle shreds rollout as the results look good: https://github.com/solana-labs/solana/pull/31950#issuecomment-1611911159
Rolls out merkle shreds to 100% of testnet slots.
> rolls out merkle shreds to 100% of testnet slots

- local-cluster/src/local_cluster.rs
another small refactor for #31239 per https://github.com/solana-labs/solana/pull/31239#discussion_r1169869003
Fixes #
> Define ClusterConfig::new_with_equal_stakes()

- ci/docker-rust/Dockerfile
`jq` is missing...... T_T:
https://buildkite.com/solana-labs/solana/builds/98449#01890a36-b5e8-4438-8b4d-b81fb0a2bae7/3083-3084
add it
blocking #32169
> Install jq in docker

- runtime/src/tiered_storage/hot.rs
- runtime/src/tiered_storage/meta.rs
In TieredAccountMeta, it uses `data` and `account_data` to refer to
the data associated with the account, and this could be confusing.
This PR makes TieredAccountMeta only use `account_data` to refer
to the data associated with the account.
> [TieredStorage] Improve TieredAccountMeta API's readability

- sdk/cargo-build-sbf/src/main.rs
make a note here: this steps can reproduce the unexpected error
1. cd to monorepo
2. ./cargo-build-sbf --help
3. rm -rf ~/.cache/solana
4. ./cargo-build-sbf --help
check if rustc exists
(btw, feel free to just close this one and create a new one if you would like to refactor these code hehe)
> fix: check if platform-tool/rust/bin/rustc exists

- core/src/consensus.rs
- core/src/consensus/tower1_14_11.rs
- core/src/consensus/tower1_7_14.rs
- core/src/consensus/tower_storage.rs
- core/src/replay_stage.rs
Non voting validators or validators with unstaked identities in hotswap setups will never generate a tower blockhash, although they will continue adding votes to the tower. 
The default blockhash is expired, so this will prompt these validators to attempt to refresh their vote. Although they can't vote anyway this will print an extra `WARN` cluttering the log. 
Return early if blockhash is default.
Fixes #
> Don't attempt to refresh votes on non voting validators

- scripts/cargo-install-all.sh
We've released a new version of Solang and would like to update it in the installation script.
https://github.com/hyperledger/solang/releases/tag/v0.3.1
Changed the version number at `scripts/cargo-install-all.sh`.
> Update Solang Solidity compiler to v0.3.1

- sdk/sbf/c/inc/sol/alt_bn128.h
- sdk/sbf/c/inc/sol/inc/alt_bn128.inc
C SDK header files are generated by a special program. This program expects syscall declarations to be in a specific format. One of the input files for the gen-header program is in incorrect format.
Fix the input file and regenerate the corresponding header file.
> Fix alt_bn128 declarations as expected by gen-headers and regenerate

- Cargo.lock
- programs/sbf/Cargo.lock
- quic-client/src/nonblocking/quic_client.rs
- streamer/src/nonblocking/quic.rs
- streamer/src/quic.rs
- turbine/Cargo.toml
- turbine/src/lib.rs
- turbine/src/quic_endpoint.rs
Currently Turbine QUIC is tied to TPU implementation which makes it difficult to make changes without impacting TPU or optimize the code specifically for Turbine.
Working towards separating out Turbine QUIC from TPU, the commit adds a new QUIC endpoint implementation specific for turbine connections.
Compared to QUIC code for TPU, in this code:
* Same endpoint sends and receives packets from the same UdpSocket.
* Packets are sent as datagram instead of streams.
* Connection cache can use a different eviction policy from the TPU one.
This commit only adds the new endpoint constructs; following commits will:
* plumb through the endpoint channels to turbine code.
* implement some cache eviction policy.
* add metrics.
> adds QUIC endpoint specific for turbine connections

- ledger-tool/src/main.rs
- ledger/src/blockstore.rs
If a slot is marked as optimistically confirmed, it is probable but not
guaranteed that its' ancestors will also be marked as optimistically
confirmed in the Blockstore.
Given the importance of examining
optimistically confirmed slots around cluster restarts, manually walk
an AncestorIterator to avoid the chance of a slot improperly being
ignored in cluster restart scenarios.
Here is the output on a ledger I hacked up to only have `16903500` as optimistically confirmed (I inserted default values for hash and timestamp). Oh, and those slots are actually vote only so that logic is working 😄 
```
$ solana-ledger-tool latest-optimistic-slots --ledger ~/test_ledger/ --num-slots 3
[... WARN  solana_ledger_tool] Slot 16903499 is an ancestor of latest optimistically confirmed slot 16903500, but …
```
> ledger-tool: Manually walk optimistic slots ancestors

- Cargo.lock
- Cargo.toml
- ledger-tool/src/program.rs
- program-runtime/src/invoke_context.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v4/src/lib.rs
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- programs/sbf/benches/bpf_loader.rs
[solana_rbpf v0.6.0](https://github.com/solana-labs/rbpf/releases/tag/v0.6.0) was released.
Contains fixes for gapped stack memory and disabling that completely before account data direct mapping is activated. The feature gate for that is to follow in a separate PR.
> Bump solana_rbpf to v0.6.0

- perf/src/thread.rs
The test needs to be aware of is_niceness_adjustment_valid from super scope; however, the use directive in test module only runs on Linux systems via the attached `#[cfg(target_os = "linux")]` statement.
> Fixup is_niceness_adjustment_valid unit test for non-linux case

- sdk/program/Cargo.toml
Currently, it's possible for programs to become unbuildable due to a transitive dependency from borsh 0.10 -> hashbrown 0.13 -> ahash 0.8 -> getrandom 0.2.
It's possible to constantly update the Cargo.lock file to force hashbrown 0.12, but cargo will constantly update it, making this a losing battle.
As pointed out in https://github.com/solana-labs/solana-program-library/pull/4703, we just need to explicitly declare the dependency on getrandom.
It's fine to do it in individual programs, but other downstream users won't know, so let's put it at the highest point where the problem is introduced, in `solana-program`.
I tested that this works for SPL using a local monorepo, thanks for finding the fix @KirillLykov !
Fixes #
> program: Explicitly pull in `getrandom` with `custom` feature

- turbine/src/broadcast_stage.rs
- turbine/src/broadcast_stage/broadcast_duplicates_run.rs
- turbine/src/broadcast_stage/broadcast_fake_shreds_run.rs
- turbine/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
- turbine/src/broadcast_stage/standard_broadcast_run.rs
`Receiver` channels are thread-safe and do not need a `Mutex` wrappers.
Removed redundant `Mutex` wrappers around `Receiver` channels.
> removes redundant Mutex wrappers around Receiver channels

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/readable.rs
This PR introduces TieredReadableAccount, a struct that takes a generic
TieredAccountMeta that implements ReadableAccount and support
StoredAccountMeta.
More tests will be added once more reader and writer functions for hot
accounts have been added.
> [TieredAccountStorage] TieredReadableAccount

- runtime/src/account_storage/meta.rs
- runtime/src/accounts_db.rs
- runtime/src/accounts_db/geyser_plugin_utils.rs
- runtime/src/append_vec.rs
- runtime/store-tool/src/main.rs
Both AppendVec::cloned_account() and ReadableAccount::to_account_shard_data()
returns an AccountSharedData instance by cloning itself as pointed out under
a [comment](https://github.com/solana-labs/solana/pull/32380#discussion_r1253856793) in PR #32380.
This PR removes AccountsFile::cloned_account() and replaces its call-sites by
ReadableAccount::to_account_shared_data().
> Replace AccountsFile::cloned_account by ReadableAccount::to_account_shared_data()

- core/src/accounts_hash_verifier.rs
- core/src/replay_stage.rs
- core/src/snapshot_packager_service.rs
- frozen-abi/macro/src/lib.rs
- geyser-plugin-manager/src/geyser_plugin_manager.rs
- ledger-tool/src/main.rs
- ledger/src/bank_forks_utils.rs
- runtime/src/bank.rs
- runtime/src/snapshot_package.rs
- validator/src/bootstrap.rs
Seems like rustfmt 1.6.0 can now format how `let/else` statements.
1.5.2 we use in our `solana-nightly` does not mind the reformatting.
```
❯ cargo +nightly fmt --version
rustfmt 1.6.0-nightly (f20afcc 2023-07-04)
❯ cargo +nightly fmt
❯ git add -u
❯ git commit
❯ ./cargo nightly fmt --version
+ exec cargo +nightly-2023-04-19 fmt --version
rustfmt 1.5.2-nightly (c609da5 2023-04-18)
❯ ./cargo nightly fmt
❯ git diff
[empty output]
```
`master` is not formatted according to the nightly rustfmt.
In particular, the `let/else` statements could be formatted inconsistently.
Ran `cargo +nightly fmt`.
> `cargo fmt` using 1.6.0-nightly

- programs/stake/src/stake_state.rs
- sdk/program/src/rent.rs
`stake_split_uses_rent_sysvar` is now activated on all clusters and unused code paths can be cleaned up
- Removed `calculate_split_rent_exempt_reserve` function
Fixes #
> feature flag cleanup: stake_split_uses_rent_sysvar

- ledger-tool/src/ledger_utils.rs
- ledger-tool/src/main.rs
It can be useful to store tx status information in the ledger after the fact.
Add a flag to `verify` command to store tx metadata
Did a quick test and confirmed that transaction status gets populated after running. Ie, without the change,
```
Status: Unavailable
```
and with it:
```
Status: Ok
Fee: ◎0.000005
...
```
> ledger-tool: Add flag to store tx metadata in verify subcommand

- ledger/Cargo.toml
- ledger/src/blockstore_meta.rs
- local-cluster/Cargo.toml
(this is the 2nd use of the shiny `dev-context-only-utils`, introduced at https://github.com/solana-labs/solana/pull/32169)
Finally, i atone for my aged sin at https://github.com/solana-labs/solana/pull/19912#discussion_r1257413361... lol
> dcou: SlotMeta::unset_parent()

- .buildkite/scripts/build-downstream-projects.sh
Re-enable spl downstream build which was disabled after borsh upgrade.
See https://github.com/solana-labs/solana/issues/32378
> Re-enable spl downstream build

- runtime/src/tiered_storage/readable.rs
While TieredReadableAccount implements ReadableAccount that
already includes `fn data(&self) -> &'a [u8]`, a `data()` function that
directly under TieredReadableAccount is still needed in order to
correctly link the lifetime of the returned value and its member
account_block.  Otherwise, cargo will complain lifetime may not
live long enough.
```
error: lifetime may not live long enough
--> runtime/src/account_storage/meta.rs:152:9
|
118 |   impl<'a> StoredAccountMeta<'a> {
|        -- lifetime `'a` defined here
...
151 |       pub fn data(&self) -> &'a [u8] {
|                   - let's call the lifetime of this reference `'1`
152 | /         match self {
153 | |             Self::AppendVec(av) => av.data(),
154 | |             // Self::Cold(cs) => cs.data(),
155 | | …
```
> [TieredStorage] TieredReadableAccount::data()

- ci/buildkite-pipeline.sh
- ci/buildkite-solana-private.sh
https://github.com/solana-labs/solana/pull/32429 re-enable spl downstream test but not trigger the correspond step cuz we ignore all_test_steps when we only modify `^.buildkite`
remove `^.buildkite` from the allow list
> ci: update rules for triggering all_test_steps

- runtime/src/partitioned_rewards.rs
part of https://github.com/solana-labs/solana/pull/32415
Add PartitionedEpochRewardsConfigRewardBlocks variant in reward config to test multiple reward blocks scenario in integration tests.
Fixes #
> add PartitionedEpochRewardsConfigRewardBlock

- ci/buildkite-secondary.yml
https://discord.com/channels/428295358100013066/910937142182682656/1127985494446325760
sometimes we need to re-run publish-crate step again for missing crates. re-triggering the whole pipeline does not quite make sense.
allow manually retrying publish-crate step although it passed
> ci: allow retrying publish-crate although passed

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
part of https://github.com/solana-labs/solana/pull/32415
Given that small epoch only have 32 slots, 5% factor will result in just one
block for reward, which will not cover multiple reward blocks for testing.
Update max reward block factor from 5% to 10%, so that we can cover multilple
reward blocks for testing.
Fixes #
> update max reward block factor

- runtime/src/ancient_append_vecs.rs
Ancient append vecs were initially implemented with append behavior. The current, newer version uses a packing algorithm. The stat for `slots_considered` didn't get hooked up for packed ancient append vecs.
Hook up metric.
Fixes #
> hook up ancient.slots_considered metric

- ledger/src/blockstore.rs
We have several other functions that return data shreds; however, these other functions map `shred::Error` to `BlockstoreError`. The other functions being:
https://github.com/solana-labs/solana/blob/cec6b861cfc9b7751d93084aa89c60b2704bde31/ledger/src/blockstore.rs#L1629
and
https://github.com/solana-labs/solana/blob/cec6b861cfc9b7751d93084aa89c60b2704bde31/ledger/src/blockstore.rs#L2937-L2943
The second one actually returns a `Vec<Entry>`, but the point stands that the return type of the function is `Result<T, BlockstoreError>`.
Make this function consistent with those and map the error.
Broke this out as cleanup from another PR
> Make Blockstore::get_data_shreds_for_slot() return type consistent

- cli/src/program.rs
Deployment of solana programs using the alt bn128 syscall fails with cli versions 1.16.*, with the following error:
```
Error: ELF error: ELF error: Unresolved symbol (sol_alt_bn128_group_op) at instruction #16736 (ELF file offset 0x20a18
```
See this example for steps to replicate the issue:
https://github.com/ananas-block/exec_test/tree/altbn_deploy
- replaces  FeatureSet::default() with   FeatureSet::all_enabled()
Fixes #
https://github.com/solana-labs/solana/issues/32447
> cli: fix program deployment elf verification issue 

- core/src/banking_stage/decision_maker.rs
#30618 did a bad copy pasta of constants.
Found this while investigating #32179 further, added some notes there on investigation.
#30618 was originally merged into v1.16. I reccommend we backport this.
My intent is to keep this fix PR simple so that it can be backported, and add tests to master in a follow-up PR.
revert constant for HOLD-only period from 20 slots to 1 slot.
Fixes #
> Bugfix: would_be_leader_shortly_fn period set to 1 slot instead of 20

- ci/order-crates-for-publishing.py
Recently, `order-crates-for-publishing.py` bite us (or me, specifically, lol) for rejecting a valid circular dep which has been legalized at https://github.com/rust-lang/cargo/pull/7333 (at rust 1.40)
as for the underlying problem, unfortunately, there's a years-long extremely muddying affair regarding circular dev-dep. and lack of grouped (i.e. `workspace`-d) `cargo publish` , our tendency of bench code placement (under `./benches`) and `#[cfg(test)]` interaction, never-stabilized `benches`, no official equivalent to `#[cfg(feature = "dev-context-only-utils")]`, and `cargo hack`-based publish and its drawbacks..... YES, I'm tortuning myself for high standards of our coding practice. ;)
I don't spend writing all the findings. for bored, you can start your rabbit hole starting at these …
> Relax dcou dep. in order-crates-for-publishing.py

- runtime/src/tiered_storage/meta.rs
`TieredAccountMeta` has default impls on many of its methods. But I don't think it should, because these defaults are not actually useful defaults (i.e. they are `unimplemented!()`).
We're only going to have a small number of structs that'll implement this trait, and each struct should be responsible for picking the correct impl for each method. 
Currently, `HotAccountMeta` is the only one, and it implements every method.
Remove default impls on TieredAccountMeta
> Removes default impls on TieredAccountMeta

- runtime/src/accounts_db.rs
During high account count testing, we discovered `remove_unrooted_slots` taking a very long time (hours).
Unfortunately, the log metrics had a bug in when to log the metrics. The metric logging code is shared. In this case, the metrics are created new each call. This means the first time to check if sufficient duration has passed will ALWAYS skip the first call and say 'no'. This prevents startup noise and gives periodic, useful metrics over time. However, in this case since we never call it a second time on the same temporary metrics struct, the metrics NEVER get logged. This is related to the skip first parameter within the elapsed time checker.
Change duration to None so that we always log the metrics NOW, the one and only time it is called from abs loop.
Fixes #
> correctly log stats at remove_unrooted_slots

- Cargo.lock
- core/Cargo.toml
- core/src/banking_trace.rs
(this is the 3rd use of the shiny `dev-context-only-utils`, introduced at https://github.com/solana-labs/solana/pull/32169)
Finally, i atone for another sin at #29196... lol
~currently, blocked by #32432~ (EDIT: unblocked now)
> dcou: mod banking_trace::for_test

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- scripts/cargo-install-all.sh
not tested at all :)
seems ntapi is still used somehow even after #32430 
so, just restore the ntapi patch.
Fixes #
> Restore ntapi patching

- runtime/src/tiered_storage/readable.rs
This PR replaces the struct life-time parameter `'a` to `'accounts_file` in
TieredReadableAccount to improve readability.
> [TieredStorage] Replace 'a by 'accounts_file in TieredReadableAccount

- runtime/src/bank.rs
- runtime/src/bank/builtin_programs.rs
- sdk/program/src/message/sanitized.rs
`get_num_signatures_in_message()` and `get_num_write_locks_in_message()` could be moved to `SanitizedMessage` implementation.
Move the methods and update the usage.
Fixes #
> Move methods to get num signatures and locks to SanitizedMessage

- cost-model/src/cost_model.rs
- program-runtime/src/compute_budget.rs
- programs/sbf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- sdk/src/fee.rs
`calculate_fee()` has dependency on `ComputeBudget` that prevents it from moving to `sdk`.
Refactor the code to remove the dependency.
Fixes #
> Remove calculate_fee()'s dependency on ComputeBudget

- banking-bench/src/main.rs
- bloom/benches/bloom.rs
- cli-output/src/cli_output.rs
- cli/src/cli.rs
- core/benches/banking_stage.rs
- core/src/verified_vote_packets.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore/blockstore_purge.rs
- ledger/src/blockstore_db.rs
- ledger/src/shred.rs
- ledger/src/shredder.rs
- perf/src/sigverify.rs
- remote-wallet/src/ledger.rs
- rpc-client/src/mock_sender.rs
- runtime/benches/status_cache.rs
- sdk/src/signature.rs
- sdk/src/signer/keypair.rs
- send-transaction-service/src/send_transaction_service.rs
- storage-proto/src/convert.rs
`Signature::new` lacks type-safety and may panic.
The commit deprecates this interface and instead implements `Signature::{try_,}from`.
> deprecates Signature::new in favor of Signature::{try_,}from

- programs/sbf/tests/programs.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- sdk/src/fee.rs
`calculate_fee()` function doesn't require access to `Bank`. Having it in bank.rs puts unnecessary dependency on `bank` in rest of the codebase.
Move `calculate_fee()` out of bank.rs
Fixes #
> Move calculate_fee() out of bank.rs

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/footer.rs
- runtime/src/tiered_storage/index.rs
This PR implements AccountIndexFormat::AddressAndOffset, the index format
that will be used by the hot account storage.
Tested via the prototype implementation of tiered-storage.
> [TieredStorage] Implementation of AccountIndexFormat for hot accounts

- cost-model/src/cost_model.rs
- program-runtime/src/compute_budget.rs
Philip @ FD pointed out "when there are no ComputeBudgetProgram instructions but at least 1 non-builtin instruction, bpf_execution_cost  is initially set to 200k*(number of non-built-in instructions) but then overwritten to 200k*(number of non-ComputeBudgetProgram instructions) by the result of compute_budget.process_instructions . This means that if you have a mix of built-in and non-built-in instructions, the built-in ones get double counted (included in builtins_execution_cost and bpf_execution_cost )."
1. add test `test_transaction_cost_with_mix_instruction_without_compute_budget` to cost_model.rs, confirms builtin ix add cost to `bpf_execution_cost`
2. add test `test_process_mixed_instructions_without_compute_budget` to compute_budget.rs, to explicitly demo default compute unit limit …
> cost model could double count builtin instruction cost

- sdk/program/src/stake/mod.rs
- sdk/program/src/stake/stake_flags.rs
Fix a stake redelegation issue.
Part of https://github.com/solana-labs/solana/pull/31876
Add stake_flag struct
Fixes #
> Add stake flags struct

- programs/bpf_loader/src/syscalls/mod.rs
The changes related to Big integer modular exponentiation (EIP-198). The calculation is implemented as syscall.
The formula that was used to approximate the compute budgets for large number exponentiation seems to under-approximate the costs for exponentiation of very large numbers (i.e. >>1000 byte numbers). This could lead to a negative impact on the network if the syscall was to be invoked with very large numbers.
In practice, it seems like any normal/non-adversarial use of the syscall will be on numbers of size less than or equal to 4096-bits (i.e. for RSA-4096)
Inside syscall all inputs are limited by value 4069 bits (512 bytes).
If the length is exceeded, an error SyscallError::InvalidLength returned.
This is a combination of the fixes by @valiksinev and the tests by @derrekr and …
> big_mod_exp syscall: exclude inputs of numbers larger than 4096-bits

- ledger/src/blockstore_db.rs
Using the `Slot` type (which is actually a `u64`) is more clear and reinforces that the field is a slot.
> Use Slot type instead of u64 for clarity

- core/src/window_service.rs
- ledger/src/blockstore.rs
The existing signature unpacked elements from a Shred and took an owned Vec<u8>, forcing a .clone() from the caller.
The Shred can be passed in directly to simplify argument list and avoid the clone.
Stumbled across this while reviewing https://github.com/solana-labs/solana/pull/32528
> Simplify signature for Blockstore::is_shred_duplicate()

- gossip/src/duplicate_shred.rs
No need to clone the payload, can let the `Shred` take ownership of it momentarily and then give it back up with `into_paylaod()`
Fixes #
> Remove unnecessary clone of shred payload

- core/src/window_service.rs
- ledger/src/blockstore.rs
There's a race condition where duplicate shreds in the same insert batch might not get detected as duplicate. The order of events is as follows:
1. A batch of shreds with both duplicate `A` and `B` arrive to `insert_shreds_handle_duplicate()` from `window_service`: https://github.com/solana-labs/solana/blob/cfb028819a63de8f726bab3c9c981eb3155e9886/core/src/window_service.rs#L283C42-L283C72
2. Duplicate `A` is inserted into `just_inserted_shreds` here: https://github.com/solana-labs/solana/blob/cfb028819a63de8f726bab3c9c981eb3155e9886/ledger/src/blockstore.rs#L867, but is not committed to blockstore yet
3. Duplicate `B` is detected here: https://github.com/solana-labs/solana/blob/cfb028819a63de8f726bab3c9c981eb3155e9886/ledger/src/blockstore.rs#L1340, and the shred is sent to the duplicate …
> Detect duplicates in the same insert batch

- ledger/src/blockstore.rs
- ledger/src/shred.rs
- turbine/src/broadcast_stage/standard_broadcast_run.rs
Switching from Legacy to Merkle shreds.
Enable Merkle shreds for devnet and development clusters.
> enables merkle shreds for devnet and development clusters

- runtime/src/accounts_db.rs
[This pr](https://github.com/solana-labs/solana/pull/29480) incorrectly identified `scan_account_storage` as a function which would only run when it was not legal for shrinking to be running in the background. It looks like all but 1 caller are from the background. Background callers would be running serially with shrinking.
As a result, there is a race condition where if shrink is active during a call to `scan_account_storage`, we can assert.
Replace `get_slot_storage_entry` with `get_slot_storage_entry_shrinking_in_progress_ok`.
It is clearly legal for a scan to be going on while background processes are active.
Fixes #
> allow shrinking to be in progress during `scan_account_storage`

- ledger/src/blockstore_db.rs
Periodic compaction was previously disabled on all columns in #27571 in favor of the delete_file_in_range() approach that #26651 introduced. However, several columns still rely on periodic compaction to reclaim storage. Namely, the `TransactionStatus` and `AddressSignatures` columns as these columns contain a slot in their key, but as a non-primary index.
The result of periodic compaction not running on these columns is that no storage space was being reclaimed from columns. This is obviously bad and would lead to a node eventually running of storage space and crashing.
Between the two PR's above and another one (#28409), we might have gotten a little overzealous in removing "dead" code and ended up deleted something that we still needed (I reviewed that PR and missed it 😢 ). This change …
> Re-enable periodic compaction on several columns

- .buildkite/scripts/common.sh
the buildkite `group` generator helper emits an empty skeleton when no steps are passed, which buildkite pukes on when the pipeline is uploaded
as seen in, https://buildkite.com/solana-labs/solana/builds/99283#01897551-c842-4618-8c70-0a0d845c9c48/179-182
harden it via:
1. strictly enforce all generated groups to pass a `name`
2. skip `group` generation altogether if no steps are passed. log on stderr instead
> ci: harden buildkite `group` generator

- .buildkite/hooks/post-command
I think it is better if we can check whether the corresponding token exists before we upload
> ci: only upload the test result when the token is present

- frozen-abi/src/abi_example.rs
- net-utils/src/lib.rs
- program-runtime/src/loaded_programs.rs
- sdk/macro/src/lib.rs
- sdk/program/src/entrypoint.rs
- sdk/program/src/message/compiled_keys.rs
- sdk/program/src/sysvar/instructions.rs
We've been sitting on an oldish version of Cargo that spits out a ton of warning on nightly. This is extremely frustrating as we need to look more carefully at our output warning to make sure they are not from changes we made, instead of just checking if there are warnings.
Wanted to begin tackling some of the clippy warnings and errors that have been introduced since our cargo freeze. This is a step towards upgrading, but does not include fixes necessary to upgrade.
- ee65ea315d1bff4a7cd0f44f939a7f51b58ff1cb - don't need to call default() here to create `PhantomData`
- 040b0f7a033a932411630e1e5874544fb8b361d9 - new lint `incorrect_clone_impl_on_copy_type` doesn't like if `Clone != Copy` for `Copy`able types. Ignore this lint on our `CloneZeroed` macro.
- …
> Preliminary Changes for Updating Cargo

- programs/bpf_loader/src/lib.rs
- runtime/src/bank.rs
The load_program function can use some streamlining and cleanup. The old code was written because of executor cache usage of bpf_loader. Since then the executor cache code has been deleted.
- Rework `load_program()` to remove the call to `load_program_from_account()`
- Remove `load_program_from_account()`
Fixes #
> Cleanup load_program() in bank.rs

- cost-model/src/cost_model.rs
- program-runtime/src/compute_budget.rs
- runtime/src/accounts.rs
- runtime/src/bank.rs
- runtime/src/transaction_priority_details.rs
Feature `8sKQrMQoUHtQSUP83SPG4ta2JDjSAiWs7t5aJ9uEd6To` has been enabled since epoch 478
cleanup feature
Fixes #
> cleanup feature: Use default units per instruction in fee calculation

- account-decoder/src/parse_stake.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- ledger-tool/src/main.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- runtime/src/non_circulating_supply.rs
- runtime/src/stake_account.rs
- runtime/tests/stake.rs
- sdk/program/src/stake/state.rs
Fix a stake redelegation issue.
Part of https://github.com/solana-labs/solana/pull/31876
Add StakeFlags to StakeState
NOTE: This change just adds StakeFlags to StakeState. The Stake behavior should not change. 
The actual fix will come in a following PR once this PR is merged.  
Fixes #
> Add stake_flags to stake state

- .buildkite/scripts/build-downstream-projects.sh
we introduced a sdk breaking changes in https://github.com/solana-labs/solana/pull/32524 but we haven't released a crate for it. It makes spl project need to use a future crate for monorepo's downstream project test.(started from https://github.com/solana-labs/solana-program-library/pull/4504 and reverted in https://github.com/solana-labs/solana-program-library/pull/4841)
I guess we should follow these steps:
1. released a new crate for sdk
2. spl project upgrade to the new version
3. restore spl downstream project
(thank @joncinque for the insight <3 )
stop spl downstream project test temporarily till we bump release new sdk version
> ci: stop spl downstream project test temporarily

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/hot.rs
This PR initiates the implementation of the main struct for the
tiered accounts storage --- TieredStorage.  Specifically,
it defines the TieredStorage struct, TieredStorageFormat,
and skeleton implementation of new_writable().
> TieredStorage struct (1/N) -- new_writable

- Cargo.lock
- cli/src/program.rs
- client-test/Cargo.toml
- client-test/tests/send_and_confrim_transactions_in_parallel.rs
- client/Cargo.toml
- client/src/lib.rs
- client/src/send_and_confirm_transactions_in_parallel.rs
- programs/sbf/Cargo.lock
- tpu-client/src/nonblocking/tpu_client.rs
Uploading a program with a large size is very difficult because the program is broken into small transactions and sent to the cluster. It will try to send all the transactions at once and then confirm them. If the program needs to send 1000 transaction to be uploaded, it will sign all transactions with a blockhash and while uploading the transactions will expire and will not be confirmed.
Updating continuously the blockhash with a task, and confirming the transaction with another. 
Using the new algorithm to update programs.
Fixes #
> New method to send large number of transactions to the cluster

- nextest.toml
`test_batched_range_proof_u256` is flaky when test it with nextest
make it use all threads during nextest testing
> ci: make test_batched_range_proof_u256 use all threads in nextest

- ledger-tool/src/main.rs
The --encoding flag only makes sense for the genesis command if the genesis accounts will be printed. Hence, the encoding flag used the Arg::requires() function on --accounts argument.
However, in what appears to be a clap bug, this made the --accounts flag required even though it should not be.
So, remove the .requires() dependency between these two arguments.
Prior to this change, running the following would error:
```
$ solana-ledger-tool genesis --ledger ~/ledger/
error: The following required arguments were not provided:
--accounts
```
When I removed the `.default_value()` specifier on the encoding arg, the error went away. So, there is seemingly some clap bug, but given how old of a version we're using, I do not plan on submitting a PR to them
> ledger-tool: Workaround clap bug for encoding arg in genesis command

- ledger-tool/src/bigtable.rs
- ledger-tool/src/ledger_utils.rs
- ledger-tool/src/main.rs
- ledger-tool/src/program.rs
- ledger/src/blockstore_options.rs
The current desired open file descriptor limit is 1,000,000. This is quite a large number, and not needed for every command. Namely, commands that do not unpack a snapshot and create an AccountsDB will likely not use this many files.
There is already an option in BlockstoreOptions to ignore errors if the desired value cannot be set; this PR just bubbles that option up to a CLI flag in ledger-tool.
Think it makes sense to keep the default of enforcing the limit. This flag is mostly orientated towards advanced users who know which command won't incur as many open files and want to run those commands without the file limitation
> ledger-tool: Add flag to ignore open file descriptor limit error

- runtime/src/snapshot_bank_utils.rs
The metrics within `add_bank_snapshot()` are kinda misleading. For one, they are in milliseconds, whereas most timing metrics report microseconds. More-so though, the `add_snapshot_ms` was only a partial piece. It covered *most* of the code in the function, but not all, which made it confusing to know what exactly was measured without looking at the code.
* Report metrics as microseconds
* Remove the `add_snapshot_ms` metric
* Rename the datapoint itself to `snapshot_bank`
* Remove the "file" part; more than one file, and use underscores instead of dashes
> Cleanups metrics in add_bank_snapshot()

- sdk/src/transaction_context.rs
reserve() only changes the capacity of the vector that holds the account data, it doesn't modify the account in any way
Extracted from https://github.com/solana-labs/solana/pull/31986 since it's a self contained change.
> BorrowedAccount: reserve() doesn't need to check for can_data_be_changed()

- programs/bpf_loader/src/syscalls/cpi.rs
Extracted from https://github.com/solana-labs/solana/pull/31986 since it's a self contained change.
> cpi: change unnecessary &mut MemoryMapping to &MemoryMapping

- program-runtime/src/invoke_context.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/cpi.rs
Instead of passing `original_account_lengths` around as `Vec<usize>`,  introduce an explicit type that includes the length and soon more. Doesn't change anything in the existing logic, just the type passed around.
Extracted from https://github.com/solana-labs/solana/pull/31986. This is preparation of passing around more data from serialization down to CPI.
> introduce SerializedAccountMetadata

- runtime/src/snapshot_bank_utils.rs
From @apfitzge's comment, https://github.com/solana-labs/solana/pull/32652#discussion_r1277750966, we can simplify the bits inside the `if-let`.
Remove unnecessary local variables.
> Simplifies if-let when rebuilding bank

- runtime/src/accounts_db.rs
- runtime/src/read_only_accounts_cache.rs
Working on improving load time from read cache.
Add `read_only_cache_load_us` metric to measure cost of load and update eviction queue.
Fixes #
> add metric read_only_cache_load_us

- streamer/src/packet.rs
The same value is reported as a field in StreamerReceiveStats in /streamer/src/streamer.rs
One more counter gone
> Remove redundant inc_new_counter for num received packets

- runtime/src/accounts_hash.rs
We create a mutex at the start of `de_dup_accounts()` that is used by the parallel threads inside. At the end of the function, we get the data out of the mutex to update stats. Since we know all the parallel threads are done, we are the only one left with access to the Mutex, and thus we can skip the final lock.
Replace the final mutex lock with an `into_inner()`.
> Uses Mutex::into_inner() at end of de_dup_accounts()

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
- runtime/src/pubkey_bins.rs
high account count simulation see 40GB memory spike while calculating accounts hash. These allocations are not necessary.
Avoid large allocations during accounts hash calculation by reworking algorithm. The previous algorithm found the range by pubkey bin and stored those off. This allocated this many vector elements: # bins (64k in master) * number of chunks, which can be very large when we have many ancient append vecs (10k on high account count sims).  The result was ~40GB in the high account count simulation. These cutoff ranges can be determined as needed using binary search and in parallel as we eliminate duplicates and get hash values sorted by pubkey for each chunk.
Fixes #
> avoid giant memory allocation in hash calc

- core/src/shred_fetch_stage.rs
- core/src/validator.rs
Packets obtained from recycler have dirty meta information and need to re-initialized.
Reset packet flags obtained from QUIC datagrams.
> resets packet flags obtained from QUIC datagrams

- frozen-abi/Cargo.toml
- sdk/program/Cargo.toml
we bumped cc to 1.0.80 in https://github.com/solana-labs/solana/pull/32681 and it only supports unix and window atm.
https://github.com/rust-lang/cc-rs/blob/7adebb9d8c235a53800c4ac3a160615aa1c5028c/src/os_pipe.rs#L19-L28
```rust
#[cfg(unix)]
#[path = "os_pipe/unix.rs"]
mod sys;
#[cfg(windows)]
#[path = "os_pipe/windows.rs"]
mod sys;
#[cfg(all(not(unix), not(windows)))]
compile_error!("Only unix and windows support os_pipe!");
```
update our Cargo.toml to fit the requirement
> ci: fix cc only support unix and window since 1.0.80

- programs/bpf_loader/src/lib.rs
#30748 is missing [this check from v1.14](https://github.com/solana-labs/solana/blob/d621b94895912a896fb893b58b77b71270103a47/programs/bpf_loader/src/lib.rs#L381C9-L387C10):
```Rust
if program.is_executable() && !check_loader_id(program.get_owner()) {
ic_logger_msg!(
log_collector,
"Executable account not owned by the BPF loader"
);
return Err(InstructionError::IncorrectProgramId);
}
```
Adds the missing error condition to the feature gated code.
Feature Gate Issue: #30747
> Fix - Adds missing "Executable account not owned by the BPF loader" error to `remove_bpf_loader_incorrect_program_id`

- programs/bpf_loader/src/syscalls/mod.rs
- runtime/src/bank.rs
Some features which affect the RBPF config or available syscalls are not in the `FEATURES_AFFECTING_RBPF` list. This explicit list will not be required anymore once the automatic detection of #32172 works.
Adds the missing feature pubkeys to the list.
> Fix - Adds missing feature pubkeys to the `FEATURES_AFFECTING_RBPF` list

- runtime/src/accounts_background_service.rs
BankForks::root_bank() already returns an Arc<Bank> so no need to clone
> Remove unnecessary clone

- turbine/src/cluster_nodes.rs
The metric is sent out for almost every shred for slots at the epoch boundary which is too many.
* Demoted the metric to debug.
* Follow up patches will fix what causes the unknown epoch staked nodes at epoch boundary.
> demotes unknown_epoch_staked_nodes metric to debug

- cli/src/feature.rs
- sdk/src/genesis_config.rs
Activating features can have major implications on the target cluster. Currently, the target cluster is determined by the RPC url, which has both a default value as well as a value that can be set in a config-file and forgotten about.
This extra argument serves as a guardrail by forcing the feature key holder to explicitly type out the cluster they intend to activate the feature on.
I did a little testing with this, and things appeared to look good. However, I don't hold any unactivated feature keys at the moment, so my testing involved hacking things up to allow the command to proceed with an invalid feature.
> Add required cluster argument to solana feature activate subcommand

- runtime/src/append_vec.rs
In nightly rust we will encounter the following error messages:
> error: casting `&T` to `&mut T` is undefined behavior, even if the reference is
> unused, consider instead using an `UnsafeCell`
>    --> runtime/src/append_vec.rs:718:17
>     |
> 718 |                 *(&self.meta.data_len as *const u64 as *mut u64) =
> new_data_len;
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: `#[deny(cast_ref_to_mut)]` on by default
> error: casting `&T` to `&mut T` is undefined behavior, even if the reference is
> unused, consider instead using an `UnsafeCell`
>    --> runtime/src/append_vec.rs:733:17
>     |
> 733 |                 *(&self.account_meta.executable as *const bool as *mut u8) =
> new_executable_byte;
>     | …
> Fix - Uses `std::mem::transmute` and `std::ptr::write` in unsafe code in append_vec.rs

- core/src/validator.rs
- rpc/src/optimistically_confirmed_bank_tracker.rs
No need to get an Arc<Bank> when we want the root slot from BankForks; can just use BankForks::root().
Note that `root_bank()` calls `root()` internally, so these are equivalent:
https://github.com/solana-labs/solana/blob/a310dd776c8f33ef3ca6ce78dc00738f7dc800ee/runtime/src/bank_forks.rs#L152-L154
> Simplify root slot lookup from BankForks

- runtime/src/accounts_db.rs
Remove cast in scan metric reporting
peeled off from https://github.com/solana-labs/solana/pull/32558
Fixes #
> remove type cast in scan metric report

- runtime/src/tiered_storage.rs
- runtime/src/tiered_storage/error.rs
- runtime/src/tiered_storage/footer.rs
- runtime/src/tiered_storage/hot.rs
- runtime/src/tiered_storage/readable.rs
This PR implements TieredStorage::new_readonly() and introduces
TieredStorageReader and HotStorageReader.
Updated the existing unit test.
This PR depends on #32541.
> TieredStorage struct (3/N) -- new_readonly and reader structs

- turbine/src/broadcast_stage/standard_broadcast_run.rs
Ramping up Merkle shreds on mainnet.
Roll out Merkle shreds to ~50% of mainnet slots.
> rolls out merkle shreds to ~50% of mainnet slots

- ci/test-checks.sh
During development, it is very nice to run sanity build check (i.e. `test-checks.sh`) with local changes before committing them. However, the `test-check.sh` script requires that there are no uncommitted changes locally. To work around this, developers usually have to commit the pending changes first, then run this script. After finding/fixing errors, commit again and then rerun the scripts ... This is annoying. We should allow the scripts to run with pending changes during development.
Only check `git diff` for ci build
Fixes #
> Allow pending changes for `test-checks.sh` for local build

- gossip/src/crds.rs
Slight modification to [PR: 32504](https://github.com/solana-labs/solana/pull/32504)
we want to track message coverage for push messages, not messages received via pull requests. Fixes this issue which was created in: [PR: 32504](https://github.com/solana-labs/solana/pull/32504).
update CrdsDataStats.record_insert() to accept a `GossipRoute` enum. If GossipRoute is of variant GossipRoute::PushMessage, then check if we need to report this message to metrics
Fixes #
> report received message signatures only on PUSH requests

- rpc/src/optimistically_confirmed_bank_tracker.rs
To be consistent on `&Arc` usage, when no need to own or clone, use `&` instead of `&Arc<>`
- use `&` for those read-only parameters
Fixes #
> Remove unnecessary ref of arc

- runtime/src/accounts_db.rs
- runtime/src/serde_snapshot.rs
- runtime/src/serde_snapshot/tests.rs
Some `accounts-db` unit tests depend on `serde-snapshot`. With `runtime` crate refactor, these tests ends up causing circular dependency between runtime and accounts-db crates.
Move the tests to `serde-snapshot` tests. This will allow these tests to have dependency on runtime as well as accounts-db.
Fixes #
> Move `serde-snapshot  dependent accounts-db tests

- runtime/src/read_only_accounts_cache.rs
Improve loads on read-only account cache.
* read-only account cache uses an atomic for index.
* `ReadOnlyAccountsCache::load` no longer needs a mutable entry.
> uses atomics for read-only account cache entry index

- gossip/src/crds.rs
- gossip/src/crds_gossip_push.rs
We want to track how push messages propagate through the network from node to node. There is currently no way to track this. This builds off of [PR: #32708](https://github.com/solana-labs/solana/pull/32708). 
Add a `from` field to `GossipRoute::PushMessage` --> `GossipRoute::PushMessage(/*from:*/ Pubkey)` 
For extracting that pubkey for reporting to metrics, an `std:: fmt::Display` was added for `GossipRoute::PushMessage(Pubkey)`.
Fixes #
> Add from field for message tracking

- gossip/src/cluster_info.rs
- turbine/benches/cluster_nodes.rs
- turbine/src/cluster_nodes.rs
`DATA_PLANE_FANOUT` is a turbine specific constant and shouldn't be defined in gossip.
Moved `DATA_PLANE_FANOUT` to turbine.
> moves DATA_PLANE_FANOUT to turbine

- Cargo.lock
- core/src/repair/serve_repair.rs
- gossip/Cargo.toml
- gossip/src/cluster_info.rs
- gossip/src/contact_info.rs
- gossip/src/legacy_contact_info.rs
- sdk/docker-solana/Dockerfile
- validator/src/admin_rpc_service.rs
`LegacyContactInfo.tvu_forwards` is unused.
Repurposing the field for TVU over QUIC will avoid `QUIC_PORT_OFFSET` hack in a backward compatible way.
repurposes `tvu_forwards` socket for TVU over QUIC.
> repurposes tvu_forwards socket for TVU over QUIC

- core/src/replay_stage.rs
- core/src/validator.rs
- rpc/src/optimistically_confirmed_bank_tracker.rs
- rpc/src/rpc.rs
- rpc/src/rpc_subscriptions.rs
Prioritization fee cache accuracy can be improved.
- moved cache's finalization from "bank replayed" to "bank opt-confirmed" 
Fixes #
> improve prioritization fee cache accuracy

- runtime/src/accounts_db.rs
- runtime/src/accounts_index.rs
`purge_exact` is slow in some instances in the high accounts simulation.
Add metrics to track how many keys are affected and the cost of the major pieces of the algorithm.
Fixes #
> add metrics around purge_exact

- runtime/src/accounts_db.rs
- runtime/src/accounts_hash.rs
- runtime/src/active_stats.rs
accounts hash algorithm is a constant concern for cpu, memory, and disk i/o performance. There are 3 distinct phases: scan, dedup, merkle tree.
Add a stat reporting which part of the algorithm is active. This allows correlation with i/o, mem usage, etc.
Fixes #
> add active stats for pieces of hash calc

- account-decoder/src/parse_stake.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- docs/art/passive-staking-callflow.msc
- docs/src/cluster/stake-delegation-and-rewards.md
- genesis/src/main.rs
- genesis/src/stakes.rs
- ledger-tool/src/main.rs
- program-test/tests/warp.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- rpc/src/rpc.rs
- rpc/src/rpc_pubsub.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/genesis_utils.rs
- runtime/src/non_circulating_supply.rs
- runtime/src/stake_account.rs
- runtime/src/stakes.rs
- runtime/tests/stake.rs
- sdk/program/src/stake/instruction.rs
- sdk/program/src/stake/state.rs
- stake-accounts/src/stake_accounts.rs
https://github.com/solana-labs/solana/pull/32524 changed the `StakeState` enum to add a new field for the `StakeState::Stake` variant, which constitutes a breaking change for downstream users such as the stake pool and single-validator stake pool programs.
To avoid instant breakage and restore the downstream SPL job, rename the current breaking `StakeState` to `StakeStateWithFlags` as the enum with the changed variant, and then re-introduce the old `StakeState` as deprecated.
This allows the SPL downstream job to pass once again. The first commit is just a `grep ... | xargs sed ...`, and the second commit adds the `StakeState` back in.
Added @AshwinSekar because this conflicts with #32723 -- this can go in afterwards. 
Fixes #
> sdk: Add new version of `StakeState` to avoid breaking downstream users

- sdk/program/src/stake/state.rs
As mentioned in https://github.com/solana-labs/solana/pull/32723#issuecomment-1670896396, #32723 is causing mismatches in the canaries on mainnet.
I'm almost 100% sure this is due to the warmup-cooldown rate no longer being set on new stake accounts. Every other mainnet node is setting it to 0.25, but master is setting it to 0.0, causing an immediate mismatch.
Just set the warmup / cooldown rate to the old value in the default `Delegation` constructor.
Following the discussion at https://discord.com/channels/428295358100013066/1027231858565586985/1138603784768069783, I built `solana-ledger-tool` with this patch, and re-ran:
```
$ ./target/release/solana-ledger-tool verify --ledger ~/ledger --halt-at-slot 214149339  > jontest.txt 2>&1
```
And compared it against `good.txt` which was on the …
> stake: Set the Delegation's warmup / cooldown to the correct default

- ledger-tool/src/main.rs
- ledger-tool/src/program.rs
Several of the program command subcommands do not require a ledger as they act solely on the program object. 
So, defer checking the ledger path until we know we need to load. Additionally, remove genesis arg from these commands that do not load a genesis.bin
Without this commit, a `ledger` directory had to be findable, whether there was one in the working directory or one supplied by user via `--ledger` arg
> ledger-tool: Relax ledger requirements for program subcommand

- gossip/src/cluster_info.rs
- gossip/src/contact_info.rs
Difficult to make changes to `ContactInfo` because of backward compatibility issues.
The commit adds a `Vec<Extension>` to `ContactInfo` so that future additions to `ContactInfo` can be done by only adding new `Extension`s instead of modifying the entire `ContactInfo`.
> adds extensions to contact-info

- sdk/program/src/stake/config.rs
These constants were moved out of the stake config which might break downstream imports. 
Re-export these constants. 
Fixes #
> stake: pub use config constants for api backwards compatibility

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_hash.rs
`let _ = ...` causes rhs to be dropped immediately.
So, active period was 0s.
use
`let _guard = ...`
Fixes #
> keep active stats lock held

- cli-output/src/cli_output.rs
- cli/src/vote.rs
- programs/vote/benches/process_vote.rs
- programs/vote/src/vote_state/mod.rs
- rpc/src/rpc.rs
- sdk/program/src/vote/state/mod.rs
- sdk/src/feature_set.rs
This is the second change to complete the implementation of the timely vote credits feature.  The first change was here:
https://github.com/solana-labs/solana/commit/a45710838d3184eb884db1b23df04f995b2fa212
This second change utilizes the new fields of the Vote account to implement the timely vote credits feature which was proposed here:
https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0033-timely-vote-credits.md
> Implement timely vote credits feature

- account-decoder/src/parse_stake.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- docs/art/passive-staking-callflow.msc
- docs/src/cluster/stake-delegation-and-rewards.md
- genesis/src/main.rs
- genesis/src/stakes.rs
- ledger-tool/src/main.rs
- program-test/tests/warp.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- rpc/src/rpc.rs
- rpc/src/rpc_pubsub.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
- runtime/src/genesis_utils.rs
- runtime/src/non_circulating_supply.rs
- runtime/src/stake_account.rs
- runtime/src/stakes.rs
- runtime/tests/stake.rs
- sdk/program/src/stake/instruction.rs
- sdk/program/src/stake/state.rs
- stake-accounts/src/stake_accounts.rs
`StakeStateWithFlags` is not an amazing name, and doesn't allow for a good evolution over time, in case we need to add more information into `StakeState` for the next version. For example, when we add `Multistake`, it'll get very confusing for everyone.
It'll be easier in the longterm to explicitly version structs, so downstream developers can know more easily what the next upgrade step is.
This redoes the first commit of #32736 to change the name once more. This time, the command run was:
```
$ git grep -l "\<StakeStateWithFlags\>" | xargs sed -i'' 's/\<StakeStateWithFlags\>/StakeStateV2/g'
```
Fixes #
> stake: Rename `StakeStateWithFlags` -> `StakeStateV2`

- program-test/src/lib.rs
- program-test/tests/compute_units.rs
As reported by users, setting `u64::MAX` for the max compute units in solana-program-test causes all sBPF tests to fail: https://discord.com/channels/428295358100013066/774014770402689065/1136270266436173886
This happens because the rbpf vm actually represents compute unit budget with a `i64` in order to catch using too many units, so if we set anything larger than `i64::MAX`, the compute units becomes negative, which immediately errors.
While it may be better to change everything to use `i64` and match the vm, this would allow people to set negative numbers for their program's compute units, which we'll need to properly define.
Once that work is done, we can expose a new function on `solana-program-test` which accepts an `i64`. In the meantime, add a debug assertion to help users fix the …
> program-test: Prohibit setting the compute unit limit past `i64::MAX`

- cli/src/program.rs
- ledger-tool/src/program.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v4/src/lib.rs
- programs/sbf/benches/bpf_loader.rs
- runtime/src/bank.rs
Program runtime V2 environment is created every time a program is loaded. This can be optimized.
Store the environment in the cache.
Another refactor is needed to reuse the cached environment.
Fixes #
> Initialize and store PRv2 environment in cache

- cli/src/stake.rs
- cli/tests/stake.rs
in v1.16 votes from unstaked nodes are ignored. this creates a chicken/egg problem with a client-side check in the cli that requires a vote account to be actively voting before it can be staked
* query cluster for the target vote account with `getVoteAccounts` instead of `getAccount` ('cause we'll need the active stake)
* skip the client-side current vote check for unstaked voters
* refactor current voter check (it's getting fugly)
reviewer note: review the commits in order for a less horrible experience
> cli: skip delegate-stake current voter check for unstaked voters

- ci/test-checks.sh
#32728 introduced skipping the stale Cargo.lock check when running `ci/test-checks.sh` locally, based around the `CI` envvar being set. this causes two problems
1) the less safe behavior is opt-out, not opt-in
2) one cannot opt-out without modifying the scripts since the `CI` variable being set effects many behaviors which are not compatible with a local ci run
* gate skipping the stale Cargo.lock check on `SOLANA_CI_ALLOW_STALE_CARGO_LOCK` being instead of `CI`
* switch to `opt-in` instead of `opt-out` of the less safe behavior
if you want this
```bash
echo "export SOLANA_CI_ALLOW_STALE_CARGO_LOCK=" >> ~/.profile
```
> ci: allow local bypass of stale Cargo.lock check with custom variable instead of `CI`

- program-test/src/lib.rs
- program-test/tests/realloc.rs
While testing token-2022, I noticed that we need the instruction padding program in BPF to make the tests work, because otherwise we get an error:
```
thread 'solBankForksCli' panicked at 'source slice length (0) does not match destination slice length (165)', program-test/src/lib.rs:344:18
```
This is happening because the "fake native mode" in program-test only allows reallocs to a bigger size.
Also allow accounts to get smaller in native mode. The test looks a bit goofy because we need to CPI into something that makes an account smaller, but we don't want to pull in the `spl-token` crate, so we just use hard-coded values.
Fixes #
> program-test: Fix realloc in native mode

- accounts-db/src/accounts_db.rs
Accounts hash scan is migrating towards using mmapped files earlier instead of memory allocations initially. After sorting here, the memory allocations are written to mmapped files for downstream processing. We are transitioning to using memory mapped files earlier on to avoid large memory allocation spikes during hash calculation.
As such, it makes sense for the sort at the end of accounts hash scanning in a chunk to happen in place instead of by copying. That made sense previously anyway...
Sort in place instead of always making copies.
Fixes #
> accounts hash sort_slot_storage_scan sorts in place

- ci/do-audit.sh
- core/src/repair/serve_repair.rs
- dos/src/main.rs
- gossip/src/cluster_info.rs
- gossip/src/contact_info.rs
- gossip/src/legacy_contact_info.rs
- validator/src/admin_rpc_service.rs
Repair responses are sent back to the address the repair request came from and there is no need to gossip repair socket address. https://github.com/solana-labs/solana/blob/9212ac347/core/src/repair/serve_repair.rs#L519
Removed repair socket from gossip `ContactInfo`.
> removes repair socket from gossip ContactInfo

- gossip/src/contact_info.rs
Wasted space in `ContactInfo.cache` due to gaps in socket tags.
Reuse old TVU-forwards socket tag for TVU over QUIC protocol.
The change is backward compatible because TVU-forwards is not used any more and TVU over QUIC is not released yet.
> reuses old TVU-forwards socket tag for TVU over QUIC

- Cargo.lock
- Cargo.toml
- accounts-db/src/accounts_db.rs
- programs/sbf/Cargo.lock
~needs to #32829 to land first but~ (EDIT: landed) `qualifier_attr` needs to be updated. its internal impl improved quite a bit by https://github.com/JohnScience/qualifier_attr/pull/1, which is released under 0.2.x releases.
thus, the crate now needs to be `default-features = false` to exclusively switch to the newer impl according to https://crates.io/crates/qualifier_attr/0.2.2#note-on-legacy-attributes.
> dcou: Update qualifier_attr to 0.2.2

- bench-tps/src/bench.rs
- bench-tps/src/cli.rs
- bench-tps/src/main.rs
bench-tps is only capable of sending random priority transactions in the range 0..=50.
Sometimes it's desirable to send transactions with a fixed priority.
Related to #29126
- Allow fixed or random compute unit prices in bench-tps
Fixes #
> BenchTPS: Allow a fixed compute-unit-price

- ledger-tool/src/args.rs
- ledger-tool/src/ledger_path.rs
- ledger-tool/src/ledger_utils.rs
When ledger-tool runs, it may create secondary directories for things
like accounts, accounts-index, etc as not to potentially interfere with
solana-validator's directories. These would show as multiple directories
with ".ledger-tool" appended to the typical directory name.
To more clearly group these items, make the default directories for
snapshots, accounts and accounts-index all within a common "ledger-tool"
directory. This eases cleaning of ledger-tool files easier too.
This should not interfere would fast-boot at all, as fast-boot will currently run with primary access.
> ledger-tool: Consolidate ledger-tool specific directories

- ledger-tool/src/program.rs
- program-runtime/src/invoke_context.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v4/src/lib.rs
- runtime/src/bank.rs
`loader-v4` code is not yet integrated with bank. So the programs owned by this loader cannot be used.
Integrate the loader code with bank.
Fixes #
> Integrate program loader-v4 with bank

- gossip/src/cluster_info.rs
`new_with_external_ip` silently ignores errors when setting socket addresses which makes it harder to catch bugs:
https://github.com/solana-labs/solana/blob/7beeb8310/gossip/src/cluster_info.rs#L3054-L3063
assert that socket addresses set in `new_with_external_ip` are valid.
> asserts that socket addresses set in new_with_external_ip are valid

- ci/do-audit.sh
due to `RUSTSEC-2022-0093`, `ed25519-dalek` should upgrade to >= 2. in case everyone is blocked by this one. I choose to ignore it temporarily. we can add it back when https://github.com/solana-labs/solana/pull/32836 is ready!
> v1.16: ci: ignore RUSTSEC-2022-0093 temporarily

- ci/do-audit.sh
due to RUSTSEC-2022-0093, ed25519-dalek should upgrade to >= 2. in case everyone is blocked by this one. I choose to ignore it temporarily. we can add it back when https://github.com/solana-labs/solana/pull/32836 is ready!
(I guess we will just ignore it in this stable branch maybe 🤔 )
> v1.14: ci: ignore RUSTSEC-2022-0093 temporarily

- cli/src/program.rs
- client-test/tests/send_and_confirm_transactions_in_parallel.rs
- client/src/send_and_confirm_transactions_in_parallel.rs
While looking over changes in #32638, I noticed some typos of `confrim` in `SendAndConfrimConfig` and `send_and_confrim_transactions_in_parallel.rs`
Fix the typos! This can go in after #32638 since that's been approved.
Fixes #
> client: Rename confrim -> confirm

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
This PR was split from #32172.
Currently `Bank::compute_active_feature_set()` does not just compute the active feature set as the name implies, but also writes the result back into `self`.
`Bank::compute_active_feature_set()` now returns the new feature set and the difference to the current one. The overwriting of `self.feature_set` was factored out into the call sites.
> Refactor - `Bank::compute_active_feature_set()`

- program-runtime/src/loaded_programs.rs
This PR was split from #32172.
At the moment only `LoadedPrograms::sort_and_unload()` uses the sorted list of verified and compiled programs to evict them, but the recompilation phase before epoch boundaries will soon need that as well.
Adds `LoadedPrograms::get_entries_sorted_by_tx_usage()` which returns the list of loaded programs which are verified and compiled sorted by `tx_usage_counter` and can filter the result depending on the selected program runtime versions.
> Refactor - `LoadedPrograms::get_entries_sorted_by_tx_usage()`

- core/src/repair/serve_repair.rs
Deprecated repair type `max_response_packets` should be consistent with other deprecated types.
Clean up legacy repair types.
Fixes #
> legacy repair type cleanup

- ci/test-checks.sh
- ci/test-sanity.sh
there are a couple tests in `test-checks.sh` that are fast and invasive to local iteration
move them to `test-sanity.sh`
> ci: move some fast checks to sanity

- runtime/src/bank.rs
An audit of the bank code identified fns missing doc comments.
Original context: https://github.com/solana-labs/solana/pull/32709
Add documentation to `non_vote_transaction_count_since_restart()`.
> Adds docs to non_vote_transaction_count_since_restart()

- ledger-tool/src/main.rs
- runtime/src/bank.rs
An audit of the bank code identified fns missing doc comments.
Original context: https://github.com/solana-labs/solana/pull/32709
Renames `scan_all_accounts_with_modified_slots()` to `scan_all_accounts()` and adds documentation.
Please refer to https://github.com/solana-labs/solana/pull/32887#discussion_r1298546704 for comments regarding the rename.
Similarly, this function is only called from ledger-tool.
> Adds docs to scan_all_accounts()

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
An audit of the bank code identified fns missing doc comments.
Original context: https://github.com/solana-labs/solana/pull/32709
Renames `get_all_accounts_with_modified_slots()` to `get_all_accounts()` and adds documentation.
> Adds docs to get_all_accounts()

- accounts-db/src/accounts_db.rs
- accounts-db/src/cache_hash_data.rs
- accounts-db/src/cache_hash_data_stats.rs
Refactoring cache hash data files for performance.
Move stats to atomics instead of mutex.
Fixes #
> refactor cache hash data stats

- runtime/src/bank_forks.rs
Several of the unit tests have repeated logic for creating the banks.
- Remove redundant `Vec<Arc<Bank>>` structure; no need to maintain list of banks side-by-side with `BankForks`
- Move repeated `BankForks::insert()` calls into loops
- Condense repeated `BankForks::insert()` into helper function
This PR spun out of comment in https://github.com/solana-labs/solana/pull/32802, I'll aim to land this PR first and then rebase that PR on top of this one
> Reduce repeated logic in BankForks unit tests

- core/src/repair/repair_response.rs
- ledger/src/sigverify_shreds.rs
- turbine/src/sigverify_shreds.rs
Unnecessary use of `[u8; 32]` instead of `Pubkey` type.
Use typed `Pubkey` instead of opaque `[u8; 32]`.
> uses typed Pubkey instead of opaque [u8; 32]

- ci/buildkite-secondary.yml
https://discord.com/channels/428295358100013066/560503042458517505/1142219875071303740
the x86_64 mac seems to upload something wrong.
allow retrying the step for easier debugging
> ci: allow retrying mac publishing steps

- ci/upload-ci-artifact.sh
the old one doesn't exist anymore 😢 it's the time to change it to official one! 
use `amazon/aws-cli` image. (I don't use the `latest` tag cuz they said: _There are no backwards compatibility guarantees in relying on the latest tag_)
> ci: update aws cli image

- accounts-db/src/accounts_db.rs
- accounts-db/src/cache_hash_data.rs
working on reducing memory footprint and improving perf of accounts hash calc
Separate out opening file and mmapping it.
Fixes #
> cache hash files: separate get_file_reference_to_map_later and map

- accounts-db/src/accounts_db.rs
- core/src/accounts_hash_verifier.rs
When creating an enum to select some underlying *kind* of a thing, we sometimes append `Enum` or `Type` for the name of the type. I think both of these are bad, but not life ending.
Obviously the variants are not *types* in the Rust sense of the word. And the type is already an enum, so adding `Enum` feels redundant.
In the Rust std lib, they have this problem for errors. They've solved this with [`ErrorKind`](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html). 
(Some non-Rust projects have also used `Flavor` too, which I like, but not as much as `Kind`.)
`CalcAccountsHashFlavor` has this naming problem—but less so. I'd like to be self-consistent.
Rename `CalcAccountsHashFlavor` to `CalcAccountsHashKind`.
> Renames CalcAccountsHashFlavor to CalcAccountsHashKind

- program-test/src/lib.rs
- programs/sbf/rust/sysvar/src/lib.rs
- programs/sbf/rust/sysvar/tests/lib.rs
- runtime/src/bank.rs
when running sbf program, sbf loader will use runtime sysvar cache to load
sysvar. Therefore, the program will return unsupported sysvar error if the
sysvar doesn't  exist in the cache. For normal sysvar, this is not a problem
because the sysvar always exists for every bank. However, for `epoch_rewards`
sysvar, the situation is different. `epoch_rewards` sysvar only exists during
the epoch reward period. Therefore, the current `program_test` framework, by
default, doesn't support `epoch_rewards` sysvar. 
1. add api in `program_test` to allow mock sysvar.
2. mock  epoch rewards sysvar for sbf tests
Fixes #
> fix sbf sysvar test

- ci/test-stable.sh
ci failed on master 😢 https://buildkite.com/solana-labs/solana/builds/100516#018a1965-b386-438a-aa6e-4fc73ebe8861
seems that we need to increase the number.
```diff
-  if ((solana_program_count > 17)); then
+  if ((solana_program_count > 18)); then
```
> ci: increase solana_program_count to 18

- core/src/warm_quic_cache_service.rs
- quic-client/src/nonblocking/quic_client.rs
The cache warmer is unnecessarily sending 1 bytes long packets. The connection can be established without this. This help reduce noise and unnecessary computations through the whole network.
Instead of sending one byte long message, send 0 length message. The quic-client will establish the connection without a send.
Fixes #
> Do not do send in cache warmer -- just establish connections

- ci/stable/run-all.sh
- ci/stable/run-partition.sh
- ci/test-stable.sh
`stable-sbf` is actually failing on master, but the error is swallowed by the pipe at https://github.com/solana-labs/solana/blob/427b8b133203dd363a4b2a22018abd66ae3693d4/ci/test-stable.sh#L96
Use `pipefail` in that script and others using `PIPESTATUS`.
This will fail until https://github.com/solana-labs/solana/pull/32803 lands
Fixes #
> ci: Use pipefail for some scripts, don't use `PIPESTATUS`

- Cargo.lock
- ci/do-audit.sh
- programs/sbf/Cargo.lock
- bump rustl-webpki to 0.101.4
- ignore RUSTSEC-2023-0052 temporarily
> ci: fix audit

- core/src/validator.rs
When Blockstore open fails, the error log didn't show the specific variant of
BlockstoreError enum.
```
[2023-08-22T02:14:24.747916442Z ERROR solana_validator] Failed to start validator: "Failed to backup and clear shreds with incorrect shred version from blockstore: blockstore error"
```
Use debug format for BlockstoreError logging
Fixes #
> Improve Blockstore error logging

- runtime/src/bank.rs
- runtime/src/bank/tests.rs
As noted in https://github.com/solana-labs/solana/issues/32805, the last restart slot account will get re-written in every slot when the feature is activated, despite the account itself not necessarily changing. This is because the function that updates last restart slot writes the account every slot:
https://github.com/solana-labs/solana/blob/6521a100f76e6aeb4e9e1e43bf8ddf6675a439e0/runtime/src/bank.rs#L2118-L2138
And as confirmed with jwash [here](https://github.com/solana-labs/solana/issues/32805#issuecomment-1680692732),
> if the bank writes it to accounts db, then it gets written at the new slot, included in the delta hash, and in the accounts hash, and supersedes the prior version of the account at an older slot.
This was an oversight in the original implementation …
> Only update last restart slot sysvar if value has changed

- connection-cache/src/client_connection.rs
- connection-cache/src/connection_cache_stats.rs
- quic-client/src/nonblocking/quic_client.rs
We do not have metrics measure time spent on sending packets and when a packet is sent how much time spent on getting or creating a connection.
Added the following metrics:
* average_send_packet_us
* average_prepare_connection_us
* successful_packets
Fixes #
> improve quic-client packet send metrics

- client/src/send_and_confirm_transactions_in_parallel.rs
- rpc-client/src/spinner.rs
- tpu-client/src/nonblocking/tpu_client.rs
While working on an alternative for sending multiple transactions quickly, the solution had me passing around many fields that could be encapsulated just to print out the progress.
Rather than pass around so many fields, let's encapsulate everything needed by `set_message_for_confirmed_transactions` into a struct, and call it properly!
Fixes #
> rpc-client: Encapsulate `set_message_for_confirmed_transactions`

- cli/Cargo.toml
- client/Cargo.toml
- download-utils/Cargo.toml
- install/Cargo.toml
- metrics/Cargo.toml
- notifier/Cargo.toml
- rpc-test/Cargo.toml
https://buildkite.com/solana-labs/solana/builds/100639#018a20fc-c99a-41c6-a543-17f73499f5b6
I think we can fix it to 0.11.11 which we're using atm.
```diff
-reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
+reqwest = { version = "=0.11.11", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
```
> v1.14: ci: fix reqwest to 0.11.11

- ci/docker-rust/Dockerfile
install dependencies for #32947
(the docker images has uploaded)
- install protobuf-compiler
> ci: install protobuf-compiler to docker image

- core/src/consensus.rs
- core/src/replay_stage.rs
- programs/vote/src/vote_state/mod.rs
On replay, if validators observe a newer vote state from a frozen bank, they will adopt that vote state in favor of their local tower. This is to avoid an outdated local tower from sending out slashable votes, or in case of large divergences, having to wait forever for lockout to expire. 
However when we adopt vote state, we do not update the tower's `last_vote` field. This causes problems in situations where our fork choice does not agree with the on chain vote state. 
Consider the following:
```
[...] - 115 - 124 - 125 - 126 - 127
\
- 120 - 121 - 122 - 123
```
Previously our validator had voted on slots `124` and `126` which landed in block `127`. Currently, our validator has replayed only up to `115` and has most recently voted on `115`.
Next it receives the remaining blocks up to …
> tower: when syncing from vote state, update last_vote

- program-runtime/src/loaded_programs.rs
The `swap_remove` can disturb the assumptions about the ordering of entries in the second level index of `LoadedPrograms`.
Replaces `swap_remove` => `remove`
> Fix - Reordering in second level index of LoadedPrograms

- runtime/src/bank.rs
The feature `delay_visibility_of_program_deployment` should also trigger a flush of the `LoadedPrograms` cache.
Adds `delay_visibility_of_program_deployment` to `FEATURES_AFFECTING_RBPF` in `Bank::apply_builtin_program_feature_transitions()`.
> Fix - missing delay visibility feature triggering cache flush

- accounts-db/src/account_storage.rs
- accounts-db/src/accounts_db.rs
- accounts-db/src/append_vec.rs
- accounts-db/src/sorted_storages.rs
- accounts-db/src/tiered_storage/mmap_utils.rs
- bucket_map/src/bucket_storage.rs
- cli-output/src/cli_output.rs
- cli/src/cluster_query.rs
- cli/src/vote.rs
- core/src/shred_fetch_stage.rs
- gossip/src/cluster_info_metrics.rs
- gossip/src/contact_info.rs
- ledger-tool/src/program.rs
- local-cluster/src/cluster_tests.rs
- merkle-tree/src/merkle_tree.rs
- metrics/src/metrics.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/stake/src/config.rs
- programs/vote/src/vote_state/mod.rs
- runtime/src/serde_snapshot.rs
- runtime/src/snapshot_bank_utils.rs
- stake-accounts/src/stake_accounts.rs
- storage-bigtable/src/compression.rs
- storage-proto/build.rs
- validator/src/admin_rpc_service.rs
- validator/src/main.rs
> General cleanup

- clap-utils/src/input_parsers.rs
- clap-utils/src/keypair.rs
- clap-v3-utils/src/input_parsers.rs
- clap-v3-utils/src/keypair.rs
- cli/src/address_lookup_table.rs
- cli/src/cli.rs
- cli/src/cluster_query.rs
- cli/src/feature.rs
- cli/src/inflation.rs
- cli/src/main.rs
- cli/src/nonce.rs
- cli/src/program.rs
- cli/src/stake.rs
- cli/src/validator_info.rs
- cli/src/vote.rs
- cli/src/wallet.rs
- keygen/src/keygen.rs
- programs/bpf_loader/src/lib.rs
- remote-wallet/src/ledger.rs
- remote-wallet/src/remote_wallet.rs
- sdk/src/transaction_context.rs
- stake-accounts/src/args.rs
Another preparation for #32961.
Future versions of clippy will complain that:
> warning: usage of an Arc that is not Send or Sync
> = note: the trait Sync is not implemented
> = note: required to implement Send and Sync
> = help: consider using an Rc instead or wrapping the inner type with a Mutex
> = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
Demotes `Arc` to `Rc` around `RemoteWalletManager`, `LedgerWallet` and `TransactionAccounts`.
> Refactor - Demotes `Arc` to `Rc`.

- .github/workflows/downstream-project-spl-nightly.yml
- .github/workflows/downstream-project-spl.yml
#32983 took a big hammer and removed all downstream SPL jobs, when only the "checks" and "tests" jobs failed during CI: https://github.com/solana-labs/solana/actions/runs/5968320899/job/16191912388?pr=32982
Add back all of the tests that depend on the SDK, keep the CLI tests disabled.
Since this PR reverts a commit and then disabling two sets of jobs, deleting and then reverting this PR doesn't really work anymore, so I went with `if: false` for the steps affected by the CLI changes.
Fixes #
> CI: Add back some downstream SPL jobs

- bucket_map/src/bucket.rs
- program-runtime/src/loaded_programs.rs
- programs/system/src/system_processor.rs
- runtime/src/serde_snapshot.rs
- sdk/src/recent_blockhashes_account.rs
- sdk/src/secp256k1_instruction.rs
Continuation of #32980, preparation for #32961.
> General cleanup (Part 2)

- core/src/replay_stage.rs
- program-runtime/src/loaded_programs.rs
Programs could be deployed in a duplicate slot. Once the slot is determined to be unconfirmed, the cache should be pruned of these programs.
Added a new method to prune cache for the programs deployed in a given slot
Call the method from replay stage from duplicate unconfirmed slot handler.
Fixes #
> Prune programs deployed in duplicate unconfirmed slot

- program-runtime/src/log_collector.rs
- runtime/src/bank.rs
imo, this use of trait `From` isn't strictly needed semantically. it's actually not like a cast, rather a finalization of some stateful builder object.
also (my personal main reason), traits doesn't work nicely for rust-analyzer's call-hierarchy...
seems this was intentionally changed to use the `Into` (ie. the mirror of `From`) trait at https://github.com/solana-labs/solana/pull/10528#discussion_r1306439150
but, this pr just convert back to the original plain old inherent method taking ownership.
> Remove From<LogCollector> for Vec<String>

- poh/src/poh_recorder.rs
- rpc/src/cluster_tpu_info.rs
- send-transaction-service/src/send_transaction_service.rs
- send-transaction-service/src/tpu_info.rs
In send_transaction_service we only have tpu leader address. This made it hard to understand if the leader obtained and used for sending transactions are up-to-date to the real leader where the transaction is really landed.
Created an overload of get_leader_tpus: get_leader_tpus_with_slots to get the tpu address along with the slot. And put that information into the debug log. This information can be compared with where the the transaction confirmed to measure leader accuracy. This help us better understand the txn latency.
Fixes #
> Get slot info along tpu leader

- program-runtime/src/loaded_programs.rs
The cache retains the deployed program even though it was closed, if the deployment and close happened in the same slot.
The tombstone for closed program was not getting inserted in the cache. This allowed the cached entry for the deployed program to remain active. This PR checks if the new entry is a tombstone, and inserts it in the cache.
Fixes #
> Handle closing of the program in the same slot as deployment

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
working on improving startup time.
```
generate_index overall_us=58,730,945 (this pr)
generate_index overall_us=65,618,285 (master)
```
update dashmap in parallel instead of serial
Fixes #
> speedup populate_and_retrieve_duplicate_keys_from_startup

- programs/loader-v4/src/lib.rs
- runtime/src/bank.rs
- sdk/program/src/loader_v4.rs
- sdk/program/src/loader_v4_instruction.rs
The current encoding of the program state leaves gaps of uninitialized / undefined memory.
See #32989, #32990 and #32991.
- Replaces `is_deployed` with `status`: `Retracted`, `Deployed`, `Finalized`
- Removes the `Option<>` from `authority_address`, `None` is now expressed as status `Finalized`
- Places the `status` at the end and gives it `repr(u64)` so that there is no padding
- Adds test for the layout of the program state
- Forbids finalizing retracted programs
> Refactor - Loader v4 deployment status

- accounts-db/src/accounts_index.rs
improving startup time performance
Return value from `reset_uncleaned_roots` is never used by any callers.
Remove the return value.
This will simplify understanding the uses of `uncleaned_roots` and perhaps facilitate removing it.
Fixes #
> remove unused return value from reset_uncleaned_roots

- banks-server/src/banks_server.rs
- program-test/tests/builtins.rs
As reported in https://solana.stackexchange.com/questions/7424/why-doesnt-solana-program-test-work-with-versionedtransaction, program-test doesn't work with versioned transactions because the banks-server is trying to deserialize legacy transactions.
Pretty simple, call `Bank::try_process_entry_transactions` instead of `try_process_transactions` in banks-server, since the former takes in versioned transactions.
Fixes #
> banks-server: Support versioned transactions

- sdk/src/feature_set.rs
- turbine/src/cluster_nodes.rs
`Bank::get_leader_schedule_epoch` returns: `1 + EpochSchedule::get_epoch`. As a result, at the epoch boundaries when the propagated shred is from the next epoch, we are looking for epoch stakes for 2 epochs ahead of the root or working bank's epoch.
However, the bank structure only contains epoch stakes for one epoch ahead. This results in shreds propagated at epoch boundary having unknown epoch stakes.
Use `EpochSchedule::get_epoch` instead of  `Bank::get_leader_schedule_epoch` for turbine epoch stakes when propagating shreds.
Previous discussion on this: https://github.com/solana-labs/solana/pull/18971#discussion_r681930509
**NOTE:**
The commit effectively uses current epoch instead of next epoch for stakes.
One question is that if that may cause more dead stake which would cause holes …
> revises turbine epoch stakes for shreds propagation

- ci/do-audit.sh
We have removed `webpki` from our repo 🎉 
remove `--ignore RUSTSEC-2022-0093`
close #32933
> ci: remove --ignore RUSTSEC-2022-0093

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_api.rs
- bucket_map/src/bucket_map.rs
- bucket_map/src/index_entry.rs
Improving startup performance.
The value of a bucket map on disk needs to have PartialEq and Debug for work that is coming soon.
Fixes #
> add PartialEq and Debug to bucket map

- accounts-db/src/accounts_db.rs
Improving startup time.
We already collect all duplicate pubkeys by pubkey bin during index generation.
It is very expensive to recreate the list of unique pubkeys that exist in several slots.
```
overall_us=35 253 824 (this pr)
overall_us=57 586 789 (master)
accounts_data_len_dedup_time_us= 2 914 578 (this pr)
accounts_data_len_dedup_time_us=24 207 990 (master)
```
So, create the list of unique pubkeys while determining the pubkeys that exist in several slots.
Fixes #
> get unique keys while finding dups

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_storage.rs
We will want to re-use existing disk index files on startup.
To do this, we need to know the name of the index file, which is a u128.
Fixes #
> return file name as u128 for disk buckets

- accounts-db/src/accounts_db.rs
- accounts-db/src/read_only_accounts_cache.rs
Working on improving load time. Read cache spends a lot of time blocked on global mutex updating eviction lru queue.
update lru for read only cache if it has been long enough since last access. The idea is that entries in the read only accounts cache will fall into 2 camps: read frequently or infrequently. Frequently read items will be accessed again prior to eviction and lru will be updated (assume 50s delay from insertion to eviction). Infrequently read items will not be accessed again prior to eviction. By avoiding lru modification on every access, the common case of read cache hits is greatly improved. The only casualties will be accounts which are read twice within the time limit (100ms atm) and then evicted after 50s instead of 50.1s. The cache will still operate correctly, and the …
> update lru for read only cache if it has been long enough since last access

- Cargo.lock
- bloom/src/bloom.rs
- perf/src/perf_libs.rs
- perf/src/sigverify.rs
- program-runtime/src/prioritization_fee.rs
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- programs/bpf_loader/src/syscalls/mem_ops.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/loader-v4/src/lib.rs
- programs/sbf/build.rs
- programs/sbf/rust/secp256k1_recover/src/lib.rs
- programs/zk-token-proof/benches/verify_proofs.rs
- sdk/cargo-build-sbf/Cargo.toml
- sdk/cargo-build-sbf/src/main.rs
- sdk/cargo-test-sbf/Cargo.toml
- sdk/cargo-test-sbf/src/main.rs
- sdk/program/src/alt_bn128.rs
- sdk/program/src/program_stubs.rs
This PR is another preparation for #32961.
`saturating` and `wrapping` versions of `div` and `rem` will no longer be accepted.
Replaces them with their `checked` version.
> Fix - Upcoming `arithmetic_side_effects` lints

- sdk/src/feature_set.rs
https://github.com/solana-labs/solana/issues/26765
devnet has this feature activated already without the fixes from #32606
unfortunately. Fortunately, testnet it's now having this feature disabled
thanks to the 1.14/1.16 restart. 
In order to turn off this feature from devnet during the next devnent upgrade,
we will need to rekey this feature. 
Rekey stake_redelegate_instruction feature
Fixes #
> rekey stake_redelegate_instruction feature

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
simplifying and improving startup time
`previous_uncleaned_roots` is only used for stats and doesn't look useful.
To simplify the expensive operation of populating `uncleaned_roots`, trying to remove related data structures to simplify.
Fixes #
> remove unused previous_uncleaned_roots

- Cargo.lock
- program-runtime/src/invoke_context.rs
- programs/bpf_loader/Cargo.toml
- programs/bpf_loader/src/lib.rs
- programs/bpf_loader/src/serialization.rs
- programs/bpf_loader/src/syscalls/cpi.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/sbf/Cargo.lock
- sdk/src/transaction_context.rs
This fixes the following issues with the direct mapping feature, it has no impact on !direct_mapping code:
- `bpf_loader: direct_mapping: enforce account info pointers to be immutable` ensures that all AccountInfo pointers are not mutated. CPI looks up memory regions based on an account's data address so it can't be changed, and other pointers are locked too since there's no (legitimate) reason to ever mutate them, they point to address space setup by the program runtime.
- `bpf_loader: cpi: access ref_to_len_in_vm through VmValue` disables "caching" of vm->host address translations. Vm address space under direct mapping has some dynamic properties (CoW, changing permissions), so memory accesses must always to go through the vm.
- `direct mapping: improve memory permission tracking across …
> direct mapping: misc fixes

- accounts-db/src/accounts_db.rs
working on improving startup time.
This is not good:
```
total_slots=445660i slots_to_clean=445339i
```
add stats
Fixes #
> add stats for generate_index

- programs/zk-token-proof/src/lib.rs
Currently, the ZK Token proof program contains a check that prevents other programs from invoking the proof program as an inner call. In the earlier version of the program, we did not vision the proof program from being invoked as an inner call, so this check made sense. However, with the way the program is set up, invocation of the proof program instructions can be useful in certain applications like in https://github.com/solana-labs/solana-program-library/issues/3984. Additionally, invocation to `CloseContextState` instruction could allow the following application:
- Due to the instruction data limit, some of the zkp's for the Token22 confidential transfer instructions must be divided into pieces.
- The processor for the confidential transfer instruction currently allows "parallel" …
> [zk-token-proof] Enable proof program to be invoked as an inner call

- sdk/src/feature_set.rs
Community contribution https://github.com/solana-labs/solana/pull/32680 on Poseidon syscall is merged.
Added feature id for the syscall.
cc: @vadorovsky 
Fixes #
> Add feature ID for `enable_poseidon_syscall`

- programs/zk-token-proof/src/lib.rs
The close context state account instruction does not incure a fee. If the feature https://github.com/solana-labs/solana/issues/30620 is activated, then any native instruction that does not incure a fee will fail.
Added compute units to close account. The instruction itself performs two things:
- Check if the owner of an account (the context account) is the signer for the transaction
- Frees the account
I modeled the compute units similar to the `spl-token` close account instruction. The token close account instruction performs similar steps as the close context state account instruction here. Although the token instruction is executed as BPF, it only really performs pubkey comparison and then frees the account, so the cost should be quite similar. The token close instruction incurs about …
> [zk-token-proof] Add CUs to close account instruction

- Cargo.lock
- clap-v3-utils/src/keypair.rs
- gossip/Cargo.toml
- gossip/src/cluster_info.rs
- programs/sbf/Cargo.lock
i left these off of #33047 since they might stir contention. the remainder of compatibility changes for bumping toolchain(s) need to go in with the bump as they reference lints that the current toolchain(s) don't know about
* work around nightly ice triggered by something something `const ref` in generic context
* allow `clippy::needless_pass_by_ref_mut` to avoid false-positive ignoring trait bounds
> round two preliminaries for bumping nightly to 2023-08-25

- programs/vote/src/vote_state/mod.rs
Activated mainnet 491.
Fixes #27091
> ff cleanup: vote_state_update_credit_per_deque

- programs/loader-v4/src/lib.rs
- sdk/program/src/loader_v4_instruction.rs
Fixes #33004
Moves initialization and growth of program accounts from the "write" to the "truncate" instruction in loader-v4.
This also means that "truncate" now becomes the only instruction to deal with transfers of funds.
Additionally, "truncate" becomes fully symmetric in the sense that it not only grows and shrinks existing programs,
but also opens programs from uninitialized accounts and closes programs back into uninitialized accounts.
> Refactor - Loader-v4 grows accounts with "truncate" not "write"

- nextest.toml
these two tests 
- test_star_network_push_star_200
- test_star_network_push_ring_200
become flaky when I migrated `cargo test` to `nextest`. I guess there was a thread issue at that time, and I always forgot to send this PR 🫠. I have tested this one and seems to work in my devbox.
thanks https://discord.com/channels/428295358100013066/560503042458517505/1146486337218814022 for reminding me of this one
> ci: allocate more threads for gossip tests

- accounts-db/src/accounts_db.rs
the setup part of the test introduced at https://github.com/solana-labs/solana/pull/7415#discussion_r1311294502 is fragile against rustc's abi-related changes.
For example, hashing change is needed due to updating rustc to 1.72: https://github.com/solana-labs/solana/pull/32961#discussion_r1311296564 
Use `repr(C)` to make test byte pattern generation more resilient to any abi changes.
i confirmed locally the updated hash in this pr is emitted now with both rust 1.69 and 1.72.
also some comment clarification is done for future me and others. :)
> Add #[repr(C)] for more future-proof byte mangling

- Cargo.lock
- core/src/window_service.rs
- gossip/Cargo.toml
- gossip/src/cluster_info.rs
- gossip/src/crds_gossip.rs
- gossip/src/duplicate_shred.rs
- gossip/src/duplicate_shred_handler.rs
- ledger/src/blockstore.rs
- ledger/src/blockstore_meta.rs
These are multiple last_shred_in_slot shreds and
coding shreds with conflicting erasure metas.
These scenarios are detected and stored in blockstore, but never sent to gossip or the state machine.
Fix the plumbing so these are sent to gossip and the state machine. 
Split from #32862
> send duplicate shred proofs for conflicting shred scenarios

- accounts-db/src/in_mem_accounts_index.rs
- bucket_map/src/bucket.rs
- bucket_map/src/bucket_api.rs
- bucket_map/src/bucket_map.rs
Reducing startup time by reducing index generation time.
When sorting before inserting into disk index, keep index to data to insert instead of copying values (such as pubkeys) around.
This also allows us to keep the data().len() around at a higher level. When we later deal with duplicates, we will have the data length already and not have to look it up again for each duplicate account.
Fixes #
> rework sorting during generate_index

- core/src/shred_fetch_stage.rs
- ledger/src/shred.rs
- sdk/src/feature_set.rs
- turbine/src/cluster_nodes.rs
No longer need to check and filter out Merkle shreds.
Removed outdated check for feature activation.
> removes outdated check for merkle shreds

- accounts-db/src/pubkey_bins.rs
pubkey to bin calculation can be done with shift in a cheaper way.
use shift for pubkey bin calculation
Fixes #
> use shift for pubkey to bin calculation

- geyser-plugin-manager/src/geyser_plugin_manager.rs
segv while running geyser plugin manager tests. didn't quite get to root cause before stumbling on a fix. some combination of...
* `unsafe` self-`dlopen()`
* `dlclose()` racing
* rust's test suite `clone(2)`s each test function with a shared address space
* genericize dummy plugin generator (to get a win while i was pounding my head against the desk)
* switch to `libloading`'s alleged safe self-`dlopen()` method
> fix memory corruption in geyser plugin manager tests with recent toolchains

- accounts-db/src/account_storage.rs
- accounts-db/src/accounts_db.rs
- accounts-db/src/ancient_append_vecs.rs
- accounts-db/src/append_vec.rs
- accounts-db/src/rolling_bit_field.rs
- entry/src/poh.rs
- runtime/src/bank/tests.rs
- sdk/program/src/epoch_rewards.rs
tldr: rust 1.73 changed panic message format, and some of tests depended on it. update them to work with both <1.73 and >1.73.
split off from #32961 as this isn't strictly coupled with the rust update pr.
> Make should_panic tests compatible with 1.73+ panic format

- ci/stable/run-all.sh
- ci/stable/run-partition.sh
- ci/test-stable.sh
`-Zunstable-options` can't be used since 1.70.0 (https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#enforced-stability-in-the-test-cli)
a possible solution, `--timings=json`, is still unstable atm 😢 
remove unstable options for stable tests atm. we will lose some test report. For unblocking our master CI, I still would like to have this stopgap first.
I will try to finish https://github.com/solana-labs/solana/issues/33102 soon!
> ci: remove unstable options for stable tests

- zk-token-sdk/src/instruction/transfer/with_fee.rs
- zk-token-sdk/src/instruction/transfer/without_fee.rs
- zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
Currently, on the ciphertext validity proof, if the auditor ElGamal public key is an all-zero key, the proof is rejected even if the algebraic relation holds. This was put in for security purposes since an ElGamal public key should never really be all zero. However, for the token application, if the auditor feature is turned off, then the proof is indeed generated with respect to the all zero public key. Therefore, currently the transfer proof always fails if the auditor feature is turned off.
Update the verification logic so that the proof does not immediately reject if the auditor public key is all zero.
This is a security fix that will unfortunately need to be backported to 🙏 .
Fixes #
> [zk-token-sdk] Allow all zero auditor pubkey in proofs

- accounts-db/src/accounts_db.rs
Index generation time is often an issue.
log rate in index generation metric to get a quick look at performance without waiting sometimes an hour or more to get a final answer.
example:
```
generating index: 2791/428550 slots... (1395/s)
generating index: 139027/428550 slots... (34756/s)
generating index: 239371/428550 slots... (39895/s)
```
Fixes #
> add rate info to generate index log

- core/src/shred_fetch_stage.rs
This function used to contain feature gate activation checks that required access to a bank. Those checks have been cleaned up, so we no longer need access to a full Bank. Also see https://github.com/solana-labs/solana/pull/33078#issuecomment-1701081550.
Rather, we can momentarily get a Bank from BankForks, calculate the necessary results and then drop the Bank along with the BankForks read lock.
> Update ShredFetchStage::modify_packets to drop root bank quicker

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
- accounts-db/src/secondary_index.rs
- validator/src/admin_rpc_service.rs
2 prs cause secondary indexes to take a long time to generate.
revert them
Fixes #
> Revert "Add an RPC API that can query the list of Top N secondary index keys and their sizes (#28887)"

- runtime/src/bank.rs
There was a bug in RBPF v0.6.0 which caused the `BuiltinProgram::eq()` to always return `false`. Thus, the behavior we stabilized implicitly in v1.16 is that the `if` condition is always `true`.
Removes the `if` block around the overwriting of the `environments`.
> Fix - Superfluous `if` condition for overwriting `environments` in feature activation code

- docs/src/api/methods/_getMultipleAccounts.mdx
- list of pubkeys is required:
```bash
curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
{
"method": "getMultipleAccounts",
"params": [],
"id": "1"
}'
{"jsonrpc":"2.0","error":{"code":-32602,"message":"`params` should have at least 1 argument(s)"},"id":"1"}
```
- encoding defaults to `base64` if not provided: https://github.com/solana-labs/solana/blob/69336ab5daa31e659ed189c955ecd5002cbff308/rpc/src/rpc.rs#L445
> Correct docs for getMultipleAccounts RPC

- core/src/banking_trace.rs
When writing my investigation utility in #32843 I came across these fields/types being private.
This makes is impossible to read a trace file outside `banking_trace.rs` and use the deserialized info.
- Make fields in `TimedTracedEvent` `pub`
- Make `TracedEvent` type `pub`
Fixes #
> Make TimedTracedEvent accessible outside banking_trace.rs

- core/src/cache_block_meta_service.rs
Sub-function doesn't need an `Arc`; this is pretty inconsequential since the caller will just drop the `Arc<Bank>` shortly after, but still more proper
> Demote Arc<Bank> parameter to &Bank

- validator/src/bin/solana-test-validator.rs
https://github.com/solana-labs/solana/pull/32174 broke the `getInflationReward` RPC endpoint on solana-test-validator because TestValidator features are always on by default, and the `enable_partitioned_epoch_reward` feature moves the location of stake rewards without updating RPC to figure out where they are. This would be a problem on a real cluster as well, but only if the feature is activated before RPC/client support is implemented
Because client support for partitioned epoch rewards isn't yet designed (as per https://github.com/solana-foundation/solana-improvement-documents/pull/15#issuecomment-1570321524), slap a bandaid on solana-test-validator that deactivates the feature in genesis.
Fixes #33098
> Boot solana-test-validator without enable_partitioned_epoch_reward feature

- docs/src/api/methods/_getStakeActivation.mdx
- rpc/src/rpc.rs
`getStakeActivation` returns incorrect data for previous epochs because it depends on a stake account's *current* Delegation, which may include past rewards, splits, or merges.
Return an error when a submitted `epoch` parameter is not the current epoch. Users should just remove the 
I updated the docs to notate the config-parameter field as "deprecated", but open to better ways to document the change.
Fixes #26622
> rpc: turn off getStakeActivation epoch parameter

- sdk/program/src/loader_v4.rs
Need convenient methods to construct loader-v4 instructions. These will be useful in CLI and other places.
Add the constructors.
Fixes #
> Add loader-v4 instruction constructors

- accounts-db/src/accounts_db.rs
`unsafe { transmute }` in the test, as written, is undefined behavior. And, I think, we actually see the compiler generating different code for it as we are changing the generated hashes when we upgrade the compiler. It happened during upgrade to 1.67.1:
https://github.com/solana-labs/solana/pull/29947
And the hashes changed again in 1.71.
---
Same as https://github.com/solana-labs/solana/pull/33082, but numbers are sequential.
> accounts-db: test_hash_stored_account: Avoid UB.

- core/src/consensus.rs
- core/src/replay_stage.rs
- local-cluster/src/integration_tests.rs
- local-cluster/tests/local_cluster.rs
After restart, any slots that were previously marked duplicate will not be marked invalid in fork choice.
When processing the result of replay (dead or frozen), also check if blockstore contains a duplicate proof. If it does, let the state machine know. 
Split from #32862
> replay: send duplicate proofs from blockstore to state machine

- CONTRIBUTING.md
The Rust and TOML syntax highlighting wasn't working before.
Fixes the syntax highlighting for two code blocks.
> docs(contributing): fix syntax highlighting

- rpc/src/optimistically_confirmed_bank_tracker.rs
[Comment](https://github.com/solana-labs/solana/pull/33062#discussion_r1309490595) points out prioritization_fee_Cache should be finalized when oc-ed bank is frozen. 
- move `finalize_priority_fee()` to when bank is frozen.
related to #32692
> finalize prioritization_fee_cache after oc-ed bank is frozen

- accounts-db/src/accounts_hash.rs
https://doc.rust-lang.org/std/io/struct.BufWriter.html#impl-Write-for-BufWriter%3CW%3E
> fn write(&mut self, buf: &[u8]) -> Result<usize>
> Write a buffer into this writer, returning how many bytes were written. Read more
> 
write() api may do partial write of `hash` and hit the assert and crash.
Use write_all instead
Fixes #
> Use `write_all` for binned account hash file writes 

- .github/workflows/client-targets.yml
our client_targets is failed on master now. I think we should trigger the pipieline when the cargo files changes so that we can catch errors earlier.
https://github.com/solana-labs/solana/actions/runs/6094904422
> ci: trigger client_targets pipeline when the cargo file changes

- Cargo.lock
- programs/sbf/Cargo.lock
- runtime/Cargo.toml
- runtime/src/accounts_background_service.rs
`PrunedBanksRequestHandler::handle_request()` is only meant to be called from AccountsBackgroundService, but it is public so that bank tests can call it. Now that we have DCOU, we no longer need for this function to be pub for non-tests.
`PrunedBanksRequestHandler::handle_request()` is only public when in dev context.
> PrunedBanksRequestHandler::handle_request() is only pub with dcou

- accounts-db/src/cache_hash_data.rs
When dropping CacheHashData, we lock the mutex holding the unused preexisting cache files for the duration of the function. Since this field can be shared, this may block others that are holding the same Arc, slowing down their `drop`.
Another potential issue, since we delete these preexisting files *but do not remove them* from the HashSet, another instance that shares the HashSet would still have PathBufs to the now-deleted files.
Take the inner HashMap of preexisting files at the beginning of `drop` and immediately release the mutex.
> Takes inner HashSet when dropping CacheHashData

- runtime/src/bank.rs
The filtering of valid programs does not include programs owned by loader-v4.
Include the loader_v4 to the list of valid program owners.
Fixes #
> Check loader-v4::id() as a valid program owner

- accounts-db/src/accounts_db.rs
ShrinkCandidates is a type. The type is currently `HashMap`. Many places in code use
`let v = ShrinkCandidates: HashMap::new()`
replace with:
`let v = ShrinkCandidates::new()`
to decouple the types.
Fixes #
> remove coupling of ShrinkCandidates to HashMap

- Cargo.toml
Canaries should build the validator with debug info. Once the profile is added a separate PR to the cluster ops repo will update the canary build script to use the new profile.
@steviez anything else we should include in this profile to facilitate debugging?
> Add release-with-debug profile

- geyser-plugin-manager/src/geyser_plugin_manager.rs
- sdk/program/src/serde_varint.rs
Improve plugin load/reload unit tests
1. Test loading different plugin of the same name. TestPlugin2 replacing TestPlugin1
2. Return the real config name in the test instead of hard coded DUMMY_CONFIG.
Fixes #
> Improve plugin load/reload unit tests

- accounts-db/src/accounts_db.rs
- accounts-db/src/ancient_append_vecs.rs
Improving startup time.
Now that we only have 1 storage per slot, it is more efficient to not hold an `Arc` to the append vec in the shrink list.
During index generation, especially with incremental snapshots, we can end up with say 60M duplicate pubkeys across all 432k slots. This results in a lot of record keeping and inefficient `HashMap` stuffing of almost every `(Slot, Arc<AppendVec>)`. Getting the append vecs is not fast. They can be looked up in the bg thread by shrink itself. A slot is sufficient to request a shrink.
Just hold a `HashSet<Slot>` instead of a `HashMap<Slot, Arc<AppendVec>>`
Fixes #
> ShrinkCandidates only holds slot

- programs/zk-token-proof/src/lib.rs
The compute units for the proof program instructions are hardcoded into the program execution, which makes them not accessible by outside programs.
Add publicly accessible variables for the compute units.
This is a follow-up to https://github.com/solana-labs/solana/pull/33042#discussion_r1310650277.
Fixes #
> [zk-token-proof] Add public compute unit variables for instructions

- accounts-db/src/accounts_db.rs
Fix assert on canaries.
Parallel iter can start a shrink, then we ask for a storage from a slot, expecting shrink to not be allowed to be active.
```
panicked at 'assertion failed: self.no_shrink_in_progress()', accounts-db/src/account_storage.rs:78:9)
```
Introduced here:
ShrinkCandidates only holds slot (#33173)
Get all stores for shrinks prior to starting shrinking.
Fixes #
> in shrink, get stores prior to shrink starting

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
- accounts-db/src/bucket_map_holder.rs
- accounts-db/src/bucket_map_holder_stats.rs
- accounts-db/src/in_mem_accounts_index.rs
Speeding up generate index/startup time.
We spend a ton of time copying data.
Add a metric for that time.
Fixes #
> stat for time spent copying generate index contents

- core/src/banking_stage/transaction_scheduler/mod.rs
- core/src/banking_stage/transaction_scheduler/transaction_packet_container.rs
- core/src/banking_stage/transaction_scheduler/transaction_priority_id.rs
- core/src/banking_stage/transaction_scheduler/transaction_state.rs
- core/src/banking_stage/transaction_scheduler/transaction_state_container.rs
Breaking out of #32981.
Central scheduling BankingStage needs a place to store transactions while they are pending scheduling/processing. 
- Add `TransactionPriorityId` - which ties together unique transaction ID and priority. This is what lives in our priority queue, rather than packets/transactions directly.
- Add `TransactionStateContainer` - responsible for priority ordering and storing of transactions (see doc comments for details on this)
Fixes #
> TransactionScheduler: TransactionStateContainer

- rpc/src/optimistically_confirmed_bank_tracker.rs
- rpc/src/rpc.rs
- runtime/src/prioritization_fee.rs
- runtime/src/prioritization_fee_cache.rs
Duplicated banks can add inconsistent data to prioritization_fee_cache.
- purge duplicated bank's priority_fee from cache during finalization
- add test for the described scenario
- add metrics counts to monitor such occurrences 
Fixes #
> purge duplicated bank prioritization fee from cache

- core/src/repair/ancestor_hashes_service.rs
- core/src/repair/quic_endpoint.rs
- core/src/repair/serve_repair.rs
- core/src/repair/serve_repair_service.rs
- core/src/validator.rs
Working towards migrating repair service to QUIC.
The commit implements server-side of repair using QUIC protocol.
UDP repair requests are adapted as `RemoteRequest` and sent down the same channel as remote requests arriving over QUIC, and the rest of the server code is update to process over `RemoteRequest` type.
> serves remote repair requests from QUIC endpoint

- accounts-db/src/accounts_hash.rs
#33174
use mmap file instead of `BufWriter`. The temp file is mmapped for reading anyway.
This avoids the `BufWriter` api completely.
Fixes #
> rework accounts hash calc dedup to avoid kernel file error

- accounts-db/src/cache_hash_data_stats.rs
merge_us is not used.
get rid of `merge_us`
Fixes #
> remove unused stats

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_hash.rs
- accounts-db/src/cache_hash_data.rs
POD (plain 'o data) types do not need a `new()` function. It's slightly less readable than constructing the type directly, and it's an unnecessary function call.
CalculateHashIntermediate and CumulativeOffset are both offenders.
Removes `new()` from POD CalculateHashIntermediate and CumulativeOffset
> Removes `new()` from POD CalculateHashIntermediate and CumulativeOffset

- .github/workflows/release-artifacts.yml
our Windows build failed on v1.14 branch
(https://github.com/solana-labs/solana/actions/runs/6123962073/job/16622993534)
the default llvm version is 16 in the window image atm. reinstall it with 15.
> v1.14: ci: use llvm 15 for Windows build

- cli-output/src/cli_output.rs
- cli/src/vote.rs
- programs/vote/benches/process_vote.rs
- programs/vote/src/vote_state/mod.rs
- rpc/src/rpc.rs
- sdk/program/src/vote/state/mod.rs
- sdk/src/feature_set.rs
Re-submission of the timely_vote_credits feature, with a guard around credits accounting to ensure that credit counting is not altered before the feature is enabled.
> Implement timely vote credits feature.

- Cargo.lock
- ci/stable/run-partition.sh
- client-test/Cargo.toml
- client-test/tests/client.rs
https://github.com/solana-labs/solana/issues/33102
nextest runs tests individually. using a static variable in solana-client-test will make these tests failed.
use random ports to test. (for now I guess it will be fine. if we have hundreds of tests here, I think we need to use another solution to avoid port number collision)
(there was a discussion about pre-defined const port numbers https://github.com/solana-labs/solana/pull/29255/commits/2436fe10bdfef7bc2586a8bf7699c631aa540d76)
> ci: move solana-client-test to nextest

- clap-v3-utils/src/input_parsers.rs
- clap-v3-utils/src/keygen/derivation_path.rs
- clap-v3-utils/src/keygen/mnemonic.rs
- clap-v3-utils/src/keygen/mod.rs
- clap-v3-utils/src/keypair.rs
The behavior of clap `ArgMatches::value_of` and `ArgMatches::is_present` in clap v2 and v3 are different making it hard to upgrade existing Solana cli tools (in particular the token-cli) from using clap v2 to clap v3.
The behavior of `ArgMatches::value_of` differs in clap v2 and v3 as follows:
- In v2, if `ArgMatches::value_of` succeeds in retrieving the argument say `arg`, then it returns `Some(arg)`. If it fails in any other way, it returns `None`.
- In v3, if `ArgMatches::value_of` succeeds in retrieving the argument, then it returns `Some(arg)`. If the queried argument id is valid (it was declared with `Arg::new(...)` when defining the command), but it was not provided by the user, the it returns `None`. If the argument id is not valid, then it panics.
The `ArgMatches::is_present` has …
> [clap-v3-utils] Add replace deprecated `value_of` and `is_present` with `get_one` and `contains_id`

- bench-tps/src/bench.rs
- bench-tps/src/keypairs.rs
- bench-tps/src/main.rs
- bench-tps/tests/bench_tps.rs
- dos/src/main.rs
When padding program is used the current default limit of 30KB is insufficient because program itself takes 28KB.
This PR increases loaded accounts data size limit when used with padding program.
> Increase loaded accounts data size when padding program is used

- ledger-tool/src/program.rs
- program-runtime/src/loaded_programs.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v4/src/lib.rs
- runtime/src/bank.rs
- runtime/src/bank/tests.rs
The programs might get unloaded from the cache due to cache overflow. The current code re-verifies these programs when reloaded. This is not needed if the runtime environment hasn't changed.
Do not re-verify the unloaded programs if the environment hasn't changed.
Fixes #
> Do not unnecessarily re-verify unloaded program

- docs/src/developing/on-chain-programs/developing-c.md
- docs/src/developing/on-chain-programs/developing-rust.md
- program-runtime/src/compute_budget.rs
- programs/bpf_loader/src/syscalls/mod.rs
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
- programs/sbf/build.rs
- programs/sbf/c/src/remaining_compute_units/remaining_compute_units.c
- programs/sbf/rust/remaining_compute_units/Cargo.toml
- programs/sbf/rust/remaining_compute_units/src/lib.rs
- programs/sbf/rust/remaining_compute_units/tests/lib.rs
- runtime/src/bank.rs
- sdk/program/src/compute_units.rs
- sdk/program/src/lib.rs
- sdk/program/src/program_stubs.rs
- sdk/program/src/syscalls/definitions.rs
- sdk/sbf/c/inc/sol/compute_units.h
- sdk/sbf/c/inc/sol/inc/compute_units.inc
- sdk/sbf/c/inc/solana_sdk.h
- sdk/src/feature_set.rs
Instructions may want to maximise their use of the compute budget, without risking going over budget. To do so, they ought to be able to inspect the current budget consumed.
Implement a syscall that allows SBF programs to make queries of `sol_remaining_compute_units` at arbitrary points in execution.
- Fixes #18134
- Rebased revival of #18227 (note that I dropped a - it seemed to me - unrelated change to the cost of `sol_log_compute_units`)
> sdk, programs/bpf_loader: add sol_remaining_compute_units syscall

- accounts-db/src/accounts_db.rs
speeding up index generation on startup
go from 2 passes 1 through each account in each append vec
Fixes #
> single pass through each storage to populate info

- accounts-db/src/accounts_db.rs
Speeding up accounts hash calculation.
approx count of an append vec is not set at load time. This is a problem because some algorithms need to know how many entries are in a storage as opposed to how many "alive" items are in an append vec.
For example, when scanning append vecs for hash calculation, if we know the upper bound of how many accounts are in an append vec, then we can plan ahead better.
Fixes #
> set approx store count at generate index time

- accounts-db/src/accounts_db.rs
speeding up index generation at startup
`&Slot` is not helpful to pass. Change to `Slot`
Fixes #
> generate index: fn arg: &Slot -> Slot

- docs/src/running-validator/vote-accounts.md
Now that https://github.com/solana-labs/solana/issues/29361 is enabled on all networks, it's not possible to update commissions in the second half of epochs, but the docs don't mention that.
Mention it!
Fixes #
> docs: Clarify when validator commission can be set

- bench-tps/src/bench.rs
CU budget is not specified when padding program is used. Default is 200k, the block limit is 48M. 
This becomes a limiting factor: tps with padding=0 is 3 times less than tps without padding program (`leader_slot_transaction_errors.would_exceed_max_block_cost_limit` metric)
Specify budget when use padding.
> specify compute budget when padding program is used

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
Speeding up index generation at startup.
`StorageSizeAndCount` is undercounting and ignoring dead accounts of several varieties. Also, further optimizations will change how we iterate the accounts in an append vec. It is better to populate storage size and count further downstream than it is currently calculated.
Populate `StorageSizeAndCount` further downstream.
Fixes #
> gen idx: refactor StorageSizeAndCount population

- accounts-db/src/accounts_index.rs
Speeding up index generation at startup.
Existing code removes vectors that are empty before iterating. This is unnecessarily wasteful. First, unlikely to have vectors that are empty. Second, we can just skip them during iteration. This simplifies everything.
Remove unnecessarily complicated code.
Fixes #
> stop removing empty bins during index generation

- programs/stake/src/stake_instruction.rs
#31007 removed overrides from `mock_process_instruction()`, but a stake-redelegate test still has a sysvar cache override block. This is because it is mutable and mutated, so doesn't alert the compiler that it is unused.
The lingering block is confusing to people reading this test to understand how to handle sysvars in stake tests.
Remove unused block
> Remove unused test code

- sdk/cargo-build-sbf/src/main.rs
when I tried to migrate tests in `solana-cargo-build-sbf` to nextest. I found that we don't check the proper path before actually removing it
check `source_path` before removing it.
> check source_path before delete it

- cost-model/src/cost_tracker.rs
- cost-model/src/transaction_cost.rs
It is a bug to include Loaded_accounts_data_size_cost to Simple Vote transaction; if feature gate #30657 is activated, each vote transaction will have ~16K more CUs (vote tx does not have compute_budget instructions), therefore resulting less votes in block. Ideally vote should have stable cost, if not static.
It needs to be BP
- sum vote cost differently.
Fixes #
> loaded accounts data size cost does not apply to vote transaction

- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- runtime/src/bank.rs
- sdk/src/feature_set.rs
`new_warmup_cooldown_rate_epoch` is wastefully recomputed once for each of ~600k stake accounts at epoch boundary. 
* moved `new_warmup_cooldown_rate_epoch` outside iterators and for loops.
* also removed `NewWarmupCooldownRateEpoch` trait which is unnecessary and verbose.
> moves new_warmup_cooldown_rate_epoch outside iterators and for loops

- .buildkite/scripts/build-stable.sh
- ci/stable/run-partition.sh
- nextest.toml
move solana-cargo-build-sbf to nextest for
- easier managing
- get the test result
(we finally get rid of the `DONT_USE_NEXTEST_PACKAGES` list 🎉 )
> ci: move solana-cargo-build-sbf to nextest

- accounts-db/src/accounts_hash.rs
We use `unsafe` blocks to read/write data in the various accounts hash files. That's not always needed.
`MmapAccountHashesFile::read()` is one of those.
Since `Hash` is `Pod`, we can use `bytemuck::cast_slice()` instead of `unsafe`.
> Refactors out `unsafe` from MmapAccountHashesFile::read()

- accounts-db/src/cache_hash_data.rs
We use `unsafe` blocks to read/write data in the various accounts hash files. That's not always needed.
The `Header` type for cache hash data files is written-to and read-from disk, and we use `unsafe` blocks for that. But we don't need to.
Derive `Pod` for `Header` and refactor all of its `unsafe` blocks to use `bytemuck`.
> Refactors `unsafe` out of CacheHashDataFile's header

- programs/loader-v4/src/lib.rs
The program deployment fails when using loader-v4.
The truncate instruction sets the deployment slot for the program to the current slot when the buffer is being initialized. The deploy instruction checks if `DEPLOYMENT_COOLDOWN_IN_SLOTS` have elapsed since the last deployment. `DEPLOYMENT_COOLDOWN_IN_SLOTS` is set to 750, so the deployment fails (since the CLI sends truncate and deploy instructions in quick succession).
Taking a step back, the truncate instruction should not be setting the deployment slot when the buffer is being initialized. It should only be set at the time of program deployment.
Fixes #
> Set loader-v4 program deployment slot at actual deployment

- programs/loader-v4/src/lib.rs
The upgrade/redeployment using temporary buffer fails for loader-v4 programs when the new program is larger than the current program.
As part of program upgrade, the loader transfers necessary lamports from the temporary buffer account to the program account. The calculation of the required lamports, and transferred lamports is incorrect. That resulted into transfer of 0 lamports the the program account resulting in underflow of account balance.
Fixes #
> Fix lamport calculation and transfer for loader-v4 program upgrade

- Cargo.lock
- cli/Cargo.toml
- cli/src/lib.rs
- cli/src/program.rs
- cli/src/program_v4.rs
- sdk/program/src/loader_v4.rs
Missing methods to construct and send RPC messages to use loader-v4 program management commands.
- Add methods to construct and send the commands
- Add unit tests
- Pending for a future PR: CLI front-end that describes the CLI commands and calls these new methods.  
Fixes #
> Processors to compile and send LoaderV4 CLI commands

- Cargo.lock
we missed the syn version bumping for test-case cuz they are created at the same time. (#33285 #33286 )
fix it
> bump syn to 2.0.37 for test-case

- accounts-db/src/accounts.rs
- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_file.rs
- accounts-db/src/append_vec.rs
- runtime/src/bank.rs
The program owners pubkeys are constant, no need to reconstruct the Vec<Pubkey> and Vec<&Pubkey> each time this function runs (every time we execute transactions).
Make a const array and remove an unnecessary layer of indirection by changing `&[&Pubkey]` (slice of pubkey references) to `&[Pubkey]` (slice of pupkeys).
> Make program owners a const array instead of Vec<_>

- ledger-tool/src/main.rs
value_t!() macro and .unwrap_or() are more succinct than if/else blocks, and the value_t!() macro handles parsing values from strings.
> ledger-tool: Cleanup argument parsing logic

- ledger-tool/src/main.rs
These path arguments are Option<Path>, and if left as None, then a TempDir will be used. However, excessive TempDir use can result in a tmpfs filling up. So, explicitly set paths to avoid this potential error condition.
Update defaults for `accounts`, `graph`, and `create-snapshot` command; `verify` already had good default set.
Given where v1.14 branch is at the moment, this is a targeted backport of https://github.com/solana-labs/solana/pull/29975 and https://github.com/solana-labs/solana/pull/30707. I think these changes are worth backporting at this point given how critical `solana-ledger-tool` is during irregular operations. For testing, I reran each of these commands and confirmed that items moved underneath `--ledger` from `/tmp/`
> ledger-tool: Set default paths for accounts index and hash cache

- Cargo.lock
- accounts-db/src/accounts_db.rs
Speeding up startup/generate_index.
approx account count is set when loading an append vec.
If the same pubkey exists in an append vec twice, `generate_index` filters the earlier entries out.
There wasn't a good test for this. And the implementation is changing for performance.
Turns out that if there are duplicate pubkeys in the same append vec, recent changes to `generate_index` would have set the approximate stored count too low, not counting the ignored earlier duplicates.
Add test to verify behavior when there are duplicate pubkeys within the same slot.
Change to assert the approximate number of accounts instead of setting it incorrectly.
Fixes #
> add test for duplicates in generate_index and fix approx stored count

- banking-bench/src/main.rs
- core/benches/banking_stage.rs
- core/src/banking_stage.rs
- core/src/tpu.rs
- core/src/validator.rs
Will need a way to switch between block production modes.
Currently only one variant, so no effect.
- Pass `BlockProductionMethod` into `BankingStage::new` and `BankingStage::new_num_threads`
- Pipe the config from `Validator -> Tpu -> BankingStage`
Fixes #
> TransactionScheduler: Pipe BlockProductionMethod

- accounts-db/src/accounts_db.rs
- accounts-db/src/accounts_index.rs
speeding up startup/generate index.
We currently put everything from the append vec into a hashmap to eliminate duplicate pubkeys from the same slot.
This should no longer be happening in the 100% common case. We only populate append vecs during write cache flushing. We clean during write cache flushing. Plus, the write cache only holds a single entry per pubkey so we'll never write the same pubkey multiple times in the same append vec. However, the append vec format supports it.
So, we must still protect against it.
We can delay the check until we have binned up the data much lower in the input process. This has an improvement in performance.
Later, we can go ahead and attempt to insert into the hashmap (in the background) and then deal with the duplicates we found after the disk index …
> in gen index, stop using big hashmap

- cli/src/clap_app.rs
- cli/src/cli.rs
- cli/src/program_v4.rs
We need a loader-v4 CLI command front-end for testing PRv2 until we have a cargo registry interface which speaks the cargo "sparse" protocol so that people can use `cargo publish` directly.
Add the CLI subcommands, description and integrate to the processors for loader-v4.
Fixes #
> Implement CLI front-end for loader-v4 commands

- programs/sbf/Cargo.lock
- sdk/program/Cargo.toml
For solana-program, array-bytes is only used in the tests
> program: move array-bytes to dev-dependencies

- core/src/banking_stage/scheduler_messages.rs
- core/src/banking_stage/transaction_scheduler/in_flight_tracker.rs
- core/src/banking_stage/transaction_scheduler/mod.rs
For scheduling work to consume we want to perform load balancing. We ideally want to balance the number of CUs and num txs between the threads evenly.
- Add `InFlightTracker` which tracks batches (num_txs, num_cus) per thread.
- Implemented Display for `TransactionBatchId` and `TransactionId` for better and easier error messages
Fixes #
> TransactionScheduler: InFlightTracker

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
The JIT in RBPF can create misaligned stack frames, which on its own is fine.
However, once it calls into Rust code which for example runs SIMD code it needs the stack to be 16 byte aligned again.
See: https://github.com/solana-labs/rbpf/releases/tag/v0.6.1
Fixes #32940
> Bump solana_rbpf to v0.6.1

- bucket_map/src/bucket_map.rs
We want to re-use index files on restart.
Prepare to conditionally wipe folder of index files on drop.
Fixes #
> conditionally erase folders on drop of `BucketMap`

- bucket_map/src/bucket_storage.rs
- vote/src/lib.rs
https://buildkite.com/solana-labs/solana/builds/101939#018aaf88-dadc-4ea1-a104-633b04ee26d1
```
error: lint `clippy::integer_arithmetic` has been renamed to `clippy::arithmetic_side_effects`
--
  | --> vote/src/lib.rs:2:10
  | \|
  | 2 \| #![allow(clippy::integer_arithmetic)]
  | \|          ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `clippy::arithmetic_side_effects`
```
change clippy allow
Fixes #
> fix clippy error

- .github/workflows/downstream-project-spl.yml
- cli/src/cli.rs
- cli/src/stake.rs
- cli/tests/stake.rs
- programs/stake/src/stake_instruction.rs
- programs/stake/src/stake_state.rs
- runtime/tests/stake.rs
- sdk/src/feature_set.rs
- tokens/src/arg_parser.rs
- tokens/src/args.rs
- tokens/src/commands.rs
- tokens/src/lib.rs
- tokens/src/main.rs
- tokens/src/stake.rs
Stake split still contains some brittle logic.
Update tests to assert that active stake is consistent across split
Add feature to make rent-exempt handling consistent
> Make active stake consistent in split

- bucket_map/src/bucket_storage.rs
working on speeding up startup & generate index.
we want to reuse existing disk index files.
Allow individual disk buckets to optionally delete on drop. Data buckets will always do this.
Resized index files will drop.
New index buckets will NOT drop once we get everything hooked up.
Bucket files loaded on restart will NOT drop once we get everything hooked up.
Fixes #
> drop disk index bucket files on drop by default

- bucket_map/src/bucket.rs
- bucket_map/src/index_entry.rs
working on speeding up startup & generate index.
we want to reuse existing disk index files.
`add occupy_if_matches()` will be used to inspect disk index file data and occupy the entry if disk already matches. This will be used shortly.
Fixes #
> add occupy_if_matches to bucket map

- docs/src/api/methods/_simulateTransaction.mdx
The `simulateTransaction` rpc method docs are unclear about which accounts encoding will be the fallback for `jsonParsed`
Corrected docs to state the correct fallback encoding of `base64` as the [fallback encoding](https://github.com/solana-labs/solana/blob/cfd0a00ae2ba85a6d76757df8b4fa38ed242d185/rpc/src/rpc.rs#L3763-L3765) when [no json parser was found](https://github.com/solana-labs/solana/blob/cfd0a00ae2ba85a6d76757df8b4fa38ed242d185/account-decoder/src/parse_account_data.rs#L98-L100).
Fixes #32964
> [docs] clarified `jsonParsed` fallback encoding for `simulateTransaction`

- program-runtime/src/compute_budget.rs
- programs/bpf_loader/src/lib.rs
- programs/loader-v4/src/lib.rs
- runtime/src/bank/tests.rs
While refactoring compute_budget, realized its `heap_size` doesn't have to be `Option` since the loader _always_  `unwrap_or(solana_sdk::entrypoint::HEAP_LENGTH)`. May as well default it to HEAP_LENGTH to streamline the logic. 
- Remove `Option`, using `solana_sdk::entrypoint::HEAP_LENGTH` as default.
Fixes #
> compute_budget heap_size does not have to be optional

- rpc/src/optimistically_confirmed_bank_tracker.rs
... about where to put optimistic-confirmation functionality
On multiple occasions, we have added functionality to be executed on optimistic confirmation to the wrong place in OptimisticallyConfirmedBankTracker.
https://github.com/solana-labs/solana/blob/525e59f01a7dcc5905f433f1fde110db55fdb876/rpc/src/optimistically_confirmed_bank_tracker.rs#L279-L280
^ intuitively seems right; however, notifications here do not guarantee that a Slot has been replayed. Most of the time, we need to verify both that this node has seen the optimistic-confirmation threshold met by the cluster *and* that this node has finished replaying the Slot.
Add a comment to help forestall this mistake in the future
> Add comment to OptimisticallyConfirmedBankTracker

- cli-output/src/cli_output.rs
- cli/src/cli.rs
- cli/src/cluster_query.rs
- cli/src/stake.rs
- cli/src/vote.rs
Rewards data for `solana vote-account` and `solana stake-account` not importable programmatically to a spreadsheet or other program
Add an option to output rewards in CSV format
Fixes #
> Add csv output option to stake and vote account rewards

- .github/workflows/release-artifacts.yml
install openssl to fix the broken Windows build.
> ci: install openssl for the Windows build

- ledger/src/blockstore.rs
The container is only used to check for inclusion of slots with
the .contains() method. This method is O(n) on a Vec<_> but O(1) on a
HashSet<_>.
The container should be fairly small given that it is populated with confirmed slots that are newer than the most recent root. So, in normal network conditions, should be around the lockout length. Regardless, still a more proper change to make
> Switch confirmed_unrooted_slots from Vec<_> to HashSet<_>

- bucket_map/src/bucket_map.rs
- bucket_map/src/lib.rs
- bucket_map/src/restart.rs
Working towards re-using disk index files on restart instead of creating new ones.
Add `Restart` and a few other structs to keep track of the current file name and random used by individual disk buckets.
Fixes #
> add Restart structs for disk index

- scripts/build-downstream-projects.sh
v1.14 CI is red: https://buildkite.com/solana-labs/solana/builds/102076
the serum-dex doesn't really active now. It might be a good idea to remove it 🤔
> v1.14: ci: remove legacy tests

- Cargo.lock
- bucket_map/Cargo.toml
- bucket_map/src/restart.rs
- programs/sbf/Cargo.lock
Speeding up restart.
Reusing disk index files on start.
Use bytemuck for manipulations.
Improve test.
Fixes #
> use bytemuck for disk bucket restart

- accounts-db/src/bucket_map_holder.rs
Populate path of disk index restart file.
Fixes #
> disk bucket: init restart path

- bucket_map/src/restart.rs
add disk bucket `get_restart_file` to load file on restart.
add disk bucket `get_restartable_buckets` to connect up disk bucket files.
Fixes #
> add disk bucket get_restart_file

- bucket_map/src/bucket_api.rs
- bucket_map/src/bucket_map.rs
Staging to prepare for each disk bucket to know the `RestartableBucket` we are keeping track of at runtime and we will reuse at startup.
Fixes #
> pass RestartableBucket through disk index

- bucket_map/src/bucket.rs
- bucket_map/src/bucket_api.rs
Working on speeding up startup.
Making generate index re-use disk index files on restart.
each index bucket holds onto a RestartableBucket, which helps it keep track of which file is in use.
Fixes #
> data bucket holds RestartableBucket

- bucket_map/src/bucket.rs
Try to re-use a disk bucket file from a previous run if one exists and is compatible.
Fixes #
> DiskIdx: reuse disk bucket file if possible

- accounts-db/src/bucket_map_holder_stats.rs
- bucket_map/src/bucket.rs
- bucket_map/src/bucket_stats.rs
Speeding up startup.
Re-using index files on startup.
Add stats for how many startup index entries were re-used vs created.
Fixes #
> diskidx: stats for created vs reused

- bucket_map/src/bucket.rs
apply_grow_index does not delete index file if we plan to re-use the file.
Fixes #
> disk idx: apply_grow_index does not delete index file

- Cargo.lock
- Cargo.toml
- programs/sbf/Cargo.lock
- programs/sbf/Cargo.toml
[solana_rbpf v0.7.2](https://github.com/solana-labs/rbpf/releases/tag/v0.7.2) was released.
> Bump solana_rbpf to v0.7.2

- accounts-db/src/bucket_map_holder_stats.rs
- bucket_map/src/bucket.rs
Working on speeding up startup and generate index.
Only dump some startup index stats after all of startup has completed.
Fixes #
> dump final startup index stats only after startup is complete

- core/src/consensus.rs
- core/src/replay_stage.rs
The `is_locked_out` cache is not updated when we adopt the on chain vote state.
This can cause a similar situation to #32880 (detailed in #32944) because we attempt to vote on a block we are locked out on which will fail. 
* Update the cache 
* Don't update last vote when there is a vote program error
Fixes #
> Update is_locked_out cache when adopting on chain vote state

- bucket_map/src/bucket.rs
- bucket_map/src/restart.rs
Speeding up startup.
Re-using index files on startup.
Now that we can re-use an individual file. Try to re-use the data already in the file while generating the index. This means instead of writing new data (over data initialized to 0), we look for data in the file to see if it already matches what we would write. 99.9% of the time it will match and we can just re-use the existing file contents.
Fixes #
> disk idx: try to reuse disk index's exisiting data on startup

- accounts-db/src/accounts_db.rs
working on speeding up startup.
generating the index takes a long time.
Change duplicate pubkey scan to use `scan(...)`, which is more efficient for iterating over many pubkeys.
Be sure to hide whitespace changes for diff.
Fixes #
> visit_duplicate_pubkeys_during_startup uses scan

- core/src/banking_stage/consumer.rs
- core/src/banking_stage/qos_service.rs
- cost-model/src/cost_model.rs
- cost-model/src/cost_tracker.rs
- cost-model/src/transaction_cost.rs
Usage cost of simple-vote transaction is static (#33269), due to restrictions of being a "simple vote transaction".
Assigning a static usage cost to simple-vote, instead of going to calculation that applies to normal transaction, would simplify code. Also preparing for enhancing normal transaction's usage cost categorization and calculation, without having to worry about accidentally changing vote's cost. Another side benefit is to slightly improve vote cost calculation performance. 
- Add `enum` cost type for `Vote` and `Transaction`.
- Sets simple-vote cost to be statically 3428 CUs
Fixes #
> Separate vote cost

- docs/src/running-validator/validator-start.md
There's a `$` in the `systemctl enable` command. When copying the command from [here](https://docs.solana.com/running-validator/validator-start#systemd-unit), it's not pasteable in the terminal as the `$` gets copied.
Remove the `$` out of the command
> docs: updating systemd command
