solana-labs/solana

Cargo.lock
program-test/Cargo.toml
program-test/tests/setup.rs
program-test/tests/stake.rs
program-test/tests/warp.rs
programs/sbf/Cargo.lock
programs/stake/src/stake_instruction.rs
programs/stake/src/stake_state.rs
sdk/program/src/stake/instruction.rs
sdk/program/src/stake/state.rs

Normally, activated stake has to wait at least one epoch after being deactivated, before it becomes deactivated and withdrawable. 
However, there is a bug in redelegation which could lead to same-epoch stake deactivation after stake redelegation. By redelegating the activated stake to another validator and deactivating the redelegated stake, the stake becomes deactivated and withdrawable in the same epoch.
Part of https://github.com/solana-labs/solana/pull/31876
Fix bug of same-epoch stake deactivation after stake redelegation
Fixes #

Fix bug of same-epoch stake deactivation after stake redelegation

---

Cargo.lock
bench-tps/src/bench_tps_client/tpu_client.rs
client/src/connection_cache.rs
client/src/nonblocking/tpu_client.rs
client/src/tpu_client.rs
connection-cache/Cargo.toml
connection-cache/src/connection_cache.rs
programs/sbf/Cargo.lock
quic-client/src/lib.rs
quic-client/src/nonblocking/quic_client.rs
sdk/program/src/serde_varint.rs
thin-client/src/thin_client.rs
tpu-client/src/nonblocking/tpu_client.rs
tpu-client/src/tpu_client.rs
udp-client/src/lib.rs

There is connection warmer creating connection in the background, and we have connection pooling in the connection cache. The default is 4. This results in we create new connection until the pool size is satisfied even when there is a connection in the cache.
If there is a connection in the cache available, use it and create the additional connection asynchronously.
Fixes #

Async connection creation in connection cache

---

programs/bpf_loader/src/lib.rs

Quoting @pgarg66:
> In deploy_program macro we are creating a new instance of runtime environment: https://github.com/solana-labs/solana/blob/ce63640d6deb29e78d6de9727afbbdc4bb1bcdca/programs/bpf_loader/src/lib.rs#L119
> This means that the cached program will get pruned here: https://github.com/solana-labs/solana/blob/ce63640d6deb29e78d6de9727afbbdc4bb1bcdca/program-runtime/src/loaded_programs.rs#L497
> Also, `reject_deployment_of_broken_elfs` is `false` when the environment is created in bank.rs while it is `true` when it is created in `deploy_program()`. This is to retain some old behavior for previously deployed program (so that bank can continue to load them), but reject the broken elf for any new program deployments.
> For loader-v4 we don't have the above restriction (i.e. no old …

Reloads deployments with `environments.program_runtime_v1`

---

accounts-db/src/tiered_storage.rs

The TieredStorageFormat field in the TieredStorage is only used in the write path.
This PR simplifies the handling of TieredStorageFormat by removing its field from
TieredStorage struct but passing via write_accounts().

[TieredStorage] Streamline the handling of TieredStorageFormat

---

accounts-db/src/accounts_hash.rs
bucket_map/src/bucket.rs

Code clean up.
1. remove unneeded `pub`.
2. remove unneeded `mod`.
Fixes #

Code clean up

---

.github/workflows/downstream-project-spl.yml

During the work to make the rent-exemption consistent during stake split https://github.com/solana-labs/solana/pull/33295, we needed to disable the downstream spl-stake-pool job because the program was designed around the old behavior.
Now that we've got all the following done:
* https://github.com/solana-labs/solana-program-library/pull/5334
* https://github.com/solana-labs/solana-program-library/pull/5288
* https://github.com/solana-labs/solana-program-library/pull/5285
* https://github.com/solana-labs/solana-program-library/pull/5322
The stake pool program handles the new behavior properly, so re-enable the downstream job!
Fixes #

ci: Re-enable spl-stake-pool downstream job

---

ci/buildkite-pipeline.sh

#33437 doesn't catch doc test error 😢 
build doc tests when either Cargo.lock or Cargo.toml is modified

ci: fix cargo files changes doens't trigger doc tests

---

runtime/src/bank.rs

Add matching start/stop lines; this matches the styles that some other services have (such as `SnapshotPackagerService`)

Add uniform start/stop log lines for background hash verification

---

accounts-db/src/accounts_hash.rs

Deduplicate and eliminate zero lamport account in accounts hash calculation is slow. 
Optimize the deduplicate and eliminate zero accounts loop. 
- master
```
sol@dev-equinix-washington-23:~$ grep calculate_accounts_hash_from_storages d1 | tail -n1 | awk '{for(i=1; i<=NF; i++) if (0 != index($i, "=")) {print($i)}}' | column -ts "=" | grep -E "pubkey_bin_search_us|eliminate_zeros_us|min_pk_scan_us|hash_writes_us|skip_duplicates_us|sort_us"
eliminate_zeros_us                  6466915i
pubkey_bin_search_us                14784327i
```
- linked list (https://github.com/solana-labs/solana/pull/33215)
```
sol@dev-equinix-washington-23:~$ grep calculate_accounts_hash_from_storages d1 | tail -n1 | awk '{for(i=1; i<=NF; i++) if (0 != index($i, "=")) {print($i)}}' | column -ts "=" | grep -E …
```

hash dedup vec

---

runtime/src/prioritization_fee_cache.rs

A WARN log being excessively triggered by vote-only slots. It was meant to log an unlikely event when duplicated bank had prioritized TXs but the confirmed bank had none. It is not entirely impossible, but maybe something worth looking into, hence logging.
- add comments and limits to reduce the logging to targeted scenario
Fixes #

reduce WARN logging to only necessary scenario

---

core/src/banking_stage.rs
core/src/banking_stage/packet_receiver.rs

Investigating potentially removing forwarding entirely.
Want some metric on what percentage of packets entering `BankingStage` are coming from forwarding.
Add a metric to count number of buffered packets that were forwarded
Fixes #

Add new received forwarded packets metric to banking stage

---

accounts-db/src/accounts_db.rs

Since slot_storage sort scan is sequential, there is no need to accumulate the scan timing with atomic u64.
Use `measure_us` to measure slot storage scan timing.
Fixes #

Move sort timer out of loop

---

gossip/tests/gossip.rs

Gossip test is setting a boolean to true at the beginning of a test and then asserting the boolean is true at the end. 
Set initial boolean to false. and remove extra `done = true` in first step of loop. `done` should only be set to true when network has converged.
Fixes #

gossip test update

---

accounts-db/src/accounts_db.rs

While investigating the v1.16 OOM on 128 GB nodes, I was looking at various `clean` metrics and came across `remove_dead_accounts_shrink_us`. It was being reported as 27 *billion* microseconds, vs 62 *million* microseconds for the *total* time to run `clean`. It's suspicious whenever a sub-metric *vastly* exceeds the `total` metric.
Here's a graph. Note the log scale:
I think this was introduced in a refactoring as part of https://github.com/solana-labs/solana/pull/29117
Note the removal of the `if self.caching_enabled` block, specifically the *closing brace*:
I believe the incorrect closing brace was removed, and it should've been the one on (old) line 8073.
Move the metrics code *outside* the for loop.
Note that the code in #29117 has another subtle change here. The old version with the …

Fixup the metrics for remove_dead_accounts_shrink_us

---

accounts-db/src/accounts_db.rs

Please read through https://github.com/solana-labs/solana/pull/33458 first. Here's the snippet from the end:
> Note that the code in https://github.com/solana-labs/solana/pull/29117 has another subtle change here. The old version with the `if` block drops the lock on `shrink_candidate_slots`, but now we don't drop until the function exits. I'll fix that in a subsequent PR.
Explicitly drop the lock.

Drops the shrink_candidate_slots lock after done inserting

---

.github/workflows/release-artifacts.yml

Windows build is broken again 😢 
set `OPENSSL_DIR` to either `C:\Program Files\OpenSSL` or `C:\Program Files\OpenSSL-Win64`, depending on which one exists.

ci: fix Windows build

---

core/src/replay_stage.rs

select_vote_and_reset_forks() logic is too complicated because the results of the switching threshold check are hard too interpret
Make switching threshold check result more explicit 
Fixes #

Cleanup select_vote_and_reset_forks()

---

ledger/src/blockstore/blockstore_purge.rs

`to_slot` is incremented by one in order to make the loop run for `[from_slot, to_slot]`. However, this value is then used with a `<=` later on; we need the original (non-incremented) value for the comparison to be correct.
Use the incremented value in the loop bounds only instead of updating `to_slot`.
This could also be done with `from_slot..=to_slot`; I'm guessing `saturating_add(1)` was used to try to make the inclusivity more obvious. I could go either way on using `..=` vs `.saturating_add(1)`

Fix off-by-one bug in Blockstore::purge_exact()

---

transaction-status/src/parse_associated_token.rs
transaction-status/src/parse_token.rs
transaction-status/src/parse_token/extension/cpi_guard.rs
transaction-status/src/parse_token/extension/default_account_state.rs
transaction-status/src/parse_token/extension/memo_transfer.rs
transaction-status/src/parse_token/extension/metadata_pointer.rs
transaction-status/src/parse_token/extension/mint_close_authority.rs
transaction-status/src/parse_token/extension/permanent_delegate.rs
transaction-status/src/parse_token/extension/reallocate.rs
transaction-status/src/parse_token/extension/transfer_fee.rs
transaction-status/src/parse_token/extension/transfer_hook.rs

While working on #33453, I noticed that helpers like `convert_pubkey` were still being used, even though #31607 removed the additional sdk crates that were pulled in through the SPL crates.
Remove all of the helpers! Essentially, I just ran a few commands to remove the functions and their usages:
```
git g -l convert_pubkey | xargs sed -i'' -re 's/convert_pubkey\(([^)]+)\)/\1/g'
```
And
```
git g -l convert_compiled_instruction | xargs sed -i'' -re 's/convert_compiled_instruction\(([^)]+)\)/\1/g'
```
And then cleaned up the build and clippy errors. Note that this only impacts tests, and nothing else.
Fixes #

transaction-status: Remove conversions between spl re-exports and local sdk

---

core/benches/banking_stage.rs
ledger/src/blockstore_processor.rs
rpc/src/rpc.rs

We currently randomly shuffle transaction order in our entries during replay.
We want to relax constraints on entries to allow for conflicting transactions within entries.
We cannot do that if we are shuffling, because it would potentially re-order conflicting transactions, and lead to non-deterministic output.
Remove entry transaction shuffling
Fixes #

Remove entry shuffling

---

program-runtime/src/loaded_programs.rs
runtime/src/bank_forks.rs

Preparation for #33477.
- Adds type `ProgramRuntimeEnvironment`: For slightly improved code readability.
- Moves `LoadedPrograms::remove_expired_entries()` into `LoadedPrograms::prune()`: As an optimization as we don't need to `retain` / `collect` the secondary index level twice.
- Adds `Stats::prunes_environment` and renames `Stats::prunes_orphan` and `Stats::prunes_expired`: So that all three reasons for pruning entries on rerooting have the same naming scheme.
- Adds `LoadedPrograms::latest_root_epoch`: To detect the first rerooting after an epoch boundary, ending the recompilation phase.

Refactor - `LoadedPrograms`

---

.mergify.yml

Update's the mergify config to handle backports for v1.16 and v1.17 (but not v1.14 anymore)

Update mergify backport actions for new minor version

---

runtime/src/snapshot_utils/archive_format.rs
scripts/run.sh

For our use cases, the compression types being removed are inferior and have caused us support burden.
These options are now disallowed on the command line for solana-validator and solana-ledger-tool, which effectively means no more snapshots will be created with this types in normal usecases. However, support for reading the deprecated types is still in place.
This PR is a follow-on to https://github.com/solana-labs/solana/pull/33442 (which I will be closing); that PR ripped several things out whereas this PR has a more gradual deprecation approach in mind

Deprecate bz2/gzip/none/tar snapshot compression types

---

ledger/src/blockstore/blockstore_purge.rs
ledger/src/blockstore_db.rs

I'm exploring removing the primary-index from the Blockstore "special column" keys. But it's difficult to tell if I might be breaking current purge functionality, because there is no test of CompactionFilter-type purge.
Add test of compaction-filter purge.
I also exposed `compact_range_cf` functionality as a method on `Database` -- I need it for the test, but thought it might be useful for purging the special columns in other contexts. But I could lock it down within `mod tests` if preferred.

Add test for compaction filter purge

---

ci/buildkite-pipeline-in-disk.sh
ci/buildkite-pipeline.sh
ci/buildkite-solana-private.sh

close #33063
remove stable-perf tests
(btw, I've created a pipeline to run stable-perf nightly on master, ~v1.16~ v1.17 and ~v1.14~ v1.16)

ci: remove stable-perf from PR and push CI

---

.github/ISSUE_TEMPLATE/2-feature-gate.yml

We want to encourage all consesus-breaking changes to first have a SIMD. Update the feature gate issue template to request a link to its SIMD as a _gentle_ nudge in this direction

Add SIMD field to feature gate issue template

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs

These entries were found to improve compaction performance when
LedgerCleanupService was performing direct compactions on each primary
index. Cleaning by primary index has been deprecated for a while, and
as such, these dummy entries are no longer needed and can be removed.
Remove the dummy entries + a few comments that will no longer be correct
This is broken out from https://github.com/solana-labs/solana/pull/33370

Remove dummy entries in Blockstore special columns

---

core/src/validator.rs
validator/src/cli.rs
validator/src/main.rs

The banking trace disabled code path is running fine with mb & v1.16.
Let's bake the banking trace with v1.17 rel train to enable it on mb by default eventually.
I'm procrastinator.. missed v1.17 branching a day.
Enable it by default.
CLI:
```
--enable-banking-trace <BYTES>
Enables the banking trace explicitly, which is enabled by default and writes trace files for simulate-
leader-blocks, retaining up to the default or specified total bytes in the ledger. This flag can be
used to override its byte limit. [default: 15032385536]
--disable-banking-trace                   
Disables the banking trace
```

Enable the banking trace by default

---

ledger/src/blockstore/blockstore_purge.rs

Currently, `Blockstore::purge_columns_exact()` gets called on cluster restarts and takes quite a while to complete. However, we can halve the number of special-column deletes in the write batch in half for nodes running with `--enable-rpc-transaction-history` (ie RPC nodes), and eliminate them altogether for nodes without this flag (the majority of staked validators).
We already read both values from the `transaction_status_index_cf`, so use this data in memory to determine which (if any) primary_index contains the slot in question.
This is a reworking of functionality that is in #33370, but done in a way that works better with #33419

Blockstore special columns: minimize deletes in PurgeType::Exact

---

Cargo.lock
ci/test-stable.sh
frozen-abi/Cargo.toml
programs/sbf/Cargo.lock

chore(solana-frozen-abi): remove unused deps

---

ledger-tool/src/main.rs
ledger/src/blockstore.rs
ledger/src/lib.rs
ledger/src/transaction_address_lookup_table_scanner.rs
sdk/program/src/lib.rs

#30165
Manually load and add lookup table addresses instead of using sanitize.
Fixes #30165

Manually add lookup table addresses instead of sanitizing

---

programs/vote/src/vote_state/mod.rs

Now that clusters are on 1.16 and the feature flag is set to be activated soon, it's fine to use the new vote state format for tests.
Update with new vote state format for tests. Should not affect any live functionality. 
Fixes #33517

initialize with new VoteState for tests

---

Cargo.lock
Cargo.toml
accounts-db/Cargo.toml
programs/sbf/Cargo.lock

In accounts-db, we make lists of slots for various tasks. We put these in HashSets/HashMaps, which perform cryptographically secure hashing of the keys. Since we (1) don't always require cryptographic security, and (2) know that slots are unique identifiers, we actually don't need to hash the slot at all, but instead can use it directly.
The [`solana-nohash-hasher`](https://crates.io/crates/solana-nohash-hasher) crate was designed for this.
Add solana-nohash-hasher to accounts-db.
Future PRs will *use* solana-nohash-hasher—explicitly not included in this PR.

Adds solana-nohash-hasher

---

ledger/src/blockstore_db.rs

When `BlockstoreError` is logged, it is impossible to see the value of the particular variant of the enum.

Add error messages for BlockstoreError

---

core/src/banking_stage/consumer.rs
core/src/banking_stage/read_write_account_set.rs
core/src/banking_stage/unprocessed_transaction_storage.rs

Shortcoming with the current multi-iterator decision function.
Allows non-conflicting txs to take higher-priority locks.
- Take these transactions (internal nodes are accounts, edges indicate conflicts) for example:
```mermaid
graph LR
subgraph Tx1 - 3
Tx1_1(1)
style Tx1_1 fill:#CF0000
Tx1_2(2)
style Tx1_2 fill:#00CF00
end
subgraph Tx2 - 2
Tx2_2(2)
style Tx2_2 fill:#00CF00
Tx2_3(3)
style Tx2_3 fill:#0000CF
end
subgraph Tx3 - 2
Tx3_3(3)
style Tx3_3 fill:#0000CF
Tx3_4(4)
style Tx3_4 fill:#333333
end
Tx1_2 --> Tx2_2
Tx2_3 --> Tx3_3
```
- `Tx1` and `Tx2` conflict so they cannot be in a batch together
- `Tx2` and `Tx3` conflict so they cannot be in a batch together
- However, `Tx1` and `Tx3` do not conflict, so they could be in a batch together
- We do not want to allow `Tx3` to execute before …

Bugfix: MultiIterator batch priority guard

---

cli/src/stake.rs

Help text is wrong for --csv option.
Change accounts -> rewards.
Fixes #

Fix CLI help text for `solana stake-account`

---

ledger/src/blockstore_db.rs

clone_from_slice() would hypothetically visit each item in the slice and clone it whereas copy_from_slice() can memcpy the whole slice in one go.
Technically, Rust does the right thing for us by making clone_from_slice() defer to copy_from_slice() for types that implement Copy trait. However, we should still use the more efficient method directly to show intent.
Use `copy_from_slice()` over `clone_from_slice()` for `&[u8]` copies.
As mentioned, Rust made it such that `copy_from_slice()` would get called in this instance starting from v1.52.0 as evidenced in this commit: https://github.com/rust-lang/rust/commit/130fb243bd9e

Use copy_from_slice() over clone_from_slice() for u8 slice copies

---

ledger/src/blockstore/blockstore_purge.rs

The special columns, TransactionStatus and AddressSignatures, are only
populated if --enable-rpc-transaction-history is passed. Cleaning these
columns for a range of slots is very expensive, as the block for each
slot must be read, deserialized, and then parsed to extract all of the
transaction signatures and address pubkeys.
This change adds a simple check to see if there are any values at all in
the special columns. If there are not, then the whole process described
above can be skipped for nodes that are not storing the special columns.
Fixes #

Make Blockstore::purge_special_columns_exact() bail if columns empty

---

ledger/src/blockstore/blockstore_purge.rs

This field was being filled with the wrong value

Fix blockstore-purge delete_files_in_range_us metric

---

ledger/src/blockstore.rs

Spin off from #33419. In the case of both `find_address_signatures_for_slot` and `find_address_signatures`, there is no reason to read from Blockstore when the slot in question (or range of slots in question, respectively) has already been purged from the ledger.
Add early return to `find_address_signatures_for_slot` and `find_address_signatures` based on `lowest_available_slot`

Add early return to Blockstore::find_address_signatures methods

---

cli/src/cli.rs
cli/src/program_v4.rs

The program-v4 command processors depend on `CliConfig`. This is making it hard to reuse the code in cargo-registry server.
Decouple the code from `CliConfig` by introducing `ProgramV4CommandConfig`.
Fixes #

Decouple program-v4 command processors from CliConfig

---

cli/src/feature.rs

When activating a feature the transaction `Signature` is not logged in the final result.
It is only logged temporarily in the progress bar during during transaction finalization.
If it activates quickly, The user misses the signature and has to find it manually.
Return the signature in the `ProcessResult` which is used to print final results.
Fixes #

log signature after successful feature activation

---

accounts-db/src/account_storage/meta.rs
accounts-db/src/append_vec.rs

All account storage formats are required to implement both StoredAccountMeta
and ReadableAccount, but the implementation for the hot account format is missing.
This PR includes hot account format into StoredAccountMeta and ReadableAccount
enum.  This will allow the TieredStorageReader in the future PRs to return hot account
format in its `get_account` implementation.

[TieredStorage] Include Hot Account in StoredAccountMeta and ReadableAccount

---

ledger/src/blockstore.rs

As pointed out [here](https://github.com/solana-labs/solana/pull/33419#discussion_r1346837089), `Blockstore::get_confirmed_signatures_for_address2()` does more iterating than it needs to.
Ensure lowest_slot >= first_available_block:
- Update `get_transaction_status` to only return data from `first_available_block` and onward (this is the expected behavior from the perspective of rpc already)
- When a transaction status is not found, set `lowest_slot` to `first_available_block`

Blockstore::get_sigs_for_addr2: ensure lowest_slot >= first_available_block

---

core/src/consensus/latest_validator_votes_for_frozen_banks.rs

fix typo in latest_validator_votes_for_frozen_banks.rs

---

validator/src/cli.rs
validator/src/main.rs

Issues with `getHealth` are known: #16957 And I believe that the issue will be fundamentally resolved.
But right now, I'm concerned about updating the validator using `wait-for-restart-window` and `exit`.
There are already a lot of messages in the chats for 1.16.
I propose this tiny change that would allow bypassing the health check.
I sincerely hope for `v1.16` and `v1.17`
Added the `--skip-health-check` flag for the `wait-for-restart-window` and `exit` commands 
Fixes #33553

validator: skip health check

---

accounts-db/src/accounts_hash.rs

We are seeing a memory allocation failure when writing 0 to the end of
account's hash file.
It seems that it could be caused by self.capacity = 0. When we estimate the
capacity, it is possible that self.capacity = 0.
However, if `write()` is called, self.capacity must be greater than 0.
To rule out the possiblity, add an "assert" for capacity must be greater than
0.
Fixes #

Assert acount hash mmap file capacity > 0

---

gossip/src/cluster_info.rs
gossip/src/crds.rs
gossip/src/crds_entry.rs
gossip/src/crds_value.rs

unused legacy-snapshot-hashes code in gossip.
removed unused legacy-snapshot-hashes api in gossip

removes unused legacy-snapshot-hashes api in gossip

---

accounts-db/src/accounts_cache.rs
accounts-db/src/accounts_db.rs

The `hash` parameter to `AccountsCache::store()` is always `None` in non-test code. We do not need the `hash` parameter anymore.
Remove the hash parameter and set the initial value to `None`.

Removes hash param from AccountsCache::store()

---

accounts-db/src/accounts_db.rs
accounts-db/src/cache_hash_data.rs

Improving performance of hash calc.
When preparing to scan append vecs, first delete all existing cache files that will no longer be used. For example, if a slot was dropped or shrunk, then the cache file containing that file will be rewritten from scratch. So, that old file will never be useful again.
Fixes #

in hash calc, delete old cache files that will not be used earlier

---

programs/loader-v4/src/lib.rs

Failure in deploying program-v4 in freshly started `test-validator`.
- The deployment slot for a program is initialized to 0 during initialization.
- The loader checks if the current slot is > deployment slot + cooldown slots. If not, it fails the deployment.
- The test-validator starts from slot 0. So if someone tries to deploy a program within `cooldown slots` after startup, the above condition fails.
- This PR skips checking the cooldown slot if the deployment slot is 0. As it indicates the program was just initialized but never deployed.
Fixes #

Fix deployment of program-v4 in freshly started test validator

---

Cargo.lock
Cargo.toml
cargo-registry/Cargo.toml
cargo-registry/src/client.rs
cargo-registry/src/dummy_git_index.rs
cargo-registry/src/main.rs
cargo-registry/src/publisher.rs
cli/src/program_v4.rs

Need convenient mechanism to hook up `cargo publish` command for on-chain program. The users should be able to deploy programs to the blockchain using `cargo publish`.
This PR implements a custom Cargo registry service. It provides a registry endpoint for cargo commands, and uses Solana's RPC client to interface with the blockchain.
1. Generate keypairs for payer and authority accounts.
2. Fund the payer's account (e.g. airdrop if using test-validator).
3. Start the server
```
solana-cargo-registry -a authority.keypair -k payer.keypair -u <rpc endpoint URL> -p <available local TCP port>
```
Insert following under `[package]` section of the toml file.
```
include = [
"**/*.rs",
"out/**.so",
"out/**.json",
"Cargo.toml",
]
```
Create (or update existing) .cargo/config by adding the …

Cargo registry service for deploying programs

---

runtime/src/bank.rs

someone snuck a laziness-motivated helper into the code base
remove it so as not to encourage more

bank: remove ambiguating "helper" method

---

core/src/replay_stage.rs
core/src/vote_simulator.rs
core/tests/snapshots.rs
ledger-tool/Cargo.toml
ledger-tool/src/main.rs
ledger/Cargo.toml
ledger/src/blockstore_processor.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/bank_forks.rs
runtime/src/snapshot_bank_utils.rs
scripts/check-dev-context-only-utils.sh

my scheduler thing needs to introduce rather invasive code changes including the `BankWithScheduler` wrapping, which touches tick registration code.
Prepare some helper functions.

Define tick related helper test methods

---

accounts-db/src/accounts_db.rs

Flushing write cache aligns the size to a page twice. The first one is not necessary.
Remove a redundant page alignment.
Fixes #

remove redundant page_align

---

accounts-db/src/accounts_db.rs

We no longer 'append' to append vecs. We know the full size when we are ready to write to them. So, it is no longer necessary to pad them to the next full page size. This makes 100% of the data in the file required and the used length equal to the allocated length.
Fixes #

stop padding new append vecs to page size

---

programs/bpf_loader/src/syscalls/cpi.rs

The current ABI is unstable as it confuses `bool` and `u8`.
Extends the feature gate of `disable_cpi_setting_executable_and_rent_epoch`:
- Rejects transactions in which a program sets invalid values to `AccountMeta::is_signer` or `AccountMeta::is_writable`
- Ignores the values set to: `AccountInfo::executable` and `AccountInfo::rent_epoch`
Feature Gate Issue: #26988

Fix - CPI interface `bool` masking

---

ledger/src/blockstore.rs
ledger/src/blockstore_db.rs

In v1.18, https://github.com/solana-labs/solana/pull/33419 will deprecate the existing special-column keys, and start using new ones without the primary indexes. We want nodes to be able to upgrade and downgrade between minor releases as needed. But currently, when a node hits a key of the wrong length, it will panic.
Add a very abbreviated version of the ColumnIndexDeprecation trait to enable the `LedgerColumn::iter_current_index_filtered()` method
Implement ColumnIndexDeprecation for the TransactionStatus and AddressSignatures columns. (While #33419 also implements the trait for the TransactionMemo column, there isn't anywhere calling the `iter()` method against that column, so nothing that will panic on the new keys.)

v1.17: skip unrecognized keys in Blockstore special-column iterators

---

cargo-registry/src/dummy_git_index.rs

The cargo registry server fails to start if the index configuration changes (e.g. due to change in port or IP address)
```
thread 'main' panicked at cargo-registry/src/dummy_git_index.rs:80:18:
Failed to get tree: Error { code: -1, klass: 14, message: "failed to insert entry: invalid object specified - git" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The config change requires a new commit to the GIT index. The staging of the commit was adding all the files, including `.git` folder. That was causing the issue. This PR adds only the required files to the stage/commit.
Fixes #

Fix failure in updating GIT index of cargo registry server

---

ci/test-checks.sh

`test-checks.sh` output for missing `cargo-hack` could be more helpful:
```
...
+ exec cargo +nightly-2023-09-20 hack --version --verbose
error: no such command: `hack`
Did you mean `check`?
...
```
Add error message indicating that `cargo-hack` is a package that should be installed.
Fixes #

indicate that test-checks.sh requires cargo-hack

---

accounts-db/src/accounts_db.rs

This reverts commit b7962a3610b9beec2bfe660622a31fc8e34c1cd3.
https://github.com/solana-labs/solana/pull/33607 and https://github.com/solana-labs/solana/pull/33608 have broken CI for the tip of master
```
running 1 test
test accounts_db::tests::test_shrink_collect_simple ... FAILED
failures:
---- accounts_db::tests::test_shrink_collect_simple stdout ----
thread 'accounts_db::tests::test_shrink_collect_simple' panicked at accounts-db/src/accounts_db.rs:17401:33:
assertion `left == right` failed
left: 272
right: 4096
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
These two commits were introduced in parallel, which means CI never previously ran with only one of the commits. Each individual commit on top of master passes CI, but the combination of the two …

Revert "stop padding new append vecs to page size (#33607)"

---

rpc-client/src/http_sender.rs

In [Triton](https://triton.one/) sometimes we use custom headers in RPC Client but it's hard to create `HttpSender` outside of solana crate so we need to use a slightly patched version. With `HttpSender::new_with_client` it would be possible to create a sender with completely controlled created `reqwest::Client`.
- Add `HttpSender::new_with_client`
- Move default headers to `HttpSender::default_headers`

Allow to create HTTP Sender with custom Client

---

rpc/src/rpc_pubsub_service.rs

Noisy metric as reported by https://github.com/solana-labs/solana/issues/33610
Move the individual datapoint into a struct of other metrics that are collected + reported every 10s
Fixes https://github.com/solana-labs/solana/issues/33610

Fold noisy metric into struct of metrics that is reported every 10s

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs

Purging the blockstore with `PurgeType::PrimaryIndex` has been dated for quite a while.
- Update instances of `PurgeType::PrimaryIndex` to `PurgeType::Exact`
- Remove now unused functions
- Remove unused `active_transaction_status_index` field

Remove dated Blockstore PurgeType::PrimaryIndex code

---

validator/src/cli.rs

--wen_restart not ready yet, hide it for now and do not take default value so not to break wait_for_supermajority.

Hide wen_restart and do not take default value for now.

---

connection-cache/src/connection_cache.rs

Reduce pool size for ConnectionCache used by send-transaction-service
Reduce pool size for ConnectionCache used by send-transaction-service to 2 from 4. No significant slow down of performance from bench-tps testing using rpc-client which is used by send-transaction-service. This will reduce active connections maintained both on the server and client. This will enable us to cache connections for more nodes. 
Fixes #

Reduce ConnectionPool size used by send-transaction-service

---

Cargo.lock
banking-bench/Cargo.toml
banking-bench/src/main.rs
core/Cargo.toml
core/src/banking_stage.rs
core/src/banking_stage/consume_worker.rs
core/src/banking_stage/consumer.rs
core/src/banking_stage/decision_maker.rs
poh/Cargo.toml
poh/src/poh_recorder.rs
poh/src/poh_service.rs
scripts/check-dev-context-only-utils.sh

my scheduler thing needs to introduce rather invasive code changes including the `BankWithScheduler` wrapping, which touches poh recorder code.
Prepare some helper functions.
note that this pr is quite similar to the previous prep. pr: #33537

Define PohRecorder set_bank related test helper methods

---

validator/src/main.rs

These values are not deprecated in v1.16, but they are deprecated in v1.17. So, give a warning in v1.16 to operators who are running the soon-to-be deprecated values.
Tested locally and confirmed the warning shows as expected (newlines inserted here for readability):
```
[2023-10-10T22:33:40.704581671Z WARN  solana_validator] The specified --snapshot-archive-format is deprecated.
Update to use either lz4 or zstd, or do not pass --snapshot-archive-format argument at all to use the default
value of zstd. Deprecated value: none
```

v1.16: Add warning about deprecated snapshot archive formats

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
sdk/program/src/clock.rs
sdk/src/feature_set.rs

Add 5 additional feature gates to be able to gradually ramp up required hashes per tick to keep validators busier based on analysis in https://docs.google.com/spreadsheets/d/1NDJZiSFxqbVIi0jn-7I7MrYN2lqP4j9GePZdyPZ1fhI/edit#gid=1060803070
Current hashes per tick is at 2M. Add features to step this up on epoch boundaries to:
- 2,800,000 https://github.com/solana-labs/solana/issues/33601
- 4,400,000 https://github.com/solana-labs/solana/issues/33602
- 7,600,000 https://github.com/solana-labs/solana/issues/33603
- 9,200,000 https://github.com/solana-labs/solana/issues/33604
- 10,000,000 https://github.com/solana-labs/solana/issues/33605

Update hashes per tick with feature gates

---

core/src/validator.rs
metrics/src/metrics.rs

`SOLANA_METRICS_CONFIG` sanity checking fails for an empty string.
- Relax sanity check to treat an empty string the same as an unset env variable.
- Move `SOLANA_METRICS_CONFIG` sanity checking earlier in startup
original change for reference: sanity check metrics configuration #32799
Fixes #

allow empty string for SOLANA_METRICS_CONFIG sanity checking

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs

https://github.com/solana-labs/solana/pull/33511 previously attempted to make `Blockstore::open()` code remove dummy entries to enable the special case check that https://github.com/solana-labs/solana/pull/33534 added. However, this change was flawed:
- The lines to remove the dummy entries was added to `Blockstore::initialize_transaction_status_index()`
- `Blockstore::initialize_transaction_status_index()` would only get called if the `TransactionStatusIndex` entries are not populated
- The previous code populated the `TransactionStatusIndex` entries and the special columns dummy entries at the same time
Thus, the logic to cleanup the dummy entries would only get called if `TransactionStatusIndex` entries are absent. But, the case where we need to clean up dummy entries is the case where …

Remove dummy entries in Blockstore special columns (part 2)

---

quic-client/src/nonblocking/quic_client.rs

The num_packets stats are counting the empty packets which are not actually sent and hence skewing the relationship between num_packets and successful_packets
Do not count the empty packets from cache warmer in num_packets stats as they are not sent.
Fixes #

Correct num_packets stats

---

accounts-db/src/ancient_append_vecs.rs

fix typo in comments

---

runtime/benches/bank.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

my scheduler thing needs to introduce rather invasive code changes including the `BankWithScheduler` wrapping, which touches the quite long-lived `goto_end_of_slot()` test helper function.
In preparation for the scheduler, adjust its argument type in advance to take `Arc<Bank>`, also clean up odd `::get_mut()` and others for consistent call-site coding styles as a bonus.

Make goto_end_of_slot() take Arc<Bank>

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs
ledger/src/blockstore_db.rs

As of [this commit](https://github.com/solana-labs/solana/pull/33419/commits/2aeacd29851c509bcf164154c5124a06530660eb), the compaction-filter purge includes the TransactionMemos column. For new TransactionMemos that include Slot in the key, the filter works as expected, and purges slots older than `oldest_slot`. However, old TransactionMemos that don't include Slot in the key are currently set to *all* be purged on the first periodic cleanup. This is because `C::slot(C::index())` always returns 0 for these entries.
Add a field to OldestSlot to track when slot-0 entries should be cleaned
Plumb into PurgedSlotFilter

Blockstore: clean/save old TransactionMemos sensibly

---

net/gce.sh

system performance tests failed recently.
it seems that this line is the culprit
https://github.com/solana-labs/solana/blob/452fd5d384e344377c4d14ab4373f9ad129f36d2/net/scripts/install-redis.sh#L7
If I don't miss anything, we don't really use redis in our performance tests.
remove the redis setup from the net.sh

remove redis setup from net.sh

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

This is creating havoc for Solang, as the return data is borsh encoded and therefore `u64` values like 0x100 get truncated.
When Solidity returns a borsh encoded return values which end in trailing zeros, then this gets mangled. For example,
a single `bool` value `false` should be a single 0 byte but this get removed. `0x100u64` has its last byte removed.
Do not remove trailing 0 bytes. There is no need for this.
Fixes #31391

bank: do not remove trailing 0 bytes from return data

---

cli-output/src/cli_output.rs
cli/src/program_v4.rs

Missing CLI commands to show/dump V4 programs.
Add the utility functions.
Fixes #

Add CLI command to show/dump v4 programs

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

General fixes split off from #33477, continuation of #33482.
- Uses one mock environment across all entries generated in each `LoadedProgram` test.
- Adds `LoadedProgramType::get_environment()`.
- Adjusts `test_runtime_feature_enable_with_program_cache()`.
- Filter out entries of different environments in `LoadedPrograms::extract()`.
- Adds `LoadedPrograms::get_environments_for_epoch()`.

Refactor - LoadedPrograms part 2

---

program-runtime/src/compute_budget.rs
programs/bpf_loader/src/syscalls/mod.rs

Problem
inner_call() function for hashing syscalls (sha256, keccak and blake3) are nearly identical
de-replicated the hashing syscalls to follow generic and trait approach, ref https://github.com/solana-labs/solana/issues/33046.

updated inner_call for hashing fn to follow generic approach

---

storage-proto/build.rs

Not possible to build 1.16 crates with rust 1.73 due to the changed `rerun` line in `build.rs`
Change `rerun` format

storage-proto: change rerun line format

---

accounts-db/src/accounts_hash.rs

Recently, on Oct 6, 20023, we saw a validator crash on one of the canaries boxes. 
```
[2023-10-06T06:29:48.605280562Z INFO  solana_metrics::metrics] datapoint: accounts_db_active shrink=0i
[2023-10-06T06:29:48.653273411Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solAccountsLo03" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: \"Cannot allocate memory\" }', accounts-db/src/accounts_hash.rs:102:34" location="accounts-db/src/accounts_hash.rs:102:34" version="1.18.0 (src:e0091d69; feat:1091887072, client:SolanaLabs)"
```
The crash happens when allocating account hash file during hash dedup. 
```
[2023-10-06T06:29:31.721389079Z INFO  solana_metrics::metrics] datapoint: memory-stats …
```

Retry hash file allocation

---

cargo-registry/src/client.rs
cargo-registry/src/main.rs
cargo-registry/src/publisher.rs
cargo-registry/src/response_builder.rs

`cargo-registry` code could use some cleanup for struct names and repeated code.
Code cleanup. No functional changes.
Fixes #

Code cleanup in cargo-registry

---

core/src/validator.rs
docs/src/api/http.md
docs/src/api/methods/_getHealth.mdx
rpc/src/rpc.rs
rpc/src/rpc_health.rs
rpc/src/rpc_service.rs
test-validator/src/lib.rs
validator/src/cli.rs
validator/src/main.rs

The current `getHealth` mechanism checks a local accounts hash slot vs. those of other nodes as specified by `--known-validator`. This is a very coarse comparison given that the default for this value is 100 slots. More so, any nodes using a value larger than the default (ie `--incremental-snapshot-interval 500`) will 100% see `getHealth` return status behind at some point.
Change the underlying mechanism of how health is computed. Instead of using the accounts hash slots published in gossip, use the latest optimistically confirmed slot from the cluster. The cluster confirmed slot can be compared against the latest optimistically confirmed bank to determine how far behind the node is. This new comparison is much more granular than the old approach, and also has the benefit of not going …

Change getHealth to compare optimistically confirmed slots

---

accounts-db/src/accounts_db.rs
runtime/src/accounts_background_service.rs
runtime/src/bank.rs

Previously ancient shrink was run when shrink ran.
The code in accounts background service ended up running ancient shrink every 100ms in some cases. This is very inefficient.
Run ancient shrink on roughly the same cadence as clean. Also, run ancient shrink prior to creating a snapshot.
Fixes #

ancient shrink on its own cadence

---

CHANGELOG.md

Update the v1.17 changelog
Fixes #

Whickey/changelog update v1.17

---

runtime/src/bank.rs

See #32801
until the `account_hash_ignore_slot` feature gets activated, there is some non-determinism in testing.
Remove non-determinism.
Fixes #32800

Fix non-determinism in account_hash_ignore_slot on genesis

---

Cargo.toml
frozen-abi/Cargo.toml
geyser-plugin-manager/Cargo.toml
programs/sbf/Cargo.toml
remote-wallet/Cargo.toml
sdk/program/Cargo.toml

A few entries in the dependency lists in `Cargo.toml` were not added in the alphabetical order.
Keeping these sorted reduces merge conflicts.
I could not find a tool that would enforce the sorting.
Just sorted manually for now.

Cargo.toml: Sort dependency and feature lists

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

When we are packing ancient append vecs, the current strategy is to not move accounts from a slot for all accounts with refcounts > 1. This is because we can't know easily what other slot(s) the older versions of the account are in. Thus, it isn't safe to move slots.
Add a metric to keep track of how many slots fit this criteria.
Fixes #

add metric for ancient can't move slots

---

gossip/src/cluster_info.rs
gossip/src/crds_gossip.rs
gossip/src/crds_gossip_pull.rs
gossip/tests/crds_gossip.rs

a validator uses the pubkey of the sender of a `PullResponse` to update the sender's liveliness in its`Crds::table`. But this is redundant because eventually the sender of the `PullResponse` will be the origin of some `CrdsValue` that the validator will receive. So the validator is essentially updating the liveliness twice.
Eliminated updating the sender of a `PullResponse`'s liveliness
Fixes #

remove redundant pubkey update record

---

docs/src/running-validator/validator-start.md
docs/src/validator/get-started/setup-an-rpc-node.md

The startup docs for a validator talk about the `--account-index` flag, which should never be used on a validator.
Moved `--account-index` information to start an rpc docs

docs: move rpc info to rpc docs

---

accounts-db/src/accounts_db.rs

Refactor: move timer code after eary exist from fn
Fixes #

move timer after early exit

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

ancient append vec packing is now running at a reasonable interval (similar to when clean runs). As a result, we should now log the metrics each time it completes. It is not uncommon for ancient append vec packing to do nothing. In those cases, we still need to log how much time the algorithms spent trying to pack.
Log each time ancient append vec packing runs.
Fixes #

log ancient stats each time we run

---

accounts-db/src/ancient_append_vecs.rs

When we disable rewrites, ancient append vec packing will run to combine old slots together.
There is a field `target_slots_sorted` which didn't end up getting sorted. Previously, this was irrelevantly incorrect. However, other changes coming soon rely on this being sorted.
Sort `target_slots_sorted`.
Fixes #

sort ancient append vec target_slots_sorted

---

accounts-db/src/tiered_storage/hot.rs

HotStorageReader currently doesn't have a test that covers its footer.
This PR includes a test for HotStorageReader that verifies the footer.

[TieredStorage] Footer test for HotStorageReader

---

gossip/benches/crds_gossip_pull.rs
gossip/src/crds_gossip_pull.rs

Push message propagation has improved in recent versions of the gossip code and we don't rely on pull requests as much as before. Handling pull requests is also inefficient and expensive.
The commit reduces number of outgoing pull requests by down sampling.

down samples outgoing gossip pull requests

---

sdk/program/src/message/account_keys.rs

It is a pretty standard set of traits to implement on most types. Both `Pubkey` and `LoadedAddresses` contained within the `AccountKeys` already implement them.  Doing the same for `AccountKeys` could simplify unit tests and/or some common value manipulation logic.

program::message::AccountKeys: `Clone`, `Default`, `Debug`, `Eq`

---

gossip/src/cluster_info.rs

Following: https://github.com/solana-labs/solana/pull/33722 `from` pubkey in PullResponse is no longer used in processing pull-responses and so the code can be simplified.
simplified pull-response handling.

simplifies pull-responses handling

---

gossip/src/cluster_info.rs
gossip/src/crds_gossip.rs
gossip/tests/crds_gossip.rs

`flush_push_queue` already covers all uses of `drain_push_queue` + write to crds table.
removed `ClusterInfo::drain_push_queue`.

removes ClusterInfo::drain_push_queue

---

accounts-db/src/tiered_storage/hot.rs

HotStorageReader currently only implements get_footer().  It does not
have a function to obtain the account meta.
This PR implements HotStorageReader::get_account_meta_from_offset().
A function that returns the account meta located at the specified offset.
This will be the helper function that will be later used to obtain the account
meta when the offset is available from the index block of a hot storage file. 
A new test is included in this PR.

[TieredStorage] HotStorageReader::get_account_meta_from_offset()

---

ledger-tool/src/program.rs
program-test/src/lib.rs
programs/bpf_loader/benches/serialization.rs
programs/bpf_loader/src/lib.rs
programs/bpf_loader/src/serialization.rs
programs/sbf/benches/bpf_loader.rs

`cap_bpf_program_instruction_accounts` is now activated on all clusters and unused code paths can be cleaned up
Removed now unused parameter in `fn serialize_parameters`
Closes https://github.com/solana-labs/solana/issues/26628

feature flag cleanup: cap_bpf_program_instruction_accounts

---

core/src/repair/quic_endpoint.rs

Currently each outgoing repair request will attempt to establish a connection if one does not already exist. This is very wasteful and consumes many tokio tasks if the remote node is down or unresponsive.
The commit decouples routing packets from establishing connections by adding a buffering channel for each remote address. Outgoing packets are always sent down this channel to be processed once the connection is established. If connecting attempt fails, all packets already pushed to the channel are dropped at once, reducing the number of attempts to make a connection if the remote node is down or unresponsive.

separates out routing repair requests from establishing connections

---

watchtower/README.md

This pull request fixes typo `recieve -> receive` in the file watchtower/README.md

docs: fix typo in watchtower/README.md

---

.github/scripts/downstream-project-spl-common.sh

With https://github.com/solana-labs/solana-program-library/pull/5575, SPL is updating to 1.17. That means the monorepo's downstream job on v1.16 will fail.
When doing the downstream job, checkout the last commit to use v1.16: https://github.com/solana-labs/solana-program-library/tree/v1.16
Fixes #

v1.16: Update SPL downstream CI to use 1.16 compatible branch

---

accounts-db/src/ancient_append_vecs.rs

When we disable rewrites, we will accumulate old append vecs & slots. We use ancient append vec packing to combine those. There exist many accounts which will remain in their dead state indefinitely.
As a result, if we don't distinguish different categories of accounts where ref_count > 1, we'll have many slots which can't be packed and moved.
Add a test to prepare to distinguish accounts with refcount > 1 where there is an alive index entry with a higher slot #. Soon, accounts will be treated differently if refcount > 1 depending on if this slot's index entry for the pubkey is higher or lower than other alive entries.
This new test is very similar to the existing `test_calc_accounts_to_combine_opposite`. In the next pr, that test will change to test the case where we have 2 refs, and 1 …

add ancient append vec test

---

ledger/src/blockstore.rs

A previous change removed logic that populated the
TransactionStatusIndex entries at each of the legacy primary index keys
(0 and 1). While these entries will not be read or written in the
future, these entries are necessary for backwards compatibility. Namely,
branches <= v1.17 expect these entries to be present and .unwrap()'s
could fail if they are not.
So, add the initialization of these entries back into Blockstore logic.
We can remove initialization of these entries once our stable and beta
branches are both versions that do not expect these entries to be
present (should be v1.18).
I encountered this issue originally by:
- Creating a `Blockstore` with master (which does not insert these entries) AND
- Attempting to open the `Blockstore` with `solana-ledger-tool` which opens in …

Make Blockstore populate TransactionStatusIndex entries

---

zk-token-sdk/src/sigma_proofs/batched_grouped_ciphertext_validity_proof.rs

The documentation of BatchedGroupedCiphertext2HandlesValidityProof::verify mentions use of `OsRng`.
This function is used in Zero-Knowledge Token Proof Program instruction processing. Therefore use of OsRng would break consensus. 
It looks like the problematic comment was copy pasted from somewhere else as is not valid. Please double check that this is actually the case.
Removes the problematic comment. 
Fixes #

zk-token-sdk: Fix incorrect mention of OsRng in docs

---

core/src/replay_stage.rs
ledger/src/bank_forks_utils.rs
ledger/src/blockstore_processor.rs
program-runtime/src/loaded_programs.rs
runtime/src/bank.rs
runtime/src/bank_forks.rs

`LoadedPrograms::prune()` is passed an instance of fork graph. Same information can be used in few other methods in the cache. It'll be ideal if the fork_graph can be set globally for the cache.
Set fork_graph at startup and use it in prune.
Fixes #

Set a global fork graph in program cache

---

.github/scripts/check-changelog.sh
.github/workflows/changelog-label.yml
CHANGELOG.md

Testing:
| Commit | changelog Label | Expected | Actual same as expected? | 
| ------ | --------------- | -------- | ------ |
| e98c0bc7 (no CHANGELOG.md entry) | Yes        | Check fails   | OK |
| e98c0bc7 | No         | Check skipped | OK |
| 73cfe1a4 (with CHANGELOG.md entry) | Yes        | Check passes  |  OK |
| 73cfe1a4 | No         | Check skipped | OK |

Add check for CHANGELOG.md change when changelog label applied to PR

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

When we disable rewrites, we will accumulate old append vecs & slots. We use ancient append vec packing to combine those. There exist many accounts which will remain in their dead state indefinitely.
Allow accounts which are alive and alive at the newest slot to still get packed together and move slots.
Fixes #

ancient: add many_refs_this_is_newest_alive

---

core/src/repair/quic_endpoint.rs
core/src/validator.rs

The number of outstanding connections can grow boundlessly.
The commit implements lazy eviction for repair QUIC connections. The cache is allowed to grow to 2 x capacity at which point at least half of the entries with lowest stake are evicted, resulting in an amortized O(1) performance.

prunes repair QUIC connections

---

zk-token-sdk/src/encryption/auth_encryption.rs
zk-token-sdk/src/encryption/elgamal.rs

https://github.com/solana-labs/solana/issues/33508
Add a maximum length (2^16 bytes, which should be plenty for any practical usecase) check on the maximum seed length for ElGamal and AES keypairs.
Fixes #

[zk-token-sdk] Limit max seed length for key derivations

---

core/src/validator.rs
turbine/src/quic_endpoint.rs

The number of outstanding connections can grow boundlessly.
The commit implements lazy eviction for turbine QUIC connections.
The cache is allowed to grow to 2 x capacity at which point at least
half of the entries with lowest stake are evicted, resulting in an
amortized O(1) performance.

prunes turbine QUIC connections

---

Cargo.lock
Cargo.toml

`aes-gcm-siv` v0.10.3 has a constraints on maximum `zeroize` version, set to be 1.3 or below.
At the same time, `cargo` does not want to construct a dependency graph with duplicate instances of a crate, when the first non-zero version of those instances are the same.  That is, it refuses to build a workspace with both 1.3 and 1.4 versions of `zeroize`.
`zeroize` is actually backward compatible, and `aes-gcm-siv` restriction is overly pessimistic.  This package lifted this restriction in a newer version, but we still depend on older versions and can not immediately update.
In order to be able to use a version of `zeroize` newer than 1.3 we need to remove a similar restriction from `curve25519-dalek` as well.

zeroize: Allow versions newer than 1.3 for `aes-gcm-siv`

---

core/benches/banking_stage.rs
core/src/replay_stage.rs
core/tests/epoch_accounts_hash.rs
ledger/src/blockstore_processor.rs
poh/src/poh_recorder.rs
program-test/src/lib.rs
rpc/src/rpc.rs
runtime/src/bank.rs
runtime/src/bank_forks.rs
runtime/src/installed_scheduler_pool.rs
runtime/src/lib.rs

There's no nice mechanism to accompany a scheduler with a bank for both replaying and banking stage usages in a uniform fashion.
Introduce it (`BankWithScheduler`) before actual introduction of scheduler code...
the code change is rather broad. but i tried to make this pr straightforward as much as possible..

Add BankWithScheduler for upcoming scheduler code

---

banking-bench/src/main.rs
client-test/tests/client.rs
core/benches/banking_stage.rs
core/src/consensus.rs
core/src/repair/ancestor_hashes_service.rs
core/src/repair/repair_service.rs
core/src/repair/serve_repair.rs
core/src/replay_stage.rs
ledger/benches/blockstore.rs
ledger/benches/protobuf.rs
poh/src/poh_recorder.rs
poh/src/poh_service.rs
rpc/src/cluster_tpu_info.rs
rpc/src/rpc_service.rs
rpc/src/rpc_subscriptions.rs
rpc/src/transaction_status_service.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/standard_broadcast_run.rs

The `get_tmp_ledger_path!()` macro is used in lots of tests to create a directory on disk for the ledger, typically combined with passing this path to `Blockstore::open()`. However, it is up to the caller to remember to remove those contents at the end of their test. This is a burden and has obviously been forgotten a decent amount (you may notice the `farf` directories on disk). And, even if the test does remember to call `Blockstore::destory()`, the enclosing directories still linger.
Update instances of `get_tmp_ledger_path!()` to `get_tmp_ledger_path_auto_delete!()`.
Two notes for reviewers:
- This PR did not get all instances, as several instances of the non-self-cleaning macro are called in helper functions. Using the self-deleting macro in the helpers would be bad as it would go …

Replace get_tmp_ledger_path!() with self cleaning version

---

programs/sbf/rust/invoke/src/processor.rs
programs/sbf/rust/ro_modify/src/lib.rs
programs/sbf/tests/programs.rs
sdk/bpf/scripts/install.sh
sdk/cargo-build-sbf/src/main.rs
sdk/program/Cargo.toml
sdk/sbf/scripts/install.sh

Update platform tools to rust 1.72, clang 16.

Bump platform-tools to v1.39

---

program-runtime/src/loaded_programs.rs
runtime/src/bank_forks.rs

`LoadedPrograms` currently clones `Debug` trait. But, not all information is useful for debugging. A custom impl will be more useful.
Implement debug for LoadedPrograms cache.
Fixes #

Custom debug impl for LoadedPrograms cache

---

accounts-db/src/accounts_db.rs

When we disable rewrites, we will accumulate old append vecs & slots. We use ancient append vec packing to combine those.
fix typo
Fixes #

typo in variable name

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

When we disable rewrites, we will accumulate old append vecs & slots. We use ancient append vec packing to combine those. Some stats could use some love.
add, remove, and update stats better for ancient packing.
Sample output:
```
num_slots_shrunk=3
bytes_ancient_created=3,584,440,968
```
Fixes #

fix some ancient stats

---

geyser-plugin-interface/src/geyser_plugin_interface.rs

Spurious validator crashes due to rust version mismatch for validator and plugins.
Made geyser interface repr(c) to improve interface stability
Fixes #

Made geyser interface repr(c) to improve interface stability

---

Cargo.lock
cargo-registry/Cargo.toml
cargo-registry/src/crate_handler.rs
cargo-registry/src/main.rs
cargo-registry/src/response_builder.rs

`cargo fetch` need fixes, as it currently doesn't return a crate package.
- Return the crate package as response to the download command
- Use base16 for program ID. Using base58 doesn't work as it is case sensitive, and fetch uses lower case for all the values
- Return just the crate file, and do not include meta data information.
Fixes #

Cargo registry server updates to download crates

---

accounts-db/src/ancient_append_vecs.rs

When we disable rewrites, we will accumulate old append vecs & slots. We use ancient append vec packing to combine those.
It is more efficient to pack a larger range of slots at a time instead of a small amount each call.
Add a low water mark. By default, when there are more than 10k ancient slots, the algorithm will pack down to 5k ancient slots. Then, the algorithm will do nothing until 10k is exceeded again.
Fixes #

ancient pack: add low water mark

---

Cargo.lock
Cargo.toml

`curve25519-dalek` v3.2.1 has a constraint on the maximum `zeroize` version to be no more than 1.3.
At the same time, `cargo` does not want to construct a dependency graph with duplicate instances of a crate, when the first non-zero version of those instances are the same.  That is, it refuses to build a workspace with both 1.3 and 1.4 versions of `zeroize`.
`zeroize` is actually backward compatible, and `curve25519-dalek` restriction is overly pessimistic.  This package lifted this restriction in newer versions, but we still depend on older version and can not immediately update.
Use a patched version based on v3.2.1 that also removes the unnecessary constraint.

zeroize: Allow versions newer than 1.3 for `curve25519-dalek`

---

accounts-bench/src/main.rs
accounts-db/benches/append_vec.rs
accounts-db/src/accounts.rs
accounts-db/src/accounts_cache.rs
accounts-db/src/accounts_db.rs
accounts-db/src/accounts_hash.rs
accounts-db/src/ancient_append_vecs.rs
accounts-db/src/append_vec.rs
accounts-db/src/stake_rewards.rs
accounts-db/src/storable_accounts.rs
core/src/accounts_hash_verifier.rs
core/tests/epoch_accounts_hash.rs
runtime/benches/accounts.rs
runtime/src/accounts_background_service.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/snapshot_bank_utils.rs
runtime/src/snapshot_minimizer.rs
runtime/src/snapshot_package.rs
runtime/tests/accounts.rs

Feature was activated, so this code can be removed for simplicity going forward.
Fixes #

remove IncludeSlotInHash after feature activation on mnb

---

docs/src/developing/runtime-facilities/programs.md

There are typos in the native program documentation for Secp256k1 signature verification, please see screenshot
Fix the doc typos, no code changes
Fixes #

Fix typos in documentation for Secp256k1 native program

---

zk-token-sdk/src/range_proof/generators.rs
zk-token-sdk/src/range_proof/mod.rs

The range proof docs are really a mess with incomplete documentation and TODO's.
It is a little embarrassing, but these have to be addressed.
- [4a79a1f](https://github.com/solana-labs/solana/pull/33803/commits/4a79a1fde31fdc922bd7433f70a377f8ad8d2ae0): I added docs to cite dalek-cryptography implementation of bulletproofs and how our implementation differs.
- [4a79a1f](https://github.com/solana-labs/solana/pull/33803/commits/4a79a1fde31fdc922bd7433f70a377f8ad8d2ae0): Removed a TODO comment on pre-computing generators for efficiency. I initially considered pre-computing the generators that are needed for range proofs as a form of optimization. I tested how pre-computing the generators effect the proof generation and runtime when I was benching the zk-token-proof program for compute units …

[zk-token-sdk] clean-up range-proof docs

---

turbine/src/quic_endpoint.rs

monitor turbine QUIC endpoint
added metrics.

adds metrics to turbine QUIC endpoint

---

zk-token-sdk/src/encryption/discrete_log.rs

https://github.com/solana-labs/solana/issues/33506
Add a check on `compression_batch_size` in the discrete logic so that the program errors gracefully.
Fixes #

[zk-token-sdk] Check that discrete log compression batch size is greater than 0

---

accounts-db/src/accounts_hash.rs

Optimize `CumulativeOffset` for raw data index during accounts hash calculation. 
The raw data is at most 2d. Therefore, instead of using a Vec to store one or two indexes to the data, we can change it to use `[usize; 2]`.
This saves heap allocation and one pointer deref when reading the index.
Use `[usize; 2]` for `CumulativeOffset`
Fixes #

Optimize account hash CumulativeOffset index from vec to 2-element array

---

accounts-db/src/storable_accounts.rs

Some impls of StorableAccounts are erroneously marked with `#[allow(dead_code)]`. 
Remove the annotation.

Removes `#[allow(dead_code)]` in StorableAccounts impl

---

accounts-db/src/accounts_hash.rs

1. `CumulativeOffset` and its fields are marked public, but are only used within `accounts_hash.rs`. 
2. With https://github.com/solana-labs/solana/pull/33839, the type of `index` will change to a two-element array. A default doesn't necessarily make sense, as we'll always need at least one valid index to be set.
Remove `pub` and `Default`.

Removes Default and pub from CumulativeOffset

---

core/src/validator.rs

`Validator::new()` already returns a `Result`, and the caller (in `validator/src/main.rs`) unwraps or prints the error & exits the process.
Replace `.expect()` statements with `.map_err(...)?`

Replace several .expect() statements with error handling

---

docs/src/running-validator/validator-stake.md
docs/src/running-validator/validator-start.md

New block building strategy ignores votes from unstaked validators.
First time validators might be confused why votes aren't landing.
Update docs to include the requirement. 
Fixes #

docs: outline requirement of stake in order to vote

---

client-test/tests/client.rs
core/src/commitment_service.rs
core/tests/snapshots.rs
program-runtime/src/loaded_programs.rs
rpc/src/rpc_pubsub.rs
rpc/src/rpc_subscriptions.rs
runtime/src/bank.rs
runtime/src/bank_forks.rs

`WorkingSlot` trait could be replaced with the global instance of `ForkGrpah`.
Use  the global `ForkGraph` if it's available. Otherwise, use the provided `WorkingSlot`.
Updated unit tests.
Fixes #

Use program cache fork graph in extract()

---

cargo-registry/src/crate_handler.rs
cargo-registry/src/main.rs

The on-chain program cannot be decompiled into a crate file. So cargo-registry server cannot be used for fetching the crate.
This is a temporary solution.
- Append the crate to ELF file (fixup the toml files and directory name in the package)
- On cargo fetch, retrieve the program, and return the appended crate from it. 
Fixes #

Append crate to ELF file while deploying program

---

core/src/repair/quic_endpoint.rs

monitor repair QUIC endpoint
added metrics.

adds metrics to repair QUIC endpoint

---

cargo-registry/src/crate_handler.rs

Crate version is hardcoded to `0.1.0` in registry server.
- Compute the crate version from the uploaded program
- Use the computed version in registry index
Fixes #

Retrieve crate version from cargo-registry package

---

ledger/src/bigtable_upload.rs

See https://github.com/solana-labs/solana/issues/33831#issuecomment-1779203305 for a detailed walk-through.
While this problem of looping on the same slot seems to be caused by an operator restarting their warehouse node without `--no-snapshot-fetch` (which can cause a gap in the blockstore), we can still be friendly and break out of this loop
Fixes #33831

Update upload_confirmed_blocks() return value when no blocks to upload

---

ledger/src/bigtable_upload_service.rs

Both `solana-ledger-tool bigtable upload` and the BigtableUploadService call `solana_ledger::bigtable_upload::upload_confirmed_blocks()` in a loop. However, they treat the return value (last slot checked) slightly differently.
Ledger tool increments the value to start checking on a fresh slot: https://github.com/solana-labs/solana/blob/70107e2196c12ef46d73788c55502ffd3fe2080e/ledger-tool/src/bigtable.rs#L83
The BigtableUploadService does not:
https://github.com/solana-labs/solana/blob/70107e2196c12ef46d73788c55502ffd3fe2080e/ledger/src/bigtable_upload_service.rs#L120
This means that the BigtablUploadService is rechecking the starting slot of a range on every iteration of the loop. It's probably not a lot of wasted work, but not nothing.
I don't think there is a specific reason the …

BigtableUploadService: increment start_slot to prevent rechecks

---

ledger/src/blockstore.rs
rpc/src/rpc.rs

As described in #33858, we unintentionally support returning block times for unrooted slots from Blockstore. This results in weird behavior where these block times are available only until the slot is purged from the local ledger, since only rooted slots are uploaded to bigtable.
- Add a new method to Blockstore that only returns block times for rooted slots
- Use this method in solana-rpc. This makes `getBlockTime` follow `getBlock` logic more closely
(edit) I thought at first we could deprecate the old method, but we do use it internally to Blockstore in `get_transaction_with_status()` and `get_confirmed_signatures_for_address2()`. We could maybe un-pub it...
Partially fixes #33858

Blockstore: only return block times for rooted slots

---

cargo-registry/src/crate_handler.rs
cargo-registry/src/main.rs

`cargo-registry` code can use some cleanup wrt names of structs, member variable and functions.
- Code cleanup
- No functional changes
Fixes #

Cleanup cargo registry code

---

core/src/banking_stage/immutable_deserialized_packet.rs
core/src/banking_stage/transaction_scheduler/mod.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
runtime/src/transaction_priority_details.rs

Need control-flow for packet receiving & scheduler.
- Add new struct `SchedulerController` that is the main interface for the scheduling thread
- Add basic sanity check tests that loop works. Actual schedule tests are in the scheduler itself, as this class could have drop-in replacements for the scheduler.
Fixes #

TransactionScheduler: SchedulerController

---

core/src/replay_stage.rs
core/src/validator.rs

Adjust solana-core for cleaner scheduler-pr diff

---

program-test/src/lib.rs
programs/sbf/tests/programs.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

Define register_unique_recent_blockhash_for_test

---

.github/workflows/downstream-project-spl.yml

We use the latest sccache. If they've tagged a new version but the binaries haven't been uploaded, we will be blocked.
https://github.com/solana-labs/solana/actions/runs/6668375969/job/18124723674
pin sccache version for sccache action.

ci: fixed sccache version for sccache-action

---

Cargo.lock
Cargo.toml

#33516 used an incorrect version of the commit hash.
One from a different repository.
Fixes
commit a099c7a0b8ac4281dbc6dd422d697e700c28a7d1
Author: Illia Bobyr <illia.bobyr@solana.com>
Date:   Mon Oct 23 12:19:59 2023 -0700
zeroize: Allow versions newer than 1.3 for `curve25519-dalek` (#33516)
Use correct commit hash from `solana-labs/curve25519-dalek.git`.

Fixup: zeroize: Allow versions newer than 1.3 for `curve25519-dalek`

---

multinode-demo/bootstrap-validator.sh
multinode-demo/validator.sh

- multi-node demo scripts do not currently support --block-production-method arguments.
- #33890 adds a new variant we should be supporting in these scripts
- Add block-production-method support to `bootstrap-validator.sh` and `validator.sh`
Fixes #

multinode-demo scripts support --block-production-method arg

---

Cargo.lock
core/src/replay_stage.rs
ledger/Cargo.toml
ledger/src/blockstore_processor.rs
programs/sbf/Cargo.lock
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/installed_scheduler_pool.rs

The upcoming unified scheduler is async by nature. so, the replay stage must eventually be blocked on block boundaries in some way for tx execution completion. however, the minimal `InstalledSchduler` (introduced at #33875) doesn't provide any such way.
Implement it and wire it exhaustively into all the needed relevant blocking points.
(fyi, planned next prs: 1. introduce `InstallSchedulerPool` 2. introduce `SchedulerPool` as its actual impl)

Define InstalledScheduler::wait_for_termination()

---

core/src/repair/repair_service.rs
core/src/repair/serve_repair.rs
gossip/tests/gossip.rs
streamer/src/nonblocking/sendmmsg.rs
streamer/src/sendmmsg.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/broadcast_duplicates_run.rs

`batch_send()` and `multi_target_send()` error handling is fragile.
Update error handling to `match` statement. Adding new error return codes will cause compilation failure.
Fixes #

improve batch_send error handling

---

tokens/src/spl_token.rs

`solana-tokens` is overly public in its interface.
Reduce the scope of some helper functions. crates.io reports that no projects are using `solana-tokens` as a dependency, so this shouldn't break anyone.
Remove a function that isn't being used (and we couldn't tell, bc pub)

solana-tokens: unpub/remove some helpers

---

geyser-plugin-manager/src/geyser_plugin_manager.rs

On `plugin_reload` we need to check the new plugin name, the path to the plugin can be changed in the config file, and as a result, already loaded plugin can be loaded again.
Add plugin name check.

check plugin name on plugin_reload rpc call

---

tokens/src/commands.rs
tokens/src/spl_token.rs

Resolves https://github.com/solana-labs/solana/issues/16489.
Hey @CriesofCarrots, I took this task on to get a bit more comfortable with Rust, lets see if it fits what you had in mind.

cli: solana-tokens, validate inputs gracefully

---

Cargo.lock
Cargo.toml
ledger/src/blockstore_processor.rs
programs/sbf/Cargo.lock
runtime/Cargo.toml
runtime/src/bank_forks.rs
runtime/src/installed_scheduler_pool.rs

`InstalledScheduler` is expected to be backed by multiple threads. thus, it's desirable to be reused to avoid thread recreation cost.
introduce some pooling mechanism.
also, finished off all the doc comments.
note that this pr contains only the trait interface bits. the actual impl will be added by later pr.

Introduce InstalledSchedulerPool trait

---

.buildkite/hooks/post-checkout
ci/docker-run.sh
ci/docker-rust-nightly/Dockerfile
ci/docker-rust/Dockerfile

we mount home directory and cargo directory when we run docker. actually we can just install those dependencies into our docker image.
build our Docker images on Ubuntu.
(will upload these images when I get approve. I have already test them and all green 🤞 but I will still run them with our ci agents again to ensure everything is fine)

ci: reorg docker images

---

account-decoder/src/lib.rs

It's hard to use `UiAccountData` with [parse_token](https://docs.rs/solana-account-decoder/1.14.27/solana_account_decoder/parse_token/index.html) function.
- encapsulate decode function deeper

chore: impl decode for UiAccountData

---

docs/src/validator/get-started/setup-a-validator.md

The docs are trying to tell the user to make sure all packages are up to date, however an `upgrade` should be run, not an `install`.
Update `sudo apt install` to `sudo apt upgrade`

docs: updating apt install to apt upgrade

---

accounts-db/src/tiered_storage.rs
accounts-db/src/tiered_storage/footer.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs
accounts-db/src/tiered_storage/writer.rs

The current tiered-storage code uses "account-index" to call index-block.
This could lead to confusion especially as we start giving each offset/position/index a specific type.
This PR renames all structs/variables that use account-index to refer to index-block.

[TieredStorage] Rename account-index to index-block

---

ledger/src/blockstore.rs
rpc/src/rpc.rs

See https://github.com/solana-labs/solana/pull/33901/files#r1374932022 for some discussion
Instead of returning Result<Option<UnixTimestamp>>, return Result<UnixTimestamp> and map None to an error. This makes the return type similar to that of Blockstore::get_rooted_block().
Given that `get_rooted_block_time()` is a new addition to the `Blockstore` API that is only present in master as of right now (https://github.com/solana-labs/solana/pull/33871), I don't think there are any concerns about adjusting the return type of a `pub` function

Remove Option<_> from Blockstore::get_rooted_block_time() return type

---

accounts-db/src/tiered_storage/index.rs

TieredStorage conceptually has different offsets.  However, the current code directly
uses the same primitive type for accessing offsets, which is error-prone as one could
easily use one offset to access data that should be accessed with a different offset
type.
This PR introduces the AccountOffset type, which allows static-check to on different
type of TieredStorage offsets.

[TieredStorage] Add AccountOffset type

---

accounts-db/src/accounts_db/geyser_plugin_utils.rs
accounts-db/src/accounts_update_notifier_interface.rs
geyser-plugin-manager/src/geyser_plugin_service.rs

The interface covered by the RwLock has no "mut" operations, leaving the RwLock unnecessary for AccountNotify.
Remove unnecessary RwLock from AccountNotify in geyser.
Fixes #

Remove RwLock on AccountsUpdateNotifier

---

install/src/command.rs

Using `solana-install init` makes API requests to GitHub even when the given version is already installed locally.
Only fetch releases from GitHub if the given version is not installed.
Fixes #33948

Fix `solana-install init` making unnecessary API requests

---

accounts-db/src/accounts_db.rs
accounts-db/src/accounts_hash.rs
accounts-db/src/cache_hash_data.rs

When we pack ancient vecs, we end up with  non-ancient append vecs interleaved with ancient append vecs.
This ends up causing hash calculation to take much longer. Hash Calculation is very sensitive to the # of chunks.
The current chunking algorithm assumes the model of appending ancient append vecs.
Just create ranges instead.
The blue line that drops here is restarting with the removal of the ancient splitter algorithm (this pr).
Here's the overall hash calc time with removing this code:
Fixes #

chunk all ancient append vecs

---

accounts-db/src/tiered_storage/index.rs

TieredStorage conceptually has different offsets. However, the current code directly
uses the same primitive type for accessing offsets, which is error-prone as one could
easily use one offset to access data that should be accessed with a different offset
type.
This PR adds IndexOffset type -- a struct for obtaining the ith entry inside the
index-block to obtain account's offset and address.

[TieredStorage] Add IndexOffset type

---

core/src/validator.rs
geyser-plugin-manager/src/geyser_plugin_service.rs
rpc/src/transaction_notifier_interface.rs
rpc/src/transaction_status_service.rs

The RwLock on TransactionNotify interface is unnecessary as there is no method need write protection.
Remove unnecessary RwLock on TransactionNotify in geyser
Fixes #

Remove RwLock on TransactionNotifier

---

scripts/cargo-install-all.sh

Canaries use the release build, which limits debugging options
Add a --release-with-debug option that uses the release-with-debug profile. The canaries will use this via a corresponding change in cluster-ops scripts.
To see a sample run check out `mce1:~/build-artifacts/`

Add --release-with-debug option to cargo-install-all.sh

---

Cargo.toml
programs/sbf/Cargo.toml

I ran into the errors described at #33424 while developing a geyser plugin, despite having the patch statements in my Cargo.toml already. I didn't think to wipe my Cargo.lock until @joncinque suggested it, and it fixed all my problems. 
The behavior feels a bit unintuitive. If having compiled successfully, you comment out the patch statements and recompile (fails), cargo adds the crates.io dependencies to the Cargo.lock. If you subsequently uncomment the patch statements and recompile, cargo does not remove these declarations from the Cargo.lock, so the compilation continues to fail.
We have helpful comments around the patch statements in the monorepo Cargo.tomls; extend them with some tips about using downstream.
Fixes #33424

Add more comments about solana-program patch (downstream)

---

ci/test-checks.sh
scripts/cargo-clippy.sh

CI uses a number of parameters when running `cargo clippy`.  Repeating the same command manually requires some copy/pasting.  It is easier when there is a common script that can be run by everyone.
Add `scripts/cargo-clippy.sh` that is used by CI and is executable directly.

scripts/cargo-clippy.sh: Extract our non-trivial `cargo clippy` command

---

ledger/src/blockstore.rs
rpc/src/rpc.rs

See https://github.com/solana-labs/solana/issues/33859 for some additional details but the TLDR is:
- The current logic in `rpc.rs` looks up min/max roots from the Blockstore to perform bounds check for the sake of error reporting
- Looking up these roots is currently expensive as it is done by constructing an iterator
- Regardless of the overhead of looking up min/max roots, some of these checks are repetitive
Remove / condense code to avoid repeating checks that have already occurred. Namely,
- `Blockstore::is_skipped()`, which was called by these two RPC methods, has been removed as it was redundant
- This avoids the overhead of (2) rocksdb iterators
- Rename `check_blockstore_root() ==> check_blockstore_bounds()` and add a bunch of comments about the handling of `Blockstore` errors at …

 Remove redundant bounds check from getBlock and getBlockTime

---

geyser-plugin-manager/src/geyser_plugin_manager.rs

When loading of geyser plugin is failed we get the error message `Cannot load plugin shared library` but does not show the exact error message so that we can fix the plugin.
Added the error message that we received while loading the plugin.
Fixes #

Display error message while laoding geyser plugins

---

core/src/replay_stage.rs
core/src/tvu.rs
geyser-plugin-manager/src/block_metadata_notifier_interface.rs
geyser-plugin-manager/src/geyser_plugin_service.rs

The BlockNotifier in geyser unnecessarily uses a RwLock as the interface has no mut operations.
Removes the RwLock from BlockNotifier
Fixes #

Remove RwLock on BlockNotifier

---

core/src/repair/quic_endpoint.rs

QUIC connections timeout due to infrequent repair requests.
Added `keep_alive_interval` to transport config.

adds keep-alive-interval to repair QUIC transport config

---

turbine/src/quic_endpoint.rs

quinn default transport config is not suitable for turbine.
Set explicit values for transport configs in turbine QUIC endpoint

expands transport configs in turbine QUIC endpoint

---

accounts-db/src/tiered_storage/hot.rs

#33927 introduced a new type AccountOffset, but HotStorageReader
still uses `usize` to access accounts.
This PR makes HotStorageReader use the new AccountOffset type.

[TieredStorage] Make HotStorageReader use AccountOffset type

---

ledger-tool/src/program.rs
program-runtime/src/loaded_programs.rs
runtime/src/bank.rs
runtime/src/bank/metrics.rs
runtime/src/bank/tests.rs

This is a different approach to the problem as #32172 was flawed. It ended the recompilation phase at the first block after the epoch boundary, but we need to wait for a rerooting to be sure that we won't replay any blocks from before the epoch boundary anymore.
- Adds `LoadedPrograms::upcoming_environments`: Which is `Some` during the recompilation phase, even if there is no change to any environment.
- Moves `LoadedPrograms::prune_feature_set_transition()` into `LoadedPrograms::prune()`: Delays it to happen on the first rerooting after the epoch boundary.
- Removes the manually managed `FEATURES_AFFECTING_RBPF` list: Because we can now automatically detect changes by using `BuiltinProgram::eq()`.
- Adds parameter recompile to `Bank::load_program()`: Which is `Some` when called from …

Feature - Epoch boundary recompilation phase

---

ledger/src/blockstore.rs
transaction-status/src/lib.rs

There is interest in storing entry data in BigTable for redundancy. The BigTable uploader uses `Blockstore::get_rooted_block()` which flattens all the transactions in the block. But since it's already looping through all entries, this seems like the right place to collect Entry data as well.
Add helper structs and method to support a new `Blockstore::get_rooted_block_with_entries()`

Add Blockstore::get_rooted_block_with_entries method

---

ledger/src/blockstore.rs
local-cluster/src/integration_tests.rs
local-cluster/tests/local_cluster.rs

The test_duplicate_with_pruned_ancestor test needs to get around a
limitation where the shreds with a parent older than the latest root are
discarded. The previous approach manually adjusted the root value in the
blockstore; this is not ideal in that it is fiddling with the inner
working of Blockstore.
So, use the is_trusted argument in Blockstore::insert_shreds(); setting
is_trusted=true bypasses the sanity checks (including the parent >=
latest root check).

Use is_trusted bool in insert_shreds() instead manually adjusting root

---

runtime/src/snapshot_utils.rs

`verify_and_unarchive_snapshots()` doesn't have any documentation. It's a public function, so it probably should.
Add documentation.

Adds documentation to verify_and_unarchive_snapshots()

---

core/src/consensus.rs
core/src/validator.rs
gossip/src/duplicate_shred_handler.rs
ledger-tool/src/bigtable.rs
ledger/src/blockstore.rs

The `Blockstore` currently maintains a `RwLock<Slot>` of the maximum root it has seen inserted. The value is initialized during `Blockstore::open()` and updated during calls to `Blockstore::set_roots()`. Accessing this `RwLock` is cheaper than constructing an iterator through the roots column every time the maximum root value is desired. The maximum root value is queried fairly often:
- Shred ingestion checks the parent slot against the max root; slots with a parent older than the most recent root can immediately be discarded as not being on the main fork
- RPC calls want to know the max root for findings slots with confirmation level `confirmed`
However, the access pattens of the max slot mirror that of an atomic, and the `RwLock` is overkill. Namely,
- All reads simply get a read lock …

Change Blockstore max_root from RwLock<Slot> to AtomicU64

---

runtime/src/snapshot_utils.rs

`create_tmp_accounts_dir_for_tests()` is used by tests to create a temp "accounts path" directory. But nothing is stopping a non-test from calling it...
...until now! Put it behind DCOU.
(and give the function some documentation too, for good measure)

Puts create_tmp_accounts_dir_for_tests() behind DCOU

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs
ledger/src/blockstore_db.rs
ledger/src/blockstore_meta.rs
ledger/src/shred.rs

In order to detect duplicate blocks with conflicting merkle roots we need to be able to access the merkle root for each FEC set. We would like to store the merkle root and relevant meta information for easy access in blockstore.
Add new merkle root meta column 

add merkle root meta column to blockstore

---

runtime/src/snapshot_utils.rs

`verify_and_unarchive_snapshots()` returns the next append vec id. There is a type alias for this already, `AtomicAppendVecId`. We already use it *within* the function, but the return type doesn't use it, yet it should.
Use the alias.

Use AtomicAppendVecId type alias in verify_and_unarchive_snapshot()

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

the bumping version action failed: https://github.com/solana-labs/solana/actions/runs/6829840095
have this bumping version PR first and will investigate it later

Bump version to v1.17.6

---

core/src/banking_stage.rs
core/src/banking_stage/committer.rs
core/src/banking_stage/decision_maker.rs
core/src/banking_stage/transaction_scheduler/mod.rs
core/src/validator.rs

Need a way to use the new BankingStage w/ central scheduler
- Factor out some code for spawning legacy/thread-local-multi-iterator banking stage threads
- Add `BlockProductionMethod::CentralScheduler` variant
- Add path to spawn new scheduling thread, workers, and legacy voting threads
- Re-use existing banking stage test to verify new production method works in basic fashion
Fixes #

TransactionScheduler: CLI and hookup for central-scheduler

---

accounts-db/src/tiered_storage/index.rs

In IndexBlockFormat, both `IndexOffset` and `AccountOffset` parameters
are named `offset` in some functions which could be confusing.
Renamed `offset` to `index_offset` and `account_offset` to improve
readability.

[TieredStorage] Improve param naming of IndexBlockFormat

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

HotStorageReader currently not yet has an API to obtain account_offset
This PR adds HotStorageReader::get_account_offset() which takes
IndexOffset and returns AccountOffset.
A new unit-test is included in this PR.

[TieredStorage] HotStorageReader::get_account_offset

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

There's been an effort underway to make append vecs the correct size. Among other benefits, this allows readers to not have to be told how many bytes are valid in an append vec.
I found a new place where we pad the size of an append vec to a page size.
Remove alignment to a page size when we're shrinking.
Fixes #

stop page aligning shrunk append vecs

---

accounts-db/src/tiered_storage/footer.rs
accounts-db/src/tiered_storage/hot.rs

TieredStorageFooter::owners_offset refers to the offset to the
owners block, which looks very similar to OwnerOffset that
has a completely different concept -- the offset to access the
address of an owner in the owners-block.
Similar to the previous renaming index_offset to index_block_offset,
this PR renames owners_offset to owners_block_offset to
avoid confusion.

[TieredStorage] Rename owners_offset to owners_block_offset

---

core/src/tpu_entry_notifier.rs
geyser-plugin-interface/src/geyser_plugin_interface.rs
geyser-plugin-manager/src/entry_notifier.rs
ledger/src/blockstore_processor.rs
ledger/src/entry_notifier_interface.rs
ledger/src/entry_notifier_service.rs

In order to verify an Entry, geyser consumers currently have to walk all the previous entries in the block and sum the executed tx counts to figure out which transactions are included in the current entry. However, the node knows the transaction index an Entry starts with, so we can save geyser consumers quite a few operations by emitting this index too.
- Add ReplicaEntryInfoV2, which includes `starting_transaction_index`
- Populate the new field in replay stage
- Cache the tx index in TpuEntryNotifier to populate in banking stage as well
- Use new ReplicaEntryInfo variant in geyser

Geyser: add starting entry to ReplicaEntryInfo(V2)

---

ledger/src/blockstore.rs
ledger/src/blockstore_metric_report_service.rs
ledger/src/blockstore_metrics.rs

Currently, the RPC API that touch the Blockstore emit a datapoint for
each call. For an RPC node serving many requests, these datapoints
could get quite noisy, both in logs as well as traffic to the metrics
agent.
So, instead of submitting a datapoint for every call, accumulate the
number of calls in a struct and report that entire struct periodically.

Condense Blockstore RPC API datapoints

---

sdk/src/quic.rs

It has been found in across region testing, transaction sending to remote regions are some time failing with WriteError(Stopped). This is caused that after a stream is opened, the client is blocked from sending due to the following error in Quinn on blocked by connection level flow control. This is due to limited receive window among the multiple streams opened, some stream spent long time in waiting for the limit to be available. The problem is not as obvious when the latency is low as contenders might release the usage fast enough before the time out is reached. But in the case of wide area network with longer latency the problem becomes more severe. Fundamentally, if we allow that many of streams to be opened, we need to ensure they have enough bandwidth to be processed concurrently. …

Adjust receive window to make them linear to the count of streams

---

docs/src/cli/deploy-a-program.md
docs/src/implemented-proposals/reliable-vote-transmission.md
docs/src/proposals/accounts-db-replication.md
docs/src/proposals/handle-duplicate-block.md
docs/src/proposals/timely-vote-credits.md

I found some English mistakes in the documentation
English mistake corrections

Fix some typo in the documentation

---

validator/src/cli.rs

accounts disk index is the future, but we still offer a flag to disable it. every operator silently reverting to old behavior is going to be a problem when we need to drop support. 
reduce the burden today. deprecate the flag

validator: deprecates `--disable-accounts-disk-index`

---

core/src/cluster_info_vote_listener.rs

logic is not updated for `VoteStateUpdate`, end up checking all 31 slots every time which grabs the lock shared with replay
filter out seen slots, no need to be precise and check every single slot, can filter by latest slot because propagated check rolls up to parent anyway. 
potentially helps #33017

reduce locking in propagated check for VoteStateUpdate

---

accounts-db/src/tiered_storage.rs
accounts-db/src/tiered_storage/owners.rs

A TieredStorage file has three types of block:  accounts block, index block,
and owner block, but implementation of the TieredStorage OwnersBlock
is missing in the current master.
This PR implements OwnersBlock which stores a set of owners' addresses
in a compact but efficient way.
A new unit-test is included in this PR.

[TieredStorage] OwnersBlock

---

programs/bpf_loader/src/syscalls/cpi.rs
programs/sbf/rust/invoke/src/processor.rs
programs/sbf/tests/programs.rs

`reserve(additional)` reserves `additional` bytes on top of the current _length_ not capacity. Before this fix we could potentially reserve less capacity than required.

cpi: fix capacity check in update_caller_account

---

accounts-db/src/accounts.rs

Cleanup - Feature gate of `disable_builtin_loader_ownership_chains`

---

programs/bpf_loader/src/lib.rs
runtime/src/bank.rs

Cleanup - Feature gate of `limit_max_instruction_trace_length`

---

ledger/src/blockstore_meta.rs

After discussion, it seems like legacy shreds should be supported for a while longer. To avoid having to use `unwrap_or_default()` and mess around with `Hash::default()`, we change the type of the yet to be used column to optional. 
Change type. This will be backported to the same branches as #33979  

blockstore: make merkle root Optional in MerkleRootMeta column

---

geyser-plugin-manager/src/geyser_plugin_manager.rs

Unloading a simple plugin which does nothing other than creating the GeyserPlugin object is found to be crashing the validator. The reason for the crash is there are two objects when _drop_plugin is called: the Library object and the Box<dyn GeyserPlugin> object. The current implementation drops the library first which already de-allocate the memory under the boxed GeyserPlugin. And when the GeyserPlugin is dropped, it tries to deallocate the memory and cause a segmentation fault.
Explicit ordering of the drop of Library and Box<dyn GeyserPlugin>: drop the latter explicitly first.
Fixes #

Fix geyser plugin unload crash

---

gossip/src/crds_gossip_pull.rs
gossip/src/crds_gossip_push.rs

Working towards migrating from legacy contact-info to the new contact-info: https://github.com/solana-labs/solana/pull/29596
The commit propagates the new contact-info through gossip.

propagates the new contact-info through gossip

---

program-runtime/src/invoke_context.rs
programs/bpf_loader/src/syscalls/cpi.rs
programs/bpf_loader/src/syscalls/logging.rs
programs/bpf_loader/src/syscalls/mem_ops.rs
programs/bpf_loader/src/syscalls/mod.rs

Cleanup - Feature gate of `check_slice_translation_size`

---

programs/bpf_loader/src/syscalls/cpi.rs

Cleanup - Feature gate of `move_serialized_len_ptr_in_cpi`

---

ledger/src/blockstore_meta.rs
ledger/src/shred.rs
ledger/src/shred/merkle.rs
ledger/src/shred/shred_code.rs
ledger/src/shred/shred_data.rs

We need to access the `merkle_root` for merkle shreds in blockstore.
Dispatch to it, return `None` for legacy shreds.
Split from #33889

shred: expose merkle root for use in blockstore

---

programs/bpf_loader/src/lib.rs

Cleanup - Feature gate of `enable_program_redeployment_cooldown`

---

accounts-db/src/tiered_storage/hot.rs

The HotStorageReader does not have an API to obtain owners_address.
This PR adds HotStorageReader::get_owner_address().
A new unit-test is added to this PR.

[TieredStorage] HotStorageReader::get_owner_address

---

cli-output/src/cli_output.rs
cli/src/program.rs
cli/tests/program.rs

Solana CLI doesn't support extending program data yet
Added a new subcommand `solana program extend` which allows extending the program data of an upgradeable program
```
USAGE:
solana program extend [FLAGS] [OPTIONS] <PROGRAM_ID> <ADDITIONAL_BYTES>
FLAGS:
-h, --help                           Prints help information
--no-address-labels              Do not use address labels in the output
--skip-seed-phrase-validation    Skip validation of seed phrases. Use this if your phrase does not use the BIP39
official English word list
--use-quic                       Use QUIC when sending transactions.
--use-udp                        Use UDP when sending transactions.
-V, --version                        Prints version information
-v, --verbose                        Show additional information …
```

cli: add solana program extend subcommand

---

programs/bpf_loader/src/syscalls/mod.rs
sdk/src/secp256k1_instruction.rs

The `libsecp256k1_0_5_upgrade_enabled` feature is enabled on all the clusters and can be cleaned up
There were a bunch of tests that intentionally disabled the feature but they all still pass when the feature is enabled 🤷🏻‍♂️ 
Fixes #

clean feature: libsecp256k1_0_5_upgrade_enabled

---

programs/config/src/config_processor.rs

`dedupe_config_program_signers` is already activated on all clusters and can be cleaned up

clean feature: dedupe_config_program_signers

---

programs/system/src/system_processor.rs

`system_transfer_zero_check` feature is already active on all clusters and should be cleaned up

clean feature: system_transfer_zero_check

---

storage-bigtable/src/bigtable.rs

I'm working on adding support for bigtable uploads to include entries. This will require users to add an `entries` table to their bigtable instances. Currently, our storage-bigtable write apis retry with exponential backoff, and will retry forever without reporting errors. This means that users who run the new entries upload code without having prepped the table will see their bigtable-uploader hang with no indication why.
Return `backoff::Error::Permanent` when a table isn't found so that retry halts and an error is actually printed.
Some kind of general error tracing across all the places we use `retry` would probably be helpful, but this seems like a reasonable short circuit.

storage-bigtable: Return error if attempting to write to table NotFound

---

programs/stake/src/stake_instruction.rs
programs/stake/src/stake_state.rs

`require_custodian_for_locked_stake_authorize` feature is activated on all clusters and was never cleaned up
Cleans up the feature and removes unnecessary function parameters and option wrapping
Fixes #

clean feature: require_custodian_for_locked_stake_authorize

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/owners.rs

The current OwnerOffset is defined as usize, which actual size could be u32 or u64.
On the other hand, the OwnerOffset is used to access the ith owner in one
TieredStorageFile.  As a result, u32 is more than enough to represent the number of
owners inside one TieredStorageFile while u16 might not be always enough.
This PR defines OwnerOffset as u32.
Existing test cases.

[TieredStorage] Define OwnerOffset as u32

---

runtime-transaction/src/runtime_transaction.rs
runtime-transaction/src/transaction_meta.rs

Following up on some minor thoughts I had from #33471.
- Remove simple comments which repeat field names
- TransactionMeta setters become `pub(crate)`
- Module level comment using //! instead of ///
The change of visibility on the TransactionMeta setters helps us, because if we forget to set a field in either `try_from` of the `Static` or `Dynamic` `RuntimeTransaction` the compiler will mark these as unused/dead code and warn us the field isn't ever being set.
Fixes #

RuntimeTransaction: Minor Cleanup

---

accounts-db/src/tiered_storage/footer.rs
accounts-db/src/tiered_storage/index.rs
accounts-db/src/tiered_storage/mmap_utils.rs

Mmap variables are used inside tiered storage in many places. Sometimes they are called `mmap` and sometimes they are called `map`. Since `map` already has a common, *different* meaning, we should (1) be consistent, and (2) prefer `mmap`. 
Renames `map` to `mmap`.

Uses `mmap` for names in tiered storage

---

programs/zk-token-proof/src/lib.rs
sdk/src/feature_set.rs

The confidential transfer with fee part of the token-2022 is targeting 1.18.
Add feature gate for processing zk token proof instructions related to transfer with fee.
Fixes #

[zk-token-proof] Feature gate transfer with fee related proofs

---

runtime/src/bank/tests.rs

The `verify_tx_signatures_len` feature is always active now but there's still a test that tries to disable it for no reason
Stop disabling `verify_tx_signatures_len` feature in tests
Fixes #

test cleanup: remove reference to verify_tx_signatures_len feature

---

runtime/src/bank/tests.rs

Noticed some weird usage of `.err()` to compare against `Some(ErrorKind)` in some of the tests while reviewing #34078
Just compare agains `Err(ErrorKind)`
Fixes #

Clean up: simplify asserts

---

ci/buildkite-pipeline.sh
ci/buildkite-solana-private.sh

a following PR for https://github.com/solana-labs/solana/pull/33815
run test-stable-sbf in docker

ci: run test-stable-sbf in docker

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

A feature activation on devnet diverged because it was activated before the epoch boundary on part of the cluster (version dependent). This happened because of the backport #34003 which depends on `Bank::compute_active_feature_set()` being without side effects (as the name suggests). 
Move the actual activation of pending features from `Bank::compute_active_feature_set()` into `Bank::apply_feature_activations()`.

Fix - `Bank::compute_active_feature_set()` and `Bank::apply_feature_activations()`

---

programs/stake/src/stake_state.rs

While going through the stake program code, I noticed that `stake_merge_with_unmatched_credits_observed` is still in there, when it's been enabled for over two years. And then I confirmed that it was mine in https://github.com/solana-labs/solana/pull/18985
Remove the feature gate, and update a test that was an old function. The removed test case is no longer valid since we relaxed the `credits_observed` equality requirement.
Fixes #

stake: Remove feature `stake_merge_with_unmatched_credits_observed`

---

ledger/src/blockstore_db.rs

The function matches the access type and calls a different RocksDB function depending on whether we have primary or secondary access. But, lots of the code is the same for these two paths so de-duplicate the repeated sections.

Consolidate repeated code in Rocks::open()

---

programs/stake/src/stake_instruction.rs
programs/vote/src/vote_processor.rs

`vote_stake_checked_instructions` feature is active on all clusters and should be cleaned up

clean feature: vote_stake_checked_instructions

---

gossip/src/cluster_info.rs
gossip/src/duplicate_shred.rs

With the addition of merkle shreds, there is a new class of duplicate proofs available to be gossiped.
Add a check for merkle root conflict proofs:
- Same fec set 
- Different merkle root OR mixture of legacy and merkle shreds
Additionally this means we can now have a duplicate proof with 1 data shred and 1 coding shred,
so the `shred_type` field on duplicate proofs is unnecessary. 
Split from #33889 

gossip: process duplicate proofs for merkle root conflicts 

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/meta.rs
accounts-db/src/tiered_storage/owners.rs

TieredAccountMeta currently uses `u32` for owner_offset, while
we already have a dedicate type for that --- OwnerOffset.
This PR makes TieredAccountMeta use OwnerOffset for its
owner_offset field.
Existing unit-tests.

[TieredStorage] Use OwnerOffset type in TieredAccountMeta

---

.mergify.yml

Core contributors are not all aligned and informed on what is acceptable to backport to stable and beta branches
Add a mergify action that will add a comment whenever a PR is labeled a `v1.16` or `v1.17` label. This extra comment will remind contributors and reviewers what the guidelines for backports are.
Fixes #

CI: automatically add a warning comment to PRs with backport labels

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/transaction_state_container.rs

- Currently no metrics for number of packets being received and scheduled by the scheduler
- Currently no metrics for amount of time spent in each code section in the scheduler
- Add metrics for number of packets received, dropped in different ways, scheduled etc
- Add metrics for amount of time spent in major code sections: decision-making, scheduling, receiving, buffering
- All metrics reports on a 1s interval
Fixes #

TransactionScheduler: Scheduler Count and Timing metrics

---

accounts-db/src/tiered_storage/footer.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

In TieredStorage, we want to make AccountOffset and IndexOffset u32 instead
of usize just like OwnerOffset.  However, we need to first change what we persist
in the storage.  Currently, IndexBlock persists offsets as u64 instead of u32. 
This PR makes IndexBlock persist u32 offsets.
Existing test cases.

[TieredStorage] Make IndexBlock persist u32 offsets

---

core/src/system_monitor_service.rs

apparently quic uses cmsgs. `net.core.optmem_max` being specified with a value of `0` still prints a suggestion message, implying that the operator should tune it to zero.  this disables cmsg support, breaks quic, prevents user tx receipt and results in leaders building vote-only blocks
* add explicit "query-only" knob specification
* don't print recommendations for query-only knobs

system monitory: don't suggest query-only limits

---

core/src/system_monitor_service.rs

Validators fail on startup.
fix logic on linux_report_network_limits
Fixes #

reverse logic on linux_report_network_limits

---

accounts-db/src/accounts_db.rs

Some ancient append vec code triggered the old code in append vecs that previously allowed multiple append vecs per slot. This code will shortly result in an assert. It would be nice to remove this code path at some point.
In the meantime, it would help with diagnosing what caused the situation if we logged some information about what was going on.
Add some logging when appending accounts exhausts all space in an append vec.
Fixes #

log when appending exceeds available space

---

ledger-tool/src/main.rs
ledger/src/blockstore_db.rs

This helper simply called std::mem::size_of<Self::Index>(). However, all of the underlying functions that create keys manually copy fields into a byte array. The fields are copied in end-to-end whereas size_of() might include alignment bytes.
That is, a (u64, u32) only has 12 bytes of "data", but it would have size 16 due to the 4 alignment padding bytes that would be added to get the u32 (size 4) aligned with the u64 (size 8).
The helper could be useful, but in its' current state, it is incorrect and dangerous to leave around in that someone might make the incorrect assumption above in regards to alignment bytes.
Also, here is a Rust playground link to demonstrate that `std::mem::size_of::<(u64, u32)>() == 16`:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b1848a …

Remove key_size() method from Column trait

---

programs/bpf_loader/src/syscalls/cpi.rs
programs/sbf/rust/invoke/src/processor.rs

If the vector holding an account is reallocated during execution of a callee, we must zero the spare capacity regardless of whether the account size changed, because the underlying vector might contain uninitialized memory in the spare capacity.

cpi: direct_mapping: always zero spare capacity if account alloc changes

---

accounts-db/src/accounts.rs
runtime/src/accounts/mod.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

`enum RewardInterval` is only used in runtime, but it is declared in `accounts-db`.
I moved the enum to `runtime/src/bank.rs`, closer to its usage.

Move `RewardInterval` to runtime

---

program-runtime/src/timings.rs

`ExecuteTimingType::TotalBatchesLen` is accumulated twice, once explicitly and once implicitly inside `self.execute_timings.accumulate(&other.execute_timings);`.
Removes the explicit accumulation.

Fix - Removes redundant `TotalBatchesLen` from `ThreadExecuteTimings::accumulate()`

---

core/src/banking_stage.rs
core/src/banking_stage/consume_worker.rs
core/src/banking_stage/consumer.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

- ConsumeWorker threads to not report any detailed transaction processing metrics
- Add detailed metrics to be collected by consume worker threads
- Because worker threads are lazy i.e. they sleep unless there's work to do; the scheduler controller will report worker metrics
Fixes #

TransactionScheduler: detailed consume worker metrics

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

IndexOffset currently uses `usize`, which size is platform dependent.
We want a fixed size type that is consist to what we persist in the tiered-storage file.
This PR makes IndexOffset use u32.

[TieredStorage] Make IndexOffset use u32

---

zk-token-sdk/src/errors.rs
zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u128.rs
zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u256.rs
zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u64.rs

https://github.com/solana-labs/solana/issues/33525
When verifying range proof, I added a condition to check that the number of commitments are capped at `MAX_COMMITMENTS`.
This is a split PR from https://github.com/solana-labs/solana/pull/34065.
Fixes #

[zk-token-sdk] Add a length check on range proof commitment length

---

zk-token-sdk/src/range_proof/errors.rs
zk-token-sdk/src/range_proof/generators.rs
zk-token-sdk/src/range_proof/inner_product.rs
zk-token-sdk/src/range_proof/mod.rs

When the input to the range proof generator become very large, then this could lead to expected behavior (https://github.com/solana-labs/solana/issues/33509).
Added a cap of `2^32`, which should be plenty for all practical use cases.
Fixes #

[zk-token-sdk] Restrict range proof generator length and prevent 0-bit range proof

---

core/src/consensus/heaviest_subtree_fork_choice.rs
core/src/replay_stage.rs
local-cluster/tests/local_cluster.rs

Add tree height metric
Use tree height metric in fork choice 
Fixes #

Add deepest slot metric

---

accounts-db/src/accounts_db.rs
accounts-db/src/ancient_append_vecs.rs

AccountsToStore, once created, its member "slot" should not be changed. However,
because pub member slot, it could be changed when holding a mut&. 
Refactor pub member slot from AccountsToStore into a readonly fn.
Refactor pub member slot from AccountsToStore into a readonly fn.
Fixes #

refactor AccountsToStore

---

accounts-db/src/accounts_db.rs
accounts-db/src/append_vec.rs

ancient append vec appending relies on a reliable count of remaining bytes. It turns out that the append vec's `len()` is up to the last written byte. This can be non-u64 aligned. The result is if we are to append more to the file, the first operation will be a `u64_align!`. This means that `remaining_bytes` was reporting too many bytes. Not all those bytes could be written to, thanks to the bytes wasted for alignment. The result was that writes could fail, causing an attempt at creating a second append vec for the slot. This is no longer allowed and will fail with an assert.
Align `len()` so that remaining bytes returns an accurate number.
Fixes #

remaining_bytes aligns len since all writes will align first

---

runtime/src/bank.rs
sdk/src/account.rs

Part of effort for https://github.com/solana-labs/solana/issues/33970
We are going to deprecate executable flags on account. Instead of relying on
executable flag on account to determine whether the account is execuable, we
are going to check the owner of the account is a variant of bpf-loader.
This change moves `PROGRAM_OWNERS` from runtime to sdk, so that it can be
shared for the upcoming work.
Move PROGRAM_OWNERS list to sdk
Fixes #

move PROGRAM_OWNERS to sdk

---

accounts-db/src/accounts_db.rs
accounts-db/src/accounts_file.rs
accounts-db/src/append_vec.rs

MatchAccountOwnerError currently belongs to append_vec.
However, it is a public error type that is also required by other AccountsFile
implementations such as TieredStorageFile.
Move MatchAccountOwnerError from append_vec to accounts_file.

Move MatchAccountOwnerError from append_vec to accounts_file

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

AccountOffset currently uses `usize`, which size is platform dependent.
We want a fixed size type that is consist to what we persist in the tiered-storage file.
This PR makes AccountOffset use u32.

[TieredStorage] Make AccountOffset use u32

---

zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u128.rs
zk-token-sdk/src/range_proof/errors.rs
zk-token-sdk/src/range_proof/inner_product.rs
zk-token-sdk/src/range_proof/mod.rs
zk-token-sdk/src/range_proof/util.rs

https://github.com/solana-labs/solana/issues/33507, https://github.com/solana-labs/solana/issues/33509, https://github.com/solana-labs/solana/issues/33510, and https://github.com/solana-labs/solana/issues/33525.
- [96020b3](https://github.com/solana-labs/solana/pull/34065/commits/96020b394505a72969f2a37a3f02914e1d9ab418): Previously, mismatch on vector lengths used in range proof was addressed by assert statements. This commit replaces them with `RangeProofGenerationError::VectorLengthMismatch`.
- [782b617](https://github.com/solana-labs/solana/pull/34065/commits/782b6173c4c3c0d7809d2f1decb92f94bdc40660): Range proof on 0-bit numbers does not really make sense, but we did not specifically take care of this case. This commit takes care of this special case. 
- …

[zk-token-sdk] Add range proof generation error types

---

cost-model/src/cost_tracker.rs

`CostTracker::would_fit` incorrectly not checking votes against block limits.
Introduced in #33230
Remove the `else` so we check against block limits regardless of `is_simple_vote`.
Fixes #

check vote costs against block limits in would_fit

---

runtime/src/bank.rs
runtime/src/bank/fee_distribution.rs

`no_overflow_rent_distribution` (https://github.com/solana-labs/solana/pull/12112) is activated on all clusters and should be cleaned up. I noticed it when doing some other fee related changes.

clean feature: no_overflow_rent_distribution

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/bank_forks.rs

In order for us to implement #34169 (remove `WorkSlot` from `LoadedPrograms::extract`), we need to make sure all tests create a `BankFork` and use a `Bank` instance that has been added to the fork.
This PR adds a few auxiliary functions to deal with `BankForks` and fixes some tests. Another PR that fixes more tests is waiting for this one to be merged.

Use `BankForks` on tests - Part 1

---

geyser-plugin-manager/src/geyser_plugin_manager.rs

Added a comment about order of dropping plugin and library
Fixes #

Added a comment about order of dropping plugin and library

---

Cargo.lock
programs/bpf_loader/Cargo.toml
programs/bpf_loader/src/syscalls/mem_ops.rs

iter_memory_pair_chunks was iterating regions in reverse, but not memory _within_ regions in reverse, which broke some overlapping memmoves.
This commit fixes the issue and simplifies the implementation by removing nested loops which made control flow hard to reason about.
I've added (a lot of) tests that compare libc's memmove against our memmove.

direct_mapping: fix iter_memory_pair_chunks in reverse mode

---

CHANGELOG.md

I did not update the CHANGELOG in #33890, which enabled this option, because I was waiting to merge a few metrics PRs first.
Those have been merged, so updating the change log now.
Add changelog line which lists new `--block-production-method central-scheduler` option
Fixes #

Update CHANGELOG for new scheduler support

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

Knowing if there are a lot of unschedulable transactions is useful
Add a metric
Fixes #

Add metric for number of unschedulable transactions

---

Cargo.lock
Cargo.toml
core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
programs/sbf/Cargo.lock

Following up on https://github.com/solana-labs/solana/issues/34221#issuecomment-1828269609.
prio-graph 0.2.0 supports conflicting transactions so if the checks added in #34229 fail, it will not crash like it did previously.
- Update Cargo.toml prio-graph to 0.2.0
- Return value of `PrioGraph::pop_and_unblock` changed, update the call-site in `PrioGraphScheduler::schedule`
- immediately drop blocked ids returned, only use the popped id
Fixes #

Bump prio-graph to 0.2.0

---

runtime/src/bank.rs

- `check_transactions` takes in a slice of **owned** `SanitizedTransaction`
- Scheduler container doesn't give up ownership until a transaction is scheduled, so we cannot pre-filter using this function as is
- Make `check_transactions` take a slice of generic `core::borrow::Borrow<SanitizedTransaction>` so we can pass `&[SanitizedTransaction]` or `&[&SanitizedTransaction]` (or really any wrapped type like `Arc<SanitizedTransaction>` for example).
- Note, this is generic and the implementation of `borrow` for `SanitizedTransaction` is a no-op.
Fixes #

Refactor: check_transactions - allow borrowed transactions

---

accounts-db/src/account_storage.rs

Several recent reports of hitting these asserts while testing. It would be useful to know what slot. This helps us know where the slot is relative to the last clean, newest root, etc.
Add `slot` to assert message.
Fixes #

add slot to assert message

---

storage-bigtable/src/lib.rs

The length of tx_cells is known at the start, so we can size the Vec appropriately off the bat to avoid the reallocations.
`vec![] ==> Vec::with_capacity()`

Use Vec::with_capacity() to avoid reallocations with repeated push()'s

---

ledger/src/bigtable_upload.rs
storage-bigtable/init-bigtable.sh
storage-bigtable/src/lib.rs
storage-proto/build.rs
storage-proto/proto/entries.proto
storage-proto/src/convert.rs

Blocks stored on bigtable are flattened, so they don't include the entry data that would allow block hashes to be verified.
Other historical ledger archives (like foundation storage buckets and [Old Faithful](https://github.com/rpcpool/yellowstone-faithful)) do include entry data, but it would provide additional redundancy if the bigtable store were made complete.
Add entries table to default bigtable setup
Upload entry summary data in `bigtable_upload` (used by both `solana-ledger-tool bigtable upload` and the BigtableUploadService). Entry-summary data is the entry data minus the actual transactions, plus a little extra indexing data to make it easy to regenerate entries from the flattened list of transactions. (This parallels geyser Entry notifications.)
✅ ~~Needs rebase on …

storage-bigtable: Upload entries

---

programs/bpf_loader/src/syscalls/mod.rs

Gaps don't work with direct mapping which assumes a 1:1 mapping between virtual and host addresses.

direct_mapping: disable stack frame gaps

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

- There's a lot of already processed or old transactions that make it into the buffer
- They aren't cleaned away before scheduling
- Remove these transactions out of the buffer before leader slot comes
Blocked by #34232
Fixes #

TransactionScheduler: Clean already processed or old transactions from container

---

core/src/system_monitor_service.rs

https://github.com/solana-labs/solana/pull/34149 added some `target_os = "linux"` handling, but the accompanying enum is not tagged, leading to clippy complaints on other OSes, like mac:
```
warning: variants `Recommend` and `QueryOnly` are never constructed
--> core/src/system_monitor_service.rs:397:5
|
396 | enum InterestingLimit {
|      ---------------- variants in this enum
397 |     Recommend(i64),
|     ^^^^^^^^^
398 |     QueryOnly,
|     ^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `solana-core` (lib) generated 1 warning
```
Tag the enum

Tag InterestingLimit enum with target_os

---

storage-bigtable/src/lib.rs

https://github.com/solana-labs/solana/pull/34099 added entry-upload to bigtable upload functionality, but did not hook up delete functionality
Extend `delete_confirmed_block()` to delete entry rows if they exist
If the entries table doesn't exist yet, or if the slot in question doesn't have an entry row, output says:
```
[2023-11-28T23:04:35.713140000Z INFO  solana_storage_bigtable] deleted ledger data for slot XX: N transaction rows, M address slot rows, WITHOUT entry row
```
This is so delete will still work elegantly on old slots and on bigtables not yet updated for entries.
Otherwise, output says this:
```
[2023-11-28T23:09:03.172500000Z INFO  solana_storage_bigtable] deleted ledger data for slot XX: N transaction rows, M address slot rows, with entry row
```

storage-bigtable: delete entry rows if they exist when deleting confirmed block

---

core/src/system_monitor_service.rs

I broke the mac build because it turns out macos does have interesting limits, kind of. Imho, clippy should therefore be able to tell that the variants of the enum get used. But it doesn't.
Fix max build by allowing dead_code on InterestingLimit when os is not linux

Fix mac build

---

ledger/src/blockstore.rs
ledger/src/shred.rs

We don't yet write to this column.
When inserting the first shred for each fec set, populate the merkle root metas
Note: we must only create the merkle root meta if the shred was successfully inserted, otherwise there will be a desync on `first_received_shred_index` and what's actually available in blockstore. 
Split from #33889 

blockstore: populate merkle root metas column

---

local-cluster/tests/local_cluster.rs

`test_duplicate_shreds_switch_failure` is flaky - see #34212 
`#[ignore]` it for now, while I put together a proper fix

local-cluster: ignore test_duplicate_shreds_switch_failure

---

geyser-plugin-interface/src/geyser_plugin_interface.rs
geyser-plugin-manager/src/geyser_plugin_manager.rs

The plugins need to be able to log as the rest of the validator in the validator logs.  The plugin could use solana_logger::setup_with_defaul, unfortunately it is found doing that will cause the plugin not be unloaded from memory when the Library was dropped.
The change creates a new interface in the GeyserPlugin interface to allow the runtime to pass the logging configuration to the plugin.
`    fn setup_logger(&self, logger: &'static dyn log::Log, level: log::LevelFilter) -> Result<()>;
`
Which the plugin can choose to set it up:
```
fn setup_logger(&self, logger: &'static dyn log::Log, level: log::LevelFilter) -> Result<()> {
log::set_max_level(level);
if let Err(err) = log::set_logger(logger) {
return Err(GeyserPluginError::Custom(Box::new(err)));
}
Ok(())
}
```
Fixes #

Support logging in geyser plugins

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

metrics should be clear on unit
add trailing _us to timing metrics
Fixes #

Trailing _us for scheduler time metrics

---

core/src/replay_stage.rs
ledger-tool/src/main.rs
runtime/src/bank/bank_hash_details.rs

Currently, the file is generated when a node drops a block that was
produced by another node. However, it would also be beneficial to see
the account state when a node drops its' own block.
Output the file in this additional failure codepath
Note that the debug file gets generated when we are not the leader via `ReplayStage::purge_unconfirmed_duplicate_slot()`:
https://github.com/solana-labs/solana/blob/e425c1acaadf6ac22aec3afa09750616443349f1/core/src/replay_stage.rs#L1510

Output BankHashDetails file when leader drops its' own block

---

Cargo.lock
runtime-transaction/Cargo.toml
runtime-transaction/src/runtime_transaction.rs

Setup basic test infra before adding functions
- add basic test
Fixes #

Add test module to runtime-transaction

---

.github/scripts/cargo-clippy-before-script.sh
.github/workflows/cargo.yml

we may accidentally merge some code that can break the macOS/Windows build
run clippy for macos.
(I would like to have Windows as well but it takes me too much time to fix 😢 so let's ship macos first)

ci: add macos clippy test

---

Cargo.toml
programs/sbf/Cargo.toml

I spotted a couple typos in the comments about patches in Cargo.toml
Fix typos and smooth language a little.
I also wrapped the lines to 80 characters, including in programs/bpf/Cargo.toml

Fix patch comment typos and wrap lines

---

core/src/validator.rs
ledger-tool/src/ledger_utils.rs
ledger/src/bank_forks_utils.rs
ledger/src/blockstore_processor.rs

There are operations in bank_fork_utils that may fail; we explicitly call std::process::exit() on several of these. Granted we may end up exiting the process higher up the callstack, bubbling the errors up allow a caller that could handle the error to do so.
Make several functions return a `Result<...>` instead of exiting, and properly handle the result up the callstack

Bubble up errors in bank_fork_utils instead of exiting process

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

#34233 will filter transactions out before we become leader, but we still may receive filterable transactions during or very close to our leader slot.
We should be filtering these out before prio-graph insertion, so they do not block other transactions.
- Add a generic filter to `PrioGraph::schedule`
- Call `Bank::check_transactions` inside filter
- Add filter count and time metrics
- For efficiency in filter, do batched pops from the container to prio-graph
Fixes #

TransactionScheduler: Schedule Filter

---

ledger/src/blockstore.rs
ledger/src/shred.rs

`fec_set_index` is `u32` but in some places we use `u64` which makes the code confusing.
Unify the type of `store_key` in `ErasureSetId` to `u32` and perform the type conversion at the call site.

blockstore: use u32 for fec_set_index in erasure set index store key

---

ledger-tool/src/bigtable.rs
ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/program.rs

This PR spun out from https://github.com/solana-labs/solana/pull/34274 per some conversation to consider running the `rustfmt` on a subset to see if it makes things more manageable.
Long string literals can cause rustfmt to fail, which results in rustfmt failing to format entire functions. There are several instances of this in ledger-tool, so format these files with wrapped strings so that formatting will apply to functions again.
Note that this PR was created by adding format_strings = true to rustfmt.toml; however, this change does NOT persist that rule as the rule would format the entire repo.
While reviewing the diff, I do see some lines that were wrapped that could be candidates for inlining the values in format strings:
https://github.com/solana-labs/solana/blob/4832b4ecec57f9e87a64 …

ledger-tool: Run rustfmt with format_strings = true

---

cli/src/address_lookup_table.rs
cli/src/clap_app.rs
cli/src/cluster_query.rs
cli/src/feature.rs
cli/src/main.rs
cli/src/nonce.rs
cli/src/program.rs
cli/src/program_v4.rs
cli/src/stake.rs
cli/src/validator_info.rs
cli/src/vote.rs
cli/src/wallet.rs

This PR is spun out from https://github.com/solana-labs/solana/pull/34274
Long string literals can cause rustfmt to fail, which results in rustfmt failing to format entire functions. There are many instances of this in the solana-cli.
Format and wrap strings to allow rustfmt to work again.
This PR was initiated by adding `format_strings = true` to the workspace rustfmt.toml. In general, this did a nice job.
However, I chose to manually preserve or improve some of the original strings where the formatting seemed to break readability. (It is just my own personal preference that `[default: ..]` blocks not be broken across multiple lines.)
If we impose `format_strings` on the workspace in the future, these strings will be "wrong" and need fixing.

solana-cli: format strings

---

accounts-db/src/accounts_db.rs
core/src/repair/ancestor_hashes_service.rs
core/src/repair/repair_weight.rs
core/src/tvu.rs
genesis/src/main.rs
genesis/src/stakes.rs
ledger/src/blockstore_processor.rs
ledger/src/leader_schedule_cache.rs
programs/bpf_loader/src/syscalls/mod.rs
programs/vote/src/vote_state/mod.rs
rpc/src/rpc.rs
runtime/src/bank.rs
runtime/src/bank/fee_distribution.rs
runtime/src/snapshot_package.rs
sdk/macro/src/lib.rs
sdk/program/src/epoch_schedule.rs
sdk/program/src/rent.rs
test-validator/src/lib.rs

In #32547, I added a clippy allow lint for `CloneZeroed` types that were `Copy` to have an "incorrect" clone. For any `Copy` types, clippy considers a `clone` that is anything other than `Copy` to be incorrect.
`EpochSchedule` and `Rent` turned out to be the only `Copy` types using this derive macro.
- EpochSchedule no longer derives `Copy`
- Rent no longer derives `Copy`
- Replace use of `Copy` by `Clone` (this will ensure padding bytes are zero consistently)
- Use references where appropriate	
Fixes #32588

Do not derive Copy for EpochSchedule and Rent

---

core/src/replay_stage.rs

The pre-existing message doesn't provide context about the caller as BankForks is accessed by lots of places in ReplayStage.
Add context to the existing log message

Add additional context to ReplayStage log message

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

Some transactions we receive may be too old or already processed, but they still make it into the buffer temporarily.
- Filter these transactions out before inserting to buffer
Fixes #

TransactionScheduler: check transaction age and already processed during receive

---

cli/tests/program.rs

Suboptimal coverage (in unit-tests) for changing program buffer authority.
This is a spin-off from https://github.com/solana-labs/solana/pull/33860 (see https://github.com/solana-labs/solana/pull/33860) to expand test coverage by checking that old authority no longer has control over buffer once buffer authority has been changed.

cli: (program) enhance test_cli_program_set_buffer_authority

---

accounts-db/src/partitioned_rewards.rs
runtime/src/bank/metrics.rs

There are unnecessary `#[allow(dead_code)]`s in the partitioned rewards code.
Remove them.

Removes unnecessary #[allow(dead_code)] in partitioned rewards

---

core/src/repair/quic_endpoint.rs

`receiver.recv()` can unnecessarily block when the connection is already closed.
Exit `send_requests_task` if the connection is closed.

exits send_requests_task if the connection is closed

---

sdk/program/src/stake/stake_flags.rs

There are unnecessary `#[allow(dead_code)]`s in the stake flags code.
Remove them.

Removes unnecessary #[allow(dead_code)] in stake flags

---

bucket_map/src/bucket.rs
bucket_map/src/bucket_api.rs
bucket_map/src/bucket_storage.rs

There are unnecessary `#[allow(dead_code)]`s in the bucket map code.
Remove them.

Removes unnecessary #[allow(dead_code)] in bucket map

---

.mergify.yml

I forgot to add `clippy (macos-latest)` to our mergify auto-merge check:
https://discord.com/channels/428295358100013066/560503042458517505/1181629892803178586
add it!

ci: block automerge until clippy (macos-latest) green

---

turbine/src/quic_endpoint.rs

Waiting on `receiver.recv()` can unnecessarily block while the connection is already closed.
Exit `send_datagram_task` if the connection is closed

exits send_datagram_task if the connection is closed

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/meta.rs

There are unnecessary `#[allow(dead_code)]`s in the tiered storage module.
Remove them.

Removes unnecessary #[allow(dead_code)] in tiered storage

---

core/src/shred_fetch_stage.rs

Orders are wrong and assigned wrong values.
Fixed ordering.

patches slots_per_epoch vs last_slot ordering in shred_fetch_stage

---

program-runtime/src/invoke_context.rs
program-runtime/src/loaded_programs.rs

The program runtime crate was reviewed, this PR addresses the informational points.

Cleanup - program runtime

---

zk-token-sdk/src/instruction/transfer/with_fee.rs

In the way the transfer with fee proof is currently calculated, it is possible for transfer fee to be greater than the transfer amount. This stems from some edge cases that were missed in the way range proof is used.
1. We call the difference of `transfer_fee * 10_000 - transfer_amount * fee_basis_point` the `delta_fee`. If the fee is calculated correctly, then the `delta_fee` must be in the range `0 <= delta_fee < 10_000`. We use range proof to check this. However, since range proof only works for ranges of power-of-two, we require the prover to generate two range proofs: (i) `0 <= delta_fee < 16_384` (16384 = 2^14) and (ii) `0 <= 10_000 - delta_fee < 16_384`. However, if `delta_fee = 10_000`, then both conditions (i) and (ii) are satisfied. What we really want for condition (ii) is `0 …

[zk-token-sdk] Fix transfer with fee edge case error

---

.mergify.yml

get macos clippy auto-merge check follow the triggering rules!
https://github.com/solana-labs/solana/blob/fa251768b301f13535dec9ce663ec663bc746271/.github/workflows/cargo.yml#L12-L17

ci: get macos clippy auto-merge check follow the triggering rules

---

.github/workflows/downstream-project-anchor.yml
scripts/build-downstream-anchor-projects.sh
scripts/patch-crates.sh

Although our downstream coverage for SPL is great, we still run the risk of breaking Anchor because we don't have a downstream test for it.
We used to have one, so bring back the old downstream job as a GitHub Action!
Fixes #

ci: Add downstream build for anchor

---

programs/address-lookup-table/src/lib.rs

`solana-address-lookup-table-program` crate causes compile errors in programs after https://github.com/solana-labs/solana/pull/33165
Problem explained in more detail in #34352
- Add `#[cfg(target_os = "solana")]` checks to decide which SDK crate to use
- Make `processor` module only available in non-program environments
Fixes #34352

Fix `solana-address-lookup-table-program` compilation

---

runtime-transaction/src/runtime_transaction.rs
runtime-transaction/src/transaction_meta.rs

Generalize message type for RuntimeTransaction types could decouple sdk, also better reflect the nature relationship between Transaction and Message.
- generalize RuntimeTransaction type
Fixes #

generalize message type for runtime-transaction

---

cli/src/program.rs
cli/tests/program.rs
transaction-dos/src/main.rs

`solana program deploy` and `solana program write-buffer` could use a `--fee-payer` argument.
This adds `--fee-payer` to `solana program deploy` and `solana program write-buffer` cli commands. It's effectively a spin-off from https://github.com/solana-labs/solana/pull/33860.

cli: (program/buffer deploy) introduce --fee-payer argument

---

sdk/program/src/message/legacy.rs
sdk/program/src/sysvar/mod.rs

Sysvar and builtin key lists shouldn't be exposed in the public API
- Add comment saying that the lists will be deprecated and shouldn't be modified
- Remove recently added sysvar keys from the sysvar list
- Remove overly restrictive sysvar list inclusion test
Fixes #

Comment sysvar and builtin lists as deprecated and remove new keys

---

tokens/src/arg_parser.rs

`solana-tokens` versions v1.16 and v1.17 aren't respecting the `--url` arg passed with a command. This is because [this change](https://github.com/solana-labs/solana/pull/29693) updated the name of the url clap arg (to be consistent with `solana-cli` and other tools), but neglected to also update the matches parser.
Update arg name in matches parser
cc @tigarcia

tokens: fix url clap arg name

---

scripts/build-downstream-anchor-projects.sh

According to the Anchor team, we should also make sure that `anchor-spl` works during our downstream checks.
Add a step to test anchor-spl with all features enabled.
@acheroncrypto I can't add you as a reviewer, but can you double-check that this is correct?
Note: This is blocked by https://github.com/coral-xyz/anchor/pull/2722, so keeping it in draft
Fixes #

ci: Test anchor-spl during downstream build

---

pubsub-client/src/nonblocking/pubsub_client.rs
pubsub-client/src/pubsub_client.rs

The docs in the `PubsubClient` dont have the the latest link to the socket events. So the links to the events they refer to are updated. 
For eg: 
The latest link referring to `account_subscribe` events is
https://docs.solana.com/api/websocket#accountsubscribe
But the link in the docs still refer to the old one.
https://docs.solana.com/developing/clients/jsonrpc-api#accountsubscribe
This PR tries to update those links.
- Updated all the links in the docs to the respective socket events they correspond to.

update pubsub docs link

---

core/src/banking_stage/committer.rs
core/src/banking_stage/consume_worker.rs
core/src/banking_stage/consumer.rs
core/src/banking_stage/leader_slot_timing_metrics.rs

Lack of metrics for blockhash queue locking
Add said metrics
Fixes #

Add metrics for locking the blockhash queue in banking stage

---

docs/src/cli/deploy-a-program.md

`solana program write-buffer` could use some clarifications regarding what **authority** types it expects/supports.
This PR is a spinoff from https://github.com/solana-labs/solana/pull/33860 (see https://github.com/solana-labs/solana/pull/33860#discussion_r1412477126 for details). It extends `solana program write-buffer` docs to elaborate on some buffer **authority** specifics. Rendered version: https://github.com/norwnd/solana/blob/docs-write-buffer-clarifications/docs/src/cli/deploy-a-program.md#using-an-intermediary-buffer-account

docs: write-buffer clarifications

---

core/benches/banking_stage.rs
core/benches/consumer.rs
program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

We need to remove `WorkingSlot`, as described in https://github.com/solana-labs/solana/issues/34169, so that cooperative program loading becomes more straightforward.
I have removed the trait `WorkingSlot` and all its references.
Fixes #34169

Remove WorkingSlot

---

docs/publish-docs.sh

The `publish-docs.sh` has a typo in the generated `vercel.json` resulting in the build and publishing of docs to fail.
Removed the erroneous extra `path` param from the publish script

[docs] fix: invalid path param

---

accounts-db/src/ancient_append_vecs.rs

There is a trade-off for selecting the ancient append vec size. Too small size will result in
too many ancient append vec memory mapped files. Too big size will make it difficult to clean and shrink.
Here, we choose 128M bytes for the ancient append vec size.
set ancient append vec size to 128M
Fixes #

tune ancient append vec size to 128M

---

accounts-db/src/tiered_storage/error.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

Hot and cold accounts storage have different implementations of
their offsets.  As a result, a single struct AccountOffset isn't suitable
to describe the offsets used by hot and cold accounts storage.
This PR makes AccountOffset a trait.  On top of that, introduces
HotAccountOffset that implements AccountOffset.
Updated existing unit-tests.

[TieredStorage] Make AccountOffset a trait, introduce HotAccountOffset

---

core/src/consensus.rs
core/src/replay_stage.rs
sdk/src/feature_set.rs

We see several cases where cluster gets partitioned in such a way that some set of validators end up voting down the minority fork and hit deep lockouts (up to 8). This can stall OC for over a minute in the worst cases. See #34107 for one example.
It would be good to resolve all the reasons why validators can vote down the minority fork (deterministic fork selection, fixing reasons why leader's broadcast gets delayed, etc.) but it could take some time to resolve all of these. Treating the symptom by reducing how far down the minority fork validators will vote can mitigate lockout period significantly.
When checking vote stake threshold as part of voting criteria, check for both of the following criteria:
1. 8th deep tower vote is at OC (66%) <-- this is existing check
2. 4th deep tower …

add additional vote lockout stake threshold

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

The current naming and the code comments for HOT_ACCOUNT_OFFSET_ALIGNMENT
aren't really reflecting its role as pointed out in #34335.
This PR renames HOT_ACCOUNT_OFFSET_ALIGNMENT to HOT_ACCOUNT_ALIGNMENT
as it's the hot account instead of hot account offset needs to be aligned.
In addition, improve the comment block for HOT_ACCOUNT_ALIGNMENT.

[TieredStorage]  Improve comments for HOT_ACCOUNT_ALIGNMENT

---

cli/src/cluster_query.rs
cli/src/inflation.rs
cli/src/lib.rs
cli/src/nonce.rs
cli/src/program.rs
cli/src/program_v4.rs
cli/src/stake.rs
cli/src/vote.rs
cli/src/wallet.rs

In https://github.com/solana-labs/solana/pull/34288, we discovered there are a bunch of uses of the `solana_cli::pubkey` macro that add unnecessary punctuation, which ends up goofy. Eg:
```
$ solana inflation rewards -h
...
ARGS:
<ADDRESS>...    Address of account to query for rewards. , one of:
* a base58-encoded public key
* a path to a keypair file
* a hyphen; signals a JSON-encoded keypair on stdin
* the 'ASK' keyword; to recover a keypair via its seed phrase
* a hardware wallet keypair URL (i.e. usb://ledger)
```
~~Remove periods and spaces. In a couple cases, we include extra information about the address -- I made these into parentheticals, so the punctuation still works. Open to other suggestions, though, as I don't love how it demotes the information.~~
Update macro to be a …

Fix pubkey-macro args

---

SECURITY.md
ci/README.md
docs/src/validator/gossip.md
docs/src/validator/runtime.md
geyser-plugin-interface/README.md
metrics/README.md
net/README.md

I've gone through some of the documentation and noticed a few spots where a little polishing could really enhance the reader's experience. With that in mind, I've made a handful of edits that I think will make a difference. Here's a quick rundown:
1. *Get Started Overview (commit 78bf40b98be8):* I tweaked the introduction a bit for smoother reading and fixed a small typo.
2. *Validator Runtime (commit cdd507066ac3):* Spotted a few grammatical hiccups and clarified some points around transaction execution.
3. *Validator Gossip (commit d2f1dbd094ca):* Ironed out some grammatical wrinkles to make things clearer.
4. *Transaction Fees (commit 6428e96c155f):* Updated a hyperlink for better navigation and corrected a couple of spelling errors.
5. *Staking (commit ff9c493ced80):* Added a missing …

Enhancements to Solana's Documentations for Better Clarity 

---

accounts-db/src/tiered_storage/hot.rs

HotAccountOffset::new() might return Err for invalid offset, and this
part needs some test coverage.
Add unit-tests for checking invalid HotAccountOffset.

[TieredStorage] Unit-tests for checking invalid HotAccountOffset

---

runtime/benches/accounts.rs

While [removing the featurization code for EpochAccountsHash](https://github.com/solana-labs/solana/pull/34417), a bench failed because EAH was now enabled.
Set EAH to Valid so that `Bank::new_from_parent()` doesn't panic during freeze.

Sets EpochAccountsHash to Valid in accounts bench

---

program-runtime/src/compute_budget_processor.rs
program-runtime/src/prioritization_fee.rs
programs/sbf/tests/programs.rs
runtime/src/accounts/mod.rs
runtime/src/bank/tests.rs
runtime/src/transaction_priority_details.rs
sdk/src/compute_budget.rs

feature `EfhYd3SafzGT472tYQDUc4dPd2xdEfKs5fwkowUgVt4W` Remove support for RequestUnitsDeprecated instruction #27500 activated everywhere.
- Cleanup feature code
- Update/remove tests on that feature gate
Fixes #

cleanup feature code after mainnet-beta activation

---

ledger/src/blockstore.rs

These entries are legacy code at this point; however, older release branches (v1.16 and v1.17) require these entries to be present. Also, while it would be nice to clean up these entries immediately, they only occupy a small amount of space so having them linger a little longer isn't a big deal.
Hold off on deleting these entries until a later point in time.
Funny enough, we've had some churn here:
- https://github.com/solana-labs/solana/pull/33649
- The `TransactionStatusIndex` entries stopped getting populated at startup
- https://github.com/solana-labs/solana/pull/33668
- The `TransactionStatusIndex` entries are explicitly deleted during blockstore cleaning via `Blockstore::maybe_cleanup_highest_primary_index_slot()`
- https://github.com/solana-labs/solana/pull/33756
- The …

Remove deletion of TransactionStatusIndex entries

---

ledger/src/shred/merkle.rs
ledger/src/shredder.rs
local-cluster/tests/local_cluster.rs

wider retransmitter set for last erasure batch.
makes last erasure batch size >= 64 shreds

makes last erasure batch size >= 64 shreds

---

Cargo.lock
Cargo.toml

This issue still exists for RPC operators: https://github.com/solana-labs/solana/issues/24644
Patch tokio to `solana-tokio` at v1.29.1 with 4eed411 manually reverted

Patch tokio to vendored version

---

programs/bpf_loader/src/lib.rs

Feature `CE2et8pqgyQMP2mQRg3CgvX8nJBKUArMu3wfiQiQKY1y` round up heap size when calculating heap cost #30679 has been activated everywhere. 
- cleanup feature code
Fixes #

cleanup feature code after activated everywhere

---

Cargo.lock
ledger-tool/Cargo.toml
ledger-tool/src/ledger_utils.rs

The ledger-tool `load_and_process_ledger()` function performs many sub-operations that can fail. The current error handling of printing text and exiting inline adds extra noise to the code that actually does work. ~Additionally, all of the separate exit points mean that there might be slightly different variations the common text when an unrecoverable error occurs.~
- Introduce `LoadAndProcessLedgerError` enum for `load_and_process_ledger()` error conditions
- Remove early exits and instead bubble up a `Result<_, LoadAndProcessLedgerError>`
- ~Introduce and use wrapper that unwraps or exits `load_and_process_ledger()`~
- ~Use the wrapper for all previous callers of `load_and_process_ledger()` to remove boilerplate code~
~The diff on this one is massive because some match statements were …

ledger-tool: Bubble up error enum instead of eprintln!() and exit()

---

runtime/src/accounts/mod.rs

feature DdLwVYuvDz26JohmgSbA7mjpJFgX5zP2dkp8qsF2C33V #27839  has been activated everywhere.
cleanup feature code
Fixes #

cleanup feature code after mainnet-beta activation of DdLwVYuvDz26JohmgSbA7mjpJFgX5zP2dkp8qsF2C33V

---

ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/program.rs

This PR is a split out from https://github.com/solana-labs/solana/pull/34426
Several commands call `load_and_process_ledger()` which can fail in a number of ways. These callers currently all handle the result in the same way by matching the return Result:
- The `Ok(_)` case uses the returned types as normal
- The `Err(_)` case prints an error message and exits
This error handling is redundant, and a helper could remove the duplicate code
- Introduce `load_and_process_ledger_or_exit()`, a wrapper for `load_and_process_ledger()` that unwraps OR prints an error message and returns for `Err`
- Use the new `load_and_process_ledger_or_exit()` in all previous callers of `load_and_process_ledger()`
- Run `cargo fmt` to remove the level of indentation from previous callers

ledger-tool: Condense repeated error handling

---

validator/src/cli.rs

- New scheduler is in, there's more than one option here, it shouldn't be hidden.
- I forgot to do this previously
- Don't hide the `--block-production-method` cli arg for validator
Fixes #

Unhide --block-production-method

---

runtime/src/bank.rs
runtime/src/bank/tests.rs

Transaction simulations only sum up the compute units of successful instructions, meaning that the compute units used on the errored instruction are lost. This creates a divergence between execution and simulation.
This one was pretty simple! Simply include the errored units to the reported units consumed. We could also read it out of the `execution_results` and avoid using the `timings`, but it seemed fine to stick with the `timings` since they gave the correct result.
Fixes #34445

bank: Add errored compute units during simulation

---

runtime/src/bank_forks.rs

`LoadedPrograms::latest_root` is set when `prune()` is called. Do an initial `prune()` call to initialize the field sooner.

v1.16: Initialize LoadedPrograms::latest_root earlier

---

ledger/src/blockstore_db.rs

A change landed somewhat recently in master that changed the key format of the transaction metadata columns. A compatibility backport was introduced to allow a blockstore that had been populated with this newer version to still be readable by v1.17 (backwards software compat).
However, there was an oversight in the backport. Namely, the `index()` function for AddressSignatures column did a regular `unwrap()` in `try_current_index()`. `try_current_index()` can fail if a key with an unknown size is encountered. This would be exactly the case for encountering a key that was populated by the newer software version with the different key format.
Namely, the following panic was observed when downgrading from recent tip of master to v1.17 with `--enable-rpc-transaction-history` flag:
```
thread …
```

blockstore: Allow fallback for AddressSignature index()

---

runtime/src/bank.rs

The same initialization occurs when the Bank is inserted into a new BankForks, so no need to duplicate the logic in this test function
Remove redundant code; below is the snippet where this same thing happens in `BankForks::new_from_banks()`:
https://github.com/solana-labs/solana/blob/2a67fa8d13e77d60704f0c522a914b0d259ecc3e/runtime/src/bank_forks.rs#L211-L216

Remove redundant code from Bank::wrap_with_bank_forks_for_tests()

---

program-runtime/src/loaded_programs.rs

This adds an explicit `SecondLevel` type where we used to use `Vec<Arc<LoadedProgram>>`, in preparation of adding more fields. 
It also fixes a minor issue where `prune_by_deployment_slot` would accidentally remove toplevel entries when it wasn't supposed to.

v1.16: LoadedPrograms: introduce explicit SecondLevel type, fix prune_by_deployment_slot bug

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

The root slot/epoch are integral part of the program cache, and must be initialized in `new()`.
- remove default implementation of cache
- add a constructor `new()` that takes root slot/epoch as parameters and sets it in the cache
- update `bank` to call the new constructor.
Fixes #

Set root slot/epoch in cache constructor

---

ci/docker-rust/README.md
docs/src/implemented-proposals/tower-bft.md
tokens/README.md

I've made a few updates to the documentation that correct typos and improve grammar. Below are the details of the changes:
1. **Commit e5c8dc1:** Fixed a duplicate word in the 'Voting Algorithm' section. This change enhances readability and clarity in the documentation.
2. **Commit 7a7f3c6:** Addressed grammatical issues in the documentation. Specifically, I removed an unnecessary 'of' from the phrase 'Both of docker images' and added 'is' to 'This image manually maintained'. These changes ensure that the documentation is more grammatically correct and easier to understand.
3. **Commit 36b49c6:** Corrected a typo from 'store it the recipient address' to 'store it in the recipient address'. This small but crucial fix ensures the sentence is accurate and clear.
These changes are minor but …

Documentation Improvements: Typos and Grammar Fixes

---

core/src/replay_stage.rs
rpc/src/rpc.rs
runtime/src/bank_forks.rs

BankForks has two constructors; one that takes a single Bank (the root) and one that can take an arbitrary number of Banks plus the root slot. However, the constructor that accepts multiple banks is unnecessary; it isn't used in production and is only used in several tests.
- Remove the BankForks constructor that allows multiple bank
- Update unit tests that used the multi-bank constructor

Only allow BankForks creation with single bank

---

RELEASE.md
ci/check-install-all.sh
ci/test-checks.sh
scripts/cargo-install-all.sh
scripts/spl-token-cli-version.sh

If https://github.com/solana-labs/solana-program-library releases a new version of `spl-token-cli` that depends on the beta branch, [this cargo-install-all command](https://github.com/solana-labs/solana/blob/39f2866a1084dd073387f47ccb7dc3a67a822ba9/scripts/cargo-install-all.sh#L154) will likely break, due to rust-version and various other mismatches.
Require the stable channel to set an explicit `$splTokenCliVersion`
Check that this is set in CI
Use `$splTokenCliVersion` to set a `--version` for the spl-token-cli `cargo install` command
Will fix #34429, with backports and (on v1.16) variable population

CI: add check for explicit spl-token-cli version

---

runtime/src/accounts/mod.rs

remove unused imports

---

local-cluster/tests/local_cluster.rs

When a leader creates a bank, it will apply new entries to the working bank and then sends them to broadcast stage to be shredded and stored in blockstore/transmitted.
There is a race between replay and broadcast stage, and sometimes replay will vote on the bank before broadcast stage has a chance to shred the last batch of entries and store them in blockstore.
When replay votes on the bank, it will notify the rpc subscribers of the new block through the `AggregateCommitmentService`:
https://github.com/solana-labs/solana/blob/a2d7be0d07d54578b64dbed79ad482229bb7e25b/core/src/replay_stage.rs#L2249-L2255
However in the case mentioned, blockstore does not yet have all of the data shreds and the subscribers will be sent an `RpcBlockUpdateError` as the `RpcBlockUpdate` cannot be constructed: …

local-cluster: fix flaky test_rpc_block_subscribe

---

runtime/src/bank.rs
runtime/src/bank/fee_distribution.rs

Feature `Fab5oP3DmsLYCiQZXdjyqT3ukFFPrsmqhXU4WU1AWVVF: prevent_rent_paying_rent_recipients` has been activated on all clusters.
Clean up feature gating
Probably easiest to review without whitespace changes, as the bulk of the lines changed are simply indented less.
Closes #30151

Clean up prevent_rent_paying_rent_recipients feature

---

cli-output/src/display.rs
client/src/send_and_confirm_transactions_in_parallel.rs

fix typo in variable names
Fixes #

fix typo in variable name and error messages

---

ledger-tool/src/bigtable.rs

We received a report of `solana-ledger-tool bigtable compare-blocks` returning a list of missing blocks that did actually appear to be present when queried with `solana-ledger-tool bigtable block`.
```
GOOGLE_APPLICATION_CREDENTIALS=<credential> ./solana-ledger-tool bigtable compare-blocks 13330000 10000 --reference-credential <other_credential> --rpc-bigtable-instance-name solana-ledger-hdd
[2023-11-12T10:37:34.112098337Z INFO  solana_ledger_tool] solana-ledger-tool 1.16.18 (src:612616be; feat:4033350765, client:SolanaLabs)
[2023-11-12T10:37:34.113806564Z INFO  solana_storage_bigtable::access_token] Requesting token for BigTableData scope
[2023-11-12T10:37:34.200364731Z INFO  solana_storage_bigtable::access_token] Token expires in 3599 seconds
[2023-11-12T10:37:34.477986775Z INFO …
```

Fix ledger-tool bigtable compare blocks

---

zk-token-sdk/src/instruction/batched_range_proof/mod.rs

As pointed out in https://github.com/solana-labs/solana/pull/34459#pullrequestreview-1782309068, there is a typo when calculating the hash of the merlin transcript in the range proof calculation. This should be fixed, but it does break compatibility with 1.17 and hence, must be backported to 1.17.
This PR is a one-line fix for the typo that should be backported to 1.17.
Note: The zk-token-proof program is not yet activated on any of the clusters.
Fixes #

[zk-token-sdk] Fix range proof transcript seed typo

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

Change extract() from returning a list of missing programs to taking an inout list from which the programs that have been found are removed. The existing cache logic is unchanged, this is just preparatory work for cooperative loading.

LoadedPrograms: refactor extract() to be able to do incremental work

---

ledger-tool/src/main.rs

Support for json output from cli tools has developed in a haphazard way. As result, there are inconsistent and sometimes duplicate implementations of things. For example, `solana-ledger-tool` uses both `solana_cli_output::OutputFormat` and its own hand-rolled output format enum in various places to track the desired output format. This makes it harder than it needs to be to make consistent the actual strings that get printed.
Remove `solana_ledger_tool::LedgerOutputMethod`
This makes no functional changes to the subcomands that used it; ie. the actual output format is still hard-coded in the subcommand match

Remove ledger-tool-specific output format enum

---

ledger-tool/src/main.rs

In most cases, the memory usage of `solana-ledger-tool` is not needed and adds extra noise to the log ouput.
Switch the default behavior from enabled to disabled for memory usage reporting. Note that the argument now differs from `solana-validator`; however, I think that is fine as again, lots of `solana-ledger-tool` runs are "one-offs" that we don't care about metrics for.

ledger-tool: Disable os memory reporting on verify command by default

---

ledger-tool/src/program.rs

The `solana-ledger-tool program` subcommand uses `solana_cli_output::OutputFormat`, but uses its own custom printer for no reason.
Use OutputFormat::formatted_string() to make usage more consistent
No functional changes, except that the order of fields for OutputFormat::JsonCompact changes slightly, due to using `serde_json::to_value(item).unwrap().to_string()` under the hood (instead of `serde_json::to_string(&output).unwrap()`). We don't guarantee the order of json fields, so this change should be non-breaking.

ledger-tool: Use OutputFormat printer in program subcommand

---

cost-model/src/cost_model.rs
sdk/src/fee.rs

cost_model:: calculate_loaded_accounts_data_size_cost() has become an unnecessary wrapper 
- remove it
Fixes #

remove unnecessary wrapper function

---

cost-model/src/cost_model.rs
program-runtime/src/compute_budget.rs
program-runtime/src/compute_budget_processor.rs
programs/sbf/tests/programs.rs
runtime/src/accounts/mod.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/transaction_priority_details.rs

after all features related to `compute_budget_processor()` are activated everywhere, it no longer needs feature-set as parameter
- remove feature-set as parameter
Fixes #

Remove feature set from compute budget processor

---

runtime-transaction/src/runtime_transaction.rs
runtime-transaction/src/transaction_meta.rs

Adding requested limits with expiry, currently set via ComputeBudgetInstructions, to runtime-transaction's static meta.
1. add internal `struct RequestedLimitsWithExpiry` to tag compute_budget_limits with expiry (eg last slot of current epoch)
2. unwrap `compute_budget_limits` into flat fields, add to `StaticMeta`, avoiding exposing compute_budget stuff to callsite.
Fixes #

add requested limits to static meta

---

docs/publish-docs.sh
docs/src/operations/setup-a-validator.md

Trailing whitespace in docs is against our style policy.
Our sanity CI check is unhappy about it.
These were added in
commit 676e80c80a914c6f41a4f5d12f419d35a8047dd8
Author: Nick Frostbutter <75431177+nickfrosty@users.noreply.github.com>
Date:   Mon Dec 11 15:17:13 2023 -0500
[docs] docs migration (#34096)
Seems like CI marked the original change as having an issue, but it was still submitted.
Removed the whitespace.

[docs] Remove trailing whitespace

---

program-runtime/src/loaded_programs.rs
programs/sbf/tests/programs.rs
runtime/src/bank.rs

Currently transaction batches race in parallel to load, verify and compile missing cache entries.
Instead they should be coordinating and split these tasks to distribute the workload across the threads and to avoid redundant work.
- Verification-less reloading had to be disabled again, it can be reintroduced later.
- Refactors `LoadedPrograms::extract()` to use a mutable parameters instead of returning them in order to support multiple iterations.
- Adds explicit `SecondLevel` structure to `LoadedPrograms` to have a per address cooperative loading lock.
- Adds a conditional variable waiting section to prevent a TX batch from spinning when waiting without a loading task of its own.
- Corrects the fork graph in some tests which is important now, otherwise a TX batch would not find the …

Feature - Cooperative Program Loading

---

sdk/src/feature_set.rs

I lost the key for `stake_minimum_delegation_for_rewards` when I migrated from gcp boxes.
rekey stake_minimum_delegation_for_rewards feature
Fixes #
Feature Gate Issue: https://github.com/solana-labs/solana/issues/29622

rekey stake limit feature

---

CHANGELOG.md

As per some conversation on the Telegram RPC channel, we should make the RPC-output changes in https://github.com/solana-labs/solana/pull/33419 more obvious
Add to changelog
Some additional details for posterity: before #33419 , for multiple addresses within the same block, those pulled from local Blockstore were returned in signature order, whereas those from Bigtable were returned in block-inclusion order. This meant, for nodes backed by Bigtable, there were inconsistencies in return data over time and at the boundary between local Blockstore ledger and Bigtable (`minimumLedgerSlot`).
After the change, ordering will be consistent regardless of which data store a particular slot is queried from.

changelog: add getSignaturesForAddress ordering

---

accounts-db/src/tiered_storage/hot.rs

Hot accounts are stored in accounts blocks, whose offset is smaller than
the index block offset.  However, the current code doesn't perform
any boundary checks when accessing hot account meta.
Adds boundary check when accessing hot account meta.

[TieredStorage] Boundary check for accessing hot account meta

---

program-runtime/src/loaded_programs.rs
programs/bpf_loader/src/lib.rs
runtime/src/bank.rs

Current eviction policy for `LoadedPrograms` cache relies on program's `usage_counter` to decide which entry to evict. The `usage_counter` increases monotonically. This means if an old program which was frequently used in the past, but not used anymore, has higher chance of staying in the cache. This can make it harder for new programs to stay in the cache once the cache depth limits are reached. 
- Decay the `usage_counter` of a program if the program does not get used.
- Use 2's random selection to pick a program entry to be evicted from the cache.
- Add unit tests for the new code
Fixes #

Improve cache eviction policy for LoadedPrograms

---

ledger-tool/src/bigtable.rs

`LedgerStorageConfig` contains a `read_only` field, but this isn't being populated correctly for some `solana-ledger-tool bigtable` subcommands. This could be a footgun for the CLI if someone modified `solana-storage-bigtable` methods to mutate the bigtable without handling appropriately in `solana-ledger-tool`.
Set more subcommands as read-only
I did confirm the setting works as intended, and prevents a block upload when set. However, the CLI just hangs indefinitely on `Preparing the next 1 blocks for upload`, which isn't very clear. I'll look at making that error out properly.

ledger-tool: make read_only consistent across bigtable subcommands

---

core/src/replay_stage.rs
sdk/src/feature_set.rs

https://github.com/solana-labs/solana/pull/32962 needs to be feature flagged as it could cause a divergence in fork choice.
Add a feature gate to ensure smooth rollout to 1.17

replay: feature flag consumption of duplicate proofs from blockstore

---

Cargo.lock
Cargo.toml
ci/run-sanity.sh
core/Cargo.toml
core/src/validator.rs
ledger-tool/Cargo.toml
ledger-tool/src/ledger_utils.rs
ledger/src/blockstore_processor.rs
local-cluster/tests/local_cluster.rs
programs/sbf/Cargo.lock
runtime/src/bank.rs
runtime/src/installed_scheduler_pool.rs
runtime/src/prioritization_fee_cache.rs
unified-scheduler-logic/Cargo.toml
unified-scheduler-logic/src/lib.rs
unified-scheduler-pool/Cargo.toml
unified-scheduler-pool/src/lib.rs

I'm quite high in the midnight, concluding all the plumbing efforts so far with this pr.
(translate: there's the last missing piece of code (trait impl boilerplates, cli integration), before landing the unified scheduler impl)
get some sleep.
(translate: this pr added the last plumbing with extensive unit tests after these plumbing is confirmed to work at https://github.com/ryoqun/solana/pull/15. also, end to end integration niceties: the dreadful local-cluster test and quick-and-dirty `run-sanity.sh` tweaks).
also note that this is the next big chunk of code (contains the real code for unified scheduler): https://github.com/ryoqun/solana/pull/15 (a bit desynced from the tip of #33070 right now...)

Finish unified scheduler plumbing with min impl

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

I want to introduce an earlier fee-payer check/validation, before we take locks.
Add a `pre_lock_filter` to schedule
Empty for now in the actual controller.
Fixes #

TransactionScheduler: pre_lock_filter

---

core/src/validator.rs

On mainnet-beta, respective QUIC endpoint are unnecessary for now until testnet has fully migrated to QUIC.
The commit disables turbine and repair QUIC endpoints on mainnet-beta.

disables turbine and repair QUIC endpoints on mainnet-beta

---

docs/src/cli/install.md

I was building the Solana binary after following the [Setup a Solana Validator](https://docs.solana.com/validator/get-started/setup-a-validator) guide. 
I used a recently created VM for this, so I had a clean environment. I ran `./scripts/cargo-install-all.sh .` up to four times because I didn't have the prerequisites to perform the build. **Using a Build from source is encouraged in the guide**
The build requirements are pretty standard and are likely to be maintained, but the failures might discourage non-developers from playing around and creating a validator node. This MR tries to fix this by providing extended information on prerequisites before triggering the build.
This MR updates the `docs/src/cli/install.md` page from the official documentation, adding the build prerequisites for …

Update build by source docs to add pre-requisites

---

scripts/cargo-install-all.sh

`scripts/cargo-install-all.sh` breaks when run outside the `solana` directory: https://discord.com/channels/428295358100013066/670512312339398668/1186583553325142077
This is because source isn't handling the relative path to `spl-token-cli-version.sh` correctly
Use full path instead

cargo-install-all: use full path for sourcing

---

runtime/src/bank/tests.rs

A test function no longer need to use feature_set; it also uses wrong variable name;
- remove unused feature_set
- remove wrongly named, and unused parameter
Fixes #

clean up no longer needed feature_set in test

---

local-cluster/tests/local_cluster.rs

format! already uses to_string() to format it's arguments, so no need to convert it with to_string()
Remove to_string()
Fixes #

Remove to_string which is not necessary

---

core/src/window_service.rs
sdk/src/feature_set.rs
turbine/src/cluster_nodes.rs

These cases introduced in 1.17 https://github.com/solana-labs/solana/pull/32965 need to be feature flagged as
https://github.com/solana-labs/solana/blob/74c54a7856982b9f4f4b2c65b79a504eb307aad3/core/src/window_service.rs#L172-L173
will update fork choice.
Add feature flag to ensure that fork choice is consistent along the cluster when upgrading to v1.17.

Add feature flag for LastIndex and Erasure duplicate proofs

---

ledger-tool/src/bigtable.rs
ledger-tool/src/output.rs

Now that entries are uploaded to bigtable, `solana-ledger-tool bigtable block` can reconstruct complete blocks comparable to the data returned by `solana-ledger-tool slot`.
Re: https://github.com/solana-labs/solana/pull/34266#pullrequestreview-1758223135
Add `--show-entries` flag to build block display struct with entries
Output looks like:
```
$ solana-ledger-tool bigtable block 2 --show-entries
Slot: 2
Parent Slot: 1
Blockhash: D9aBYGVchmxMprqqGDGhCcYkJXS78S4Xnygj2Lnd9pvu
Previous Blockhash: FP1G5WQBMebHhnBkCXLctcU63rkRCzkYACKsPEyZJPvT
Block Time: 2023-12-14T17:28:49-07:00
Block Height: 2
Rewards:
Address                                            Type        Amount           New Balance           Percent Change  Commission
9a25m7QZ2VMkiFETP2UzQxnCnUfEE3LUKbXCnWPb1mGz        fee …
```

ledger-tool: add show-entries option to bigtable block

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

get_account_address() does not check whether IndexOffset is valid.
This PR adds two checks.  First, it checks whether the IndexOffset exceeds
the boundary of the index block.  Second, when an index format that has the
same index entries as account entries is used, it also checks whether IndexOffset
is smaller than account_entry_count.
New unit-test is added.

[TieredStorage] boundary check for get_account_address()

---

scripts/cargo-install-all.sh
scripts/spl-token-cli-version.sh

https://github.com/solana-labs/solana/pull/34547 for v1.16
Move arg to after install subcommand
Also fix semver, now that version is actually being respected

V1.16: Cargo needs version arg after subcommand

---

ledger-tool/src/bigtable.rs

Querying bigtable for a block with a v0 transaction in it errors:
```
$ GOOGLE_APPLICATION_CREDENTIALS=<mnb_credential> solana-ledger-tool bigtable block 236304134
..
"Failed to process unsupported transaction version (0) in block"
```
Update encoding options to support blocks with v0 transactions

ledger-tool: support v0 transactions in blocks from bigtable

---

scripts/cargo-install-all.sh

Move arg to after `install` subcommand

Cargo needs version arg after subcommand

---

ci/publish-crate.sh

Crate publishing failed for v1.16.24, starting with `solana-storage-proto` and all child crates
```
Caused by:
package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
```
Hardcode a slightly higher rust version for crate publishing
(v1.16 is v close to EOL; hopefully after this minor version we can just keep up!)

v1.16: Hardcode rust version for publish-crate

---

storage-bigtable/src/access_token.rs

extracted from #34213
Right now we clone `AccessToken` on every request to BigTable, also we clone it when making a token refresh. Inside `AccessToken` we clone [Credentials](https://docs.rs/goauth/latest/src/goauth/credentials.rs.html#9-22) struct which contains few strings and also clone 2 Arc. We can wrap everything into one Arc and significantly reduce the number of clones.

bigtable: remove extra clones

---

runtime/src/accounts/mod.rs

The comment about simplify_writable_program_account_check in `load_transaction_accounts()` currently describes the block below, not its own if branch.
Rewords the comment.

Reword comment in `load_transaction_accounts()`

---

bloom/benches/bloom.rs
bloom/src/bloom.rs
gossip/src/crds_gossip_pull.rs
gossip/src/push_active_set.rs

- `contains`, `add` operations are not atomic at the struct level. This should be reflected in the structure name.
- The `clear` function takes a mutable reference for no reason
- The `clear` function is named `for_tests`, but this is a valid operation which I want to use for filtering invalid payer keys, and clearing periodically w/o locking
- Rename struct `AtomicBloom` to `ConcurrentBloom`
- `clear` - Take immutable reference, rename to `clear` from `clear_for_tests`
- All read/write operations are not atomic at the struct level, but only at the element level. Renaming the struct makes it clear that operations are not atomic.
- A concurrent write can be partially overwritten, since the operation(s) are not atomic at the structure-level, but at each group of 64 bits in the `AtomicU64`. …

Rename: AtomicBloom to ConcurrentBloom

---

.github/workflows/cargo.yml
.mergify.yml
scripts/cargo-clippy-nightly.sh
scripts/cargo-clippy-stable.sh
scripts/cargo-clippy.sh

context: https://discord.com/channels/428295358100013066/560503042458517505/1187442157326450780
- split cargo-clippy into stable and nightly
btw, if we still feel this one too slow, I can split them into smaller pieces (but will be a little bit hardcoded)
or we need a better macos runner 😢

ci: split cargo-clippy into stable and nightly

---

accounts-db/src/tiered_storage/index.rs

TieredStorage doesn't perform boundary check in get_account_offset
when the input IndexOffset isn't valid.
This PR adds two checks.  First, it checks whether the IndexOffset exceeds
the boundary of the index block.  Second, when an index format that has the
same index entries as account entries is used, it also checks whether IndexOffset
is smaller than account_entry_count.
Two new tests are added in this PR.

[TieredStorage] Boundary check for get_account_offset()

---

sdk/src/feature_set.rs

I lost the key for partitioned epoch rewards feature when we migrated from gcp
boxes.
rekey partitioned epoch rewards feature
Fixes #
Feature Gate Issue: # https://github.com/solana-labs/solana/issues/32166

rekey partitioned epoch rewards

---

cli/src/stake.rs
program-test/tests/warp.rs
programs/stake/src/stake_instruction.rs
programs/stake/src/stake_state.rs
rpc/src/rpc.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/stakes.rs
runtime/tests/stake.rs
sdk/program/src/stake/state.rs

The optional `stake_history` arg is never `None` except for in tests which can use `StakeHistory::default()`
- Remove option wrapping for `stake_history` arg
Fixes #

refactor: optional `stake_history` arg is never `None`

---

bench-tps/src/send_batch.rs
local-cluster/tests/local_cluster.rs
quic-client/tests/quic_client.rs
streamer/src/nonblocking/quic.rs

We currently limit of concurrent unstaked QUIC streams. But the client can create unbounded number of streams over time by closing existing streams and creating new ones.
Track number of streams created in a connection
Once the limit is reached, wait till the next time interval before accepting new streams
Fixes #

Throttle unstaked quic streams for a given connection

---

accounts-db/src/tiered_storage/hot.rs

Each AccountsFile is required to implement account_matches_owners(),
a public API that checks whether the account located at the specified
offset matches any input owners.  However, the implementation of
account_matches_owners() for HotAccountsStorage is missing.
This PR implements HotStorageReader::account_matches_owners().
A new unit-test is added to this PR.

[TieredStorage] HotStorageReader::account_matches_owners

---

accounts-db/src/tiered_storage/index.rs

There're some typos in the comments and assert messages index.rs mentioned in #34529
Fix the typos (only in assert message and comments).

[TieredStorage] Fix typos in index.rs

---

CHANGELOG.md
docs/src/implemented-proposals/rpc-transaction-history.md

The BigTableUploadService now uploads entries, but this behavior isn't documented.
Add entries schema to "Longterm RPC Transaction History" implemented proposal
Add to changelog
solana-bigtable repo updated here: https://github.com/solana-labs/solana-bigtable/pull/17

Add entries table to bigtable docs

---

ledger/src/blockstore.rs

We commit the in memory maps to blockstore every iteration which results in a lot of rewrites.
Explicitly track which entries are dirty and only commit those.

blockstore: write only dirty erasure meta and merkle root metas

---

streamer/src/nonblocking/quic.rs
streamer/src/quic.rs

add metrics on throttled streams

---

accounts-db/src/tiered_storage/hot.rs

All structs that implement AccountsFile are required to support get_account,
but the implementation for HotAccounts is currently missing.
This PR implements HotAccountsReader::get_account_from_index_offset.
This will allow it to support AccountsFile::get_account API.
Add new unit-test.

[TieredStorage] HotAccountsReader::get_account

---

runtime/src/bank/bank_hash_details.rs

The original implementation for bank hash details files (https://github.com/solana-labs/solana/pull/32632) only allows for outputting a single slot at a time. It is advantageous to allow the schema to support multiple slots. One such usescase is a proposed process described in more detail in https://github.com/solana-labs/solana/pull/34246#issuecomment-1833284535. The idea would be:
- Generate the bank hashes for a bunch of slots in a ledger using a "known good" version
- Retain the ledger and bank hash file
- Later, use the ledger + good hashes for testing, whether manual testing of a new feature or in some automated fashion
- Ie, run the test branch and check computed hashes against good hashes, divergent could be spit out to reduce triage time
Adjust the `BankHashDetails` struct to …

Allow bank hash file to contain details for multiple slots

---

bloom/src/bloom.rs

- Want to do earlier filtering for keys we know to not pay fees
- `ConcurrentBloomInterval` - will be used to store invalid fee paying keys and filter them out quickly. These keys should be reset periodically, so wrapped in an `AtomicInterval` so that only 1 thread actually does the clearing.
- Eventually, I'm hoping to use this in both sigverify and banking stage, so wanted to define the struct somewhere both perf and core can use it.
Fixes #

ConcurrentBloomInterval

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock

- prio-graph 0.2.0 had a bug which did not correctly track write-read conflicts if there were multiple reads after a write. This is fixed in 0.2.1 - see https://github.com/apfitzge/prio-graph/pull/57
- If the write had higher-priority, the scheduler will still have scheduled the write first. However, if they had the same priority, it could have led to an inconsistent scheduling order.
- Bump prio-graph version
Fixes #
--- 
Close #34606

Bump prio-graph version to 0.2.1

---

Cargo.toml
programs/sbf/Cargo.lock

the error:
https://buildkite.com/solana-labs/solana/builds/106180#018ccc86-c779-4137-926a-13d3f3752bb4
the convo:
https://discord.com/channels/428295358100013066/560503042458517505/1191428671303598242
pin ahash to 0.8.4 (0.8.3 has been yanked and solana-frozen-abi is using 0.8.4)

v1.17: pin ahash to 0.8.4

---

validator/src/dashboard.rs

There are new nightly clippy lints in the validator crate. Refer to https://github.com/solana-labs/solana/issues/34626 for more information.
```
warning: in a `match` scrutinee, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a `let`
--> validator/src/dashboard.rs:223:38
|
223 |                       match async move {
|  ______________________________________^
224 | |                         let rpc_addr = admin_client.rpc_addr().await?;
225 | |                         let start_time = admin_client.start_time().await?;
226 | |                         Ok::<_, jsonrpc_core_client::RpcError>((rpc_addr, start_time))
227 | |                     }
| |_____________________^
|
= help: for further information visit …
```

clippy: validator lints

---

accounts-db/src/rolling_bit_field/iterators.rs

There are new nightly clippy lints in the accounts-db crate. Refer to https://github.com/solana-labs/solana/issues/34626 for more information.
```
warning: this `let...else` may be rewritten with the `?` operator
--> accounts-db/src/rolling_bit_field/iterators.rs:36:13
|
36 | /             let Some(bit) = self.bit_range.next() else {
37 | |                 return None;
38 | |             };
| |______________^ help: replace it with: `let bit = self.bit_range.next()?;`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#question_mark
= note: `#[warn(clippy::question_mark)]` on by default
Checking solana-rpc-client-api v1.18.0 (/Users/brooks/src/solana/rpc-client-api)
warning: `solana-accounts-db` (lib) generated 1 warning
```
Fix 'em.

clippy: accounts-db lints

---

ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/output.rs

We have a dedicated file for CLI output, so move the various output functions there.
There is probably work to be done to clean up these `output_*()` functions; however, I think that should be deferred for the sake of this PR as I have another PR that I would like to have consume this one.

ledger-tool: Move ledger output methods to output.rs

---

.gitignore

we should ignore all *farf* dirs in .gitignore.
add `farf/` to git ignore
Fixes #

chore: ignore farf/ in .gitignore

---

core/src/window_service.rs
ledger/src/blockstore.rs
ledger/src/blockstore_meta.rs
sdk/src/feature_set.rs

We only construct duplicate proofs for conflicting shreds, LAST_SHRED_IN_SLOT, and erasure meta conflicts.
When receiving a new shred check to see if there is a merkle root conflict from an existing merkle root meta. If there is such a conflict, construct a duplicate proof and notify gossip and the duplicate block state machine. 
Split from https://github.com/solana-labs/solana/pull/33889
Fixes #33644

blockstore: populate duplicate shred proofs for merkle root conflicts

---

program-test/src/lib.rs
program-test/tests/warp.rs

The program test contains only method to warping to a particular slot. It would be nice to have a way to easily warp per epoch. The method https://github.com/solana-labs/solana/blob/v1.17.7/ledger-tool/src/main.rs#L3447 provides the calculation of the number of slots per epoch.
It could be then mapped to e.g., `bankrun` to profit from https://github.com/kevinheavey/solana-bankrun/pull/13
New method `warp_to_epoch` for the tests.

[program-test] adding method warp_to_epoch

---

ledger-tool/src/main.rs

There are new nightly clippy lints in the `ledger-tool` source. See the parent issue https://github.com/solana-labs/solana/issues/34626 for more context
Apply the change suggested below
```
warning: `flatten()` will run forever if the iterator repeatedly produces an `Err`
--> ledger-tool/src/main.rs:2649:39
|
2649 |                 for line in f.lines().flatten() {
|                                       ^^^^^^^^^ help: replace with: `map_while(Result::ok)`
|
note: this expression returning a `std::io::Lines` may produce an infinite number of `Err` in case of a read error
--> ledger-tool/src/main.rs:2649:29
|
2649 |                 for line in f.lines().flatten() {
|                             ^^^^^^^^^
= help: for further information visit …
```

clippy: ledger-tool lints

---

cli/src/program.rs
cli/tests/program.rs
program-runtime/src/invoke_context.rs
programs/bpf_loader/src/lib.rs
programs/bpf_loader/src/serialization.rs
programs/loader-v4/src/lib.rs
programs/sbf/benches/bpf_loader.rs
programs/sbf/tests/programs.rs
runtime/src/accounts/mod.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
sdk/src/account.rs
sdk/src/feature_set.rs
sdk/src/transaction_context.rs

Part of effort for https://github.com/solana-labs/solana/issues/33970
We are deprecating executable meta flags on account. Instead of relying on executable flag on account to determine whether the account is executable, we are going to check the owner of the account and the loader's meta data in account data to determine whether the account is executable.
- use owner + metadata in accounts data to determine whether the account is executable in transaction loading/processing.
- add disable_bpf_loader_instructions feature to disable bpf loader management instructions,
- add deprecate_executable_meta_update_in_bpf_loader feature to deprecate executable meta update in bpf loader
- [34424](https://github.com/solana-labs/solana/issues/34424)
- …

Deprecate account meta executable read/update in bpf loaders 

---

ledger-tool/src/bigtable.rs
ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/program.rs

The `open_blockstore()` helper currently takes multiple configurable options. While the arguments are parsed at a high enough scope in `main.rs` to avoid repeated calls, this parsing is duplicated in `program.rs` and `bigtable.rs`. The repeated parsing is redundant, and also prone to having to missing an arg (as was the case with bigtable not having wal_recovery_mode).
Move the argument parsing to within `open_blockstore()` to avoid repeated code and to reduce the number of parameters getting passed around.

ledger-tool: Move blockstore arg parsing to open_blockstore()

---

programs/bpf_loader/src/syscalls/mem_ops.rs

See https://github.com/solana-labs/solana/issues/34626

bpf_loader: fix clippy::blocks_in_conditions lint

---

ledger-tool/src/main.rs

A future change will add more cases to this if-else if-...-else chain. Using a match statement will be easier to follow then a very long if-else if-... chain.
This change was broken out in order to have a higher signal to noise ratio in the subsequent change.
Switch if-else over to match, and then run cargo fmt which will adjust white space in a lot of places. The downstream PR that would build on top of this is https://github.com/solana-labs/solana/pull/34597. Namely, this section [here](https://github.com/solana-labs/solana/pull/34597/files#diff-fe20bb9062954767913766205f72e8eb5ae88909c0d2529ec706e27a3e0eb800R1475-R1497) would look like this with the match statement:
```rust
match matches.subcommand() {
("bigtable", Some(arg_matches)) => bigtable_process_command(&ledger_path, …
```

ledger-tool: Switch subcommand dispatch from if-else to match

---

ledger-tool/src/ledger_utils.rs

TransactionStatusService needs Primary access in order to write
transaction status into the Blockstore if enable_rpc_transaction_history
is set to True. The current logic attempts to get Primary access for the
service.
However, in the event that this function had been called with a
Blockstore that already had Primary access, this second attempt to get
Primary access would fail. So, only attempt to open with Primary access
when necessary AND when the current access level is not sufficient.
Note that this function is currently called with `Secondary` (read only) blockstore access. So, we would not currently run into this error with the default. Someone setting several flags in a particular manner could technically encounter this error. 
Regardless, there is no requirement about the access …

ledger-tool: Adjust logic to obtain TransactionStatusService Blockstore

---

core/src/banking_stage/consumer.rs
core/tests/fork-selection.rs

There are new nightly clippy lints in the core crate. Refer to https://github.com/solana-labs/solana/issues/34626 for more information.
```
warning: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
--> core/src/banking_stage/consumer.rs:153:29
|
153 |         packets_to_process: &Vec<Arc<ImmutableDeserializedPacket>>,
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `&[Arc<ImmutableDeserializedPacket>]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
= note: `#[warn(clippy::ptr_arg)]` on by default
warning: `solana-core` (lib) generated 1 warning
```
```
warning: unit tests in doctest are not executed
--> core/tests/fork-selection.rs:15:5
|
15 |   //! #[test]
| …
```

clippy: core lints

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs
ledger/src/blockstore_db.rs
ledger/src/blockstore_meta.rs

Semi-automated backport of #33979; we had previously marked that branch for v1.16 BP in https://github.com/solana-labs/solana/pull/34046, but I am unable to reopen that PR. This is the same state of those commits with a rebase for tip of v1.16
As for the motivation for this PR (discussion happened in Discord starting from [here](https://discord.com/channels/428295358100013066/910937142182682656/1192134449740120115)):
- The new column was backported to v1.17
- Because of the above, a blockstore that has been modified by v1.17 CANNOT be opened by v1.16 due to the extra column
- The above could be problematic for operators who try upgrading to v1.17 and then want to downgrade to v1.16. As we saw in the testnet restart exercise, the "solution" was to wipe rocksdb ... this is unacceptable for …

v1.16: add merkle root meta column to blockstore (backport of #33979)

---

CHANGELOG.md
clap-utils/src/offline.rs
clap-v3-utils/src/offline.rs

The `--signer` arg doesn't exactly work as expected because it allows for multiple values. This means clap allows for someone to specify: `--signer <PUBKEY>=<SIG> <PUBKEY>=<SIG>`
This can be useful in some situations, but it's inconsistent with the documentation.
For example, https://docs.solana.com/offline-signing#submitting-offline-signed-transactions-to-the-network mentions to specify "--signer BASE58_PUBKEY=BASE58_SIGNATURE, one for each offline signer.", and the examples use multiple occurrences of `--signer`.
Also, the example command of:
```
solana@online$ solana transfer --blockhash 5Tx8F3jgSHx21CbtjwmdaKPLM5tWmreWAnPrbqHomSJF \
--signer FhtzLVsmcV7S5XqGD79ErgoseCLhZYmEZnz9kQg1Rp7j=4vC38p4bz7XyiXrk6HtaooUqwxTWKocf45cstASGtmrD398biNJnmTcUCVEojE7wVQvgdYbjHJqRFZPpzfCQpmUN …
```

clap-utils: Forbid multiple values for `--signer`

---

clap-v3-utils/src/fee_payer.rs
clap-v3-utils/src/input_parsers/signer.rs
clap-v3-utils/src/input_validators.rs
clap-v3-utils/src/keypair.rs
clap-v3-utils/src/nonce.rs
keygen/src/keygen.rs
remote-wallet/src/locator.rs
zk-keygen/src/main.rs

In clap-v3, the `Arg::validator` is deprecated and replaced with `Arg::value_parser`. The idea is that when we validate an argument input, we generally parse the input, so dividing validation and parsing in separate steps forces you to parse input twice.
A previous PR https://github.com/solana-labs/solana/pull/33276 deprecated most of the validation functions in clap-v3-utils and replaced them with parsing functions. This PR is a follow-up that deprecates validation functions related to the signer.
I thought a bit about implementing the clap parsers for `Signer`, `Pubkey`, and `Keypair`. I think the most idiomatic way of doing this is to expose the `SignerSource` as an intermediate type to do the parsing. I made some examples in the test.
- …

[clap-v3-utils] Deprecate signer source validation

---

ledger/src/blockstore.rs

Grepping logs, one is probably inclined to search for `blockstore` (the name of the higher level object in the source code) instead of `database`.
- Use `blockstore` in place of `database`
- Make the log after the open operation more similar to one prior to make it more clear that they are the before/after
Before this PR:
```
[...  solana_ledger::blockstore] Opening database at "/home/sol/ledger/rocksdb
[...  solana_ledger::blockstore] "/home/sol/ledger/rocksdb" open took 895ms
```
And after this PR:
```
[...  solana_ledger::blockstore] Opening blockstore at "/home/sol/ledger/rocksdb
[...  solana_ledger::blockstore] Opening blockstore done; blockstore open took 895ms
```

Adjust blockstore open logs to say blockstore instead of database

---

accounts-cluster-bench/src/main.rs

No way to benchmark the RPC subsystem while creating large numbers of accounts like with accounts-cluster-bench.
Add RPC benchmarking threads to accounts-cluster-bench which can query for the created accounts while the bench is running.
Fixes #

Add RPC bench threads to accounts-cluster-bench

---

accounts-db/src/tiered_storage/footer.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/index.rs

In the previous refactoring, IndexBlockFormat::AddressAndBlockOffsetOnly
can now work independently with the AccountMetaFormat.  As a result,
the naming of this format should be updated to reflect this.
As the format first persists the list of addresses followed by the list of offsets,
this PR renames AddressAndBlockOffsetOnly to AddressesThenOffsets.

[TieredStorage] Rename AddressAndBlockOffsetOnly to AddressesThenOffsets

---

accounts-db/src/tiered_storage/hot.rs

The implementation of HotAccountWriter is missing.
This PR kicks off the implementation of HotStorageWriter by
adding HotStorageWriter::new().
Add a new unit-test that verifies the correctness of HotStorageWriter
writing zero accounts using HotStorageReader.

[TieredStorage] HotStorageWriter::new()

---

programs/zk-token-proof-tests/tests/process_transaction.rs

feature gate #30620 is activated everywhere, forcing all native programs to consume CUs. Some of ZK token programs consume more than default instruction CU limits (eg 200_000 CUs), therefore its tests would fail when feature code is cleaned up.
- set all ZK-token-programs test transactions with MAX cu limits (eg 1_400_000)
Fixes #

add max cu-limit to test transactions

---

SECURITY.md

It's not clear that the SPL has its own security policy for those just looking at the monorepo security policy, and in fact confused a few people.
In the "Out of Scope" section, add a link to the SPL security policy. 
Fixes #

security-policy: Refer to SPL for on-chain programs

---

.gitignore

We have at least target/ and programs/sbf/target/

git: ignore all `target/` directories

---

accounts-db/src/accounts.rs

- I am adding some earlier filtering of transactions that has different `TransactionError`, which happens before locking
- We are unlocking some error'd lock results if they do not match the specific set of possible errors that is currently in this function
- With newly introduced filtering, this creates a race condition that leads to multiple write locks being taken concurrently if a batch with an error were unlocked during processing
- Only unlock transactions that we actually took locks for
Fixes #

Unlock only if lock_result was Ok

---

ledger-tool/src/args.rs

Really minor change here; made the change as part of something else but decided to break it out to avoid cluttering the other PR
- Avoid parsing the `accounts_index_path` twice when it is present
- Reorder the parsing so that the "associated" items appear next to each other. Namely, put all of the parts of `AccountsIndexConfig` next to each other instead of having the `test_partitioned_epoch_rewards` smack in the middle of it

ledger-tool: Minor cleanup on accountsdb config argument parsing

---

ledger/src/blockstore_processor.rs
program-test/src/lib.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

When creating bank 0 for tests, oftentimes the genesis config doesn't include a staked node. This means that bank creation has to arbitrarily pick a node id for block 0 in order for bank creation to succeed. The arbitrary node id was recently updated to be a random unique pubkey in https://github.com/solana-labs/solana/pull/33887 but as discussed [here](https://github.com/solana-labs/solana/pull/33887#discussion_r1394732271) we need to make sure this path is never hit by tests.
- Add the arg `test_collector_id: Option<Pubkey>` to `Bank::new_with_paths` which can be used as a fallback collector id if no staked nodes are defined in the genesis. This arg is set to `None` in call-sites that aren't related to testing or benchmarks.
Fixes #

Update genesis processing to have a fallback collector id for tests

---

.github/workflows/autolock_bot_PR.txt
.github/workflows/autolock_bot_closed_issue.txt
.github/workflows/downstream-project-spl-nightly.yml
.github/workflows/manage-stale-issues-and-prs.yml

Forks will run all the cron schedules.  And I do not think they benefit from those.  For the downstream project checks, these runs are actually very expensive - about an hour of run time per execution.  Easily draining free account limits.
Disable jobs that run on cron schedules, except for the main repo.
---
I am not 100% sure this is the best solution.
But this is what I was able to figure out base on some online discussions.
I do not think anyone wants to run this in their forks?
But if they do, they would need to carry a local patch.

GitHub workflows: Disable cron schedule for forks

---

program-test/src/lib.rs
runtime/src/bank/tests.rs

All builtin programs must consume some units. Program-test should too when it is in "native" mode.
- Program-test consume 1 unit when in native mode
- harden a unit test wrt if builtin consumes units.
Fixes #

program-test consumes some units as native

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs

- This feature helped in simulated traffic with forking/joining and txs were relatively cheap, but is not helping w/ mnb traffic where the txs are more expensive
- Remove this feature for the time being
- Removing this will increase the number of unschedulable transactions, but will also lead to better load balancing for our highest priority transactions.
Fixes #

Remove chain-joining thread-selection

---

.github/workflows/cargo.yml
.mergify.yml

after we bumped rust nightly version, the macos nightly clippy becomes very flaky. listed some of them here:
- https://github.com/solana-labs/solana/actions/runs/7471834475
- https://github.com/solana-labs/solana/actions/runs/7470806359
- https://github.com/solana-labs/solana/actions/runs/7468751360
- https://github.com/solana-labs/solana/actions/runs/7468441247
all of them are terminated by signal 6
use `macos-latest-large` for macos nightly clippy test
---
the only concern is that it will charge us more.
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

ci: use larger runner for macos nightly clippy 

---

runtime/src/loader_utils.rs

When we use bpf_loader v2 to load a program, we create a buffer account to
upload the program data. However, the required minimum balance of the account
is calculated directly from the program data length, which is not the correct
length for the actual account's data. The actual accounts' data include the additional
45 bytes of metadata. 
Therefore, this can result that buffer account doesn't have enough lamport to be rent
exempted and fails the transaction. 
Example: 
```
[2024-01-09T20:45:22.340224015Z DEBUG solana_metrics::metrics] CounterPoint { name: "rent_paying_err-new_account", count: 0, timestamp: SystemTime { tv_sec: 1704833122, tv_nsec: 340211290 } }
[2024-01-09T20:45:22.340219646Z DEBUG solana_runtime::accounts::account_rent_state] Account …
```

Fix program buffer account rent-exempt lamport calculation

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock

Either this one or #34716
Close #34716
---
v1.16.26 publish failed:
I think `cargo publish` ignores `Cargo.lock`. (I tried to use a local vendor as well but no luck 😢 )
pin ahash to 0.8.4

v1.16: pin ahash to 0.8.4

---

.github/workflows/downstream-project-anchor.yml
.github/workflows/downstream-project-spl.yml

we don't need to run the previous build if a new commit lands.
get `downstream-project-spl.yml` and `downstream-project-anchor.yml` cancel the previous build when a new commit lands.

ci: cancel the previous build when a new commit lands

---

core/src/consensus.rs
core/src/replay_stage.rs

State machine is only notified of duplicate confirmed rollup when optimistically confirmed
Make the check granular, notify when >52% 
dedup requests against duplicate confirmed slots already sent to the fsm
Fixes #

fix duplicate confirmed rollup detection for descendants

---

CHANGELOG.md
cli/src/program.rs
cli/tests/program.rs
docs/src/cli/examples/deploy-a-program.md

The default behavior for program deployments uses 2x the length of the deployed program. This behavior accommodated larger program deployments over time, but requires a greater upfront cost. With `solana program extend`, however, there's no need to lock up more SOL than necessary for a program.
Use the program length when deploying instead of 2x, and update the documentation to reflect that change, including how to extend a program.
There might be some overlap of changes by including the `extend` documentation, so let me know if you prefer that in a separate PR!
Fixes #

cli: Use program length for deployments instead of 2x length

---

ledger-tool/src/blockstore.rs
ledger-tool/src/main.rs

`solana-ledger-tool` is a bit of a kitchen sink, and has upwards of 30 commands at the top level (ie 30 commands that can be invoked via `solana-ledger-tool <SOME_COMMAND>`). UI Aside, the contents of `ledger-tool/src/main.rs` are somewhat cluttered.
To reduce the clutter, this PR:
- Introduces a new blockstore subcommand, and moves all commands that only operate on the blockstore to this new subcommand.
- As an example, `solana-ledger-tool slot` is now `solana-ledger-tool blockstore slot`
- Supports the old command style (`solana-ledger-tool slot`), but does not display those commands in the top level `--help` command.
- This steers new users towards using new calling format while avoiding breaking the old calling format for people who have muscle memory with those commands
With this PR, …

ledger-tool: Move blockstore commands to blockstore subcommand

---

scripts/check-dev-context-only-utils.sh

dcou needs some bruteforce compilation for every crates to circumvent cargo's feature unification for its intended functioning. so, it's slow. and people (including me) are starting to be frustrated about it.
use recent rust's parallelization for front-end. this is especially effective, because the dcou check only doesn't care about generating binaries.
https://blog.rust-lang.org/2023/11/09/parallel-rustc.html
before (taken from https://github.com/solana-labs/solana/pull/34732):
buildkite/solana/checks2 Passed (7 minutes) 
buildkite/solana/checks3 Passed (14 minutes, 50 seconds) 
after:
buildkite/solana/checks2 Passed (5 minutes, 55 seconds) 
buildkite/solana/checks3 Passed (10 minutes, 52 seconds) 
related: #32169

Make check{2,3} faster by enabling parallel rustc for dcou

---

ledger-tool/src/bigtable.rs
rpc/src/rpc.rs
rpc/src/rpc_service.rs
storage-bigtable/proto/google.api.rs
storage-bigtable/proto/google.bigtable.v2.rs
storage-bigtable/proto/google.rpc.rs
storage-bigtable/src/bigtable.rs
storage-bigtable/src/lib.rs
validator/src/bin/solana-test-validator.rs
validator/src/cli.rs
validator/src/main.rs

Blocks with rewards are not returning from bigtable on v1.17+. This is because we bumped tonic (https://github.com/solana-labs/solana/pull/32994), which now [limits the size of decoded messages to 4MB by default](https://github.com/hyperium/tonic/pull/1335).
There is a Grpc client method to customize this limit, but since we didn't regenerate the google/bigtable protobuf files, current code doesn't support that method.
Regenerate the google/bigtable proto files, which includes the Grpc client and new method
Add our own default max_message_size value of 64MB (currently, the first block of an epoch is ~30MB encoded)
Add solana-validator CLI arg to allow tuning max_message_size

Bigtable: update google proto files and allow configuration of max_message_size

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml
sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml

```
$ glol -2
44a4117ea5 2024-01-10 22:53:46 -0600  (HEAD -> version_bump_v1.16.28, origin/version_bump_v1.16.28)  will.hickey@solana.com Revert hashbrown version change
8fa19e9c2a 2024-01-10 22:45:44 -0600   will.hickey@solana.com Update version to v1.16.28
$ git diff v1.16..HEAD | grep -vE "^ |^@@ |^--- |^\+\+\+ |^index |^diff |^-( \")?solana.*1.16.27|^\+( \")?solana.*1.16.28|^-version|^\+version"
$
```

Version bump v1.16.28

---

.github/workflows/cargo.yml
.mergify.yml

if we can cover the expense, the larger runner can save us more time!
use larger runner for macos stable clippy

ci: use larger runner for macos stable clippy

---

streamer/src/nonblocking/quic.rs
streamer/src/quic.rs

The limit for staked connection streams doesn't use current load. If the load is less, more streams can be allowed to the connections.
- Add support for computing load using EMA
- Update limit calculation logic to use the load
- Add/update unit tests.
Fixes #

Use EMA to compute QUIC streamer load for staked connections

---

runtime/src/bank.rs
runtime/src/epoch_rewards_hasher.rs

Partitioned rewards code requires exposing the parent bank's hash to clients trying to find stake rewards, because that is the seed used for the partition hasher: https://github.com/solana-labs/solana/blob/166be2995ee76e51a343f04e41d348cfeb1cc8d9/runtime/src/bank.rs#L2360
The EpochRewardsHasher calls this the `parent_block_hash` https://github.com/solana-labs/solana/blob/166be2995ee76e51a343f04e41d348cfeb1cc8d9/runtime/src/epoch_rewards_hasher.rs#L45, so it's unclear which hash was intended.
Either way, it will certainly be easier for clients if we use the blockhash, since this is already stored in block metadata (and can be easily looked up).
Update `Bank::calculate_rewards_for_partitioning()` to pass the parent blockhash to `EpochRewardsHasher::calculate_rewards_for_partitioning()`

Use parent blockhash to seed EpochRewardsHasher

---

ledger-tool/src/args.rs
ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
ledger-tool/src/program.rs

The code to parse `ProcessOptions` is repeated in several places. The repetition adds clutter and makes it easier to "miss a spot" if adding a new flag that should be available for all commands. Granted, there are a handful of flags that are not available on all commands, but I plan to tackle that to some extent in a follow-up PR
Introduce a function that parses all of the `ProcessOptions` related arguments, and use that helper across all of the subcommands that process blocks.
There are some changes to default behavior with this PR; however, I think the changes are justified:
- `run_verification` ==> Default value changes from `false` to `true` for all commands that previously had `false` hard-coded. My opinion is that this is fine as we're making the replay more rigorous; if there is …

ledger-tool: Condense ProcessOptions parsing logic

---

streamer/src/nonblocking/mod.rs
streamer/src/nonblocking/quic.rs
streamer/src/nonblocking/stream_throttle.rs

The `quic.rs` file is getting bloated, and some code could be moved out.
Move stream throttling related code to `stream_throttle.rs`.
Fixes #

Move EMA and stream throttling code to a new file

---

programs/zk-token-proof/src/lib.rs

The `VerifyBatchRangeProofU256` instruction allows users to create a "batched" range proof on a sequence of commitments. The individual bit-lengths of the encoded values in these commitments must some up to 256. 
Technically this allows a user to create a range proof of a single 256-bit committed value. This is theoretically fine, but since elliptic curve group is defined over a 256-bit prime number, it could lead to some unexpected consequences/security issues in the future. It would be good to restrict the individual bit-lengths in the batched range proof to be at most 128.
Since `VerifyBatchRangeProofU256` is technically only required for transfer with fee, include the instruction as part of the transfer with fee feature gate.
Fixes #

[zk-token-proof] include `VerifyBatchRangeProofU256` in the `enable_zk_transfer_with_fee` feature gate

---

core/src/banking_stage/consumer.rs
core/src/banking_stage/unprocessed_transaction_storage.rs
runtime/src/accounts/mod.rs

- Expired, already processed, and transactions that cannot pay fees can still take locks.
- Check these conditions before taking locks
- No significant affect on max or avg TPS in bench-tps
- The account loading will bring the fee-paying account into cache (if not already there), which will typically make the subsequent load during actual processing faster  
I made a patched bench-tps to spam 60% invalid fee-paying txs. Saw degraded perf on master, much better perf with this change:
```
master: max= 9744, avg=1714
thispr: max=20065, avg=9018
```
bench-tps patch/hack: [invalid-transfer-generation.patch](https://github.com/solana-labs/solana/files/13891624/invalid-transfer-generation.patch)
Blocked by #34652 
Fixes #

earlier fee payer validation

---

core/benches/consumer.rs

Comment https://github.com/solana-labs/solana/pull/34717#discussion_r1448378961 for similar benchmark of the block-validation execution path. Bench results of different batch sizes are directly comparable if we always execute the same number of txs per bench iteration.
Run same number of txs per bench iteration in consumer benchmarks.
before
```
running 6 tests
test bench_process_and_record_transactions_full_batch                        ... bench:     940,906 ns/iter (+/- 150,107)
test bench_process_and_record_transactions_full_batch_disable_tx_cost_update ... bench:     954,505 ns/iter (+/- 148,716)
test bench_process_and_record_transactions_half_batch                        ... bench:     486,423 ns/iter (+/- 95,842)
test bench_process_and_record_transactions_half_batch_disable_tx_cost_u …
```

consumer bench same number of txs per iteration

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

- Invalid fee-paying transactions can get inserted into the graph, and take up place in batches which can delay valid transactions.
- Verify fee-payer validity before inserting into the graph (similar to #34666 for legacy)
Blocked by #34652
Fixes #

TransactionScheduler: Add funded check before graph insertion

---

program-runtime/src/invoke_context.rs
program-test/src/lib.rs
programs/bpf_loader/src/lib.rs
programs/loader-v4/src/lib.rs
programs/sbf/tests/programs.rs
programs/zk-token-proof/src/lib.rs
runtime/src/bank/tests.rs

feature `8pgXCMNXC8qyEFypuwpXyRxLXZdpM4Qo72gJ6k87A6wL - Native program should consume compute units` #30620 has been activated everywhere
- remove feature checking code
Fixes #

cleanup feature code after activation

---

programs/zk-token-proof-tests/tests/process_transaction.rs
programs/zk-token-proof/src/lib.rs
sdk/src/feature_set.rs
zk-token-sdk/src/zk_token_proof_instruction.rs

Some of the proofs in the zk-token-proof program is too large to fit in a single transaction.
Update the proof program so that users can provide the zkp as either part of the instruction data or as an account data.
still TODO:
Fixes #

[zk-token-proof] Add functionality to read proof from accounts instead of instruction data

---

cost-model/src/cost_tracker.rs

After #34688, `CostTracker.account_data_size_limit` becomes obsolete.
- remove obsolete field
Fixes #

removed obsolete field from cost_tracker

---

ledger/benches/blockstore_processor.rs

- We have a benchmark for the equivalent processing path for block-production, but it doesn't exist on the block-verification side 
- Add a benchmark for `execute_batch` with varying batch size: 1, 32, 64
```
test bench_execute_batch_full_batch                        ... bench:     740,785 ns/iter (+/- 28,929)
test bench_execute_batch_full_batch_disable_tx_cost_update ... bench:     739,307 ns/iter (+/- 43,300)
test bench_execute_batch_half_batch                        ... bench:     410,188 ns/iter (+/- 13,334)
test bench_execute_batch_half_batch_disable_tx_cost_update ... bench:     407,061 ns/iter (+/- 11,797)
test bench_execute_batch_unbatched                         ... bench:      20,892 ns/iter (+/- 573)
test bench_execute_batch_unbatched_disable_tx_cost_update  ... bench: …
```

Add benchmark for execute_batch

---

multinode-demo/bench-tps.sh
net/net.sh
net/remote/remote-client.sh

After adding throttling to streamer bench-tps shows ~50tps. To fix this we use staked connection.
The same as https://github.com/solana-labs/solana/pull/34749

use staked connection for bench-tps in net scripts

---

programs/zk-token-proof-tests/tests/process_transaction.rs

It seems like with https://github.com/solana-labs/solana/pull/34695, the zk-token-proof program tests fail due to compute budget.
Increase the compute budget for zk-token-proof tests.
Fixes #

[zk-token-proof] Increase compute budget for zk-token-proof tests

---

quic-client/src/lib.rs
streamer/src/nonblocking/quic.rs
streamer/src/nonblocking/stream_throttle.rs

The usage of `ConnectionPeerType` to determine if a connection is staked is incorrect. The `peer_type` is an attribute of the `connection_table` where a QUIC connection gets stored. We maintain two tables, one for staked connections, and the other for unstaked connections. But if the staked connection is full, the new connections get stored in the unstaked connection table, even if the peer is a staked client. So `ConnectionPeerType` can incorrectly mark a staked connection as unstaked.
Peer's stake correctly identifies if the connection is from a staked client or not. 
Update code to use peer's stake to determine if the connection is from a staked client.
Remove `ConnectionPeerType` and its usage.
Fixes #

Fix determination of staked QUIC connections

---

programs/sbf/c/src/invoked/invoked.c
programs/sbf/c/src/read_program/read_program.c
programs/sbf/rust/invoked/src/processor.rs
programs/sbf/tests/programs.rs
runtime/src/loader_utils.rs

Follow up https://github.com/solana-labs/solana/pull/34194
Update programs/sbf/tests/programs.rs to use bpf_loader v3.
Fixes #

Upgrade sbf tests to use bpf loader v3

---

runtime/src/loader_utils.rs

In https://github.com/solana-labs/solana/pull/34722, we are using the wrong metadata size (i.e. program metadata) for program buffer account rent-exempt lamport calculation, i.e. 45bytes vs 37btes. 
Fix the wrong metadata size by using the correct size_of_buffer fn.
Fixes #

fix buffer size for updateable program buffer rent exempt fee calculation

---

.github/workflows/release-artifacts.yml

the latest openssl (3.2.0) broke Windows builds:
https://github.com/solana-labs/solana/actions/runs/7537712991/job/20517067308
use 3.1.1 (the previous version) for Windows builds.

ci: use openssl 3.1.1 for Windows build

---

accounts-db/src/tiered_storage/meta.rs

Before we have fully switched to the new way to determine whether
an account is executable, we still need a bit for th executable flag at
this moment in the TieredStorage as well as for backward compatibility
in case we want to revert it back.
This PR adds the executable flag into AccountMetaFlags.
Updated existing tests for AccountMetaFlags to cover executable flag.

[TieredStorage] Include executable field into AccountMetaFlags

---

ledger/src/shred/merkle.rs

Working towards chained Merkle shreds variant.
In preparation of adding chained Merkle shreds variant, the commit reworks api for proof-offset within the shred binary.

adds get_proof_offset for Merkle shreds

---

Cargo.lock
programs/sbf/Cargo.lock

The `h2` crate has a security advisory[^1]:
```
+ cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2023-0001 --ignore RUSTSEC-2022-0093
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 589 security advisories (from /usr/local/cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (798 crate dependencies)
Crate:     h2
Version:   0.3.18
Title:     Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:      2024-01-17
ID:        RUSTSEC-2024-0003
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0003
Solution:  Upgrade to ^0.3.24 OR >=0.4.2
Dependency tree:
h2 0.3.18
```
[^1]: https://rustsec.org/advisories/RUSTSEC-2024-0003
I ran `cargo update h2 --workspace` to update h2

deps: Upgrades h2 due to security advisory

---

sdk/src/signer/keypair.rs

no bounds check on candidate by array in `Keypair::from_bytes()`
h/t: certik
add one

sdk: add bounds check when instantiating `Keypair` from byte array

---

sdk/program/src/message/versions/mod.rs

Versioned message deserialization is broken when using `serde_json` because serde_json expects the versioned message visitor to handle a u64 rather than a u8.
- Update the message prefix visitor to implement `visit_u64` instead of `visit_u8`
- Add tests
Fixes https://github.com/solana-labs/solana/issues/34608

Fix versioned message json deserialization

---

Cargo.lock
programs/sbf/Cargo.lock

https://github.com/solana-labs/solana/pull/34816 for v1.17

v1.17: Bump h2 to v0.3.24

---

zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u128.rs
zk-token-sdk/src/instruction/batched_range_proof/batched_range_proof_u256.rs
zk-token-sdk/src/instruction/batched_range_proof/mod.rs

The problem is shared with https://github.com/solana-labs/solana/pull/34747.
Restrict the bit-length in a 256-bit range proof to 128.
This is a follow-up to https://github.com/solana-labs/solana/pull/34747. Since this part of the logic is gated, it does not need to be backported.
Fixes #

[zk-token-sdk] Restrict a single-bit of 256-bit batched range proof to 128

---

ledger/src/blockstore.rs

The log statement is currently a bit misleading, and could be interpretted as saying this routine deleted a shred.
Adjust the log statement to state that this routine is looking for the shred but couldn't find it. Also, elevate the log to error level as inconsistent state across columns should not be happening.
I updated from `warn` to `error` for visibility altho this function can technically handle the shred being absent.

blockstore: Adjust the error message for missing shreds

---

runtime/src/accounts/mod.rs
runtime/src/bank/tests.rs

`simplify_writable_program_account_check` is active on all clusters now. The code can be cleaned up.
Code cleanup.
Fixes #

Cleanup after simplify_writable_program_account_check feature activation

---

runtime/src/snapshot_bank_utils.rs

A test expects zero transaction fee, without explicit about it.
- explicitly sets fee rate to zero for test
Fixes #

be explicit of test expects zero transaction fee

---

core/src/admin_rpc_post_init.rs
core/src/repair/repair_service.rs
core/src/tvu.rs
core/src/validator.rs
validator/src/admin_rpc_service.rs
validator/src/cli.rs
validator/src/main.rs

This builds off of #34771. The repair-shred-from-peer command currently requires a valid peer pubkey to be provided as input and a valid repair socket to exist in cluster info. In the event no pubkey or an invalid pubkey is provided, it would be nice to log this and then sample a random set of validators instead. The idea here is that one of the validators should possess 
1. Make pubkey input optional
2. When pubkey is not present or no socket can be acquired, sample a random set of 10 validators that are likely to have the slot we're trying to repair (based on LowestSlot data in Gossip)
For testing, spun up a node on testnet and tried issuing this command with the following pubkey inputs:
* valid pubkey `9YVpEeZf8uBoUtzCFC6SSFDDqPt16uKFubNhLvGxeUDy` <-- we requested repair from only this …

Sample peers if input peer missing for repair shred

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs

- scheduler controller tests are spawning separate thread for controller. these threads sleep while waiting for packets, and thus can cause flakiness in these tests if the OS does not wake them up fast enough
- Have tests directly call receive, then schedule 
- This is a better alternative to #34834 
Fixes #

Refactor: SchedulerController tests call receive then schedule

---

programs/bpf_loader/src/syscalls/logging.rs
programs/bpf_loader/src/syscalls/mod.rs

Cleanup - feature gate of `stop_truncating_strings_in_syscalls`

---

stake-accounts/src/stake_accounts.rs

Stake-accounts tests don't handle transaction fee. 
- explicitly sets fee rate to zero.
Fixes #

explicitly sets fee rate to zero for stake-accounts tests

---

runtime/src/accounts/mod.rs

FeeStructure used in tests should be initialized with intended `lamports_per_signature`.  Using `FeeStructure::default()` only works if `lamports_per_signature == 0 or 5_000`.
- Initialize FeeStructure with intended lamports_per_signature for tests
Fixes #

use intended lamports_per_signature for fee_structure

---

accounts-db/src/hardened_unpack.rs
core/src/validator.rs
ledger-tool/src/ledger_utils.rs
local-cluster/tests/local_cluster.rs

Currently, the function `open_genesis_config()` performs several operations that could fail, and unwraps / exits immediately.
Bubble the error up to allow the caller to decide what to do with the result. `solana-validator` and `solana-ledger-tool` will essentially have unchanged behavior as they both exit if this result is bad. But, this change removes one more place that could kill the process

Bubble up genesis load errors instead of exiting

---

docs/publish-docs.sh
docs/src/operations/setup-a-validator.md

The sanity CI check on the docs is failing due to extra white spaces.
- removed dangling white spaces from `publish-docs.sh`
- ran the prettier config on the `setup-a-validator.md` doc

[docs] CI white spaces

---

cli/tests/nonce.rs
cli/tests/stake.rs
cli/tests/transfer.rs

TestValidator can be created with custom specified target_lamportds_per_signature
```
pub fn with_custom_fees(
mint_address: Pubkey,
target_lamports_per_signature: u64,
faucet_addr: Option<SocketAddr>,
socket_addr_space: SocketAddrSpace,
) -> Self 
```
Cli tests uses `with_custom_fees()` but with `target_lamports_per_signature == 1`. This works accidentally because `calculate_fee()` currently uses fee_structure's default `lamports_per_signature` so long fee_rate_governor.lamport_per_signature <> 0.
`Calculate_fee()` is going to change (eg. be corrected). But in any case, cli tests should use correct value in setting up TestValidator.
- setting up TestValidator with correct target_lamports_per_signature
Fixes #

harden cli tests

---

clap-v3-utils/src/keypair.rs

Due to the differences in the way `value_of` and `is_present` functions behave in clap-v2 and clap-v3, the `try_` versions of different key parsers were added in https://github.com/solana-labs/solana/pull/33184. However, that PR missed a point in the logic in `signer_from_path_with_config` where `pubkeys_sigs_of` is still used instead of `try_pubkeys_sigs_of`. The panicking behavior of `pubkeys_sigs_of` when called on a non pre-specified argument, it is blocking the token-cli from being upgraded to clap-v3.
I replaced the `pubkeys_sigs_of` with `try_pubkeys_sigs_of` when parsing `SignerSourceKind::Pubkey`. 
Technically, to be consistent with the rest of the module, we should call `try_pubkeys_sigs_of(matches, SIGNER_ARG.name)?`. However, this changes the behavior of the function. In …

[clap-v3-utils] Replace `pubkeys_sigs_of` with `try_pubkeys_sigs_of`

---

ledger/src/shred.rs
ledger/src/shred/common.rs
ledger/src/shred/merkle.rs
ledger/src/shred/shred_data.rs
ledger/src/shred/stats.rs
ledger/src/shredder.rs
ledger/src/sigverify_shreds.rs

Harden shreds spec.
With the new variants, each Merkle shred will also include the Merkle
root of the previous erasure batch.
```diff
- For easier review, I have removed all the plumbing from this commit.
- The commit only includes the changes to shred struct and the code to generate
- and recover shreds.
- The rest would be done in separate commits.
```

adds chained merkle shreds variant

---

ci/publish-crate.sh

- we don't raise errors when publishing crates
- we try to verify a crate even if it fails to publish
- the verification seems a little bit cumbersome
a related convo: https://discord.com/channels/428295358100013066/560503042458517505/1196572613523279942
1. return an error when the crate fails to publish
=> sometimes we receive reports about missing crates. I think we can detect these issues earlier and take appropriate actions (like re-publish or move to next tag)
2. use the check which is already in `cargo publish` instead of crate test
=> I guess we use crate-test for ensuring the successful publishing of the next crate 🤔 maybe we can just retry `cargo publish`. this command will tell us if anything goes wrong. (like dependences are not ready or building error)
these are big changes to …

ci: publish crates directly

---

cost-model/src/cost_model.rs
sdk/program/src/message/sanitized.rs
sdk/src/feature_set.rs

Implementation of #34819
- Some write-locks are demoted to read-locks during transaction sanitization
- Change the cost model to apply write lock costs for the number of requested write locks, instead of the number of write-locks after demotion
- Requires feature-gate so that activation of 2ry7ygxiYURULZCrypHhveanvP5tzZ4toRwVp89oCNSj (
https://github.com/solana-labs/solana/issues/29595) will not cause this change to break consensus
Fixes #

Feature Impl: cost model uses number of requested write locks

---

runtime/src/snapshot_utils.rs

We're trying to remove the `fs-err` crate. For more information, please refer to https://github.com/solana-labs/solana/pull/34838.
Some uses of fs-err in `snapshot_utils.rs` can easily be replaced with their `std::fs` counterparts.
Replace 'em, and add the path info the error log.

Replaces fs-err in snapshot_utils fns

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/transaction_state.rs
core/src/banking_stage/transaction_scheduler/transaction_state_container.rs

- We currently do not track the TransactionCost in the TransactionState (currently holds some meta), but only the requested_cus.
- For simple txs, such as transfers, the requested CUs **massively** over-estimates the CUs as they count towards limits - this has made throttling the scheduler unreliable for such txs.
- Allow TransactionState to calculate and cache TransactionCost
This will allow 2 subsequent improvements:
1. Scheduler can more reliably throttle number of CUs sent for execution
2. Scheduler can prioritize by reward / cost
Fixes #

TransactionState: add TransactionCost

---

ledger/src/blockstore.rs
ledger/src/blockstore_meta.rs

Move the method whose sole input is a `SlotMeta` to be a method of the `SlotMeta` object

blockstore: Make is_orphan() a method of SlotMeta

---

runtime/src/bank.rs
sdk/program/src/epoch_rewards_partition_data.rs

If the epoch-rewards partition data accounts are owned by the Stake program, parsers try to deserialize them as StakeState variants. This feels icky.
Use the sysvar program id to own these PDAs
Also, remove storage of HasherKind to save 4 bytes and provide mapping fn instead.

Define epoch-rewards partition data program id

---

core/src/banking_stage/transaction_scheduler/transaction_state_container.rs

- functions are unused
- tests rely on actual value of `priority`
- value of `priority` changing with #34888, which breaks tests of these fns
- remove the unused functions and their tests
Fixes #

remove unused functions

---

runtime/src/snapshot_utils.rs

We're trying to remove the `fs-err` crate. For more information, please refer to https://github.com/solana-labs/solana/pull/34838.
`snapshot_utils::purge_bank_snapshot()` still uses fs-err, but doesn't need to.
Replace fs-err with std::fs

Replaces fs-err in purge_bank_snapshot()

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
sdk/src/fee.rs

`congestion_multiplier` variable in `sdk::fee_structure::calculate_fee(...)` does not have to do with congestion, it actually zeros out transaction fee for tests that don't handle transaction fees - those tests sets fee rate to zero in genesis config.
It is better to sync up fee_structure with fee_rate_governor during bank initialization to support those tests.
- set fee_structure.lamports_per_signature by fee_rate_governor during bank initialization
- remove `congestion_multiplier` in calculation_fee()
Fixes #

Remove congestion multiplier from calculate fee

---

core/src/validator.rs
ledger-tool/src/ledger_utils.rs
runtime/src/snapshot_utils.rs

We're trying to remove the `fs-err` crate. For more information, please refer to https://github.com/solana-labs/solana/pull/34838.
`snapshot_utils::clean_orphaned_account_snapshot_dirs()` still uses fs-err, but doesn't need to.
Replace fs-err with std::fs

Replaces fs-err in clean_orphaned_account_snapshot_dirs()

---

CHANGELOG.md

It's time to branch v1.18 off of master and advance the master version number to 2.0. This resets the changelog in preparation.

Update changelog in preparation for creating new  v1.18 branch

---

runtime/src/bank.rs

#34862 attempted to change the program-owner of the epoch rewards partition-data PDAs. However, the runtime constructs the account manually, so the owner needs to be updated there too.
Fix owner assignment
Sorry, dumb bug

Fix epoch rewards partition-data program owner

---

Cargo.lock
accounts-db/Cargo.toml
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/owners.rs
programs/sbf/Cargo.lock
programs/sbf/Cargo.toml

To write the owners-block, it requires an in-memory struct that maintains
a set of unique owner addresses while providing a look-up function to
obtain the OwnerOffset with the specified owner address. 
This PR adds OwnersTable, the in-memory struct that maintains
a set of unique owner addresses while providing a look-up function to
obtain the OwnerOffset with the specified owner address.
A new unit-test is added.

[TieredStorage] In-memory struct for writing OwnersBlock

---

streamer/src/nonblocking/quic.rs

A low staked peer may not be able to open any QUIC streams.
Allow a minimum number of QUIC streams for a staked connection.
Fixes #

Allow some minimum number of streams for a staked connection - v1.17

---

Cargo.lock
Cargo.toml
programs/sbf/Cargo.lock
unified-scheduler-logic/Cargo.toml
unified-scheduler-logic/src/lib.rs
unified-scheduler-pool/Cargo.toml
unified-scheduler-pool/src/lib.rs

(no need to start to review this at weekend).
There's no threading support in the unified scheduler, which will exhibit an extremely minimized overhead for unbatched processing.
Add minimum threading model and wire it, which still lacks suspending (and resuming) threads and aborting them on transaction error in dead blocks. Also, current impl is still full of `.unwrap()`s.
also, note that the actual scheduling code will come in later prs. after that, the code in this pr is ready for multi threaded with proper scheduling code. yet, it's still single threaded at the time of this pr. all this breakdowns are done for bite-sized pr reviewing.
Also, patching crossbeam is planned but yet not included in this pr as well.

Introduce primitive threading in unified scheduler

---

account-decoder/src/parse_sysvar.rs

New epoch rewards partition-data sysvars aren't parsed, even though all the other accounts owned by `Sysvar1111111111111111111111111111111111111` are.
Implement parsing
```
$ curl  -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getAccountInfo", "params":["FdAGcHUFksSVgNj5ihPaddMet3cuuFwJsxkG6ZXVA4Ly", {"encoding":"jsonParsed","commitment":"confirmed"}]}' 127.0.0.1:8899 | jq
{
"result": {
"context": {
"apiVersion": "1.18.0",
"slot": 831
},
"value": {
"data": {
"parsed": {
"info": {
"numPartitions": 18,
"parentBlockhash": "8m6GQ3auZGBMKsqcShxSqzUhuUpATJmXbbn3FqKYFdQp",
"version": 0
},
"type": "epochRewardsPartitionData"
},
"program": "sysvar",
"space": 44
},
"executable": false,
"lamports": 1197120,
"owner": …
```

Support json parsing of epoch-rewards partition data sysvar accounts

---

zk-token-sdk/src/errors.rs
zk-token-sdk/src/instruction/errors.rs
zk-token-sdk/src/instruction/transfer/mod.rs
zk-token-sdk/src/instruction/transfer/with_fee.rs
zk-token-sdk/src/instruction/transfer/without_fee.rs
zk-token-sdk/src/zk_token_elgamal/ops.rs

The `split_u64`, `combine_lo_hi_u64`, `combine_lo_hi_ciphertexts`, `combine_lo_hi_commitments`, and `combine_lo_hi_openings` functions use unchecked bit shift operations that can cause a panic.
Deprecate these functions and replace them with `try_` versions that return a `Result`.
Fixes #

[zk-token-sdk] Use checked arithmetic when processing transfer amount

---

accounts-db/src/nonce_info.rs
rpc/src/transaction_status_service.rs
runtime/src/accounts/mod.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs

This is in preparation for further refactoring of
Bank::load_and_execute_transactions in a separate commit. #34893

Refactor load_accounts to take a reference to a slice instead of vec

---

runtime/src/bank.rs

Processing a batch of transactions in bank currently depends on locking the accounts used by the transactions in the batch. This refactoring isolates the locking in a wrapper method, thus preparing for future extraction of the transaction processing code out of bank.
Add an internal method that does the processing of sanitized transaction batch after the accompanying account locking has been performed in the caller to the new internal method.  Temporarily add a new structure to wrap results of transaction batch processing.

Refactor bank's load_and_execute_transaction

---

clap-v3-utils/src/input_parsers/signer.rs
clap-v3-utils/src/input_validators.rs
clap-v3-utils/src/keypair.rs

As described in https://github.com/solana-labs/solana/pull/33478, the `Arg::validator` is deprecated in clap-v3. The approach specified in https://github.com/solana-labs/solana/pull/33478 is to naturally use `SignerSource` as an intermediate type so that applications can call `matches.get_one::<SignerSource>(...)` to idiomatically validate and parse signer source.
A previous PR https://github.com/solana-labs/solana/pull/33802 added a way to flexibly parse `SignerSource`. What we need now is to parse `Signer`, `Keypair`, or `Pubkey` from a source.
- [87f0cb1](https://github.com/solana-labs/solana/pull/34678/commits/87f0cb14119779cd5237892d9abebf369ce0d08e): Added `_from_source` variants of the functions that parse `Signer`, `Keypair`, or `Pubkey` from "path".
- …

[clap-v3-utils] Add functions to parse directly from `SignerSource`

---

CHANGELOG.md
core/src/validator.rs
local-cluster/tests/local_cluster.rs

- New scheduler is on-average performing better than the multi-iterator approach
- Change default block-production method to central-scheduler
- Can be opted out of via `--block-production-method thread-local-multi-iterator
Fixes #

BlockProductionMethod::CentralScheduler as default

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/readable.rs

The implementation of write_accounts() for HotAccountStorage is missing.
It consists of the writing of account blocks, index block, and owners block.
This PR completes part of the HotStorageWriter::write_accounts().
Specifically, it finishes the writing of account blocks and index block.
A new unit-test is added to verify the correctness of the work-in-progress
HotStorageWriter::write_accounts().

[TieredStorage] writing hot account blocks and index blocks

---

core/src/validator.rs
local-cluster/tests/local_cluster.rs

- Some local-cluster tests rely on transaction forwarding by the leaders in order to run in a timely manner: https://discord.com/channels/428295358100013066/560503042458517505/1199965947285487636
- Use the MI method for block-production, which will do forwarding, while proper fixes in the client's used by tests are worked on.
Fixes #

Use ThreadLocalMultiIterator for tests

---

accounts-cluster-bench/src/main.rs

While `solana-accounts-cluster-bench` can be halted early using the `--iterations` arg, if the actual goal is some number of accounts, this requires cumbersome mathing of iterations with the batch size and number of instructions per transaction. It would be nice to have a simple cli argument that halts the client when a limit is reached.
Add `--max-accounts` cli arg and break out of accounts-bench loop when reached. Because of the async nature of the TransactionExecutor, the exact number of accounts that were created may vary from the limit set. If more precision is needed, tune `--iterations` instead.

accounts-cluster-bench: Break early when a max-accounts limit is reached

---

rpc/src/rpc.rs
validator/src/bin/solana-test-validator.rs

Since https://github.com/solana-labs/solana/pull/34624, we can pull the PartitionData PDA to create the hasher to locate specific rewards.
- Add branch for partitioned rewards in `get_inflation_rewards`
- Remove feature deactivation in solana-test-validator

Add rpc support for partitioned rewards

---

cli-output/src/cli_output.rs
cli/src/program.rs
cli/src/program_v4.rs

As outlined in #34830, `solana program deploy` operations do not return a relevant transaction signature, although it might appear temporarily on stderr. It is quite convenient to keep track of the exact transaction in which a program was upgraded in order to better document its evolution and write tools which are compatible with its entire transaction history, even through breaking changes.
- Adds a new optional `transaction` field to the `cli_output::CliProgramId` return struct.
- Patches `program::send_deploy_messages` to return this final transaction signature.
Fixes #34830

Cli: Return final transaction signature in solana program deploy

---

accounts-db/src/tiered_storage/hot.rs

In HotStorageWriter::write_accounts, it skips storing rent-epoch when
the rent-epoch equals Epoch::MAX.  While the value is correct, it is
more suitable to use RENT_EXEMPT_RENT_EPOCH instead as the
goal here is to save bytes for rent-exempt accounts.
Replace Epoch::MAX by RENT_EXEMPT_RENT_EPOCH when checking
whether to skip storing rent-epoch in HotStorageWriter.

[TieredStorage] Use RENT_EXEMPT_RENT_EPOCH in HotStorageWriter

---

ledger-tool/src/main.rs

This argument is a flag and doesn't take a value; however, it had the .value_name() modifier set with "FORMAT". This could be confusing so remove .value_name() and add .takes_value(false).
Here is the only place where this argument is read; note that it checks for presence and not value:
https://github.com/solana-labs/solana/blob/b04765f8b582a3156bf009307708e3c9701cea8d/ledger-tool/src/ledger_utils.rs#L428
Before:
```
--ignore-ulimit-nofile-error <FORMAT>
Allow opening the blockstore to succeed even if the desired open file descriptor limit cannot be configured.
Use with caution as some commands may run fine with a reduced file descriptor limit while others will not
```
After:
```
--ignore-ulimit-nofile-error    Allow opening the blockstore to succeed even if the desired open file …
```

ledger-tool: Minor cleanup on --ignore-ulimit-nofile-error flag

---

ledger-tool/src/main.rs
ledger-tool/src/output.rs
runtime/src/bank.rs

The implementation of the `accounts` subcommand currently streams account information as each account is handled. This prevents memory pressure from collecting all of the information in a `Vec`, and is more efficient by doing the I/O as we go instead of waiting until the end. But, this implementation is a bit cluttered.
This PR does the following:
- Shift the logic for outputting accounts over to `output.rs`
- Add an object `AccountScanner` to handle
- Allows running with `--output json` to output the summary information as well while still being a valid json object
- This is accomplished by putting the list of accounts in an array for `accounts` field, and then adding a `summary` field
This change lays the groundwork for cleanly adding modes where the output is limited to individual …

ledger-tool: Refactor accounts subcommand output code

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/owners.rs

So far the current HotStorageWriter::write_accounts() only writes
accounts blocks and index block.
The PR further writes owners block in HotStorageWriter::write_accounts().
Extended existing test for HotStorageWriter to cover the owners block.

[TieredStorage] Write owners block for HotAccountStorage

---

accounts-db/src/tiered_storage/byte_block.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/meta.rs

Using non-reference type of AccountHash in 
AccountMetaOptionalFields causes an unnecessary copy
as mentioned in https://github.com/solana-labs/solana/issues/34948.
Uses &AccountHash in AccountMetaOptionalFields to
avoid copying.
Existing unit tests.
Fixes https://github.com/solana-labs/solana/issues/34948

[TieredStorage] Avoid AccountHash copy in AccountMetaOptionalFields

---

accounts-db/src/tiered_storage/hot.rs

In HotStorageReader, the account_matches_owners takes
&[&Pubkey] as the address candidates.  However, it should
be &[Pubkey] as defined in the accounts_file API.
Correct HotStorageReader::account_matches_owners() to
take &[Pubkey] instead.
Existing unit-tests

[TieredStorage] Correct the HotStorage API for account_matches_owners

---

runtime/src/bank.rs

A follow up PR from https://github.com/solana-labs/solana/pull/34809
We can run the validator against mainnet with the new partitioned reward code by enabling `--partitioned-epoch-rewards-force-enable-single-slot` CLI argument. 
Recently, my test node running with the above CLI fails on account hash mismatch. It turns out that the mismatch is coming from the new partition reward account introduced at the epoch, i.e. https://github.com/solana-labs/solana/pull/34624.
In https://github.com/solana-labs/solana/pull/34809, we solve this problem by ignoring the PDA accounts for account hash, bank capital and bank hash. This works but it is too *hacky*. And it turns out that keeping the PDA accounts doesn't provide any other benefit to test the related `getInflactionReward` RPC method.
Therefore, …

Skip creating reward partition account for `--partitioned-epoch-rewards-force-enable-single-slot` 

---

accounts-db/src/accounts_db.rs

While looking at https://github.com/solana-labs/solana/pull/34918 and auditing where we clone the Arc from account index, I find that get_append_vec_id does clone the Arc. However, it is not used anywhere.
https://github.com/solana-labs/solana/pull/34918#issuecomment-1908755604
Looks like it is left-over from previous code.
- remove unused get_append_vec_id fn
Fixes #

Remove unused get_append_vec_id function

---

accounts-db/src/transaction_results.rs
core/src/banking_stage/consumer.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/unprocessed_transaction_storage.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/svm/account_loader.rs

The transaction account loading part of SVM related code is dependent on `BlockhashQueue`. Dropping this dependency will help split SVM code from `Bank`.
The `BlockhashQueue` was mainly being used to find `lamports_per_signature` for the transactions. This can be resolved before SVM code gets called.
Fixes #

Remove BlockhashQueue dependency from SVM related code

---

core/src/accounts_hash_verifier.rs
core/src/validator.rs
core/tests/epoch_accounts_hash.rs
core/tests/snapshots.rs
ledger-tool/src/ledger_utils.rs

Follow up from https://github.com/solana-labs/solana/pull/34971, `AccountsHashVerifier::new()` has unused parameters that can be removed.
Remove 'em.

Removes unused parameters from AccountsHashVerifier::new()

---

core/src/shred_fetch_stage.rs
ledger/src/shred.rs
sdk/src/feature_set.rs

During a cluster upgrade when only half of the cluster can ingest the new shred variant, sending shreds of the new variant can cause nodes to diverge.
Added feature to enable chained Merkle shreds explicitly.

adds feature to enable chained Merkle shreds

---

core/benches/shredder.rs
core/src/window_service.rs
gossip/src/duplicate_shred.rs
ledger/src/blockstore.rs
ledger/src/shredder.rs
ledger/src/sigverify_shreds.rs
ledger/tests/shred.rs
local-cluster/tests/local_cluster.rs
turbine/benches/retransmit_stage.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/broadcast_duplicates_run.rs
turbine/src/broadcast_stage/broadcast_fake_shreds_run.rs
turbine/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
turbine/src/broadcast_stage/standard_broadcast_run.rs

Working towards chaining Merkle root of erasure batches.
Added `chained_merkle_root` to shredder arguments

adds chained_merkle_root to shredder arguments

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/svm/mod.rs
runtime/src/svm/transaction_account_state_info.rs

`TransactionAccountStateInfo` is only used by transaction processing code in SVM. It can be moved to the `svm` folder and cleaned up to remove dependency on `Bank`.
Move to svm, and remove `Bank` deps.
Fixes #

SVM: Move `TransactionAccountStateInfo` to svm and decouple from `bank`

---

sdk/program/src/serialize_utils/cursor.rs
sdk/program/src/vote/state/mod.rs
sdk/program/src/vote/state/vote_state_deserialize.rs

originally i wrote the `VoteState` parse to check `is_empty` and skip parsing `prior_voters` if it was empty. later i got rid of this as unnecessary complexity. however it turns out `prior_voters` may be fully half the CU cost of a typical vote account, 7-8k vs 15-16k total
add this logic back in for a 50% efficiency gain if `prior_voters` is empty, which is more likely than not. i wrote this to only operate with the cursor, rather than the raw input bytes, per jons suggestion
also i added bounds checking to the cursor before and after; while writing this, i discovered `Cursor` successfully returns 0 rather than erroring if it runs out of bounds. also i fixed a mistake with the tests where insufficient data was generated, making coverage of the full struct basically nil

solana-program: only decode prior_voters if needed

---

runtime/src/bank.rs
runtime/src/bank/serde_snapshot.rs

We have a bug when reconstruct the `reward_status` on the bank from deserialized field. 
Bank `new_from_field` is not using deserialized epoch reward status from field to reconstruct the bank.
This should have been caught by our tests. But unfortunately, there is a typo in the test, which didn't catch the bug. 
- fix bank new_from_field to reconstruct epoch reward status.
- fix bank serde test assert for epoch reward status
Fixes #

Fix bank new_from_field for epoch reward status

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/readable.rs

TieredStorageReader is a wrapper enum that works for
both Hot and Cold storage readers, but its get_account()
and account_matches_owner() API are missing.
Add get_account() and account_matches_owner() to
TieredStorageReader.
hot.rs offers similar coverage for HotStorageReader.

[TS] Add get_account() and account_matches_owner() to TieredStorageReader

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/svm/account_loader.rs

SVM specific code's dependency on `Bank::should_collect_rent()` can be resolved by looking up `feature_set`. The current dependency is causing unnecessary bindings between bank and SVM.
Update the code to use `feature_set`.
Fixes #

Remove SVM dependency on Bank::should_collect_rent()

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
sdk/src/fee.rs

https://github.com/solana-labs/solana/pull/34865 caused hash mismatch.
revert https://github.com/solana-labs/solana/pull/34865, and two PRs built on top of it: https://github.com/solana-labs/solana/pull/34757 and https://github.com/solana-labs/solana/pull/34970
Fixes #35008

Revert PRs caused hash mismatch

---

ledger-tool/src/main.rs
ledger-tool/src/program.rs

This change makes solana-ledger-tool match solana-validator CLI; the old
flag --snapshot-archive-path is retained as an argument alias and can
still be used for the sake of backwards compatibility.
https://github.com/solana-labs/solana/blob/0dcac3fe7c4832fc6f358f010ddba8a116da70ab/validator/src/cli.rs#L296-L302
Possibly more work to be done to deduplicate the arguments between validator and ledger-tool, but I think that is for another day.

ledger-tool: Change --snapshot-archive-path to --snapshots

---

accounts-db/src/tiered_storage/hot.rs

To allow hot-storage to use HotStorageWriter::write_account() to
implement AccountsFile::append_accounts(), it is required to
provide a Vector of StoredAccountInfo to allow AccountsDB to
properly prepare the entry for each account.
This PR enables HotStorageWriter::write_account() to return
Vec<StoredAccountInfo>.
Extend existing tests for HotStorageWriter to verify the correctness
of the returned Vec<StoredAccountInfo>.

[TieredStorage] Have HotStorageWriter::write_account() return Vec<StoredAccountInfo>

---

sdk/program/src/instruction.rs

The `AbiEnumVisitor` derivation on `InstructionError` blows out the stack space for Solana builds, giving the error:
```
Error: Function _ZN112_$LT$solana_program..instruction..InstructionError$u20$as$u20$solana_frozen_abi..abi_example..AbiEnumVisitor$GT$13visit_for_abi17ha3a75fe06f2a2af4E Stack offset of 4584 exceeded max offset of 4096 by 488 bytes, please minimize large stack variables
```
Since these tests aren't useful for on-chain program builds, and only run with the nightly compiler anyway, don't derive the trait for on-chain programs.
Fixes #35003

sdk: Do not derive AbiEnum on InstructionError for Solana builds

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

Through multiple reworks of the loaded programs cache its statistics have become meaningless nonsense.
- Fixes `hits`, `misses`
- Adds `reloads`, `lost_insertions`
- Removes `prunes_expired`

Fix - LoadedPrograms statistics

---

accounts-db/src/account_storage/meta.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/readable.rs

TieredStorageMeta and TieredStorageReader::get_account API uses
u32 to represent IndexOffset.  However, within the TieredStorage scope,
IndexOffset should be used, it is not until working with AccountsFile API
when u32 representation of offset is needed.
Have TieredStorageMeta and TieredStorageReader to use IndexOffset.
Existing unit-tests.

[TieredStorage] Use IndexOffset in TieredStorageMeta and get_account()

---

program-runtime/src/loaded_programs.rs

https://github.com/solana-labs/solana/pull/34391/files#r1476263596
Shifting the value for more than 63 times can cause an overflow. Add a limit, and a unit test.
Fixes #

Fix: decayed_counter can overflow if shifted more than 63

---

accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/readable.rs

HotStorageReader and TieredStorageReader haven't implemented
accounts() that is required by AcocuntsFile.
This PR implements accounts() for both HotStorageReader
and TieredStorageReader
Extend the existing test to cover accounts().

[TieredStorage] TieredStorageReader:: and HotStorageReader:: accounts()

---

accounts-db/src/append_vec.rs

append_accounts() only appends (len - skip) accounts.
However, AppendVec::append_accounts() reserves `len`
instead of `(len - skip)` for its vectors.
Use (len - skip) as the initial size of the Vectors.

[AppendVec] Use proper Vec initial size in append_accounts()

---

runtime/src/bank.rs
runtime/src/bank/address_lookup_table.rs
runtime/src/bank/sysvar_cache.rs
runtime/src/bank/tests.rs
runtime/src/bank_forks.rs
runtime/src/svm/account_loader.rs

The transaction processing code is intertwined with `Bank`. It'll be easier for SVM implementation if the code could be split into its own struct and impl.
Move necessary code to its own struct. The impl is currently scattered around in `bank.rs` for ease of review. In a follow on PR the code will be moved to its own file, out of `bank.rs`.
Fixes #

SVM: Split transaction processing code into its own struct

---

accounts-db/src/append_vec.rs

I added a check for `STORE_META_OVERHEAD` in #35053, but turns out there already was one down in the tests module. It was pointed out here: https://github.com/solana-labs/solana/pull/35053#issuecomment-1924836417. So now we have two basically identical checks, but only need one.
Remove the test-only check.

Removes redundant check on STORE_META_OVERHEAD

---

runtime/src/bank.rs
runtime/src/bank/tests.rs
runtime/src/svm/account_loader.rs
runtime/src/svm/mod.rs
runtime/src/svm/transaction_processor.rs

The transaction processing code needs to be moved out of `bank.rs` to isolate SVM dependencies.
Moved the code to a new file in `svm/transaction_processor.rs`, and updated the usage and dependencies.
Fixes #

SVM: Move transaction processing code out of `bank.rs`

---

accounts-db/src/accounts_db.rs
accounts-db/src/accounts_index.rs

In shrinking, we use `get()` to find the index entry and update refcount. However, getting account index entry will result in an Arc clone.
Similar to https://github.com/solana-labs/solana/pull/34918
- use `scan` to avoid account's index entry Arc clone in `do_shrink_slot_store`. 
Fixes #

Avoid account index entry Arc clone in shrinking

---

accounts-db/src/tiered_storage.rs
accounts-db/src/tiered_storage/error.rs

While the implementation of hot-storage reader and writer
are mostly done, it is not yet connected to TieredStorage. 
This PR enables hot-storage in TieredStorage::write_accounts().
Completes the existing tests in TieredStorage to directly
write and read from a TieredStorage with the hot storage format.

[TieredStorage] Enable hot-storage in TieredStorage::write_accounts()

---

core/src/banking_stage/unprocessed_transaction_storage.rs

Not sure why I added this metric, it doesn't convey any useful information considering we have `packet_conversion_elapsed`.
Remove it

banking stage: remove spammy packet conversion metric

---

core/src/banking_stage/consumer.rs
core/src/banking_stage/immutable_deserialized_packet.rs
core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/transaction_state.rs
core/src/banking_stage/transaction_scheduler/transaction_state_container.rs
core/src/banking_stage/unprocessed_packet_batches.rs
core/src/banking_stage/unprocessed_transaction_storage.rs
program-runtime/src/prioritization_fee.rs
runtime/src/compute_budget_details.rs
runtime/src/lib.rs
runtime/src/prioritization_fee.rs
runtime/src/prioritization_fee_cache.rs
runtime/src/transaction_priority_details.rs

- Term "priority" is overloaded and used in multiple places to mean different things
- Split out of #34888 to make the overloaded "priority" less overloaded
- Renames `TransactionPriorityDetails` `priority` field to `compute_unit_price`
- Renames `TransactionPriorityDetails` and associated traits to `ComputeBudgetDetails`
Fixes #

Rename priority to compute_unit_price

---

programs/bpf_loader/src/lib.rs
programs/sbf/benches/bpf_loader.rs
programs/sbf/tests/programs.rs
sdk/src/feature_set.rs

Manual backport of one of two features added in #34194.
Feature Gate Issue: #34424

Backport - feature `disable_bpf_loader_instructions` to v1.17

---

programs/bpf_loader/src/lib.rs

Allows restart with code behind feature `disable_bpf_loader_instructions` hard coded activated.
Remove feature gate check introduced in: #35093
Code runs as if feature is activated.
Fixes #

Feature - `disable_bpf_loader_instructions`

---

core/src/consensus.rs
core/src/consensus/tower1_14_11.rs
core/src/consensus/tower1_7_14.rs
core/src/consensus/tower_storage.rs
core/src/replay_stage.rs

Bug in https://github.com/solana-labs/solana/pull/32315 disallows the last vote to be refreshed after a restart.
This was previously allowed before that change.
Distinguish a failed vote vs an uninitialized tower from restart.

replay: votes made before restart are eligible for refresh

---

runtime/src/bank/tests.rs

feature `set_exempt_rent_epoch_max` was activated.
Updating hashes on a test is dangerous. it is easy to miss an unintentional change.
Modify a bank hash test to prepare to remove the code behind the feature change. This way the contents are known and the hashes will match. #35082 will be easier to verify as correct.
Fixes #

update rent epoch max test

---

ledger/src/shred.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/broadcast_fake_shreds_run.rs
turbine/src/broadcast_stage/broadcast_utils.rs

Use chained Merkle shreds in `turbine/src/broadcast_stage/broadcast_fake_shreds_run.rs`.
Chains Merkle shreds in broadcast fake shreds.

chains Merkle shreds in broadcast fake shreds

---

ledger/src/shred.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/broadcast_utils.rs
turbine/src/broadcast_stage/fail_entry_verification_broadcast_run.rs

Chain Merkle shreds in `turbine/src/broadcast_stage/fail_entry_verification_broadcast_run.rs`.
Chained Merkle shreds in fail-entry-verification broadcast.

chains Merkle shreds in fail-entry-verification broadcast

---

keygen/src/keygen.rs

During the `solana-keygen` process, if an user enters mismatching passphrases, then the program simply crashes and doesn't show any intuitive error message to the user. 
Just added `map_err` instead of `unwrap` on `acquire_passphrase_and_message`.
Fixes https://github.com/solana-labs/solana/issues/34811

Show error instead of panic on passphrase mismatch during solana-keygen

---

ledger/src/slot_stats.rs

Put the slot as the first field to make grep'ing for datapoints for a specific slot in logs easier. This does not effect the datapoints submission / presentation in metrics database

Reorder fields in shred_insert_is_full datapoint

---

accounts-db/src/accounts.rs
runtime/src/bank.rs

`Accounts` methods are being passed instance of `RentCollector`, but it's never used. Maybe it can be removed.
Update methods to not take `RentCollector` as an argument.
Fixes #

Remove unnecessary usage of RentCollector

---

local-cluster/tests/local_cluster.rs
turbine/src/broadcast_stage/broadcast_duplicates_run.rs

Testing with legacy shreds is not good.
Use Merkle shreds in broadcast duplicates.

uses Merkle shreds in broadcast duplicates

---

accounts-db/src/rent_debits.rs
accounts-db/src/stake_rewards.rs
core/src/rewards_recorder_service.rs
geyser-plugin-manager/src/block_metadata_notifier.rs
geyser-plugin-manager/src/block_metadata_notifier_interface.rs
runtime/src/bank.rs
runtime/src/bank/fee_distribution.rs
runtime/src/bank/serde_snapshot.rs
sdk/src/lib.rs
sdk/src/reward_info.rs

Move definition of `RewardInfo` struct from accounts-db to solana_sdk. This is an intermediate step for breaking the dependency of SVM on accounts-db. Done in the process of working on #35094.

SVM: Move RewardInfo from accounts-db to Solana SDK

---

turbine/src/broadcast_stage/broadcast_duplicates_run.rs

Use chained Merkle shreds in `turbine/src/broadcast_stage/broadcast_duplicates_run.rs`.
Chains Merkle shreds in broadcast duplicates.

chains Merkle shreds in broadcast duplicates

---

ledger/src/shred/stats.rs
turbine/src/broadcast_stage/broadcast_utils.rs
turbine/src/broadcast_stage/standard_broadcast_run.rs

Roll out chained Merkle shreds
The commit adds `should_chain_merkle_shreds` to incrementally roll out chained Merkle shreds to clusters.

adds rollout path for chained Merkle shreds

---

accounts-db/src/transaction_results.rs
core/src/banking_stage/consumer.rs
runtime/src/bank.rs
svm/src/account_loader.rs
svm/src/transaction_processor.rs

Continue breaking ties between accounts-db and SVM.
Move definition of TransactionCheckResult type from accounts-db create to SVM, fixing up corresponding imports.

SVM: Move TransactionCheckResult definition from accounts-db to SVM

---

ledger-tool/src/main.rs
ledger-tool/src/output.rs
runtime/src/bank.rs

The `accounts` subcommand currently dumps every single account. This is very intensive and overkill for some situations, such as wanting to know the state of a single account.
This change adds two flags to limit the output of the command to either:
- A set of accounts specified by `--account <PUBKEY>`; multiple pubkeys can be passed
- A set of accounts owned by a program account specified by `--program-account <PUBKEY>`
Here is some sample output running with `--output json` (piped through `jq .` to pretty print):
<details>
<summary>--account 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on </summary>
```
{
"accounts": [
{
"pubkey": "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
"account": {
"lamports": 43871930671716,
"data": [
"",
"base64"
],
"owner": "11111111111111111111111111111111", …
```

ledger-tool: Add additional modes for accounts subcommand

---

rust-toolchain.toml

https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html
https://releases.rs/docs/1.76.0/

Upgrades Rust to 1.76.0

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/transaction_state.rs
core/src/banking_stage/transaction_scheduler/transaction_state_container.rs

- selling CUs for non-optimal prices because prioritization does not include the base fees collected
- calculate prioritization as fees / cost instead of purely compute_budget priority
Blocked by #34881 
Fixes #

Scheduler - prioritization fees/cost

---

docs/README.md
docs/crowdin.yml
docs/package-lock.json
docs/package.json
docs/src/index.mdx
docs/src/runtime/zk-token-proof.md

The validator docs translations broke a long time ago. And have not displayed any translated content since.
Note: The docs use the [Crowdin](https://crowdin.com/) platform to facilitate translations
- updated the Crowdin CLI
- updated the `crowdin.yml` configuration file to upload and download the correct doc file to Crowdin
- added the serve command for better local testing of doc builds via docusaurus
- make MDX/JSX imports use the [`@site` alias](https://docusaurus.io/docs/markdown-features/react#importing-components)
- make static pdf files link to the github blob (since building translations fail with relative paths)
- updated the docs readme to include details and common issues with translations

[docs] translation support

---

accounts-db/src/tiered_storage.rs
accounts-db/src/tiered_storage/hot.rs
accounts-db/src/tiered_storage/test_utils.rs

There're some test functions that have been used in different
mod in TieredStorage.  It's better to have one same place for
all tiere-storage related test functions.
Created test_utils.rs under /tiered_storage and move test-related
functions into it.
Existing tests.

[TieredStorage] Put commonly used test functions into test_utils.rs

---

programs/sbf/Cargo.lock

context: https://github.com/solana-labs/solana/pull/35126
bump `toml` for `programs/sbf` from 0.5.8 to 0.5.11 (0.5.11 is the latest version of toml 0.5.x atm)

chore: bump toml for programs/sbf from 0.5.8 to 0.5.11

---

programs/bpf_loader/src/lib.rs

Clean up feature gating for activated `enable_bpf_loader_extend_program_ix` feature
Closes https://github.com/solana-labs/solana/issues/26385

clean feature: enable_bpf_loader_extend_program_ix

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

`LoadedPrograms::replenish()` was originally implemented to support deduplication of loaded entries when threads raced to load their TX batches. Now, with cooperative loading an entry should never be loaded twice.
- Replaces all occurrences of `LoadedPrograms::replenish()` by `LoadedPrograms::assign_program()`.
- Disallows replacement of tombstone, but allows replacement of built-ins

Refactor - `LoadedPrograms::replenish()`

---

program-runtime/src/loaded_programs.rs

`loaded-programs-cache-stats.lost_insertions` is wrongly reporting its value using `insertions`, introduced at https://github.com/solana-labs/solana/pull/35026#discussion_r1488763316.
Use correct `lost_insertions` instead.
Maybe worth to bp to v1.18 and v1.17?

Report lost_insertions metrics correctly

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs

Currently the only thing stopping a tombstone from being unloaded is that it never gets selected as a candidate by `LoadedPrograms::get_flattened_entries()`.
Adds check that prevents anything but loaded programs from being unloaded.

Refactor - Adds check that only loaded programs can be unloaded

---

cli/src/address_lookup_table.rs

`address-lookup-table get` subcommand in solana cli panics if `LOOKUP_TABLE_ADDRESS` argument is not given, yet the argument isn't marked as required.
made it required.
Fixes #

Fix: add missing required attribute to LOOKUP_TABLE_ADDRESS arg for get subcommand

---

programs/bpf_loader/src/lib.rs
programs/sbf/Cargo.toml
programs/sbf/benches/bpf_loader.rs
programs/sbf/tests/programs.rs
runtime/src/bank_client.rs
runtime/src/loader_utils.rs

The feature was forced in v1.17.20 on MNB.
Removes it from master and v1.18 as well to stay in sync.
Feature Gate Issue: #34424

Cleanup - `disable_bpf_loader_instructions`

---

ledger-tool/src/main.rs

As brought up [here](https://github.com/solana-labs/solana/pull/35107#discussion_r1480148907), `solana-ledger-tool create-snapshot` operations that change the capitalization are intended for testing purposes and should be used with caution. The script silently calls `Bank::set_capitalization()` regardless of whether such operations are included. Node operators use this script on restarts on live clusters, like mainnet-beta, so it's worth taking extra care to ensure capitalization changes are intended.
Check capitalization before and after `Bank::set_capitalization()` and emit a warning if the value changes.

ledger-tool: add warn log if capitalization changes during create-snapshot

---

sdk/program/src/alt_bn128/mod.rs

Refactor function names from "convert_edianness_64" and "convert_edianness_128" to "convert_endianness_64" and "convert_endianness_128" respectively, fixing a typo.
None, just typo.
Corrected the function names to accurately reflect their purpose.

fix: correct typo in alt_bn128 function names.

---

metrics/src/datapoint.rs
send-transaction-service/src/send_transaction_service.rs

#35132
- Remove ability to submit fieldless datapoints via macros
- Remove attempts to submit fieldless datapoints via macros
Fixes #35132

Remove ability to submit metrics with no fields

---

ledger/src/blockstore.rs

Mac os creates files with ._ prefix with the tar command, and our genesis checks don't like that.
Set the COPYFILE_DISABLE env variable to disable this behavior.
Fixes #34176

Set COPYFILE_DISABLE for mac os so it doesn't generate ._ files

---

accounts-db/src/tiered_storage.rs

While accounts-db might not invoke appends_account twice
for the same AccountsFile, TieredStorage::write_accounts()
itself isn't thread-safe, and it depends on the above accounts-db
assumption.
This PR makes TieredStorage::write_accounts() thread-safe.
So only the first thread who successfully updates the readonly
flag can proceed and writes the input accounts.  All subsequent
calls to write_accounts() will be no-op and return AttemptToUpdateReadOnly
Error.

[TieredStorage] Make TieredStorage::write_accounts() thread-safe

---

ledger-tool/src/main.rs
validator/src/cli.rs

The help text for `--accounts-index-path` on the validator and ledger-tool is inconsistent with other cli args that default to within the ledger directory.
Related to https://github.com/solana-labs/solana/pull/35254
Make the help text default value consistent.

Makes help's default for `--accounts-index-path` consistent

---

ledger-tool/src/main.rs
validator/src/cli.rs

`--accounts` is not a required argument, so list what the default location is if unspecified. We do this for several others similar arguments.

List the default value for `--accounts` in CLI help

---

scripts/build-downstream-anchor-projects.sh
scripts/patch-crates.sh

The script for building mango and metaplex was outdated.
I updated the script for testing Solana (and the runtime tools) with Mango-v4 and Metaplex. I also included a function for testing it against Openbook-v2.

Update build downstream projects script

---

sdk/src/account.rs

The code comments for `is_builtin` is inaccurate. 
For all valid builtin accounts, the account's data are not empty. 
Vote program actually has 19 bytes data on mainnet/testnet.
Interestingly, vote program has only 12 bytes data on devnet (maybe we should
fix it?).
https://explorer.solana.com/address/Vote111111111111111111111111111111111111111
The extra check for non-empty accounts data is to prevent user from create
empty builtin account.
Update the code comments for `is_buitin`.
Fixes #

update comments for is_builtin

---

core/src/validator.rs

useful to determine whether the shred version cleanup logic in blockstore was performed.

validator: include waited_for_supermajority in startup metric

---

scripts/build-downstream-anchor-projects.sh
scripts/patch-crates.sh

https://github.com/solana-labs/solana/pull/35262 breaks CI; namely:
```
Updating crates.io index
Updating git repository `[https://github.com/openbook-dex/program/`](https://github.com/openbook-dex/program/%60)
error: failed to select a version for the requirement `solana-cli-config = "=1.19.0"`
candidate versions found which didn't match: 1.18.2, 1.18.1, 1.18.0, ...
location searched: crates.io index
required by package `anchor-cli v0.29.0 (/home/runner/work/solana/solana/target/downstream-projects-anchor/anchor/cli)`
perhaps a crate was updated and forgotten to be re-vendored?
```
This reverts commit 40224345765cb6a379a4182ad395582284d6bdd9.
Fixes #

Revert "Update build downstream projects script (#35262)"

---

core/src/replay_stage.rs

We get a read lock twice in immediate succession; only need to grab it once and fetch the two items we want.

Obtain BankForks read lock once to get ancestors and descendants

---

core/src/replay_stage.rs
core/src/tvu.rs
ledger/src/blockstore_cleanup_service.rs

Currently, ReplayStage sends new roots to BlockstoreCleanupService, and
BlockstoreCleanupService decides when to clean based on the advancement
of the latest root. This is totally unnecessary as the latest root is
cached by the Blockstore, and this value can simply be fetched.
- Rip out the channel, and instead query latest root from Blockstore directly
- Eliminate separate thread that was spawned to do the cleanup while the channel was drained
- Remove `latest_root_senders` from `ReplayStage` as the only receiver of these roots was `BlockstoreCleanupService`
Prior to this change, we were sending / receiving up to 150 roots/min (assuming 0% skip rate) across the channel. With the change, we are now reading an atomic every (512 * 0.4 / 10) ~20 seconds instead of using the channel. …

Remove channel that sends roots to BlockstoreCleanupService

---

ci/downstream-projects/func-spl.sh

When running `ci/downstream-projects/func-spl.sh`, the binary for `spl_transfer_hook_example.so` is missing and we get the error:
```
---- test::test_create stdout ----
thread 'test::test_create' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-program-test-1.17.17/src/lib.rs:451:31:
Failed to open "../../../target/deploy/spl_transfer_hook_example.so": No such file or directory (os error 2)
```
I added a command to build the aforementioned binary.

Build transfer hook for downstream project

---

core/src/consensus.rs
core/src/replay_stage.rs

If the identity is changed on the validator using `set-identity` and there is a tower file for new identity, but the data in the file is outdated, then the validator terminates its operation.
Instead of terminating, the data for the tower will be taken from the current state of the cluster.

validator: ignore too old tower error

---

validator/src/admin_rpc_service.rs
validator/src/bin/solana-test-validator.rs
validator/src/bootstrap.rs
validator/src/cli.rs
validator/src/dashboard.rs
validator/src/main.rs

There are a lots of string literals in this directory, including many for CLI help messages. Any of these strings literals that exceed 100 characters prevent `rustfmt` from running properly.
- Temporarily adjust `rustfmt.toml` to add `format_strings = true`
- Run `../cargo nightly fmt` within `/validator` directory
- Revert the change to `rustfmt.toml`
- Manual review / tweaks to the changes made
- The linter tries to fill up the character limit as full as possible. However, some strings are otherwise more readable so adjust those manually / manually revert the strings that were well formatted prior to running the linter

Format the string literals in /validator directory

---

Cargo.lock
core/src/validator.rs
ledger-tool/src/ledger_utils.rs
ledger-tool/src/main.rs
local-cluster/src/validator_configs.rs
programs/sbf/Cargo.lock
unified-scheduler-pool/src/lib.rs
validator/Cargo.toml
validator/src/cli.rs
validator/src/main.rs

There's no way to adjust the number of threads via cli for unified scheduler because it's still single-threaded. However, this won't hold eternally. :)
Provide such a way in advance for upcoming pr, which makes the unified scheduler multi-threaded with actual scheduler logic.
(note: both output is identical)
```
$ SOLANA_NO_HIDDEN_CLI_ARGS="" solana-validator --help
...
--unified-scheduler-handler-threads <COUNT>
Change the number of the unified scheduler's transaction execution threads dedicated to each block,
otherwise calculated as cpu_cores/4 [default: 12]
...
$ SOLANA_NO_HIDDEN_CLI_ARGS="" solana-ledger-tool --help
...
--unified-scheduler-handler-threads <COUNT>
Change the number of the unified scheduler's transaction execution threads dedicated to each block,
otherwise calculated as …
```

Add --unified-scheduler-handler-threads

---

core/src/replay_stage.rs

From https://github.com/solana-labs/solana/pull/35173#discussion_r1485686323 
Return a `Result` and set the `exit` flag if `load_tower` fails.

replay: gracefully exit if tower load fails

---

ledger-tool/src/blockstore.rs
ledger-tool/src/error.rs
ledger-tool/src/main.rs

There are lots of operations that could fail, including lots of the
Blockstore calls. The old code matched on Ok(_) or did unwrap()'s
which clutter the code and increase indentation.
This change wraps the entire command in a function that returns a
Result. The wrapper then does a single unwrap_or_else() and prints
any error message. Everywhere else is now free to use the ? operator

ledger-tool: Use error handling in blockstore command code

---

program-runtime/src/loaded_programs.rs

Only the `executable` might need to be mutable.  This `allow(unused_mut)` is probably a leftover from a previous version.

loaded-programs: Remove unnecessary `allow(unused_mut)`

---

genesis/src/genesis_accounts.rs

There is a list of accounts to be created and included in the MainnetBeta genesis. These accounts also exist in Devnet genesis, but they don't need to exist in Development clusters (especially since nobody has the keys)
Skip adding the accounts for Development clusters

genesis: Skip inserting genesis accounts for Development clusters

---

runtime/src/bank/tests.rs
svm/tests/mod.rs
svm/tests/rent_state.rs

`test_rent_state_list_len` test SVM features but was located in the runtime crate.
Test moved to the SVM crate.

Move `test_rent_state_list_len` to SVM

---

core/src/banking_stage/transaction_scheduler/scheduler_metrics.rs

Another split out of #35087.
- Create inner structs for scheduler counts and timings
- Wrap inner structs with interval-reported structs which impl Deref & DerefMut for easy field access
- These inner structs will be re-used for reporting on slot-level in #35087
Fixes #

scheduler inner metrics

---

runtime/src/bank/tests.rs
svm/src/transaction_processor.rs

The testnet outage 2024/02/21 was caused by a feature activation which affected RBPF and thus changed the program runtime environment. A bug it the program loading caused programs of the new environment after the epoch boundary to be discarded as they had the same effective slot as programs of the old environment before the epoch boundary.
- Limit effective slot to the begin of the current epoch when there is a relevant feature activation.
- Adds `test_feature_activation_loaded_programs_epoch_transition()`.

Fix - program loading with effective slot at epoch boundary

---

ledger-tool/src/program.rs
runtime/src/bank.rs
runtime/src/bank/tests.rs
svm/src/transaction_processor.rs

The adjustments for programs being loaded in the recompilation phase can be done at the caller (`Bank::_new_from_parent()`) and don't need to pollute the callee (`TransactionBatchProcessor::load_program()`).
This PR was split from #35283 which should land first.
Moves the setting of `effective_epoch`, `tx_usage_counter` and `ix_usage_counter` from the callee to the caller.

Refactor - Move recompilation out of program loading

---

CHANGELOG.md

- `central-scheduler` became the default in #34891, which barely missed the cut for 1.18
- Move changelog line to changes for 2.0.0
Fixes #

move changelog note of default central-scheduler

---

accounts-db/src/accounts_db.rs
accounts-db/src/accounts_index.rs

See https://github.com/solana-labs/solana/issues/34786 for background.
We want to limit the use of `ReadAccountMapEntry`, from AccountsIndex, everywhere. Ultimately removing it once there are no more uses.
There are two tests that use `get_for_tests()` that really need the whole index entry in order the check the invariants. To remove ReadAccountMapEntry usage from these tests, we can use the `get_and_then()` family instead. And given the actual implementation, using `get_cloned()` will be more straight forward.
Replaces uses of `get_for_tests()` with `get_cloned()`.

Replaces ReadAccountMapEntry in more tests

---

accounts-db/src/accounts_index.rs

See https://github.com/solana-labs/solana/issues/34786 for background.
We want to limit the use of `ReadAccountMapEntry`, from AccountsIndex, everywhere. Ultimately removing it once there are no more uses.
`get_account_read_entry()` is now only used by `get()`. Removing these functions is the ultimate goal. Removing one at a time makes it easier to see (1) everything is still correct, and (2) future changes only need to look for one fn instead of two.
Remove `get_account_read_entry()` and inline the impl into `get()`.

Removes get_account_read_entry()

---

core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
core/src/banking_stage/transaction_scheduler/scheduler_metrics.rs

While interval-reported metrics show a more complete picture, it is often the first step of debugging to check stats on a non-specific leader. This is not easily done by checking the interval-reported metrics.
Collect and report count/timing metrics for scheduler at leader-slot level.
Fixes #

Scheduler: Leader-Slot metrics for Scheduler

---

Cargo.lock
Cargo.toml
frozen-abi/src/hash.rs
programs/sbf/Cargo.lock
sdk/program/src/keccak.rs
sdk/program/src/message/legacy.rs
sdk/program/src/message/versions/mod.rs

`sha2` and `sha3` crates already moved to `generic-array` 0.14.7, which means that we can safely convert the hash result to a sized array just by calling `finalize().into()`, which doesn't return any errors.

hash: Use `finalize().into()` instead of `try_into()` for hash results

---

ledger/src/shred.rs
ledger/src/shred/common.rs
ledger/src/shred/merkle.rs
ledger/src/shred/shred_data.rs

Working towards adding a new Merkle shred variant with retransmitter's signature.
The commit uses struct instead of tuple for Merkle shreds variant.
This is part of https://github.com/solana-labs/solana/pull/35293 factored out into its own commit.

uses struct instead of tuple for Merkle shreds variant

---

ledger/src/blockstore.rs

Retrieving entries from the Blockstore is a necessary for several uses-cases:
1. Feeding entries to `ReplayStage`
2. Feeding entries to `CompletedDataSetService`
3. Feeding entries to RPC calls such as `getBlock`
While these operations all occur in different threads, the implementation of the `Blockstore` function utilizes a thread-pool to parallelize the operation of fetching / deshreding / deserializing shreds into entries. That thread pool is currently set to scale with the number of cores on the machine. Several problems with this:
- The thread pool is shared between all of these cases, but replay is the most critical and should not be prone to potential jitter/latency as a result of another operation utilizing the thread pool
- The thread pool is very overprovisioned; CPU utilization …

Remove the Blockstore thread pool used for fetching Entries

---

rpc/src/rpc.rs

`getTokenLargestAccounts` collects all data in `Vec` and after that takes only 30 top accounts
use `BinaryHeap` instead of `Vec` and do not keep more than 30 accounts
based on https://github.com/solana-labs/solana/pull/34583
Fixes #

rpc: optimize `getTokenLargestAccounts`

---

rpc/src/rpc_pubsub_service.rs

These threads use the default name (`tokio-runtime-worker`). By not having specific names, it is harder to profile the threads from this service vs. other threads that also use default name
Name the threads in this pool, and also add logs to note that the service has stopped/started. These logs will be useful if we ever need to debug the validator process hanging on teardown.

Name PubSubService tokio threads

---

Cargo.lock
program-runtime/Cargo.toml
program-runtime/src/loaded_programs.rs

- Forbids all program replacements except for reloads and builtins.
- Removes `test_assign_program_tombstones()`
- Adds `test_assign_program_failure()` and `test_assign_program_success()`.

Refactor - `LoadedPrograms::assign_program()`

---

sdk/src/transaction/sanitized.rs
svm/src/account_loader.rs

Private functions in `svm/account_loader.rs` lacked unit tests.
I added tests for them.
PS: Tests for the public functions and for the SVM entry points (file `transfer_processor.rs`) will be in another PR.

Add tests for private functions in `account_loader.rs`

---

bench-tps/src/cli.rs
net/net.sh
net/remote/remote-client.sh

It is time to deprecate and then remove `ThinClient` from `bench-tps`. This is the first PR to simply just change the default `bench-tps` client from `ThinClient` to `TpuClient` 
Change `ThinClient` to `TpuClient`, add flag for running `thin-client` explicitly (will be removed in future), and update `net.sh` scripts to reflect the change.
Fixes #

change default `bench-tps` client to `tpu-client`

---

core/src/repair/repair_generic_traversal.rs
ledger/src/blockstore.rs
ledger/src/shred.rs
ledger/src/shred/merkle.rs
ledger/src/shred/shred_data.rs

Locking down Turbine propagation path.
Added Merkle shred variant with reserved buffer for retransmitter's signature.

adds Merkle shred variant with retransmitter's signature

---

banks-server/src/banks_server.rs
program-runtime/src/message_processor.rs
programs/sbf/tests/programs.rs
rpc/src/rpc.rs
runtime/benches/prioritization_fee_cache.rs
runtime/src/bank/tests.rs
runtime/src/bank_client.rs
runtime/src/compute_budget_details.rs
runtime/src/prioritization_fee_cache.rs
sdk/benches/serialize_instructions.rs
sdk/program/src/message/sanitized.rs
sdk/program/src/sysvar/instructions.rs
sdk/src/nonce_info.rs
svm/src/account_loader.rs
svm/tests/rent_state.rs

`TryFrom` only supports a single argument, but in https://github.com/solana-labs/solana/pull/34901, `SanitizedMessage` will need an additional parameter for reserved account keys.
Rename `SanitizedMessage::try_from` to `try_from_legacy_message`
Note that the only non test/bench uses of the changed method are in banks-server and banks-client
Fixes #

Rename `SanitizedMessage::try_from` to `try_from_legacy_message`

---

core/src/banking_stage/consumer.rs
program-runtime/src/loaded_programs.rs
runtime/src/bank.rs
svm/src/transaction_processor.rs

Forward port of da2078d is missing on master branch.
The code has diverged. So manually imported the commit to master branch.
Fixes #

Add limit to looping in banking-stage

---

ledger/src/leader_schedule.rs
local-cluster/tests/local_cluster.rs

* C can produce blocks before it is initially killed
* This could cause duplicate blocks on C's restart with purge
* This could also cause a block past the fork slot to get OC and repaired by A on restart 
* If A is slower to start than B, B could end up producing blocks in the second cycle of the leader schedule which might chain to C's leader slots / not be purged properly
Use a custom leader schedule such that C never produces blocks after restart and B only produces blocks up until the initial fork
Fixes #29221 #34102 #33669

local-cluster: fix flaky optimistic_confirmation tests

---

ledger-tool/src/main.rs
ledger/src/blockstore_processor.rs
runtime/src/bank/bank_hash_details.rs

This adds:
--record-slots <FILENAME>
Write the slot hashes to this file, optionally with all the acounts
--record-slots-config hash-only|bank
Store the bank (=accounts) json file, or not.
--verify-slots <FILENAME>
Verify slot hashes against this file.
The first case can be used to dump a list of (slot, hash) to a json file
during a replay. The second case can be used to check slot hashes against
previously recorded values.
This is useful for debugging consensus failures, eg:
ledger-tool verify --record-slots good.json --record-slots-config=bank
ledger-tool verify --verify-slots good.json
On a hash mismatch an error will be logged with the expected hash vs the computed hash.
Fixes #

ledger-tool: verify: add --record-slots and --verify-slots

---

cli/src/cli.rs
cli/src/cluster_query.rs
cli/src/nonce.rs
cli/src/program.rs
cli/src/program_v4.rs
cli/src/stake.rs
cli/src/vote.rs
sdk/src/signer/mod.rs
sdk/src/signer/signers.rs
tokens/src/commands.rs

See #34983
- Remove `From` blanket impl for `Signer`
- add `?Sized` trait bound to blanket impl for `Signer` for `Box<dyn Signer>`
- retain `Deref` blanket impl for `Signer`
- refactor `Signers` to blanket impl for all types where their references impls `IntoIterator` yielding `Signer` refs
Fixes #34983
Fixes #13670

SDK: refactor `Signer` and `Signers` traits

---

core/src/replay_stage.rs

The struct to track / report ReplayStage timing information needed some love. I initially only wanted to add `loop_count`, but took the time to clean stuff up a little more.
The motivation to add `loop_count` comes from some recent debugging where `ReplayStage` was slowed down as a result of other effects in the system. We missed this at first, but `loop_count` should be a direct indicator of whether `ReplayStage` is looping at a normal rate. Could be interesting to consider from a perf perspective too; it might be looping slower/faster than the rate at which new changes are coming in.
- Rename `ReplayTiming ==> ReplayLoopTiming` to potentially disambiguate
- Track and report loop count
- Make variable / metric names consistent, they are all now `*_elapsed_us` instead of a mix
- Break …

Cleanup ReplayStage loop timing struct

---

core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
core/src/banking_stage/transaction_scheduler/thread_aware_account_locks.rs

#35368 was reported. The code is fine, but clarifying comments are helpful here.
- Add comment on `ThreadAwareAccountLocks::try_lock_accounts` to clarify it will never call `thread_selector` with a non-empty thread-set.
- Add comment on `PrioGraphScheduler::select_thread` to clarify it will never be called with a non-empty set.
Fixes #35368

Comments clarifying non-emptiness of threadset

---

bench-streamer/src/main.rs
core/src/fetch_stage.rs
core/src/repair/ancestor_hashes_service.rs
core/src/repair/serve_repair_service.rs
core/src/shred_fetch_stage.rs
gossip/src/gossip_service.rs
streamer/src/streamer.rs

The name was previously hard-coded to solReceiver. The use of the same name makes it hard to figure out which thread is which when this code is used for many services (Gossip, Tvu, etc).
Add a thread name parameter, and let the caller choose a meaningful name.

Give streamer::receiver() threads unique names

---

bench-tps/src/cli.rs
bench-tps/src/main.rs
bench-tps/src/perf_utils.rs
bench-tps/tests/bench_tps.rs
client/src/thin_client.rs
net/net.sh
net/remote/remote-client.sh
thin-client/README.md
thin-client/src/thin_client.rs

2nd PR on the way to remove `ThinClient` completely. 
See first PR: [#35335](https://github.com/solana-labs/solana/pull/35335)
It is time to deprecate `ThinClient` as it is rarely used and only sends to one leader. 
- Deprecate `ThinClient`
- Remove `ThinClient` from `bench-tps`
Note: I left in `BenchTpsClient` implementation for `ThinClient` since `dos/` requires `ThinClient` as of now. Next PR will remove the `dos/` `ThinClient` dependency.

Deprecate `ThinClient` and remove `ThinClient` from `bench-tps`

---

runtime/src/bank.rs

`simulate_transaction_unchecked()` does unnecessary `unwrap()`, that can be handled more gracefully.
Replace `unwrap()` with better handling.
Fixes #

Remove unnecessary unwrap from `simulate_transaction_unchecked()`

---

accounts-db/src/tiered_storage/readable.rs

In TieredAccountMeta, RENT_EXEMPT_RENT_EPOCH will be used when
its optional field rent_epoch is None.  However, for legacy reasons, 0
should be used for zero-lamport accounts.
Return 0 for TieredAccountMeta::rent_epoch() for zero-lamport accounts.
accounts_db::tests::test_clean_zero_lamport_and_dead_slot

[TieredStorage] rent_epoch() returns 0 for zero-lamport accounts

---

runtime/src/bank.rs
svm/src/account_loader.rs
svm/src/transaction_processor.rs

In `svm/src/account_loader.rs` `SanitizedTransaction` is passed between functions in many cases, when just a `SanitizedMessage` can work without any loss.
I swapped `SanitizedTransaction` for `SanitizedMessage` in the pertinent locations. One item to be cautious in the review is that I removed one if-condition (see line 131 in `account_loader.rs`) marked as unused, because the message was previously sanitized, so that the check would never evaluate true.

Proposal: Use SanitizedMessage when possible in `svm/account_loader.rs`

---

program-runtime/src/loaded_programs.rs
runtime/src/bank/tests.rs

The test currently does skip most of the epoch so the recompilation phase only starts after the epoch boundary. Also, it does only have a single slot after the epoch boundary which does only select programs for recompilation but never recompiles a selected program, as that would take another slot.
Insert two slots mid epoch to start the recompilation phase and recompile the program, both before the epoch boundary.

Fix - `test_feature_activation_loaded_programs_recompilation_phase()`

---

ledger/src/blockstore.rs
ledger/src/blockstore/blockstore_purge.rs
ledger/src/blockstore_db.rs

clear_unconfirmed_slot can leave blockstore in an irrecoverable state
if it panics in the middle. write batch this function, so that any
errors can be recovered after restart.

blockstore: atomize slot clearing, relax parent slot meta check 

---

.github/workflows/close-new-issues.yml

After we move to anza-xyz/agave we don't want people to create new issues here.
Add a GHA to automatically close new or re-opened issues 
This shouldn't be merged until Saturday.
Tested on my fork and it works:
https://github.com/willhickey/solana/issues/17

Add GHA to close new issues with a comment

---

.github/workflows/close-new-pull-requests.yml

After 2024-03-03T04:00:00Z we don't want any new commits merged to solana-labs/solana. This will ensure that anyone attempting to open a pull request gets redirected to agave.
This PR should be merged *after* the solana -> agave sync (so it isn't synced to agave)
Tested by pushing close-new-pull-requests.yml to willhickey/solana/master and then opening a PR on my fork:
https://github.com/willhickey/solana/pull/19

Add github action to close new pull requests

---

core/src/consensus/heaviest_subtree_fork_choice.rs
core/src/replay_stage.rs
docs/static/katex/katex.js
docs/static/katex/katex.mjs
dos/src/main.rs
download-utils/src/lib.rs
local-cluster/tests/local_cluster.rs
sdk/program/src/secp256k1_recover.rs
sdk/src/secp256k1_instruction.rs
send-transaction-service/src/tpu_info.rs

I completely spaced and merged https://github.com/solana-labs/solana/pull/35434; not realizing that I was operating on the solana-labs repo and NOT agave.
This reverts commit 556a7499487d32359019e1e3f8fd3a28e2033b0b.

Revert "remove repetitive words (#35434)"
