sdk/src/sysvar/slot_hashes.rs, sdk/src/sysvar/stake_history.rs
=> remove hashmap from stake_history

Cargo.lock, core/src/blocktree.rs, metrics/Cargo.toml, metrics/src/counter.rs, metrics/src/datapoint.rs, metrics/src/lib.rs, metrics/src/metrics.rs, upload-perf/src/upload-perf.rs
influx_db_client is high overhead and brings in openssl
=> Use ureq instead of influx_db_client

programs/vote_api/src/vote_state.rs, runtime/src/accounts.rs, runtime/src/bank.rs, sdk/src/sysvar/slot_hashes.rs
Lots of duplicated types
Consolidate into typedefs.
Fixes #
=> More types

core/src/cluster.rs, core/src/lib.rs, local_cluster/src/cluster.rs, local_cluster/src/lib.rs, local_cluster/src/local_cluster.rs, local_cluster/tests/local_cluster.rs
Local cluster does not support exiting and restarting nodes
Refactor `restart_node` to allow this behavior
Fixes #
=> Refactor restart function in local cluster 

cli/src/wallet.rs, programs/budget_api/src/budget_instruction.rs, programs/budget_api/src/budget_processor.rs, programs/budget_api/src/budget_state.rs, programs/stake_api/src/stake_instruction.rs, programs/stake_api/src/stake_state.rs, programs/vote_api/src/vote_instruction.rs, programs/vote_api/src/vote_state.rs, runtime/src/stakes.rs
to support re-delegation of stake, consumers of voter_pubkey need to pass in
an epoch to correctly calculate stake
* add voter_pubkey() to stake
* other junk: move errors to instruction files
Fixes #
=> make voter_pubkey a function of epoch

ci/testnet-deploy.sh, ci/testnet-manager.sh, ci/testnet-sanity.sh, net/net.sh, net/remote/remote-sanity.sh
=> Remove ledger verification, it's racy and essentially globaly disabled already

core/src/replay_stage.rs
=> Add replay-stage-mark_dead_slot datapoint

metrics/src/metrics.rs
Note that Counters remain at debug! to avoid excessive default logging
=> metrics: Data points are now logged according to their level, instead of always debug!

core/src/shred.rs
Current erasure configuration (number of shreds per FEC block) is causing performance limits of the Erasure library. The performance benchmarks show better results if a lower number of shreds per FEC block is used.
Reduced the shred count to 4. Fixed existing tests. Added a new test to check if correct coding shreds are getting generated.
=> Reduce number of shreds per FEC block

programs/vote_api/src/vote_instruction.rs
=> Demote vote-native datapoint from warn to info

crate-features/Cargo.toml, programs/bpf/Cargo.lock, programs/bpf/build.rs, programs/bpf/rust/do.sh
ELF files loaded on chain contain bloat (debug info, symbol table, extra strings)
Get skimpy
Fixes #
=> Strip ELF files

programs/bpf/Cargo.lock, programs/bpf/rust/128bit_dep/src/lib.rs, programs/bpf/rust/many_args_dep/src/lib.rs
https://github.com/solana-labs/solana/issues/4972
Unable to reproduce the issue, closing the issue and removing the workaround
Fixes #4972
=> unable to reproduce linkage issue

core/src/banking_stage.rs, core/src/blocktree_processor.rs, runtime/src/bank.rs, runtime/src/locked_accounts_results.rs
=> refactor: Get transactions from LockedAccountsResults when possible

core/src/broadcast_stage/broadcast_utils.rs, core/src/shred.rs
Erasure config is slightly out of sync with our best known config
Tune erasure to our best known config
=> Change erasure ratio to 0.25 and increase data shreds to 16

sdk/src/inflation.rs
grants no longer inflate
remove grant parameters from inflation
Fixes #
=> remove grants from inflation

core/src/confidence.rs, core/src/consensus.rs, core/src/replay_stage.rs
Confidence components are interspersed through a number of modules
Move confidence components into confidence.rs
Fixes #
=> Refactor confidence from replay stage

book/src/cli.md, book/src/cluster.md, book/src/programs.md, book/src/terminology.md, book/src/transaction-api.md, book/src/transaction.md
Book description of programs suggests the runtime enforces read/write rules using digital signatures. It doesn't. Programs define those rules.
* Clarify runtime vs program rules
* Add a definition for "smart contract"
Fixes #5892
=> Clarify runtime vs program rules

scripts/wallet-sanity.sh
wallet-sanity.sh appears to fail on occasion on the testnet due to lack of error handing in bash, fix by removing the bash
=> Rewrite wallet sanity test to use the ping command

ci/testnet-automation.sh
=> Narrow wildcard matching for solana tarball

programs/budget_api/src/budget_instruction.rs
Not using `pub(crate)`
Delete dead code.
=> Delete dead code

programs/bpf/Cargo.lock, programs/bpf/rust/do.sh
=> Dump debug version of BPF shared object

multinode-demo/setup.sh, net/net.sh, net/remote/remote-client.sh, net/remote/remote-node.sh
=> `net/net.sh start --skip-setup ...` now works again

core/src/banking_stage.rs, core/src/blocktree_processor.rs, runtime/src/bank.rs, runtime/src/lib.rs, runtime/src/transaction_batch.rs
names are wrong for locked_accounts_results
* change to locked_accounts_results to transaction_batch
* drop repeated parameters from process_entries, par_execute_entries
* other nits
Fixes #
=> transaction batch

net/gce.sh, net/scripts/azure-provider.sh, net/scripts/ec2-provider.sh, net/scripts/gce-provider.sh
`cloud_CreateInstances` documentation and usage are out of sync with current interface
Update them
=> net/gce.sh: Sync cloud_CreateInstances docs and usage

runtime/benches/bank.rs
cargo +nightly bench complains
=> add dyn to Fn() in runtime benches

core/src/bank_forks.rs, core/src/snapshot_utils.rs
Need more granular logs for snapshotting time
logging around `add_snapshot()`
Fixes #
=> log snapshot time

programs/btc_spv_api/src/spv_processor.rs, programs/btc_spv_api/src/utils.rs
insufficient tests for variable ints, decode not consistently working correctly
added tests and fix for decode function
Fixes #
=> Btc spv - variable int improvements

scripts/cargo-install-all.sh
The `cuda` feature
Shuffle the pile of hacks around and maybe it'll work this way
=> Properly build solana-validator-cuda

core/src/repair_service.rs, metrics/src/datapoint.rs, metrics/src/metrics.rs
Metrics datapoint logs were ugly and difficult to quickly scan
=> :sparkles: Beautify metrics datapoint logging

book/src/terminology.md
Terminology section is not sorted alphabetically by name
Sorted now.
Fixes #
=> Sort terminology in book

core/src/confidence.rs, core/src/replay_stage.rs, runtime/src/bank.rs
Same problem described in https://github.com/solana-labs/solana/pull/5903
Implementation of https://github.com/solana-labs/solana/pull/5903
Fixes #
=> Confidence implementation

.gitignore, book/build-svg.sh, book/makefile, book/src/img/consensus.svg, book/src/img/data-plane-fanout.svg, book/src/img/data-plane-neighborhood.svg, book/src/img/data-plane-seeding.svg, book/src/img/data-plane.svg, book/src/img/fork-generation.svg, book/src/img/forks-pruned.svg, book/src/img/forks-pruned2.svg, book/src/img/forks.svg, book/src/img/passive-staking-callflow.svg, book/src/img/runtime.svg, book/src/img/sdk-tools.svg, book/src/img/spv-bank-merkle.svg, book/src/img/spv-block-merkle.svg, book/src/img/tpu.svg, book/src/img/tvu.svg, book/src/img/validator-proposal.svg, book/src/img/validator.svg, ci/test-checks.sh
####Problem
For Gitbook to display our diagrams, we need to keep them live in the repo.
Generated latest SVGs, uploaded them.
=> Add SVGs for Gitbook pt 2

ci/publish-tarball.sh
=> Remove the _/deps symlink, just copy instead

Cargo.lock, core/Cargo.toml, core/src/erasure.rs, core/src/shred.rs
We are using a fork of ReedSolomon library, due to perf issues. They have made a new release which should address the perf. We should move to that release.
Upgrade to 4.0 release
Fixes #6018
=> Upgrade to ReedSolomon 4.0 release

Cargo.lock, core/Cargo.toml, core/src/erasure.rs, core/src/shred.rs
Manual cherry-pick of https://github.com/solana-labs/solana/pull/6026
=> [v0.19] Upgrade to ReedSolomon 4.0 release (#6026)

core/Cargo.toml
=> Fix ReedSolomon 4.0 windows build

runtime/src/accounts.rs, runtime/src/message_processor.rs
Cherry pick #5992 from master to v0.19
=> Fix BPF program static linking (#5992)

core/src/cluster_info.rs
Cluster Info has some dead code
Removed it
Fixes #
=> Remove dead code from cluster_info

genesis/src/main.rs
`./net.sh`'s `--internal-nodes-lamports` argument was failing due to this, which is need for the TdS cluster
=> genesis: Support primordial accounts with no data

core/src/shred.rs, core/src/window_service.rs
Test coverage is lacking for `should_retransmit_and_persist`
Added more tests. Also uncommented out some existing tests.
=> Additional tests for should_retransmit_and_persist

core/src/snapshot_package.rs
https://github.com/solana-labs/solana/issues/6001#issuecomment-534677126
Used a fixed name file
=> Fix using temp file for archive

bench-tps/src/main.rs
=> bench-tps: Avoid accidential tx_count mismatches when using an accounts file

ci/test-stable.sh
CI jobs are not running the tests they are supposed to be
Remove local_cluster tests from stable-perf job, remove other tests from local-cluster job
Fixes #
=> Fix CI Jobs

programs/stake_api/src/stake_state.rs
Happened to notice that staker / voter credits were returned out of order while perusing the code
Fix order of credits and add a test
=> Fix staker / voter credit redemption

core/src/blocktree.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
Erasure recovery information is missing in dashboard
Added the counter, and updated dashboard to visualize it
Fixes #
=> Add erasure recovery stats to dashboard

core/src/snapshot_package.rs, core/src/snapshot_utils.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json, runtime/src/accounts_db.rs, runtime/src/append_vec.rs
AccountStorage Serialization is slow
Remove some account storage serialization, make validators reconstruct it
Fixes #
=> Remove some AccountStorage Serialization

runtime/src/accounts_db.rs
Snapshots currently serialize all fork hashes from slot 0 onwards which can be slow as the number of slots grows
Only serialize the latest fork hash
Fixes #
=> Remove serializing all ForkHashes

cli/src/vote.rs, cli/src/wallet.rs
```bash
solana create-vote-account ~/validator-vote-keypair.json ~/validator-keypair.json 1
```
creates a vote account with 1 lamport instead of 1 SOL.
Show stake/vote account command also didn't handle the common `--lamports` arg
=> Enable SOL or lamports for create-vote-account, show-{stake,vote}-account commands

sdk/bpf/scripts/install.sh
=> Cleanup Rust BPF Sysroot

core/tests/fork-selection.rs, local_cluster/src/tests/local_cluster.rs, programs/bpf/Cargo.lock
=> rename locktower to tower

programs/stake_api/src/stake_state.rs, programs/stake_tests/tests/stake_instruction.rs
=> staking rewards reinvestment

cli/src/vote.rs, cli/src/wallet.rs, core/src/confidence.rs, core/src/staking_utils.rs, genesis/src/main.rs, local_cluster/src/local_cluster.rs, programs/stake_api/src/stake_instruction.rs, programs/stake_api/src/stake_state.rs, programs/stake_tests/tests/stake_instruction.rs, programs/vote_api/src/vote_instruction.rs, programs/vote_api/src/vote_state.rs, runtime/src/bank.rs, runtime/src/genesis_utils.rs, runtime/src/stakes.rs
Makes Vote and Stake account format and CLI usage consistent between v0.19 and v0.20
=> Cherry-pick vote and stake authority changes

sdk/bpf/scripts/install.sh
=> Remove libstd statics to eliminate .bss

book/src/cluster/performance-metrics.md
No specific hardware and configuration setup in docs.
Add section in performance metrics.
Fixes #
=> Add specific hardware setup to performance metrics doc.

net/scripts/solana-user-authorized_keys.sh
=> Add sakridge pubkey

book/src/running-validator/validator-info.md
=> doc: update validator-info publish arguments

bench-tps/Cargo.toml, bench-tps/src/bench.rs, ci/test-stable.sh, core/Cargo.toml, genesis_programs/Cargo.toml, genesis_programs/src/lib.rs, local_cluster/Cargo.toml, local_cluster/src/lib.rs, local_cluster/src/tests/bench_tps.rs
Move takes a long time.
Move move into a feature.
This saves about 2 minutes for a clean build running setup.sh:
master: 4m4.437s
move-feature: 5m55.859s
Fixes #
=> Featureize move

book/src/running-validator/validator-info.md
=> Validator-info doc update

book/src/running-validator/validator-info.md
=> Validator-info doc update (#6152)

core/src/shred.rs
Shredding performance is worse when FEC rate is 0. This is counter intuitive.
Rayon work stealing algorithm was causing perf regression when there were no coding shreds to be signed. Added a check to skip signing coding shreds if FEC rate is 0.
=> Don't try signing coding shred if fec rate is 0

cli/src/wallet.rs, client/src/lib.rs, client/src/rpc_client.rs, client/src/rpc_request.rs, core/src/rpc.rs
```
$ solana get-epoch-info
Keypair: /Users/mvines/validator-keypair.json
RPC Endpoint: http://tds.solana.com:8899
Current epoch: 13
Total slots in current epoch: 8192
Remaining slots in current epoch: 995
Time remaining in current epoch: 6.63 minutes
```
=> cli:  Add get-epoch-info command

multinode-demo/delegate-stake.sh
Testnet boot failing on `create-stake-account`
Fixup command in delegate-stake.sh
=> Fixup create-stake-account command

runtime/src/bank.rs, runtime/src/stakes.rs
Need to have access to the current stake accounts of a bank to calculate rewards for TdS while processing the blocktree
Fixes #
=> Expose current stake accounts of a bank for use in cli tooling

runtime/src/bank.rs, runtime/src/stakes.rs
Cherry pick https://github.com/solana-labs/solana/pull/6184 from master to v0.19
=> Expose current stake accounts of banks

cli/src/input_parsers.rs, cli/src/lib.rs, cli/src/wallet.rs, sdk/src/lib.rs, sdk/src/native_token.rs
Need a place to put native token conversion utilities
Moved token conversion utilities from cli into sdk
=> Add native_token module to sdk

metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json, runtime/src/bank.rs
Cannot access the current block height of a bank
=> Rename bank height to block_height and expose method

core/src/repair_service.rs
Unused numbers.
Remove them.
Fixes #
=> Remove dead constants

programs/exchange_api/src/exchange_processor.rs, programs/exchange_api/src/exchange_state.rs
=> fix clippy

client/src/rpc_client.rs, client/src/rpc_client_request.rs, client/src/thin_client.rs, drone/src/drone.rs, drone/src/drone_mock.rs, install/src/command.rs, install/src/update_manifest.rs, programs/config_api/src/config_processor.rs, programs/librapay_api/src/librapay_transaction.rs, programs/storage_api/src/storage_contract.rs, programs/storage_api/src/storage_processor.rs, programs/vote_api/src/vote_instruction.rs
Progress towards #6144 (upgrading to rust 1.38)
=> Clippy work towards rust 1.38

ci/docker-rust-nightly/Dockerfile, ci/rust-version.sh, scripts/coverage.sh
=> Jump to nightly-2019-10-03

core/src/cluster_info.rs
Two or more gossip nodes can find themselves partitioned off from the rest of the cluster when the network link between them and the rest of the cluster goes down for more than 15seconds.
Avoid this by periodically checking whether the gossip entrypoint has disappeared, and if so try to pull from it to re-find everybody else.
Future work: #5438
TODO:
=> gossip: Periodically pull from the entrypoint if it's no longer in Crdt

bench-tps/src/bench.rs, core/src/blocktree.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/cluster_info.rs, core/src/consensus.rs, core/src/repair_service.rs, core/src/replay_stage.rs, core/src/retransmit_stage.rs, core/src/sigverify_stage.rs, metrics/src/datapoint.rs, programs/vote_api/src/vote_instruction.rs, sealevel/src/bank.rs
Too much datapoint logging.
Lower level of some of the most common logs which are already duplicated with another human-readable print anyway.
Fixes #
=> Tweak debug to remove unreadable datapoints

core/src/broadcast_stage/broadcast_utils.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/shred.rs
Hard to visualize breakdown of work in broadcast like shredding, signing, broadcast, etc.
More detailed metrics calculating sum of all the different pieces of work
Fixes #
=> Broadcast Metrics

core/Cargo.toml, core/benches/retransmit_stage.rs, core/src/retransmit_stage.rs
No way to benchmark retransmit stage.
Add a benchmark.
Fixes #
=> Retransmit stage benchmark

net/scripts/colo-provider.sh, net/scripts/colo-utils.sh
Scripts prefer private IPs
Prefer public IPs
=> Colo: Prefer public IPs

core/src/broadcast_stage/broadcast_utils.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/shred.rs
1) Timing metrics for serializing shredding is incomplete
2) No timing metrics for time in receive from banking_stage in broadcast
Fixes #
=> Broadcast/Shredding Metrics

core/src/broadcast_stage/standard_broadcast_run.rs
Stats don't need to be u128 and there was already a struct and function for handling broadcast stats.
Use u64 and combine logic into existing function.
Fixes #
=> Reconsolidate broadcast stats

core/src/blocktree_processor.rs
=> Fix blocktree processor entry callback test

book/src/.gitbook/assets/forks-pruned.svg, book/src/.gitbook/assets/forks.svg, book/src/.gitbook/assets/tpu.svg
SVGs are causing CI check to fail
Rebuild SVGs with `./book/build-svg.sh`
=> Fix book SVGs

net/scripts/colo-provider.sh
I left part of 57916f8 in a stash...
Commit the rest of the patch set.  Unbreak `net/colo.sh create`
=> Colo: Prefer public IPs, part 2

programs/vest_api/src/vest_processor.rs
Vest program assumes the client creates valid transactions. An invalid transaction, such as one that doesn't specify which accounts to load, can cause the on-chain program to panic, which will then kill the validator.
Don't panic.
cc: #6292
=> Plug potential panic in Vest

core/benches/retransmit_stage.rs, core/src/cluster_info.rs, core/src/retransmit_stage.rs, core/src/tvu.rs, core/src/validator.rs, validator/src/lib.rs
retransmit is not fast enough
Split work across multiple threads.
Fixes #
=> Use multiple retransmit threads/sockets

core/benches/poh.rs, core/benches/shredder.rs, core/src/poh.rs, genesis/src/main.rs
No benches for shredding on larger entries to simulate realistic workloads
Integrating @sagar-solana suggestion for bench with larger entries
Fixes #
=> Add benches for shredding and poh

programs/vest_api/src/vest_instruction.rs, programs/vest_api/src/vest_processor.rs
Was 96.8% line coverage. Weak.
More tests.
=> Better Vest code coverage

runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/rent_collector.rs
Reverts solana-labs/solana#6181
=> Revert "collect rent from the accounts"

cli/src/cli.rs, cli/src/cluster_query.rs, client/src/rpc_client.rs, client/src/rpc_request.rs, core/src/rpc.rs, net/remote/remote-sanity.sh
```
$ solana show-validators
Keypair: /Users/mvines/.config/solana/id.json
RPC Endpoint: http://edge.testnet.solana.com:8899
Identity Pubkey                               Vote Pubkey                                    Commission   Last Vote   Root Block  Active Stake
HY6zF16jcrBkQnHLxgbJqTpcgnqrjDrnsis1DnPd5XXZ  GtN8cdrDLhtCHU7Kb5GjaVZzGdCPxo3QetncaBxAbixd        49.8%       23362            -  0.00002469 SOL (25.00%)
9VdE4GbQabpCCuu1pw45yHV1geHdfWb1NRAdmCpz7MCy  3C6sSU9cafD7152zDcTgoTVGD34RVo1EebWY8ANYDcwz        49.8%       23362            -  0.00002469 SOL (25.00%)
6QSR2T9xJANPVatGthvJ4wrQFx9hM16VvpR9Yxr5KNcD  ARJMdX5dsmNgoET4skxN8gShcKbngHfwjAcmErqHLvNX        49.8%       23361            -  0.00002469 SOL (25.00%)
B3C12LVYU4Dz3Jzzhjz27kgZBFu5H4YtLK5woqWvBMPb …
```
=> Add `solana show-validators` command

core/src/confidence.rs
The RPC API returns results based on either the latest bank, or a bank from a couple blocks ago. There is currently no way to determine which bank to query for account state
- Adds ForkConfidenceCache methods to analyze the cache and return the most recent fork that meets the minimum criteria for confirmation depth and stake percentage, if any.
Toward #6346
=> Add methods to get appropriate bank_fork from ForkConfidenceCache based on confirmation depth and stake percentage

core/src/replay_stage.rs, core/src/shred.rs, core/src/streamer.rs
too many messages
Lower datapoint levels.
Fixes #
=> Lower shred/receiver stats

programs/config_api/src/config_processor.rs, programs/config_tests/tests/config_processor.rs
Config program blindly indexes into keyed_accounts. A client can crash the leader by sending it an invalid transaction.
Same fix as in Vest, Stake and System - iterate instead of index.
cc: #6292
=> Fix blind keyed accounts indexing in Config program

core/src/cluster_info.rs
num_nodes datapoint prints too much
Lower to _debug level
Fixes #
=> Lower cluster_info-num_nodes datapoint

programs/librapay_api/src/lib.rs
Librapay ignores the number of tokens to mint
Respect!
Fixes #
=> Create genesis with the requested amount

programs/move_loader_api/src/processor.rs
=> Enforce move loader program account size

core/src/recvmmsg.rs
`test_recv_mmsg_batch_size` is flaky
Fixed the test. Added more iterations to make it more conclusive.
=> Fix flaky test_recv_mmsg_batch_size

runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/rent_collector.rs
This reverts commit c1b401a04ace4d83dee0d10923cae5a9a2d13460.
Commit breaks testnet. 
Note how in the first run the cluster is unable to idle (no confirmation after the initial boot up). 
The other runs are on the tip of master with this commit reverted. 
Revert commit
=> Revert "collect rent from accounts (take:2) (#6360)"

core/src/blocktree.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/replay_stage.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
No metrics about ReplayStage performance exist
Adding metrics surrounding ReplayStage performance
Fixes #
=> ReplayStage metrics

banking_bench/src/main.rs
pthread argument crash in banking_bench sometimes.
call join on banking_stage after dropping channels
Fixes #
=> Close down banking stage in banking_bench

programs/bpf/Cargo.lock, programs/bpf/rust/do.sh
=> BPF script nits

core/src/blocktree.rs, core/src/replay_stage.rs, core/src/shred.rs
`test_dead_fork_blob_deserialize_failure` doesn't test what it's meant to test.
Fix the test, fix the code, and add more checks in shreds.
Fixes #
=> Fix replay stage test

core/src/entry.rs
entry.rs can't escape from the core crate because of circular module dependencies
Remove unused code.
cc: @pgarg66
=> Remove unused code in entry

metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
The dashboard layout for some panels is not streamlined.
Fixed the layout. Also removed some obsoleted graphs
Fixes #
=> Fix metrics dashboard layout

Cargo.lock, Cargo.toml, genesis_programs/Cargo.toml, genesis_programs/src/lib.rs, programs/vest_api/Cargo.toml, programs/vest_program/Cargo.toml, programs/vest_program/src/lib.rs
The plumbing to actually activate the Vest program on testnets was missing.
cc: #6234
=> Add vest program to genesis

core/src/shred.rs
Can't extract shred from core without blocktree, because it depends on blocktree for its error struct.
Give Shredder its own error type. Sadly, no tests needed to be updated with this change.
cc: @pgarg66
=> Don't use BlocktreeError from Shredder

scripts/coverage.sh
Don't care about bencher code coverage
=> Exclude bench-exchange from coverage

core/src/blocktree.rs, core/src/blocktree/db.rs
To update `rocksdb` we need to remove the abstractions built to insert `kvstore`. This includes the `Cursor` struct.
Rip out `Cursor` struct.
Towards #5507
=> Remove the Cursor struct

core/src/snapshot_utils.rs
`snapshot_utils` serializes error messages as strings for no apparent purpose. Maybe these functions used to return `io::Error` and this code wasn't updated?
Don't do that.  See if the change breaks anything.
=> Don't stringify errors in snapshot_utils

genesis/src/main.rs, multinode-demo/delegate-stake.sh, multinode-demo/setup.sh, multinode-demo/validator.sh, run.sh, scripts/wallet-sanity.sh, sdk/src/fee_calculator.rs
The current default baseline cluster signature fee of 42 is not realistic.  Update it
Fixes #5467
=> Adjust default cluster signature fees

scripts/increment-cargo-version.sh
Add increment documentation to the `increment-cargo-version.sh` script
Fixes #
=> Add increment docs infra to increment-cargo-version

core/src/banking_stage.rs, core/src/poh_recorder.rs
Follow up from: https://github.com/solana-labs/solana/pull/6263#pullrequestreview-302664394
=> Rename leader_after_slots to leader_after_n_slots

cli/src/cli.rs
1) Fix confusing balance line
2) **bold**ify
=> cli/: Beautify show-account output

ledger/src/blocktree/db.rs
=> Remove dead code in Rocks wrapper

net/scripts/colo-utils.sh
Colo scripting doesn't propagate errors consistently
Add error propagation
Add I/O validation
Fixes #5872
=> Colo verbosity

ci/nits.sh, net/scripts/colo-utils.sh, netutil/src/lib.rs, runtime/src/bank.rs
=> Ban XXX, TBD, FIXME comments

cli/src/validator_info.rs
```
$ solana validator-info get
Keypair: /Users/mvines/.config/solana/id.json
RPC Endpoint: http://edge.testnet.solana.com:8899
Validator Identity Pubkey: 5UrfkWjA7uBW6WM76xpcsPG82ikP5CqstYmtQxggfKmp
info pubkey: 2cWVywCu7GNXXveMGgzg5yscD33FAq7AVg1yv6A3B3HJ
keybaseUsername: team/solana
name: edge-testnet-solana-com-bootstrap-leader
Validator Identity Pubkey: 8bMiEwHqsWPzvfbehh6ZiFT3StP2QYdJTVArXkj4b6Di
info pubkey: GBEp259u9vLbfbSmo8dWusy47HZgDiULvJoJCM9EkdB3
keybaseUsername: team/solana
name: edge-testnet-solana-com-us-west1-b-fullnode2
Validator Identity Pubkey: EubgaJCxV1tNtv8V8F7td2LQ8f51RH7bFvhrgxKryU67
info pubkey: EQTm1ZcFDKSM2Jq5HPoC2MNytqhHo44GswTEAcDCxNRE
keybaseUsername: team/solana
name: edge-testnet-solana-com-blockstreamer
Validator Identity Pubkey: …
```
=> cli: Beautify `solana validator-info get` output

book/src/getting-started/README.md, book/src/terminology.md, ci/testnet-deploy.sh, ci/testnet-manager.sh, net/common.sh, net/gce.sh, net/net.sh, net/remote/remote-deploy-update.sh, net/remote/remote-node.sh, net/remote/remote-sanity.sh, net/scripts/colo-utils.sh, net/ssh.sh
Fullnode was renamed to validator everywhere but the shell scripts.
Renamed fullnode to validator in the shell scripts.
=> Rename remaining uses of fullnode to validator

ledger/src/blocktree.rs, ledger/src/blocktree/db.rs
Unused code.
Remove it, or mark as allowed (opens #6489)
=> Remove unused re-exports of Rocks wrapper and related dead code

core/src/archiver.rs
Test is flaky on slower hardware.
Increase the timeout so that the network is up when the archiver is asking for its balance.
Fixes #
=> Increase archiver polling timeout

system-test/testnet-performance/upload_results_to_slack.sh
=> Explicitly resolve git commit SHA

ci/testnet-deploy.sh, ci/testnet-manager.sh, net/gce.sh, net/net.sh
Need to be able to start/stop client nodes only for easy TdS TPS ramping
=> net: Add ability to only start/stop client nodes

system-test/testnet-performance/testnet-automation-json-parser.py
=> Do not break build on missing curl results

ledger/src/blocktree.rs, ledger/src/blocktree_db.rs
I can't read the code
clean it up
=> Cleanup blocktree

book/src/api-reference/jsonrpc-api.md
We added a new rpc method, but didn't update documentation to include it.
- Add getEpochSchedule to jsonrpc.md
- Also fix A-Z
fyi: @sunnygleason
=> Add getEpochSchedule to rpc docs

gossip/src/main.rs
It's nice to be able to fetch all the RPC URLs that are visible, `solana-gossip get-rpc-url --all` now does this.
=> Add --all flag to `solana-gossip get-rpc-url`

core/src/cluster_info.rs, core/src/gossip_service.rs, gossip/src/main.rs
Console 1: spy on the full cluster
```
$ solana-gossip spy -n beta.testnet.solana.com:8001 --gossip-port 8001
```
Console 2: spy on the full cluster using the console 1 spy as the entrypoint
```
$ solana-gossip spy -n 127.0.0.1:8001
```
=> solana-gossip spy nodes are now gossip entrypoints

ledger-tool/src/main.rs
It'd be nice to have a way of seeing the lowest and highest slot stored in a ledger.
Ledger commands `list-roots` `prune` do not work.
1 - Added a `bounds` subcommand that prints out the range of slots a ledger contains. Note: Does not account for holes, just lists the lowest and highest slot that blocktree knows about.
2- Fixed incorrect usage of blocktree apis that was breaking functionality. 
```
~/$ solana-ledger-tool -l config/bootstrap-leader/  bounds
Collecting Ledger information...
Ledger contains some data for slots 11 to 200
```
=> Add "bounds" command to ledger-tool and fix broken funtionality

system-test/testnet-performance/testnet-automation.sh
=> Enforce machine type definition on GCE

system-test/testnet-performance/gce-gpu-perf-10-node.yml, system-test/testnet-performance/gce-gpu-perf-25-node.yml
Adding explicit test case definitions for multi node perf tests.
=> Define 10, 25, 50 node testcases

cli/src/stake.rs
Follow up from: https://github.com/solana-labs/solana/pull/6541#discussion_r339153836
=> Return error if stake history deser fails in cli

net/gce.sh, net/net.sh, net/remote/remote-node.sh, net/scripts/install-iftop.sh, scripts/iftop.sh
Need a mechanism to monitor network bandwidth usage, and identify packet drops in a connection (where connection = uniq(Src IP,  Src Port, Dest IP, Dest Port))
Use `iftop` to collect this information
Fixes #
=> Use iftop to collect network bandwidth usage

net/scripts/colo-node-onacquire-sh, net/scripts/colo-node-onfree-sh
Some logical failures can exit without printing
Print a messages wherever we can exit with failure
=> Colo: Don't fail without a message

core/src/lib.rs, core/src/sigverify.rs, core/src/sigverify_shreds.rs, ledger/src/shred.rs
Shreds are verified on the CPU, and there are a lot of shreds.
Verify shreds on the GPU.  TVU stage is in #6563
Fixes #
=> Shred gpu sigverify

run.sh
Localnet is being run in SoftLaunch mode which means some programs are not available and some are only added after certain epochs
Run localnet in development mode
Fixes #6545
=> Run localnet in development mode

core/benches/sigverify_stage.rs, core/src/archiver.rs, core/src/retransmit_stage.rs, core/src/sigverify.rs, core/src/sigverify_shreds.rs, core/src/sigverify_stage.rs, core/src/tpu.rs, core/src/tvu.rs, core/src/validator.rs, core/src/window_service.rs
Missing a TVU Stage for GPU sigverify of shreds
Add the stage.
needs rebase if #6520 is merged first.
Fixes #
=> Shred gpu sigverify stage

Cargo.lock, local_cluster/src/tests/bench_tps.rs, programs/librapay_api/Cargo.toml, programs/librapay_api/src/lib.rs, programs/librapay_api/src/librapay_instruction.rs, programs/librapay_api/src/librapay_transaction.rs, programs/move_loader_api/Cargo.toml, programs/move_loader_api/src/account_state.rs, programs/move_loader_api/src/data_store.rs, programs/move_loader_api/src/error_mappers.rs, programs/move_loader_api/src/processor.rs
We are using an old branch of libra
Switch to the new branch.
Fixes #
=> Update libra to new fork

book/src/cluster/stake-delegation-and-rewards.md, book/src/running-validator/validator-stake.md, programs/bpf/Cargo.lock, programs/stake_api/src/stake_instruction.rs, programs/stake_api/src/stake_state.rs, runtime/src/stakes.rs
=> fix re delegate

ledger/src/blocktree_db.rs
Some small column families are write stalling
Expand column families
Fixes #
=> Test expanding all CF's 

bench-tps/src/cli.rs, bench-tps/src/main.rs
Sometimes you only want to transact with the entrypoint
=> bench-tps: Add --no-multi-client flag

net/gce.sh, net/scripts/install-ag.sh
ag > grep.  First thing I always do on a testnet node is install ag.  Now it'll already be there!
=> net: Install ag on nodes

ledger/src/blocktree.rs
`get_index_meta` won't cache an index meta if the shred gets filtered out. This means if a lot of spam comes in, `get_index_meta` will repeatedly go to disk to get the index meta.
Keep the index meta in the cache until all shreds are done being processed, then filter it out.
Fixes #
=> Rework get_index_meta

core/src/poh_recorder.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
PohRecorder Dashboard and Metrics don't distinguish between record time and record locking time
Update Dashboard and Metrics
Fixes #
=> Fix PohRecorder Metrics

bench-tps/src/bench.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
Bench-tps metrics and dashboard is outdated
Update the metrics and dashboard to reflect the time it takes to perform the various steps in bench-tps.
Fixes #
=> Fix Bench-Tps Metrics

Cargo.lock, keygen/Cargo.toml, keygen/src/keygen.rs
`ChorusM5BVgnAKbg9PF15285LkqeCoZWK2p9s35T7J2A` makes me so jealous
`solana-keygen new --starts-with mvines`, and my search begins!
=> keygen/: Add --starts-with for vanity key grinding

runtime/src/message_processor.rs
Code comment says system program can set the executable bit, but the code doesn't allow that.
Update the comment.
cc: @rob-solana
=> Fix code comment

system-test/testnet-performance/aws-cpu-only-perf-10-node.yml, system-test/testnet-performance/aws-cpu-only-perf-2-node.yml, system-test/testnet-performance/aws-cpu-only-perf-5-node-single-zone.yml, system-test/testnet-performance/aws-cpu-only-perf-5-node.yml, system-test/testnet-performance/testnet-automation.sh
Building out AWS test cases to start supporting multi-cloud automation
=> Implementation of AWS support in automation

ledger/src/leader_schedule_cache.rs, programs/storage_program/tests/storage_processor.rs, sdk/src/clock.rs, sdk/src/sysvar/clock.rs
=> document clock

core/src/validator.rs
Validator binaries built on a machine with AVX support will generate invalid opcodes when run on machines without AVX causing a non-obvious process abort.  Instead detect the mismatch and error cleanly.
=> validator: Fail gracefully if AVX support is missing

cli/src/stake.rs, ledger/src/staking_utils.rs, programs/bpf/rust/sysval/src/lib.rs, programs/stake_api/src/stake_instruction.rs, programs/stake_tests/tests/stake_instruction.rs, programs/storage_api/src/storage_processor.rs, programs/storage_program/tests/storage_processor.rs, programs/vote_api/src/vote_instruction.rs, runtime/src/bank.rs, sdk/src/sysvar/clock.rs, sdk/src/sysvar/epoch_schedule.rs, sdk/src/sysvar/fees.rs, sdk/src/sysvar/mod.rs, sdk/src/sysvar/recent_blockhashes.rs, sdk/src/sysvar/rent.rs, sdk/src/sysvar/rewards.rs, sdk/src/sysvar/slot_hashes.rs, sdk/src/sysvar/stake_history.rs
sysvar replicode
* sysvar trait
* more macro magic
Fixes #6654
=> sysvar trait

core/src/cluster_info.rs
Need a mechanism to identify node ports and their functions to analyze packet drop information.
Updated gossip program to display all ports and their function. Reworked table structure to make it more concise.
This is how the updated table looks like
```
IP Address         | Age     | Node identifier                               | Gossip|  TPU  |TPU_FWD|  TVU  |TVU_FWD| Repair|Storage|  RPC  | PubSub
--------------------+---------+-----------------------------------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------
4.30.5.194      (me)|   622ms | 8eCdkTa8uScZocbi8bhVYc2B3UvfKox5eiiZd2thvNuw  | 8415  | none  | none  | none  | none  | none  | none  | none  | none 
34.69.163.237       |    54ms | EVAd3n5iqZcsXwK76bsNp9eLxyTf35PejpeqHuZ3CndL  | 8001  | 9722 …
```
=> Show all ports for nodes in gossip table

core/src/replay_stage.rs
Too much verify-batch-size.
Lower to debug level.
Fixes #
=> Lower verify-batch-size to debug

core/src/validator.rs, core/tests/bank_forks.rs, ledger-tool/src/main.rs, ledger/src/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/lib.rs
=> Move get_bank_forks() into ledger/ so it's available for use by ledger-tool/

core/src/validator.rs, core/tests/bank_forks.rs, ledger-tool/src/main.rs, ledger/src/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/lib.rs
=> v0.20: Move get_bank_forks() into ledger/ so it's available for use by ledger-tool/

ci/testnet-manager.sh, core/src/validator.rs, ledger-tool/src/main.rs, ledger/src/blocktree_processor.rs, multinode-demo/bootstrap-leader.sh, multinode-demo/validator.sh, net/net.sh, validator/src/main.rs
=> ledger-tool can now load a ledger snapshot

ci/testnet-manager.sh, core/src/validator.rs, ledger-tool/src/main.rs, ledger/src/blocktree_processor.rs, multinode-demo/bootstrap-leader.sh, multinode-demo/validator.sh, net/net.sh, validator/src/main.rs
=> v0.20: ledger-tool can now load a ledger snapshot

Cargo.lock, ledger-tool/Cargo.toml, ledger-tool/src/main.rs
=> ledger-tool: Add --graph-forks option

Cargo.lock, ledger-tool/Cargo.toml, ledger-tool/src/main.rs
=> v0.20: ledger-tool: Add --graph-forks option

core/src/storage_stage.rs
Doing storage work even if there are no proofs generated.
Track if there are proofs collected in the last segment and only do mining if there are some.
Fixes #
=> Calculate proofs collected and don't encrypt if there are none

cli/Cargo.toml, cli/src/cli.rs, cli/src/stake.rs, cli/src/storage.rs, cli/src/vote.rs, multinode-demo/archiver.sh
See #6449 
CLI changes required to make #6449 to work
Fixes #
=> CLI changes required for `to` account signing

net/datacenter-node-install/setup-dc-node-1.sh, net/datacenter-node-install/setup-procfs-knobs.sh
Extra tools that have been requested for install on colo nodes aren't documented or scripted for reinstall
Add their packages to installer scripts
=> Add some addition packages to DC installer scripts

validator/src/main.rs
Some cleanup I just can't say no to
=> validator/: Restructure main() to fully parse cli arguments first

validator/src/main.rs
=> v0.20: validator/: Restructure main() to fully parse cli arguments first

Cargo.lock, genesis/src/main.rs, keygen/src/keygen.rs, multinode-demo/setup.sh, net/remote/remote-node.sh, sdk/src/pubkey.rs
genesis uses keypairs, we generally will not have keypairs
parse pubkeys out of input, which can be either pubkeys or keypairs
Fixes #
=> use pubkeys in genesis

book/src/proposals/snapshot-verification.md
Snapshot verification proposal requires SPV
Propose a new snapshot verification method that doesn't require SPV.
=> Update snapshot verification proposal

validator/src/main.rs
=> validator: Fix windows build

run.sh
Genesis args were changed recently but not changed here
=> Fix genesis arg names in run.sh

book/src/cluster/turbine-block-propagation.md
FEC rate is chosen randomly.
Docs for choosing the FEC rate.
Fixes #
=> Add docs for FEC rate calculation

genesis/src/main.rs, genesis_programs/src/lib.rs, local_cluster/src/local_cluster.rs, runtime/src/bank.rs, sdk/src/inflation.rs
This reverts commit a9c4cd6cbe21eb46a76f9f9ad4fd24599f86d166.
Regression: nodes lose consensus randomly (at the same slot every run)
Revert
=> Revert "Add inflation to epoch phases (#6787)"

net/net.sh
Quotes were not "escaped" and so iftop wasn't being stopped correctly.
Escape the script correctly.
=> Fix iftop not being stopped correctly

genesis/src/main.rs, genesis_programs/src/lib.rs, local_cluster/src/local_cluster.rs, runtime/src/bank.rs, sdk/src/inflation.rs
This reverts commit d89271528edccf949838fe2a7beb4226299b56bf.
This commit does not seem to be causing issues. Looks like I had a bad set of testnet runs that coincided with every time I ran with or without this change.
Unrevert this since its not cause for concern. 
Sorry @jackcmay
=> Revert "Revert "Add inflation to epoch phases (#6787)" (#6802)"

net/.gitignore, net/common.sh
Reverts solana-labs/solana#6794
=> Revert "Clean up net/log symlinks"

runtime/src/native_loader.rs
Already covered by #1314
(removes a todo #6474 )
Fixes #
=> TODO already covered by issue

sdk/bpf/c/bpf.mk
TODO replaced with #6822
Fixes #
=> Replace todo with issue

netutil/src/lib.rs
Code quality Friday!  Add more tests into netutil/, and fix a bug that was discovered as a result.
Are we 80% yet?
=> netutil/: Add more tests

net/scripts/install-earlyoom.sh
=> net: earlyoom now works on reboots

core/src/rpc_pubsub.rs, metrics/src/metrics.rs, net/gce.sh, net/scripts/colo-provider.sh, net/scripts/colo-utils.sh, net/scripts/ec2-provider.sh, sdk/src/fee_calculator.rs
Stale, misleading, unhelpful, and abandoned TODOs
Part of #6474
=> Remove some low-hanging TODOs

cli/src/cli.rs, cli/src/cluster_query.rs, cli/src/stake.rs, cli/src/storage.rs, cli/src/vote.rs, core/src/tvu.rs, ledger/src/blocktree_meta.rs, runtime/src/genesis_utils.rs
=> Remove more stale TODOs

core/src/broadcast_stage/broadcast_fake_blobs_run.rs, core/src/broadcast_stage/standard_broadcast_run.rs
Cherry picking #6831 and https://github.com/solana-labs/solana/pull/6588
=> [V0.20] Cherry pick from master branch

runtime/src/bank.rs, runtime/tests/bank.rs
https://github.com/solana-labs/solana/pull/6013 fixed the race, but was broken again in later changes.
Refix #6003 
Fixes #
=> Fix freeze and register_tick race

ledger-tool/src/main.rs
=> ledger-tool: Add print-genesis-hash command

book/src/SUMMARY.md
=> Update book toc for readonly accounts

core/src/rpc.rs
Requesting an airdrop times out if the max commitment level is used
Increase timeout when max commitment is used
No tests but there is an integration test covering this (it successfully broke) in solana-web3.js
Fixes #
=> Increase timeout when confirming airdrop for max commitment

ledger/src/blocktree.rs
The validators insert coding shreds to blocktree, even if the FEC set is complete, or FEC recovery could be performed using the current data set. Such coding shreds are never used in future. However, this slows down window service due to extra cost of blocktree insert.
Refactored the blocktree code to attempt recovery before inserting coding shreds to the blocktree. The newly received coding shreds that correspond to FEC set that are fully recovered, or already full, are not inserted in the blocktree.
=> Insert coding shreds to blocktree only if needed in future

ledger-tool/src/main.rs
https://github.com/solana-labs/solana/pull/6878 for v0.20
=> v0.20: ledger-tool: print command now supports multiple slots and decodes system/vote instructions

core/src/rpc.rs
`getBlock` RPC method returns transactions as serialized json objects (via default json_rpc serialization), which makes the response unnecessarily long
- Serialize transactions in wire format instead.
=> Serialize transaction in proper wire format instead of json

ledger-tool/src/main.rs
It can be useful to visualize all the votes from each validator sometimes.   However this causes the resulting graph to be very busy and much slower to render, so it's disabled by default.
=> ledger-tool: forks graph can now optionally display all validator votes

ledger-tool/src/main.rs
https://github.com/solana-labs/solana/pull/6885 for v0.20
=> v0.20: ledger-tool: forks graph can now optionally display all validator votes

core/src/validator.rs, sdk/src/genesis_config.rs
=> Don't panic in sdk/ when genesis fails to load

validator/src/main.rs
When a validator starts, it always attempts to fetch the genesis block from the provided entrypoint.  This is convenient in a testnet but unnecessary for a long-running validator on a mainnet and will just slow down a validator restart.
=> validator: Add --no-genesis-fetch flag

system-test/testnet-performance/testnet-automation.sh
Add Pankaj's inter-node packet loss analyzer to the testnet automation framework log.
Fixes #6709
=> Add packet loss analyzer to testnet automation

core/src/commitment.rs, genesis/src/main.rs, programs/stake_api/src/stake_state.rs, runtime/src/genesis_utils.rs, runtime/src/stakes.rs, sdk/src/rent.rs
bootstrap stakes should take into consideration rent exemption
add support for gathering rent exemption into stakes at bootstrap/genesis time
Fixes #
=> add rent reserve for bootstrap stakes

ledger/src/blocktree_processor.rs
A ledger with dead slots in it cannot be loaded at startup if blocktree_processor panics
TODO:
Fixes #5019
=> blocktree_processor: Handle dead slots when loading ledger

ledger-tool/src/main.rs
Annoying:
```
$ solana-ledger-tool verify -l ledger-dir --graph-forks forks.pv
$ dot -tPDF -oforks.pdf forks.pv
```
Better:
```
$  solana-ledger-tool verify -l ledger-dir --graph-forks forks.pdf
```
=> ledger-tool: Automatically run dot to generate PDFs or PNGs

Cargo.lock, programs/storage_api/Cargo.toml, sdk/Cargo.toml
Unused dependencies
Delete them
=> Remove unused dependencies

cli/src/cli.rs, client/src/rpc_client.rs, client/src/rpc_client_request.rs, core/src/archiver.rs, drone/src/drone.rs, install/src/update_manifest.rs, ledger/src/bank_forks.rs, ledger/src/blocktree_processor.rs, programs/stake_api/src/stake_instruction.rs, programs/vote_api/src/vote_instruction.rs, runtime/src/bank.rs, runtime/src/bank_client.rs, runtime/src/genesis_utils.rs, runtime/src/status_cache.rs, system-test/testnet-performance/testnet-automation.sh
Removed some stale TODOs and addressed some other TODOs.  
Towards #6474
=> Remove/address some TODOs

system-test/testnet-performance/testnet-automation.sh, system-test/testnet-performance/upload_results_to_slack.sh
We should be passing the variable-expanded last executed command to the results app for faster debugging.
Echo to buildkite and to slack the last known execution stage of the test when it exited the main function.
=> Fix busted failure messaging for slack app uploading

measure/src/measure.rs
Makes it easy to log the duration that Measure measured in duration-appropriate units
=> measure: Implement Display trait

system-test/testnet-performance/testnet-automation.sh
Update the iftop processing command to handle private and public IPs.  
Depends on #6907
=> Update Iftop command in testnet automation

client/src/rpc_client.rs
* previous commits introduced unwraps for common responses 😞 
* don't panic! 😹 
Fixes #6915
=> feat: remove unwraps from client code, fixes #6915

Cargo.lock, Cargo.toml, net-shaper/Cargo.toml, net-shaper/src/main.rs
Need a mechanism to partition the network and induce latencies and packet drops. This will be needed for fork generation and testing.
Added a new utility that uses IP TOS field to partition the network. It uses `tc` to add filters and rules to induce network latencies and packet drops.
=> Tool to partition network and induce packet drops/delays

Cargo.lock, book/src/running-validator/validator-monitor.md, cli/Cargo.toml, cli/src/cli.rs, cli/src/cluster_query.rs, client/src/rpc_client.rs, client/src/rpc_request.rs, core/src/rpc.rs, net/remote/remote-node.sh
https://github.com/solana-labs/solana/pull/6922 for the v0.20 branch
=> v0.20: cli: Add validator catchup command

ledger/src/shred.rs
Shred counters cover a big chunk of time.
Split up the timings to see where time is spent.
Fixes #
=> More granular timings in shred generation

runtime/src/bank.rs
=> bank.rs: Remove unneeded prepare_batch() frozen bank assert

net/scripts/azure-provider.sh, system-test/testnet-performance/azure-cpu-only-perf-5-node.yml, system-test/testnet-performance/testnet-automation.sh
The Azure provider functions got bit rot from us only using GCE.  We might need them some day.
Implement an Azure based testcase to run on a weekly regression to prevent bitrot of the azure cloud services.
=> Add Azure testnet to automation

core/tests/client.rs, core/tests/rpc.rs
* recent CLI breakage from subtle API changes 💔   (see #6915)
* add tests to cover some edges 💖 
Fixes # N/A
=> feat: add tests for invalid/failure rpc cases

core/Cargo.toml
Extra sha2 dep not used.
Remove it.
Fixes #
=> Remove unused sha2 dep

core/Cargo.toml
pin_memory feature unused.
remove it
Fixes #
=> Remove pinned memory feature

core/src/consensus.rs, core/src/lib.rs, core/src/partition_cfg.rs, core/src/replay_stage.rs, core/src/retransmit_stage.rs, core/src/tvu.rs, core/src/validator.rs, local_cluster/src/cluster_tests.rs, local_cluster/src/tests/local_cluster.rs
Merge #6906 into v0.20
Fixes #
=> Fix rules for fork selection (#6906)

programs/vote_api/src/vote_instruction.rs, programs/vote_api/src/vote_state.rs
A vote withdraw instruction cannot use the authorized_withdrawer (that is signing the transaction) as the withdrawal recipient, because it causes a DuplicateAccountIndex transaction error.
Restructure the vote handling logic to pull out the full set of signers present for an instruction. Then use this set for authorization checks rather than limiting the checked keys to the vote account and the "rest" of the keyed accounts.
Fixes https://github.com/solana-labs/solana/issues/6943
_(Note: I didn't do a full refactor to match stake yet. This change gets us closer though and fixes the withdraw issue)_
=> Allow withdraws to the authorized withdrawer

core/src/replay_stage.rs
No logging to detect when a bank fails threshold
Add logging for a threshold failure
Fixes #
=> Log for threshold failure

validator/src/main.rs
The requirement that the validator's entrypoint run an RPC service is unnecessarily limiting.  If the entrypoint isn't running RPC, the validator can locate an alternative RPC service using gossip instead of outright failing.
Also avoid RPC entirely when `--no-genesis-fetch` is given in conjunction with `--entrypoint`
Fixes #6967
=> validator: Relax requirement that the entrypoint node runs the RPC service

core/src/replay_stage.rs
Confirmation metrics broke in https://github.com/solana-labs/solana/pull/7026
Fix typo!
=> Fix confirmation metrics

net/net.sh
Recent change to `net.sh` missed a rebase and reverted some new features
https://github.com/solana-labs/solana/pull/7002
Fix it
=> Fix missed rebase on net.sh

multinode-demo/validator.sh
A couple validator arg else statements are duplicated in multinode-demo/validator.sh
Confusing
🐃
=> Remove duplicated args

core/src/cluster_info.rs
Gossip tries to discard values that cannot fit in a single transmission.
The logic that does this fails to account for a border condition where a value is small enough by itself but doesn't leave enough room for the "vec" wrapper that needs to go around it. This causes the function to loop for ever
Fixed the check to see if a message can fit in a separate transmission
=> Fix a bug where gossip loops forever while splitting messages

book/src/api-reference/jsonrpc-api.md
New rpc method not documented
Add it to docs
Toward #6867
=> Add getConfirmedBlock to json-rpc docs

genesis/src/main.rs
There doesn't seem to be any good reason for why --bootstrap-storage-pubkey is required, and for SLP1 I don't want to even provide one
=> genesis: --bootstrap-storage-pubkey is now optional

net/gce.sh
When an `*IpList` are empty, the script was trying to access elements with indexes `0` to `-1`
Only print IP table row when ip list for a node type is not empty
Fixes #
=> Fix gce.sh info

core/benches/blocktree.rs, core/src/archiver.rs, core/src/cluster_info.rs, core/src/consensus.rs, core/src/repair_service.rs, ledger/src/blocktree.rs, programs/bpf_loader_api/src/helpers.rs
Noticed a lot of nightly warnings
Fix 'em 
Fixes #
=> Cleanup nightly warnings

ci/test-stable.sh
perf crate not tested in cuda mode
Add perf module to test-stable-perf CI
Fixes #
=> Add perf module to stable-perf CI

sdk/src/signature.rs
=> Fix `solana-keygen new --force ...`

ci/order-crates-for-publishing.py
nit: error output hard to read
print each dep on its own line
Fixes #
=> nit: Circular dependency error is hard to read

book/src/SUMMARY.md, book/src/proposals/durable-tx-nonces.md
There's no proposal in the book for the program-based solution to #1982 
Add one
=> Book: Add proposal for durable transaction nonces

scripts/cargo-install-all.sh
=> Fix publish of move program

metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json, scripts/system-stats.sh
No way to see cluster wide gpu usage
Add average gpu compute and memory usage to metrics
=> Add gpu resource usage tracking

sdk/src/signature.rs
=> keygen: Truncate new keypair files

Cargo.lock, ci/run-sanity.sh, cli/src/cli.rs, cli/src/stake.rs, genesis/Cargo.toml, genesis/src/address_generator.rs, genesis/src/genesis_accounts.rs, genesis/src/main.rs, genesis/src/stakes.rs, genesis/src/unlocks.rs, programs/stake/src/config.rs, programs/stake/src/lib.rs, programs/stake/src/rewards_pools.rs, programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs, programs/storage/src/rewards_pools.rs, runtime/src/bank.rs, sdk/src/epoch_schedule.rs, sdk/src/instruction_processor_utils.rs, sdk/src/timing.rs
genesis stakes are not currently in genesis
add genesis stake placeholders with lockups and dummy keys
Fixes #
=> add genesis stake placeholders

multinode-demo/validator.sh
This is a thing we don't need anymore
=> validator.sh: Remove unused --poll-for-new-genesis-config feature

runtime/src/bank.rs
I found remnants. Just do it. :)
=> Really remove mentions of 'genesis_block'

Cargo.lock, install/Cargo.toml, install/src/command.rs, install/src/config.rs, install/src/update_manifest.rs
=> install: Drop unneeded sha2 dependency

ci/rust-version.sh, scripts/coverage.sh
You know, our environment is important. :) This makes my life easier a bit.
=> Improve coverage.sh's environment awareness

cli/src/stake.rs, ledger/src/staking_utils.rs, local-cluster/src/local_cluster.rs, programs/stake/src/config.rs, programs/stake/src/stake_state.rs, programs/stake_tests/tests/stake_instruction.rs, runtime/src/bank.rs, runtime/src/stakes.rs
keeping track of prior delegates is too expensive for bank.stakes
shrink stake state in bank.stakes
Fixes #
=> shrink stakes

Cargo.lock, ci/run-sanity.sh, cli/src/cli.rs, cli/src/stake.rs, genesis/Cargo.toml, genesis/src/address_generator.rs, genesis/src/genesis_accounts.rs, genesis/src/main.rs, genesis/src/stakes.rs, genesis/src/unlocks.rs, programs/stake/src/config.rs, programs/stake/src/lib.rs, programs/stake/src/rewards_pools.rs, programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs, programs/storage/src/rewards_pools.rs, runtime/src/bank.rs, sdk/src/epoch_schedule.rs
Reverts solana-labs/solana#7109
=> Revert "Revert "add genesis stake placeholders (#6969)""

keygen/src/keygen.rs
There is no convenient way to prevent `solana-keygen new` from writing the keypair to disk, which is desirable in a paper wallet scenario.  The closest we have now is `$ solana-keygen -o - &> /dev/null`
Add a new flag `--no-outfile` to prevent writing the keypair to disk, but still output the pubkey and mnemonic on `stderr`
Depends on #7134
=> keygen: Support not writing keypairs to disk

book/src/running-validator/validator-reqs.md, book/src/running-validator/validator-stake.md, book/src/running-validator/validator-troubleshoot.md
Built validator docs exhibit some weirdnesses around hyperlink formatting and line wrapping in lists, plus some unexpected references to TdS
- Fix those things
=> Further validator doc cleanup

genesis/Cargo.toml, genesis/src/address_generator.rs, genesis/src/genesis_accounts.rs, genesis/src/lib.rs, runtime/src/bank.rs
bank size sometimes grows non-linearly
add an el-cheapo, ignored test to be able to track such
Fixes #
=> track bank size

net-utils/src/lib.rs
Green tests don't matter if they're the wrong tests.  🤕
=> Correctly parse ip echo server response and fix broken test

runtime/src/bank.rs
advice was bad for other than linux
fix advice
Fixes #
=> bank_leak_mac_os

Cargo.lock, core/src/replay_stage.rs, core/src/validator.rs, ledger/src/leader_schedule.rs, ledger/src/leader_schedule_cache.rs, local-cluster/Cargo.toml, local-cluster/src/cluster.rs, local-cluster/src/cluster_tests.rs, local-cluster/src/local_cluster.rs, local-cluster/tests/local_cluster.rs
Local cluster is missing the ability to set up tests for edge cases
1) Add ability to set up a specific leader schedule to test specific scenarios
2) Add ability to kill a partition in local cluster
3) Add test that tests killing a partition when
a) It is the majority partition
b) The rest of the network is locked out on the dead, majority partition
Fixes #7086
=> Support local cluster edge case testing

book/src/paper-wallet/keypair.md
duplicate word
removed
Fixes #
=> Remove duplicate word

book/src/SUMMARY.md
=> Add Paper Wallet Installation page to sidebar (#7242)

genesis/src/genesis_accounts.rs, genesis/src/lib.rs, genesis/src/main.rs, genesis/src/stakes.rs, genesis/src/validators.rs, programs/stake/src/stake_state.rs, programs/vote/src/vote_state.rs
genesis validators aren't yet in the code for genesis
add support for provisioning genesis validators
Fixes #
=> genesis validators

book/src/api-reference/cli.md, book/src/api-reference/jsonrpc-api.md, cli/src/cluster_query.rs, cli/src/vote.rs, multinode-demo/validator.sh, programs/stake/src/stake_state.rs, programs/stake_tests/tests/stake_instruction.rs, programs/vote/src/vote_state.rs
std::u8::MAX has unnecessary resolution and is confusing
use 0-100 instead
Fixes #
=> commission as percent

programs/move_loader/Cargo.lock, runtime/src/native_loader.rs, sdk/src/instruction_processor_utils.rs
Deprecated macro no longer used
Remove it
Fixes #
=> Remove old program declare macro

ci/order-crates-for-publishing.py
=> nit: cleanup order-crates-for-publishing output

genesis/src/address_generator.rs, genesis/src/genesis_accounts.rs, genesis/src/lib.rs, genesis/src/main.rs, genesis/src/stakes.rs, genesis/src/validators.rs, programs/stake/src/stake_state.rs, programs/vote/src/vote_state.rs
* genesis validators
* slp1 nodes get 500SOL
* no commission
Fixes #
=> genesis validators (#7235)

programs/bpf_loader/src/lib.rs
BPF loader will finalize an ELF that it cannot later load
Check the ELF during the finalization step
Fixes #7220
=> Verify BPF ELF during finalize

genesis/src/genesis_accounts.rs
=> genesis: Import validators

runtime/src/bank.rs, sdk/src/rent.rs
Right now, we are not paying collected rent to validators.
paying rent to validator accounts, weighted by stake just before bank freezes.
Remaining:
Fixes #5815
=> Pay rent to validators

genesis/src/genesis_accounts.rs, genesis/src/stakes.rs, genesis/src/unlocks.rs
=> more genesis

keygen/src/keygen.rs
After storing their keypair somewhere safe, at some point someone might want to verify that their keypair is still working and could sign a message. Or double check after they wrote it that they wrote it correctly and can remember the passphrase.
Add a 'verify' command to sign a message with a given keypair and then verify the signature.
Fixes #
=> Add verify of keypair

genesis/src/genesis_accounts.rs
=> Add ChorusOne ValidatorInfo

genesis/src/genesis_accounts.rs
=> Add RockX ValidatorInfo

system-test/testnet-performance/colo-gpu-perf-high-txcount.yml
Sagar wants to try txcount=30000 as a new testcase for the colo GPU nightly.
=> Add higher txcount testcase to Colo nightly

book/src/paper-wallet/README.md, book/src/paper-wallet/usage.md
=> Add docs for using a paper wallet with solana cli (#7311)

keygen/src/keygen.rs
=> Add verify of keypair (#7301)

genesis/src/genesis_accounts.rs
=> v0.21: Add spare validator accounts

book/src/running-validator/validator-software.md, book/src/running-validator/validator-start.md, book/src/running-validator/validator-testnet.md
It should be easy to copy-paste your way through starting a validator using solana docs; it isn't.
Improvements
=> Brush up validator start docs

core/src/replay_stage.rs, core/src/tvu.rs
`ReplayStageConfig` doesn't impl `Default`.
Put some fields of `ReplayStageConfig` back into `ReplayStage::new()` and derive `Default` on `ReplayStageConfig`.
Fixes #
=> Split up ReplayStageConfig to make it derive Default

genesis/src/genesis_accounts.rs
=> Add Forbole ValidatorInfo

cli/src/cluster_query.rs
```
| | |
\ \ \
| | |
```
```
| | |
| | |
| | |
```
Fixes #
=> cli: Adjust show-validators column alignment

genesis/src/main.rs
Freebies: remove unwanted short args; clean up summary output
=> genesis: Add argument to configure the authorized pubkey for the bootstrap leader's stake

genesis/src/genesis_accounts.rs
community pool will fund other things, can't be subject to lockups
unlock community pool immediately
Fixes #
=> no lockups for community

cli/src/cli.rs
=> Remove println in solana balance command

runtime/src/nonce_utils.rs, sdk/src/nonce_instruction.rs, sdk/src/nonce_state.rs
Post-merge review of #7353 raised concerns RE complicating a potential derived address solution and a couple of nits.
I also left some tests in a stash...
Address review, add tests
=> Address post-merge review for #7353

ledger/src/blocktree_processor.rs
blocktree_processor no longer aborts on errors that should just result in a single fork getting marked dead (matching replay)
Fixes #7379
=> blocktree_processor: Continue processing the ledger on InvalidTickCount errors

book/src/paper-wallet/usage.md
=> Fix broken link in paper wallet docs

cli/src/storage.rs, cli/src/vote.rs, genesis/src/main.rs, programs/bpf_loader/src/lib.rs, programs/librapay/src/librapay_transaction.rs, programs/move_loader/src/processor.rs, programs/stake/src/stake_state.rs, programs/vote/src/vote_instruction.rs, runtime/src/bank.rs, runtime/src/storage_utils.rs, sdk/src/nonce_instruction.rs, sdk/src/rent.rs
rent code isn't exercised
turn on rent (1SOL/MByear)
Fixes #
=> turn on rent

core/src/replay_stage.rs
N/A
Adding a test case to simulate minority fork overcommit attack
cc: @carllin @aeyakovenko
=> add unit test for minority fork overcommit attack

core/src/sigverify_stage.rs, core/src/streamer.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json
Sigverify metrics are not comprehensive
Update sigverify metrics
Fixes #
=> Fix sigverify metrics

multinode-demo/validator.sh, net/remote/remote-node.sh
testnet scripts were using a non-default, small stake for bs leader
remove special case, use defaults where possible
Fixes #
=> testnet updates for rent exempt stakes

book/src/running-validator/validator-testnet.md
The book doesn't define each testnet well enough that an application developer, validator, or Solana developer would know which to choose.
* Clarify the scope and target audience for each testnet
=> Add more precision to testnet definitions and expectations

Cargo.lock, Cargo.toml, watchtower/.gitignore, watchtower/Cargo.toml, watchtower/README.md, watchtower/src/main.rs
Need this on v0.21 so I can deploy it to the slp1 infra
=> v0.21: Add solana-watchtower program

ci/publish-tarball.sh, sdk/docker-solana/build.sh
No docker images published for Solana releases (only changes images published)
Publish docker-solana images for Solana releases
Fixes #
=> Publish solana-docker releases

cli/src/vote.rs
stray dbg!
remove stray dbg!()
Fixes #
=> Remove dbg!() from cli

cli/src/cli.rs, cli/src/vote.rs, programs/vote/src/vote_instruction.rs
=> cli: Add vote-update-validator subcommand

core/src/replay_stage.rs
generate_new_bank_forks hold the bank write lock too long blocking other users like sigverify stage
Use a read lock around copying out the frozen banks for computation and creating new banks, then only take the write lock when we need to actually insert the new banks.
Fixes #
=> Optimize bank_forks critical section

ledger/benches/sigverify_shreds.rs
ledger shred sign benches are broken.
fix them.
Fixes #
=> Fix sigverify benches

core/src/rpc.rs
This keeps abandoned vote accounts out of the `solana show-validators` output
=> getVoteAccounts RPC API now excludes listing inactive unstaked accounts as delinquent

programs/bpf/Cargo.lock
ci/test-checks.sh moves bpf's Cargo.lock
update it
Fixes #
=> update bpf Cargo_lock

programs/stake/src/stake_state.rs
Stake.split() doesn't support 100% transfer
add support for 100% split
Fixes #7506
=> Add support for split of 100% of stake

ledger/src/blocktree.rs
**Credit**: found/fixed by @sdhawan
The product is currently not purging ledger storage correctly, it may fail
to purge slots from later column families based on earlier column family
purge results due to short-circuit logic.
* Remove short-curcuit logic: `&& -> &`
Fixes: (partial fix for https://github.com/solana-labs/solana/issues/7499)
We likely need additional fixes to compact storage.
=> Fix/remove short circuit logic in ledger_purge_batch (&& -> &)

net/datacenter-node-install/setup-cuda.sh, net/datacenter-node-install/setup-dc-node-1.sh
Last couple of install/setup requests for colo haven't been documented in installer scripts
Add them
=> Colo - Node install scripts missing latest user requests

ledger-tool/src/main.rs
The product cannot currently analyze storage in rocksdb unless it is a completely valid
ledger w/ genesis, precluding the following important types of storage analysis:
* Benchmark ledgers (which do not include genesis hash/block)
* Older ledgers (due to genesis ABI changes)
* Ledgers where the `genesis.bin` is missing or damaged
This applies to other commands besides `analyze-storage`: before this change, if there is a failure in either blocktree or genesis hash loading, other commands would error (even if the command could otherwise proceed without error).
* Make functions for opening `genesis_hash`, `blocktree`, and `database`
* Modify commands to selectively call these functions as needed
=> Add selective loading of Blocktree, GenesisHash, Database to ledger-tool

core/src/window_service.rs
When window insertion is slow, retransmit is blocked
Move window insertion to separate thread
Fixes #
=> Move window insertion to separate thread

cli/src/cluster_query.rs
`solana show-block-production` takes too long to process a production-sized Epoch.  Take some loops from `O(n^2)` to `O(n)`
=> Speed up show-block-production command

Cargo.lock, book/src/api-reference/cli.md, clap-utils/Cargo.toml, clap-utils/src/input_parsers.rs, cli/src/cli.rs, cli/src/main.rs, cli/src/stake.rs, cli/tests/stake.rs, genesis/Cargo.toml, genesis/src/main.rs, genesis/src/stakes.rs, programs/stake/src/stake_state.rs
stakes also require lockups that are time-based, as provided by genesis
* add unix_timestap to Lockup
* fix consumers of Lockup
* update cli reference
Fixes #
=> Add unix_timestamp to stake lockups

net/remote/remote-node.sh
=> Fix broken internal-nodes-stake-lamports arg in scripts

sdk/benches/slot_hashes.rs, sdk/src/slot_hashes.rs, sdk/src/sysvar/slot_hashes.rs
duplicate const lint
remove duplicate
Fixes #
=> Remove duplicate def of MAX_SLOT_HASHES

book/src/SUMMARY.md, book/src/offline-signing/README.md
CLI's offline signing process isn't documented
Document it
=> Book: Document CLI offline signing

book/src/running-validator/validator-testnet.md
Testnet descriptions to match what's implemented. Edge is gone and Beta follows untagged commits on the release branch.
Update the descriptions.
=> Update testnet descriptions

cli/src/cluster_query.rs, ledger-tool/src/main.rs
++tooling to help debug what's happening at #7587
=> ledger-tool: Add --all option to bounds, to display all non-empty slots

banking-bench/src/main.rs
Hard to compare bench results when modifying thread or tx count parameters.
Report tps instead of total time taken
Fixes #
=> Switch banking bench to report tps instead of total time

runtime/src/accounts.rs
Accounts lock causing high thread contention and slow-ness.
Use the lock for the whole batch instead of per-tx.
Optimize the critical section to pre-generate the key list as
necessary before taking the lock.
This gives around 15-20% improvement in banking-bench with 16 banking threads on 8c,16t xeon v4.
Fixes #
=> Optimize lock_accounts mutex use

ledger/src/blocktree_processor.rs
=> blocktree_processor: Groom log messages

net/net.sh, net/remote/cleanup.sh
Cherry-picking @sakridge 's change to v0.22
https://github.com/solana-labs/solana/pull/7603
=> Move cleanup to a script so it doesn't kill itself (#7603)

genesis/src/genesis_accounts.rs, genesis/src/stakes.rs, genesis/src/validators.rs, runtime/src/bank.rs
sol_to_lamports can induce rounding errors when we're counting every last
lamport for genesis
use lamports in genesis
Fixes #
=> Use lamports in genesis

genesis/src/genesis_accounts.rs, genesis/src/stakes.rs, genesis/src/validators.rs, runtime/src/bank.rs
=> Use lamports in genesis (#7631)

book/src/SUMMARY.md, book/src/api-reference/cli.md, book/src/offline-signing/README.md, book/src/offline-signing/durable-nonce.md
CLI nonce account management isn't documented
Document it
Towards #7444
=> Book: Document CLI durable nonce account management

bench-tps/src/cli.rs, faucet/src/faucet.rs, genesis/src/genesis_accounts.rs, genesis/src/validators.rs, sdk/src/native_token.rs
Knowing what a sol is and what a lamport is does not imply what SOL_LAMPORTS might mean
Rename SOL_LAMPORTS to LAMPORTS_PER_SOL
(Will mirror in https://github.com/solana-labs/solana-web3.js) 
Fixes #7632
=> Make sol-to-lamport const name more clear

programs/stake/src/stake_state.rs, runtime/src/bank.rs, runtime/src/stakes.rs
leftover type from first go at refactoring stakes
remove the type, fix leak test, better assert!() message
Fixes #
=> Delete unused type

book/src/api-reference/cli.md, book/src/offline-signing/durable-nonce.md
CLI subcommands that support durable nonces are undocumented
Bump CLI API docs
Add documentation and example
Fixes #7444
=> Book - Document nonceable CLI subcommands

sdk/bpf/rust/test/src/lib.rs, sdk/src/entrypoint.rs
Nightly clippy requires them
Add something
Fixes #
=> Add safety docs

sdk/src/account.rs, sdk/src/account_info.rs
account_info is missing utility functions that make writing tests easier
- Add some based on `KeyedAccount`
- KeyedAccount name nits
Fixes #
=> account_info utilities

core/tests/ledger_cleanup.rs
test_ledger_cleanup_compaction takes way too long with the default constants
Reduce constants and remove sleeps to reduce test time to ~30s from 2.5m
Fixes #
=> Reduce compaction test constants

net-utils/src/ip_echo_server.rs
testnet.solana.com was down this morning due to:
```
thread 'tokio-runtime-worker-0' panicked at 'Expect peer_addr(): Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1165:5
```
Swap out the `.expect()` for proper error handling
=> net-utils/: Don't panic if peer_addr() fails

ledger/src/blocktree.rs
Validators booted from snapshot or limiting ledger size returning `null` for all `getBlockTime` queries. This is because getBlockTime is attempting to build a RootedSlotIterator from root `0`. On validators that boot from snapshot or limit ledger-size (ie. have a purged blocktree), root 0 exists in the Root column family, but isn't a proper root chained to the next largest slot.
- Find the lowest nonzero root to construct RootedSlotIterator
- Also clean up slot math (offset needs to be calculated from the slot recorded in the vote timestamp, not the slot that carries the successful vote transaction)
- Also filter out vote timestamp duplicates by the same validator
Along with #7673 , this should fix getBlockTime on testnets and heterogeneous clusters.
A reminder: Validators that are …
=> getBlockTime: Fix RootedSlotIterator lowest root

programs/stake/src/stake_state.rs
docs are from before custodian had to sign
fix docs
Fixes #
=> Update Lockup comments

programs/bpf/Cargo.lock, programs/bpf/rust/sysval/src/lib.rs, sdk/src/account_info.rs, sdk/src/entrypoint.rs, sdk/src/instruction_processor_utils.rs, sdk/src/lib.rs, sdk/src/log.rs, sdk/src/nonce_state.rs, sdk/src/pubkey.rs
Program featurization scattered around and overused
- packet.rs is now usable by programs, remove featurization
- remove unnecessary featurization
Fixes #
=> Cleanup usage of feature "program"

cli/src/cli.rs, cli/src/nonce.rs, cli/src/stake.rs, cli/src/vote.rs, cli/tests/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, sdk/src/system_instruction.rs
seed-based account creation not supported by the cli
add support (for stakes)
Fixes #
=> Add create with seed to cli

core/src/replay_stage.rs, runtime/src/bank.rs
Bank hash and inputs not visible in logs.
Add some logs to components.
Fixes #
=> Print bank hash and hash inputs.

programs/bpf/build.rs
=> nit, clearer error message

programs/bpf_loader/src/alloc.rs, programs/bpf_loader/src/helpers.rs, programs/bpf_loader/src/lib.rs, programs/librapay/Cargo.lock, programs/librapay/src/lib.rs, programs/librapay/src/librapay_instruction.rs, programs/librapay/src/librapay_transaction.rs, programs/move_loader/Cargo.lock
=> nit, cleanup uses

book/src/proposals/validator-proposal.md
Old proposal showing its age.
* Use 80-char lines
* Remove the part that was implemented in Gulf Stream
=> Update validator proposal

net/README.md
No docs for partition testing.
Add example config and docs for partition testing in net/readme.md
Fixes #
=> Add partition testing documentation

ci/nits.sh, ledger/src/blocktree.rs, ledger/src/blocktree_processor.rs
Println crept into PR 🗡
Remove
Fixes #
=> Remove print in test

book/src/offline-signing/durable-nonce.md
The book still mentions the nonce fee-theft known issue, but it has been fixed in #7684 
Remove it
=> Book: Drop since-fixed nonce known issue

runtime/src/native_loader.rs, runtime/src/system_instruction_processor.rs, sdk/src/sysvar/mod.rs, sdk/src/sysvar/rent.rs
nit: Variable naming inconsistency
Rename
Fixes #
=> Naming nits

genesis/src/main.rs, multinode-demo/validator.sh
One default vote account commission across the code base is better than 3 (0%, 50%, 100%), and  100% works better for TdS 
cc: a8fd42c1df0c365a367de1d6bd1e4349222f6731
=> Set bootstrap leader and net/ validator vote account commission to 100%

perf/src/perf_libs.rs
Not everybody installs CUDA in /usr/local/cuda-x.y, use $CUDA_HOME if available before falling back to the hard coded CUDA locations.
Fixes #7699
=> Prefer CUDA_HOME environment variable

genesis/src/address_generator.rs, genesis/src/stakes.rs
=> Remove word pair from address generator seed string (#7802)

ci/test-checks.sh
`cargo audit` fails
ignore prost issue
Fixes #
=> Ignore prost RUSTSEC issue

core/src/window_service.rs, ledger/src/blockstore.rs
No component owns detecting and storing duplicate slots
Add a separate thread in WindowService to detect and store duplicate slots
A shred arrives at WindowService, which then passes it to Blockstore for insertion. Upon detecting the same shred slot and index as an existing shred in the database, Blockstore will call a handler, which passes the shred to a separate thread (introduced in this PR) to check if the shreds are the same. If they are not the same, Blockstore stores both shreds as proof that the leader sent duplicate slots, a slashable offense.
Fixes #
=> Add thread to check for and store duplicate slot proofs

ledger/src/blockstore.rs
Not enough logging surrounding this failure: https://github.com/solana-labs/solana/issues/7828
Add logs to make error apparent
Fixes #
=> Add logging surrounding failure in `get_slot_entries_with_shred_info()`

clap-utils/src/input_parsers.rs, cli/src/cli.rs, cli/src/cluster_query.rs, cli/src/stake.rs
```
$ solana show-stakes --help
solana-show-stakes 
Show stake account information
USAGE:
solana show-stakes [FLAGS] [OPTIONS] [VOTE ACCOUNT PUBKEY]
...
```
Fixes #7841
=> cli: Add show-stakes subcommand

validator/src/main.rs
An SLP validator ran into a footgun where a disk permission error caused their snapshot to fail to extract and the validator then attempted to boot from genesis (which would never work due to the current aggressive ledger pruning in SLP).  It got stuck at slot 0 and could never catch up, but nevertheless persisted causing unnecessary confusion and support burden.
Instead when the `--no-snapshot` argument is not specified, it seems more desirable to abort in the case when a snapshot fails to extract so the user knows something is wrong.
=> validator: Abort if a snapshot download fails for any reason other than 404

validator/src/main.rs
Sometimes the RPC ports that show up on gossip are blocked or otherwise not functional.  If at first you don't succeed, try try again!
Fixes #7843
=> validator: If a bad RPC node is selected try another one instead of aborting

validator/src/main.rs
=> validator: Create ledger directory if it doesn't already exist

core/src/replay_stage.rs, core/src/rpc_pubsub.rs, core/src/rpc_pubsub_service.rs, core/src/rpc_subscriptions.rs, core/src/tvu.rs, core/src/validator.rs
* PR #7791 was mistakenly closed
* see #7791 
Fixes #7437
=> feat: implement RPC notification queue

programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf/build.rs, programs/bpf/rust/dup_accounts/Cargo.toml, programs/bpf/rust/dup_accounts/Xargo.toml, programs/bpf/rust/dup_accounts/src/lib.rs
=> Add rust duplicate account test program

run.sh
5 minutes of my time I'll never get back
Don't be weird
=> run.sh: don't put accounts in a weird location, use the defaults

core/src/snapshot_packager_service.rs, ledger/src/snapshot_utils.rs, runtime/src/bank.rs
=> Add mechanism to load v0.22.3 snapshots on newer Solana versions

core/src/validator.rs
Boring stuff from #7801 that should just land without delay
=> Uninteresting cleanup

Cargo.lock, core/src/snapshot_packager_service.rs, core/tests/bank_forks.rs, ledger-tool/src/main.rs, ledger/Cargo.toml, ledger/src/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/blockstore_processor.rs, ledger/src/snapshot_package.rs, ledger/src/snapshot_utils.rs, local-cluster/tests/local_cluster.rs, multinode-demo/bootstrap-leader.sh, runtime/src/accounts_db.rs, runtime/src/bank.rs, validator/src/main.rs
=> Various minor fixes and improvements

ledger/src/bank_forks_utils.rs, ledger/src/blockstore_processor.rs
=> v0.22: Add BlockstoreProcessorResult

Cargo.lock, ledger-tool/Cargo.toml, ledger-tool/src/main.rs
=> v0.22: ledger-tool: Add create-snapshot command

programs/bpf/rust/dup_accounts/src/lib.rs, programs/bpf/rust/external_spend/src/lib.rs, programs/bpf/rust/noop/src/lib.rs, programs/bpf/rust/sysval/src/lib.rs, sdk/src/entrypoint.rs, sdk/src/log.rs
Nits and other general cleanups of the BPF SDK files
Fixes #
=> Cleanup BPF SDK

programs/bpf/rust/dup_accounts/src/lib.rs, programs/bpf/rust/external_spend/src/lib.rs, sdk/src/account_info.rs, sdk/src/log.rs
Ugly syntax to access the mutable members of the `AccountInfo` structure
Add accessor functions
Fixes #
=> Add account accessor functions

core/src/consensus.rs
Consensus failure.
Don't consider threshold check if it does not increase lockouts past threshold.
Fixes #
=> Consensus fix, don't consider threshold check if

fetch-perf-libs.sh
=> Bump perf libs to v0.18.0 for CUDA 10.2 support

cli/src/nonce.rs
Nonce authority isn't displayed in the output of CLI's `show-nonce-account` subcommand
Display it
=> CLI: Add authority to show-nonce-account output

cli/src/cli.rs, cli/src/lib.rs, cli/src/nonce.rs, cli/src/offline.rs, cli/src/stake.rs
Lots of replicode in declaration and assignment of CLI's offline signing args
Use constants for strings values
Use functions to declare and assign args
=> CLI: Cleanup offline args

core/src/validator.rs, ledger/src/snapshot_utils.rs
=> Fix compute_shred_version() 

core/src/validator.rs, ledger/src/snapshot_utils.rs
=> v0.22: Fix compute_shred_version()

programs/bpf/Cargo.lock, programs/bpf/rust/alloc/src/lib.rs, programs/bpf/rust/dup_accounts/src/lib.rs, programs/bpf/rust/external_spend/src/lib.rs, programs/bpf/rust/iter/src/lib.rs, programs/bpf/rust/many_args/src/lib.rs, programs/bpf/rust/many_args_dep/src/lib.rs, programs/bpf/rust/noop/src/lib.rs, programs/bpf/rust/param_passing/src/lib.rs, programs/bpf/rust/param_passing_dep/src/lib.rs, programs/bpf/rust/sysval/src/lib.rs, sdk/src/entrypoint.rs
- Remove leftover `mut`s
- Rewording
- Cleanup `use` formatting
Fixes #
=> Rust BPF program cleanup

sdk/src/transaction.rs
=> Update and fix transaction error documentation

sdk/src/account.rs, sdk/src/account_utils.rs, sdk/src/bank_hash.rs, sdk/src/fee_calculator.rs, sdk/src/hash.rs, sdk/src/instruction.rs, sdk/src/loader_instruction.rs, sdk/src/message.rs, sdk/src/native_loader.rs, sdk/src/nonce_state.rs, sdk/src/packet.rs, sdk/src/pubkey.rs, sdk/src/short_vec.rs, sdk/src/system_instruction.rs, sdk/src/sysvar/recent_blockhashes.rs, sdk/src/transaction.rs, sdk/src/transport.rs
Inconsistent
Consistent
Fixes #
=> Cleanup SDK use syntax

runtime/benches/accounts.rs, runtime/benches/accounts_index.rs, runtime/benches/append_vec.rs, runtime/benches/bank.rs, runtime/benches/bloom.rs, runtime/benches/status_cache.rs, runtime/benches/transaction_utils.rs, runtime/src/accounts.rs, runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/bank.rs, runtime/src/bank_client.rs, runtime/src/blockhash_queue.rs, runtime/src/bloom.rs, runtime/src/loader_utils.rs, runtime/src/message_processor.rs, runtime/src/native_loader.rs, runtime/src/serde_utils.rs, runtime/src/stakes.rs, runtime/src/status_cache.rs, runtime/src/storage_utils.rs, runtime/src/system_instruction_processor.rs, runtime/src/transaction_batch.rs, runtime/tests/bank.rs, runtime/tests/noop.rs, runtime/tests/storage.rs
Inconsistent
consistent
Fixes #
=> Cleanup runtime use syntax

programs/bpf/benches/bpf_loader.rs, programs/bpf/build.rs, programs/bpf/tests/programs.rs
Inconsistent
consistent
Fixes #
=> Cleanup BPF use syntax

keygen/src/keygen.rs
https://github.com/solana-labs/solana/pull/7984 for master
=> Solana keygen grind improvements

programs/stake/src/stake_instruction.rs, programs/stake/src/stake_state.rs
lockups are set at stake initialization time and can't be changed, but token distribution has a lot of moving parts, requires more flexibilty
add support for changing lockup (including re-assigning custodian)
Fixes #
=> Add set_lockup() to stake

cli/src/cli.rs, cli/src/cluster_query.rs, core/src/cluster_info.rs, core/src/rpc.rs, core/src/validator.rs, validator/src/main.rs
=> v0.22: Various fixes/improvements resulting from SLP 1.1 restart debug

archiver-lib/src/archiver.rs, core/src/cluster_info.rs, validator/src/main.rs
Freebie: rename rpc_peers() to all_rpc_peers() for consistency
=> Minor --expected-shred fix, clean up shred-related gossip log messages

cli/src/stake.rs, client/src/rpc_client.rs, client/src/rpc_client_request.rs
Little boring things I ran into while looking into a SLP staking question today...
=> Minor cli fixes

system-test/partition-testcases/colo-partition-once-then-stabilize.yml, system-test/performance-testcases/colo-cpu-only-perf-4-val-1-client.yml, system-test/performance-testcases/colo-gpu-perf-4-val-1-client.yml, system-test/performance-testcases/colo-gpu-perf-high-txcount-4-val-1-client.yml
We need new nightly test cases on colo now that 2 of the 7 nodes are dedicated for other uses
Create analogous tests of the nightlies with reduced node count.
=> Add new colo test cases using reduced node count

core/src/consensus.rs
When a new root is created, the oldest slot is popped off
but when the logic checks for identical slots, it assumes
that any difference means a slot was popped off the front.
Check the same slot in the old vote state is the same confirmation count as the new threshold slot.
Fixes #8086
=> Fix consensus threshold when new root is created

cli/src/offline.rs, cli/tests/pay.rs, cli/tests/stake.rs
The helper function for parsing `sign_only` replies is buried in the staking tests, despite being helpful anywhere offline signing is tested
Expose it.
De-replicode
=> CLI: Expose sign-only reply parsing helper

programs/bpf/Cargo.lock, programs/bpf/rust/error_handling/src/lib.rs, sdk/src/program_error.rs
Printing program errors is clunky
Allow the printing of program errors and a program's custom errors
Fixes #
=> Facilitate printing program errors from BPF programs

runtime/src/accounts_db.rs
Mispelling in error
verificaton => verification
Fixes #
=> Fix spelling of verification in accounts_db

programs/bpf/rust/dup_accounts/src/lib.rs, programs/bpf/rust/error_handling/src/lib.rs, programs/bpf/rust/external_spend/src/lib.rs, programs/bpf/rust/noop/src/lib.rs, programs/bpf/rust/sysval/src/lib.rs, sdk/src/entrypoint.rs
Nit: verbose BPF program entrypoint return type
Create a `type`
Fixes #
=> Add BPF program entrypoint return type

sdk/src/slot_hashes.rs, sdk/src/sysvar/slot_hashes.rs
slot_hashes are bank hashes, not block hashes
update comments
Fixes #
=> Fix slot_hashes documentation

Cargo.lock, core/Cargo.toml, core/src/result.rs
core/src/result.rs
make it smaller
=> Remove reed-solomon-erasure from core/

README.md
=> add step "apt-get update", add package "libudev-dev"

core/src/snapshot_packager_service.rs, core/tests/bank_forks.rs, ledger/src/snapshot_package.rs, ledger/src/snapshot_utils.rs, runtime/src/bank.rs
Just tiny clean up, spawned from #8012.
No functional change.
=> Just define BnakSlotDelta type alias

ledger/src/snapshot_utils.rs, runtime/src/bank.rs
=> Minor logging improvements

cli/src/cli.rs, cli/tests/transfer.rs
CLI `transfer` subcommand uses dummy keypair pubkeys (accounts to which do not exists) for client-side account pre-checks in offline-submit case
Use the real account pubkeys
Add test for offline transfer with nonce
=> CLI: `transfer` fix checks pubkeys

core/src/local_vote_signer_service.rs, ledger/src/sigverify_shreds.rs
Another tiny PR for nightly rustc. (I use nightly often because of #8012).
No functional change.
=> Fix nightly clippy warnings

cli/src/cli.rs, cli/src/stake.rs, cli/tests/stake.rs
CLI `stake-split` snuck in between branch and merge for `--fee-payer`
Add `--fee-payer` arg to `stake-split`
Add integration test for `stake-split`
=> CLI: Add fee-payer param to stake-split subcommand

sdk/bpf/scripts/bpf-trace.py
BPF stack trace script does not handle helper functions very well
- Handle and report helper functions
- Report more information about the trace
Fixes #
=> Update bpf trace

ci/docker-rust-nightly/Dockerfile, ci/docker-rust/Dockerfile, ci/rust-version.sh, core/build.rs, core/src/validator.rs, sdk/src/clock.rs, sdk/src/entrypoint.rs, sdk/src/hash.rs
=> Upgrade to rust 1.41.0

archiver-lib/src/archiver.rs, core/src/cluster_info.rs, core/src/contact_info.rs, core/src/gossip_service.rs, core/src/lib.rs, core/src/repair_service.rs, core/src/serve_repair.rs, core/src/serve_repair_service.rs, core/src/validator.rs, core/tests/gossip.rs, local-cluster/tests/archiver.rs, metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json, validator/src/main.rs
PR was reverted here: https://github.com/solana-labs/solana/pull/8143 due to ABI incompatibility. 
Re-introduce PR
Fixes #
=> Factor repair from gossip (#8044)

core/src/rpc_subscriptions.rs
A single unsubscribe can result in many more unsubscribes than intended due to a bug
* Fix unsubscribe bug
* Add tests
Fixes #
=> Fix RPC pub sub unsubscribe

core/src/serve_repair.rs
=> Quash 'repair listener error: Err(RecvTimeoutError(Timeout))' log spam

system-test/abi-testcases/.gitignore, system-test/abi-testcases/mixed-validator-test.sh
0.23.3 is borked, error handling sucks
0.23.4 will save us all.  polish the error handles
=> mixed-validator-test.sh: Bump baseline version to 0.23.4, improve error reporting

core/src/gossip_service.rs
`solana-gossip spy --num-nodes 2` can pass when there's only one validator in gossip since a validator has a TVU and Storage port, and each port was considered a "node"
=> Nodes with a tvu and storage port are no longer double counted

core/src/cluster_info.rs, core/src/contact_info.rs, core/src/serve_repair.rs
=> Expel ContactInfo::new()

cli/src/cli.rs, cli/src/stake.rs, cli/tests/stake.rs
No facilities for adjusting lockup from the cli.
Add StakeSetLockup cli command
Also remove a couple errant prints in cli/tests/stake.rs, and update a couple typos in cli arg definitions in cli/src/stake.rs
=> Add CliCommand::StakeSetLockup

core/src/rpc_subscriptions.rs
All signature subscriptions are removed after each slot, regardless if the subscription was sent a notification or not. This means that if you subscribe to a signature before the corresponding transaction was processed, the subscription will get removed before the subscriber gets any result.
Also, if a signature subscription is configured for a certain number of confirmations. That subscription could get removed before reaching the desired number of slot confirmations.
- Return a set of notified subscription ids for each subscription
- Auto remove signature subscriptions for all corresponding subscription ids that have been notified
Fixes #
=> Retain signature subscriptions that haven't been notified

ledger/src/blockstore.rs
```
thread 'http.worker10' panicked at 'Rooted slot must exist in SlotMeta', src/libcore/option.rs:1188:5
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:84
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
at src/libstd/sys_common/backtrace.rs:61
4: core::fmt::write
at src/libcore/fmt/mod.rs:1025
5: std::io::Write::write_fmt
at src/libstd/io/mod.rs:1426
6: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:65 …
```
=> get_confirmed_block: expect() less

sdk/src/signature.rs
We have no mechanism to sign a transaction with pre-generated signatures
Add a `Presigner` `KeypairUtil` implementer
=> Presigner KeypairUtil implementer

Cargo.lock, programs/exchange/Cargo.toml, programs/exchange/src/exchange_processor.rs
Exchange program uses deprecated `GenericError`
Use `thiserror` instead
Fixes #
=> Remove Exchange program's use of GenericError

system-test/abi-testcases/mixed-validator-test.sh, system-test/stability-testcases/.gitignore, system-test/stability-testcases/gossip-dos-test.sh, system-test/stability-testcases/gossip-dos-test.yml
Add a nightly test to demonstrate #8175, which should turn green when #8175 is fixed.
=> Add simple gossip DoS test

core/src/consensus.rs, core/src/replay_stage.rs, runtime/src/genesis_utils.rs
Functionality to create genesis with vote accounts, which is useful for testing, is not exposed.
Factor out creating genesis with vote accounts into a utility function
Fixes #
=> Factor out creating genesis with vote accounts into a utility function

core/src/replay_stage.rs
Some warnings should be infos
Change replay stage warnings to infos
Fixes #
=> Change warnings to infos

Cargo.lock, core/Cargo.toml, core/src/cluster_info.rs, core/src/crds_value.rs, core/src/repair_service.rs
Cherry picking #8276 and #8341
=> [V0.23] Cherry picks from master

core/src/rpc_subscriptions.rs
There's no reason that a notification entry needs to be locked across threads
`Arc<Mutex<NotificationEntry>>` -> `NotificationEntry`
Fixes #
=> Remove unnecessary arc and mutex for rpc notifications

metrics/src/metrics.rs
The metrics agent was issuing between 3-5 HTTP POSTs every 10 seconds to submit metrics for each enabled log level, serially.   But really one HTTP POST to send all the log levels at once is enough.
=> Submit all metrics in one HTTP POST rather than a HTTP POST per level

programs/librapay/Cargo.lock, runtime/src/message_processor.rs
`PreAccounts` are generated for duplicate accounts, Only a single one is needed
Only generate one `PreAccount` per unique `Account`
Fixes #
=> Optimize verification

remote-wallet/src/ledger.rs
Can't send transactions longer than ~300 bytes to Ledger Wallet. Ours are up to 1.5k.
* Break the message up into 300-byte chunks.
The tests for this are over in the ledger-app-solana repo.
=> Add support for large transactions with Ledger Wallet

programs/bpf/Cargo.lock, sdk/Cargo.toml
Chrono (and time in general) is not compatible with BPF
Make it an optional SDK dependency
Fixes #
=> Fix SDK dependencies

core/src/replay_stage.rs
Commonality in create new bank path for leader/non-leader cases.
Combine logic for creating a new bank and notifying downstream receivers.
Fixes #
=> Refactor new bank paths into common function

core/src/replay_stage.rs
Replay stage memory reporting has a lot of duplicated logic.
Move into a function.
Fixes #
=> Combine replay stage memory reporting

docs/src/SUMMARY.md, docs/src/remote-wallet/README.md, docs/src/remote-wallet/ledger.md, remote-wallet/src/ledger.rs
No docs on how to use a Ledger hardware wallet with the CLI
Add a doc
Closes #8466
=> Ledger hardware wallet docs

net/scripts/solana-user-authorized_keys.sh
Need another pubkey in authorized keys.
Add it.
Fixes #
=> Add curie pubkey to authorized keys

core/src/consensus.rs, core/src/replay_stage.rs
`VoteResult` doesn't scale well as number of errors grows
Return a vector of possible `VoteFailures`
Fixes #
=> Update voting simulation

docs/src/SUMMARY.md, docs/src/remote-wallet/README.md, docs/src/remote-wallet/ledger.md, remote-wallet/src/ledger.rs
* Update protocol documentation
* Correct app-version command const
* Rough initial Ledger docs
* Add more docs
* Cleanup
* Add remote-wallet to docs TOC
Co-authored-by: Greg Fitzgerald <greg@solana.com>
Backport didn't happen automatically, for some reason.
=> Ledger hardware wallet docs (#8472)

ledger/src/snapshot_utils.rs
https://github.com/solana-labs/solana/pull/8497 for master
=> Peg snapshot version to 1.0.0

sdk/bpf/scripts/install.sh
Installing or updating xargo could take a while or fail but the install script is silent during this time and does not report any errors that may have occurred.
Report and bail if there is an error
Fixes #
=> Improve install messaging

net/README.md
This is just minor clarifications, which found valuable gained from the first-time experience of running a testnet. :)
=> Improve net/README.md a bit

keygen/src/keygen.rs
`solana-keygen verify` is useful for checking keys derived from remote wallets. However, remote-wallet application code requires that data be parseable as a legitimate solana message before it can be signed.
- Build a simple (but legitimate) message to sign in solana-keygen verify
@garious , any concerns with this solution? Alternatives would be to allow ledger-solana-app to sign garbage, or to disable `solana-keygen verify` for ledger devices.
Fixes #8422
=> Use legitimate solana message in keygen verify

validator/src/main.rs
Sometimes there are evil RPC nodes around.  The `---no-untrusted-rpc` tells your validator to only use RPC from a `--trusted-validator` node.
TBD: RPC runs over cleartext HTTP so yeah...
=> validator: Add ---no-untrusted-rpc flag

core/src/snapshot_packager_service.rs
Snapshot packaging is currently very slow, and gossiping unpublished snapshot hashes can cause a node to incorrectly reject an valid snapshot because the snapshot hash was pushed out of gossip before the node could load and verify it.
Ideally snapshot packaging would be faster, and if/when it is this PR could probably be reverted.
=> snapshot_packager: Only gossip packaged snapshots

core/src/rpc_subscriptions.rs
A futures-related error is occasionally popping up on the new CI machines: "no Task is currently running"
Run pubsub test poller in tokio runtime
=> Run pubsub test poller in tokio runtime

docs/src/remote-wallet/ledger.md
The Solana Ledger App can't yet be installed via the Ledger Live Manager.
Add instructions for how to install the latest release from the ledger-app-solana GitHub repo.
=> Add Ledger wallet installation instructions

runtime/src/accounts_db.rs
Snapshot ingest is really slow from this move_items call.
Use fs::rename which is much faster.
For an 8500 append-vec file, this reduces the store rebuild time from 136 seconds to 17 seconds.
Fixes #
=> Use fs::rename which is much faster than move_items

cli/src/cli.rs, cli/src/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/nonce_utils.rs, runtime/src/system_instruction_processor.rs, sdk/src/lib.rs, sdk/src/nonce/account.rs, sdk/src/nonce/mod.rs, sdk/src/nonce/state.rs, sdk/src/system_instruction.rs
The nonce state module's organization makes versioning difficult
Reorganize it (purely cosmetic)
=> SDK: Re-org nonce state module to facilitate versioning

cli/src/cli.rs, cli/src/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs, runtime/src/bank.rs, runtime/src/nonce_utils.rs, sdk/src/nonce/account.rs, sdk/src/nonce/state.rs
Nonce account state data is unversioned
Version it
=> SDK: Add versioning to nonce state

sdk/src/nonce/state/current.rs, sdk/src/nonce/state/mod.rs
Versioned and unversioned types live in the same file
Minor cosmetic module re-org
=> Prepare nonce module for multiple account state versions

docs/src/apps/jsonrpc-api.md
Descriptive text is incorrect for JSON RPC sendTransaction
Fix it
=> Fix sendTransaction doc

cli/src/cli.rs, cli/src/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/nonce_utils.rs, runtime/src/system_instruction_processor.rs, sdk/src/nonce/account.rs, sdk/src/nonce/state/current.rs, sdk/src/nonce/state/mod.rs
Nonce state data items are stored independently. Two's a party, three's a crowd.
Combine them
=> Consolidate Nonce state under one struct

local-cluster/tests/local_cluster.rs
Partition flag not connected to validators.
Connect it.
Fixes #
=> Connect partition flag to validators

programs/bpf/c/src/bench_alu/bench_alu.c, programs/bpf/c/src/bpf_to_bpf/entrypoint.c, programs/bpf/c/src/bpf_to_bpf/helper.c, programs/bpf/c/src/move_funds/move_funds.c, programs/bpf/c/src/relative_call/relative_call.c, programs/bpf/rust/128bit/src/lib.rs, programs/bpf/rust/alloc/src/lib.rs, programs/bpf/rust/dep_crate/src/lib.rs, programs/bpf/rust/error_handling/src/lib.rs, programs/bpf/rust/many_args/src/helper.rs, programs/bpf/rust/noop/src/lib.rs
Inconsistencies and spelling errors
Fix'em
Fixes #
=> Consistency nits and spelling

runtime/src/native_loader.rs
=> Nit: Update native loader to iterate accounts

core/src/repair_service.rs, ledger/src/blockstore.rs
No way to get all the orphans higher than a given slot `S`, which is useful for finding incomplete slots greater than the root, whose parents are unknown (cannot be found by iterating from the root).
Add an orphans iterator
Fixes #
=> Add orphan iterator

runtime/src/message_processor.rs
Overly verbose
Much cleaner
Fixes #
=> Nit: Use accessor function

ledger/src/bank_forks.rs
Snapshot slots not deterministic.
While each node may root a different bank at different times, they all root the same fork. Therefore each node should observe the same parent slot when squashing a root bank. Instead of just generating a snapshot at the root, the node should find the parent which is at the synchronization point and generate a snapshot form that bank.
Check to not double-squash the rooted bank.
Fixes #
=> Generate a snapshot at synchronized points

ledger/src/lib.rs, ledger/src/next_slots_iterator.rs
No convenient method for iterating through a set of connected slots
Add an iterator to do above
Fixes #
=> Add NextSlotsIterator

cli/src/cli.rs, cli/src/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs, core/src/transaction_status_service.rs, runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/blockhash_queue.rs, runtime/src/lib.rs, runtime/src/nonce_utils.rs, runtime/src/system_instruction_processor.rs, sdk/src/lib.rs, sdk/src/nonce/account.rs, sdk/src/nonce/mod.rs, sdk/src/nonce/state.rs, sdk/src/nonce/state/current.rs, sdk/src/nonce/state/mod.rs, sdk/src/system_instruction.rs, sdk/src/sysvar/recent_blockhashes.rs
Backport of https://github.com/solana-labs/solana/pull/8659 and its dependencies
cc/ @mvines 
closes: #8659, #8660
=> Nonce fees 1.0

core/src/repair_service.rs, ledger/src/blockstore.rs
Need a method of efficiently finding all incomplete slots for repair
Add `find_incomplete_slots`
Fixes #
=> Add find_incomplete_slots

runtime/src/native_loader.rs
Not using the iterated account
Fixes #
=> Use the iterated account

core/src/snapshot_packager_service.rs, core/src/tvu.rs, core/src/validator.rs, core/tests/bank_forks.rs
=> Publish initial snapshot hash in gossip on validator startup

system-test/testnet-automation.sh
We do not have a way to verify wallclock slot rate over long duration test cases
Record slot number and `$SECONDS` at the beginning and end of a test and publish the time-averaged result when the test is finished.
Fixes #8450
=> Add slot rate check to automation framework

genesis/src/genesis_accounts.rs
Creators unlock at the same time as everyone else.
Only unlock half, then the remaining over 2 years.
=> Split staker infos

README.md
Duplicate release documentation.
Delete the copy in the readme.  Use the "Install Solana" page in the docs instead.
=> Remove releases from readme

net/net.sh
In certain cluster tests it is undesirable or can cause instability when a bench-tps client is started immediately after the validators have booted and stake has not been distributed away from the bootstrapper.
Add `startclients` subcommand to `net.sh` which accepts the same client options as the `net.sh [re]start` logic
Usage example:
1). Start the validator nodes but set the client nodes to remain idle
`net.sh start -c idle=1`
2)  Start client nodes only
`net.sh startclients -c bench-tps=1=txcount=25000`
This PR is the backend needed to automate the stake distribution logic needed by #8675
=> Add ability to start clients separately from validators

programs/bpf/Cargo.lock, programs/bpf/tests/programs.rs, programs/bpf_loader/Cargo.toml
copypasta in program tests
Clean it up
Fixes #
=> Remove copypasta

docs/src/install-solana.md, docs/src/remote-wallet/ledger.md
Installing the Solana Ledger app can fail if Ledger Live is open.
* Add troubleshooting notes
* Also, update the version in "Install Solana" such that the scripts will automagically update it
Fixes #8701
=> Fix Ledger docs

docs/src/install-solana.md
Version scripts won't update the version unless it matches the old version verbatim.
Manually bump the docs version.
=> Docs version bump

Cargo.lock, Cargo.toml, core/src/rpc_service.rs, download-utils/Cargo.toml, download-utils/src/lib.rs, local-cluster/Cargo.toml, local-cluster/tests/local_cluster.rs, validator/Cargo.toml, validator/src/main.rs
Want to test snapshot download code in a local_cluster.
Move download code to download-utils crate where it can be called in local-cluster and validator/src/main
Fixes #
=> Move snapshot/genesis download code to download-utils crate

cli/src/stake.rs, sdk/src/system_instruction.rs
Typos in CLI error messages
Fix 'em
=> Fix typos in error messages

system-test/testnet-automation.sh
Starting the clients before stake is distributed to non-bootstrapper nodes can lead to instability around the time nodes first enter the leader schedule in the nightly automation
Call `net.sh startclients` only after stake has fallen below a prescribed threshold.
Depends on https://github.com/solana-labs/solana/pull/8690
Fixes #8675
=> Wait for stake distribution before starting clients in nightly tests

remote-wallet/src/ledger.rs
Because large messages prompt multiple calls to `send_adpu()`, the "Waiting..." message is printed more than once. Unnecessary.
- Update logic to only print "Waiting..." message on single- or last-chunk apdus
Fixes #8691
=> Limit waiting-message to single- or last-chunk apdus

watchtower/src/main.rs
`--validator-identity PUBKEY` can now be supplied multiple times so the same watchtower instance can monitor multiple validators
=> watchtower: Support monitoring multiple validators

docs/src/SUMMARY.md, docs/src/cli/README.md, docs/src/install-solana.md, docs/src/terminology.md
Indirect titles in the docs. People don't want to "Use Solana from the command-line". They're more likely trying to get something done, like accepting the tokens someone is trying to send them.
* Moar better
* And define *wallet*
cc https://github.com/solana-labs/solana/issues/8739
=> Better titles

Cargo.lock, cli/Cargo.toml, cli/src/cli.rs, cli/src/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs
Replicode for accessing nonce account data
Add helpers
Use them
=> CLI Nonce account access dereplicode

watchtower/src/main.rs
`solana-watchtower --monitor-active-stake ...` now raises the alarm if the cluster goes below 80% current stake
=> watchtower: Add --monitor-active-stake flag

Cargo.lock, remote-wallet/Cargo.toml, remote-wallet/src/ledger.rs
Add checkmark to Ledger device approved message to spark more joy
https://github.com/solana-labs/solana/pull/8771#issuecomment-597317723
=> Emojify the "Approved" message

watchtower/src/main.rs
The bootstrap validator on TdS ran out of SOL last night and it took me too long to figure out that it needed a top-off.  Now watchtower will alert me.
=> watchtower: Notify when validator balance goes below 1 SOL

ci/buildkite.yml
Band-aid fix until https://github.com/solana-labs/solana/issues/8798 is resolved
=> Restrict which nodes can run stable and coverage

docs/src/validator/runtime.md
=> Fix malformed doc link

ci/docker-rust-nightly/Dockerfile, ci/docker-rust-nightly/README.md, ci/docker-rust/Dockerfile, ci/rust-version.sh, ledger/src/blockstore.rs, runtime/src/bank.rs, runtime/src/transaction_batch.rs
=> Upgrade to Rust 1.42

net/remote/remote-client.sh, net/remote/remote-deploy-update.sh, net/remote/remote-node.sh, run.sh
=> Apply s/faucet-keypair/faucet renaming to net scripts

validator/src/main.rs
Due to the current operational challenges with issuing `solana vote-authorize-voter` for all live TdS validators, re-introduce the legacy `solana-validator` arguments (undocumented) so existing TdSers can effortlessly upgrade to v1.0.7 and deal with double paying for votes later
=> validator: Quietly re-introduce legacy --voting-keypair/--identity-keypair args for v1.0.6 compatibility

run.sh
=> Fix faucet command in run.sh

cli/src/cli.rs, cli/src/main.rs, keygen/src/keygen.rs
Review feedback #8878 from @CriesofCarrots
=> Cleanup CLI types

system-test/genesis-test/cluster_token_count.sh, system-test/genesis-test/get_owned_accounts_info.sh, system-test/genesis-test/get_program_accounts.sh
The script to sum all tokens on a fresh cluster has been living outside the solana repo
Bring the tooling into system-test
Fixes #6141
=> Add genesis token counter test to system test

Cargo.lock, Cargo.toml, accounts-bench/Cargo.toml, accounts-bench/src/main.rs, ci/test-bench.sh, runtime/src/accounts.rs
No accounts benchmark to test a large accounts set for clean and hashing operations.
Add accounts-bench benchmark.
Fixes #
=> Add accounts-bench, a benchmark to test the accounts speed

programs/bpf_loader/src/helpers.rs
More capable BPF virtual address macros needed for cross-program invocations.  
Add them upfront and switch the existing helpers to use them.
Fixes #
=> Add BPF virtual address translate helpers

docs/src/running-validator/validator-start.md
Doc doesn't mention --no-untrusted-rpc flag to limit nodes to trusted validator set.
Add that.
Fixes #
=> Add --no-untrusted-rpc to docs

runtime/src/bank.rs
Little bit of refactoring that might have helped me read the code right the first time and not think that https://github.com/solana-labs/solana/issues/8938 was an issue
=> bank: Refactor distribute_rent_to_validators() for clarity

docs/src/cli/choose-a-wallet.md
Last PR had valid links in mdbook, but broken in gitbook. gitbook doesn't understand github markdown. we don't render gitbook locally, unlike mdbook, so couldn't see these bugs until after merging.
dumb it down for gitbook
cc: @rmshea
=> Fix links for gitbook

docs/src/paper-wallet/README.md
cc https://github.com/solana-labs/solana/issues/8742
=> Delete broken link

cli/src/cli.rs, cli/src/vote.rs, cli/tests/stake.rs, cli/tests/vote.rs, ledger/src/leader_schedule_cache.rs, ledger/src/staking_utils.rs, programs/vote/src/vote_instruction.rs, programs/vote/src/vote_state/mod.rs, runtime/src/bank.rs, runtime/tests/stake.rs
=> Vote InitializeAccount and UpdateNode instructions now need a signature from the validator identity

cli/src/cli.rs, cli/src/vote.rs, cli/tests/stake.rs, cli/tests/vote.rs, ledger/src/leader_schedule_cache.rs, ledger/src/staking_utils.rs, programs/vote/src/vote_instruction.rs, programs/vote/src/vote_state/mod.rs, runtime/src/bank.rs, runtime/tests/stake.rs
=> v1.0: Backport of #8939

cli/src/cli.rs, remote-wallet/src/ledger.rs, remote-wallet/src/remote_wallet.rs
=> Backport: Some Cli polish (#8966)

Cargo.lock, core/Cargo.toml, core/tests/cluster_info.rs, ledger/Cargo.toml, ledger/src/blockstore_db.rs, metrics/Cargo.toml, metrics/src/metrics.rs, rayon-threadlimit/Cargo.toml, rayon-threadlimit/src/lib.rs, runtime/Cargo.toml
=> v1.0: Fix windows build by removing sys-info (#8860)

docs/src/cli/transfer-tokens.md
Followup to https://github.com/solana-labs/solana/pull/8972
=> Update value names in docs

core/src/shred_fetch_stage.rs
Debug messages left in.
Remove them, add slightly elucidating comment about epoch limit.
Fixes #
=> Shred fetch comment and debug tweak

Cargo.lock, archiver-lib/src/archiver.rs, core/src/shred_fetch_stage.rs, core/src/tvu.rs
Shred dos causes problems.
Filter same slot/index shreds in a 200ms window.
Fixes #
=> Shred filter v1.0 backport (#8975)

Cargo.lock, Cargo.toml, dos/Cargo.toml, dos/src/main.rs, scripts/cargo-install-all.sh, system-test/stability-testcases/gossip-dos-test.sh
No tools to dos
Add a tool to send random inputs to validators on gossip.
Fixes #
=> Dos all the things

sdk/src/pubkey.rs
Old error stuff
Cleanup using thiserror
Fixes #
=> Nit thiserror for pubkey

runtime/src/accounts_db.rs
Locks not dropped in a consistent order.
Drop storage, then accounts lock
Fixes #
=> Drop storage lock

ledger-tool/src/main.rs
When a validator panics due to a modification of a frozen account (cc: #8989), the slot containing the bad transaction must be set dead to allow the validator to successfully start again
eg, mark slots 510 and 511 dead:
```
$ solana-ledger-root -l ledger set-dead-slot 510 511
```
=> ledger-tool: Add set-dead-slot command

core/src/rpc_pubsub.rs, core/src/rpc_subscriptions.rs, core/tests/rpc.rs
RPC pubsub subscribers have no context on what slot they are receiving a notification for, it could be a fork and they would have no idea.
* Wrap responses for account, program account, and signature subscriptions with `Response`
Fixes https://github.com/solana-labs/solana/issues/8978
=> Add slot context to rpc pubsub notifications

genesis/src/main.rs
Outdated help text
- Fix help text
Fixes #
=> Update outdated solana-genesis cli help text

ledger/src/blockstore_processor.rs
No idea what speed the ledger is processing at.
Add slots/s and txs/s to the existing print.
Fixes #
=> Ledger processing speed tracking

sdk/src/pubkey.rs
No way to generate program addresses used by programs to sign cross-program invocations
Provide one adherent to https://github.com/solana-labs/solana/pull/8155
These changes are part of a larger effort that has been broken into logical pieces to ease review
Fixes #
=> Program address generator

client/src/mock_rpc_client_request.rs, client/src/rpc_client.rs, client/src/rpc_request.rs, client/src/rpc_response.rs, core/src/rpc.rs, core/src/storage_stage.rs, core/src/transaction_status_service.rs, core/src/validator.rs, docs/src/apps/jsonrpc-api.md, docs/src/cli/delegate-stake.md, docs/src/cli/transfer-tokens.md, genesis/src/main.rs, ledger/src/blockstore.rs, ledger/src/blockstore_db.rs, multinode-demo/bootstrap-validator.sh, multinode-demo/validator.sh, net/remote/remote-node.sh, run.sh, runtime/src/bank.rs, runtime/src/bank_client.rs, runtime/src/status_cache.rs, validator/src/main.rs
https://github.com/solana-labs/solana/pull/9011
https://github.com/solana-labs/solana/pull/9018
https://github.com/solana-labs/solana/pull/9020
https://github.com/solana-labs/solana/pull/9021
https://github.com/solana-labs/solana/pull/9022
=> Manual v1.0 backports

docs/src/cli/choose-a-wallet.md, docs/src/remote-wallet/ledger.md
Broken link in gitbook.
`index.md` -> `README.md`
Couldn't find a way to do this without breaking mdbook
=> Fix link in gitbook

docs/src/cli/choose-a-wallet.md
Docs include concerns with hardware wallets that are details of a specific hardware wallet. Wrong place for that content.
Remove that content.
=> Remove Ledger-specific analysis of hardware wallets

core/src/rpc_pubsub.rs, core/src/rpc_subscriptions.rs, core/tests/rpc.rs, runtime/src/bank.rs
=> Backport: add slot to signature notification & respect confirmations param

client/src/rpc_client.rs
=> rpc_client: Add get_confirmed_block_with_encoding()

streamer/src/recvmmsg.rs, streamer/tests/recvmmsg.rs
recvmmsg is failing in the coverage build.
Move to integration tests.
Fixes #
=> Move streamer test to integration test

ci/_, ci/test-checks.sh
https://github.com/solana-labs/solana/pull/8959/commits/8b5ddd8c44a8fb751eccb5a734dd5e20f6d5fe0f
Related to #9058
=> Ignore RUSTSEC-2020-0006 for the moment

runtime/src/accounts_db.rs
unwrap in accounts cleanup.
Remove unwrap.
Fixes #
=> Remove accounts unwrap v1.0 backport

archiver-lib/src/archiver.rs, core/src/cluster_slots.rs, core/src/repair_service.rs, core/src/retransmit_stage.rs, core/src/tvu.rs, core/src/validator.rs, core/src/window_service.rs
`ClusterSlots` is not `Sync` and cannot be shared with other threads like `ReplayStage` that need the info
Add fine grained locking and replace `Rc` with `Arc`
Fixes #
=> Update Cluster Slots to support multiple threads

core/src/window_service.rs, ledger/src/blockstore.rs
Blockstore metrics are turned off because they are too chatty.
Accumulate the metrics over a longer time and submit them only every 2 seconds.
Fixes #
=> Accumulate blockstore metrics and submit every 2s

ci/rust-version.sh
=> Revert setting the default toolchain

docs/src/SUMMARY.md, docs/src/cli/README.md, docs/src/wallet/README.md, docs/src/wallet/app-wallets.md, docs/src/wallet/cli-wallets.md, docs/src/wallet/ledger-live.md, docs/src/wallet/trust-wallet.md
We don't have docs for our third-party wallet integrations
Add 'em
=> Add docs for app wallets

core/src/replay_stage.rs
Math for throttling transmit frequency is backwards, causing retransmits to occur on every slot instead of every `NUM_CONSECUTIVE_LEADER_SLOTS`
Fix the math
Fixes #
=> Reduce transmit frequency

docs/src/terminology.md
Lack of clarity over how to measure confirmations for a transaction signature
=> Add "transaction confirmations" term to docs

docs/src/apps/jsonrpc-api.md
Missing the JSON definition for a transaction which is needed to for documenting the getConfirmedBlock API. The API docs still link to the now-deleted page here: https://docs.solana.com/apps/jsonrpc-api#getconfirmedblock
- Add detailed documentation for the structure of a transaction
Fixes #9117
=> Document transaction field in getConfirmedBlock responses

docs/src/cli/generate-keys.md, docs/src/cli/transfer-tokens.md
A couple links are broken from the wallet refactor.
Fix them
=> Fix more broken links in docs

system-test/stake-operations-testcases/offline_stake_operations.sh
Typo in the test script somehow worked for some commands but not others, breaking the test.
Fix it
Fixes #9100
=> Fix offline stake ops test script

cli/src/cli.rs, cli/src/storage.rs, client/src/rpc_client.rs, client/src/thin_client.rs, core/tests/client.rs
=> RpcClient now returns Signatures instead of Strings

Cargo.lock, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml
=> Bump rBPF version to v0.1.25: Fix Windows build

cli/src/cluster_query.rs
When a validator is still booting it has no RPC port published yet for `solana catchup` to find.  Rather than aborting `solana catchup` now retries as a convenience
=> cli: catchup now retries when the desired node is not yet online

Cargo.lock, core/src/serve_repair.rs, dos/Cargo.toml, dos/src/main.rs
Dos tool doesn't support sending repair messages.
Add support and also a test.
Fixes #
=> Repair dos support

scripts/cargo-install-all.sh
solana-stake-accounts not installed via solana-install
Add it to the list of installed binaries
cc: @mvines
=> Install solana-stake-accounts

docs/src/remote-wallet/README.md, docs/src/remote-wallet/ledger.md
* Ledger doc missing note about the "Pending Ledger review" screen
* zsh silently ignores keypair URL parameters
Add docs
=> Add more Ledger wallet documentation

sdk/src/instruction.rs
=> Nit: print program error as hex

core/src/ledger_cleanup_service.rs, core/src/tvu.rs, core/src/validator.rs, core/tests/ledger_cleanup.rs, local-cluster/tests/local_cluster.rs, validator/src/main.rs
max ledger slots is now max ledger shreds.
rename things
Fixes #
=> max_ledger_slots -> max_ledger_shreds

programs/bpf_loader/src/lib.rs
Hard to tell what program is being run
Print information on what program is being run
Fixes #
=> Improve BPF Loader reporting

stake-accounts/src/main.rs
Rebase stake accounts on the new base key, not the old one.
Note: Adding tests here will need to be part of a larger refactor.
Fixes #9189
=> Fix solana-stake-accounts rebase/move

stake-accounts/src/arg_parser.rs, stake-accounts/src/args.rs, stake-accounts/src/main.rs
Messy code, hard to test
Clean it up
=> Clean up solana-stake-accounts

core/src/accounts_hash_verifier.rs
Accounts hashes array not capped in size so nodes will stop publishing new hashes on gossip and also a slow memory leak.
Cap the array size and add a test.
Fixes #
=> Fix error with account hash list getting too big for gossip

docs/src/SUMMARY.md, docs/src/paper-wallet/paper-wallet-usage.md, docs/src/remote-wallet/ledger.md, docs/src/wallet/ledger-live.md, docs/src/wallet/support.md, docs/src/wallet/trust-wallet.md
No way for people to get in contact with us if they have trouble after reading wallet creation docs.
Add a support page with links to TG and Discord
=> Add a support page for wallet docs

cli/src/cli.rs, remote-wallet/src/remote_wallet.rs, sdk/src/signature.rs
More redundant "Error" in error variants
Clean them up
Fixes #
=> More custom error rename

core/src/rpc.rs
Made a breaking change to rpc by removing a method we thought was unused, and broke external clients.
Restore `getSignatureConfirmation`
cc @jstarry
=> Undo breaking rpc removal of getSignatureConfirmation

ci/buildkite-tests.yml, ci/buildkite.yml, ci/maybe-trigger-tests.sh
=> Do not trigger tests if only docs were modified (#9240)

sdk/src/program_error.rs
=> Nit: ProgramError cleanup

core/src/consensus.rs, core/src/replay_stage.rs
=> Cherry-pick #9271

docs/src/wallet/ledger-live.md
Clean up whitespace around screenshots.
=> Minor doc fixup

docs/set-solana-release-tag.sh
Backport of https://github.com/solana-labs/solana/pull/9286
=> Fix sed command for mac and linux

Cargo.lock, core/src/accounts_hash_verifier.rs, core/src/rpc_service.rs, core/src/snapshot_packager_service.rs, core/tests/bank_forks.rs, download-utils/src/lib.rs, ledger-tool/src/main.rs, ledger/Cargo.toml, ledger/src/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/snapshot_package.rs, ledger/src/snapshot_utils.rs, local-cluster/tests/local_cluster.rs, validator/src/main.rs
bz2 is horribly horribly slow
Add gzip and zstd as options for snapshot compression
Fixes #
=> Add snapshot compression option

core/src/serve_repair.rs
Repair service can be dos'ed with too many requests.
Adaptively drop requests the server can't handle.
Fixes #
=> Fix repair dos (#9056) (1.0 backport)

bench-tps/src/bench.rs
bench-tps funding prints too often during funding.
Reduce the printing to be time-based so when speed is high, the prints are not too often.
Fixes #
=> Reduce bench-tps funding printing

core/src/transaction_status_service.rs, ledger-tool/src/main.rs, ledger/src/blockstore.rs, ledger/src/blockstore_db.rs, ledger/src/blockstore_meta.rs, transaction-status/src/lib.rs
=> v1.0: Backport "Rework TransactionStatus index in blockstore"

core/benches/cluster_info.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/broadcast_fake_shreds_run.rs, core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/cluster_info.rs
=> Remove write lock

docs/src/SUMMARY.md, docs/src/cli/choose-a-cluster.md, docs/src/cli/install-solana-cli-tools.md
No information about connecting to mainnet beta in our CLI docs
Add it and clean up Devnet/Testnet information
=> Update choose cluster docs

core/src/rpc.rs
=> v1.0: Reinstate commitment param to support old clients

docs/src/wallet/trust-wallet.md
Add instructions for creating and managing multiple wallet addresses using Trust Wallet.
=> Add instructions for multiple trust wallet addresses

docs/src/SUMMARY.md, docs/src/proposals/rust-clients.md
Our Rust clients got messy and the parts of the test suite that use them got very slow.
Add a proposal for how to clean it up.
cc https://github.com/solana-labs/solana/issues/9225
=> Add Rust client proposal

sdk/bpf/scripts/install.sh
Bernal keeps timing out in `sdk/bpf/scripts/install.sh`, hopefully this'll help
=> sdk/bpf/scripts/install.sh: Cache downloads to speed up CI

stake-monitor/README.md, stake-monitor/src/lib.rs
=> stake-monitor: Add 1 SOL grace, to allow for a complaint system account to fund a reasonable number of transactions.

ledger-tool/src/main.rs
error message for missing ledger_path argument is poor, purge vs. prune difference is very ambiguous from the help descriptions.
use .required(true) to get clap to help us and improve help text.
*edit, .required(true) doesn't work for .global arguments so just improved the error message.
Fixes #
=> Improve ledger-tool help

ledger-tool/src/main.rs
I've modified a bit this while investigating #9357.
- Show accounts sorted by their pubkey.
- Add a flag to include sysvars
- Show data length.
=> Improve ledger-tool/accounts for easier debuging

sys-tuner/src/main.rs
* https://github.com/solana-labs/solana/issues/9383
* https://github.com/solana-labs/solana/issues/9373
=> Moar vm.max_map_count

docs/src/running-validator/validator-monitor.md, docs/src/running-validator/validator-stake.md, docs/src/tour-de-sol/participation/steps-to-create-a-validator/delegating-stake.md, docs/src/tour-de-sol/participation/steps-to-create-a-validator/install-the-solana-software.md
Apply some discord doc feedback
=> doc: Use consistent vote account filename

cli/src/lib.rs, cli/src/nonce.rs, cli/src/test_utils.rs, cli/tests/nonce.rs, cli/tests/pay.rs, cli/tests/stake.rs, cli/tests/transfer.rs, cli/tests/vote.rs, core/tests/rpc.rs
Lots of duplicated logic.
Reduce with functions.
Fixes #
=> Reduce rpc test code

core/src/cluster_info.rs
see title
Less  log messages.
Fixes #
=> ReceiveUpdates spams the log, adjust the threshold higher

core/src/consensus.rs, core/src/replay_stage.rs
Vote simulation is complicated doesn't easily support creating arbitrary fork structures
Factored out vote simulation changes from: https://github.com/solana-labs/solana/pull/9218
Fixes #
=> Simplify vote simulation

ledger-tool/src/main.rs
=> ledger-tool: accounts subcommand now prints account balances in SOL

scripts/coverage.sh
hard to debug failures in coverage build
unfold the errors so they're more visible
=> Unfold coverage test failures

cli-config/src/config.rs
cc: https://github.com/solana-labs/solana-web3.js/pull/821
=> cli: Assume json_rpc_url can be upgrade to a websocket if no port is supplied

core/src/cluster_info.rs, sys-tuner/src/lib.rs, validator/src/main.rs
#9488 highlighted some poor error messages/handling.  Improve the situation.
=> validator: Improve --dynamic-port-range and sys-tuner error messages

net-utils/src/lib.rs
multi_bind_in_range is racy
Retry first port bind if second bind fails.
Fixes #
=> Fix race in multi_bind_in_range

runtime/src/accounts_db.rs
Too much log spam from accounts-db
Reduce metrics to each snapshot interval.
Fixes #
=> Reduce accounts_db prints

core/src/ledger_cleanup_service.rs, core/tests/ledger_cleanup.rs
test_compaction is slow
Move to integration side.
Fixes #
=> Move slow compaction test to integration

core/benches/cluster_info.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/broadcast_fake_shreds_run.rs, core/src/broadcast_stage/broadcast_metrics.rs, core/src/broadcast_stage/fail_entry_verification_broadcast_run.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/crds_gossip_pull.rs, metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
broadcast stats not working correctly
bp fix
Fixes #
=> Fix broadcast metrics (v1.1 backport)

core/src/repair_service.rs
1) Updating EpochSlots unnecessarily iterates the database on every update, when the `completed_slots_receiver` should be sending all the updates
2) Checking `let mine = cluster_slots.collect(id);` to see if we've already updated a slot sometimes fails as there is a delay between when a slot is inserted into gossip and when `ClusterSlots` is updated, causing some slots to be  occasionally inserted multiple times
1) Iterate Blockstore once at startup for completed slots
2) Check  `completed_slots_receiver` for subsequent updates
Fixes #
=> Simplify EpochSlots update

core/src/rpc_pubsub.rs
rpc tests are flaky
See if serializing them helps.
Fixes #
=> Make rpc tests serial

cli/src/cli.rs
`solana confirm -v ..` was failing to display details if the transaction failed, but there's no reason for that.
eg:
```
$ solana confirm 2Pppog58P9tRip9j3vLaEBnJWHQQngbcrH76WRXNBJT9h6epRnsKhmxNyBgVq7m6ewkH9sAyZ4dh9sL9c9c7NaZN -v`
RPC URL: http://devnet.solana.com
Default Signer Path: /Users/mvines/vines1vzrYbzLMRdu58ou5XTby4qAqVRLmqo36NKPTg.json
Transaction executed in slot 4081172:
Recent Blockhash: GrEXGd4oRtE4M5zMp1dxsMsesE2U7qsdUKVRuhmKzURV
Signature 0: 2Pppog58P9tRip9j3vLaEBnJWHQQngbcrH76WRXNBJT9h6epRnsKhmxNyBgVq7m6ewkH9sAyZ4dh9sL9c9c7NaZN
MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 2 }
Account 0: DDbpcBLRiJxYYHgg7vtkdkdjzRAnvqUdbs92qu1gLJKp
Account 1: 72VNGbhqqRtxW2JqDK3eC8SKiTskhi6oGRBEkk2BYTDj
Account 2: …
```
=> cli: confirm --verbose now displays failed transactions

Cargo.lock, Cargo.toml, ramp-tps/Cargo.toml, ramp-tps/src/main.rs, ramp-tps/src/notifier.rs, ramp-tps/src/results.rs, ramp-tps/src/stake.rs, ramp-tps/src/tps.rs, ramp-tps/src/utils.rs, ramp-tps/src/voters.rs
Rampy was bit rotting over in https://github.com/solana-labs/tour-de-sol, welcome it into the fold
=> Add ramp-tps

core/src/validator.rs, local-cluster/tests/local_cluster.rs
Back out https://github.com/solana-labs/solana/pull/9571 and fix the real bug introduced by #9560
=> validator: Consider the activated stake of this node to be online again

core/src/cluster_info.rs
Gossip can send a huge amount of traffic
Have a budget for outbound requests and try to do QoS on responses.
Fixes #
=> Gossip pull response budget

ledger/src/shred.rs
Shred header can be incorrect and cause overflow in validators.
Check for parent slot on deserialize.
Maybe the cause of #9586
Fixes #
=> Error for invalid shred header on deserialize

core/src/epoch_slots.rs
Get slot on bitvec could panic
guard the call
Fixes #9591
tag: @mvines
=> Get slot on bitvec needs a guard

cli/src/cli.rs
Sometimes you see a transaction fly by in a validator log and want to know what it is.
example log: 
```
[2020-04-19T16:28:47.355031252Z TRACE jsonrpc_core::io] Request: {"id":1,"jsonrpc":"2.0","method":"sendTransaction","params":["CQLiJ6ERQJHwqpL7S1gMC3LE8ombGtxcvHtoaXKpWGBsTJtrCDksQQBPFpeLdgGcv77x43tZbSfSjCH9pYGLkqWNs9WMXAqNgh91bUuw2Chv9uHEEcjDRXXQCSad1qaGa3BcU8ZD2gE8YyFdr6X8TGGi7wasmZmhPRvBD5vSwr7KiyiWkxKiskst9J4LyesTWg4u6EFzrNGoTSAjFV1PpV166vk5WqkMTeA9GNj3QjpJtpkHrP5H8fyCH7Q31uYgrWTu95kwMcjrrVn9wPVwu3RzqkvNMsBRkPXDzeT5K3mtZKiWFN6pdTBQWMaVGjwLouXE8vEAj18YPvtguwvLBUnjpjS17PxQbDec64stidAbaqn9ficuuXRqatGXaqKAoj5n3U5BuWEUrgM5VCGTNraUvsVFFNVfx6HNCZ8rSk3Jt7aDsy1g36GaciSgZUa65cNn528PipR42B"]}.
```
Now you can hand it to `solana decode-transaction` like so:
```
$ solana decode-transaction …
```
=> cli: Add decode-transaction

programs/bpf/Cargo.lock, programs/librapay/Cargo.lock
=> Update Cargo.lock files

cli/src/cli.rs
A generic error message that provides no useful information
Return more details
Fixes #
=> Nit: More informative error message

programs/librapay/src/lib.rs, programs/librapay/src/librapay_transaction.rs
Unused public functions
Cleanup
Fixes #
=> Cleanup move

cli/src/lib.rs
CLI help message too 1337
Attempt to get closer to English
=> Cleanup CLI public key description

docs/src/remote-wallet/ledger.md
Latest Ledger app not available on Ledger Live yet.
Add back command-line installation instructions to get a "beta" version.
=> Add docs for installing the beta Ledger app

Cargo.lock, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/helpers.rs
Solana-logger conflicts between tests
Run the tests that depend on it serially
Fixes #
=> Serialize test

core/src/gossip_service.rs, dos/src/main.rs, gossip/src/main.rs, system-test/stability-testcases/gossip-dos-test.sh, system-test/stability-testcases/gossip-dos-test.yml
This should get `system-test/stability-testcases/gossip-dos-test.sh` passing again
=> solana-dos can now DoS gossip nodes

metrics/src/metrics.rs
=> Exit cleanly on panic! so the process don't limp along in a half-dead state

core/src/cluster_info_vote_listener.rs
Vote listener can pass votes that didn't pass sig check
Chunk transactions into len=1 packets vec instead. Also, add some tests.
Fixes #9684
=> Fix vote listener passing bad transactions

core/src/serve_repair.rs
Copied from ClusterInfo:handle_packets, but not applicable here.
=> Fix comment in serve_repair

core/src/crds_gossip_pull.rs, core/src/ledger_cleanup_service.rs, core/src/poh_recorder.rs, core/src/repair_service.rs, core/src/snapshot_packager_service.rs, core/src/tvu.rs, core/src/validator.rs, core/tests/bank_forks.rs, ledger-tool/src/main.rs, ledger/src/blockstore.rs, ledger/src/blockstore_meta.rs, ledger/src/hardened_unpack.rs, local-cluster/tests/local_cluster.rs
Shred fs slower than rocskdb atm and rocksdb deficiencies have been somewhat mitigated by tuning.
Revert shred fs.
Fixes #
=> Revert shred fs

runtime/src/accounts.rs, runtime/src/bank/mod.rs
Program ids not filtered to collect_accounts_to_store
Filter the same as load_tx_accounts
Fixes #
=> Filter program ids v1.0

runtime/src/accounts.rs, runtime/src/bank.rs
Accounts to store not filtered by same program ids as in load_tx_accounts
Use same filter.
Fixes #9710
=> Filter program ids to store

docs/src/apps/jsonrpc-api.md
=> Fix broken doc link to anatomy of transaction

docs/src/implemented-proposals/ed_overview/ed_storage_rent_economics.md, docs/src/implemented-proposals/ed_overview/ed_validation_client_economics/ed_vce_state_validation_protocol_based_rewards.md, docs/src/proposals/block-confirmation.md
`mdbook-linkcheck` complaining about bad links in docs.
I'm not real sure how these are passing in CI.  They blew up on me running the CI scripts locally for another PR.
Correct them
=> Docs: Fix linkcheck errors

runtime/src/bank.rs
Compile broken
Rename bank method to new one.
Fixes #
=> fix test compilation from add_static_program change

banking-bench/src/main.rs, core/src/commitment.rs, core/src/consensus.rs, core/src/replay_stage.rs, core/src/rpc.rs, core/src/rpc_pubsub.rs, core/src/rpc_pubsub_service.rs, core/src/rpc_service.rs, core/src/rpc_subscriptions.rs, core/src/storage_stage.rs, core/src/tvu.rs, core/src/validator.rs, core/tests/bank_forks.rs, core/tests/client.rs, core/tests/storage_stage.rs, ledger/src/bank_forks.rs
Backport of commitment max redefinition work to v1.1
=> v1.1: backport commitment max changes

programs/exchange/src/exchange_processor.rs
=> Fix exchange_program typo

sdk/bpf/scripts/install.sh
BPF tool cache is not versioned so upgrading to a new version is broken
version the cache
Fixes #
=> Fix BPF tool caching

cli/src/cluster_query.rs
It's nice to know how long your wait time might be, eg:
```
$ solana catchup bw2P3Re8Egw4keSP6R5EfjQfJHtzLRyYgYS1VdDUrMH 
⠒ 1824 slots behind (us:8116864 them:8118688), gaining at 3.2 slots/second. Time remaining: 9m 30s
```
=> solana catchup now estimates the time remaining

Cargo.lock, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls.rs, sdk/bpf/c/inc/solana_sdk.h, sdk/bpf/rust/test/src/lib.rs
BPF calls to outside the VM are called helpers, but helpers isn't a good description of them
Call them syscalls
Fixes #
=> Rename BPF helper to syscall

runtime/src/accounts.rs, runtime/src/bank/mod.rs, runtime/src/rent_collector.rs, sdk/macro/src/lib.rs, sdk/src/incinerator.rs, sdk/src/lib.rs
cc: #9815
Same as https://github.com/solana-labs/solana/pull/9836 but for v1.0
=> v1.0: incinerator backport

runtime/src/accounts.rs, runtime/src/bank.rs, runtime/src/rent_collector.rs, sdk/macro/src/lib.rs, sdk/src/incinerator.rs, sdk/src/lib.rs
cc: https://github.com/solana-labs/solana/pull/9815
Incinerator will be rolled out according to this schedule, which gives validators ~2 weeks to upgrade from now:
```rust
if operating_mode == OperatingMode::Preview && bank.epoch() == 50 {
bank.incinerator_enabled = true; // testnet
}
if operating_mode == OperatingMode::Stable && bank.epoch() == 30 {
bank.incinerator_enabled = true; // mainnet-beta
}
```
=> v1.1: incinerator backport

scripts/cargo-for-all-lock-files.sh
Move lock files not included
include them
Fixes #
=> Reenable move lock files

runtime/src/accounts.rs, runtime/src/bank/mod.rs, runtime/tests/stake.rs, sdk/src/message.rs, sdk/src/transaction.rs
Backport of bad accounts indexing.
Also, check for program ids in payer position: account_keys[0]
Insert default account in program positions.
Fixes #
=> Fix accounts indexing (v1.0)

Cargo.lock, cli/src/display.rs, watchtower/Cargo.toml, watchtower/src/main.rs, watchtower/src/notifier.rs
https://github.com/solana-labs/solana/pull/9845 for v1.0
=> Watchtower can now emit a notification on all non-vote transactions

Cargo.lock, cli/src/display.rs, watchtower/Cargo.toml, watchtower/src/main.rs, watchtower/src/notifier.rs
```
export TRANSACTION_NOTIFIER_SLACK_WEBHOOK=123
solana-watchtower --notify-on-transactions
```
buckle up!
=> Watchtower can now emit a notifiation on all non-vote transactions

Cargo.lock, runtime/src/accounts.rs, runtime/src/bank.rs, sdk/src/transaction.rs
Crashes from bad transactions.
Fixes and fuzzer.
Fixes #
=> Fuzzer test and fixes (v1.1 bp #9853)

cli/src/cli.rs, client/src/rpc_client.rs
CLI's deploy program sends all the program data writes together and does not wait for any confirmation that they have been confirmed before attempting to finalize the load.  This results in an attempt to finalize without all the writes present which fails.
- Modify the batch transaction sender algorithm to wait for at least one confirmation
- More informative messaging
Fixes #
=> Wait for at least one confirmation when uploading program data

genesis-programs/src/lib.rs
Time to enable inflation on TdS
Fixes #9875
=> Enable inflation on testnet effective epoch 44

core/src/cluster_info.rs, core/src/crds_gossip.rs, core/src/crds_gossip_pull.rs, core/src/crds_gossip_push.rs
=> Gossip no longer pushes/pulls from nodes with a different shred version

core/src/replay_stage.rs
=> Fix reset slot not in BankForks

Cargo.lock, fetch-perf-libs.sh, perf/Cargo.toml, perf/src/perf_libs.rs, perf/src/sigverify.rs
GPU Sigverify turned off
Re-enable, add sigverify fuzz and scalar test.
Fixes #
=> Re-enable gpu sigverify

chacha-sys/cpu-crypt/chacha.h, chacha-sys/cpu-crypt/chacha20_core.c, core/src/cluster_info_vote_listener.rs, core/src/storage_stage.rs, core/src/tpu.rs, core/src/tvu.rs, core/src/validator.rs, core/tests/storage_stage.rs, validator/src/main.rs
Security review indicated argument to disable sigverify is dangerous and also identified some dead code.
Remove sigverify disable argument and move unused code to test modules.
Fixes #9926 #9927
=> Security changes

Cargo.lock, programs/bpf/Cargo.lock, programs/bpf/Cargo.toml, programs/bpf/tests/programs.rs, programs/bpf_loader/Cargo.toml, programs/bpf_loader/src/allocator_bump.rs, programs/bpf_loader/src/bpf_verifier.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls.rs, sdk/bpf/c/inc/solana_sdk.h, sdk/bpf/rust/test/src/lib.rs
Backport of the following PRs:
#9931 
#9819
=> Backport hardened bpf runtime to v1.1

archiver-lib/src/archiver.rs, client/src/client_error.rs, client/src/generic_rpc_client_request.rs, client/src/mock_rpc_client_request.rs, client/src/rpc_client.rs, client/src/rpc_client_request.rs, client/src/rpc_request.rs
=> Remove RpcClient code duplication

ledger/src/blockstore.rs
ErasureMeta warnings are hard to debug on Tds
Add more logging
Fixes #
=> More logging around ErasureMeta warnings

core/src/retransmit_stage.rs, core/src/shred_fetch_stage.rs
No retransmit metrics, and metrics for shred fetch are spammy and not as useful as they could be.
Add timer for retransmit metrics and enable by default and add some more fields for the all the possible cases for shred fetch.
Fixes #
=> Retransmit and shred fetch metrics

programs/bpf/benches/bpf_loader.rs, programs/bpf/c/src/invoke/invoke.c, programs/bpf/c/src/invoked/instruction.h, programs/bpf/c/src/invoked/invoked.c, programs/bpf/rust/invoke/src/lib.rs, programs/bpf/rust/invoked/src/instruction.rs, programs/bpf/rust/invoked/src/lib.rs, programs/bpf/tests/programs.rs, programs/bpf_loader/src/lib.rs, programs/bpf_loader/src/syscalls.rs, runtime/src/message_processor.rs, sdk/src/entrypoint_native.rs
Programs are able to sign other program's accounts
They can only sign accounts their own
Fixes #
=> Programs can only sign their accounts

core/src/retransmit_stage.rs, ledger/src/blockstore.rs
No information about what slot is being retransmitted.
Add a print for a slot histogram which prints when the stats are updated.
Fixes #
=> Add retransmit packets_by_slot metrics

docs/src/cli/install-solana-cli-tools.md
Missed a documentation backport.  Fixing here.  Nobody seems to be using Windows but the paragraph about updating the PATH variable on MacOS should be helpful.
=> Backport CLI install instruction tweak

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/cluster_info.rs, core/src/crds_value.rs, core/src/rpc.rs, core/tests/client.rs, version/.gitignore, version/Cargo.toml, version/src/lib.rs
Backport of https://github.com/solana-labs/solana/pull/9981
=> v1.1: Advertise node version in gossip

validator/src/main.rs
`solana-validator  --wait-for-supermajority ...` fails with `Failed to get RPC node slot: rpc request error: RPC Error response: {"code":-32000,"message":"Cluster largest_confirmed_root 0 does not exist on node. Node root: 12961040"}` because there's no cluster confirmed root during a cluster restart.   
Update the sanity checks in `solana-validator` to explicitly use CommitmentConfig::root() instead.
=> validator: Use CommitmentConfig::root() when checking accounts, CommitmentConfig::max() may not be available yet

core/src/ledger_cleanup_service.rs
No metrics for rocksdb disk usage or shred count.
Enable them.
Fixes #
=> Enable rocksdb disk metrics

core/tests/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/snapshot_utils.rs, runtime/src/accounts.rs, runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/bank.rs, sdk/src/clock.rs, sdk/src/hash.rs
Reverts solana-labs/solana#10022
=> Revert "[NO-MERGE; needs gating logic] Introduce eager rent collection (bp #9527)"

ledger/src/blockstore.rs
Blockstore insert functions too big, hard to understand code flow.
Refactor.
Fixes #
=> Refactor blockstore recovery code

cli/src/cli.rs
We're using Base58, not Base85
=> Fix decode-transaction about string

core/tests/bank_forks.rs, ledger/src/bank_forks_utils.rs, ledger/src/snapshot_utils.rs, runtime/src/accounts.rs, runtime/src/accounts_db.rs, runtime/src/accounts_index.rs, runtime/src/bank.rs, sdk/src/clock.rs, sdk/src/hash.rs
we need bankhash-affecting imcompat change (eager-rent-collection) to all the clusters; otherwise, we can't do seamless upgrade...
manual backport of #9527
FYI: @sakridge
=> v1.1: Eager rent collection

core/src/rpc_service.rs
backport https://github.com/solana-labs/solana/pull/9551
=> v1.0 Increase the number of JSON RPC service threads

metrics/scripts/grafana-provisioning/dashboards/cluster-monitor.json
10s too short, 1m too long, 30s just right.
Add 30s option.
Fixes #
=> Add 30s refresh option to dashboard

archiver-lib/src/archiver.rs, core/benches/cluster_info.rs, core/benches/shredder.rs, core/src/broadcast_stage.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/lib.rs, core/src/repair_response.rs, core/src/repair_service.rs, core/src/replay_stage.rs, core/src/serve_repair.rs, core/src/window_service.rs, ledger/src/blockstore.rs, ledger/src/shred.rs, ledger/src/sigverify_shreds.rs, ledger/tests/shred.rs
Integration path suggested here https://github.com/solana-labs/solana/pull/10043#discussion_r425255524
Fixes #
=> v1.1: Add nonce to shreds repairs, add shred data size to header

archiver-lib/src/archiver.rs, core/benches/cluster_info.rs, core/benches/shredder.rs, core/src/broadcast_stage/standard_broadcast_run.rs, core/src/lib.rs, core/src/repair_response.rs, core/src/repair_service.rs, core/src/replay_stage.rs, core/src/serve_repair.rs, core/src/window_service.rs, ledger/src/blockstore.rs, ledger/src/shred.rs, ledger/src/sigverify_shreds.rs, ledger/tests/shred.rs
Integration path suggested here https://github.com/solana-labs/solana/pull/10043#discussion_r425255524
Fixes #
=> v1.0: Add nonce to shreds repairs, add shred data size to header

core/src/shred_fetch_stage.rs, ledger/src/shred.rs, ledger/tests/shred.rs
Erasure FEC coding blocks are overlapping
Fixes #
=> Fix erasure

bench-exchange/src/bench.rs, cli/src/cluster_query.rs, core/src/non_circulating_supply.rs, ledger-tool/src/main.rs, remote-wallet/src/remote_wallet.rs, sdk/src/hard_forks.rs, watchtower/src/main.rs
Several instances where `fold()` obfuscates the code.
Prefer `sum()` when summing or a for loop when `mut` is involved.
=> Remove folds

docs/src/apps/jsonrpc-api.md
=> Fixup subscription docs

cli/src/cluster_query.rs
During a short-term fork, `get_new_blockhash()` can time out and cause `solana ping` to prematurely exit.   Rework the ping transactions so the same blockhash can be used for multiple transactions
=> cli: ping now reuses the same blockhash for a minute

docs/src/SUMMARY.md, docs/src/proposals/optimistic-confirmation-and-slashing.md
Optimistic confirmation lacks high level docs.
Add docs for optimistic confirmation roadmap documentation that covers the slashing and expected security.
Fixes #
=> document optimistic confirmation and slashing roadmap

core/src/cluster_info_vote_listener.rs, core/src/cluster_slots.rs, core/src/pubkey_references.rs
Redundant logic could be extracted out into common module
Refactor
Fixes #
=> Factor out LockedPubkeyReferences

docs/src/proposals/optimistic-confirmation-and-slashing.md
Grammar and rendering.
Fixes
Fixes #
=> Fix grammar and rendering in optimistic slashing doc

ci/run-sanity.sh
Test passes locally.
Context: https://github.com/solana-labs/solana/pull/10209#discussion_r429616595
=> v1.1: Test ledger-tool commands in run-sanity.sh

runtime/src/accounts_db.rs
Fixes https://github.com/solana-labs/solana/issues/10224
TODO:
=> v1.1: Adjust include_owner_in_hash to match mainet-beta v1.0 activation

core/src/cluster_info.rs, core/src/crds_gossip.rs, core/src/crds_gossip_pull.rs, core/tests/crds_gossip.rs
Lock contention on gossip locks are causing lots of latency.
Add metrics about which users are taking lock time.
Fixes #
=> Cluster info metrics

docs/src/apps/jsonrpc-api.md
Storage rpc endpoints were removed, but still appear in docs
Remove those docs
=> Remove storage rpc docs

sdk/src/pubkey.rs
`create_program_address` naming isn't ideal and won't match the web3 sdk
Cleanup and align the Rust SDK with the Solana-web3.js SDK
Related to: https://github.com/solana-labs/solana-web3.js/pull/928
Fixes #
=> Program address nits
